### DISCUSSION TITLE
Disable NodePort in cluster

### DISCUSSION THREAD

**Discussion by rivolity** [cilium/cilium#35970] [General]
I have created a cluster with the following config

```
nodePort:
  enabled: false
 
l2announcements:
  enabled: true

bpf:
  masquerade: true

gatewayAPI:
  enabled: true
  hostNetwork:
network.
    enabled: true

hostPort:
  enabled: true

kubeProxyReplacement: true

```

By running the following command, i still see the the NodePort is Enabled, why ?

```
kubectl -n kube-system exec ds/cilium -c cilium-agent -- cilium status --verbose | grep -i NodePort
```

```
  - NodePort:       Enabled (Range: 30000-32767) 
      │   │   └── job-ServiceReconciler                           [OK] 1 NodePort frontend addresses (10m, x1)
```
