### DISCUSSION TITLE
CiliumNetworkPolicy allow traffic fromCIDRset

### DISCUSSION THREAD

**Discussion by jDmacD** [cilium/cilium#36469] [Q&A]
```shell
cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    OK
 \__/¯¯\__/    Hubble Relay:       OK
    \__/       ClusterMesh:        disabled

DaemonSet              cilium             Desired: 3, Ready: 3/3, Available: 3/3
DaemonSet              cilium-envoy       Desired: 3, Ready: 3/3, Available: 3/3
Deployment             cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Deployment             hubble-relay       Desired: 1, Ready: 1/1, Available: 1/1
Deployment             hubble-ui          Desired: 1, Ready: 1/1, Available: 1/1
Containers:            cilium             Running: 3
                       cilium-envoy       Running: 3
                       cilium-operator    Running: 1
                       hubble-relay       Running: 1
                       hubble-ui          Running: 1
Cluster Pods:          30/30 managed by Cilium
Helm chart version:    
Image versions         cilium             rancher/mirrored-cilium-cilium:v1.16.0: 3
                       cilium-envoy       rancher/mirrored-cilium-cilium-envoy:v1.29.7-39a2a56bbd5b3a591f69dbca51d3e30ef97e0e51: 3
                       cilium-operator    rancher/mirrored-cilium-operator-generic:v1.16.0: 1
                       hubble-relay       rancher/mirrored-cilium-hubble-relay:v1.16.0: 1
                       hubble-ui          rancher/mirrored-cilium-hubble-ui-backend:v0.13.1: 1
                       hubble-ui          rancher/mirrored-cilium-hubble-ui:v0.13.1: 1
```
I have the following deployment
```yaml
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-port
  selector:
    app: whoami
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami
  name: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami

    spec:
      containers:
      - image: traefik/whoami
        name: whoami
        ports:
        - containerPort: 80
          name: http-port
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 1m
            memory: 20Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production-issuer
    external-dns.alpha.kubernetes.io/hostname: whoami.company.io
  name: whoami
spec:
  ingressClassName: cilium
  rules:
  - host: whoami.company.io
    http:
      paths:
      - backend:
          service:
            name: whoami
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - whoami.company.io
    secretName: letsencrypt-production-certificate
```
Our clusters are configured with a `CiliumLoadBalancerIPPool` and a shared ingress
```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  labels:
  name: l2-announced-pool
spec:
  blocks:
  - start: 99.1.99.185
    stop: 99.1.99.188
  disabled: false
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: kube-system
```
I have a `CiliumClusterwideNetworkPolicy` that restricts access to clients within our VPN
```yaml
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "allow-vpn"
spec:
  description: "Allow all the traffic originating from within vpn"
  endpointSelector:
    matchExpressions:
    - key: reserved:ingress
      operator: Exists
  ingress:
  - fromCIDRSet:
    - cidr: 99.1.99.0/24
```
This works as expected, but is a bit heavy handed. I would like application owners to be able to write their own policies using `CiliumNetworkPolicy`. My expectation would be that my requirements would be similar to the examples in [Tutorial: Cilium Network Policy in Practice (Part 2)](https://isovalent.com/blog/post/tutorial-cilium-network-policy/#user-story-2-ipcidr-ingress-traffic-filter-for-database-access)

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: database-policy
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      tier: database
  ingress:
    - fromEndpoints:
        - matchLabels:
            tier: backend
      toPorts:
        - ports:
            - port: "7379"
    - fromCIDRSet:
        - cidr: 102.213.50.174/32
      toPorts:
        - ports:
            - port: "443"
  egress:
    - {}
 ```

Despite several attempts I cannot create a `CiliumNetworkPolicy` to restrict access to a particular CIDR.  
Is it possible to accomplish what I want with a single policy per namespace?
