### DISCUSSION TITLE
Cilium in EKS cluster with hybrid nodes

### DISCUSSION THREAD

**Discussion by danielec7** [cilium/cilium#36755] [General]
I have been looking into the new feature of hybrid nodes in AWS eks clusters. 

Disclaimer: I'm relatively new to Cilium, so apologies if I miss any key concepts.

In their docs https://docs.aws.amazon.com/eks/latest/userguide/hybrid-nodes-cni.html#_install_cilium_on_hybrid_nodes
they seem to suggest to install cilium only in the hybrid nodes:

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: eks.amazonaws.com/compute-type
          operator: In
          values:
          - hybrid
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4MaskSize: 25
    clusterPoolIPv4PodCIDRList:
    - POD_CIDR
operator:
  unmanagedPodWatcher:
    restart: false
```

I was tinkering with the idea of having Cilium running in the whole cluster, and I'm not sure if that can work or not.
I tried installing Cilium globally using `ipam=eni` and then using `CiliumNodeConfig` in hybrid node to use `cluster-pool` ipam.
I got inconsistent results with the solution intermittently working or not, and I'm not clear what is happening.

But I noticed that cilium operator configuration is global, so it won't work with different ipam modes.

Do you know if what I want is achievable, or makes sense? I would like to use cilium with native routing mode and eni mode in aws and something else in the hybrid nodes.

Any guidance, insights, or examples would be greatly appreciated

Thank you.
