### DISCUSSION TITLE
Ingress SSL is not working

### DISCUSSION THREAD

**Discussion by kotyara85** [cilium/cilium#36778] [Q&A]
So I created a new ingress - 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example
  namespace: example
spec:
  ingressClassName: cilium
  rules:
  - host: service.example.com
    http:
      paths:
      - backend:
          service:
            name: example
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - service.example.com
```

Cilium config:
```
l7Proxy: true
nodePort:
    enabled: true
ingressController:
    defaultSecretNamespace: kube-system
    defaultSecretName: default-certificate
    enabled: true
    loadbalancerMode: shared
    service:
        type: NodePort
        insecureNodePort: 30080
        secureNodePort: 30443
endpointRoutes:
    enabled: true
```

Http call:
```
curl host:30080 -H "Host: service.example.com" -v
< HTTP/1.1 301 Moved Permanently
...
```

Https call:
```
curl https://host:30443 -H "Host: service.example.com" -v
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to host:30443
```

If I disable tls on the ingress port 30443 stops responding, so I'm assuming something is half way working.
I was under impression cilium can offload ssl and forward the traffic

Thanks
