### DISCUSSION TITLE
possibility to attach IP pool to node

### DISCUSSION THREAD

**Discussion by prog76** [cilium/cilium#36794] [Q&A]
We have two k8s nodes in two AZ. We need to configure a LB service that will work if one of them fails. 
Note that in different AZ we have different IP pools.

What we can do with MetalLB:
```
kind: IPAddressPool
metadata:
  name: primary
spec:
  addresses:
  - 172.18.255.193-172.18.255.206
---
kind: L2Advertisement
metadata:
  name: primary
spec:
  ipAddressPools:
  - primary
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: NodeA
---
kind: IPAddressPool
metadata:
  name: secondary
spec:
  addresses:
  - 172.19.255.193-172.19.255.206
---
kind: L2Advertisement
metadata:
  name: secondary
spec:
  ipAddressPools:
  - secondary
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: NodeB
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-api
  annotations:
    external-dns.alpha.kubernetes.io/hostname: myapp.example.com
spec:
  type: LoadBalancer
```  

Possible Cilium alternative:
```
kind: CiliumLoadBalancerIPPool
metadata:
  name: primary
spec:
  cidrs:
  - cidr: "172.18.255.192/28"
---
kind: CiliumL2AnnouncementPolicy
metadata:
  name: primary
spec:
  loadBalancerIPs: true
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: NodeA
---
kind: CiliumLoadBalancerIPPool
metadata:
  name: secondary
spec:
  cidrs:
  - cidr: "172.19.255.192/28"
---
kind: CiliumL2AnnouncementPolicy
metadata:
  name: secondary
spec:
  loadBalancerIPs: true
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: NodeB
```
Here, I can't find the possibility to attach specific pool to the Node.

Question:
Is it possible?
