### DISCUSSION TITLE
Issue with L7 Policy block everything - doesn't block only particular URL path

### DISCUSSION THREAD

**Discussion by iracic82** [cilium/cilium#36797] [Q&A]
Guys,

I've got an issue using this policy:

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-specific-path-and-egress
  namespace: api
spec:
  endpointSelector:
    matchLabels:
      app: rest-api
  ingress:
  - fromEndpoints:
    - matchLabels:
        app: test-webapp
        namespace: webapp
    toPorts:
    - ports:
      - port: "5000"
        protocol: TCP
      rules:
        http:
        - method: GET
          path: "/api/status"
  egress:
  - toEntities:
    - all
```

From some reason the traffic got blocked completely and in logs it doesn't show L7info.

Envoy-proxy is running OK
