### DISCUSSION TITLE
Gateway API and BGP control plane

### DISCUSSION THREAD

**Discussion by dhess** [cilium/cilium#36804] [Q&A] [answered]
Hi! We've been using Cilium ingress, Cilium's BGP control plane, the `io.cilium/lb-ipam-ips` service annotation, and the `io.cilium/bgp-control-plane` `loadBalancerClass` to route external clients to cluster-hosted services for quite awhile. Now we'd like to switch to the Gateway API.

As a test, we replaced several of our `Ingress` resources with equivalent `Gateway`s and `HTTPRoute`s. Though we weren't able to set the `Gateway` IPs or underlying load balancer IPs explicitly, Cilium always chooses the IPs from the same IP range that we're using for our ingress LB-IPAM range, and initially, at least, the IPs were announced to our routers via BGP. We verified that external clients could successfully connect to the `Gateway`-fronted services.

All was working well until it wasn't. I'm not certain when the problems started, but a few hours after we made these changes, we were suddenly unable to connect to the `Gateway` services from outside the cluster. When I looked for the root cause, I noticed that the `Gateway`/load balancer IPs were no longer present in our routers'  tables. It's possible this change occurred after the Cilium pods restarted due to some unrelated changes, but I can't be certain.

Is this meant to work? If so, how? Things I've tried, to no avail:

* Add a `io.cilium/lb-ipam-ips` annotation to the `Gateway`'s `spec.infrastructure.annotations`, but this just gets ignored, and in fact, Argo CD shows the `Gateway` as out of sync because Cilium seems to be stripping the annotations from the resource, and it shows up as a manifest diff in Argo CD.
* Add a `loadBalancerClass: io.cilium/bgp-control-plane` annotation to the `Gateway`'s `spec.infrastructure.annotations`, with the same result as above.
* Specify the `Gateway` `address` using an IP from the LB-IPAM range. This field is preserved, but ignored: Cilium chooses whatever IP it likes from the LB-IPAM range. In any case, it doesn't cause Cilium to announce the IP via BGP.

We're on Cilium v1.16.5. This is happening in 2 different clusters, both attached to the same routers.

**Comment by dhess** [comment]
Here's the Helm config for one of the clusters. The other is nearly identical, except for the IP ranges.

```yaml
cluster:
  name: cluster-a
  id: 1

clustermesh:
  useAPIServer: true
  apiserver:
    replicas: 3
    service:
      type: LoadBalancer
      loadBalancerClass: io.cilium/bgp-control-plane
      externalTrafficPolicy: Local
      annotations:
        io.cilium/lb-ipam-ips: 10.0.20.245
    tls:
      authMode: cluster
      auto:
        method: certmanager
        certValidityDuration: 90
        certManagerIssuerRef:
          group: cert-manager.io
          kind: ClusterIssuer
          name: cilium-issuer
    metrics:
      enabled: true
      kvstoremesh:
        enabled: true
      etcd:
        enabled: true
      serviceMonitor:
        enabled: true
        interval: 30s
        kvstoremesh:
          interval: 30s
        etcd:
          interval: 30s
  config:
    enabled: true
    clusters:
      - name: cluster-b
        port: 2379
        ips:
          - 10.0.24.245
      - name: cluster-c
        port: 2379
        ips:
          - 10.64.70.245

updateStrategy:
  rollingUpdate:
    maxUnavailable: 1

upgradeCompatibility: "1.14"
kubeProxyReplacement: true
k8sServiceHost: localhost
k8sServicePort: 7445
ipam:
  mode: kubernetes

rollOutCiliumPods: true

bgpControlPlane:
  enabled: true

hostFirewall:
  enabled: false

# Fix for Talos.
# https://github.com/cilium/cilium/issues/21603#issuecomment-1453753820
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

l7Proxy: true

# Deploy Envoy as a daemonset, rather than as part of the Cilium agent
# pods.
envoy:
  enabled: true
  # Required to permit Envoy to bind to privileged ports.
  #
  # Ref:
  # https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/#bind-to-privileged-port
  securityContext:
   capabilities:
     keepCapNetBindService: true
     envoy:
       # Defaults.
       - NET_ADMIN
       - SYS_ADMIN

       # Required by Gateway (for privileged ports).
       - NET_BIND_SERVICE
  rollOutPods: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

gatewayAPI:
  enabled: true
  enableAlpn: true
  externalTrafficPolicy: "Local"

ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  service:
    # Argo CD can't properly reconcile the ports on this service, so
    # we specify them. Here I've chosen whatever defaults the service
    # uses when they're not specified.
    insecureNodePort: 30332
    secureNodePort: 30235
    annotations:
      io.cilium/lb-ipam-ips: 10.0.20.253

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

operator:
  rollOutPods: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true

hubble:
  enabled: true
  redact:
    enabled: true
    http:
      headers:
        deny:
          - Authorization
          - Proxy-Authorization
      userInfo: true
    kafka:
      apiKey: true
  relay:
    enabled: true
    replicas: 3
    prometheus:
      serviceMonitor:
        enabled: true
  ui:
    enabled: true
  tls:
    auto:
      enabled: true
      method: certmanager
      certValidityDuration: 1095
      certManagerIssuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: cilium-issuer
  metrics:
    enableOpenMetrics: true
    enabled:
      - dns:labelsContext=source_namespace,destination_namespace
      - drop:labelsContext=source_namespace,destination_namespace
      - tcp:labelsContext=source_namespace,destination_namespace
      - port-distribution:labelsContext=source_namespace,destination_namespace
      - icmp:labelsContext=source_namespace,destination_namespace;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity
      - flow:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity;labelsContext=source_namespace,destination_namespace
      - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      - "policy:sourceContext=app|workload-name|pod|reserved-identity;destinationContext=app|workload-name|pod|dns|reserved-identity;labelsContext=source_namespace,destination_namespace"
    dashboards:
      enabled: true
    serviceMonitor:
      enabled: true

# Native, L2 direct routing.
routingMode: native
autoDirectNodeRoutes: true
# Seems required for clustermesh to work?
# ref:
# https://github.com/cilium/cilium/issues/31843
directRoutingSkipUnreachable: true
ipv4NativeRoutingCIDR: 10.0.0.0/8

loadBalancer:
  algorithm: maglev
  mode: dsr
  dsrDispatch: opt
  acceleration: native

maglev:
  hashSeed: [redacted]

bpf:
  masquerade: true

# Performance tweaks.
# https://docs.cilium.io/en/stable/operations/performance/tuning/
enableIPv4BIGTCP: true
enableIPv6BIGTCP: true
bandwidthManager:
  enabled: true
  bbr: true

dashboards:
  enabled: true
```

**Comment by dhess** [comment]
By switching *all* of the installed Gateway API CRDs to the v1.1 experimental channel, and not just `TCPRoute`, we're able to make the `infrastructure.annotations` work, and that seems to have made it possible to assign a specific IP to the gateway resource and its underlying load balancer. It would help if this were documented somewhere.

However, we're still not getting VIP BGP announcements. Adding a `loadBalancerClass` annotation didn't do the trick.

**Comment by dhess** [comment]
This issue persists in Cilium v1.17.1. It would be nice to get some feedback on whether this is expected to work, at least.

**Comment by dhess** [comment, marked as answer]
Answering my own question here:

With Cilium v1.17.1, at least, the issue appears to have been this setting:

```yaml
gatewayAPI:
  externalTrafficPolicy: "Local"
```

By removing that setting, our Gateways that include the following spec are being announced into BGP, and are reachable via an `HTTPRoute`:

```
spec:
  infrastructure:
    annotations:
      loadBalancerClass: io.cilium/bgp-control-plane
      io.cilium/lb-ipam-ips: x.x.x.x
  gatewayClassName: cilium
```

The Cilium Operator warns about the `io.cilium/lb-ipam-ips:` annotation being deprecated, and advises us to switch to `addresses`, but I haven't tried that yet.

In any case, hopefully this helps anyone who runs across the same issue. This stuff should be documented better: I feel like I had to figure it out on my own by piecing together bits of various issues in the tracker and reading CRDs.
