### DISCUSSION TITLE
[Hubble] Deleted pod metrics are still exported 30 days after

### DISCUSSION THREAD

**Discussion by Eclion** [cilium/cilium#37080] [Q&A]
Hello!

We are using Cilium & Hubble on Kubernetes in my team, and we noticed that at one point we couldn't scrap metrics from Cilium pods anymore.

We did a bit of investigation, and we found out that the metrics emitted by Cilium never expire, resulting in metrics such as `hubble_tcp_flags_total` about pods removed 30 days ago...

Increasing `promscrape.maxScrapeSize` in our scrapper does help in getting the metrics again, but it does not solve the issue, as the more pods we will have, the sooner we will reach the limit again.

Is there a way to expire the metrics aside from deleting the pod, "refreshing" the metrics this way ?
Or does our configuration make Cilium generate metrics that are more fine-grained than needed?

FYI, here is our hubble.metrics configuration:
```
hubble:
  # -- Enable Hubble (true by default).
  enabled: true
  metrics:
    tls:
      # Enable hubble metrics server TLS.
      enabled: false
    enableOpenMetrics: true
    enabled:
      - "dns:sourceContext=workload-name|pod-name|reserved-identity;destinationContext=workload-name|pod-name|reserved-identity;labelsContext=source_namespace,destination_namespace,traffic_direction"
      - drop
      - "tcp:sourceContext=workload-name|pod-name|reserved-identity;destinationContext=workload-name|pod-name|reserved-identity;labelsContext=source_namespace,destination_namespace,traffic_direction"
      - flow
      - "http:sourceContext=workload-name|pod-name|reserved-identity;destinationContext=workload-name|pod-name|reserved-identity;labelsContext=source_namespace,destination_namespace,traffic_direction"
      - "kafka:sourceContext=workload-name|pod-name|reserved-identity;destinationContext=workload-name|pod-name|reserved-identity;labelsContext=source_namespace,destination_namespace,traffic_direction"
```
