### DISCUSSION TITLE
Add Egress Connection Timeouts to Cilium Egress Gateway Policy

### DISCUSSION THREAD

**Discussion by rari459** [cilium/cilium#37454] [Ideas]
I would like to propose Modifying CiliumEgressPolicy (CEGP) to include an optional timeout field would allow us to ingest custom timeouts and give users additional control over egress connections. 

This is because currently Cilium relies heavily on default operating system connection timeout settings and offers control over connection timeouts at cluster or node level.

It is not optimal for all workloads to be bound to these node level timeouts, especially with respect to egress gateways where prolonged idle connections can contribute to port exhaustion on the NAT gateway.

I expect the modified CEGP to look like this:
```
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egress-sample
spec:
  [other fields] ...
  connection-timeouts:
      bpf-ct-timeout-regular-any: 60
      bpf-ct-timeout-regular-tcp: 21600
      bpf-ct-timeout-regular-tcp-fin: 10
      bpf-ct-timeout-regular-tcp-syn: 60
      bpf-ct-timeout-service-any: 60
      bpf-ct-timeout-service-tcp: 21600
      bpf-ct-timeout-service-tcp-grace: 60
  ...   
  ```
  
I would like to hear feedback from the community on how useful a feature like this could be. Thank you!

@bowei

**Comment by joestringer** [comment]
Could you rephrase this in the form of a user story, that is, paint a picture about a problem that a user has (ideally a user situation you're directly familiar with), how they think about the timeouts, how they might make different timeout decisions for different services, what's special about those services and what their ideal configuration parameters might look like?

**Reply by rari459** [reply]
Lets say we have a **Kubernetes cluster hosting apps with varying egress traffic patterns:**

**Real-time apps**: Require short timeouts for low-latency, continuous connections.
**Batch processing apps**: Need longer timeouts for stable, large file transfers.
**Infrequent API apps:** Have long idle periods, but need quick connections.

**Problem:**
Default or cluster-wide timeouts cause:
- Delays in real-time apps.
- Disruptions in batch processing.
- NAT port exhaustion from idle connections.

**User Need:**
Platform admins need granular control over egress timeouts to:
- Optimize resource use.
- Prevent port exhaustion.
- Ensure app reliability.

**Ideal Configuration:**
Service-level timeouts within CiliumEgressGatewayPolicy, allowing for:
- Service/Application-specific timeouts with CEGP label selectors
- Protocol-specific timeouts.
- Fine-grained TCP phase timeouts.

**Reply by joestringer** [reply]
Thanks, this is quite helpful. Would you say that the core problem with all of these use cases ultimately comes down to NAT port exhaustion?

**Reply by rari459** [reply]
Yes, this is the main issue that we are seeing, causing other egress traffic to be stifled from lack of available ports on the egress gateway node.

**Reply by joestringer** [reply]
I see. From that perspective, I can see how giving control over timers to users might give them some degree of ability to affect this. On the other I'm not sure I'm convinced that giving timers control to users is the right interface for users to help influence Cilium's NAT port management. If they have services that have specific properties like "frequent short lived connections" or "few long-lived connections" then it could help for the user to specify/classify these. If there are more critical services, it could help to have a user-defined "priority" in some form. Let's say Cilium is able to know these properties of the different connections, then Cilium could use these signals to optimize the NAT management. That would give me more confidence in optimizing the GC/resource management internally rather than just exporting very specific internal implementation details and hoping the user knows how to write the timers well.

**Reply by rari459** [reply]
Connection timeouts are exposed to users today in cilium-agent config, is the concern with moving them to CEGP a question of roles? (Cilium config is only exposed to admins who are more aware of low-level implementation whereas CEGP could be exposed to non-admin users who are less aware of these low-level details?)

My understanding was that users could classify their traffic according to their patterns/priorities and create a specific CEGP to attract that traffic and provide custom ct timeouts based on the application timeouts. It seems CT timeouts are the primary way to deal with idle connections and ct entry cleanup. 

If we expose this instead as priority/traffic-pattern categories, how exactly would Cilium be able to make GC/resource management decisions based on this data? Would it be dynamic or would it just be static timeout values attached to each category?

**Reply by joestringer** [reply]
Yes, I do see this as partly a concern around roles. I also see this as a question of how much we expect to teach users of CEGP the internals of how Cilium centrally manages these resources and how the user should think about / model the underlying behavior.

If the user interface is a bit less direct, then Cilium has a lot more room to solve the problem and even optimize over time, perhaps starting with static timeouts, maybe make them configurable centrally, or adapt them dynamically. That would partly come down to how much work that we as developers want to put in to simulating usage of the NAT table and balancing high connection use of the different categories.

What I don't love about handing timeouts to users is that the optimal solution to this problem for a target environment might involve Cilium ignoring some of these timeouts or perhaps early-evicting some lower-priority sessions, or maybe there's some other opportunistic algorithm we may come up with. If the user configures some timeouts, then they'll expect these timeouts to be adhered to even if their configuration is suboptimal. We also then have the problems of teaching those users about how the timers really work (complicated to explain) and each user needs to tweak those settings themselves (added complexity).

**Reply by rari459** [reply]
Thank you for the detailed explanation, it makes sense why exposing low-level config could lead to suboptimal setups for users. A more dynamic and abstracted approach would be much more involved than the design proposed in https://github.com/cilium/design-cfps/pull/63/commits.

Is there any example/precedent for such a optimized garbage collection feature in other areas of Cilium?

**Reply by joestringer** [reply]
I agree such a proposal would be more involved. My point is not to set the bar way higher than your current scope of work, but rather to think about the user interface to make it easier to use and less likely to block any future work if we decide that we want to optimize the logic further in future.

As for examples of garbage collection, I think the conntrack GC is probably the most nuanced so far, but that's more about how we measure the entry deletion rate and feed that back into the scheduling time for the next GC run. I don't think that the actual assessment heuristic for eviction is much fancier than just respecting existing timers.

**Reply by rari459** [reply]
Hi Joe, I wanted to continue the discussion on timeouts, both in support of exposing timeouts to users and in a possible hybrid abstraction approach that gives users preset timeouts and the ability to add their own custom ones if needed.

***Keeping Exposed Connection Timeouts in CEGP API:***
This seems to be a common feature in many public cloud offerings and it could be a good idea for Cilium to also follow this model:
GCP Cloud NAT lets users specify timeouts for a gateway at a similar level of granularity as was proposed above for cilium: [link](https://cloud.google.com/nat/docs/tune-nat-configuration#nat-timeouts)
Microsoft Azure NAT lets users configure TCP Timeouts for NAT gateway mappings from 4-120 mins: [link](https://learn.microsoft.com/en-us/azure/nat-gateway/nat-gateway-resource#tcp-idle-timeout)


***Hybrid Approach:***
The CiliumEgressGatewayPolicy can offer a hybrid timeout configuration approach. Users can have predefined timeout profiles (short, medium, long) for quick and common configurations, while keeping the flexibility to specify custom timeout values for granular control. This allows users to easily manage connection timeouts according to their specific application requirements and network characteristics. By providing sensible defaults through presets, we simplify common use cases and can prevent users from choosing suboptimal configurations. Simultaneously, allowing custom configurations ensures that advanced users can fine-tune timeouts.
```
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egress-sample
spec:
  [other fields] ...
  connection-timeouts:
      profile: medium # Optional: short, medium, long, or custom
      custom: # Optional: Only used when profile is "custom"
      bpfCtTimeoutRegularAny: 60 # Seconds 
      bpfCtTimeoutRegularTcp: 21600 # Seconds bpfCtTimeoutRegularTcpFin: 10 # Seconds 
      bpfCtTimeoutRegularTcpSyn: 60 # Seconds
  ...  

# Example of preset timeout values (these would be defined internally):
# medium: 
# bpfCtTimeoutRegularAny: 60 
# bpfCtTimeoutRegularTcp: 21600 
# bpfCtTimeoutRegularTcpFin: 10 
# bpfCtTimeoutRegularTcpSyn: 60
```

**Reply by joestringer** [reply]
That seems like a step in the right direction. I wonder, can we make the "custom" section an opaque blob? It would be written like the following, but the details would not be hardcoded in the API, something like:

```
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egress-sample
spec:
  [other fields] ...
  connection-timeouts:
      profile: custom
      custom: |
          bpfCtTimeoutRegularAny: 60s
          bpfCtTimeoutRegularTcp: 21600s
          bpfCtTimeoutRegularTcpFin: 10s
          bpfCtTimeoutRegularTcpSyn: 60s
```

The suggestion is to not define the timeout fields in the API; we just define that the "custom" field can have some text which the agent can interpret as a set of advanced settings. This way for a given version of Cilium it's possible to configure these parameters, but if we decide to rework the CT parameters in future then it's not directly part of the API and we'd have more freedom to break them. I'd expect we still release-note any changes, but there would be fewer guarantees about what the contents of this blob does.

I would like to emphasize seeing that users digging this deep into implementation details means that they are power users and they are willing to (a) take on all of the risk and repercussions of their configuration, and (b) track the evolution of these settings upstream and participate to provide feedback about what works well and what doesn't. If we end up breaking the settings for someone, they should be willing to reach out upstream to help guide us towards the right UX to solve the problems they have. On the other hand, if multiple users feel really strongly that these provide the right level of granularity for configuring these objects we might consider formalizing them more.
