### DISCUSSION TITLE
How to do gateways & ingresses w/o LoadBalancers

### DISCUSSION THREAD

**Discussion by jonsch318** [cilium/cilium#38201] [Q&A]
Okay I wanted to use cilium as my gateway and ingress and I have it setup like this

```yaml
---
[...]
gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true
  gatewayClass:
    create: "true"
  hostNetwork:
    enabled: true
    # sharedListenerPort: 443
ingressController:
  enabled: true
  default: true
  loadBalancerMode: shared
  hostNetwork:
    enabled: true
    # sharedListenerPort: 443
  service:
    externalTrafficPolicy: "null"
    type: ClusterIP
    #type: NodePort
loadBalancer:
  l7:
    backend: envoy
envoy:
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy:
        - NET_BIND_SERVICE
        - NET_ADMIN
        - BPF
````

So it uses the hostNetwork mode and not the LoadBalancer type since I run talos on multiple vps on multiple cloud providers. I don't want any cloud providers load balancer. Now I want to deploy multiple web servers on different domains with tls. My understanding is to use a separate gateway (one for each webserver / app i guess) and use cert-manager to issue certs to them. 

With the host Network mode i cannot create two gateways that both listen on `:80` or `:443` for example regardless if there are listening for different hostnames.

Is there a way to make this happen or should i again use traefik with a singular NodePort service as the "LoadBalancer".
