### DISCUSSION TITLE
Is this possible to filter which apps have access to specifis ingress domains?

### DISCUSSION THREAD

**Discussion by adippl** [cilium/cilium#38275] [Q&A] [answered]
Hi, 

I'm looking for a way to grant applications access to only some of the domains exposed via cilium ingress.
I'm working on a locked down cluster and everything is blocked by default.
To make blackbox exporter work I had to configure this rule.

```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: blackbox-ingress-access
spec:
  endpointSelector:
    matchExpressions:
    - key: reserved:ingress
      operator: Exists
  ingress:
    - fromEndpoints:
      - matchLabels:
          io.kubernetes.pod.namespace: monitoring-blackbox
          app.kubernetes.io/name: prometheus-blackbox-exporter
```
This rule gives blackbox access to all ingresses.
Egress rule doesn't seem to be required for blackbox-exporter to initiate connections to cilium ingress.
I would like blackbox exporter access to only some of the domains on cilium ingress.

For example I currently have admin services such as prometheus and hubble-ui on separate ingress-nginx because I can easily lockout other apps from accessing it. With cilium ingress everything seems to be lumped into one bag.

Is it possible to apply dns or fqdn filtering to this rule?
