### DISCUSSION TITLE
cluster-pool in eks not able to scale more pods

### DISCUSSION THREAD

**Discussion by zoezhangmattr** [cilium/cilium#38571] [Q&A] [answered]
try to run cilium in aws eks, with 1 t3.small instance type, no kube-proxy, no aws-vpc-cni,  with helm below values, chart version 1.17.2, i can see my deathstar demo pods have the expected ips. 11 pods running in the cluster just fine, everything works, when i try to deploy new pod, its pending, and error saying `0/1 nodes are available: 1 Too many pods. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod`. 

running kubectl exec -n kube-system ds/cilium -- cilium-dbg status 
    displayed IPAM:                   IPv4: 10/254 allocated from 10.10.0.0/24, i think the allocator is not using cilium podcidr, but eks node cidr, what did i configure wrong 

helm release custom value files.
```yaml
ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDRList: ["10.10.0.0/16"]
ipv4NativeRoutingCIDR: "10.10.0.0/16"
routingMode: native
autoDirectNodeRoutes: true
bpf:
  masquerade: true
operator:
  replicas: 1
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
kubeProxyReplacement: true
k8sServiceHost: <host>
k8sServicePort: "443"
```
