### DISCUSSION TITLE
Best practice to upgrade cilium in large clusters

### DISCUSSION THREAD

**Discussion by pasteley** [cilium/cilium#39267] [Q&A]
For clusters with over 2k+ nodes, updating a single CRD can cause the kube-apiserver to be flooded with watch requests from cilium-agents. Is there any way to make this process more gradual, beside disabling CRD installation in the operator?

**Comment by joestringer** [comment]
Which CRD is this referring to? Could you describe in a bit more detail how the CRD is updated?

@cilium/sig-scalability might be interested in this topic too. 

If there's something we could document better, or a proposal for a code change that would enable Cilium to handle this scenario more gracefully, then I think the developers would be interested to discuss those options.

**Comment by bowei** [comment]
I put this in Slack -- but I think this is due to how the K8s API server works when updating the CRD -- it will close all of the current watches and force re-establishment of the all the informers. We might need to working with upstream K8s on how to deal with this.

**Comment by bowei** [comment]
Looks like there are some improvements in how the API server handles large response sizes: https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/5116-streaming-response-encoding/README.md -- this is in 1.34. Does not remove the situation but could make the load on the API server not as high.

**Comment by jpbetz** [comment]
cc @serathius for any thoughts on if/how APF might be tuned to help here

**Comment by jaredledvina** [comment]
This behavior has been an issue for as long as I've run Cilium. So far, the best mitigation is to configure APF. You'd want to play around with the exact configuration but, the following has worked alright for clusters up to 3k nodes:
```yaml
---
apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: FlowSchema
metadata:
  name: cilium-agent
spec:
  matchingPrecedence: NNN # Pick whatever makes sense in your cluster
  priorityLevelConfiguration:
    name: cilium-agent
  rules:
  - nonResourceRules:
    - nonResourceURLs:
      - '*'
      verbs:
      - '*'
    resourceRules:
    - apiGroups:
      - '*'
      clusterScope: true
      namespaces:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
    subjects:
    - kind: ServiceAccount
      serviceAccount:
        name: cilium-agent
        namespace: XXXXXXX
---
apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: PriorityLevelConfiguration
metadata:
  name: cilium-agent
spec:
  type: Limited
  limited:
    nominalConcurrencyShares: 30
    lendablePercent: 50
    limitResponse:
      type: Queue
      queuing:
        handSize: 15
        queueLengthLimit: 500
        queues: 15
```
I've had good results adding `borrowingLimitPercent: 0` temporarily before upgrading the `cilium-operator` (which is the step that'll update all of the CRDs) to ensure the cilium-agent doesn't take shares from other queues too. 

It's worth reading all of https://kubernetes.io/docs/concepts/cluster-administration/flow-control/ though as APF can be pretty confusing and exactly what setting you need depends on how your cluster is setup and used. It also really depends on how you've sized your kube-apiserver's and etcd clusters to handle the request load. It's very unfortunate that this is the behavior upstream w/ the k8s apiserver when CRD's are updated. If they could jitter or slow down the cancelation of all of the watches, that'd be nice. It ends up causing a classic stampeding hoard issue.
