### DISCUSSION TITLE
Restricting traffic to specific ingresses when using the ingress controller

### DISCUSSION THREAD

**Discussion by jsw1993** [cilium/cilium#39301] [Q&A]
Hi All

I'm having a play with Cilium. I'm trying to block by default but allow specific traffic. I'm using the below policies. In my ArgoCD namespace I only want to allow traffic from a specific internal CIDR however all traffic seems to be allowed.

I'm going to guess it's because the traffic has ` reserved:ingress` it's always going to be allowed despite the CIDR restriction.

Is there a way round this that allows me to filter the CIDRs that can get to the ingress? Within the networkpolicy I also need to allow all traffic within the namespace

Many thanks

# Cluster Policies
```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "default-deny"
spec:
  description: "Block all the traffic (except DNS) by default"
  egress:
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: '53'
        protocol: UDP
      rules:
        dns:
        - matchPattern: '*'
  endpointSelector:
    matchExpressions:
    - key: io.kubernetes.pod.namespace
      operator: NotIn
      values:
      - kube-system
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-ingress-egress
spec:
  description: "Allow all the egress traffic from reserved ingress identity to any endpoints in the cluster"
  endpointSelector:
    matchExpressions:
    - key: reserved:ingress
      operator: Exists
  egress:
  - toEntities:
    - cluster
```

 # Network Policy
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: argocd
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - {}
    - fromEndpoints:
        - matchExpressions:
            - key: reserved:ingress
              operator: Exists
    - fromCIDRSet:
        - cidr: 172.16.50.0/24
  egress:
    - toEndpoints:
        - {}
    - toFQDNs:
        - matchPattern: "*.github.io"
    - toFQDNs:
        - matchName: charts.jetstack.io
    - toFQDNs:
        - matchName: github.com
    - toEntities:
        - kube-apiserver
```
