### DISCUSSION TITLE
External addresses are not visible in cilium

### DISCUSSION THREAD

**Discussion by ivansmm** [cilium/cilium#39514] [Q&A]
Greetings! Can you help me with advice where to look for the problems with following setup: I have a service for which I assign an external address as follows:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
  name: test
spec:
  type: LoadBalancer
  selector:
    app: test
  ports:
  - name: "http"
    port: 80
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "test-pool"
spec:
  blocks:
  - cidr: "10.194.99.132/32"
```

Service reports this address as assigned:

`default       test        LoadBalancer   10.195.0.144   10.194.99.132   80:31303/TCP   12h   app=test`

But when I try to telnet to it:

`telnet 10.194.99.132 80`

It just hangs.

10.194.0.0/16 is my LAN segment. When I check ip address assignments on all of my cluster nodes, I do not see any.

cilium was started up as follows:

```
helm install cilium cilium/cilium   --namespace kube-system   \
    --set kubeProxyReplacement=true   \
    --set ipam.mode=kubernetes   \
    --set masquerade=true   \
    --set enableIPv4=true   \
    --set enableIPv4Masquerade=true   \
    --set enableBPFMasquerade=true   \
    --set enableIPMasqAgent=false   \
    --set routingMode=native   \
    --set ipv4NativeRoutingCIDR=127.0.0.1/32  \
    --set noMasqueradeCIDRs="{10.196.0.0/16,10.195.0.0/24}"   \
    --set l2announcements.enabled=true   \
    --set l2announcements.interface=eth0   \
    --set autoDirectNodeRoutes=true   \
    --set loadBalancer.enabled=true   \
    --set loadBalancer.mode=dsr   \
    --set k8sServiceHost=10.194.99.80   \
    --set k8sServicePort=6443   \
    --set ingressController.enabled=true   \
    --set ingressController.loadBalancer.enabled=true   \
    --set ingressController.loadbalancerMode=shared   \
    --set ingressController.default=true   \
    --set hubble.relay.enabled=true   \
    --set hubble.ui.enabled=true
```

Cilium version is 1.17.3
In which direction to dig?

Thanks!
