### DISCUSSION TITLE
Cilium-Induced Latency Issues in EKS: Impact of Identity Updates and BPF Map Tuning Strategies

### DISCUSSION THREAD

**Discussion by yieon-lyon** [cilium/cilium#40006] [General]
Hi team,
We’re currently running EKS 1.30 and in the process of adopting Cilium. After going through various validation steps, we've rolled it out to our staging cluster. However, we’re now facing a critical issue.
### [Issue]
Since enabling Cilium, we've observed a significant spike in latency across the platform, which is resulting in frequent connection timeouts and overall degraded response times in our services.
### [Environment]
  - Average node count: ~200 nodes
  - Node provisioning: Managed by Karpenter (autoscaling)
  - Node type: Mostly 4 vCPU instances
  - CNI mode: Using Cilium with aws-vpc-cni in chaining mode
### [Hypothesis]
We suspect this may be due to BPF map pressure, and we're considering tuning `bpf.mapDynamicSizeRatio` as a potential solution. We believe increasing this value from the default (`0.002`) might bring dramatic improvements, but we’d appreciate a more fine-grained recommendation.

### [Looking for insights on:]
1. Tuning BPF settings
  - Suggested starting values for `bpf.mapDynamicSizeRatio` in high-node-count clusters
  - Related BPF map parameters to adjust (`nodeMapMax`, `ctTcpMax/ctAnyMax`, `lbMapMax`, etc.) and how they interact
  - How to balance memory consumption and performance when scaling up these values
2. Graceful Cilium rollout strategy
  - Best practices for zero-downtime adoption, especially avoiding initial latency spikes
  - Recommendations on rolling migration or dual-stack coexistence strategies
  - Any known caveats when replacing kube-proxy with Cilium in a live environment, and how to mitigate service disruption risks

We’d greatly appreciate any guidance or shared experiences regarding fine-tuning and safe adoption patterns for large-scale environments.
Thanks in advance!

**Comment by yieon-lyon** [comment]
staging-values.yaml
```yaml
kubeProxyReplacement: true

priorityClassName: system-cluster-critical

k8sServicePort: 443

resources:
   limits:
     cpu: 250m
     memory: 512Mi
   requests:
     cpu: 250m
     memory: 512Mi

updateStrategy:
  rollingUpdate:
    maxUnavailable: "10%"

cni:
  chainingMode: aws-cni
  chainingTarget: aws-cni
  exclusive: false

dnsProxy:
  enableTransparentMode: false

enableIPv4Masquerade: false
enableIPv6Masquerade: false

endpointRoutes:
  enabled: false

routingMode: native

ipv4:
  enabled: true
ipv6:
  enabled: false

l7Proxy: false

pprof:
  enabled: false

hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - flow
      - icmp
      - port-distribution
      - tcp
      - kafka
      - httpV2
    enableOpenMetrics: true

prometheus:
  enabled: true

operator:
  enabled: true
  replicas: 3
  prometheus:
    enabled: true

nodeinit:
  enabled: false

clustermesh:
  useAPIServer: false

bgpControlPlane:
  enabled: false
socketLB:
  enabled: false

```


duration metrics
![image](https://github.com/user-attachments/assets/c41f5df1-68a3-4d5f-95ae-edb7bd5ff979)
