### ISSUE TITLE
Cannot connect to pod local to node through kube-proxy NodePort service (AWS ENI mode)

### ISSUE THREAD

**Issue by huntermassey** [cilium/cilium#10324]
## Bug report

**General Information**

- Cilium version (run `cilium version`)

```
Client: 1.6.6 40814d5b7 2020-02-03T19:05:30+01:00 go version go1.12.16 linux/amd64
Daemon: 1.6.6 40814d5b7 2020-02-03T19:05:30+01:00 go version go1.12.16 linux/amd64
```

- Kernel version (run `uname -a`)

```
Linux ip-192-168-40-159.us-west-2.compute.internal 4.14.154-128.181.amzn2.x86_64 #1 SMP Sat Nov 16 21:49:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)

```
AWS EKS, eksctl, Kubernetes 1.14
```

- Upload a system dump

[cilium-sysdump-20200224-163627.zip](https://github.com/cilium/cilium/files/4247203/cilium-sysdump-20200224-163627.zip)

**How to reproduce the issue**

1. Create a new Kubernetes 1.14 cluster with eksctl

```
eksctl create cluster \
--name test \
--version 1.14 \
--nodegroup-name testcluster-issue \
--node-type m5.large \
--nodes 3 \
--nodes-min 1 \
--nodes-max 4 \
--node-ami auto
```

2. Install cilium in AWS ENI mode following instructions here https://docs.cilium.io/en/v1.6/gettingstarted/aws-eni/
3. Install a NodePort service (YAML provided at bottom)
4. Make an HTTP request to the assigned node port on the node running the created pod for the NodePort service. Request will time out.

Sample NodePort YAML for echoserver:

```
---
apiVersion: v1
kind: Service
metadata:
  name: echo-echoserver-svc
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: echo-echoserver
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo-echoserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echo-echoserver
    spec:
      containers:
      - image: gcr.io/google_containers/echoserver:1.4
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 8080
        resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
```
