### ISSUE TITLE
Endpoint in hostNetwork of LoadBalancer, NodePort, externalIP Service cannot be reached from outside cluster

### ISSUE THREAD

**Issue by maxbischoff** [cilium/cilium#10402]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
`Client: 1.7.0 adeaf8c04 2020-02-18T21:41:10+01:00 go version go1.13.8 linux/amd64
Daemon: 1.7.0 adeaf8c04 2020-02-18T21:41:10+01:00 go version go1.13.8 linux/amd64`
- Kernel version (run `uname -a`)
`4.19.86-flatcar`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...) 
`kubectl version`
`Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}`
- Link to relevant artifacts (policies, deployments scripts, ...)
We deployed the helm chart from https://github.com/maxbischoff/cilium/tree/patches/install/kubernetes/cilium with following values:
<details><summary>values.yaml</summary>
<p>

```yaml
global:
  tag: v1.7.0
  psp:
    enabled: true
  kubeProxyReplacement: "strict"
  hostServices:
    enabled: true
  k8sServiceHost: "127.0.0.1"
  k8sServicePort: 11000
  nodePort:
    enabled: true
  externalIPs:
    enabled: true
agent:
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
      ephemeral-storage: 250Mi
  monitor:
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
        ephemeral-storage: 250Mi
operator:
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
      ephemeral-storage: 250Mi
```

</p>
</details>

kube-proxy is **not** deployed
- Upload a system dump (run `curl -sLO
https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip &&
python cilium-sysdump.zip` and then attach the generated zip file)
[cilium-sysdump-20200302-110411.zip](https://github.com/cilium/cilium/files/4275451/cilium-sysdump-20200302-110411.zip)

**How to reproduce the issue**

1. Create a pod running in the host Network
2. expose it with a loadBalancer service with `externalTrafficPolicy: Local`
3. curl the service, observe that the traffic times out
