### ISSUE TITLE
Helm: Add support for injecting custom environment variables into containers via extraEnv

### ISSUE THREAD

**Issue by seanmwinn** [cilium/cilium#10503]
## Proposal / RFE

Presently, the Helm chart does not allow for a user to inject custom environment variables into their containerized workloads.

Propose adding support for an extraEnv value per-container which will allow users to inject their own custom environment variables into the containerized workload using Helm.

**Comment by aanm** [comment]
This feature has been implemented. The Helm chart now supports `extraEnv` for all major components:

- `extraEnv` - Cilium Agent
- `operator.extraEnv` - Cilium Operator  
- `hubble.relay.extraEnv` - Hubble Relay
- `hubble.ui.backend.extraEnv` / `hubble.ui.frontend.extraEnv` - Hubble UI
- `envoy.extraEnv` - Envoy proxy

Example usage:
```yaml
extraEnv:
  - name: MY_CUSTOM_VAR
    value: "my-value"
  - name: MY_SECRET_VAR
    valueFrom:
      secretKeyRef:
        name: my-secret
        key: secret-key
```
