### ISSUE TITLE
Enabling remote-node-identity then disabling doesn't properly disable it

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#10702]
Cilium: v1.7.1
Kernel: Ubuntu 4.15 AWS

We observed in a community report that if Cilium was deployed with the remote node identity option enabled, then redeployed to disable the option, traffic would continue to be classified as remote-node in cilium monitor:

```
xx drop (Policy denied) flow 0x4ca54ca5 to endpoint 4017, identity 6->28806: 192.168.138.220:36473 -> 192.168.128.41:53 udp
```

Interestingly, the source identity shows up as "host" in the userspace view of the ipcache:

```
$ cilium map get cilium_ipcache
...
192.168.138.220/32   1 0 0.0.0.0             sync
```

Debuginfo reported from cilium agent:
```
"enable-remote-node-identity:false"
```

On this kernel, we cannot fetch ipcache directly from the kernel:

```
> Error while running 'cilium bpf ipcache list':  exit status 1                 
                                                                                                                                                                              
error dumping contents of map: Unable to get next key from map with file descriptor 5: errno 524
```

However the identity comes from somewhere, either through a tunnel from the source node or from ipcache.

**Comment by joestringer** [comment]
A crucial question here is how is the remote-node identity being disabled?

**Comment by lrouquette** [comment]
@joestringer - I've seen this behavior on a cluster built from scratch with cilium 1.7.1: the ConfigMap had:
```
enable-remote-node-identity: "false"
```
It was generated via helm. @danwent has some details and a sysdump.

**Comment by seanmwinn** [comment]
I was able to reproduce this in my environment.
Sysdump and flow logs attached.

[cilium-sysdump-20200410-142201.zip](https://github.com/cilium/cilium/files/4463454/cilium-sysdump-20200410-142201.zip)
[flow-log.txt](https://github.com/cilium/cilium/files/4463455/flow-log.txt)

Vagrantfile:
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

#The cluster will start with 2 agent nodes by default. You can tune the
#number of agent nodes by passing an enviornment variable for K3S_AGENTS

number_of_agents = (ENV['K3S_AGENTS'] || "1").to_i
box_name = (ENV['VAGRANT_BOX'] || "ubuntu/eoan64")
Vagrant.configure("2") do |config|
  config.vm.box = "#{box_name}"


  config.vm.define "master" do |master|
    master.vm.hostname = 'master'
    master.vm.network :private_network, ip: "192.168.80.10", :netmask => "255.255.255.0"
    master.vm.provision :shell, :path => "master.sh"
    master.vm.provider :virtualbox do |vbox|
        vbox.customize ["modifyvm", :id, "--memory", 2048]
        vbox.customize ["modifyvm", :id, "--cpus", 1]
    end
  end

  (1..number_of_agents).each do |node_number|
    config.vm.define "agent#{node_number}" do |agent|
      agent.vm.hostname = "agent#{node_number}"
      ip = node_number + 100
      agent.vm.network :private_network, ip: "192.168.80.#{ip}", :netmask => "255.255.255.0"
      agent.vm.provision :shell, :path => "agent.sh"
      agent.vm.provider :virtualbox do |vbox|
          vbox.customize ["modifyvm", :id, "--memory", 2048]
          vbox.customize ["modifyvm", :id, "--cpus", 1]
      end
    end
  end
end
```

agent.sh:
```
export AGENT_IP=$(ip a |grep global | grep -v '10.0.2.15' | awk '{print $2}' | cut -f1 -d '/')
export MASTER_IP=$(cat /vagrant/master-ip)
export NODE_TOKEN=$(cat /vagrant/node-token)

sudo mount bpffs -t bpf /sys/fs/bpf

curl -sfL https://get.k3s.io | K3S_URL="https://${MASTER_IP}:6443" K3S_TOKEN="${NODE_TOKEN}" INSTALL_K3S_EXEC="--no-flannel --node-ip=${AGENT_IP} --node-external-ip=${AGENT_IP}" sh -
```

master.sh
```
sudo mount bpffs -t bpf /sys/fs/bpf

export MASTER_IP=$(ip a |grep global | grep -v '10.0.2.15' | awk '{print $2}' | cut -f1 -d '/')

curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-backend=none \
--no-flannel --node-ip=${MASTER_IP} --node-external-ip=${MASTER_IP} \
--bind-address=${MASTER_IP} --no-deploy servicelb --no-deploy traefik" sh -

echo $MASTER_IP > /vagrant/master-ip
sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/node-token
sudo cp /etc/rancher/k3s/k3s.yaml /vagrant/k3s.yaml
sudo sed -i -e "s/127.0.0.1/${MASTER_IP}/g" /vagrant/k3s.yaml
```
Install Cilium:
`helm install cilium cilium/cilium --namespace kube-system --set global.device=enp0s8`

Run applications:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: rebel-base
  annotations:
    io.cilium/global-service: "true"
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    name: rebel-base
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rebel-base
spec:
  selector:
    matchLabels:
      name: rebel-base
  replicas: 2
  template:
    metadata:
      labels:
        name: rebel-base
    spec:
      containers:
      - name: rebel-base
        image: docker.io/nginx:1.15.8
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html/
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
      volumes:
        - name: html
          configMap:
            name: rebel-base-response
            items:
              - key: message
                path: index.html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rebel-base-response
data:
  message: "{\"Galaxy\": \"Alderaan\", \"Cluster\": \"Cluster-1\"}\n"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-wing
spec:
  selector:
    matchLabels:
      name: x-wing
  replicas: 2
  template:
    metadata:
      labels:
        name: x-wing
    spec:
      containers:
      - name: x-wing-container
        image: docker.io/cilium/json-mock:1.0
        command: ["bash", "-c", "while true; do curl -sS rebel-base;sleep 1;done"]
      hostNetwork: true
```

Monitor output on the agent node.
`kubectl exec -n kube-system cilium-xyxyx -- cilium monitor`

Get the IP of the rebel-base service:
`export REBEL_BASE=$(kubectl get svc | grep rebel-base | awk '{print $3}')`

SSH to the master and curl:

`vagrant ssh master -- "while true;do curl $REBEL_BASE;sleep 1;done"`

Reconfigure to disable remote node identities:

`helm upgrade cilium cilium/cilium --namespace kube-system --set global.device=enp0s8 \
--set global.remoteNodeIdentity=false`

Restart cilium and cilium-operator pods.

Identity 6 still reported in flow logs.


```
sean.winn@Seans-MacBook-Pro cilium-k3s-demo % kubectl exec -n kube-system cilium-ndr2c -- cilium map get cilium_ipcache
Key                 Value                   State   Error
10.42.0.92/32       35989 0 192.168.80.10   sync
10.42.0.201/32      1 0 192.168.80.10       sync
10.42.0.229/32      52597 0 192.168.80.10   sync
192.168.80.101/32   1 0 0.0.0.0             sync
10.42.1.143/32      1 0 0.0.0.0             sync
10.42.1.30/32       4 0 0.0.0.0             sync
10.0.2.15/32        1 0 0.0.0.0             sync
0.0.0.0/0           2 0 0.0.0.0             sync
10.42.1.238/32      19624 0 0.0.0.0         sync
10.42.0.14/32       19624 0 192.168.80.10   sync
10.42.0.12/32       4405 0 192.168.80.10    sync
192.168.80.10/32    1 0 0.0.0.0             sync
10.42.0.31/32       4 0 192.168.80.10       sync
sean.winn@Seans-MacBook-Pro cilium-k3s-demo % kubectl exec -n kube-system cilium-ndr2c -- cilium bpf ipcache list
IP PREFIX/ADDRESS   IDENTITY
10.42.0.92/32       35989 0 192.168.80.10
10.42.1.30/32       4 0 0.0.0.0
0.0.0.0/0           2 0 0.0.0.0
10.0.2.15/32        1 0 0.0.0.0
10.42.0.12/32       4405 0 192.168.80.10
10.42.0.14/32       19624 0 192.168.80.10
10.42.0.31/32       4 0 192.168.80.10
192.168.80.10/32    1 0 0.0.0.0
192.168.80.101/32   1 0 0.0.0.0
10.42.0.201/32      1 0 192.168.80.10
10.42.0.229/32      52597 0 192.168.80.10
10.42.1.143/32      1 0 0.0.0.0
10.42.1.238/32      19624 0 0.0.0.0
```
