### ISSUE TITLE
K8s Network Policy not working with configured auto-direct-node-routes

### ISSUE THREAD

**Issue by zbindenren** [cilium/cilium#11096]
- Client: 1.7.90 c3c69547f 2020-04-17T21:33:13+02:00 go version go1.14.2 linux/amd64
- Daemon: 1.7.90 c3c69547f 2020-04-17T21:33:13+02:00 go version go1.14.2 linux/amd64
- Linux 5.6.5-1.el7.elrepo.x86_64 #1 SMP Thu Apr 16 14:02:22 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
- Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

We have a problem with cilium's network policy implementation. For testing purposes we deployed a simple kuard deployment like:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard
  name: kuard
  namespace: namespace-1
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kuard
  name: kuard
  namespace: namespace-1
spec:
  progressDeadlineSeconds: 600
  replicas: 6
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kuard
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - image: gcr-docker-remote.repo.pnet.ch/kuar-demo/kuard-amd64:1
        imagePullPolicy: Always
        name: kuard
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

To deny traffic from all other namespaces we created the following network policy [description here](https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/04-deny-traffic-from-other-namespaces.md):

```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: secondary
  name: deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
```

But all traffic gets dropped from within that namespace.

I can neither access the service `kuard.namespace-1.svc.cluster.local:8080` from any pod nor `<ip of pod>:8080` from a different pod in the same namespace.

But tracing gives me the following output:

```
cilium policy trace --src-k8s-pod namespace-1:kuard-cd66bf97c-sfcf5 --dst-endpoint 242
----------------------------------------------------------------

Tracing From: [k8s:app=kuard, k8s:io.cilium.k8s.policy.cluster=t1-k8s-online-a, k8s:io.cilium.k8s.policy.serviceaccount=default, k8s:io.kubernetes.pod.namespace=namespace-1] => To: [k8s:app=kuard, k8s:io.cilium.k8s.policy.cluster=t1-k8s-online-a, k8s:io.cilium.k8s.policy.serviceaccount=default, k8s:io.kubernetes.pod.namespace=namespace-1] Ports: [0/ANY]

Resolving ingress policy for [k8s:app=kuard k8s:io.cilium.k8s.policy.cluster=t1-k8s-online-a k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=namespace-1]
* Rule {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"namespace-1"}}: selected
    Allows from labels {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"namespace-1"}}
      Found all required labels
1/3 rules selected
Found allow rule
Ingress verdict: allowed

Final verdict: ALLOWED
```

cilium config:
```
auto-direct-node-routes: "true"
bpf-ct-global-any-max: "262144"
bpf-ct-global-tcp-max: "524288"
cluster-name: t1-k8s-online-a
debug: "false"
enable-auto-protect-node-port-range: "false"
enable-endpoint-health-checking: "true"
enable-external-ips: "true"
enable-host-reachable-services: "true"
enable-ipv4: "true"
enable-ipv6: "false"
enable-node-port: "true"
enable-remote-node-identity: "true"
enable-well-known-identities: "false"
enable-xt-socket-fallback: "true"
identity-allocation-mode: crd
install-iptables-rules: "true"
k8s-require-ipv4-pod-cidr: "true"
kube-proxy-replacement: strict
masquerade: "true"
monitor-aggregation: medium
monitor-aggregation-flags: all
monitor-aggregation-interval: 5s
node-port-mode: hybrid
node-port-range: 1600,10000
preallocate-bpf-maps: "true"
prometheus-serve-addr: :9090
sidecar-istio-proxy-image: cilium/istio_proxy
tofqdns-enable-poller: "false"
tunnel: disabled
wait-bpf-mount: "true"
```

If we change the config from :
```
tunnel: disabled
auto-direct-node-routes: "true"
```

to:
```
tunnel: vxlan
auto-direct-node-routes: "false"
```

everything works as expected.

```
cilium status --all-nodes
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.17 (v1.17.3) [linux/amd64]
Kubernetes APIs:        ["CustomResourceDefinition", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Endpoint", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [NodePort (HYBRID, 1600-10000, XDP: NONE), HostPort, ExternalIPs, HostReachableServices (TCP, UDP)]
Cilium:                 Ok       OK
NodeMonitor:            Disabled
Cilium health daemon:   Ok
IPAM:                   IPv4: 13/127 allocated from 10.127.68.128/25,
Controller Status:      53/53 healthy
Proxy Status:           OK, ip 10.127.68.208, 0 redirects active on ports 10000-20000
Hubble:                 Disabled
Cluster health:   10/10 reachable   (2020-04-22T07:06:31Z)
```

**Comment by aanm** [comment]
@zbindenren the policy provided seems to be applied to a second namespace.
```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: secondary
  name: deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
```

Was that your intention or was the namespace in the policy suppose to be `namespace-1`?

**Comment by zbindenren** [comment]
@aanm Sorry this was a copy/paste error: for `namespace-1` I have the following netpol:

`kubectl get netpol namespace-default -o yaml`:
```yaml

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: namespace-default
  namespace: namespace-1
spec:
  ingress:
  - from:
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress
```
