### ISSUE TITLE
Potential race condition with kubeadm, no kube-proxy, ENI-mode, with Cloud-Controller-Manager

### ISSUE THREAD

**Issue by dmolik** [cilium/cilium#11146]
## Bug report

**General Information**

- Cilium version: 1.7.2
- Kernel version: 5.6.6
- Orchestration system version: Kubernetes 1.18.2

I'm using terraform to spool and deploy kubeadm on AWS. 

**How to reproduce the issue**

The issues is that if the Cloud Controller Manager is not brought up before Cilium the node is brought, and the operator starts running ENIs will be attached to the instance before the CCM has a chance to validate the node, AWS will return a 400 because it won't know which interface to validate against. Similar to this big report: https://github.com/kubernetes/kubernetes/issues/70924

**Potential workaround**

I used the following for my CCM deployment:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: cloud-controller-manager
  name: cloud-controller-manager
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: cloud-controller-manager
  template:
    metadata:
      labels:
        k8s-app: cloud-controller-manager
    spec:
      hostNetwork: true
      serviceAccountName: cloud-controller-manager
      containers:
      - name: cloud-controller-manager
        image: docker.io/graytshirt/cloud-provider-aws:0.18.0
        env:
        - name: KUBERNETES_PORT_6443_TCP
          value: tcp://@KUBEENDPOINT@:6443
        - name: KUBERNETES_SERVICE_HOST
          value: @KUBEENDPOINT@
        - name: KUBERNETES_PORT
          value: tcp://@KUBEENDPOINT@:6443
        - name: KUBERNETES_SERVICE_PORT
          value: "6443"

        command:
        - /usr/bin/aws-cloud-controller-manager
        args:
        - --leader-elect=true
        - --use-service-account-credentials
        #- --allocate-node-cidrs=true
        #- --configure-cloud-routes=true
        - --cluster-cidr=@POD_SUBNET@
        - --cluster-name=@CLUSTER_NAME@
      tolerations:
      # this is required so CCM can bootstrap itself
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        effect: NoSchedule
      # this is to have the daemonset runnable on master nodes
      # the taint may vary depending on your cluster setup
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      # Spool the CCM before there is a CNI present
      - key: node.kubernetes.io/not-ready
        effect: NoSchedule
      # this is to restrict CCM to only run on master nodes
      # the node selector may vary depending on your cluster setup
      nodeSelector:
        node-role.kubernetes.io/master: ""
```
As you may see the kubernetes environment variables have been overwritten with the OOB api endpoint address. Similar to setting the SERVER_IP_ADDRESS in the helm chart here: https://docs.cilium.io/en/v1.7/gettingstarted/kubeproxy-free/#quick-start
