### ISSUE TITLE
CI: log cluttered with `grep: _/home/vagrant/go/src...: No such file or directory` messages during build

### ISSUE THREAD

**Issue by tklauser** [cilium/cilium#11219]
Log outputs such as the following clutter the CI logs during build:

<details><summary>Example CI log output</summary>
```
    k8s1-1.18: grep: _/home/vagrant/go/src/bugtool
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/bugtool/cmd: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/cilium: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/cilium/cmd: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/cilium-health: No such file or directory
    k8s1-1.18: grep: 
    k8s1-1.18: _/home/vagrant/go/src/cilium-health/cmd: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/cilium-health/launch: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/cilium-health/responder: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/common: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/common/addressing: No such file or directory
    k8s1-1.18: grep: 
    k8s1-1.18: _/home/vagrant/go/src/common/types: No such file or directory
    k8s1-1.18: grep: 
    k8s1-1.18: _/home/vagrant/go/src/daemon: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/daemon/cmd: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/hubble-relay: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/hubble-relay/cmd: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/hubble-relay/cmd/completion: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/hubble-relay/cmd/serve: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/hubble-relay/cmd/version: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/operator: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/operator/metrics: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/operator/option
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/alignchecker: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/allocator: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/annotation: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/api: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/api/helpers: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/api/metrics: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/api/metrics/mock: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/aws/ec2: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/aws/ec2/mock
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/aws/eni: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/aws/eni/routing: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/aws/metadata: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/aws/types: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/azure/api: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/azure/api/mock: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/azure/ipam: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/azure/types: No such file or directory
    k8s1-1.18: grep: 
    k8s1-1.18: _/home/vagrant/go/src/pkg/backoff: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/bpf: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/bpf/binary: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/byteorder: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/cgroups: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/checker: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/cidr: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/cleanup: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/client: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/clustermesh: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/clustermesh/types: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/command: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/command/exec: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/comparator: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/completion: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/components: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/controller: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/counter: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/crypto/certificatemanager: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/crypto/sha1
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/datapath: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/datapath/alignchecker: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/datapath/connector: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/datapath/fake: No such file or directory
    k8s1-1.18: grep: 
    k8s1-1.18: _/home/vagrant/go/src/pkg/datapath/ipcache: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/datapath/iptables: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/datapath/link: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/datapath/linux: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/datapath/linux/config: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/datapath/linux/ipsec: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/datapath/linux/linux_defaults: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/datapath/linux/probes: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/datapath/linux/route: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/datapath/loader: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/datapath/loader/metrics: No such file or directory
    k8s1-1.18: grep: 
    k8s1-1.18: _/home/vagrant/go/src/pkg/datapath/maps: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/datapath/prefilter
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/debug: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/defaults: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/elf: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/endpoint: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/endpoint/id: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/endpoint/regeneration: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/endpointmanager
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/endpointmanager/idallocator: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/envoy
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/envoy/xds: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/eventqueue
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/flowdebug: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/fqdn: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/fqdn/dnsproxy: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/fqdn/matchpattern: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/health/client: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/health/defaults: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/health/probe: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/health/probe/responder: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/health/server: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/container
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/defaults: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/filters: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/ipcache: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/k8s: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/listener: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/logger: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/math: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/metrics: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/metrics/api: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/metrics/drop: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/metrics/flow: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/metrics/http: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/metrics/icmp: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/metrics/port-distribution: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/metrics/tcp: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/observer: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/observer/observeroption: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/parser: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/parser/endpoint: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/parser/errors
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/parser/getters: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/parser/options: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/parser/seven: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/parser/threefour: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/peer: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/peer/serviceoption: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/relay: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/relay/relayoption: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/server: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/hubble/server/serveroption: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/identity: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/identity/cache: No such file or directory
    k8s1-1.18: grep: 
    k8s1-1.18: _/home/vagrant/go/src/pkg/identity/identitymanager: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/identity/model: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/idpool: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/ip: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/ipam: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/ipam/allocator: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/ipam/allocator/aws: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/ipam/allocator/azure: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/ipam/metrics: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/ipam/metrics/mock
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/ipam/types: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/ipcache: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/ipcache/fake: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/apis/cilium.io: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/apis/cilium.io/utils: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/apis/cilium.io/v2: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/apis/cilium.io/v2/client: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/client/clientset/versioned: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/client/clientset/versioned/fake: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/client/clientset/versioned/scheme: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/client/clientset/versioned/typed/cilium.io/v2: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/client/clientset/versioned/typed/cilium.io/v2/fake: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/client/informers/externalversions: No such file or directory
    k8s1-1.18: 
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/client/informers/externalversions/cilium.io: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/client/informers/externalversions/cilium.io/v2
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/client/informers/externalversions/internalinterfaces: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/client/listers/cilium.io/v2: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/endpointsynchronizer
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/identitybackend: No such file or directory
    k8s1-1.18: grep: 
    k8s1-1.18: _/home/vagrant/go/src/pkg/k8s/informer
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/informer/benchmarks: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/metrics: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/types: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/utils
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/version: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/k8s/watchers: No such file or directory
    k8s1-1.18: grep: 
    k8s1-1.18: _/home/vagrant/go/src/pkg/kafka: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/kvstore: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/kvstore/allocator: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/kvstore/store: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/labels: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/labels/cidr: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/labels/model
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/labelsfilter
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/launcher: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/loadbalancer: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/loadinfo: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/lock: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/logging: No such file or directory
    k8s1-1.18: grep: 
    k8s1-1.18: _/home/vagrant/go/src/pkg/logging/logfields: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/mac
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/maps/cidrmap: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/maps/ctmap: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/maps/ctmap/gc: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/maps/encrypt: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/maps/eppolicymap: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/maps/eventsmap: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/maps/fragmap: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/maps/ipcache: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/maps/lbmap: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/maps/lxcmap: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/maps/metricsmap: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/maps/nat: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/maps/neighborsmap: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/maps/policymap: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/maps/signalmap
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/maps/sockmap: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/maps/tunnel: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/math: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/metrics: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/modules: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/monitor: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/monitor/agent: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/monitor/alignchecker: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/monitor/api: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/monitor/notifications
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/monitor/payload: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/mountinfo: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/mtu: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/netns: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/node
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/node/addressing: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/node/manager: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/node/store: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/node/types: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/nodediscovery: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/option: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/option/fake: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/pidfile: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/policy: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/policy/api: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/policy/groups: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/policy/groups/aws: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/policy/trace: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/policy/trafficdirection: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/pprof: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/probe: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/proxy: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/proxy/accesslog: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/proxy/logger: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/rand: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/revert: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/safetime: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/serializer: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/service: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/service/healthserver: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/service/store: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/set: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/signal: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/sockops: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/source: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/spanstat: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/status: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/sysctl: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/trigger: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/tuple: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/u8proto: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/uuid: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/version: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/pkg/versioncheck: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/plugins/cilium-cni: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/plugins/cilium-cni/chaining/api: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/plugins/cilium-cni/chaining/awscni: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/plugins/cilium-cni/chaining/azure: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/plugins/cilium-cni/chaining/flannel: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/plugins/cilium-cni/chaining/generic-veth: No such file or directory
    k8s1-1.18: grep: 
    k8s1-1.18: _/home/vagrant/go/src/plugins/cilium-cni/chaining/portmap
    k8s1-1.18: : No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/plugins/cilium-cni/types: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/plugins/cilium-docker: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/plugins/cilium-docker/driver: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/proxylib: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/proxylib/accesslog: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/proxylib/cassandra: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/proxylib/memcached: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/proxylib/memcached/binary: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/proxylib/memcached/meta: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/proxylib/memcached/text: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/proxylib/npds: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/proxylib/proxylib: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/proxylib/r2d2: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/test/helpers/logutils: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/tools/alignchecker: No such file or directory
    k8s1-1.18: grep: _/home/vagrant/go/src/tools/maptool: No such file or directory
    k8s1-1.18: dirname: missing operand
    k8s1-1.18: Try 'dirname --help' for more information.
```
</details>

Also note the `dirname: missing operand` error. I assume this is due to the following lines:

https://github.com/cilium/cilium/blob/2950ea40eea38813bccdfa94b98cb30894d2fa2d/Makefile#L89-L90

which is the only place where `dirname` seems to be used.

It doesn't look like this has any implications on the build apart from cluttering the log, so cleaning this up would just be nice to have. Can easily be reproduced by running e2e tests locally: https://docs.cilium.io/en/latest/contributing/testing/e2e/
