### ISSUE TITLE
Add support for TargetPort

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#11345]
https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
```
This specification creates a new Service object named “my-service”, which targets TCP port 9376 on any Pod with the app=MyApp label.
