### ISSUE TITLE
Failure in [sig-network] NetworkPolicy between server and client should enforce policy based on NamespaceSelector with MatchExpressions

### ISSUE THREAD

**Issue by brb** [cilium/cilium#11365]
The k8s e2e test from $title (https://github.com/kubernetes/kubernetes/blob/v1.15.7/test/e2e/network/network_policy.go#L212) fails against Cilium (latest master and v1.7.3): `client-a` was able to connect to the svc protected by the netpol.

```
# netpol
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: NetworkPolicy
  metadata:
    name: allow-any-ns-different-than-ns-a-via-ns-selector-with-match-expressions
    namespace: network-policy-2300
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchExpressions:
          - key: ns-name
            operator: NotIn
            values:
            - network-policy-c
    podSelector:
      matchLabels:
        pod-name: server
    policyTypes:
    - Ingress

# client
apiVersion: v1
kind: Pod
metadata:
  labels:
    pod-name: client-a
  name: client-a-qm5jw
  namespace: network-policy-c-9654
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - for i in $(seq 1 5); do nc -vz -w 8 svc-server.network-policy-8440
      80 && exit 0 || sleep 1; done; exit 1
    image: docker.io/library/busybox:1.29

# client ns
apiVersion: v1
kind: Namespace
metadata:
  labels:
    ns-name: network-policy-c
    ...
  name: network-policy-c-9654
```

Note that the match expression is matching on the label which is defined in the client's ns.

**Comment by aanm** [comment]
discussed during the weekly meeting it might be as simple as setting `identity-change-grace-period=0s` in the upstream k8s

**Comment by brb** [comment]
@aanm I've tried adding a sleep for 60s after the netpol creation, and also settings `identity-change-grace-period=0s`. Neither helped, so it's probably a real bug.

**Comment by aanm** [comment]
@brb could this be an occurrence of https://github.com/cilium/cilium/issues/11593?

**Comment by brb** [comment]
> @brb could this be an occurrence of #11593?

I doubt. Do we have tests in CI where we check whether `namespaceSelector` works with `matchExpressions`?

**Comment by brb** [comment]
The server pod spec (got from another run, so `name` and `namespace` is different than in the issue description of other objects):

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    pod-name: server
  name: server-r4z8x
  namespace: network-policy-8704
spec:
  containers:
  - args:
    - porter
    env:
    - name: SERVE_PORT_80
      value: foo
    image: us.gcr.io/k8s-artifacts-prod/e2e-test-images/agnhost:2.13
    imagePullPolicy: IfNotPresent
    name: server-container-80
    ports:
    - containerPort: 80
      name: serve-80
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-sw6jg
      readOnly: true
  - args:
    - porter
    env:
    - name: SERVE_PORT_81
      value: foo
    image: us.gcr.io/k8s-artifacts-prod/e2e-test-images/agnhost:2.13
    imagePullPolicy: IfNotPresent
    name: server-container-81
    ports:
    - containerPort: 81
      name: serve-81
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 81
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-sw6jg
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  ```
