### ISSUE TITLE
pod-to-external-fqdn-allow-google-cnp connectivity test fails. Possible documentation contradiction.

### ISSUE THREAD

**Issue by uipo78** [cilium/cilium#11428]
## Bug report

I just deployed Cilium onto an AKS cluster following the Azure CNI chaining instructions as well as the connectivity test. Every test passed except for `pod-to-external-fqdn-allow-google-cnp`, so I proceeded to investigate. What I noticed was something contradictory between the documentation and the network policy deployed for `pod-to-external-fqdn-allow-google-cnp`.

Snippet from [this section](https://docs.cilium.io/en/stable/policy/language/#dns-based) of the docs:
 > `toFQDNs` egress rules cannot contain any other L3 rules, such as `toEndpoints` (under Labels Based) and `toCIDRs` (under CIDR Based). 

The CiliumNetworkPolicy associated with `pod-to-external-fqdn-allow-google-cnp`:
```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "pod-to-external-fqdn-allow-google-cnp"
spec:
  endpointSelector:
    matchLabels:
      name: pod-to-external-fqdn-allow-google-cnp
  egress:
  - toEndpoints:
    - matchLabels:
       "k8s:io.kubernetes.pod.namespace": kube-system
       "k8s:k8s-app": kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: openshift-dns
        k8s:dns.operator.openshift.io/daemonset-dns: default
    toPorts:
    - ports:
      - port: "5353"
        protocol: UDP
      rules:
        dns:
        - matchPattern: "*"
  - toFQDNs:
    - matchPattern: "*.google.com"
```

Notice how its `egress` contains multiple `toEndpoints` rules.

**General Information**

- Cilium version (run `cilium version`): `1.7.3`
- Kernel version (run `uname -a`): `Linux aks-akspool-26081535-vmss000002 4.15.0-1071-azure #76-Ubuntu SMP Wed Feb 12 03:02:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...): `1.15.7`
- Upload a system dump (run `curl -sLO
https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip &&
python cilium-sysdump.zip` and then attach the generated zip file) [cilium-sysdump-20200508-111644.zip](https://github.com/cilium/cilium/files/4600383/cilium-sysdump-20200508-111644.zip)

**How to reproduce the issue**

1. [Follow cilium's documentation on how to install Cilium on an AKS cluster in combination with Azure CNI.](https://docs.cilium.io/en/v1.7/gettingstarted/cni-chaining-azure-cni/)
2. [Deploy the connectivity test](https://docs.cilium.io/en/v1.7/gettingstarted/cni-chaining-azure-cni/#deploy-the-connectivity-test)

**Comment by uipo78** [comment]
Posting this information here just in case it's useful.

[cilium-sysdump-20200518-094655.zip](https://github.com/cilium/cilium/files/4657606/cilium-sysdump-20200518-094655.zip)

**Comment by uipo78** [comment]
@tgraf any idea?

**Comment by joestringer** [comment]
In the example:

```
  egress:
  - toEndpoints:
    - matchLabels:
       "k8s:io.kubernetes.pod.namespace": kube-system
       "k8s:k8s-app": kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: openshift-dns
        k8s:dns.operator.openshift.io/daemonset-dns: default
    toPorts:
    - ports:
      - port: "5353"
        protocol: UDP
      rules:
        dns:
        - matchPattern: "*"
  - toFQDNs:
    - matchPattern: "*.google.com"
```

I see an egress spec with 3 rules:
* toEndpoints + toPorts: "match on port 53 DNS traffic at L7 which is destined to the kube-dns pod and allow it all"
* toEndpoints + toPorts: "match on port 5353 DNS traffic at L7 which is destined to the openshift DNS pod and allow it all"
* toFQDNs: Match on requests to subdomains of google.com.

The quoted snippet of the docs:

> toFQDNs egress rules cannot contain any other L3 rules, such as toEndpoints (under Labels Based) and toCIDRs (under CIDR Based).

The intention here is to describe that the individual last rule which has a `toFQDNs` match cannot also match on `toEndpoints`. Having another separate rule like the example does is valid. 

From the above I think that it doesn't contradict itself, however there may be room for improving the precision of the wording or to improve the clarity.
