### ISSUE TITLE
Cilium egress policies should support local node redirection

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#11646]
Tools like kiam (https://github.com/uswitch/kiam) and kube2iam (https://github.com/jtblin/kube2iam) use iptables rules to redirect traffic destined to the cloud metadata service (169.254.169.254:80) to a local daemonset running in host networking.   These iptables rules match on the source device name (e.g., lxc+ for cilium) in order to ensure they match only pod traffic, and not traffic from the host itself.  

However, if pods an an egress L7 proxy redirection policy to enable HTTP visibility on TCP/80 policy for all destinations, traffic to the metadata service will be redirect to the L7 proxy (which is OK), but then the traffic leaving this proxy and going to the outside world will not match the iptables redirect rule, because the source device will not longer by lxcXXXX.  

One possible long-term path for this would be to implement the type of redirection done by kiam in iptables directly in BPF.   It is a pretty simple DNAT rule: 

```
iptables \
  --append PREROUTING \
  --protocol tcp \
  --destination 169.254.169.254 \
  --dport 80 \
  --in-interface lxc+ \
  --jump DNAT \
  --table nat \
  --to-destination <node-ip>:8181
```

This is likely what we would want to do for enabling kiam/kube2iam in a iptables free env anyway.

Note that we would likely want this rule inserted via a config time option, or via cluster-wide network policy if we wanted a bit more configurability, but not via standard CNP, as we wouldn't want tenants being able to disable this.   It is similar to Node firewall in that sense.

**Comment by joestringer** [comment]
From @errordeveloper  during Cilium community meeting: There is a AWS feature that implements this more natively, did we look into this?

**Comment by errordeveloper** [comment]
I was referring to [IAM roles for service accounts
](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), it's native to AWS IAM and more secure by design (since it doesn't require special node configuration) and is available for EKS as well as self-managed Kubernetes deployment on EC2.

**Comment by tgraf** [comment]
KIAM was one prominent use case for this feature. I agree that going forward, demand for KIAM redirect will shrink.

I think pursuing this still makes sense though outside of the KIAM use case. There are many more examples where redirect a known VIP to a node-local port is useful.

We can support this with a CRD or via CNPs to allow redirecting certain connections to a local node port.

**Comment by dmolik** [comment]
I use aws irsa ( IAM roles for service accounts ) as I can sell it to my parent Org easier because of the aforementioned security features. However I still think there is a use case for CNP denials for pods that don't need to access sts or other AWS services. Or even limiting scope of existing access.

**Comment by aditighag** [comment]
The current proposal is to expose this functionality to end users via a CRD, wherein the user would specify the frontend IP (or VIP) and port to be redirected. The CRD would have a "local endpoint" selector to redirect the traffic to a local node entity. Kubernetes RBAC roles can be used to enforce security related considerations.

**Comment by joestringer** [comment]
A user has reported to us that when running kube2iam on older releases of Cilium, forwarding via kube2iam may be broken. In this environment, there was a clash with [AAD Pod Identity](https://github.com/Azure/aad-pod-identity). Removing AAD Pod Identity resolved the issue.

**Comment by lucioveloso** [comment]
Example using CiliumLocalRedirectPolicy CRD:

```
apiVersion: "cilium.io/v2"
kind: CiliumLocalRedirectPolicy
metadata:
  name: "kiam-redirect"
  namespace: default
spec:
  redirectFrontend:
    addressMatcher:
      ip: "169.254.169.254"
      toPorts:
        - port: "80"
          protocol: TCP
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        app: kiam
        component: "agent"
    toPorts:
      - port: "8181"
        protocol: TCP
```
