### ISSUE TITLE
Helm: Implement per-container image, tag, and pull policy controls

### ISSUE THREAD

**Issue by seanmwinn** [cilium/cilium#11962]
## Proposal / RFE

Implement support in the Helm charts for each container to independently specify image name, tag, and image pull policy which will control the sub-chart values. Implement defaults at the sub-chart level with the ability to override at the parent chart. This should be implemented for every container consistently:

```yaml
image:
  repository: 
  tag:
  pullPolicy:
```
