### ISSUE TITLE
Helm: Implement per-container resource controls for CPU and Memory requests and limits

### ISSUE THREAD

**Issue by seanmwinn** [cilium/cilium#11963]
## Proposal / RFE

Implement support for each sub-chart to configure resource requests and limits related to CPU and Memory independently for each cilium application. Implement defaults at the sub-chart level with the ability to override using the parent chart's values file. Leverage to-YAML to render the resources block directly in the template.

**Comment by aanm** [comment]
I'm on the fence WRT CPU & memory limits for Cilium as it is part of the infrastructure and the OS manages the memory in a better way.

**Comment by acholt** [comment]
Hey @seanmwinn 

I'm in agreement with you after reviewing the resources request and limits of the various components. I see only the Cilium daemonset has requests set but no limits.

- daemonset.apps/cilium (Requests Only)
- deployment.apps/cilium-operator (None)
- deployment.apps/hubble-relay (None)
- deployment.apps/hubble-ui (None)

I believe we should have default requests and limits for all the above☝️  to protect those resources as they are critical components when the system is under load, they will get killed.

**Comment by aanm** [comment]
The Cilium Helm chart now supports per-container resource controls for CPU and Memory requests and limits. Here's how to use it:

## Example `values.yaml` Override

```yaml
# Cilium Agent resources
resources:
  limits:
    cpu: 4000m
    memory: 4Gi
  requests:
    cpu: 100m
    memory: 512Mi

# Agent init containers resources
initResources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

# CNI init container resources
cni:
  resources:
    requests:
      cpu: 100m
      memory: 10Mi

# Cilium Operator resources
operator:
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

# Hubble Relay resources
hubble:
  relay:
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
  ui:
    backend:
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 64Mi
    frontend:
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 64Mi

# Cilium Envoy resources (when using separate DaemonSet)
envoy:
  resources:
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 512Mi

# Node Init resources
nodeinit:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

# Preflight resources
preflight:
  resources:
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 512Mi

# ClusterMesh API Server resources
clustermesh:
  apiserver:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1000m
        memory: 1024Mi
    etcd:
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 256Mi
      init:
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
    kvstoremesh:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 1000m
          memory: 1024Mi

# Certgen Job resources
certgen:
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Cgroup automount init container resources
cgroup:
  init:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

# SPIRE resources (when using mutual authentication)
authentication:
  mutual:
    spire:
      install:
        agent:
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
        server:
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
```
