### ISSUE TITLE
Cilium native hostport only listens on a internal IP, unlike CNI portmap

### ISSUE THREAD

**Issue by dghubble** [cilium/cilium#12116]
## Bug report

Cilium v1.8 release candidates include a native bpf hostport feature to replace CNI [portmap](https://github.com/containernetworking/plugins/tree/master/plugins/meta/portmap) chaining ([#10359](https://github.com/cilium/cilium/issues/10359)) implemented in https://github.com/cilium/cilium/pull/10592. In testing, it seems this feature is a partial implementation of CNI portmap.

When CNI portmap is used in a CNI conflist (with any CNI provider, not just Cilium), Kubernetes Pods that set a hostPort proxy any traffic on that host port to the container.

```
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
```

For example, a PodSpec above would allow the web app to be accessed via multiple host IPs - hostPort maps multiple interface addresses (unless a single hostIP is set https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#containerport-v1-core).

```
curl 127.0.0.1:80  (works)
curl 10.135.173.170:80 (works)
curl publicipv4:80 (works)
curl [someipv6]:80 (depends)
```

In Cilium v1.8.0-rc3 the hostport feature works as described in docs, but its always picking the node's own internal IP, which doesn't satisfy the use cases CNI portmap had.

```
curl 127.0.0.1:80  (no)
curl 10.135.173.170:80 (works)
curl publicipv4:80 (no)
curl [someipv6]:80 (no)
```

```
cilium service list
...
13   10.135.173.170:80      HostPort       1 => 10.2.0.214:80
```

So its not a bug per-se, more that the implementation isn't a drop-in for CNI portmap yet, unless the node's internal IP is the only address you are interested in. (imo) Most uses of CNI portmap to support containers with hostPort are using it to listen on any of the available host addresses.

* node with a private IP (kubelet internal IP, tunnels) and public IP (interfacing with LBs)
* health checks may expect the hostPort to be available on 127.0.0.1 or ::1 as well
* node with multiple addresses for other reasons

For myself, I have to fallback to certain pods that could use hostPort to just using full hostNetwork.

**General Information**

- Cilium version: 1.8.0-rc3
- Kernel version: 5.6.11
- Orchestration system version: Kubernetes v1.18.3

**Comment by dghubble** [comment]
Workaround attempts by setting an explicit `hostIP` field in the [ContainerPort](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#containerport-v1-core) spec as `0.0.0.0` will not actually work either, despite appearances.

```
            - name: http
              hostIP: 0.0.0.0
              containerPort: 80
              hostPort: 80
            - name: https
              hostIP: 0.0.0.0
              containerPort: 443
              hostPort: 443
```

```
kubectl exec -it cilium-agent-rplt6 -n kube-system cilium service list
...
14   0.0.0.0:80          HostPort       1 => 10.2.2.154:80      
15   0.0.0.0:443         HostPort       1 => 10.2.2.154:443     
```

```
curl 127.0.0.1:80  (no)
curl 10.135.173.170:80 (no)
curl publicipv4:80 (no)
curl [someipv6]:80 (no)
```

**Comment by soumynathan** [comment]
Yes I did validate and I am seeing the same behavior as well for the Hostport. The service is only accessible through the HostIP:Port combination.

**Comment by borkmann** [comment]
@dghubble Fixed via #12446. For testing feel free to use `docker.io/cilium/cilium:latest` for the time being until it ends up in `1.8.2`. Thanks for reporting!

**Comment by povils** [comment]
Hey! Could this also affect docker0 bridge compatability?
The I am using portmap i am able to reach `curl 172.17.0.1:hostPort`
With cilium BPF implementation I cannot anymore

**Comment by borkmann** [comment]
> Hey! Could this also affect docker0 bridge compatability?
> When I am using portmap i am able to reach `curl 172.17.0.1:hostPort`
> With cilium native hosrtport implementation I cannot anymore

Thanks for the report, how does your pod spec look like?

**Comment by povils** [comment]
Hey! thanks for looking into it. This is the spec i used to replicate the issue:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
          hostPort: 8081
`
And what i tried is curl from other pod:
```
curl 172.17.0.1:8081
```
