### ISSUE TITLE
IPv6 service does not works in dual-stack cluster with NodePorts enabled

### ISSUE THREAD

**Issue by Jean-Daniel** [cilium/cilium#12247]
## Bug report

I'm experimenting with a dual-stack cluster, and encounter an issue with IPv6 service reachability when cilium has `KubeProxyReplacement: NodePort` enabled.

I deployed 2 nginx services, one IPv4 and one IPv6. The IPv4 service works fine. I can `ping` it and reach it with `curl` from anywhere. For the IPv6 service, I can `ping` it normally, but `curl` never receive any reply and timeouts.

When using `cilium monitor`, I can see the initial request passing, but nothing else:

```
-> endpoint 1655 flow 0x0 identity 2->3706 state established ifindex lxcdc689d449885 orig-ip 2a01:e0a:164:2090:18b6:e0ad:fc50:5a88: [2a01:e0a:164:2090:18b6:e0ad:fc50:5a88]:52584 -> [fd00:abba:96fb::37]:80 tcp SYN
```

When disabling kube-proxy replacement, the IPv6 service works fine.

**General Information**

- Cilium version (run `cilium version`): 1.8.0
- Kernel version (run `uname -a`): 5.4.0-37-generic #41-Ubuntu 
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...): Kubernetes v1.18.4

[cilium-sysdump-20200623-235939.zip](https://github.com/cilium/cilium/files/4822199/cilium-sysdump-20200623-235939.zip)

**How to reproduce the issue**

1. instruction 1
This is a minimal cluster on bare-metal with a single controller and a single node.
This cluster only contains cilium and MetalLB. 

Note: It runs with a patched version of Kubelet that export both IPv4 and IPv6 node addresses as InternalIPs (this is how kubelet behaves on cloud providers, but bare-metal support for this feature is still a work in progress)

I installed cilium using the command:

```
helm install cilium cilium/cilium --version 1.8.0 \
--namespace kube-system \
--set global.ipv6.enabled=true \
--set global.tunnel=disabled \
--set global.autoDirectNodeRoutes=true \
--set global.nativeRoutingCIDR=10.145.0.0/16 \
--set config.ipam=cluster-pool \
--set global.ipam.operator.clusterPoolIPv4PodCIDR=10.145.0.0/16 \
--set global.ipam.operator.clusterPoolIPv6PodCIDR=fd00:abba:96fb::/104
```

The nginx service is declared as follow:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 81.201.186.64
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: nginx6
  annotations:
    metallb.universe.tf/address-pool: ipv6
spec:
  ipFamily: IPv6
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 2a02:2218:100:1:1eaf::10
  externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.18.0
        ports:
        - containerPort: 80
```
