### ISSUE TITLE
What is difference between Host-Reachable Services and Container HostPort

### ISSUE THREAD

**Issue by soumynathan** [cilium/cilium#12347]
## Support

What is the difference between Host-Reachable Services and Container HostPort?

While I was going through the documentation i had this question.

If they are different, it would make sense to add an Example for 'Host-Reachable Services'. 
If they are the same, then provide a note or link in the "Host-Reachable Services" to the Container HostPort Example.

**Comment by soumynathan** [comment]
Ok, so the Host-Reachable Services is the direct use of host network for the service without any nodeport which can be achieved by 'hostNetwork: true' enablement for the pod/service.

So adding an example in the documentation would be helpful.

```
:~$ kubectl exec -it -n kube-system cilium-6wbn4 -- cilium status | grep KubeProxyReplacement
KubeProxyReplacement:   Probe   [ens3 (DR)]   [NodePort (SNAT, 30000-32767, XDP: DISABLED), HostPort, ExternalIPs, HostReachableServices (TCP, UDP), SessionAffinity]
```

Example yaml for the app.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      hostNetwork: true
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
```
After this run this command to see the IP Address assigned to the pod.

```
#kubectl get pods -o wide
NAME                        READY   STATUS    RESTARTS   AGE     IP                NODE            NOMINATED NODE   READINESS GATES
my-nginx-694b8667c5-rv9mf   1/1     Running   0          4m32s   192.168.122.133   worker1   <none>           <none>

```
Make sure the IP is assigned as the node IP address and the App/Pod can be directly accessed using the IP.

You can test it as shown.
```
:~$ curl http://192.168.122.133
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
</html>
```
