### ISSUE TITLE
Issues with dns "Timeout waiting for response to forwarded proxied DNS lookup" after enabling dns visibility

### ISSUE THREAD

**Issue by weikinhuang** [cilium/cilium#12503]
## Bug report

I'm seeing general issues with dns after enabling the tofqdn-dns-visibility.

Asked for help here: https://cilium.slack.com/archives/C1MATJ5U5/p1594496566463000, but unable to solve it.

**General Information**

- Cilium version: `v1.8.1`
- Kernel version: `Linux n002 5.4.0-41-generic #45-Ubuntu SMP Fri Jul 3 10:57:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use: `v1.18.5`
- Baremetal cluster running ubuntu 20.04
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

Setup cilium with helm with the following values.yaml
```
agent:
  enabled: true
config:
  enabled: true
operator:
  enabled: true
global:
  identityAllocationMode: crd
  ipv4:
    enabled: true
  ipv6:
    enabled: false
  debug:
    enabled: false
  prometheus:
    enabled: true
    port: 9090
    serviceMonitor:
      enabled: true
  operatorPrometheus:
    enabled: true
  cni:
    chainingMode: none
    customConf: false
  cluster:
    name: default
  tunnel: "vxlan"
  containerRuntime:
    integration: none
  bpf:
    monitorAggregation: medium
  kubeProxyReplacement: "probe"
  hostServices:
    enabled: true
    protocols: tcp,udp
  nodePort:
    enabled: true
    bindProtection: true
    autoProtectPortRange: true
  hostPort:
    enabled: true
  externalIPs:
    enabled: true
  ipvlan:
    enabled: false
  k8s:
    requireIPv4PodCIDR: true
  nodeinit:
    enabled: false
  psp:
    enabled: true
  hubble:
    enabled: true
    ui:
      enabled: true
    listenAddress: ":4244"
    metrics:
      enabled:
        - dns:query;ignoreAAAA
        - drop
        - tcp
        - flow
        - port-distribution
        - icmp
        - http
      serviceMonitor:
        enabled: true
    relay:
      enabled: true
  ipam:
    operator:
      clusterPoolIPv4PodCIDR: "10.2.0.0/16"
      clusterPoolIPv4MaskSize: 24
      clusterPoolIPv6PodCIDR: "fd00::/104"
      clusterPoolIPv6MaskSize: 120
```

Generated configmap
```
apiVersion: v1
data:
  auto-direct-node-routes: "false"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  cluster-name: default
  cluster-pool-ipv4-cidr: 10.2.0.0/16
  cluster-pool-ipv4-mask-size: "24"
  debug: "false"
  disable-cnp-status-updates: "true"
  enable-auto-protect-node-port-range: "true"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "true"
  enable-endpoint-health-checking: "true"
  enable-host-reachable-services: "true"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-metrics: "true"
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  hubble-listen-address: :4244
  hubble-metrics: dns:query;ignoreAAAA drop tcp flow port-distribution icmp http
  hubble-metrics-server: :9091
  hubble-socket-path: /var/run/cilium/hubble.sock
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  ipam: cluster-pool
  k8s-require-ipv4-pod-cidr: "true"
  k8s-require-ipv6-pod-cidr: "false"
  kube-proxy-replacement: probe
  masquerade: "true"
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: :6942
  preallocate-bpf-maps: "false"
  prometheus-serve-addr: :9090
  sidecar-istio-proxy-image: cilium/istio_proxy
  tofqdns-enable-poller: "false"
  tunnel: vxlan
  wait-bpf-mount: "false"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: cilium-cni
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2020-07-09T23:36:09Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cilium-config
  namespace: kube-system
```

Using coredns, apply the `tofqdn-dns-visibility` policy:
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  labels:
    cluster.kubernetes.io/name: tofqdn-dns-visibility
    cluster.kubernetes.io/component: networkpolicy
    cluster.kubernetes.io/managed-by: system
    cluster.kubernetes.io/part-of: cluster
    networking.k8s.io/class: global
  name: tofqdn-dns-visibility
  namespace: {{ $ns.name }}
spec:
  endpointSelector: {}
  egress:
  - toEndpoints:
    - matchLabels:
       k8s:io.kubernetes.pod.namespace: kube-system
       k8s:k8s-app: kube-dns
    - matchLabels:
       k8s:io.kubernetes.pod.namespace: kube-system
       k8s-app: coredns
    toPorts:
      - ports:
         - port: "53"
           protocol: ANY
        rules:
          dns:
            - matchPattern: "*"
```

When tailing cilium, I'm seeing an enormous amount of logs similar to:
```
level=warning msg="Timeout waiting for response to forwarded proxied DNS lookup" DNSRequestID=11479 dnsName=elasticsearch-master.logging.svc.cluster.local. endpointID=478 error="read udp 10.2.4.252:61002->10.2.2.231:53: i/o timeout" ipAddr="10.2.4.75:42609" subsys=fqdn/dnsproxy
```

Checking with `cilium monitor -t drop`:

```
xx drop (No mapping for NAT masquerade) flow 0xbcae5969 to endpoint 0, identity 0->0: 10.2.4.252:43838 -> 10.2.2.231:53 udp
xx drop (No mapping for NAT masquerade) flow 0xa5145c1a to endpoint 0, identity 0->0: 10.2.4.252:42354 -> 10.2.2.231:53 udp
xx drop (No mapping for NAT masquerade) flow 0xc43745ca to endpoint 0, identity 0->0: 10.2.4.252:38430 -> 10.2.2.231:53 udp
xx drop (No mapping for NAT masquerade) flow 0xa25c72eb to endpoint 0, identity 0->0: 10.2.4.252:43351 -> 10.2.2.231:53 udp
xx drop (No mapping for NAT masquerade) flow 0xc3840bbb to endpoint 0, identity 0->0: 10.2.4.252:42694 -> 10.2.2.231:53 udp
xx drop (No mapping for NAT masquerade) flow 0xc644db96 to endpoint 0, identity 0->0: 10.2.4.252:65404 -> 10.2.2.231:53 udp
xx drop (No mapping for NAT masquerade) flow 0x2da04aed to endpoint 0, identity 0->0: 10.2.4.252:45845 -> 10.2.2.231:53 udp
xx drop (No mapping for NAT masquerade) flow 0x39fa1689 to endpoint 0, identity 0->0: 10.2.4.252:64869 -> 10.2.2.231:53 udp
xx drop (No mapping for NAT masquerade) flow 0xe6a4189 to endpoint 0, identity 0->0: 10.2.4.252:45080 -> 10.2.2.231:53 udp
xx drop (No mapping for NAT masquerade) flow 0x6e9e0ca2 to endpoint 0, identity 0->0: 10.2.4.252:49402 -> 10.2.2.231:53 udp
xx drop (No mapping for NAT masquerade) flow 0xc87efc1 to endpoint 0, identity 0->0: 10.2.4.252:59803 -> 10.2.2.231:53 udp
```

where `10.2.2.231` is the coredns pod
```
kube-system             coredns-5bd54647dc-597mn                                      1/1     Running     0          3h7m    10.2.2.231
```
