### ISSUE TITLE
Cilium does not correlate endpoints with service

### ISSUE THREAD

**Issue by kvaster** [cilium/cilium#12513]
Cilium does not correlate endpoins with service when endpoints are manager 'manually' (i.e. by operator). Bug was found when I was experimenting with zolando postgresql operator - operator creates service without selector and later creates endpoint to postgresql master. And it's ok for kubernetes according to [docs](https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors).

- Cilium version
Client: 1.8.1 5ce2bc7b3 2020-07-02T20:04:47+02:00 go version go1.14.4 linux/amd64
Daemon: 1.8.1 5ce2bc7b3 2020-07-02T20:04:47+02:00 go version go1.14.4 linux/amd64

- Kernel version - Linux k8s-1 5.7.0-gentoo #1 SMP PREEMPT Wed Jun 3 18:34:14 -00 2020 x86_64 Intel Core Processor (Skylake, IBRS) GenuineIntel GNU/Linux

- Orchestration system version in use:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"archive", BuildDate:"2020-07-13T10:27:10Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

[cilium-sysdump-20200713-175126.zip](https://github.com/cilium/cilium/files/4913231/cilium-sysdump-20200713-175126.zip)

**How to reproduce the issue**

1. Create test service without selector:

```
kind: Pod
apiVersion: v1
metadata:
  name: test-app
  labels:
    app: test
spec:
  containers:
    - name: test-app
      image: hashicorp/http-echo
      args:
        - "-text=test"
---
kind: Service
apiVersion: v1
metadata:
  name: test-service
spec:
  ports:
    - port: 5678 # Default port for image
```

2. Wait for service and app to start, retrieve current pod ip and create endpoint:

```
kind: Endpoints
apiVersion: v1
metadata:
  name: test-service
  namespace: default
subsets:
  - addresses:
    - ip: <POD IP>
    ports:
      - port: 5678
        protocol: TCP
```

3. Get test-service endpoints with kubectl - our endpoint will be available:

```
kubectl get endpoints test-service
NAME           ENDPOINTS           AGE
test-service   10.244.3.167:5678   8m27s
```

4. Run `cilium bpf lb list` - there will be NO ip of our service. As a result you're not able to connect to service on 5678 port.

**Comment by kvaster** [comment]
It seems that there is no k8s pod name defined for such endpoint. I can see following message in logs:

```
Skipping CiliumEndpoint update because it has no k8s pod name
```

**Comment by brb** [comment]
@kvaster Thanks for the report. Do you plan to work on this?

**Comment by kvaster** [comment]
I'm trying to investigate a problem right now, but will have to spend some time to learn internals. At least dev environment is working and problem is reproduced in vbox vagrant.

**Comment by kvaster** [comment]
Problem is related to endpoint slices. With enable-k8s-endpoint-slice: 'false' it works. It seems that k8s does not send such endpoint updates in slice mode.

**Comment by kvaster** [comment]
Seems this is not cilium bug. This is kubernetes bug. `kubectl get endpoitslices` have no corresponding resources to endpoint created manually.

**Comment by joestringer** [comment]
@kvaster do you need to create an `endpointslice` resource instead of an `endpoint` resource in that case?

**Comment by brb** [comment]
@kvaster Thanks for the update. Have you verified that the issue is fixed with k8s 1.19? Anyway, closing this issue as it's unrelated to Cilium.

**Comment by kvaster** [comment]
Verified with 1.19.0 kubernetes - it works !

**Comment by LeoQuote** [comment]
Hi, I'm expirencing this issue recently, but a bit different. If the endpoint is **outside the cluster** , the service will be working well, but if the endpoints is **inside the cluster** , like the kube-controller-manager and the endpoint is using the host ip , the service will fail.

```
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-controller-manager
  labels:
    k8s-app: kube-controller-manager
spec:
  ports:
  - name: https-metrics
    port: 10257
    targetPort: 10257
    protocol: TCP

---

apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: kube-controller-manager
  name: kube-controller-manager
  namespace: kube-system
subsets:
  - addresses:
     # these three ips are the k8s node ip that where kube-controller-manager are run
      - ip: 10.1.32.30
      - ip: 10.1.32.40
      - ip: 10.1.32.43
    ports:
    - name: https-metrics
      port: 10257
      protocol: TCP
```


I wonder how did you find the root cause , what can I do to solve this problem?
