### ISSUE TITLE
Cilium 1.8.1 CNI mode in EKS, pod scheduled to the nodes with 0 allocate-able IPs.

### ISSUE THREAD

**Issue by wizard580** [cilium/cilium#12557]
**General Information**

- Cilium version: 1.8.1
- Kernel version: idk, one provided by EKS.
- Orchestration system version in use: Kubernetes 1.16.x (latest in EKS for 1.16)

**How to reproduce the issue**

Makefile
```
.PHONY: help bootstrap-cluster remove-aws-node-ds deploy-cilium build-nodegroups
.DEFAULT_GOAL := start-cluster
ARGS = $(filter-out $(firstword $(MAKECMDGOALS)), $(MAKECMDGOALS))

TESTEKSCTL=awsudo -u profile eksctl
TESTKUBECTL=awsudo -u profile kubectl
HELM=awsudo -u profile helm3 

# start a cluster with zero nodes, working master, reuse previous terraform created subnets
bootstrap-cluster:
	$(TESTEKSCTL) create cluster --name test --without-nodegroup \
		--vpc-private-subnets=subnet-xxx,subnet-yyy,subnet-zzz\
		--vpc-public-subnets=subnet-qqq,subnet-www,subnet-eee

# remove the AWS CNI
remove-aws-node-ds:
	$(TESTKUBECTL) -n kube-system delete daemonset aws-node

# deploy Cilium via helm chart, pods will be in Pending state
deploy-cilium:
	$(HELM) repo add cilium https://helm.cilium.io/
	$(HELM) install cilium cilium/cilium --version 1.8.1 \
		--namespace kube-system \
		--set global.eni=true \
		--set config.ipam=eni \
		--set global.egressMasqueradeInterfaces=eth0 \
		--set global.tunnel=disabled \
		--set global.nodeinit.enabled=true \
		--set global.hubble.enabled=true \
		--set global.hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,http}"

build-nodegroups: update-cluster

start-cluster: bootstrap-cluster remove-aws-node-ds deploy-cilium build-nodegroups

delete-cluster:
	$(TESTEKSCTL) delete cluster --name test

# enable nodegroups, pods will reach Running state, enable flux and any additional cluster.yaml config
update-cluster:
	$(TESTEKSCTL) create nodegroup --config-file ./cluster.yaml
	$(TESTEKSCTL) update cluster --config-file ./cluster.yaml
	$(TESTEKSCTL) enable repo --config-file ./cluster.yaml

```

cluster.yaml
```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test
  region: eu-central-1

vpc:
  subnets:
    private:
      eu-central-1a: { id: subnet-xxx}
      eu-central-1b: { id: subnet-yyy}
      eu-central-1c: { id: subnet-zzz}
    public:
      eu-central-1a: { id: subnet-qqq}
      eu-central-1b: { id: subnet-www}
      eu-central-1c: { id: subnet-eee}
  nat:
    gateway: HighlyAvailable
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  publicAccessCIDRs: ["xxx/32", "ccc/32", "vvv/32", ...]

nodeGroups:
  - name: node-group-base
    labels: { role: nodes-base }
    instanceType: t3.medium
    desiredCapacity: 3
    privateNetworking: true
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
    asgMetricsCollection:
      - granularity: 1Minute
        metrics:
          - GroupMinSize
          - GroupMaxSize
          - GroupDesiredCapacity
          - GroupInServiceInstances
          - GroupPendingInstances
          - GroupStandbyInstances
          - GroupTerminatingInstances
          - GroupTotalInstances

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]

git:
  repo:
    url: "git@gitlab.com:mypath/ekstest.git"
    branch: master
    fluxPath: "flux/"
    user: "flux"
    email: "admin@domain.com"
  operator:
    namespace: "flux"
    withHelm: true
```

when all 3 nodes have enough resources and allocate-able IPs everything works fine.
What we did - installed tiny Grafana+Prometheus stack and connectivity checks from examples on your site (tried with kafka examples as well).
Some pods were in constant container creating state . 

We checked with kubectl describe pods XXX and found messages:
```
Warning  FailedCreatePodSandBox  70s (x4 over 76s)   kubelet, ip-172-19-31-197.eu-central-1.compute.internal  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "10b1949374c284791a6eec9209dc31e7c5b4f1ed5e74cd13f0f8da6eb89d92b1" network for pod "empire-outpost-9999-f6f4c5867-2bwr2": networkPlugin cni failed to set up pod "empire-outpost-9999-f6f4c5867-2bwr2_default" network: unable to allocate IP via local cilium agent: [POST /ipam][502] postIpamFailure  No more IPs available
```

Next step we did - check the nodes for such failing pods with kubectl describe node XXX and we saw that node had 17 running pods (t3.medium can host 3x6 - 1 pod)... and new pod was scheduled to the node which can't host it. It was kind of deadlock.

After that we extended our nodes pool to 4 nodes... Pod with issues wasn't re-scheduled. It was keeping try to start on the node where it couldn't start. All other pods which were in pending state - started on new node. 

Then I just deleted those stuck pods. They were re-scheduled to the new node and started without issues. 

I see this as critical blocker for Cilium in any EKS environment (not sure about others) at least with same K8S version and EC2 instance type/size.
