### ISSUE TITLE
Some backend of cluster IPs never gets picked

### ISSUE THREAD

**Issue by Weil0ng** [cilium/cilium#12609]
## Bug report

**General Information**

- Cilium version (run `cilium version`): 
Client: 1.8.0 bfda356ab 2020-07-14T14:55:21-07:00 go version go1.14.4 linux/amd64
Daemon: 1.8.0 bfda356ab 2020-07-14T14:55:21-07:00 go version go1.14.4 linux/amd64

- Kernel version (run `uname -a`)
Linux gke-test-default-pool-31018309-mqh4 4.19.112+ #1 SMP Thu May 21 12:32:19 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.8-gke.16", GitCommit:"39e5210b77df372ed214a56b84af65e7ee0fb8dc", GitTreeState:"clean", BuildDate:"2020-07-10T00:42:05Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)
Yaml to reproduce issue:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
        name: server
        labels:
                role: server
                app: MyApp
spec:
        containers:
        - name: nginx
          image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: curl-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 88
      targetPort: 80
```

- Generate and upload a system zip: shared offline on slack
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. Apply provided yaml
2. curl from server pod to curl-service:88
3. monitor connections
