### ISSUE TITLE
Fresh install on EKS causes coredns failures (Istio + NodeLocalDNS)

### ISSUE THREAD

**Issue by jaygorrell** [cilium/cilium#12631]
## Support

I have an EKS cluster using the official eks-cni plugin and Istio (in case that's relevant) and NodeLocalDNS. In order to keep cluster bootstrapping simple (no manual deletion) I wanted to go with the chaining method and followed the instructions on [this](https://docs.cilium.io/en/v1.8/gettingstarted/cni-chaining-aws-cni/) page exactly.

My helm values look like:
```
        global:
          cni:
            chainingMode: aws-cni
          masquerade: false
          tunnel: disabled
          nodeinit:
            enabled: true
```

After installing this, I noticed my pods couldn't make requests anymore. One thing I did notice is that coredns was in a crash loop. I had to quickly roll back so I didn't get to investigate too deep but I do have most logs available from the pods, and I do see that Cilium tried to restart coredns -- it just never came back up healthy. It might have been failing health checks.

I mention istio because i do have mTLS enabled and it does rewrite liveness probes, but it is not enabled in the kube-system namespace where coredns and cilium exists so I highly doubt it matters.

I'm hoping to make another attempt soon to gather more information if there's anything specific I can check for.

Environment information:
AWS EKS v1.16.8
Cilium v1.8 Helm Chart
Istio 1.5
[NodeLocalDNS](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/)
