### ISSUE TITLE
hubble-relay: Failed to create gRPC client connection to peer context deadline exceeded

### ISSUE THREAD

**Issue by Antiarchitect** [cilium/cilium#12645]
## Bug report

Hubble configuration:
```
cilium:
  enabled: true
  global:
    hubble:
      enabled: true
      ui:
        enabled: true
      listenAddress: ":4244"
      metrics:
        enabled:
        - dns
        - drop
        - tcp
        - flow
        - port-distribution
        - icmp
        - http
      relay:
        enabled: true
```

hubble-relay: for all of nodes - no exceptions:
```
level=warning msg="Failed to create gRPC client connection to peer kube-3.xx.xx.xx; next attempt after 1h30m0s" address="xx.xx.xx.56:4244" error="context deadline exceeded" subsys=hubble-relay
level=warning msg="Failed to create gRPC client connection to peer worker-5.xx.xx.xx; next attempt after 1h30m0s" address="xx.xx.xx.55:4244" error="context deadline exceeded" subsys=hubble-relay
```

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.8.2 aa42034f0 2020-07-23T15:02:39-07:00 go version go1.14.6 linux/amd64
Daemon: 1.8.2 aa42034f0 2020-07-23T15:02:39-07:00 go version go1.14.6 linux/amd64
```

- Kernel version (run `uname -a`) (all nodes)
```
5.7.9-1.el7.elrepo.x86_64
```

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:03Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```
https://gofile.io/d/GTuJGW
