### ISSUE TITLE
Timeouts on EKS with Istio Ingress Gateway

### ISSUE THREAD

**Issue by jaygorrell** [cilium/cilium#12647]
## Support

I have an EKS cluster using the official eks-cni plugin and Istio with mTLS. In order to keep cluster bootstrapping simple (no manual deletion) I wanted to go with the chaining method and followed the instructions on [this](https://docs.cilium.io/en/v1.8/gettingstarted/cni-chaining-aws-cni/) page exactly.

My helm values look like:
```
        global:
          cni:
            chainingMode: aws-cni
          masquerade: false
          tunnel: disabled
          nodeinit:
            enabled: true
```

After installing I restarted the Istio Ingress Gateway pods as well as a couple services behind them. At first I was getting timeouts (or "headers sent before response" errors) but then it started to occasionally work. Sometimes it would be an instant response, sometimes it would be a couple seconds delay, and most often it would still time out.

The interesting thing is if I put a `LoadBalancer` service on any of these systems, they responded 100% normally, so this is isolated to the ingress-gateway. Without Cilium, these function with ingress-gateway normally.

Environment information:
AWS EKS v1.16.8
Cilium v1.8.1 Helm Chart
Istio 1.5
