### ISSUE TITLE
Unable to have connectivity on GKE from control plane to pods with kube-proxy replacement enabled

### ISSUE THREAD

**Issue by hightoxicity** [cilium/cilium#12679]
## Support

Hi,

We have cilium 1.8.1 deployed into a private GKE cluster and we have some admissions webhooks + control plane that can not reach a pod IP, this is also the case from metrics server that is in-box with GKE.
The control plane is setup on 172.16.0.0/28 (managed by GKE), nodes on 10.1.0.0/20 and pods on 10.233.64.0/18, firewall rules (GCP fw rules) are setup from the control plane subnet to be able to reach all the previous targeted ports on host VPC subnetwork.

The workaround I use to have admission webhooks working consists in setting target webhooks pods on host net then control plane can reach the node IP + port, but I have no workaround for metrics server since its spec is managed by GKE.

Without talking about Cilium, reacheability is fixed only by a FW rule in GCP, look at:

https://github.com/kubernetes/kubernetes/issues/79739

They say that Google is using --enable-aggregator-routing=true to resolve endpoints IP directly so it is something expected that the control plane can talk to pods in GKE.

With cilium, It seems that something is preventing control plane (172.16.0.0/28) to talk to my pod subnet (10.233.64.0/18), is it something blocked by design into Cilium or shall I have to configure something to allow that?

Great thanks.

**Comment by hightoxicity** [comment]
Here is some details about my cilium helm deployment:

```
cilium:
  enabled: true
  config:
    ipam: kubernetes
  global:
    # prometheus enables
    prometheus:
      enabled: true
      port: 9092
      serviceMonitor:
        enabled: true
    # operatorPrometheus enables
    operatorPrometheus:
      enabled: true
      port: 6942
    hostServices:
      enabled: true
      protocols: tcp
    cni:
      binPath: /home/kubernetes/bin
    gke:
      enabled: true
    nativeRoutingCIDR: 10.233.64.0/18
    nodeinit:
      enabled: true
    psp:
      enabled: true
    hubble:
      enabled: true
      ui:
        enabled: true
      relay:
        enabled: true
      metrics:
        enabled:
        - dns:query;ignoreAAAA
        - drop
        - tcp
        - flow
        - port-distribution
        - icmp
        - http
        port: 9095
        serviceMonitor:
          enabled: true
  nodeinit:
    reconfigureKubelet: true
    removeCbrBridge: true

```
