### ISSUE TITLE
Enabling `--enable-bpf-masquerade` with `enable-host-services=false` when using kube-proxy prevents connectivity to ClusterIP services from remote hosts

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#12699]
### Summary

When Cilium is configured with kube-proxy, `hostNetwork` pods (or applications on hosts) cannot establish connectivity with pods on remote nodes via ClusterIP. Regular pods are not affected by this issue.

### Environment

- Cilium v1.8.2
  - Using kube-proxy
- Kernel 5.4
- Kubernetes v1.17 via KIND v0.7.0

### How to reproduce the issue

1. Create 2-node KIND cluster from cilium git tree using `kind create cluster --config=.github/kind-config.yaml`
1. Load Cilium via these instructions: 
   https://github.com/cilium/cilium/blob/0a4f34a7d75bf99ebe301dd5ef529b03d19b4e35/.github/workflows/smoke-test.yaml#L126-L143
   (I later modified the image manually to v1.8.2 but you can `docker pull ...` + `kind load docker-image ...` to preload specific versions)
1. Deploy connectivity check YAML 
1. Edit the host-to-echo-b-clusterip deployment via `kubectl edit deploy host-to-b-multi-node-clusterip`
   * Replace `livenessProbe` with `readinessProbe`
1. Observe that the new pod created for this deployment never becomes ready

### Symptoms

Source node sees SYN go out to the remote pod via the overlay:

```
root@kind-control-plane:/home/cilium# cilium monitor
...
-> overlay flow 0x88ee9aa7 identity 6->0 state new ifindex cilium_vxlan orig-ip 0.0.0.0: 172.17.0.3:28440 -> 10.244.1.175:80 tcp SYN
```

Destination node (`kind-worker`) sees the SYN, passes to pod, which responds with a SYN-ACK. This gets passed to the stack:
```
root@kind-worker:/home/cilium# cilium monitor
...
-> endpoint 351 flow 0xfd614d2c identity 6->13896 state new ifindex lxccc74c557b238 orig-ip 172.17.0.3: 172.17.0.3:29228 -> 10.244.1.175:80 tcp SYN
-> stack flow 0xeac287bd identity 13896->6 state reply ifindex 0 orig-ip 0.0.0.0: 10.244.1.175:80 -> 172.17.0.3:29228 tcp SYN, ACK
```

With `tcpdump` at the destination node (`kind-worker`), we see that the response is being SNAT'd to the node's IP:

```
# tcpdump -nvei eth0 | grep  172.17.0.3
...
    172.17.0.3.50507 > 10.244.1.175.80: Flags [S], cksum 0xb8e5 (incorrect -> 0x36d2), seq 2626802039, win 64240, options [mss 1460,sackOK,TS val 3387777011 ecr 0,nop,wscale 7], length 0
...
    172.17.0.2.57629 > 172.17.0.3.50507: Flags [S.], cksum 0x5856 (incorrect -> 0x72a4), seq 2606385031, ack 2626802040, win 64308, options [mss 1410,sackOK,TS val 901524270 ecr 3387777011,nop,wscale 7], length 0
```

### Mitigation

I manually modified the `cilium-config` ConfigMap to configure `enable-bpf-masquerade: "false"` then restarted Cilium pods, and the connectivity check started working.

**Comment by joestringer** [comment]
@brb Should we be disabling bpf-based masquerade when using kube-proxy to prevent issues like this?

**Comment by joestringer** [comment]
There may be some simple answers here, like requiring `enable-host-services` if `enable-bpf-masquerade` is enabled.

**Comment by brb** [comment]
Does KIND create two interfaces on each node (one with a default route, one for communication between nodes)?

**Comment by joestringer** [comment]
[cilium-sysdump-20200728-181418.zip](https://github.com/cilium/cilium/files/4995723/cilium-sysdump-20200728-181418.zip)

**Comment by joestringer** [comment]
Whatever solution we decide, we should consider updating the kind install parameters to ensure they're simplified (along with the smoke tests): https://docs.cilium.io/en/latest/gettingstarted/kind

**Comment by networkop** [comment]
I've come across a similar-looking issue on a self-managed cluster. The cluster is built (using kubespray) on top of Azure but has cloud-provider disabled. API-server pods are running as static pods in host OS namespace on 3 controller nodes. 
Every time a pod (e.g. ingress controller) wants to communicate with the API server, it sends a packet to its clusterIP. The packets get picked up by cilium and DNAT'ed to one of the node IPs.
```
16   10.0.128.1:443         ClusterIP      1 => 10.0.255.10:6443
                                           2 => 10.0.255.6:6443
                                           3 => 10.0.255.7:6443
```

However, when the packet hits the node's stack, it's source IP is still the IP of the POD (10.0.7.117)
```
root@node-1:~# tcpdump -i any host 10.0.7.117
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
13:49:27.862772 IP 10.0.7.117.34906 > 10.0.255.6.6443: Flags [S], seq 2746917916, win 42300, options [mss 1410,sackOK,TS val 3319336610 ecr 0,nop,wscale 8], length 0
13:49:28.891100 IP 10.0.7.117.34906 > 10.0.255.6.6443: Flags [S], seq 2746917916, win 42300, options [mss 1410,sackOK,TS val 3319337638 ecr 0,nop,wscale 8], length 0
13:49:30.906961 IP 10.0.7.117.34906 > 10.0.255.6.6443: Flags [S], seq 2746917916, win 42300, options [mss 1410,sackOK,TS val 3319339654 ecr 0,nop,wscale 8], length 0
13:49:35.163173 IP 10.0.7.117.34906 > 10.0.255.6.6443: Flags [S], seq 2746917916, win 42300, options [mss 1410,sackOK,TS val 3319343910 ecr 0,nop,wscale 8], length 0
```

So it leaves the VM nic with its original IP which is not known by Azure SDN and gets dropped by it.

Here's our `cilium-config` cm (sorry I couldn't find the helm values)

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
data:
  # Identity allocation mode selects how identities are shared between cilium
  # nodes by setting how they are stored. The options are "crd" or "kvstore".
  # - "crd" stores identities in kubernetes as CRDs (custom resource definition).
  #   These can be queried with:
  #     kubectl get ciliumid
  # - "kvstore" stores identities in a kvstore, etcd or consul, that is
  #   configured below. Cilium versions before 1.6 supported only the kvstore
  #   backend. Upgrades from these older cilium versions should continue using
  #   the kvstore by commenting out the identity-allocation-mode below, or
  #   setting it to "kvstore".
  identity-allocation-mode: crd

  # If you want to run cilium in debug mode change this value to true
  debug: "false"

  # Enable IPv4 addressing. If enabled, all endpoints are allocated an IPv4
  # address.
  enable-ipv4: "true"

  # Enable IPv6 addressing. If enabled, all endpoints are allocated an IPv6
  # address.
  enable-ipv6: "false"
  enable-bpf-clock-probe: "true"

  # If you want cilium monitor to aggregate tracing for packets, set this level
  # to "low", "medium", or "maximum". The higher the level, the less packets
  # that will be seen in monitor output.
  monitor-aggregation: medium

  # The monitor aggregation interval governs the typical time between monitor
  # notification events for each allowed connection.
  #
  # Only effective when monitor aggregation is set to "medium" or higher.
  monitor-aggregation-interval: 5s

  # The monitor aggregation flags determine which TCP flags which, upon the
  # first observation, cause monitor notifications to be generated.
  #
  # Only effective when monitor aggregation is set to "medium" or higher.
  monitor-aggregation-flags: all
  # bpf-policy-map-max specified the maximum number of entries in endpoint
  # policy map (per endpoint)
  bpf-policy-map-max: "16384"
  # Specifies the ratio (0.0-1.0) of total system memory to use for dynamic
  # sizing of the TCP CT, non-TCP CT, NAT and policy BPF maps.
  bpf-map-dynamic-size-ratio: "0.0025"

  # Pre-allocation of map entries allows per-packet latency to be reduced, at
  # the expense of up-front memory allocation for the entries in the maps. The
  # default value below will minimize memory usage in the default installation;
  # users who are sensitive to latency may consider setting this to "true".
  #
  # This option was introduced in Cilium 1.4. Cilium 1.3 and earlier ignore
  # this option and behave as though it is set to "true".
  #
  # If this value is modified, then during the next Cilium startup the restore
  # of existing endpoints and tracking of ongoing connections may be disrupted.
  # This may lead to policy drops or a change in loadbalancing decisions for a
  # connection for some time. Endpoints may need to be recreated to restore
  # connectivity.
  #
  # If this option is set to "false" during an upgrade from 1.3 or earlier to
  # 1.4 or later, then it may cause one-time disruptions during the upgrade.
  preallocate-bpf-maps: "false"

  # Regular expression matching compatible Istio sidecar istio-proxy
  # container image names
  sidecar-istio-proxy-image: "cilium/istio_proxy"

  # Encapsulation mode for communication between nodes
  # Possible values:
  #   - disabled
  #   - vxlan (default)
  #   - geneve
  tunnel: vxlan

  # Name of the cluster. Only relevant when building a mesh of clusters.
  cluster-name: default

  # wait-bpf-mount makes init container wait until bpf filesystem is mounted
  wait-bpf-mount: "false"

  masquerade: "true"
  # (Michael) workaround for https://github.com/cilium/cilium/issues/12699
  enable-bpf-masquerade: "false"
  enable-xt-socket-fallback: "true"
  install-iptables-rules: "true"
  auto-direct-node-routes: "false"
  kube-proxy-replacement:  "strict"
  enable-health-check-nodeport: "true"
  node-port-bind-protection: "true"
  enable-auto-protect-node-port-range: "true"
  enable-session-affinity: "true"
  enable-endpoint-health-checking: "true"
  enable-well-known-identities: "false"
  enable-remote-node-identity: "true"
  operator-api-serve-addr: "127.0.0.1:9234"
  # Enable Hubble gRPC service.
  enable-hubble: "true"
  # UNIX domain socket for Hubble server to listen to.
  hubble-socket-path:  "/var/run/cilium/hubble.sock"
  # An additional address for Hubble server to listen to (e.g. ":4244").
  hubble-listen-address: ""
  ipam: "kubernetes"
  disable-cnp-status-updates: "true"
  
  # (Michael) workaround for https://github.com/cilium/cilium/issues/10627
  blacklist-conflicting-routes: "false"
```

**Comment by brb** [comment]
@networkop Thanks for the report. It looks that your issue seems to be unrelated to the issue discussed here, as in your case you have `enable-host-services=true` because of `kube-proxy-replacement=true`. So, I'd suggest to open a separate issue.

> However, when the packet hits the node's stack, it's source IP is still the IP of the POD (10.0.7.117)

The BPF-based masquerading happens on TC egress of the native device, so it's expected that in tcpdump output you will see the pod IP addr. If you run `tcpdump -i any -n 'host 10.0.255.10 or host 10.0.255.6 or 10.0.255.7'`, you should be able to see two traces per request - one with the pod IP addr, and one with the native device IP addr (after SNAT).

**Comment by brb** [comment]
I managed to reproduce the original issue on non-KIND env. As a temporary mitigation, I'm going to create a PR to disable BPF-based masq if the host-reachable svc feature is disabled incl. all details why it's currently broken.

**Comment by claneys** [comment]
Hi,

Quite a long time since no update in this issue, but I ran into the same issue, or pretty much. As the cilium's configuration evolve, I assume that enable-bpf-masquerade flag is now enable-ipv4-masquerade and enable-ipv6-masquerade. My setup do not uses kube-proxy and I have the masquerade enabled when I hit the issue when I try by example to resolve a hostname from a Pod with `hostNetwork: true`.

Here my pod yaml and cilium config map 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  #  namespace: kube-system
spec:
  containers:
  - name: dnsutils
    image: k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
  dnsConfig:
    searches:
      - operators.svc.cluster.local
      - svc.cluster.local
      - cluster.local
  nodeName: gilgamesh.uruk.home
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
```

```yaml
apiVersion: v1
data:
  agent-not-ready-taint-key: node.cilium.io/agent-not-ready
  arping-refresh-period: 30s
  auto-direct-node-routes: "false"
  bpf-lb-external-clusterip: "false"
  bpf-lb-map-max: "65536"
  bpf-lb-sock: "false"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  bpf-root: /sys/fs/bpf
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: "0"
  cluster-name: uruk-cluster
  cluster-pool-ipv4-cidr: 10.0.0.0/8
  cluster-pool-ipv4-mask-size: "24"
  custom-cni-conf: "false"
  debug: "false"
  disable-cnp-status-updates: "true"
  disable-endpoint-crd: "false"
  enable-auto-protect-node-port-range: "true"
  enable-bgp-control-plane: "false"
  enable-bpf-clock-probe: "true"
  enable-endpoint-health-checking: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv4-masquerade: "true"
  enable-ipv6: "false"
  enable-ipv6-masquerade: "true"
  enable-k8s-terminating-endpoint: "true"
  enable-l2-neigh-discovery: "true"
  enable-l7-proxy: "true"
  enable-local-redirect-policy: "false"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-svc-source-range-check: "true"
  enable-vtep: "false"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  hubble-disable-tls: "false"
  hubble-listen-address: :4244
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  install-no-conntrack-iptables-rules: "false"
  ipam: cluster-pool
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: ""
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  nodes-gc-interval: 5m0s
  operator-api-serve-addr: 127.0.0.1:9234
  preallocate-bpf-maps: "false"
  remove-cilium-node-taints: "true"
  set-cilium-is-up-condition: "true"
  sidecar-istio-proxy-image: cilium/istio_proxy
  synchronize-k8s-nodes: "true"
  tofqdns-dns-reject-response-code: refused
  tofqdns-enable-dns-compression: "true"
  tofqdns-endpoint-max-ip-per-hostname: "50"
  tofqdns-idle-connection-grace-period: 0s
  tofqdns-max-deferred-connection-deletes: "10000"
  tofqdns-min-ttl: "3600"
  tofqdns-proxy-response-max-delay: 100ms
  tunnel: vxlan
  unmanaged-pod-watcher-interval: "15"
  vtep-cidr: ""
  vtep-endpoint: ""
  vtep-mac: ""
  vtep-mask: ""
kind: ConfigMap
```

My iptables rules if it matters : 
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-FIREWALL  all  --  0.0.0.0/0            0.0.0.0/0           

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-FIREWALL  all  --  0.0.0.0/0            0.0.0.0/0           

Chain KUBE-FIREWALL (2 references)
target     prot opt source               destination         
DROP       all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000
DROP       all  -- !127.0.0.0/8          127.0.0.0/8          /* block incoming localnet connections */ ! ctstate RELATED,ESTABLISHED,DNAT

Chain KUBE-KUBELET-CANARY (0 references)
target     prot opt source     
```
