### ISSUE TITLE
Host firewall should also be able to block NodePorts

### ISSUE THREAD

**Issue by kilokang** [cilium/cilium#12781]
## Proposal / RFE

**Is your feature request related to a problem?**
When you rent a dedicated server at some company like online.net/scaleway or Hetzner outside they cloud they public your new server to the internet directly without any possibility of any firewall. This means that your servers must communicate using directly public IPs and limit those connections "somehow" in the host.

On these providers you can rent also more public IPs that you can change between servers which (for online.net example) are called failover IPs. To configure and use these IPs I am using MetalLB.

Until now I've been using only mono-node clusters and using iptables to disallow kubelet and any other host service to be public into what I am going to call from now on "management IP" as it is the only way you can do any maintenance to the node.

Here is the issue: Any LoadBalancer is going to be published in the desired port and failover IP by MetalLB at the same time it will open a NodePort at the management IP. That http backend served as a NodePort is also served without any possible auth/connection upgrade made by ingress controller.

**Describe the solution you'd like**
With the new feature of Host Firewall I would like to block Nodeports or any port I need to close.

Here is an example on my lab:

I deployed a caddy to my mono-node cluster which has IP `192.168.0.20` and configured MetalLB to use `192.168.0.200-209` to LoadBalancer service type.
```
% kubectl -n cilium-issue get pod,service,endpoints        
NAME                         READY   STATUS    RESTARTS   AGE
pod/caddy-75584b9449-99tbs   1/1     Running   1          3d21h

NAME            TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)                      AGE
service/caddy   LoadBalancer   172.20.148.187   192.168.0.200   80:31025/TCP,443:32140/TCP   13d

NAME              ENDPOINTS                           AGE
endpoints/caddy   172.20.0.47:8000,172.20.0.47:8443   13d
```
Then I block any traffic from outside the cluster (this works):
```yaml
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
description: ""
metadata:
  name: "allow-cluster-traffic"
  namespace: traefik-system
spec:
  endpointSelector: {}
  ingress:
  - fromEntities:
    - cluster
```
What I would like to have is a way of making a CCNP that allows this endpoint to be reached only by MetalLB IP or to the port I want.

The example below example do not work as caddy is listening to 8000 and 8443 but it represent the destination port as seen as host scope.
```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: ""
metadata:
  name: "allow-ingress"
  namespace: cilium-issue
spec:
  endpointSelector:
    matchLabels:
      k8s:app: caddy
  ingress:
  - toPorts:
    - ports:
      - port: "80"
        protocol: ANY
      - port: "443"
        protocol: ANY
```
Then I run 2 different tests:
```
watch -n3 'echo -n "To MetalLB: "; curl --no-progress-meter -H "Host: caddy.k8s.lab" 192.168.0.200 | wc -l'
watch -n3 'echo -n "To NodePort: "; curl --no-progress-meter -H "Host: caddy.k8s.lab" 192.168.0.20:31025 | wc -l'
```
With the example tests above I would like the first one working and the second one failing.

**Comment by pchaigno** [comment]
To address this, I've been considering a second mode for the host firewall where it would protect the node itself instead of the host network namespace only. In that mode, policies would be enforced for all traffic entering (or leaving) the node regardless of whether it is destined to (resp. coming from) the hostns or a regular pod. Policies would also be enforced before DNAT is applied, so they would apply on k8s services and ports and not their backends.

Such an enforcement mode would be closer to regular software firewalls, but it would be fairly different from how we usually enforce policies in CIlium. The implementation would be simpler though not necessarily more efficient.

**Comment by kang-makes** [comment]
This is still an issue from my side. First I tackled it with a dirty hack using a pod with a shell script.

I don't want in my cluster but Cilium opens (as it is expected from Kubernetes as it the intended behavior). So, as I was learning Go, I created a service that automatically deletes all those endpoints: https://github.com/kang-makes/cilium-nodeport-deleter/tree/main

I am free to check other ways to resolve this while I learn to do a proper PR to this project.

**Comment by elfadel** [comment]
Assigned me, please.

**Comment by kerossin** [comment]
What's the status on this?

We have nodes only with public IPs and generally use iptables with ipsets to restrict traffic but I can't seem to find a way to restrict access to NodePort services, they are reachable by anyone.

I've tried different iptables rules in different chains, CiliumClusterwideNetworkPolicy, different Cilium configurations (with kube-proxy, without kube-proxy, etc.) but nothing works, everything goes through.

**Comment by pchaigno** [comment]
@kerossin All Cilium policies currently apply to backend pods, so it's expected they wouldn't work to block NodePort services directly (but you can block the backends to achieve almost the same). Without kube-proxy, I think it's expected for iptables rules to not work because Cilium then performs DNAT before iptables is reached. With kube-proxy however, I would expect iptables rules to work, assuming they are set before the kube-proxy DNAT rules.

**Comment by kerossin** [comment]
@pchaigno Yes, I've had some misunderstandings on how these policies work and I think more or less I got the hang of it but I wasn't successful in securing my services.

Overall, firewalling with Cilium is currently problematic.

You can't use iptables because of eBPF so you have to rely on what Cilium provides. I got the host firewall working but it's only for host services and I couldn't properly secure NodePort services with network policies. Because of SNAT all incoming traffic looks like it's coming from inside the cluster so external traffic just goes through to the pod. Setting `externalTrafficPolicy` to `Local` on the service gets the traffic restricted but it comes with it's own downsides and it's only for that service so creating a new service and forgetting to change the default leaves you out in the open.

I expected the host firewall to work like your idea mentioned in a previous comment where you could use it properly secure the whole node.

**Comment by kladiv** [comment]
+1 for NodePort security

**Comment by agouin** [comment]
We have this issue also, and it applies to the host ports also. We'd like to lock down the NodePorts, and separately host ports, to a specific CIDR or set of CIDRs.

**Comment by shapirus** [comment]
Since neither iptables (because of eBPF), nor CiliumClusterwideNetworkPolicy work to block NodePort host ports, are there any other alternatives or workarounds without putting another machine in front of the host that has the NodePort open?

It's a real bummer. Dropping packets matching a very simple rule has always been the most trivial task, and now, with Cilium, it can no longer be done.

**Comment by Cajga** [comment]
I believe that this ticket is obsolete. With host firewall enabled, it is indeed possible to block a NodePorts type service port.

For example, we have the following rule that only allows the prometheus server to reach the kube-state-metrics nodeport:
```yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: prometheus-to-kube-state-metrics-nodeport
spec:
  # apply to worker nodes only
  nodeSelector:
    matchLabels:
      noderole: 'worker'
  ingress:
    - fromCIDR:
      - 192.168.1.5/32
      toPorts:
      # kube-state-metrics nodeport
      - ports:
        - port: '32767'
          protocol: TCP

```

**Comment by Cajga** [comment]
I believe that this ticket is obsolete. With host firewall enabled, it is indeed possible to block a NodePorts type service port.

For example, we have the following rule that only allows our external prometheus server to reach the kube-state-metrics nodeport:
```yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: prometheus-to-kube-state-metrics-nodeport
spec:
  # apply to worker nodes only
  nodeSelector:
    matchLabels:
      noderole: 'worker'
  ingress:
    - fromCIDR:
      - 192.168.1.5/32
      toPorts:
      # kube-state-metrics nodeport
      - ports:
        - port: '32767'
          protocol: TCP
```

**Comment by shapirus** [comment]
@Cajga your example does the opposite: it allows the specified port, whereas this ticket is about blocking a specific port on the host, which is also a nodePort of a Service.

my example is this:

```
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "block-aws-healthcheck"
spec:
  description: "block AWS NLB healthchecks for quick targets deregistering"
  nodeSelector:
    matchLabels:
      block-aws-healthcheck: "true"
  ingressDeny:
  - toPorts:
    - ports:
      - port: "30876"
        protocol: TCP
```

This blocks everything _except_ port 30876 to which a nodePort service is bound.
