### ISSUE TITLE
Egress policy to Kubernetes service port

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#1299]
Hi,

I'm running a slightly modified version of the minikube demo app where the service port is different from the container port:

```
diff --git a/examples/minikube/demo.yaml b/examples/minikube/demo.yaml
index 0412996..f1b1bc1 100644
--- a/examples/minikube/demo.yaml
+++ b/examples/minikube/demo.yaml
@@ -5,7 +5,8 @@ metadata:
   name: app1-service
 spec:
   ports:
-  - port: 80
+  - port: 8080
+    targetPort: 80
   selector:
     id: app1
 ---
```

and I'm trying to define an egress policy to allow traffic to the service port:

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: my-policy
specs:
  - endpointSelector:
      matchLabels: {}
    egress:
      - toPorts:
          - ports:
              - port: '8080'
                protocol: TCP
            rules: {}
```

but packets are getting dropped when I do `kubectl exec $APP2_POD -- curl $SVC_IP:8080 -s`:

```
root@minikube:/# cilium endpoint list
ENDPOINT   POLICY        IDENTITY   LABELS (source:key[=value])               IPv6                   IPv4            STATUS
           ENFORCEMENT
792        Enabled       260        k8s:id=app1                               f00d::a00:20f:0:318    10.15.145.61    ready
                                    k8s:io.kubernetes.pod.namespace=default
12879      Enabled       258        k8s:id=app3                               f00d::a00:20f:0:324f   10.15.161.35    ready
                                    k8s:io.kubernetes.pod.namespace=default
44742      Enabled       257        k8s:id=app2                               f00d::a00:20f:0:aec6   10.15.24.58     ready
                                    k8s:io.kubernetes.pod.namespace=default
45979      Enabled       260        k8s:id=app1                               f00d::a00:20f:0:b39b   10.15.211.143   ready
                                    k8s:io.kubernetes.pod.namespace=default
root@minikube:/# cilium monitor -t drop
Listening for events on 2 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
xx drop (Policy denied) to endpoint 45979, identity 257->260: 10.15.24.58 -> 10.15.211.143
```

Does the policy look ok? I want to allow app2 to access the service port, but it shouldn't be able to access the container port directly.

**Comment by tgraf** [comment]
Do you have an L3 policy? The policy denied monitor message indicates that the drop is due to L3 violation.

**Comment by michi-covalent** [comment]
@tgraf here is the output from `cilium policy get`:

```
root@minikube:/# cilium policy get
[
  {
    "endpointSelector": {
      "matchLabels": {
        "k8s:io.kubernetes.pod.namespace": "default"
      }
    },
    "egress": [
      {
        "toPorts": [
          {
            "ports": [
              {
                "port": "8080",
                "protocol": "TCP"
              }
            ],
            "rules": {}
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "io.cilium.k8s-policy-name",
        "value": "my-policy",
        "source": "unspec"
      }
    ]
  }
]
Revision: 59
```

**Comment by tgraf** [comment]
@michi-covalent The endpointSelector matches all pods and thus enables policy enforcement on all pods but then no L3 policy is inserted so all packets will be dropped.

**Comment by michi-covalent** [comment]
Thanks @tgraf  I update the policy to include an ingress L4 policy to allow traffic to the container port, and it's working now.

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: my-policy
specs:
  - endpointSelector:
      matchLabels: {}
    egress:
      - toPorts:
          - ports:
              - port: '8080'
                protocol: TCP
    ingress:
      - fromEndpoints:
          - matchLabels: {}
      - toPorts:
          - ports:
              - port: '80'
                protocol: TCP
```
