### ISSUE TITLE
Honor the service.kubernetes.io/service-proxy-name label

### ISSUE THREAD

**Issue by uablrek** [cilium/cilium#13019]
## Proposal / RFE

Cilium should honor the `service.kubernetes.io/service-proxy-name` label when taking over the standard kube-proxy. This means; if the label is defined for a service Cilium **must not** setup loadbalancing for that service. Example;

```
apiVersion: v1
kind: Service
metadata:
  name: mserver-no-proxy
  labels:
    service.kubernetes.io/service-proxy-name: istio
spec:
  selector:
    app: mserver-deployment
  ports:
  - port: 5001
    name: mconnect
```

#### Other info

* [PR](https://github.com/kubernetes/kubernetes/pull/71355)
* [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/0031-20181017-kube-proxy-services-optional.md)
* Slack thread; https://cilium.slack.com/archives/C53TG4J4R/p1598862108037400
* Related comment; https://github.com/kubernetes/kubernetes/issues/92369#issuecomment-650034563

**Is your feature request related to a problem?**

Not yet but I think there will be more specialized K8s proxiers coming in the near future. People has requirement for special things and to get a (possibly odd) feature into the "real" K8s proxier (or Cilium) is hard (if at all possible).

There may also be service mesh + cilium users that with the use-case in the KEP.

**Describe the solution you'd like**

Cilium should ignore services with the `service.kubernetes.io/service-proxy-name` label.

You could also take a more defensive approach in Cilium by (optionally) allowing a setting like `service.kubernetes.io/service-proxy-name: cilium` to let cilium handle _only_ some services, e.g. for DSR. Some administrations are reluctant to deviate from "standard" K8s, but special handling for special services may be ok.
