### ISSUE TITLE
Node Local DNS does not work with kube-proxy replacement

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#13040]
The NodeLocal DNS feature does not work with kube-proxy replacement mode. This is mostly due the fact that Cilium performs the service translation for all services (a.k.a ClusterIPs) and the node local DNS pod listens on both the kube-dns Cluster IP as well as the `node-local-address` in the host network. Thus, the node local DNS pod will never see packets destined to kube-dns Cluster IP because Cilium does the service translation before hand.

More info: https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/

This will likely be fixed by the introduction of LRP https://github.com/cilium/cilium/pull/12831

**Comment by mvisonneau** [comment]
I am curious / happy to investigate this a bit more as I believe it works fine for me 🤔

```
~$ kubectl -n kube-system get cm cilium-config -o yaml | grep kube-proxy
  kube-proxy-replacement: strict
~$ kubectl run -it --restart=Never test --image=tutum/dnsutils -- /bin/bash
root@test:/# grep nameserver /etc/resolv.conf
nameserver 169.254.20.10
root@test:/# dig cilium.io

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> cilium.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32184
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;cilium.io.			IN	A

;; ANSWER SECTION:
cilium.io.		44	IN	A	104.198.14.52

;; Query time: 0 msec
;; SERVER: 169.254.20.10#53(169.254.20.10)
;; WHEN: Wed Sep 02 09:53:52 UTC 2020
;; MSG SIZE  rcvd: 63
```

Is there something obvious I am missing?

--- 
Cilium : 1.18.2
Kernel: 5.4.0-1021-aws
K8S: 1.17.7
NodeLocalDNS image: 1.15.13

**Comment by mvisonneau** [comment]
Ok, rereading the issue more carefully, I am not using the kube-dns ClusterIP service, hence the non-issue on my end. You can forget my former comment 😅

**Comment by Weil0ng** [comment]
Discussed extensively with @aditighag offline. It seems that current [LRP design](https://github.com/cilium/cilium/pull/12831) won't close all the gaps to support NodelocalDNS. The main issue is that, even if we redirect DNS pkts to local node-local-dns pod ip, NodelocalDNS only [listens on two specified ip addresses](https://github.com/kubernetes/dns/blob/master/cmd/node-cache/app/cache_app.go#L72) so it won't answer queries via pod it (aka node ip since it is a host-network ds).

We've tried with several setups with LRP and observed two interesting things:
- directly deploy LRP with the following yaml
```
apiVersion: "cilium.io/v2"
kind: CiliumLocalRedirectPolicy
metadata:
  name: "lrp-svc"
  namespace: kube-system
spec:
  redirectFrontend:
    serviceMatcher:
      service:
        serviceName: kube-dns
        namespace: kube-system
      ports:
        - port: dns
          protocol: UDP
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: node-local-dns
    ports:
      - port: dns
        protocol: UDP
```
I can see that service map is updated as expected and dns pkts are DNATed to node-local-dns pod, but the connection is closed immediately.

- After deleting LRP, as a by-product it also deletes the dns service map entry entirely, we have no service translation but DNS works. Reason is the pkts leave pod ns un-DNATed (Cilium doesn't see dns service anymore), NodelocalDNS intercepts such pkts in rootns, handling DNS.

Personally I think what we really need is a no-op for service translation for DNS requests when NodelocalDNS is present. A possible way of achieving that without too much change/dependency in the datapath could be to still leverage LRP with an extension that it allows for arbitrary backend <ip:port>, then we deploy LRP along with NodelocalDNS to map DNS service vip -> DNS service vip, aka no-op.

Thoughts?

**Comment by aditighag** [comment]
> NodelocalDNS only [listens on two specified ip addresses](https://github.com/kubernetes/dns/blob/master/cmd/node-cache/app/cache_app.go#L72) so it won't answer queries via pod it (aka node ip since it is a host-network ds).


I wonder if it's possible to pass pod IP as one of the `-localip` [1] parameters via environment variables [2]. 

[1] https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml
[2] https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

**Comment by Weil0ng** [comment]
> I wonder if it's possible to pass pod IP as one of the `-localip` [1] parameters via environment variables [2].

I think the `localip` is (by NodelocalDNS design) identical across all nodes, making it unique for each node would require pretty intrusive change to NodelocalDNS. Essentially what current setting does is to [deploy NodelocalDNS ds with IPs passed in as cmdline args](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml#L146), making it accept/discover pod ip for each node is an architecturally significant change.

**Comment by aditighag** [comment]
We discussed about node-local DNS functionality in the recent sig-datapath meetings - https://docs.google.com/document/d/1IZZ-FTM_U3zN06-M_mDOgep_DcDM0Oe3YOFVM1BTIt8/edit#heading=h.rtsvie75srz9

@Weil0ng Given that we have some protections in place in cilium around managing conntrack entries, I believe we left the discussion at a point, where it was decided to revisit some of the architecture decisions taken for the node-local dns functionality. Particularly, things like using hard-coded IP addresses, etc.  Any update on that front? Let us know if we need a follow-up meeting to close on this.

Also, in the meantime, I suppose we can test the functionality by creating a `LocalRedirectPolicy`. We can still run the `kube-dns` pods in the `hostNetwork` mode, and try passing the podIP as one of the arguments to [-localip](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml#L146). Let us know if you hit any issues.

**Comment by aditighag** [comment]
@Weil0ng I think it would be useful if you could point users to your upstream changes. We can probably add those notes #13543. Wdyt?

**Comment by Weil0ng** [comment]
> Particularly, things like using hard-coded IP addresses, etc. Any update on that front?

Yea, this can be lifted when we put node-local-dns in its own pod namespace, it will listen on the pod IP.

>I think it would be useful if you could point users to your upstream changes. We can probably add those notes #13543. Wdyt?

Makes sense, I'll push a new commit to the PR.

**Comment by aditighag** [comment]
@Weil0ng Can we close this issue?

**Comment by joestringer** [comment]
As far as I understand, most of this issue is mitigated by running node-local DNS inside a regular pod (*not* hostNetwork), then there's just one remaining issue with node-local DNS when running Cilium in endpoint-routes mode which @Weil0ng is still investigating.

**Comment by aditighag** [comment]
> As far as I understand, most of this issue is mitigated by running node-local DNS inside a regular pod (_not_ hostNetwork), then there's just one remaining issue with node-local DNS when running Cilium in endpoint-routes mode which @Weil0ng is still investigating.

**Comment by Weil0ng** [comment]
The missing NOTRACK rules won't affect the functionality of node-local-dns, I guess we can close this issue and maybe track that as a separate issue/optimization if that's prefered.

**Comment by aditighag** [comment]
Sorry, I didn't mean to close the issue. I was just replying to Joe's comment saying that there is no such issue as such. @Weil0ng can comment more.

**Comment by Weil0ng** [comment]
The core functionality is in place now, let's close this one and I'll open a new issue to track the NOTRACK rule optimization.

**Comment by atsai1220** [comment]
In case anyone runs into this from the Internet, restarting Cilium operator got the ball rolling. See: https://github.com/cilium/cilium/issues/16906

We got stuck configuring `CiliumLocalRedirectPolicy`. In our environment with Cilium 1.14.4, we had to specify `.spec.redirectFrontend.serviceMatcher.toPorts` otherwise the LRP list does not show the endpoints and traffic is not routed to node-local dns cache.

Here are the steps to verify:

1. Create this `CiliumLocalRedirectPolicy` without `.spec.redirectFrontend.serviceMatcher.toPorts`. This is as described in the [documentation](https://docs.cilium.io/en/v1.14/network/kubernetes/local-redirect-policy/#node-local-dns-cache) and the provided [example](https://raw.githubusercontent.com/cilium/cilium/v1.14/examples/kubernetes-local-redirect/node-local-dns-lrp.yaml).

```yaml
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: node-local-dns
  namespace: kube-system
spec:
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: node-local-dns
    toPorts:
    - name: dns
      port: "53"
      protocol: UDP
    - name: dns-tcp
      port: "53"
      protocol: TCP
  redirectFrontend:
    serviceMatcher:
      namespace: kube-system
      serviceName: rke2-coredns-rke2-coredns
```

2. View your lrp list. You will _not_ see your pods on the right side of the arrow and traffic is not directed to node-local dns cache.

``` shell
❯ kubectl -n kube-system exec ds/cilium -- cilium lrp list
LRP namespace   LRP name         FrontendType                Matching Service
kube-system     node-local-dns   clusterIP + all svc ports   kube-system/rke2-coredns-rke2-coredns
                |                10.43.0.10:53/UDP ->
                |                10.43.0.10:53/TCP ->
```

3. Delete your existing lrp. At the time of writing, there is a [limitation](https://docs.cilium.io/en/v1.14/network/kubernetes/local-redirect-policy/#limitations) that prevents modifications to an existing lrp.
```
kubectl delete ciliumlocalredirectpolicies -n kube-system node-local-dns
```

4. Create a new `CiliumLocalRedirectPolicy` with `.spec.redirectFrontend.serviceMatcher.toPorts`.
```yaml
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: node-local-dns
  namespace: kube-system
spec:
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: node-local-dns
    toPorts:
    - name: dns
      port: "53"
      protocol: UDP
    - name: dns-tcp
      port: "53"
      protocol: TCP
  redirectFrontend:
    serviceMatcher:
      namespace: kube-system
      serviceName: rke2-coredns-rke2-coredns
      toPorts:
        - name: dns-tcp
          port: "53"
          protocol: TCP
        - name: dns
          port: "53"
          protocol: UDP
```
5. Verify your lrp list has backend pods and traffic routed to your node-local dns cache. The output will show your node-local-dns pod IPs.

```shell
❯ kubectl -n kube-system exec ds/cilium -- cilium lrp list
LRP namespace   LRP name         FrontendType              Matching Service
kube-system     node-local-dns   clusterIP + named ports   kube-system/rke2-coredns-rke2-coredns
                |                10.43.0.10:53/TCP -> 10.42.3.193:53(kube-system/node-local-dns-sbtdr),
                |                10.43.0.10:53/UDP -> 10.42.3.193:53(kube-system/node-local-dns-sbtdr),
```
