### ISSUE TITLE
Traffic from inside the cluster to external LB not working if IPSec is enabled

### ISSUE THREAD

**Issue by tobiaskohlbau** [cilium/cilium#13064]
## Bug report

I've ran into issues with IPSec enabled and trying to reach a service inside the cluster via it's external LB IP. As far as I understand _kube-proxy_ inserts rules which rewrite the destination from external IP to internal pod IP to avoid hitting the loadbalancer as the traffic could flow within the cluster only. I've gathered that these rules are inserted and the traffic arrives at the destination pod. On the return path it looks like the connection tracking is not working as the traffic hits the lxc interface of the pod with source ip beeing the from pod instead of the service. Internal traffic with is directly addressed to the service ip from within the cluster works like expected: Pod->SVC(ClusterIP)->Pod.

For more information see below about configuration and sysdump. 

**General Information**

- Cilium version (run `cilium version`)
> 1.8.2
- Kernel version (run `uname -a`)
> Linux node1 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
> 1.19

**How to reproduce the issue**

1. Create cluster and install cilium with settings from `cilium.values.yaml`.
2. Observe traffic flowing between pods via SVC(ClusterIP) is working like expected hitting the external load balancer via it's global ip is not working.
3. Disabling IPSec from the helm chart and redeploying the cluster  fixes this issue.

If you need more information or I should try a dev build let me know.

**cilium.values.yaml**
```YAML
config:
  enabled: true
  blacklistConflictingRoutes: false
  ipam: "kubernetes"
  bpfMasquerade: false

global:
  tunnel: "disabled"
  kubeProxyReplacement: disabled

  encryption:
    enabled: true
    nodeEncryption: false
    interface: enp7s0

  nodePort:
    directRoutingDevice: enp7s0

  masquerade: true

  endpointRoutes:
    enabled: true

  nativeRoutingCIDR: "10.128.0.0/9"
  autoDirectNodeRoutes: false
```

[cilium-ipsec-disabled.zip](https://github.com/cilium/cilium/files/5166963/cilium-ipsec-disabled.zip)
[cilium-ipsec-enabled.zip](https://github.com/cilium/cilium/files/5166958/cilium-ipsec-enabled.zip)
(Sysdumps where taken from completly different clusters to avoid having leftovers from other settings)
