### ISSUE TITLE
Traffic from pod to node , the stream service like exec will automatically close with no error.

### ISSUE THREAD

**Issue by Mengkzhaoyun** [cilium/cilium#13077]
## Bug report

**General Information**

- Cilium version : 1.8.90
- Kernel version : 5.8.5
- Orchestration system version in use : kubernetes v1.18.8
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and cilium config : 
```
{
	"auto-direct-node-routes": "false",
	"bpf-lb-map-max": "65536",
	"bpf-map-dynamic-size-ratio": "0.0025",
	"bpf-policy-map-max": "16384",
	"cluster-name": "default",
	"cluster-pool-ipv4-cidr": "10.0.0.0/11",
	"cluster-pool-ipv4-mask-size": "24",
	"debug": "false",
	"disable-cnp-status-updates": "true",
	"disable-envoy-version-check": "true",
	"enable-auto-protect-node-port-range": "true",
	"enable-bpf-clock-probe": "true",
	"enable-bpf-masquerade": "false",
	"enable-endpoint-health-checking": "true",
	"enable-external-ips": "true",
	"enable-health-check-nodeport": "true",
	"enable-host-port": "true",
	"enable-host-reachable-services": "true",
	"enable-hubble": "true",
	"enable-ipv4": "true",
	"enable-ipv6": "false",
	"enable-node-port": "true",
	"enable-remote-node-identity": "true",
	"enable-session-affinity": "true",
	"enable-well-known-identities": "false",
	"enable-xt-socket-fallback": "true",
	"hubble-listen-address": ":4244",
	"hubble-socket-path": "/var/run/cilium/hubble.sock",
	"identity-allocation-mode": "crd",
	"install-iptables-rules": "true",
	"ipam": "cluster-pool",
	"k8s-require-ipv4-pod-cidr": "true",
	"k8s-require-ipv6-pod-cidr": "false",
	"kube-proxy-replacement": "partial",
	"masquerade": "true",
	"monitor-aggregation": "medium",
	"monitor-aggregation-flags": "all",
	"monitor-aggregation-interval": "5s",
	"node-port-bind-protection": "true",
	"node-port-range": "20,65000",
	"operator-api-serve-addr": "127.0.0.1:9234",
	"preallocate-bpf-maps": "false",
	"sidecar-istio-proxy-image": "cilium/istio_proxy",
	"tunnel": "vxlan",
	"wait-bpf-mount": "false"
}
```

**How to reproduce the issue**

1. Deploy Kubernetes with no kube-proxy
2. Deploy soft LB addon kube-vip
3. Deploy the kubernetes/dashboard(v2.0.3) addon 
4. Exec to Pod
5. After sdtin some word , with no error exit the exec , the stream service exit automatically

**Comment by aanm** [comment]
@Mengkzhaoyun thanks for opening the issue.

can you provide:
- the service artifacts used on step 2;
- the application pod artifacts used for step 4;
- a cilium sysdump of the cluster.

**Comment by Mengkzhaoyun** [comment]
my env like #12988 
3 master 
192.168.1.200,192.168.1.201,192.168.202
vip 1 (kube-vip)
192.168.1.172

the kubernetes-ui config with kube-apiserver by env
KUBERNETES_SERVICE_HOST : 192.168.1.200
KUBERNETES_SERVICE_PORT : 6443
there is no need through kubernetes.default.svc , because the svc default LB mode is rr , rr is not support stream service with session.
so i set kubernetes-ui direct to connect one of apiserver by pod --> host network.

there is no specail pod to exec , random select a busybox pod in kube-system or any other namespace, any pod  , through the kubernetes ui panel to click exec button to exec the pod , like below
![image](https://user-images.githubusercontent.com/6711398/92218067-22552a80-eecb-11ea-833a-0d85990cd970.png)
the exec page will lost connection by anytime in one minitues

after i remove kube-vip for soft LB for kube-apiserver according by k8s.io [Creating Highly Available clusters with kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/)  the exec page will recover ,  the long connect such as stream service will work for as long as succeful , and my cloud shell comp develop by apiserver will take the work stable.

**Comment by Mengkzhaoyun** [comment]
the sysdump file.
[cilium-sysdump-20200904-165241.zip](https://github.com/cilium/cilium/files/5173699/cilium-sysdump-20200904-165241.zip)

**Comment by Mengkzhaoyun** [comment]
oh , after i set kube-vip vip_arp mode=false the issue is solve ......
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  hostNetwork: true
  priorityClassName: system-cluster-critical
  containers:
  - name: kube-vip
    image: "registry.local:5000/k8s/kube-vip:v0.1.7"
    args:
    - start
    env:
    - name: vip_arp
      value: "false"
    - name: vip_interface
      value: "eth0"
    - name: vip_address
      value: "192.168.1.172"
    - name: vip_startleader
      value: "true"
    - name: vip_addpeerstolb
      value: "false"
    - name: vip_localpeer
      value: "ubuntu-1:192.168.1.200:10000"
    - name: vip_remotepeers
      value: "ubuntu-2:192.168.1.201:10000,ubuntu-3:192.168.1.202:10000"      
    - name: lb_bindtovip
      value: "true"
    - name: lb_name
      value: "Beagle APIServer Load Balancer"
    - name: lb_type
      value: "tcp"
    - name: lb_port
      value: "6444"
    - name: lb_backends
      value: "192.168.1.200:6443,192.168.1.201:6443,192.168.1.202:6443"      
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_TIME
```

mybe the arp mode make bad effect cilium's pod --> host network.
