### ISSUE TITLE
Hubble Relay TLS flags naming

### ISSUE THREAD

**Issue by kaworu** [cilium/cilium#13094]
Multiple TLS related flags for Relay are introduced by https://github.com/cilium/cilium/pull/12900. Some are related to (1) the connection from Relay to Hubble servers, and other are related to (2) the connection from various clients (e.g. Hubble UI) to Relay itself.

1. Relay itself can connect to Hubble servers with mTLS, TLS, or without TLS. The related flags are:
```
--tls-client-cert-file
--tls-client-key-file
--tls-hubble-server-ca-files
--disable-client-tls
```

Relay can be configured to serve with TLS, or without TLS. The related flags are:
```
--tls-server-cert-file
--tls-server-key-file
--disable-server-tls
```

Since both (1) and (2) involved client and servers, client/server is not very useful to distinguish between the two. Some other scheme is needed.

cc @Rolinh @gandro 

PS: there were other nits related to theses flags raised on https://github.com/cilium/cilium/pull/12906 and https://github.com/cilium/cilium/pull/12900 which could be addressed as well on the way.

**Comment by aanm** [comment]
The `tls-hubble-client-ca-files` is missing. Also it would be preferable that `hubble` would be a prefix for all of these flags.

**Comment by Rolinh** [comment]
> The `tls-hubble-client-ca-files` is missing.

I think you're referring to `hubble-tls-client-ca-files` as mentioned [here](https://github.com/cilium/cilium/pull/12906#discussion_r482057737) but this was addressed in the PR itself. Or did I miss something?

> Also it would be preferable that `hubble` would be a prefix for all of these flags.

All Hubble related flags for the cilium-agent (aka daemon) are all prefixed with `hubble-`. However, Hubble Relay is a different binary/container that does not make use of the cilium configmap and uses its own. Thus, prefixing every Hubble Relay flags with `hubble-` would clutter I think.

**Comment by aanm** [comment]
@Rolinh 100% agreed.

**Comment by onedr0p** [comment]
I am using the new helm chart 1.9.0-rc1 and coming across a similar issue:

```
Warning  FailedMount       112s (x14 over 14m)  kubelet            MountVolume.SetUp failed for volume "tls" : [secret "hubble-relay-client-certs" not found, configmap "hubble-ca-cert" not found]
```

Helm values for hubble are:

```
    hubble:
      enabled: true
      ui:
        enabled: true
      relay:
        enabled: true
      metrics:
        enabled:
        - dns
        - drop
        - tcp
        - flow
        - port-distribution
        - icmp
        - http
        serviceMonitor:
          enabled: true
```

Let me know if this warrants a new issue. Thanks!
