### ISSUE TITLE
helm: inconsistency in hubble-relay chart

### ISSUE THREAD

**Issue by ghouscht** [cilium/cilium#13115]
## Bug report

There is a little inconsistency in [charts/hubble-relay/templates/deployment.yaml](https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/charts/hubble-relay/templates/deployment.yaml#L32-L36)

Inside the if block the tag of the image is missing, if it is not set directly via `hubble-relay.image.repository` - see example below: 
```yaml
hubble-relay:
  image:
    repository: docker-remote.repo.pnet.ch/cilium/hubble-relay:v1.8.3
    tag: not relevant if .Values.image.repository is set and contains a /
hubble-ui:
  image:
    repository: quay-docker-remote.repo.pnet.ch/cilium/hubble-ui
    tag: v0.6.1
```

This is a bit misleading and not consistent with the behaviour of the hubble-ui subchart. Let me know if you'd like to clean this up. Things would also be a bit easier if the hubble-ui docker image would be on docker hub, this would allow us to use `.Values.image.repository` globally and just append the repository/tag to it for all deployments.
