### ISSUE TITLE
UDP hostPort packets go to wrong ip after udp server restarted

### ISSUE THREAD

**Issue by enkov** [cilium/cilium#13123]
## Bug report

Hello!
I installed cilium in kube-proxy free mode.
Deployed jaeger as a daemon set with enabled HostPort for UDP traffic.
In my app I get host ip from `status.hostIP`.
App works as expect and sends traces to jaeger until I restart jaeger pod.
After it I see in `cilium monitor --type drop` that my app tries to send traces to old jaeger pod ip.
```
xx drop (Stale or unroutable IP) flow 0xf9f6f75e to endpoint 0, identity 60166->0: 10.0.3.152:47767 -> 10.0.3.212:6832 udp
xx drop (Stale or unroutable IP) flow 0xf9f6f75e to endpoint 0, identity 60166->0: 10.0.3.152:47767 -> 10.0.3.212:6832 udp
xx drop (Stale or unroutable IP) flow 0xf9f6f75e to endpoint 0, identity 60166->0: 10.0.3.152:47767 -> 10.0.3.212:6832 udp
xx drop (Stale or unroutable IP) flow 0xf9f6f75e to endpoint 0, identity 60166->0: 10.0.3.152:47767 -> 10.0.3.212:6832 udp
xx drop (Stale or unroutable IP) flow 0xf9f6f75e to endpoint 0, identity 60166->0: 10.0.3.152:47767 -> 10.0.3.212:6832 udp
```
In this log `10.0.3.212` is old ip of jaeger pod before it was restarted
**General Information**

- Cilium version (run `cilium version`)
Client: 1.8.3 54cf3810d 2020-09-04T14:01:53+02:00 go version go1.14.7 linux/amd64
Daemon: 1.8.3 54cf3810d 2020-09-04T14:01:53+02:00 go version go1.14.7 linux/amd64
- Kernel version (run `uname -a`)
Linux node6 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```
https://drive.google.com/file/d/1nU7v6AuOcOdqsJQOWB9bzT3zKCNqCnow/view?usp=sharing
**How to reproduce the issue**
I made example with simple udp client server app
Create namespace
```bash
kubectl create -f namespace.yaml
```
Create udp server

```bash
kubectl create -f udp_server.yaml
```

Create udp client

```bash
kubectl create -f udp_client.yaml
```
Manifests for this
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: udp
---
apiVersion: v1
kind: Pod
metadata:
  name: udp-server
  namespace: udp
spec:
  nodeName: node6
  containers:
    - name: udp-server
      image: aardvarkx1/udp-server
      imagePullPolicy: Always
      ports:
        - containerPort: 10001
          protocol: UDP
          hostPort: 10001
          name: udp-test
---
apiVersion: v1
kind: Pod
metadata:
  name: udp-client
  namespace: udp
spec:
  nodeName: node6
  containers:
    - name: udp-client
      image: aardvarkx1/udp-client
      imagePullPolicy: Always
      env:
        - name: SERVER_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP

```
I use nodeName selector so all pod go to one node
After udp server and client deployed we need to delete server pod and create it again. And after it client still sends to old pod ip.
