### ISSUE TITLE
helm: Review pod toleration of Hubble Relay deployment

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#13166]
Currently, the `hubble-relay` deployment tolerates to be scheduled on any node:

https://github.com/cilium/cilium/blob/f191f9eed4b9ab1d09c4bd8a6bf2456011acea52/install/kubernetes/cilium/charts/hubble-relay/templates/deployment.yaml#L72-L73

This means that hubble-relay can end up deployed on tainted nodes (such as the master node). It is unclear as to why this toleration is needed.

We should review the current toleration and either make it less permissive (e.g. by using the default toleration), or add comment as to why it needs to be scheduled on e.g. the master node.

**Comment by aanm** [comment]
@gandro to give an update on this. If you have a single node cluster, where that node behaves has the master, hubble-relay won't be scheduled into that node.

In the case of cilium-agent & cilium-operator we need to make sure it's running on all nodes since it is an important part of the infrastructure so the tolerations need to be permissive as possible. In case of hubble-relay relay it will depend on important hubble-relay is to be running in the cluster. (Also in the 1 node cluster I mentioned)

**Comment by Antiarchitect** [comment]
@aanm Could it be something like this?

```
affinity:
  nodeAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: DoesNotExist
```
