### ISSUE TITLE
Cilium fails to update status on CiliumNode resource, leading to Cilium never becoming ready

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#13193]
This issue seems to only be observable on EKS environments. Because the issue is failing to update the CiliumNode status, likely Azure environments are broken as well. GKE is not affected because this only bug exists with IPAM modes that use the CiliumNode resource to hold IPAM information.

Cilium version: `master`
Steps to reproduce:
1) Follow EKS GSG guide
2) Deploy latest `master`.

I traced this down to this call here: https://github.com/cilium/cilium/blob/868feac8abcb70159f2a5709c5c36acbda14ac22/pkg/ipam/node.go#L716

I added an extra log statement:

```
diff --git a/pkg/ipam/node.go b/pkg/ipam/node.go
index ec000292a..0d96156cb 100644
--- a/pkg/ipam/node.go
+++ b/pkg/ipam/node.go
@@ -714,6 +714,9 @@ func (n *Node) syncToAPIServer() (err error) {
 
 		n.ops.PopulateStatusFields(node)
 		updatedNode, err = n.manager.k8sAPI.UpdateStatus(origNode, node)
+		if err != nil {
+			scopedLog.WithError(err).Warning("Failed to update status of node")
+		}
 		if updatedNode != nil && updatedNode.Name != "" {
 			node = updatedNode.DeepCopy()
 			if err == nil {
```

And that leads me to see the following log msgs:

```
[cilium-operator-58678745f4-nmftv] level=info msg="Synchronized ENI information" numInstances=4 numSecurityGroups=20 numSubnets=19 numVPCs=5 subsys=eni
[cilium-operator-58678745f4-nmftv] level=warning msg="Failed to update status of node" error="ciliumnodes.cilium.io \"ip-192-168-86-159.us-east-2.compute.internal\" not found" instanceID=i-0e986523decf7234c name=ip-192-168-86-159.us-east-2.compute.internal subsys=ipam
[cilium-operator-58678745f4-nmftv] level=warning msg="Failed to update status of node" error="ciliumnodes.cilium.io \"ip-192-168-5-163.us-east-2.compute.internal\" not found" instanceID=i-0b2545c92023c4eb8 name=ip-192-168-5-163.us-east-2.compute.internal subsys=ipam
[cilium-operator-58678745f4-nmftv] level=warning msg="Failed to update status of node" error="ciliumnodes.cilium.io \"ip-192-168-5-163.us-east-2.compute.internal\" not found" instanceID=i-0b2545c92023c4eb8 name=ip-192-168-5-163.us-east-2.compute.internal subsys=ipam
[cilium-operator-58678745f4-nmftv] level=warning msg="Failed to update status of node" error="ciliumnodes.cilium.io \"ip-192-168-86-159.us-east-2.compute.internal\" not found" instanceID=i-0e986523decf7234c name=ip-192-168-86-159.us-east-2.compute.internal subsys=ipam
```

Seems like we swallow the error a few lines down if a subsequent `Get` request for the CN resource succeeds.

**Comment by christarazi** [comment]
Seems like we've missed adding a `/status` subresource to CiliumNode. It is there in < 1.8 (under `spec`):

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
...
  name: ciliumnodes.cilium.io
...
spec:
  conversion:
    strategy: None
  group: cilium.io
  names:
    kind: CiliumNode
    listKind: CiliumNodeList
    plural: ciliumnodes
    shortNames:
    - cn
    - ciliumn
    singular: ciliumnode
  preserveUnknownFields: true
  scope: Cluster
  versions:
  - name: v2
    schema:
      openAPIV3Schema:
        description: CiliumNode represents the k8s node from the view of Cilium.
        properties:
          spec:
            properties:
              ...
    served: true
    storage: true
    subresources:
      status: {}
status:
...
  - v2
```

> A /status subresource MUST be provided to enable system components to update statuses of resources they manage.

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
