### ISSUE TITLE
Support explicit entities whitelisting in the policy

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1325]
Special identities such as external clients or the host are currently representing as special labels in the form `reserved:world` and `reserved:host`.  The advantage of this is that it allows to use the existing `fromEndpoints` structure to define policies to such special entities. It is somewhat unintuitive though.

Instead, add a `fromEntities` and `toEntities` to make this both intuitive and super simple to understand:
```
apiVersion: "cilium.io/v1"
kind: CiliumNetworkPolicy
description: "L7 policy for getting started using Kubernetes guide"
metadata:
  name: "rule1"
spec:
  endpointSelector:
    matchLabels:
      id: app1
  ingress:
  - fromEntities:
    - host
  egress:
  - toEntities:
    - world
```
