### ISSUE TITLE
static egress ip for services

### ISSUE THREAD

**Issue by asannes** [cilium/cilium#13269]
## Proposal / RFE

I would like to control what IP is used when a service is connecting to something externally from the k8s cluster.

**Is your feature request related to a problem?**

Scenario is as follows:

SMTP submission server (sending e-mails for external clients), it is running as a deployment with multiple replicas on multiple nodes exposed as a service.

"Other" service is also running in the same cluster, it has different requirements.

What is important is that "Other" service and the SMTP service is not sharing externally visible IP, even if they share the node they are running on.

The problem in this scenario is that I do not want "Other" service to make the SMTP server reputation to go bad by accident.

**Describe the solution you'd like**

From the users perspective: a per service rule to choose what IPs can be used.

I see https://github.com/nirmata/kube-static-egress-ip has done some work on this (alpha), but it falls short because it have no way of handling IPs going away (gateway node dies), and also they end up sending all traffic through one node. Their concept seems sound, you have gateway nodes with the actual IPs and everyone else directs the outgoing data to those nodes which masquerades it.

What would be nice is if you could specify one or multiple ips that the service could be masquarded as when connecting out, this way you could opt to use the local gateway if it has one of the ips the service is allowed to use.

I use MetalLB (arp mode) to have IPs move between nodes and it could be nice to reuse those IPs as both incoming and outgoing, but for my use-case this is not necessary as only outgoing IP is important.

Some random thoughts:
- IPs could either be managed by cilium where they are assigned to nodes or they could be discovered by cilium and made available for masquarding (i.e. you add the ips manually to nodes, and then cilium will be able to use them, or you set per node what interface it may add external ips to?).
- It seems that cilium must keep an overview over what IPs are available to reconfigure routing if it somehow fails.
- For most things running in k8s, this is not necessary.
- Maybe configure pools of egress ips, so that you can have different pools for different trust.

I am not sure what the best solution is to my problem or how well a solution would fit with cilium.

You set up the egress pools:
```
kind: StaticEgressPool
metadata:
  name: smtp-pool
spec:
  egressip:
   - 10.10.10.10/32
   - 10.10.11.0/32
```

And then configure it per service:
```
kind: Service
metadata:
  labels:
    egress-pool: smtp-pool
```
Maybe add some per node configuration to select what interfaces or how things are routed externally.

**Comment by anfernee** [comment]
This looks interesting. I think it requires another annotation to mark some of the nodes as "gateway". 

```
kind: Node
metadata:
  name: node-1
  annotations:
     egress-gateway: true
```

To configure it on service, use annotation might make more sense:
```
kind: Service
metadata:
  annotations:
    egress-pool: smtp-pool
```

Ideas?

**Comment by brb** [comment]
@asannes @anfernee @christianhuening Is this a duplicate issue of https://github.com/cilium/cilium/issues/9589?

What would be an IP selection criteria for the following pool?

```
kind: StaticEgressPool
metadata:
  name: smtp-pool
spec:
  egressip:
   - 10.10.10.10/32
   - 10.10.11.0/32
```
