### ISSUE TITLE
Helm chart to support affinity for operator

### ISSUE THREAD

**Issue by pielu** [cilium/cilium#13279]
## Proposal / RFE

**Helm chart could support affinity settings for operator**

The deamonset for e.g. agent has the following in the template
```
{{- if .Values.global.affinity }}
      affinity:
{{ toYaml .Values.global.affinity | indent 8 }}
```
However, the deployment for the operator has it static in template
```
{{- if or (ge .Capabilities.KubeVersion.Minor "14") (gt .Capabilities.KubeVersion.Major "1") }}
      # In HA mode, cilium-operator pods must not be scheduled on the same
      # node as they will clash with each other.
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: io.cilium/app
                operator: In
                values:
                - operator
            topologyKey: "kubernetes.io/hostname"
{{- end }}
```
It would be great to make operator's affinity parametrized as well.
