### ISSUE TITLE
[Cilium with kubeproxy] IPv4 Fragmented packets are being dropped

### ISSUE THREAD

**Issue by liuyuan10** [cilium/cilium#13349]
## Bug report

We find even when running cilium with kubeproxy in tunneling mode, IPv4 fragmented packets coming into the cluster (e.g. nodePort) are dropped at a high chance. Further investigation observes:

- OOO packets being observed on the 2nd Node. Proved by "tcpdump -ni cilium_geneve". tcpdump on the first node doesn't see packets reordered.
- The drop happens when fragmented packets are OOO. Cilium on the 2nd node can't handle the case where the non-first fragments are seen first.

The two things combined together are causing high packet drops for IPv4 fragmented packets coming into cluster.

While I know IPv4 fragments are not supported yet for node port  #11180, we don't expect it to break when using kube-proxy.

Our cilium config is:
```
  auto-direct-node-routes: "false"
  blacklist-conflicting-routes: "false"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  cluster-name: default
  debug: "false"
  disable-cnp-status-updates: "true"
  enable-auto-protect-node-port-range: "true"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "false"
  enable-endpoint-health-checking: "true"
  enable-host-reachable-services: "true"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-local-node-route: "true"
  enable-metrics: "true"
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  ipam: kubernetes
  k8s-require-ipv4-pod-cidr: "true"
  k8s-require-ipv6-pod-cidr: "false"
  kube-proxy-replacement: disabled
  masquerade: "true"
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  native-routing-cidr: 192.168.0.0/16
  node-port-bind-protection: "true"
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: :6942
  preallocate-bpf-maps: "false"
  prometheus-serve-addr: :9990
  sidecar-istio-proxy-image: cilium/istio_proxy
  tofqdns-enable-poller: "false"
  tunnel: geneve
  wait-bpf-mount: "false"
```

**General Information**

- Cilium version (run `cilium version`)
1.8.1
- Kernel version (run `uname -a`)
5.4.0-47 ubuntu 1804
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
1.17.8
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:

**How to reproduce the issue**

1. create a udp echo service:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-echo-deployment
spec:
  selector:
    matchLabels:
      app: udp-echo
  replicas: 1
  template:
    metadata:
      labels:
        app: udp-echo
    spec:
      containers:
      - name: echo-container
        image: n0r1skcom/echo
        ports:
        - containerPort: 3333
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: udp-echo-service-ilb
spec:
  selector:
    app: udp-echo
  type: NodePort
  ports:
    - name: udp
      protocol: UDP
      port: 3331
      targetPort: 3333
```
2. using netcat from outside of the cluster and hit the nodePort with `nc -u IP port`
3. Send a long string bigger than MTU (like 2000) to trigger IP fragmentation. Can use a [random string generator](http://www.unit-conversion.info/texttools/random-string-generator/)
4. keeping sending large payload and packet drops will be observed (no echo back).
