### ISSUE TITLE
Helm install gives hubble-relay-client-certs not found for hubble-relay pod

### ISSUE THREAD

**Issue by onedr0p** [cilium/cilium#13537]
I am using the new helm chart `v1.9.0-rc1` and coming across an issue:

```
Warning  FailedMount       112s (x14 over 14m)  kubelet            MountVolume.SetUp failed for volume "tls" : [secret "hubble-relay-client-certs" not found, configmap "hubble-ca-cert" not found]
```

All my configmaps:

```
❯ k get configmap -A
NAMESPACE     NAME                                 DATA   AGE
kube-system   chart-content-cilium                 0      18m
kube-system   chart-values-cilium                  1      18m
kube-system   cilium-config                        54     18m
kube-system   cluster-dns                          2      19m
kube-system   coredns                              2      19m
kube-system   extension-apiserver-authentication   6      19m
kube-system   hubble-relay-config                  1      18m
kube-system   hubble-ui-envoy                      1      18m
kube-system   k3s                                  0      19m
```

Helm values for hubble are:

```
    hubble:
      enabled: true
      ui:
        enabled: true
      relay:
        enabled: true
      metrics:
        enabled:
        - dns
        - drop
        - tcp
        - flow
        - port-distribution
        - icmp
        - http
        serviceMonitor:
          enabled: true
```

From my understanding this should be creating the certs automatically, correct?
Thanks!
