### ISSUE TITLE
Inconsistent L7 Network Policy blocking result

### ISSUE THREAD

**Issue by manuelbuil** [cilium/cilium#13597]
## Bug report
I have an httpbin pod in the default namespace that contains an HTTP server listening on port 80. I expose that server through a  k8s service (named httpbin) listening on port 8000 and with targetport 80. Then, I have two HTTP clients, one, named multitool-default, running in a pod in the default namespace and the other, named multitool-testing, running in a pod in a namespace called testing. All HTTP GET requests work correctly. Summary of the set-up:

```
$> kubectl get pods -n default
NAME                                 READY   STATUS    RESTARTS   AGE
httpbin-66cdbdb6c5-rttnp             1/1     Running   0          44h
multitool-default-59667bd7cb-7rnd4   1/1     Running   0          45h
$> kubectl get pods -n testing
NAME                                 READY   STATUS    RESTARTS   AGE
multitool-testing-556bb5bb55-x4wt8   1/1     Running   0          4d8h
$> kubectl get service -n default
NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
httpbin      ClusterIP   10.107.105.5   <none>        8000/TCP   44h
kubernetes   ClusterIP   10.96.0.1      <none>        443/TCP    70d
```

Now, I apply the following cnp:
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "L7 policy to restrict access to specific HTTP call"
metadata:
  name: "rule1"
spec:
  endpointSelector:
    matchLabels:
      app: httpbin
  ingress:
  - fromEndpoints:
    - matchLabels:
        app: multitool-default
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        http:
        - method: "GET"
          path: "/status/202"
```

When using the multitool-default client, things behave as expected:

```
$> kubectl exec -ti multitool-default-59667bd7cb-7rnd4 -n default -- curl -X GET -I http://httpbin.default.svc.cluster.local:8000/status/202
HTTP/1.1 202 Accepted
server: envoy
date: Fri, 16 Oct 2020 07:28:22 GMT
content-type: text/html; charset=utf-8
access-control-allow-origin: *
access-control-allow-credentials: true
content-length: 0
x-envoy-upstream-service-time: 6

$> kubectl exec -ti multitool-default-59667bd7cb-7rnd4 -n default -- curl -X GET -I http://httpbin.default.svc.cluster.local:8000/status/201
HTTP/1.1 403 Forbidden
content-length: 15
content-type: text/plain
date: Fri, 16 Oct 2020 07:28:27 GMT
server: envoy

$> k exec -ti multitool-default-59667bd7cb-7rnd4 -n default -- curl -X GET http://httpbin.default.svc.cluster.local:8000/status/201
Access denied
```
When using the multitool-testing, all traffic towards httpbin should be blocked, and that is what actually happens but instead of getting a quick "Access denied", it hangs forever (until a curl timeout). If I create a another namespace and deploy another client there, I get the same hanging result. Therefore, it seems that if the client is in the same namespace as the server, I see a HTTP 403 response, whereas if it is in a different namespace, the client gets no response.

If I check `cilium monitor -v --type l7`, I can see the requests of the multitool-default but I don't see the ones from multitool-testing. 

Is this an expected behavior?  Thanks!

**General Information**

- Cilium version (run `cilium version`) ==> 1.8.3
- Kernel version (run `uname -a`) ==> 5.3.18-24.15-default
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...) ==> Kubernetes 1.18

httpbin server was fetched from ==> https://raw.githubusercontent.com/istio/istio/release-1.7/samples/httpbin/httpbin.yaml
client is using the multitool image ==> praqma/network-multitool

**How to reproduce the issue**

1 - kubectl apply -f  https://raw.githubusercontent.com/istio/istio/release-1.7/samples/httpbin/httpbin.yaml
2 - Deploy a pod using an image that contains curl in the default namespace and in another namespace
3 - Apply the cnp described above changing the fromEndpoints/matchLabels to match the one of your client
4 - Curl a forbidden url with both clients and see that the result is different
