### ISSUE TITLE
helm: 1.9.0rc1 hubble.ui.ingress and k8s 1.19 not working together

### ISSUE THREAD

**Issue by asannes** [cilium/cilium#13611]
## Bug report

**General Information**

- Cilium 1.9.0rc1
- 5.4.0
- kubeadm 1.19.3

**How to reproduce the issue**

1.Create cilium-values.yaml file with the following:
```
hubble:
    enabled: true
    listenAddress: ":4244"
    relay:
        enabled: true
    ui:
        enabled: true
        ingress:
            enabled: true
            hosts:
                - testhubble.mycompany-example.com
```
2. Run:
```
helm -n kube-system upgrade cilium cilium/cilium --version 1.9.0-rc1 -f cilium-values.yaml
```
Get:
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]

Change hubble.ui.ingress.enabled to false and it succeeds.

It may be related to the change in expected fields in k8s 1.19:
https://kubernetes.io/docs/concepts/services-networking/ingress/ which expects it like:
```
...
  - host: bar.baz.com
    http:
      paths:
      - backend:
          service:
            name: service2
            port:
              number: 80
        path: /foo
        pathType: Prefix
...
```

while template from:
https://github.com/cilium/cilium/blob/1.9.0-rc1/install/kubernetes/cilium/templates/hubble-ui-ingress.yaml
creates:
```
  {{- range .Values.hubble.ui.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: hubble-ui
              servicePort: http
  {{- end }}
```

So some voodoo seems necessary to differentiate k8s versions.
