### ISSUE TITLE
kubernetes network policy lead to incorrect packet classification with k3s

### ISSUE THREAD

**Issue by reneluria** [cilium/cilium#13615]
## Bug report

**description**

with k3s:

with a cilium network policy, the packet is classified as `remote ID 1`

with a kubernetes network policy, the packet is classified as `remote ID 2`
leading to a packet drop

**General Information**

- Cilium version 1.8.4
- Kernel version 4.19.0-11-cloud-amd64
- Orchestration system version in use k3s (v1.18.9+k3s1)
- Generate and upload a system zip:
[cilium-sysdump-20201019-095154.zip](https://github.com/cilium/cilium/files/5400880/cilium-sysdump-20201019-095154.zip)

**How to reproduce the issue**

- Create a vm with debian 10.6.0

- Install k3s

```
sudo apt-get update && sudo apt-get -y install --no-install-recommends curl
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-backend=none --no-deploy=servicelb,traefik,local-storage,metrics-server --write-kubeconfig-mode=0644" sh -
sudo mount bpffs -t bpf /sys/fs/bpf
kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.8/install/kubernetes/quick-install.yaml
kubectl get pods --all-namespaces -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,HOSTNETWORK:.spec.hostNetwork --no-headers=true | grep '<none>' | awk '{print "-n "$1" "$2}' | xargs -L 1 -r kubectl delete pod
```

- Create deploy

```
kubectl apply -f - <<EOD
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
          - name: http
            protocol: TCP
            containerPort: 80
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
      terminationGracePeriodSeconds: 0
EOD
```

- Monitor pod logs

```
kubectl logs -f --tail 0 $(kubectl get pod -l app=nginx -o name)
(...)
10.103.98.54 - - [19/Oct/2020:09:31:28 +0000] "GET / HTTP/1.1" 200 612 "-" "kube-probe/1.18" "-"
```

- Apply Cilium Network Policy

```
kubectl apply -f - <<EOD
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "deny-ingress"
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - {}
EOD
```

- Verify policy

Show policy

```
kubectl -n kube-system exec -ti $(kubectl -n kube-system get pod -l k8s-app=cilium -o name | head -n 1) -- cilium policy get
[
  {
    "endpointSelector": {
      "matchLabels": {
        "k8s:io.kubernetes.pod.namespace": "default"
      }
    },
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "k8s:io.kubernetes.pod.namespace": "default"
            }
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "io.cilium.k8s.policy.derived-from",
        "value": "CiliumNetworkPolicy",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.name",
        "value": "deny-ingress",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.namespace",
        "value": "default",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.uid",
        "value": "ac81f5c8-9dc5-4cba-9203-767cb635c6e1",
        "source": "k8s"
      }
    ]
  }
]
Revision: 2
```

- Inspect policy
```
kubectl -n kube-system exec -ti $(kubectl -n kube-system get pod -l k8s-app=cilium -o name | head -n 1) -- cilium monitor -t policy-verdict
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
Policy verdict log: flow 0x1bfdc4ae local EP ID 1420, remote ID 1, dst port 80, proto 6, ingress true, action allow, match L3-Only, 10.103.98.54:55624 -> 10.103.206.98:80 tcp SYN
Policy verdict log: flow 0x44be0214 local EP ID 1420, remote ID 1, dst port 80, proto 6, ingress true, action allow, match L3-Only, 10.103.98.54:55630 -> 10.103.206.98:80 tcp SYN
Policy verdict log: flow 0x44a3cc87 local EP ID 1420, remote ID 1, dst port 80, proto 6, ingress true, action allow, match L3-Only, 10.103.98.54:55634 -> 10.103.206.98:80 tcp SYN
```

- Delete policy

```
kubectl delete ciliumnetworkpolicy deny-ingress
```

- Apply plain kubernetes Network policy

```
kubectl apply -f - <<EOD
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-ingress
spec:
  ingress:
    - from:
        - podSelector: {}
  podSelector: {}
  policyTypes:
    - Ingress
EOD
```

- Show policy

```
kubectl -n kube-system exec -ti $(kubectl -n kube-system get pod -l k8s-app=cilium -o name | head -n 1) -- cilium policy get
[
  {
    "endpointSelector": {
      "matchLabels": {
        "k8s:io.kubernetes.pod.namespace": "default"
      }
    },
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "k8s:io.kubernetes.pod.namespace": "default"
            }
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "io.cilium.k8s.policy.derived-from",
        "value": "NetworkPolicy",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.name",
        "value": "deny-ingress",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.namespace",
        "value": "default",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.uid",
        "value": "38419d46-5d02-4dcf-a95a-82d5bdf4a88d",
        "source": "k8s"
      }
    ]
  }
]
Revision: 4
```

- Inspect policy

```
kubectl -n kube-system exec -ti $(kubectl -n kube-system get pod -l k8s-app=cilium -o name | head -n 1) -- cilium monitor -t policy-verdict
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
Policy verdict log: flow 0xe5a4b28e local EP ID 1420, remote ID 2, dst port 80, proto 6, ingress true, action deny, match none, 10.103.98.54:56550 -> 10.103.206.98:80 tcp SYN
Policy verdict log: flow 0xdfaba05c local EP ID 1420, remote ID 2, dst port 80, proto 6, ingress true, action deny, match none, 10.103.98.54:56554 -> 10.103.206.98:80 tcp SYN
Policy verdict log: flow 0xab941ea8 local EP ID 1420, remote ID 2, dst port 80, proto 6, ingress true, action deny, match none, 10.103.98.54:56550 -> 10.103.206.98:80 tcp SYN
Policy verdict log: flow 0x6dc1645b local EP ID 1420, remote ID 2, dst port 80, proto 6, ingress true, action deny, match none, 10.103.98.54:56550 -> 10.103.206.98:80 tcp SYN
Policy verdict log: flow 0x8ceb6ff9 local EP ID 1420, remote ID 2, dst port 80, proto 6, ingress true, action deny, match none, 10.103.98.54:56558 -> 10.103.206.98:80 tcp SYN
```
