### ISSUE TITLE
Incorrect indentation in hubble-relay Helm chart deployment

### ISSUE THREAD

**Issue by alex1989hu** [cilium/cilium#14000]
## Bug report
Incorrect indentation in hubble-relay Helm chart deployment.

> error validating data: [ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "limits" in io.k8s.api.core.v1.Container, ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "requests" in io.k8s.api.core.v1.Container]

**General Information**

- Cilium version (run `cilium version`):
`1.9.0`
- Kernel version (run `uname -a`)
`N/A`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...):
`N/A`
- Link to relevant artifacts (policies, deployments scripts, ...):
`N/A`
- Generate and upload a system zip:
`N/A`

**How to reproduce the issue**
1. Clone `cilium` and checkout `1.9.0` 
2. Navigate to directory `cilium/install/kubernetes`
1. Create `custom-values.yaml` file with the following content:

```yaml
hubble:
  relay:
    enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 12Mi
```

2. Execute `helm template cilium -f custom-values.yaml cilium/ > test.yaml`
3. Open `test.yaml`
4. Go to `# Source: cilium/templates/hubble-relay-deployment.yaml` comment
5. Check `resources` section

```yaml
          resources: # check the lines after here !
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 12Mi
```
