### ISSUE TITLE
Ability to ignore tcp connection state established on filters

### ISSUE THREAD

**Issue by gpl** [cilium/cilium#14040]
## Proposal / RFE

We're looking for the ability to explicitly block all traffic from specified ranges irrespective of connection state or TCP flags.

**Describe the solution you'd like**

Potentially something like an optional `ignoreEstablished` attribute:
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "testpolicy1"
  namespace: cilium-test-01
spec:
  endpointSelector:
    matchLabels:
      app: testapp
  ingress:
    - fromCIDRSet:
      - cidr: 173.245.48.0/20
      - cidr: 103.21.244.0/22
      ignoreEstablished: true # defaults at false(?)
```
