### ISSUE TITLE
Cilium negative policies

### ISSUE THREAD

**Issue by bruun365** [cilium/cilium#14228]
## Proposal / RFE

**Is your feature request related to a problem?** 

**Describe the solution you'd like**
It would be great if it's possible to write a CiliumClusterwideNetworkPolicy that will be applied to all namespaces with the exception of the kube-system and / or default namespace (negative policy). This ensures that a default CiliumClusterwideNetworkPolicy policy will be applied automatically to each new namespace that is created. For example, this can be a policy that only allows egress traffic to kube-system namespace/endpoints. 

Calico has developed something called a negative policy: _namespaceSelector: has(projectcalico.org/name) && projectcalico.org/name not in {"kube-system", "calico-system", "default"}_

Link: https://docs.projectcalico.org/security/kubernetes-default-deny

**Comment by aanm** [comment]
You can achieve that with something similar as this policy:
```
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "rule"
spec:
  endpointSelector:
    matchExpressions:
    - key: io.kubernetes.pod.namespace
      operator: "NotIn"
      values:
        - "kube-system"
        - "default"
  egress:
  - toEndpoints:
    - matchExpressions:
      - key: io.kubernetes.pod.namespace
        operator: "In"
        values:
          - "kube-system"
```
