### ISSUE TITLE
Elevated 5xx rate when using network policies on either side of a connection

### ISSUE THREAD

**Issue by nicktrav** [cilium/cilium#14268]
When applying a Layer 7 network policy to pods on either side of a HTTP, I'm observing some weird behavior where only one pod is returning 200 responses and the remainder are returning 500s.

Initially, I started with a load test of 50 requests / second on a Deployment of three Pods. The namespace in which these pods reside have a network policy:

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: backend-1
spec:
  description: L7 policy - backend 1
  endpointSelector:
    matchLabels:
      "k8s:io.kubernetes.pod.namespace": backend
      "k8s:app": backend
      "k8s:version": v1
  ingress:
  - fromEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": load-test
        "k8s:app": load-test-1
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": load-test
        "k8s:app": load-test-2
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": cilium-monitoring
    toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
      rules:
        http:
        - method: GET
        - method: HEAD
        - method: POST
```

Load was split evenly across the three pods, as expected.

I then applied a network policy to the namespace in which the load-test was running (basically the inverse of the policy in the destination namespace):

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: load-test-1
spec:
  description: L7 policy - load-test-1
  endpointSelector:
    matchLabels:
      "k8s:io.kubernetes.pod.namespace": load-test
      "k8s:app": load-test-1
  egress:
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": backend
        "k8s:app": backend
        "k8s:version": v1
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": backend
        "k8s:app": backend
        "k8s:version": v2
    toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
      rules:
        http:
        - method: GET
        - method: HEAD
        - method: POST
  - toPorts:
    - ports:
      - port: "53"
        protocol: ANY
```

The load then becomes skewed:

![Screenshot from 2020-12-03 16-24-35](https://user-images.githubusercontent.com/804457/101106924-0cb4d700-3586-11eb-8f1c-7be9f860f02e.png)

More requests are reported by Hubble for one Pod, but the application level metrics from that Pod show the actual requests received to be the same as what was reported before the second policy was applied:

![Screenshot from 2020-12-03 16-24-50](https://user-images.githubusercontent.com/804457/101106977-26561e80-3586-11eb-9430-653f4bb713ec.png)

One Pod is returning 200s, the other two return 500s:

![Screenshot from 2020-12-03 16-25-02](https://user-images.githubusercontent.com/804457/101106983-2a823c00-3586-11eb-8416-d61ad2b39256.png)

Interestingly, the Pod returning 200s is running on the same node as the single Pod generating the load.

If I restart the load-test, load looks reasonable for a minute or so before reverting back to a single pod returning 200s:

![Screenshot from 2020-12-03 16-47-44](https://user-images.githubusercontent.com/804457/101107564-6669d100-3587-11eb-8d42-ddf7fdd2f604.png)

![Screenshot from 2020-12-03 16-47-58](https://user-images.githubusercontent.com/804457/101107569-69fd5800-3587-11eb-94b9-f68f81db5135.png)

**General Information**

- Cilium version (run `cilium version`)

```shelll
$ kubectl -n kube-system exec ds/cilium -- cilium version
Client: 1.9.0 dcda3fd98 2020-11-10T13:24:55+01:00 go version go1.15.4 linux/amd64
Daemon: 1.9.0 dcda3fd98 2020-11-10T13:24:55+01:00 go version go1.15.4 linux/amd64
```

- Kernel version (run `uname -a`)

```shell
$ uname -a
Linux nickt 5.8.0-31-generic #33-Ubuntu SMP Mon Nov 23 18:44:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)

```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

Installed with the following:

```shell
helm upgrade cilium cilium/cilium \
  --install \
  --version "$_version" \
  --namespace kube-system \
  --set nodeinit.enabled=true \
  --set kubeProxyReplacement=partial \
  --set hostServices.enabled=false \
  --set externalIPs.enabled=true \
  --set nodePort.enabled=true \
  --set hostPort.enabled=true \
  --set bpf.masquerade=false \
  --set image.pullPolicy=IfNotPresent \
  --set ipam.mode=kubernetes \
  --set hubble.metrics.enabled="{dns,drop,tcp,flow,icmp,http:sourceContext=pod;destinationContext=pod}" \
  --set hubble.listenAddress=":4244" \
  --set hubble.relay.enabled=true \
  --set hubble.ui.enabled=true \
  --set prometheus.enabled=true \
  --set operator.prometheus.enabled=true \
  --set debug.enabled=true
```

**How to reproduce the issue**

I put a reproducer together here: https://github.com/nicktrav/cilium-debugging/tree/nickt.debugging-2
