### ISSUE TITLE
Cilium does not recognise identity thus got policy denied

### ISSUE THREAD

**Issue by alex1989hu** [cilium/cilium#14284]
## Bug report

Possible related to https://github.com/cilium/cilium/issues/13240

I don't know what triggers it, but after a while Cilium starts to drop packages with `Policy denied` (see `CNP` later.). Everything goes to green if I remove the `CNP`. Pod deletion or kill also does not help it.

I see in `hubble` that a Pod called `argocd-redis` considered as world/no category from multiple pods within the same namespace. Thus, all packages dropped `Policy denied`. 

>Timestamp
2020-12-04T16:50:17.057Z
Verdict
dropped
Drop reason
Policy denied
Traffic direction
egress
TCP flags
SYN
Source pod
argocd-repo-server-75ff7d8b4c-l5k2v
Source identity
18696
Source labels
name=argocd-repo-server
io.cilium.k8s.policy.cluster=default
io.cilium.k8s.policy.serviceaccount=default
namespace=argocd
Source IP
10.0.4.163
Destination pod
argocd-redis-678b9dd489-xlzw9
Destination identity
52549
Destination IP
10.0.0.237
Destination port
6379

```bash
$ kubectl -n argocd describe pod argocd-redis-678b9dd489-xlzw9
Name:         argocd-redis-678b9dd489-xlzw9
Namespace:    argocd
Priority:     0
Node:         bucaw250-9/10.135.250.9
Start Time:   Fri, 04 Dec 2020 16:39:58 +0000
Labels:       app.kubernetes.io/name=argocd-redis
              pod-template-hash=678b9dd489
Annotations:  kubernetes.io/psp: privileged
Status:       Running
IP:           10.0.0.237
IPs:
  IP:           10.0.0.237
Controlled By:  ReplicaSet/argocd-redis-678b9dd489
...
```

![ciliumv190world](https://user-images.githubusercontent.com/10764100/101199544-53c5c980-3665-11eb-8396-897a763956b7.PNG)

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "argocd-application-controller-policy"
  namespace: argocd
specs:
  - endpointSelector:
      matchLabels:
        "app.kubernetes.io/name": argocd-application-controller
    ingress:
    - fromEndpoints:
      - matchLabels:
          "app.kubernetes.io/name": argocd-redis
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
    - fromEntities:
      - remote-node
    egress:
    - toEndpoints:
      - matchLabels:
          "app.kubernetes.io/name": argocd-redis
      - matchLabels:
          "app.kubernetes.io/name": argocd-repo-server
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
    - toEntities:
      - remote-node
      - world

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "argocd-dex-server-policy"
  namespace: argocd
specs:
  - endpointSelector:
      matchLabels:
        "app.kubernetes.io/name": argocd-dex-server
    ingress:
    - fromEndpoints:
      - matchLabels:
          "app.kubernetes.io/name": argocd-server
    - fromEntities:
      - remote-node
    egress:
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
    - toEntities:
      - remote-node
      - world

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "argocd-repo-server-policy"
  namespace: argocd
specs:
  - endpointSelector:
      matchLabels:
        "app.kubernetes.io/name": argocd-repo-server
    ingress:
    - fromEndpoints:
      - matchLabels:
          "app.kubernetes.io/name": argocd-application-controller
      - matchLabels:
          "app.kubernetes.io/name": argocd-server
    - fromEntities:
      - remote-node
    egress:
    - toEndpoints:
      - matchLabels:
          "app.kubernetes.io/name": argocd-redis
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
    - toEntities:
      - world

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "argocd-redis-policy"
  namespace: argocd
specs:
  - endpointSelector:
      matchLabels:
        "app.kubernetes.io/name": argocd-redis
    ingress:
    - fromEndpoints:
      - matchLabels:
          "app.kubernetes.io/name": argocd-application-controller
      - matchLabels:
          "app.kubernetes.io/name": argocd-repo-server
      - matchLabels:
          "app.kubernetes.io/name": argocd-server
    - fromEntities:
      - remote-node
    egress:
    - toEndpoints:
      - matchLabels:
          "app.kubernetes.io/name": argocd-application-controller
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "argocd-server-policy"
  namespace: argocd
specs:
  - endpointSelector:
      matchLabels:
        "app.kubernetes.io/name": argocd-server
    ingress:
    - fromEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": projectcontour
          app: envoy
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": argocd-image-updater
          "app.kubernetes.io/name": argocd-image-updater
    - fromEntities:
      - remote-node
    egress:
    - toEndpoints:
      - matchLabels:
          "app.kubernetes.io/name": argocd-dex-server
      - matchLabels:
          "app.kubernetes.io/name": argocd-redis
      - matchLabels:
          "app.kubernetes.io/name": argocd-repo-server
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": projectcontour
          app: envoy
    - toEntities:
      - remote-node
      - world
```

**General Information**

- Cilium version (run `cilium version`)
> Client: 1.9.0 dcda3fd98 2020-11-10T13:24:55+01:00 go version go1.15.4 linux/amd64
Daemon: 1.9.0 dcda3fd98 2020-11-10T13:24:55+01:00 go version go1.15.4 linux/amd64
- Kernel version (run `uname -a`)
> Linux bucaw250-8 5.9.3-talos #1 SMP Fri Nov 13 16:04:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
> Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
- Link to relevant artifacts (policies, deployments scripts, ...)
N/A
- Generate and upload a system zip:
Attached
[cilium-sysdump-20201204-191108.zip](https://github.com/cilium/cilium/files/5644589/cilium-sysdump-20201204-191108.zip)

**How to reproduce the issue**
Do not know what triggers it.
