### ISSUE TITLE
Cilium is using wrong interface for MTU detection

### ISSUE THREAD

**Issue by samling** [cilium/cilium#14339]
## Bug report

We've deployed Cilium 1.9.1 via Helm in a bare metal Kubernetes 1.19.4 cluster running MetalLB as a load balancer. It's a 4-node cluster (one control + 3 worker nodes); each node runs Ubuntu 20.04.1 and has two primary interfaces, one for external connectivity and one to talk to our storage backend. These instances are provisioned using Ubuntu MaaS and the interfaces are aliased using netplan for consistency, named `external` and `storage` respectively.

What we're noticing is that Cilium appears to default to the storage interface rather than the external interface. The tell is that the storage interface has an MTU size of 9000 vs the default 1500 for the external interface; after the cluster is stood up and Cilium and MetalLB are running, any new pods created have an MTU size of 9000 on their primary interface:

```
~ > kubectl exec -it alpine-deployment-5dbfb45ff5-jpbtn -- sh
/ # ifconfig
eth0      Link encap:Ethernet  HWaddr FE:DA:85:63:64:91
          inet addr:10.0.3.87  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:9000  Metric:1
          RX packets:13 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1006 (1006.0 B)  TX bytes:0 (0.0 B)
```

This suggests that Cilium is not respecting the Helm setting `devices: "external"`.

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.9.1 975b66772 2020-12-04T18:16:09+01:00 go version go1.15.5 linux/amd64
Daemon: 1.9.1 975b66772 2020-12-04T18:16:09+01:00 go version go1.15.5 linux/amd64
```

- Kernel version (run `uname -a`)
`Linux k8s01 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
ubuntu@k8s01:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Link to relevant artifacts (policies, deployments scripts, ...)

`values.yaml`:
```
containerRuntime:
  integration: "auto"
policyEnforcementMode: "never"
devices: "external"
etcd:
  enabled: true
  ssl: true
  endpoints:
  - "https://172.18.73.31:2379"
hubble:
  enabled: true
  listenAddress: ":4244"
  metrics:
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - port-distribution
    - icmp
    - http
  relay:
    enabled: true
  ui:
    enabled: true
```
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```
https://novacoast-my.sharepoint.com/:u:/p/sboynton/Ea_SbyQeXKBKrLlb-JKOknEBtPHScZxG54JTEhO229wAlw?e=oCHRbG

**How to reproduce the issue**

1. Build cluster nodes with two interfaces, one configured for jumbo frames (e.g. MTU size of 9000)
2. Standardize interface names using e.g. netplan
3. Provision nodes as kubernetes nodes
4. Install Cilium via Helm with `devices: "external"`
5. Check MTU size of any new pods to see if they have inherited settings from the external or storage interface
