### ISSUE TITLE
CiliumIdentities should print namespace of entity in kubectl output

### ISSUE THREAD

**Issue by james-callahan** [cilium/cilium#14344]
Running e.g. `kubectl get ciliumidentities` doesn't tell you much about the resources.
Add in some `additionalPrintColumns` so that users get more information:

```yaml
    additionalPrinterColumns:
    - name: Namespace
      description: The namespace of the entity
      type: string
      jsonPath: .metadata.labels.io\.kubernetes\.pod\.namespace
    - name: Age
      jsonPath: .metadata.creationTimestamp
      type: date
```
