### ISSUE TITLE
Cilium helm chart should support creating cni configmap

### ISSUE THREAD

**Issue by ScottKGregory** [cilium/cilium#14430]
## Proposal / RFE

**Is your feature request related to a problem?**
While trying to set up cilium cni to use eth0 for pod IP allocation I cam across this [comment](https://github.com/cilium/cilium/issues/10426#issuecomment-609415599) which outlines a solution.

**Describe the solution you'd like**
Because this needs to be applied to the cluster before/during cilium's installation I propose adding to the cilium helm chart to allow not only setting the configmap name via `cni.configMap` but allowing for the configmap itself to be defined.

My suggestion is to add another key to the values file along the lines of  `cni.configMapData`. I don't think the file needs to be overly complex, primarily leveraging the `toJson` function to populate the config map.

I'm happy to write up a PR etc. myself if it's agreed the feature would be useful.

## Example
Taking the previously linked comment as an example the process would look like this:

**values.yaml**
```yaml

cni:
  configMap: cilium-cni-configuration
  configMapData:
    cniVersion: "0.3.1"
    name: "cilium"
    type: "cilium-cni"
    enable-debug: "false"
    eni:
      first-interface-index: "0"

````

**resulting configmap file**
```yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-cni-configuration
  namespace: kube-system
data:
  cni-config: |
    {
      "cniVersion": "0.3.1",
      "name": "cilium",
      "type": "cilium-cni",
      "enable-debug": false,
      "eni": {
        "first-interface-index": 0
      }
    }

```
