### ISSUE TITLE
Kubernetes Egress network policy with CIDR covering Pod IPs is not supported

### ISSUE THREAD

**Issue by knabben** [cilium/cilium#14497]
## Bug report

Kubernetes Egress Netpol using `ipBlock.cidr` does not works, and blocks transactions.   

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.9.1 975b66772 2020-12-04T18:16:09+01:00 go version go1.15.5 linux/amd64
Daemon: 1.9.1 975b66772 2020-12-04T18:16:09+01:00 go version go1.15.5 linux/amd64
```
- Kernel version (run `uname -a`)
```
Linux cilium-control-plane 4.19.0-13-cloud-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. I'm using Kind to start the cluster without CNI 
2. Installing Cilium with Helm
3. Create Pod A
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    pod: a
  name: a
spec:
  containers:
  - command:
    - /agnhost
    - serve-hostname
    - --tcp
    - --http=false
    - --port
    - "80"
    image: k8s.gcr.io/e2e-test-images/agnhost:2.21
    imagePullPolicy: IfNotPresent
    name: cont-80-tcp
    ports:
    - containerPort: 80
      name: serve-80-tcp
      protocol: TCP
```
4. Create Pod B
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    pod: b
  name: b
spec:
  containers:
  - command:
    - /agnhost
    - serve-hostname
    - --tcp
    - --http=false
    - --port
    - "80"
    image: k8s.gcr.io/e2e-test-images/agnhost:2.21
    imagePullPolicy: IfNotPresent
    name: cont-80-tcp
    ports:
    - containerPort: 80
      name: serve-80-tcp
      protocol: TCP
```
5. Connect A -> B = `kubectl exec a -- /agnhost connect b:80 --timeout=2s`
6. Get B podIP - `kubectl get pod b -o jsonpath="{.status.podIP}/32"` - e.g. `192.168.3.166/32`
7. Create a new Network policy using podSelector (A) and ipBlock (B)
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-client-a-via-cidr-egress-rule
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 192.168.3.166/32
  - ports:
    - port: 53
      protocol: UDP
  podSelector:
    matchLabels:
      pod: a
  policyTypes:
  - Egress
```
8. Failed to connect A -> B = `kubectl exec a -- /agnhost connect b:80 --timeout=2s` - TIMEOUT
