### ISSUE TITLE
Services are inaccessible from KubeVirt VMs when using kube-proxy free configuration

### ISSUE THREAD

**Issue by briantopping** [cilium/cilium#14563]
## Bug report

Kubevirt has a layered networking stack that is described [here](https://github.com/kubevirt/kubevirt/blob/master/docs/devel/networking.md). As Daniel Borkman kindly described [here](https://cilium.slack.com/archives/C1MATJ5U5/p1610058107366400?thread_ts=1609804735.250100&cid=C1MATJ5U5), "the east-west based load-balancing is basically realised through BPF attaching to socket hooks e.g. connect(2) and then doing the service xlation once at connect time from there. This means there is no packet-based NAT involved. To get this to work, we'd need to compile in the old-style service translation in bpf_lxc to catch untranslated service requests on a per-packet basis (cc @martynas). This would get ClusterIP translation working for kubevirt case containers at least (and therefore resolve your DNS issues)."

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.9.1 975b66772 2020-12-04T18:16:09+01:00 go version go1.15.5 linux/amd64
Daemon: 1.9.1 975b66772 2020-12-04T18:16:09+01:00 go version go1.15.5 linux/amd64
```
- Kernel version (run `uname -a`)
```
Linux r3c1n1 5.10.4-051004-generic #202012301142 SMP Wed Dec 30 11:44:55 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:18:51Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:10:32Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**How to reproduce the issue**

1. Bootstrap minimal kubernetes, I used Kubeadm
2. Install Cilium with values:
  ```
upgradeCompatibility: "1.8"
autoDirectNodeRoutes: true
ipam:
  operator:
    clusterPoolIPv4MaskSize: 24
    clusterPoolIPv4PodCIDR: 10.16.0.0/15
kubeProxyReplacement: strict
nativeRoutingCIDR: 10.16.0.0/14
loadBalancer:
  acceleration: native
  mode: dsr
tunnel: disabled
operator:
  numReplicas: 1
  ```
3. Install Kubevirt:
  ```
  kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/v0.36.0/kubevirt-operator.yaml
  kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/v0.36.0/kubevirt-cr.yaml
  ```
4. Create VM:
  ```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvmi-nocloud
spec:
  terminationGracePeriodSeconds: 5
  domain:
    resources:
      requests:
        memory: 2Gi
    devices:
      disks:
        - name: containerdisk
          disk:
            bus: virtio
        - disk:
            bus: virtio
          name: cloudinitdisk
  volumes:
    - name: containerdisk
      containerDisk:
        image: kubevirt/fedora-cloud-container-disk-demo
    - cloudInitNoCloud:
        userData: |-
          #cloud-config
          password: fedora
          chpasswd: { expire: False }
      name: cloudinitdisk
  ```
5. Find the IP address with `kubectl get vmi -A`, then log in with `ssh fedora@IP`, u/p is `fedora/fedora`.

At this point you can hack around to see the problem with services being inaccessible.
