### ISSUE TITLE
Explicit allow-listing for ICMP traffic 

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#14609]
## Proposal / RFE

**Is your feature request related to a problem?**

Yes.  There is no way to have an ingress/egress policy that both limits TCP/UDP reachability to a set of ports, while also allowing ICMP pings for manual connectivity checks.   ICMP pings are automatically allowed if a policy permits all L3 connectivity, but if that rule is made more granular to limit things to a specific set of TCP/UDP ports, L3 connectivity including ICMP is denied by default.   

The existing documentation describes this: https://docs.cilium.io/en/v1.9/policy/language/#limit-ingress-egress-ports 

**Describe the solution you'd like**

One approach would be to follow the common pattern of mapping ICMP to TCP/UDP port style syntax, for example, with ping (type: 6) being:  

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
spec:
  endpointSelector:
    matchLabels:
      org: empire
      class: deathstar
  ingress:
  - fromEndpoints:
    - matchLabels:
        org: empire
    toPorts:
    - ports:
      - port: "8"
        protocol: ICMP
```

Another approach might be to create a "toICMP" clause or similar.   

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
spec:
  endpointSelector:
    matchLabels:
      org: empire
      class: deathstar
  ingress:
  - fromEndpoints:
    - matchLabels:
        org: empire
    toICMP:
    - types: 
       - type: 8
```

**Other Comments**

There presumably would need to be considerations for connection tracking (for example, if I allow echo ingress, I would automatically allow "reply" echo reply packets. 

We would want to consider both ICMP and ICMPv6

Note:  #8129 seems very similar based on title, but the specific problem was more narrow, about making sure ICMP fragmentation needed messages where returned, and the issues seems to be have closed when that specific problem was addressed, but without providing a more generic policy construct.

**Comment by joestringer** [comment]
Is it important to only allow such ICMP echo request+response packets for some nodes in the cluster while dropping such traffic for other nodes? If not, another plausible approach is to have a generic agent option to allow "l3 reachability" for all  pods, in which case there is always an explicit hole opened for ICMP echo request+response.

Also, are there any other known ICMP types/codes that would be important to cover with this? As I understand, the primary use case is simply debugging and verifying endpoint reachability.

**Comment by johnrengelman** [comment]
Looking at the ICMP specs there are messages associated with router solicitation/discovery in both IPv4 and IPv6 (IPv6 neighbor discovery protocol) that people may want to enable while using Cilium for endpoint control (I won't claim to know any specifics here on how these are used in practice).

I think there is an argument for two additions here:
1. Global setting to allow ICMP EchoRequest/EchoReply - model this after the `PolicyEnforcement` setting: `never`, `always`, `l3` (where it is allowed in L3 connectivity exists between the nodes, eg any L4/L7 policy allows traffic between the endpoints)
2. Addition to the `Rule` api to allow complete configuration of ICMP controls at the `type` and `code` levels. From API design, it probably makes sense to introduce the `toICMP` type instead of re-using `toPort` because ICMP has both a type and code field and trying to map that onto `port` would be awkward or limiting.

**Comment by pchaigno** [comment]
If we have the second addition (to `Rule`), the first should be possible using a CCNP, without needing to introduce a new agent flag.

**Comment by johnrengelman** [comment]
> If we have the second addition (to `Rule`), the global setting should be possible using a CCNP, without needing to introduce a new agent flag.

To level set, my use case has Cilium outside of a K8s environment, so as long as I can configure the same effect using Cilium policies directly, 👍

**Comment by joestringer** [comment]
> Looking at the ICMP specs there are messages associated with router solicitation/discovery in both IPv4 and IPv6 (IPv6 neighbor discovery protocol) that people may want to enable while using Cilium for endpoint control (I won't claim to know any specifics here on how these are used in practice).

For this particular aspect, my base inclination is that Cilium itself acts as an L3 router between the endpoints and remote peers so if there's some integration use case around better handling of these message types, it would be somehow embedded into Cilium itself rather than being opened via some policy mechanism.

**Comment by joestringer** [comment]
> To level set, my use case has Cilium outside of a K8s environment, so as long as I can configure the same effect using Cilium policies directly, :+1:

This is the type of feedback I was trying to solicit :-) If the agent-wide setting doesn't provide a full resolution then I think we'd probably be better placed to look at how to extend the policy language to provide this and maybe not look at an agent-wide option. The policy-based approach would be more flexible and should still allow users to implement the behaviour that an agent flag could otherwise provide.

**Comment by johnrengelman** [comment]
Agreed. 
In my initial reply I was thinking the option 1 would be fastest to implement since we wouldn’t need to figure out the API model at the cost of not being as flexible. 
I agree that option 2 is ultimately the right end solution.
👍

**Comment by chez-shanpu** [comment]
Hi! I'm trying to make a GSoC proposal for this issue and I have some questions about this.
As you said, I think the second approach is better too.
And now I'm thinking about how to implement this and where should I edit.
I think we have to make a new API under `cilium/pkg/policy/api/`, and update validation in `rule_validation.go`.
And I'm wondering if I should set ICMP type and code field into `L4filter` struct in `l4.go` and `PolicyKey` struct in `cilium/pkg/maps/policymap/policymap.go`.

**Comment by pchaigno** [comment]
For UDP/TCP, our datapath currently supports a single port, so I'm wondering if it wouldn't be easier, for a first version at least, to only support ICMP types and not the codes. What do we lose if we don't support codes? What's the use case for policies using ICMP codes?

If we don't support ICMP codes, then we can reuse most of the code for the L4 policies. We could still provide a `to/fromICMPs` field in CiliumNetworkPolicies, to be able to extend support later on. We wouldn't need to extend the BPF maps or introduce new types of policies alongside L4 policies.

**Comment by chez-shanpu** [comment]
We can use ICMP codes for ACL in iptables and I thought we need.
But I can't find any use cases that requires ICMP code by searching or asking people .
So, I don't think we have to support it for now either.

BTW if we only support ICMP type, do we use `DestPort` in PolicyKey as an ICMP type and add "ICMP" in `api.L4Proto`?

**Comment by johnrengelman** [comment]
AWS Security Groups support ICMP types & codes in their rules - https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html#SecurityGroupRules

> Any protocol that has a standard protocol number (for a list, see Protocol Numbers). If you specify ICMP as the protocol, you can specify any or all of the ICMP types and codes.

**Comment by johnrengelman** [comment]
Specifically, they store ICMP type in the `FromPort` field and ICMP Code in the `ToPort` - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-rule-1.html

**Comment by chez-shanpu** [comment]
Thank you for the information!

Hmm... I'm wondering if we need ICMP code support 🤔
I know that other services support ICMP code, but I don't think that's a reason to need ICMP code support.

**Comment by chez-shanpu** [comment]
I thought again from the beginning.
IMO if we can't find a reason to support ICMP codes, we don't have to support it.
And also, if we don't support ICMP code, I think using `toPort` field (the first idea) is better, because it's easier to implement.

**Comment by pchaigno** [comment]
> Specifically, they store ICMP type in the FromPort field and ICMP Code in the ToPort

Unfortunately, our datapath currently only filters based on a single port (destination port). Changing that is likely possible but it's a lot more work and I'm not sure it would be possible in the scope of a GSoC project. That doesn't mean we shouldn't discuss and consider that of course.

@johnrengelman Do you have a use case for filtering based on ICMP codes?

**Comment by chez-shanpu** [comment]
Can't we allow multiple ICMP types using multiple CNP?

**Comment by johnrengelman** [comment]
@pchaigno Probably not today, so I think not supporting codes initially makes sense.

**Comment by jamesharr** [comment]
I'm interested in this feature and am tracking it. No pressing need at the very moment.

My two use-cases are:
1. Allowing ping for diagnostics and/or an application that uses icmp to check for remote side availability (usually outside of a cluster)
2. To ensure that PMTUD works with IPv6 if it doesn't already. ICMP return codes are required for path-mtu discovery to work. I'd rather this be taken care of out of the box because it's basically required, though.
3. Work-arounds in case they are needed.

I see a lot of firewall logging stuff ICMP-Code and ICMP-Type into source-port and destination-port. From one perspective, I get it -- it's a field that's not used very often, but on the other hand I think we can do better at data modeling and support some common names like "echo".

This would be my preferred API structure. Key points
* `toICMP` makes very little sense. There is no L4 source/destination in ICMP like there is with UDP and TCP.
* The most common type (used for ping) is a textual representation.
* Numerical matching on type/code is still allowed
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
spec:
  endpointSelector:
    matchLabels:
      org: empire
      class: deathstar
  ingress:
  - fromEndpoints:
    - matchLabels:
        org: empire
    ICMP:
     - type: echo
     - typeNum: 11
       codes:
         - codeNum: 0
         - codeNum: 1
```

Alternate approach I'd still like. Key differences:
* Flatter structure
* string and numerical type/codes are a type union. Not sure if this is possible (or a good idea) with the K8s API.
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
spec:
  endpointSelector:
    matchLabels:
      org: empire
      class: deathstar
  ingress:
  - fromEndpoints:
    - matchLabels:
        org: empire
    ICMP:
     - type: echo
     - type: 11
       code: 0
     - type: 11
       code: 1
```
