### ISSUE TITLE
NetworkPolicy using `ipBlock.cidr` fails when the address being referenced is an external interface

### ISSUE THREAD

**Issue by briantopping** [cilium/cilium#14690]
## Bug report

Generating a network policy using `ipBlock.cidr` fails when the address being referenced is an interface of the system. For instance:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-seed-apiserver
  namespace: garden
spec:
  egress:
  - ports:
    - port: 6443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 10.10.0.31/32
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-seed-apiserver: allowed
  policyTypes:
  - Egress
```

Pods annotated this way cannot reach the CIDR because the policy tries to match against the label `cidr:10.10.0.31/31` and the endpoint only has `reserved:remote-host`. It's a legal `NetworkPolicy` and can't be matched. 

Seems like one way to solve this would be to add the `cidr:` labels to the external endpoints, but that may not be possible because the label does not match the regex.

Relevant Slack thread [here](https://cilium.slack.com/archives/C01JALNQAR1/p1611266668007800).

**General Information**

- Cilium version: 1.9.1
- Kernel version (run `uname -a`): 5.10.4
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...): Kubernetes 1.19.7

**How to reproduce the issue**

1. Create a `NetworkPolicy` as above targeting an external interface that is on a Cilium host.
2. The connection trace will show that the egress is denied
