### ISSUE TITLE
Namespace Level Overrides to Deny policy

### ISSUE THREAD

**Issue by mannytoledo** [cilium/cilium#14776]
## Proposal / RFE

**Is your feature request related to a problem?**

With Isovalent recently introducing Cluster-wide Deny policies in Cilium 1.9, we request to extend this feature. What currently works for us is that the policies take precedence over all other rules on the cluster. The problem we face is on multi-tenant clusters where we want to allow namespaces to access their peered networks but not others.

**Describe the solution you'd like**
To address our use case, we need the ability to specify a list of namespaces excluded from this cluster-wide deny policy. In essence, we would expect a namespace found in this exclusion list to default to normal allowlist behavior. In which case, a subsequent netpol must be created inside the excluded namespace to allow access to the specific resources.

**Comment by pchaigno** [comment]
Discussed on Slack:

You can address this use case with `matchExpressions` in the CCNP's `endpointSelector`, with a `NotIn` operator, such as:
```yaml
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "deny-egress"
spec:
  endpointSelector:
    matchExpressions:
      - key: k8s:io.kubernetes.pod.namespace
        operator: NotIn
        values:
          - ns-tenant-a
          - ns-tenant-b
  egressDeny:
  - ...
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "ns-tenant-a-egress"
spec:
  endpointSelector:
    matchExpressions:
      k8s:io.kubernetes.pod.namespace: ns-tenant-a
  egress:
  - ...
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "ns-tenant-b-egress"
spec:
  endpointSelector:
    matchLabels:
      k8s:io.kubernetes.pod.namespace: ns-tenant-b
  egress:
  - ...
```
