### ISSUE TITLE
policy-enforcement: Setting "enable-policy: always" causes unexpected behaviour in not honouring policies 

### ISSUE THREAD

**Issue by acholt** [cilium/cilium#14860]
A discussion took place on slack first before logging this issue [1].

## Bug report
I recently changed `enable-policy: default` --> `enable-policy: always` as described in [2]

- I see the Cilium Health status endpoints become unreachable, I don’t see anything in the Cilium agent logs.
- External DNS and KubeDNS is being blocked even though there is are policies allowing traffic.

```shell
Cluster health:                                1/5 reachable   (2021-02-03T11:10:39Z)
Node        Endpoints
reachable   unreachable
reachable   unreachable
reachable   unreachable
reachable   unreachable
```

I'm seeing denies even though a policy exists below, but after looking at the cilium trace, I’m also seeing no matches [3].

This is the policy to allow external-dns to the outside world.
```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "infra-external-dns"
  namespace: default
spec:
  description: "L3-L4 policy for External DNS"
  endpointSelector:
    matchLabels:
      partition: core-infra
      name: external-dns
  egress:
    - toEntities:
      - world
      toPorts:
        - ports:
          - port: "443"
            protocol: TCP
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
          - port: "53"
            protocol: ANY
```

Cilium health checks are also being dropped `10.26.25.48:34878 -> 10.26.14.11:4240`, so added this policy with a wide scope just to see if it worked, but still getting denied on health endpoint as well.

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "cilium-health-checks"
spec:
  endpointSelector:
    matchLabels:
      reserved: health
  ingress:
    - fromEntities:
      - all
```

Looking into the health endpoints, they are in a ready state.
```shell
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                            IPv6   IPv4           STATUS
591        Enabled            Enabled           4          reserved:health                                               10.26.27.65    ready
1787       Enabled            Enabled           4          reserved:health                                               10.26.9.143    ready
1104       Enabled            Enabled           4          reserved:health                                               10.26.19.91    ready
502        Enabled            Enabled           4          reserved:health                                               10.26.15.115   ready
2604       Enabled            Enabled           4          reserved:health                                               10.26.27.88    ready
```

**General Information**
- Cilium version: `1.9.4`
- Hosted on AWS EKS
- Kernel version: `5.4.80-40.140.amzn2.x86_64`
- Orchestration system version in use: `v1.18.9-eks-d1db3c`
- SysDump attached
- Link to relevant artifacts:  
[1] https://cilium.slack.com/archives/C1MATJ5U5/p1612352711307400
[2] https://docs.cilium.io/en/v1.9/policy/intro/#policy-enforcement-modes
[3] https://cilium.slack.com/files/U016LMKM1JS/F01LSPW09FG/health_endpoints 

**Current configuration**
```yaml
apiVersion: v1
data:
  auto-create-cilium-node-resource: "true"
  auto-direct-node-routes: "false"
  aws-release-excess-ips: "true"
  bpf-lb-map-max: "65536"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: ""
  cluster-name: default
  custom-cni-conf: "false"
  debug: "false"
  disable-cnp-status-updates: "true"
  egress-masquerade-interfaces: eth+
  enable-auto-protect-node-port-range: "true"
  enable-bandwidth-manager: "false"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "true"
  enable-endpoint-health-checking: "true"
  enable-endpoint-routes: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-l7-proxy: "true"
  enable-local-redirect-policy: "false"
  enable-metrics: "true"
  enable-policy: always
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  hubble-disable-tls: "false"
  hubble-listen-address: :4244
  hubble-metrics: dns drop tcp flow port-distribution icmp http
  hubble-metrics-server: :9091
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  ipam: eni
  kube-proxy-replacement: probe
  kube-proxy-replacement-healthz-bind-address: ""
  masquerade: "true"
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: :6942
  preallocate-bpf-maps: "false"
  prometheus-serve-addr: :9090
  proxy-prometheus-port: "9095"
  sidecar-istio-proxy-image: cilium/istio_proxy
  tunnel: disabled
  wait-bpf-mount: "false"
kind: ConfigMap
```

**How to reproduce the issue**
Focusing on `external-dns` as an example to reproduce.

1. Set `enable-policy: always` in the Cilium config
2. Ensure Cilium component are restarted to load the config
3. Monitor dropped traffic with Hubble `hubble --server localhost:4245 observe -f --verdict DROPPED`
4. View the Cilium health status on all nodes`./k8s-cilium-exec.sh cilium status`

**Comment by acholt** [comment]
[cilium-sysdump-20210204-170601.zip](https://github.com/cilium/cilium/files/5927545/cilium-sysdump-20210204-170601.zip)

**Comment by pchaigno** [comment]
The health endpoint selection bug is not limited to `enable-policy=always`. I've opened https://github.com/cilium/cilium/issues/14871 to track that separately.

**Comment by pchaigno** [comment]
The policy for the health endpoint has an incorrect `endpointSelector` has stated in https://github.com/cilium/cilium/issues/14871#issuecomment-774300176. I tested it locally and it should work once fixed. We will improve the documentation on that.

For the first policy, I'm not finding any endpoint in the sysdump with label `name=external-dsn` so I think it's expected that it doesn't match anything. You do have an endpoint with label `k8s:app.kubernetes.io/name=external-dns`, so maybe that's the mistake. @acholt Could you confirm that it works once the labels are fixed?

**Comment by acholt** [comment]
> The health endpoint selection bug is not limited to `enable-policy=always`. I've opened #14871 to track that separately.

Responed on: https://github.com/cilium/cilium/issues/14871#issuecomment-775169216

**Comment by pchaigno** [comment]
@acholt Is everything working as expected now with the correct labels?

**Comment by acholt** [comment]
> The policy for the health endpoint has an incorrect `endpointSelector` has stated in [#14871 (comment)](https://github.com/cilium/cilium/issues/14871#issuecomment-774300176). I tested it locally and it should work once fixed. We will improve the documentation on that.
> 
> For the first policy, I'm not finding any endpoint in the sysdump with label `name=external-dsn` so I think it's expected that it doesn't match anything. You do have an endpoint with label `k8s:app.kubernetes.io/name=external-dns`, so maybe that's the mistake. @acholt Could you confirm that it works once the labels are fixed?

The healthend is now fixed after the change you suggested, I posted an update to the seperate ticket you created. ✅ 
https://github.com/cilium/cilium/issues/14871#issuecomment-775169216

I could find the `name=external-dsn` that must of been a mistake on my part when I was testing before I reverted the code back for my policies.


I have found what the issue is and have logged it seperatly here #14890. After switching to `enable-policy: always` the behaviour of the policies appear to have changed as I wasn't getting denies before, in theory, I should have as I was managing ingress and egress for my endpoints.

Focus on the `external-dns`, I changed the `matchLabels` under the `endpointSelector` section as you can see below. Nothing is being dropped now after changing this thoughout my 22 policies, busy getting a sysdump and I will upload it shortly.
```bash
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "infra-external-dns"
  namespace: default
spec:
  description: "L3-L4 policy for External DNS"
  endpointSelector:
    matchLabels:
      "k8s:app.kubernetes.io/name": external-dns
      "k8s:partition": core-infra
      # partition: core-infra
      # name: external-dns
  ingressDeny:
    - fromEntities:
      - all
  egress:
    - toEntities:
      - world
      toPorts:
        - ports:
          - port: "443"
            protocol: TCP
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
          - port: "53"
            protocol: ANY
```

**Comment by acholt** [comment]
[cilium-sysdump-20210208-142358.zip](https://github.com/cilium/cilium/files/5944300/cilium-sysdump-20210208-142358.zip)

**Comment by pchaigno** [comment]
Does this policy work?
```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "infra-external-dns"
  namespace: default
spec:
  description: "L3-L4 policy for External DNS"
  endpointSelector:
    matchLabels:
      "app.kubernetes.io/name": external-dns
      partition: core-infra
  ingressDeny:
    - fromEntities:
      - all
  egress:
    - toEntities:
      - world
      toPorts:
        - ports:
          - port: "443"
            protocol: TCP
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
          - port: "53"
            protocol: ANY
```
