### ISSUE TITLE
Helm chart doesn't support multiple --api-rate-limit arguments

### ISSUE THREAD

**Issue by funkypenguin** [cilium/cilium#14944]
## Bug report

Hey guys,

Further to our [slack thread](https://cilium.slack.com/archives/C1MATJ5U5/p1613075990014900), I'm creating this issue to associate with the PR I'm about to submit.

The issue is that in order to adjust the default API rate limits, it's necessary to pass multiple `--api-rate-limit` arguments to cilium-agent. However, the helm chart implements `extraArgs` as an object, and so it's not possible to pass duplicate keys with different values. (duplicates are discarded).

**General Information**

- Cilium version (run `cilium version`) : 1.9.4
- Kernel version (run `uname -a`) : N/A
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...) : Kubernetes with helm v3.5.2

**How to reproduce the issue**

```
❯ helm template . --set extraArgs.api-rate-limit=foo --set extraArgs.api-rate-limit=bar | grep rate-limit -C 3
      containers:
      - args:
        - --config-dir=/tmp/cilium/config-map
        - --api-rate-limit=bar
        command:
        - cilium-agent
        livenessProbe:
```
