### ISSUE TITLE
EgressDeny for a port dropping all egress traffic

### ISSUE THREAD

**Issue by Champ-Goblem** [cilium/cilium#14992]
I have been attempting to block the unauthenticated kubernetes port 10255 from all pod access bar prometheus through the use of an egressDeny rule that matches the port above and any pod with labels not in `app=prometheus` and this is applied to all pods as a whole via a CiliumClusterwideNetworkPolicy. I can see that this policy is selecting the pods correctly as the prometheus pod is still able to connect to the port on each node but for all other pods, no matter the port, all egress traffic is dropped. Changing the port 10255 to any arbitrary port also causes the same issue.

The basic version of the network policy looks like so:
```
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "block-10255-egress"
spec:
  description: ""
  endpointSelector:
    matchExpressions:
      - key: k8s:app
        operator: NotIn
        values:
        - "prometheus"
  egressDeny:
  - toPorts:
    - ports:
      - port: "10255"
        protocol: TCP
```

Cilium is installed using the following values:
```
USER-SUPPLIED VALUES:
cni:
  binPath: /home/kubernetes/bin
endpointRoutes:
  enabled: false
gke:
  enabled: false
hostFirewall: true
hubble:
  listenAddress: :4244
  relay:
    enabled: true
  ui:
    enabled: true
ipam:
  mode: kubernetes
nativeRoutingCIDR: 10.56.0.0/14
nodeinit:
  enabled: true
  reconfigureKubelet: true
  removeCbrBridge: true
tunnel: disabled
```
Cilium has been setup to enable host filtering as suggested in the documentation.

Versions:
```
Cilium version: 1.9.4
Kubernetes version: v1.19.7-gke.800
Kubernetes provider: GKE
Node OS: Ubuntu + CoS (some nodes are running gvisor but cilium is not deployed with gvisor as its runtime class)
CoS kernel version: 5.4.49+
Ubuntu kernel version: 5.4.0-1033-gke
```
