### ISSUE TITLE
Run GitHub actions when certain paths are modified

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#15036]
Not all of the GH actions need to be run once a PR is pushed. GitHub actions have the ability of understanding paths that will should trigger a particular workflow. For example:

```yaml
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - images/runtime/**
      - images/builder/**
```

It would be good to set these paths, if possible, in all GitHub actions so we make sure we only run them when necessary.

More info [here](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths).
