### ISSUE TITLE
Global Services not syncing when using clustermesh-apiserver

### ISSUE THREAD

**Issue by AlexLast** [cilium/cilium#15276]
## Bug report
Have tried to raise this a couple of times via Slack, but hopefully I can get some more traction here.

**General Information**

- Cilium version `1.9.1 975b66772 2020-12-04T18:16:09+01:00`
- Kernel version `Linux <redacted> 5.4.92-flatcar #1 SMP Wed Jan 27 16:53:10 -00 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use `Kubernetes v1.19.8`

**How to reproduce the issue**

We’re looking at using Cilium Cluster Mesh and have created a mesh of 6 development clusters. We run Cilium 1.9.1 in CRD mode and have configured `clustermesh-apiserver` using the official helm chart. The `clustermesh-apiserver` process seems mostly to be working as expected and I can see a full list of nodes from all clusters when I run `cilium status --verbose` on any agent. I have also verified I can connect from pod in cluster a => pod in cluster b via the pods IP address.

We're using the following `clustermesh` specific flags to render with helm:

```
--set clustermesh.useAPIServer=true
--set clustermesh.apiserver.replicas=3
--set clustermesh.apiserver.service.type=LoadBalancer
--set-string clustermesh.apiserver.service.annotations.'service\.beta\.kubernetes\.io/aws-load-balancer-internal'=true
--set clustermesh.apiserver.service.annotations.'service\.beta\.kubernetes\.io/aws-load-balancer-type'=nlb
--set clustermesh.apiserver.tls.auto.enabled=false
```

The issue I’m having is with services and the global service annotation, no matter what I try I can’t seem to get any global services working. For example I create `my-service` on cluster A in namespace `my-namespace` with the annotations:

```yaml
io.cilium/global-service: "true"
io.cilium/shared-service: "false"
```

I create `my-service` on cluster B in namespace `my-namespace` with the annotation:

```yaml
io.cilium/global-service: "true"
```

My understanding is this should allow pods in cluster A to call `my-service.my-namespace` and communicate with the service in cluster B, unfortunately some part of this process isn’t working. I’ve run through the [troubleshooting guide](https://docs.cilium.io/en/v1.9/gettingstarted/clustermesh/#troubleshooting) and can confirm that `cilium service list` returns my service, with local frontend IP but with no remote backends (cluster B).

If I run `cilium debuginfo` on cluster B, I see no externalEndpoints:

```
 externalEndpoints: (map[k8s.ServiceID]k8s.externalEndpoints) {
 },
 ```
 
It feels like whatever part of the process is responsible for watching for the `io.cilium/global-service` annotations isn’t working as expected. I assume this issue is somewhere in the `cilium-operator` or `clustermesh-apiserver`, the helm generated configuration for `cilium-operator` looks something like:

```yaml
auto-direct-node-routes: "false"
bpf-lb-map-max: "65536"
bpf-map-dynamic-size-ratio: "0.0025"
bpf-policy-map-max: "16384"
cilium-endpoint-gc-interval: 5m0s
cluster-id: "2"
cluster-name: <redacted>
cluster-pool-ipv4-cidr: 100.102.128.0/17
cluster-pool-ipv4-mask-size: "24"
custom-cni-conf: "false"
debug: "true"
disable-cnp-status-updates: "true"
enable-auto-protect-node-port-range: "true"
enable-bandwidth-manager: "false"
enable-bpf-clock-probe: "true"
enable-bpf-masquerade: "true"
enable-endpoint-health-checking: "true"
enable-health-check-nodeport: "true"
enable-health-checking: "true"
enable-hubble: "true"
enable-ipv4: "true"
enable-ipv6: "false"
enable-l7-proxy: "true"
enable-local-redirect-policy: "false"
enable-policy: default
enable-remote-node-identity: "true"
enable-session-affinity: "true"
enable-well-known-identities: "false"
enable-xt-socket-fallback: "true"
hubble-disable-tls: "false"
hubble-listen-address: :4244
hubble-socket-path: /var/run/cilium/hubble.sock
hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
identity-allocation-mode: crd
install-iptables-rules: "true"
ipam: cluster-pool
kube-proxy-replacement: disabled
masquerade: "true"
monitor-aggregation: medium
monitor-aggregation-flags: all
monitor-aggregation-interval: 5s
node-port-bind-protection: "true"
operator-api-serve-addr: 127.0.0.1:9234
preallocate-bpf-maps: "false"
sidecar-istio-proxy-image: cilium/istio_proxy
tunnel: vxlan
wait-bpf-mount: "false"
``` 

I had a quick read through the `cilium-operator` & `clustermesh-apiserver` `StartSynchronizingServices` calls and noticed there was a `synchronize-k8s-services` option that hadn't been set by the `helm` chart, however setting this to `true` doesn't seem to fix things (have since realised `true` is the default).

I've looked through the logs for `clustermesh-apiserver` and can see the watcher apparently starting:

```
level=info msg="Starting to synchronize k8s services to kvstore..." subsys=watchers
```

No matter what I do to a `v1.Service` whether it's, create, update or delete does anything seem to happen in the `clustermesh-apiserver` logs.

Noticed there are [some conditions](https://github.com/cilium/cilium/blob/master/pkg/k8s/utils/utils.go#L97) for only watching services that have specific labels set, when `k8s-service-proxy-name` is set, although we're not setting this and I assume it defaults to empty?

I do see some errors/warnings slightly earlier on, but these seem to be for CRDs and apparently resolve themselves - so not sure if it's relevant:

```
level=info msg="Waiting until all Cilium CRDs are available" subsys=k8s
github.com/cilium/cilium/pkg/k8s/synced/crd.go:153: Failed to watch *v1.PartialObjectMetadata: unknown
level=error msg="github.com/cilium/cilium/pkg/k8s/synced/crd.go:153: Failed to watch *v1.PartialObjectMetadata: unknown" subsys=klog
level=info msg="github.com/cilium/cilium/pkg/k8s/synced/crd.go:153: Failed to watch *v1.PartialObjectMetadata: unknown" subsys=klog
level=warning msg="github.com/cilium/cilium/pkg/k8s/synced/crd.go:153: Failed to watch *v1.PartialObjectMetadata: unknown" subsys=klog
level=info msg="All Cilium CRDs have been found and are available" subsys=k8s
```

Would really appreciate if anyone would be able to provide some insight into this issue, thanks 👍
