### ISSUE TITLE
Improve user experience of policy trace with regard to port and protocol

### ISSUE THREAD

**Issue by mikberg** [cilium/cilium#15387]
## Bug report

**General Information**

- Cilium version (run `cilium version`): 1.9.5
- Kernel version (run `uname -a`): Linux aks-stand16-26081535-vmss000014 5.4.0-1036-azure #38~18.04.1-Ubuntu SMP Wed Jan 6 18:26:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...): AKS 1.18.14
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

We have a namespace with these two policies.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-cluster-network-policy-kafka
  namespace: kafka
spec:
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          strimzi.io/kind: cluster-operator
    - podSelector:
        matchLabels:
          strimzi.io/name: kafka-cluster-kafka
    - podSelector:
        matchLabels:
          strimzi.io/name: kafka-cluster-entity-operator
    - podSelector:
        matchLabels:
          strimzi.io/name: kafka-cluster-kafka-exporter
    - podSelector:
        matchLabels:
          strimzi.io/name: kafka-cluster-cruise-control
    ports:
    - port: 9091
      protocol: TCP
  - ports:
    - port: 9092
      protocol: TCP
  - ports:
    - port: 9093
      protocol: TCP
  - ports:
    - port: 9404
      protocol: TCP
  podSelector:
    matchLabels:
      strimzi.io/name: kafka-cluster-kafka
  policyTypes:
  - Ingress
```

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: kafka-cluster-all
  namespace: kafka
spec:
  endpointSelector:
    matchLabels:
      app: kafka-cluster
  ingress:
  - fromEndpoints:
    - {}
```

Together, these policies allow traffic from other namespaces to ports 9092, 9093 and 9404.

However, using `cilium policy trace` to verify this shows `Final verdict: DENIED`. I'm assuming that the NetworkPolicy is not taken into account here.

```
root@aks-fdbts-26081535-vmss00001I:/home/cilium# cilium policy trace --src-identity 43182 --dst-identity 58080
----------------------------------------------------------------
Tracing From: [k8s:app=context-api-entity-matcher-worker, k8s:app.kubernetes.io/managed-by=spinnaker, k8s:app.kubernetes.io/name=context-api, k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker, k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config, k8s:io.cilium.k8s.namespace.labels.name=context, k8s:io.cilium.k8s.namespace.labels.team=contextualization, k8s:io.cilium.k8s.policy.cluster=default, k8s:io.cilium.k8s.policy.serviceaccount=default, k8s:io.kubernetes.pod.namespace=context, k8s:team=contextualization] => To: [k8s:app=kafka-cluster, k8s:app.kubernetes.io/instance=kafka-cluster, k8s:app.kubernetes.io/managed-by=strimzi-cluster-operator, k8s:app.kubernetes.io/name=kafka, k8s:app.kubernetes.io/part-of=strimzi-kafka-cluster, k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker, k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config, k8s:io.cilium.k8s.namespace.labels.name=kafka, k8s:io.cilium.k8s.policy.cluster=default, k8s:io.cilium.k8s.policy.serviceaccount=kafka-cluster-kafka, k8s:io.kubernetes.pod.namespace=kafka, k8s:statefulset.kubernetes.io/pod-name=kafka-cluster-kafka-1, k8s:strimzi.io/cluster=kafka-cluster, k8s:strimzi.io/kind=Kafka, k8s:strimzi.io/name=kafka-cluster-kafka] Ports: [0/ANY]
Resolving ingress policy for [k8s:app=kafka-cluster k8s:app.kubernetes.io/instance=kafka-cluster k8s:app.kubernetes.io/managed-by=strimzi-cluster-operator k8s:app.kubernetes.io/name=kafka k8s:app.kubernetes.io/part-of=strimzi-kafka-cluster k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config k8s:io.cilium.k8s.namespace.labels.name=kafka k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=kafka-cluster-kafka k8s:io.kubernetes.pod.namespace=kafka k8s:statefulset.kubernetes.io/pod-name=kafka-cluster-kafka-1 k8s:strimzi.io/cluster=kafka-cluster k8s:strimzi.io/kind=Kafka k8s:strimzi.io/name=kafka-cluster-kafka]
* Rule {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kafka","k8s:strimzi.io/name":"kafka-cluster-kafka"}}: selected
    Enforcing requirements [{Key:k8s.io.kubernetes.pod.namespace Operator:Exists Values:[]}]
    Allows from labels {"matchLabels":{"k8s:strimzi.io/kind":"cluster-operator"},"matchExpressions":[{"key":"k8s:io.kubernetes.pod.namespace","operator":"Exists"}]}
      No label match for [k8s:app=context-api-entity-matcher-worker k8s:app.kubernetes.io/managed-by=spinnaker k8s:app.kubernetes.io/name=context-api k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config k8s:io.cilium.k8s.namespace.labels.name=context k8s:io.cilium.k8s.namespace.labels.team=contextualization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=context k8s:team=contextualization]
    Allows from labels {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kafka","k8s:strimzi.io/name":"kafka-cluster-kafka"}}
      No label match for [k8s:app=context-api-entity-matcher-worker k8s:app.kubernetes.io/managed-by=spinnaker k8s:app.kubernetes.io/name=context-api k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config k8s:io.cilium.k8s.namespace.labels.name=context k8s:io.cilium.k8s.namespace.labels.team=contextualization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=context k8s:team=contextualization]
    Allows from labels {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kafka","k8s:strimzi.io/name":"kafka-cluster-entity-operator"}}
      No label match for [k8s:app=context-api-entity-matcher-worker k8s:app.kubernetes.io/managed-by=spinnaker k8s:app.kubernetes.io/name=context-api k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config k8s:io.cilium.k8s.namespace.labels.name=context k8s:io.cilium.k8s.namespace.labels.team=contextualization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=context k8s:team=contextualization]
    Allows from labels {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kafka","k8s:strimzi.io/name":"kafka-cluster-kafka-exporter"}}
      No label match for [k8s:app=context-api-entity-matcher-worker k8s:app.kubernetes.io/managed-by=spinnaker k8s:app.kubernetes.io/name=context-api k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config k8s:io.cilium.k8s.namespace.labels.name=context k8s:io.cilium.k8s.namespace.labels.team=contextualization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=context k8s:team=contextualization]
    Allows from labels {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kafka","k8s:strimzi.io/name":"kafka-cluster-cruise-control"}}
      No label match for [k8s:app=context-api-entity-matcher-worker k8s:app.kubernetes.io/managed-by=spinnaker k8s:app.kubernetes.io/name=context-api k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config k8s:io.cilium.k8s.namespace.labels.name=context k8s:io.cilium.k8s.namespace.labels.team=contextualization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=context k8s:team=contextualization]
      Found all required labels
      Allows port [{9092 TCP}]
        No port match found
      Found all required labels
      Allows port [{9093 TCP}]
        No port match found
      Found all required labels
      Allows port [{9404 TCP}]
        No port match found
* Rule {"matchLabels":{"any:app":"kafka-cluster","k8s:io.kubernetes.pod.namespace":"kafka"}}: selected
    Allows from labels {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kafka"}}
      No label match for [k8s:app=context-api-entity-matcher-worker k8s:app.kubernetes.io/managed-by=spinnaker k8s:app.kubernetes.io/name=context-api k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config k8s:io.cilium.k8s.namespace.labels.name=context k8s:io.cilium.k8s.namespace.labels.team=contextualization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=context k8s:team=contextualization]
2/59 rules selected
Found no allow rule
Found no deny rule
Ingress verdict: denied
Final verdict: DENIED
```

The identities were collected from `hubble observe`:

```
{"time":"2021-03-18T13:13:12.991348254Z","verdict":"FORWARDED","ethernet":{"source":"62:4f:11:75:33:f5","destination":"26:05:d1:cc:81:6e"},"IP":{"source":"10.240.29.7","destination":"10.240.27.183","ipVersion":"IPv4"},"l4":{"TCP":{"source_port":57264,"destination_port":9092,"flags":{"PSH":true,"ACK":true}}},"source":{"identity":43182,"namespace":"context","labels":["k8s:app.kubernetes.io/managed-by=spinnaker","k8s:app.kubernetes.io/name=context-api","k8s:app=context-api-entity-matcher-worker","k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker","k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config","k8s:io.cilium.k8s.namespace.labels.name=context","k8s:io.cilium.k8s.namespace.labels.team=contextualization","k8s:io.cilium.k8s.policy.cluster=default","k8s:io.cilium.k8s.policy.serviceaccount=default","k8s:io.kubernetes.pod.namespace=context","k8s:team=contextualization"],"pod_name":"context-api-entity-matcher-worker-75c9f8cb7d-bfxjz"},"destination":{"ID":1278,"identity":58080,"namespace":"kafka","labels":["k8s:app.kubernetes.io/instance=kafka-cluster","k8s:app.kubernetes.io/managed-by=strimzi-cluster-operator","k8s:app.kubernetes.io/name=kafka","k8s:app.kubernetes.io/part-of=strimzi-kafka-cluster","k8s:app=kafka-cluster","k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker","k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config","k8s:io.cilium.k8s.namespace.labels.name=kafka","k8s:io.cilium.k8s.policy.cluster=default","k8s:io.cilium.k8s.policy.serviceaccount=kafka-cluster-kafka","k8s:io.kubernetes.pod.namespace=kafka","k8s:statefulset.kubernetes.io/pod-name=kafka-cluster-kafka-1","k8s:strimzi.io/cluster=kafka-cluster","k8s:strimzi.io/kind=Kafka","k8s:strimzi.io/name=kafka-cluster-kafka"],"pod_name":"kafka-cluster-kafka-1"},"Type":"L3_L4","node_name":"aks-stand16-26081535-vmss000018","event_type":{"type":4},"traffic_direction":"INGRESS","trace_observation_point":"TO_ENDPOINT","Summary":"TCP Flags: ACK, PSH"}
```
