### ISSUE TITLE
Cilium not respect network prefix from podCIDR

### ISSUE THREAD

**Issue by kvaps** [cilium/cilium#15500]
## Bug report

cilium installed with the following values:
```yaml
autoDirectNodeRoutes: true
hubble:
  tls:
    auto:
      method: cronJob
ipam:
  operator:
    clusterPoolIPv4MaskSize: '24'
    clusterPoolIPv4PodCIDR: 10.112.0.0/12
    clusterPoolIPv6MaskSize: '112'
    clusterPoolIPv6PodCIDR: fd00::/104
ipv4:
  enabled: true
ipv6:
  enabled: false
k8sServiceHost: 10.36.20.1
k8sServicePort: '8443'
kubeProxyReplacement: strict
loadBalancer:
  algorithm: maglev
nativeRoutingCIDR: 10.112.0.0/12
operator:
  numReplicas: 1
tunnel: disabled
```
**kube-controller-manager** was running with `--cluster-cidr=10.112.0.0/12` and `--node-cidr-mask-size=26`, so many nodes have podCIDR already allocated, let's take these two:

```yaml
# k get node pve3 -o yaml | neat
apiVersion: v1
kind: Node
metadata: 
  annotations: 
    io.cilium.network.ipv4-cilium-host: 10.112.0.54
    io.cilium.network.ipv4-health-ip: 10.112.0.31
    io.cilium.network.ipv4-pod-cidr: 10.112.0.0/24
    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  labels: 
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: pve3
    kubernetes.io/os: linux
    node-role.kubernetes.io/control-plane: ""
    node-role.kubernetes.io/dnsmasq: ""
    node-role.kubernetes.io/master: ""
  name: pve3
spec: 
  podCIDR: 10.112.0.0/26
  podCIDRs: 
  - 10.112.0.0/26
```

```yaml
# k get node pve4 -o yaml | neat
apiVersion: v1
kind: Node
metadata: 
  annotations: 
    io.cilium.network.ipv4-cilium-host: 10.112.0.12
    io.cilium.network.ipv4-health-ip: 10.112.0.3
    io.cilium.network.ipv4-pod-cidr: 10.112.0.0/24
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  labels: 
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: pve4
    kubernetes.io/os: linux
  name: pve4
spec: 
  podCIDR: 10.112.0.64/26
  podCIDRs: 
  - 10.112.0.64/26
```

However, cilium-operator has `/24` prefix configured, and creates two ciliumnodes with the conflicting address range:

```yaml
# k get ciliumnode pve3 | neat
apiVersion: cilium.io/v2
kind: CiliumNode
metadata: 
  labels: 
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: pve3
    kubernetes.io/os: linux
    node-role.kubernetes.io/control-plane: ""
    node-role.kubernetes.io/dnsmasq: ""
    node-role.kubernetes.io/master: ""
  name: pve3
spec: 
  addresses: 
  - ip: 10.36.20.3
    type: InternalIP
  - ip: 10.112.0.17
    type: CiliumInternalIP
  - ip: 10.112.0.54
    type: CiliumInternalIP
  health: 
    ipv4: 10.112.0.31
  ipam: 
    podCIDRs: 
    - 10.112.0.0/24
    - fd00: :/112
```

```yaml
# k get ciliumnode pve4 | neat
apiVersion: cilium.io/v2
kind: CiliumNode
metadata: 
  labels: 
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: pve3
    kubernetes.io/os: linux
    node-role.kubernetes.io/control-plane: ""
    node-role.kubernetes.io/dnsmasq: ""
    node-role.kubernetes.io/master: ""
  name: pve3
spec: 
  addresses: 
  - ip: 10.36.20.3
    type: InternalIP
  - ip: 10.112.0.17
    type: CiliumInternalIP
  - ip: 10.112.0.54
    type: CiliumInternalIP
  health: 
    ipv4: 10.112.0.31
  ipam: 
    podCIDRs: 
    - 10.112.0.0/24
    - fd00: :/112
```

**General Information**

- Cilium version (run `cilium version`): `1.9.1 975b66772`
- Kernel version (run `uname -a`): `5.3.10-1-pve`
- Orchestration system version in use: `v1.20.4`
- Link to relevant artifacts (policies, deployments scripts, ...)

**How to reproduce the issue**

1. run kube-controller-manager with `--cluster-cidr=10.112.0.0/12` and `--node-cidr-mask-size=26`
2. join nodes

**Expected behavior**

I guess in this case cilium should fail with the error, or respect podCIDR's network prefix from the node object.
Any case it should never make such conflicts.
