### ISSUE TITLE
eBPF masq breaks ClusterIP access on Kata/gVisor

### ISSUE THREAD

**Issue by Sh4d1** [cilium/cilium#15626]
## Bug report

**General Information**

- Cilium version (run `cilium version`) : 
```
Client: 1.9.5 079bdaf 2021-03-10T13:12:19-08:00 go version go1.15.8 linux/amd64
Daemon: 1.9.5 079bdaf 2021-03-10T13:12:19-08:00 go version go1.15.8 linux/amd64
```
- Kernel version (run `uname -a`) : 
```
Linux scw-test-dev-125-default-f3890dc7f73749b69a8f5 5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use (e.g. `kubectl version`, ...) : 
```
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip: 
https://static.ptrk.io/cilium-sysdump-20210409-142327.zip

**How to reproduce the issue**

1. Install gVisor on a Kubernetes cluster with a runtime class named `gvisor`
2. Apply the following:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dns
  namespace: default
spec:
  runtimeClassName: gvisor
  containers:
  - name: dns
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```
3. Exec into the pod and `dig google.com` : 
```
/ # dig google.com
;; reply from unexpected source: 100.64.0.7#53, expected 10.32.0.10#53
```

**Additional info**:

Tcpdump:
```
14:09:04.150057 IP 100.64.0.31.43762 > 10.32.0.10.domain: 44778+ [1au] A? google.com. (51)
14:09:04.150173 IP 100.64.0.31.43762 > 100.64.0.7.domain: 44778+ [1au] A? google.com. (51)
14:09:04.150706 IP 100.64.0.7.domain > 100.64.0.31.43762: 44778* 6/0/1 A 173.194.76.139, A 173.194.76.138, A 173.194.76.102, A 173.194.76.101, A 173.194.76.100, A 173.194.76.113 (207)
14:09:04.150730 IP 100.64.0.7.domain > 100.64.0.31.43762: 44778* 6/0/1 A 173.194.76.139, A 173.194.76.138, A 173.194.76.102, A 173.194.76.101, A 173.194.76.100, A 173.194.76.113 (207)
```

100.64.0.31 IP of the pod with gvisor
10.32.0.10 ClusterIP of coredns
100.64.0.7 Pod IP of coredns

**Comment by Sh4d1** [comment]
Same thing is happening with Kata containers by the way

**Comment by brb** [comment]
Thanks for the issue. What is your gVisor configuration?

What happens in the Kata case is that the host-reachable services cannot be applied, as your pods are running in separate VMs. Try disabling it with `kubeProxyReplacement=partial` and then enabling each individual feature you need for kube-proxy replacement (https://docs.cilium.io/en/v1.9/gettingstarted/kubeproxy-free/#kubeproxy-free).

**Comment by Sh4d1** [comment]
> Thanks for the issue. What is your gVisor configuration?

```toml
  [plugins.cri.containerd.untrusted]
    runtime_type = "io.containerd.runsc.v1"
  [plugins.cri.containerd.runtimes.runsc]
     runtime_type = "io.containerd.runsc.v1"
     [plugins.cri.containerd.runtimes.runsc.options]
       NoPivotRoot = false
       NoNewKeyring = false
       ShimCgroup = ""
       IoUid = 0
       IoGid = 0
       BinaryName = "/usr/local/bin/runsc"
       Root = ""
       CriuPath = ""
       SystemdCgroup = false
```

This is the containerd conf for gvisor, no additional conf on gvisor side.

For kata, as for gvisor, it works when I set `bpf-masquerade` to false. (Just need to verifiy for kata)
