### ISSUE TITLE
Proposal: Reduce the amount of lines generated when logging expired FQDN IPs

### ISSUE THREAD

**Issue by mvisonneau** [cilium/cilium#15935]
## Proposal

Reduce the amount of lines generated when logging expired FQDN IPs

**Is your feature request related to a problem?**

Trying out `v1.10.0-rc1`, I stumbled upon these new log lines:

```
{"dnsName":"foo.s3.eu-west-1.amazonaws.com.","ipAddr":"52.218.36.51","level":"warning","msg":"FQDN has multiple IPs. One IP has an expired TTL.","subsys":"fqdn"}
{"dnsName":"foo.s3.eu-west-1.amazonaws.com.","ipAddr":"52.218.96.19","level":"warning","msg":"FQDN has multiple IPs. One IP has an expired TTL.","subsys":"fqdn"}
{"dnsName":"foo.s3.eu-west-1.amazonaws.com.","ipAddr":"52.218.24.72","level":"warning","msg":"FQDN has multiple IPs. One IP has an expired TTL.","subsys":"fqdn"}

[~10k similar lines]

{"controller":"dns-garbage-collector-job","level":"info","msg":"FQDN garbage collector work deleted 1 name entries: foo.s3.eu-west-1.amazonaws.com.","subsys":"daemon"}
```

I have indeed a L7 egress CNP with the following configuration:

```yaml
egress:
    # Authorize outbound connectivity to necessary AWS components
  - toFQDNs:
      - matchName: sts.amazonaws.com
      - matchPattern: '*.s3.eu-west-1.amazonaws.com'
    toPorts:
      - ports:
          - port: '443'
            protocol: TCP
```

**Describe the solution you'd like**

It would be great to be able to reduce the verbosity of this feature as it seem to occur on each garbage collection cycle :bow:!
