### ISSUE TITLE
Egress rule ignored when using `toCIDRSet` with contiguous `except` cidrs

### ISSUE THREAD

**Issue by mogindi** [cilium/cilium#15952]
**General Information**

When creating `toCIDRSet` rule, with `except` cidrs, if 2 cidrs in `except` are contiguous ip blocks, the whole rule is ignored.

Note: I tested only with egress rule `CiliumClusterwideNetworkPolicy` but its probably reproducible with just `CiliumNetworkPolicy`, ingress or egress.

- Cilium version (run `cilium version`)
```
Client: 1.8.6 a527d2bbb 2020-12-04T14:29:52+01:00 go version go1.14.12 linux/amd64
Daemon: 1.8.6 a527d2bbb 2020-12-04T14:29:52+01:00 go version go1.14.12 linux/amd64
```

- Kernel version (run `uname -a`)
```
Linux reg1z1-compute-1 5.4.0-72-generic #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

- Orchestration system version in use (e.g. `kubectl version`, ...)
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.14", GitCommit:"f238f5142728be4033c37aa0ad69bf806090beae", GitTreeState:"clean", BuildDate:"2020-11-11T13:11:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.14", GitCommit:"f238f5142728be4033c37aa0ad69bf806090beae", GitTreeState:"clean", BuildDate:"2020-11-11T13:03:54Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**How to reproduce the issue**

1. Create pod and have CiliumEndpoint be created:
`kubectl run -i --tty busybox --image=busybox -n test --restart=Never -- sh`
2. Apply policy:
```
apiVersion: cilium.io/v2              
kind: CiliumClusterwideNetworkPolicy  
metadata:                             
  name: test                          
spec:                                 
  endpointSelector: {}                
  egress:                             
  - toCIDRSet:                        
    - cidr: 0.0.0.0/0                 
      except:                         
      - 192.168.0.0/24           
      - 192.168.1.0/24      #  contiguous cidr block
```
3. Try to access internet from pod. You can't.

In fact, no cidr rules show up:
```
$ kubectl -n kube-system exec -ti <cilium pod> -- cilium endpoint get <endpoint id> | grep "cidr\." | wc -l
0
```

**My amazing work around**

Merge consecutive CIDR blocks before feeding to the network policy

**What I think the issue is:**

Looking at the code, looks like the issue is somewhere here: 
https://github.com/cilium/cilium/blob/44099a46016360278381f9fd181853a88f695d99/pkg/ip/ip.go#L181-L186

1. Not a go expert, but modifying the slice that your looping through is not great practice. It looks like the indexes are getting messed up as the slice is changing in size
2. You can probably get duplicate and/or conflicting rules that way? Unless that's filtered later
4. Probably adding a `mergeConsecutiveCIDRs(removeCIDRs)` at the top of the function will fix the issue
