### ISSUE TITLE
--install-no-conntrack-iptables-rules prevents ipv4 masquerading 

### ISSUE THREAD

**Issue by Jean-Daniel** [cilium/cilium#16046]
## Bug report

When passing `--install-no-conntrack-iptables-rules`, the generated rules may prevent IPv4 masquerading (if iptables masquerading is use).

The pods packets are forwarded to the gateway, but the source address is not translated. (iptables NAT rules are ignored, despite being properly installed)

**General Information**

- Cilium version (run `cilium version`)
```
Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
Client: 1.10.0-rc1 efc15cd 2021-04-27T17:45:59-07:00 go version go1.16.3 linux/amd64
Daemon: 1.10.0-rc1 efc15cd 2021-04-27T17:45:59-07:00 go version go1.16.3 linux/amd64
```

- Kernel version (run `uname -a`)
`Linux 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

- Orchestration system version in use (e.g. `kubectl version`, ...)
```
Server Version: "v1.21.0"
```

**How to reproduce the issue**

Install cilium 1.10.0-rc1 using helm and the following values file:

```yaml
autoDirectNodeRoutes: true
bpf:
  masquerade: false
enableK8sEndpointSlice: true
enableXTSocketFallback: false
endpointRoutes:
  enabled: true
hostServices:
  enabled: true
ipam:
  operator:
    clusterPoolIPv4PodCIDR: "10.145.0.0/16"
    clusterPoolIPv6PodCIDR: "fd00:abba:96fb::/104"
ipv6:
  enabled: true
kubeProxyReplacement: "strict"
l7Proxy: false
nativeRoutingCIDR: "10.145.0.0/16"
nodePort:
  enabled: true
sessionAffinity: true
sockops:
  enabled: true
tunnel: "disabled"
```
