### ISSUE TITLE
Egress for destination CIDR 0.0.0.0/0 blocks all network connections

### ISSUE THREAD

**Issue by UbiquitousBear** [cilium/cilium#16147]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
- Kernel version (run `uname -a`)
- Orchestration system version in use (e.g. `kubectl version`, ...)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. Use the following egress rule
```
apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
metadata:
  name: egress-mailserver
spec:
  egress:
  - podSelector:
      matchLabels:
        # The following label selects default namespace
        io.kubernetes.pod.namespace: mailserver
    # Or use namespace label selector to select multiple namespaces
    # namespaceSelector:
    #  matchLabels:
    #    ns: default
  destinationCIDRs:
  - 0.0.0.0/0
  egressSourceIP: "51.195.x.x" 
```
2. curl http://checkip.amazonaws.com from a pod
 
Expected result: 51.195.x.x
Actual result: bash-5.0# curl http://checkip.amazonaws.com
curl: (6) Could not resolve host: checkip.amazonaws.com
