### ISSUE TITLE
.github: Scheduled job to cleanup leftover clusters

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#16209]
When GitHub jobs are cancelled, we have only 5 minutes to run cleanup steps, including deleting clusters for end-to-end tests. After those 5 minutes, the job is forcefully stopped and we may end up with leftover clusters.

A solution to this issue would be to have a schedule workflow to regularly check for leftover clusters and delete them. It could for instance delete all clusters older than the respective end-to-end test's timeout, to guarantee we only delete unused clusters. So for example, we would regularly check for GKE clusters older than [30min](https://github.com/cilium/cilium/blob/4a831f48ea9c0d333147d844c10b3424b1350982/.github/workflows/gke.yaml#L31) and delete them.

/cc @nebril

**Comment by auriaave** [comment]
This has been addressed using Cloud Custodian, and the following policy:

For AWS:
```
policies:
  - name: aws-cfn-delete
    description: |
      Delete stale and failed cloud formation stacks.
      Scope: AWS account.
    resource: aws.cfn
    filters:
      - or:
          - and:
              - type: value
                key: CreationTime
                value_type: age
                op: greater-than
                value: 0.125
          - and:
              - type: value
                key: StackStatus
                op: in
                value: [ DELETE_FAILED, ROLLBACK_COMPLETE, ROLLBACK_FAILED ]
    actions:
      - type: delete
        force: true
```

For Azure:
```
policies:
  - name: az-delete
    description: |
      Find and delete stale resource groups.
      Scope: Azure subscription.
    resource: azure.resourcegroup
    filters:
      - tag:expiry: present
      - type: value
        key: tag:expiry
        value_type: expiration
        op: less-than
        value: 0
    actions:
      - type: delete
```

For Google Cloud:
```
policies:
  - name: gcp-delete-gke
    description: |
      Find and delete stale GKE clusters.
      Scope: GCP project.
    resource: gcp.gke-cluster
    filters:
      - type: value
        key: createTime
        value_type: age
        op: greater-than
        value: 0.125
    actions:
      - type: delete

  - name: gcp-delete-gce
    description: |
      Find and delete stale GCE instances.
      Scope: GCP project.
    resource: gcp.instance
    filters:
      - tag:goog-gke-node: absent
      - type: value
        key: creationTimestamp
        value_type: age
        op: greater-than
        value: 0.125
    actions:
      - type: delete

  - name: gcp-delete-disk
    description: |
      Find and delete stale unused GCP disks.
      Scope: GCP project.
    resource: gcp.disk
    filters:
      - users: absent
      - lastDetachTimestamp: present
      - type: value
        key: creationTimestamp
        value_type: age
        op: greater-than
        value: 0.125
    actions:
      - type: delete
```
