### ISSUE TITLE
Cannot reach external endpoint with service ip when the external endpoint is one of k8s node

### ISSUE THREAD

**Issue by LeoQuote** [cilium/cilium#16235]
## Bug report

**General Information**

- Cilium version  `1.9.3 ae8661f14 2021-01-22T18:34:11+01:00 go version go1.15.6 linux/amd64`
- Kernel version `Linux borin3 5.4.66-gentoo #3 SMP Fri Oct 9 14:07:20 CST 2020 x86_64 AMD EPYC 7K62 48-Core Processor AuthenticAMD GNU/Linux`
- Orchestration system version in use `Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-12-21T08:52:16Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. Create an Endpoint and a service with same name using `kubectl apply` 
```
apiVersion: v1
kind: Service
metadata:
  name: kube-scheduler
spec:
  ports:
  - name: https-metrics
    port:  10259
    targetPort: 10259
    protocol: TCP

---

apiVersion: v1
kind: Endpoints
metadata:
  name: kube-scheduler
subsets:
  - addresses:
      - ip: 10.1.20.43
    ports:
    - name: https-metrics
      port:  10259
      protocol: TCP
```
2. use `kubectl -n kube-system get svc kube-scheduler -o wide ` to get svc ip and try to curl or nc the resource  `curl -v  10.102.61.101:10259`

normally it should return 403 forbidden but it just get stuck. Seems to be some network issue.

I wonder how can I debug it.

I ran `cilium bpf lb list` and found the broken service ` 10.102.61.101:10259   0.0.0.0:0 (216) [ClusterIP]`

I found a similar case https://github.com/cilium/cilium/issues/12513 , like this issue, the `EndpointSlice` for this manually created service is also not present. but when the endpoints are outside of cluster , things will go well, it can work, endpointslice is present.

hope I can get some clue about how to debug this issue.
