### ISSUE TITLE
Localredirectpolicies (lrp) on OKD breaks openshift-dns dns-node-resolver. Cilum 1.9.5

### ISSUE THREAD

**Issue by msheldyakov** [cilium/cilium#16247]
## Bug report
On http://okd.io/ cilium with Local redirect policies for dns service breaks resolving in openshift-dns/dns container dns-node-resolver.
Confirmed in 4 clusters.

```
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: nodelocal-dns
  namespace: openshift-dns
spec:
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        dns.operator.openshift.io/daemonset-dns: default
    toPorts:
      - name: dns-tcp
        port: '5353'
        protocol: TCP
      - name: dns
        port: '5353'
        protocol: UDP
  redirectFrontend:
    serviceMatcher:
      namespace: openshift-dns
      serviceName: dns-default

```
**General Information**

- Cilium version:  Client: 1.9.5 079bdaf 2021-03-10T13:12:19-08:00 go version go1.15.8 linux/amd64
- Kernel version: 5.10.19-200.fc33.x86_64
- Orchestration system version in use: 4.7.0-0.okd-2021-03-21-094146 / Kubernetes Version: v1.20.0-1054+bafe72fb05eddc-dirty

**How to reproduce the issue**

1. Open terminal in any openshift-dns/dns-default-XXXX pod. Container dns-node-resolver.
2. Try (env comes from openshift dns pod). Thats how openshift collects image registry ip for /etc/hosts 
dig -t A @"${NAMESERVER}" +short "${svc}.${CLUSTER_DOMAIN}"
it will respond with image registry service ip
3. Create LRP policy from "bug report" 
4. Try resolve again. It will fail with " ;; connection timed out; no servers could be reached"
5. Remove LRP policy - resolving from this container works.
6. Note: resolving works nice in other containers. Maybe openshift dns is somehow special. With LRP container connects to dns in the same pod(to itself).
