### ISSUE TITLE
Running Tailscale in a Cilium cluster

### ISSUE THREAD

**Issue by tux21b** [cilium/cilium#16266]
This was initially a question on the Slack channel. @brb was very kind and helped me to solve the issue quickly and @pchaigno asked me to documented the issue here.

# Scenario

I run a small bare-metal k8s cluster on Hetzner, mostly for being able to quickly host / deploy smaller projects. I really like the convenience of cert-manager (Let's Encrypt client) and Contour (ingress controller). I also run Emby (media center) at a PC at home. Sometimes I like to watch a movie while traveling, and therefore I decided to expose my Media PC via Tailscale and an Ingress object.

The setup looks basically like this:

``
Browser -> Contour Pod -> Cilium CNI -> k8s Cluster -> Tailscale -> Media PC
``

Emby runs on the Media-PC which is not part of the k8s Cluster. But the media PC and k8s cluster are connected via Tailscale.

# Setup

The setup required some tricks. Tailscale is running within the cluster as a static Pod with host networking enabled. This setup is currently not supported by Tailscale, but it seems to run fine. Alternatively, you can also install Tailscale the conventional way.

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tailscale
  name: tailscale
spec:
  containers:
  - name: tailscale
    image: tailscale:1.8.3
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_MODULE
    volumeMounts:
    - mountPath: /var/lib/tailscale
      name: data
    - mountPath: /dev/net/tun
      name: devnet
  hostNetwork: true
  dnsPolicy: ClusterFirst
  volumes:
  - name: data
    hostPath:
      path: /var/lib/tailscale
  - name: devnet
    hostPath:
      path: /dev/net/tun
```

Afterwards I was able to access Emby on the k8s Host via the Tailscale-IP (100.94.48.18) of my media PC at home. Unfortunately its not possible to specify IP-Addresses in an Ingress (or Contour's HTTPRouter) object directly. Therefore I have created a service and it's endpoint manually:

```
apiVersion: v1
kind: Service
metadata:
  name: emby
  namespace: watch
spec:
  clusterIP: None
  ports:
  - name: http
    protocol: TCP
    port: 8096
    targetPort: 8096
---
apiVersion: v1
kind: Endpoints
metadata:
  name: emby
  namespace: watch
  labels:
    kubernetes.io/service-name: emby
subsets:
  - addresses:
    - ip: 100.94.48.18
    ports:
    - port: 8096
      name: http
```

The clusterIP can be set to `None` (aka headless service) since my endpoint is already a static IP that does not change.

Finally I was able to create the Ingress object (I used the slightly more powerful HTTPProxy in this case):

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: http
  namespace: watch
spec:
  virtualhost:
    fqdn: emby.example.com
    tls:
      secretName: tls-cert
  routes:
    - services:
      - name: emby
        port: 8096
      timeoutPolicy:
        response: infinity
```

This setup worked fine with flannel, but didn`t work with Cilium. All packages sent to the Emby server got lost somewhere.

# Solution

@brb figured out that the problem was probably related to masquerading. Tailscale gets IP-Packages with the Pod-IP and does not accept them / does not know how to route them. And indeed, advertising the Pod-IP range (10.0.0.8/16 in my case) to the Tailscale network solved the problem.

The command that was required was:

```
tailscale up --hostname node01 --advertise-routes 10.0.0.0/16
```
(followed by a manual click on approve in the Tailscale Admin UI)

An alternative approach would be to fix masquerading, but I think it has also advantages of being able to access the k8s network from home.
