### ISSUE TITLE
Helm template rendering error when specifying both bgp.enabled and operator.resources

### ISSUE THREAD

**Issue by rkage** [cilium/cilium#16272]
## Bug report
**General Information**

- Cilium version: 1.10.0
- Kernel version: 5.11.0-1008-raspi
- Orchestration system version in use: kubectl/1.21.1, helm/3.5.4

**How to reproduce the issue**

1. Create a `values.yaml` file with the following contents:
```
operator:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 384Mi

bgp:
  enabled: true
  announce:
    loadbalancerIP: true
```

2. `helm install cilium cilium/cilium -f values.yaml`

Error reported by helm:
`YAML parse error on cilium/templates/cilium-operator-deployment.yaml: error converting YAML to JSON: yaml: line 92: did not find expected key`

It appears the lines 231-239 of the `cilium-operator-deployment.yaml` file are out of order; https://github.com/cilium/cilium/blob/d3b54929c51235850a1132efa558c0554f961886/install/kubernetes/cilium/templates/cilium-operator-deployment.yaml#L231-L239

The `{{- if .Values.bgp.enabled }}` block should be moved above the `{{- if .Values.operator.resources }}` block.
