### ISSUE TITLE
Connectivity issues with IPsec after node reboot

### ISSUE THREAD

**Issue by martin31821** [cilium/cilium#16279]
## Bug report

We run flatcar-linux in our production clusters and since we updated to cilium 1.9 pods don't get connectivity after node reboots.
To fix it, we need to manually delete the cilium-agent pod on the corresponding node.
`cilium-health status` reports host connectivity to other nodes, but both ICMP to stack and HTTP to stack report timeouts.

Reproducible on both cilium 1.9.6 and 1.9.7, against recent Flatcar Linux stable versions (tested against 2765.2.3, 2765.4, 2765.2.5)
/cc: @johannwagner @Jasper-Ben

**General Information**

- Cilium version: 1.9.7
- Kernel version: 5.9.11, 5.9.16, 5.10.16, 5.10.25, 5.10.32, 5.10.37
- Orchestration system version: Kubernetes 1.20.7
- Link to relevant artifacts: To be followed, I'm working on building a reproducible deployment set.
- Generate and upload a system zip: (To be followed from reproducible deployment)

**How to reproduce the issue**

1. Setup Cilium 1.9.7 on a Cluster consisting of Flatcar Linux nodes
2. Reboot one node
3. See that the pods don't get connectivity on the rebooted node, until the cilium agent on this node is deleted and recreated

**Comment by martin31821** [comment]
Just got it reproduced in a test environment, I'll be preparing that into a repo and link it here. 
After deploying the connectivity test and rebooting one node, I see the following:

`cilium-health status` (on the master node, not rebooted)
```
Probe time:   2021-05-22T12:37:04Z
Nodes:
  master-test-node (localhost):
    Host connectivity to a.b.c.110:
      ICMP to stack:   OK, RTT=546.361µs
      HTTP to agent:   OK, RTT=404.004µs
    Endpoint connectivity to 10.0.1.172:
      ICMP to stack:   OK, RTT=528.017µs
      HTTP to agent:   OK, RTT=405.057µs
  worker-test-node:
    Host connectivity to a.b.c.233:
      ICMP to stack:   OK, RTT=1.081699ms
      HTTP to agent:   OK, RTT=1.396567ms
    Endpoint connectivity to 10.0.0.146:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.0.0.146:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

On the worker node (after reboot):
```
Probe time:   2021-05-22T12:39:37Z
Nodes:
  worker-test-node (localhost):
    Host connectivity to a.b.c.233:
      ICMP to stack:   OK, RTT=627.376µs
      HTTP to agent:   OK, RTT=520.044µs
    Endpoint connectivity to 10.0.0.146:
      ICMP to stack:   OK, RTT=580.217µs
      HTTP to agent:   OK, RTT=319.138µs
  master-test-node:
    Host connectivity to a.b.c.110:
      ICMP to stack:   OK, RTT=1.461229ms
      HTTP to agent:   OK, RTT=655.739µs
    Endpoint connectivity to 10.0.1.172:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.0.1.172:4240/hello": dial tcp 10.0.1.172:4240: i/o timeout (Client.Timeout exceeded while awaiting headers)
```

Connectivity test was deployed before the worker node was rebooted and afterwards I get this result:
![Screenshot from 2021-05-22 14-38-48](https://user-images.githubusercontent.com/5557633/119226990-2a620280-bb0c-11eb-88c7-586d8648d416.png)

My cilium config looks like this:
```yaml

# Source: cilium/templates/cilium-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
data:
  identity-allocation-mode: crd
  cilium-endpoint-gc-interval: "5m0s"

  debug: "false"
  enable-policy: "default"
  enable-ipv4: "true"
  enable-ipv6: "true"
  custom-cni-conf: "false"
  enable-bpf-clock-probe: "true"
  monitor-aggregation: medium
  monitor-aggregation-interval: 5s
  monitor-aggregation-flags: all
  bpf-map-dynamic-size-ratio: "0.01"
  bpf-policy-map-max: "16384"
  bpf-lb-map-max: "65536"
  preallocate-bpf-maps: "false"

  sidecar-istio-proxy-image: "cilium/istio_proxy"

  cluster-name: default
  cluster-id: ""

  tunnel: vxlan
  enable-l7-proxy: "true"

  wait-bpf-mount: "false"

  masquerade: "true"
  enable-bpf-masquerade: "true"
  enable-ipsec: "true"

  ipsec-key-file: /etc/ipsec/keys
  enable-xt-socket-fallback: "true"
  install-iptables-rules: "true"

  auto-direct-node-routes: "false"
  enable-bandwidth-manager: "false"
  enable-local-redirect-policy: "false"
  kube-proxy-replacement:  "probe"
  kube-proxy-replacement-healthz-bind-address: ""
  enable-health-check-nodeport: "true"
  node-port-bind-protection: "true"
  enable-auto-protect-node-port-range: "true"
  enable-session-affinity: "true"
  enable-endpoint-health-checking: "true"
  enable-health-checking: "true"
  enable-well-known-identities: "false"
  enable-remote-node-identity: "true"
  operator-api-serve-addr: "127.0.0.1:9234"
  enable-hubble: "false"
  ipam: "cluster-pool"
  cluster-pool-ipv4-cidr: "10.0.0.0/8"
  cluster-pool-ipv6-cidr: "fd00::/104"
  cluster-pool-ipv4-mask-size: "24"
  cluster-pool-ipv6-mask-size: "120"
  disable-cnp-status-updates: "true"
---
```
