### ISSUE TITLE
BGP integration doesn't work when `node-selectors` are used in the BGP configmap

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#16340]
## Bug report

**General Information**

- v1.10.0, master

**How to reproduce the issue**

1. Deploy with BGP enabled and configure BGP with node selectors. For example:
```
      node-selectors:
      - match-expressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [ocp-dd8732c4-worker-0.ocp.n8m.io, ocp-dd8732c4-worker-1.ocp.n8m.io, ocp-dd8732c4-worker-2.ocp.n8m.io]
```

The expected behavior is that Cilium will peer with the nodes with the above hostnames.
