### ISSUE TITLE
hubble-relay: failed to create gRPC client

### ISSUE THREAD

**Issue by alex1989hu** [cilium/cilium#16361]
## Bug report

After upgrading from Cilium `v1.9.7` to Cilium `v1.10.0` hubble-relay stopped working: it can not connect to `node:4244`.

I did not change anything in Helm Chart values.yaml file, except Chart version replace.

I thought issue caused :
- by `CiliumNetworkPolicy` -> removed -> nothing changed.
- relay tls server is needed, so enabled option `hubble.relay.tls.server.enabled`: true > rerun cronjob -> killed `hubble-relay` Pod -> nothing changed.

Sample log lines:
> level=info msg=Connecting address="3.249.66.182:4244" hubble-tls=true peer=prod-k8s-master-3 subsys=hubble-relay
level=warning msg="Failed to create gRPC client" address="3.249.66.182:4244" error="context deadline exceeded" hubble-tls=true next-try-in=10s peer=prod-k8s-master-3 subsys=hubble-relay

`next-try-in` is constantly increasing but nothing helped.

**General Information**

- Cilium version (run `cilium version`)
> Client: 1.10.0 952d9d3 2021-05-19T18:42:32+02:00 go version go1.16.4 linux/amd64
Daemon: 1.10.0 952d9d3 2021-05-19T18:42:32+02:00 go version go1.16.4 linux/amd64

- Kernel version (run `uname -a`)
> Linux prod-k8s-master-3 5.10.29-talos #1 SMP Wed Apr 28 14:43:26 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, ...)
> Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)
N/A

- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

Can not attach cilium-sysdump - file size is `52M`

**How to reproduce the issue**

Do not know.

**Comment by rolinh** [comment]
I am unable to reproduce. Could you please share your Helm install options (at least the Hubble section) as well as the upgrade command?

**Comment by alex1989hu** [comment]
Sure, @rolinh 

Cilium installation and upgrading is managed by [ArgoCD](https://argo-cd.readthedocs.io/en/stable/).

Chart.yaml

```
apiVersion: v2
appVersion: "1.0"
description: Helm chart for Cilium
name: cilium
version: 0.0.1
dependencies:
- name: cilium
  version: 1.10.0
  repository: "@cilium"
```
values.yaml

```yaml
cilium:
  bpf:
    policyMapMax: 40960
  hubble:
    enabled: true
    metrics:
      enabled:
      - drop:sourceContext=pod;destinationContext=pod
      - icmp
      - tcp
      - flow
    relay:
      enabled: true
    serviceMonitor:
      enabled: true
    tls:
      enabled: true
      auto:
        enabled: true
        method: cronJob
        certValidityDuration: 70
        schedule: "0 0 1 */2 *"
    ui:
      enabled: true
      backend:
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 32Mi
      frontend:
        resources:
          limits:
            cpu: 1000m
            memory: 160Mi
          requests:
            cpu: 100m
            memory: 96Mi
  operator:
    replicas: 2
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
```
