### ISSUE TITLE
k8s deployment restart causes brief outage with cilium and kubeProxy disabled

### ISSUE THREAD

**Issue by ajitre** [cilium/cilium#16518]
## Bug report

**General Information**

- Cilium version : 1.9.8
- Kernel version : 5.8.0-1035-aws #37~20.04.1-Ubuntu
- Orchestration system version in use: k8s v1.20.7 (running on AWS setup with kops 1.20.1)

**How to reproduce the issue**

1. Install k8s 1.20.7 with kops (1.20.1) on AWS
2. Disable kubeProxy and enable Cilium nodeport : kops cluster spec: 
```
 kubeProxy:
   enabled: false
[..]
 networking:
   cilium:
     enableNodePort: true
```
 
2. Create a deployment with spec: 
```spec:
  type: LoadBalancer
  externalTrafficPolicy: Local 
  ```
3. When I rollout restart the deployment, there is a brief outage because it seems like with cilium enabled with KubeProxy disabled, traffic continues going to the pod that has been set in Terminating sate by k8s.
