### ISSUE TITLE
datapath: Istio and Linkerd do not work with socket-LB

### ISSUE THREAD

**Issue by brb** [cilium/cilium#16583]
This is a placeholder issue for https://github.com/cilium/cilium/pull/13882.

TLDR; the socket-LB based service translation happens before the Istio's iptables rule in the pod netns which makes the Envoy proxy to match on the VIP, as it matches on SO_ORIGINAL_DST.

**Comment by alex-berger** [comment]
**Linkerd**

Linkerd injects an [init container](https://github.com/linkerd/linkerd2-proxy-init) and a [proxy sidecar](https://github.com/linkerd/linkerd2-proxy) into meshed Pods. The `linkerd-init` container will setup some iptable rules to forward all traffic to the `linkerd-proxy`sidecar. Those iptables rules look like this:

```
2021/06/16 21:09:16 :; iptables -t nat -N PROXY_INIT_REDIRECT -m comment --comment proxy-init/redirect-common-chain/1623877756
2021/06/16 21:09:16 :; iptables -t nat -A PROXY_INIT_REDIRECT -p tcp --match multiport --dports 4190,4191,8443,8080 -j RETURN -m comment --comment proxy-init/ignore-port-4190,4191,8443,8080/1623877756
2021/06/16 21:09:16 :; iptables -t nat -A PROXY_INIT_REDIRECT -p tcp -j REDIRECT --to-port 4143 -m comment --comment proxy-init/redirect-all-incoming-to-proxy-port/1623877756
2021/06/16 21:09:16 :; iptables -t nat -A PREROUTING -j PROXY_INIT_REDIRECT -m comment --comment proxy-init/install-proxy-init-prerouting/1623877756
2021/06/16 21:09:16 :; iptables -t nat -N PROXY_INIT_OUTPUT -m comment --comment proxy-init/redirect-common-chain/1623877756
2021/06/16 21:09:16 :; iptables -t nat -A PROXY_INIT_OUTPUT -m owner --uid-owner 2102 -o lo ! -d 127.0.0.1/32 -j PROXY_INIT_REDIRECT -m comment --comment proxy-init/redirect-non-loopback-local-traffic/1623877756
2021/06/16 21:09:16 :; iptables -t nat -A PROXY_INIT_OUTPUT -m owner --uid-owner 2102 -j RETURN -m comment --comment proxy-init/ignore-proxy-user-id/1623877756
2021/06/16 21:09:16 :; iptables -t nat -A PROXY_INIT_OUTPUT -o lo -j RETURN -m comment --comment proxy-init/ignore-loopback/1623877756
2021/06/16 21:09:16 :; iptables -t nat -A PROXY_INIT_OUTPUT -p tcp -j REDIRECT --to-port 4140 -m comment --comment proxy-init/redirect-all-outgoing-to-proxy-port/1623877756
2021/06/16 21:09:16 :; iptables -t nat -A OUTPUT -j PROXY_INIT_OUTPUT -m comment --comment proxy-init/install-proxy-init-output/1623877756
```

**Comment by brb** [comment]
Linkerd proxy is using `SO_ORIGINAL_DST` too. So the same solution based on a BPF getsockopt program should work for Istio and Linkerd.

**Comment by brb** [comment]
After offline discussion with @borkmann it became clear that some kernel work is still required to make the BPF getsockopt based solution viable.

**Comment by alex-berger** [comment]
@brb Just for my understanding, but that does not block the solution (`--bpf-lb-sock-hostns-only: true`) implemented in https://github.com/cilium/cilium/pull/13882?

I am asking, because `--bpf-lb-sock-hostns-only: true` would likely be an acceptable solution to this problem for the time being (of course we have to first test it, but for that we need a release that supports `--bpf-lb-sock-hostns-only: true`).

**Comment by brb** [comment]
It doesn't block. I'm currently reviving that PR in https://github.com/cilium/cilium/pull/17154.

**Comment by zhengzepeng** [comment]
Define a crd to let us to config rules, like iptables rule, or maybe self define rules (by ebpf). So if istio want to redirect traffic, submit the own crd yaml. I think this is a good choice.

**Comment by brb** [comment]
> Define a crd to let us to config rules, like iptables rule, or maybe self define rules (by ebpf). So if istio want to redirect traffic, submit the own crd yaml. I think this is a good choice.

@zhengzepeng Could you elaborate more on this? We don't have control over rules Istio installs.

**Comment by zhengzepeng** [comment]
istio auto inject a init container and a proxy container into a pod(by webhook). Init container will apply iptables rule, so all traffic will redirect to proxy container. Proxy container receive trafiics and do something like lb and so on...

what init container do like that:
```
Environment:
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=

Variables:
----------
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337,1338
PROXY_GID=1337,1338
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
DNS_SERVERS=[],[]

Writing following contents to rules file:  /tmp/iptables-rules-1632585621432198181.txt390483472
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1338 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1338 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT

iptables-restore --noflush /tmp/iptables-rules-1632585621432198181.txt390483472
Writing following contents to rules file:  /tmp/ip6tables-rules-1632585621444146495.txt898330671

ip6tables-restore --noflush /tmp/ip6tables-rules-1632585621444146495.txt898330671
iptables-save 
# Generated by iptables-save v1.8.4 on Sat Sep 25 16:00:21 2021
*mangle
:PREROUTING ACCEPT [859912:382037236]
:INPUT ACCEPT [859912:382037236]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [795462:2387612104]
:POSTROUTING ACCEPT [795462:2387612104]
COMMIT
# Completed on Sat Sep 25 16:00:21 2021
# Generated by iptables-save v1.8.4 on Sat Sep 25 16:00:21 2021
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1338 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1338 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1338 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Sat Sep 25 16:00:21 2021
# Generated by iptables-save v1.8.4 on Sat Sep 25 16:00:21 2021
*filter
:INPUT ACCEPT [859912:382037236]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [795462:2387612104]
COMMIT
# Completed on Sat Sep 25 16:00:21 2021
```
the init container like that
```
apiVersion: v1
kind: Pod
metadata:
  name: reviews-v1-86c9d797c7-88szc
  namespace: default
spec:
  ...
  initContainers:
  - args:
    - istio-iptables
    - -p
    - "15001"
    - -z
    - "15006"
    - -u
    - 1337,1338
    - -m
    - REDIRECT
    - -i
    - '*'
    - -x
    - ""
    - -b
    - '*'
    - -d
    - 15090,15021,15020
    image: istio/proxyv2:1.9.7
    imagePullPolicy: IfNotPresent
    name: istio-init
    resources:
      limits:
        cpu: "2"
        memory: 512Mi
      requests:
        cpu: "1"
        memory: 256Mi
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        drop:
        - ALL
      privileged: true
      readOnlyRootFilesystem: false
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: bookinfo-reviews-token-9c5sp
      readOnly: true
  ...
```

So if cilium support some crd to let us to config some rules like iptable rules or self define rules(ebpf), istio doesn't need to auto inject a init container(just modify webhook logic), just apply a yaml to apply some rules to achive redirect target.

And i think the rule will be so simple. Just redirect the traffic to 15001 port (outbound) or 15006 port (inbound). Maybe add some filtering rules.

Just like that:
```
apiVersion: "cilium.io/v2"
kind: CiliumLocalRulePolicy
metadata:
  name: "istio-redirect-rules"
spec:
  selector:
    security.istio.io/tlsMode: istio
  inbound:
    filters: 
      ...
    toPort:
      port: "15006"
      protocol: TCP
  outbound:
    filters:
      ...
    toPort:
      port: "15001"
      protorol: TCP
```

So if cilium support this option, it means it has less to do with istio.
