### ISSUE TITLE
Egress policy for traffic to external k8s services

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#1668]
This is a first step to handle egress traffic to services.

This issue is about headless k8s services.

Example policy which should be possible to create and enforce:

```
spec:
  endpointSelector:
    matchLabels:
      id: app1
  egress:
    toServices:
      - k8s-service:
        matchLabels:
          svc: my-service
```

Documentation on services: https://kubernetes.io/docs/concepts/services-networking/service/
