### ISSUE TITLE
DNS request from hostNetwork pods cannot be delivered to local backend with LRP

### ISSUE THREAD

**Issue by Weil0ng** [cilium/cilium#16694]
When doing `nslookup` from within a hostNetwork pod with NodelocalDNS + Cilium (full KRP), DNS requests time out. I do not see any dropped packets with `cilium monitor -t drop`. Running `tcpdump` on the veth of the local node-cache backend pod doesn't show anything, aka the packets never hit local backend pot.

**General Information**

- Cilium version (run `cilium version`): 
   Client: 1.9.5 caf84d780 2021-04-23T00:39:47+00:00 go version go1.15.8 linux/amd64

- Kernel version (run `uname -a`):
   Linux gke-nld-default-pool-5a5e9ec3-8llq 5.4.104+ SMP Tue Apr 6 09:49:56 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux

- Orchestration system version in use (e.g. `kubectl version`, ...)
GKE cluster v1.20.6-gke.1400

**How to reproduce the issue**

1. Deploy NodelocalDNS with Cilium following [gsg](https://docs.cilium.io/en/v1.9/gettingstarted/local-redirect-policy/#node-local-dns-cache)
2. Deploy following pod and do `nslookup` from within:
```
apiVersion: v1
kind: Pod
metadata:
        name: dnsclienthostnet1
spec:
  dnsPolicy: ClusterFirstWithHostNet
  hostNetwork: true
  containers:
      - image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.1
        name: dnsclient
        resources:
                limits:
                        cpu: "0.1"
                requests:
                        cpu: 100m
        command: ["sh", "-c"]
        args: ["sleep 36000"]
```
Note this issue only happens when the pod has `dnsPolicy: ClusterFirstWithHostNet`.
