### ISSUE TITLE
Resolving `service.namespace` should work when `rules.dns: [matchPattern: '*.*.svc.cluster.local']` is allowed

### ISSUE THREAD

**Issue by sciolgono** [cilium/cilium#16740]
## Proposal / RFE

With the following CiliumNetworkPolicy, pods in the namespace `test` can resolve and access `foo.bar.svc.cluster.local` but unfortunately they can't resolve `foo.bar` which breaks many setups. Would be really cool if this worked.

The goal here is to stop pods from phoning home or even ex-filtrating data by querying public DNS records like `bG90cy1hbmQtbG90cy1vZi1lbmNvZGVkLWRhdGEK.domain-controlled-by-attacker.example.com`.

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-the-bare-minimum
  namespace: test
spec:
  endpointSelector:
    matchLabels: {}
  egress:
    - toEndpoints:
        - matchLabels:
            'k8s:io.kubernetes.pod.namespace': kube-system
            'k8s:k8s-app': kube-dns
      toPorts:
        - ports:
            - port: '53'
              protocol: ANY
          rules:
            dns:
              - matchPattern: '*.*.svc.cluster.local'
    - toServices:
        - k8sService:
            serviceName: foo
            namespace: bar
      toPorts:
        - ports:
            - port: '80'
              protocol: TCP
```
