### ISSUE TITLE
Nodelocaldns does not work after Cilium deploy/upgrade

### ISSUE THREAD

**Issue by rearden-steel** [cilium/cilium#16906]
## Bug report

**General Information**

- Cilium version (run `cilium version`): tried from 1.9.8 to 1.10.3
- Kernel version (run `uname -a`): `5.4.0-77-generic`
- Orchestration system version in use (e.g. `kubectl version`, ...) `v1.21.1`
- Link to relevant artifacts (policies, deployments scripts, ...)
Cilium deployment:
```
helm upgrade --install cilium cilium/cilium --version 1.10.3 \
  --namespace kube-system \
  --set kubeProxyReplacement=strict \
  --set k8sServiceHost=127.0.0.1 \
  --set k8sServicePort=6443 \
  --set tunnel="disabled" \
  --set ipam.mode="kubernetes" \
  --set etcd.clusterDomain="abc.prod" \
  --set nativeRoutingCIDR="10.233.0.0/17" \
  --set localRedirectPolicy=true \
  --set hubble.listenAddress=":4244" \
  --set hubble.relay.enabled=true \
  --set hubble.ui.enabled=true \
  --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,http}"
```
And kube-router with BGP.

**How to reproduce the issue**

1. Install fresh Kubernetes cluster via kubespray with nodelocaldns and no CNI.
2. Deploy cilium via Helm.
3.  Run test pod and check DNS is not working:
```
kubectl run -it --restart=Never test3 --image=tutum/dnsutils -n default -- /bin/bash
root@test3:/# nslookup google.com 169.254.25.10
;; connection timed out; no servers could be reached
```
4. Run the same test from host system:
```
root@worker2:~# nslookup google.com 169.254.25.10
Server:         169.254.25.10
Address:        169.254.25.10#53

Non-authoritative answer:
Name:   google.com
Address: 142.250.186.142
```

I've tried adding LRP without success.
Here is my LRP:
```
apiVersion: "cilium.io/v2"
kind: CiliumLocalRedirectPolicy
metadata:
  name: "nodelocaldns"
  namespace: kube-system
spec:
  redirectFrontend:
    serviceMatcher:
      serviceName: coredns
      namespace: kube-system
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: nodelocaldns
    toPorts:
      - port: "53"
        name: dns
        protocol: UDP
      - port: "53"
        name: dns-tcp
        protocol: TCP
```

Once I've got working configuration (without LRP) by restarting pods and rebooting nodes — but this is crazy, everything stopped working after upgrading Cilium 1.10.2 to 1.10.3. Rolling back to 1.10.2 did not resolve the issue.

**Comment by aditighag** [comment]
@rearden-steel Just to confirm, you followed the steps given in the guide - https://docs.cilium.io/en/v1.10/gettingstarted/local-redirect-policy/#node-local-dns-cache? Can you attach cilium sysdump from your cluster? /cc @Weil0ng

**Comment by rearden-steel** [comment]
> @rearden-steel Just to confirm, you followed the steps given in the guide - https://docs.cilium.io/en/v1.10/gettingstarted/local-redirect-policy/#node-local-dns-cache? Can you attach cilium sysdump from your cluster? /cc @Weil0ng

Nodelocaldns has been deployed by kubespray, but it's config is standard.
As I mentioned above, I was able to make it work by rebooting nodes.
After Cilium upgrade DNS stopped working.
Here is the [dump](https://drive.google.com/file/d/1edxIBShWde19T1ladPq7LchyD98CuYpy/view?usp=sharing)

**Comment by rearden-steel** [comment]
What happens on tcpdump:
```
root@worker2:~# tcpdump -i any -enn "host 169.254.25.10 and port 53"
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked v1), capture size 262144 bytes
23:55:02.387794  In 2a:67:fe:67:19:07 ethertype IPv4 (0x0800), length 93: 10.233.70.248.43806 > 169.254.25.10.53: 10825+ A? google.com.default.svc.mycluster.prod. (49)
23:55:02.387839 Out 3e:a3:0b:35:e9:62 ethertype IPv4 (0x0800), length 93: 10.19.0.81.43806 > 169.254.25.10.53: 10825+ A? google.com.default.svc.mycluster.prod. (49)
23:55:07.387898  In 2a:67:fe:67:19:07 ethertype IPv4 (0x0800), length 93: 10.233.70.248.43806 > 169.254.25.10.53: 10825+ A? google.com.default.svc.mycluster.prod. (49)
23:55:07.387944 Out 3e:a3:0b:35:e9:62 ethertype IPv4 (0x0800), length 93: 10.19.0.81.43806 > 169.254.25.10.53: 10825+ A? google.com.default.svc.mycluster.prod. (49)
23:55:12.388068  In 2a:67:fe:67:19:07 ethertype IPv4 (0x0800), length 93: 10.233.70.248.43806 > 169.254.25.10.53: 10825+ A? google.com.default.svc.mycluster.prod. (49)
23:55:12.388109 Out 3e:a3:0b:35:e9:62 ethertype IPv4 (0x0800), length 93: 10.19.0.81.43806 > 169.254.25.10.53: 10825+ A? google.com.default.svc.mycluster.prod. (49)
```

where 10.19.0.81 is node IP, 10.233.70.248 is test pod IP.

**Comment by Weil0ng** [comment]
I see in the dump that nodelocaldns pods are deployed in hostNetwork mode (it has an ip in the node cidr range), can you confirm? For it to work with Cilium, we do need to deploy it in non-hostNetwork mode as described in https://docs.cilium.io/en/v1.10/gettingstarted/local-redirect-policy/#node-local-dns-cache

**Comment by Weil0ng** [comment]
> As I mentioned above, I was able to make it work by rebooting nodes.

Can you check if traffic is actually going to the nodelocaldns pods? My suspicion is that it is not, because without LRP, nodelocaldns would simply be skipped.

**Comment by rearden-steel** [comment]
I've redeployed node-local-dns using templates from docs. Now it does not bind on host interface.
I've applied LRP.
Does not work anyway...

```
root@test5:/# nslookup google.com 10.233.0.3
Server:		10.233.0.3
Address:	10.233.0.3#53

Non-authoritative answer:
Name:	google.com
Address: 142.250.186.142

root@test5:/# nslookup google.com
;; connection timed out; no servers could be reached
```

**Comment by rearden-steel** [comment]
I've checked LRP in cilium pod:
```
root@worker2:/home/cilium# cilium lrp list
LRP namespace   LRP name       FrontendType                Matching Service
kube-system     nodelocaldns   clusterIP + all svc ports   kube-system/coredns
                |              10.233.0.3:9153/TCP ->
                |              10.233.0.3:53/UDP -> 10.233.70.84:53(kube-system/node-local-dns-vmq7x),
                |              10.233.0.3:53/TCP -> 10.233.70.84:53(kube-system/node-local-dns-vmq7x),
```
Querying 10.233.0.3 works:
```
root@test6:/# nslookup google.com. 10.233.0.3
Server:		10.233.0.3
Address:	10.233.0.3#53

Non-authoritative answer:
Name:	google.com
Address: 142.250.186.110
```

So should I change my pods to use 10.233.0.3 in resolv.conf and it will be a solution?

**Comment by rearden-steel** [comment]
BINGO.
I've created the second LRP with IP matcher and it works now.
```
apiVersion: "cilium.io/v2"
kind: CiliumLocalRedirectPolicy
metadata:
  name: "nodelocaldns-ip"
  namespace: kube-system
spec:
  redirectFrontend:
    addressMatcher:
      ip: "169.254.25.10"
      toPorts:
        - name: dns-tcp
          port: "53"
          protocol: TCP
        - name: dns
          port: "53"
          protocol: UDP
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: node-local-dns
    toPorts:
      - port: "53"
        name: dns
        protocol: UDP
      - port: "53"
        name: dns-tcp
        protocol: TCP

root@worker2:/etc# cilium lrp list
LRP namespace   LRP name          FrontendType       Matching Service
kube-system     nodelocaldns-ip   IP + named ports
                |                 169.254.25.10:53/TCP -> 10.233.70.84:53(kube-system/node-local-dns-vmq7x),
                |                 169.254.25.10:53/UDP -> 10.233.70.84:53(kube-system/node-local-dns-vmq7x),
kube-system     nodelocaldns      clusterIP + all svc ports   kube-system/coredns
                |                 10.233.0.3:9153/TCP ->
                |                 10.233.0.3:53/UDP -> 10.233.70.84:53(kube-system/node-local-dns-vmq7x),
                |                 10.233.0.3:53/TCP -> 10.233.70.84:53(kube-system/node-local-dns-vmq7x),
```

**Comment by Weil0ng** [comment]
I don't think you need the second LRP for it to work in general, I can verify that in my setup the first one alone works fine, although there's a known issue that it doesn't work for hostNetwork client pods, were you testing nslookup from a hostNetwork pod?

**Comment by aditighag** [comment]
> I've created the second LRP with IP matcher and it works now.

The addressMatcher LRP isn't meant to be configured for the node-local dns use case. Kube-dns clusterIP can change, and you'll have to re-create the LRP every time it does.

**Comment by aditighag** [comment]
> I've checked LRP in cilium pod:
> 
> ```
> root@worker2:/home/cilium# cilium lrp list
> LRP namespace   LRP name       FrontendType                Matching Service
> kube-system     nodelocaldns   clusterIP + all svc ports   kube-system/coredns
>                 |              10.233.0.3:9153/TCP ->
>                 |              10.233.0.3:53/UDP -> 10.233.70.84:53(kube-system/node-local-dns-vmq7x),
>                 |              10.233.0.3:53/TCP -> 10.233.70.84:53(kube-system/node-local-dns-vmq7x),
> ```
> 
> Querying 10.233.0.3 works:
> 
> ```
> root@test6:/# nslookup google.com. 10.233.0.3
> Server:		10.233.0.3
> Address:	10.233.0.3#53
> 
> Non-authoritative answer:
> Name:	google.com
> Address: 142.250.186.110
> ```
> 
> So should I change my pods to use 10.233.0.3 in resolv.conf instead of 169.254.24.10 and it will be a solution?

LRP is working as expected for the nodeLocal DNS use case. Node-local dns cache works transparently, which means DNS requests destined to the **kube-dns clusterIP** are redirected to the node-local dns cache pod. See the office documentation - https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/#architecture-diagram. 
I'm closing the issue since based on your comments things are working as expected

**Comment by atsai1220** [comment]
In case anyone runs into this from the Internet, restarting Cilium operator got the ball rolling.

We got stuck configuring `CiliumLocalRedirectPolicy`. In our environment with Cilium 1.14.4, we had to specify `.spec.redirectFrontend.serviceMatcher.toPorts` otherwise the LRP list does not show the endpoints and traffic is not routed to node-local dns cache.

Here are the steps to verify:

1. Create this `CiliumLocalRedirectPolicy` without `.spec.redirectFrontend.serviceMatcher.toPorts`. This is as described in the [documentation](https://docs.cilium.io/en/v1.14/network/kubernetes/local-redirect-policy/#node-local-dns-cache) and the provided [example](https://raw.githubusercontent.com/cilium/cilium/v1.14/examples/kubernetes-local-redirect/node-local-dns-lrp.yaml).

```yaml
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: node-local-dns
  namespace: kube-system
spec:
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: node-local-dns
    toPorts:
    - name: dns
      port: "53"
      protocol: UDP
    - name: dns-tcp
      port: "53"
      protocol: TCP
  redirectFrontend:
    serviceMatcher:
      namespace: kube-system
      serviceName: rke2-coredns-rke2-coredns
```

2. View your lrp list. You will _not_ see your pods on the right side of the arrow and traffic is not directed to node-local dns cache.

``` shell
❯ kubectl -n kube-system exec ds/cilium -- cilium lrp list
LRP namespace   LRP name         FrontendType                Matching Service
kube-system     node-local-dns   clusterIP + all svc ports   kube-system/rke2-coredns-rke2-coredns
                |                10.43.0.10:53/UDP ->
                |                10.43.0.10:53/TCP ->
```

3. Delete your existing lrp. At the time of writing, there is a [limitation](https://docs.cilium.io/en/v1.14/network/kubernetes/local-redirect-policy/#limitations) that prevents modifications to an existing lrp.
```
kubectl delete ciliumlocalredirectpolicies -n kube-system node-local-dns
```

4. Create a new `CiliumLocalRedirectPolicy` with `.spec.redirectFrontend.serviceMatcher.toPorts`.
```yaml
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: node-local-dns
  namespace: kube-system
spec:
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: node-local-dns
    toPorts:
    - name: dns
      port: "53"
      protocol: UDP
    - name: dns-tcp
      port: "53"
      protocol: TCP
  redirectFrontend:
    serviceMatcher:
      namespace: kube-system
      serviceName: rke2-coredns-rke2-coredns
      toPorts:
        - name: dns-tcp
          port: "53"
          protocol: TCP
        - name: dns
          port: "53"
          protocol: UDP
```
5. Verify your lrp list has backend pods and traffic routed to your node-local dns cache. The output will show your node-local-dns pod IPs.

```shell
❯ kubectl -n kube-system exec ds/cilium -- cilium lrp list
LRP namespace   LRP name         FrontendType              Matching Service
kube-system     node-local-dns   clusterIP + named ports   kube-system/rke2-coredns-rke2-coredns
                |                10.43.0.10:53/TCP -> 10.42.3.193:53(kube-system/node-local-dns-sbtdr),
                |                10.43.0.10:53/UDP -> 10.42.3.193:53(kube-system/node-local-dns-sbtdr),
```
