### ISSUE TITLE
BGP announcements not occurring on single-node cluster

### ISSUE THREAD

**Issue by shosti** [cilium/cilium#16967]
## Bug report

**General Information**

- Cilium version: 1.10.3
- Kernel version: 5.10.43-flatcar
- Orchestration system version in use: 1.20.0
- Generate and upload a system zip:
[cilium-sysdump-20210721-162754.zip](https://github.com/cilium/cilium/files/6859260/cilium-sysdump-20210721-162754.zip)

**How to reproduce the issue**

I'm trying to deploy cilium on a single-node bare-metal cluster with BGP load balancer announcements enabled. I'm deploying with using helm with the following values.yaml file:

```yaml
debug:
  enabled: true
ipam:
  operator:
    clusterPoolIPv4PodCIDR: "10.101.0.0/16"
l7Proxy: false
encryption:
  enabled: true
  type: wireguard
bgp:
  enabled: true
  announce:
    loadbalancerIP: true
operator:
  replicas: 1
```

The BGP configmap is as as follows:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
      - peer-address: 10.51.60.1
        peer-asn: 65500
        my-asn: 65501
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          - 172.16.16.0/24
```
My BGP setup on the external router is VyOS with the following configuration:

```
protocols {
    bgp 65500 {
        neighbor 10.51.60.82 {
            description "Kubernetes load balancer"
            remote-as 65501
        }
        parameters {
            router-id 10.51.60.1
        }
    }
```
I confirmed that this setup seems to work perfectly with MetalLB (and BGP disabled in Cilium), but with the Cilium there are no BGP announcements happening. tcpdump shows periodic `KEEPALIVE` messages but no other updates. The logs for the cilium pod show a fair number of:
```
level=debug msg="event startUpdate msg start of service update" subsys=bgp-speaker
level=debug msg="event endUpdate msg end of service update" subsys=bgp-speaker
```
but that's the only indication of anything happening.

The LoadBalancer I'm trying to deploy is:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-test-lb
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    svc: test-lb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    matchLabels:
      svc: test-lb
  template:
    metadata:
      labels:
        svc: test-lb
    spec:
      containers:
      - name: web
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
```
(Pretty much straight from the documentation.)
