### ISSUE TITLE
multiple networkpolicy union doesn't combine 'except' statements

### ISSUE THREAD

**Issue by sdhoward** [cilium/cilium#17129]
## Bug report

**Summary**

Created two network policies which are said to be additive. They instead cancel each other out. Is this the right behavior?

The [doc for Network Policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/#isolated-and-non-isolated-pods) says that "policies do not conflict; they are additive".

**General Information**

- Cilium v1.9.7
- Kernel 5.4.0-64-generic (ubuntu 18.04)
- Kubernetes v1.19.9

**Relevant artifacts**

Create the following networkpolicies, each containing a v4 address of [httpbin.org](http://httpbin.org):

`policy1.yaml`:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: policy1
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
          except:
            - 3.230.5.238/32
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
```

`policy2.yaml`:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: policy2
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
          except:
            - 3.209.114.127/32
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
```

Also create a pod to test:

`pod.yaml`:

```
---
apiVersion: v1
kind: Pod
metadata:
  name: rules-test
spec:
  containers:
    - image: alpine:3.14
      name: rules-test-manual
      command:
        - "sh"
        - "-c"
        - "sleep 300"
```

**how to reproduce**

exec into the pod and test connection to port 80:

```
$ kubectl -n test-networkpolicy exec -it rules-test -- sh
/ # nc -vz 3.230.5.238 80
3.230.5.238 (3.230.5.238:80) open
/ # nc -vz 3.209.114.127 80
3.209.114.127 (3.209.114.127:80) open
```

**expected behavior**

expected both connections to be denied

**actual behavior**

both connections are allowed
