### ISSUE TITLE
Pod-to-remote-nodeport identified wrongly as `world`

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#17144]
## Bug report

Inter-node traffic is broken **with policies applied** (`world` is disallowed), where a pod on A hits `nodeIP:nodePort` of another node, B. Traffic is dropped because when the packet arrives on the dst node (B), it is identified as `world`, because of [this code](https://github.com/cilium/cilium/blob/v1.10.3/bpf/bpf_lxc.c#L1540-L1551).

This occurs with the following config:

* `kube-proxy-replacement: disabled` (kpr=disabled)
* `tunnel: vxlan` (tunneling)
* `masquerade: true`

(Thanks to @pchaigno & @aditighag)

**General Information**

Tested against 1.10.3 and master as of date of the issue

**How to reproduce the issue**

1. Create kind cluster (2 nodes)
2. Install via Cilium CLI
3. Apply the below resources
4. Initiate traffic from the `client` via `curl` to the node IP and node port of the `echo-other-node` service. Ensure that the node IP corresponds to a different node than the node `client` is on. In other words, we want to test inter-node traffic.

<details> 
  <summary>CNP </summary>

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-all-except-world
spec:
  endpointSelector: {}
  egress:
  - toEntities:
    - host
    - remote-node
    - cluster
    - init
    - health
  ingress:
  - fromEntities:
    - host
    - remote-node
    - cluster
    - init
    - health
```
</details>

<details> 
  <summary>Deployment and service </summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kind: client
    name: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      kind: client
      name: client
  template:
    metadata:
      labels:
        kind: client
        name: client
      name: client
    spec:
      containers:
      - command:
        - /bin/ash
        - -c
        - sleep 10000000
        env:
        - name: PORT
          value: "8080"
        image: quay.io/cilium/alpine-curl:v1.3.0@sha256:1d928912e5d9dc9994b038b5df7434790c4bb9bd64f60570d78c1dee13befc76
        imagePullPolicy: IfNotPresent
        name: client
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kind: echo
    name: echo-other-node
  name: echo-other-node
spec:
  replicas: 1
  selector:
    matchLabels:
      kind: echo
      name: echo-other-node
  template:
    metadata:
      creationTimestamp: null
      labels:
        kind: echo
        name: echo-other-node
      name: echo-other-node
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - client
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: PORT
          value: "8080"
        image: quay.io/cilium/json-mock:v1.3.0@sha256:2729064827fa9dbfface8d3df424feb6c792a0ba07117b844349635c93c06d2b
        imagePullPolicy: IfNotPresent
        name: echo-other-node
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kind: echo
  name: echo-other-node
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: echo-other-node
    port: 8080
    protocol: TCP
  selector:
    name: echo-other-node
  type: NodePort
```

</details>

**Comment by christarazi** [comment]
Monitor traces:

src pod: `10.244.1.195` on node1
dst svc: `172.20.0.2:32243` on node2

Src:
```
<- endpoint 406 flow 0xaa0385 identity 41070->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.244.1.195:53020 -> 172.20.0.2:32243 tcp SYN
CPU 07: MARK 0xaa0385 FROM 406 DEBUG: Conntrack lookup 1/2: src=10.244.1.195:53020 dst=172.20.0.2:32243
CPU 07: MARK 0xaa0385 FROM 406 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 07: MARK 0xaa0385 FROM 406 DEBUG: CT verdict: New, revnat=0
CPU 07: MARK 0xaa0385 FROM 406 DEBUG: Successfully mapped addr=172.20.0.2 to identity=6
Policy verdict log: flow 0xaa0385 local EP ID 406, remote ID remote-node, proto 6, egress, action allow, match L3-Only, 10.244.1.195:53020 -> 172.20.0.2:32243 tcp SYN
CPU 07: MARK 0xaa0385 FROM 406 DEBUG: Conntrack create: proxy-port=0 revnat=0 src-identity=41070 lb=0.0.0.0
-> stack flow 0xaa0385 identity 41070->remote-node state new ifindex 0 orig-ip 0.0.0.0: 10.244.1.195:53020 -> 172.20.0.2:32243 tcp SYN
-> 0: 10.244.1.195:53020 -> 172.20.0.2:32243 tcp SYN
```

Dst:
```
<- host flow 0xd0e31aee identity world->unknown state new ifindex eth0 orig-ip 0.0.0.0: 172.20.0.2:36296 -> 10.244.0.14:8080 tcp SYN
CPU 01: MARK 0xd0e31aee FROM 1645 DEBUG: Successfully mapped addr=172.20.0.2 to identity=2
CPU 01: MARK 0xd0e31aee FROM 1645 DEBUG: Attempting local delivery for container id 268 from seclabel 2
CPU 01: MARK 0xd0e31aee FROM 268 DEBUG: Conntrack lookup 1/2: src=172.20.0.2:36296 dst=10.244.0.14:8080
CPU 01: MARK 0xd0e31aee FROM 268 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 01: MARK 0xd0e31aee FROM 268 DEBUG: CT verdict: New, revnat=0
CPU 01: MARK 0xd0e31aee FROM 268 DEBUG: Policy evaluation would deny packet from 2 to 3445
Policy verdict log: flow 0xd0e31aee local EP ID 268, remote ID world, proto 6, ingress, action deny, match none, 172.20.0.2:36296 -> 10.244.0.14:8080 tcp SYN
xx drop (Policy denied) flow 0xd0e31aee to endpoint 268, identity world->3445: 172.20.0.2:36296 -> 10.244.0.14:8080 tcp SYN
```

**Comment by pchaigno** [comment]
To fix this issue, we need to associate the proper source identity to the packet when it reaches the destination's bpf_lxc program and its policy enforcement. We cannot derive the source identity in bpf_lxc because the packet has already been SNATed by kube-proxy's iptables rules at that point.

Instead, we could attach a BPF program at the native device (i.e., before SNATing is applied), to:
- resolve the source identity using the ipcache and
- store that source identity in the packet mark.

We then wouldn't even need to change bpf_lxc because it [already checks the packet mark](https://github.com/cilium/cilium/blob/v1.10.3/bpf/lib/identity.h#L54-L55) for an identity.

**Comment by christarazi** [comment]
AFAIU, this seems to affect all instances of pod-to-remote-nodeport, aka tunneling is not only affected.

**Comment by pchaigno** [comment]
It seems this can also happen if a request from outside the cluster comes to a NodePort with local or remote backend: https://github.com/cilium/cilium/issues/23603.

**Comment by j-land** [comment]
We are also seeing this with Cilium v1.14.3. This behavior not only complicates our network policies, but our security posture is degraded since `world` is such a permissive entity.

Here is a subset of the configuration from our Helm values file:

```
eni:
  enabled: true

ipam:
  mode: eni

tunnel: disabled

egressMasqueradeInterfaces: eth+

encryption:
  enabled: true
  nodeEncryption: false
  type: ipsec
```
