### ISSUE TITLE
After apply L7 policy,tiefighter can only connect to one copy of deathstar

### ISSUE THREAD

**Issue by tiggoins** [cilium/cilium#17164]
### Sumamry 

Hi,guys! I use [this page](https://docs.cilium.io/en/v1.10/gettingstarted/http/#check-current-access) to learn about networkpolicy.But after i  deploy the L7policy,tieghter can only connect to one copy of deathstar

### General information

- Cilium v1.10.3
- Kernel 5.4.101-1.el7.elrepo.x86_64
- Kubernetes v1.19.3

### Relevant artifacts

`deployment.yaml`

```
---
apiVersion: v1
kind: Service
metadata:
  name: deathstar
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    org: empire
    class: deathstar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deathstar
spec:
  replicas: 2
  selector:
    matchLabels:
      org: empire
      class: deathstar
  template:
    metadata:
      labels:
        org: empire
        class: deathstar
    spec:
      containers:
      - name: deathstar
        image: docker.io/cilium/starwars
---
apiVersion: v1
kind: Pod
metadata:
  name: tiefighter
  labels:
    org: empire
    class: tiefighter
spec:
  containers:
  - name: spaceship
    image: docker.io/tgraf/netperf
---
apiVersion: v1
kind: Pod
metadata:
  name: xwing
  labels:
    org: alliance
    class: xwing
spec:
  containers:
  - name: spaceship
    image: docker.io/tgraf/netperf
```

`policy-l7.yaml`

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "rule1"
spec:
  description: "L7 policy to restrict access to specific HTTP call"
  endpointSelector:
    matchLabels:
      org: empire
      class: deathstar
  ingress:
  - fromEndpoints:
    - matchLabels:
        org: empire
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        http:
        - method: "POST"
          path: "/v1/request-landing"
```

### how to reproduce

```
[root@master-1 cilium-learn]# kubectl get pods -o wide --show-labels
NAME                        READY   STATUS    RESTARTS   AGE   IP           NODE       NOMINATED NODE   READINESS GATES   LABELS
deathstar-c74d84667-259l7   1/1     Running   0          28m   10.0.3.225   node-1     <none>           <none>            class=deathstar,org=empire,pod-template-hash=c74d84667
deathstar-c74d84667-dggdp   1/1     Running   0          28m   10.0.0.81    master-3   <none>           <none>            class=deathstar,org=empire,pod-template-hash=c74d84667
tiefighter                  1/1     Running   0          28m   10.0.3.216   node-1     <none>           <none>            class=tiefighter,org=empire
xwing                       1/1     Running   0          28m   10.0.3.108   node-1     <none>           <none>            class=xwing,org=alliance
```

```
[root@master-1 cilium-learn]# kubectl exec tiefighter -- curl -s -XPOST 10.0.3.225/v1/request-landing                         
Ship landed
[root@master-1 cilium-learn]# kubectl exec tiefighter -- curl -s -XPOST 10.0.0.81/v1/request-landing
```

and i can't see any difference between this two pods from cilium endpoint list
```
[root@master-1 cilium-learn]# kubectl exec -n kube-system cilium-c9k7s -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                           IPv6   IPv4         STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                            
345        Disabled           Disabled          45998      k8s:control-plane=controller-manager                                         10.0.3.254   ready   
                                                           k8s:io.cilium.k8s.namespace.labels.control-plane=controller-manager                               
                                                           k8s:io.cilium.k8s.policy.cluster=cluster-local                                                    
                                                           k8s:io.cilium.k8s.policy.serviceaccount=operator-controller-manager                               
                                                           k8s:io.kubernetes.pod.namespace=operator-system                                                   
403        Disabled           Disabled          1          reserved:host                                                                             ready   
510        Disabled           Disabled          57247      k8s:app=nginx-deployment                                                     10.0.3.190   ready   
                                                           k8s:io.cilium.k8s.policy.cluster=default                                                          
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                   
                                                           k8s:io.kubernetes.pod.namespace=k8s-api                                                           
667        Disabled           Disabled          6663       k8s:class=xwing                                                              10.0.3.108   ready   
                                                           k8s:io.cilium.k8s.policy.cluster=cluster-local                                                    
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                   
                                                           k8s:io.kubernetes.pod.namespace=default                                                           
                                                           k8s:org=alliance                                                                                  
976        Disabled           Disabled          4          reserved:health                                                              10.0.3.170   ready   
1027       Disabled           Disabled          29536      k8s:class=tiefighter                                                         10.0.3.216   ready   
                                                           k8s:io.cilium.k8s.policy.cluster=cluster-local                                                    
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                   
                                                           k8s:io.kubernetes.pod.namespace=default                                                           
                                                           k8s:org=empire                                                                                    
1962       Disabled           Disabled          9052       k8s:app=nginx-deployment                                                     10.0.3.211   ready   
                                                           k8s:io.cilium.k8s.policy.cluster=cluster-local                                                    
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                   
                                                           k8s:io.kubernetes.pod.namespace=k8s-api                                                           
2782       Enabled            Disabled          7338       k8s:class=deathstar                                                          10.0.3.225   ready   
                                                           k8s:io.cilium.k8s.policy.cluster=cluster-local                                                    
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                   
                                                           k8s:io.kubernetes.pod.namespace=default                                                           
                                                           k8s:org=empire                                                                                    
4055       Disabled           Disabled          10109      k8s:app=busybox-deployment                                                   10.0.3.188   ready   
                                                           k8s:io.cilium.k8s.policy.cluster=cluster-local                                                    
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                   
                                                           k8s:io.kubernetes.pod.namespace=k8s-api                              
```

```
[root@master-1 cilium-learn]# kubectl exec -n kube-system cilium-kxsrl -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6   IPv4         STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                        
1240       Disabled           Disabled          4          reserved:health                                          10.0.0.142   ready   
1660       Disabled           Disabled          1          k8s:node-role.kubernetes.io/master                                    ready   
                                                           reserved:host                                                                 
2016       Enabled            Disabled          7338       k8s:class=deathstar                                      10.0.0.81    ready   
                                                           k8s:io.cilium.k8s.policy.cluster=cluster-local                                
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                               
                                                           k8s:io.kubernetes.pod.namespace=default                                       
                                                           k8s:org=empire                                                       
```
this is the monitor log from tiefighter to 10.0.3.225
```
[root@master-1 cilium-learn]# kubectl exec -n kube-system cilium-c9k7s -- cilium monitor --from 1027
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
-> endpoint 1027 flow 0x2291029 identity 7338->29536 state reply ifindex lxc42f53d97f3b2 orig-ip 10.0.3.225: 10.0.3.225:80 -> 10.0.3.216:51794 tcp SYN, ACK
-> endpoint 1027 flow 0x2291029 identity 7338->29536 state reply ifindex lxc42f53d97f3b2 orig-ip 10.0.3.225: 10.0.3.225:80 -> 10.0.3.216:51794 tcp ACK
-> endpoint 1027 flow 0x2291029 identity 7338->29536 state reply ifindex lxc42f53d97f3b2 orig-ip 10.0.3.225: 10.0.3.225:80 -> 10.0.3.216:51794 tcp ACK, FIN
```
and no monitor log from  tiefighter to 10.0.0.81

I both use cilium-cli and helm to deploy the cilium,but the outcome is same.
Any hint will be grateful.
