### ISSUE TITLE
LB Service connexion disruption on Readiness failure (due to bad NAT?)

### ISSUE THREAD

**Issue by joulaud** [cilium/cilium#17252]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.10.3 4145278 2021-07-15T16:11:03+02:00 go version go1.16.6 linux/amd64
Daemon: 1.10.3 4145278 2021-07-15T16:11:03+02:00 go version go1.16.6 linux/amd64
```

- Kernel version (run `uname -a`)
```
Linux ip-10-82-33-185 4.19.0-17-cloud-amd64 #1 SMP Debian 4.19.194-1 (2021-06-10) x86_64 x86_64 x86_64 GNU/Linux
```

- Orchestration system version in use (e.g. `kubectl version`, ...)
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```
deployed with kops 1.21.0

- Cilium config
```
root@ip-10-82-33-185:/home/cilium# cilium config
Conntrack                Enabled
ConntrackAccounting      Enabled
ConntrackLocal           Disabled
Debug                    Disabled
DebugLB                  Disabled
DropNotification         Enabled
MonitorAggregationLevel  Medium
PolicyAuditMode          Disabled
PolicyTracing            Disabled
PolicyVerdictNotification Enabled
TraceNotification        Enabled
k8s-configuration        
k8s-endpoint             
PolicyEnforcement        default
MonitorNumPages          64
```
Due to possible sensitive information I cannot share full sysdump publicly but I have taken one I can make available if wanted.

**How to reproduce the issue**

I have not managed to make a simple reproduction case. Load (on network or k8s API, idk) seem to be a big factor.

We could pinpoint the issue after several tries of investigating strange behaviour under load and can consistently reproduce problems on our testing environment.

**Description of the problem**

Under certain conditions Cilium seems to lose track of the way it does kubernetes Service translation.

This seems to lead to : 
- ghost connexions (closed on one side but not the other)
- spurious disconnexions
- confusion between destination (connexions which goes to different pod than expected, this last one is perhaps not directly linked)

This network trace screen-capture describes the problem observed.
![20210827T144906_manual_ZONE_wireshark-Wireshark__begining_of_problem_pcapng](https://user-images.githubusercontent.com/48206448/131131262-45f653e2-f89b-43f0-8379-d0ae5ce8ea6b.png)

**Comment by joulaud** [comment]
We seem to have discovered a relationship between Readiness failure and the behaviour observed above.
I will do some more test and give back any pertinent information.

**Comment by joulaud** [comment]
I have pinned down at least part of the problem with a simpler test case 100% reproducible.
- all pods on same node
- one client pod (clt)
- one service (svc)
- two server pods (srv and other-srv) behind the service
- one TCP connexion from client to service
- server pod joined by client (srv) have readiness failing (I provoke this at will with a specially tailored ReadinessProbe)
- observe connexion routed to bad other-server pod (and RSTed by it)
![20210917T194423_manual_ZONE_wireshark-Wireshark__all_merges_pcapng](https://user-images.githubusercontent.com/48206448/133832706-9a700267-a1ab-459a-a413-92a0f28eca49.png)

Cilium configmap is:
```yaml
data:
  auto-direct-node-routes: "false"
  bpf-ct-global-any-max: "262144"
  bpf-ct-global-tcp-max: "524288"
  cluster-name: default
  container-runtime: none
  debug: "false"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-metrics: "true"
  enable-node-port: "false"
  enable-remote-node-identity: "true"
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  ipam: kubernetes
  kube-proxy-replacement: partial
  masquerade: "true"
  monitor-aggregation: medium
  operator-prometheus-serve-addr: :6942
  preallocate-bpf-maps: "false"
  prometheus-serve-addr: :9090
  sidecar-istio-proxy-image: cilium/istio_proxy
  tofqdns-dns-reject-response-code: refused
  tofqdns-enable-poller: "false"
  tunnel: vxlan
  wait-bpf-mount: "false"
```

cilium status is
```
Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
KVStore:                                       Ok   Disabled
Kubernetes:                                    Ok   1.21 (v1.21.3) [linux/amd64]
Kubernetes APIs:                               ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:                          Partial   
Cilium:                                        Ok   1.10.3 (v1.10.3-4145278)
NodeMonitor:                                   Disabled
Cilium health daemon:                          Ok   
IPAM:                                          IPv4: 63/254 allocated from 100.81.255.0/24, 
BandwidthManager:                              Disabled
Host Routing:                                  Legacy
Masquerading:                                  IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:                             262/262 healthy
Proxy Status:                                  OK, ip 100.81.255.56, 0 redirects active on ports 10000-20000
Hubble:                                        Disabled
Encryption:                                    Disabled
Cluster health:                                11/14 reachable   (2021-09-17T17:54:37Z)
  Name                                         IP                Node          Endpoints
  ip-10-81-32-148.eu-west-3.compute.internal   10.81.32.148      unreachable   reachable
  ip-10-81-33-14.eu-west-3.compute.internal    10.81.33.14       unreachable   reachable
  ip-10-81-34-127.eu-west-3.compute.internal   10.81.34.127      unreachable   reachable
```
