### ISSUE TITLE
egress NAT gateway: exceptions to destinationCIDRs

### ISSUE THREAD

**Issue by mstarostik** [cilium/cilium#17295]
## RFE

**Is your feature request related to a problem?**
Cannot (conveniently) use CiliumEgressNATPolicy to specify egress NAT gateway for all egress from a pod

**Describe the solution you'd like**
I would like to have all of a pod's egress traffic be subject to egress NAT. I still want the pod to be able to access other pods, most notably CoreDNS without NAT

This basically works:
```
apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
spec:
  destinationCIDRs:
  - 0.0.0.0/0
```
but the targeted pods are not able to use DNS anymore, presumably because even in-cluster traffic will be NATed.

I propose to allow for something like
```
destinationCIDRs:
- 0.0.0.0/0
- !10.0.0.0/8
```
or
```
destinationCIDRs:
- 0.0.0.0/0
excludeCIDRs:
- 10.0.0.0/8
```
or even default to 0.0.0.0/0 if only excludeCIDRs is given.
Alternatively or additionally a special flag (field or annotation) to automagically exclude the cluster and service CIDRs would be nice to have.

In my case at hand, this workaround does the trick, but that doesn't really scale:
```
destinationCIDRs:
- 0.0.0.0/5
- 8.0.0.0/7
- 11.0.0.0/8
- 12.0.0.0/6
- 16.0.0.0/4
- 32.0.0.0/3
- 64.0.0.0/2
- 128.0.0.0/1
```

**Comment by pchaigno** [comment]
> This basically works:
> 
> ```
> apiVersion: cilium.io/v2alpha1
> kind: CiliumEgressNATPolicy
> spec:
>   destinationCIDRs:
>   - 0.0.0.0/0
> ```
> 
> but the targeted pods are not able to use DNS anymore, presumably because even in-cluster traffic will be NATed.

That bug is tracked at https://github.com/cilium/cilium/issues/16147. In-cluster traffic shouldn't be SNATed to the egress IP. As far as I understand, once that bug is fixed, it should solve your issue, right?

cc @anfernee @MasterZ40

**Comment by mstarostik** [comment]
@pchaigno looks very much like it, yes. Sorry, totally missed that one when searching.
However, I'm on 1.10.3 and the problem persists. So not sure if it's (just) the same issue or not.

I'm also totally new to cilium so it might be an obvious oversight...
My Helm values:
```
rollOutCiliumPods: true
operator:
  rollOutPods: true

kubeProxyReplacement: strict
k8sServiceHost: ${api_server}
k8sServicePort: 6443
hostServices:
  enabled: true

tunnel: disabled
nativeRoutingCIDR: ${cluster_cidr}
endpointRoutes:
  enabled: true

ipam:
  operator:
    clusterPoolIPv4PodCIDR: ${cluster_cidr}

hostPort:
  enabled: true

egressGateway:
  enabled: true

bpf:
  masquerade: true
```
The variables are substituted by terraform, leaving the symbolic names as they're clearer than some random IPs though.
All nodes are running k3s v1.21.1+k3s1
eth0 with a public /32
eth1 with a private /32 and L3 connectivity between the nodes
