### ISSUE TITLE
Please support "Services without selectors" feature

### ISSUE THREAD

**Issue by qingkunl** [cilium/cilium#17320]
The K8s official document has [Services without selectors](https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors) feature. However, when I experiment it with Cilium (`kubeProxyReplacement=strict`), it doesn't work. It seems like Cilium doesn't support this feature now. Many other CNIs already support it.

**Comment by brb** [comment]
@qingkunl Thanks for the issue. Are you sure that it doesn't work? Have you seen https://github.com/cilium/cilium/issues/12513 and  https://github.com/cilium/cilium/issues/12438?

**Comment by qingkunl** [comment]
> @qingkunl Thanks for the issue. Are you sure that it doesn't work? Have you seen #12513 and #12438?

Thanks for the reference. I'm using K8s v1.20.2 + Cilium v1.9.9 and still see this issue.

Following is my service config. Please advice.

```
apiVersion: v1
kind: Service
metadata:
  name: service-qingkun
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31081

---

apiVersion: v1
kind: Endpoints
metadata:
  name: service-qingkun
subsets:
  - addresses:
      - ip: 10.62.32.11
      - ip: 10.62.32.12
    ports:
      - port: 32080
```
