### ISSUE TITLE
Incorrect egress source IP when recreating Pod

### ISSUE THREAD

**Issue by tomaik** [cilium/cilium#17333]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
Client: 1.10.4 2a46fd6 2021-09-01T12:58:41-07:00 go version go1.16.7 linux/amd64
Daemon: 1.10.4 2a46fd6 2021-09-01T12:58:41-07:00 go version go1.16.7 linux/amd64

- Kernel version (run `uname -a`)
Linux node3 5.4.0-33-generic 37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux Ubuntu 20.04LTS
- Orchestration system version in use (e.g. `kubectl version`, ...)
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:

[debuginfo.txt](https://github.com/cilium/cilium/files/7122051/debuginfo.txt)
[cilium-sysdump-20210907-135552.zip](https://github.com/cilium/cilium/files/7122049/cilium-sysdump-20210907-135552.zip)

**How to reproduce the issue**

1. Starting point, egress gateway works ok for pod 'mediabot' https://raw.githubusercontent.com/cilium/cilium/1.10.4/examples/kubernetes-dns/dns-sw-app.yaml

```
root@node3:~# kubectl -n kube-system exec cilium-dg978 -- cilium bpf egress list
SRC IP & DST CIDR        EGRESS INFO
10.233.66.13 0.0.0.0/0   10.38.3.198 10.38.3.198
```

2. Delete policy, egress is removed

```
root@node3:~# kubectl -n kube-system exec cilium-dg978 -- cilium bpf egress list
No entries found.
```

3. Recreate pod (gets different IP)

`mediabot                            1/1     Running   0          7s      10.233.66.197   node3   <none>           <none>`

4. Recreate policy

```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
metadata:
  name: egress-sample
spec:
  egress:
  - podSelector:
      matchLabels:
        org: empire
        class: mediabot
        # The following label selects default namespace
        io.kubernetes.pod.namespace: kube-system
    # Or use namespace label selector to select multiple namespaces
    # namespaceSelector:
    #  matchLabels:
    #    ns: default
  destinationCIDRs:
  - 0.0.0.0/0
  egressSourceIP: "10.38.3.198"
```

5. Egress list has incorrect src IP (old pod IP)

```
root@node3:~# kubectl -n kube-system exec cilium-dg978 -- cilium bpf egress list
SRC IP & DST CIDR        EGRESS INFO
10.233.66.13 0.0.0.0/0   10.38.3.198 10.38.3.198
```

6. Recreate cilium pod, duplicated entries

```
root@node3:~# kubectl -n kube-system exec cilium-ltjx9 -- cilium bpf egress list
SRC IP & DST CIDR         EGRESS INFO
10.233.66.13 0.0.0.0/0    10.38.3.198 10.38.3.198
10.233.66.197 0.0.0.0/0   10.38.3.198 10.38.3.198
```
