### ISSUE TITLE
ArgoCD deletes CustomResourceDefinitions that Cilium uses to implement networking and security

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#17349]
When deploying Cilium with ArgoCD, some users have reported that Cilium-generated custom resources are disappearing, which can cause a variety of issues.

To prevent this issue, declare resource exclusions in the ArgoCD ConfigMap by following [these instructions](https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#resource-exclusioninclusion).

Here is an example snippet:

```
   resource.exclusions: |
     - apiGroups:
         - cilium.io
       kinds:
         - CiliumIdentity
       clusters:
         - "*"
```

Note that the ArgoCD deployments may need restarting after configuring these settings in order for the settings to take effect.

**Comment by joestringer** [comment]
Fredrik Björkman on Slack also reported that:

> This problem is related to all workloads you deploy with ArgoCD in a cluster running cilium, not just cilium itself.

> If you deploy cilium with ArgoCD, you also need these exclusions in the ArgoCD application definition to not get “out of sync” when hubble rotates it certificates.

```
ignoreDifferences:
      - group: ""
        kind: ConfigMap
        name: hubble-ca-cert
        jsonPointers:
        - /data/ca.crt
      - group: ""
        kind: Secret
        name: hubble-relay-client-certs
        jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
      - group: ""
        kind: Secret
        name: hubble-server-certs
        jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
```

**Comment by cguertin14** [comment]
thank you 🙏🏻 this just helped me fixed things on my cluster.

**Comment by travnewmatic** [comment]
my `kustomization.yaml` for my whole stupid cluster looks approximately like this:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml
- cilium-application.yaml
- appX.yaml

patches:
  - patch: |-
      - op: add
        path: /data
        value:
          resource.exclusions: |
            - apiGroups:
                - cilium.io
              kinds:
                - CiliumIdentity
              clusters:
                - "*"
    target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
```

i'm very open to suggestions!

my considerations for this approach are:
- i dont want to change how i'm managing argocd in my cluster. living on the 'bleeding' edge, perpetually applying `https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml` has worked reasonably well for me.  the alternative (maybe) would be to switch to installing argocd with helm, but i'm not exactly sure that way would be cleaner/neater.
- i dont think creating another `argocd-cm` resource/manifest is appropriate.  that resource would conflict with the resource already included in `install.yaml`.  my new argocd-cm manifest could be `merged` with the `argocd-cm` included in `install.yaml`, but i figured there had to be a way to "add a thing to an existing resource with kustomize".

please let me know if i did this in a really dumb way.  but this does appear to work.  all of my applications that were flapping synced/out-of-sync because of `ciliumIdentities` are happily `synced` now.

**Comment by joebowbeer** [comment]
@travnewmatic Can accomplish the same thing using `clusterResourceBlacklist` in an AppProject? If so, you can declare it in one of the argocd-cm `globalProjects`.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: application project
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceBlacklist:
  - group: cilium.io
    kind: CiliumIdentity
  sourceRepos:
  - '*'
  destinations:
  - namespace: "*"
    server: "*"
```
