### ISSUE TITLE
HostPort reachable from every pods on localhost

### ISSUE THREAD

**Issue by krasenn** [cilium/cilium#17454]
Hi all, here is a strange issue I have observed using a HostPort in Cilium :

### Env
Cilium :
```
cilium status --verbose
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.22 (v1.22.1) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [ens2 10.194.69.137 (Direct Routing)]
Cilium:                 Ok   1.10.3 (v1.10.3-4145278)
NodeMonitor:            Listening for events on 8 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPAM:                   IPv4: 4/254 allocated from 100.64.2.0/24, 
Allocated addresses:
  100.64.2.151 (kube-system/node-problem-detector-nvpfw [restored])
  100.64.2.168 (kube-system/nginx-ingress-trjbj [restored])
  100.64.2.241 (health)
  100.64.2.49 (router)
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           IPTables [IPv4: Enabled, IPv6: Disabled]
Clock Source for BPF:   ktime
Controller Status:      30/30 healthy
  Name                                          Last success   Last error   Count   Message
  bpf-map-sync-cilium_lxc                       6s ago         never        0       no error   
  cilium-health-ep                              21s ago        never        0       no error   
  dns-garbage-collector-job                     34s ago        never        0       no error   
  endpoint-1032-regeneration-recovery           never          never        0       no error   
  endpoint-2126-regeneration-recovery           never          never        0       no error   
  endpoint-2629-regeneration-recovery           never          never        0       no error   
  endpoint-987-regeneration-recovery            never          never        0       no error   
  endpoint-gc                                   1m34s ago      never        0       no error   
  k8s-heartbeat                                 3s ago         never        0       no error   
  mark-k8s-node-as-available                    1h11m22s ago   never        0       no error   
  metricsmap-bpf-prom-sync                      4s ago         never        0       no error   
  neighbor-table-refresh                        1m22s ago      never        0       no error   
  resolve-identity-1032                         1m21s ago      never        0       no error   
  restoring-ep-identity (2126)                  1h11m22s ago   never        0       no error   
  restoring-ep-identity (2629)                  1h11m22s ago   never        0       no error   
  restoring-ep-identity (987)                   1h11m22s ago   never        0       no error   
  sync-endpoints-and-host-ips                   22s ago        never        0       no error   
  sync-lb-maps-with-k8s-services                1h11m22s ago   never        0       no error   
  sync-policymap-1032                           15s ago        never        0       no error   
  sync-policymap-2126                           15s ago        never        0       no error   
  sync-policymap-2629                           15s ago        never        0       no error   
  sync-policymap-987                            12s ago        never        0       no error   
  sync-to-k8s-ciliumendpoint (1032)             11s ago        never        0       no error   
  sync-to-k8s-ciliumendpoint (2126)             2s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (2629)             2s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (987)              2s ago         never        0       no error   
  template-dir-watcher                          never          never        0       no error   
  update-k8s-node-annotations                   1h11m33s ago   never        0       no error   
  waiting-initial-global-identities-ep (2126)   1h11m22s ago   never        0       no error   
  waiting-initial-global-identities-ep (2629)   1h11m22s ago   never        0       no error   
Proxy Status:   OK, ip 100.64.2.49, 0 redirects active on ports 10000-20000
Hubble:         Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 2.82   Metrics: Disabled
KubeProxyReplacement Details:
  Status:                Strict
  Socket LB Protocols:   TCP, UDP
  Devices:               ens2 10.194.69.137 (Direct Routing)
  Mode:                  SNAT
  Backend Selection:     Random
  Session Affinity:      Enabled
  XDP Acceleration:      Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Enabled (Range: 30000-32767) 
  - LoadBalancer:   Enabled 
  - externalIPs:    Enabled 
  - HostPort:       Enabled
BPF Maps:   dynamic sizing: on (ratio: 0.002500)
  Name                          Size
  Non-TCP connection tracking   147688
  TCP connection tracking       295377
  Endpoint policy               65535
  Events                        8
  IP cache                      512000
  IP masquerading agent         16384
  IPv4 fragmentation            8192
  IPv4 service                  65536
  IPv6 service                  65536
  IPv4 service backend          65536
  IPv6 service backend          65536
  IPv4 service reverse NAT      65536
  IPv6 service reverse NAT      65536
  Metrics                       1024
  NAT                           295377
  Neighbor table                295377
  Global policy                 16384
  Per endpoint policy           65536
  Session affinity              65536
  Signal                        8
  Sockmap                       65535
  Sock reverse NAT              147688
  Tunnel                        65536
Encryption:                                                    Disabled
Cluster health:                                                3/3 reachable   (2021-09-22T11:50:18Z)
  Name                                                         IP              Node        Endpoints
  scw-k8s-serene-engelbart-default-f7cf3cc08a664 (localhost)   10.194.69.137   reachable   reachable
  scw-k8s-serene-engelbart-default-4af138d35a4c4               10.66.239.131   reachable   reachable
  scw-k8s-serene-engelbart-default-8c4f10a711d84               10.12.159.195   reachable   reachable

```
```
  auto-direct-node-routes: "false"
  bpf-lb-map-max: "65536"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: ""
  cluster-name: default
  custom-cni-conf: "false"
  debug: "false"
  disable-cnp-status-updates: "true"
  enable-auto-protect-node-port-range: "true"
  enable-bandwidth-manager: "false"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "false"
  enable-bpf-tproxy: "true"
  enable-endpoint-health-checking: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-l7-proxy: "true"
  enable-local-redirect-policy: "false"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  hubble-disable-tls: "false"
  hubble-listen-address: :4244
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  ipam: kubernetes
  k8s-api-server: https://foo.bar:6443
  k8s-require-ipv4-pod-cidr: "true"
  k8s-require-ipv6-pod-cidr: "false"
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: ""
  masquerade: "true"
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  operator-api-serve-addr: 127.0.0.1:9234
  preallocate-bpf-maps: "false"
  sidecar-istio-proxy-image: cilium/istio_proxy
  tunnel: vxlan
  wait-bpf-mount: "false"
```
Kernel :
```
# uname -a
Linux scw-k8s-serene-engelbart-default-8c4f10a711d84 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
Kubernetes :
```
# kubectl version
# [..]
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```
### Issue description/How to reproduce
1. Deploy a Nginx ingress controller using a DaemontSet, using a HostPort. This means that on every nodes of the cluster, the nginx is listening on 0.0.0.0 on both 80 and 443 port (here is the manifest):
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-nginx-configuration
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: nginx
    k8s.scw.cloud/object: ConfigMap
  annotations:
    meta.helm.sh/release-namespace: kube-system
    meta.helm.sh/release-name: kapsule-ingress
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-nginx-tcp-services
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: nginx
    k8s.scw.cloud/object: ConfigMap
  annotations:
    meta.helm.sh/release-namespace: kube-system
    meta.helm.sh/release-name: kapsule-ingress
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-nginx-udp-services
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: nginx
    k8s.scw.cloud/object: ConfigMap
  annotations:
    meta.helm.sh/release-namespace: kube-system
    meta.helm.sh/release-name: kapsule-ingress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: nginx
    k8s.scw.cloud/object: ServiceAccount
  annotations:
    meta.helm.sh/release-namespace: kube-system
    meta.helm.sh/release-name: kapsule-ingress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-ingress
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: nginx
    k8s.scw.cloud/object: ClusterRole
  annotations:
    meta.helm.sh/release-namespace: kube-system
    meta.helm.sh/release-name: kapsule-ingress
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-ingress
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: nginx
    k8s.scw.cloud/object: Role
  annotations:
    meta.helm.sh/release-namespace: kube-system
    meta.helm.sh/release-name: kapsule-ingress
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ''
    resources:
      - configmaps
      - pods
      - secrets
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - configmaps
    resourceNames:
      - ingress-controller-leader
      - ingress-controller-leader-nginx
    verbs:
      - get
      - update
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-ingress
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: nginx
    k8s.scw.cloud/object: RoleBinding
  annotations:
    meta.helm.sh/release-namespace: kube-system
    meta.helm.sh/release-name: kapsule-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-ingress
subjects:
  - kind: ServiceAccount
    name: nginx-ingress
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: nginx
    k8s.scw.cloud/object: ClusterRoleBinding
  annotations:
    meta.helm.sh/release-namespace: kube-system
    meta.helm.sh/release-name: kapsule-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-ingress
subjects:
  - kind: ServiceAccount
    name: nginx-ingress
    namespace: kube-system
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  name: nginx
  namespace: kube-system
spec:
  controller: k8s.io/ingress-nginx
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
    meta.helm.sh/release-namespace: kube-system
    meta.helm.sh/release-name: kapsule-ingress
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/part-of: ingress-nginx
      annotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
    spec:
      # wait up to five minutes for the drain of connections
      terminationGracePeriodSeconds: 300
      serviceAccountName: nginx-ingress
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: false
      containers:
        - name: nginx-ingress-controller
          image: k8s.gcr.io/ingress-nginx/controller:v1.0.0-beta.1
          args:
            - /nginx-ingress-controller
            - --election-id=ingress-controller-leader-nginx
            - --controller-class=k8s.io/ingress-nginx
            - --configmap=$(POD_NAMESPACE)/ingress-nginx-configuration
            - --tcp-services-configmap=$(POD_NAMESPACE)/ingress-nginx-tcp-services
            - --udp-services-configmap=$(POD_NAMESPACE)/ingress-nginx-udp-services
            - --annotations-prefix=nginx.ingress.kubernetes.io
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
            # www-data -> 33
            runAsUser: 101
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
            - name: https
              containerPort: 443
              hostPort: 443
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
```
2. Deploy a pod in the default namespace using this manifest
```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
```
3. Into that pod curl localhost
```
# kubectl exec -it ubuntu /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@ubuntu:/# curl -k https://localhost
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
4. /etc/hosts in the pod
```
root@ubuntu:/# cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
100.64.1.230	ubuntu
```
### Expected behaviour
As this pod should be running in its own network namspace, the nginx should be unreachable on localhost. The same test has been run on a cluster with Calico and the expected behaviour is seen :
```
root@ubuntu:/# curl -k https://localhost:443
curl: (7) Failed to connect to localhost port 443: Connection refused
```

Cilium sysdump available here : https://ciliumissue.s3.fr-par.scw.cloud/cilium-sysdump-20210922-145557.zip

Thanks a lot for your help
