### ISSUE TITLE
Cannot create two `CiliumEgressNATPolicy` with the same `egressSourceIP`

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#17678]
The Cilium agents rejects egress gateway policies if they have the same `egressSourceIP` has an existing egress gateway policy.
```
level=warning msg="Failed to add CiliumEgressNATPolicy." ciliumEgressNATPolicyName=egress-sample2 error="CiliumEgressNatPolicy for egress IP 192.168.33.100 already exists" k8sApiVersion= k8sUID=4fd8cf1d-9592-4256-b248-201ddd6a5ded subsys=k8s-watcher
```

### Reproduction steps
```bash
./cilium install --kube-proxy-replacement strict --config enable-bpf-masquerade=true --config enable-egress-gateway=true
cat << EOF > test-egresspolicy1.yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
metadata:
  name: egress-sample1
spec:
  egress:
  - podSelector:
      matchLabels:
        kind: client
  destinationCIDRs:
  - 192.168.1.1/32
  egressSourceIP: "192.168.33.100"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
metadata:
  name: egress-sample2
spec:
  egress:
  - podSelector:
      matchLabels:
        kind: echo
  destinationCIDRs:
  - 192.168.1.2/32
  egressSourceIP: "192.168.33.100"
EOF
```

### Root cause
That is explicitly disallowed by the code at https://github.com/cilium/cilium/blob/e057d6058e426fbea5ff44946b46d2263e063e42/pkg/egressgateway/manager.go#L249-L255

### Workaround

It's possible to achieve almost the same by combining the two policies:
```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
metadata:
  name: egress-sample2
spec:
  egress:
  - podSelector:
      matchLabels:
        kind: client
  - podSelector:
      matchLabels:
        kind: echo
  destinationCIDRs:
  - 192.168.1.1/32
  - 192.168.1.2/32
  egressSourceIP: "192.168.33.100"
```
Note however that this new egress gateway policy will redirect traffic from `kind=client` destined to `192.168.1.2/32` to the gateway even though the two original policies did not.

<br>

@MasterZ40 @anfernee Do you remember why you added that check? I can't think of a reason why that would be required.
