### ISSUE TITLE
service cannot match endpoint

### ISSUE THREAD

**Issue by mengxifl** [cilium/cilium#17681]
### What happened?

service cannot match endpoint

### What did you expect to happen?

I think service can match pod

### How can we reproduce it (as minimally and precisely as possible)?

```
helm upgrade cilium cilium/cilium --version 1.10.3 --namespace=kube-system \
......
--set prometheus.enabled=true \
--set prometheus.port=9390 \
--set proxy.prometheus.port=9390 \
--set operator.prometheus.enabled=true \
......
```

then I find kube-system ns svc/cilium-agent can not match endpoint 
label had been set . and same as endporint(pod)

![image](https://user-images.githubusercontent.com/48743664/138416069-7233a12b-6ae2-4deb-9f17-33f49f4ead0c.png)
![image](https://user-images.githubusercontent.com/48743664/138416371-24072e37-a854-4629-922a-a97a82253495.png)
```
{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/port":"9390","prometheus.io/scrape":"true"},"labels":{"k8s-app":"cilium"},"name":"cilium-agent","namespace":"kube-system"},"spec":{"clusterIP":"None","ports":[{"name":"envoy-metrics","port":9390,"protocol":"TCP","targetPort":9390}],"selector":{"k8s-app":"cilium"},"type":"ClusterIP"}}
```
![image](https://user-images.githubusercontent.com/48743664/138416572-245cb056-fe6e-48c1-bf4e-54caf69041ea.png)

But When I use the file I'm editing it matches up file 
```
[root@k8smaster00 ~]# cat /yaml/selector.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: cilium-agent
  labels:
     k8s-app: cilium
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: "9390"
spec:
  selector:
    k8s-app: cilium
  type: ClusterIP
  clusterIP: None
  ports:
  - name: envoy-metrics
    port: 9390
    targetPort: 9390
    protocol: TCP

kubectl apply --filename=/yaml/selector.yaml
```
![image](https://user-images.githubusercontent.com/48743664/138417146-959107ff-3021-4b3f-8f55-9adc8ecf6c27.png)
![image](https://user-images.githubusercontent.com/48743664/138417222-90a0f53a-d9f5-49e7-90bd-7e7addcc5f5e.png)

```
{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/port":"9390","prometheus.io/scrape":"true"},"labels":{"k8s-app":"cilium"},"name":"cilium-agent","namespace":"kube-system"},"spec":{"clusterIP":"None","ports":[{"name":"envoy-metrics","port":9390,"protocol":"TCP","targetPort":9390}],"selector":{"k8s-app":"cilium"},"type":"ClusterIP"}}
```

old service same new service but old service can not  match endpoint 

### Kubernetes version

<details>

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T21:01:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

<details>
there is no cloud
</details>

### OS version

<details>
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
Linux k8smaster00 4.20.13-1.el7.elrepo.x86_64 #1 SMP Wed Feb 27 10:02:05 EST 2019 x86_64 x86_64 x86_64 GNU/Linux

</details>

### Install tools

<details>
kubeadm init --skip-phases=addon/kube-proxy
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
cilium --version 1.10.3 
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
