### ISSUE TITLE
Packets loss in DSR mode when request is forwarded to client node

### ISSUE THREAD

**Issue by kvaster** [cilium/cilium#17747]
## Bug report

Service inside k8s is making request to another service inside k8s, but request is made through public name (i.e. via public ip). In some cases request will be dropped.

Config example: 

```
kind: Pod
apiVersion: v1
metadata:
  name: net-test-1
  namespace: default
  labels:
    app: net-test-1
spec:
  nodeName: k8s-1
  containers:
  - name: main
    image: ealen/echo-server
---
kind: Pod
apiVersion: v1
metadata:
  name: net-test-2
  namespace: default
  labels:
    app: net-test-2
spec:
  nodeName: k8s-1
  containers:
  - name: main
    image: ealen/echo-server
---
kind: Pod
apiVersion: v1
metadata:
  name: net-test-3
  namespace: default
  labels:
    app: net-test-3
spec:
  nodeName: k8s-2
  containers:
  - name: main
    image: ealen/echo-server
---
kind: Service
apiVersion: v1
metadata:
  name: net-test-1
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: net-test-1
  externalIPs:
  - 10.117.11.22
  ports:
    - port: 11116
      targetPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: net-test-2
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: net-test-2
  externalIPs:
  - 10.117.11.22
  ports:
    - port: 11117
      targetPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: net-test-3
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: net-test-3
  externalIPs:
  - 10.117.11.22
  ports:
    - port: 11118
      targetPort: 80
```

There are three nodes: `k8s-1`, `k8s-2` and `k8s-3`. External IP `10.117.11.22` is assigned to `k8s-3` node (i.e. ip of load balancer). And there are three services (pods) `net-test-1`, `net-test-2` and `net-test-3`. First two pods are statically assigned to `k8s-1` node and `net-test-3` is assigned to `k8s-2` node.

We'll be making requests from pod `net-test-1`:

```
wget http://10.117.11.22:11116
wget http://10.117.11.22:11117
wget http://10.117.11.22:11118
```

Same requests may be performed directly from node `k8s-1`. Third request (flow is: `k8s-1` -> `k8s-3` -> `k8s-2`) will be executed normally, but first two requests (flow is `k8s-1` -> `k8s-3` -> `k8s-1`) will fail to execute - initial packet will be dropped.

In such case request packet will have IP which belongs to `k8s-1` node. `k8s-3` will receive such packet and will change only dst ip of the packet. As a result, `k8s-1` will receive packet (confirmed via tcpdump) where src ip belongs to `k8s-1` and dst ip is `net-test-1` pod ip. And such packet will be dropped by a system.

Workaround: enabling bpf masquerading solves problem.

**General Information**

- Cilium version: 1.10.5
- Kernel version: 5.14.9
- Orchestration system version in use: kubernetes v1.21.5
- Cilium sysdump:

[cilium-sysdump-20211101-141135.zip](https://github.com/cilium/cilium/files/7452654/cilium-sysdump-20211101-141135.zip)

    ```
    cilium sysdump
    ```
** Cilium setup

```
--set nodePort.enabled=true
--set k8sServiceHost=$API_SERVER_IP
--set k8sServicePort=$API_SERVER_PORT
--set kubeProxyReplacement=strict
--set nativeRoutingCIDR=10.244.0.0/16
--set masquerade=true
--set ipam.mode=kubernetes
--set bpf.masquerade=false
--set devices=${CILIUM_IF}
--set hostServices.enabled=true
--set externalIPs.enabled=true
--set tunnel=disabled
--set autoDirectNodeRoutes=true
--set nodePort.directRoutingDevice=${CILIUM_IF}
--set loadBalancer.mode=dsr
--set global.tag=v1.10.5
```
