### ISSUE TITLE
Short interruption of egress gateway functionality on `CiliumEgressNATPolicy` updates

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#17753]
The logic to update the BPF map and agent caches on `CiliumEgressNATPolicy` updates starts by [removing all policies matching the endpoints](https://github.com/cilium/cilium/blob/203fb2ee27a8faf5dde6cd29553d51d0bc90bb15/pkg/egressgateway/manager.go#L156-L171) before [adding the new versions back](https://github.com/cilium/cilium/blob/203fb2ee27a8faf5dde6cd29553d51d0bc90bb15/pkg/egressgateway/manager.go#L173-L186). As result, the egress gateway feature in the datapath may shortly stop working during the update.

For example, changing `destinationCIDRs` to `192.168.33.0/24` in the following policy may break connections already established for `192.168.33.13/32` because packets may shortly not be redirected and SNATed with a different IP address.
```
apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
metadata:
  name: egress-sample
spec:
  egress:
  - podSelector:
      matchLabels:
        org: empire
        class: mediabot
  destinationCIDRs:
  - 192.168.33.13/32
  egressSourceIP: "192.168.33.100"
```

Note I have not tested this bug; this is just based on a code review.

cc @MasterZ40 @anfernee
