### ISSUE TITLE
GKE kubelet Pod probe source IP denied when using `allow-localhost: always`

### ISSUE THREAD

**Issue by splushii** [cilium/cilium#17839]
## Bug report

Hello! Bumped GKE to `1.21.5-gke.1802` (running Cilium `1.10.4`) and all Pods with healthchecks started to fail. Noticed that the probes have started to originate from the source `169.254.169.252` (the GKE metadata server IP) which got dropped, therefore failing the Pod healthchecks. Adding a CNP allowing the traffic resolved it. Have previously relied on https://docs.cilium.io/en/v1.10/concepts/kubernetes/concepts/#default-ingress-allow-from-local-host. I'm guessing that the problem is that `169.254.169.252` counts as an unmanaged/external IP and not as "local host". It sits on the node `lo` interface:
```shell
# ip -br a
lo               UNKNOWN        127.0.0.1/8 169.254.169.252/32 ::1/128
```

`allow-localhost` is not explicitly set, so using the default value (`auto` -> `always`, being in Kubernetes)

**General Information**

- Cilium version: `1.10.4`
- Kernel version: `5.4.144`
- Kubernetes:  GKE `1.21.5-gke.1802`
```
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5-gke.1802", GitCommit:"d464a255a4acb8dca1e0914586f4f5085681fb51", GitTreeState:"clean", BuildDate:"2021-10-21T21:43:23Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}
```

**How to reproduce the issue**

1. Create a GKE cluster at `1.21.5-gke.1802` and install Cilium `1.10.4`
2. Create a default-deny CNP for a namespace
```yaml
---

apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny
  namespace: <namespace>
spec:
  endpointSelector:
    matchLabels: {}
  egress:
  - {}
  ingress:
  - {}
```
3. Create a workload with network liveness-/readiness-probes in `<namespace>`
4. Liveness-/readiness-probes get dropped
