### ISSUE TITLE
Host firewall drops LLC packets regardless of host policies

### ISSUE THREAD

**Issue by nadiamoe** [cilium/cilium#17877]
## Bug report

I run a Kubernetes cluster at my home, which does not have a very high reliability. Sometime power failures will cause my master node to unexpectedly shut down.

When this happens, after the kubelet is back up, containers lose all kind of network connectivity, both to the outside and inside of the cluster (e.g. they cannot reach the APIServer service endpoint). Liveness probes start to fail and they go into `CrashLoopBackOff`, but the restart does not fix the issue.

The only way to fix it is to manually delete the `cilium` pod. After this, network comes back to the pods normally.

**General Information**

- Cilium version (run `cilium version`) `quay.io/cilium/cilium:v1.10.4`
- Kernel version (run `uname -a`) `5.10.77-3-lts`
- Orchestration system version in use (e.g. `kubectl version`, ...) `Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}`

- Generate and upload a sysdump:

  - [Install Cilium CLI](https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/#install-the-cilium-cli).
  - Run `cilium sysdump` command:

Sysdump taken just after reboot, where the network is not working.
[cilium-sysdump-20211114-154853.zip](https://github.com/cilium/cilium/files/7533981/cilium-sysdump-20211114-154853.zip)

**How to reproduce the issue**

1. Install cilium using the Helm chart. Use the following `values.yml`:
```
cilium:
  kubeProxyReplacement: strict

  k8sServiceHost: 10.0.0.10
  k8sServicePort: 6443

  operator:
    replicas: 1

  externalIPs:
    enabled: true

  hostFirewall: true

  ipam:
    mode: kubernetes

  k8s:
    requireIPv4PodCIDR: true

  egressGateway:
    enabled: false

  # Needed to replace kube-proxy
  hostServices:
    enabled: true
    protocols: tcp,udp

  nodePort:
    enabled: true
    bindProtection: true
    autoProtectPortRange: true
```
2. Restart the master node.
