### ISSUE TITLE
Incorrect policy verdict when using port name in NP

### ISSUE THREAD

**Issue by jonkerj** [cilium/cilium#17903]
## Bug report
I keep running into drop verdicts when I refer to ports by their `name` in (vanilla k8s) network policies. They do not fail consitently, but often in my setup.

**General Information**
- Cilium version: `1.10.5 b0836e8`
- Kernel version: `Linux omitted 5.10.69-talos #1 SMP Thu Sep 30 16:08:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use: Kubernetes v1.22.3
- Link to relevant artifacts: n/a
- Generate and upload a sysdump: will do so upon request.

**How to reproduce the issue**
This is tricky. I can reproduce it fairly easy in my cluster, but when I try to re-create the circumstances from scratch in an empty cluster, everything seems to work perfect.

I've working towards a situation where every pod has explicit egress and ingress policies, using as many NPs as possible, and leveraging CNPs for stuff that can't be covered by NPs yet. One of the failing examples is traffic from ingress-nginx to nextcloud. It is covered by:

ingress-nginx is covered by many policies, but these are the only ones related to nextcloud:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-egress-nextcloud
  namespace: ingress
spec:
  egress:
  - ports:
    - port: http
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: nextcloud
      podSelector:
        matchLabels:
          app.kubernetes.io/component: app
          app.kubernetes.io/name: nextcloud
  podSelector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
  policyTypes:
  - Egress
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  egress:
  - toEntities:
    - host
    - remote-node
    toPorts:
    - ports:
      - port: "6443"
        protocol: TCP
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
  ingress:
  - fromEntities:
    - host
    toPorts:
    - ports:
      - port: metrics
        protocol: TCP
  - fromEntities:
    - host
    - remote-node
    toPorts:
    - ports:
      - port: http
        protocol: TCP
      - port: https
        protocol: TCP
      - port: webhook
        protocol: TCP
```

nextcloud pods/endpoints are not selected by any NP or CNP yet, it was already failing due to the egress policy for nginx before I got to write them.

When it fails, hubble tells me:
```
Nov 16 15:32:56.495: ingress/ingress-nginx-controller-795d4946d9-d89mn:45310 <> nextcloud/nextcloud-7cd59f8777-6nhr7:80 Policy denied DROPPED (TCP Flags: SYN)
Nov 16 15:32:57.515: ingress/ingress-nginx-controller-795d4946d9-d89mn:45310 <> nextcloud/nextcloud-7cd59f8777-6nhr7:80 Policy denied DROPPED (TCP Flags: SYN)
Nov 16 15:32:59.531: ingress/ingress-nginx-controller-795d4946d9-d89mn:45310 <> nextcloud/nextcloud-7cd59f8777-6nhr7:80 Policy denied DROPPED (TCP Flags: SYN)
```

When I change `http` in the networkpolicy above to `80`, traffic passes and hubble shows no drops. To confirm the pod name correspons to the number:

```
$ kubectl get pod -n nextcloud nextcloud-7cd59f8777-6nhr7 -o jsonpath='{.spec.containers[0].ports[0]}'
{"containerPort":80,"name":"http","protocol":"TCP"}
```

I tried playing around with `cilium policy trace` in the situation where I refer to `http` (I know this tool may be deprecated, but I think it demonstrates my issue quite well):

```
$ cilium policy trace --src-k8s-pod ingress:ingress-nginx-controller-795d4946d9-d89mn --dst-k8s-pod nextcloud:nextcloud-7cd59f8777-6nhr7 --dport 80/TCP
----------------------------------------------------------------
Tracing From: [k8s:app.kubernetes.io/component=controller, k8s:app.kubernetes.io/instance=ingress-nginx, k8s:app.kubernetes.io/name=ingress-nginx, k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=ingress, k8s:io.cilium.k8s.namespace.labels.kustomize.toolkit.fluxcd.io/name=ingress, k8s:io.cilium.k8s.namespace.labels.kustomize.toolkit.fluxcd.io/namespace=flux-system, k8s:io.cilium.k8s.policy.cluster=default, k8s:io.cilium.k8s.policy.serviceaccount=ingress-nginx, k8s:io.kubernetes.pod.namespace=ingress] => To: [k8s:app.kubernetes.io/component=app, k8s:app.kubernetes.io/instance=nextcloud, k8s:app.kubernetes.io/name=nextcloud, k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=nextcloud, k8s:io.cilium.k8s.namespace.labels.kustomize.toolkit.fluxcd.io/name=nextcloud, k8s:io.cilium.k8s.namespace.labels.kustomize.toolkit.fluxcd.io/namespace=flux-system, k8s:io.cilium.k8s.policy.cluster=default, k8s:io.cilium.k8s.policy.serviceaccount=default, k8s:io.kubernetes.pod.namespace=nextcloud] Ports: [80/TCP]

Resolving egress policy for [k8s:app.kubernetes.io/component=controller k8s:app.kubernetes.io/instance=ingress-nginx k8s:app.kubernetes.io/name=ingress-nginx k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=ingress k8s:io.cilium.k8s.namespace.labels.kustomize.toolkit.fluxcd.io/name=ingress k8s:io.cilium.k8s.namespace.labels.kustomize.toolkit.fluxcd.io/namespace=flux-system k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=ingress-nginx k8s:io.kubernetes.pod.namespace=ingress]
[.. loads of output without matches ..]
* Rule {"matchLabels":{"k8s:app.kubernetes.io/component":"controller","k8s:app.kubernetes.io/instance":"ingress-nginx","k8s:app.kubernetes.io/name":"ingress-nginx","k8s:io.kubernetes.pod.namespace":"ingress"}}: selected
    Allows to labels {"matchLabels":{"k8s:app.kubernetes.io/component":"app","k8s:app.kubernetes.io/name":"nextcloud","k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name":"nextcloud"}}
      Found all required labels
      Allows port [{http TCP}]
12/52 rules selected
Found allow rule
Found no deny rule
Egress verdict: denied


Final verdict: DENIED
```

When I change `--dport 80/TCP` into `--dport http/TCP`, it gets accepted:

```
[..]
* Rule {"matchLabels":{"k8s:app.kubernetes.io/component":"controller","k8s:app.kubernetes.io/instance":"ingress-nginx","k8s:app.kubernetes.io/name":"ingress-nginx","k8s:io.kubernetes.pod.namespace":"ingress"}}: selected
    Allows to labels {"matchLabels":{"k8s:app.kubernetes.io/component":"app","k8s:app.kubernetes.io/name":"nextcloud","k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name":"nextcloud"}}
      Found all required labels
      Allows port [{http TCP}]
12/52 rules selected
Found allow rule
Found no deny rule
Egress verdict: allowed


Final verdict: ALLOWED
```

Also, when I change `http` into `80`, this behaviour flips: `--dport 80/TCP` gets accepted and `--dport http/TCP` gets denied. It may be a red herring, but the part where it finds an allow rule and still decides to drop feels suspicious to me.

I'd like to think that I am seeing this behaviour on both egress and ingress sides, although all "proof" I've seen so far concerns the egress side (like above).

I've spent many evenings trying to re-create a small reproduction case, without any luck, it always works. So I can't rule out something outside of what I've shown here causes the issues. Any tips on narrowing down this issue would be very welcome.
