### ISSUE TITLE
cilium lrp list is empty after apply a lrp rules

### ISSUE THREAD

**Issue by konghui** [cilium/cilium#17917]
## Bug report
When I use LRP with node-local-dns. I find a problem, when I apply a LRP yaml file. The `cilium lrp list ` out put still is empty. and no extra log output.

LRP yaml:
```
apiVersion: "cilium.io/v2"
kind: CiliumLocalRedirectPolicy
metadata:
  name: "nodelocaldns"
  namespace: kube-system
spec:
  redirectFrontend:
    serviceMatcher:
      serviceName: coredns
      namespace: kube-system
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: node-local-dns
    toPorts:
      - port: "53"
        name: dns
        protocol: UDP
      - port: "53"
        name: dns-tcp
        protocol: TCP
```
![image](https://user-images.githubusercontent.com/379565/142205945-e496b683-601c-4baf-80a0-6812e892cc5e.png)

**General Information**

- Cilium version (run `cilium version`) 1.10.2
- Kernel version (run `uname -a`) 5.9.13
- Orchestration system version in use (e.g. `kubectl version`, ...) 1.19
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a sysdump:  when I run cilium sysdump, it output unknown command.

  - [Install Cilium CLI](https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/#install-the-cilium-cli).
  - Run `cilium sysdump` command:

    ```
    cilium sysdump
    ```

**How to reproduce the issue**

1. apply lrp yaml file
```
apiVersion: "cilium.io/v2"
kind: CiliumLocalRedirectPolicy
metadata:
  name: "nodelocaldns"
  namespace: kube-system
spec:
  redirectFrontend:
    serviceMatcher:
      serviceName: coredns
      namespace: kube-system
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: node-local-dns
    toPorts:
      - port: "53"
        name: dns
        protocol: UDP
      - port: "53"
        name: dns-tcp
        protocol: TCP
```
2.  run `cilium lrp list`
