### ISSUE TITLE
Stop annonsed to bgp peer podCidrs after creating Service LoadBalanser type

### ISSUE THREAD

**Issue by epollia** [cilium/cilium#17922]
## Bug report
**General Information**

- Cilium version 1.11.0-rc1
- Kernel version 5.15.0-1
- Orchestration system version in use kubectl v1.22.3

```
bgp:
  enabled: true
  announce:
    loadbalancerIP: true
    podCIDR: true

```
```
    address-pools:
      - name: default
        protocol: bgp
        avoid-buggy-ips: true
        addresses:
          - 10.60.250.0/24
```
**How to reproduce the issue**

1. Configure BGP, enable bgp.announce.podCIDR = true and loadbalancerIP = true
2. Create Service LoadBalancer
