### ISSUE TITLE
Traffic gets dropped after some time when using toFQDNs

### ISSUE THREAD

**Issue by codablock** [cilium/cilium#18023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

toFQDNs based CNPs result in random traffic drops. It usually starts with allowed traffic, and then for some reason gets forbidden. I have found a reliable reproducer as well:

1. Deploy the following resources:
```yaml
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "allow-dns-policy-endpoint"
spec:
  endpointSelector: {}
  egress:
    - toEntities:
        - all
      toPorts:
        # always allow DNS queries
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: test-cnp
spec:
  egress:
    - toFQDNs:
        - matchPattern: '*.debian.org'
        - matchName: 'registry-1.docker.io'
        - matchName: 'a.example.com'
  endpointSelector:
    matchLabels:
      app: test-pod
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-pod
spec:
  containers:
  - name: test-pod
    image: debian
    imagePullPolicy: IfNotPresent
    command:
    - sh
    - -c
    - |
      apt update
      apt install -y wget curl inetutils-ping dnsutils
      sleep infinity
```
2. Wait for test-pod to have the apt install finished.
3. Shell into test-pod and verify that `curl https://registry-1.docker.io` is returning 404 (so, traffic is accepted).
4. Modify the CNP test-cnp and change a.example.com to b.example.com. Deploy this and wait for 10 seconds or so.
5. Retry point 3., this time a timeout is happening instead of a 404.

Looking at hubble while doing 3. and 5. reveals that the target identity changes. In 3., it is an identity with a single /32 cidr, pointing at one of the IPs returned by DNS queries to registry-1.docker.io. In 5., the identity used is `world`. Checking `cilium identity list` confirms the disappearance of the initial identity.

The situation sometimes fixes itself, sometimes not. Using `cilium fqdn cache clean` speeds up the self-healing, leading to 5. using a proper identity again.

### Cilium Version

1.11.0-rc3

### Kernel Version

Linux ip-100-65-69-100.eu-central-1.compute.internal 5.4.156-83.273.amzn2.x86_64 #1 SMP Sat Oct 30 12:59:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.21.2-eks-0389ca3 on control-plane and v1.21.5 on the nodes.

### Sysdump

I prefer to not include a sysdump as I don't know what info it will contain.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
