### ISSUE TITLE
eBPF host routing breaks remote-node identity classification

### ISSUE THREAD

**Issue by bazuchan** [cilium/cilium#18042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm running cilium on k3s with metallb. I have setup cilium with loadBalancer.mode=hybrid. I have UDP service and corresponding network policy to allow its traffic:
```
- apiVersion: v1         
  kind: Service
  metadata:
    labels:     
      app: oregon            
    annotations:
      metallb.universe.tf/allow-shared-ip: 'true'
    name: oregon  
    namespace: hass
  spec:                      
    ports:                                                                                                                                                                                     
    - name: oregon-udp
      port: 4360
      protocol: UDP
      targetPort: 4360
    selector:
      app: oregon
    loadBalancerIP: 172.17.2.230
    type: LoadBalancer
- apiVersion: cilium.io/v2
  kind: CiliumNetworkPolicy
  metadata:
    name: oregon-udp
    namespace: hass
  spec:
    endpointSelector:
      matchLabels:
        app: oregon
    ingress:
    - fromEntities:
      - remote-node
      toPorts:
        - ports:
            - port: '4360'
              protocol: UDP
    - fromCIDRSet:
        - cidr: 172.17.2.70/32
        - cidr: 172.17.2.71/32
      toPorts:
        - ports:
            - port: '4360'
              protocol: UDP
```
But packets gets dropped when loadbalanced to another node:
```
$ kubectl -n kube-system exec -ti cilium-f285n -- cilium monitor | grep 4360
Policy verdict log: flow 0x0 local EP ID 3521, remote ID world, proto 17, ingress, action deny, match none, 172.17.5.1:42644 -> 172.17.194.61:4360 udp
xx drop (Policy denied) flow 0x0 to endpoint 3521, identity world->17290: 172.17.5.1:42644 -> 172.17.194.61:4360 udp
```
```
$ kubectl get ciliumendpoints -A | grep oregon
hass             oregon-788c446575-2h5k6                        3521          17290                                                                        ready            172.17.194.61
```

For some reason `172.17.5.1/32` gets classified as `world`, but should be classified as `remote-node` (6):
```
$ kubectl -n kube-system exec -ti cilium-f285n -- cilium bpf ipcache list | grep ' 6 '
172.17.2.92/32      6 0 0.0.0.0
172.17.193.2/32     6 0 172.17.5.2
172.17.192.172/32   6 0 172.17.5.1
172.17.2.91/32      6 0 0.0.0.0
172.17.5.2/32       6 0 0.0.0.0
172.17.5.1/32       6 0 0.0.0.0
```

Cilium installed from chart with folowing configuration:
```
--set tunnel=disabled
--set autoDirectNodeRoutes=true
--set kubeProxyReplacement=strict
--set loadBalancer.mode=hybrid
--set k8sServiceHost=172.17.5.100
--set k8sServicePort=6443
--set hubble.enabled=false
--set ipam.operator.clusterPoolIPv4PodCIDR=172.17.192.0/18
--set nativeRoutingCIDR=172.17.192.0/18
```

### Cilium Version

1.10.5

### Kernel Version

5.11.0-16-generic

### Kubernetes Version

K3S

Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
> For some reason `172.17.5.1/32` gets classified as `world`, but should be classified as `remote-node` (6):

Uh, that's indeed weird. Would you be able to share a sysdump and the full path of the packet on the receiving node with `monitor-aggregation` disabled? That should tell us which BPF program assigned the source identity to the packet and what the packet looked like at that point.

**Comment by bazuchan** [comment]
[cilium-sysdump-20211130-140816.zip](https://github.com/cilium/cilium/files/7625234/cilium-sysdump-20211130-140816.zip)

**Comment by bazuchan** [comment]
On node with metallb listener:
```
<- network flow 0x0 identity unknown->unknown state new ifindex wire0.2 orig-ip 0.0.0.0: 172.17.2.71:42644 -> 172.17.2.230:4360 udp
-> network flow 0x0 identity unknown->unknown state new ifindex 0 orig-ip 0.0.0.0: 172.17.5.1:42644 -> 172.17.194.61:4360 udp
```

On node with pod:
```
<- network flow 0x0 identity unknown->unknown state new ifindex wire0.5 orig-ip 0.0.0.0: 172.17.5.1:49890 -> 172.17.194.61:4360 udp
Policy verdict log: flow 0x0 local EP ID 3521, remote ID world, proto 17, ingress, action deny, match none, 172.17.5.1:49890 -> 172.17.194.61:4360 udp
xx drop (Policy denied) flow 0x0 to endpoint 3521, identity world->17290: 172.17.5.1:49890 -> 172.17.194.61:4360 udp
```

**Comment by hwaastad** [comment]
Hi, I've seen similar issue in my configuration.
Running Rancher RKE2 and cilium 1.10.4 (Flatcar OS)
https://cilium.slack.com/archives/C01JALNQAR1/p1638544034273000
Tested using default global health networkpolicy and auditing.
```
Policy verdict log: flow 0x0 local EP ID 2245, remote ID host, proto 1, ingress, action allow, match L3-Only, 10.42.1.72 -> 10.42.1.91 EchoRequest
Policy verdict log: flow 0x0 local EP ID 2245, remote ID world, proto 1, ingress, action audit, match none, 10.210.151.106 -> 10.42.1.91 EchoRequest
```
and
```
<- host flow 0x0 identity host->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.42.1.72 -> 10.42.1.200 EchoRequest
Policy verdict log: flow 0x0 local EP ID 803, remote ID host, proto 1, ingress, action allow, match L3-Only, 10.42.1.72 -> 10.42.1.200 EchoRequest
-> endpoint 803 flow 0x0 identity host->health state new ifindex lxc_health orig-ip 10.42.1.72: 10.42.1.72 -> 10.42.1.200 EchoRequest
<- endpoint 803 flow 0x0 identity health->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.42.1.200 -> 10.42.1.72 EchoReply
-> host from flow 0x0 identity health->host state reply ifindex cilium_net orig-ip 0.0.0.0: 10.42.1.200 -> 10.42.1.72 EchoReply
-> stack flow 0x0 identity unknown->unknown state new ifindex cilium_host orig-ip 0.0.0.0: 10.42.1.200 -> 10.42.1.72 EchoReply
<- network flow 0x0 identity unknown->unknown state new ifindex ens33 orig-ip 0.0.0.0: 10.42.0.46 -> 10.210.151.105 EchoReply
<- network flow 0x0 identity unknown->unknown state new ifindex ens33 orig-ip 0.0.0.0: 10.210.151.106 -> 10.210.151.105 EchoReply
```
My current config is:
```
cilium:
  azure:
    enabled: false
  cni:
    chainingMode: none
    customConf: false
  eni:
    enabled: false
  image:
    repository: rancher/mirrored-cilium-cilium
    tag: v1.10.4
    useDigest: false
  imagePullSecrets: []
  ipam:
    mode: kubernetes
  ipv6:
    enabled: false
  masquerade: true
  nodeinit:
    image:
      repository: rancher/mirrored-cilium-startup-script
      tag: 62bfbe88c17778aad7bef9fa57ff9e2d4a9ba0d8
  operator:
    image:
      repository: rancher/mirrored-cilium-operator
      tag: v1.10.4
    replicas: 1
  preflight:
    enabled: false
    image:
      repository: rancher/mirrored-cilium-cilium
      tag: v1.10.4
  tunnel: disabled
  autoDirectNodeRoutes: true
  hostFirewall: true
  hostServices:
    enabled: true
  k8sServiceHost: 10.210.151.107
  k8sServicePort: 6443
  kubeProxyReplacement: strict
  nativeRoutingCIDR: 10.42.0.0/16
  policyAuditMode: true
global:
  systemDefaultRegistry: ''
```
pretty std, but I also add a kube-vip manifest to my konfig to get the proxy-free konfig HA.
