### ISSUE TITLE
Cilium 1.11.0 does not start on EKS with pod subnet-filter

### ISSUE THREAD

**Issue by mhulscher** [cilium/cilium#18239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am installing Cilium 1.11.0 on a brand new EKS cluster on nodes that did not previously have a CNI installed. The cilium-agents do not become ready. They create CiliumNode resources. However, the cilium-operator does not allocate ENIs/IPs to the nodes. As a result the nodes don't become ready. The VPCs primary and secondary CIDRs don't seem to be discovered either.

### Cilium Version

1.11.0

### Kernel Version

5.4.156-83.273.amzn2.x86_64

### Kubernetes Version

v1.21.2-eks-06eac09

### Sysdump

I don't feel comfortable sharing this in a public github issue. Please reach out and I can share this privately.

### Anything else?

Installing cilium 1.10.5 with the same values.yaml works well.

EDIT: Just tested, the same values also work with 1.10.6. So the problem is unlikely to be present in any of the fixes backported to 1.10

Collected log files:

[cilium-1-11-0.zip](https://github.com/cilium/cilium/files/7696918/cilium-0-11-0.zip)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mhulscher** [comment]
Interestingly enough I can upgrade Cilium on existing nodes from 0.10 to 0.11. However, new nodes don't become ready with 0.11.

**Comment by pchaigno** [comment]
> I am installing Cilium 0.11.0

I guess you meant Cilium 1.11.0? We've had stable releases for years now :sweat_smile: 

In the cilium-operator logs, I'm seeing a lot of warnings for different nodes:
```
level=warning msg="Instance not found! Please delete corresponding ciliumnode if instance has already been deleted." instanceID=i-02ad8b4c55e4a7c08 name=ip-10-28-92-98.eu-west-1.compute.internal subsys=ipam
```
It's probably because the operator can't find the nodes that it is not allocating ENIs and IP addresses.

Could you please share the `ciliumnodes-xxx.yaml` and `k8s-nodes-xxx.yaml` files from the sysdump?

**Comment by mhulscher** [comment]
Yes, this relates to 1.11.0 :') I will reproduce the issue again tomorrow and attach the ciliumnodes and k8s-nodes

**Comment by mhulscher** [comment]
I've attached the files.
[cilium-sysdump-20211215-113339.zip](https://github.com/cilium/cilium/files/7718565/cilium-sysdump-20211215-113339.zip)

**Comment by azharprabudi** [comment]
i face the same problem when configure filter subnets by id or tags

**Comment by pchaigno** [comment]
@mhulscher @azharprabudi Could you share the exact reproduction steps if you have them?

**Comment by amilanoski** [comment]
I am facing this issue in 1.10.6

eni portion helm values.yaml
```
eni:
  # -- Enable Elastic Network Interface (ENI) integration.
  enabled: true
  # -- Update ENI Adapter limits from the EC2 API
  updateEC2AdapterLimitViaAPI: true
  # -- Release IPs not used from the ENI
  awsReleaseExcessIPs: true
  # -- EC2 API endpoint to use
  ec2APIEndpoint: ""
  # -- Tags to apply to the newly created ENIs
  eniTags: {}
  # -- If using IAM role for Service Accounts will not try to
  # inject identity values from cilium-aws kubernetes secret.
  # Adds annotation to service account if managed by Helm.
  # See https://github.com/aws/amazon-eks-pod-identity-webhook
  iamRole: "arn:aws:iam::xxxx:role/cilium_operator_serviceaccount_role"
  # -- Filter via subnet IDs which will dictate which subnets are going to be used to create new ENIs
  # subnetIDsFilter: ""
  subnetIDsFilter: "subnet-097xxxxxfabc3,subnet-0f7cbxxxa4d3d,subnet-0892xxx003d7"
  # -- Filter via tags (k=v) which will dictate which subnets are going to be used to create new ENIs
  # subnetTagsFilter: function=eks
  subnetTagsFilter: ""
```

Logs: in operator showing similar logs

```
level=info msg="Synchronized ENI information" numInstances=0 numSecurityGroups=12 numSubnets=0 numVPCs=1 subsys=eni
level=debug msg="Resetting resyncNeeded" instanceID=i-07a87xxxa424d1 name=ip-100-88-xx-x.ec2.internal subsys=ipam
level=warning msg="Instance not found! Please delete corresponding ciliumnode if instance has already been deleted." instanceID=i-07a87xxx7aa424d1 name=ip-100-88-xx-xx.ec2.internal subsys=ipam
level=warning msg="Instance not found! Please delete corresponding ciliumnode if instance has already been deleted." instanceID=i-07a87xxxa424d1 name=ip-100-88-xx-xx.ec2.internal subsys=ipam
level=debug msg="Resetting resyncNeeded" instanceID=i-00980xxx4890cca name=ip-100-88-xx-xx.ec2.internal subsys=ipam
```

however when I update value **subnetTagsFilter** with like below

`subnetTagsFilter: function=eks`

logs show
`level=info msg="Synchronized ENI information" numInstances=11 numSecurityGroups=12 numSubnets=11 numVPCs=1 subsys=eni`

Notice the **numSubnets**

It looks like the operator is filtering correctly based on the parameters that are being passed to it.
