### ISSUE TITLE
Cilium 1.11 fails the kubernetes e2e test "[sig-network] Services should create endpoints for unready pods"

### ISSUE THREAD

**Issue by olemarkus** [cilium/cilium#18241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium 1.11 fails the kubernetes e2e test `[sig-network] Services should create endpoints for unready pods`
https://github.com/kubernetes/kops/pull/12919 is a PR that only changes the default cilium version to 1.11.

The test log can be found at https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/12919/pull-kops-e2e-cni-cilium/1469638304646303744/build-log.txt
The pod logs and config maps can be found at https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kops/12919/pull-kops-e2e-cni-cilium/1469638304646303744/artifacts/cluster-info/kube-system/

### Cilium Version

1.11.0

### Kernel Version

Linux ip-172-20-33-11 5.10.0-9-cloud-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

### Kubernetes Version

1.23.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by olemarkus** [comment]
Just to let you know that this failure still persists on cilium 1.11

**Comment by aditighag** [comment]
We skip non-ready endpoints in Cilium while parsing endpoint slice resources.  Do you have a use case for considering non-ready pods for load-balancing service traffic? Or is this bug filed to mainly track the k8s sig-network test failure?

**Comment by aditighag** [comment]
>Services should create endpoints for unready pods

Do you know how the test validates this behavior? Does it send traffic to the non-ready pods?

**Comment by olemarkus** [comment]
I have not looked very closely at exactly how k/k implemented the test. I would assume it only checks that there is a service endpoint. I don't see how it could be a requirement that the non-ready endpoint actually accepts traffic.

That being said, I would also assume that cilium is not responsible for populating these endpoints, but that KCM did this. So it could be the case it actually tries to send traffic.

**Comment by johngmyers** [comment]
The test is at https://github.com/kubernetes/kubernetes/blob/9c3a0e63a71c0890a5ab1aa0a267e91a81e5c441/test/e2e/network/service.go#L1648

It creates a Service with the `spec.publishNotReadyAddresses` field set to true and appears to send traffic to the service cluster ip and verify it is received by the non-ready pod. It then turns off `publishNotReadyAddresses` and verifies the non-ready pod is no longer reachable.

**Comment by olemarkus** [comment]
Another related test failing: `Services should be able to connect to terminating and unready endpoints if PublishNotReadyAddresses is true`

**Comment by aojea** [comment]
@aanm what Endpoint/EndpointSlices uses Cilium to map the Service to the Pods? this CRD ?

https://github.com/cilium/cilium/blob/01f7d9a4a51735afdd1d0b8288cd34e539eaa8a2/Documentation/network/kubernetes/ciliumendpointslice.rst#L16

because the EndpointSlices present those pods in the ready addresses when the Service PublishNotReadyAddresses is true

**Comment by aanm** [comment]
@aojea It uses the one available in the cluster, either k8s endpoints or k8s endpointslices.

**Comment by aojea** [comment]
I'm trying to figure out why it omits these Pods, if the Service sets PublishNotReadyAddresses the Endpoints and EndpointSlices controller sets their state to read on the corresponding object 

https://gist.github.com/aojea/30ee9ff53022d6b3e6156c4d2e570852

is there any other source of readiness for the Pods in cilium?

**Comment by aojea** [comment]
in this test, the Pod has a graceful timeout of 600 seconds, it gets deleted and after that, the Pod will become unready but will still be able to serve traffic, and since the Service has `PublishNotReadyAddresses` it will be available on the endpoints

> Jan 27 12:58:12.082: INFO: At 2023-01-27 12:52:56 +0000 UTC - event for slow-terminating-unready-pod: {replication-controller } SuccessfulDelete: Deleted pod: slow-terminating-unready-pod-nk64j

It seems that there is a pod controller that 

https://github.com/cilium/cilium/blob/e4889d72f9a8f86bee47327dbab7b46773607a7e/pkg/k8s/watchers/pod.go#L61-L126

if this controller sees the Delete and removes the pod from the cilium endpoints, then it may explain why the test fails, since it is not sending traffic to it ... but I'm not familiar with the code, so just throwing ideas 

@squeed we went through this together in our previous gig ;) , the edge vs trigger thing, it is better if you reconcile instead of processing the events directly ...

**Comment by aojea** [comment]
I was wrong, the problem is simpler, it seems that cilium does not implement this kubernetes feature `service.Spec. PublishNotReadyAddresses` at all, at least I could not find any place that checks for that field in the codebase
```
grep -r PublishNotReadyAddresses | grep -v vendor
aojea@aojea:~/src/cilium$ 
```

/cc @thockin

**Comment by aojea** [comment]
another false assumption it seems I did, that information is set on the EndpointSlice

```
ready := service.Spec.PublishNotReadyAddresses || (serving && !terminating)
pkg/controller/endpointslice/utils.go
```

unless there is a check in cilium on the pod status in addition to the endpointslice status ...

**Comment by aojea** [comment]
ok, I verified that `service.Spec.PublishNotReadyAddresses` works correctly in Cilium

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: MyApp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: MyApp
  template:
    metadata:
      labels:
        app: MyApp
    spec:
      containers:
      - name: agnhost
        image: k8s.gcr.io/e2e-test-images/agnhost:2.39
        args:
          - netexec
          - --http-port=80
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
---
apiVersion: v1
kind: Service
metadata:
  name: notready-service
spec:
  type: ClusterIP
  selector:
    app: MyApp
  publishNotReadyAddresses: true
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```

pods are not ready
```
kubectl get pods
NAME                                 READY   STATUS    RESTARTS   AGE
server-deployment-58bc78d657-kz6vv   0/1     Running   0          11s
server-deployment-58bc78d657-q7mlz   0/1     Running   0          11s
```
Service is created
```
kubectl get service
NAME               TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
kubernetes         ClusterIP   10.96.0.1     <none>        443/TCP   20m
notready-service   ClusterIP   10.96.68.59   <none>        80/TCP    11m
```

curl to the service works, ciliums forwards traffic correctly
```
curl 10.96.68.59/hostname
server-deployment-58bc78d657-kz6vvroot@kind-worker:/# curl 10.96.68.59/hostname
server-deployment-58bc78d657-q7mlzroot@kind-worker:/# curl 10.96.68.59/hostname
server-deployment-58bc78d657-q7mlzroot@kind-worker:/# curl 10.96.68.59/hostname
```

it has to be here then

```
		ginkgo.By("Check if terminating pod is available through service")
```

the handling of terminating 👀

**Comment by aojea** [comment]
ok, confirmed , the bugs is on how the terminating is being handled

```
apiVersion: v1
kind: Pod
metadata:
  name: terminating
  labels:
    app: MyApp
spec:
  terminationGracePeriodSeconds: 300
  containers:
  - name: agnhost
    image: k8s.gcr.io/e2e-test-images/agnhost:2.39
    args:
      - netexec
      - --http-port=80
      - --delay-shutdown=300
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: terminating-service
spec:
  type: ClusterIP
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```
```
 kubectl get service
NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
kubernetes            ClusterIP   10.96.0.1       <none>        443/TCP   33m
terminating-service   ClusterIP   10.96.183.210   <none>        80/TCP    2m57s
```

once you delete the pod, the traffic to the service stops
```
kubectl delete pod terminating
pod "terminating" deleted
```
but the connectivity to the pod works
```
 curl  10.96.183.210/hostname
curl: (7) Couldn't connect to server
root@kind-worker:/# curl 10.244.0.58/hostname
terminatingroot@kind-worker:/#
```

however, I still see the service in cilium

```
6    10.96.183.210:80   ClusterIP      1 => 10.244.0.58:80 (terminating)
```
