### ISSUE TITLE
Network randomly dropping between 2 nodes after few days with IPsec

### ISSUE THREAD

**Issue by GabMgt** [cilium/cilium#18256]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

Hello everyone,
Since months I have a weird issue with cilium:
The network is working fine but after few days two nodes on the cluster can't communicate anymore. After rebooting one of them, they can communicate again but after few days the problem re-appears.

### Cilium Version

I have this problem since I started with cilium (1.10.0) to now (1.10.6)

### Kernel Version

I had this problem with debian 10 (4.19 kernel) and after upgrading to debian 11 (5.10 kernel) the problem is still here.

```
Linux [CONFIDENTIAL] 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
```

### Kubernetes Version

v1.21.1 with cri-o v1.21.4

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

I can't upload a sysdump due to confidentiality reasons, sorry.

### Anything else?

For confidentiality purpose, I must replace the hostname and IP of the faulty nodes with NODE-A / NODE-B and IP-A / IP-B:

When I run a cilium status (with grep 'Cluster health') on each cilium pod I see this:
```
Cluster health:                                  10/11 reachable   (2021-12-14T10:08:45Z) # this is the NODE-A
Cluster health:         11/11 reachable   (2021-12-14T10:09:12Z)
Cluster health:         11/11 reachable   (2021-12-14T10:09:33Z)
Cluster health:         11/11 reachable   (2021-12-14T10:08:45Z)
Cluster health:         11/11 reachable   (2021-12-14T10:08:46Z)
Cluster health:                                  10/11 reachable   (2021-12-14T10:09:30Z) # this is the NODE-B
Cluster health:         11/11 reachable   (2021-12-14T10:08:42Z)
Cluster health:         11/11 reachable   (2021-12-14T10:09:24Z)
Cluster health:         11/11 reachable   (2021-12-14T10:09:08Z)
Cluster health:         11/11 reachable   (2021-12-14T10:09:21Z)
Cluster health:         11/11 reachable   (2021-12-14T10:07:59Z)
```

When I run the `cilium-health status` command on NODE-A, I can see this:

```
  NODE-B:
    Host connectivity to IP-B:
      ICMP to stack:   OK, RTT=1.155894ms
      HTTP to agent:   OK, RTT=1.080386ms
    Endpoint connectivity to 10.244.10.112:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.244.10.112:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

When I run the `cilium-health status` command on NODE-B, I can see this:

```
  NODE-A:
    Host connectivity to IP-A:
      ICMP to stack:   OK, RTT=2.893292ms
      HTTP to agent:   OK, RTT=1.073204ms
    Endpoint connectivity to 10.244.11.37:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.244.11.37:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

I also did a tcpdump on each node an find out that:
- When I send pings from `NODE-A` to `NODE-B` (using cilium private IP), I see ICMP packages on `NODE-B`
- When I send pings from `NODE-B` to `NODE-A` (using cilium private IP), I don't see ICMP packages on `NODE-A`

So I deduce that `NODE-A` can communicate with `NODE-B`, but `NODE-B` cannot communicate with `NODE-A` using the cilium private IP but I don't know why.

Another important thing: the problem is ALWAYS with the two same nodes and I am seeing this same issue with all my k8s clusters with cilium.
Those clusters have different size (11 nodes for this one but I have another one with +130 nodes and the same problem appears) 

If someone can help me, it would be very nice, thank you very much in advance.
(if you need more logs/information, I will provide them quickly)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
> Another important thing: the problem is ALWAYS with the two same nodes and I am seeing this same issue with all my k8s clusters with cilium.
Those clusters have different size (11 nodes for this one but I have another one with +130 nodes and the same problem appears)

And it always happen between only two nodes? What's specific about those nodes?

> When I send pings from NODE-B to NODE-A (using cilium private IP), I don't see ICMP packages on NODE-A

Are you able to trace these dropped packets? Where along the path are they dropped? Are they dropped by Cilium?

**Comment by GabMgt** [comment]
> And it always happen between only two nodes? What's specific about those nodes?
Yes and it's always only the 2 same nodes on every clusters. I don't know, they are identical and configured with ansible, so a missconfiguration seems unlikely.

> Are you able to trace these dropped packets? Where along the path are they dropped? Are they dropped by Cilium?
Well, for now I don't know how to get this information. For now I assume that the network and firewall are ok on every node (because everything was working yesterday and this morning it was broken without reconfiguration).

**Comment by pchaigno** [comment]
> Yes and it's always only the 2 same nodes on every clusters.

If they are nodes on different clusters, what do you mean by "the 2 same nodes"? How do you identify them as being the same?

> Well, for now I don't know how to get this information.

You can check https://docs.cilium.io/en/stable/operations/troubleshooting/#observing-flows-with-hubble.

**Comment by GabMgt** [comment]
> If they are nodes on different clusters, what do you mean by "the 2 same nodes"? How do you identify them as being the same?

Sorry, I understand how it was confusing.
I have multiple clusters with k8s + cilium + cri-o

And sometime in a cluster two nodes (in the same k8s cluster) cannot communicate on the private network anymore.
It is always the 2 same nodes (I know it because I know the hostname of the "faulty" nodes).

Example: in the staging cluster, it is always between `node-7` and `node-8`, and in the "internal services" cluster it is always between the `node-5` and `node-8`. (and I don't use the cluster mesh feature)

I hope it's more understandable now, sorry maybe it is my bad english.

> You can check https://docs.cilium.io/en/stable/operations/troubleshooting/#observing-flows-with-hubble.

Thank you I will check.

**Comment by GabMgt** [comment]
I also tried to monitor dropped packets with:

```
kubectl -n kube-system exec -c cilium-agent cilium-c8ktf -- cilium monitor --type drop
kubectl -n kube-system exec -c cilium-agent cilium-ztp24 -- cilium monitor --type drop
```

On `NODE-A` and `NODE-B` but found nothing

**Comment by GabMgt** [comment]
I swear, I really tried to debug this issue but I don't find any clue. Do you know what I do more please ?

**Comment by aanm** [comment]
@GabMgt have you checked if you have any firewall rules deployed between those 2 nodes? Are you using ArgoCD by any chance?

**Comment by GabMgt** [comment]
Hello @aanm and thank you for your response. Yes I checked the firewall and there is not blocking rule. I am not using ArgoCD, why ?

**Comment by aanm** [comment]
This is a duplicate of https://github.com/cilium/cilium/issues/18256

**Comment by aanm** [comment]
@GabMgt please send me a sysdump of the cluster over slack where it has at least the source and the destination nodes having issues. My username on slack.cilium.io is `aanm`

**Comment by GabMgt** [comment]
I am sorry but I can't. These are clusters at the company I work at. I built a "decoy" cluster with the same config for this purpose but no network issue since 2 weeks.

**Comment by GabMgt** [comment]
The decoy cluster is still running without a network issue.

We switch the container engine from cri-o (1.21.X) to containerd (1.5.9) and no problem since 2-3 weeks.

**Comment by GabMgt** [comment]
We just had the same problem with 2 nodes:

```
VERSION   OS-IMAGE                         KERNEL-VERSION    CONTAINER-RUNTIME
v1.20.1   Debian GNU/Linux 11 (bullseye)   5.10.0-11-amd64   containerd://1.5.9
```

This issue makes me crazy

**Comment by yilas** [comment]
Hi all,
I just found a way to "solve" that issue. It seems that the issue came from `ipsec` since the connection came back between the both pods after following these steps :
- Flush all state in `xfrm` with an `ip xfrm state flush` on both worker nodes
- Wait the recreation of states by the cilium agent
- Test connections => OK

If the same error reappears, I will do more selective flushes on the concerned networks.
I guess something went wrong at the ipsec layer but what ? I don't see the way to troubleshoot that part, to be honest.

**Comment by pchaigno** [comment]
Do you have any non-zero counters in `/proc/net/xfrm_stat`?

**Comment by yilas** [comment]
Yes, for the node which encountered the issue, I get these non-zero values :

```bash
root@eu2-data-39:/home/cilium# grep -v 0$ /proc/net/xfrm_stat
XfrmInError             	1
XfrmInNoStates          	33
```

**Comment by GabMgt** [comment]
Hey, sadly I still have this issue even with the recent versions of cilium.

**Comment by yilas** [comment]
> Is this with node encryption enabled or just the default pod-to-pod encryption? Could you share your Cilium config?

Here is the configuration of Cilium (from the ConfigMap `cilium-config`)

```yaml
apiVersion: v1
data:
  auto-direct-node-routes: "false"
  bpf-lb-external-clusterip: "false"
  bpf-lb-map-max: "65536"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  clean-cilium-state: "false"
  cluster-id: "1"
  cluster-name: eu1
  cluster-pool-ipv4-cidr: 10.201.0.0/16
  cluster-pool-ipv4-mask-size: "24"
  custom-cni-conf: "false"
  debug: "false"
  disable-cnp-status-updates: "true"
  disable-endpoint-crd: "false"
  enable-auto-protect-node-port-range: "true"
  enable-bandwidth-manager: "false"
  enable-bpf-clock-probe: "true"
  enable-endpoint-health-checking: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-hubble: "false"
  enable-ipsec: "true"
  enable-ipv4: "true"
  enable-ipv4-masquerade: "true"
  enable-ipv6: "false"
  enable-ipv6-masquerade: "true"
  enable-k8s-terminating-endpoint: "true"
  enable-l2-neigh-discovery: "true"
  enable-l7-proxy: "true"
  enable-local-redirect-policy: "false"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  etcd-config: |-
    ---
    endpoints:
      - https://ip_etcd_1:2379/
      - https://ip_etcd_2:2379/
      - https://ip_etcd_3:2379/
    trusted-ca-file: '/var/lib/etcd-secrets/etcd-client-ca.crt'
    key-file: '/var/lib/etcd-secrets/etcd-client.key'
    cert-file: '/var/lib/etcd-secrets/etcd-client.crt'
  hubble-disable-tls: "false"
  hubble-listen-address: :4244
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: kvstore
  install-iptables-rules: "true"
  install-no-conntrack-iptables-rules: "false"
  ipam: cluster-pool
  ipsec-key-file: /etc/ipsec/keys
  kube-proxy-replacement: disabled
  kvstore: etcd
  kvstore-opt: '{"etcd.config": "/var/lib/etcd-config/etcd.config"}'
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  operator-api-serve-addr: 127.0.0.1:9234
  preallocate-bpf-maps: "false"
  sidecar-istio-proxy-image: cilium/istio_proxy
  tunnel: vxlan
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: cilium
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cilium-config
  namespace: kube-system
  ```
