### ISSUE TITLE
Enabling DSR + WireGuard breaks connectivity to cluster-cidr

### ISSUE THREAD

**Issue by rlex** [cilium/cilium#18257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Enabling DSR breaks service-cidr connectivity

k3s 1.22, cilium 1.11.0, network running on top of wireguard. Everything works great, but when i enable DSR i lose connectivity to service-cidr. 

Config (DSR parts commented out)
```yaml
repositories:
  - name: cilium
    url: https://helm.cilium.io/

releases:
  - name: cilium
    kubeContext: lbn-de1
    namespace: kube-system
    createNamespace: true
    chart: cilium/cilium
    values:
      - debug:
          enabled: false
      - kubeProxyReplacement: strict
      - rollOutCiliumPods: true
      - k8sServiceHost: 127.0.0.1
      - k8sServicePort: 16443
      - bandwidthManager: true
      - l7Proxy: true
      - hostFirewall:
          enabled: true
      - monitor:
          enabled: true
#      - ipv4NativeRoutingCIDR: 10.0.0.0/16
#      - autoDirectNodeRoutes: true
#      - tunnel: disabled
#      - loadBalancer:
#          mode: dsr
#      - endpointRoutes:
#          enabled: true
      - nodeinit:
          restartPods: true
      - devices:
          - eth0
          - wg0
#      - installNoConntrackIptablesRules: true
      - bpf:
          masquerade: true
      - ipam:
          mode: "cluster-pool"
          operator:
            clusterPoolIPv4PodCIDRList:
              - 10.0.0.0/16
            clusterPoolIPv4MaskSize: 24
      - encryption:
          enabled: false
          type: wireguard
      - hubble:
          listenAddress: ":4244"
          relay:
            enabled: true
          tls:
            auto:
              method: cronJob
          metrics:
            enabled:
              - dns:query;ignoreAAAA
              - drop
              - tcp
              - flow
              - icmp
              - http
            serviceMonitor:
              enabled: true
          ui:
            enabled: true
            ingress:
              enabled: true
              className: nginx
              annotations:
                kubernetes.io/ingress.class: "nginx"
              hosts:
                - hubble.example.com
      - prometheus:
          enabled: true
          serviceMonitor:
            enabled: true
      - operator:
          prometheus:
            enabled: true
            port: 6942
            serviceMonitor:
              enabled: true
          nodeSelector:
            node-role.kubernetes.io/master: "true"
      - hostServices:
          enabled: true
          protocols: tcp,udp
      - monitor:
          enabled: false
      - pprof:
          enabled: true
      - containerRuntime:
          integration: containerd
```

k3s default service-cidr is 10.43.0.0/16, k8s apiserver is located at 10.43.0.1, and as soon as i enable DSR i start seeing timeouts to 10.43.0.1:443

### Cilium Version

cilium-cli: 0.10.0 compiled with go1.17.3 on darwin/amd64
cilium image (default): v1.11.0
cilium image (stable): v1.11.0
cilium image (running): v1.11.0

### Kernel Version

5.11.0-40-generic #44~20.04.2-Ubuntu

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:08:39Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3+k3s1", GitCommit:"61a2aab25eeb97c26fa3f2b177e4355a7654c991", GitTreeState:"clean", BuildDate:"2021-11-04T00:24:35Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
> Config (DSR parts commented out)

Do you mean it doesn't work once you uncomment ALL the commented lines? `endpointRoutes.enabled` and `installNoConntrackIptablesRules` shouldn't be required for DSR to work. Does it work if you run in native routing mode without DSR?

> k3s default service-cidr is 10.43.0.0/16, k8s apiserver is located at 10.43.0.1, and as soon as i enable DSR i start seeing timeouts to 10.43.0.1:443

Are you able to trace the connections to 10.43.0.1:443 to see where the packets are dropped? Are they dropped by Cilium?

**Comment by rlex** [comment]
installNoConntrackIptablesRules is indeed leftover and doesn't get uncommented when i enable DSR. Only following gets enabled:

```
#      - ipv4NativeRoutingCIDR: 10.0.0.0/16
#      - autoDirectNodeRoutes: true
#      - tunnel: disabled
#      - loadBalancer:
#          mode: dsr
#      - endpointRoutes:
#          enabled: true
```

>  Does it work if you run in native routing mode without DSR?

You mean tunnel: disabled + autoDirectNodeRoutes: true? No, i hasn't tried that

>Are you able to trace the connections to 10.43.0.1:443 

Any preferred tool for that to do inside pod? Or just trace it from host? If i recall correctly, i hasn't saw any routes with ip's inside service-cidr on nodes with endpointRoutes.enabled: true)  
It's personal cluster so generally i can break it as much as needed.

**Comment by pchaigno** [comment]
> You mean tunnel: disabled + autoDirectNodeRoutes: true? No, i hasn't tried that

Yes, plus `ipv4NativeRoutingCIDR` probably. Ok, so we're not sure yet that it's DSR breaking things here.

> Any preferred tool for that to do inside pod? Or just trace it from host?

See https://docs.cilium.io/en/stable/operations/troubleshooting/#observing-flows-with-hubble.

**Comment by rlex** [comment]
Found following in log, might be related?
```
level=info msg="BPF host routing is currently not supported with devices without L2 addr. Falling back to legacy host routing (enable-host-legacy-routing=true)." subsys=daemon
```

**Comment by rlex** [comment]
Okay, checked with native-routing, autoDirectNodeRoutes and ipv4NativeRoutingCIDR.
There is more: it also breaks out-of-cluster connectivity to external services.
As well as DNS (well, it's located within service-cidr, so it's expected.

```
Healthcheck (via unix:///var/run/cilium/hubble.sock): Ok
Current/Max Flows: 4,095/4,095 (100.00%)
Flows/s: 64.99
```

restic to k8s api:
```
Dec 14 18:07:49.646: velero/restic-f2klt:34460 -> external_ip_of_my_node:6443 to-stack FORWARDED (TCP Flags: SYN)
Dec 14 18:07:56.775: velero/restic-f2klt:34460 -> external_ip_of_my_node:6443 to-stack FORWARDED (TCP Flags: SYN)
Dec 14 18:08:04.968: velero/restic-f2klt:34460 -> external_ip_of_my_node:6443 to-stack FORWARDED (TCP Flags: SYN)
```

Checked with another app which calls for external service before turning green:
```
Dec 14 18:13:35.600: authelia/authelia-0:36721 -> kube-system/coredns-coredns-7cf8d5c75f-zq8bd:53 to-stack FORWARDED (UDP)
Dec 14 18:13:35.600: 10.0.6.132 -> authelia/authelia-0 to-endpoint FORWARDED (ICMPv4 DestinationUnreachable(Host))
Dec 14 18:13:35.600: authelia/authelia-0:35327 -> kube-system/coredns-coredns-7cf8d5c75f-4spl8:53 to-stack FORWARDED (UDP)
Dec 14 18:13:40.603: authelia/authelia-0:46611 -> kube-system/coredns-coredns-7cf8d5c75f-4spl8:53 to-stack FORWARDED (UDP)
Dec 14 18:13:40.603: 10.0.6.132 -> authelia/authelia-0 to-endpoint FORWARDED (ICMPv4 DestinationUnreachable(Host))
Dec 14 18:13:41.563: authelia/authelia-0:35894 -> kube-system/coredns-coredns-7cf8d5c75f-zq8bd:53 to-stack FORWARDED (UDP)
Dec 14 18:13:41.563: authelia/authelia-0:46916 -> kube-system/coredns-coredns-7cf8d5c75f-4spl8:53 to-stack FORWARDED (UDP)
```

Routing table:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         provider_gw   0.0.0.0         UG    0      0        0 eth0
10.0.0.0        172.25.25.74    255.255.255.0   UG    0      0        0 wg0
10.0.1.0        10.0.1.200      255.255.255.0   UG    0      0        0 cilium_host
10.0.1.200      0.0.0.0         255.255.255.255 UH    0      0        0 cilium_host
10.0.2.0        172.25.25.71    255.255.255.0   UG    0      0        0 wg0
10.0.3.0        172.25.25.73    255.255.255.0   UG    0      0        0 wg0
10.0.4.0        172.25.25.62    255.255.255.0   UG    0      0        0 wg0
10.0.5.0        172.25.25.63    255.255.255.0   UG    0      0        0 wg0
10.0.6.0        172.25.25.72    255.255.255.0   UG    0      0        0 wg0
#this one is probably irrelevant - not used in k8s in any way.
172.24.25.0     0.0.0.0         255.255.255.0   U     0      0        0 tinc0
172.25.25.5     0.0.0.0         255.255.255.255 UH    0      0        0 wg0
172.25.25.11    0.0.0.0         255.255.255.255 UH    0      0        0 wg0
172.25.25.62    0.0.0.0         255.255.255.255 UH    0      0        0 wg0
172.25.25.63    0.0.0.0         255.255.255.255 UH    0      0        0 wg0
172.25.25.71    0.0.0.0         255.255.255.255 UH    0      0        0 wg0
172.25.25.72    0.0.0.0         255.255.255.255 UH    0      0        0 wg0
172.25.25.73    0.0.0.0         255.255.255.255 UH    0      0        0 wg0
172.25.25.74    0.0.0.0         255.255.255.255 UH    0      0        0 wg0
```

commenting out those 3 parameters and rebooting makes cluster all green again.

**Comment by rlex** [comment]
Some additional info: host-firewall is used with some rules (btw, very neat feature and very easy to configure to "lockdown" nodes and not expose too much ports, ways easier than other CNIs, thanks for that!):

```yaml
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "node-lockdown"
spec:
  description: "Lockdown of nodes"
  nodeSelector:
    matchLabels:
      node-access: restricted
  ingress:
  - fromEntities:
    - cluster
  - toPorts:
    - ports:
      # ssh
      - port: "22"
        protocol: TCP
      # kubeapi
      - port: "6443"
        protocol: TCP
      # wireguard
      - port: "51820"
        protocol: UDP
      # ingress-nginx
      - port: "80"
        protocol: TCP
      - port: "443"
        protocol: TCP
      # etcd
      - port: "2379"
        protocol: TCP
      - port: "2380"
        protocol: TCP
      - port: "2381"
        protocol: "TCP"
      # telegraf
      - port: "9273"
        protocol: "TCP"
```

Cilium is pointing to 
```yaml
      - k8sServiceHost: 127.0.0.1
      - k8sServicePort: 16443
```

Because i have haproxy running on every k3s node for load-balancing / ha to masters. On masters themselves, haproxy is only used for cilium.

There is also metallb in l2 mode installed managing floating external IP, but i'm not sure if it related in any way (probably not)

Wireguard is installed separately from cilium on host-node, it's not running in k8s.

cluster-cidr is different from cilium (10.42.0.0/16 in k3s vs 10.0.0.0/16 in cilium), but i assume if i use ipam in cluster-pool mode, cluster-cidr specified in k3s is simply unused.
