### ISSUE TITLE
EKS Nodes NotReady with node to node encryption enabled.

### ISSUE THREAD

**Issue by Ian-Greene** [cilium/cilium#18329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When setting `encryption.nodeEncryption` to true we noticed that all of our EKS nodes can join the cluster but are always NotReady. The cilium agents are unable to start and any attempts to contact the node fail. Here are our helm values.

```
  values:
  - eni:
      enabled: true
      iamRole: <iam role arn>
      subnetIDsFilter: <subnet ids>
      awsReleaseExcessIPs: true
    ipam:
      mode: eni
    tunnel: disabled
    egressMasqueradeInterfaces: eth0
    tls:
      enabled: true
      secretsBackend: k8s
    encryption:
      enabled: true
      nodeEncryption: true
      type: ipsec
      ipsec:
        keyFile: keys
        secretName: cilium-ipsec-keys
        mountPath: /etc/ipsec
```
        
Are we missing any configuration options we are missing that would allow us to enable node to node encryption on EKS?

### Cilium Version

1.11.0

### Kernel Version

Linux 5.4.156

### Kubernetes Version

1.21

### Sysdump

[cilium-sysdump-20211222-142036.zip](https://github.com/cilium/cilium/files/7764758/cilium-sysdump-20211222-142036.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
