### ISSUE TITLE
pod visit failed after networkpolicy has set

### ISSUE THREAD

**Issue by llhhbc** [cilium/cilium#18340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: department-isolation
  namespace: admin
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchExpressions:
        - key: name
          operator: In
          values:
          - admin
          - kube-system
    - podSelector:
        matchLabels:
          allowed-namespace: admin
  podSelector: {}
  policyTypes:
  - Ingress
 ```

When pods are frequently created and deleted, the rules that have been created will become invalid, and there will be a phenomenon of network inaccessibility between pods

### Cilium Version

```sh
Client: 1.10.4 2a46fd6 2021-09-01T12:58:41-07:00 go version go1.16.7 linux/amd64
Daemon: 1.10.4 2a46fd6 2021-09-01T12:58:41-07:00 go version go1.16.7 linux/amd64
```

### Kernel Version

```sh
Linux 10-10-40-25 4.19.113-300.el7.x86_64 #1 SMP Mon Mar 30 21:50:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T00:54:02Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
