### ISSUE TITLE
Helm chart does not generate ServiceMonitor resource for Hubble

### ISSUE THREAD

**Issue by inductor** [cilium/cilium#18375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have the following values.yaml as minimum configuration, but neither of `helm upgrade --install cilium cilium/cilium --namespace kube-system -f values.yaml` or ` helm template cilium/cilium -f values.yaml --api-versions=monitoring.coreos.com/v1` succeeds installation with `ServiceMonitor` for Hubble.

```yaml
hubble:
  enabled: true
  metrics:
    serviceMonitor:
      enabled: true
operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
```

This is the summarisedresult

```
$ helm template cilium/cilium -f cilium-values.yaml --api-versions=monitoring.coreos.com/v1 | grep "ServiceMonitor" |  wc -l
2
```

```yaml
# Source: cilium/templates/cilium-agent/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium-agent
  namespace: default
  labels:
spec:
  selector:
    matchLabels:
      k8s-app: cilium
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: metrics
    interval: 10s
    honorLabels: true
    path: /metrics
  targetLabels:
  - k8s-app
---
# Source: cilium/templates/cilium-operator/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium-operator
  namespace: default
  labels:
spec:
  selector:
    matchLabels:
      io.cilium/app: operator
      name: cilium-operator
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: metrics
    interval: 10s
    honorLabels: true
    path: /metrics
  targetLabels:
  - io.cilium/app
```

### Cilium Version

```
$ cilium version
cilium-cli: v0.10.0 compiled with go1.17.4 on linux/amd64
cilium image (default): v1.11.0
cilium image (stable): v1.11.0
cilium image (running): v1.11.0
```

### Kernel Version

Control plane

```
$ uname -a
Linux cp 5.4.0-1047-raspi #52-Ubuntu SMP PREEMPT Wed Nov 24 08:16:38 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

Worker

```
$ uname -a
Linux worker 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/arm64"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
