### ISSUE TITLE
HTTP outbound traffic forbidden with istio-proxy installed

### ISSUE THREAD

**Issue by yangyang198703** [cilium/cilium#18465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Installing Cilium 1.11.0 + Istio 1.10.4 (quay.io/cilium/istio_proxy:1.10.4) on Kubernetes cluster, and configured a `Sidecar` to expose a HTTP service on `127.0.0.1:8094` endpoint by following the practice from istio official documentation (https://istio.io/latest/docs/ops/deployment/requirements/#outbound-traffic)

The `Sidecar` definition is as below

```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: sdc-app-name
spec:
  egress:
  - bind: 127.0.0.1
    captureMode: NONE
    hosts:
    - ns/service.svc.cluster.local
    port:
      name: egress-c2
      number: 8094
      protocol: HTTP
  - hosts:
    - ns/service.svc.cluster.local
  workloadSelector:
    labels:
      app: name
```

The above setting worked perfect with calico + istio 1.10.4, we can use curl and Host HTTP header to access the HTTP service
```
curl -H "Host:service.svc.cluster.local" 127.0.0.1:8094/status
200 OK
```

However, switching to cilium + istio (cilium version), the access was defined
```
curl -H "Host:service.svc.cluster.local" 127.0.0.1:8094/status
HTTP/1.1 403 Forbidden
content-length: 15
content-type: text/plain
date: Wed, 12 Jan 2022 14:45:30 GMT
server: envoy
```

and saw some warning messages in istio-proxy container
```
2022-01-12T13:34:46.362382Z warning envoy config cilium.bpf_metadata (egress): No policy found for 127.0.0.1
2022-01-12T13:34:46.362567Z warning envoy filter Cilium L7: Cilium Socket Option not found
```

### Cilium Version

1.11.0

### Kernel Version

Linux ip-172-22-88-223.us-west-2.compute.internal 5.10.75-79.358.amzn2.x86_64 #1 SMP Thu Nov 4 21:08:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.20.2

### Relevant log output

```shell
2022-01-12T13:34:46.362382Z warning envoy config cilium.bpf_metadata (egress): No policy found for 127.0.0.1
2022-01-12T13:34:46.362567Z warning envoy filter Cilium L7: Cilium Socket Option not found
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
