### ISSUE TITLE
Single agent failure, restart of cilium agent fixes the issue

### ISSUE THREAD

**Issue by farodin91** [cilium/cilium#18485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. See it most at, if prometheus is unable to reach to it scrape endpoints. 
2. We restart the cilium agent either on the prometheus node or on the scrape endpoint node.
3. Everything works again.

### Cilium Version

1.11.0

### Kernel Version

5.4.0-92-generic

### Kubernetes Version

1.21.8

### Anything else?

Our config:
```yaml
  auto-direct-node-routes: 'false'
  bpf-lb-algorithm: maglev
  bpf-lb-external-clusterip: 'false'
  bpf-lb-map-max: '65536'
  bpf-map-dynamic-size-ratio: '0.0025'
  bpf-policy-map-max: '16384'
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-name: cluster-name
  custom-cni-conf: 'false'
  debug: 'false'
  disable-cnp-status-updates: 'true'
  disable-endpoint-crd: 'false'
  enable-auto-protect-node-port-range: 'true'
  enable-bandwidth-manager: 'false'
  enable-bpf-clock-probe: 'true'
  enable-endpoint-health-checking: 'true'
  enable-health-check-nodeport: 'true'
  enable-health-checking: 'true'
  enable-hubble: 'true'
  enable-ipv4: 'true'
  enable-ipv4-masquerade: 'true'
  enable-ipv6: 'false'
  enable-ipv6-masquerade: 'true'
  enable-k8s-terminating-endpoint: 'true'
  enable-l2-neigh-discovery: 'true'
  enable-l7-proxy: 'true'
  enable-local-redirect-policy: 'false'
  enable-metrics: 'true'
  enable-policy: default
  enable-remote-node-identity: 'true'
  enable-session-affinity: 'true'
  enable-well-known-identities: 'false'
  enable-xt-socket-fallback: 'true'
  hubble-disable-tls: 'false'
  hubble-listen-address: ':4244'
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  install-iptables-rules: 'true'
  install-no-conntrack-iptables-rules: 'false'
  ipam: kubernetes
  kube-proxy-replacement: probe
  kube-proxy-replacement-healthz-bind-address: ''
  labels: >-
    any:!beta.kubernetes.io any:!k8s.io any:!pod-template-generation
    any:!pod-template-hash any:!controller-revision-hash any:!annotation.*
    any:!etcd_node
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: 'true'
  operator-api-serve-addr: '127.0.0.1:9234'
  operator-prometheus-serve-addr: ':6942'
  preallocate-bpf-maps: 'false'
  prometheus-serve-addr: ':9090'
  proxy-prometheus-port: '9095'
  sidecar-istio-proxy-image: cilium/istio_proxy
  tunnel: vxlan
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
