### ISSUE TITLE
aoe: packet could not be sent on *. consider increasing tx_queue_len

### ISSUE THREAD

**Issue by anthr76** [cilium/cilium#18622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using Cilium with these values:
```yaml
USER-SUPPLIED VALUES:
autoDirectNodeRoutes: true
bgp:
  announce:
    loadbalancerIP: true
  enabled: true
cluster:
  id: 1
  name: scr1-cluster-0
containerRuntime:
  integration: containerd
endpointRoutes:
  enabled: true
hubble:
  enabled: true
  metrics:
    enabled:
    - dns:query;ignoreAAAA
    - drop
    - tcp
    - flow
    - port-distribution
    - icmp
    - http
  relay:
    enabled: true
    rollOutPods: true
  serviceMonitor:
    enabled: true
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 10.244.0.0/16
ipv6:
  enabled: true
k8sServiceHost: cluster-0.scr1.rabbito.tech
k8sServicePort: 6443
kubeProxyReplacement: strict
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
loadBalancer:
  algorithm: maglev
  mode: dsr
localRedirectPolicy: true
operator:
  rollOutPods: true
rollOutCiliumPods: true
tunnel: disabled
```

### Cilium Version

`1.11.1`

### Kernel Version

`5.15.16-talos`

### Kubernetes Version

`v1.23.2`

### Relevant log output

```shell
worker-05: kern: warning: [2022-01-25T19:28:24.213091719Z]: aoe: packet could not be sent on eth0.101.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:28:24.225984719Z]: aoe: packet could not be sent on eth0.806.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:28:24.234131719Z]: aoe: packet could not be sent on eth0.808.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:28:24.242302719Z]: aoe: packet could not be sent on lxc_health.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:28:24.250630719Z]: aoe: packet could not be sent on lxc20ff71bff324.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:28:24.259369719Z]: aoe: packet could not be sent on lxc509065416a63.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:28:24.268106719Z]: aoe: packet could not be sent on lxc4d4522d51015.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:28:24.276895719Z]: aoe: packet could not be sent on lxcec0318107c08.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:28:24.285641719Z]: aoe: packet could not be sent on lxc757851c95c88.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:28:24.294386719Z]: aoe: packet could not be sent on lxc02bbf9f0d58f.  consider increasing tx_queue_len
worker-07: kern: warning: [2022-01-25T19:28:54.478812607Z]: aoe: packet could not be sent on eth0.101.  consider increasing tx_queue_len
worker-07: kern: warning: [2022-01-25T19:28:54.486969607Z]: aoe: packet could not be sent on eth0.806.  consider increasing tx_queue_len
worker-07: kern: warning: [2022-01-25T19:28:54.495120607Z]: aoe: packet could not be sent on eth0.808.  consider increasing tx_queue_len
worker-07: kern: warning: [2022-01-25T19:28:54.503267607Z]: aoe: packet could not be sent on lxca03b16c4b974.  consider increasing tx_queue_len
worker-07: kern: warning: [2022-01-25T19:28:54.512027607Z]: aoe: packet could not be sent on lxcf9760c4cfdbb.  consider increasing tx_queue_len
worker-07: kern: warning: [2022-01-25T19:28:54.520790607Z]: aoe: packet could not be sent on lxc58904a73a07a.  consider increasing tx_queue_len
worker-07: kern: warning: [2022-01-25T19:28:54.529557607Z]: aoe: packet could not be sent on lxc_health.  consider increasing tx_queue_len
worker-07: kern: warning: [2022-01-25T19:28:54.537876607Z]: aoe: packet could not be sent on lxcc16ba4c2b272.  consider increasing tx_queue_len
worker-07: kern: warning: [2022-01-25T19:28:54.546621607Z]: aoe: packet could not be sent on lxcfad80acbbdaa.  consider increasing tx_queue_len
worker-04: kern: warning: [2022-01-25T19:29:23.276846213Z]: net_ratelimit: 13 callbacks suppressed
worker-04: kern: warning: [2022-01-25T19:29:23.276857213Z]: aoe: packet could not be sent on eth0.101.  consider increasing tx_queue_len
worker-04: kern: warning: [2022-01-25T19:29:23.289847213Z]: aoe: packet could not be sent on eth0.806.  consider increasing tx_queue_len
worker-04: kern: warning: [2022-01-25T19:29:23.298009213Z]: aoe: packet could not be sent on eth0.808.  consider increasing tx_queue_len
worker-04: kern: warning: [2022-01-25T19:29:23.306160213Z]: aoe: packet could not be sent on lxc_health.  consider increasing tx_queue_len
worker-04: kern: warning: [2022-01-25T19:29:23.314468213Z]: aoe: packet could not be sent on lxc654c6d4bf3f8.  consider increasing tx_queue_len
worker-04: kern: warning: [2022-01-25T19:29:23.323205213Z]: aoe: packet could not be sent on lxc5ad6646eaf2a.  consider increasing tx_queue_len
worker-04: kern: warning: [2022-01-25T19:29:23.331957213Z]: aoe: packet could not be sent on lxcdebc3d70c565.  consider increasing tx_queue_len
worker-04: kern: warning: [2022-01-25T19:29:23.340726213Z]: aoe: packet could not be sent on lxc5100779875eb.  consider increasing tx_queue_len
worker-04: kern: warning: [2022-01-25T19:29:23.349483213Z]: aoe: packet could not be sent on lxce7cd2bc0aba6.  consider increasing tx_queue_len
worker-04: kern: warning: [2022-01-25T19:29:23.358229213Z]: aoe: packet could not be sent on lxc5ead2ec60da9.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:29:25.654009719Z]: net_ratelimit: 7 callbacks suppressed
worker-05: kern: warning: [2022-01-25T19:29:25.654022719Z]: aoe: packet could not be sent on eth0.101.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:29:25.666928719Z]: aoe: packet could not be sent on eth0.806.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:29:25.675070719Z]: aoe: packet could not be sent on eth0.808.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:29:25.683216719Z]: aoe: packet could not be sent on lxc_health.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:29:25.691526719Z]: aoe: packet could not be sent on lxc20ff71bff324.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:29:25.700269719Z]: aoe: packet could not be sent on lxc509065416a63.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:29:25.709022719Z]: aoe: packet could not be sent on lxc4d4522d51015.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:29:25.717774719Z]: aoe: packet could not be sent on lxcec0318107c08.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:29:25.726534719Z]: aoe: packet could not be sent on lxc757851c95c88.  consider increasing tx_queue_len
worker-05: kern: warning: [2022-01-25T19:29:25.735284719Z]: aoe: packet could not be sent on lxc02bbf9f0d58f.  consider increasing tx_queue_len
```

Until an eventual lockup and trace from the kernel - https://gist.github.com/anthr76/b5fe646fcef703d330264836accc02e8

Note: this doesn't happen until a "big enough" workload is scheduled on a node. For example, if I were to drain it, it would go away.

### Anything else?

I've also filed a ticket to https://github.com/talos-systems/talos/issues/4863

Talos, the Cilium slack, and I are having a hard time figuring out who's at fault and why aoe (`ATA over Lan`) is being used in the first place. The cluster is backed by rook-ceph so this is most likely the culprit but ceph docs/rook mention it very little..

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
