### ISSUE TITLE
topology hints do not work as expected.

### ISSUE THREAD

**Issue by mauilion** [cilium/cilium#18710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have brought up a kind cluster with the following configuration and starting command: 

kind-config.yaml:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
featureGates:
  TopologyAwareHints: true
nodes:
- role: control-plane
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "topology.kubernetes.io/zone=zone-a"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "topology.kubernetes.io/zone=zone-a"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "topology.kubernetes.io/zone=zone-b"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "topology.kubernetes.io/zone=zone-b"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "topology.kubernetes.io/zone=zone-c"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "topology.kubernetes.io/zone=zone-c"
```
kind start command: 
```bash
$ kind create cluster --config kind.yaml --name=cilium --image=kindest/node:v1.23.3
```

This creates a kind cluster with 6 worker nodes 2 in each of zone-a zone-b and zone-c.

I then deploy cilium with this command: 
```bash
helm upgrade --install  cilium cilium/cilium --version 1.11.1 \
    --namespace kube-system \
    --set kubeProxyReplacement=strict \
    --set k8sServiceHost="cilium-control-plane"\
    --set k8sServicePort=6443 \
    --set loadBalancer.serviceTopology=true \
    --set ipam.mode="kubernetes"
```

This brings up a working configuration of 6 nodes running cilium 1.11.1 with topology hints enabled.

I then deploy a service and some pods with this script:
```bash 
function echopod () {
  ZONE=""
  case $1 in
    cilium-worker)
      ZONE=1
      ;;
    cilium-worker2)
      ZONE=1
      ;;
    cilium-worker3)
      ZONE=2
      ;;
    cilium-worker4)
      ZONE=2
      ;;
    cilium-worker5)
      ZONE=3
      ;;
    cilium-worker6)
      ZONE=3
      ;;
  esac
  kubectl run echo${2}-${1} \
     --image overridden  --labels app=echo,pod=echo${2}-${1},node=${1},zone=$ZONE  --overrides \
    '{
      "spec":{
        "hostname": "echo'${2}-${1}'",
	      "subdomain": "test",
        "nodeName": "'$1'",
        "containers":[{
          "name":"echo",
          "image":"inanimate/echo-server",
          "env":[{
            "name":"ZONE",
            "value":"'$ZONE'"
          }]
        }]
      }
    }'
}
for worker in $(kind get nodes --name=cilium | grep worker)
  do 
    for i in {1..2}
      do echopod $worker $i
    done
  done

kubectl create service clusterip echo --tcp 8080 
```
we can validate at this point that each cilium node shows the service in both 
cilium service list and cilium bpf lb list

example:
```bash
$ kubectl get svc echo
NAME   TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
echo   ClusterIP   10.96.153.38   <none>        8080/TCP   3h57m

$ kubectl exec -ti -n kube-system ds/cilium -- cilium service get 4
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)
10.96.153.38:8080 =>
		1 => 10.244.4.90:8080 (4)
		2 => 10.244.5.240:8080 (4)
		3 => 10.244.4.218:8080 (4)
		4 => 10.244.5.141:8080 (4)
		5 => 10.244.3.115:8080 (4)
		6 => 10.244.1.96:8080 (4)
		7 => 10.244.6.7:8080 (4)
		8 => 10.244.1.73:8080 (4)
		9 => 10.244.6.37:8080 (4)
		10 => 10.244.2.156:8080 (4)
		11 => 10.244.2.187:8080 (4)
		12 => 10.244.3.105:8080 (4)
$ kubectl exec -ti -n kube-system ds/cilium -- cilium bpf lb list 
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)
SERVICE ADDRESS     BACKEND ADDRESS
--snip--                  
10.96.153.38:8080   10.244.6.7:8080 (4)                       
                    0.0.0.0:0 (4) [ClusterIP, non-routable]   
                    10.244.1.96:8080 (4)                      
                    10.244.5.240:8080 (4)                     
                    10.244.2.156:8080 (4)                     
                    10.244.6.37:8080 (4)                      
                    10.244.4.218:8080 (4)                     
                    10.244.2.187:8080 (4)                     
                    10.244.3.105:8080 (4)                     
                    10.244.5.141:8080 (4)                     
                    10.244.3.115:8080 (4)                     
                    10.244.4.90:8080 (4)                      
                    10.244.1.73:8080 (4)   
```
I then annotate the service with 
```
$ kubectl annotate service echo service.kubernetes.io/topology-aware-hints=auto
```
and I can see that the service definition in the cilium bpf side of things is changed.

```
10.96.153.38:8080   0.0.0.0:0 (4) [ClusterIP, non-routable]   
                    10.244.5.240:8080 (4)                     
                    10.244.4.90:8080 (4)                      
                    10.244.4.218:8080 (4)                     
                    10.244.5.141:8080 (4) 
```

based on this I would expect that a client pod deployed into a zone will keep it's traffic to the endpoints deployed in the same zone.

What is see is something else. 
```bash
bash-5.1# while true ; do curl -sS 10.96.153.38:8080 | egrep '(HOSTNAME|ZONE)' ; sleep 1 ; done
  HOSTNAME=echo2-cilium-worker6
  ZONE=3
  HOSTNAME=echo2-cilium-worker4
  ZONE=2
  HOSTNAME=echo1-cilium-worker2
  ZONE=1
  HOSTNAME=echo1-cilium-worker
  ZONE=1
  HOSTNAME=echo1-cilium-worker4
  ZONE=2
  HOSTNAME=echo1-cilium-worker5
  ZONE=3
  HOSTNAME=echo1-cilium-worker
  ZONE=1
  HOSTNAME=echo2-cilium-worker2
  ZONE=1
  HOSTNAME=echo1-cilium-worker6
  ZONE=3
  HOSTNAME=echo1-cilium-worker3
  ZONE=2
```

The only explanation is that some bpf program is making a routing decision before the lb filtered endpoints are considered. 

Digging in a bit more if I instead deploy with the following config I do see things working somewhat as expected:

```bash
helm upgrade cilium cilium/cilium --version 1.11.1 \
    --namespace kube-system \
    --set kubeProxyReplacement=strict \
    --set k8sServiceHost="cilium-control-plane"\
    --set k8sServicePort=6443 \
    --set loadBalancer.serviceTopology=true \
    --set ipam.mode="kubernetes" \
    --set hostServices.enabled=false
```

This is an interesting change in behaviour because in both cases cilium config --all | grep -i reachable shows enabled. 

So not totally sure what else is affected by disabling hostServices but even with "--set hostServices.enabled=false" the config is enabled. 

### Cilium Version

cilium-cli: v0.10.2 compiled with go1.17.6 on linux/amd64
cilium image (default): v1.11.1
cilium image (stable): v1.11.1
cilium image (running): v1.11.1

### Kernel Version

Linux lynx 5.15.18-1-lts #1 SMP Sat, 29 Jan 2022 12:13:13 +0000 x86_64 GNU/Linux

### Kubernetes Version

$▶ kubectl version 
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"archive", BuildDate:"2022-01-27T18:26:18Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-26T08:02:07Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
