### ISSUE TITLE
Request response for call from NLB doesn't get allowed

### ISSUE THREAD

**Issue by mantoine96** [cilium/cilium#18733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello,

I’m running into trouble when trying to enforce the network policies on a service. This service accesses a service running in the same cluster via an AWS NLB.

```
$ k get svc -nservice-b
NAME               TYPE           CLUSTER-IP      EXTERNAL-IP                                                                     PORT(S)         AGE
service-b   LoadBalancer   10.100.105.58   ae70248432da94246b62b1510dd9780d-d657221345d6c071.elb.eu-west-1.amazonaws.com   443:30855/TCP   3d6h 
```

When I run  hubble observe I notice the requests are matched for outgoing traffic, but replies are identified as coming from another entity (which is actually the IP of a node + port of the service)
```
Feb  7 15:11:33.235: service/service-agent-5c7fb8b944-48mv2:41122 -> service-b.account.fqdn.com:443 to-stack FORWARDED (TCP Flags: SYN)
Feb  7 15:11:33.236: 172.31.159.194:30855 <> service/service-agent-5c7fb8b944-48mv2:41122 Policy denied DROPPED (TCP Flags: SYN, ACK) 
```

Therefore I can’t make this work without allowing world or at the very least cluster in ingress, over several ports.

Is there something obvious I’m missing?

### What was expected

I would expect to see the response linked to the original request and therefore allowed, since Cilium's firewalling is stateful. 

### Reproducing the issue

Here is a quick reproduction:

In an EKS cluster, deploy this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: default
spec:
  selector:
    matchLabels:
      app: service-b
  replicas: 2
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: service-b
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: service-b
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deployment
  namespace: default
  labels:
    app: service-a
spec:
  replicas: 2
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: ubuntu
        image: curlimages/curl:7.81.0
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: service-a
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      app: service-a
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s:k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: '*'
  - toFQDNs:
    - matchPattern: '*.elb.eu-west-1.amazonaws.com'
    toPorts:
    - ports:
      - port: "80"
  ingress:
    - {}
```

Then exec into one of the service-a pods and try accessing the service-b NLB using `curl -v https://$NLB_ENDPOINT`.

 At the same time open hubble and observe traffic from service-a. You will see similar output to the one I pasted above.

### Cilium Version

v1.10.3

### Kernel Version

Linux 5.4.172-90.336.amzn2.x86_64

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-eks-f17b81", GitCommit:"f17b810c9e5a82200d28b6210b458497ddfcf31b", GitTreeState:"clean", BuildDate:"2021-10-15T21:46:21Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

### Relevant log output

```shell
Feb  7 15:11:33.235: service/service-agent-5c7fb8b944-48mv2:41122 -> service-b.account.fqdn.com:443 to-stack FORWARDED (TCP Flags: SYN)
Feb  7 15:11:33.236: 172.31.159.194:30855 <> service/service-agent-5c7fb8b944-48mv2:41122 Policy denied DROPPED (TCP Flags: SYN, ACK)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
