### ISSUE TITLE
LoadBalancer Services return `no route` response

### ISSUE THREAD

**Issue by gpl** [cilium/cilium#18744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In 1.11.1, it looks like LoadBalancer services don't get correctly programmed into the maglev table, but only to our control plane nodes.  For our standard worker nodes, there doesn't seem to be an issue. 

We tested this by routing traffic to a single worker node, and then a single control plane node.  None of the control plane nodes forwarded traffic, but worker nodes did successfully.

For the following service, any traffic going to the externalIPs does not work.

```
apiVersion: v1
kind: Service
metadata:
  name: echo-server-6-lbtest
  namespace: echo-server
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: web
  selector:
    app: echo-server
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  externalIPs:
    - 2001:db8:100::200
    - 192.0.2.200
  ipFamilies:
    - IPv6
    - IPv4
  ipFamilyPolicy: RequireDualStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster

```

### Cilium Version

1.11.1

### Kernel Version

5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.23.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
