### ISSUE TITLE
Wrong identity for the ipBlock traffic which comes from the world 

### ISSUE THREAD

**Issue by mimek** [cilium/cilium#18749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello,
I have defined some network policies on EKS with Cilium which based on ipCidr blocks for ingress traffic:

```
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    creationTimestamp: "2021-11-24T12:21:49Z"
    generation: 3
    name: allow-loadbalancers
    namespace: orders
    resourceVersion: "25630988"
    uid: 547eb640-a29e-41c2-8393-3fefc8cddead
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
    - from:
      - ipBlock:
          cidr: 10.200.121.0/24
      - ipBlock:
          cidr: 10.200.120.0/24
      - ipBlock:
          cidr: 10.200.114.0/24
      - ipBlock:
          cidr: 10.200.117.0/24
      - ipBlock:
          cidr: 10.200.112.0/24
      - ipBlock:
          cidr: 10.200.111.0/24
      - ipBlock:
          cidr: 10.200.119.0/24
      - ipBlock:
          cidr: 10.200.113.0/24
      - ipBlock:
          cidr: 10.200.115.0/24
      - ipBlock:
          cidr: 10.200.116.0/24
      - ipBlock:
          cidr: 10.200.118.0/24
      - ipBlock:
          cidr: 10.200.110.0/24
    podSelector: {}
    policyTypes:
    - Ingress
```

Policy should allow for traffic incoming from that cidr's (these are subnets which exists within AWS VPC). Ranges are being recognized by cilium and particular identities are assigned to them:
```
16777235   cidr:10.200.121.0/24
           reserved:world
16777238   cidr:10.200.108.143/32
           reserved:world
16777239   cidr:10.200.120.0/24
           reserved:world
16777240   cidr:10.200.114.0/24
           reserved:world
16777241   cidr:10.200.117.0/24
           reserved:world
16777242   cidr:10.200.112.0/24
           reserved:world
16777243   cidr:10.200.111.0/24
           reserved:world
16777244   cidr:10.200.119.0/24
           reserved:world
16777245   cidr:10.200.113.0/24
           reserved:world
16777246   cidr:10.200.115.0/24
           reserved:world
16777247   cidr:10.200.116.0/24
           reserved:world
16777248   cidr:10.200.118.0/24
           reserved:world
16777249   cidr:10.200.110.0/24
           reserved:world
```
But when the traffic comes from that subnets into the cluster, all of it it's being dropped. I assume that's because for some reason cilium marks this traffic as source identity:
`2          reserved:world`

which is visible in Hubble:

![image](https://user-images.githubusercontent.com/6304986/153188195-ec9dbeab-6210-4d22-b8f9-a353e2a6b473.png) 

instead of more specific identities with higher number as I mentioned earlier (I tried also with exact IPs with /32 mask).. The outcome is that if I want to allow for ingress traffic to the cluster, I need to allow it for whole `2          reserved:world` entity. I was trying also to write CilimNetworkPolicies with such specific CIDRSets but it doesn't change the way how it works.

Do I missed something with the configuration, understanding or this is a real bug?

Kind regards,
mimek

### Cilium Version

cilium-cli: v0.10.0 compiled with go1.17.4 on darwin/amd64
cilium image (default): v1.11.0
cilium image (stable): v1.11.1
cilium image (running): **v1.10.6**

### Kernel Version

Linux ip-10-200-104-151.eu-central-1.compute.internal 5.4.149-73.259.amzn2.x86_64 #1 SMP Mon Sep 27 12:48:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.21.5-eks-bc4871b

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi @mimek , are you able to share the exact policy corresponding to the drop that you linked there? I imagine that it's similar to the one you shared above, but the IP `10.200.108.143` does not fall inside the policy that you shared above.

It could also help to send such traffic and then take a sysdump, so that we can understand more about the state of the system - eg Cilium bpf policymap contents, ipcache contents, etc. `hubble observe` output with the exact traffic that you expect to be allowed can also help to dig deeper on this issue.

Also, is there any chance that the linked IP addresses are corresponding to other EKS nodes? Or are they corresponding to non-k8s nodes it the VPC?

**Comment by mlosekWA** [comment]
Hi @joestringer,
thanks for follow-up, currently I have applied below networkpolicy:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  generation: 14
  name: allow-loadbalancers
  namespace: productinformation
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
  - from:
    - ipBlock:
        cidr: 10.200.116.0/24
    - ipBlock:
        cidr: 10.200.117.0/24
    - ipBlock:
        cidr: 10.200.118.0/24
    - ipBlock:
        cidr: 10.200.119.0/24
    - ipBlock:
        cidr: 10.200.120.0/24
    - ipBlock:
        cidr: 10.200.121.0/24
    - ipBlock:
        cidr: 10.200.104.0/24
    - ipBlock:
        cidr: 10.200.108.0/24
    - ipBlock:
        cidr: 10.0.2.0/24
    - ipBlock:
        cidr: 10.0.1.0/24
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ```

I'm attaching cilium sysdump created during making some requests on that traffic and hubble outputs.
[cilium-sysdump-20220215-135057.zip](https://github.com/cilium/cilium/files/8069326/cilium-sysdump-20220215-135057.zip)

[hubble.txt](https://github.com/cilium/cilium/files/8069334/hubble.txt) (Actually a json)

Most of these subnets are AWS Loadbalancers subnets. VPC CIDR is: 10.200.0.0/16
Cilium is deployed on EKS in overlay mode, these 10.0.2.0/24 and 10.0.1.0/24 are podCidrs ranges from nodes:

```
ipam:
      podCIDRs:
      - 10.0.2.0/24
```
