### ISSUE TITLE
`hubble-ui` `backend` container file permissions issue on loading client cert for `hubble-relay` 

### ISSUE THREAD

**Issue by andy-v-h** [cilium/cilium#18816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using mTLS between `hubble-relay` and `hubble-ui`, the backend pod cannot open the `client.crt` with mode `0400` set (or `256` in decimal).  This looks possibly related to https://github.com/cilium/cilium/issues/18732, but as that was closed with a workaround via `kubectl port-forward` I'd like to open an issue to address the file permissions in the pod. 

A workaround is to manually set the default mode to `0404`. I think this is because the projected volume is owned by `root` and we're running at uid `1001` per the security context

### Cilium Version

v1.11.0

### Kernel Version

5.10.96

### Kubernetes Version

v1.22.5

### Sysdump

n/a

### Relevant log output

```shell
➤ kubectl logs po/hubble-ui-856f65c48f-f9twl backend  
level=info msg="initialized with TLS enabled\n" subsys=config
level=error msg="failed to initialize hubble-ui backend: failed to load keypair: open /var/lib/hubble-ui/certs/client.crt: permission denied\n" subsys=ui-backend
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andy-v-h** [comment]
I've worked around this projected volumes issue on other charts by using an `init-container` to move the certs to a new directory and `chown` and `chmod` the files.

**Comment by andy-v-h** [comment]
After investigating the chart further, I found I can set the security context to run as root, and Hubble UI works as shipped. I'd still advocate for a change that allows to work as not root.

**Comment by stelucz** [comment]
Issue is still present in Cilium (1.15.4)

```
hubble:
  metrics:
    enabled:
    - dns:query;ignoreAAAA
    - drop
    - tcp
    - flow
    - icmp
    - http
  peerService:
    clusterDomain: <domain_name>
  relay:
    enabled: true
    prometheus:
      enabled: true
    tls:
      server:
        enabled: true
  ui:
    enabled: true
```

pod log:
```
hubble-ui-5656559996-msvpx backend time="2024-04-16T13:41:00Z" level=warning msg="using fallback value for env var" fallback=false var=GOPS_ENABLED
hubble-ui-5656559996-msvpx backend time="2024-04-16T13:41:00Z" level=error msg="failed to initialize application config" error="failed to load keypair: open /var/lib/hubble-ui/certs/client.crt: permission denied"
Stream closed EOF for kube-system/hubble-ui-5656559996-msvpx (backend)
```

Workaround by Andy works, but there's no way to specify mode in helm chart.

**Comment by jfroy** [comment]
If you're using flux, you can use `postRenderers` to fix the permissions:

```yaml
  postRenderers:
    - kustomize:
        patches:
          # hubble-ui backend container file permissions issue on loading client cert for hubble-relay
          # https://github.com/cilium/cilium/issues/18816
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: hubble-ui
            patch: |
              - op: replace
                path: /spec/template/spec/volumes/2/projected/defaultMode
                value: 0404
```
