### ISSUE TITLE
The label k8s:io.cilium.k8s.namespace.labels in fromEndpoints doesn't work

### ISSUE THREAD

**Issue by ysksuzuki** [cilium/cilium#18865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium drops packets from the source that is allowed with the label k8s:io.cilium.k8s.namespace.labels in fromEndpoints.

1. Create a cluster with kind and install Cilium 1.11.1

```
$ curl -LO https://raw.githubusercontent.com/cilium/cilium/1.11.1/Documentation/gettingstarted/kind-config.yaml
$ kind create cluster --config=kind-config.yaml

$ helm repo add cilium https://helm.cilium.io/
$ helm install cilium cilium/cilium --version 1.11.1 \
  --namespace kube-system
```

2. Apply the following manifest.

```
apiVersion: v1
kind: Namespace
metadata:
  name: server
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    team: test-team
  name: client
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: test-ingress
  namespace: server
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.cilium.k8s.namespace.labels.team: test-team
            #k8s:io.kubernetes.pod.namespace: client
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: server
spec:
  containers:
  - name: ubuntu
    image: quay.io/cybozu/ubuntu-debug:20.04
    command: ["/usr/local/bin/pause"]
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: client
spec:
  containers:
  - name: ubuntu
    image: quay.io/cybozu/ubuntu-debug:20.04
    command: ["/usr/local/bin/pause"]
```

3. Ping the server Pod from the client Pod.

```
$ kubectl  get po -o wide -A
NAMESPACE            NAME                                         READY   STATUS    RESTARTS   AGE   IP           NODE                 NOMINATED NODE   READINESS GATES
client               ubuntu                                       1/1     Running   0          21m   10.0.3.32    kind-worker3         <none>           <none>
server               ubuntu                                       1/1     Running   0          21m   10.0.2.81    kind-worker          <none>           <none>

$ kubectl -n client exec ubuntu -- ping -c 1 -W 3 10.0.2.81
PING 10.0.2.81 (10.0.2.81) 56(84) bytes of data.

--- 10.0.2.81 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

command terminated with exit code 1
```

### Cilium Version

```
Client: 1.11.1 76d34db 2022-01-18T15:52:51-08:00 go version go1.17.6 linux/amd64
Daemon: 1.11.1 76d34db 2022-01-18T15:52:51-08:00 go version go1.17.6 linux/amd64
```

### Kernel Version

```
$ uname -a
Linux host-vm 5.11.0-1023-gcp #25~20.04.1-Ubuntu SMP Mon Nov 15 15:54:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

### Anything else?

The label `k8s:io.kubernetes.pod.namespace: client` works.

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: test-ingress
  namespace: server
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: client
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
Hello @ysksuzuki thanks for opening the GitHub issue. CiliumNetworkPolicy is namespaced and therefore when there isn't a namespace defined in `fromEndpoints`, Cilium will automatically select the endpoints on the same namespace where the policy is deployed. In this case the `server` namespace. The user can overwrite this selection by manually setting the namespace in the form of `k8s:io.kubernetes.pod.namespace`. For your use case, the following policy will work:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: server
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    team: test-team
  name: client
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: test-ingress
  namespace: server
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.cilium.k8s.namespace.labels.team: test-team
            k8s:io.kubernetes.pod.namespace: client
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: server
spec:
  containers:
  - name: ubuntu
    image: quay.io/cybozu/ubuntu-debug:20.04
    command: ["/usr/local/bin/pause"]
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: client
spec:
  containers:
  - name: ubuntu
    image: quay.io/cybozu/ubuntu-debug:20.04
    command: ["/usr/local/bin/pause"]
```

One other suggestion would be to use `CiliumClusterwideNetworkPolicies` which are non-namespaced.

**Comment by ysksuzuki** [comment]
Thank you so much for explaining in detail!

> CiliumNetworkPolicy is namespaced and therefore when there isn't a namespace defined in fromEndpoints, Cilium will automatically select the endpoints on the same namespace where the policy is deployed.

I didn't understand this.

In our case CiliumClusterwideNetworkPolicy would be better because we can avoid specifying all namespaces that belong same team. 

```
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "allow-from-test-team"
spec:
  endpointSelector:
    matchLabels:
      k8s:io.kubernetes.pod.namespace: server
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.cilium.k8s.namespace.labels.team: test-team
```
