### ISSUE TITLE
Cilium kube-proxy free doesn't run with konnectivity service

### ISSUE THREAD

**Issue by batistein** [cilium/cilium#18871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When trying to run cilium in kube-proxy free mode together with the konnectivity-server and konnectivity-agents see: https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/

I'm getting the following error on the cilium operator:
`level=error msg="Unable to contact k8s api-server" error="Get \"https://<my-domain>:443/api/v1/namespaces/kube-system\": dial tcp <my-ip>:443: connect: connection refused" ipAddr="https://<my-domain>:443" subsys=k8s`

On the cilium agent I'm getting the same error message.

These are my settings:
```
k8sServiceHost: <my-domain>
k8sServicePort: 443
kubeProxyReplacement: "strict"
ipam:
    mode: "kubernetes"
hostServices:
  hostNamespaceOnly: true
```

I tested the kube-proxy free setup **without the konnectivity server** and everything was working. 
I also tested cilium **with kube-proxy** and replacement=partial and with the konnectivity server and it works.

### Cilium Version

v1.11.1

### Kernel Version

5.16.5-200.fc35.x86_64

### Kubernetes Version

v1.23.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brb** [comment]
@batistein Thanks for the issue. It looks that you are hitting the same issue as Istio / Linkerd. Can you try with `hostServices.hostNamespaceOnly: true` introduced in https://github.com/cilium/cilium/pull/17154?

**Comment by batistein** [comment]
@brb good catch! Sorry this should be true, as I had also the same idea that it could be the same issue as Istio have... I have updated my issue now. 
Anyway setting this to true or to false (i tried both) doesn't resolve the issue.
Maybe you have another idea?
According to my understanding it could also be a chicken egg problem, because cilium probably wants to connect to the kube-apiserver via the konnectivity-agent and konnectivity-server which is on a different node, but at the same time a pod network is needed.

**Comment by brb** [comment]
> According to my understanding it could also be a chicken egg problem, because cilium probably wants to connect to the kube-apiserver via the konnectivity-agent and konnectivity-server which is on a different node, but at the same time a pod network is needed.

Could you run konnectivity-agent in host netns? This would eliminate the chicken-egg problem.

**Comment by batistein** [comment]
You mean running it without cilium directly via the host network?

I tried it with the following deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konnectivity-agent
  namespace: kube-system
  labels:
    helm.sh/chart: konnectivity-agent-1.0.3
    app.kubernetes.io/name: konnectivity-agent
    app.kubernetes.io/instance: konnectivity-agent
    k8s-app: konnectivity-agent
    app.kubernetes.io/version: "v0.0.27"
    app.kubernetes.io/managed-by: Helm
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: konnectivity-agent
      app.kubernetes.io/instance: konnectivity-agent
      k8s-app: konnectivity-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: konnectivity-agent
        app.kubernetes.io/instance: konnectivity-agent
        k8s-app: konnectivity-agent
    spec:
      hostNetwork: true
      priorityClassName: system-cluster-critical
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
        - key: "node.cloudprovider.kubernetes.io/uninitialized"
          value: "true"
          effect: "NoSchedule"
      serviceAccountName: konnectivity-agent
      securityContext:
        {}
      containers:
        - name: konnectivity-agent
          securityContext:
            {}
          image: "us.gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent:v0.0.27"
          imagePullPolicy: Always
          command: ["/proxy-agent"]
          args: [
                  "--logtostderr=true",
                  "--ca-cert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt",
                  # Since the konnectivity server runs with hostNetwork=true,
                  # this is the IP address of the master machine.
                  "--proxy-server-host=<my-domain>",
                  "--proxy-server-port=8132",
                  "--admin-server-port=8133",
                  "--health-server-port=8134",
                  "--service-account-token-path=/var/run/secrets/tokens/konnectivity-agent-token"
                  ]
          volumeMounts:
            - mountPath: /var/run/secrets/tokens
              name: konnectivity-agent-token
          livenessProbe:
            httpGet:
              port: 8134
              path: /healthz
            initialDelaySeconds: 15
            timeoutSeconds: 15
          resources:
            {}
      volumes:
        - name: konnectivity-agent-token
          projected:
            sources:
              - serviceAccountToken:
                  path: konnectivity-agent-token
                  audience: system:konnectivity-server
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - konnectivity-agent
            topologyKey: kubernetes.io/hostname
```

The result is still the same. The difference is now that i'm getting some logs from the konnectivity-agent like this:

```
I0222 10:35:25.189608       1 client.go:534] "write to remote" connectionID=2 lastData=259 dataSize=259
I0222 10:35:35.189497       1 client.go:445] "received DATA" connectionID=2
I0222 10:35:35.189596       1 client.go:534] "write to remote" connectionID=2 lastData=259 dataSize=259
I0222 10:35:45.187548       1 client.go:445] "received DATA" connectionID=2
I0222 10:35:45.187654       1 client.go:534] "write to remote" connectionID=2 lastData=259 dataSize=259
```
The cilium operator is still restarting but now without the error message.

```
level=info msg="  --limit-ipam-api-burst='4'" subsys=cilium-operator-generic
level=info msg="  --limit-ipam-api-qps='20'" subsys=cilium-operator-generic
level=info msg="  --log-driver=''" subsys=cilium-operator-generic
level=info msg="  --log-opt='map[]'" subsys=cilium-operator-generic
level=info msg="  --nodes-gc-interval='2m0s'" subsys=cilium-operator-generic
level=info msg="  --operator-api-serve-addr='127.0.0.1:9234'" subsys=cilium-operator-generic
level=info msg="  --operator-prometheus-serve-addr=':6942'" subsys=cilium-operator-generic
level=info msg="  --parallel-alloc-workers='50'" subsys=cilium-operator-generic
level=info msg="  --pprof='false'" subsys=cilium-operator-generic
level=info msg="  --pprof-port='6061'" subsys=cilium-operator-generic
level=info msg="  --skip-crd-creation='false'" subsys=cilium-operator-generic
level=info msg="  --subnet-ids-filter=''" subsys=cilium-operator-generic
level=info msg="  --subnet-tags-filter=''" subsys=cilium-operator-generic
level=info msg="  --synchronize-k8s-nodes='true'" subsys=cilium-operator-generic
level=info msg="  --synchronize-k8s-services='true'" subsys=cilium-operator-generic
level=info msg="  --unmanaged-pod-watcher-interval='15'" subsys=cilium-operator-generic
level=info msg="  --version='false'" subsys=cilium-operator-generic
level=info msg="Cilium Operator 1.11.1 76d34db 2022-01-18T15:52:51-08:00 go version go1.17.6 linux/amd64" subsys=cilium-operator-generic
level=info msg="Starting apiserver on address 127.0.0.1:9234" subsys=cilium-operator-api
level=info msg="Establishing connection to apiserver" host="https://<my-domain>:443" subsys=k8s

```

And the cilium pod is also restarting without the error message:

```
level=info msg="linking environment: OK!" subsys=linux-datapath
level=info msg="Detected mounted BPF filesystem at /sys/fs/bpf" subsys=bpf
level=info msg="Mounted cgroupv2 filesystem at /run/cilium/cgroupv2" subsys=cgroups
level=info msg="Parsing base label prefixes from default label list" subsys=labels-filter
level=info msg="Parsing additional label prefixes from user inputs: []" subsys=labels-filter
level=info msg="Final label prefixes to be used for identity evaluation:" subsys=labels-filter
level=info msg=" - reserved:.*" subsys=labels-filter
level=info msg=" - :io.kubernetes.pod.namespace" subsys=labels-filter
level=info msg=" - :io.cilium.k8s.namespace.labels" subsys=labels-filter
level=info msg=" - :app.kubernetes.io" subsys=labels-filter
level=info msg=" - !:io.kubernetes" subsys=labels-filter
level=info msg=" - !:kubernetes.io" subsys=labels-filter
level=info msg=" - !:.*beta.kubernetes.io" subsys=labels-filter
level=info msg=" - !:k8s.io" subsys=labels-filter
level=info msg=" - !:pod-template-generation" subsys=labels-filter
level=info msg=" - !:pod-template-hash" subsys=labels-filter
level=info msg=" - !:controller-revision-hash" subsys=labels-filter
level=info msg=" - !:annotation.*" subsys=labels-filter
level=info msg=" - !:etcd_node" subsys=labels-filter
level=info msg="Using autogenerated IPv4 allocation range" subsys=node v4Prefix=10.218.0.0/16
level=info msg="Initializing daemon" subsys=daemon
level=info msg="Establishing connection to apiserver" host="https://<my-domain>:443" subsys=k8s

```
