### ISSUE TITLE
CiliumClusterwideNetworkPolicy does not apply to cilium Daemonset

### ISSUE THREAD

**Issue by foosinn** [cilium/cilium#18938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium 1.11 is running on GKE with the old dataplane. 

The cluster is running the following firewall rules:

```yaml
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default
  namespace: kube-system
spec:
  endpointSelector: {}
  ingress:

    # allow traffic from master servers
    - fromCIDRSet:
        - cidr: 192.168.50.0/28  # TODO

    # dns access
    - fromEntities:
        - cluster
        - remote-node
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP

    # remote nodes to clilium
    - fromEntities:
        - remote-node
      toPorts:
        - ports:
            - port: "4240"

  egress:

    # allow traffic to master servers
    - toCIDRSet:
        - cidr: 192.168.50.0/28  # TODO

    # allow dns traffic
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: default
spec:
  endpointSelector: {}
  ingress:

    # allow local namespace
    - fromEndpoints:
        - {}

    # allow fron loadbalancer
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: projectcontour

  egress:

    # allow to local namespace
    - toEndpoints:
        - {}

    # allow to any pod in cluster
    - toEntities:
        - cluster
```

On running `hubble observe --verdict DROPPED -f` i noticed that cilium related traffic is being dropped:

```
Feb 25 09:53:36.695: 10.50.5.223:55948 <> 10.60.0.199:4240 Policy denied DROPPED (TCP Flags: SYN)
Feb 25 09:53:36.695: 10.50.5.223:55948 <> 10.60.0.199:4240 Policy denied DROPPED (TCP Flags: SYN)
Feb 25 09:53:36.715: 10.50.5.224:52928 <> 10.60.0.199:4240 Policy denied DROPPED (TCP Flags: SYN)
Feb 25 09:53:36.715: 10.50.5.224:52928 <> 10.60.0.199:4240 Policy denied DROPPED (TCP Flags: SYN)
Feb 25 09:53:37.610: 10.50.5.222:47956 <> 10.60.1.60:4240 Policy denied DROPPED (TCP Flags: SYN)
Feb 25 09:53:37.610: 10.50.5.222:47956 <> 10.60.1.60:4240 Policy denied DROPPED (TCP Flags: SYN)
```

Moving the `remote nodes to clilium` ingress rule from the `CiliumNetworkPolicy` in kube-system to the `CiliumClusterWideNetworkPolicy` fixes this.

Did I understand something wrong? I got the impression that it's possible to combine `CiliumClusterwideNetworkPolicy` with normal policies.

### Cilium Version

```
cilium-cli:  compiled with go1.16.13 on linux/amd64
cilium image (default): v1.10.5
cilium image (stable): v1.11.2
cilium image (running): v1.11.0
```

### Kernel Version

```
Linux container 5.4.144+ #1 SMP Wed Nov 3 09:56:10 PDT 2021 x86_64 Linux
```

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.16.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6-gke.1500", GitCommit:"7ce0f9f1939dfc1aee910732e84cba03840df91e", GitTreeState:"clean", BuildDate:"2021-11-17T09:30:26Z", GoVersion:"go1.16.9b7", Compiler:"gc", Platform:"linux/amd64"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
