### ISSUE TITLE
Packets to host dropped with chaining mode and host firewall

### ISSUE THREAD

**Issue by ysksuzuki** [cilium/cilium#18942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium drops packets destined to host when hostFirewall is enabled here
https://github.com/cilium/cilium/blob/b8506a1dcc8ccc1eb07117953a46f7c6181742e3/bpf/bpf_lxc.c#L788
https://github.com/cilium/cilium/blob/b8506a1dcc8ccc1eb07117953a46f7c6181742e3/bpf/bpf_lxc.c#L1745

```
$ kubectl -n kube-system exec cilium-n9vcc -- cilium monitor --type drop
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)
Listening for events on 12 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
xx drop (Missed tail call) flow 0x7bda48fd to endpoint 0, , identity 19387->host: 172.19.0.1:53 -> 10.69.1.133:58314 tcp SYN, ACK
xx drop (Missed tail call) flow 0x36a2383e to endpoint 0, , identity 19387->host: 172.19.0.1:53 -> 10.69.1.133:58536 tcp SYN, ACK
xx drop (Missed tail call) flow 0x0 to endpoint 0, , identity 19387->host: 172.19.0.1:3128 -> 10.69.1.133:43088 tcp ACK, RST
xx drop (Missed tail call) flow 0x1356d934 to endpoint 0, , identity 19387->host: 172.19.0.1:53 -> 10.69.1.133:58516 tcp SYN, ACK
xx drop (Missed tail call) flow 0x6f751770 to endpoint 0, , identity 19387->host: 172.19.0.1:53 -> 10.69.1.133:58440 tcp SYN, ACK
xx drop (Missed tail call) flow 0x51ffc6cc to endpoint 0, , identity 19387->host: 172.19.0.1:53 -> 10.69.1.133:58482 tcp SYN, ACK
xx drop (Missed tail call) flow 0xd56deee0 to endpoint 0, , identity 19387->host: 172.19.0.1:53 -> 10.69.1.133:58324 tcp SYN, ACK
xx drop (Missed tail call) flow 0xecfdc48d to endpoint 0, , identity 19387->host: 172.19.0.1:53 -> 10.69.1.133:58326 tcp SYN, ACK
xx drop (Missed tail call) flow 0x7f2930f to endpoint 0, , identity 19387->host: 172.19.0.1:53 -> 10.69.1.133:58550 tcp SYN, ACK

$ kubectl -n kube-system exec cilium-n9vcc -- bpftool map dump pinned /sys/fs/bpf/tc/globals/cilium_call_policy
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)
key: 26 03 00 00  value: c0 0f 00 00
key: ec 03 00 00  value: c4 0f 00 00
key: bd 0a 00 00  value: 4a 11 00 00
key: 0e 0c 00 00  value: 4c 11 00 00
Found 4 elements
```

helm values
```
devices: "eth+ eno1+ eno2+"
cni:
  chainingMode: "generic-veth"
  customConf: true
datapathMode: "veth"
tunnel: "disabled"
enableIPv4Masquerade: false
enableIdentityMark: false
hostFirewall:
  enabled: true
policyEnforcementMode: "default"
policyAuditMode: true
kubeProxyReplacement: "disabled"
prometheus:
  enabled: true
rollOutCiliumPods: true
resources:
  requests:
    cpu: 100m
    memory: 400Mi
operator:
  rollOutPods: true
  prometheus:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
hubble:
  relay:
    enabled: true
    tls:
      server:
        enabled: true
    rollOutPods: true
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
  tls:
    auto:
      method: "cronJob"
  metrics:
    enabled:
      - "dns"
      - "drop:destinationContext=pod|dns|ip;sourceContext=pod|dns|ip"
      - "tcp"
      - "flow:destinationContext=pod|dns|ip;sourceContext=pod|dns|ip"
      - "icmp"
      - "http"
```

### Cilium Version

```
$ kubectl -n kube-system exec cilium-n9vcc -- cilium version
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)
Client: 1.11.0 27e0848cc5 2021-12-05T15:34:41-08:00 go version go1.17.3 linux/amd64
Daemon: 1.11.0 27e0848cc5 2021-12-05T15:34:41-08:00 go version go1.17.3 linux/amd64
```

### Kernel Version

```
$ uname -a
Linux rack2-cs5 5.10.96-flatcar #1 SMP Thu Feb 3 20:00:07 -00 2022 x86_64 AMD EPYC 7413 24-Core Processor AuthenticAMD GNU/Linux
```

### Kubernetes Version

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"archive", BuildDate:"2021-12-20T06:57:14Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
