### ISSUE TITLE
Packets going through EgressGateway may left unchanged when port range in nat map near to run out for specific remote endpoint

### ISSUE THREAD

**Issue by aleksey-novikov** [cilium/cilium#18956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If multiple connections, not necessarily simultaneous, to the same host go through the egress gateway, NAT map continuos filled up and some outgoing packets are not SNATed. Such behavior is found on TCP SYN packets. In some cases after SYN packet left unchanged following outgoung packets already SNATed.

### Cilium Version

Same results on 1.10.7 and 1.11.2

### Kernel Version

CentOS 8 - 4.18.0-348.el8.x86_64

### Kubernetes Version

1.20.5

### Sysdump

[cilium-sysdump-20220227-210512.zip](https://github.com/cilium/cilium/files/8149180/cilium-sysdump-20220227-210512.zip)
Some information is absent because cilium installed in the non-standard namespace and cilium sysdump command has not namespace option.

### Anything else?

Traffic captured on EgressGateway Node (on remote host allow connections from EG only)
![image](https://user-images.githubusercontent.com/16462224/155895453-bcf04630-9b8a-4e50-b442-c160f4002248.png)

NAT entries count:
```
kubectl -n system-network exec cilium-wzmvc -- cilium bpf nat list | fgrep '10.76.151.142:80' | fgrep 'TCP IN' | wc -l
32767
```

Sample deployment:
```
apiVersion: apps/v1
kind: Deployment
  name: eg-test
spec:
  selector:
    matchLabels:
      app: eg-test
  template:
    metadata:
      labels:
        app: eg-test
    spec:
      containers:
      - env:
        - name: URL
          value: http://<some-URL>
        image: <private-registry>/eg-test:latest
        name: eg-test
```
Sample script (log date to detect connection drops):
```
#!/bin/sh
while true; do curl -s -I --connect-timeout 1 "$URL" >/dev/null || date; sleep 0.01; done
```
Dockerfile:
```
FROM alpine:latest
RUN apk add curl
COPY src/script.sh /
CMD ["/script.sh"]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
