### ISSUE TITLE
Advertise PodCIDR doesn't work on Ipv6

### ISSUE THREAD

**Issue by arianvp** [cilium/cilium#18989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When enabling bgp podCIDR announcement it doesn't work when on ipv6

```
level=error msg="Failed to announce pod CIDRs" CIDRs="&[2001:19f0:6c01:12c:1::/80]" cidrs="&[2001:19f0:6c01:12c:1::/80]" component=MetalLBSpeaker.handleNodeEvent error="cannot advertise non-v4 prefix \"2001:19f0:6c01:12c:1::/80\"" labels="&map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:worker-0 kubernetes.io/os:linux]" subsys=bgp-speaker
```

### Cilium Version

1.11.2

### Kernel Version

5.10.84

### Kubernetes Version

1.23.4

### Relevant log output

```shell
level=error msg="Failed to announce pod CIDRs" CIDRs="&[2001:19f0:6c01:12c:1::/80]" cidrs="&[2001:19f0:6c01:12c:1::/80]" component=MetalLBSpeaker.handleNodeEvent error="cannot advertise non-v4 prefix \"2001:19f0:6c01:12c:1::/80\"" labels="&map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:worker-0 kubernetes.io/os:linux]" subsys=bgp-speaker
```

### Anything else?

BGP Config:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
      - peer-address: "2001:19f0:ffff::1"
        peer-asn: 64515
        my-asn: 4288000094
        password: XXXXXXXX
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          - "2001:19f0:6c01:1323::/64"
```

Helm values:
```yaml
bgp:
  enabled: true
  announce:
    loadbalancerIP: true
    podCIDR: true

k8sServiceHost: "2001:19f0:6c01:050c:5400:03ff:fee2:77f3"
k8sServicePort: 6443

# We're announcing pod CIDRs so no need for tunnel
tunnel: disabled
ipv4:
  enabled: false
ipv6:
  enabled: true
ipam:
  mode: kubernetes

enableIPv6Masquerade: false
enableIPv4Masquerade: false

# installIptablesRules: false
# installNoConntrackIptablesRules: true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
