### ISSUE TITLE
Cilium keeps creating temporary network interfaces when it can't allocate more IPs

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#19004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

i installed cilium on eks with eni mode. when cilium cannot allocate more IPs, pods fails to start (which is expected):
```
  Warning  FailedCreatePodSandBox  9m57s                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "b217c5d39aa90120cc5c7d814dc3747b95ecbe597fc7ae38833e1d4481bc8e61" network for pod "nginx-deployment-66b6c48dd5-d6lbr": networkPlugin cni failed to set up pod "nginx-deployment-66b6c48dd5-d6lbr_default" network: unable to allocate IP via local cilium agent: [POST /ipam][502] postIpamFailure  No more IPs available
```
when cilium fails to initialize the pods, kubernetes keeps calling cilium-cni, and each call creates a new temporary interface.
```
% dmesg -wT
[Wed Mar  2 04:24:10 2022] eth0: renamed from tmp2c88e
[Wed Mar  2 04:24:11 2022] eth0: renamed from tmpeea9f
[Wed Mar  2 04:24:13 2022] eth0: renamed from tmp57161
[Wed Mar  2 04:24:14 2022] eth0: renamed from tmp0201c
...
```
at some point some pods get rescheduled to some other nodes, and cilium succeeds to allocate a new IP. then cilium crashes because the interface index is now too high:
```
level=fatal msg="ens6 link ifindex 317689 exceeds max(uint16)" subsys=daemon 
```
assuming an interface gets created every second, it takes 65535 seconds (about 18 hours) to hit the limit. restarting the node fixes the issue.

### Cilium Version

```
% cilium version
cilium-cli: v0.10.4 compiled with go1.17.7 on linux/amd64
cilium image (default): v1.11.2
cilium image (stable): v1.11.2
cilium image (running): v1.11.2
```

### Kernel Version

`5.4.176-91.338.amzn2.x86_64`

### Kubernetes Version

```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

i'll share it privately if necessary.

### Anything else?

i opened a draft PR: https://github.com/cilium/cilium/pull/18975 the idea here is to try calling `c.IPAMAllocate()` before creating an interface so that we don't keep creating temporary interfaces when `c.IPAMAllocate()` fails.

steps to repro:
```
% export NAME="$(whoami)-$RANDOM"

% cat <<EOF >eks-config.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${NAME}
  region: eu-west-1

managedNodeGroups:
- name: ng-1
  desiredCapacity: 2
  privateNetworking: true
  # taint nodes so that application pods are
  # not scheduled until Cilium is deployed.
  taints:
   - key: "node.cilium.io/agent-not-ready"
     value: "true"
     effect: "NoSchedule"
EOF

% eksctl create cluster -f ./eks-config.yaml

% cilium install

% cilium version
cilium-cli: v0.10.4 compiled with go1.17.7 on linux/amd64
cilium image (default): v1.11.2
cilium image (stable): v1.11.2
cilium image (running): v1.11.2

% cat deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 50
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

% kubectl apply -f ./deployment.yaml
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
