### ISSUE TITLE
Cluster mesh: Selecting a metallb address pool possible?

### ISSUE THREAD

**Issue by seimic** [cilium/cilium#19035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This is not a bug, just a question. Is it possible to specify the address pool from metallb instead of using the default one?

For example. metallb has two address pools. The default and an external one.
```yaml
configInline:
  address-pools:
   - name: default
     protocol: layer2
     addresses:
     - <INTERNAL-IPs>
   - name: external
     protocol: layer2
     addresses:
     - <EXTERNAL-IPs>
```

When enabling clustermesh it gets an IP address from the 'default'-pool. I could make external pool the default, but I would like to avoid this.

```cilium clustermesh enable --service-type LoadBalancer ...```

Thanks,
Michael

### Cilium Version

v1.11.2

### Kernel Version

5.4.0-100-generic (Ubuntu 20.04.4 LTS)

### Kubernetes Version

v1.23.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
