### ISSUE TITLE
Cilium DNS-based egress rules (toFQDN) not working reliably

### ISSUE THREAD

**Issue by ScheererJ** [cilium/cilium#19045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In kubernetes clusters managed by [gardener](https://gardener.cloud) with cilium configured, pods are not reliable able to resolve the DNS names according to their [DNS-based L3 rules](https://docs.cilium.io/en/v1.9/policy/language/#dns-based) (`toFQDN`). The resolution only works if the pod is on the same node as one of the `kube-dns` replicas.

**Background**:
Gardener sets up `kube-dns` with a network policy like the following.
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows CoreDNS to lookup DNS records, talk to the API Server. Also allows
      CoreDNS to be reachable via its service and its metrics endpoint.
    resources.gardener.cloud/description: |-
      DO NOT EDIT - This resource is managed by gardener-resource-manager.
      Any modifications are discarded and the resource is returned to the original state.
  labels:
    shoot.gardener.cloud/no-cleanup: "true"
  name: gardener.cloud--allow-dns
  namespace: kube-system
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector: {}
    - ipBlock:
        cidr: <node-network-cidr>
    - ipBlock:
        cidr: <pod-network-cidr>
    ports:
    - port: 9153
      protocol: TCP
    - port: 8053
      protocol: TCP
    - port: 8053
      protocol: UDP
  podSelector:
    matchExpressions:
    - key: k8s-app
      operator: In
      values:
      - kube-dns
      - coredns
  policyTypes:
  - Egress
  - Ingress
```

**How to reproduce (as minimally as possible)**
1. Create a cluster with two nodes
2. Have `kube-dns` running all replicas only on the first node, e.g. by cordoning the second node and scaling the `kube-dns` deployment accordingly
3. The following variables are used in subsequent commands
```
NODE1=$(kubectl get nodes -o jsonpath='{.items[0].metadata.name}')
NODE2=$(kubectl get nodes -o jsonpath='{.items[1].metadata.name}')
```
4. Ensure that `kube-dns` runs on a single
```
echo "$NODE1"; kubectl -n kube-system get pods -o wide | grep coredns
```
```
ip-10-250-14-108.eu-central-1.compute.internal
coredns-6c4f754f4b-6nmwp            1/1     Running   0          11m   100.96.1.91     ip-10-250-14-108.eu-central-1.compute.internal   <none>           <none>
coredns-6c4f754f4b-h2fmm            1/1     Running   0          11m   100.96.1.173    ip-10-250-14-108.eu-central-1.compute.internal   <none>           <none>
```
5. Create a test namespace including a `CiliumNetworkPolicy` using [DNS-based L3 rules](https://docs.cilium.io/en/v1.9/policy/language/#dns-based) (`toFQDN`)
```
kubectl create -f - <<EOF
---
apiVersion: v1
kind: Namespace
metadata:
  name: testcase
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: dns-based-l3-rules
  namespace: testcase
spec:
  endpointSelector:
    matchLabels:
      affected-by-dns-based-l3-rules: "true"
  egress:
  - toFQDNs:
    - matchPattern: "*"
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        "k8s:k8s-app": kube-dns
    toPorts:
    - ports:
      - port: "8053"
        protocol: ANY
      - port: "53"
        protocol: ANY
      rules:
        # enable DNS proxy to enable toFQDN egress rules
        dns:
        - matchPattern: "*"
EOF
```
6. Open a remote shell in a pod on the _second_ node that is affected by CiliumNetworkPolicy `dns-based-l3-rules`
```
kubectl run -n testcase \
  --labels="affected-by-dns-based-l3-rules=true" \
  --overrides='{"spec":{"nodeName":"'"$NODE2"'"}}' \
  --image arunvelsriram/utils \
  -it --rm \
  restricted--node2 \
  -- bash
```
7. Within that remote shell, try to resolve a DNS name both via UPD and TCP
```
root@restricted--node2:/# dig heise.de +notcp

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> heise.de +notcp
;; global options: +cmd
;; connection timed out; no servers could be reached
```
```
root@restricted--node2:/# dig heise.de +tcp

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> heise.de +tcp
;; global options: +cmd
;; connection timed out; no servers could be reached
```
The DNS resolution failed because there was no answer from the DNS server!
8. Run a remote shell in a similar pod, but this time on the _first_ node
```
kubectl run -n testcase \
  --labels="affected-by-dns-based-l3-rules=true" \
  --overrides='{"spec":{"nodeName":"'"$NODE1"'"}}' \
  --image arunvelsriram/utils \
  -it --rm \
  restricted--node1 \
  -- bash
```
9. Within that remote shell, try to resolve a DNS name both via UPD and TCP
```
root@restricted--node1:/# dig heise.de +notcp

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> heise.de +notcp
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14006
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 8a9db8963e5c579f (echoed)
;; QUESTION SECTION:
;heise.de.			IN	A

;; ANSWER SECTION:
heise.de.		30	IN	A	193.99.144.80

;; Query time: 3 msec
;; SERVER: 100.64.0.10#53(100.64.0.10)
;; WHEN: Mon Dec 07 13:30:07 UTC 2020
;; MSG SIZE  rcvd: 73
```
```
root@restricted--node1:/# dig heise.de +tcp

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> heise.de +tcp
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54001
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;heise.de.			IN	A

;; ANSWER SECTION:
heise.de.		30	IN	A	193.99.144.80

;; Query time: 4 msec
;; SERVER: 100.64.0.10#53(100.64.0.10)
;; WHEN: Mon Dec 07 13:30:11 UTC 2020
;; MSG SIZE  rcvd: 61
```
Here it works!

**Analysis**
When running `cilium monitor` while executing the scenario above we see the following
```
xx drop (Policy denied) flow 0xaa59aa59 to endpoint 1272, identity 6->9560: 100.96.0.217:57536 -> 100.96.1.91:8053 udp
xx drop (Policy denied) flow 0xdc51dc51 to endpoint 1272, identity 6->9560: 100.96.0.217:47925 -> 100.96.1.91:8053 udp
xx drop (Policy denied) flow 0x46c946c9 to endpoint 1272, identity 6->9560: 100.96.0.217:41670 -> 100.96.1.91:8053 udp
```

It seems that the dns requests are not executed based on the requesting pod identity, but rather as `remote-node` in the error case.

In previous cilium releases we could also use `cilium policy trace` to gain more insights
```
$ kubectl -n kube-system exec "$NODE1_CILIUM_POD" -- cilium policy trace --src-identity 6 --dst-identity 9560 --dport 8053/UDP
----------------------------------------------------------------

Tracing From: [reserved:remote-node] => To: [k8s:garden.sapcloud.io/role=system-component, k8s:io.cilium.k8s.namespace.labels.gardener.cloud/purpose=kube-system, k8s:io.cilium.k8s.namespace.labels.shoot.gardener.cloud/no-cleanup=true, k8s:io.cilium.k8s.policy.cluster=default, k8s:io.cilium.k8s.policy.serviceaccount=coredns, k8s:io.kubernetes.pod.namespace=kube-system, k8s:k8s-app=kube-dns, k8s:origin=gardener, k8s:shoot.gardener.cloud/no-cleanup=true] Ports: [8053/UDP]

Resolving ingress policy for [k8s:garden.sapcloud.io/role=system-component k8s:io.cilium.k8s.namespace.labels.gardener.cloud/purpose=kube-system k8s:io.cilium.k8s.namespace.labels.shoot.gardener.cloud/no-cleanup=true k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=coredns k8s:io.kubernetes.pod.namespace=kube-system k8s:k8s-app=kube-dns k8s:origin=gardener k8s:shoot.gardener.cloud/no-cleanup=true]
* Rule {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kube-system"},"matchExpressions":[{"key":"k8s:k8s-app","operator":"In","values":["kube-dns","coredns"]}]}: selected
    Enforcing requirements [{Key:k8s.io.kubernetes.pod.namespace Operator:Exists Values:[]}]
      No label match for [reserved:remote-node]
    Allows from labels {"matchLabels":{"cidr:100.96.0.0/11":""}}
      No label match for [reserved:remote-node]
1/9 rules selected
Found no allow rule
Ingress verdict: denied

Final verdict: DENIED
```

Again it points to the dns request not being accounted to the actual pod, but rather the cilium internal `reserved:remote-node`.

With a specific `CiliumNetworkPolicy` it works
```
kubectl create -f - <<EOF
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-dns-from-remote-nodes
  namespace: kube-system
spec:
  description: |
    Enables access from non-pod remote node IPs, in particular
    Cilium DNS proxies, to the cluster's DNS resolvers.
  endpointSelector:
    matchExpressions:
    - key: k8s-app
      operator: In
      values:
      - kube-dns
      - coredns
  ingress:
  - fromEntities:
    - remote-node
    toPorts:
    - ports:
      - port: "8053"
        protocol: TCP
      - port: "8053"
        protocol: UDP
EOF
```

```
$ kubectl -n kube-system exec "$NODE1_CILIUM_POD" -- cilium policy trace --src-identity 6 --dst-identity 9560 --dport 8053/UDP
----------------------------------------------------------------

Tracing From: [reserved:remote-node] => To: [k8s:garden.sapcloud.io/role=system-component, k8s:io.cilium.k8s.namespace.labels.gardener.cloud/purpose=kube-system, k8s:io.cilium.k8s.namespace.labels.shoot.gardener.cloud/no-cleanup=true, k8s:io.cilium.k8s.policy.cluster=default, k8s:io.cilium.k8s.policy.serviceaccount=coredns, k8s:io.kubernetes.pod.namespace=kube-system, k8s:k8s-app=kube-dns, k8s:origin=gardener, k8s:shoot.gardener.cloud/no-cleanup=true] Ports: [8053/UDP]

Resolving ingress policy for [k8s:garden.sapcloud.io/role=system-component k8s:io.cilium.k8s.namespace.labels.gardener.cloud/purpose=kube-system k8s:io.cilium.k8s.namespace.labels.shoot.gardener.cloud/no-cleanup=true k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=coredns k8s:io.kubernetes.pod.namespace=kube-system k8s:k8s-app=kube-dns k8s:origin=gardener k8s:shoot.gardener.cloud/no-cleanup=true]
* Rule {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kube-system"},"matchExpressions":[{"key":"k8s:k8s-app","operator":"In","values":["kube-dns","coredns"]}]}: selected
    Enforcing requirements [{Key:k8s.io.kubernetes.pod.namespace Operator:Exists Values:[]}]
      No label match for [reserved:remote-node]
    Allows from labels {"matchLabels":{"cidr:100.96.0.0/11":""}}
      No label match for [reserved:remote-node]
* Rule {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kube-system"},"matchExpressions":[{"key":"k8s:k8s-app","operator":"In","values":["kube-dns","coredns"]}]}: selected
    Allows from labels {"matchLabels":{"cidr:100.96.0.0/11":""}}
      No label match for [reserved:remote-node]
* Rule {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kube-system"},"matchExpressions":[{"key":"any:k8s-app","operator":"In","values":["kube-dns","coredns"]}]}: selected
    Allows from labels {"matchLabels":{"reserved:remote-node":""}}
      Found all required labels
      Allows port [{8053 TCP} {8053 UDP}]
3/11 rules selected
Found allow rule
Ingress verdict: allowed

Final verdict: ALLOWED
```

However, it is not expected that this network policy is required.

### Cilium Version

First discovered on 1.8.5
Still same behaviour on 1.11.1

### Kernel Version

Most recently evaluated on
Linux ip-10-255-9-93.eu-central-1.compute.internal 5.10.0-garden-cloud-amd64 #1 SMP Debian 5.10.93-0gardenlinux1 (2022-01-24) x86_64 GNU/Linux, but same behaviour on previous kernel releases

### Kubernetes Version

Initially found on 1.19.3, but other releases affected as well, e.g. 1.20.14

### Anything else?

Link to the original ticket: https://github.com/gardener/gardener-extension-networking-cilium/issues/35

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
