### ISSUE TITLE
Allow namespace in endpointSelector to be different from the namespace where the cilium policy is created

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#1922]
This is an enhancement request. Currently endpointSelector in the CiliumNetworkPolicy spec selects the namespace based on which namespace the CiliumNetworkPolicy resource gets created. It would be nice if there is an option where the namespace for the endpointSelector can be different from the namespace of the CiliumNetworkPolicy resource. I can think of a few cases where this could be useful:

- This allows the CiliumNetworkPolicy to be created in a separate isolated namespace so that you can modify the policies only if you have access to this protected namespace.
- It makes it easier to manage inter-namespace specs. Right now you need to create a separate policy in each namespace, making it difficult to "atomically" replace inter-namespace specs.
- It allows you to select endpoints without specifying a namespace. Sometimes you might want to select endpoints regardless of namespaces.
- You can express policies more concisely when you need to select multiple namespaces, doing something like this: 
   ```
  - endpointSelector:
      matchLabels:
        'k8s:app': myapp
      matchExpressions:
        - key: 'k8s:io.kubernetes.pod.namespace'
          operator: In
          values:
            - ns1
            - ns2
            - ns3
 ```
