### ISSUE TITLE
NetworkPolicy of fluxcd notification-controller causes constant failing cilium pod on a node in v1.11.[1-3]

### ISSUE THREAD

**Issue by DirkTheDaring** [cilium/cilium#19279]
this bug blocks a complete node from running its pods properly - please find a fix or suggest a workaround.
You can see effect of this by noticing hanging pods which do not get an IP Address assigned, e.g. the notification-controller of fluxcd hanging in "ContainerCreating".

Environment: Kubernetes cluster v1.23.5  with 14 nodes created with kubespray and cilium setting (1.11.[1-3])

What happens? When fluxcd v0.28.0  is rolled out in a cluster with cilium v1.11.[1-3] whenever the Networkpolicy of fluxcd for notification controller is applied, the cilium pod goes crazy and spits out a lot of similar messages (see below)
It restarts the a specific cilium pod every minute  - the cilium pod  runs  on the same node where pod notification-controller of fluxcd is running - which in turn has this NetworkPolicy (see below)

By trial and error I have found out when I delete NetworkPolicy the cilium  pod starts working again 
`kubectl -n flux-system delete NetworkPolicy allow-webhooks`

Messages in the cilium log (usually 30-50 of them.. only a sample here)
```
level=error msg="Failed to add PolicyMap key" bpfMapKey="{19103 0 0 0}" containerID=b7762c7eb5 datapathPolicyRevision=12 desiredPolicyRevision=16 endpointID=419 error="Unable to update element for cilium_policy_00419 map with file descriptor 152: the map is full, please consider resizing it. argument list too long" identity=47140 ipv4=192.168.67.184 ipv6= k8sPodName=flux-system/notification-controller-7dd8bdf67-kdrc6 port=0 subsys=endpoint
level=error msg="Failed to add PolicyMap key" bpfMapKey="{54803 0 0 0}" containerID=b7762c7eb5 datapathPolicyRevision=12 desiredPolicyRevision=16 endpointID=419 error="Unable to update element for cilium_policy_00419 map with file descriptor 152: the map is full, please consider resizing it. argument list too long" identity=47140 ipv4=192.168.67.184 ipv6= k8sPodName=flux-system/notification-controller-7dd8bdf67-kdrc6 port=0 subsys=endpoint
```
NetworkPolicy which causes this issue. Hint when i replace the  namespaceSelector line with another selector ,e.g. ipBlock then cilium has no problems at all.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v0.28.0
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: allow-webhooks
  namespace: flux-system
spec:
  ingress:
  - from:
    - namespaceSelector: {}
  podSelector:
    matchLabels:
      app: notification-controller
  policyTypes:
  - Ingress
```
