### ISSUE TITLE
Client Source IP from cilium_host interface

### ISSUE THREAD

**Issue by WMP** [cilium/cilium#19340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have k8s cluster with installed MetalLb with layer2 protocol:
```
  address-pools:
    - name: nginx-pool
      protocol: layer2
      addresses:
      - 172.17.2.7/32
      auto-assign: false
```

In deployment i install nginx with Service:
```
kind: Service
metadata:
  name: nginx-proxy
  annotations:
    metallb.universe.tf/address-pool:  nginx-pool
spec:                  
  loadBalancerIP: 172.17.2.7
  selector:
    app: nginx-proxy
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  type: LoadBalancer
  externalTrafficPolicy: Cluster 
```

I would like to have the real client IP in the logs, but I have the IP address from the cilium_host interface from the node on which the ARP for the address 172.17.2.7 is propagated through MetalLB. When I set `externalTrafficPolicy: Local` I have the real client IP in the logs, but I don't have traffic spread over multiple pods - the traffic always goes to the node that is propagating ARP for the MetalLb address. 

My cilium configuration:
```
kubeProxyReplacement: strict
      tunnel: disabled
      autoDirectNodeRoutes: true
      loadBalancer:
        mode: hybrid
        acceleration: native
      ipam:
        operator:
          clusterPoolIPv4PodCIDR: 10.42.0.0/16
          clusterPoolIPv4PodCIDRList:
            - 10.42.0.0/16
      ipv4NativeRoutingCIDR: 172.19.5.0/24
      nativeRoutingCIDR: 172.19.5.0/24
      k8sServiceHost: 172.19.5.1
      k8sServicePort: 6443
      operator:
        replicas: 2
      encryption:
        enabled: false
        type: wireguard
      l7Proxy: false
```

### Cilium Version

1.10.4

### Kernel Version

5.4.0-104-generic #118-Ubuntu

### Kubernetes Version

 1.22 (v1.22.7+rke2r1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WMP** [comment]
Yes,  i trying to use DSR, following with: https://docs.cilium.io/en/v1.10/gettingstarted/kubeproxy-free/#dsr-mode . I trying settings:
```
kubeProxyReplacement: strict 
tunnel: disabled
autoDirectNodeRoutes: true
loadBalancer:
   mode: dsr
```

and 

```
kubeProxyReplacement: strict 
tunnel: disabled
autoDirectNodeRoutes: true
loadBalancer:
   mode: hybrid
```

**Comment by WMP** [comment]
Now i trying with `externalIPs` field in service, but without any change, i still see IP from cilium_host.

**Comment by pchaigno** [comment]
DSR didn't work? What was the issue?

**Comment by WMP** [comment]
The issue is that i havent really client source IP but i have IP from cilium_host interface. 

Cilium config:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    cilium:
      kubeProxyReplacement: strict
      tunnel: disabled
      autoDirectNodeRoutes: true
      loadBalancer:
        mode: dsr
      ipam:
        operator:
          clusterPoolIPv4PodCIDR: 10.42.0.0/16
          clusterPoolIPv4PodCIDRList:
            - 10.42.0.0/16
      ipv4NativeRoutingCIDR: 172.19.5.0/24
      nativeRoutingCIDR: 172.19.5.0/24
      k8sServiceHost: 172.19.5.1
      k8sServicePort: 6443
      operator:
        replicas: 2
      encryption:
        enabled: false
        type: wireguard
      l7Proxy: false
      hubble:
        metrics:
          enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - icmp
          - http
        relay:
          enabled: true
        ui:
          enabled: true
          replicas: 1
          ingress:
            enabled: true
            className: nginx
            hosts:
              - hubble.CUT-HERE
            annotations:
              cert-manager.io/cluster-issuer: acme.CUT-HERE
              kubernetes.io/ingress.class: nginx
            tls:
            - secretName: ingress-hubble-ui-tls
              hosts:
              - hubble.CUT-HERE
      prometheus:
        enabled: true
        # Default port value (9090) needs to be changed since the RHEL cockpit also listens on this port.
        port: 19090
        # Configure this serviceMonitor section AFTER Rancher Monitoring is enabled!
        #serviceMonitor:
        #  enabled: true
```

Cilium status:
```
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.22 (v1.22.7+rke2r1) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [br100 172.17.2.6, br705 172.19.5.1 (Direct Routing)]
Cilium:                 Ok   1.10.4 (v1.10.4-2a46fd6)
NodeMonitor:            Listening for events on 56 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPAM:                   IPv4: 6/254 allocated from 10.42.0.0/24, 
Allocated addresses:
  10.42.0.148 (router)
  10.42.0.197 (kube-logging/fluentd-b2gx6)
  10.42.0.211 (kube-system/csi-secrets-store-secrets-store-csi-driver-7tv46)
  10.42.0.227 (health)
  10.42.0.6 (ceph-csi-rbd/ceph-csi-rbd-provisioner-f875545b-mzvml)
  10.42.0.66 (dc-debug/debian9-qj4vd)
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           BPF   [br100, br705]   10.42.0.0/24 [IPv4: Enabled, IPv6: Disabled]
Clock Source for BPF:   ktime
Controller Status:      35/35 healthy
  Name                                  Last success    Last error   Count   Message
  cilium-health-ep                      13s ago         never        0       no error   
  dns-garbage-collector-job             29s ago         never        0       no error   
  endpoint-1211-regeneration-recovery   never           never        0       no error   
  endpoint-1445-regeneration-recovery   never           never        0       no error   
  endpoint-179-regeneration-recovery    never           never        0       no error   
  endpoint-2476-regeneration-recovery   never           never        0       no error   
  endpoint-2710-regeneration-recovery   never           never        0       no error   
  endpoint-48-regeneration-recovery     never           never        0       no error   
  endpoint-gc                           2m30s ago       never        0       no error   
  k8s-heartbeat                         22s ago         never        0       no error   
  mark-k8s-node-as-available            22h52m16s ago   never        0       no error   
  metricsmap-bpf-prom-sync              6s ago          never        0       no error   
  neighbor-table-refresh                2m16s ago       never        0       no error   
  resolve-identity-1211                 2m15s ago       never        0       no error   
  resolve-identity-1445                 2m15s ago       never        0       no error   
  resolve-identity-179                  2m16s ago       never        0       no error   
  resolve-identity-2476                 2m16s ago       never        0       no error   
  resolve-identity-2710                 2m16s ago       never        0       no error   
  resolve-identity-48                   2m15s ago       never        0       no error   
  sync-endpoints-and-host-ips           14s ago         never        0       no error   
  sync-lb-maps-with-k8s-services        22h52m16s ago   never        0       no error   
  sync-policymap-1211                   7s ago          never        0       no error   
  sync-policymap-1445                   7s ago          never        0       no error   
  sync-policymap-179                    7s ago          never        0       no error   
  sync-policymap-2476                   5s ago          never        0       no error   
  sync-policymap-2710                   7s ago          never        0       no error   
  sync-policymap-48                     7s ago          never        0       no error   
  sync-to-k8s-ciliumendpoint (1211)     10s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (1445)     10s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (179)      10s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (2476)     11s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (2710)     10s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (48)       9s ago          never        0       no error   
  template-dir-watcher                  never           never        0       no error   
  update-k8s-node-annotations           22h52m29s ago   never        0       no error   
Proxy Status:   No managed proxy redirect
Hubble:         Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 7.21   Metrics: Ok
KubeProxyReplacement Details:
  Status:                Strict
  Socket LB Protocols:   TCP, UDP
  Devices:               br100 172.17.2.6, br705 172.19.5.1 (Direct Routing)
  Mode:                  SNAT
  Backend Selection:     Random
  Session Affinity:      Enabled
  XDP Acceleration:      Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Enabled (Range: 30000-32767) 
  - LoadBalancer:   Enabled 
  - externalIPs:    Enabled 
  - HostPort:       Enabled
BPF Maps:   dynamic sizing: on (ratio: 0.002500)
  Name                          Size
  Non-TCP connection tracking   592286
  TCP connection tracking       1184572
  Endpoint policy               65535
  Events                        56
  IP cache                      512000
  IP masquerading agent         16384
  IPv4 fragmentation            8192
  IPv4 service                  65536
  IPv6 service                  65536
  IPv4 service backend          65536
  IPv6 service backend          65536
  IPv4 service reverse NAT      65536
  IPv6 service reverse NAT      65536
  Metrics                       1024
  NAT                           1184572
  Neighbor table                1184572
  Global policy                 16384
  Per endpoint policy           65536
  Session affinity              65536
  Signal                        56
  Sockmap                       65535
  Sock reverse NAT              592286
  Tunnel                        65536
Encryption:              Disabled
Cluster health:          3/3 reachable   (2022-04-07T09:22:39Z)
  Name                   IP              Node        Endpoints
  kub05n01 (localhost)   172.19.5.1      reachable   reachable
  kub05n02               172.19.5.2      reachable   reachable
  kub05n03               172.19.5.3      reachable   reachable
```
`cilium bpf lb list` for LoadBalancer IP :
```
172.17.2.7:80        0.0.0.0:0 (7) [ExternalIPs]                      
                     10.42.2.109:80 (7)                               
                     10.42.2.224:80 (7)                               
                     10.42.1.64:80 (7)                                                
172.17.2.7:443       0.0.0.0:0 (8) [ExternalIPs]                      
                     10.42.2.224:443 (8)                              
                     10.42.2.109:443 (8)                              
                     10.42.1.64:443 (8)                               

```
kubectl get pod -o wide:
```
NAME                                      READY   STATUS    RESTARTS      AGE   IP            NODE       NOMINATED NODE   READINESS GATES
nginx-proxy-deployment-7f9554bfbf-c7dt9   2/2     Running   2 (22h ago)   23h   10.42.2.109   kub05n03   <none>           <none>
nginx-proxy-deployment-7f9554bfbf-gvv7p   2/2     Running   2 (22h ago)   25h   10.42.2.224   kub05n03   <none>           <none>
nginx-proxy-deployment-7f9554bfbf-gz5sc   2/2     Running   2 (23h ago)   44h   10.42.1.64    kub05n02   <none>           <none>
```

kubectl describe service:
```
Name:                     nginx-proxy
Namespace:                wildcard-test
Labels:                   app.kubernetes.io/managed-by=Helm
Annotations:              field.cattle.io/publicEndpoints:
                            [{"addresses":["172.17.2.7"],"port":80,"protocol":"TCP","serviceName":"wildcard-test:nginx-proxy","allNodes":false},{"addresses":["172.17....
                          meta.helm.sh/release-name: wildcard-test
                          meta.helm.sh/release-namespace: wildcard-test
                          metallb.universe.tf/address-pool: wildcard-vlan100
Selector:                 app=nginx-proxy
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.43.131.47
IPs:                      10.43.131.47
External IPs:             172.17.2.7
LoadBalancer Ingress:     172.17.2.7
Port:                     http  80/TCP
TargetPort:               80/TCP
NodePort:                 http  30372/TCP
Endpoints:                10.42.1.64:80,10.42.2.109:80,10.42.2.224:80
Port:                     https  443/TCP
TargetPort:               443/TCP
NodePort:                 https  30325/TCP
Endpoints:                10.42.1.64:443,10.42.2.109:443,10.42.2.224:443
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

MetalLb configuration:
```
NAME                                      READY   STATUS    RESTARTS      AGE
pod/metallb-controller-69bbb4669c-mmw5z   1/1     Running   1 (23h ago)   23h
pod/metallb-speaker-kmppg                 1/1     Running   3 (22h ago)   21d
pod/metallb-speaker-r6dnq                 1/1     Running   2 (22h ago)   21d
pod/metallb-speaker-xhcsr                 1/1     Running   2 (23h ago)   21d

NAME                             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/metallb-speaker   3         3         3       3            3           kubernetes.io/os=linux   21d

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/metallb-controller   1/1     1            1           21d

NAME                                            DESIRED   CURRENT   READY   AGE
replicaset.apps/metallb-controller-69bbb4669c   1         1         1       21d
```
metallb configmap:
```
kubectl describe cm metallb
Name:         metallb
Namespace:    metallb-system
Labels:       app.kubernetes.io/instance=metallb
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=metallb
              app.kubernetes.io/version=v0.12.1
              helm.sh/chart=metallb-0.12.1
Annotations:  meta.helm.sh/release-name: metallb
              meta.helm.sh/release-namespace: metallb-system

Data
====
config:
----
address-pools:
- addresses:
  - 172.17.1.95/32
  auto-assign: false
  name: ingress-internal
  protocol: layer2
- addresses:
  - 172.17.2.7/32
  auto-assign: false
  name: wildcard-vlan100
  protocol: layer2
```

And issue - Nginx logs has ` Allocated addresses: 10.42.0.148 (router)` expected  as my real IP:

```
nginx-proxy-deployment-7f9554bfbf-gvv7p nginx-proxy 10.42.0.148 - - [07/Apr/2022:11:30:23 +0200] "GET / HTTP/2.0" 200 181731 "-" "curl/7.68.0"
```
If i change service to `External Traffic Policy: Local` i have my real IP.
