### ISSUE TITLE
DNS policies: block egress traffic only to blacklisted FQDNs

### ISSUE THREAD

**Issue by norbjd** [cilium/cilium#19386]
## Proposal / RFE

**Is your feature request related to a problem?**

In a k8s cluster where untrusted workloads are running, there is no way to block traffic only to specific destinations. For example, block access to `*.twitter.com` to avoid having Twitter bots working in the k8s cluster.

**Describe the solution you'd like**

As of now, it is possible to define [DNS policies using patterns](https://docs.cilium.io/en/v1.11/gettingstarted/dns/#dns-policies-using-patterns), like this:

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "fqdn"
spec:
  endpointSelector:
    matchLabels:
      class: test
  egress:
  - toFQDNs:
    - matchPattern: "*.twitter.com" 
```

This blocks all egress traffic, **except** to `*.twitter.com`. From a pod with `class: test` label, `curl api.twitter.com` will work, but `curl google.com` won't.

It should be nice to implement the "opposite" behavior. That means: all `curl` will work, except `curl api.twitter.com`, `curl help.twitter.com`, etc. Something like the following (notice the introduction of the `notToFQDNs` field):

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "fqdn"
spec:
  endpointSelector:
    matchLabels:
      class: test
  egress:
  - notToFQDNs:
    - matchPattern: "*.twitter.com" 
```

Or maybe by taking the example of [`except` in `toCIDRSet`](https://docs.cilium.io/en/v1.11/policy/language/#allow-to-external-cidr-block):

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "fqdn"
spec:
  endpointSelector:
    matchLabels:
      class: test
  egress:
  - toFQDNs:
    - matchPattern: "*"
      except:
      - "*.twitter.com" 
```

What do you think of this? Am I missing something and is this already possible? Thanks :pray:

**Comment by aanm** [comment]
What if the application already knows the IP address of twitter.com and will use that IP address without performing a DNS resolution?

**Comment by norbjd** [comment]
@aanm In that case, I guess that using `except` with `toCIDRSet` is ok.

But this requires to find **every** IP behind all `*.twitter.com`. This is not really convenient. And it only works if IPs behind the FQDN do not change.

Note that `*.twitter.com` is just an example, we can imagine having something larger like `*.com`.

**Comment by aanm** [comment]
> But this requires to find every IP behind all *.twitter.com. This is not really convenient. And it only works if IPs behind the FQDN do not change.

@norbjd precisely my point, if `192.0.2.1` is blocked because there was a DNS resolution that resolved the `www.twitter.com` to `192.0.2.1`, how could we know that the App didn't store the IP address `192.0.2.2`, which also belongs to `www.twitter.com` and uses that IP address instead of `192.0.2.1`?

**Comment by norbjd** [comment]
Ok, I misunderstood your first comment, sorry. Thanks for clarifying :raised_hands: 

You are right, I haven't thought about this. I guess that **just** blocking DNS is not 100% reliable, but most of the applications resort to DNS and use FQDNs instead of bothering to manage an up-to-date IP list behind a FQDN.

But I guess this is the same issue with the existing [DNS policies](https://docs.cilium.io/en/v1.11/gettingstarted/dns/#dns-policies-using-patterns), right?

I mean, with this `CiliumNetworkPolicy`:

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "fqdn"
spec:
  endpointSelector:
    matchLabels:
      class: test
  egress:
  - toFQDNs:
    - matchPattern: "*.twitter.com" 
```

Running a query to `google.com` won't work, but calling directly an IP behind `google.com` will work, am I right?
