### ISSUE TITLE
[BGP Control Plane]: Reports of incorrect PodCIDR announcement 

### ISSUE THREAD

**Issue by ldelossa** [cilium/cilium#19411]
I am also working on integration Cilium with BGP and I am having a few issues:

- Can't set a password for the peering as said by @arianvp 
- I am not sure how I advertise LoadBalancer IPs via BGP
- The documentation is contradicting itself: in https://github.com/cilium/cilium/tree/master/pkg/bgpv1 is stated:
  `Only a single CiliumBGPPeeringPolicy can apply to a Cilium node.`
and then in https://github.com/cilium/cilium/tree/master/pkg/bgpv1#virtual-router-attributes
`A CiliumBGPPeeringPolicy can apply to multiple nodes.`
- I want to peer each Cilium node to two switches for redundancy. I did it like this and is working. This is not documented specifically but I guess is fine?
```
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: rack2
  namespace: kube-system
spec:
 nodeSelector:
   matchLabels:
     rack_id: "2"
 virtualRouters: # []CiliumBGPVirtualRouter
 - localASN: 65003
   exportPodCIDR: true
   neighbors: # []CiliumBGPNeighbor
    - peerAddress: "192.168.11.203/32"
      peerASN: 65002
    - peerAddress: "192.168.11.204/32"
      peerASN: 65002
```
- Only 1 node is advertising the POD CIDR and it advertising the /24 POD CIDR but not the /27 POD subnets that I allocate to the nodes:

```
kubectl  describe node | grep ipv4-pod-cidr
                    io.cilium.network.ipv4-pod-cidr: 192.168.12.160/27
                    io.cilium.network.ipv4-pod-cidr: 192.168.12.64/27
                    io.cilium.network.ipv4-pod-cidr: 192.168.12.96/27
                    io.cilium.network.ipv4-pod-cidr: 192.168.12.0/27
                    io.cilium.network.ipv4-pod-cidr: 192.168.12.128/27
                    io.cilium.network.ipv4-pod-cidr: 192.168.12.32/27
```

For example:

```
Leaf201# show ip route vrf  Cilium:Cilium 192.168.12.0
192.168.12.0/24, ubest/mbest: 1/0
    *via 192.168.11.1%Cilium:Cilium, [20/0], 00:13:05, bgp-65002, external, tag 65003
         recursive next hop: 192.168.11.1/32%Cilium:Cilium

Leaf201# show ip route vrf  Cilium:Cilium 192.168.12.0/27
Route not found
```
I was expecting to get the /27, before I tested with the "old" BGP feature (the on in beta) and it did export the /27

my Cilium config is like this:

```
# CiliumBGPPeeringPolicy CRDs.
bgpControlPlane:
  enabled: true

ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDRList: ["192.168.12.0/24"]
    clusterPoolIPv4MaskSize: 27
```

Also more in general, if I am looking to create a configuration best practice for Cilium and BGP should I focus on this new implementation ? Seems to me this is the way forward? But I would like to be certain.

_Originally posted by @camrossi in https://github.com/cilium/cilium/issues/19376#issuecomment-1096055394_
