### ISSUE TITLE
CFP: allow CiliumClusterwideNetworkPolicy to match namespaces based on their labels

### ISSUE THREAD

**Issue by norbjd** [cilium/cilium#19547]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

When having multiple namespaces in a cluster (hundreds or thousands) with the same ingress or egress rules, creating and maintaining one `CiliumNetworkPolicy` per namespace can be cumbersome.

Example with 1000 namespaces (`ns1`, `ns2`, ..., `ns1000`), there is one file like this per namespace:

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: netpol
  namespace: ns1 # for every namespace ns1, ns2, ..., ns1000
spec:
  ... # always the same spec
```

Using a `CiliumClusterwideNetworkPolicy` does not work (as far as I know), because it applies on all namespaces, and we only want to restrict to `ns1`, `ns2`, ..., `ns1000` namespaces.

Note that in my case, **all namespaces** `ns1`, `ns2`, ..., `ns1000`, on which I want to apply the network policy, have the same labels (example: `class: special-namespace`):

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    class: special-namespace
  name: ns1
spec: {}
```

**Describe the feature you'd like**

With `CiliumClusterwideNetworkPolicy`, it would be nice to select some namespaces **based on their labels**.

**(Optional) Describe your proposed solution**

Maybe `matchLabels` could reference **namespace labels**? Something like this:

```yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: netpol
spec:
  endpointSelector:
    matchLabels:
      # not sure if something like this would work, but you got the idea
      k8s:io.kubernetes.pod.namespace.labels.class: special-namespace
```

Or maybe there is a simpler solution that I have not seen?

**Comment by aanm** [comment]
@norbjd I believe `matchExpressions` could work for your use case.

**Comment by norbjd** [comment]
@aanm Thanks for your help! Indeed, it works with:

```yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: netpol
spec:
  endpointSelector:
    matchExpressions:
    - key: "any:io.cilium.k8s.namespace.labels.class"
      operator: In
      values:
      - "special-namespace"
```

Sorry about the noise, I will close the issue. Thanks again!
