### ISSUE TITLE
When specifying l4 CNP rule, trace succeeds but packets are dropped

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#1955]
It was observed that with the following L4 policy, packets to port 80 were dropped, but the `cilium policy trace` output suggested that the traffic should be allowed.

```
kind: CiliumNetworkPolicy
apiVersion: cilium.io/v2
specs:
  - endpointSelector:
      matchLabels:
        'k8s:app': frontend
    ingress:
      - toPorts:
          - ports:
              - port: '80'
                protocol: TCP
            rules:
              http:
                - method: .*
                  path: .*
```

The trace was performed like: `cilium policy trace --src-identity XXX --dst-identity XXX --dport 80`.
