### ISSUE TITLE
K8s watcher doesn't regenerate policy after endpoint backing headless service is added

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#1964]
### How to reproduce the issue

1. deploy demo app `kubectl create -f https://raw.githubusercontent.com/cilium/cilium/master/examples/minikube/demo.yaml`
2. `kubectl create -f policy.yaml` policy.yaml contents:
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "L7 policy for getting started using Kubernetes guide"
metadata:
  name: "rule2"
spec:
  endpointSelector:
    matchLabels:
      "id": "app2"
  egress:
  -
    toServices:
    - k8sService:
        serviceName: headless-service
        namespace: default
```

3. `kubectl create -f headless.yaml`
```
apiVersion: v1
kind: Service
metadata:
  name: headless-service
spec:
  clusterIP: None
```

4. `kubectl create -f endpoint.yaml`
```
apiVersion: v1
kind: Endpoints
metadata:
  name: headless-service
  namespace: default
subsets:
- addresses:
  - ip: 54.186.23.98
  ports:
  - port: 80
    protocol: TCP
```
5. `kubectl exec -n kube-system $(ciliumpod) cilium policy get` returns egress policy with toCIDR populated from endpoint IP.

6. `kubectl exec -n kube-system $(ciliumpod) cilium endpoint get <enforced endpoint id>` returns policy without the toCIDR egress rules. This is caused by not regenerating cilium endpoint after k8s endpoint is added.
