### ISSUE TITLE
Egress gateway partially incompatible with L7 policies 

### ISSUE THREAD

**Issue by jibi** [cilium/cilium#19642]
The egress gateway feature is partially incompatible with L7 policies: traffic will not be forwarded to a gateway if there's an L7 policy selecting the same endpoint selected by an egress gateway policy.

The specific problem is that the egress gateway logic to forward traffic to a gateway lives currently in `bpf_lxc`, right after the L7 proxy redirection, so if a packet is redirected to the L7 proxy (and then reinjected back into the stack), egress gateway will be completely skipped.

One way to fix this would be to move the egress gateway logic from `bpf_lxc` to `bpf_host`, but this is currently not a viable option as the agent is not yet able to dynamically load `bpf_host` on new network devices. This in turn would be a problem in environments such as EKS, where new ENIs are dynamically allocated to accommodate additional pod IPs.

**Comment by joestringer** [comment]
Related: #17460

**Comment by shaardie** [comment]
Is the problem limited to the ports with the actual l7 policies? We have l7 proxy activated and have egress DNS l7 policies for all Pods, but the Egress Gateway is still working fine for HTTP Traffic.

**Comment by jibi** [comment]
> Is the problem limited to the ports with the actual l7 policies? We have l7 proxy activated and have egress DNS l7 policies for all Pods, but the Egress Gateway is still working fine for HTTP Traffic.

If the L7 policies are not selecting the same endpoint targeted by an egress gateway policy, which seems to be the case here, then it shouldn't be an issue

**Comment by shaardie** [comment]
> > Is the problem limited to the ports with the actual l7 policies? We have l7 proxy activated and have egress DNS l7 policies for all Pods, but the Egress Gateway is still working fine for HTTP Traffic.
> 
> If the L7 policies are not selecting the same endpoint targeted by an egress gateway policy, which seems to be the case here, then it shouldn't be an issue

Thanks for the answer, but unfortunately I still did not understand. I used `cilium endpoint get <id>` to get information about the endpoint and I see a lot of l7 policies there (derived from our `CiliumClusterwideNetworkPolicies`) and the IP of the Endpoint is listed in `cilium bpf egress list`. So I thought the same endpoint is targeted from the egress gateway policy and the l7 policy.

**Comment by jibi** [comment]
@shaardie could you share an example of a policy?

**Comment by shaardie** [comment]
> @shaardie could you share an example of a policy?


Sure. A little stripped down example working on our cluster:

```yaml
---
# Clusterwide Policy
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: dns-visibility
spec:
  egress:
  - toEntities:
    - host
    - world
    toPorts:
    - ports:
      - port: "53"
        protocol: TCP
      - port: "53"
        protocol: UDP
      rules:
        dns:
        - matchPattern: '*'
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.namespace.labels.dnsvisibility: "true"
---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  labels:
    dnsvisibility: "true"
  name: sven-test
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload
  namespace: sven-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload
  template:
    metadata:
      labels:
        app: workload
        cilium.io/egress: "true"
    spec:
      containers:
      - args:
        - -c
        - while true; do curl -v4 --max-time 1 https://example.com; sleep 1; done
        command:
        - /bin/bash
        image: centos
        name: workload
---
# Namespaced Policy
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: workload
  namespace: sven-test
spec:
  egress:
  - toFQDNs:
    - matchName: example.com
    toPorts:
    - ports:
      - port: "443"
    - ports:
      - port: "80"
  endpointSelector:
    matchLabels:
      app: workload
```

and our gateway configuration:

```yaml
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egressgateway
spec:
  destinationCIDRs:
  # Stripped. Basically everything, but the local networks
  - 0.0.0.1/32
  - 0.0.0.2/31
  - 0.0.0.4/30
  - 0.0.0.8/29
  - 0.0.0.16/28
  - 0.0.0.32/27
  - 0.0.0.64/26
  - 0.0.0.128/25
  - 0.0.1.0/24
  - 0.0.2.0/23
  - 0.0.4.0/22
  - 0.0.8.0/21
  - 0.0.16.0/20
  - 0.0.32.0/19
  - 0.0.64.0/18
  - 0.0.128.0/17
  - 0.1.0.0/16
  - 0.2.0.0/15
  - 0.4.0.0/14
  - 0.8.0.0/13
  - 0.16.0.0/12
  - 0.32.0.0/11
  - 0.64.0.0/10
  - 0.128.0.0/9
  - 1.0.0.0/8
  - 2.0.0.0/7
  - 4.0.0.0/6
  - 8.0.0.0/7
  - 11.0.0.0/8
...
  egressGateway:
    nodeSelector:
      matchLabels:
        role.node.kubernetes.io/external: ""
  selectors:
  - podSelector:
      matchLabels:
        cilium.io/egress: "true"
```

So as far as I can see both Policies should match the pods created by this Deployment. I can also see that the Traffic is routed via our Nodes with `role.node.kubernetes.io/external: ""`.

Btw. we are currently running 1.12.4.

@jibi  I hope, I have not stripped away something essential. If you need any other information, please let me know.
