### ISSUE TITLE
Egress policy blocks all outgoing traffic

### ISSUE THREAD

**Issue by carloruiz** [cilium/cilium#19676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Steps to repro:**

1. Create a sample kubernetes app.
2. Install Cilium on GKE using this guide https://docs.cilium.io/en/v1.11/gettingstarted/k8s-install-helm/
3. Add an egress network policy targeting the sample app, with any value for `toCIDR`.
```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: sample-egress-policy
  namespace: us-west2
spec:
  egress:
  - toCIDR:
    - 0.0.0.0/0
  endpointSelector:
    matchLabels:
      app: cockroachdb
```
4. The pods with targeted labels are unable to establish network connections, either to internal cluster endpoints or external services. 

Note: I've tried different values for the `toCIDR` block with the same results. 

### Cilium Version

v1.10.10

### Kernel Version

Red Hat Enterprise Linux 8.5

### Kubernetes Version

v1.19.16-gke.11000

### Sysdump

[cilium-sysdump-20220503-035026.zip](https://github.com/cilium/cilium/files/8608011/cilium-sysdump-20220503-035026.zip)

### Anything else?

Seems like this [issue](https://github.com/cilium/cilium/issues/16147) is related.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by carloruiz** [comment]
I'm guessing this is a bug in the tutorial than the code itself.

**Comment by kaworu** [comment]
The sysdump shows dropped flows from `cockroachdb-1` to `kube-dns`. From the [IP/CIDR based Policy documentation](https://docs.cilium.io/en/stable/policy/language/#ip-cidr-based):
> […] CIDR rules do not apply to traffic where both sides of the connection are either managed by Cilium or use an IP belonging to a node in the cluster (including host networking pods). This traffic may be allowed using labels, services or entities -based policies as described above.

So in addition to the `toCIDR` egress policy you need to allow `kube-dns`:
```yaml
  egress:
    - toCIDR:
      - 0.0.0.0/0
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
          - port: "53"
            protocol: ANY
          rules:
            dns:
              - matchPattern: "*"

```
