### ISSUE TITLE
CFP:  Multiple egressSourceIPs(Round-robin) In CiliumEgressNATPolicy

### ISSUE THREAD

**Issue by k-nuhdim** [cilium/cilium#19763]
## Cilium Feature Proposal
      
Hello Team, 

Requirement - Need to sent egress traffic via a Pool of IP's as Round-robin.
i.e Any external traffic going out from the application pod should be pick in roundrobin from a set of  IPs.

```
apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
metadata:
  name: egress-sample
spec:
  egress:
  - podSelector:
      matchLabels:
        org: empire
        class: mediabot
        # The following label selects default namespace
        io.kubernetes.pod.namespace: default
  destinationCIDRs:
  - 192.168.60.13/32
  egressSourceIP: "192.168.60.100"
```

Above are the existing policy where we can pick only single IP as egresssource IP, expecting  some feature where we can use multiple IP;s in above policies
 eg:-  like  "egressSourceIPs: "192.168.60.10,192.168.60.11,192.168.60.12,192.168.60.13"  like this and also cilium can take care of the roundrobin of picking the IP from the pool. It would be a great feature if we have this kind of flexibility in Policy. 
 

~ Midhun K
