### ISSUE TITLE
Rolling restart pods causes brief outage with externalTrafficPolicy=Local

### ISSUE THREAD

**Issue by ysksuzuki** [cilium/cilium#19810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Some requests to Loadbalancer service with externalTrafficPolicy=Local failed due to `No route to host` during we updated its backend pods. The old pods remained in the terminating state for a while to handle the existing active connections and gracefully shut down. (We updated our Envoy pods.) It seems that the packets received by the nodes where the terminating pods were running were getting nowhere.

## How to reproduce the issue

- Install Cilium with kube-proxy replacement and bgp.announce.loadbalancerIP are enabled. (See values.yaml following)
- Apply the manifest. (The pods derived from the deployment will remain terminating state by the preStop hook when those stop.)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suzuki-test
  namespace: dctest
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: suzuki-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: suzuki-test
    spec:
      containers:
      - image: quay.io/ysksuzuki/testhttpd:0
        name: testhttpd
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "30"]
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: suzuki-test
  namespace: dctest
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: suzuki-test
```
- Run `kubectl -n dctest rollout restart deployment/suzuki-test`
- Access to the service

```
$ curl -v 10.72.32.1
*   Trying 10.72.32.1:80...
* TCP_NODELAY set
* connect to 10.72.32.1 port 80 failed: No route to host
* Failed to connect to 10.72.32.1 port 80: No route to host
* Closing connection 0
curl: (7) Failed to connect to 10.72.32.1 port 80: No route to host
```

vallues.yaml
```
bgp:
  announce:
    loadbalancerIP: true
  enabled: true
bpf:
  hostRouting: true
cni:
  chainingMode: "generic-veth"
  customConf: true
datapathMode: "veth"
devices: "eth+ eno1+ eno2+"
enableIPv4Masquerade: false
enableIdentityMark: false
externalIPs:
  enabled: true
hostPort:
  enabled: false
hostServices:
  enabled: true
  hostNamespaceOnly: true
hubble:
  relay:
    enabled: true
    tls:
      server:
        enabled: true
    rollOutPods: true
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
  tls:
    auto:
      method: "cronJob"
  metrics:
    enabled:
      - "dns"
      - "drop:destinationContext=pod|dns|ip;sourceContext=pod|dns|ip"
      - "tcp"
      - "flow:destinationContext=pod|dns|ip;sourceContext=pod|dns|ip"
      - "icmp"
      - "http"
k8sServiceHost: 127.0.0.1
k8sServicePort: 16443
kubeProxyReplacement: "partial"
loadBalancer:
  # We can't enable XDP Acceleration because of the issue https://github.com/cilium/cilium/issues/19453
  acceleration: disabled
  algorithm: maglev
  mode: dsr
maglev:
  hashSeed: 3HCx6JennjWtot2U
nodePort:
  directRoutingDevice: "e+"
  enabled: true
operator:
  rollOutPods: true
  prometheus:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
policyAuditMode: false
policyEnforcementMode: "default"
prometheus:
  enabled: true
resources:
  requests:
    cpu: 100m
    memory: 400Mi
rollOutCiliumPods: true
tunnel: "disabled"
```

## What is happening?

When pods restart, Cilium detects the endpoint state is terminating and remove the service's backend from cilium_lb4_services_v2. 

```
$ kubectl -n kube-system exec cilium-6xm8g -- cilium bpf lb list
SERVICE ADDRESS       BACKEND ADDRESS
10.72.32.1:80         0.0.0.0:0 (26) [LoadBalancer, Local]
```

MetalLB is advertising the route to the LB until the pods are removed. So the node where the terminating pod is running still receives new connections to the LB, but Cilium can't handle the new connection because there's no backend for LB_LOOKUP_SCOPE_EXT scope value, and it won't forward them to the cluster-wide backends for externalTrafficPolicy=Local service.

```
# Pod is terminating
bird> show route 10.72.32.1/32
Table master4:
10.72.32.1/32        unicast [metallb 06:32:34.149 from 127.0.0.1] * (100/?) [AS64698?]
        via 10.69.1.193 on eth0

# Pod is removed. MetalLB withdraw the advertisement
bird> show route 10.72.32.1/32
Table master4:
10.72.32.1/32        unicast [tor1 07:40:56.715] * (100/?) [AS64698?]
        via 10.69.1.193 on eth0
                     unicast [tor2 07:40:56.715] (100/?) [AS64698?]
        via 10.69.2.1 on eth1
```

### Cilium Version

Client: 1.11.4 9d2546357e 2022-04-15T08:33:55-07:00 go version go1.17.9 linux/amd64
Daemon: 1.11.4 9d2546357e 2022-04-15T08:33:55-07:00 go version go1.17.9 linux/amd64

### Kernel Version

```
$ uname -a
Linux rack0-cs5 5.15.32-flatcar #1 SMP Tue Apr 5 17:17:31 -00 2022 x86_64 AMD EPYC 7413 24-Core Processor AuthenticAMD GNU/Linux
```

### Kubernetes Version

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"archive", BuildDate:"2022-03-23T08:04:34Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

[cilium-sysdump-20220513-070444.zip](https://github.com/cilium/cilium/files/8685324/cilium-sysdump-20220513-070444.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
