### ISSUE TITLE
Cilium blocking valid traffic if the port is named 'api' (AKS specific?)

### ISSUE THREAD

**Issue by akostic-kostile** [cilium/cilium#19851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I seem to have run into a weird case where valid traffic is being dropped, if the port is named 'api'. 
**This was tested on AKS, on k8s version v1.22.6.**

I was able to reproduce the issue by using the following manifests.

API:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api-svc
spec:
  ports:
  - name: api
  # - name: example
    port: 8080
    targetPort: api
    # targetPort: example
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:latest
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 8080
          name: api
          # name: example
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  labels:
    app: api
  name: api-cnp
spec:
  egress:
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: '*'
  endpointSelector:
    matchLabels:
      app: api
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: api
  name: api-np
spec:
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - dashboard
    ports:
    - port: api
    # - port: example
  podSelector:
    matchLabels:
      app: api
  policyTypes:
  - Ingress
```

dashboard:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dashboard
  name: dashboard-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:latest
        imagePullPolicy: Always
        name: dashboard
        ports:
        - containerPort: 8080
          name: dashboard
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  labels:
    app: dashboard
  name: dashboard-cnp
spec:
  egress:
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: '*'
  endpointSelector:
    matchLabels:
      app: dashboard
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: dashboard
  name: dashboard-np
spec:
  egress:
  - ports:
    - port: api
    # - port: example
    to:
    - podSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - api
  podSelector:
    matchLabels:
      app: dashboard
  policyTypes:
  - Egress
```

If we deploy these manifests we'll see that dashboard is unable to communicate with API:
```
nginx@dashboard-deploy-75d9988f5b-jjnbj:/$ curl --connect-timeout 5 --head http://api-svc:8080/
curl: (28) Connection timed out after 5001 milliseconds
```
When traffic is dropped this is how hubble-ui is reporting it:
![Screenshot 2022-05-17 at 12 32 53](https://user-images.githubusercontent.com/54955148/168792643-ae002f7c-8391-40e8-a6a7-bdc766686e4a.png)

However, replacing port name 'api' everywhere with anything else, e.g. 'example', makes the traffic flow:
```
nginx@dashboard-deploy-75d9988f5b-jjnbj:/$ curl --connect-timeout 5 --head http://api-svc:8080/
HTTP/1.1 200 OK
Server: nginx/1.21.6
Date: Tue, 17 May 2022 10:20:17 GMT
Content-Type: text/html
Content-Length: 615
Last-Modified: Tue, 25 Jan 2022 15:03:52 GMT
Connection: keep-alive
ETag: "61f01158-267"
Accept-Ranges: bytes
```
Traffic going through:
![Screenshot 2022-05-17 at 12 38 53](https://user-images.githubusercontent.com/54955148/168793000-fcf58337-1e04-4d97-91bc-59336f2d6421.png)

This bug was discovered by pure accident. When I replaced 1 node pool with a different one (due to MS making taints set with AKS API non-removable from K8S API, see https://github.com/cilium/cilium/issues/19788) part of our applications broke for no obvious reason. Strange thing is, only the nodes were replaced, everything else remained the same, versions of our apps, Cilium version, k8s version etc.
Further debugging led me to try changing the port name to something other than 'api' which made the network policies functional again. To strengthen this point, network policies were working fine, but broke for no apparent reason just by replacing the node pool. Why exactly replacing the nodes broke policies in this way still remains a mystery. 

One more thing, the bug seems to lie somewhere with the egress rules, our actual api deployment is still happy to receive traffic from Nginx ingress controller by using a named port called 'api' (there are no network policies defined for ingress namespace).
Also, using port numbers instead of names works as well, this is how I triaged our clusters when the bug first popped up.

### Cilium Version

```
❯ cilium version
cilium-cli: 0.11.1 compiled with go1.18.1 on darwin/arm64
cilium image (default): v1.11.3
cilium image (stable): v1.11.5
cilium image (running): v1.11.4
```

### Kernel Version

`5.4.0-1078-azure`

### Kubernetes Version

```
❯ k version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:41:58Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"07959215dd83b4ae6317b33c824f845abd578642", GitTreeState:"clean", BuildDate:"2022-03-30T18:28:25Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
