### ISSUE TITLE
Host firewall: Select nodes based on the pods they have

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#19948]
### Problem
In particular for liveness and readiness probes, it is sometimes useful to be able to define host policies on a node based on the pods that are running on that node. For example, if a pod is expecting readiness probes on port 8080, we may need to define a policy to allow traffic from the host network namespace to that pod on port 8080. We can do this with the following host policy, but it will also allow from any remote node to that pod.
```yaml
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "allow-readiness-probe"
spec:
  nodeSelector: {}
  egress:
  - toEndpoints:
    - matchLabels:
        role: frontend
    toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
```
Ideally we would like to apply the host policy only to the node that hosts the pod.

This use case was initially raised at https://medium.com/@charled.breteche/kubernetes-security-explore-cilium-host-firewall-and-host-policies-de93ea9da38c.

### Proposed Solution
We would have a new `nodeWithEndpointSelector` to be used in place of the `nodeSelector`, to select nodes on which to apply host policies based on the pods they are running.
```yaml
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "allow-readiness-probe"
spec:
  nodeWithEndpointSelector:
  - matchLabels:
      role: frontend
  egress:
  - toEndpoints:
    - matchLabels:
        role: frontend
    toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
```

Implementing this may be a bit tricky because, when we match policy rules against endpoints, we typically only carry the endpoints' security identity, not the node they reside on. See [`getMatchingRules`](https://github.com/cilium/cilium/blob/82c742f2e9fb65fb3fc392c7dcb3b4e22b69c650/pkg/policy/repository.go#L562).
