### ISSUE TITLE
Clarify Cilium policy documentation regarding multiple rules in a spec

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#19956]
A user mentioned on Slack that the docs don't clearly define how multiple rules in a Spec behave:

https://docs.cilium.io/en/stable/policy/intro/#policy-rule

Question explicitly:

As defined in the documentation,  `Ingress` is a list of type `IngressRule`. Are all the rules inside Ingress applied as an AND or OR. So if I define something like:

```
ingress:
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
    - fromEntities:
        - health
```

How is this translated to behaviour?:
1. `requests from entity health are allowed. Also, requests from endpoints from the kube-system namespace are allowed.`, or
1. `requests from entity health in the namespace kube-system are allowed`

The answer is (1).

We could improve the policy docs to clarify these topics, and potentially also update the `type Rule` definition in the codebase to include this detail in the comment above the fields.
