### ISSUE TITLE
CFP: [Helm chart] Allow configuration of serviceMonitor interval 

### ISSUE THREAD

**Issue by RixTmobilender** [cilium/cilium#19978]
## Cilium Feature Proposal

**Describe the feature you'd like**

I want to configure the scrape interval for the helm chart's included ServiceMonitor, I want to raise the seconds a bit to lower my costs.
This affects the operator, agent and hubble deployments

**(Optional) Describe your proposed solution**

Allow an extra option "interval" for the serviceMonitor blocks in `values.yaml` as such:
```
serviceMonitor:
  enabled: false
  labels: {}
  annotations: {}
  interval: "10s"
```
