### ISSUE TITLE
Add support for "any" port/protocol in ingress rules

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#1997]
@tgraf I have a use case where I need to specify an L7 rule for some ports and allow L4 traffic to all the other ports. The policy rule could look something like this:

```
ingress:
- fromEndpoints:
  - matchLabels: {}
  toPorts:
  - ports:
    - port: "80"
      protocol: TCP
    rules:
      http:
      - method: ".*"
        path: ".*"
  - ports:
    - port: any
      protocol: any 
```

**Comment by ianvernon** [comment]
The closest our current policy implementation would be the following: 

```
ingress:
- fromEndpoints:
  - matchLabels: {}
  toPorts:
  - ports:
    - port: "80"
      protocol: TCP
    rules:
      http:
      - method: ".*"
        path: ".*"
  - ports:
    - port: any
      protocol: any 
- fromEndpoints:
  - matchLabels: {}
```

This would allow all traffic from all endpoints, but traffic on port 80 will be redirected  through the proxy (with no restrictions on L7). All other traffic (not on port 80) would be allowed at L3 and would not go through the proxy. 

Given that Cilium's policy model is whitelisted based, allowing all traffic at L3 but restricting on L7 isn't really feasible, because punching a hole at L3 widens up all traffic at L7. This means that you can't really restrict at L7 from all endpoints unless we allowed port ranges in Cilium policy (i.e., 0-79,81-63355) to allow traffic.
