### ISSUE TITLE
CFP: nonMasqueradeCIDRs configuration added to the helm chart.

### ISSUE THREAD

**Issue by alphabet5** [cilium/cilium#20051]
## Cilium Feature Proposal

It would be nice if nonMasqueradeCIDRs could be configured/managed with the helm chart instead of deploying a separate manifest.

I think it would make sense to add it to the ipMasqAgent section in values. Even as a multi-line scalar.

```yaml
ipMasqAgent:
  enabled: true
  config: |
    nonMasqueradeCIDRs:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    masqLinkLocal: false
```

or

```yaml
ipMasqAgent:
  enabled: true
  config:
    nonMasqueradeCIDRs:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    masqLinkLocal: false
```
