### ISSUE TITLE
CFP: Cilium-native multi-homing

### ISSUE THREAD

**Issue by tklauser** [cilium/cilium#20129]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

No, it's a new feature.

**Describe the feature you'd like**

In Kubernetes each pod typically only has one network interface (apart from a loopback). Cilium-native multi-homing would allow to attach additional network interfaces to pods. This is similar to how the [Multus CNI](https://github.com/k8snetworkplumbingwg/multus-cni) allows to attach multiple network interfaces to pods. However, in contrast to using Multus, Cilium-native multi-homing would rely on Cilium CNI as the only CNI being installed.

The feature should offer support for all existing Cilium datapath features, in particular: network policies, observability, datapath acceleration, and service discovery. The developer experience should be simple and in line with the developer experience that Cilium delivers today.

**(Optional) Describe your proposed solution**

tbd

**Comment by vincentmli** [comment]
is this feature plan to be able  attach SR-IOV VF to pod ?

**Comment by tklauser** [comment]
> is this feature plan to be able attach SR-IOV VF to pod ?

@vincentmli I'm not very familiar with SR-IOV VF specifically. This feature should work work with any type of network interfaces supported by the node, as it would be implemented using routes. However, it will not take care of setting up or configuring interface-specific parameters (e.g. SR-IOV VF).

**Comment by vincentmli** [comment]
https://github.com/k8snetworkplumbingwg/multus-cni and 
 https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin seems work together for SR-IOV,  just curious if Cilium CNI could replace the role of  multus-cni here  :)

**Comment by vincentmli** [comment]
@brb I see, thanks! I am just curious since the company I work for use Multus to attach SR-IOV or FPGA/smartNIC provisioned interface to pod for high speed packet processing

**Comment by anupamdialpad** [comment]
Is there a plan to support network policy on the additional network interfaces with this feature?

**Comment by brb** [comment]
@anupamdialpad Yes, the netpols are supported.

**Comment by ntoofu** [comment]
Which packets received by a node are transferred to the additional interface in a pod? I am wondering if this feature is useful when some pods need to receive all packets received on a node's dedicated interface regardless of their destination IP address.

**Comment by cyclinder** [comment]
We have had some recent practice at this point. In a cluster with cilium installed (we call it `default-cni`), we use `multus` and have the flexibility to attach additional network interfaces to pods, such as `macvlan` or `sriov-cni`.

And we have developed two underlay plugins, The `router` and `veth` plugin (Please see https://github.com/spidernet-io/cni-plugins).

These plugins help us set some policy routes in Pod, The router plugin controls the forwarding of packets from different NICs through policy route. east-west traffic is forwarded from eth0(from cilium) and north-south traffic is forwarded from eth1(macvlan or sriov). The `Router` plugin moves all routes from the `eth0` in the pod to table 100 and keeps the routes from the `eth1` in the main table. 

When Pods access a target in the cluster (a cilium pod or a clusterIP), they look up table 100, and the packets match the route in table 100 and are then forwarded out of eth0. When accessing targets outside the cluster, they match the default route in the main table and are forwarded out of eth1.

**Comment by rajendrakumara** [comment]
Any idea when this feature will be available multi home in cilium

**Comment by brb** [comment]
Most likely that the first version will land in v1.14.

**Comment by 0dragosh** [comment]
Is this still due in 1.14?

**Comment by seastco** [comment]
any update? would love to have this

**Comment by tklauser** [comment]
No updates as v1.15 planning hasn't started, so this has not been decided yet.

**Comment by maxpain** [comment]
+1. Multus is trash, there is no even Helm chart, also the last version (v4) doesn't work properly with Cilium.

**Comment by 0dragosh** [comment]
> +1. Multus is trash, there is no even Helm chart, also, the last version (v4) doesn't work properly with Cilium. [k8snetworkplumbingwg/multus-cni#1077](https://github.com/k8snetworkplumbingwg/multus-cni/issues/1077)

I want this as a first class capability in cilium since it's already got everything and the kitchen sink, _but_ you are wrong, multus works just fine with ciilum 1.14 rc0. Here's my flux HelmRelease for multus:

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multus
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: multus
      version: 5.0.2
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
      interval: 30m
  values:
    image:
      repository: ghcr.io/k8snetworkplumbingwg/multus-cni
      tag: v4.0.1-thick

    cni:
      image:
        repository: ghcr.io/angelnu/cni-plugins
        tag: 1.3.0

      paths:
        config: /etc/cni/net.d
        bin: /opt/cni/bin

    resources:
      requests:
        cpu: 5m
        memory: 70M
      limits:
        memory: 150M

    hostPaths:
      netns: /var/run/netns

```
