### ISSUE TITLE
toFQDNs broken when using CoreDNS' autopath

### ISSUE THREAD

**Issue by CallMeFoxie** [cilium/cilium#20191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using Cilium in combination with CoreDNS' `autopath` feature, `toFQDNs` is broken. How?

When you set egress enable to `somedomain.tld`, the `search` in pod will try to search through `somedomain.tld.svc.cluster.local` BEFORE searching for `somedomain.tld`, to which the CoreDNS will reply as `somedomain.tld.svc.cluster.local CNAME somedomain.tld` and the rest of the chain. However the `fqdn cache` with allowed domains gets populated only with the `somedomain.tld.svc.cluster.local` meaning that the original `somedomain.tld` is not accessible, at least that's how I understood it while debugging.

Is there any reason to not allow the whole CNAME chain in fqdn cache?

Cilium version 1.10.8 (we are in the process of porting our environment to 1.11 branch)

Ashley

### Cilium Version

1.10.8

### Kernel Version

Linux node.somedomain.tld 5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.22.8

### Relevant log output

```shell
-> Response dns to 1 ([k8s:ftxt=metasearch k8s:io.cilium.k8s.namespace.labels.xxx/realm=stable k8s:io.cilium.k8s.policy.serviceaccount=default k8s:statefulset.kubernetes.io/pod-name=metasearch-0 k8s:io.cilium.k8s.namespace.labels.xxx/realm=stable k8s:io.cilium.k8s.namespace.labels.xxx/department=technicke_oddeleni k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=infraf-test k8s:io.cilium.k8s.policy.cluster=tt-k8s4-ko k8s:io.cilium.k8s.namespace.labels.xxx/owner=infraf k8s:io.cilium.k8s.namespace.labels.xxx/contract=scif k8s:io.kubernetes.pod.namespace=infraf-test]) from 0 ([reserved:host]), identity 3446194->1, verdict Forwarded DNS Proxy: fhdfs-nn1.yyy.svc.cluster.local. A TTL: 78 Answer: '10.249.9.46' CNAMEs: fhdfs-nn1.yyy.,fvirtvidbase1.yyy.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment]
@CallMeFoxie Could you point out what the exact issue you are having is? What exactly about `toFQDNs` is broken?

It is true that Cilium doesn't map all CNAMEs with the IPs of the underlying A / AAAA records in the FQDN cache. But I don't think this is an issue, so let's leave that aside for now and focus on the `toFQDNs` policy aspect.

In my quick testing, I deployed the following service and policy, and traffic is flowing.

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "tofqdn-dns-visibility"
spec:
  endpointSelector:
    matchLabels:
      name: netperf
  egress:
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
      toPorts:
      - ports:
        - port: "53"
          protocol: ANY
        rules:
          dns:
          - matchPattern: "*"
    - toFQDNs:
      - matchPattern: "*.*.svc.cluster.local"
```

```yaml
apiVersion: v1
kind: Service
  labels:
    app: github
  name: github
spec:
  externalName: github.com
  selector:
    app: github
  type: ExternalName
```

**Comment by CallMeFoxie** [comment]
Hello :)

Basically:

1. I have a rule:
```
  - toFQDNs:
    - matchName: fhdfs-nn1.xxx
    toPorts:
    - ports:
      - port: "50070"
        protocol: TCP
```

which should allow me to go to `fhdfs-nn1.xxx`

But when it tries to open `fhdfs-nn1.xxx` it goes through `search` on the POD and finds `fhdfs-nn1.xxx.svc.cluster.local` first. This DNS request goes through DNS Proxy and the underlying DNS server replies with `fhdfs-nn1.xxx.svc.cluster.local CNAME fhdfs-nn1.xxx` and the rest of the chain. At that point the DNS stops because it successfuly resolved the `fhdfs-nn1.xxx(+ search)` but only `fhdfs-nn1.xxx.svc.cluster.local` goes into cache, even though I asked and enabled access to `fhdfs-nn1.xxx` which doesn't work because of it.

Better explanation? I can try some other way :)
