### ISSUE TITLE
Accessing service endpoint behind tailscale subnet router.

### ISSUE THREAD

**Issue by ileixe** [cilium/cilium#20192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm trying to connect `Service` endpoint behind the Tailscale subnet router client like below

---

```
Client (Tailscale client) -- Tailscale pod (Tailscale subnet router client) -- Service -- Pod  
```

- Client (100.114.185.64/32)
My laptop

Tailscale turned on 
```
$ sudo tailscale up --login-server https://controlplane.tailscale.com --accept-routes
$ tailscale status
100.114.185.64  yan                  yan@         linux   -
100.86.164.72   mgmt00               infra@       linux   -
100.80.155.114  private-mgmt-002     yan@         linux   active; relay "tok", tx 366612 rx 609964

```

- Tailscale pod (100.80.155.114/32)

```
pod$ cat tailscale.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tailscale
  name: tailscale
spec:
  containers:
  - name: tailscale
    image: tailscale/tailscale
    command:
      - "sleep"
      - "604800"
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_MODULE
    volumeMounts:
    - mountPath: /var/lib/tailscale
      name: data
    - mountPath: /dev/net/tun
      name: devnet
  hostNetwork: true
  dnsPolicy: ClusterFirst
  volumes:
  - name: data
    hostPath:
      path: /var/lib/tailscale
  - name: devnet
    hostPath:
      path: /dev/net/tun
```
Tailscale turned on

```
tailscale up --advertise-routes=172.0.0.0/16,10.96.0.0/12  # Pod network CIDR, Service network CIDR
```

- Service (Cluster IP: 10.111.207.98)

```
pod$ k get svc
NAME         TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)        AGE
httpbin      ClusterIP      10.111.207.98   <none>          8000/TCP       139m
```

- Pod (172.0.2.217) 
  - httpbin application 

---
I have networks

Pod network CIDR: 172.0.0.0/16
```
pod$ cilium  config view | grep ipv4-cidr
cluster-pool-ipv4-cidr                         172.0.0.0/16
```

Service network CIDR: 10.96.0.0/12

```
pod$ kubectl cluster-info dump | grep -m 1 service-cluster-ip-range

                            "--service-cluster-ip-range=10.96.0.0/12",
```

---

At the client (my laptop), I want to access Pod via Service endpoint so

```
curl 172.25.100.27:8080
```

it reached Tailscale pod, but did not reach httpbin Pod. I read the issue from https://github.com/cilium/cilium/issues/16266 and follow the solution from there (adding Pod network CIDR) but it made no difference. 

I'm not sure what happened internally so any guide to inspect would be appreicated.

 

### Cilium Version

```
$ cilium version
cilium-cli: v0.9.3 compiled with go1.17.3 on linux/amd64
cilium image (default): v1.10.5
cilium image (stable): v1.11.5
cilium image (running): v1.11.2
```

### Kernel Version

/ # uname -r
5.4.0-110-generic

### Kubernetes Version

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:18:48Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.24) exceeds the supported minor version skew of +/-1

```

### Sysdump

https://drive.google.com/file/d/1P8BIc3JHlb-70xa6nTcAFioDfmwy_LOK/view?usp=sharing

### Anything else?

Issue that I referenced: https://github.com/cilium/cilium/issues/16266

Same issue report from tailscale side: https://forum.tailscale.com/t/tailscale-proxy-in-k8s-with-cilium-works-with-pod-not-with-svc/1910

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
