### ISSUE TITLE
Clear `CNP.Status.Nodes` field if node status updates have been disabled

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#20231]
`CiliumNetworkPolicies` contain a `status.nodes` field where we used to track the enforcement status of the policy for each node, e.g.

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: example-policy
  namespace: default
spec:
  egress:
  - toEntities:
    - cluster
  endpointSelector: {}
status:
  nodes:
    kind-worker-1:
      enforcing: true
      lastUpdated: "2020-06-08T15:56:41Z"
      localPolicyRevision: 121
      ok: true
    kind-worker-2:
      enforcing: true
      lastUpdated: "2020-06-08T15:58:37Z"
      localPolicyRevision: 121
      ok: true
    kind-worker-3:
      enforcing: true
      lastUpdated: "2020-06-08T15:55:51Z"
      localPolicyRevision: 121
      ok: true
```

However, in [Cilium v1.8](https://docs.cilium.io/en/v1.8/operations/upgrade/#upgrade-notes) we disabled this feature by default for scalability reasons. Users who ran v1.8 or earlier were also encouraged to turn it off, so most users today run with `disable-cnp-status-updates: "true"` in their ConfigMap, so the field is not updated anymore. However, if they previously had the status updates enabled, then the field still contains the last status of each node when the feature was turned off.

There is a garbage collector in the operator which removes nodes from the list if the corresponding node has been removed from the cluster:

https://github.com/cilium/cilium/blob/5a4d26164998288d0e6bc542f3abeaffe6254f70/operator/cilium_node.go#L315-L318

But the status of _alive_ nodes is left untouched. If users have turned off the node status, we should add a mechanism in the operator which clears the node status field of all CNPs and CCNPs, as keeping the stale node status can consume quite a lot of memory in large clusters.

Note that the above `runCNPNodeStatusGC` is only executed if `synchronize-k8s-nodes=true` and kvstore is enabled. We should however also clear the CCNP/CNP field even if `synchronize-k8s-nodes=false`
