### ISSUE TITLE
Cilium Pod OOM constantly

### ISSUE THREAD

**Issue by Thearas** [cilium/cilium#20597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium Pod OOM constantly, the status:

```yaml
⚡ kdp cilium-4h2hk
...
Containers:
  cilium-agent:
    Container ID:  containerd://2d716e98dd4c996151b7b6d067daecb2ee79926cf771e39d56a1623710629e41
    Image:         quay.io/cilium/cilium:v1.11.3
    Image ID:      quay.io/cilium/cilium@sha256:cb6aac121e348abd61a692c435a90a6e2ad3f25baa9915346be7b333de8a767f
    Port:          9090/TCP
    Host Port:     9090/TCP
    Command:
      cilium-agent
    Args:
      --config-dir=/tmp/cilium/config-map
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 20 Jul 2022 17:24:10 +0800
      Finished:     Wed, 20 Jul 2022 17:24:14 +0800
    Ready:          False
    Restart Count:  7
    Limits:
      cpu:     500m
      memory:  500M
    Requests:
      cpu:      100m
      memory:   64M
...
Events:
  Type     Reason     Age                 From     Message
  ----     ------     ----                ----     -------
  Normal   Pulled     15m (x4 over 28h)   kubelet  Container image "quay.io/cilium/cilium:v1.11.3" already present on machine
  Normal   Created    15m (x4 over 28h)   kubelet  Created container cilium-agent
  Normal   Started    15m (x4 over 28h)   kubelet  Started container cilium-agent
  Warning  Unhealthy  14m (x17 over 28h)  kubelet  Startup probe failed: Get "http://127.0.0.1:9876/healthz": dial tcp 127.0.0.1:9876: connect: connection refused
  Warning  BackOff    42s (x82 over 15m)  kubelet  Back-off restarting failed container
```

When I delete this Pod manually, it restarts successfully, but the OOM crash will occur again after few hours.

### Cilium Version

cilium image (running): v1.11.3

### Kernel Version

Linux 10.2.12.7 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: v1.21.12

### Sysdump

I only collect the node that has cilium pod OOM.

[cilium-sysdump-20220720-172531.zip](https://github.com/cilium/cilium/files/9148454/cilium-sysdump-20220720-172531.zip)

### Relevant log output

See Sysdump above.

### Anything else?

```log
⚡ cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         2 errors
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         OK
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

DaemonSet         cilium             Desired: 22, Ready: 21/22, Available: 21/22, Unavailable: 1/22
Deployment        cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Deployment        hubble-relay       Desired: 1, Ready: 1/1, Available: 1/1
Deployment        hubble-ui          Desired: 1, Ready: 1/1, Available: 1/1
Containers:       cilium             Running: 22
                  hubble-relay       Running: 1
                  hubble-ui          Running: 1
                  cilium-operator    Running: 1
Cluster Pods:     151/284 managed by Cilium
Image versions    cilium-operator    quay.io/cilium/operator:v1.11.3: 1
                  cilium             quay.io/cilium/cilium:v1.11.3: 22
                  hubble-relay       quay.io/cilium/hubble-relay:v1.11.3: 1
                  hubble-ui          quay.io/cilium/hubble-ui:v0.7.3: 1
                  hubble-ui          quay.io/cilium/hubble-ui-backend:v0.7.3: 1
                  hubble-ui          docker.io/envoyproxy/envoy:v1.14.5: 1
Errors:           cilium             cilium          1 pods of DaemonSet cilium are not ready
                  cilium             cilium-4h2hk    unable to retrieve cilium status: unable to upgrade connection: container not found ("cilium-agent")
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
