### ISSUE TITLE
CFP: IngressController in tunnel: disabled mode

### ISSUE THREAD

**Issue by ghost** [cilium/cilium#20634]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature request for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your feature request related to a problem?**

I am trying to implement ingresscontroller to my existing cilium setup (DSR mode, tunnel disabled, kube-proxy to strict and installNoConntrackIptablesRules enabled), it is not working.

For loadbalancer, I am using metallb latest version with layer2 arp configuration.

Full values:

```
---
cluster:
  name: test
  id: 1

ingressController:
  # -- Enable cilium ingress controller
  # This will automatically set enable-envoy-config as well.
  enabled: true

egressGateway:
  enabled: true

securityContext:
  # runAsUser: 0
  privileged: true
  extraCapabilities:
    # Allow discretionary access control (e.g. required for package installation)
    - DAC_OVERRIDE
    # Allow to set Access Control Lists (ACLs) on arbitrary files (e.g. required for package installation)
    - FOWNER
    # Allow to execute program that changes GID (e.g. required for package installation)
    - SETGID
    # Allow to execute program that changes UID (e.g. required for package installation)
    - SETUID

k8sServiceHost: "192.168.1.156"
k8sServicePort: "6443"
identityAllocationMode: crd
kubeProxyReplacement: strict
enableK8sEndpointSlice: true
installNoConntrackIptablesRules: true
bandwidthManager:
  enabled: true
  bbr: false
tunnel: disabled
autoDirectNodeRoutes: true
ipv4NativeRoutingCIDR: 10.0.0.0/8
cni:
  install: true
  #exclusive: false
ipam:
  mode: "kubernetes"
bpf:
  masquerade: true
ipMasqAgent:
  enabled: true
socketLB:
  enabled: true
  hostNamespaceOnly: true
hostPort:
  enabled: true
nodePort:
  enabled: true
externalIPs:
  enabled: true
hostFirewall:
  enabled: true
loadBalancer:
  mode: dsr
#  acceleration: native
containerRuntime:
  integration: containerd

hubble:
  enabled: true
  metrics:
    #serviceMonitor:
    #  enabled: true
    enabled:
    - dns:query;ignoreAAAA
    - drop
    - tcp
    - flow
    - icmp
    - http
  ui:
    enabled: true

  relay:
    # -- Enable Hubble Relay (requires hubble.enabled=true)
    enabled: true
prometheus:
  enabled: true
  #serviceMonitor:
  # enabled: true
operator:
  enabled: true
  replicas: 1
  prometheus:
    enabled: true
    #serviceMonitor:
    #  enabled: true
```

Whenever I change tunnel mode to vxlan, ingresscontroller is working fine.

**Describe the feature you'd like**

Is IngressController actually supported if running it with cilium set to DSR? Thank you
