### ISSUE TITLE
CFP: IngressController configurable cloud provider related LoadBalancer

### ISSUE THREAD

**Issue by therapy-lf** [cilium/cilium#20646]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

Cilium adds ingress service without any option to pass additional annotations to it. These annotations are used for various cloud and other controllers. For instance, configuring AWS LoadBalancer or cert-manager:
 
```
service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "TCP"
service.beta.kubernetes.io/aws-load-balancer-internal: "true"
service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
```

Also, there's no way to re-use the same cloud LoadBalancer for multiple ingress services. It'd be great to have just a few types(e.g. public and internal) LoadBalancers for different purposes shared across multiple services. Currently, for each service controller runs a separate service backed by a dedicated LoadBalancer.

Controller should respect ingress object annotations and pass its annotations to the ingress service:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "TCP"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
```

**(Optional) Describe your proposed solution**

I see a few options:
- have an option to create a static service used for cilium ingress and disable service auto-creation
- pass all annotations from the ingress object to the auto-created ingress service
