### ISSUE TITLE
no outgoing traffic after the Cilium agent has been stopped

### ISSUE THREAD

**Issue by phin1x** [cilium/cilium#20667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We are in the process of migrating our cni to cilium. When cilium is running, everything works as expected. But when the Cilium agent is stopped (e.g. when the agent is restarted), all outgoing packets are discarded somewhere. When I try to run curl, I get a connection timeout error. Kubelet has lost its connection to the API server. tcpdump shows only incoming packets. The only way to bring the node back online is a hard reset.

eBPF is still very new to me. does anyone have any idea how i can debug the problem or am I missing something here? 

these are my helm values:
```
k8sServiceHost: 192.168.10.10
k8sServicePort: 6443

cluster:
  name: test
  id: 0

agent: true
name: cilium
# rollOutCiliumPods: true

autoDirectNodeRoutes: true

tunnel: disabled

ipv4NativeRoutingCIDR: 172.19.0.0/16

annotateK8sNode: true

bpf:
  clockProbe: true
  preallocateMaps: true
  masquerade: true
  hostLegacyRouting: false
  tproxy: true

containerRuntime:
  integration: crio

enableK8sEndpointSlice: true
enableCiliumEndpointSlice: false

hostFirewall:
  enabled: true

nodePort:
  enabled: true

externalIPs:
  enabled: true

hubble:
  enabled: true

  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - http

  tls:
    enabled: true
    auto:
      enabled: true
      method: helm
      
  relay:
    enabled: true

    rollOutPods: true

  ui:
    enabled: true

    standalone:
      enabled: false

    rollOutPods: true

    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: http,https
        traefik.ingress.kubernetes.io/router.middlewares: https-redirect-permanent@file,basic-auth@file
      hosts:
        - hubble.cluster.intern
      tls:
        - hosts:
          - hubble.cluster.local

ipam:
  mode: "kubernetes"

ipv4:
  enabled: true

ipv6:
  enabled: false

k8s:
  requireIPv4PodCIDR: true
  requireIPv6PodCIDR: false

kubeProxyReplacement: "strict"

loadBalancer:
  mode: dsr
  algorithm: maglev
#  acceleration: native

l2NeighDiscovery:
  enabled: true
  refreshPeriod: "30s"

l7Proxy: true

enableIPv4Masquerade: true
enableIPv6Masquerade: false

bandwidthManager:
  enabled: true

egressGateway:
  enabled: true

# enable later
monitor:
  enabled: false

prometheus:
  enabled: true
  serviceMonitor:
    enabled: false

proxy:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: false

remoteNodeIdentity: true

operator:
  rollOutPods: true

  prometheus:
    enabled: true
    serviceMonitor:
      enabled: false

```

### Cilium Version

v1.12.0

### Kernel Version

5.14.21

### Kubernetes Version

1.23.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
