### ISSUE TITLE
BGP: Announcing IPv6 causes 100% cpu on cilium-agent/containerd and cilium completely hangs.

### ISSUE THREAD

**Issue by vosdev** [cilium/cilium#20713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened!

```
root @ cilium1 # cilium config view  | grep bgp
bgp-announce-lb-ip                             true
enable-bgp                                     true
enable-bgp-control-plane                       false
```

When I stick solely to IPv4, the addresses are announced just fine via BGP and accepted by my router.

When I add IPv6 address space to the BGP address pool, reload cilium and wait for an ipv6 address to be handed out to a service, cilium-agent/containerd immediately jumps to 100% cpu usage when it does so. Normal usage is 1-2%.
![image](https://user-images.githubusercontent.com/45820840/181773989-02a6ad75-83b3-41a9-b45a-ad0dd2ef3325.png)

When this happens, I get **10-20 THOUSAND** of these log lines **per SECOND**:
`level=info msg="processing new event." component=MetalLBSpeaker.run subsys=bgp-speaker`
```
root @ cilium1 # k logs -n kube-system cilium-7l94f -f | pv --line-mode --rate > /dev/null
16.5k/s]
```

bgp-config:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
      - peer-address: 10.0.1.1
        peer-asn: 64512
        my-asn: 64513
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          #- 2001:db8:3cc4:c::10-2001:db8:3cc4:c::50
          - 10.5.5.10-10.5.5.50
```

MetalLB only recently gained support for IPv6, is an outdated version included with cilium?

### Cilium Version

```
root @ cilium1 # cilium version
cilium-cli: v0.12.0 compiled with go1.18.4 on linux/amd64
cilium image (default): v1.12.0
cilium image (stable): v1.12.0
cilium image (running): v1.12.0
```

Cilium installed with:
```
cilium install --version=v1.12.0 --kube-proxy-replacement strict --helm-set-string=k8sServiceHost=cilium1.example.com,k8sServicePort=6443,ipv6.enabled=true,ipam.mode=kubernetes,enableIPv6Masquerade=false,externalIPs=true,bgp.enabled=true,bgp.announce.loadbalancerIP=true
```

### Kernel Version

`Linux cilium1 5.15.0-41-generic #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:41Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

I get an HTTP 422 when I attempt to upload the sysdump. File size too big, 25MB is allowed, the sysdump is 32MB.

### Relevant log output

```shell
`level=info msg="processing new event." component=MetalLBSpeaker.run subsys=bgp-speaker`
^ 20.000 times per second
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ldelossa** [comment]
Hello @vosdev 

Currently, we do not plan on supporting IPv6 with out MetalLB feature set. 

Instead we have migrated toward the new "BGP Control Plane" feature set which properly supports IPv6. See: https://docs.cilium.io/en/v1.12/gettingstarted/bgp-control-plane/#cilium-bgp-control-plane

The issue you see here is because the MetalLB fork we use does not support IPv6 and we do not plan on patching this functionality in moving forward. 

Still, the issue in event processing should not cause this hot loop to occur. I will place a fix for this.

**Comment by vosdev** [comment]
Sweet, I'll immediately start with a rewrite of my configuration!

**Comment by ldelossa** [comment]
@vosdev please be aware, the ability to announce LoadBalancer IPs via BGP has not been ported over to the BGP Control Plane feature set yet.

**Comment by vosdev** [comment]
And handing out External IPs will stay a MetalLB feature or will this also move to the control plane? 

So this part of the MetalLB config:
```
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          #- 2001:db8:3cc4:c::10-2001:db8:3cc4:c::50
          - 10.5.5.10-10.5.5.50
```
