### ISSUE TITLE
Cilium Health Endpoint does not properly use IPv6 for HTTPProbe

### ISSUE THREAD

**Issue by jccepeda** [cilium/cilium#20796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We are using Cilium on a cluster with IPv6 only (and without kube-proxy among other things).

Upgraded cilium from `1.11.1` to `1.11.7` (before `1.12.0`). However, after upgrade, cilium health endpoint is unable to retrieve `httpProbe` IPv6, with the following event message:

```
Get "http://<nil>:4240/hello": dial tcp: lookup <nil>: no such host
```

No problem with previous version 1.11.6.

### Cilium Version

v1.11.7

### Kernel Version

`5.13.0-52-generic #59~20.04.1-Ubuntu`

### Kubernetes Version

v1.23.9

### Relevant log output

```shell
level=info msg="Removed endpoint" containerID= datapathPolicyRevision=2 desiredPolicyRevision=2 endpointID=3909 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3502 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3502 identityLabels="reserved:health" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3502 identity=4 identityLabels="reserved:health" ipv4= ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3502 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
```

### Anything else?

Problem can be reproduced using Kind (`v0.14.0`) and Helm (`v3.9.2`).

Kind `config.yaml`:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.23.6@sha256:b1fa224cc6c7ff32455e0b1fd9cbfd3d3bc87ecaa8fcb06961ed1afb3db0f9ae
- role: worker
  image: kindest/node:v1.23.6@sha256:b1fa224cc6c7ff32455e0b1fd9cbfd3d3bc87ecaa8fcb06961ed1afb3db0f9ae
- role: worker
  image: kindest/node:v1.23.6@sha256:b1fa224cc6c7ff32455e0b1fd9cbfd3d3bc87ecaa8fcb06961ed1afb3db0f9ae
- role: worker
  image: kindest/node:v1.23.6@sha256:b1fa224cc6c7ff32455e0b1fd9cbfd3d3bc87ecaa8fcb06961ed1afb3db0f9ae
networking:
  disableDefaultCNI: true
  kubeProxyMode: "none"
  ipFamily: ipv6
```
Helm command:
```bash
helm install cilium cilium/cilium --version 1.11.7 \
  --namespace kube-system \
  --set kubeProxyReplacement=strict \
  --set k8sServiceHost=kind-control-plane \
  --set k8sServicePort=6443 \
  --set hostServices.enabled=true \
  --set externalIPs.enabled=true \
  --set nodePort.enabled=true \
  --set hostPort.enabled=true \
  --set bpf.masquerade=false \
  --set image.pullPolicy=IfNotPresent \
  --set ipam.mode=kubernetes \
  --set tunnel=disabled \
  --set l7Proxy=false \
  --set ipv4.enabled=false \
  --set ipv6.enabled=true
```

Result:
```
$ helm -n kube-system list
NAME    NAMESPACE       REVISION        UPDATED                                         STATUS          CHART           APP VERSION
cilium  kube-system     1               2022-08-05 14:27:44.025257881 +0200 CEST        deployed        cilium-1.11.7   1.11.7

$ k -n kube-system get ds/cilium
NAME     DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
cilium   4         4         4       4            4           <none>          3m28s

$ cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         4 errors
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         disabled
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

Deployment        cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
DaemonSet         cilium             Desired: 4, Ready: 4/4, Available: 4/4
Containers:       cilium             Running: 4
                  cilium-operator    Running: 2
Cluster Pods:     3/3 managed by Cilium
Image versions    cilium             quay.io/cilium/cilium:v1.11.7@sha256:66a6f72a49e55e21278d07a99ff2cffa7565ed07f2578d54b5a92c1a492a6597: 4
                  cilium-operator    quay.io/cilium/operator-generic:v1.11.7@sha256:0f8ed5d815873d20848a360df3f2ebbd4116481ff817d3f295557801e0b45900: 2
Errors:           cilium             cilium-2v5c7    controller cilium-health-ep is failing since 3s (9x): Get "http://<nil>:4240/hello": dial tcp: lookup <nil>: no such host
                  cilium             cilium-w6hhj    controller cilium-health-ep is failing since 3s (9x): Get "http://<nil>:4240/hello": dial tcp: lookup <nil>: no such host
                  cilium             cilium-r7jls    controller cilium-health-ep is failing since 2s (9x): Get "http://<nil>:4240/hello": dial tcp: lookup <nil>: no such host
                  cilium             cilium-rm7dx    controller cilium-health-ep is failing since 2s (9x): Get "http://<nil>:4240/hello": dial tcp: lookup <nil>: no such host
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
