### ISSUE TITLE
Can not use BGP to announce LoadBalancer IP and Pod CIDR simultaneously.

### ISSUE THREAD

**Issue by Huweicai** [cilium/cilium#20836]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

I want to use BGP to announce my Pod CIDR and LoadBalancer IP, so I've set these two options in config-map `cilium-config` to true
```
  bgp-announce-lb-ip: "true"
  bgp-announce-pod-cidr: "true"
  ipam: "kubernetes"
  k8s-require-ipv4-pod-cidr: "true"
```
And my bgp-config looks like below:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
      - peer-address: 198.18.255.1
        peer-asn: 65535
        my-asn: 64549
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          - 10.229.64.0/20
        bgp-advertisements:
          - aggregation-length: 28
``` 

I found that PodCIDR announcement works well first, but after I created a LoadBalancer the PodCIDR announcement suddenly crashed while the LoadBalancer can continue to work.

I've restarted the agent for many times, still can not work.

Then I dumped the traffic, found that the PodCIDR announcement was withdrew.

![image](https://user-images.githubusercontent.com/29170746/183623134-68e78f90-f30b-41de-b8e0-4b00cbd28b66.png)

`10.229.193.128/26` is the PodCIDR of that node.

Is there anything wrong with my config or cilium actually do not support them work simultaneously.

### Cilium Version

v1.11.6

### Kernel Version

5.15.58 x86_64

### Kubernetes Version

v1.22.8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
