### ISSUE TITLE
Cilium fails to start with "RTNETLINK answers: Operation not supported"

### ISSUE THREAD

**Issue by dirien** [cilium/cilium#20858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Architecture: x86_64

I installed cilium via helm chart into our k3s cluster.

helm values:

```yaml
containerRuntime:
  integration: containerd
  socketPath: /var/run/k3s/containerd/containerd.sock

hubble:
  tls:
    enabled: false
  relay:
    enabled: true
  ui:
    enabled: true

ipam:
  mode: "kubernetes"

operator:
  replicas: 1

kubeProxyReplacement: disabled
```

Unfortunatly cilium want start and fail with following logs:

```bash
level=warning msg="+ tc qdisc replace dev cilium_vxlan clsact" subsys=datapath-loader
level=warning msg="RTNETLINK answers: Operation not supported" subsys=datapath-loader
level=warning msg="+ true" subsys=datapath-loader
level=warning msg="++ grep -v 'pref 1 bpf chain 0 $\\|pref 1 bpf chain 0 handle 0x1'" subsys=datapath-loader
level=warning msg="++ tc filter show dev cilium_vxlan ingress" subsys=datapath-loader
level=warning msg="RTNETLINK answers: Operation not supported" subsys=datapath-loader
level=warning msg="Dump terminated" subsys=datapath-loader
level=warning msg="+ '[' -z '' ']'" subsys=datapath-loader
level=warning msg="+ cilium bpf migrate-maps -s bpf_overlay.o" subsys=datapath-loader
level=warning msg="+ tc filter replace dev cilium_vxlan ingress prio 1 handle 1 bpf da obj bpf_overlay.o sec from-overlay" subsys=datapath-loader
level=warning msg="RTNETLINK answers: Operation not supported" subsys=datapath-loader
level=warning msg="We have an error talking to the kernel" subsys=datapath-loader
level=warning msg="+ cilium bpf migrate-maps -e bpf_overlay.o -r 1" subsys=datapath-loader
level=warning msg="+ return 1" subsys=datapath-loader
level=fatal msg="Error while creating daemon" error="error while initializing daemon: failed while reinitializing datapath: exit status 1" subsys=daemon
```

### Cilium Version

1.12.0

### Kernel Version

5.15.0-1013-kvm #16-Ubuntu SMP Fri Jul 1 21:19:48 UTC 2022

### Kubernetes Version

v1.24.3+k3s1

### Relevant log output

```shell
see above
```

### Anything else?

When I upgrade the kernel (by hand) to version: 5.18.0-051800-generic, everything is working fine again.

Unfortunatly, we are using the jammy cloud image and we don't want to update the kernel by ourself.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
