### ISSUE TITLE
 [sig-network] Networking should check kube-proxy urls test failing with KPR strict mode

### ISSUE THREAD

**Issue by tamilmani1989** [cilium/cilium#20888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Creating this issue to find out if this testcase is expected fail with KPR strict mode or something wrong with my environment. Enabled kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256.

**Error:**

<failure message="Aug 12 09:44:22.844: Timed out in 30s: failed executing cmd curl -o /dev/null -i -q -s -w %{http_code} --connect-timeout 1 http://localhost:10249/proxyMode in nettest-4806/host-test-container-pod:

+ curl -o /dev/null -i -q -s -w '%!{(MISSING)http_code}' --connect-timeout 1 http://localhost:10249/proxyMode
    command terminated with exit code 7

**Config change from default:**

```
ipam:
  mode: "delegated-plugin"
tunnel: disabled
endpointRoutes:
  enabled: true
extraArgs:
  - --local-router-ipv4=169.254.23.0
ipv4NativeRoutingCIDR: 10.0.0.0/16
enableIPv4Masquerade: false
installIptablesRules: true
l7Proxy: false
kubeProxyReplacement: strict
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
hubble:
  enabled: false
endpointHealthChecking:
  enabled: false

```

**Kubetest cmd:**

`KUBECONFIG=<kubeconfig_file>  kubetest2  --test ginkgo --   --focus-regex "should check kube-proxy urls"   --skip-regex "\[Slow\]|\[Serial\]|\[Flaky\]|\[Feature:(Networking-IPv6|Example|Federation|PerformanceDNS|ProxyTerminatingEndpoints)\]|LB.health.check|LoadBalancer|load.balancer|GCE|DualStack|NetworkPolicy"`

### Cilium Version

1.12.0

### Kernel Version

5.4.0-1086-azure

### Kubernetes Version

1.22.11

### Anything else?

whats the difference between cilium healthz endpoint listening on 9879 (in liveness probe) and   kubeProxyReplacementHealthzBindAddr healthz endpoint? confused if cilium agent has two healthz endpoints?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
