### ISSUE TITLE
CFP: Support TLS (HTTPS) backends and TLS passthrough on Cilium Ingress

### ISSUE THREAD

**Issue by eyanulis** [cilium/cilium#20960]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

Follow-up from Slack thread found [here](https://cilium.slack.com/archives/C53TG4J4R/p1660718164559439). In short, while Cilium's `Ingress` controller has full support for TLS _frontends_, it does not currently appear to have support for TLS _backends_.

There exist some Kubernetes services that will serve HTTPS connections from the pod itself. An example of this is the Ceph Dashboard from Rook, which (if configured) will generate and serve a self-signed certificate on the dashboard port.

Attempting to point Cilium's `Ingress` controller at such a backend will not work. The Ingress config is as follows:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: lng1-letsencrypt-clusterissuer
    external-dns.alpha.kubernetes.io/hostname: ceph-dash-lng1.k8s.yanulis.net
  name: rook-ceph-dashboard
  namespace: rook-ceph
spec:
  ingressClassName: cilium
  rules:
  - host: ceph-dash-lng1.k8s.yanulis.net
    http:
      paths:
      - backend:
          service:
            name: rook-ceph-mgr-dashboard
            port:
              name: https-dashboard
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - ceph-dash-lng1.k8s.yanulis.net
    secretName: ceph-dash-ingress-tls
```

(Note that this Ingress _is_ annotated such that cert-manager will issue a certificate for the _frontend_ connection (client to Envoy), but that is not relevant here - this discussion is regarding the connection between Envoy and the _backend_.)

As-is, with the backend pod serving TLS with a self-signed certificate, attempts to reach this `Ingress` from a client will fail with an HTTP 503 and the following error:
```
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

After some digging, it has become clear that Cilium's `Ingress` controller simply does not configure Envoy for TLS upstreams. This can be made to work by manually updating the relevant `CiliumEnvoyConfig` and changing the `Cluster` configuration from this (original):
```
 - '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
    connectTimeout: 5s
    name: rook-ceph/rook-ceph-mgr-dashboard:https-dashboard
    outlierDetection:
      consecutiveLocalOriginFailure: 2
      splitExternalLocalOriginErrors: true
    type: EDS 
    typedExtensionProtocolOptions:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        useDownstreamProtocolConfig:
          http2ProtocolOptions: {}
```
to this (modified - note the addition of a `transportSocket` section:
```
  - '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
    connectTimeout: 5s
    name: rook-ceph/rook-ceph-mgr-dashboard:https-dashboard
    outlierDetection:
      consecutiveLocalOriginFailure: 2
      splitExternalLocalOriginErrors: true
    transportSocket:
      name: envoy.transport_sockets.tls
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
    type: EDS 
    typedExtensionProtocolOptions:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        useDownstreamProtocolConfig:
          http2ProtocolOptions: {}
```

However, no configuration option (annotation, etc) currently appears to exist for the Cilium `Ingress` controller to effect such a change.

My use case as described above is for TLS on both legs of a proxied connection - I am fine with terminating TLS at the "front" of the `Ingress` and then making a separate TLS connection at the "back" of the `Ingress`.
That said, @sayboras on Slack also noted that there is likely a use case for full TLS passthrough (where the client is presented with the same certificate served by the backend pod, instead of a cert served directly from Envoy).

**Describe the feature you'd like**

In `ingress-nginx` terms (which makes for quite a good summary of the above) I would like Cilium's `Ingress` controller to support functionality equivalent to the following:

1. TLS upstreams with two TLS sessions terminated at Envoy, equivalent to `nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"`
2. TLS passthrough, with a single TLS session terminated at the backend pod, equivalent to `nginx.ingress.kubernetes.io/ssl-passthrough`

**(Optional) Describe your proposed solution**

For item 1, an annotation could be created and sufficient code added approximately [here](https://github.com/cilium/cilium/blob/master/operator/pkg/ingress/envoy_config.go#L403-L425) such that the appropriate `transportSocket` parameters are added to the `Cluster` configuration. 

Item 2 will likely be more complex as Envoy's TLS passthrough (and similarly Nginx's) appear to rely on simple L4 proxying rather than processing the connection at L7.
