### ISSUE TITLE
helm chart cgroup.automount.enabled=false option generates invalid manifest

### ISSUE THREAD

**Issue by eburghar** [cilium/cilium#21007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Using helm chart with `--set cgroup.autoMount.enabled=false` generates manifest we can't apply

There are still references to resources not included in the resulting manifest

In cilium DaemonSet

```yaml
    annotations:
        container.apparmor.security.beta.kubernetes.io/mount-cgroup: unconfined
        container.apparmor.security.beta.kubernetes.io/apply-sysctl-overwrites: unconfined
```

in cilium 1.12.0 there also the initcontainer `apply-sysctl-overwrites` but this is now hidden in cilium 1.12.1

### Cilium Version

```
cilium-cli: v0.12.0 compiled with go1.18.4 on linux/amd64
cilium image (default): v1.12.0
cilium image (stable): v1.12.1
cilium image (running): v1.12.0
```

### Kernel Version

Linux flatcar0 5.15.58-flatcar #1 SMP Wed Aug 3 19:35:04 -00 2022 x86_64 Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz GenuineIntel GNU/Linux

### Kubernetes Version

```
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.24.3
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
