### ISSUE TITLE
src ip is 0.0.0.0 when sending out packets to remote endpoints

### ISSUE THREAD

**Issue by jansmets** [cilium/cilium#21042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm trying to redirect traffic to an external endpoint.
Traffic ingress is with metallb v0.13.4 , bgp/frr enabled

Cilium v1.12.0 deployed with helm chart using these parameters:
```
    --namespace=kube-system \
    --set kubeProxyReplacement=strict \
    --set k8sServiceHost=172.22.35.134 \
    --set k8sServicePort=6443 \
    --set l7Proxy=false
```

I have this Service and Endpoint:
```
kind: Service
apiVersion: v1
metadata:
  name: external-svc
spec:
  type: LoadBalancer
  #externalTrafficPolicy: Local
  externalTrafficPolicy: Cluster
  loadBalancerIP: X.Y.35.167
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
kind: Endpoints
apiVersion: v1
metadata:
  name: external-svc
subsets:
  - addresses:
        - ip: X.Y.67.204
    ports:
      - port: 80
        name: http
      - port: 443
        name: https
```

In FRR vtysh, all nodes show :
```
nodeX# show ip bgp
<snip>
   Network          Next Hop            Metric LocPrf Weight Path
*> A.B.35.167/32 0.0.0.0                  0         32768 i
```

Ingress traffic is OK and arrives at the correct node(s). The problem is that cilium is sending back out the traffic with source ip 0.0.0.0, whereas I believe it should be the Node's IP instead.

From tcpdump on the eth0 interface :
IN:
```
11:15:08.980597 IP A.B.C.D.52676 > X.Y.35.167.http: Flags [S], seq 337435015, win 64240, options [mss 1460,sackOK,TS val 2660245581 ecr 0,nop,wscale 7], length 0
```
OUT:
```
11:15:08.980630 IP 0.0.0.0.52676 > X.Y.67.204.http: Flags [S], seq 337435015, win 64240, options [mss 1460,sackOK,TS val 2660245581 ecr 0,nop,wscale 7], length 0
```

@joestringer suggested to file this bug report.

Thanks

### Cilium Version

v1.12.0

### Kernel Version

5.15.0-46-generic #49-Ubuntu

### Kubernetes Version

v1.24.4

### Sysdump

Can provide sysdump information on demand privately.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
