### ISSUE TITLE
Cilium agent restart causes dns requests failure

### ISSUE THREAD

**Issue by egsysoev** [cilium/cilium#21059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. We have the CiliumClusterwideNetworkPolicy that allows all pods to access coreDNS to resolve any domain names:
```
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: default-allow-egress-to-kube-dns
spec:
  endpointSelector:
    matchLabels: {}
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
            - matchPattern: "*"
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: node-local-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
            - matchPattern: "*"
```
2. Pod A and Pod B run on node workerA. Pod C runs on node workerB. CoreDNS runs on node infraA.
3. I run the following command inside Pod A: `while true; do dig kubernetes.default.svc.cluster.local +tries=1 +time=5 +noall +answer +stats; done`. It works as expected all the time.
4. I run the following command inside Pod B: `while true; do curl --silent --output /dev/null --show-error http://$POD-C-IP; done`. It works as expected all the time.
5. I then restart cilium agent on node workerA. Until new cilium agent is up and running, Pod A gets `connection timed out; no servers could be reached` for dig command. At the same time Pod B has no problem with curl.
6. If I deliberately break cilium agent on workerA (e.g. define illegal option inside cilium-config and restart agent) all dns traffic from that node is broken.
7. This behavior takes place on any node in the cluster.
8. I checked tcpdump on workerA and infraA (where coreDNS runs): I see outgoing packets from workerA and I see no incoming packets from workerA on infraA. 
9. I checked `cilium monitor -t drop` on workerA and infraA and I saw no drops. 
10. If I delete dns rules in my cnnp the problem is gone:
```
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: default-allow-egress-to-kube-dns
spec:
  endpointSelector:
    matchLabels: {}
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          # rules:
          #   dns:
          #   - matchPattern: "*"
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: node-local-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          # rules:
          #   dns:
          #   - matchPattern: "*"
```
with the policy above there is no dns traffic problem during cilium agent restart.

What is the reason of this behavior and how can we resolve it? 

### Cilium Version

1.11.4

### Kernel Version

5.4.0-100-generic

### Kubernetes Version

v1.20.15

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
