### ISSUE TITLE
Egress Gateway Policy not working

### ISSUE THREAD

**Issue by dcardellino** [cilium/cilium#21099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am trying to use cilium to NAT connections from specific Pods, but I can not get it to work.
I have deployed Cilium according to this documentation: https://docs.cilium.io/en/stable/gettingstarted/egress-gateway/

When I curl the nginx server from a pod on the cluster I get the expected resonse.
Once I apply the cilium egress gateway policy, I am no longer able to talk to the nginx because the connection times out. Talking to other hosts outsite of the destinationCIDR can be reached.

```
kubectl exec mediabot -- curl http://1.2.3.4:80
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:09 --:--:--     0curl: (7) Failed to connect to 1.2.3.4 port 80: Operation timed out
command terminated with exit code 7
```

My CiliumEgressGatewayPolicy:

```
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: example-policy
spec:
  selectors:
  - podSelector:
      matchLabels:
        org: empire
        class: mediabot
        io.kubernetes.pod.namespace: default
  destinationCIDRs:
  - 1.2.3.4/32
  egressGateway:
    nodeSelector:
      matchLabels:
        egress-node: "true"
```

### Cilium Version

```
cilium version
cilium-cli: 0.12.1 compiled with go1.18.5 on darwin/arm64
cilium image (default): v1.12.0
cilium image (stable): v1.12.1
cilium image (running): v1.12.0
```

### Kernel Version

```
uname -a
Linux cilium-control-plane-1 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
kubectl version --short
Client Version: v1.24.4
Kustomize Version: v4.5.4
Server Version: v1.23.9
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
