### ISSUE TITLE
BPF host routing broken on EKS due to --egress-masquerade-interfaces helm flag

### ISSUE THREAD

**Issue by carjessu-zerohash** [cilium/cilium#21198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When running our cluster with the following values:

```
k8sServiceHost: ${k8s_service_host}
k8sServicePort: ${k8s_service_port}

kubeProxyReplacement: "strict"
eni:
  enabled: true
  updateEC2AdapterLimitViaAPI: true
  awsReleaseExcessIPs: true
  awsEnablePrefixDelegation: true
ipam:
  mode: eni
bpf:
  hostLegacyRouting: false
  masquerade: true
devices: "eth+"
```

We can observe the following output on the pod: 
```
level=warning msg="BPF masquerade does not allow to specify devices via --egress-masquerade-interfaces (use --devices instead). Falling back to iptables-based masquerading." subsys=daemon
level=info msg="BPF masquerade could not be enabled. Falling back to legacy host routing (--enable-host-legacy-routing=\"true\")." subsys=daemon
```

Which is interesting as we did provide the `--devices` flag. The nodes did still have:
```
 --egress-masquerade-interfaces='eth0'" subsys=daemon
 ```

We temporarily solved it by providing: 
```
extraConfig:
  egress-masquerade-interfaces: ""
```

We tried this on multiple versions of Cilium in 1.11.x, 1.12.x and even the 1.13.0-rc0 release. All reported the same issue. This seems to be an issue with the helm chart as we've seen the exact same issue occur with ` enable-endpoint-routes` being sticky while we did definitely set it to `false`.

If there is something you guys would like us to test, let us know!

### Cilium Version

1.11.8, 1.12.0, 1.12.1, 1.13.0-rc0

### Kernel Version

Amazon Linux 2
5.10.135-122.509.amzn2.x86_64

### Kubernetes Version

v1.21.12-eks

### Relevant log output

```shell
level=warning msg="BPF masquerade does not allow to specify devices via --egress-masquerade-interfaces (use --devices instead). Falling back to iptables-based masquerading." subsys=daemon
level=info msg="BPF masquerade could not be enabled. Falling back to legacy host routing (--enable-host-legacy-routing=\"true\")." subsys=daemon
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
