### ISSUE TITLE
Cannot use IRSA when using AWS instance metadata for setting up rules

### ISSUE THREAD

**Issue by wolviecb** [cilium/cilium#21332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am trying to setup AWS Security Groups in CNP as described [here](https://docs.cilium.io/en/v1.12/gettingstarted/aws/#aws-access-keys-and-iam-role), but the process of creating AWS secrets is cumbersome, I've tried just to annotate the service accounts with an IAM Role but it seems that this is not supported as I get errors like

```
level=error msg="Cannot create derivative rule. Installing deny-all rule." ciliumNetworkPolicyName=to-groups-sample error="Provider AWS is not registered" k8sNamespace=default subsys=Groups
```
I'm using this to test the rule

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: "nginx"
  replicas: 1
  template:
    metadata:
      labels:
        app: "nginx"
        filter: "true"
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.1
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 100M
            cpu: 50m
          limits:
            memory: 100M
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - host: "nginx.example.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: to-groups-sample
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      app: nginx
      filter: "true"
  ingress:
    - toPorts:
      - ports:
        - port: '8080'
          protocol: TCP
  egress:
    - toPorts:
      - ports:
        - port: '80'
          protocol: TCP
      toGroups:
      - aws:
          securityGroupsIds:
          - 'sg-123456'
```

### Cilium Version

1.12.1

### Kernel Version

Linux 66dd6f6474-hrqcz 5.4.209-116.363.amzn2.x86_64 #1 SMP Wed Aug 10 21:19:18 UTC 2022 x86_64 GNU/Linux

### Kubernetes Version

1.22

### Sysdump

sysdump file is too big for uploading (28MB)

### Relevant log output

```shell
level=error msg="Cannot create derivative rule. Installing deny-all rule." ciliumNetworkPolicyName=to-groups-sample error="Provider AWS is not registered" k8sNamespace=default subsys=Groups
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
