### ISSUE TITLE
udp package drops in recent cilium versions with masquerade

### ISSUE THREAD

**Issue by schmitch** [cilium/cilium#21411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

hello we currently have problems with udp traffic on cilium, currently sometimes the node works (after a reboot everything works for a while) however after some time cilium does incorrect masquerade's of udp traffic. 

cilium monitor contains the following:

```
xx drop (Unsupported protocol for NAT masquerade) flow 0x0 to endpoint 0, file bpf_host.c line 2183, , identity unknown->unknown: 10.0.3.87 -> 192.168.179.179 TimeExceeded(FragmentReassemblyTimeExceeded)
```

tcp works fine, we do not have any firewall or network policy.

coredns log entry:
```
[ERROR] plugin/errors: 2 excample.com. A: read udp 10.0.3.87:48370->192.168.179.179:53: i/o timeout
```
(note that the ip is basically wrong, because it's a cluster internal 

after a reboot of the node it works again for a while. we upgraded from cilium 1.11.9 to see if it makes a difference but did not use `cleanBpfState` our values.yaml:

```
autoDirectNodeRoutes: true
bpf:
  masquerade: true
  vlan-bpf-bypass:
  - 0
enableIPv4Masquerade: true
enableIPv6Masquerade: true
externalIPs:
  enabled: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
ipv4NativeRoutingCIDR: 10.10.10.0/24
k8sServiceHost: 127.0.0.1 # k3s does load balance on 6444 on every node
k8sServicePort: 6444
kubeProxyReplacement: strict
loadBalancer:
  mode: dsr
operator:
  rollOutPods: true
rollOutCiliumPods: true

tunnel: disabled
localRedirectPolicy: true # not in use yet but we want to look into nodelocaldns soon
```

we use flatcar linux and recently dropped from a higher kernel version due to : https://github.com/flatcar/Flatcar/issues/847 (thus we are now on the lts branch) (might be related)

### Cilium Version

1.12.2, 1.11.9

### Kernel Version

Linux worker1 5.10.137-flatcar #1 SMP Mon Aug 29 19:00:33 -00 2022 x86_64 Intel(R) Xeon(R) Gold 6208U CPU @ 2.90GHz GenuineIntel GNU/Linux

### Kubernetes Version

v1.24.4+k3s1

### Sysdump

(too big but I have a dump it's 62mb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
