### ISSUE TITLE
k8s node cannot access services despite fromCIDR policy allowing it

### ISSUE THREAD

**Issue by gpl** [cilium/cilium#21464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We run a workload inside of Kubernetes that we'd like the k8s nodes themselves to access.  There is a service in front of this workload, and connectivity to the service works from pods inside of the cluster.

Helm values: https://gist.github.com/gpl/67a66e78e27811f553e3f77f27ee1f34

However, when we try to connect to this service from a k8s node, the traffic shows up as policy denied; despite there being a `fromCIDR` rule that matches the IP of the host.

Additionally, we expect the host to be detected as as `remote-node` entity, but that doesn't seem to be the case here, it shows up as "reserved:world" in hubble.

```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: my-policy
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: my-workload
  ingress:
    - fromCIDR:
        - 2001:db8::/32
 ```

If we change this fromCIDR entry to ::/0, or set fromEntities: all, the traffic is then allowed.  

We are testing with `curl http://{ip of workload}:80` 

On the nodes hosting the workload, we run `cilium monitor -t drop` and observe the following:
xx drop (Policy denied) flow 0xbd92f9fc to endpoint 308, ifindex 5, file 2:1577, , identity world->1280: {ip of k8s node}:56468 -> {one of the pods behind the service}:80 tcp SYN

So it seems like we have two different / potentially a combination of issues:

* It doesn't look like the Cilium identity for nodes is being resolved correctly ( edit: related? https://github.com/cilium/cilium/issues/18042 )
* It looks like CIDR rules don't work correctly if one of the IP addresses  is that of a node.  (For example, when we assigned a second IP address to a node and tested traffic from there - the connection established and the CIDR rule worked as expected.  When we tested from the node's primary IP, it didn't work.).

### Cilium Version

1.12.0

### Kernel Version

5.15.49

### Kubernetes Version

1.24.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
