### ISSUE TITLE
Network policies function incorrectly for IPv6 traffic when node-cidr-mask-size-ipv6 is set to a value higher than 64

### ISSUE THREAD

**Issue by karelvanhecke** [cilium/cilium#21605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When a Kubernetes cluster is configured with `node-cidr-mask-size-ipv6: 64`, network policies function as expected. If `node-cidr-mask-size-ipv6` is set to a higher value, for example `96`, IPv6 traffic that is expected to pass is also blocked.

Example:
The following network policy allows ingress from pods within the namespace it is applied in.
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-namespace
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector: {}
  policyTypes:
  - Ingress
```
The following configuration allows the network policy to function as expected.
```
Pod Subnet: 2001:db8::/56
node-cidr-mask-size-ipv6: 64
```
The following configuration causes the network policy to block all ingress IPv6 traffic, even from pods within the namespace.
```
Pod Subnet: 2001:db8::/64
node-cidr-mask-size-ipv6: 96
```

Cilium installation helm values:
```
enableIPv4Masquerade: false
enableIPv6Masquerade: false
ipam:
  mode: kubernetes
ipv6:
  enabled: true
k8sServiceHost: control-plane
k8sServicePort: 6443
kubeProxyReplacement: strict
kubeProxyReplacementHealthzBindAddr: '[::]:10256'
loadBalancer:
  algorithm: maglev
  mode: dsr
tunnel: disabled
```

### Cilium Version

Client: 1.12.2 c7516b9 2022-09-14T15:25:06+02:00 go version go1.18.6 linux/amd64
Daemon: 1.12.2 c7516b9 2022-09-14T15:25:06+02:00 go version go1.18.6 linux/amd64

### Kernel Version

Linux cke-cmp-2a02-1812-1d1c-8e04--a 5.14.0-168.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Sep 23 11:43:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:27:13Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
