### ISSUE TITLE
Shared load balancer not getting created v1.13.0-rc1

### ISSUE THREAD

**Issue by Woidla27** [cilium/cilium#21745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I wanted to try out the new shared lb mode for ingress from here #21386

Installed cilium 1.13 rc using the cli with ingressController.loadbalancerMode=shared
```
cilium install --version "v1.13.0-rc1" \
            --helm-set ingressController.enabled=true \
            --helm-set ingressController.loadbalancerMode=shared \
            --helm-set bgp.enabled=true \
            --helm-set bgp.announce.loadbalancerIP=true
```

Then added an ingress obect
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: news-ingress
  namespace: news
spec:
  ingressClassName: cilium
  rules:
    - host: news.kube2.domain.local
      http:
        paths:
          - backend:
              service:
                name: url-service
                port:
                  number: 5000
            path: /api/url
            pathType: Prefix

  tls:
    - hosts:
        - news.kube2.domain.local
      secretName: ingress-cert
```

But no LoadBalancer service gets created.

When I omit ingressController.loadbalancerMode=shared the LoadBalancer looks like this
```
NAMESPACE     NAME                                  TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                      AGE
news          service/cilium-ingress-news-ingress   LoadBalancer   10.43.25.77     192.168.2.144   80:31680/TCP,443:32395/TCP   11m
```

Am I doing anything wrong here?

### Cilium Version

v1.13.0-rc1

### Kernel Version

Linux kube02 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux

### Kubernetes Version

v1.24.6+k3s1

### Sysdump

[cilium-sysdump-20221015-201208.zip](https://github.com/cilium/cilium/files/9792835/cilium-sysdump-20221015-201208.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
:wave: 

The above installation command looks good to me, however, it's hard to know for sure what is insuded cilium-ci:latest image.

Can you help to update the image of cilium-opeator and cilium agent to v1.13.0-rc1 and retry ?

```
          image: quay.io/cilium/cilium-ci:latest
```

**Comment by Woidla27** [comment]
Yes of course.
I ran `cilium upgrade --version "v1.13.0-rc1"`, now cilium version displays v1.13.0-rc1 as running
After that I deleted and re-added the ingress -> no change on service side
New logs attached: [cilium-sysdump-20221017-001314.zip](https://github.com/cilium/cilium/files/9795805/cilium-sysdump-20221017-001314.zip)

BTW is this intended that the cli installer uses latest instead of the specified version?

**Comment by aanm** [comment]
> BTW is this intended that the cli installer uses latest instead of the specified version?

@Woidla27 no, that was a bug and is now fixed in the latest cilium-cli.

**Comment by sayboras** [comment]
Not sure if it's still issue for you, kindly let me know how it's going.

**Comment by Woidla27** [comment]
Yes this is still an issue for me.

Meanwhile I tried out cilium v1.13.0-rc3 ok kubernetes v1.25.4+k3s1 and still no LoadBalancer in shared mode.

```
cilium install --version "1.13.0-rc3" \
	--helm-set kubeProxyReplacement=strict \
	--helm-set k8sServiceHost=192.168.2.3 \
	--helm-set k8sServicePort=6443 \
	--helm-set ingressController.enabled=true \
	--helm-set ingressController.loadbalancerMode=shared \
	--helm-set bgp.enabled=true \
	--helm-set bgp.announce.loadbalancerIP=true
```

`Linux kube02 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux`

Here is a new log bundle: [cilium-sysdump-20221214-210905.zip](https://github.com/cilium/cilium/files/10231553/cilium-sysdump-20221214-210905.zip)

I am happy to provide more logs as required

@aanm cilium-cli installs the correct version now. Thank you.

**Comment by sayboras** [comment]
can you also share you bgp-config map as well ? 

I have tested with latest master image, it seems working well.

```
$ cilium status                      
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         OK
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         disabled
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

Deployment        cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
DaemonSet         cilium             Desired: 1, Ready: 1/1, Available: 1/1
Containers:       cilium             Running: 1
                  cilium-operator    Running: 1
Cluster Pods:     2/4 managed by Cilium
Image versions    cilium             cilium:tilt-79a3eb9e6cdccb6c: 1
                  cilium-operator    operator-generic-ci:tilt-07cfa4c9560e9f54: 1

$ ksysg services cilium-ingress                         
NAME             TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
cilium-ingress   LoadBalancer   10.104.20.130   192.0.2.0     80:32708/TCP,443:30417/TCP   24m
```

**Comment by Woidla27** [comment]
Here is my bgp config map

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
    - peer-address: 192.168.2.126
      peer-asn: 65535
      my-asn: 64512
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 192.168.2.144/28
```

**Comment by Woidla27** [comment]
Today I had some time to experiment.

Tried a lot of things.
- Fresh installation using K3S v1.26.0+k3s2 + Cilium v1.13.0-rc3, still on Debian 11
- Migrated MetallLB BGP to Cilium BGP Control Plane + LB IPAM
- Different combinations with shared and dedicated LoadBalancer (both as default value in cilium-config configmap and annotation)

But in the end it remains: a LoadBalancer for shared ingress is missing.
IP assignment via BGP seems to work in dedicated mode.

Any Ideas how to further debug this issue?

Here is a log with activated debug mode while dedicated ingress should be applied.
[logs-cilium-z2mcs-cilium-agent-20230123-002546.zip](https://github.com/cilium/cilium/files/10475863/logs-cilium-z2mcs-cilium-agent-20230123-002546.zip)


Here the shared config and result
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: news-ingress
  namespace: news
  annotations:
    io.cilium.ingress/loadbalancer-mode: shared
spec:
  ingressClassName: cilium
  rules:
    - host: news.kube2.domain.local
      http:
        paths:
          - backend:
              service:
                name: url-service
                port:
                  number: 5000
            path: /api/url
            pathType: Prefix
```
```
# kubectl get service -A
NAMESPACE     NAME                          TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                      AGE
default       kubernetes                    ClusterIP      10.43.0.1       <none>          443/TCP                      5h47m
kube-system   hubble-peer                   ClusterIP      10.43.31.236    <none>          443/TCP                      3h32m
kube-system   hubble-relay                  ClusterIP      10.43.116.63    <none>          80/TCP                       3h32m
kube-system   hubble-ui                     ClusterIP      10.43.227.143   <none>          80/TCP                       3h32m
kube-system   kube-dns                      ClusterIP      10.43.0.10      <none>          53/UDP,53/TCP,9153/TCP       5h47m
kube-system   metrics-server                ClusterIP      10.43.161.142   <none>          443/TCP                      5h47m
news          cilium-ingress-news-ingress   LoadBalancer   10.43.109.238   192.168.2.152   80:31003/TCP,443:32150/TCP   95s
news          url-service                   ClusterIP      10.43.243.136   <none>          5000/TCP                     3h31m
```


Here in dedicated mode:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: news-ingress
  namespace: news
  annotations:
    io.cilium.ingress/loadbalancer-mode: dedicated
spec:
  ingressClassName: cilium
  rules:
    - host: news.kube2.domain.local
      http:
        paths:
          - backend:
              service:
                name: url-service
                port:
                  number: 5000
            path: /api/url
            pathType: Prefix
```
```
# kubectl get service -A
NAMESPACE     NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes       ClusterIP   10.43.0.1       <none>        443/TCP                  5h48m
kube-system   hubble-peer      ClusterIP   10.43.31.236    <none>        443/TCP                  3h32m
kube-system   hubble-relay     ClusterIP   10.43.116.63    <none>        80/TCP                   3h32m
kube-system   hubble-ui        ClusterIP   10.43.227.143   <none>        80/TCP                   3h32m
kube-system   kube-dns         ClusterIP   10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP   5h47m
kube-system   metrics-server   ClusterIP   10.43.161.142   <none>        443/TCP                  5h47m
news          url-service      ClusterIP   10.43.243.136   <none>        5000/TCP                 3h32m
```
