### ISSUE TITLE
Cilium 1.12.2 CNI daemonset pods failing

### ISSUE THREAD

**Issue by Sandy7894** [cilium/cilium#21752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi All,

We are trying to deploy Cilium CNI helm chart using terraform on EKS cluster, we are planning to use a dedicated subnet to deploy the pods and below are the params which we are using to deploy the same :

```
ipam:
  mode: eni
cni:
  chainingMode: aws-cni
  configMap: cni-configuration
  customConf: true
enableIPv4Masquerade: false
endpointRoutes:
  enabled: true
eni:
  enabled: true
  subnetTagsFilter: Identifier=eks-pods
tunnel: disabled
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
```

We have created a configMap,  to use subnet-tags and enabled customConf to use the same. With this method, we are observing an issue where the Cilium daemonset pods are failing with below errors :

`Startup probe failed: Get "http://127.0.0.1:9879/healthz": dial tcp 127.0.0.1:9879: connect: connection refused`

When we observe the pod logs, we could see the below message : 

`msg="Waiting for IPs to become available in CRD-backed allocation pool" available=0 helpMessage="Check if cilium-operator pod is running and does not have any warnings or error messages."`

Cilium operator is running fine and could see that it is able to get the subnets, but it has some warnings as below :

`level=warning msg="Instance not found! Please delete corresponding ciliumnode if instance has already been deleted."`

Have seen few other issue, mentioning this error but heard this issue has been resolved post v1.11.. So could you please let us know how to debug the same and know the issue. Deployment is getting successful, if we dont use "subnetTagFilter", the pods are not complaining but the pods are not getting deployed to expected subnet.

### Cilium Version

1.12.2

### Kernel Version

5.4.209-116.367.amzn2.x86_64

### Kubernetes Version

1.22

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
