### ISSUE TITLE
setting up cilium with ipv6 removes default ipv6 route if it was learned from router advertisement

### ISSUE THREAD

**Issue by jose-ledesma** [cilium/cilium#21819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When cilium enables ipv6 forwarding in systems which configuration is the default one for the network interfaces (i.e. `net.ipv6.conf.<interface>.accept_ra=1`)  the default route is lost if it was learned from router advertisement, leaving the node unable to communicate using IPv6

Similar issues: https://github.com/cilium/cilium/issues/11263 https://github.com/cilium/cilium/issues/10633

Not sure if cilium should set the `net.ipv6.conf.<interface>.accept_ra=2` automatically  or controlled by an argument, but happy to open a PR if I get some guidance there :)

### Cilium Version

```
# cilium version
Client: 1.12.90 d5a1a041 2022-10-19T10:01:11-07:00 go version go1.19.2 linux/amd64
Daemon: 1.12.90 d5a1a041 2022-10-19T10:01:11-07:00 go version go1.19.2 linux/amd64
```

### Kernel Version

Linux ip-10-67-217-49.ec2.internal 5.4.209-116.367.amzn2.x86_64 #1 SMP Wed Aug 31 00:09:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.10-eks-15b7512", GitCommit:"cd6399691d9b1fed9ec20c9c5e82f5993c3f42cb", GitTreeState:"clean", BuildDate:"2022-08-31T19:17:01Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by clementnuss** [comment]
I'm having the exact same issue, if there is some guidance on how to address this that would be nice.

For additional context, I'm using 2 interfaces on my node, one for k8s-only traffic, the other for ipv6 connectivity. I wasn't expecting the ipv6-only interface to be modified 🤔

**Comment by jose-ledesma** [comment]
If you have control over the `sysctl` settings of the host, you can add to the `/etc/sysctl.conf` something like:
```
net.ipv6.conf.<interfaced_name>.accept_ra=2
```

Because I have no control over the `sysctl` settings at the host level, I'm using the following hack to make it work (disclaimer, I'm using Helm to deploy Cilium):
```
extraContainers:
  - name: setup-accept-ra
    image: busybox
    command:
      - sh
      - "-c"
      - "echo 2 > /hostproc/sys/net/ipv6/conf/eth0/accept_ra; while :; do  sleep 30;done"
    volumeMounts:
    - mountPath: /hostproc
      name: hostproc
```
