### ISSUE TITLE
Kafka L7 visibility policy causes connection errors due to parser errors

### ISSUE THREAD

**Issue by chancez** [cilium/cilium#21813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using Kafka L7 visibility policies, I'm seeing my Kafka consumers get disconnected roughly every 30-60 seconds. I enabled debug logging and verbose envoy logs and was able to find the error related to the disconnect, it seems the Kafka parser is encountering an error and closing the connection as a result.

### Cilium Version

I'm using a recent master build, but this is present in all versions I've tried.

### Kernel Version

Linux lima-docker 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 12:56:31 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-09-01T23:50:12Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/arm64"}

### Sysdump

[cilium-sysdump-20221019-110146.zip](https://github.com/cilium/cilium/files/9823130/cilium-sysdump-20221019-110146.zip)

### Relevant log output

```shell
level=debug msg="time=\"2022-10-19T17:59:56Z\" level=debug msg=\"Ignoring Kafka message apiKey=8,apiVersion=5,len=156: null due to parse error\" error=\"invalid array length\"" subsys=envoy-filter threadID=638
level=debug msg="time=\"2022-10-19T17:59:56Z\" level=warning msg=\"Unable to parse Kafka request; closing Kafka connection\" error=\"invalid array length\"" subsys=envoy-filter threadID=638
```

### Anything else?

I have a demo app to reproduce but it's private. PM me if you need a way to reproduce the error.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
test

**Comment by daviddyball** [comment]
Can confirm this behaviour on my own Cilium `1.12.7` deployment.

**Comment by daviddyball** [comment]
Is this an issue with envoy or with Cilium itself? Do we have to wait for upstream envoy to resolve an issue there, or is it Cilium's use of envoy?

**Comment by chancez** [comment]
@daviddyball The Kafka protocol handling is custom implemented envoy filter, so it's something we need to resolve.

**Comment by jValdron** [comment]
Hitting the same error in our environment while trying to enable L7 observability on Kafka, using the following network policy:
```
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-kafka-traffic
  annotations:
    io.cilium.policy.audit-mode: "true"
    io.cilium.proxy-visibility: 'enabled'  # Enables logging of all traffic via proxy
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
  - fromEntities:
    - "all"
  - toPorts:
    - ports:
      - port: "9092"
        protocol: TCP
      rules:
       kafka: [{}]
  egress:
  - toEntities:
    - "all"
  - toPorts:
    - ports:
      - port: "9092"
        protocol: TCP
      rules:
       kafka: [{}] 
```

This does enable us to see flows within Hubble, but it does cause some blocking issues, similar error as mentioned in this thread but a little different:
```
time="2025-02-26T13:31:54Z" level=debug msg="time=\"2025-02-26T13:31:54Z\" level=debug msg=\"Ignoring Kafka message apiKey=3,apiVersion=11,len=617: null due to parse error\" error=\"unexpected EOF\"" subsys=envoy-conn_handler threadID=321
time="2025-02-26T13:31:54Z" level=debug msg="time=\"2025-02-26T13:31:54Z\" level=warning msg=\"Unable to parse Kafka request; closing Kafka connection\" error=\"unexpected EOF\"" subsys=envoy-conn_handler threadID=321
```

We are using WarpStream, which should be pretty much Kafka compatible. I can try it against an MSK cluster and see if I can also reproduce it.

It seems like the [Kafka library](https://github.com/cilium/kafka/) is a bit out of date from the [original fork](https://github.com/optiopay/kafka) but I don't see a whole lot of changes with the logic to parse the metadata (`apiKey=3`) requests.
