### ISSUE TITLE
Cilium L7 HTTP visibility policy causes "Connection reset reset reason: overflow" with high request volume

### ISSUE THREAD

**Issue by chancez** [cilium/cilium#21814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I was updating my application to increase it's request rate I had an "off by 1000" error, so it ended up sending a ton more requests than intended, and as a result I started seeing the following errors:
```
upstream connect error or disconnect/reset before headers. reset reason: overflow
```

This seems to be caused by envoy's default circuit breaker which has a limit of 1024 parallel/pending requests: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/circuit_breaking

Additionally, my application does retries, and I noticed that envoy was retrying my requests 3 times each also, meaning I'm seeing request amplification caused by the default http retry configuration cilium uses with envoy.  

The default for how many times to retry is specified here: https://github.com/cilium/cilium/blob/f20d921fdf115a8062870133219a4ba01ffcde16/daemon/cmd/daemon_main.go#L371 which gets used in the HTTP filter chain: https://github.com/cilium/cilium/blob/26d31f00dd2858401d35a5afa0626c810ecbe207/pkg/envoy/server.go#L270

As you can see it retries on all 5xx errors, which is a bit surprising.

I tried setting the value to 0, and it didn't seem to make a huge difference given my request volume, but it certainly wasn't helping, but possibly making the problem worse.

### Cilium Version

Using a recent master build: 
```
cilium image (running): -ci:df6a89cdcc8ce15dcf9e9644a321e78f37fb038b
```

### Kernel Version

Linux lima-docker 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 12:56:31 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-09-01T23:50:12Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/arm64"}

### Sysdump

[cilium-sysdump-20221019-114842.zip](https://github.com/cilium/cilium/files/9823366/cilium-sysdump-20221019-114842.zip)

### Relevant log output

From verbose agent logs with envoy logging enabled:
```
level=debug msg="[max streams overflow" subsys=envoy-pool threadID=607
level=debug msg="[[C12][S16447794163553078762] upstream reset: reset reason: overflow, transport failure reason: " subsys=envoy-router threadID=607
level=debug msg="[[C12][S16447794163553078762] Sending local reply with details upstream_reset_before_response_started{overflow}" subsys=envoy-http threadID=607
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yanivNaor92** [comment]
@chancez I'm having the same issue.
Did you manage to find a way to configure the default circuit breaking?

**Comment by chancez** [comment]
@yanivNaor92 unfortunately no. You can adjust the number of default retries however, using the `http-retry-count` flag/config option on cilium agent. There is also `http-idle-timeout`, `http-retry-timeout` and `http-request-timeout`.

**Comment by aramalipoor** [comment]
In case this is useful for anyone, here's how I could override the Envoy circuit-breaker for a Cilium ingress:
```
apiVersion: cilium.io/v2
kind: CiliumClusterwideEnvoyConfig
metadata:
  name: a-0-c-8339-erpc
  namespace: erpc
spec:
  services:
    - name: a-0-c-8339-erpc
      namespace: erpc
  backendServices:
    - name: a-0-c-8339-erpc
      namespace: erpc
  resources:
    - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
      name: "kube-system/cilium-ingress/erpc:a-0-c-8339-erpc:80"
      type: EDS
      connect_timeout: 5s
      eds_cluster_config:
        service_name: "erpc/a-0-c-8339-erpc:80"
      circuit_breakers:
        thresholds:
          - priority: DEFAULT
            max_connections: 2000000
            max_pending_requests: 2000000
            max_requests: 2000000
            max_retries: 2000000
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          common_http_protocol_options:
            idle_timeout: 60s
          use_downstream_protocol_config:
            http2_protocol_options: {}
```

I hope this is the right way of doing this :D At least during load-tests I don't get the "overflow" anymore.
