### ISSUE TITLE
CFP: Ability to defined Custom Entities in CiliumNetworkPolicy

### ISSUE THREAD

**Issue by alexbescond** [cilium/cilium#21832]
## Cilium Feature Proposal
        
Hi Folks, I create this Feature Request in response to the slack conversation [here](https://cilium.slack.com/archives/C1MATJ5U5/p1666257650191789). 

**Is your feature request related to a problem?**

It is not really a problem, meaning we can do without, but having this feature will really help on the management of the CiliumNetworkPolicy.

**Describe the feature you'd like**

This feature is about `CiliumNetworkPolicy` and “Custom Entities”.
Right now, we can use predefined Entity like `kube-apiserver` in `CiliumNetworkPolicy`. However it would be great to be able to define our own “Custom Entities” and use them on the `CiliumNetworkPolicy`.
For instance, one use case would be to provision the AWS regional STS on each region as `CiliumCustomEntity`. Then we just need to allow this custom entity on `CiliumNetworkPolicy` no matter where the application is deployed.

In cluster A we have:
Entity named: `aws-sts-regional` linked to: `sts.regionA.amazonaws.com`
In cluster B we have:
Entity named: `aws-sts-regional` linked to: `sts.regionB.amazonaws.com`

And finally, when we deploy a `CiliumNetworkPolicy` we only have to allow egress/ingress from/to this entity named `aws-sts-regional`

**(Optional) Describe your proposed solution**

This proposed solution is about defining a new resource named: `CiliumCustomEntity`.

```
---
apiVersion: cilium.io/v2
kind: CiliumCustomEntity
metadata:
  name: whitelisted-domains
spec:
  FQDNs:
    - matchPattern: *.example.com
    - matchName: example.com

---
apiVersion: cilium.io/v2
kind: CiliumCustomEntity
metadata:
  name: aws-sts-regional
spec:
  FQDNs:
    - matchName: sts.regionA.amazonaws.com

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: foo
spec:
  egress:
    - toCustomEntities:
        - whitelisted-domains
        - aws-sts-regional
...
...
``` 

By doing that, we can factorize `CiliumNetworPolicy`. 
* For `whitelisted-domains`, we can easily add/remove endpoints without modifying all the `CiliumNetworPolicy` that use it. 
* For `aws-sts-regional`, it facilitates our deployments when we use clusters in several regions. Indeed, only the `CiliumCustomEntity` change but the `CiliumNetworkPolicy` can be the same across all our deployments. 

Open Question:
What should be the scope of this CiliumCustomEntity, namespace or cluster?
I think it makes more sense to have this CiliumCustomEntity at a Cluster level because having this namespaced will drastically reduce the possible factorization of the network policies.
