### ISSUE TITLE
CiliumIdentity Out of Sync while using argocd

### ISSUE THREAD

**Issue by rozen-dada** [cilium/cilium#21873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened! When i sync my application repository, all the deployments and services created successfully but one CiliumIdentity appeared and have status out of sync causing my whole application as out of sync.

### Cilium Version

I used DigitalOcean kubernetes Cluster

### Kernel Version

I dont know

### Kubernetes Version

Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.24.4

### Anything else?

![image](https://user-images.githubusercontent.com/25153518/197669655-e1a1170a-6d8e-442a-9093-3e477cda8c51.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by babykart** [comment]
Hi,

There is a piece of documentation about this : https://docs.cilium.io/en/stable/configuration/argocd-issues/#argo-cd-deletes-customresourcedefinitions.

My values of the argo-cd helm chart:

```yaml
configs:
  cm:
    create: true
    resource.exclusions: |
      - apiGroups:
          - cilium.io
        kinds:
          - CiliumIdentity
        clusters:
          - "*"
```
