### ISSUE TITLE
NetworkPolicy egress strange behaviour.

### ISSUE THREAD

**Issue by feitnomore** [cilium/cilium#21883]
I've got a local cluster running 1.24
```
clientVersion:
  buildDate: "2022-09-21T13:19:24Z"
  compiler: gc
  gitCommit: b39bf148cd654599a52e867485c02c4f9d28b312
  gitTreeState: clean
  gitVersion: v1.24.6
  goVersion: go1.18.6
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-09-21T13:12:04Z"
  compiler: gc
  gitCommit: b39bf148cd654599a52e867485c02c4f9d28b312
  gitTreeState: clean
  gitVersion: v1.24.6
  goVersion: go1.18.6
  major: "1"
  minor: "24"
  platform: linux/amd64
 ```

I've installed Cilium 1.11.2 with the following steps:
```
helm repo add cilium https://helm.cilium.io/
helm repo update

helm template cilium cilium/cilium \
    --version 1.11.2 \
    --namespace kube-system \
    --set kubeProxyReplacement=strict > cilium.yaml

Adjusted CIDR on cilium.yaml
changed --cni-exclusive to false on cilium.yaml

kubectl apply -f cilium.yaml
```

After that I've also installed `Multus` to use Kubevirt with some network bridges.
Whenever I use `matchLabels` on my egress (can be podSelector or namespaceSelector), the rule doesn't work.
Here is an example that doesn't work:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-access
  namespace: internal-services
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
```

And this example works (10.96.0.10 is ip of kube-dns service):
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-access
  namespace: internal-services
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.96.0.10/32
    ports:
    - protocol: UDP
      port: 53
```

Any clues or tips on how to troubleshoot it?
Thanks!
