### ISSUE TITLE
host firewall: duplicate policy verdict events

### ISSUE THREAD

**Issue by sypakine** [cilium/cilium#21884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Problem:
Host firewall policies (https://docs.cilium.io/en/v1.12/policy/language/#host-policies) product duplicate policy verdict events. Reproduced on multiple versions.

Expect:
Single policy verdict event per flow

Actual:
Two (2) policy verdicts per flow

Reproduction:

1. Follow quick installation guide (https://docs.cilium.io/en/v1.12/gettingstarted/k8s-install-default/#quick-installation)
1. Follow instructions to create a GKE cluster (presumably `kind` or other would also reproduce the issue)
1. `alias k=kubectl`
1. `k config set-context --current --namespace=kube-system`
1.  Enable host firewall:
    ```
    k patch cm cilium-config --type=json -p '[
      { "op": "add", "path": "/data/enable-host-firewall", "value": "true" }
    ]'
    ```
1. Create host firewall policy (https://docs.cilium.io/en/v1.12/policy/language/#host-policies):
    ```
    k apply -f - <<EOF
    apiVersion: "cilium.io/v2"
    kind: CiliumClusterwideNetworkPolicy
    metadata:
      name: "node-allow-all-ingress"
    spec:
      nodeSelector: {}
      ingress:
      - fromEntities:
        - all
    EOF
    ```
1. `k rollout restart ds/cilium && k rollout status ds/cilium`
1. ` k exec -it $( k get pod -l=k8s-app=cilium -ojsonpath='{.items[].metadata.name}' ) -- cilium monitor --type policy-verdict`
1. deploy busybox pod
    ```
    k apply -f - <<EOF
    apiVersion: v1
    kind: Pod
    metadata:
      name: busybox-sleep
    spec:
      containers:
      - name: busybox
        image: busybox:1.28
        args:
        - sleep
        - "1000000"
    EOF
    ```
1. `k exec -it busybox-sleep -- ping -c1 $( k get pod -l=k8s-app=cilium -ojsonpath='{.items[].status.podIP}' )`
    > Policy verdict log: flow 0x0 local EP ID 930, remote ID 5912, proto 1, ingress, action allow, match all, 10.116.0.10 -> 10.168.0.28 EchoRequest
    > Policy verdict log: flow 0x0 local EP ID 930, remote ID 5912, proto 1, ingress, action allow, match all, 10.116.0.10 -> 10.168.0.28 EchoRequest
1. `k exec -it busybox-sleep -- wget $( k get pod -l=k8s-app=cilium -ojsonpath='{.items[].status.podIP}' )`
    > Policy verdict log: flow 0x0 local EP ID 930, remote ID 5912, proto 6, ingress, action allow, match all, 10.116.0.10:55180 -> 10.168.0.28:80 tcp SYN
    > Policy verdict log: flow 0x0 local EP ID 930, remote ID 5912, proto 6, ingress, action allow, match all, 10.116.0.10:55180 -> 10.168.0.28:80 tcp SYN

### Cilium Version

> Client: 1.12.2 c7516b9 2022-09-14T15:25:06+02:00 go version go1.18.6 linux/amd64
> Daemon: 1.12.2 c7516b9 2022-09-14T15:25:06+02:00 go version go1.18.6 linux/amd64

### Kernel Version

> Linux ${NODE_NAME} 5.10.127+ #1 SMP Fri Jul 8 00:39:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

> Client Version: v1.24.2
> Kustomize Version: v4.5.4
> Server Version: v1.23.8-gke.1900

### Sysdump

If this is important, we'll work on a way to provide.

### Relevant log output

```shell
ICMP:
> Policy verdict log: flow 0x0 local EP ID 930, remote ID 5912, proto 1, ingress, action allow, match all, 10.116.0.10 -> 10.168.0.28 EchoRequest
> Policy verdict log: flow 0x0 local EP ID 930, remote ID 5912, proto 1, ingress, action allow, match all, 10.116.0.10 -> 10.168.0.28 EchoRequest
  
> 19:06:34.750785 IP 10.116.0.10 > 10.168.0.28: ICMP echo request, id 18944, seq 0, length 64
> 19:06:34.750900 IP 10.168.0.28 > 10.116.0.10: ICMP echo reply, id 18944, seq 0, length 64

TCP:

> Policy verdict log: flow 0x0 local EP ID 930, remote ID 5912, proto 6, ingress, action allow, match all, 10.116.0.10:55180 -> 10.168.0.28:80 tcp SYN
> Policy verdict log: flow 0x0 local EP ID 930, remote ID 5912, proto 6, ingress, action allow, match all, 10.116.0.10:55180 -> 10.168.0.28:80 tcp SYN

> 19:06:18.153217 IP 10.116.0.10.46046 > 10.168.0.28.80: Flags [S], seq 2475669049, win 42600, options [mss 1420,sackOK,TS val 2336915253 ecr 0,nop,wscale 7], length 0
> 19:06:18.153326 IP 10.168.0.28.80 > 10.116.0.10.46046: Flags [R.], seq 0, ack 2475669050, win 0, length 0
```

### Anything else?

- Checked existing issues and didn't find a duplicate issue.
- This only happens with host firewall policies. 
- confirmed via `tcpdump` that the node is only receiving single flow

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
