### ISSUE TITLE
bgp-control-plane  withdrawing pod CIDR bug

### ISSUE THREAD

**Issue by wenqiang0527** [cilium/cilium#21901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

kubernetes version: 1.25
cilium version : 1.21.1

bgp-control-plane: true
ipam: cluster-pool-v2beta

when operator assign two PodCIDRs to a node, if  node release them ,  the bgp-control-plane  withdrawing pod CIDR  only withdrawing one PodCIDR， it that a bug?

here is my test,
create many pods on one node，the operator assign two PodCIDRs to that node，and bgp-control-plane Advertising pod CIDR 
here is the logs: （bgp-control-plane sent two PodCIDRs , 10.142.48.112/28 and 10.142.48.128/28）
```
level=debug msg="Begin reconciling pod CIDR advertisements for virtual router with local ASN 64512" component=gobgp.exportPodCIDRReconciler subsys=bgp-control-plane
level=debug msg="Advertising pod CIDR 10.142.48.112/28 for policy with local ASN: 64512" component=gobgp.exportPodCIDRReconciler subsys=bgp-control-plane
level=debug msg="create Destination" Nlri=10.142.48.112/28 Topic=Table asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=debug msg="Successfully completed reconciliation" component=Controller.Run subsys=bgp-control-plane
level=debug msg="sent update" Key=10.125.2.8 State=BGP_FSM_ESTABLISHED Topic=Peer asn=64512 attributes="[{Origin: i} 64512 {Nexthop: 10.182.11.54}]" component=gobgp.BgpServerInstance nlri="[10.142.48.112/28]" subsys=bgp-control-plane withdrawals="[]"
level=debug msg="sent update" Key=10.125.3.8 State=BGP_FSM_ESTABLISHED Topic=Peer asn=64512 attributes="[{Origin: i} 64512 {Nexthop: 10.182.11.54}]" component=gobgp.BgpServerInstance nlri="[10.142.48.112/28]" subsys=bgp-control-plane withdrawals="[]"
level=debug msg="sent update" Key=10.125.1.8 State=BGP_FSM_ESTABLISHED Topic=Peer asn=64512 attributes="[{Origin: i} 64512 {Nexthop: 10.182.11.54}]" component=gobgp.BgpServerInstance nlri="[10.142.48.112/28]" subsys=bgp-control-plane withdrawals="[]"

level=debug msg="Begin reconciling pod CIDR advertisements for virtual router with local ASN 64512" component=gobgp.exportPodCIDRReconciler subsys=bgp-control-plane
level=debug msg="Advertising pod CIDR 10.142.48.128/28 for policy with local ASN: 64512" component=gobgp.exportPodCIDRReconciler subsys=bgp-control-plane
level=debug msg="create Destination" Nlri=10.142.48.128/28 Topic=Table asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=debug msg="Successfully completed reconciliation" component=Controller.Run subsys=bgp-control-plane
level=debug msg="sent update" Key=10.125.1.8 State=BGP_FSM_ESTABLISHED Topic=Peer asn=64512 attributes="[{Origin: i} 64512 {Nexthop: 10.182.11.54}]" component=gobgp.BgpServerInstance nlri="[10.142.48.128/28]" subsys=bgp-control-plane withdrawals="[]"
level=debug msg="sent update" Key=10.125.3.8 State=BGP_FSM_ESTABLISHED Topic=Peer asn=64512 attributes="[{Origin: i} 64512 {Nexthop: 10.182.11.54}]" component=gobgp.BgpServerInstance nlri="[10.142.48.128/28]" subsys=bgp-control-plane withdrawals="[]"
level=debug msg="sent update" Key=10.125.2.8 State=BGP_FSM_ESTABLISHED Topic=Peer asn=64512 attributes="[{Origin: i} 64512 {Nexthop: 10.182.11.54}]" component=gobgp.BgpServerInstance nlri="[10.142.48.128/28]" subsys=bgp-control-plane withdrawals="[]"
```

the ciliumnodes status is:
```
  ipam:
    podCIDRs:
    - 10.142.48.0/28
    - 10.142.48.16/28
    - 10.142.48.112/28
    - 10.142.48.128/28
status:
  alibaba-cloud: {}
  azure: {}
  eni: {}
  ipam:
    operator-status: {}
    pod-cidrs:
      10.142.48.0/28:
        status: depleted
      10.142.48.16/28:
        status: depleted
      10.142.48.112/28:
        status: depleted
      10.142.48.128/28:
        status: in-use
```

delete these pods, ciliumnode release  these podCIDRs ( 10.142.48.112/28 ,10.142.48.128/28 )
```
  ipam:
    podCIDRs:
    - 10.142.48.0/28
    - 10.142.48.16/28
status:
  alibaba-cloud: {}
  azure: {}
  eni: {}
  ipam:
    operator-status: {}
    pod-cidrs:
      10.142.48.0/28:
        status: in-use
      10.142.48.16/28:
        status: in-use
      10.142.48.112/28:
        status: released
      10.142.48.128/28:
        status: released
```

but  bgp-control-plane only withdrawing pod CIDR 10.142.48.128/28，
```
level=debug msg="Begin reconciling pod CIDR advertisements for virtual router with local ASN 64512" component=gobgp.exportPodCIDRReconciler subsys=bgp-control-plane
level=debug msg="Withdrawing pod CIDR 10.142.48.128/28 for policy with local ASN: 64512" component=gobgp.exportPodCIDRReconciler subsys=bgp-control-plane
level=debug msg="Removing withdrawals" Key=10.142.48.128/28 Topic=Table asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=debug msg="Withdrawing pod CIDR 10.142.48.128/28 for policy with local ASN: 64512" component=gobgp.exportPodCIDRReconciler subsys=bgp-control-plane
level=debug msg="Removing withdrawals" Key=10.142.48.128/28 Topic=Table asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=debug msg="Found withdrawals for path(s) that did not get installed" Key=10.142.48.128/28 Topic=Table asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=debug msg="Successfully completed reconciliation" component=Controller.Run subsys=bgp-control-plane
level=debug msg="sent update" Key=10.125.1.8 State=BGP_FSM_ESTABLISHED Topic=Peer asn=64512 attributes="[]" component=gobgp.BgpServerInstance nlri="[]" subsys=bgp-control-plane withdrawals="[10.142.48.128/28]"
level=debug msg="sent update" Key=10.125.2.8 State=BGP_FSM_ESTABLISHED Topic=Peer asn=64512 attributes="[]" component=gobgp.BgpServerInstance nlri="[]" subsys=bgp-control-plane withdrawals="[10.142.48.128/28]"
level=debug msg="sent update" Key=10.125.3.8 State=BGP_FSM_ESTABLISHED Topic=Peer asn=64512 attributes="[]" component=gobgp.BgpServerInstance nlri="[]" subsys=bgp-control-plane withdrawals="[10.142.48.128/28]"
```

the switch still has route 10.142.48.112/28

### Cilium Version

1.12.1

### Kernel Version

4.18.0-348.el8.x86_64

### Kubernetes Version

1.25

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
