### ISSUE TITLE
CFP: cilium-grafana chart

### ISSUE THREAD

**Issue by jcpunk** [cilium/cilium#21921]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature request for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your feature request related to a problem?**

Defining which metrics should be charted for cilium is a bit complex.

**Describe the feature you'd like**

A Helm chart that provides useful CRDs that I can install after I've loaded a grafana image (to get the CRD definitions)

**(Optional) Describe your proposed solution**

A separate cilium-grafana chart that uses https://github.com/cilium/cilium/blob/master/examples/kubernetes/addons/prometheus/monitoring-example.yaml (or some better dashboards if they are on hand) to provide the CRDs.

**Comment by aanm** [comment]
@jcpunk we do provide some grafana dashboards. Are those not enough? cc @tom-hadlaw-hs for more info

**Comment by jcpunk** [comment]
Grafana has a [CRD](https://github.com/grafana-operator/grafana-operator/blob/master/documentation/dashboards.md) that can read in dashboards packaged up with a project.

I'll confess I was hopeful to get the provided dashboards into a separate helm chart I could install.  I figure the dashboards might move a a different pace than cilium, so having them under one chart would be bad.

**Comment by jcpunk** [comment]
I'm still interested in this

**Comment by lambdanis** [comment]
A few comments:

The original proposal was to create a new Helm chart only for Grafana dashboards. Maybe it's just a detail in phrasing, but I don't see a reason to have another Helm chart, dashboards should be included in the Cilium Helm chart.

There is another issue to add dashboards to the Helm chart as configmaps (that could be mounted in a Grafana pod or loaded automatically by its dashboards sidecar): https://github.com/cilium/cilium/issues/20354 One Hubble dashboard is already included under `hubble.metrics.dashboards.*`.

Adding an option to create `GrafanaDashboard` custom resource might be a nice little addition (although by no means crucial, adding dashboards as configmaps would be good for now IMO). `GrafanaDashboard` can contain ref to a configmap, so it could be an extra option, something like:
```
dashboards:
  enabled: true
  namespace: ~
  label: grafana_dashboard
  labelValue: "1" 
  annotations: {}
  grafanaDashboardCRD:
    enabled: true
    # some extra config for metadata
```
Or they could be created instead of configmaps with raw JSONs inline, e.g.:
```
dashboards:
  enabled: true
  mode: grafanadashboard  # configmap by default
  namespace: ~
  label: grafana_dashboard
  labelValue: "1" 
  # Grafana operator can use multiple labels to select GrafanaDashboards, so the labels config gets tricky
  # if we want to support both and keep backwards compatibility.
  additionalLabels:
    somelabel: somevalue
  annotations: {}
```
I'm not sure which option would be prefered by Grafana operator users, but I like the former more, the latter makes the config a bit messy.

Also, creating `GrafanaDashboard` custom resources depends on the CRDs being present in the cluster. So it needs careful docs, and ideally also Helm validation checks and support in Cilium CLI.
