### ISSUE TITLE
[DOC] Monitoring & Metrics page has incomplete/inaccurate data

### ISSUE THREAD

**Issue by jcpunk** [cilium/cilium#21958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

from: https://docs.cilium.io/en/stable/operations/metrics/

> When metrics are enabled, all Cilium components will have the following annotations. They can be used to signal Prometheus whether to scrape metrics:
> prometheus.io/scrape: true
> prometheus.io/port: 9962

The helm chart, however, has:

```yaml
    {{- if not .Values.hubble.metrics.serviceMonitor.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.hubble.metrics.port | quote }}
    {{- end }}
```

Which shows the annotation is only enabled in some cases.

### Cilium Version

1.12.3

### Kernel Version

This is a documentation issue, local software doesn't seem relevant.

### Kubernetes Version

This is a documentation issue, local software doesn't seem relevant.

### Sysdump

This is a documentation issue, local software doesn't seem relevant.

### Relevant log output

```shell
This is a documentation issue, local software doesn't seem relevant.
```

### Anything else?

Additional fields on how to use the cilium serviceMonitor (with prometheus-kube-stack helm chart) would be most welcome!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
