### ISSUE TITLE
CiliumClusterwideNetworkPolicy not working

### ISSUE THREAD

**Issue by sunnoy** [cilium/cilium#21963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

i apply the CiliumClusterwideNetworkPolicy

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "ccp"
spec:
  description: ""
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: k3s-2
  ingress:
  - fromCIDR:
    - 11.0.0.0/16
  - toPorts:
    - ports:
      - port: "2049"
        protocol: TCP
```

but i from other node in clueter and it's ip not in 11.0.0.0/16,can curl k3s-2:2049

### Cilium Version

Client: 1.12.2 c7516b9 2022-09-14T15:25:06+02:00 go version go1.18.6 linux/amd64
Daemon: 1.12.2 c7516b9 2022-09-14T15:25:06+02:00 go version go1.18.6 linux/amd64

### Kernel Version

Linux k3s-2 5.10.134-12.al8.x86_64 #1 SMP Tue Sep 6 14:59:57 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.25.2+k3s1

### Sysdump

[cilium-sysdump-20221102-112009.zip](https://github.com/cilium/cilium/files/9915647/cilium-sysdump-20221102-112009.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
This policy has two rules:

(1) Allow from 11.0.0.0/16
```
  - fromCIDR:
    - 11.0.0.0/16
```

(2) Allow to port 2049 on TCP
```
  - toPorts:
    - ports:
      - port: "2049"
        protocol: TCP
```

If you want to only allow from 11.0.0.0/16 AND to port 2049, it must be specified as one rule:

```
  - fromCIDR:
    - 11.0.0.0/16
    toPorts:
    - ports:
      - port: "2049"
        protocol: TCP
```
