### ISSUE TITLE
DSR for NodePort with kube-router not working

### ISSUE THREAD

**Issue by damieneichhorn** [cilium/cilium#22015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have a cluster setup, following the kube-proxy replacement and kube-router guide, with the following helm command:

```
helm install cilium cilium/cilium --version 1.12.3 \
   --namespace kube-system \
   --set kubeProxyReplacement=strict \
   --set loadBalancer.mode=dsr \
   --set k8sServiceHost=<ip node 1> \
   --set k8sServicePort=6443 \
   --set hubble.relay.enabled=true \
   --set hubble.ui.enabled=true \
   --set ipam.mode=kubernetes \
   --set ipv4NativeRoutingCIDR=10.42.0.0/16 \
   --set tunnel=disabled
```

The kube-router configuration is as follows(I have omitted everything except the main daemonset):
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-router
    tier: node
  name: kube-router
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kube-router
      tier: node
  template:
    metadata:
      labels:
        k8s-app: kube-router
        tier: node
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: kube-router
      containers:
      - name: kube-router
        image: docker.io/cloudnativelabs/kube-router
        imagePullPolicy: Always
        args:
        - "--run-router=true"
        - "--run-firewall=false"
        - "--run-service-proxy=false"
        - "--bgp-graceful-restart=true"
        - "--enable-cni=false"
        - "--enable-ibgp=true"
        - "--enable-overlay=true"
        - "--advertise-cluster-ip=true"
        - "--advertise-external-ip=true"
        - "--advertise-loadbalancer-ip=true"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        livenessProbe:
          httpGet:
            path: /healthz
            port: 20244
          initialDelaySeconds: 10
          periodSeconds: 3
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: xtables-lock
          mountPath: /run/xtables.lock
          readOnly: false
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
        - name: xtables-lock
          hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
```

I am running a test nginx pod with a NodePort service and externalTrafficPolicy Cluster:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    run: my-nginx
  ports:
  - name: nginx
    protocol: TCP
    port: 80
```

If I try to reach the nginx service there are 2 options:
- I try to reach it on the node that its running on: this works as expected

![Screenshot 2022-11-05 at 15 30 23](https://user-images.githubusercontent.com/9391905/200124835-96d955c8-8913-4bce-9c60-fd22b752a6d4.png)

- I try to reach it on a node it's not directly running on(I expect DSR to work in this case): this doesn't work as it just times out.

![Screenshot 2022-11-05 at 15 32 21](https://user-images.githubusercontent.com/9391905/200124896-914c3852-ce94-4958-9f63-0cb0731d1ffa.png)

Kube router seems to work fine as all the routes are properly injected into the routing tables for each node

**Node 1**
```
10.42.1.0/24 dev tun-511613342 proto 17 src <ip node 1> 
10.42.0.0/24 via 10.42.0.13 dev cilium_host src 10.42.0.13 
10.42.0.13 dev cilium_host scope link 
10.42.2.0/24 dev tun-512228636 proto 17 src <ip node 1> 
```

**Node 2**
```
10.42.0.0/24 dev tun-51797152 proto 17 src <ip node 2>
10.42.1.0/24 via 10.42.1.172 dev cilium_host src 10.42.1.172
10.42.1.172 dev cilium_host scope link 
10.42.2.0/24 dev tun-512228636 proto 17 src <ip node 2> 
```

**Node 3**
```
10.42.0.0/24 dev tun-51797152 proto 17 src <ip node 3>
10.42.2.0/24 via 10.42.2.116 dev cilium_host src 10.42.2.116
10.42.2.116 dev cilium_host scope link
10.42.1.0/24 dev tun-511613342 proto 17 src <ip node 3>  
```

The tunnels for kube-router are also all getting setup correctly:

**Node 1**
```
18: tun-511613342@ens3: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip <ip node 1> peer <ip node 2>
    inet6 fe80::200:5efe:334f:4734/64 scope link 
       valid_lft forever preferred_lft forever
19: tun-512228636@ens3: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip <ip node 1> peer <ip node 3>
    inet6 fe80::200:5efe:334f:4734/64 scope link 
       valid_lft forever preferred_lft forever
```

**Node 2**
```
14: tun-51797152@ens3: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip <ip node 2> peer <ip node 1>
    inet6 fe80::200:5efe:33a1:212a/64 scope link 
       valid_lft forever preferred_lft forever
15: tun-512228636@ens3: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip <ip node 2> peer <ip node 3>
    inet6 fe80::200:5efe:33a1:212a/64 scope link 
       valid_lft forever preferred_lft forever
```

**Node 3**
```
20: tun-51797152@ens3: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip <ip node 3> peer <ip node 1>
    inet6 fe80::200:5efe:33de:5624/64 scope link 
       valid_lft forever preferred_lft forever
21: tun-511613342@ens3: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip <ip node 3> peer <ip node 2>
    inet6 fe80::200:5efe:33de:5624/64 scope link 
       valid_lft forever preferred_lft forever
```

### Cilium Version

1.12.3

### Kernel Version

5.10.0-19-cloud-amd64

### Kubernetes Version

v1.25.3+k3s1

### Sysdump

[cilium-sysdump-20221105-154638.zip](https://github.com/cilium/cilium/files/9944058/cilium-sysdump-20221105-154638.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
