### ISSUE TITLE
Connecting to ClusterIP service not possible from inside service pod with ingress policy

### ISSUE THREAD

**Issue by cyvcloud** [cilium/cilium#22107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Create a simple pod with a ClusterIP service pointing to it:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
```
Connecting to the service from inside the container works as expected:
```
$ kubectl exec -it nginx -- bash
root@nginx:/# curl -v --connect-timeout 5 nginx-service
*   Trying 10.107.234.179:80...
* Connected to nginx-service (10.107.234.179) port 80 (#0)
> GET / HTTP/1.1
> Host: nginx-service
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.22.1
< Date: Fri, 11 Nov 2022 11:08:12 GMT
< Content-Type: text/html
< Content-Length: 615
< Last-Modified: Wed, 19 Oct 2022 08:02:20 GMT
< Connection: keep-alive
< ETag: "634faf0c-267"
< Accept-Ranges: bytes
< 
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
* Connection #0 to host nginx-service left intact
```
Add a network policy allowing ingress access on port 80:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-networkpolicy
spec:
  ingress:
  - ports:
    - port: 80
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: proxy
  policyTypes:
  - Ingress
```
Trying to connect to the service from inside the container now does not work anymore:
```
$ kubectl exec -it nginx -- bash
root@nginx:/# curl -v --connect-timeout 5 nginx-service
*   Trying 10.107.234.179:80...
* Connection timed out after 5001 milliseconds
* Closing connection 0
curl: (28) Connection timed out after 5001 milliseconds
```

### Cilium Version

cilium-cli: v0.12.6 compiled with go1.19.1 on linux/amd64
cilium image (default): v1.12.2
cilium image (stable): v1.12.3
cilium image (running): v1.12.2

### Kernel Version

```yaml
System Info:
  Machine ID:                 1e3016a9d7c74efdbc4c4102e1b1debf
  System UUID:                1e3016a9-d7c7-4efd-bc4c-4102e1b1debf
  Boot ID:                    9541ba81-63ec-4b84-9578-90df63d3b23c
  Kernel Version:             5.4.0-125-generic
  OS Image:                   Ubuntu 20.04.5 LTS
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.6.5
  Kubelet Version:            v1.24.7
  Kube-Proxy Version:         v1.24.7
```

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7", GitCommit:"e6f35974b08862a23e7f4aad8e5d7f7f2de26c15", GitTreeState:"clean", BuildDate:"2022-10-12T10:50:21Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20221111-122534.zip](https://github.com/cilium/cilium/files/9989810/cilium-sysdump-20221111-122534.zip)

### Anything else?

The same behaviour does not occur with Cilium 1.11.10. With this version connecting from the pod to the service with the same NetworkPolicy works as expected.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
