### ISSUE TITLE
Upgrading from 1.12.0 to 1.12.1 and newer breaks hostPort on EKS

### ISSUE THREAD

**Issue by markododa** [cilium/cilium#22139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

With cilium 1.12.0 i can access hostPorts just fine, either from my own daemonset or cilium's

```
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
cilium  kube-system     17              2022-11-14 10:16:25.719711736 +0100 CET deployed        cilium-1.12.0   1.12.0

kubectl exec -ti curl -- curl 192.168.214.147:8123
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>

kubectl exec -ti curl -- curl 192.168.214.147:4244
curl: (52) Empty reply from server
command terminated with exit code 52
```

however when i do an upgrade to 1.12.1 or newer i can no longer access my daemonset, however the cilium port still works

```

helm upgrade -n kube-system -f helm-values.yaml cilium cilium/cilium

NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
cilium  kube-system     18              2022-11-14 10:39:50.303573162 +0100 CET deployed        cilium-1.12.3   1.12.3

kubectl exec -ti curl -- curl 192.168.214.147:8123
curl: (7) Failed to connect to 192.168.214.147 port 8123: Connection refused
command terminated with exit code 7


kubectl exec -ti curl -- curl 192.168.214.147:4244
curl: (52) Empty reply from server
command terminated with exit code 52
```

reverting the version to 1.12.0 fixes the issue

The cilium helm values file is the following

```
USER-SUPPLIED VALUES:
egressMasqueradeInterfaces: eth0
eni:
  enabled: true
hubble:
  listenAddress: :4244
  relay:
    enabled: false
  ui:
    enabled: false
ipam:
  mode: eni
nodeinit:
  enabled: true
operator:
  podAnnotations:
    ad.datadoghq.com/cilium-operator.checks: |
      {
          "cilium": {
              "instances": [
                  {"operator_endpoint": "http://%%host%%:9963/metrics", "use_openmetrics": "true"}
              ]
          }
      }
  prometheus:
    enabled: true
    port: 9963
podAnnotations:
  ad.datadoghq.com/cilium-agent.checks: |
    {
        "cilium": {
            "instances": [
                {"agent_endpoint": "http://%%host%%:9962/metrics", "use_openmetrics": "true"}
            ]
        }
    }
prometheus:
  enabled: true
  port: 9962
tunnel: disabled
```

the example daemonset

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset-test
spec:
  selector:
    matchLabels:
      app: test-networking-nginx
  template:
    metadata:
      labels:
        app: test-networking-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          hostPort: 8123
```
and the curl pod

```
apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  containers:
  - args:
    - -f
    - /dev/null
    command:
      - tail
    image: curlimages/curl
    imagePullPolicy: Always
    name: curl
```

### Cilium Version

1.12.1

### Kernel Version

5.4.209-116.363.amzn2.x86_64

### Kubernetes Version

v1.22.12-eks-ba74326

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
