### ISSUE TITLE
Upgrading Cilium from v1.11.11 to v1.12.4 breaks network connectivity

### ISSUE THREAD

**Issue by nielsvz** [cilium/cilium#22311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrading Cilium using the Helm chart from version 1.11.11 to 1.12.4, several DaemonSets and Deployments are losing network connectivity in our EKS v1.22 cluster.

We're upgrading the Helm chart using the following values:
```yaml
cni:
  chainingMode: aws-cni
enableIPv4Masquerade: false
tunnel: disabled
upgradeCompatibility: "1.11"
```

Looking at the differences between 1.11.11 and 1.12.4, it appears that `defaultKubeProxyReplacement` is set to `probe` in `cilium-configmap.yaml` when `upgradeCompatibility` is set to 1.9-1.11

When explicitly setting `kubeProxyReplacement` to `disabled`, the upgrade is successful; no network connectivity is impacted.

Potentially related to #21255

### Cilium Version

1.11.11

### Kernel Version

n/a

### Kubernetes Version

v1.22.15-eks-fb459a0

### Sysdump

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
