### ISSUE TITLE
ingress: incompatible with cert-manager ACME DNS-01

### ISSUE THREAD

**Issue by nikhiljha** [cilium/cilium#22340]
### What is happening?

With cilium `1.13.0-rc2`, set the default ingress class to `shared` (this functionality was implemented in #21386). Create a basic `ClusterIssuer` for the Let's Encrypt ACME HTTP01 challenge. Create an Ingress with the appropriate annotation and `spec.tls` setup properly. Observe as cert manager spins in a loop and creates hundreds of ingresses.

<img width="822" alt="Screenshot 2022-11-23 at 5 16 06 PM" src="https://user-images.githubusercontent.com/2773700/203672880-f65fb39d-c814-456c-9afc-b96dc843cb1e.png">

### Why is this happening?

This one took me a while to track down!

This happens because **cert-manager does not set ingressClassName**: see https://github.com/cert-manager/cert-manager/commit/65902d57a32fb9cc76bfae24a81400f1560cfc78

If the Kubernetes admission controller sees something without ingressClassName, and without the legacy ingressclass annotation, it will apply the default one ([relevant source lines from kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/network/defaultingressclass/admission.go#L85)), and **in the process, will strip ownerReference**. This causes cert-manager to believe that it doesn't own the ingress, and so it creates a new one, where the ownerReference gets stripped, which causes cert-... you get the point. A control loop creating infinite objects makes my cluster very sad.

### Possible Fixes

- respect the legacy `kubernetes.io/ingress.class` annotation, if `ingressClassName` is not set (apparently every other ingress controller works this way, since cert-manager + HTTP01 ACME seems like a very popular use case)
- decide we won't fix this in cilium, and cert-manager needs to have an option to set `ingressClassName` (which is reasonable)

cc @sayboras 

### Cilium Version

1.13.0-rc2

### Kernel Version

Linux <hostname> 6.0.5-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 26 15:55:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nikhiljha** [comment]
Actually this snippet is a pretty good argument to just fix this in Cilium (respect the legacy annotation)...

https://github.com/kubernetes/kubernetes/blob/45279654db87f4908911569c07afc42804f0e246/plugin/pkg/admission/network/defaultingressclass/admission.go#L106-L109

Kubernetes itself still treats the annotation as "ingressClassName is applied"

**Comment by vincedihub** [comment]
Hello

I have the same problem as post N°1 with the following versions: 

- cert-manager **v1.13.1** 
- cilium **1.14.2** 

I also use the cilium ingress class by default and in share mode.
![image](https://github.com/cilium/cilium/assets/5277569/cc36ed05-c81a-4a5f-9575-71c2747a18ba)


I tried with the annotation kubernetes.io/ingress.class and/or .spec.ingressClassName. 
I've still got 

![image](https://github.com/cilium/cilium/assets/5277569/51a469f2-a5f2-44b7-99b8-773d01612062)

How can I solve the problem?

Thanks in advance for your help

**Comment by raphink** [comment]
Have you specified the `ingressClassName` parameter in your Issuer configuration (as per https://cert-manager.io/docs/configuration/acme/http01/#configuring-the-http01-ingress-solver)?

**Comment by vincedihub** [comment]
I've tested several combinations but always come up with the exact same result. 

However, I found the following error:

![image](https://github.com/cilium/cilium/assets/5277569/8659ff60-d9a5-4f95-ace2-69bc40438692)
It seems that envoy is waiting for something in the kube-system namespace

**Comment by vincedihub** [comment]
Will fix with https://github.com/cilium/cilium/pull/28379

**Comment by vincedihub** [comment]
We found a partial solution 

 We have update the ingress with this annotation : `acme.cert-manager.io/http01-edit-in-place: "true"` .
 See : 
 - https://cert-manager.io/docs/usage/ingress/#supported-annotations
 - https://cert-manager.io/docs/usage/certificate/#temporary-certificates-whilst-issuing
 
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  namespace: my-app-namespace

  annotations:
    cert-manager.io/cluster-issuer: zerossl-production
    acme.cert-manager.io/http01-edit-in-place: "true"
    # kubernetes.io/ingress.class: cilium
    # ingress.cilium.io/service-type: LoadBalancer
    # ingress.cilium.io/loadbalancer-mode: shared
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - app.mydomain.com
    secretName: my-app-tls
  rules:
  - host: app.mydomain.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: my-app-svc
              port:
                number: 9600
```

Now, we don't have many well-know like before.  
Cert-manager add a well-know in the original Ingress request

```yaml
....
     http:
        paths:
        - backend:
            service:
              name: cm-acme-http-solver-69fj5
              port:
                number: 8089
          path: /.well-known/acme-challenge/j_fnZrscaPRqlNTcLh3KmaaE1JPK_tekuM1ZtrLgav0
          pathType: ImplementationSpecific
        - backend:
            service:
              name: transmission-service
              port:
                number: 9091
          path: /
          pathType: Prefix
```

But we have discovered another problem: Cilium does not correctly manage two types of pathType in the same ingress. `pathType: ImplementationSpecific` and `pathType: Prefix`.

We found that `pathType: Prefix` took precedence over `pathType: ImplementationSpecific`which poses a problem.
