### ISSUE TITLE
DNS proxy: preserve security identity (native routing mode)

### ISSUE THREAD

**Issue by aspsk** [cilium/cilium#22366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Summary.** When the DNS proxy issues a request to a remote host, it doesn't preserve the original identity in native routing mode. See the short description and the steps to reproduce the issue, and a hotfix below.  (This issue was fixed for the tunneling mode in the following PRs: https://github.com/cilium/cilium/pull/20711 and https://github.com/cilium/cilium/pull/20859).

**Short description.** When a DNS request from a pod running at node `X` is redirected by the DNS Proxy to a `coredns` instance running on a different node `Y`, the node `Y` sees a request from the `remote-node` identity. This happens because the DNS proxy uses the node IP address to send requests and not the pod's original IP address. So, if an ingress policy exists which allows such a request from this pod, it drops the traffic if traffic from `remote-node` is not allowed specifically.

**How to reproduce.** The simplest way to reproduce is as follows.

Create a cluster and install cilium:
```
make kind kind-image

helm template cilium \
        ./install/kubernetes/cilium \
        --namespace kube-system \
        --set kubeProxyReplacement=strict \
        --set bpf.masquerade=true \
        --set externalIPs.enabled=true \
        --set nodePort.enabled=true \
        --set hostPort.enabled=true \
        --set image.pullPolicy=IfNotPresent \
        --set image.repository=localhost:5000/cilium/cilium-dev \
        --set image.tag=local \
        --set operator.image.repository=localhost:5000/cilium/operator \
        --set operator.image.suffix= \
        --set operator.image.tag=local \
        --set ipam.mode=kubernetes \
        --set autoDirectNodeRoutes=true \
        --set endpointRoutes.enabled=true \
        --set ipv4NativeRoutingCIDR=10.217.0.0/16 \
        --set tunnel=disabled \
        --set bpf.monitorAggregation=low \
        > /tmp/cilium.yaml

kubectl apply -f /tmp/cilium.yaml
```

Apply the following policies:
```
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "egress-dns"
spec:
  endpointSelector:
    matchLabels:
      woo: hoo
  egress:
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
      rules:
        dns:
          - matchPattern: "*"
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "ingress-dns"
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      k8s-app: kube-dns
  ingress:
  - fromEndpoints:
    - {}
    toPorts:
      - ports:
        - port: "53"
          protocol: UDP
```

Create a pod (this pod will use 8.8.8.8 as the DNS server, so it should be able to install all required packets):
```
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: kube-system
  labels:
    woo: hoo
spec:
  nodeSelector:
    kubernetes.io/hostname: kind-worker
  dnsConfig:
    nameservers:
      - 8.8.8.8
  containers:
    - name: test-client
      image: ubuntu:latest
      command:
        - "sh"
        - "-c"
        - |
          /bin/bash <<EOF
          apt update
          apt install -y iproute2 bind9-dnsutils netcat tcpdump netperf iputils-ping
          while :; do sleep 10; date; done
          EOF
```

Next, we need to have a DNS server running on the other node than the pod, e.g.:
```
NAMESPACE     NAME                      READY  STATUS    RESTARTS   AGE   IP             NODE
kube-system   coredns-6d4b75cb6d-5blcf  1/1    Running   0          61m   10.244.1.120   kind-worker
kube-system   coredns-6d4b75cb6d-w9jwz  1/1    Running   0          61m   10.244.0.223   kind-control-plane
kube-system   pod1                      1/1    Running   0          61m   10.244.1.122   kind-worker
```

Then the issue is that the pod can access the DNS at 10.244.1.120, but can't access DNS at 10.244.1.122:
```
root@pod1:/# dig freebsd.org @10.244.1.120 +short
96.47.72.84

root@pod1:/# dig freebsd.org @10.244.0.223 +short

; <<>> DiG 9.18.1-1ubuntu1.2-Ubuntu <<>> freebsd.org @10.244.0.223 +short
;; global options: +cmd
;; connection timed out; no servers could be reached
```

The policy drop looks like this:
```
Policy verdict log: flow 0x62b562ca local EP ID 660, remote ID remote-node, proto 17, ingress, action deny, match none, 172.19.0.2:41299 -> 10.244.0.223:53 udp
```

This happens because the DNS proxy issues a request using the host IP address (observed at the `kind-control-plane` node):
```
# tcpdump -n -i any udp port 53
15:33:03.316223 eth0  In  IP 172.19.0.2.51064 > 10.244.0.223.53: 30015+ [1au] A? freebsd.org. (52)
```

**Hotfix.** Allow traffic from `remote-node` identity, like this:
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "hot-hot-fix"
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      k8s-app: kube-dns
  ingress:
  - fromEntities:
    - remote-node
    toPorts:
      - ports:
        - port: "53"
          protocol: UDP
```
then traffic is allowed:
```
root@pod1:/# dig freebsd.org @10.244.0.223 +short
96.47.72.84

Policy verdict log: flow 0x6b687057 local EP ID 660, remote ID remote-node, proto 17, ingress, action allow, match L3-L4, 172.19.0.2:54958 -> 10.244.0.223:53 udp
```

### Cilium Version

All cilium versions

### Kernel Version

All kernel versions

### Kubernetes Version

All k8s versions

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
