### ISSUE TITLE
Cannot access LoadBalancerIP from host network.

### ISSUE THREAD

**Issue by reitermarkus** [cilium/cilium#22375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

https://github.com/cilium/cilium/issues/12895 seems similar, which is closed without any obvious solution since MetalLB/BGP support was integrated into Cilium.

### What happened?

1. I updated Talos (1.2.7), MetalLB (1.13.7) and Cilium (1.12.3).
2. Noticed that services using `hostNetwork: true` which also have a `LoadBalancer` service cannot be reached anymore on the load balancer IP.
3. Discovered Cilium now has BGP support built-in, so I uninstalled MetalLB (which was using L2 announcements) and configured BGP on my router (OPNsense) and Cilium:
    ```yaml
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: bgp-config
      namespace: kube-system
    data:
      config.yaml: |
        peers:
          - peer-address: 10.0.0.1
            peer-asn: 64512
            my-asn: 64513
        address-pools:
          - name: default
            protocol: bgp
            addresses:
              - 10.0.1.0/24
    ```
4. Deployed `test-lb` NGINX container and service:
    `kubectl get svc/test-lb -o wide` shows:
    ```
    test-lb   LoadBalancer   10.109.14.81   10.0.1.0      80:30558/TCP   28m   svc=test-lb
    ```
    `cilium bpf lb list` shows:
    ```
    10.0.1.0:80            0.0.0.0:0 (368) (0) [LoadBalancer]                                     
                           10.244.0.137:80 (368) (1)                                              
    ```
    
    OPNsense > System > Routes > Status shows a route with:
    ```
    Destination: 10.0.1.0
    Gateway 10.0.0.41 (a node IP)
    ````
5. `curl http://10.0.1.0` does not work from host network.
    `curl http://10.0.0.41:30558` works from host network.
    `curl http://10.0.1.0` works from a pod on the same node.
    `curl http://10.0.0.41:30558` works from a pod on the same node.
    `curl http://10.0.1.0` works from a pod on another node.
    `curl http://10.0.0.41:30558` works from a pod on another node.

### Cilium Version

```
Client: 1.12.3 1c466d2 2022-10-12T11:33:37+01:00 go version go1.18.6 linux/amd64
Daemon: 1.12.3 1c466d2 2022-10-12T11:33:37+01:00 go version go1.18.6 linux/amd64
```

### Kernel Version

```
Linux talos-cp-1 5.15.79-talos #1 SMP Mon Nov 21 12:57:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.25.3
```

### Anything else?

I tried updating Cilium to 1.12.4, but on one of my nodes, the `mount-cgroup` init container fails with `exec format error`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mazzy89** [comment]
I confirm I have the following issue too. It differs from the one of @reitermarkus because I use Cilium Ingress.

Running Cilium 1.12.4 and using the Cilium Ingress feature:

```
kubectl get ingress
NAME       CLASS    HOSTS                   ADDRESS      PORTS     AGE
demo   cilium   app.demo.com   192.0.10.0   80, 443   16h
```

```
kubectl get service
NAME                                     TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
cilium-ingress-demo                  LoadBalancer   10.111.188.199   192.0.10.0    80:32724/TCP,443:32359/TCP   17h
```

IP `192.0.10.0` is provided using L2 announcements from Cilium. 


Services are presents in each node.
```
kubectl exec -nkube-system -i -t cilium-vq6dc -- cilium service list

...
14   192.0.10.0:80           LoadBalancer
15   192.0.10.0:443          LoadBalancer
16   192.168.166.110:32724   NodePort
17   0.0.0.0:32724           NodePort
18   192.168.166.110:32359   NodePort
19   0.0.0.0:32359           NodePort
...
```

**Comment by mazzy89** [comment]
@reitermarkus do you deploy Cilium in a k8s cluster cube-proxy free? Also the `kubeProxyReplacement` is set to `strict`?

**Comment by mazzy89** [comment]
these are the flag I use to configure my Cilium

```
  set {
    name  = "ipam.mode"
    value = "kubernetes"
  }

  set {
    name  = "kubeProxyReplacement"
    value = "strict"
  }

  set {
    name  = "k8sServiceHost"
    value = "192.168.166.2"
  }

  set {
    name  = "k8sServicePort"
    value = "6443"
  }

  set {
    name  = "securityContext.privileged"
    value = "true"
  }

  set {
    name  = "ingressController.enabled"
    value = "true"
  }

  set {
    name  = "bgp.enabled"
    value = "true"
  }

  set {
    name  = "bgp.announce.loadbalancerIP"
    value = "true"
  }

  set {
    name  = "hubble.relay.enabled"
    value = "true"
  }

  set {
    name  = "hubble.ui.enabled"
    value = "true"
  }
```

**Comment by reitermarkus** [comment]
> @reitermarkus do you deploy Cilium in a k8s cluster cube-proxy free? Also the `kubeProxyReplacement` is set to `strict`?

Yes.

I have since found the solution for my problem.

First of all, my network was not configured correctly for BGP. Since I was previously using MetalLB with L2 advertisements, I was using a 10.0.0.0/23 network, with 10.0.0.0/24 being my LAN and 10.0.1.0/24 for MetalLB L2 advertisements. For BGP, I needed to switch my network to 10.0.0.0/24, since otherwise the 10.0.0.0/23 route pointing to my router would be preferred to say a 10.0.1.0/32 route pointing to a K8s node.

After switching from 10.0.0.0/23 to a 10.0.0.0/24 network, I was able to access the LoadBalancer IPs again. Still, LoadBalancer IPs with pods using `hostNetwork: true` still did not work.

For this to work, I had to add 

```yaml
socketLB:
  enabled: true
```

to my Cilium config. It seems like the [documentation](https://docs.cilium.io/en/v1.12/gettingstarted/kubeproxy-free/#kube-proxy-hybrid-modes) is wrong here:

> The following Helm setup below would be equivalent to `kubeProxyReplacement=strict` in a kube-proxy-free environment:
>
> ```
> helm install cilium ./cilium \
>    --namespace kube-system \
>    --set kubeProxyReplacement=partial \
>    --set socketLB.enabled=true \
>    --set nodePort.enabled=true \
>    --set externalIPs.enabled=true \
>    --set hostPort.enabled=true \
>    --set k8sServiceHost=${API_SERVER_IP} \
>    --set k8sServicePort=${API_SERVER_PORT}
> ```

I am using `kubeProxyReplacement: strict` and still had to set `socketLB.enabled` to `true`.

**Comment by reitermarkus** [comment]
For reference, here is my current configuration:

```yaml
kubeProxyReplacement: strict
k8sServiceHost: {{ virtual_ip }}
k8sServicePort: 6443

ipam:
  mode: kubernetes

cni:
  chainingMode: portmap

rollOutCiliumPods: true

bgp:
  enabled: true
  announce:
    loadbalancerIP: true

socketLB:
  enabled: true

autoDirectNodeRoutes: true

tunnel: disabled

ipv4NativeRoutingCIDR: 10.0.0.0/9

enableXTSocketFallback: false

upgradeCompatibility: '1.11'

securityContext:
  privileged: true
```
