### ISSUE TITLE
Pod hostPort not reachable after node restart when GracefulNodeShutdown kublet config set

### ISSUE THREAD

**Issue by yasz24** [cilium/cilium#22460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We found an issue where the pod hostPort connection is refused, following a node restart, after the old pod is deleted.

Here are the steps to reproduce:
Prerequisite:
1. Ensure that the pods for a deployment are scheduled on the same node. Couple ways to achieve this is by having a node pool with only a single worker node or by using a `nodeSelector` on the single pod deployment. (This issue seems to only be reproduced when the new pod is scheduled on the same node as the old one.)
2. Add the GracefulNodeShutdown in the kubelet config on all nodes by modifying the configuration in `/var/lib/kubelet/config.yaml`
```
 featureGates:
   GracefulNodeShutdown: true
 shutdownGracePeriod: 30s
 shutdownGracePeriodCriticalPods: 10s
```
3. Run `sudo systemctl restart kubelet` on each node to apply the kubelet config change.

Reproduce:

1. Deploy the nginx web server with hostPort set as 8081
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/hostname: <node-name>
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          hostPort: 8081
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 20
          httpGet:
            path: /
            port: 80
```
2. ***Important:*** Run `systemctl reboot` on the worker node to restart the machine.
3. After reboot spot the old pod in `Completed` state, while the new pod is `Running`.
```
# k get pods
NAME                                READY   STATUS      RESTARTS   AGE
nginx-deployment-645797c867-8p2hp   0/1     Completed   0          13m
nginx-deployment-645797c867-dx2m8   1/1     Running     0          4m2s
```
4. curl the `nodeIP:hostPort` successfully get the result.
5. Manually deleted the old pod which is in `Completed` state.
6. Redo the curl `nodeIP:hostPort`, but this time the connection refused.

### Cilium Version

v1.12, also on master.

### Kernel Version

 5.4.0-42-generic #46-Ubuntu SMP

### Kubernetes Version

v1.25.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
