### ISSUE TITLE
CFP: Helm chart should follow "Recommended Labels" (app.kubernetes.io/..)

### ISSUE THREAD

**Issue by mkilchhofer** [cilium/cilium#22574]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

In the past, helm charts were not standardized. But at least since [K8s 1.12](https://github.com/kubernetes/website/blob/release-1.12/content/en/docs/concepts/overview/working-with-objects/common-labels.md) it is recommended in the [kubernetes.io/docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/)
use labels with `app.kubernetes.io/xyz`. **Cilium uses an inconsistent labeling format**:
- `k8s-app: xxx` (for hubble-relay, ui, cilium-agent)
- `name: xxx` for cilium-operator

**Describe the feature you'd like**

Follow https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/ and use:
```yaml
app.kubernetes.io/name: cilium
app.kubernetes.io/instance: cilium # might be optional, as cilium cannot be installed twice inside a cluster
app.kubernetes.io/version: "1.2.3"
app.kubernetes.io/managed-by: helm
app.kubernetes.io/component: cilium
```

**(Optional) Describe your proposed solution**

Label selectors are immutable. We need to instruct users howto update to the new label format or introduce a new toggle (or maybe use `.Values.upgradeCompatibility`).

**Links to other issues**:
- https://github.com/cilium/cilium/pull/20213
