### ISSUE TITLE
NetworkPolicy and CiliumNetworkPolicy allow IPv6 egress if 0.0.0.0/0 is allowed

### ISSUE THREAD

**Issue by juliusrickert** [cilium/cilium#22610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When applying a `NetworkPolicy` or a `CiliumNetworkPolicy` which only allows cluster-external traffic to `0.0.0.0/0`, Cilium will continue to allow traffic to cluster-external IPv6 targets.
This behaviour is not present for subnets of `0.0.0.0/0`, like `0.0.0.0/1` or in case an `except` rule is present.

Cilium seems to treat `0.0.0.0/0` differently from other prefixes.

`NetworkPolicy` allowing IPv6 traffic:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ipv4-only
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
    - to:
        - podSelector: {}
    - to:
        - namespaceSelector: {}
```

Same `NetworkPolicy` with `except` rule, blocking IPv6 traffic:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ipv4-except
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 0.0.0.0/8
    - to:
        - podSelector: {}
    - to:
        - namespaceSelector: {}
```

Another `NetworkPolicy` not using `0.0.0.0/0`, blocking IPv6 traffic

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ipv4-only-subnet
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/1
    - to:
        - podSelector: {}
    - to:
        - namespaceSelector: {}
```

`CiliumNetworkPolicy` allowing IPv6 traffic:

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ipv4-only
spec:
  endpointSelector: {}
  egress:
    - toCIDRSet:
        - cidr: 0.0.0.0/0
    - toEndpoints:
        - {}
    - toEntities:
        - cluster
```

Same `CiliumNetworkPolicy` with `except` rule, blocking IPv6 traffic:

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ipv4-except
spec:
  endpointSelector: {}
  egress:
    - toCIDRSet:
        - cidr: 0.0.0.0/0
          except:
            - 0.0.0.0/8
    - toEndpoints:
        - {}
    - toEntities:
        - cluster
```

### Expected bahaviour

I would expect Cilium to treat all IPv4 prefixes the same and not to treat `0.0.0.0/0` differently to allow IPv6 communication as well.

### Cilium Version

Client: 1.12.4 6eaecaf 2022-11-16T05:45:01+00:00 go version go1.18.8 linux/amd64
Daemon: 1.12.4 6eaecaf 2022-11-16T05:45:01+00:00 go version go1.18.8 linux/amd64

### Kernel Version

Linux k8s0-controleplane0 5.19.0-2-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1 (2022-09-24) x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:28:30Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### Anything else?

`cilium status`:
```
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.25 (v1.25.3) [linux/amd64]
Kubernetes APIs:         ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    Strict    [internet 192.0.2.1 2001:db8::1 (Direct Routing)]
Host firewall:           Enabled   [internet]
CNI Chaining:            none
Cilium:                  Ok   1.12.4 (v1.12.4-6eaecaf)
NodeMonitor:             Listening for events on 4 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok   
IPAM:                    IPv4: 4/254 allocated from 10.0.2.0/24, IPv6: 4/65534 allocated from 2001:db8:1f::2:0/112
BandwidthManager:        EDT with BPF [BBR] [internet]
Host Routing:            BPF
Masquerading:            BPF   [internet]   10.0.0.0/8 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       30/30 healthy
Proxy Status:            OK, ip 10.0.2.231, 0 redirects active on ports 10000-20000
Global Identity Range:   min 256, max 65535
Hubble:                  Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 45.90   Metrics: Ok
Encryption:              Disabled
Cluster health:          3/3 reachable   (2022-12-08T00:45:43Z)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Thanks for the report! There's a PR out that looks like it should fix the issue. You're welcome to try out the PR by following the `Image Digests Output` for the image pull step on the PR: https://github.com/cilium/cilium/actions/runs/3691119265/jobs/6249127882

**Comment by juliusrickert** [comment]
I tried it and it works. Thank you very much, @nathanjsweet!

Didn't update without the digest for some reason. Was stuck on 1.12.4.

Additions to Helm values if someone else wants to try:

```yaml
image:
  repository: quay.io/cilium/cilium-ci
  tag: eca53f768761730b6c7106428e9349f7573c00cf
  digest: sha256:8306cf4572eecd58fa7d2929513fad18249c40299326b549d68a3f46d8f4568f
operator:
  replicas: 1
  image:
    repository: quay.io/cilium/operator
    suffix: -ci
    tag: eca53f768761730b6c7106428e9349f7573c00cf
    genericDigest: sha256:c0560e8dc8e734537e0ccabb686a2c56d8ea88031e2266bee8e10f75b43109e1
    useDigest: true
```

In the DaemonSet Pod:

```
# cilium version
Client: 1.13.90 eca53f76 2022-12-08T10:17:49-08:00 go version go1.19.3 linux/amd64
Daemon: 1.13.90 eca53f76 2022-12-08T10:17:49-08:00 go version go1.19.3 linux/amd64
```

**Comment by juliusrickert** [comment]
I just realised that my testing has been too preliminary.

To me, it seems like there is something wrong with policy handling in the PR (49db46744e981f73cc690b3768c2915373b2a930).
It's working fine with 1.12.4, 1.13.0-rc3, and the master (49db46744e981f73cc690b3768c2915373b2a930).

Regardless whether I am applying a `NetworkPolicy` or a `CiliumNetworkPolicy`, the `ipv4-only` policies from my initial report, no traffic is allowed to leave the cluster.

### cilium policy get

#### NetworkPolicy
<details>

```json
[
  {
    "endpointSelector": {
      "matchLabels": {
        "k8s:io.kubernetes.pod.namespace": "cert-manager"
      }
    },
    "egress": [
      {
        "toCIDRSet": [
          {
            "cidr": "0.0.0.0/0"
          }
        ]
      },
      {
        "toEndpoints": [
          {
            "matchLabels": {
              "k8s:io.kubernetes.pod.namespace": "cert-manager"
            }
          }
        ]
      },
      {
        "toEndpoints": [
          {
            "matchExpressions": [
              {
                "key": "k8s:io.kubernetes.pod.namespace",
                "operator": "Exists"
              }
            ]
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "io.cilium.k8s.policy.derived-from",
        "value": "NetworkPolicy",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.name",
        "value": "ipv4-only",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.namespace",
        "value": "cert-manager",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.uid",
        "value": "5d5de8ca-b3b0-458c-8962-2f9ecc9bb3df",
        "source": "k8s"
      }
    ]
  }
]
```

</details>

#### CiliumNetworkPolicy

<details>

```json
[
  {
    "endpointSelector": {
      "matchLabels": {
        "k8s:io.kubernetes.pod.namespace": "cert-manager"
      }
    },
    "egress": [
      {
        "toCIDRSet": [
          {
            "cidr": "0.0.0.0/0"
          }
        ]
      },
      {
        "toEndpoints": [
          {
            "matchLabels": {
              "k8s:io.kubernetes.pod.namespace": "cert-manager"
            }
          }
        ]
      },
      {
        "toEntities": [
          "cluster"
        ]
      }
    ],
    "labels": [
      {
        "key": "io.cilium.k8s.policy.derived-from",
        "value": "CiliumNetworkPolicy",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.name",
        "value": "ipv4-only-still-allowing-ipv6",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.namespace",
        "value": "cert-manager",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.uid",
        "value": "123ca6ec-d25c-49df-9ca1-cbf8ff17290f",
        "source": "k8s"
      }
    ]
  }
]
```

</details>

### Connectivity testing

#### Cilium versions & images

<details>

##### 1.13.0-rc3

```
Client: 1.13.0-rc3 d37596cf 2022-12-01T14:37:11+01:00 go version go1.19.3 linux/amd64
Daemon: 1.13.0-rc3 d37596cf 2022-12-01T14:37:11+01:00 go version go1.19.3 linux/amd64
```

##### master

```
Client: 1.13.90 49db4674 2022-12-12T09:46:52+02:00 go version go1.19.3 linux/amd64
Daemon: 1.13.90 49db4674 2022-12-12T09:46:52+02:00 go version go1.19.3 linux/amd64
```

```yaml
image:
  repository: quay.io/cilium/cilium-ci
  tag: latest
  digest: sha256:2d6382bc65f4d57da43f255c58c66042182b1003b2ede147e562341ee9790e05
operator:
  image:
    repository: quay.io/cilium/operator
    suffix: -ci
    tag: latest
    genericDigest: sha256:5ba41b7c7ada348c14054c3db129e2fecad312df5719a83398d9d977569e81fc
    useDigest: true

```

##### PR

```
Client: 1.13.90 eca53f76 2022-12-08T10:17:49-08:00 go version go1.19.3 linux/amd64
Daemon: 1.13.90 eca53f76 2022-12-08T10:17:49-08:00 go version go1.19.3 linux/amd64
```

```yaml
image:
  repository: quay.io/cilium/cilium-ci
  tag: eca53f768761730b6c7106428e9349f7573c00cf
  digest: sha256:8306cf4572eecd58fa7d2929513fad18249c40299326b549d68a3f46d8f4568f
operator:
  image:
    repository: quay.io/cilium/operator
    suffix: -ci
    tag: eca53f768761730b6c7106428e9349f7573c00cf
    genericDigest: sha256:c0560e8dc8e734537e0ccabb686a2c56d8ea88031e2266bee8e10f75b43109e1
    useDigest: true

```

##### 

</details>

#### Results

| Target | 1.13.0-rc3 (NP) | 1.13.0-rc3 (CNP) | master (NP) | master (CNP) | PR (NP) | PR (CNP) |
| - | - | - | - | - | - | - |
| Same namespace | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| Other namespace | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| Cluster API v4* | ❌ | ✅ | ❌ | ✅ | ❌ | ✅ |
| World v4 | ✅ | ✅ | ✅ | ✅ | ❌ | ❌ |
| World v6 | ✅ | ✅ | ✅ | ✅ | ❌ | ❌ |

\* The Cluster API is shown with its IP address in the `hubble observe` logs, not as a Cilium entity. I will open an issue on the matter.
