### ISSUE TITLE
Reply by local NodePort backend in hostNetwork doesn't get revNATed

### ISSUE THREAD

**Issue by mskrocki** [cilium/cilium#22659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Steps to repro:
1. run 1-replica deployment with hostNetwork enabled:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      containers:
      - name: nginx
        image: nginx:1.14.2
```
3. Create NodePort Service
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
```
5. Get the service's Port
6. Get the Node on which the Pod from 1. runs
7. curl to the Node that has the Pod from 1. running `curl <node_ip>:<nodeport_port>`

In step 7. curl will timeout.

### Cilium Version

Tested with 1.11.7 and 1.12.4

### Kernel Version

5.4.0-42-generic #46-Ubuntu SMP ... x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.25.3

### Sysdump

N/A

### Relevant log output

```shell
IPs:
* 21.0.100.49 <- client
* 21.0.100.111 <- Node with Pod
* 30622 <- Service's Node Port


tcpdump on the client side:
21:54:33.214939 IP 21.0.100.49.49034 > 21.0.100.111.30622: Flags [S], seq 611078560, win 64240, options [mss 1460,sackOK,TS val 2341570527 ecr 0,nop,wscale 7], length 0
21:54:33.215274 IP 21.0.100.111.80 > 21.0.100.49.49034: Flags [S.], seq 5949333, ack 611078561, win 65160, options [mss 1460,sackOK,TS val 2525517164 ecr 2341570527,nop,wscale 7], length 0
21:54:33.215323 IP 21.0.100.49.49034 > 21.0.100.111.80: Flags [R], seq 611078561, win 0, length 0


Dump from `cilium monitor -v` from the node that runs the Pod (different flow than above):

<- network flow 0x68c2c982 , identity unknown->unknown state unknown ifindex ens192 orig-ip 0.0.0.0: 21.0.100.49:54090 -> 21.0.100.111:30622 tcp SYN
CPU 07: MARK 0x68c2c982 FROM 3011 DEBUG: Successfully mapped addr=21.0.100.49 to identity=2
CPU 07: MARK 0x68c2c982 FROM 3011 DEBUG: Conntrack lookup 1/2: src=21.0.100.49:54090 dst=21.0.100.111:30622
CPU 07: MARK 0x68c2c982 FROM 3011 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=4
CPU 07: MARK 0x68c2c982 FROM 3011 DEBUG: CT verdict: New, revnat=0
CPU 07: MARK 0x68c2c982 FROM 3011 DEBUG: Service backend slot lookup: slot=1, dport=30622
CPU 07: MARK 0x68c2c982 FROM 3011 DEBUG: Conntrack create: proxy-port=0 revnat=27 src-identity=0 lb=0.0.0.0
CPU 07: MARK 0x68c2c982 FROM 3011 DEBUG: Conntrack lookup 1/2: src=21.0.100.49:54090 dst=21.0.100.111:80
CPU 07: MARK 0x68c2c982 FROM 3011 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 07: MARK 0x68c2c982 FROM 3011 DEBUG: CT verdict: New, revnat=0
CPU 07: MARK 0x68c2c982 FROM 3011 DEBUG: Conntrack create: proxy-port=0 revnat=27 src-identity=2 lb=21.0.100.111
-> network flow 0x11d9165b , identity unknown->unknown state unknown ifindex 0 orig-ip 0.0.0.0: 21.0.100.111:80 -> 21.0.100.49:54090 tcp SYN, ACK
```

### Anything else?

This issue is not related to #22557. I have reverted #18815 and was able to curl to the service using different Node. Curl to node with the Pod was still failing.

Tested with tunnel enabled and disabled.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
