### ISSUE TITLE
ingress: generated envoy config for TLS is incorrect 

### ISSUE THREAD

**Issue by nikhiljha** [cilium/cilium#22668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. Setup Cilium on Kubernetes 1.25, with Ingress in `loadbalancerMode: "shared"`

<details><summary>Expand: My Helm Configuration Values</summary>

```python
values = {
    "kubeProxyReplacement": "strict",
    "k8sServiceHost": "{snip}",
    "k8sServicePort": "6443",
    "hubble": {
        "tls": {"auto": {"method": "cronJob"}},
        "listenAddress": ":4244",
        "relay": {"enabled": True},
        "ui": {"enabled": True},
    },
    "ipam": {
        "mode": "cluster-pool",
        "operator": {
            "clusterPoolIPv4PodCIDRList": ["10.244.0.0/16"],
            "clusterPoolIPv6PodCIDRList": ["(snip)/112"],
        },
    },
    "bpf": {
      "masquerade": True,
    },
    # needed for bpf masquerade
    "enableIPv6Masquerade": False,
    "ipv6": {
        "enabled": True,
    },
    "ipv4": {
        "enabled": True,
    },
    "k8s": {
        "requireIPv6PodCIDR": True,
        "requireIPv4PodCIDR": True,
    },
    "ingressController": {
        "enabled": True,
        "loadbalancerMode": "shared",
        "enforceHttps": True,
        "service": {
            # Hardcode the shared loadbalancer IP, since lots of external DNS points to it and it should not change easily.
            "annotations": { "metallb.universe.tf/loadBalancerIPs": f"{v4_cidr},{v6_cidr}" },
        },
        # first two are default values, we aren't using them as of 2022
        "ingressLBAnnotationPrefixes": ['service.beta.kubernetes.io', 'service.kubernetes.io', 'metallb.universe.tf'],
    },
}
```

</details>

2. Create two different Ingress in two different namespace, with two different hosts and two different TLS certificates. e.x. `thing1.corp.net` with matching TLS cert, then `thing2.corp.net` with matching TLS cert

3. The envoy config that gets generated looks like (in the ciliumenvoyconfig object for `cilium-ingress` in `kube-system`)...

```yaml
      transportSocket:
        name: envoy.transport_sockets.tls
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          commonTlsContext:
            tlsCertificateSdsSecretConfigs:
            - name: cilium-secrets/thing1-thing1-server-tls
              sdsConfig:
                apiConfigSource:
                  apiType: GRPC
                  grpcServices:
                  - envoyGrpc:
                      clusterName: xds-grpc-cilium
                  transportApiVersion: V3
                resourceApiVersion: V3
            - name: cilium-secrets/thing2-thing2-ingress-tls
              sdsConfig:
                apiConfigSource:
                  apiType: GRPC
                  grpcServices:
                  - envoyGrpc:
                      clusterName: xds-grpc-cilium
                  transportApiVersion: V3
                resourceApiVersion: V3
```

However, according to Envoy docs, specifying the certificates this way means "the first certificate listed is used" -- see https://github.com/envoyproxy/envoy/blob/master/docs/root/intro/arch_overview/security/ssl.rst#certificate-selection. So this means that all Ingresses use `thing1`'s certificate.

Expected behavior: thing1 uses thing1's certificate, and thing2 uses thing2's certificate

Actual behavior: both thing1 and thing2 use thing1's certificate

### Cilium Version

```
cilium-cli: 0.12.11 compiled with go1.19.3 on darwin/arm64
cilium image (default): v1.12.2
cilium image (stable): v1.12.4
cilium image (running): v1.13.0-rc2
```

### Kernel Version

Linux (snip) 6.0.10 #1-NixOS SMP PREEMPT_DYNAMIC Sat Nov 26 08:27:56 UTC 2022 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
