### ISSUE TITLE
CFP: Support filtering by node for Cilium Egress Gateway Policy

### ISSUE THREAD

**Issue by TheGrayFrost** [cilium/cilium#22664]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature request for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your feature request related to a problem?**

All my k8s nodes belong to 2 virtual networks. Suppose Node-1 has IP-1 = 196.168.0.5/24 (in vnet-1) and IP-2 = 172.16.0.5/24 (in vnet-2).
Now, I want some of my pods to be in vnet-1 and some pods to be in vnet-2. The way I am accomplishing this is using Cilium Egress Gateway Policy. I redirect all the outbound 0.0.0.0/0 to go via whichever vnet IP I need.
Eg:
```
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egress-node-1-vnet-2
spec:
  selectors:
    - podSelector:
        matchLabels:
          host: "node-1" # I manually added this label for pods running on node-1
          egress: "vnet-2" # I add this label to pods which should access things in vnet-2
  destinationCIDRs:
    - 0.0.0.0/0
  egressGateway:
    nodeSelector:
      matchLabels:
        kubernetes.io/hostname: node-1
    egressIP: "172.16.0.5" # vnet-2 IP of node-1
```
To reduce the hops, I want to select the node that pod is on, as the gateway node. And then use the correct IP for outbound.

**Describe the feature you'd like**

I want to be able to select pods based on the node they're placed on. Currently CEGP only supports label-based selectors. I can't add the "node name" as label on the pod during creation, as node is decided by the scheduler later.
There might be other use cases where people have multiple IP addresses on their nodes, and want to prefer one for outbound. By default cilium picks the first IP on eth0.

**(Optional) Describe your proposed solution**

Either we can support field selectors in `selectors` for CEGP.
Or we can provide a special label like `io.kubernetes.pod.spec.nodeName` to select nodes (similar to `io.kubernetes.pod.namespace`)
[Note: K8s Scheduler adds a field called spec.nodeName after scheduling the pod.]
