### ISSUE TITLE
Layer 7 Proxy not working as expected

### ISSUE THREAD

**Issue by paulrichter2001** [cilium/cilium#22682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I added annotation to make use of L7 policies, and it breaks cluster communication.

Our cluster is a k3s cluster without flannel.
We install cilium via helm with following flags:
```
helm upgrade \
        cilium/cilium \
        --install \
        --version 1.12.2 \
	--set bpf.masquerade=true \
	--set cluster.id=0 \
	--set cluster.name=testcluster \
	--set egressGateway.enabled=true \
	--set encryption.nodeEncryption=false \
	--set hubble.enabled=true \
	--set hubble.relay.enabled=true \
	--set hubble.ui.enabled=true \
	--set ipam.operator.clusterPoolIPv4PodCIDRList=10.50.0.0/16 \
	--set k8sServiceHost=172.1.1.254 \
	--set k8sServicePort=6443 \
	--set kubeProxyReplacement=strict \
	--set l7Proxy=true \
	--set operator.replicas=1 \
	--set serviceAccounts.cilium.name=cilium \
	--set serviceAccounts.operator.name=cilium-operator  \
	--set tunnel=vxlan

```
			
We deploy a default nginx with default values and a LoadBalancer Service for testing.
We create a ciliumnetworkpolicy to manage ingress traffic.
It works for Layer3/4, ingress to pod is fine, we get a 200 response and see the index.html file.
As soon as we put the visibility expression on a pod (e.g io.cilium.proxy-visibility: "<Ingress/80/TCP/HTTP>") or we add L7 rules to the ingress policy, all traffic to the pod is impossible.

Last entry in the hubble UI.
![image](https://user-images.githubusercontent.com/67266149/207023598-080552b5-014f-4643-abba-f80c4b393002.png)

We don't see L7 information in Hubble.
It works fine as soon as the visibility annotation and the rule for the ciliumnetworkpolicy is removed.

Where do we go wrong? Is there something that we are missing so no packets are finally forwarded to the pod correctly with l7 rules?
Hubble UI both shows that the connection was forwarded successfully.

similar issue on eks: https://github.com/cilium/cilium/issues/19455

### Cilium Version

1.12.2

### Kernel Version

5.15.0-56-generic

### Kubernetes Version

v1.25.4+k3s1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
- Did you try with the latest v1.12 Cilium version?
- Do you also have this issue if you disable the egress gateway feature?
- Could you upload a sysdump of the cluster?

**Comment by paulrichter2001** [comment]
@pchaigno 

- Did you try with the latest v1.12 Cilium version?
  - yes, we tried with version v1.12.4
  - same result
- Do you also have this issue if you disable the egress gateway feature?
  - yes, same result
-  Could you upload a sysdump of the cluster?
   - we changed our current config, because we had some other connectivity issues
   - our current helm values:

      ```
      autoDirectNodeRoutes: true
      bpf:
        masquerade: true
      cluster:
        id: 0
        name: testcluster
      encryption:
        nodeEncryption: false
      externalIPs:
        enabled: true
      hostPort:
        enabled: true
      hubble:
        relay:
          enabled: true
        ui:
          enabled: true
      ipam:
        operator:
          clusterPoolIPv4PodCIDR: 10.50.0.0/16
      ipv4NativeRoutingCIDR: 10.50.0.0/16
      k8sServiceHost: 10.1.1.250
      k8sServicePort: 6443
      kubeProxyReplacement: strict
      l7Proxy: true
      loadBalancer:
        mode: dsr
      nodePort:
        enabled: true
      operator:
        replicas: 2
      serviceAccounts:
        cilium:
          name: cilium
        operator:
          name: cilium-operator
      tunnel: disabled
      ```
   - for the sysdump we used a k8s cluster installed via kubeadm (same result) 
     ```
     NAME          STATUS   ROLES           AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
     tf-master-1   Ready    control-plane   8d    v1.25.5   10.1.1.121    <none>        Ubuntu 22.04.1 LTS   5.15.0-56-generic   containerd://1.6.12
     tf-master-2   Ready    control-plane   8d    v1.25.5   10.1.1.118    <none>        Ubuntu 22.04.1 LTS   5.15.0-56-generic   containerd://1.6.12
     tf-master-3   Ready    control-plane   8d    v1.25.5   10.1.1.123    <none>        Ubuntu 22.04.1 LTS   5.15.0-56-generic   containerd://1.6.12
     tf-worker-1   Ready    <none>          8d    v1.25.5   10.1.1.120    <none>        Ubuntu 22.04.1 LTS   5.15.0-56-generic   containerd://1.6.12
     tf-worker-2   Ready    <none>          8d    v1.25.5   10.1.1.122    <none>        Ubuntu 22.04.1 LTS   5.15.0-56-generic   containerd://1.6.12
     tf-worker-3   Ready    <none>          8d    v1.25.5   10.1.1.119    <none>        Ubuntu 22.04.1 LTS   5.15.0-56-generic   containerd://1.6.12
     ```

   - sysdump: 
     - [sysdump_part1.zip](https://github.com/cilium/cilium/files/10294818/sysdump_part1.zip)
     - [sysdump_part2.zip](https://github.com/cilium/cilium/files/10294819/sysdump_part2.zip)
