### ISSUE TITLE
Using Egress NAT Policies with more than trivial number of CIDR blocks breaks outbound connectivity

### ISSUE THREAD

**Issue by alex-hunt-materialize** [cilium/cilium#22805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using a CiliumEgressNATPolicy with many CIDR blocks, the EgressPolicyMap fills up, and outbound network traffic from some (many) pods fails. This traffic is not marked as denied by cilium when checking with cilium monitor or with hubble.

After it gets into this state, there doesn't seem to be any way to fix it other than to recreate the entire node. Even after removing the offending policy and restarting the cilium agent pods, connectivity is not restored.

This speculatively seems to be caused by cilium filling the EgressPolicyMap and somehow putting the kernel into a bad state, which isn't cleaned up properly by cilium after changing the configuration.

The EgressPolicyMap  can contain a hard-coded maximum of 16535 entries, and seems to contain entries from the entire cluster, not just entries pertaining to pods on that node. It is unclear to me why it would need entries for pods on other nodes, but I haven't read all the relevant code. This drastically impacts the likelihood of hitting this issue in larger clusters. In our case, we had ~60 nodes and 954 pods.

As this map contains entries for every endpoint/destCIDR/gateway combination, the number of entries gets huge very quickly. In our case, we had 65 CIDR blocks in our NAT policy, caused by us essentially wanting all traffic EXCEPT a few CIDR blocks to go through the egress gateway, and there doesn't seem to be any way to create an exclusion rule.

954 pods * 65 CIDR blocks * 1 egress gateway = 62010 entries in a table that can only hold 16535.

### Cilium Version

1.11.11

The code seems to be the same in later versions, though.
https://github.com/cilium/cilium/blob/843c07276ac6029e86d78b60d3bd9f4aff98e8a0/pkg/maps/egressmap/egress.go#L9

### Kernel Version

5.4.219-126.411.amzn2.x86_64

### Kubernetes Version
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14", GitCommit:"3321ffc07d2f046afdf613796f9032f4460de093", GitTreeState:"clean", BuildDate:"2022-11-09T13:40:19Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

### Relevant log output

```shell
Cilium agents spam messages like the following:

cilium-agent level=error msg="Error applying egress gateway policy" destinationCIDR="{18.34.224.0 fffff800}" egressIP=10.2.45.235 error="update failed: no space left on device" gatewayIP=10.2.45.235 sourceIP=10.2.71.60 subsys=egressgateway
```

Evidence the table is full:
```
root@ip-10-2-72-124:/home/cilium# cilium bpf egress list | wc -l
16385
```
```
root@ip-10-2-72-124:/home/cilium# cilium bpf egress list | awk '{ print $1 }' | sort | uniq | wc -l
254
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
Thanks for the report! cc @jibi 

> When using a CiliumEgressNATPolicy with many CIDR blocks,

Could you share the CiliumEgressNATPolicy you were using in your case?

> the EgressPolicyMap fills up, and outbound network traffic from some (many) pods fails.

Do you know how it fails? Is it just failing because the egress NAT policy isn't applied and your network setup requires it? I would have expected for the only impact to be the egress NAT policy to be skipped for some pods.

> After it gets into this state, there doesn't seem to be any way to fix it other than to recreate the entire node. Even after removing the offending policy and restarting the cilium agent pods, connectivity is not restored.

That doesn't seem expected. Do you know if the `update failed: no space left on device` errors kept appearing in logs after you removed all the CiliumEgressNATPolicy objects?

> The EgressPolicyMap can contain a hard-coded maximum of 16535 entries

I've opened https://github.com/cilium/cilium/issues/22929 to add a flag to allow changing that limit.

> The EgressPolicyMap can contain a hard-coded maximum of 16535 entries, and seems to contain entries from the entire cluster, not just entries pertaining to pods on that node.

Hm, that doesn't sound optimal indeed. We probably need the entries to be present only (1) on the node hosting the pods and (2) on the selected gateway node(s). I'm not sure how easily (2) can be implemented as the gateway nodes can change.

> In our case, we had 65 CIDR blocks in our NAT policy, caused by us essentially wanting all traffic EXCEPT a few CIDR blocks to go through the egress gateway, and there doesn't seem to be any way to create an exclusion rule.

It's probably worth creating a feature-request issue for such exclusion rules, if that's something you would be interested in.

**Comment by alex-hunt-materialize** [comment]
> Could you share the CiliumEgressNATPolicy you were using in your case?

It was something like this:
```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
metadata:
  name: storaged-egress
spec:
  destinationCIDRs:
  - 128.0.0.0/1
  - 64.0.0.0/2
  - 32.0.0.0/4
  - 24.0.0.0/5
  - 56.0.0.0/5
  - 4.0.0.0/6
  - 12.0.0.0/6
  - 20.0.0.0/6
  - 48.0.0.0/6
  - 0.0.0.0/7
  - 8.0.0.0/7
  - 16.0.0.0/7
  - 2.0.0.0/8
  - 11.0.0.0/8
  - 19.0.0.0/8
  - 53.0.0.0/8
  - 55.0.0.0/8
  - 3.128.0.0/9
  - 10.128.0.0/9
  - 18.128.0.0/9
  - 52.0.0.0/9
  - 54.0.0.0/9
  - 3.64.0.0/10
  - 10.64.0.0/10
  - 18.64.0.0/10
  - 52.128.0.0/10
  - 54.128.0.0/10
  - 3.32.0.0/11
  - 10.32.0.0/11
  - 18.0.0.0/11
  - 52.224.0.0/11
  - 54.192.0.0/11
  - 3.16.0.0/12
  - 10.16.0.0/12
  - 18.48.0.0/12
  - 52.192.0.0/12
  - 54.240.0.0/12
  - 3.8.0.0/13
  - 10.8.0.0/13
  - 18.40.0.0/13
  - 52.208.0.0/13
  - 54.232.0.0/13
  - 3.0.0.0/14
  - 10.4.0.0/14
  - 18.36.0.0/14
  - 52.220.0.0/14
  - 54.224.0.0/14
  - 3.6.0.0/15
  - 10.0.0.0/15
  - 18.32.0.0/15
  - 52.218.0.0/15
  - 54.228.0.0/15
  - 3.4.0.0/16
  - 10.3.0.0/16
  - 18.35.0.0/16
  - 54.230.0.0/16
  - 3.5.128.0/17
  - 3.5.64.0/18
  - 18.34.64.0/18
  - 18.34.128.0/18
  - 3.5.32.0/19
  - 18.34.32.0/19
  - 18.34.192.0/19
  - 18.34.240.0/20
  - 18.34.224.0/21
  egress:
  - podSelector:
      matchExpressions:
      - key: environmentd.materialize.cloud/namespace
        operator: In
        values:
        - storage
        - compute
  egressSourceIP: 10.2.67.59
```

> Do you know how it fails? Is it just failing because the egress NAT policy isn't applied and your network setup requires it? I would have expected for the only impact to be the egress NAT policy to be skipped for some pods.

I think it was all traffic, but I don't remember for sure. It was almost a month ago.

> Do you know if the `update failed: no space left on device` errors kept appearing in logs after you removed all the CiliumEgressNATPolicy objects?

I don't sorry. If I have time I may try to reproduce this, but I can't promise I'll get to it.

> I've opened https://github.com/cilium/cilium/issues/22929 to add a flag to allow changing that limit.

Thank you!

> Hm, that doesn't sound optimal indeed. We probably need the entries to be present only (1) on the node hosting the pods and (2) on the selected gateway node(s). I'm not sure how easily (2) can be implemented as the gateway nodes can change.

In our case, most of the egress for the cluster will be going through the egress gateway nodes, so those nodes may hit this limit pretty easily.
