### ISSUE TITLE
CFP: Egress Gateway destinationCIDRs exclusions

### ISSUE THREAD

**Issue by alex-hunt-materialize** [cilium/cilium#23002]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

Egress Gateway policies are difficult to configure in the common case of wanting a default route through the gateway, but some traffic to not go through the gateway.

This is exacerbated by the the inability to support large number of CIDRs due to BPF map size limits.
https://github.com/cilium/cilium/issues/22805
https://github.com/cilium/cilium/issues/22929

For example, the following policy would be much simpler to define and would require a much smaller map if we could use a destination of `0.0.0.0/0` with a few exclusions.

```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
metadata:
  name: storaged-egress
spec:
  destinationCIDRs:
  - 128.0.0.0/1
  - 64.0.0.0/2
  - 32.0.0.0/4
  - 24.0.0.0/5
  - 56.0.0.0/5
  - 4.0.0.0/6
  - 12.0.0.0/6
  - 20.0.0.0/6
  - 48.0.0.0/6
  - 0.0.0.0/7
  - 8.0.0.0/7
  - 16.0.0.0/7
  - 2.0.0.0/8
  - 11.0.0.0/8
  - 19.0.0.0/8
  - 53.0.0.0/8
  - 55.0.0.0/8
  - 3.128.0.0/9
  - 10.128.0.0/9
  - 18.128.0.0/9
  - 52.0.0.0/9
  - 54.0.0.0/9
  - 3.64.0.0/10
  - 10.64.0.0/10
  - 18.64.0.0/10
  - 52.128.0.0/10
  - 54.128.0.0/10
  - 3.32.0.0/11
  - 10.32.0.0/11
  - 18.0.0.0/11
  - 52.224.0.0/11
  - 54.192.0.0/11
  - 3.16.0.0/12
  - 10.16.0.0/12
  - 18.48.0.0/12
  - 52.192.0.0/12
  - 54.240.0.0/12
  - 3.8.0.0/13
  - 10.8.0.0/13
  - 18.40.0.0/13
  - 52.208.0.0/13
  - 54.232.0.0/13
  - 3.0.0.0/14
  - 10.4.0.0/14
  - 18.36.0.0/14
  - 52.220.0.0/14
  - 54.224.0.0/14
  - 3.6.0.0/15
  - 10.0.0.0/15
  - 18.32.0.0/15
  - 52.218.0.0/15
  - 54.228.0.0/15
  - 3.4.0.0/16
  - 10.3.0.0/16
  - 18.35.0.0/16
  - 54.230.0.0/16
  - 3.5.128.0/17
  - 3.5.64.0/18
  - 18.34.64.0/18
  - 18.34.128.0/18
  - 3.5.32.0/19
  - 18.34.32.0/19
  - 18.34.192.0/19
  - 18.34.240.0/20
  - 18.34.224.0/21
  egress:
  - podSelector:
      matchExpressions:
      - key: environmentd.materialize.cloud/namespace
        operator: In
        values:
        - storage
        - compute
  egressSourceIP: 10.2.67.59
```

**Describe the feature you'd like**

The ability to specify CIDR block exclusions in the egress gateway policies.

**(Optional) Describe your proposed solution**

Add an additional field to the policy spec for `excludeCIDRs`.
Add an additional BPF map to hold the excluded CIDR blocks.
When deciding whether to route traffic through the egress gateway, also consult the map of excluded CIDR blocks.
