### ISSUE TITLE
Support names for the ICMP and ICMPv6 types

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#23000]
The ICMP policies currently require users to provide the specific ICMP and ICMPv6 types for the messages they want to allow through. The goal would be to support something like:
```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "icmp-rule"
spec:
  endpointSelector:
    matchLabels:
      app: myService
  egress:
  - icmps:
    - fields:
      - type: Echo
        family: IPv4
      - type: Echo Request
        family: IPv6
```
