### ISSUE TITLE
bgp-announce-lb-ip with kube-proxy-replacement=probe, traffic fails with load balancer ip

### ISSUE THREAD

**Issue by tedli** [cilium/cilium#23010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have a working cluster. I want to evaluate the `loadbalancer` feature. BGP announced with no error reported, ingress ip assigned in service status.

But access that load balancer ip outside cluster fails, meanwhile inside cluster this ip works.

If I config `kube-proxy-replacement` to `disabled`, load balancer ip works both inside and outside cluster.

### Cilium Version

v1.11.2

### Kernel Version

4.19.91-24.8.an8.x86_64

### Kubernetes Version

v1.19.7

### Relevant log output

My cilium config map:

```yaml
apiVersion: v1
data:
  auto-direct-node-routes: "true"
  bgp-announce-lb-ip: "true"
  bpf-lb-acceleration: native
  bpf-lb-algorithm: maglev
  bpf-lb-mode: dsr
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  cluster-name: default
  cluster-pool-ipv4-cidr: 172.24.68.0/22
  cluster-pool-ipv4-mask-size: "24"
  debug: "false"
  disable-cnp-status-updates: "true"
  enable-auto-protect-node-port-range: "true"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "false"
  enable-endpoint-health-checking: "true"
  enable-ipv4: "true"
  enable-ipv4-masquerade: "false"
  enable-ipv6: "false"
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  ipam: cluster-pool
  k8s-require-ipv4-pod-cidr: "true"
  k8s-require-ipv6-pod-cidr: "false"
  kube-proxy-replacement: probe
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  node-port-mode: dsr
  operator-api-serve-addr: 127.0.0.1:9234
  preallocate-bpf-maps: "false"
  sidecar-istio-proxy-image: cilium/istio_proxy
  tofqdns-enable-poller: "false"
  tunnel: disabled
  wait-bpf-mount: "false"
```

cilium status output:
```shell
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.19 (v1.19.7) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Probe   [eth2 10.206.67.114 (Direct Routing)]
Host firewall:          Disabled
Cilium:                 Ok   1.11.2 (v1.11.2-17b0dbd)
NodeMonitor:            Disabled
Cilium health daemon:   Ok   
IPAM:                   IPv4: 11/254 allocated from 172.24.68.0/24, 
Allocated addresses:
  172.24.68.119 (kstone/kstone-inspection-controller-fcb4fb4fd-jwbdk[restored])
  172.24.68.123 (kube-system/kstone-tapp-69b7997cf5-x5b8t[restored])
  172.24.68.130 (kstone/kstone-dashboard-api-569978ff7f-gkzq9[restored])
  172.24.68.133 (router)
  172.24.68.154 (kstone/kstone-etcd-controller-7c848f6bff-qj7qb[restored])
  172.24.68.211 (kstone/kstone-grafana-7764d7dcdb-lrjmp[restored])
  172.24.68.222 (kstone/test12-etcd-2[restored])
  172.24.68.245 (health)
  172.24.68.253 (lm-test/kubecluster-sample-1-21-3-etcd-1[restored])
  172.24.68.4 (kube-system/open-local-controller-58dfb5fff-gt6qj[restored])
  172.24.68.59 (qihoo-system/loadbalancers-babel-controller-manager-55665c89f6-6hvz9[restored])
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           Disabled
Clock Source for BPF:   ktime
Controller Status:      66/66 healthy
  Name                                          Last success   Last error   Count   Message
  bpf-map-sync-cilium_lxc                       5s ago         never        0       no error   
  cilium-health-ep                              59s ago        never        0       no error   
  dns-garbage-collector-job                     7s ago         never        0       no error   
  endpoint-1060-regeneration-recovery           never          never        0       no error   
  endpoint-1628-regeneration-recovery           never          never        0       no error   
  endpoint-193-regeneration-recovery            never          never        0       no error   
  endpoint-197-regeneration-recovery            never          never        0       no error   
  endpoint-271-regeneration-recovery            never          never        0       no error   
  endpoint-2844-regeneration-recovery           never          never        0       no error   
  endpoint-2850-regeneration-recovery           never          never        0       no error   
  endpoint-441-regeneration-recovery            never          never        0       no error   
  endpoint-54-regeneration-recovery             never          never        0       no error   
  endpoint-55-regeneration-recovery             never          never        0       no error   
  endpoint-826-regeneration-recovery            never          never        0       no error   
  endpoint-gc                                   4m7s ago       never        0       no error   
  ipcache-inject-labels                         18m31s ago     34m6s ago    0       no error   
  k8s-heartbeat                                 7s ago         never        0       no error   
  mark-k8s-node-as-available                    34m0s ago      never        0       no error   
  metricsmap-bpf-prom-sync                      2s ago         never        0       no error   
  neighbor-table-refresh                        0s ago         never        0       no error   
  resolve-identity-271                          3m59s ago      never        0       no error   
  restoring-ep-identity (1060)                  33m35s ago     never        0       no error   
  restoring-ep-identity (1628)                  33m35s ago     never        0       no error   
  restoring-ep-identity (193)                   33m35s ago     never        0       no error   
  restoring-ep-identity (197)                   33m35s ago     never        0       no error   
  restoring-ep-identity (2844)                  34m0s ago      never        0       no error   
  restoring-ep-identity (2850)                  33m35s ago     never        0       no error   
  restoring-ep-identity (441)                   33m35s ago     never        0       no error   
  restoring-ep-identity (54)                    33m35s ago     never        0       no error   
  restoring-ep-identity (55)                    33m35s ago     never        0       no error   
  restoring-ep-identity (826)                   33m35s ago     never        0       no error   
  sync-endpoints-and-host-ips                   0s ago         never        0       no error   
  sync-lb-maps-with-k8s-services                34m0s ago      never        0       no error   
  sync-policymap-1060                           30s ago        never        0       no error   
  sync-policymap-1628                           30s ago        never        0       no error   
  sync-policymap-193                            30s ago        never        0       no error   
  sync-policymap-197                            30s ago        never        0       no error   
  sync-policymap-271                            30s ago        never        0       no error   
  sync-policymap-2844                           30s ago        never        0       no error   
  sync-policymap-2850                           30s ago        never        0       no error   
  sync-policymap-441                            30s ago        never        0       no error   
  sync-policymap-54                             30s ago        never        0       no error   
  sync-policymap-55                             30s ago        never        0       no error   
  sync-policymap-826                            30s ago        never        0       no error   
  sync-to-k8s-ciliumendpoint (1060)             5s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (1628)             5s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (193)              5s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (197)              5s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (271)              9s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (2844)             0s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (2850)             5s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (441)              5s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (54)               5s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (55)               5s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (826)              5s ago         never        0       no error   
  template-dir-watcher                          never          never        0       no error   
  update-k8s-node-annotations                   34m6s ago      never        0       no error   
  waiting-initial-global-identities-ep (1060)   33m35s ago     never        0       no error   
  waiting-initial-global-identities-ep (1628)   33m35s ago     never        0       no error   
  waiting-initial-global-identities-ep (193)    33m35s ago     never        0       no error   
  waiting-initial-global-identities-ep (197)    33m35s ago     never        0       no error   
  waiting-initial-global-identities-ep (2850)   33m35s ago     never        0       no error   
  waiting-initial-global-identities-ep (441)    33m35s ago     never        0       no error   
  waiting-initial-global-identities-ep (54)     33m35s ago     never        0       no error   
  waiting-initial-global-identities-ep (55)     33m35s ago     never        0       no error   
  waiting-initial-global-identities-ep (826)    33m35s ago     never        0       no error   
Proxy Status:   OK, ip 172.24.68.133, 0 redirects active on ports 10000-20000
Hubble:         Disabled
KubeProxyReplacement Details:
  Status:                 Probe
  Socket LB Protocols:    TCP, UDP
  Devices:                eth2 10.206.67.114 (Direct Routing)
  Mode:                   DSR
  Backend Selection:      Maglev (Table Size: 16381)
  Session Affinity:       Enabled
  Graceful Termination:   Enabled
  XDP Acceleration:       Native
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Enabled (Range: 30000-32767) 
  - LoadBalancer:   Enabled 
  - externalIPs:    Enabled 
  - HostPort:       Enabled
BPF Maps:   dynamic sizing: on (ratio: 0.002500)
  Name                          Size
  Non-TCP connection tracking   589737
  TCP connection tracking       1179474
  Endpoint policy               65535
  Events                        40
  IP cache                      512000
  IP masquerading agent         16384
  IPv4 fragmentation            8192
  IPv4 service                  65536
  IPv6 service                  65536
  IPv4 service backend          65536
  IPv6 service backend          65536
  IPv4 service reverse NAT      65536
  IPv6 service reverse NAT      65536
  Metrics                       1024
  NAT                           1179474
  Neighbor table                1179474
  Global policy                 16384
  Per endpoint policy           65536
  Session affinity              65536
  Signal                        40
  Sockmap                       65535
  Sock reverse NAT              589737
  Tunnel                        65536
Encryption:                                         Disabled
Cluster health:                                     3/3 reachable   (2023-01-10T09:26:41Z)
  Name                                              IP              Node        Endpoints
  docker13.xxxx (localhost)   10.206.67.114   reachable   reachable
  docker11.xxxx               10.206.67.95    reachable   reachable
  docker12.xxxx               10.206.67.96    reachable   reachable
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
