### ISSUE TITLE
BGP: Support MD5 Authentication

### ISSUE THREAD

**Issue by camrossi** [cilium/cilium#23052]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

For most production environment configuring BGP MD5 authentication is considered a must and a best practice 

**Describe the feature you'd like**

This feature was already discussed in this comment: https://github.com/cilium/cilium/issues/19376#issuecomment-1099904483
however I do not think was ever implemented, since goBGP already support Password Authentication this should be easy to implement. Something like this would work great:

```
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: rack2
  namespace: kube-system
spec:
 nodeSelector:
   matchLabels:
     rack_id: "2"
 virtualRouters: # []CiliumBGPVirtualRouter
 - localASN: 65003
   exportPodCIDR: true
   neighbors: # []CiliumBGPNeighbor
    - peerAddress: "192.168.11.203/32"
      peerASN: 65002
      peerPassword:
        secretKeyRef:
          name: bgp-password
          key: password
```
