### ISSUE TITLE
Traffic being dropped when pod_name == value of label 

### ISSUE THREAD

**Issue by sec** [cilium/cilium#23154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have hit a strange issue on our env. Looks like traffic is being dropped, when it should be allowed.
Short setup is something like
```
apiVersion: v1
kind: Pod
metadata:
  name: some-pod
  labels:
    app: some-pod
```
and having NetworkPolicy with
```
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app: some-pod
```

Traffic is blocked, doing change in label (ex. adding -anything) to both pod label and policy makes the traffic flow.

### Cilium Version

cilium image (default): v1.12.5
cilium image (stable): v1.12.5
cilium image (running): v1.11.1-gke3.8.1

### Kernel Version

5.10.147+

### Kubernetes Version

v1.23.13-gke.900

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
