### ISSUE TITLE
SNAT of ICMP echo request packets through an egress gateway breaks after upgrade to v1.12.4 

### ISSUE THREAD

**Issue by dhedberg** [cilium/cilium#23173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrading cilium to v1.12.4 (or v1.12.5), ping no longer works. Reverting to v1.12.3 restores the functionality. Other traffic, like https, works.

192.168.123.11 is the ip on eth1 on the node k8c1 acting as the gateway, 192.168.3.182 is the IP of the pod running on another node.

Running tcpdump with v1.12.3 shows the correct IP as source (reproduced in a VM):

```
21:31:58.515439 52:54:00:f3:cc:35 > 52:54:00:01:35:68, ethertype IPv4 (0x0800), length 98: 192.168.123.11 > 192.168.123.12: ICMP echo request, id 65327, seq 0, length 64
```

The same request with v1.12.4 results in requests like:
```
21:26:04.036635 52:54:00:f3:cc:35 > 52:54:00:01:35:68, ethertype IPv4 (0x0800), length 98: 192.168.3.182 > 192.168.123.12: ICMP echo request, id 3307, seq 0, length 64
```

The same issue is also seen for IPs outside of the network in question:
```
22:32:11.447417 52:54:00:f3:cc:35 > 52:54:00:01:35:68, ethertype IPv4 (0x0800), length 98: 192.168.3.182 > 134.25.4.140: ICMP echo request, id 3322, seq 0, length 64
```

Policy:
```
---
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: some-policy
spec:
  destinationCIDRs:
  - 0.0.0.0/0
  egressGateway:
    interface: eth1
    nodeSelector:
      matchLabels:
        kubernetes.io/hostname: k8c1
  selectors:
  - podSelector:
      matchLabels:
        some/label: value
```

### Cilium Version

v1.12.4

### Kernel Version

Linux test 5.14.21-150400.24.21-default #1 SMP PREEMPT_DYNAMIC Wed Sep 7 06:51:18 UTC 2022 (974d0aa) x86_64 GNU/Linux

### Kubernetes Version

v1.25.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
