### ISSUE TITLE
Ingress: No healthy upstream for headless service

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#23182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

Reported by: @knfoo

### What happened?

If the Ingress is configured with a headless service like below, the response from the Ingress route is coming back as `no healthy upstream`. Ideally, the request should be coming IP (which is specified in Endpoint object of the headless Service)

```yaml
apiVersion: v1
kind: Service
metadata:
  name: details-headless
  namespace: default
spec:
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  clusterIP: None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
---
apiVersion: v1
kind: Endpoints
metadata:
  name: details-headless
  namespace: default
subsets:
- addresses:
  - ip: 10.244.0.95 # manually configure this Endpoints resource with valid backend IP
  ports:
  - name: http
    port: 9080
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress-headless
  namespace: default
spec:
  ingressClassName: cilium
  rules:
  - http:
      paths:
      - backend:
          service:
            name: details-headless
            port:
              number: 9080
        path: /details
        pathType: Prefix
---
```

### Cilium Version

1.13.x
1.12.x

### Kernel Version

N/A

### Kubernetes Version

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
Upon investigating this issue, I found out that endpoint IP is not bumped to Envoy due to below code block, which skipped further processing of Service.

https://github.com/cilium/cilium/blob/07dea5d1da0337ff2e5c27ef993a1e8f5fa41047/pkg/k8s/watchers/watcher.go#L902-L904

Seems like it's a side effect of having shared code between Service watcher and Envoy

https://github.com/cilium/cilium/issues/19698
> Move Envoy specifics from pkg/service to pkg/k8s/watchers, see https://github.com/cilium/cilium/pull/18894#discussion_r840633249 

The workaround is to add dummy Service IP like below.

```
apiVersion: v1
kind: Service
metadata:
  name: details-headless
  namespace: default
spec:
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  clusterIP: 192.192.192.192 --> dummy IP, this should belong to service CIDR of cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
```

**Comment by youngnick** [comment]
Should be fixed by #25105 ?

**Comment by sayboras** [comment]
yes, I am marking the above PR as draft to add e2e test.

**Comment by tchellomello** [comment]
@sayboras I'm hitting this problem on the latest `v1.15.5`. Are there any plans to get this addressed?

**Comment by sayboras** [comment]
Thanks for your comment, the approach in mentioned PR is no longer ideal due to recent refactor and discussion. 

I am currently exploring alternative options now.

**Comment by tchellomello** [comment]
@sayboras I appreciate the update. I'll be tuned in and please let me know how I can help testing.

**Comment by sayboras** [comment]
Thanks, can you help to test out the changes in https://github.com/cilium/cilium/pull/32644, the image digests can be found in the below CI job:

https://github.com/cilium/cilium/actions/runs/9203017338/job/25314240955?pr=32644

**Comment by tchellomello** [comment]
@sayboras just to make sure I'll test it properly. 

I need to replace the container image "cilium" by the "cilium-ci", right?

Do I need to replace the operator, clustermesh and all other images too? 

Furthermore, I'm running envoy as a dedicated daemonset, but I don't see in that CI job the `cilium-envoy`. Is that OK?

**Comment by sayboras** [comment]
> I need to replace the container image "cilium" by the "cilium-ci", right? Do I need to replace the operator, clustermesh and all other images too? 

Yes, you are right. For this change, the operator is not required to be updated, however, no harm to keep them in sync. 

> Furthermore, I'm running envoy as a dedicated daemonset, but I don't see in that CI job the cilium-envoy. Is that OK?

Cilium Envoy is built from cilium/proxy repo, no change is required.

**Comment by tchellomello** [comment]
@sayboras I was going to post on the PR but decided to do here instead. Not sure exactly the reason but this is pretty odd. I'm using a BGP Announcements on my cluster and as soon as changed the operator and the cilium images to CI, I cannot connect to the my HTTP Gateway (however other services exposed via Loadbalancer and shared via BGP are working). It seems something is up with the envoy gateway directly. Check it out: 

1. Images and status
```yaml
cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    OK
 \__/¯¯\__/    Hubble Relay:       OK
    \__/       ClusterMesh:        OK

DaemonSet              cilium-envoy             Desired: 4, Ready: 4/4, Available: 4/4
Deployment             hubble-ui                Desired: 1, Ready: 1/1, Available: 1/1
Deployment             cilium-operator          Desired: 1, Ready: 1/1, Available: 1/1
Deployment             hubble-relay             Desired: 1, Ready: 1/1, Available: 1/1
DaemonSet              cilium                   Desired: 4, Ready: 4/4, Available: 4/4
Deployment             clustermesh-apiserver    Desired: 1, Ready: 1/1, Available: 1/1
Containers:            cilium-envoy             Running: 4
                       hubble-ui                Running: 1
                       clustermesh-apiserver    Running: 1
                       cilium-operator          Running: 1
                       hubble-relay             Running: 1
                       cilium                   Running: 4
Cluster Pods:          139/139 managed by Cilium
Helm chart version:    
Image versions         hubble-ui                quay.io/cilium/hubble-ui:v0.13.0@sha256:7d663dc16538dd6e29061abd1047013a645e6e69c115e008bee9ea9fef9a6666: 1
                       hubble-ui                quay.io/cilium/hubble-ui-backend:v0.13.0@sha256:1e7657d997c5a48253bb8dc91ecee75b63018d16ff5e5797e5af367336bc8803: 1
                       clustermesh-apiserver    quay.io/cilium/clustermesh-apiserver:v1.15.5@sha256:914549caf4376a844b5e7696019182dd2a655b89d6a3cad10f9d0f9821759fd7: 2
                       cilium-operator          quay.io/cilium/operator-generic-ci:a83a327fd6663778cb3af62fb9254f05ef66206d@sha256:5edbb65701aec94e81c89613c0275b9584d7c73897f7c3185f4b6ce44e85fd53: 1
                       hubble-relay             quay.io/cilium/hubble-relay:v1.15.5@sha256:1d24b24e3477ccf9b5ad081827db635419c136a2bd84a3e60f37b26a38dd0781: 1
                       cilium                   quay.io/cilium/cilium-ci:a83a327fd6663778cb3af62fb9254f05ef66206d@sha256:8a6169c94371ec59ac4f3c431dc7c2606a37678b2398498d907a9f18928f0c7d: 4
                       cilium-envoy             quay.io/cilium/cilium-envoy:v1.28.3-31ec52ec5f2e4d28a8e19a0bfb872fa48cf7a515@sha256:bc8dcc3bc008e3a5aab98edb73a0985e6ef9469bda49d5bb3004c001c995c380: 4
```

2. Gateway up
```yaml
kubectl get gateway -n public-gateway 
NAME     CLASS    ADDRESS         PROGRAMMED   AGE
public   cilium   192.168.108.7   True         10d

kubectl get svc -n public-gateway 
NAME                    TYPE           CLUSTER-IP    EXTERNAL-IP     PORT(S)                      AGE
cilium-gateway-public   LoadBalancer   10.105.54.2   192.168.108.7   443:32005/TCP,80:30343/TCP   10d
```
3. BPG routes correct
```yaml
cilium  bgp routes 
(Defaulting to `available ipv4 unicast` routes, please see help for more options)

Node               VRouter   Prefix              NextHop   Age     Attrs
p53.tatu.home      64552     192.168.108.1/32    0.0.0.0   8m13s   [{Origin: i} {Nexthop: 0.0.0.0}]   
  
                   64552     192.168.108.4/32    0.0.0.0   8m13s   [{Origin: i} {Nexthop: 0.0.0.0}]   

                   64552     192.168.108.7/32    0.0.0.0   8m13s   [{Origin: i} {Nexthop: 0.0.0.0}]   
 
                   64552     192.168.108.9/32    0.0.0.0   8m13s   [{Origin: i} {Nexthop: 0.0.0.0}]   
p70.tatu.home      64552     192.168.108.1/32    0.0.0.0   7m52s   [{Origin: i} {Nexthop: 0.0.0.0}]     
 
                   64552     192.168.108.7/32    0.0.0.0   7m52s   [{Origin: i} {Nexthop: 0.0.0.0}]   
  
t470n1.tatu.home   64552     192.168.108.1/32    0.0.0.0   7m48s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                   64552     192.168.108.7/32    0.0.0.0   7m48s   [{Origin: i} {Nexthop: 0.0.0.0}]   
  
t470n2.tatu.home   64552     192.168.108.1/32    0.0.0.0   8m11s   [{Origin: i} {Nexthop: 0.0.0.0}]    
                   64552     192.168.108.7/32    0.0.0.0   8m11s   [{Origin: i} {Nexthop: 0.0.0.0}]   

```

5. Other services exposed working
```yaml
❯ kubectl get svc -n default postgresql-toca
NAME              TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)          AGE
postgresql-toca   LoadBalancer   10.108.198.10   192.168.108.4   5432:30557/TCP   5d21h

❯ psql -h 192.168.108.4
psql (16.2, server 15.2 (Debian 15.2-1.pgdg110+1))
Type "help" for help.

postgres=# 
```

6. HTTPRoute is accepted 
```yaml
kubectl describe httproutes.gateway.networking.k8s.io  -n mattermost mattermost-public
Name:         mattermost-public
Namespace:    mattermost
Labels:       app.kubernetes.io/instance=mattermost
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1
Kind:         HTTPRoute
Metadata:
  Creation Timestamp:  2024-05-20T16:33:47Z
  Generation:          7
  Resource Version:    857653081
  UID:                 9164c8f7-3b7b-4877-ba85-7515e5df1ab4
Spec:
  Parent Refs:
    Group:         gateway.networking.k8s.io
    Kind:          Gateway
    Name:          public
    Namespace:     public-gateway
    Section Name:  https-main
  Rules:
    Backend Refs:
      Group:   
      Kind:    Service
      Name:    mmtatu-workaround
      Port:    8065
      Weight:  1
    Matches:
      Path:
        Type:   PathPrefix
        Value:  /mmgtest
Status:
  Parents:
    Conditions:
      Last Transition Time:  2024-05-25T14:43:30Z
      Message:               Accepted HTTPRoute
      Observed Generation:   7
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2024-05-25T14:43:30Z
      Message:               Service reference is valid
      Observed Generation:   7
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Controller Name:         io.cilium/gateway-controller
    Parent Ref:
      Group:         gateway.networking.k8s.io
      Kind:          Gateway
      Name:          public
      Namespace:     public-gateway
      Section Name:  https-main
Events:              <none>
```
7. But connection is failing to reach out TCP 443
```yaml
nc -vv 192.168.108.7 443
nc: connect to 192.168.108.7 port 443 (tcp) failed: Connection refused

curl -v https://internal.host/mmgtest/
* Host internal.host:443 was resolved.
* IPv6: (none)
* IPv4: 192.168.108.7
*   Trying 192.168.108.7:443...
* connect to 192.168.108.7 port 443 from 192.168.111.58 port 52498 failed: Connection refused
* Failed to connect to internal.host port 443 after 20 ms: Couldn't connect to server
* Closing connection
curl: (7) Failed to connect to internal.host port 443 after 20 ms: Couldn't connect to server
```

I also disabled the envoy as a dedicated daemonset and the result was the same. 

However, restoring back the original image works again (however, the problem with the headless service remains as expected). 

Any ideas?

**Comment by sayboras** [comment]
:wave: 

Most likely it's related to BGP Announcements IMO, the CI tests are actually having the similar setup, can you cross check if there is any discrepancy which could cause issue :thinking: 

https://github.com/cilium/cilium/blob/c52bee974efe8ae9196355c5ab44d7278468c6d3/.github/workflows/conformance-ingress.yaml#L223

**Comment by tchellomello** [comment]
@sayboras :wave: 

Yes, I can confirm the issue was related with L2 announcements. I had to disable STP on my switches to get the ARP announcements to work. I was hitting several TCP Spurious Retransmissions but it seems to be better now. Thanks for working on that fix! :1st_place_medal:

**Comment by major-sam** [comment]
Is it possible to use _any port_ headless service and endpoint? Or cilium can't build rule without ports on bound service?
example(not working `no healthy upstream`):
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test-app
  namespace: external
spec:
  hostnames:
  - test001.local
  - test002.local
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: default-gw
    namespace: default
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: agent
      namespace: external
      port: 4442
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: v1
kind: Service
metadata:
  name: agent
  namespace: external
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
---
apiVersion: v1
kind: Endpoints
metadata:
  name: agent
  namespace: external
subsets:
- addresses:
  - ip: 192.168.1.111 # routable address from default gw or address in nodes network
```

```cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    disabled (using embedded mode)
 \__/¯¯\__/    Hubble Relay:       OK
    \__/       ClusterMesh:        disabled

DaemonSet              cilium                   Desired: 6, Ready: 6/6, Available: 6/6
Deployment             cilium-operator          Desired: 2, Ready: 2/2, Available: 2/2
Deployment             hubble-relay             Desired: 1, Ready: 1/1, Available: 1/1
Deployment             hubble-ui                Desired: 1, Ready: 1/1, Available: 1/1
Containers:            cilium                   Running: 6
                       cilium-operator          Running: 2
                       clustermesh-apiserver
                       hubble-relay             Running: 1
                       hubble-ui                Running: 1
Cluster Pods:          32/32 managed by Cilium
Helm chart version:    1.18.6
Image versions         cilium             quay.io/cilium/cilium:v1.18.6@sha256:42ec562a5ff6c8a860c0639f5a7611685e253fd9eb2d2fcdade693724c9166a4: 6
                       cilium-operator    quay.io/cilium/operator-generic:v1.18.6@sha256:34a827ce9ed021c8adf8f0feca131f53b3c54a3ef529053d871d0347ec4d69af: 2
                       hubble-relay       quay.io/cilium/hubble-relay:v1.18.6@sha256:fb6135e34c31e5f175cb5e75f86cea52ef2ff12b49bcefb7088ed93f5009eb8e: 1
                       hubble-ui          quay.io/cilium/hubble-ui-backend:v0.13.3@sha256:db1454e45dc39ca41fbf7cad31eec95d99e5b9949c39daaad0fa81ef29d56953: 1
                       hubble-ui          quay.io/cilium/hubble-ui:v0.13.3@sha256:661d5de7050182d495c6497ff0b007a7a1e379648e60830dd68c4d78ae21761d: 1```
