### ISSUE TITLE
intermittent pod and host v6 connectivity

### ISSUE THREAD

**Issue by nikhiljha** [cilium/cilium#23207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

IPv6 connectivity is intermittent on hosts running Cilium (both on the host and inside pods), but works fine all the time on hosts not configured with Cilium. We took a pcap and verified that traffic is reaching the router, and that the router is returning traffic to the host. The only other thing involved is cilium, so we suspect that, but we have no idea how to debug eBPF.

```
[x@thymine:~]$ ping -6 google.com
PING google.com(sfo03s26-in-x0e.1e100.net (2607:f8b0:4005:811::200e)) 56 data bytes
64 bytes from sfo03s26-in-x0e.1e100.net (2607:f8b0:4005:811::200e): icmp_seq=1 ttl=115 time=2.70 ms
64 bytes from sfo03s26-in-x0e.1e100.net (2607:f8b0:4005:811::200e): icmp_seq=2 ttl=115 time=2.73 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 2.700/2.715/2.730/0.015 ms

[x@thymine:~]$ ping -6 google.com
PING google.com(sfo03s27-in-x0e.1e100.net (2607:f8b0:4005:813::200e)) 56 data bytes
^C
--- google.com ping statistics ---
8 packets transmitted, 0 received, 100% packet loss, time 7144ms
```

### Cilium Version

```
cilium-cli: 0.12.11 compiled with go1.19.3 on darwin/arm64
cilium image (default): v1.12.2
cilium image (stable): v1.12.5
cilium image (running): v1.12.5
```

### Kernel Version

`Linux adenine 6.0.10 #1-NixOS SMP PREEMPT_DYNAMIC Sat Nov 26 08:27:56 UTC 2022 x86_64 GNU/Linux`

### Kubernetes Version

```yaml
serverVersion:
  buildDate: "2022-10-12T10:49:09Z"
  compiler: gc
  gitCommit: 434bfd82814af038ad94d62ebe59b133fcb50506
  gitTreeState: clean
  gitVersion: v1.25.3
  goVersion: go1.19.2
  major: "1"
  minor: "25"
  platform: linux/amd64
```

### Sysdump

https://ocf.berkeley.edu/~njha/tmp/cilium-sysdump-20230119-170648.zip

### Anything else?

We are running Cilium via helm chart, with the values described at this commit: https://github.com/ocf/kubernetes/commit/fc01f86fcf2c786bf96ead8c9ea91b2a6a09083c

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
