### ISSUE TITLE
Create a NetworkPolicy from AWS SecurityGroupPolicy for pods

### ISSUE THREAD

**Issue by tamilhce** [cilium/cilium#23209]
## Problem Statement 

with respect to EKS clusters with VPC CNI , To control the application pod to reach to the external AWS services like Amazon RDS /EC2 etc.., We can use Amazon EC2 security groups to define rules that allow inbound and outbound network traffic to and from pods this achieved by defining  `SecurityGroupPolicy`  for the pod.  Reference : https://aws.amazon.com/blogs/containers/introducing-security-groups-for-pods/.

```
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: securitygrouppolicy
  namespace: test-namespace
  labels:
  annotations: {}
spec:
  podSelector: {}
  securityGroups:
    groupIds:
    - sg-******
    - sg-******

```
This Security Groups are attached to the POD ENI's and it is applicable only for the VPC IP subnets. This is not applicable  for the cilium overlay network.
It will be challenging to migrate the `SecurityGroupPolicy` configurations attached to the pod from VPC CNI to Cilium overlay mode. 
Currently, there is no solution to this use case, as discussed in Slack

## Proposed solution 
Cilium supports NetworkPolicy. We can consider converting the `SecurityGroupPolicy` as `NetworkPolicy`. 

Read the `SecurityGroupPolicy` CRD object and get the securityGroups IDs. Then call the AWS API's to fetch the inbound & outbound details and construct the equivalent   `NetworkPolicy` object. 

Please let me know your suggestions with this approach.
