### ISSUE TITLE
v1.13.0-rc5 Service announcement failure

### ISSUE THREAD

**Issue by BurlyLuo** [cilium/cilium#23280]
1.Environment Details:
Kind + metallb + CONTAINERlab(VyoS)
1.1:Kind
```
cat <<EOF | kind create cluster --image=kindest/node:v1.23.4 --config=-
kind: Cluster
name: clab-bgp
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: "10.98.0.0/16"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-ip: 10.1.5.10
        node-labels: "rack=rack0"

- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-ip: 10.1.5.11
        node-labels: "rack=rack0"

- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-ip: 10.1.8.10
        node-labels: "rack=rack1"

- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-ip: 10.1.8.11
        node-labels: "rack=rack1"

containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."192.168.2.100:5000"]
    endpoint = ["http://192.168.2.100:5000"]
EOF
```
1.2: metallb:
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: my-ip-space
      protocol: layer2
      addresses:
      - 172.18.0.200-172.18.0.210
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-metallb-test
spec:
  selector:
    matchLabels:
      app: nginx-metallb-test
  template:
    metadata:
      labels:
        app: nginx-metallb-test
    spec:
      containers:
      - name: nginx
        image: 192.168.2.100:5000/nettool
        ports:
        - name: http
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-metallb-test
  type: LoadBalancer
```
3.CONTAINERlab(VyoS)
```
cat <<EOF>clab.yaml | clab deploy -t clab.yaml -
name: bgp
topology:
  nodes:
    spine0:
      kind: linux
      image: 192.168.2.100:5000/vyos/vyos:1.2.8
      cmd: /sbin/init
      binds:
        - /lib/modules:/lib/modules


    spine1:
      kind: linux
      image: 192.168.2.100:5000/vyos/vyos:1.2.8
      cmd: /sbin/init
      binds:
        - /lib/modules:/lib/modules


    leaf0:
      kind: linux
      image: 192.168.2.100:5000/vyos/vyos:1.2.8
      cmd: /sbin/init
      binds:
        - /lib/modules:/lib/modules


    leaf1:
      kind: linux
      image: 192.168.2.100:5000/vyos/vyos:1.2.8
      cmd: /sbin/init
      binds:
        - /lib/modules:/lib/modules


    br-leaf0:
      kind: bridge
  
    br-leaf1:
      kind: bridge


    server1:
      kind: linux
      image: 192.168.2.100:5000/nettool
      network-mode: container:control-plane
      exec:
      - ip addr add 10.1.5.10/24 dev net0
      - ip route replace default via 10.1.5.1

    server2:
      kind: linux
      image: 192.168.2.100:5000/nettool
      network-mode: container:worker
      exec:
      - ip addr add 10.1.5.11/24 dev net0
      - ip route replace default via 10.1.5.1

    server3:
      kind: linux
      image: 192.168.2.100:5000/nettool
      network-mode: container:worker2
      exec:
      - ip addr add 10.1.8.10/24 dev net0
      - ip route replace default via 10.1.8.1

    server4:
      kind: linux
      image: 192.168.2.100:5000/nettool
      network-mode: container:worker3
      exec:
      - ip addr add 10.1.8.11/24 dev net0
      - ip route replace default via 10.1.8.1


  links:
    - endpoints: ["br-leaf0:br-leaf0-net0", "server1:net0"]
    - endpoints: ["br-leaf0:br-leaf0-net1", "server2:net0"]

    - endpoints: ["br-leaf1:br-leaf1-net0", "server3:net0"]
    - endpoints: ["br-leaf1:br-leaf1-net1", "server4:net0"]

    - endpoints: ["leaf0:eth1", "spine0:eth1"]
    - endpoints: ["leaf0:eth2", "spine1:eth1"]
    - endpoints: ["leaf0:eth3", "br-leaf0:br-leaf0-net2"]

    - endpoints: ["leaf1:eth1", "spine0:eth2"]
    - endpoints: ["leaf1:eth2", "spine1:eth2"]
    - endpoints: ["leaf1:eth3", "br-leaf1:br-leaf1-net2"]

EOF
```

2.Cilium CiliumBGPPeeringPolicy
```
cat <<EOF | kubectl apply -f -
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: rack0
spec:
  nodeSelector:
    matchLabels:
      rack: rack0
  virtualRouters:
  - localASN: 65005
    serviceSelector:
      matchExpressions:
        - {key: app, operator: NotIn, values: []}
    exportPodCIDR: true
    neighbors:
    - peerAddress: "10.1.5.1/24"
      peerASN: 65005
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: rack1
spec:
  nodeSelector:
    matchLabels:
      rack: rack1
  virtualRouters:
  - localASN: 65008
    serviceSelector:
      matchExpressions:
        - {key: app, operator: NotIn, values: []}
    exportPodCIDR: true
    neighbors:
    - peerAddress: "10.1.8.1/24"
      peerASN: 65008
EOF
```
But there is no service ip announced to the leaf bgp router.
```
root@vyos:/# show ip bgp 
BGP table version is 23, local router ID is 10.1.5.1, vrf id 0
Default local pref 100, local AS 65005
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete

   Network          Next Hop            Metric LocPrf Weight Path
*> 10.1.5.0/24      0.0.0.0                  0         32768 i
*= 10.1.8.0/24      10.1.12.2                              0 800 65008 i
*>                  10.1.10.2                              0 500 65008 i
*>i10.98.0.0/24     10.1.5.10                     100      0 i
*= 10.98.1.0/24     10.1.12.2                              0 800 65008 i
*>                  10.1.10.2                              0 500 65008 i
*> 10.98.2.0/24     10.1.10.2                              0 500 65008 i
*=                  10.1.12.2                              0 800 65008 i
*>i10.98.3.0/24     10.1.5.11                     100      0 i

Displayed  6 routes and 9 total paths
root@vyos:/# 
```

The below is the topo for reference:
![image](https://user-images.githubusercontent.com/35321202/214259881-3ad2e78c-1adb-48a9-89d0-491f0ed36aca.png)

cilium k8s and kernel version:
```
kk exec -it ds/cilium -- cilium version
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init)
Client: 1.13.0-rc5 dc22a46f 2023-01-23T18:46:23-08:00 go version go1.19.5 linux/amd64
Daemon: 1.13.0-rc5 dc22a46f 2023-01-23T18:46:23-08:00 go version go1.19.5 linux/amd64
root@wluo:~/wcni/cilium/c-cilium-bgp-control-plane/v1.13.0-rc5/metallb# 
```
```
root@wluo:~/wcni/cilium/c-cilium-bgp-control-plane/v1.13.0-rc5/metallb# k get nodes -owide 
NAME                     STATUS   ROLES                  AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION      CONTAINER-RUNTIME
clab-bgp-control-plane   Ready    control-plane,master   83m   v1.23.4   10.1.5.10     <none>        Ubuntu 21.10   5.15.0-58-generic   containerd://1.5.10
clab-bgp-worker          Ready    <none>                 82m   v1.23.4   10.1.5.11     <none>        Ubuntu 21.10   5.15.0-58-generic   containerd://1.5.10
clab-bgp-worker2         Ready    <none>                 83m   v1.23.4   10.1.8.10     <none>        Ubuntu 21.10   5.15.0-58-generic   containerd://1.5.10
clab-bgp-worker3         Ready    <none>                 83m   v1.23.4   10.1.8.11     <none>        Ubuntu 21.10   5.15.0-58-generic   containerd://1.5.10
root@wluo:~/wcni/cilium/c-cilium-bgp-control-plane/v1.13.0-rc5/metallb# 
```
Install Cilium CLI:
```
controller_node=`kubectl get nodes --no-headers  -o custom-columns=NAME:.metadata.name| grep control-plane`

helm repo add cilium https://helm.cilium.io/ 
helm repo update
helm install cilium cilium/cilium --set k8sServiceHost=$controller_node --set k8sServicePort=6443 --version v1.13.0-rc5 --namespace kube-system --set debug.enabled=true --set debug.verbose=datapath --set monitorAggregation=none --set cluster.name=clab-bgp-cplane --set tunnel=disabled --set ipam.mode=kubernetes --set ipv4NativeRoutingCIDR=10.0.0.0/8 --set bgpControlPlane.enabled=true --set k8s.requireIPv4PodCIDR=true
```
2.sysdump
[cilium-sysdump-20230124-095000.zip](https://github.com/cilium/cilium/files/10488298/cilium-sysdump-20230124-095000.zip)

3.bgp routing table
```
root@vyos:/# show ip bgp 
BGP table version is 23, local router ID is 10.1.5.1, vrf id 0
Default local pref 100, local AS 65005
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete

   Network          Next Hop            Metric LocPrf Weight Path
*> 10.1.5.0/24      0.0.0.0                  0         32768 i
*= 10.1.8.0/24      10.1.12.2                              0 800 65008 i
*>                  10.1.10.2                              0 500 65008 i
*>i10.98.0.0/24     10.1.5.10                     100      0 i
*= 10.98.1.0/24     10.1.12.2                              0 800 65008 i
*>                  10.1.10.2                              0 500 65008 i
*> 10.98.2.0/24     10.1.10.2                              0 500 65008 i
*=                  10.1.12.2                              0 800 65008 i
*>i10.98.3.0/24     10.1.5.11                     100      0 i

Displayed  6 routes and 9 total paths
root@vyos:/# 
```
