### ISSUE TITLE
Egress Gateway interrupts long running tcp connections

### ISSUE THREAD

**Issue by paulrichter2001** [cilium/cilium#23289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Our Pod uses an external Postgres database. The connection is established over a Cilium Egress Gateway and the connection is kept open over quite some time. 
After a few minutes (~15-20 minutes) the TCP connection gets closed improperly. The pod cannot interact with the database any longer. The connection is not re-established.

We found a similar issue here:
https://github.com/cilium/cilium/issues/22377

What we found out so far:
- the problem is not limited to our database connection
  - it is also reproducible with a ssh connection from the pod to an external server (also via Cilium Egress Gateway)
  -  without egress gateway the problem does not occur
- the issue seems only to happen if pod runs on a non-egress node
- if container runs on an egress node, the problem does not occur
- there might be a some issue with the NAT table cleanup of the cilium agent
  - we checked by running `cilium bpf nat list | wc -l` in the cilium agent pod on the egress node
  - if the count goes down, the connection (from pod on non-egress node) is interrupted

helm values:
```
autoDirectNodeRoutes: true
bpf:
  masquerade: true
cluster:
  id: 0
  name: k3s-cluster
egressGateway:
  enabled: true
encryption:
  nodeEncrpytion: false
externalIPs:
  enabled: true
hostPort:
  enabled: true
hubble:
  metrics:
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - icmp
    - http
    serviceMonitor:
      enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
ipam:
  operator:
    clusterPoolIPv4PodCIDR: 10.100.0.0/16
ipv4NativeRoutingCIDR: 10.100.0.0/16
k8sServiceHost: 10.0.0.254
k8sServicePort: 6443
kubeProxyReplacement: strict
l7Proxy: true
loadBalancer:
  mode: dsr
nodePort:
  enabled: true
operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  replicas: 2
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
tunnel: disabled
```

### Cilium Version

1.12.5

### Kernel Version

Linux 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4+k3s1", GitCommit:"0dc63334c0db3e7b99244427615e091909fc486e", GitTreeState:"clean", BuildDate:"2022-11-18T18:17:40Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}

### Relevant log output

```shell
2023-01-19 06:06:27,587 WARNING  [-] Database settings are not available, using defaults. error: connection already closed
2023-01-19 06:06:27,588 WARNING  [-] Database settings are not available, using defaults. error: connection already closed
2023-01-19 06:08:27,710 WARNING  [-] Database settings are not available, using defaults. error: connection already closed
2023-01-19 06:08:27,711 WARNING  [-] Database settings are not available, using defaults. error: connection already closed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by borkmann** [comment]
Cc @jibi

**Comment by jibi** [comment]
Hey @paulrichter2001 :wave: could you share a sysdump of the environment please?

**Comment by paulrichter2001** [comment]
Hey @jibi here is the sysdump of our current test cluster.
[sysdump_part1.zip](https://github.com/cilium/cilium/files/10501137/sysdump_part1.zip)
[sysdump_part2.zip](https://github.com/cilium/cilium/files/10501141/sysdump_part2.zip)


Cilium helm vars:
```
autoDirectNodeRoutes: true
bpf:
  masquerade: true
cluster:
  id: 0
  name: testcluster
egressGateway:
  enabled: true
encryption:
  nodeEncryption: false
externalIPs:
  enabled: true
hostPort:
  enabled: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
ipam:
  operator:
    clusterPoolIPv4PodCIDR: 10.50.0.0/16
ipv4NativeRoutingCIDR: 10.50.0.0/16
k8sServiceHost: 10.1.1.250
k8sServicePort: 6443
kubeProxyReplacement: strict
l7Proxy: true
loadBalancer:
  mode: dsr
nodePort:
  enabled: true
operator:
  replicas: 2
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
tunnel: disabled
```
