### ISSUE TITLE
k8s default deny ingress policy does not deny any traffic

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#2333]
### General Information
A user reported (https://cilium.slack.com/team/U8ENGFU3C) that cilium enforces no policy when  the policy below is imported. aanm and I were able to reproduce this independently. I tested with the getting started minikube example (i.e. pod-to-pod) and aanm tested host-to-pod.
This policy is the k8s doc example for default deny (https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-ingress-traffic). Our documentation suggests that default policy enforcement follows the k8s model (http://cilium.readthedocs.io/en/stable/policy/#policy-enforcement-mode).
I'm not sure if this is bad documentation, and we should instead suggest that folks boot with `--policy-enforcement=always` or if this is an actual bug in how we convert k8s policies. From what we could tell, we can't represent this deny-all behaviour in the cilium network policy data structures, so I'm not sure if it's even possible.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector: {}
  policyTypes:
  - Ingress  
```

- Cilium version: reported on stable, tested on master on 2017-12-14

### How to reproduce the issue
1. `kubectl create -f examples/minikube/demo.yaml`
2. Import the policy above `kubectl create -f mypolicy.yaml`
3. Try to connect from one pod to another (following the demo example)
```bash
$ APP2_POD=$(kubectl get pods -l id=app2 -o jsonpath='{.items[0].metadata.name}')
$ SVC_IP=$(kubectl get svc app1-service -o jsonpath='{.spec.clusterIP}')
$ kubectl exec $APP2_POD -- curl -s $SVC_IP
```
4. be sad because you wanted it to be denied

**Comment by tgraf** [comment]
We can represent this with Cilium policy rules:
http://docs.cilium.io/en/latest/policy/language/#ingress-egress-default-deny

``` yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "deny-all-ingress"
spec:
  endpointSelector:
    matchLabels:
  ingress:
```
