### ISSUE TITLE
Problem with connectivity to Service ExternalIP on node with LoadBalancer Service pod

### ISSUE THREAD

**Issue by rearden-steel** [cilium/cilium#23434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi.
I have a strange problem.
I have a cluster with Cilum 1.12.6 and BGP routing with kube-router.
I have Nginx ingress Service with type=LoadBalancer and external IP (10.80.4.1).
The problem is that this external IP does not work on the same host where Service's pod exists. And works good on other hosts.
```
tf@worker5:~$ curl -v https://10.80.4.1:443
* Trying 10.80.4.1:443...
```
I see that packets to 10.80.4.1 go out on the interface and I see replies which are dropped by Cilium:
```
host_machine# tcpdump -n -i eth0 port 443
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes

14:21:23.639644 IP 10.80.3.14.57678 > 10.80.4.1.443: Flags [S], seq 2510042583, win 64240, options [mss 1460,sackOK,TS val 3952465790 ecr 0,nop,wscale 7], length 0
14:21:23.639828 IP 10.80.3.14.57678 > 10.80.4.1.443: Flags [S], seq 2510042583, win 64240, options [mss 1460,sackOK,TS val 3952465790 ecr 0,nop,wscale 7], length 0

cilium_pod# cilium monitor
...
xx drop (FIB lookup failed, 4) flow 0xed9f072d to endpoint 0, file bpf_lxc.c line 2005, , identity unknown->unknown: 10.80.4.1:443 -> 10.80.3.14:36810 tcp SYN, ACK
xx drop (FIB lookup failed, 4) flow 0xa90e3d5e to endpoint 0, file bpf_lxc.c line 2005, , identity unknown->unknown: 10.80.4.1:443 -> 10.80.3.14:36810 tcp SYN, ACK

```

### Cilium Version

1.12.6
```
helm upgrade --install cilium cilium/cilium --version 1.12.6 \
  --namespace kube-system \
  --set devices="{eth0,eth1}" \
  --set kubeProxyReplacement=strict \
  --set k8sServiceHost=127.0.0.1 \
  --set k8sServicePort=6443 \
  --set tunnel="disabled" \
  --set ipam.mode="kubernetes" \
  --set ipv4NativeRoutingCIDR="10.180.0.0/17" \
  --set localRedirectPolicy=true \
  --set hubble.listenAddress=":4244" \
  --set hubble.relay.enabled=true \
  --set hubble.ui.enabled=true \
  --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,http}" \
  --set prometheus.enabled=true \
  --set operator.prometheus.enabled=true \
  --set bpf.masquerade=true
```

### Kernel Version

Linux worker5 5.15.0-58-generic #64~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.22.12

### Sysdump

https://filetransfer.io/data-package/jg8maArH#link

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rearden-steel** [comment]
```
ciliium bpf lb list
...
10.80.4.1:443         10.180.69.21:443 (145) (1)
                      0.0.0.0:0 (145) (0) [ExternalIPs, Local]
```

**Comment by rearden-steel** [comment]
Hi.
Seems that setting `externalTrafficPolicy=Cluster` fixes the issue.
There is related information here: https://docs.cilium.io/en/stable/gettingstarted/kubeproxy-free/

> "externalTrafficPolicy=Local is possible and can also be reached from nodes which have no local backends"

Is it correct? Unfortunately documentation does not provide enough details to understand and investigate the issue.

**Comment by pchaigno** [comment]
> Is it correct? Unfortunately documentation does not provide enough details to understand and investigate the issue.

`externalTrafficPolicy={Cluster,Local}` is a Kubernetes feature and not Cilium-specific. See https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip for its documentation.

>  Seems that setting externalTrafficPolicy=Cluster fixes the issue.

Are you saying you had `externalTrafficPolicy` set to `Local` by mistake?

**Comment by brb** [comment]
@rearden-steel The `FIB lookup failed` indicates that you might be hitting issues with https://docs.cilium.io/en/v1.12/gettingstarted/kubeproxy-free/#neighbor-discovery.

**Comment by pr0ton11** [comment]
I am running into the same issue with a LoadBalancer service that would allow me to use SSH for Gitea, which is very annoying.

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    io.cilium/lb-ipam-ips: redacted
  labels:
    app: gitea
    app.kubernetes.io/instance: git
  name: git-ssh
  namespace: world
spec:
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app.kubernetes.io/instance: git
    app.kubernetes.io/name: gitea
  sessionAffinity: None
  type: LoadBalancer
  
```
