### ISSUE TITLE
Multus cannot bring up secondary interface with Cilium CNI

### ISSUE THREAD

**Issue by anupamdialpad** [cilium/cilium#23483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We want to add a secondary interface to our pods and are using Multus for that. Multus pods adds additional interface based on a `NetworkAttachmentDefinition` and the workload pods need to be annotated with the name of the NetworkAttachmentDefinition for Multus to add a secondary interface.
This is the NetworkAttachmentDefinition CRD
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: cilium-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "cilium-cni",
      "ipam": {
        "type": "host-local",
        "subnet": "10.33.2.0/24"
      }
    }'
```

Following is the error we are seeing when pods are coming up.
```
Failed to create pod sandbox: rpc error: code = Unknown
desc = failed to setup network for sandbox "ea73d59875afffabc926e6a692c12abe57097ac5b2907fafe96e23d56b8ce50c": 
plugin type="multus" name="multus-cni-network" 
failed (add): [default/samplepod/0f80c4e3-6d45-4643-aa1b-33b9ec08ea7b:cilium-conf]: 
error adding container to network "cilium-conf": unable to set up veth on host side: unable to create veth pair: file exists
```
Is there something I am missing in the CRD configuration, that you can help with?

### Cilium Version

1.12.5

### Kernel Version

4.19.0-17

### Kubernetes Version

1.23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cyclinder** [comment]
Could you show the annotations of pod ?

**Comment by anupamdialpad** [comment]
This is my pod.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: cilium-conf
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
```

Just tried adding with `k8s.v1.cni.cncf.io/networks: cilium-conf@eth1`. Still it throws the same error
```
Normal   AddedInterface          0s    multus             Add eth0 [fc00::35ba/128 10.32.0.174/32] from cilium
Warning  FailedCreatePodSandBox  0s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "a02100bbc0d9578840d1e5c42faf694ec2f382176f2990054c803502eaa8a974": plugin type="multus" name="multus-cni-network" failed (add): [default/samplepod/167b9672-2095-4d1a-bb4a-843e6c5c8c93:cilium-conf]: error adding container to network "cilium-conf": unable to set up veth on host side: unable to create veth pair: file exists
```
