### ISSUE TITLE
Helm values for subchart are not rendered properly

### ISSUE THREAD

**Issue by grem11n** [cilium/cilium#23507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using the official Helm chart for Cilium as a subchart, some values are not rendered properly.

**Setup**:

1. Create a new chart that has the official Cilium chart as a dependency:

```yaml
apiVersion: v2
name: my-cilium
type: application
version: 0.0.0
dependencies:
  - name: cilium
    version: 1.12.6
    repository: https://helm.cilium.io
```

2. Provide some custom values for the subchart according to the [Helm rules](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/):

```yaml
cilium:
  operator:
    replicas: 4
    image:
      repository: "my-repo.com/cilium-operator"
```

3. Template the parent chart:
```bash
helm template cilium . --show-only charts/cilium/templates/cilium-operator/deployment.yaml
```

**Expected results**:

Cilium operator deployment is rendered with parent chart values taken into account e.g.:

```yaml
---
# Source: cilium/charts/cilium/templates/cilium-operator/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
... OMITED ...
spec:
  replicas: 4
... OMITED ...
    spec:
      containers:
      - name: cilium-operator
        image: "my-repo.com/cilium-operator-generic:v1.12.6@sha256:eec4430d222cb2967d42d3b404d2606e66468de47ae85e0a3ca3f58f00a5e017"        imagePullPolicy: IfNotPresent
 ... OMITED ...
```

**Actual results**:

Default values are applied:

```yaml
---
# Source: cilium/charts/cilium/templates/cilium-operator/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
 ... OMITED ...
spec:
  replicas: 2
 ... OMITED ...
    spec:
      containers:
      - name: cilium-operator
        image: "quay.io/cilium/operator-generic:v1.12.6@sha256:eec4430d222cb2967d42d3b404d2606e66468de47ae85e0a3ca3f58f00a5e017"
        imagePullPolicy: IfNotPresent
 ... OMITED ...
```

### Cilium Version

Cilium Helm chart version: `1.12.6`
Cilium version: `v1.12.6` (irrelevant for this issue)

### Kernel Version

irrelevant for this issue

### Kubernetes Version

Kuberentes version: `v1.23.15`
Helm version: `v3.11.0`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
