### ISSUE TITLE
Network Policy drops ingress traffic from cidr with /N but allows it with /0

### ISSUE THREAD

**Issue by seanmwinn** [cilium/cilium#23603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Kind environment:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kirk
nodes:
  - role: control-plane
  - role: worker
networking:
  podSubnet: "172.30.0.0/16"
  serviceSubnet: "172.31.1.0/24"
```

Cilium install:
```
export CIDR=$(docker network inspect multicluster | jq -r '.[].IPAM.Config[0].Subnet')
cilium install --config tunnel=disabled \
--config ipv4-native-routing-cidr="${CIDR}" \
--config auto-direct-node-routes=true \
--config enable-local-node-route=false \
--config enable-endpoint-health-checking=false \
--config enable-l7-proxy=false \
--config monitor-aggregation=none \
--config debug=true \
--config enable-hubble=true \
--config enable-well-known-identities=true \
--config enable-endpoint-routes=true \
--config enable-no-encapsulation=true \
--config enable-k8s-networkpolicy=false \
--config cluster-name=kirk \
--config cluster-id=100 \
--restart-unmanaged-pods=false \
--context=kind-kirk
```

Run the following pod:
```
kubectl run echo --image=hashicorp/http-echo --port=5678 -- -text="hello"
```

Expose the pod as a NodePort service:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    run: echo
  name: echo
  namespace: default
spec:
  ports:
  - nodePort: 32000
    port: 5678
    protocol: TCP
  selector:
    run: echo
  type: NodePort
```

Apply the following NetworkPolicy making sure w.x.y.z is the cidr where traffic originates and nn is a valid subnet mask greater than 0:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow
  namespace: default
spec:
  podSelector:
    matchLabels:
      run: echo
  ingress:
    - from:
        - ipBlock:
            cidr: w.x.y.z/nn
      ports:
        - protocol: TCP
          port: 5678
```

Attempt to curl the nodeport service on the worker node and observe the following drop with source identity 2:
```json
{"flow":{"time":"2023-02-06T22:58:13.215860855Z","verdict":"DROPPED","drop_reason":133,"ethernet":{"source":"9a:e0:d6:d7:45:7b","destination":"86:07:90:23:90:2f"},"IP":{"source":"172.22.0.5","destination":"172.30.1.167","ipVersion":"IPv4"},"l4":{"TCP":{"source_port":17917,"destination_port":5678,"flags":{"SYN":true}}},"source":{"identity":2,"labels":["reserved:world"]},"destination":{"ID":2331,"identity":6566331,"namespace":"default","labels":["k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default","k8s:io.cilium.k8s.policy.cluster=kirk","k8s:io.cilium.k8s.policy.serviceaccount=default","k8s:io.kubernetes.pod.namespace=default","k8s:run=echo"],"pod_name":"echo"},"Type":"L3_L4","node_name":"kirk/kirk-worker","event_type":{"type":1,"sub_type":133},"traffic_direction":"INGRESS","drop_reason_desc":"POLICY_DENIED","Summary":"TCP Flags: SYN"},"node_name":"kirk/kirk-worker","time":"2023-02-06T22:58:13.215860855Z"}
```

Attempt to curl the nodeport service on the master node and the packet is dropped with source identity 7:
```json
{"flow":{"time":"2023-02-06T23:17:46.022283520Z","verdict":"DROPPED","drop_reason":133,"ethernet":{"source":"9a:e0:d6:d7:45:7b","destination":"86:07:90:23:90:2f"},"IP":{"source":"172.22.0.2","destination":"172.30.1.167","ipVersion":"IPv4"},"l4":{"TCP":{"source_port":59632,"destination_port":5678,"flags":{"SYN":true}}},"source":{"identity":7,"labels":["reserved:kube-apiserver","reserved:remote-node"]},"destination":{"ID":2331,"identity":6566331,"namespace":"default","labels":["k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default","k8s:io.cilium.k8s.policy.cluster=kirk","k8s:io.cilium.k8s.policy.serviceaccount=default","k8s:io.kubernetes.pod.namespace=default","k8s:run=echo"],"pod_name":"echo"},"Type":"L3_L4","node_name":"kirk/kirk-worker","event_type":{"type":1,"sub_type":133},"traffic_direction":"INGRESS","drop_reason_desc":"POLICY_DENIED","Summary":"TCP Flags: SYN"},"node_name":"kirk/kirk-worker","time":"2023-02-06T23:17:46.022283520Z"}
```

Change the CIDR range to w.x.y.z/0 and the packet is allowed with source identity 2:
```json
{"flow":{"time":"2023-02-06T23:13:56.606798881Z","verdict":"FORWARDED","ethernet":{"source":"9a:e0:d6:d7:45:7b","destination":"86:07:90:23:90:2f"},"IP":{"source":"172.22.0.5","destination":"172.30.1.167","ipVersion":"IPv4"},"l4":{"TCP":{"source_port":5672,"destination_port":5678,"flags":{"ACK":true}}},"source":{"identity":2,"labels":["reserved:world"]},"destination":{"ID":2331,"identity":6566331,"namespace":"default","labels":["k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default","k8s:io.cilium.k8s.policy.cluster=kirk","k8s:io.cilium.k8s.policy.serviceaccount=default","k8s:io.kubernetes.pod.namespace=default","k8s:run=echo"],"pod_name":"echo"},"Type":"L3_L4","node_name":"kirk/kirk-worker","event_type":{"type":4},"traffic_direction":"INGRESS","trace_observation_point":"TO_ENDPOINT","is_reply":false,"Summary":"TCP Flags: ACK"},"node_name":"kirk/kirk-worker","time":"2023-02-06T23:13:56.606798881Z"}
```

It's expected for the traffic to be allowed with a valid subnet mask.

### Cilium Version

1.12.6

### Kernel Version

Linux kirk-worker 5.15.49-linuxkit #1 SMP Tue Sep 13 07:51:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-09-01T23:30:43Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20230206-152132.zip](https://github.com/cilium/cilium/files/10669991/cilium-sysdump-20230206-152132.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
