### ISSUE TITLE
Document Hubble L7 HTTP exemplar functionality

### ISSUE THREAD

**Issue by chancez** [cilium/cilium#23619]
https://github.com/cilium/cilium/pull/21599 introduced the ability to extract traceIDs from from HTTP flows and expose them as exemplars. We documented how to enable open metrics in that PR, but not how to configure the HTTP v2 metrics with the new exemplars option. 

For example:
```
hubble:
  metrics:
    enableOpenMetrics: true
    enabled:
      - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
```
