### ISSUE TITLE
`maxUnavailable` defaults to `1` even when `maxUnavailable` is disabled as instructed with `maxUnavailable: null` for cilium-operator

### ISSUE THREAD

**Issue by helpmerightthismoment** [cilium/cilium#23614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When setting `maxUnavailable: null` as advised in the comments (in `values.yaml` for `cilium-operator`):

```yaml
  operator:
    # PodDisruptionBudget settings
    podDisruptionBudget:
      # -- enable PodDisruptionBudget
      # ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
      enabled: true
      # -- Minimum number/percentage of pods that should remain scheduled.
      # When it's set, maxUnavailable must be disabled by `maxUnavailable: null`
      minAvailable: 1
      # -- Maximum number/percentage of pods that may be made unavailable
      maxUnavailable: null
```

The rendered PodDisruptionBudget (as the default value for `operator.podDisruptionBudget.maxUnavailable` is `1`):

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cilium-operator
  namespace: kube-system
  labels:
    io.cilium/app: operator
    name: cilium-operator
spec:
  maxUnavailable: 1
  minAvailable: 1
  selector:
    matchLabels:
      io.cilium/app: operator
      name: cilium-operator
```

which then subsequently errors with:
```
The PodDisruptionBudget "cilium-operator" is invalid: spec: Invalid value: policy.PodDisruptionBudgetSpec{MinAvailable:(*intstr.IntOrString)(0xc0142d1140), Selector:(*v1.LabelSelector)(0xc0142d1160), MaxUnavailable:(*intstr.IntOrString)(0xc0142d1120)}: minAvailable and maxUnavailable cannot be both set
```

This workaround seems to work:

```yaml
  operator:
    # PodDisruptionBudget settings
    podDisruptionBudget:
      # -- enable PodDisruptionBudget
      # ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
      enabled: true
      # -- Minimum number/percentage of pods that should remain scheduled.
      # When it's set, maxUnavailable must be disabled by `maxUnavailable: null`
      minAvailable: 1
      # -- Maximum number/percentage of pods that may be made unavailable
      maxUnavailable: 0
```

### Cilium Version

1.12.4

### Kernel Version

$ uname -a
Linux ip-10-2-96-166.eu-west-1.compute.internal 5.4.228-131.415.amzn2.x86_64 #1 SMP Tue Dec 20 12:51:02 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.22

### Sysdump

[cilium-sysdump-20230207-155349.zip](https://github.com/cilium/cilium/files/10677036/cilium-sysdump-20230207-155349.zip)

### Relevant log output

```shell
🔍 Collecting sysdump with cilium-cli version: v0.12.12, args: [sysdump]
🔮 Detected Cilium installation in namespace "kube-system"
Detected Cilium operator in namespace "kube-system"
🔍 Collecting Kubernetes nodes
🔍 Collect Kubernetes nodes
🔍 Collecting Kubernetes events
🔍 Collect Kubernetes version
🔍 Collecting Kubernetes pods
🔍 Collecting Kubernetes namespaces
🔍 Collecting Kubernetes services
🔍 Collecting Kubernetes pods summary
🔍 Collecting Kubernetes endpoints
🔍 Collecting Kubernetes network policies
🔍 Collecting Cilium network policies
🔍 Collecting Kubernetes leases
🔍 Collecting Cilium egress NAT policies
🔍 Collecting Cilium cluster-wide network policies
🔍 Collecting Cilium local redirect policies
🔍 Collecting Cilium Egress Gateway policies
🔍 Collecting Cilium endpoints
🔍 Collecting Cilium identities
🔍 Collecting Cilium nodes
🔍 Collecting Ingresses
🔍 Collecting CiliumClusterwideEnvoyConfigs
🔍 Collecting CiliumEnvoyConfigs
🔍 Collecting Cilium etcd secret
🔍 Collecting the Cilium configuration
🔍 Collecting the Cilium daemonset(s)
🔍 Collecting the Hubble daemonset
🔍 Collecting the Hubble Relay configuration
🔍 Collecting the Hubble Relay deployment
🔍 Collecting the Hubble UI deployment
🔍 Collecting the Cilium operator deployment
🔍 Collecting the 'clustermesh-apiserver' deployment
🔍 Collecting the CNI configuration files from Cilium pods
🔍 Collecting the CNI configmap
🔍 Collecting gops stats from Hubble pods
🔍 Collecting gops stats from Cilium pods
🔍 Collecting gops stats from Hubble Relay pods
🔍 Collecting logs from Cilium pods
🔍 Collecting bugtool output from Cilium pods
🔍 Collecting logs from 'clustermesh-apiserver' pods
🔍 Collecting logs from Cilium operator pods
🔍 Collecting logs from Hubble pods
⚠️ Deployment "clustermesh-apiserver" not found in namespace "kube-system" - this is expected if 'clustermesh-apiserver' isn't enabled
🔍 Collecting logs from Hubble Relay pods
🔍 Collecting logs from Hubble UI pods
🔍 Collecting bugtool output from Tetragon pods
🔍 Collecting platform-specific data
🔍 Collecting kvstore data
🔍 Collecting Hubble flows from Cilium pods
⚠️ Failed to unarchive 'cilium-bugtool' output for "cilium-7z2bq": reading file in tar archive: /tmp/3869475955/cilium-sysdump-20230207-155349/cilium-bugtool-cilium-7z2bq-20230207-155349/cmd/state/2933/ep_config.h: writing file: unexpected EOF
⚠️ The following tasks failed, the sysdump may be incomplete:
⚠️ [12] Collecting Cilium egress NAT policies: failed to collect Cilium egress NAT policies: the server could not find the requested resource (get ciliumegressnatpolicies.cilium.io)
⚠️ [13] Collecting Cilium Egress Gateway policies: failed to collect Cilium Egress Gateway policies: the server could not find the requested resource (get ciliumegressgatewaypolicies.cilium.io)
⚠️ [14] Collecting Cilium local redirect policies: failed to collect Cilium local redirect policies: the server could not find the requested resource (get ciliumlocalredirectpolicies.cilium.io)
⚠️ [19] Collecting CiliumClusterwideEnvoyConfigs: failed to collect CiliumClusterwideEnvoyConfigs: the server could not find the requested resource (get ciliumclusterwideenvoyconfigs.cilium.io)
⚠️ [20] Collecting CiliumEnvoyConfigs: failed to collect CiliumEnvoyConfigs: the server could not find the requested resource (get ciliumenvoyconfigs.cilium.io)
⚠️ cilium-bugtool-cilium-b7g55: failed to collect 'cilium-bugtool' output for "cilium-b7g55" in namespace "kube-system": command terminated with exit code 137: Unable to dump envoy config: Get "http://admin/config_dump?include_eds": dial unix /var/run/cilium/envoy-admin.sock: connect: no such file or directory

⚠️ hubble-flows-cilium-hhhnp: failed to collect hubble flows for "cilium-hhhnp" in namespace "kube-system": command terminated with exit code 137: time="2023-02-07T15:54:03Z" level=debug msg="Sending GetFlows request" request="number:10000 follow:true"
unknown response type: &{LostEvents:source:HUBBLE_RING_BUFFER num_events_lost:1}

⚠️ cilium-bugtool-cilium-hhhnp: failed to collect 'cilium-bugtool' output for "cilium-hhhnp" in namespace "kube-system": command terminated with exit code 137: Unable to dump envoy config: Get "http://admin/config_dump?include_eds": dial unix /var/run/cilium/envoy-admin.sock: connect: no such file or directory

⚠️ gops-cilium-b7g55-memstats: failed to list processes "cilium-b7g55" ("cilium-agent") in namespace "kube-system": command terminated with exit code 137
⚠️ cilium-bugtool-cilium-jw72k: failed to collect 'cilium-bugtool' output for "cilium-jw72k" in namespace "kube-system": command terminated with exit code 137: Unable to dump envoy config: Get "http://admin/config_dump?include_eds": dial unix /var/run/cilium/envoy-admin.sock: connect: no such file or directory

⚠️ gops-cilium-b7g55-stack: failed to list processes "cilium-b7g55" ("cilium-agent") in namespace "kube-system": unable to upgrade connection: container not found ("cilium-agent")
⚠️ hubble-flows-cilium-pdh9m: failed to collect hubble flows for "cilium-pdh9m" in namespace "kube-system": command terminated with exit code 1: time="2023-02-07T15:54:08Z" level=debug msg="Sending GetFlows request" request="number:10000 follow:true"
unknown response type: &{LostEvents:source:HUBBLE_RING_BUFFER num_events_lost:1}
rpc error: code = Unavailable desc = error reading from server: read unix @->/var/run/cilium/hubble.sock: read: connection reset by peer

⚠️ cilium-bugtool-cilium-pdh9m: failed to collect 'cilium-bugtool' output for "cilium-pdh9m" in namespace "kube-system": command terminated with exit code 137: Unable to dump envoy config: Get "http://admin/config_dump?include_eds": dial unix /var/run/cilium/envoy-admin.sock: connect: no such file or directory

⚠️ gops-cilium-hhhnp-memstats: failed to list processes "cilium-hhhnp" ("cilium-agent") in namespace "kube-system": command terminated with exit code 137
⚠️ gops-cilium-pdh9m-memstats: failed to list processes "cilium-pdh9m" ("cilium-agent") in namespace "kube-system": unable to upgrade connection: container not found ("cilium-agent")
⚠️ Please note that depending on your Cilium version and installation options, this may be expected
🗳 Compiling sysdump
✅ The sysdump has been saved to /root/setup_scripts/cilium-sysdump-20230207-155349.zip
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
