### ISSUE TITLE
ENI: security-group-tags not working

### ISSUE THREAD

**Issue by blang** [cilium/cilium#23678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Specifying `spec.eni.security-group-tags` in custom cni-config has no effect.**

Debugging information:
- Similar fields like `spec.eni.security-groups` and `spec.eni.subnet-tags` work.
- SNI Debug reveals that `security-group-tags` get properly parsed (see logs below).
- `ciliumnode` resource after startup does contain all fields except for `security-group-tags`:
```yaml
apiVersion: cilium.io/v2
kind: CiliumNode
spec:
  alibaba-cloud: {}
  azure: {}
  encryption: {}
  eni:
    availability-zone: eu-central-1a
    disable-prefix-delegation: false
    first-interface-index: 1
    instance-type: r5a.large
    subnet-tags:
      testing-subnet: "true"
    use-primary-address: false
    vpc-id: vpc-03bdc4a64bd4a96d8
```

- Status field in `ciliumnode` reveals it uses security groups from first eni.

CNI Custom config:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-cni-config
data:
  cni-config: |-
    {
      "cniVersion":"0.3.1",
      "name":"cilium",
      "plugins": [
        {
          "cniVersion":"0.3.1",
          "type":"cilium-cni",
          "eni": {
            "vpc-id": "vpc-03bdc4a64bd4a96d8",
            "first-interface-index": 1,
            "security-group-tags": {
              "testing-sg": "true"
            },
            "subnet-tags": {
              "testing-subnet": "true"
            }
          },
          "enable-debug": true,
          "log-file": "/var/run/cilium/cilium-cni.log"
        }
      ]
    }
```

Setup considerations:
- Node role has permissions `ec2:DescribeSecurityGroups`.
- Agent reports all security groups in log: `level=info msg="Synchronized ENI information" numInstances=10 numSecurityGroups=9 numSubnets=33 numVPCs=2 subsys=eni`

### Cilium Version

```
cilium-cli: v0.12.12 compiled with go1.19.4 on linux/amd64
cilium image (default): v1.12.5
cilium image (stable): v1.12.6
cilium image (running): v1.12.5
```

### Kernel Version

AWS Bottlerocket, 5.10.157

### Kubernetes Version

v1.23.14-eks-ffeb93d

### Sysdump

Will provide upon request

### Relevant log output

Cilium CNI Debug log:

```shell
level=debug msg="CNI NetConf: &types.NetConf{NetConf:types.NetConf{CNIVersion:\"0.3.1\", Name:\"cilium\", Type:\"cilium-cni\", Capabilities:map[string]bool(nil), IPAM:types.IPAM{Type:\"\"}, DNS:types.DNS{Nameservers:[]string(nil), Domain:\"\", Search:[]string(nil), Options:[]string(nil)}, RawPrevResult:map[string]interface {}(nil), PrevResult:types.Result(nil)}, MTU:0, Args:types.Args{}, ENI:types.ENISpec{InstanceID:\"\", InstanceType:\"\", MinAllocate:0, PreAllocate:0, MaxAboveWatermark:0, FirstInterfaceIndex:(*int)(0xc00030d980), SecurityGroups:[]string(nil), SecurityGroupTags:map[string]string{\"testing-sg\":\"true\"}, SubnetIDs:[]string(nil), SubnetTags:map[string]string{\"testing-subnet\":\"true\"}, VpcID:\"vpc-03bdc4a64bd4a96d8\", AvailabilityZone:\"\", ExcludeInterfaceTags:map[string]string(nil), DeleteOnTermination:(*bool)(nil), UsePrimaryAddress:(*bool)(nil), DisablePrefixDelegation:(*bool)(nil)}, Azure:types.AzureSpec{InterfaceName:\"\"}, IPAM:types.IPAM{IPAM:types.IPAM{Type:\"\"}, IPAMSpec:types.IPAMSpec{Pool:types.AllocationMap(nil), PodCIDRs:[]string(nil), MinAllocate:0, MaxAllocate:0, PreAllocate:0, MaxAboveWatermark:0, PodCIDRAllocationThreshold:0, PodCIDRReleaseThreshold:0}}, AlibabaCloud:types.Spec{InstanceType:\"\", AvailabilityZone:\"\", VPCID:\"\", CIDRBlock:\"\", VSwitches:[]string(nil), VSwitchTags:map[string]string(nil), SecurityGroups:[]string(nil), SecurityGroupTags:map[string]string(nil)}, EnableDebug:true, LogFormat:\"\", LogFile:\"/var/run/cilium/cilium-cni.log\"}" eventUUID=c7b55ec1-a809-401e-8091-8e5ab0e1b84c subsys=cilium-cni
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
