### ISSUE TITLE
CFP: Support AWS Metadata for external access for AWS Privatelink

### ISSUE THREAD

**Issue by georgew5656** [cilium/cilium#23677]
## Cilium Feature Proposal
        

**Is your feature request related to a problem?**
We are unable to use (https://docs.cilium.io/en/stable/gettingstarted/aws/#locking-down-external-access-using-aws-metadata) to lock down access to external VPC endpoints in our cilium enabled EKS cluster.

**Describe the feature you'd like**
Cilium currently supports network policies that look like the below
```
  endpointSelector:
    matchLabels:
      org: alliance
      class: xwing
  egress:
  - toPorts:
    - ports:
      - port: '80'
        protocol: TCP
    toGroups:
    - aws:
        securityGroupsIds:
        - 'sg-0f2146100a88d03c3'
```

where pods with a label can be allowed to access any ec2 instances running under sg-0f2146100a88d03c3.

We would like this to also apply to AWS VPC Interface Endpoints (Privatelink) that are also running under the specified security group id.

See: https://docs.aws.amazon.com/vpc/latest/privatelink/what-is-privatelink.html

**(Optional) Describe your proposed solution**
I'm not 100% sure about how this solution is implemented, but it seems like currently we just run ec2 describe-instances and filter by anything with one of the securityGroupIds, then lookup the IP's for those instances and filter by them.

If this is the case, it should be a simple matter of also running ec2 describe-vpc-endpoints and filtering those by the securityGroupIds as well, then filtering the resolved ips.

Maybe for backwards compatibility this should only be enabled with another flag like
```
- aws:
      vpcEndpointSecurityGroupIds:
     - 'sg-12345'
```
