### ISSUE TITLE
CFP: support advertising cluster IPs via BGP

### ISSUE THREAD

**Issue by ivandyukov** [cilium/cilium#23765]
(note from @nbusseneau: this was originally an issue submitted by @ivandyukov, which is recycled into a feature request as per the discussions below)

**Is your feature request related to a problem?**

1. setup cilium with bgp-announce-lb-ip: "True"
2. setup address-pools in bgp config:
    
```
 address-pools:
     - name: default
       protocol: bgp
       addresses:
       - 10.0.20.0/24
```

3. create service with specific externalIP:

```
 apiVersion: v1
 kind: Service
 metadata:
   name: test-lb-envoy-http
 spec:
   type: LoadBalancer
   ports:
   - port: 80
     targetPort: 8080
     protocol: TCP
     name: tcpport1
   selector:
     svc: test-lb-envoy-http
   externalIPs:
   - 10.0.20.22
 ---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: envoy-http
 spec:
   replicas: 1
   selector:
     matchLabels:
       svc: test-lb-envoy-http
   template:
     metadata:
       labels:
         svc: test-lb-envoy-http
     spec:
       tolerations:
       - effect: NoSchedule
         key: node-role.kubernetes.io/control-plane
       volumes:
       - name: envoy-config
         hostPath:
           path: /etc/envoy/envoy_http.yaml
           type: FileOrCreate
       containers:
       - name: envoy-http
         image: envoyproxy/envoy:v1.25.0
         imagePullPolicy: IfNotPresent
         ports:
         - containerPort: 8080
         volumeMounts:
         - name: envoy-config
           mountPath: /etc/envoy/envoy.yaml
 
         readinessProbe:
           exec:
             command:
               - ps
               - -aux
           initialDelaySeconds: 15
           periodSeconds: 20
```

BUG#1: no bgp annoncement of specified external service IP
BUG#2: service is not available on specified external ip even from k8s master. it's just ignored by cilium

**Describe the feature you'd like**

Cilium supports advertising cluster IPs via BGP.
