### ISSUE TITLE
BGP Control Plane is not used

### ISSUE THREAD

**Issue by krouma** [cilium/cilium#23817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The cilium-agent tries to use MetalLBSpeaker even when I set `bgpControlPlane.enabled=true` in helm values. I'm trying to announce PodIPs in a IPv6 single-stack cluster. I have set the router-id on nodes.

### Cilium Version

1.13.0

### Kernel Version

6.1.10-200.fc37.x86_64

### Kubernetes Version

1.25.6

### Relevant log output

```shell
level=info msg="processing new event." component=MetalLBSpeaker.run subsys=bgp-speaker
level=info msg="Advertising CIDRs to all available session" advertisements="[<redacted>]" component=MetalLBSpeaker.announcePodCidrs subsys=bgp-speaker
level=error msg="Failed to announce pod CIDRs" CIDRs="&[<redacted>]" cidrs="&[<redacted>]" component=MetalLBSpeaker.handleNodeEvent error="cannot advertise non-v4 prefix \"<redacted>\"" labels="&map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux hailstone.cz/hypervisor:bare-metal kubernetes.io/arch:amd64 kubernetes.io/hostname:isengard kubernetes.io/os:linux node-role.kubernetes.io/control-plane: node.kubernetes.io/exclude-from-external-load-balancers:]" subsys=bgp-speaker
```

### Anything else?

Relevant helm values:
```
autoDirectNodeRoutes: true

bgp:
  enabled: true
  announce:
    loadBalancerIP: true
    podCIDR: true

bgpControlPlane:
  enabled: true

bpf:
  lbExternalClusterIP: true


ipam:
  mode: kubernetes

ipv4:
  enabled: false

ipv6:
  enabled: true

ipv6NativeRoutingCIDR: "{{ ipv6_lan_network }}"

enableIPv6Masquerade: false

kubeProxyReplacement: strict
kubeProxyReplacementHealtzBindAddr: "[::]:10256"

k8sServiceHost: "{{ ipv6_addr }}"
k8sServicePort: 6443

loadBalancer:
  mode: dsr

tunnel: disabled
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
