### ISSUE TITLE
NetworkPolicy: `toGroups` rule in `egressDeny` policy doesn't generate derivative policy 

### ISSUE THREAD

**Issue by rockc2020** [cilium/cilium#23829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I followed the document [Locking down external access using AWS metadata](https://docs.cilium.io/en/stable/gettingstarted/aws/) to create a `toGroups` rule with an AWS security group id under the `egress` policy and an derivative policy can be generated with my ec2 instance IPs.
Here is the policy:
```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: egress-default
  namespace: network-multitool
spec:
  egress:
    - toGroups:
        - aws:
            securityGroupsIds:
              - sg-07283569446d92723
  endpointSelector: {}
```
The generated derivative policy is:
```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  labels:
    io.cilium.network.policy.kind: derivative
    io.cilium.network.policy.parent.uuid: a45969bd-1b05-47a5-8147-3895e2b5da96
  name: egress-default-togroups-a45969bd-1b05-47a5-8147-3895e2b5da96
  namespace: network-multitool
specs:
  - egress:
      - toCIDRSet:
          - cidr: 10.103.10.122/32
          - cidr: 10.103.25.222/32
          - cidr: 10.103.217.142/32
    endpointSelector:
      matchLabels:
        k8s:io.kubernetes.pod.namespace: network-multitool
    labels:
      - key: io.cilium.k8s.policy.derived-from
        source: k8s
        value: CiliumNetworkPolicy
      - key: io.cilium.k8s.policy.name
        source: k8s
        value: egress-default
      - key: io.cilium.k8s.policy.namespace
        source: k8s
        value: network-multitool
      - key: io.cilium.k8s.policy.uid
        source: k8s
        value: a45969bd-1b05-47a5-8147-3895e2b5da96
```

Well, when I update the CNP by changing the `egress` to `egressDeny`, there is no derivative policy generated (the previous one was deleted by cilium operator after the update).
Here is the CNP after being updated:
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: egress-default
  namespace: network-multitool
spec:
  egressDeny:
    - toGroups:
        - aws:
            securityGroupsIds:
              - sg-07283569446d92723
  endpointSelector: {}
```
There is a log from `cilium-operator` pod:
```
level=info msg="New CNP does not have derivative policy, but old had. Deleting old policies" ciliumNetworkPolicyName=egress-default k8sNamespace=network-multitool subsys=Groups
```

Then, it looks like being logged from here https://github.com/cilium/cilium/blob/4b803e9cdf4a9365b12c158787abbe2172d5321c/pkg/policy/groups/actions.go#L72-L76 that the `newCNP.RequiresDerivative()` returns `true`.

When I dug a bit more codes, it looks like the the follow codes only check `Egress` field of `Rule` but missed checking `EgressDeny` field. https://github.com/cilium/cilium/blob/4b803e9cdf4a9365b12c158787abbe2172d5321c/pkg/policy/api/rule.go#L207-L214

```go
func (r *Rule) RequiresDerivative() bool {
	for _, rule := range r.Egress {
		if rule.RequiresDerivative() {
			return true
		}
	}
	return false
}
```
Also, the derivative policy creation for `egressDeny` is also missed from the method `CreateDerivative` just below it.
https://github.com/cilium/cilium/blob/4b803e9cdf4a9365b12c158787abbe2172d5321c/pkg/policy/api/rule.go#L218-L230

### Cilium Version

```
root@ip-10-103-111-49:/home/cilium# cilium version
Client: 1.12.4 6eaecaf 2022-11-16T05:45:01+00:00 go version go1.18.8 linux/amd64
Daemon: 1.12.4 6eaecaf 2022-11-16T05:45:01+00:00 go version go1.18.8 linux/amd64
```

### Kernel Version

```
Linux ip-10-103-111-49.us-east-2.compute.internal 5.4.228-131.415.amzn2.x86_64 #1 SMP Tue Dec 20 12:51:02 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.16-eks-ffeb93d", GitCommit:"52e500d139bdef42fbc4540c357f0565c7867a81", GitTreeState:"clean", BuildDate:"2022-11-29T18:41:42Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

### Anything else?

I am assuming `toGroups` should be supported by `egressDeny` since it is defined in the CNP's CRD and not sure if this is intentional.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
