### ISSUE TITLE
LRP with node-local-dns can't reach ClusterIP for forwarding

### ISSUE THREAD

**Issue by Elegant996** [cilium/cilium#23848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Deployed node-local-dns per the LRP cilium guide. All traffic properly redirects to the pods of the node-local-dns. When the node-local-dns pods forward their traffic back to the original ClusterIP of kube-dns/coredns for lookup, it only succeeds if one of the kube-dns/coredns pods is running on that node.

To be clear, the daemonset for node-local-dns runs on all nodes but forwarding only happens on nodes that contain a pod belonging to the kube-dns/core deployment (not all nodes have a pod from this deployment).

The current cilium config and a screenshot from hubble when the incident occurs can be seen below. The ClusterIP for coredns is at 10.96.0.10. Had to schedule both coredns and hubble pods on same node otherwise hubble could not lookup cilium...

Removing the LRP resource restores DNS.

Thanks!

### Cilium Version

v1.13.0

### Kernel Version

6.1.6-200.fc37.x86_64

### Kubernetes Version

v1.26.0

### Sysdump

[cilium-sysdump-20230217-235319.zip](https://github.com/cilium/cilium/files/10768262/cilium-sysdump-20230217-235319.zip)

### Anything else?

![Screenshot 2023-02-17 231947](https://user-images.githubusercontent.com/873556/219680341-cb3af97c-f754-49a9-ad05-58127e4f7865.jpg)

```
agent-not-ready-taint-key: node.cilium.io/agent-not-ready
arping-refresh-period: 30s
auto-direct-node-routes: "true"
bpf-lb-external-clusterip: "true"
bpf-lb-map-max: "65536"
bpf-lb-mode: dsr
bpf-lb-sock: "false"
bpf-map-dynamic-size-ratio: "0.0025"
bpf-policy-map-max: "16384"
bpf-root: /sys/fs/bpf
cgroup-root: /run/cilium/cgroupv2
cilium-endpoint-gc-interval: 5m0s
cluster-id: "0"
cluster-name: default
custom-cni-conf: "false"
debug: "false"
devices: ens192
disable-cnp-status-updates: "true"
disable-endpoint-crd: "false"
enable-auto-protect-node-port-range: "true"
enable-bgp-control-plane: "true"
enable-bpf-clock-probe: "true"
enable-bpf-masquerade: "true"
enable-endpoint-health-checking: "true"
enable-endpoint-routes: "true"
enable-health-check-nodeport: "true"
enable-health-checking: "true"
enable-hubble: "true"
enable-ip-masq-agent: "true"
enable-ipv4: "true"
enable-ipv4-egress-gateway: "true"
enable-ipv4-masquerade: "true"
enable-ipv6: "false"
enable-ipv6-big-tcp: "false"
enable-ipv6-masquerade: "true"
enable-k8s-terminating-endpoint: "true"
enable-l2-neigh-discovery: "true"
enable-l7-proxy: "false"
enable-local-redirect-policy: "true"
enable-pmtu-discovery: "true"
enable-policy: default
enable-remote-node-identity: "true"
enable-sctp: "false"
enable-svc-source-range-check: "true"
enable-vtep: "false"
enable-well-known-identities: "false"
enable-xt-socket-fallback: "true"
hubble-disable-tls: "false"
hubble-listen-address: :4244
hubble-socket-path: /var/run/cilium/hubble.sock
hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
identity-allocation-mode: crd
identity-gc-interval: 15m0s
identity-heartbeat-timeout: 30m0s
install-iptables-rules: "false"
install-no-conntrack-iptables-rules: "false"
ipam: kubernetes
ipv4-native-routing-cidr: 10.244.0.0/17
k8s-require-ipv4-pod-cidr: "true"
kube-proxy-replacement: strict
kube-proxy-replacement-healthz-bind-address: ""
monitor-aggregation: medium
monitor-aggregation-flags: all
monitor-aggregation-interval: 5s
node-port-bind-protection: "true"
nodes-gc-interval: 5m0s
operator-api-serve-addr: 127.0.0.1:9234
preallocate-bpf-maps: "false"
procfs: /host/proc
remove-cilium-node-taints: "true"
set-cilium-is-up-condition: "true"
sidecar-istio-proxy-image: cilium/istio_proxy
skip-cnp-status-startup-clean: "false"
synchronize-k8s-nodes: "true"
tofqdns-dns-reject-response-code: refused
tofqdns-enable-dns-compression: "true"
tofqdns-endpoint-max-ip-per-hostname: "50"
tofqdns-idle-connection-grace-period: 0s
tofqdns-max-deferred-connection-deletes: "10000"
tofqdns-min-ttl: "3600"
tofqdns-proxy-response-max-delay: 100ms
tunnel: disabled
unmanaged-pod-watcher-interval: "15"
vtep-cidr: ""
vtep-endpoint: ""
vtep-mac: ""
vtep-mask: ""
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
Can you attach a sysdump from your cluster? Will need to to take a look at the cilium services and lrp state.

**Comment by Elegant996** [comment]
Sysdump attached. Thanks!

**Comment by Elegant996** [comment]
Still an ongoing issue. Thanks!

**Comment by jwitko** [comment]
Having the same issue currently

**Comment by Elegant996** [comment]
It's possible that it's tied to BGP routing. Since traffic is being redirected to the pod, the pod is then attempting to forward it to the upstream DNS service but it doesn't know how to reach it on nodes that do not have the service.

This would make sense since the BGP CP does not exchange routes to K8s services between nodes, so it has no idea. We could add a static route to FRR (or whatever you're peering with outside the cluster) to route the K8s service CIDR back to the nodes with speakers but this seems like a lot of extra steps and you'd save more cycles doing this the documented way with a `169.254.x.x` subnet and not through LRP.

We may need nodes to peer with each other internally so that they are aware of pod IPs for each assigned ClusterIP. The goal here might not be to do this for all services but yet another service selector for ClusterIPs similar to LoadBalancerIPs.

Not sure I'll have time to implement but this may make more sense as to why it's happening...

**Comment by Elegant996** [comment]
Still an ongoing issue, not sure when this is scheduled for review though...

**Comment by Elegant996** [comment]
Could this be re-opened? It's still an ongoing issue that is very much a shortcoming of LRP. Thanks!

**Comment by atsai1220** [comment]
In case anyone runs into this from the Internet, restarting Cilium operator got the ball rolling.

We got stuck configuring `CiliumLocalRedirectPolicy`. In our environment with Cilium 1.14.4, we had to specify `.spec.redirectFrontend.serviceMatcher.toPorts` otherwise the LRP list does not show the endpoints and traffic is not routed to node-local dns cache.

Here are the steps to verify:

1. Create this `CiliumLocalRedirectPolicy` without `.spec.redirectFrontend.serviceMatcher.toPorts`. This is as described in the [documentation](https://docs.cilium.io/en/v1.14/network/kubernetes/local-redirect-policy/#node-local-dns-cache) and the provided [example](https://raw.githubusercontent.com/cilium/cilium/v1.14/examples/kubernetes-local-redirect/node-local-dns-lrp.yaml).

```yaml
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: node-local-dns
  namespace: kube-system
spec:
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: node-local-dns
    toPorts:
    - name: dns
      port: "53"
      protocol: UDP
    - name: dns-tcp
      port: "53"
      protocol: TCP
  redirectFrontend:
    serviceMatcher:
      namespace: kube-system
      serviceName: rke2-coredns-rke2-coredns
```

2. View your lrp list. You will _not_ see your pods on the right side of the arrow and traffic is not directed to node-local dns cache.

``` shell
❯ kubectl -n kube-system exec ds/cilium -- cilium lrp list
LRP namespace   LRP name         FrontendType                Matching Service
kube-system     node-local-dns   clusterIP + all svc ports   kube-system/rke2-coredns-rke2-coredns
                |                10.43.0.10:53/UDP ->
                |                10.43.0.10:53/TCP ->
```

3. Delete your existing lrp. At the time of writing, there is a [limitation](https://docs.cilium.io/en/v1.14/network/kubernetes/local-redirect-policy/#limitations) that prevents modifications to an existing lrp.
```
kubectl delete ciliumlocalredirectpolicies -n kube-system node-local-dns
```

4. Create a new `CiliumLocalRedirectPolicy` with `.spec.redirectFrontend.serviceMatcher.toPorts`.
```yaml
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: node-local-dns
  namespace: kube-system
spec:
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: node-local-dns
    toPorts:
    - name: dns
      port: "53"
      protocol: UDP
    - name: dns-tcp
      port: "53"
      protocol: TCP
  redirectFrontend:
    serviceMatcher:
      namespace: kube-system
      serviceName: rke2-coredns-rke2-coredns
      toPorts:
        - name: dns-tcp
          port: "53"
          protocol: TCP
        - name: dns
          port: "53"
          protocol: UDP
```
5. Verify your lrp list has backend pods and traffic routed to your node-local dns cache. The output will show your node-local-dns pod IPs.

```shell
❯ kubectl -n kube-system exec ds/cilium -- cilium lrp list
LRP namespace   LRP name         FrontendType              Matching Service
kube-system     node-local-dns   clusterIP + named ports   kube-system/rke2-coredns-rke2-coredns
                |                10.43.0.10:53/TCP -> 10.42.3.193:53(kube-system/node-local-dns-sbtdr),
                |                10.43.0.10:53/UDP -> 10.42.3.193:53(kube-system/node-local-dns-sbtdr),
```
