### ISSUE TITLE
ipv6-only cluster + KPR/wireguard: connectivity breaks after agent restart

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#23840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The issue can be reproduced with the following:
1. Install cilium on an ipv6-only cluster, in direct routing mode and with wireguard encryption enabled
2. Restart the cilium agent pods
3. Observe that node-to-pod connectivity breaks

The same issue occurs when wireguard is disabled, and kube-proxy replacement is enabled. It does not occur in IPv4-only clusters.

### Cilium Version

Latest commit available on master as of today (499846cb58db7635ba518e4123aa1158431e4c26).
The issue with KPR reproduced also on v1.11. As for Wireguard, it does not apply to v1.13 and earlier, since they do not support wireguard on ipv6-only clusters (#https://github.com/cilium/cilium/issues/23545, https://github.com/cilium/cilium/pull/23552)

### Kernel Version

Linux ubuntu-focal 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.25.3

### Sysdump

[cilium-sysdump-20230217-080109.zip](https://github.com/cilium/cilium/files/10764649/cilium-sysdump-20230217-080109.zip)

### Relevant log output

```shell
$ cilium-health status (after restart)

cilium-health status
Probe time:   2023-02-17T08:09:40Z
Nodes:
  kind-kind/kind-control-plane (localhost):
    Host connectivity to fc00:f853:ccd:e793::2:
      ICMP to stack:   OK, RTT=1.01174ms
      HTTP to agent:   OK, RTT=407.288µs
    Endpoint connectivity to fd00:10:242::a57:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://[fd00:10:242::a57]:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  kind-kind/kind-worker:
    Host connectivity to fc00:f853:ccd:e793::3:
      ICMP to stack:   OK, RTT=983.503µs
      HTTP to agent:   OK, RTT=1.279184ms
    Endpoint connectivity to fd00:10:242:1::f53e:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://[fd00:10:242:1::f53e]:4240/hello": dial tcp [fd00:10:242:1::f53e]:4240: connect: no route to host
```

### Anything else?

Cilium was installed through:

```
cilium install --chart-directory=install/kubernetes/cilium \
    --helm-set=image.repository=quay.io/cilium/cilium-ci \
    --helm-set=image.useDigest=false \
    --helm-set=image.tag="499846cb58db7635ba518e4123aa1158431e4c26" \
    --helm-set=operator.image.repository=quay.io/cilium/operator \
    --helm-set=operator.image.suffix=-ci \
    --helm-set=operator.image.tag="499846cb58db7635ba518e4123aa1158431e4c26" \
    --helm-set=operator.image.useDigest=false \
    --config monitor-aggregation=none \
    --version="" \
    --helm-set-string=tunnel=disabled \
    --helm-set=autoDirectNodeRoutes=true \
    --helm-set=ipv6NativeRoutingCIDR=fd00:10:240::/44 \
    --helm-set=ipv4.enabled=false \
    --helm-set=ipv6.enabled=true \
    --helm-set=ipv4NativeRoutingCIDR=10.240.0.0/12 \
    --encryption=wireguard
```

Kind cluster configuration:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
      # To make sure that there is no taint for master node.
      # Otherwise additional worker node might be required for conformance testing.
      - |
        apiVersion: kubeadm.k8s.io/v1beta3
        kind: InitConfiguration
        nodeRegistration:
          taints: []
- role: worker
networking:
  disableDefaultCNI: true
  ipFamily: ipv6
  podSubnet: fd00:10:242::/48
  serviceSubnet: fd00:10:243::/112
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
