### ISSUE TITLE
Ingress: upstream connect error or disconnect/reset before headers.

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#23906]
### Description

This is reported in Cilium OSS slack by Brandon Mcnama https://cilium.slack.com/archives/C53TG4J4R/p1676675736396739

> Hey all, I bumped Cilium to 1.13.0 just now and none of my Ingress services are working. All of them are resulting in upstream connect error or disconnect/reset before headers. reset reason: connection failure, though TLS termination is working correctly

### Sysdump

Sysdump was shared via DM as well, but it's bigger than the limit in Github.

**Comment by DWSR** [comment]
There are other reports of similar behaviour as well:

https://cilium.slack.com/archives/C1MATJ5U5/p1676916171268779
> After upgrading from 1.12.5 to 1.13.0, Ingresses aren't reachable by clients in the cluster anymore and they get a Operation not permitted. I'll be troubleshooting the problem today, but wondering if anyone has experienced it before (nothing on GH issues yet).

https://cilium.slack.com/archives/C1MATJ5U5/p1676916171268779
> Hello, I tried using cilium ingress, but I get: upstream connect error or cancel/reset before headers. reset reason: connection failure
cilium image (running): v1.13.0

**Comment by DWSR** [comment]
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cilium-system

resources:
  - namespace.yaml
  - bgpcontrolplane.yaml

helmCharts:
  - name: "cilium"
    repo: https://helm.cilium.io
    version: "1.13.0"
    namespace: "cilium-system"
    releaseName: cilium
    includeCRDs: true
    valuesInline:
      image:
        pullPolicy: Always
      apiserver:
        image:
          pullPolicy: Always
        etcd:
          image:
            pullPolicy: Always
      preflight:
        enabled: false
        image:
          pullPolicy: Always
      nodeinit:
        image:
          pullPolicy: Always
      cluster:
        name: prod-19-parker
        id: 1
      endpointStatus:
        enabled: true
        status: "policy"  
      priorityClassName: system-node-critical
      # Workaround for this issue: https://github.com/cilium/cilium/issues/21603
      securityContext:
        privileged: true
      installNoConntrackIptablesRules: true
      enableXTSocketFallback: false
      autoDirectNodeRoutes: true
      # Can't be enabled until 1.14 due to incompatibility with L7 proxy
      # https://github.com/cilium/cilium/commit/481015e34edd2d24206838c045ac08cec35a459e
      # encryption:
      #   enabled: true
      #   type: wireguard
      rollOutCiliumPods: true
      loadBalancer:
        mode: dsr
        serviceTopology: true
        algorithm: maglev
      ingressController:
        enabled: true
        loadbalancerMode: shared
        enforceHttps: true
        secretsNamespace:
          create: false
          name: cilium-system
          sync: true
        service:
          name: cilium-ingress
          type: LoadBalancer
          # insecureNodePort: 30080
          # secureNodePort: 30443
      # Do this instead of setting gatewayAPI.enabled true because doing that
      # results in invalid YAML; the enable-envoy-config key is duplicate
      # https://github.com/cilium/cilium/issues/23859
      # gatewayAPI:
      #   enabled: true
      #   secretsNamespace:
      #     name: cilium-system
      #     create: false
      extraConfig:
        enable-gateway-api: "true"
        enable-gateway-api-secrets-sync: "true"
        gateway-api-secrets-namespace: "cilium-system"
        # loadbalancer-l7: "envoy"
        # loadbalancer-l7-ports: ""
        # loadbalancer-l7-algorithm: "maglev"
      monitor:
        enabled: false
      bpf:
        clockProbe: true
        masquerade: true
        tproxy: true
        lbExternalClusterIP: true
      bgp:
        # enabled: true
        enabled: false
        announce:
          loadbalancerIP: true
          podCIDR: true
      bgpControlPlane:
        enabled: true
      tunnel: disabled
      ipMasqAgent:
        enabled: true
      ipam:
        mode: kubernetes
      extraVolumeMounts:
        - name: containerd-sock
          mountPath: /run/containerd/containerd.sock
      extraVolumes:
        - name: containerd-sock
          hostPath:
            path: /run/containerd/containerd.sock
            type: Socket
      containerRuntime:
        integration: containerd
        socketPath: /run/containerd/containerd.sock
      ipv4NativeRoutingCIDR: 192.168.192.0/18
      kubeProxyReplacement: strict
      k8sServiceHost: 192.168.192.7
      k8sServicePort: 6443
      hubble:
        relay:
          image:
            pullPolicy: Always
          enabled: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 64Mi
        ui:
          enabled: true
          backend:
            image:
              pullPolicy: Always
            resources:
              requests:
                cpu: 25m
                memory: 32Mi
              limits:
                memory: 32Mi
          frontend:
            image:
              pullPolicy: Always
            resources:
              requests:
                cpu: 25m
                memory: 32Mi
              limits:
                memory: 32Mi
      resources:
        requests:
          cpu: 250m 
          memory: 384Mi 
        limits:
          memory: 384Mi
      operator:
        image:
          pullPolicy: Always
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node-role.kubernetes.io/control-plane
                      operator: Exists
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  io.cilium/app: operator
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 64Mi

patches:
  - target:
      kind: ClusterRole
      name: cilium-operator
    patch: |-
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - gateway.networking.k8s.io
          resources:
            - gatewayclasses
            - gateways
            - httproutes
            - referencegrants
            - referencepolicies
          verbs:
            - get
            - list
            - watch
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - gateway.networking.k8s.io
          resources:
            - gatewayclasses/status
            - gateways/status
            - httproutes/status
          verbs:
            - update
            - patch
```

This is how I'm generating the Cilium manifests.

**Comment by DWSR** [comment]
I'm also seeing this on 1.13.1.

**Comment by michael-robbins** [comment]
I'm seeing this on 1.13.0 as well, getting `upstream connect error or disconnect/reset before headers. reset reason: connection failure` but can confirm via Hubble that the Ingress flows are allowed, the browser shows TLS is all fine.

I can also port forward the Service the ingress is being sent to and that works as well.

**Comment by julianwiedmann** [comment]
Some of the reported troubles here might be fixed in `v1.13.1` with https://github.com/cilium/cilium/commit/8306178e91325ed1a4be651e3b28d1f02f238e9e. So if you haven't done so yet, please test `v1.13.1`.

**Comment by TaylorFinklea** [comment]
I'm using 1.13.1 and am still having this issue. Here is my configuration using helm
```
export KUBERNETES_API_SERVER_ADDRESS=fdae:41e4:649b:9303::1
export KUBERNETES_API_SERVER_PORT=10001

helm template \
    cilium \
    cilium/cilium \
    --version 1.13.1 \
    --namespace kube-system \
    --set=ipam.mode=kubernetes \
    --set=kubeProxyReplacement=strict \
    --set=securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
    --set=securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
    --set=cgroup.autoMount.enabled=false \
    --set=cgroup.hostRoot=/sys/fs/cgroup \
    --set=k8sServiceHost="${KUBERNETES_API_SERVER_ADDRESS}" \
    --set=k8sServicePort="${KUBERNETES_API_SERVER_PORT}" \
    --set=ingressController.enabled=true \
    --set=ingressController.loadbalancerMode=dedicated \
    --set=hubble.enabled=true \
    --set=hubble.relay.enabled=true \
    --set=hubble.ui.enabled=true \
    --set=hubble.ui.standalone.enabled=true > cilium-strict.yaml
```

**Comment by DWSR** [comment]
I'm also seeing this on 1.13.1

**Comment by michael-robbins** [comment]
I've also tried this out on `1.13.2` and seeing the same behaviour, `upstream connect error or disconnect/reset before headers. reset reason: connection failure` message, Hubble reporting the flow as successful, able to port forward the underlying Service just fine, Ingress reports back with correct TLS cert/etc.

```
% helm install cilium cilium/cilium \
    --version 1.13.2 \
    --namespace kube-system \
    --set ipam.mode=kubernetes \
    --set kubeProxyReplacement=strict \
    --set enableXTSocketFallback=false \
    --set=securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
    --set=securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
    --set=cgroup.autoMount.enabled=false \
    --set=cgroup.hostRoot=/sys/fs/cgroup \
    --set k8sServiceHost="${KUBERNETES_API_SERVER_ADDRESS}" \
    --set k8sServicePort="${KUBERNETES_API_SERVER_PORT}" \
    --set ingressController.enabled=true \
    --set ingressController.loadbalancerMode=dedicated \
    --set hubble.relay.enabled=true \
    --set hubble.ui.enabled=true
```

**Comment by christarazi** [comment]
@sayboras Can you confirm whether the issue was resolved and close the ticket if so?

**Comment by sayboras** [comment]
> Can you confirm whether the issue was resolved and close the ticket if so?

Thanks for the ping, this is still under my radar, but I didn't have time to verify the setup originally raised by Brandon (e.g. dsr). Deeply appreciate if you can test it out with snapshot 2 Brandon 🙇‍♂️.

**Comment by TECHNOFAB11** [comment]
I had the same issue with 1.13 and 1.14 versions and can confirm that the error disappears with the latest snapshot (.2)

**Comment by justingarfield** [comment]
FWIW...While following the steps @ https://docs.cilium.io/en/stable/network/servicemesh/http/ I had this issue as well when using Cilium `v1.13.0`, `v1.13.1`, and `v1.13.2` on a fresh Talos Linux `v1.4` cluster w/ Kubernetes `1.27.1` (nothing else installed/deployed at this point).

Updating to the `v1.14.0-snapshot.2` release seems to have fixed it, as I can now get to the demo bookstore endpoints through an Ingress as expected.

**Comment by DWSR** [comment]
I upgraded to `v1.14.0-snapshot.2` and this appears to be resolved as well with Talos 1.4.

**Comment by frank-bee** [comment]
I am getting this error on AWS with this cilium config
```
helm_releases = {
    cilium = {
      name             = "cilium"
      chart            = "cilium"
      chart_version          = "1.15.4"
      repository       = "https://helm.cilium.io/"
      description      = "Cilium Add-on"
      namespace        = "kube-system"
      create_namespace = false

      values = [
        <<-EOT
          cni:
            chainingMode: aws-cni
            exclusive: false
          nodePort:
            enabled: true
          enableIPv4Masquerade: false
          routingMode: native
          tunnel: disabled
          endpointRoutes:
            enabled: true
          ingressController:
            enabled: true
            loadbalancerMode: shared
          gatewayAPI:
            enabled: true
          hubble:
            relay:
              enabled: true
            ui:
              enabled: true
        EOT
      ]
    }
  }
}
```

**Comment by listellm** [comment]
I am also getting this on AWS EKS.

It has been working absolutely fine and then overnight this issue has occured

```
k8s version = 1.29.0
AWS LB controller = v2.7.2
Cilium = 1.15.4
k8s gateway api version = 1.0.0 (experimental channel for Gateway crd
```

```
bandwidthManager:
  enabled: true
  bbr: false
bpf:
  preallocateMaps: true
endpointRoutes:
  enabled: true
rollOutCiliumPods: true
securityContext:
  privileged: true
operator:
  rollOutPods: true
eni:
  enabled: true
  updateEC2AdapterLimitViaAPI: true
  awsReleaseExcessIPs: true
  awsEnablePrefixDelegation: true
ipam:
  mode: "eni"
egressMasqueradeInterfaces: "eth0"
tunnel: disabled
routingMode: native
autoDirectNodeRoutes: true
installNoConntrackIptablesRules: true
kubeProxyReplacement: "true"
l2announcements:
  enabled: true
gatewayAPI:
  enabled: true
```
