### ISSUE TITLE
Possible bootstrap problem with host firewall enabled

### ISSUE THREAD

**Issue by devasmith** [cilium/cilium#23978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Whenever I perform a rollout restart of the cilium daemonset `kubectl -n kube-system rollout restart daemonset/cilium`, I get connectivity issues for quite some time. This seems to be affecting both `etcd` and the `apiserver`, both these services are using `hostNetwork: true` so they are not managed by Cilium.

The control plane nodes that has `etcd` are recognised as `remote-node` AND `world` but not as `kube-apiserver` during this time. SYN and ACK between control plane nodes gets denied for a while. Monitoring with `hubble observe -f --verdict ERROR --verdict DROPPED`. See logs further down.

Output from `stern-t -n kube-system kube-apiserver` during a configmap change and rollout restart:

```sh
kube-apiserver-k8s-dev002-master001.example.com kube-apiserver 2023-02-24T08:49:28.267720557+01:00 E0224 07:49:28.267490       1 upgradeaware.go:440] Error proxying data from backend to client: write tcp 127.0.0.1:6443->127.0.0.1:37792: write: broken pipe
kube-apiserver-k8s-dev002-master001.example.com kube-apiserver 2023-02-24T08:49:29.097008527+01:00 E0224 07:49:29.096822       1 upgradeaware.go:426] Error proxying data from client to backend: write tcp 127.0.0.1:12246->127.0.0.1:9345: write: broken pipe
kube-apiserver-k8s-dev002-master001.example.com kube-apiserver 2023-02-24T08:49:33.409712230+01:00 E0224 07:49:33.409255       1 upgradeaware.go:440] Error proxying data from backend to client: write tcp 127.0.0.1:6443->127.0.0.1:24414: write: broken pipe
kube-apiserver-k8s-dev002-master001.example.com kube-apiserver 2023-02-24T08:49:42.066161879+01:00 E0224 07:49:42.065890       1 upgradeaware.go:440] Error proxying data from backend to client: write tcp 127.0.0.1:6443->127.0.0.1:32786: write: broken pipe
kube-apiserver-k8s-dev002-master001.example.com kube-apiserver 2023-02-24T08:49:44.210418034+01:00 E0224 07:49:44.210306       1 upgradeaware.go:440] Error proxying data from backend to client: write tcp 127.0.0.1:6443->127.0.0.1:32806: write: broken pipe
kube-apiserver-k8s-dev002-master001.example.com kube-apiserver 2023-02-24T08:49:44.210530452+01:00 E0224 07:49:44.210454       1 upgradeaware.go:426] Error proxying data from client to backend: write tcp 127.0.0.1:18942->127.0.0.1:9345: write: broken pipe
kube-apiserver-k8s-dev002-master001.example.com kube-apiserver 2023-02-24t08:49:48.574841336+01:00 e0224 07:49:48.574598       1 upgradeaware.go:440] error proxying data from backend to client: write tcp 127.0.0.1:6443->127.0.0.1:32846: write: connection reset ggby peer
kube-apiserver-k8s-dev002-master001.example.com kube-apiserver 2023-02-24T08:50:18.415178487+01:00 E0224 07:50:18.415133       1 watcher.go:227] watch chan error: etcdserver: no leader
```

Output from `stern-t -n kube-system etcd` during a configmap change and rollout restart:

```sh
etcd-k8s-dev002-master002.example.com etcd 2023-02-24T09:17:11.968052686+01:00 {"level":"warn","ts":"2023-02-24T08:17:11.965Z","caller":"v3rpc/interceptor.go:197","msg":"request stats","start time":"2023-02-24T08:16:42.097Z","time spent":"29.868758045s","remote":"127.0.0.1:41840","response type":"/etcdserverpb.KV/Range","request count":0,"request size":60,"response count":0,"response size":0,"request content":"key:\"/registry/leases/kube-system/cilium-operator-resource-lock\" "}
etcd-k8s-dev002-master002.example.com etcd 2023-02-24T09:17:11.968056503+01:00 {"level":"warn","ts":"2023-02-24T08:17:11.965Z","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"29.992484841s","expected-duration":"100ms","prefix":"read-only range ","request":"key:\"/registry/namespaces/\" range_end:\"/registry/namespaces0\" count_only:true ","response":"","error":"etcdserver: request timed out"}
etcd-k8s-dev002-master002.example.com etcd 2023-02-24T09:17:11.968060103+01:00 {"level":"info","ts":"2023-02-24T08:17:11.965Z","caller":"traceutil/trace.go:171","msg":"trace[718835568] range","detail":"{range_begin:/registry/namespaces/; range_end:/registry/namespaces0; }","duration":"29.992503464s","start":"2023-02-24T08:16:41.973Z","end":"2023-02-24T08:17:11.965Z","steps":["trace[718835568] 'agreement among raft nodes before linearized reading'  (duration: 29.992485431s)"],"step_count":1}
etcd-k8s-dev002-master002.example.com etcd 2023-02-24T09:17:11.968064070+01:00 {"level":"warn","ts":"2023-02-24T08:17:11.965Z","caller":"v3rpc/interceptor.go:197","msg":"request stats","start time":"2023-02-24T08:16:41.973Z","time spent":"29.992534368s","remote":"127.0.0.1:41680","response type":"/etcdserverpb.KV/Range","request count":0,"request size":48,"response count":0,"response size":0,"request content":"key:\"/registry/namespaces/\" range_end:\"/registry/namespaces0\" count_only:true "}
etcd-k8s-dev002-master001.example.com etcd 2023-02-24T09:17:12.109068710+01:00 {"level":"warn","ts":"2023-02-24T08:17:12.108Z","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"4.999075119s","expected-duration":"100ms","prefix":"read-only range ","request":"key:\"/registry/leases/kube-system/kube-scheduler\" ","response":"","error":"context deadline exceeded"}
etcd-k8s-dev002-master001.example.com etcd 2023-02-24T09:17:12.109151892+01:00 {"level":"info","ts":"2023-02-24T08:17:12.109Z","caller":"traceutil/trace.go:171","msg":"trace[422194424] range","detail":"{range_begin:/registry/leases/kube-system/kube-scheduler; range_end:; }","duration":"4.999853233s","start":"2023-02-24T08:17:07.109Z","end":"2023-02-24T08:17:12.108Z","steps":["trace[422194424] 'agreement among raft nodes before linearized reading'  (duration: 4.999073584s)"],"step_count":1}
etcd-k8s-dev002-master001.example.com etcd 2023-02-24T09:17:12.109470477+01:00 {"level":"warn","ts":"2023-02-24T08:17:12.109Z","caller":"v3rpc/interceptor.go:197","msg":"request stats","start time":"2023-02-24T08:17:07.109Z","time spent":"4.999902795s","remote":"127.0.0.1:26556","response type":"/etcdserverpb.KV/Range","request count":0,"request size":45,"response count":0,"response size":0,"request content":"key:\"/registry/leases/kube-system/kube-scheduler\" "}
etcd-k8s-dev002-master003.example.com etcd 2023-02-24T09:17:12.243993371+01:00 {"level":"warn","ts":"2023-02-24T08:17:12.243Z","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"4.99895223s","expected-duration":"100ms","prefix":"read-only range ","request":"key:\"/registry/leases/kube-system/kube-controller-manager\" ","response":"","error":"context deadline exceeded"}
etcd-k8s-dev002-master003.example.com etcd 2023-02-24T09:17:12.244013064+01:00 {"level":"info","ts":"2023-02-24T08:17:12.243Z","caller":"traceutil/trace.go:171","msg":"trace[1705358601] range","detail":"{range_begin:/registry/leases/kube-system/kube-controller-manager; range_end:; }","duration":"4.999017195s","start":"2023-02-24T08:17:07.244Z","end":"2023-02-24T08:17:12.243Z","steps":["trace[1705358601] 'agreement among raft nodes before linearized reading'  (duration: 4.998950857s)"],"step_count":1}
etcd-k8s-dev002-master003.example.com etcd 2023-02-24T09:17:12.244023368+01:00 {"level":"warn","ts":"2023-02-24T08:17:12.243Z","caller":"v3rpc/interceptor.go:197","msg":"request stats","start time":"2023-02-24T08:17:07.244Z","time spent":"4.999063403s","remote":"127.0.0.1:25304","response type":"/etcdserverpb.KV/Range","request count":0,"request size":54,"response count":0,"response size":0,"request content":"key:\"/registry/leases/kube-system/kube-controller-manager\" "}
etcd-k8s-dev002-master003.example.com etcd 2023-02-24T09:17:12.257759114+01:00 {"level":"warn","ts":"2023-02-24T08:17:12.257Z","caller":"etcdserver/v3_server.go:852","msg":"timed out waiting for read index response (local node might have slow network)","timeout":"15s"}
```

I've also installed `cilium-cli` on one of the nodes to check how fast cilium gets back in good shape during this operation.

With host firewall enabled:

```sh
# time cilium status --wait
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         OK
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         OK
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

Deployment        hubble-relay       Desired: 1, Ready: 1/1, Available: 1/1
Deployment        hubble-ui          Desired: 1, Ready: 1/1, Available: 1/1
DaemonSet         cilium             Desired: 3, Ready: 3/3, Available: 3/3
Deployment        cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
Containers:       hubble-ui          Running: 1
                  cilium-operator    Running: 2
                  hubble-relay       Running: 1
                  cilium             Running: 3
Cluster Pods:     8/8 managed by Cilium
Image versions    cilium             rancher/mirrored-cilium-cilium:v1.12.4: 3
                  hubble-ui          rancher/mirrored-cilium-hubble-ui:v0.9.2: 1
                  hubble-ui          rancher/mirrored-cilium-hubble-ui-backend:v0.9.2: 1
                  cilium-operator    rancher/mirrored-cilium-operator-generic:v1.12.4: 2
                  hubble-relay       rancher/mirrored-cilium-hubble-relay:v1.12.4: 1

real    1m42.591s
user    0m0.843s
sys     0m0.132s
```

With host firewall disabled:
```sh
# time cilium status --wait
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         OK
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         OK
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

Deployment        hubble-ui          Desired: 1, Ready: 1/1, Available: 1/1
Deployment        hubble-relay       Desired: 1, Ready: 1/1, Available: 1/1
Deployment        cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
DaemonSet         cilium             Desired: 3, Ready: 3/3, Available: 3/3
Containers:       hubble-ui          Running: 1
                  hubble-relay       Running: 1
                  cilium-operator    Running: 2
                  cilium             Running: 3
Cluster Pods:     8/8 managed by Cilium
Image versions    cilium             rancher/mirrored-cilium-cilium:v1.12.4: 3
                  hubble-ui          rancher/mirrored-cilium-hubble-ui:v0.9.2: 1
                  hubble-ui          rancher/mirrored-cilium-hubble-ui-backend:v0.9.2: 1
                  hubble-relay       rancher/mirrored-cilium-hubble-relay:v1.12.4: 1
                  cilium-operator    rancher/mirrored-cilium-operator-generic:v1.12.4: 2

real    0m34.818s
user    0m0.778s
sys     0m0.131s
```

RKE2 config

```yaml
---
tls-san: ['k8s-node001-master001.example.com']
etcd-snapshot-schedule-cron: 0 */12 * * *
etcd-snapshot-retention: 5
disable: ['rke2-ingress-nginx']
node-name: k8s-node001-master001.example.com
cni: cilium
disable-kube-proxy: true
protect-kernel-defaults: True
selinux: True
resolv-conf: /etc/resolv.conf
etcd-expose-metrics: true
kube-controller-manager-arg:
  - "bind-address=0.0.0.0"
  - "allocate-node-cidrs=true"
kube-scheduler-arg:
  - "bind-address=0.0.0.0"
```

Cilium config

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: strict
    tunnel: disabled
    autoDirectNodeRoutes: true
    ipv4NativeRoutingCIDR: 10.42.0.0/16
    installNoConntrackIptablesRules: true
    k8sServiceHost: localhost
    k8sServicePort: 6443
    cni:
      chainingMode: none
    bpf:
      masquerade: true
      mapDynamicSizeRatio: 0.02
    hostFirewall:
      enabled: true
    policyEnforcementMode: default
    policyAuditMode: false
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    prometheus:
      enabled: true
      port: 9962
      metrics:
        - +cilium_bpf_map_pressure
```

CiliumClusterwideNetworkPolicy

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: ingress-k8s-masters
spec:
  nodeSelector:
    matchLabels: 
      # only apply on master nodes
      node-role.kubernetes.io/control-plane: 'true'

  ingress:
      # Allow ICMPv4
    - icmps:
      - fields:
        - type: 8
          family: IPv4

    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "6443" # kube-apiserver
              protocol: TCP

    - fromEntities:
        - cluster
        - health
      toPorts:
        - ports:
            - port: "4240" # cilium health checks
              protocol: TCP

    - fromEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "2380" # etcd server to server
              protocol: TCP

    - fromEntities:
        - remote-node
      toPorts:
        - ports:
            - port: "9345" # rke2 agent node registration
              protocol: TCP
            - port: "7946" # metallb speaker
            
    - fromCIDR:
      # Allow access from all nodes in the cluster before the node has joined the cilium cluster
      - 10.83.11.135/32
      - 10.83.11.136/32
      - 10.83.11.137/32
      toPorts:
        - ports:
            - port: "2380" # etcd server to server
              protocol: TCP
            - port: "9345" # rke2 agent node registration
              protocol: TCP
            - port: "6443" # kube-apiserver
              protocol: TCP
            - port: "10250" # kubelet
              protocol: TCP

    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "2381" # etcd metrics
              protocol: TCP
            - port: "10259" # kube-scheduler metrics
              protocol: TCP
            - port: "10257" # kube-controller-manager metrics
              protocol: TCP
            - port: "7472" # metallb speaker metrics
              protocol: TCP
            - port: "9962" # cilium agent metrics
              protocol: TCP
            - port: "9963" # cilium operator metrics
              protocol: TCP
            - port: "10250" # kubelet
              protocol: TCP
            - port: "4244" # hubble server (cilium-agent)
              protocol: TCP
```

I tried adding `remote-node` to the `etcd` firewall ruleset but it did not seem to help:

```yaml
    - fromEntities:
        - kube-apiserver
        - remote-node
      toPorts:
        - ports:
            - port: "2380" # etcd server to server
              protocol: TCP
```

### Cilium Version

1.12.4 (v1.12.4-6eaecaf)

### Kernel Version

5.14.0-162.12.1.el9_1.0.2.x86_64 (Rocky9)

### Kubernetes Version

v1.25.5+rke2r2

### Relevant log output

```shell
Feb 23 15:00:29.213: 10.83.11.137:25550 (remote-node) <> 10.83.11.135:2380 (host) policy-verdict:none INGRESS DENIED (TCP Flags: SYN)
Feb 23 15:00:29.213: 10.83.11.137:25550 (world) <> 10.83.11.135:2380 (host) Policy denied DROPPED (TCP Flags: SYN)
Feb 23 15:00:29.214: 10.83.11.137:38886 (remote-node) <> 10.83.11.136:2380 (host) policy-verdict:none INGRESS DENIED (TCP Flags: SYN)
Feb 23 15:00:29.214: 10.83.11.137:38886 (world) <> 10.83.11.136:2380 (host) Policy denied DROPPED (TCP Flags: SYN)
Feb 23 15:00:29.214: 10.83.11.137:38894 (remote-node) <> 10.83.11.136:2380 (host) policy-verdict:none INGRESS DENIED (TCP Flags: SYN)
Feb 23 15:00:29.214: 10.83.11.137:38894 (world) <> 10.83.11.136:2380 (host) Policy denied DROPPED (TCP Flags: SYN)
Feb 23 15:00:29.275: 10.83.11.137:29458 (remote-node) <> 10.83.11.135:2380 (host) policy-verdict:none INGRESS DENIED (TCP Flags: ACK)
Feb 23 15:00:29.275: 10.83.11.137:29458 (world) <> 10.83.11.135:2380 (host) Policy denied DROPPED (TCP Flags: ACK)
Feb 23 15:00:30.238: 10.83.11.137:25552 (remote-node) <> 10.83.11.135:2380 (host) policy-verdict:none INGRESS DENIED (TCP Flags: SYN)
Feb 23 15:00:30.238: 10.83.11.137:25552 (world) <> 10.83.11.135:2380 (host) Policy denied DROPPED (TCP Flags: SYN)

Feb 23 15:21:07.846: 10.83.11.137:9345 (kube-apiserver) <> 10.83.11.136:20372 (host) policy-verdict:none INGRESS DENIED (TCP Flags: ACK, PSH)
Feb 23 15:21:07.846: 10.83.11.137:9345 (world) <> 10.83.11.136:20372 (host) Policy denied DROPPED (TCP Flags: ACK, PSH)
Feb 23 15:21:08.006: 10.83.11.137:2380 (kube-apiserver) <> 10.83.11.136:29350 (host) policy-verdict:none INGRESS DENIED (TCP Flags: ACK, PSH)
Feb 23 15:21:08.006: 10.83.11.137:2380 (world) <> 10.83.11.136:29350 (host) Policy denied DROPPED (TCP Flags: ACK, PSH)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
