### ISSUE TITLE
Kubelet `FailedKillPod`: Terminating backend of UDP service receives packets until pod delete event received

### ISSUE THREAD

**Issue by ysksuzuki** [cilium/cilium#24128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There's a brief outage during the graceful termination for the UDP service 

1. Set metadata.deletionTimestamp to the pod(now + terminationGracePeriodSeconds)
2. kubelet runs PreStop hooks If one of the Pod's containers has defined them. The terminating backend starts draining traffic.
3. Cilium sets the terminating backend as inactive, but still sends traffic to the inactive backend for UDP service if the client hits a stale tuple. The terminating backend can't drain traffic
4. kubelet(containerd) sends SIGTERM to the container process. If it doesn't finish within the terminationGracePeriodSeconds, then it sends SIGKILL. **There's a brief outage from here until cilium removes the pod(6).**
5. kubelet(containerd) tears down the pod network by executing CNI DEL, and the pod disappears
6. Cilium starts selecting a new backend for the UDP service even if the client hits the stale tuple

#20407 handled the tuple collisions for the TCP service, but the issue still occurs with the UDP service

We observed this brief outage with this UDP service. (with per packet load-balancing)

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: egress
    app.kubernetes.io/instance: nat
    app.kubernetes.io/name: coil
  name: nat
  namespace: domestic-egress
spec:
  ports:
  - port: 5555
    protocol: UDP
    targetPort: 5555
  selector:
    app.kubernetes.io/component: egress
    app.kubernetes.io/instance: nat
    app.kubernetes.io/name: coil
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 43200
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: egress
    app.kubernetes.io/instance: nat
    app.kubernetes.io/name: coil
  name: nat
  namespace: domestic-egress
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: egress
      app.kubernetes.io/instance: nat
      app.kubernetes.io/name: coil
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: egress
        app.kubernetes.io/instance: nat
        app.kubernetes.io/name: coil
    spec:
      containers:
      - args:
        - --zap-stacktrace-level=panic
        command:
        - coil-egress
        env:
        - name: COIL_POD_NAMESPACE
          value: domestic-egress
        - name: COIL_EGRESS_NAME
          value: nat
        - name: COIL_POD_ADDRESSES
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIPs
        image: ghcr.io/cybozu-go/coil:2.3.0
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "5"]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: health
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: egress
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: health
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /run
          name: run
        - mountPath: /lib/modules
          name: modules
          readOnly: true
      serviceAccount: coil-egress
      serviceAccountName: coil-egress
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: run
      - hostPath:
          path: /lib/modules
          type: ""
        name: modules
```

### Cilium Version

v1.12.4

### Kernel Version

5.15.89-flatcar

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9", GitCommit:"9710807c82740b9799453677c977758becf0acbb", GitTreeState:"clean", BuildDate:"2022-12-08T10:15:09Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9", GitCommit:"9710807c82740b9799453677c977758becf0acbb", GitTreeState:"archive", BuildDate:"2023-01-20T04:20:04Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
