### ISSUE TITLE
Cilium pods can't run, when Local Redirect Policy is activated in v1.13.0

### ISSUE THREAD

**Issue by eminaktas** [cilium/cilium#24201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I deployed the 1.13.0 Cilium with the following `values.yaml`. When I activated the LRP (Local Redirect Policy), the pods cannot work.

However, it is working with the older versions for example 1.12.7.

```yaml
USER-SUPPLIED VALUES:
bpf:
  hostLegacyRouting: false
  masquerade: true
cluster:
  id: 0
  name: cluster-1
debug:
  enabled: true
encryption:
  enabled: false
  nodeEncryption: false
hubble:
  enableOpenMetrics: true
  enabled: true
  metrics:
    enabled:
    - dns:query
    - drop:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity
    - tcp
    - icmp
    - port-distribution
    - flow:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity
    - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity
    port: 9965
    serviceMonitor:
      enabled: true
      metricRelabelings:
      - action: drop
        regex: grpc_server_.*
        sourceLabels:
        - __name__
  peerService:
    clusterDomain: cluster-1
  relay:
    enabled: true
    prometheus:
      enabled: false
      port: 9966
      serviceMonitor:
        enabled: false
    tolerations:
    - operator: Exists
  ui:
    enabled: true
    service:
      nodePort: 31235
      type: NodePort
    tolerations:
    - operator: Exists
ingressController:
  enabled: false
ipam:
  mode: kubernetes
k8sServiceHost: 127.0.0.1
k8sServicePort: "6443"
kubeProxyReplacement: strict
localRedirectPolicy: true
operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
proxy:
  prometheus:
    enabled: false
securityContext:
  privileged: false
socketLB:
  enabled: true
  hostNamespaceOnly: true
tunnel: vxlan
```

### Cilium Version

cilium-cli: 0.12.13 compiled with go1.19.6 on darwin/arm64
cilium image (default): v1.12.6
cilium image (stable): v1.13.0
cilium image (running): v1.13.0

### Kernel Version

Linux k8s-s-container-p1-3mars-master-1 5.15.0-57-generic #63~20.04.1-Ubuntu SMP Wed Nov 30 13:40:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.23.7

### Sysdump

[cilium-sysdump-20230307-000657.zip](https://github.com/cilium/cilium/files/10902780/cilium-sysdump-20230307-000657.zip)

### Relevant log output

```shell
level=debug msg="cache synced" kubernetesResource="crd:ciliumnetworkpolicies.cilium.io" subsys=k8s
level=debug msg="cache synced" kubernetesResource="crd:ciliumloadbalancerippools.cilium.io" subsys=k8s
level=debug msg="cache synced" kubernetesResource="crd:ciliumclusterwidenetworkpolicies.cilium.io" subsys=k8s
level=debug msg="Controller func execution time: 117.225µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 125.206µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 122.728µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 123.915µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 123.743µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 1.31µs" name=k8s-heartbeat subsys=controller uuid=87e056a2-aa7d-4b48-8460-5a409c1efef7
level=debug msg="Controller func execution time: 118.62µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 120.509µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 138.774µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 131.026µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 119.903µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 134.269µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 2.200512ms" name=k8s-heartbeat subsys=controller uuid=87e056a2-aa7d-4b48-8460-5a409c1efef7
level=debug msg="Performing regular background work" subsys=nodemanager syncInterval=1m0s
level=debug msg="Controller func execution time: 115.09µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 3.656µs" name=dns-garbage-collector-job subsys=controller uuid=a56e8f79-ec12-4559-a32c-a5196979a766
level=debug msg="Controller func execution time: 124.725µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 113.841µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 123.032µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 137.852µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 126.444µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 2.063798ms" name=k8s-heartbeat subsys=controller uuid=87e056a2-aa7d-4b48-8460-5a409c1efef7
level=debug msg="Controller func execution time: 119.536µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 149.206µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 117.864µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 124.495µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 134.718µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 117.97µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 2.185977ms" name=k8s-heartbeat subsys=controller uuid=87e056a2-aa7d-4b48-8460-5a409c1efef7
level=debug msg="Performing regular background work" subsys=nodemanager syncInterval=1m0s
level=debug msg="Controller func execution time: 3.228µs" name=dns-garbage-collector-job subsys=controller uuid=a56e8f79-ec12-4559-a32c-a5196979a766
level=debug msg="Controller func execution time: 114.432µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 121.435µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 132.598µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 112.615µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 139.319µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 111.123µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 2.41586ms" name=k8s-heartbeat subsys=controller uuid=87e056a2-aa7d-4b48-8460-5a409c1efef7
level=debug msg="Controller func execution time: 116.454µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 116.69µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 110.437µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 139.91µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 126.882µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 121.148µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 2.228517ms" name=k8s-heartbeat subsys=controller uuid=87e056a2-aa7d-4b48-8460-5a409c1efef7
level=debug msg="Performing regular background work" subsys=nodemanager syncInterval=1m0s
level=debug msg="Controller func execution time: 4.067µs" name=dns-garbage-collector-job subsys=controller uuid=a56e8f79-ec12-4559-a32c-a5196979a766
level=debug msg="Controller func execution time: 113.608µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 118.645µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 118.587µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 111.989µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 124.301µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
level=debug msg="Controller func execution time: 117.643µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=15352895-5362-484f-889b-b21e6c4cff8a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
