### ISSUE TITLE
Configuring io.cilium.proxy-visibility annotation in Helm Charts prevents pod from starting correctly. 

### ISSUE THREAD

**Issue by tricky42** [cilium/cilium#24242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi, I want to annotate pods with the `io.cilium.proxy-visibility` annotations. When I use `kubectl` to add the annotations to the pods directly, all works as expected.

```
kubectl annotate pod hostedui-54bbd5858d-f8cff io.cilium.proxy-visibility="<Ingress/3000/TCP/HTTP>"
```
But when I configure the annotations for the pods via `values.yaml` of the used Helm Charts, the pods are not starting correctly and end up in `CrashLoopBackOff`.

In the logs of the `cilium-agent` I see the following warnings:
```
cilium-agent level=warning msg="[[C1053] cilium.network: Policy NOT FOUND for id: 1 port: 3000" subsys=envoy-filter threadID=420
cilium-agent level=warning msg="[[C1054] cilium.network: Policy NOT FOUND for id: 1 port: 4456" subsys=envoy-filter threadID=420
cilium-agent level=warning msg="[[C1055] cilium.network: Policy NOT FOUND for id: 1 port: 4434" subsys=envoy-filter threadID=420
cilium-agent level=warning msg="[[C1056] cilium.network: Policy NOT FOUND for id: 1 port: 4410" subsys=envoy-filter threadID=420
cilium-agent level=warning msg="[[C1057] cilium.network: Policy NOT FOUND for id: 1 port: 4445" subsys=envoy-filter threadID=427
cilium-agent level=warning msg="[[C1058] cilium.network: Policy NOT FOUND for id: 1 port: 3000" subsys=envoy-filter threadID=427
cilium-agent level=warning msg="[[C1059] cilium.network: Policy NOT FOUND for id: 1 port: 3000" subsys=envoy-filter threadID=427
cilium-agent level=warning msg="[[C1060] cilium.network: Policy NOT FOUND for id: 1 port: 4456" subsys=envoy-filter threadID=427
cilium-agent level=warning msg="[[C1061] cilium.network: Policy NOT FOUND for id: 1 port: 4434" subsys=envoy-filter threadID=422
```

When I set the annotation value in the `values.yaml` to e.g. `aaaa` instead of `<Ingress/3000/TCP/HTTP>` the pods start without problem….

### Cilium Version

```
> cilium version
Client: 1.13.0 c9723a8d 2023-02-15T14:18:31+01:00 go version go1.19.6 linux/arm64
Daemon: 1.13.0 c9723a8d 2023-02-15T14:18:31+01:00 go version go1.19.6 linux/arm64
```

Also tested version `1.11.7`.

### Kernel Version

```
uname -a
Linux k3d-ory-cloud-server-0 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

### Kubernetes Version

```
> kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.2
Kustomize Version: v4.5.7
Server Version: v1.25.6+k3s1
```

### Sysdump

[cilium-sysdump-20230308-132103.zip](https://github.com/cilium/cilium/files/10920638/cilium-sysdump-20230308-132103.zip)

### Relevant log output

```shell
cilium-agent
level=warning msg="[[C1053] cilium.network: Policy NOT FOUND for id: 1 port: 3000" subsys=envoy-filter threadID=420
cilium-agent
level=warning msg="[[C1054] cilium.network: Policy NOT FOUND for id: 1 port: 4456" subsys=envoy-filter threadID=420
cilium-agent
level=warning msg="[[C1055] cilium.network: Policy NOT FOUND for id: 1 port: 4434" subsys=envoy-filter threadID=420
cilium-agent
level=warning msg="[[C1056] cilium.network: Policy NOT FOUND for id: 1 port: 4410" subsys=envoy-filter threadID=420
cilium-agent
level=warning msg="[[C1057] cilium.network: Policy NOT FOUND for id: 1 port: 4445" subsys=envoy-filter threadID=427
cilium-agent
level=warning msg="[[C1058] cilium.network: Policy NOT FOUND for id: 1 port: 3000" subsys=envoy-filter threadID=427
cilium-agent
level=warning msg="[[C1059] cilium.network: Policy NOT FOUND for id: 1 port: 3000" subsys=envoy-filter threadID=427
cilium-agent
level=warning msg="[[C1060] cilium.network: Policy NOT FOUND for id: 1 port: 4456" subsys=envoy-filter threadID=427
cilium-agent
level=warning msg="[[C1061] cilium.network: Policy NOT FOUND for id: 1 port: 4434" subsys=envoy-filter threadID=422
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mhofstetter** [comment]
Hi @tricky42 

It looks like the Pods don't become ready because their readiness probes don't succeed due to the health requests being blocked by Cilium.

All affected Pods have a visibility annotation applied, which matches the port that serves the health endpoint which is used by the readiness probe. The same time, the affected Pods have Kubernetes Network Policies applied, which don't include this health (& visibility) port.

In this case, HTTP requests (including health probe) on that port are redirected to the L7 proxy (Envoy) due to the visilibity annotation - but the actual L7 policy enforcement doesn't find a matching rule for the port in the Network Policy (Agents log output `Policy NOT FOUND`). This results in a block of the request.

L7 Visibility policy annotation shouldn't be used in combination with Network Policy rules selecting the same Pod. This is mentioned as limitation within the [documentation](https://docs.cilium.io/en/stable/observability/visibility/#limitations).

It's recommended to get rid of the visibility annotation and replace it with a corresponding Cilium Network Policy - which matches and allows all HTTP traffic on the given port.

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: visilibity
spec:
  endpointSelector:
    matchLabels:
      <labels matching the pod>
  ingress:
    - toPorts:
        - ports:
            - port: <visibility port>
              protocol: TCP
	  rules:
	    http:
	    - {}
```

This way all HTTP traffic on the configured port gets redirected to Envoy without being blocked by it. Only visibility information gets extracted.

Could you try whether this helps in your case?

Note: The same issue should also occur if the visibility annotation gets added to a running Pod with the same preconditions. In this case the readiness probe should also start to fail and degrade the Pod readiness state after some time - depending on the configuration of the probe (period, failureThreshold, ...)

**Comment by hoozgomk** [comment]
Hi @mhofstetter,

Thank you for your feedback. I'm also interested in this case. 
As explained, L7 visibility annotations and Kubernetes Network Policies cannot be applied together. 
Will applying Cilium Network Policy instead of Kubernetes Network Policy enable the L7 visibility (without the separate L7 annotation)? I'm interested in collecting Hubble metrics to measure HTTP traffic between the services and still having some sort of Network Policy in place.

Regards,

**Comment by mhofstetter** [comment]
@hoozgomk

You might face this issues when combining network policies with the l7 visibility annotation - regardless whether the policies are provided via Kubernetes or Cilium Network Policies.

But with the `CIliumNetworkPolicy` you have the possibility to express the L7 protocol visibility as mentioned in my above example.

The "empty" HTTP rule at the end is kind of the 1:1 replacement for the L7 visibility annotation and should enable the L7 visibility without having the need for the annotation itself.

**Comment by hoozgomk** [comment]
Hello,

@mhofstetter I made a test with Cilium network policy as proposed by you and the result was correct - I could see L7 flows with `hubble observe` or `cilium hubble ui` for the scoped service without the manual annotation.

On the other hand, I tried to reproduce the issue with manual annotation and Kubernetes network policy. 
In my test setup, I have two simple services (client and server) where each has one endpoint for which I defined the liveness and readiness probes, like in the example:

```
          readinessProbe:
            httpGet:
              path: "/go/cars"
              port: 8080
          livenessProbe:
            httpGet:
              path: "/go/cars"
              port: 8080
```
Port 8080 is the only port on which service serves requests.
I have also defined the following annotation:

`io.cilium.proxy-visibility: <Egress/8080/TCP/HTTP>,<Ingress/8080/TCP/HTTP>"`

The Kubernetes network policy I applied is also simple, but it contains an additional rule allowing ingress traffic to port 8080 from the whole cluster (to make readiness and liveness probe succeed):

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: goclient
  namespace: default
spec:
  podSelector:
    matchLabels:
      name: go-client
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              name: go-server
    - from:
        - namespaceSelector: {}
      ports:
        - port: 8080
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    - to:
        - podSelector:
            matchLabels:
              name: go-server
```


As a result, I got the same warning in cilium-agent logs:

`│ cilium-agent level=warning msg="[[C720] cilium.network: Policy NOT FOUND for id: 1 port: 8080" subsys=envoy-filter threadID=567    `

The difference is that my services are starting up just fine and serving requests. Also, L7 visibility remains in place.
If you have any ideas why this is working on my setup, please let me know.

Regards,

**Comment by mhofstetter** [comment]
hi @hoozgomk 

in your case the application startup (and therefore the readiness probe) works because the same ports used in the ingress visibility annotation `8080` is also present as ingress rule within the `NetworkPolicy`. try changing the port from `8080` to `8081` in the `ingress` section of your `NetworkPolicy` and i assume you will face the same error after redeploying the application.

i guess you face the warning `Policy NOT FOUND` only at the beginning of the deployment (until everything is reconciled) - and not periodically? Otherwise, it might be the case that this is from the egress visibility rule whose port isn't present in the egress section of the NetworkPolicy.

In @tricky42 's case , the networkpolicy DOESN'T include the port that its used in the visibility annotation & health endpoint.

**Comment by hoozgomk** [comment]
Hello @mhofstetter,

I appreciate your support.
Indeed, the ingress rule:
```
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - port: 8080
```
solves the problem - readiness and liveness probes pass.

I started to wonder if there is a possibility to make this ingress rule more strict. Currently, it allows incoming traffic to port 8080 from anything in the cluster. As readiness/liveness checks are executed by kubelet which runs on each node in the k8s cluster, I currently don't know how to define the source for this ingress rule. Any suggestions are appreciated.

Regards,

**Comment by mhofstetter** [comment]
hey @hoozgomk - happy to help!

the entity based approach with `host` might be what your looking for.

```
  ingress:
    - fromEntities:
        - host
      toPorts:
        - ports:
            - port: "8080"
```

please contact the docs (https://docs.cilium.io/en/v1.13/security/policy/language/#entities-based) or slack for further questions not specifically related to this issue.
