### ISSUE TITLE
Restart cilium-agent will make the pod connection lost  for a while

### ISSUE THREAD

**Issue by yanhongchang** [cilium/cilium#24323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1、k8s cluster, install cilium with --enable-bgp-control-plane=true
2、label node cilium/bgp-policy=in
3、create CiliumBGPPeeringPolicy
```
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering-policy-default
spec:
  nodeSelector:
    matchLabels:
      cilium/bgp-policy: in
  virtualRouters:
  - exportPodCIDR: true
    localASN: 12345
    neighbors:
    - peerASN: 12346
      peerAddress: 10.19.x.x/32
    serviceSelector:
      matchExpressions:
      - key: somekeyThatDoesNotExist
        operator: DoesNotExist
```
and the podCIDR announce   normally.

4、delete one of cilium-agent in cluster and will found those pods on the node will ping down .

### Cilium Version

1.13.0

### Kernel Version

5.10

### Kubernetes Version

1.24

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
