### ISSUE TITLE
BGP Control Plane doesn't advertise IPv6 LB IPAM addresses

### ISSUE THREAD

**Issue by itz-Jana** [cilium/cilium#24362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am configuring Cilium to assign IP addresses to LoadBalancer services with LB IPAM and I want it to advertise those IPs to my VyOS Router using the BGP Control Plane.
Sadly I am unable to get it to advertise both the IPv4 and IPv6 address to VyOS and I only ever receive the IPv4 address.

I installed Cilium with:
```
cilium install --helm-set bgpControlPlane.enabled=true,ipv6.enabled=true,ipam.operator.clusterPoolIPv4PodCIDRList={10.42.0.0/16},ipam.operator.clusterPoolIPv6PodCIDRList={2001:cafe:42:0::/112}
```

My BGPPolicy:
```
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: vyos
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  virtualRouters:
    - localASN: 65001
      neighbors:
        - peerASN: 65000
          peerAddress: 10.0.0.1/32
      serviceSelector:
        matchExpressions:
          - { key: somekey, operator: NotIn, values: ["never-used-value"] }
```

My IPPool:
```
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: home-pool
spec:
  cidrs:
    - cidr: "10.0.1.0/24"
    - cidr: "fd48:e380:751a:1::/64"
```

I manually assign the IPs using an annotation like in this example service:
```
---
apiVersion: v1
kind: Service
metadata:
  name: blocky-service
  namespace: blocky
  annotations:
    io.cilium/lb-ipam-ips: 10.0.1.11,fd48:e380:751a:1::11
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ipFamilyPolicy: RequireDualStack
  selector:
    app: blocky
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
```

It successfully assigns the IP addresses to the service, as I can see from `get svc`:
```
NAMESPACE          NAME                                 TYPE           CLUSTER-IP      EXTERNAL-IP                      PORT(S)                      AGE
blocky             blocky-service                       LoadBalancer   10.43.66.106    10.0.1.11,fd48:e380:751a:1::11   53:30204/UDP                 11d
```

But VyOS seems to only receive the IPv4 address:
```
jonatan@vyos:~$ show bgp ipv4
BGP table version is 119, local router ID is 10.0.0.1, vrf id 0
Default local pref 100, local AS 65000
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete

   Network          Next Hop            Metric LocPrf Weight Path
*= 10.0.1.10/32     10.0.0.14                              0 65001 i
*>                  10.0.0.13                              0 65001 i
*= 10.0.1.11/32     10.0.0.14                              0 65001 i
*>                  10.0.0.13                              0 65001 i

Displayed  2 routes and 4 total paths

jonatan@vyos:~$ show bgp ipv6
No BGP prefixes displayed, 0 exist
```

At this point I am at a loss at what else to try or configure, can anyone help me?

### Cilium Version

v1.13.0

### Kernel Version

Linux ananke 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

### Kubernetes Version

v1.25.7+k3s1

### Sysdump

[cilium-sysdump-20230314-140855.zip](https://github.com/cilium/cilium/files/10968864/cilium-sysdump-20230314-140855.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
