### ISSUE TITLE
Egress HTTP Policy is not blocking ICMP protocol

### ISSUE THREAD

**Issue by eloycoto** [cilium/cilium#2450]
When a new Egress HTTP rule is defined, source pod can ping to other pod when it shoudln't

Pod manifest:
```
apiVersion: v1
kind: Pod
metadata:
  name: 700e0976-6cb50b02
  labels:
    id: 700e0976-6cb50b02
    zgroup: 700e0976
spec:
  containers:
  - name: app-frontend
    image: byrnedo/alpine-curl
    command: [ "sleep" ]
    args:
      - "1000h"
---
apiVersion: v1
kind: Pod
metadata:
  name: 700e0976-afd3a30c
  labels:
    id: 700e0976-afd3a30c
    zgroup: 700e0976
spec:
  containers:
  - name: web
    image: cilium/demo-httpd
    ports:
      - containerPort: 80
```

Cilium Network Policy Manifest:

```
{
  "apiVersion": "cilium.io/v2",
  "kind": "CiliumNetworkPolicy",
  "metadata": {
    "name": "700e0976",
    "test": "L3:No Policy L4:No Policy L7:Egress policy to /private/ Destination:Direct"
  },
  "specs": [
    {
      "EndpointSelector": {
        "matchlabels": {
          "id": "700e0976-afd3a30c"
        }
      },
      "Ingress": [
        {
          "FromEndpoints": [
            {}
          ]
        }
      ],
      "Egress": null
    },
    {
      "EndpointSelector": {
        "matchlabels": {
          "id": "700e0976-6cb50b02"
        }
      },
      "Ingress": null,
      "Egress": [
        {
          "ToPorts": [
            {
              "Ports": [
                {
                  "port": "80",
                  "protocol": "TCP"
                }
              ],
              "Rules": {
                "http": [
                  {
                    "method": "GET",
                    "path": "/private"
                  }
                ]
              }
            }
          ]
        }
      ]
    }
  ]
}
```

Endpoints
```
root@k8s1:/home/vagrant# kubectl -n kube-system exec -ti cilium-v69tp cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                   IPv6                   IPv4         STATUS
           ENFORCEMENT        ENFORCEMENT
173        Disabled           Disabled          256        k8s:io.kubernetes.pod.namespace=kube-system   f00d::a0a:100:0:ad     10.10.1.66   ready
                                                           k8s:k8s-app=kube-dns
13949      Disabled           Enabled           258        k8s:id=700e0976-6cb50b02                      f00d::a0a:100:0:367d   10.10.1.32   ready
                                                           k8s:io.kubernetes.pod.namespace=default
                                                           k8s:zgroup=700e0976
29381      Enabled            Disabled          257        k8s:id=700e0976-afd3a30c                      f00d::a0a:100:0:72c5   10.10.1.59   ready
                                                           k8s:io.kubernetes.pod.namespace=default
                                                           k8s:zgroup=700e0976
```

Ping
```
root@k8s1:/home/vagrant# kubectl exec 700e0976-6cb50b02 ping 10.10.1.59
PING 10.10.1.59 (10.10.1.59): 56 data bytes
64 bytes from 10.10.1.59: seq=0 ttl=63 time=0.503 ms
```

HTTP:
```
root@k8s1:/home/vagrant# kubectl exec 700e0976-6cb50b02 curl http://10.10.1.59/public
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Access denied
100    14  100    14    0     0     14      0  0:00:01 --:--:--  0:00:01  2800
root@k8s1:/home/vagrant# kubectl exec 700e0976-6cb50b02 curl http://10.10.1.59/private
{ 'val': 'this is private' }
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    29  100    29    0     0     29      0  0:00:01 --:--:--  0:00:01 14500
```
