### ISSUE TITLE
manifest schema v1 unsupported

### ISSUE THREAD

**Issue by weironz** [cilium/cilium#24501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

can this cilium-etcd-operator image update to schema v2?

[sealos issue releated!](https://github.com/labring/sealos/issues/2802)

when i run sealos build command , i get this error 
```
Error: failed to save images: save domain quay.io image quay.io/cilium/cilium-etcd-operator:v2.0.7: get digest error: get image manifest error: manifest schema v1 unsupported
```

### Cilium Version

1.13.1

### Kernel Version

# uname -sr
Linux 5.15.0-67-generic

### Kubernetes Version

v1.25.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
The `cilium-etcd-operator` image hasn't been updated in four years, and its manifest is out of date. It seems like a pull and then push with Docker should have Docker update the manifest format.

**Comment by willzhang** [comment]
> The `cilium-etcd-operator` image hasn't been updated in four years, and its manifest is out of date. It seems like a pull and then push with Docker should have Docker update the manifest format.

but cilium still use the old one by default, not dockerhub image, so maybe should update quay.io image from dockerhub.

**Comment by youngnick** [comment]
I meant that using the `docker` tool to pull from `quay.io`, and then push back to `quay.io` by someone with access should fix this problem, because `docker` has automatically upgraded the manifest format for a couple of years now.

**Comment by youngnick** [comment]
Update: I've made a mistake here. `cilium-etcd-operator` is deprecated and no longer maintained, which is why it hasn't been updated in four years. It shouldn't be being used anyway, so I'd suggest updating sealos to exclude that image instead.

Because the image is deprecated, we won't be able to update it, sorry.

You can see that https://github.com/cilium/cilium-etcd-operator is archived.

**Comment by willzhang** [comment]
so can you help update values.yaml for cilium at next version, maybe this block should delete.

because we usually auto generate image list use helm charts.

```
etcd:
  # -- Enable etcd mode for the agent.
  enabled: false

  # -- cilium-etcd-operator image.
  image:
    override: ~
    repository: "quay.io/cilium/cilium-etcd-operator"
    tag: "v2.0.7@sha256:04b8327f7f992693c2cb483b999041ed8f92efc8e14f2a5f3ab95574a65ea2dc"
    pullPolicy: "IfNotPresent"
```
