### ISSUE TITLE
Cilium-envoy autodiscovery founds only one port on the pod with multiple ports

### ISSUE THREAD

**Issue by igort77** [cilium/cilium#24572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we run cilium envoy for L7 load balancing it discovers only one port on the pod that contains multiple ports. After updating the envoy config, the port may change to a different port, but still uses only one port.

If we leave only one available port on the pod, it works as expected.

The envoy clusters config with only one available port:
> dev/app1::observability_name::dev/app1
> dev/app1::outlier::success_rate_average::-1
> dev/app1::outlier::success_rate_ejection_threshold::-1
> dev/app1::outlier::local_origin_success_rate_average::-1
> dev/app1::outlier::local_origin_success_rate_ejection_threshold::-1
> dev/app1::default_priority::max_connections::1024
> dev/app1::default_priority::max_pending_requests::1024
> dev/app1::default_priority::max_requests::1024
> dev/app1::default_priority::max_retries::3
> dev/app1::high_priority::max_connections::1024
> dev/app1::high_priority::max_pending_requests::1024
> dev/app1::high_priority::max_requests::1024
> dev/app1::high_priority::max_retries::3
> dev/app1::added_via_api::true
> dev/app1::10.201.90.246:8085::cx_active::4
> dev/app1::10.201.90.246:8085::cx_connect_fail::0
> dev/app1::10.201.90.246:8085::cx_total::6
> dev/app1::10.201.90.246:8085::rq_active::0
> dev/app1::10.201.90.246:8085::rq_error::0
> dev/app1::10.201.90.246:8085::rq_success::87
> dev/app1::10.201.90.246:8085::rq_timeout::0
> dev/app1::10.201.90.246:8085::rq_total::87
> dev/app1::10.201.90.246:8085::hostname::
> dev/app1::10.201.90.246:8085::health_flags::healthy
> dev/app1::10.201.90.246:8085::weight::1
> dev/app1::10.201.90.246:8085::region::
> dev/app1::10.201.90.246:8085::zone::
> dev/app1::10.201.90.246:8085::sub_zone::
> dev/app1::10.201.90.246:8085::canary::false
> dev/app1::10.201.90.246:8085::priority::0
> dev/app1::10.201.90.246:8085::success_rate::-1
> dev/app1::10.201.90.246:8085::local_origin_success_rate::-1 

The pod ports config:
>    ports:
>     - containerPort: 8085
>       name: http-app
>       protocol: TCP
>     - containerPort: 8091
>       name: http-prometheus
>       protocol: TCP
> 

### Cilium Version

1.13.1

### Kernel Version

5.10.167-147.601.amzn2.x86_64

### Kubernetes Version

AWS EKS 1.25

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
Hi! In order to investigate the relevant logs, can you please share a sysdump for such a config?

**Comment by igort77** [comment]
Sorry I can't share logs due to privacy policy. Maybe someone can reproduce the issue by running pod with multiple ports?

**Comment by dbazhal** [comment]
I can't say that I'm having exactly the same issue. I just realised that I don't know how to work with multiple ports in cilium-envoy.
(please tell me if I should create the separate issue for my question).
I have service with multiple ports, like this
```
kind: Service
apiVersion: v1
metadata:
  name: grpc-server-helloworld
  namespace: etalon-grpc
  labels:
    app: grpc-server-helloworld
spec:
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: "50051"
    - name: http
      potocol: TCP
      port: 8080
      targetPort: "80"
  type: ClusterIP
  selector:
    name: grpc-server-helloworld
```

And I make CEC like this:
```
apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:
  name: l7-router-etalon-grpc-grpc-server-helloworld
  namespace: etalon-grpc
spec:
  backendServices:
  - name: grpc-server-helloworld
    namespace: etalon-grpc
    number:
    - "50051"
  - name: grpc-server-helloworld-next
    namespace: etalon-grpc
    number:
    - "50051"
  resources:
  - '@type': type.googleapis.com/envoy.config.listener.v3.Listener
    filterChains:
    - filterChainMatch:
        transportProtocol: raw_buffer
      filters:
      - name: envoy.filters.network.http_connection_manager
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          httpFilters:
          - name: envoy.filters.http.router
          rds:
            routeConfigName: l7-router-etalon-grpc-grpc-server-helloworld_route
          statPrefix: l7-router-etalon-grpc-grpc-server-helloworld
    name: l7-router-etalon-grpc-grpc-server-helloworld
    socketOptions:
    - description: Enable TCP keep-alive, annotation io.cilium/tcp-keep-alive. (default
        to enabled)
      intValue: "1"
      level: "1"
      name: "9"
      state: STATE_LISTENING
    - description: TCP keep-alive idle time (in seconds). Annotation io.cilium/tcp-keep-alive-idle
        (defaults to 10s)
      intValue: "10"
      level: "6"
      name: "4"
      state: STATE_LISTENING
    - description: TCP keep-alive probe intervals (in seconds). Annotation io.cilium/tcp-keep-alive-probe-interval
        (defaults to 5s)
      intValue: "5"
      level: "6"
      name: "5"
      state: STATE_LISTENING
    - description: TCP keep-alive probe max failures. Annotation io.cilium/tcp-keep-alive-probe-max-failures
        (defaults to 10)
      intValue: "10"
      level: "6"
      name: "6"
      state: STATE_LISTENING
  - '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
    name: l7-router-etalon-grpc-grpc-server-helloworld_route
    virtualHosts:
    - domains:
      - '*'
      name: '*'
      routes:
      - match:
          prefix: "/"
          headers:
            - name: "xxx"
              present_match: true
        route:
          cluster: etalon-grpc/grpc-server-helloworld-next:50051
          maxStreamDuration:
            maxStreamDuration: 0s
      - match:
          prefix: "/"
        route:
          cluster: etalon-grpc/grpc-server-helloworld:50051
          maxStreamDuration:
            maxStreamDuration: 0s
  - '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
    connectTimeout: 5s
    name: etalon-grpc/grpc-server-helloworld:50051
    outlierDetection:
      consecutiveLocalOriginFailure: 2
      splitExternalLocalOriginErrors: true
    type: EDS
    typedExtensionProtocolOptions:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        useDownstreamProtocolConfig:
          http2ProtocolOptions: {}
  - '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
    connectTimeout: 5s
    name: etalon-grpc/grpc-server-helloworld-next:50051
    outlierDetection:
      consecutiveLocalOriginFailure: 2
      splitExternalLocalOriginErrors: true
    type: EDS
    typedExtensionProtocolOptions:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        useDownstreamProtocolConfig:
          http2ProtocolOptions: {}
  services:
  - listener: l7-router-etalon-grpc-grpc-server-helloworld
    name: grpc-server-helloworld
    namespace: etalon-grpc
```

So my working service is now served by envoy. But. The port that isn't described in CEC(http one), isn't working(obviously, as I am now thinking about it).
I know that the first issue with that is that I'm rewriting working service. But for me that is the point - I want to take existing service, create CEC for serving it, and process only traffic for some specific port, leaving other ports unprocessed.
Everything worked for me while there was single port. And now I'm wondering, **how do I do multiple ports?**
In CEC I should somehow figure out what target port is. Traffic to specific port I should process with http manager. And all other traffic I should somehow route to it's original destination without processing it.
While writing it I realise that this would be done easily if cilium itself would route to CEC only single specified port.
Like, CEC `services` attribute should look something like this
```
  services:
  - listener: l7-router-etalon-grpc-grpc-server-helloworld
    name: grpc-server-helloworld
    namespace: etalon-grpc
    port: 50051
```
so all other ports probably shouldn't even hit envoy.
So one again, _the question is_: How do I process multiple ports with cilium service mesh without creating separate services for each port separately?
Any help would be appreciated :)
