### ISSUE TITLE
CiliumClusterwideNetworkPolicy does not allow us to define policy to lockdown traffic within each of the namespaces

### ISSUE THREAD

**Issue by vethastanley** [cilium/cilium#24731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As of now, if we need to lock down both ingress and egress within a particular namespace, it is achievable only by defining a network policy like the one below. It has to be created for each namespace in the cluster.

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ns-traffic
  namespace: default
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - {}
  egress:
    - toEndpoints:
        - {}
```
There is no facility to define one cluster-wide policy which automatically enforces this policy for all the namespaces in the cluster including any new namespaces that will be created in the cluster. This is because of the fact there is no possibility to mention the namespace as self.

### Cilium Version

1.30.0

### Kernel Version

5.15.0-1022-azure

### Kubernetes Version

1.25.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
