### ISSUE TITLE
local-port annotation not respected by Cilium BGP

### ISSUE THREAD

**Issue by CorneJB** [cilium/cilium#24737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using node annotations to set the local-port, these values do not seem to be respected by Cilium. Looks similar to https://github.com/cilium/cilium/issues/23155. 

Given these annotations:

```
apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      cilium.io/bgp-virtual-router.65341: local-port=42424,router-id=192.168.178.201
```

In the Cilium logs a different port is selected by the VirtualRouter:

```
kind: CiliumBGPPeeringPolicy
metadata:
  name: mikro
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: X
  virtualRouters:
    - localASN: 65341
      neighbors:
        - peerASN: 65340
          peerAddress: 192.168.178.1/32
      serviceSelector:
        matchLabels:
          io.cilium.gateway/owning-gateway: tls-gateway
```

The router gives the following error when connecting on the port annotated on the node:
![image](https://user-images.githubusercontent.com/49902683/229842136-6a1d0f82-834c-467a-ac17-8e7950787446.png)

### Cilium Version

cilium-cli: v0.13.2 compiled with go1.20.2 on linux/amd64
cilium image (default): v1.13.1
cilium image (stable): v1.13.1
cilium image (running): v1.13.1

### Kernel Version

Linux steamroller2 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.7+k3s1", GitCommit:"f7c20e237d0ad0eae83c1ce60d490da70dbddc0e", GitTreeState:"clean", BuildDate:"2023-03-10T22:16:07Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.7+k3s1", GitCommit:"f7c20e237d0ad0eae83c1ce60d490da70dbddc0e", GitTreeState:"clean", BuildDate:"2023-03-10T22:16:07Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

### Relevant log output

```shell
level=info msg="type:STATE peer:{conf:{local_asn:65341 neighbor_address:\"192.168.178.1\" peer_asn:65340} state:{local_asn:65341 neighbor_address:\"192.168.178.1\" peer_asn:65340 session_state:IDLE router_id:\"192.168.178.1\"} transport:{local_address:\"192.168.178.201\" local_port:53903 remote_port:179}}"
level=info msg="type:STATE peer:{conf:{local_asn:65341 neighbor_address:\"192.168.178.1\" peer_asn:65340} state:{local_asn:65341 neighbor_address:\"192.168.178.1\" peer_asn:65340 session_state:ACTIVE router_id:\"192.168.178.1\"} transport:{local_address:\"192.168.178.201\" local_port:53903 remote_port:179}}"
level=info msg="type:STATE peer:{conf:{local_asn:65341 neighbor_address:\"192.168.178.1\" peer_asn:65340} state:{local_asn:65341 neighbor_address:\"192.168.178.1\" peer_asn:65340 session_state:OPENSENT router_id:\"192.168.178.1\"} transport:{local_address:\"192.168.178.201\" local_port:53405 remote_port:179}}"
level=info msg="type:STATE peer:{conf:{local_asn:65341 neighbor_address:\"192.168.178.1\" peer_asn:65340} state:{local_asn:65341 neighbor_address:\"192.168.178.1\" peer_asn:65340 session_state:OPENCONFIRM router_id:\"192.168.178.1\"} transport:{local_address:\"192.168.178.201\" local_port:53405 remote_port:179}}"
level=info msg="Peer Up" Key=192.168.178.1 State=BGP_FSM_OPENCONFIRM Topic=Peer asn=65341 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=info msg="type:STATE peer:{conf:{local_asn:65341 neighbor_address:\"192.168.178.1\" peer_asn:65340} state:{local_asn:65341 neighbor_address:\"192.168.178.1\" peer_asn:65340 session_state:ESTABLISHED router_id:\"192.168.178.1\"} transport:{local_address:\"192.168.178.201\" local_port:53405 remote_port:179}}"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
