### ISSUE TITLE
NetworkPolicy with named port is not working, when there are more than one port with the same name.

### ISSUE THREAD

**Issue by axel7born** [cilium/cilium#24779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We use named port in several pods as `containerPort`. 
Some pods use the same name for a port but with different values. 

This repro case works with two pods and one networkpolicy:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: simple-server-1
  namespace: default
spec:
  containers:
  - env:
    ports:
    - containerPort: 8000
      name: http-test
      protocol: TCP
```

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: simple-server-2
    role: logging
  namespace: test
spec:
  containers:
  - env:
    ports:
    - containerPort: 8080
      name: http-test
      protocol: TCP
```

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
  name: allow-egress
  namespace: default
spec:
  egress:
  - ports:
    - port: http-test
      protocol: TCP
  podSelector:
    matchLabels:
      role: logging
  policyTypes:
  - Egress
```

Pod `simple-server-2` can't reach `simple-server-1` in that case. If I replace the port name `http-test` in the network policy, it works. If I remove the named port from the second pod it will work too.

### Cilium Version

```
cilium version
Client: 1.13.1 a6be57eb 2023-03-15T19:39:01+01:00 go version go1.19.6 linux/amd64
Daemon: 1.13.1 a6be57eb 2023-03-15T19:39:01+01:00 go version go1.19.6 linux/amd64
```

### Kernel Version

```
uname -a
Linux ip-10-180-15-212.eu-west-1.compute.internal 5.15.101-gardenlinux-cloud-amd64 #1 SMP Debian 5.15.101-0gardenlinux1 (2023-03-12) x86_64 GNU/Linux
```

### Kubernetes Version

```
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-18T19:15:26Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

[cilium-sysdump-20230406-105447.zip](https://github.com/cilium/cilium/files/11168315/cilium-sysdump-20230406-105447.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
