### ISSUE TITLE
when i use cilium network policy, pods of a service on different nodes can't reach.

### ISSUE THREAD

**Issue by Shuxu001** [cilium/cilium#24927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I thought this is not a BUG，but I didn't find an example. So I need help actually _(:з」∠)_ 
I just use this yaml:
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: test
  namespace: default
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
  - fromEndpoints:
    - matchLabels: {}
```
I think it means that in default namespace, all pods can be telnet each other, this is true.
But when I curl service's cluster ip, only pods on the same node can be reach. 
The packets is dropped when it comes back, and is from interface cilium_vxlan to interface lxcdf235337145c.

### Cilium Version

1.10.4 c10b1c5611 2022-10-14T19:17:34+08:00 go version go1.16.7 linux/amd64

### Kernel Version

Linux 10-0-3-49 5.4.119-19-0009.11 #1 SMP Wed Oct 5 18:41:07 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.22.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
