### ISSUE TITLE
Host ingress traffic is annotated as "world" for pods with AWS security groups when cilium is deployed in CNI chaining mode.

### ISSUE THREAD

**Issue by vgrigoruk** [cilium/cilium#24946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. Create a new EKS cluster (1.25) and install recommended versions of EKS addons (AWS VPC CNI, CoreDNS, kubeproxy).
2. Install cilium in CNI chaining mode (please note `--set endpointRoutes.enabled=false` is used because of https://github.com/cilium/cilium/issues/24943) with hubble enabled as described in [cilium docs](https://docs.cilium.io/en/v1.13/installation/cni-chaining-aws-cni/) (including EKS changes related to enabling Security Groups for pods):
    ```
    helm upgrade --install cilium cilium/cilium --version 1.13.1 \
      --namespace kube-system \
      --set cni.chainingMode=aws-cni \
      --set cni.exclusive=false \
      --set enableIPv4Masquerade=false \
      --set tunnel=disabled \
      --set hubble.relay.enabled=true \
      --set hubble.ui.enabled=true \
      --set endpointRoutes.enabled=false
    ```
3. Run `cilium connectivity test`
4. Run `cilium hubble ui` and navigate to http://localhost:12000/?namespace=cilium-test and see that ingress traffic from kubelet is correctly annotated as `reserved:host`
![Screenshot 2023-04-18 at 09 57 15](https://user-images.githubusercontent.com/487261/232743510-f3d16142-bf19-439e-b70d-88981a77fc2a.png)
5. Create pod security group policy (so pods matching a selector get their own branch ENI) 
    ```
    kubectl apply -f - <<EOF
    apiVersion: vpcresources.k8s.aws/v1beta1
    kind: SecurityGroupPolicy
    metadata:
      name: test-app-psgp
      namespace: cilium-test
    spec:
      podSelector:
        matchLabels:
          kind: echo
      securityGroups:
        groupIds:
          - sg-XXXXXX # a test SG that allows all ingress/egress traffic 
    EOF
    ```
6. Delete a `echo-other-node-*` pod, so it is re-created with pod security group policy applied.
7. Navigate to Hubble UI: http://localhost:12000/?namespace=cilium-test. Kubelet traffic to `echo-other-node-*` pod is annotated as `reserved:world` instead of `reserved:host` (see screenshot)
![Screenshot 2023-04-18 at 09 54 51](https://user-images.githubusercontent.com/487261/232744800-cff76f60-c6fe-411f-8be9-334595ee6383.png)

### Cilium Version

- v1.13.1
- v1.14.0-snapshot.0

### Kernel Version

Linux ip-XXX-XXX-XXX-XXX.eu-west-1.compute.internal 5.10.173-154.642.amzn2.x86_64 #1 SMP Wed Mar 15 00:26:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.25.8-eks-ec5523e

### Sysdump

[cilium-sysdump-20230418-120818.zip](https://github.com/cilium/cilium/files/11263287/cilium-sysdump-20230418-120818.zip)

### Anything else?

- Traffic is annotated correctly after removing pod security group policy from the cluster and re-creating affected pods. 

- As host traffic is not recognised properly, we can not create a properly-restrict ingress network policy for application pods, as this issue forces us to allow ingress traffic from `world`, which defeats the value of running cilium in CNI Chaining mode with AWS VPC CNI and Security Groups for Pods.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
