### ISSUE TITLE
L7 HTTPS egress visibility breaks pod external connectivity - except the subject of inspection

### ISSUE THREAD

**Issue by vladimirkus** [cilium/cilium#25083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

According to this [DOC](https://docs.cilium.io/en/v1.13/security/tls-visibility/#gs-tls-inspection) I tested L7 visibility.
I've created a policy that should have captured traffic to `https://google.com`, the required secrets and a test pod.
After getting to the pod I've noticed the next behavior: all egress requests to something different than `https://google.com`, even plain http requests were unsuccessful. However, all requests to `https://google.com` has passed as expected with swapped by the proxy certificate. 
I expected policy with explicit
```
- toFQDNs:
    - matchName: "google.com"
```
to affect not all HTTPS requests.
If there is a possibility to avoid such behavior?

### Cilium Version

Daemon: 1.13.0 c9723a8d 2023-02-15T14:18:31+01:00 go version go1.19.6 linux/amd64

### Kernel Version

5.4.228-132.418.amzn2.x86_64

### Kubernetes Version

v1.22.17-eks-48e63af

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ti-mo** [comment]
Hi @vladimirkus, do you still have the full policy available you used in your test? If you're using this one (https://docs.cilium.io/en/v1.13/security/tls-visibility/#apply-dns-and-tls-aware-egress-policy), what you're seeing is expected and a normal mode of operation of network policies.

The section I linked above states:

> Note that with this policy the mediabot doesn’t have access to any internal cluster service other than kube-dns and will have no access to any other external destinations either. Refer to [Network Policy](https://docs.cilium.io/en/v1.13/security/policy/#id1) to learn more about policies for controlling access to internal cluster services.

See https://docs.cilium.io/en/v1.13/security/policy/language/#ingress-egress-default-deny for more info.

**Comment by vladimirkus** [comment]
Hi @ti-mo , thank you for the clarifications.
This is the policy I tested:
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l7-visibility-tls"
spec:
  description: L7 policy with TLS
  endpointSelector:
    matchLabels:
      org: foo
      class: test
  egress:
  - toFQDNs:
    - matchName: "google.com"
    toPorts:
    - ports:
      - port: "443"
        protocol: "TCP"
      terminatingTLS:
        secret:
          namespace: "kube-system"
          name: "google-tls-data"
      originatingTLS:
        secret:
          namespace: "kube-system"
          name: "tls-orig-data"
      rules:
        http:
          - {}
  - toFQDNs:
    - matchPattern: "*"
    toPorts:
    - ports:
      - port: "443"
        protocol: "TCP"
      rules:
        http:
          - {}
  - toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        http:
        - {}
  - toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
          - matchPattern: "*"
```

So, egress-default-deny policy in my example should deny any egress except tcp(80), any(53) and tcp(443).
I've read the docs but still have a few question regarding this setup
- egress rule is created explicitly for google.com, when I do egress calls from the pod to another HTTPS resources I have an error. The error happens because all other egress calls are falling on default-deny policy or because all HTTPS traffic is being redirected to the proxy, that has no relevant certificates?
- assuming it may be a deny, I tried to add sections like 
``` 
  - toPorts:
    - ports:
      - port: "443"
        protocol: ANY
      rules:
        http:
        - {} 
```
or 
```
- toFQDNs:
    - matchHost: "hostname.com"
    toPorts:
    - ports:
      - port: "443"
        protocol: "TCP"
      rules:
        http:
          - {}
```
in order to allow egress, but the error haven't change:
```
curl https://hostname.com
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```
so it seems like the issue is not default-deny rule, but the proxy itself.

The desired state:
I'd like to configure cilium to do Egress HTTPS Inspection on https://google.com and not to impact another egress destinations. Is it possible?

**Comment by joestringer** [comment]
Hmm, I suspect that this part is correct:

> or because all HTTPS traffic is being redirected to the proxy, that has no relevant certificates?

Do you need L7 visibility for traffic destined to destinations other than `google.com`? If no, you might be able to try the following in addition to the first rule you have for port443/toFQDNs google.com:

```
  - toPorts:
    - ports:
      - port: "443"
        protocol: ANY
```

**Comment by vladimirkus** [comment]
No, I don't need L7 visibility for traffic destined to destinations other than `google.com`. This is exactly what I'm trying to reach - visibility on one particular destination domain. However I was not able to configure the policy to work as desired, and I'm wondering if it's possible to do it?
I've tried to add additional rule like you suggest to the very base policy that adds L7 visibility to `google.com`
```
spec:
  description: L7 policy with TLS
  egress:
  - toFQDNs:
    - matchName: google.com
    toPorts:
    - originatingTLS:
        secret:
          name: tls-orig-data
          namespace: kube-system
      ports:
      - port: "443"
        protocol: TCP
      rules:
        http:
        - {}
      terminatingTLS:
        secret:
          name: google-tls-data
          namespace: kube-system
  - toPorts:
    - ports:
      - port: "443"
        protocol: ANY
  - toPorts:
    - ports:
      - port: "80"
        protocol: ANY
  - toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: '*'
  endpointSelector:
    matchLabels:
      class: test
      org: foo
```
This policy indeed allows access access to any destinations other than `google.com`, but breaks access to `google.com` with the next error (looks like it overrides the certificates config for `google.com`):
```
*   Trying 172.253.122.113...
* TCP_NODELAY set
* Expire in 149991 ms for 3 (transfer 0x5573e500c110)
* Expire in 200 ms for 4 (transfer 0x5573e500c110)
* Connected to google.com (172.253.122.113) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

**Comment by LarsBingBong** [comment]
@vladimirkus what was the fix that made you set this issue as completed? Thanks

**Comment by cezarsa** [comment]
For anyone coming late to this issue, this fixes it:
```
spec:
  description: L7 policy with TLS
  egress:
  - toFQDNs:
    - matchName: artii.herokuapp.com
    toPorts:
    - serverNames:
      - artii.herokuapp.com
      originatingTLS:
        secret:
          name: tls-orig-data
          namespace: cilium-test
      ports:
      - port: "443"
        protocol: TCP
      rules:
        http:
        - {}
      terminatingTLS:
        secret:
          name: artii-tls-data
          namespace: cilium-test
  - toFQDNs:
    - matchPattern: '*'
    toPorts:
    - ports:
      - port: "443"
        protocol: ANY
  - toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: '*'
  endpointSelector:
    matchLabels:
      class: mediabot
      org: empire
```

This config allows inspecting traffic to `artii.herokuapp.com` while forwarding traffic without inspection to anything else:
```
$ kubectl exec -it mediabot -- curl -v -m2 -sS 'https://google.com' | grep 'issuer:'
*  issuer: C=US; O=Google Trust Services; CN=WR2

$ kubectl exec -it mediabot -- curl -v -sSL 'https://artii.herokuapp.com/make' | grep 'issuer:'
*  issuer: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd
```

 The `toFQDNs` matcher with a wildcard pattern is important in the catch-all rule for port 443, otherwise this doesn't work.
