### ISSUE TITLE
CFP: ToFQDNs Support at host

### ISSUE THREAD

**Issue by PriyaSharma9** [cilium/cilium#25166]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature request for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your feature request related to a problem?**
> Yes

If so, please describe the problem
> CiliumClusterwideNetworkPolicy with Nodeselector supports restricting egress toPorts, toCIDR but not ToFQDNs. 

**Describe the feature you'd like**
- ToFQDNs support for CiliumClusterwideNetworkPolicy with Nodeselector.
- The below policy should allow egress only to www.google.com

    ```
    apiVersion: "cilium.io/v2"
    kind: CiliumClusterwideNetworkPolicy
    metadata:
      name: "to-fqdn"
    spec:
      nodeSelector:
        matchLabels:
          node-role.kubernetes.io/master: "true"
      egress:
        - toEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": kube-system
              "k8s:k8s-app": kube-dns
          toPorts:
            - ports:
               - port: "53"
                 protocol: ANY
              rules:
                dns:
                  - matchName: "*"
        - toFQDNs:
            - matchName: www.google.com
          toPorts:
            - ports:
                - port: "443"
     ```
