### ISSUE TITLE
Egress Gateway is not SNAT'ing the correct IP

### ISSUE THREAD

**Issue by mattmalec** [cilium/cilium#25239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When routing a pod through the egress gateway, it doesn't seem to be using the correct IP address. On each of my nodes, it shares the same L2 network and has access to a full /24 block across all of the nodes. Each of the nodes has a single /32 from the /24. Ideally, I'd like to use another IP that isn't currently used from that same /24 block.

For example: if I have `33.44.55.1` as the main IP address, and `33.44.55.25` as an additional IP on the same interface, and I set up my policy like so:
```yaml
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: example-policy
spec:
  selectors:
  - podSelector:
      matchLabels:
        k8s.my-pod-label.com/id: abc123
        io.kubernetes.pod.namespace: the-namespace

  destinationCIDRs:
  - "0.0.0.0/0"

  egressGateway:
    nodeSelector:
      matchLabels:
        k8s.my-node-label.com/id: abc123

    egressIP: 33.44.55.25
```
It actually ends up making the egress IP `33.44.55.1`, even though it's actually defined as `33.44.55.25` in the above config. Additionally, when I run `cilium bpf egress list` on the Cilium pod that matches the egress gateway node, it shows the correct `33.44.55.25` egress IP, even though that's incorrect.

I add the secondary IP using the following command:
`ip addr add 33.44.55.25/32 br 33.44.55.25 dev bond0`
But it also seemed to perform the same when permanently attaching the IP to the NIC with nmcli.

### Cilium Version

1.14.0-snapshot.2 (but also experienced this in 1.13.2)

### Kernel Version

Linux rn6-k8s.va.internal.rocketnode.net 5.14.15-1.el8.elrepo.x86_64 #1 SMP Tue Oct 26 11:45:20 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-18T19:08:10Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
