### ISSUE TITLE
Support Use of Annotations on Cilium Gateway API Load Balancer Services

### ISSUE THREAD

**Issue by cmcgalliard** [cilium/cilium#25357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. using Linode's infrastrucuture
2. create a Kubernetes cluster with cilium as CNI & Gateway Class
3. Create HTTP Routes & add Cert Manager
4. Traffic needed to validate the HTTP Cert Request fail / timeout
```Failed to connect to hostname.example.com port 80 after 4 ms: Couldn't connect to server```
5. this is happening because the load-balencer service needs the following annotation for linode LB / pod routing
```service.beta.kubernetes.io/linode-loadbalancer-hostname-only-ingress: "true"```
6. If I manually edit the `cilium-gateway-service` which generates the LB - the request will work for a moment and then fail as the gateway controller removes the annotations.

is it possible to have the controller to not remove the annotations

- and/or -

the ability to supply the needed service annotations :)

### Cilium Version

v1.13.0

### Kernel Version

UBUNTU 22.04
Linux dev-master-0 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.26.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cmcga1125** [comment]
For a bit more details, here's the slack conversation:

https://cilium.slack.com/archives/C53TG4J4R/p1683666665428989

Also, you mentioned upstream being aware, I'd there an issue or creator request I can follow?

**Comment by youngnick** [comment]
We have an open issue on using paramsRef in GatewayClass, #21923. We absolutely could use that to do this sort of customisation of the generated Service object.

However, also relevant is https://github.com/kubernetes-sigs/gateway-api/pull/1868, which is adding a new infrastructure stanza to Gateways which we can also support, and will allow us to do the same thing.

Practically, depending on the timelines for Gateway API releases and Cilium releases, we may shuffle which one comes first though.

**Comment by youngnick** [comment]
We don't have an implementation issue yet for the `infrastructure` stanza, I'll link it in here once I have better info about timings and open one.

**Comment by sergeyshevch** [comment]
@cmcga1125 If you are looking for a workaround. We mitigated such an issue with MutationWebhook by Kyverno. You can use other policy engines as well

**Comment by wwentland** [comment]
Thanks! A MutationWebhook does indeed work well. It would still be nice for Cilium to support this directly though.

**Comment by rauanmayemir** [comment]
@sergeyshevch Do you mind sharing an example of such policy?

**Comment by youngnick** [comment]
I should be clear that we are going to build support for this into Cilium, we just have to finish designing it in Gateway API first.

**Comment by sergeyshevch** [comment]
@rauanmayemir Sure. There is our example

<details><summary>Details</summary>
<p>

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-rest-gateway-svc
  annotations:
    policies.kyverno.io/title: Mutate Rest Gateway Service
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      We need to mutate the rest gateway service for adjusting some annotations.
spec:
  rules:
    - name: mutate-svc-annotations
      match:
        any:
          - resources:
              kinds:
                - Service
              namespaces:
                - gateway-api
              name: cilium-gateway-rest-gateway
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
              service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
```

</p>
</details>

**Comment by rauanmayemir** [comment]
@sergeyshevch thanks a lot, this is great.

**Comment by Cajga** [comment]
@youngnick would the support of infrastructure in cilium also support NodePorts as gateway service?
Our use case in short: We are on Bare Metal (EKS Anywhere). We got an external and an internal HW load balancer cluster. We would like to have two gateways defined in Cilium (one internal and one external facing) using nodeports and forward the traffic from the LBs to these.

**Comment by youngnick** [comment]
Ah, that's the use case covered in your CFP (#27273 )? Yes, `infrastructure` should help with that as well, although we don't have an upstream GEP to define that yet. We may look at setting that globally at a Cilium level instead for now, but I'll put something on #27273 when we have more.

**Comment by Cajga** [comment]
Yes, #27273 is about this use case. Sorry for opening that CFP, as well as writing here but I was not sure it this covers our use case so, I thought to describe it with the Istio implementation in a separate CFP just to make sure it is captured.

**Comment by sergeyshevch** [comment]
@rauanmayemir Please note that my workaround policy will also cause #27493 to appear in your cluster. I attached updated workaround mutation policy in #27493 issue

**Comment by zs-ko** [comment]
@youngnick do cilium support GatewayInfrastructure in the Gateway API or is this something that is going to be added in the future?

**Comment by sergeyshevch** [comment]
@zs-ko We discussed it with @youngnick in the Closed PR below. AFAIK it will be added in the future (After it will be included in the GW API release)

**Comment by snovak7** [comment]
Well it was added 4days ago, now just to make it official in next iteration, I already see it present in website docs, but no implementation supports that.
https://github.com/kubernetes-sigs/gateway-api/blob/main/apis/v1beta1/gateway_types.go#L188

**Comment by rauanmayemir** [comment]
'Infrastructure' helps setting LB IP, but there is still no way to set LB service labels and annotations.

**Comment by youngnick** [comment]
With the merge of kubernetes-sigs/gateway-api#2440, the `infrastructure` field in Gateway will grow the required fields in the 1.0 release, due out in the next month or so. Once that is out and we have upgraded Cilium to use that version, we'll be able to use those fields to do this.

I'm sorry this has taken a long time, but we are making progress! As to what version of Cilium this will be included in, I'm not sure - I don't think it likely we will get this in for 1.15.0, but depending on how big the rest of the committers think this feature is, I will _try_ to make the argument that this should be backported to 1.15.x once we get it merged into `main` after the release is cut. But I can't make any promises there, sorry.

**Comment by cmcga1125** [comment]
Thanks for the update!

**Comment by youngnick** [comment]
@cmcga1125, I think that should solve the initial issue as well?

**Comment by sergeyshevch** [comment]
@youngnick Looks like it will cover our case with AWS NLB. Will this merge be included in the next 1.15 release?

**Comment by cmcga1125** [comment]
thanks everyone! this will work for the original issues!

**Comment by youngnick** [comment]
Feature freeze is this week, and it's merged already, so yes, it will be included in 1.15.

**Comment by a114383** [comment]
I'm sorry to be late to this, but i've tried to follow the issues linked, and specifically this one: https://github.com/cilium/cilium/pull/29122

Would lead me to believe I should be able to do something like this with `gateway.spec.infrastructure` to set the service annotations:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: my-gateway
  namespace: cilium
spec:
  infrastructure:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
...
````

but I don't see this in gateway or cilium?

**Comment by rouke-broersma** [comment]
@a114383 I'm not sure but I think the field is still experimental so you will need to use crd v1beta1

**Comment by rauanmayemir** [comment]
@a114383 You'll have to apply `experimental` gateway CRD, not `standard`.

**Comment by a114383** [comment]
That did it thank you very much!!

**Comment by xaviergrandmougin** [comment]
Confirmed, it worked with the `1.0.0` experimental `gateway.networking.k8s.io/v1`. Thank you!

**Comment by hongbo-miao** [comment]
Thanks @rauanmayemir ! 😃

After updating from
https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml
to
https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/experimental/gateway.networking.k8s.io_gateways.yaml

Below code works:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: my-gateway
  namespace: my-cilium
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
```

However, I would expect it would be better a newer version such as v1.2.0 experimental instead of using existing v1.1.0 as it is a new feature.
