### ISSUE TITLE
CFP: dynamic endpoint label selectors

### ISSUE THREAD

**Issue by DekusDenial** [cilium/cilium#25366]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

The Endpoint Selector is currently based on K8s' LabelSelector, which means the labels would likely need to be explicit.
That also means that network policy creators would need to know the set of labels (mostly along with their values) ahead of time so that the policies can be applied to the desired targets.
It is not yet possible to have network policy that can "dynamically" applied to endpoints that allows traffic to/from pods with the same set of labels without knowing the actual labels and their values. So it’s kinda like the pods are part of the same k8s deployment in a sense.

**Describe the feature you'd like**

I would like to have a different endpoint selector logic where I can specify endpoints based on:

1. labels that are common to both the source and target endpoints, e.g. allow traffic between pods with labels (role=backend,env=prod,k8s-app=api) in the same namespace but NOT to/from pods with labels (role=database,env=prod,k8s-app=database) because the label values are different. However, pods with labels (role=database,env=prod,k8s-app=database) themselves can allow traffic between each other.
```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l3-selective-equal-labels-rule"
spec:
  endpointSelector:
    matchLabelsOfEqualValue:
      - role
      - env
      - k8s-app
  ingress:
  - fromEndpoints:
    - matchLabelsOfEqualValue:
        - role
        - env
        - k8s-app
```

2. all labels that both the source and target endpoints possess. e.g. as long as pods that have all the equal label pairs, so pods with labels (role=backend,env=prod) can allow traffic between each other, but not to/from pods with labels (role=backend,env=prod,k8s-app=api) because they have an extra label pair (k8s-app=api) that the former do not have
```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l3-all-equal-labels-rule"
spec:
  endpointSelector:
    matchAllLabelsOfEqualValue: true
  ingress:
  - fromEndpoints:
    - matchAllLabelsOfEqualValue: true
```

I feel like 2) maybe too much of a stretch but that use case is plausible because sometimes cluster admins may not have all the exact details about the workloads from the tenants in the cluster.

**Comment by odinuge** [comment]
Thanks for bringing this up @DekusDenial! We have also been thinking about something similar, as that would significantly reduce the number of policies we would have to have.

I'm really want to join in here and help working on the proposal to push it trough!

I think possibly something like this, more close to your number `1)` could make the required API change even simpler;

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: untitled-policy
spec:
  endpointSelector:
    matchExpressions:
      - key: app-id
        operator: Exists
  ingress:
    - fromEndpoints:
        - matchExpressions:
            - key: app-id
              operator: MatchesEndpointSelector # or something similar
  egress:
    - toEndpoints:
        - matchExpressions:
            - key: app-id
              operator: MatchesEndpointSelector # or something similar
```

In the above case I would imaging that the policy applies to all endpoints with a label with the key `app-id`, and all endpoints with the same value of the `app-id` label would be able to egress and ingress to each other.
