### ISSUE TITLE
FILTEROP_ERROR When Applying Kafka L7 Policy

### ISSUE THREAD

**Issue by daviddyball** [cilium/cilium#25489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Attempting to apply a Kafka-aware L7 policy drops all traffic to Kafka:
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: my-topic-policy
  namespace: kafka
spec:
  endpointSelector:
    matchLabels:
      strimzi.io/cluster: my-cluster
  ingress:
  - fromEndpoints:
    - matchLabels:
        app: my-app
    toPorts:
    - ports:
      - port: 9092
        protocol: TCP
      rules:
        kafka:
        - role: "consume"
          topic: my-topic
```

### Cilium Version

1.12.7

### Kernel Version

5.15.92

### Kubernetes Version

1.25.8

### Relevant log output

Thousands of these logs

```shell
{"level":"warning","msg":"[[C135995] Cilium Network::OnIO: FILTEROP_ERROR: 2 bytes","subsys":"envoy-filter","threadID":"966815"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
