### ISSUE TITLE
CFP-2023-05-17: Hubble Flow Logs

### ISSUE THREAD

**Issue by AwesomePatrol** [cilium/cilium#25508]
## Cilium Feature Proposal
        
**Is your feature request related to a problem?**

Without Hubble Timescape it is impossible to get information about the past Hubble Flows (outside the history stored in the ring buffer).

**Describe the feature you'd like**

I want to have an option to output information on Flows for a period of time (maybe indefinite).

**(Optional) Describe your proposed solution**

I can't link to the doc, so I will copy the content in the first comment.

**Comment by AwesomePatrol** [comment]
### Proposal

Add a new CRD that will be watched by `cilium-agent`. When `end` is in the future it will process Hubble flows, the ones that match the filter will be stripped from information outside the `field mask` and logged in a file. Most observability tools can be configured to ingest it.

#### Definition

```yaml
// Not a real CRD
kind: flowlogging.networking.gke.io
spec:
  properties:
    fieldmask:
      description: "List of field names that will be kept in the log output"
      type: array
      items:
        description: "Field name that will be kept in the output. Subfields are separated by dot"
        type: string
    filter:
      description: "Filter"
      type: object
      properties:
        allowlist:
          description: "Allowlist filter generated by CLI. Empty matches all. Flow passes the filter if any of the entries match. Only Flows matching Allowlist, but not matching Denylist will be logged"
          type: array
          items:
            description: "Allowlist entry"
            type: string
        denylist:
          description: "Denylist filter generated by CLI. Empty matches none. Flow passes the filter if none of the entries match. Only Flows matching Allowlist, but not matching Denylist will be logged"
          type: array
          items:
            description: "Denylist entry"
            type: string
    end:
      description: "End denotes the timestamp when logging will stop"
      type: string
```

#### Examples

Example of collecting Flow logs for a specific user-project.
* until `15:04:05` of `2023-05-10 PDT`
* from all pods in a `user-project` namespace
* but exclude `kube-dns` traffic in both directions
* keep only 4 fields: `time`, `src`, `dst`, `verdict` (forward/drop)

```yaml
spec:
  fieldmask:
    - "time"
    - "source.pod_name"
    - "destination.pod_name"
    - "verdict"
  filter:
    allowlist:
      - '{"source_pod":["user-project/"]}'
      - '{"destination_pod":["user-project/"]}'
    denylist:
      - '{"source_label":["k8s:k8s-app=kube-dns"]}'
      - '{"destination_label":["k8s:k8s-app=kube-dns"]}'
  end: "2023-05-10T15:04:05-07:00"
```

Example of collecting Flow logs for an entire organization.
* until `15:04:05` of `2023-05-10 PDT`
* from all pods in all organization clusters
* keep all information

```yaml
spec:
  fieldmask:
  filter:
  end: "2023-05-10T15:04:05-07:00"
```

Example of stopping Flow logs collection:
* end is set to a timestamp in a past

```yaml
spec:
  fieldmask:
  filter:
  end: "1970-01-01T00:00:00"
```

**Comment by EItanya** [comment]
Thinking out loud I wonder if this would already be possible with something like https://github.com/cilium/hubble-otel. You could send all of the flows through oTEL and do all filtering/storage that way.

**Comment by AwesomePatrol** [comment]
Thanks for pointing it out to me. This may indeed cover my use-case. However, as it is a separate component, I wonder if it doesn't waste too much resources by requiring every Flow to go through grpc. I need to investigate it further. I hope to have results next week

**Comment by AwesomePatrol** [comment]
Unfortunately there are too many issues with Otel approach:
1. Repository is not maintained: most instructions no longer work and code dependencies weren't updated in almost 2 years
2. Documentation is almost non-existent: I can read flags from the code, but I have no idea how to use them in the configuration (see https://github.com/cilium/hubble-otel/issues/94)
3. Resource consumption makes it impossible to use as DaemonSet. GRPC -> logs, with only 15 flows/s, consumed 27 CPU and 121 MB of memory (maybe with https://github.com/cilium/cilium/pull/25647 I could run it as a sidecar to Hubble-relay)
4. Traces in Jaeger are very hit or miss

**Comment by EItanya** [comment]
That's too bad.

Given that the CFP here would require engineering work either way, I think the engineering work would be better directed at fixing up the oTEL approach, rather than adding it directly into Hubble. That would immediately fix issues 1 + 2 outlined above.

As far as resource consumption. The logic to handle the flows needs to happen somewhere, whether it's in the oTEL pod or somewhere else, so I think optimizing it within the pipeline makes sense either way.

**Comment by AwesomePatrol** [comment]
> CFP here would require engineering work either way

We already have very similar functionality, so I would say that over 60% work for this is already done.

> The logic to handle the flows needs to happen somewhere, whether it's in the oTEL pod or somewhere else

It is still surprising to me as other components (Hubble CLI/Relay) use ~20 MB. It seems that it is mainly caused by oTEL boilerplate as I see a similar collector using 110 MB and doing pretty much nothing.

> I think optimizing it within the pipeline makes sense either way.

I see that it is possible to run `hubble-otel` in a standalone mode. It gives me hope that I can use it without introducing OpenTelemetry stack (just yet).

I started working on getting it working again. Let's see if I need to become a maintainer to change it quickly to suit my needs 😄

**Comment by AwesomePatrol** [comment]
As discussed on slack, https://github.com/cilium/hubble-otel is unfortunately abandoned and there is no willing maintainer to take care of it.

About the proposal, I think instead of having JSON embedded in YAML. It is better to just use flow.Filter directly.

Go struct will look like this:
```go
type FlowLogging struct {
  // List of field names that will be kept in the log output
  fieldmask []string
  // Flow passes the allowlist filter if any of the entries match. The check is disabled when empty. Only Flows matching Allowlist, but not matching Denylist will be logged. 
  allowlist []flow.Filter
  // Flow passes the denylist filter if none of the entries match. The check is disabled when empty. Only Flows matching Allowlist, but not matching Denylist will be logged. 
  denylist  []flow.Filter
  // End denotes the timestamp when logging will stop.
  end       string
}
```

And the first example:
```yaml
spec:
  fieldmask:
    - "time"
    - "source.pod_name"
    - "destination.pod_name"
    - "verdict"
  allowlist:
    - source_pod:
      - "user-project/"
    - destination_pod:
      - "user-project/"
  denylist:
    - source_label:
      - "k8s:k8s-app=kube-dns"
    - destination_label:
      - "k8s:k8s-app=kube-dns"
  end: "2023-05-10T15:04:05-07:00"
```
