### ISSUE TITLE
Dual Stack: ExternalIP allocation in infinite loop

### ISSUE THREAD

**Issue by Shashankft9** [cilium/cilium#25530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have a dual stack environment, where I have configured bgp-config that looks something like this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
    - peer-address: 10.8.30.25
      peer-asn: 64516
      my-asn: 64516
      peer-port: 179
      router-id: 127.0.0.1
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 92.0.2.0/24
      avoid-buggy-ips: true
      bgp-advertisements:
      - aggregation-length: 32
 ```
 
 next, I have created IPPool that looks like this:
 ```
apiVersion: "cilium.io/v2alpha1" 
kind: CiliumLoadBalancerIPPool 
metadata: 
  name: "pool-yellow" 
spec: 
  cidrs: 
  - cidr: "2341:3673:2902::09/120" 
  serviceSelector: 
    matchLabels: 
      "io.kubernetes.service.namespace": "tenant-c"
 ```
 
 After this, when i give the appropriate labels to my service, although it gets assigned an `externalIP` from the CIDR which is advertised as well, but this ip keeps getting deallocated and then reallocated in an infinite loop.
 The same setup works perfectly fine in a single stack environment. 

### Cilium Version

1.13.2

### Kernel Version

5.4.4

### Kubernetes Version

v1.20

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
