### ISSUE TITLE
CFP: Enable loadbalancerMode: dedicated for GatewayClass to enable more than one IP address

### ISSUE THREAD

**Issue by Jamison1** [cilium/cilium#25567]
Currently, when setting up a 2nd gatewayClass the cloud IPAM provider assigns the same IP address as the cilium gatewayClass.
This seems like `loadbalancerMode: shared` behavior.

2nd GatewayClass Example:
```
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: management
  namespace: longhorn-system
  labels:
    app.kubernetes.io/managed-by: "Ansible"
    app.kubernetes.io/name: "management"
spec:
  controllerName: "io.cilium/gateway-controller"
  description: "Management Gateway"
```

After installing the 2nd gateway class:
```
NAME         CONTROLLER                     ACCEPTED   AGE
cilium       io.cilium/gateway-controller   True       6h38m
management   io.cilium/gateway-controller   True       6m59s
```

Loadbalancer IPAM assignment (kube-vip-cloud-controller) with 2 gateway classes, each with their own gateway:
```
NAMESPACE         NAME                    CLASS        ADDRESS      PROGRAMMED   AGE
kube-system       dev-hubble-ui-gateway   cilium       10.0.0.132   Unknown      7h
longhorn-system   dev-longhorn-gateway    management   10.0.0.132   Unknown      47m
```
Proposed Solution:
Enable loadbalancer mode with dedicated or shared similar to ingress controller.

```
values:
  gatewayAPI:
    enabled: true
    loadbalancerMode: dedicated
```

This may also solve the issue #21926 with not being able to assign an gateway address to a specific gateway

Additionally, the ability to [spec the ip address in the GatewayClass](https://gateway-api.sigs.k8s.io/api-types/gatewayclass/#gatewayclass-parameters) may also fit here something like this:

```
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: management
  namespace: longhorn-system
  labels:
    app.kubernetes.io/managed-by: "Ansible"
    app.kubernetes.io/name: "management"
spec:
  controllerName: "io.cilium/gateway-controller"
  description: "Management Gateway"
  parametersRef:
    group: cilium.io/v1alpha1
    kind: Configmap
    name: management-gateway-config
---
apiVersion: cilium.io/v1alpha1
kind: Configmap
metadata:
  name: management-gateway-config
spec:
  ip-address-pool: 10.0.0.133
```

**Comment by Jamison1** [comment]
Currently testing with two gateways, one for https and the other for tls with kube-vip handling the loadbalancer IP assignment and the same IP gets assigned for each gateway which renders each useless.

Any update on enabling LoadbalancerMode: dedicated?

Or is there another way to use multiple gateways without using kube-vip for this but still retain kube-vip for control-plane VIP?

**Comment by youngnick** [comment]
Right now, we watch and update GatewayClasses that match the `controllerName` string, as you can see in your examples, but we don't do separate config for them. That will probably require something like #21923 (which would also allow us to do `loadBalancer: dedicated|shared` in config.

We _may_ also be able to change the contract a bit and say that each GatewayClass you create gets a _separate_ loadbalancer, and then all the Gateways in that GatewayClass are shared onto that. 

Either of those things fit into what's allowed upstream, but I think that the latter may be slightly less work to implement.

**Comment by youngnick** [comment]
I've been thinking about this some more, and come up with some ideas, @Jamison1, any thoughts you have here would be appreciated.

As I said above, right now we watch and update the status of multiple GatewayClasses, but those have no way to have separate config. I can see two options to resolve this:
- We could build out the support for using `parametersRef` in GatewayClass (that's #21923), and have the object that we reference have the same `loadBalancerMode: dedicated|shared` config. This would mean that each GatewayClass could have a different setting for if things are in Dedicated or Shared mode, and then each Gateway within that class would be treated the same as Ingresses in either Dedicated or Shared mode respectively (meaning that Gateways in a Dedicated GatewayClass would each get a separate IP address, and Gateways in a Shared GatewayClass would share one IP address).
- We could also just decide that each GatewayClass is distinct, but always Shared. This would mean that to get Dedicated-style behavior, users would need to create one GatewayClass for each loadBalancer created, and all Gateways within each GatewayClass would be Shared.

The first option is quite a bit more work (we need to create a new parameters CRD, or use a ConfigMap, watch that, and then change the behavior of the GatewayClass accordingly).

The second option could actually be a subset of the first - in order to build out the support for multiple Shared mode GatewayClasses, we'd need to do a lot of the same work that the first option would need, so we could always come back and add the `parametersRef` part on top later.

Because of all that, I'm inclined to do the second option for now, and look at the first option if people want a _lot_ of Dedicated Gateways.

@sayboras @meyskens @mhofstetter @jrajahalme, any thoughts?

**Comment by Jamison1** [comment]
@youngnick, the second option will likely work for my usage for now.  I need 4-5 dedicated gateways.

**Comment by rouke-broersma** [comment]
@youngnick I think option 2 would already fit most migration scenarios from ingress to gateway api so sounds like more than enough for a first implementation.

**Comment by youngnick** [comment]
With #37402 merging, we now have mechanisms in place to get this done.

**Comment by youngnick** [comment]
Currently, when using Cilium's built-in IPAM, each Gateway will try to provision a new Loadbalancer Service. There's no support for sharing an IP between Gateways because of this.

So, only giving one IP address means that the second Loadbalancer Service will fail to get an IP address, as you can see in the error message. Note that this is one place where using Cilium's built in IPAM and using Cloud IPAMs may be different.

**Comment by daleckystepan** [comment]
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: abc
  namespace: xyz
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      lbipam.cilium.io/sharing-key: '1234'
  listeners: [...]
```

Works but you need to have different ports per gateway. In case you have 443 everywhere then it does not work.
