### ISSUE TITLE
Cilium drops out of order IP Fragments

### ISSUE THREAD

**Issue by sebltm** [cilium/cilium#25709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We're running a cluster in AWS with Cilium in ENI mode (will share full config below). This cluster has nodes with multiple interfaces (eth0, eth1, eth2...) but only one of those is managed by Cilium (always eth0). However Cilium attaches the ``tc clsact`` to every interface.
We've found a bug where, when we're sending large UDP packets to this host such that the UDP packets are fragmented, most of the time the fragments get dropped by the ``from-netdev`` part of the BPF.

```yaml
  agent-not-ready-taint-key: node.cilium.io/agent-not-ready
  arping-refresh-period: 30s
  auto-create-cilium-node-resource: "true"
  auto-direct-node-routes: "false"
  aws-enable-prefix-delegation: "true"
  bpf-fragments-map-max: "65535"
  bpf-lb-external-clusterip: "false"
  bpf-lb-map-max: "131072"
  bpf-lb-sock: "false"
  bpf-lb-sock-hostns-only: "true"
  bpf-map-dynamic-size-ratio: "0.01"
  bpf-policy-map-max: "16384"
  bpf-root: /sys/fs/bpf
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: "0"
  cluster-name: default
  cni-uninstall: "true"
  custom-cni-conf: "true"
  debug: "false"
  debug-verbose: ""
  direct-routing-device: eth0
  disable-cnp-status-updates: "true"
  disable-endpoint-crd: "false"
  ec2-api-endpoint: ""
  enable-auto-protect-node-port-range: "true"
  enable-bgp-control-plane: "false"
  enable-bpf-clock-probe: "true"
  enable-endpoint-health-checking: "true"
  enable-endpoint-routes: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-host-firewall: "false"
  enable-host-legacy-routing: "true"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv4-fragment-tracking: "true"
  enable-ipv4-masquerade: "false"
  enable-ipv6: "false"
  enable-ipv6-big-tcp: "false"
  enable-ipv6-masquerade: "false"
  enable-k8s-terminating-endpoint: "true"
  enable-l2-neigh-discovery: "true"
  enable-l7-proxy: "false"
  enable-local-redirect-policy: "true"
  enable-metrics: "true"
  enable-node-port: "false"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-sctp: "true"
  enable-svc-source-range-check: "true"
  enable-vtep: "false"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  eni-tags: '{}'
  hubble-disable-tls: "false"
  hubble-listen-address: :4244
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  identity-gc-interval: 15m0s
  identity-heartbeat-timeout: 30m0s
  install-no-conntrack-iptables-rules: "false"
  ipam: eni
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: ""
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  node-port-range: 3000,5000
  nodes-gc-interval: 5m0s
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: :9963
  preallocate-bpf-maps: "false"
  procfs: /host/proc
  prometheus-serve-addr: :9962
  proxy-prometheus-port: "9964"
  read-cni-conf: /tmp/cni-configuration/cni-config
  remove-cilium-node-taints: "true"
  set-cilium-is-up-condition: "true"
  sidecar-istio-proxy-image: cilium/istio_proxy
  skip-cnp-status-startup-clean: "false"
  synchronize-k8s-nodes: "true"
  tofqdns-dns-reject-response-code: refused
  tofqdns-enable-dns-compression: "true"
  tofqdns-endpoint-max-ip-per-hostname: "50"
  tofqdns-idle-connection-grace-period: 0s
  tofqdns-max-deferred-connection-deletes: "10000"
  tofqdns-min-ttl: "3600"
  tofqdns-proxy-response-max-delay: 100ms
  tunnel: disabled
  unmanaged-pod-watcher-interval: "15"
  update-ec2-adapter-limit-via-api: "true"
  vtep-cidr: ""
  vtep-endpoint: ""
  vtep-mac: ""
  vtep-mask: ""
  write-cni-conf-when-ready: /host/etc/cni/net.d/05-cilium.conflist
  ```

### Cilium Version

v1.13.2

### Kernel Version

Linux <hostname> 5.4.0-1021-aws-fips #21+fips2-Ubuntu SMP Thu Dec 2 20:11:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.23.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Interesting! Have you considered setting the `devices` value in the ConfigMap / Helm values? I'm curious if that solves the issue.

**Comment by sebltm** [comment]
@squeed good point, didn't try setting ``devices``.  I guess we have the additional challenge that this is affecting all the interfaces on the host (including the Cilium-managed ones) so we instead went for a (perhaps naive) patch: https://github.com/cilium/cilium/compare/v1.13.2...sebltm:cilium:frag-workaround

**Comment by julianwiedmann** [comment]
> @squeed good point, didn't try setting `devices`. I guess we have the additional challenge that this is affecting all the interfaces on the host (including the Cilium-managed ones) so we instead went for a (perhaps naive) patch: [v1.13.2...sebltm:cilium:frag-workaround](https://github.com/cilium/cilium/compare/v1.13.2...sebltm:cilium:frag-workaround)

Curious - that would point at an issue with the [fragmentation tracking](https://github.com/cilium/cilium/blob/a7a483ac3782574e56d63e7adbd5d6fb61686743/bpf/lib/ipv4.h#L155) code, and how we cache the ports for subsequent fragments.

**Comment by sebltm** [comment]
I think there might also be cases where packets/fragments arrive out of order, and sending fragments back through the qdisc might allow time for the the first frame of the packet to arrive and then process the fragment.
I haven't had time to investigate more in depth, so I'm assuming there is still some kind of bug with the fragment tracking code but I don't have proof of that just yet

**Comment by sebltm** [comment]
Just had a look at this. I would expect from https://github.com/cilium/cilium/blob/a7a483ac3782574e56d63e7adbd5d6fb61686743/bpf/lib/ipv4.h#L167-L168 that if this was a problem in adding the first frame into the datagram map, we'd see a spike in errors with ``reason="Fragmented packet entry update failed"`` from https://github.com/cilium/cilium/blob/a7a483ac3782574e56d63e7adbd5d6fb61686743/pkg/monitor/api/drop.go#L27 but after running the test that exposes this particular bug, I don't see this happening.
However we do see ``reason="First logical datagram fragment not found"`` from https://github.com/cilium/cilium/blob/a7a483ac3782574e56d63e7adbd5d6fb61686743/bpf/lib/ipv4.h#L118 so something must be happening: the first datagram is getting added to the map, but gets cleaned up too quickly? Some configuration that limits the size of the map? The ``frag_id`` somehow ends up being different between the first frame and the following fragments? More investigation needed

**Comment by Mitsuwa** [comment]
Is it possible that this issue can be reopened, this still seems to be an issue

**Comment by joestringer** [comment]
Cilium's IP fragment tracking doesn't cache or reassemble out-of-order messages. Doing so would be a feature request and likely a major amount of work at that. If there is a way to mitigate this through better MTU tuning or otherwise, then that would seem like the most practical solution.

**Comment by nijich** [comment]
I have similar problem for v1.14.6. When using vxlan tunnel with non-eBPF masquerade, the encapsuled UDP packets drop on receive side. `cilium monitor` shows `Invalid packet` and `Unsupported protocol for NAT masquerade... TimeExceeded(FragmentReassemblyTimeExceeded)`.

**Comment by sebltm** [comment]
Looks like there is some support to reassemble IPv4 in BPF https://lore.kernel.org/lkml/1f48a340a898c4d22d65e0e445dbf15f72081b9a.1671049840.git.dxu@dxuuu.xyz/
I wonder if we could make use of that

**Comment by new-vkatamre-cisco** [comment]
Is there a way to send all the fragmented packets to regular reassembly path in the kernel and then reinject back into ?

**Comment by guoard** [comment]
Is it possible to reopen this issue?

**Comment by pchaigno** [comment]
Joe's [answer](https://github.com/cilium/cilium/issues/25709#issuecomment-1969602232) is still relevant here. So unless someone is ready to invest the time to implement this feature request, this issue will go stale again after a while.

> Looks like there is some support to reassemble IPv4 in BPF https://lore.kernel.org/lkml/1f48a340a898c4d22d65e0e445dbf15f72081b9a.1671049840.git.dxu@dxuuu.xyz/ I wonder if we could make use of that

That patch wasn't merged as is. In the end, the defragmentation support was added directly to BPF programs of type netfilter, which we don't use.

**Comment by joestringer** [comment]
There's some good resources out there around the shortfalls of IP fragmentation, which I think help to inform why this issue isn't getting much traction:

[RFC 8900: IP Fragmentation Considered Fragile](https://www.ietf.org/rfc/rfc8900.html)
[CloudFlare: IP Fragmentation is Broken](https://blog.cloudflare.com/ip-fragmentation-is-broken/)

**Comment by brianbraunstein** [comment]
Unfortunately, if you're working with SIP you're forced into supporting fragmented UDP packets, both inbound and outbound.  While the SIP RFC says otherwise, the practical world of SIP is different and so you won't be able to interoperate with a large percentage of the SIP world.  Hopefully there's a workaround otherwise it seems like Cilium is essentially incompatible with SIP.

**Comment by lorenzo-biava** [comment]
@joestringer given the current state of Cilium and the stance not to implement reliable support for fragmented packets, if there was an absolute need to support fragmented packets, do you think there would be a way to have a dedicated set of nodes that don't run Cilium at all, or configure Cilium not to intercept incoming packets on the main interface of the node?
My current understanding is that even with pods in host network the incoming packets would be dropped if the first one isn't the first fragment (and in some scenarios this happens consistently).

Also would you consider adding an explicit disclaimer under the [fragmentation doc](https://docs.cilium.io/en/latest/network/concepts/fragmentation/)? this would make it easier for adopters to really understand the limitations, and potentially not invest too much if there is a lack of compatibility with their scenario

**Comment by joestringer** [comment]
I'm sure there's a way, and by all means I'd encourage you to try things out and share what works for you in this thread. As for the documentation, I would welcome a PR contributon to clarify the current status of not supporting out-of-order fragments. It would probably make sense to have a known issues section in the document that links to this issue so that users who need this capability can find others who are working on this problems. That'll make it easier to coordinate and push this deployment case forward 👍 

For now I'll reopen & pin and reword the title to clarify that it's about out-of-order fragment handling.

**Comment by lorenzo-biava** [comment]
I tried multiple options (disabling fragmentation -- just drops the packets; removing kube-proxy-replacement; disabling host firewall)... It seems that any configuration will go through that BPF code and drop the packet.

The only hack I managed to find is to run a tc filter before Cilium's, and just have it claim packets that have any fragmentation flags. e.g.
```
tc filter add dev enp0s5 ingress prio 1 protocol ip \
        flower ip_flags frag/frag action ok
```

Plus using a CiliumNodeConfig to shift the priority of its filter (this might be applied globally, but I wanted to make it clear these nodes are special).

```
apiVersion: cilium.io/v2
kind: CiliumNodeConfig
metadata:
  namespace: kube-system
  name: <your node pool>-overrides
spec:
  nodeSelector:
    matchLabels:
      <your node pool label>
  defaults:
    bpf-filter-priority: "10"
```

Do you find this reasonable? Any catches I'm missing? I'm not an expert in this specific domain, but this sounds ok to me.
However, ideally there would be a native setting in Cilium to opt-out the fragmentation logic completely (instead of it dropping the fragmented packets).

I'm happy to open that PR, but I would like to include some pointers on how to work around the limited support to make it more complete and useful.
