### ISSUE TITLE
Cilium doesn't select the endpoints in another cluster if a subset of labels is specified

### ISSUE THREAD

**Issue by farcaller** [cilium/cilium#25762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

(This is a followup to #25630 that was further discussed on [slack](https://cilium.slack.com/archives/C01JALNQAR1/p1684953184140429). Opening a new bug as the behavior seems very confusing).

Given the following policy:

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: blog-caddy
  namespace: blog
spec:
  egress:
    - toEndpoints:
        - matchLabels:
            app: blog-php
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: '53'
              protocol: UDP
          rules:
            dns:
              - matchPattern: '*'
  endpointSelector:
    matchLabels:
      app: blog-caddy
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: istio-ingress
      toPorts:
        - ports:
            - port: '80'
```

And the following endpoints discovered from the clustermesh:

```
cilium identity list -o json|jq '.[] | select( .labels | any(contains("app=istio-ingress")) )'
{
  "id": 921087,
  "labels": [
    "k8s:io.cilium.k8s.policy.serviceaccount=istio-ingress-tailnet",
    "k8s:istio=ingress-tailnet",
    "k8s:istio.io/rev=default",
    "k8s:service.istio.io/canonical-name=istio-ingress-tailnet",
    "k8s:app=istio-ingress-tailnet",
    "k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=istio-ingress",
    "k8s:io.cilium.k8s.policy.cluster=ingress-istio",
    "k8s:io.kubernetes.pod.namespace=istio-ingress",
    "k8s:service.istio.io/canonical-revision=latest",
    "k8s:sidecar.istio.io/inject=true"
  ]
}
{
  "id": 960438,
  "labels": [
    "k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=istio-ingress",
    "k8s:io.kubernetes.pod.namespace=istio-ingress",
    "k8s:istio=ingress",
    "k8s:istio.io/rev=default",
    "k8s:app=istio-ingress",
    "k8s:io.cilium.k8s.policy.cluster=ingress-istio",
    "k8s:io.cilium.k8s.policy.serviceaccount=istio-ingress",
    "k8s:service.istio.io/canonical-name=istio-ingress",
    "k8s:service.istio.io/canonical-revision=latest",
    "k8s:sidecar.istio.io/inject=true"
  ]
}
```

The CEP status is

```
    ingress:
      allowed:
        - identity: 1
          identity-labels:
            'reserved:host': ''
        - dest-port: 80
          identity: 1
          identity-labels:
            'reserved:host': ''
          protocol: 6
      enforcing: true
      state: enforcing
```

And the endpoints are not selected (all the ingress traffic is dropped).

The issue resolves itself upon adding `k8s:io.kubernetes.pod.namespace: istio-ingress` to the match list, but I want to emphasise that those two endpoints are the only ones in the whole mesh that have `app=istio-ingress`  label so there's really no good reason for them not to be selected.

### Cilium Version

1.13 and 1.14-snapshot-2

### Kernel Version

`Linux web 6.1.27 https://github.com/cilium/cilium/pull/1-NixOS SMP PREEMPT_DYNAMIC Sun Apr 30 23:26:28 UTC 2023 x86_64 GNU/Linux`

### Kubernetes Version

`v1.26.4+k3s1`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
