### ISSUE TITLE
Cilium Clustermesh Failover not working on ingress-nginx but on service level

### ISSUE THREAD

**Issue by jannes-stubbemann-20230331** [cilium/cilium#25818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We got two clusters and have set up cilium clustermesh for cluster failover. 

When deleting the pods I can confirm the failover is working on service level. But when accessing the service from the outside through nginx ingress, a `503 Service Unavailble` response is returned in that case.

This is our ingress config:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/upstream-hash-by: "$remote_addr"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/connection-proxy-header: ""
    nginx.ingress.kubernetes.io/proxy-body-size: "3m"
  name: test-ingress
spec:
  rules:
  - host: test.example.com
      paths:
      - backend:
          service:
            name: test
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
```

and this is how we enabled the clustermesh with helm values:

```
cilium:
  cluster:
    name: cluster-x
    id: x
  externalWorkloads:
    enabled: true
  clustermesh:
    useAPIServer: true
    apiserver:
      service:
        type: LoadBalancer
      replicas: 3
      tls:
        auto:
          method: certmanager
          certManagerIssuerRef:
            group: cert-manager.io
            kind: ClusterIssuer
            name: cilium-clustermesh-ca-issuer
        server:
          extraDnsNames:
            - '*.example.com'
    config:
      enabled: true
      clusters:
      - name: cluster-y
        address: {LB-ADDRESS-Y}
        port: 2379
```

### Cilium Version

```
-> cilium version -n cilium
cilium-cli: 0.14.0 compiled with go1.20.3 on darwin/arm64
cilium image (default): v1.13.2
cilium image (stable): v1.13.3
cilium image (running): v1.14.0-snapshot.2
```

### Kernel Version

-

### Kubernetes Version

```
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.13-eks-0a21954", GitCommit:"6305d65c340554ad8b4d7a5f21391c9fa34932cb", GitTreeState:"clean", BuildDate:"2023-04-15T00:33:45Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
