### ISSUE TITLE
CiliumInternalIP not restored on reboot

### ISSUE THREAD

**Issue by joamaki** [cilium/cilium#25856]
The IP address of the cilium_host device is not restored correctly from `CiliumNode` CRD across reboots.
On agent restart (`kill 1`) the IP is restored correctly from `cilium_host` device. Verified on v1.11.16 and v1.13.1.

Before reboot:
```
level=info msg="  Internal-Node IPv4: 10.1.1.42" subsys=daemon
```

After reboot (by mounting writeable proc and `echo b > sysrq-trigger`):
```
level=info msg="  Internal-Node IPv4: 10.1.1.228" subsys=daemon
```

Possibly relevant Cilium configuration values:
```
cluster:
  name: default
encryption:
  enabled: true
  type: ipsec
endpointRoutes:
  enabled: true
eni:
  enabled: true
etcd:
  enabled: true
  k8sService: false
  ssl: false
identityAllocationMode: kvstore
ipam:
  mode: eni
ipv4:
  enabled: true
ipv6:
  enabled: false
kvstore: etcd
localRedirectPolicy: true
tunnel: disabled
```
