### ISSUE TITLE
Update labels on endpoint upon k8s pod labels change

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#2590]
Currently we don't update the endpoints' labels if the labels are changed as well on running k8s pods .

This requires to add a new k8s watcher to watch for pods' changes.

**Comment by GolubevV** [comment]
I have got this problem reproduced in cilium 1.13.1.

Context:
- Vanilla K8s Ingress netpol
```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: sgp-test
  name: backend-policy
spec:
  ingress:
   - from:
     - podSelector:
         matchLabels:
           role: frontend
     ports:
     - port: 8080
       protocol: TCP
  podSelector:
    matchLabels:
      role: backend
  policyTypes:
  - Ingress
```

- Existing pod named `client` without any label with key `role`

- Label the pod either via `kubectl` or by editing applying manifest and check it was applied:
```bash
 kubectl label pod client role=frontend

kubectl get pod -l role=frontend
NAME     READY   STATUS    RESTARTS   AGE
client   1/1     Running   0          25m
```

- Look in the Hubble UI - traffic is dropped

-Check the Cilium endpoint of the object - no label is propagated:
```bash
kubectl get cep client --show-labels

NAME     ENDPOINT ID   IDENTITY ID   INGRESS ENFORCEMENT   EGRESS ENFORCEMENT   VISIBILITY POLICY   ENDPOINT STATE   IPV4           IPV6                        LABELS
client   318           53845         <status disabled>     <status disabled>    <status disabled>   ready            10.55.237.45   fe80::bc2b:bcff:feda:b1d3   app.kubernetes.io/name=client,skaffold.dev/run-id=c5407da2-5d14-41d1-9492-9a77cd4283ca
```
