### ISSUE TITLE
Incorrect handling of NetworkPolicy rules when configuring CiliumEnvoyConfig.

### ISSUE THREAD

**Issue by r541754175** [cilium/cilium#25998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
We use NetworkPolicy to restrict access to our services, and everything works fine before enabling EnvoyConfig. However, once EnvoyConfig is configured and the traffic is routed through Envoy, we experience unexpected 403 Access Denied errors. Upon investigation, it seems that this 403 error issue stems from the NetworkPolicy restrictions being enforced by Envoy.

This issue occurs only when the target service is configured in the spec.services of EnvoyConfig and the NetworkPolicy rules of the source service include the container port of the target service, along with multiple CIDR IP configurations.  

## Env

|----test-ns-- | -----------------------------my-ns----------------------------------- |
| &nbsp;&nbsp;   curl pod &nbsp; ->&nbsp; my-service[Envoyconfig,port:80]&nbsp;  &nbsp; ->&nbsp; &nbsp; my-service-pod [port:8080]   &nbsp;  |     
|------------- | -----------------------------------------------------------------------|
- "my-service" is a basic API service. Configure a simple EnvoyConfig with a custom header.
- Curl is running inside a pod, and there are no NetworkPolicy/CiliumNetworkPolicy defined within the namespace where Curl resides.
- All the subsequent traffic occurs within the context of Internal Traffic (east-west).

###  1. Configure a basic NetworkPolicy to allow Curl to access "my-service".
 
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pass
  namespace: test-ns
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: curl
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: my-service
          namespaceSelector:
            matchLabels:
              name: my-ns
  policyTypes:
    - Egress
```
#### 📌At this stage, the access to the service is functioning properly, and it returns an HTTP status code of **200**.  
&emsp;
![MicrosoftTeams-image (3)](https://github.com/cilium/cilium/assets/2620036/c7704363-b174-4071-8bed-59a5e893001d)

  
  
###  2. To add an egress rule allowing the Curl pod to access port 8080 on IP address 192.168.0.1,please note that the port specified in the egress rule should match the container port of 'my-service', but the IP address is not related to 'my-service'.
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pass
  namespace: test-ns
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: curl
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: my-service
          namespaceSelector:
            matchLabels:
              name: my-ns
    - ports:
        - protocol: TCP
          port: 8080
      to:
        - ipBlock:
            cidr: 192.168.0.1/32
  policyTypes:
    - Egress
```
#### 📌At this stage, the access to the service is functioning properly, and it returns an HTTP status code of 200.  
&emsp;
### 3.To add another "ipBlock" to the "to" array, with an IP of 192.168.0.2  
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pass
  namespace: test-ns
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: curl
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: my-service
          namespaceSelector:
            matchLabels:
              name: my-ns
    - ports:
        - protocol: TCP
          port: 8080
      to:
        - ipBlock:
            cidr: 192.168.0.1/32
        - ipBlock:
            cidr: 192.168.0.2/32
  policyTypes:
    - Egress
```
  

#### 📌This time, the request returns a 403 Access Denied response, and the "x-envoy-flags" header is set to "UAEX," indicating that it has been blocked by the policy.

> but,If you change the protocol of egress[1].ports[0] to UDP, the HTTP request will still return a 200 success.  
###  
![MicrosoftTeams-image (2)](https://github.com/cilium/cilium/assets/2620036/aeb6235c-6fef-4733-8ac2-6924104bd37f)

### 4.Now, delete the EnvoyConfig. The request will immediately return to normal and respond with a 200 status code. The NetworkPolicy remains unchanged.
![MicrosoftTeams-image (1)](https://github.com/cilium/cilium/assets/2620036/70754ead-3ea1-42a4-8379-8bedbff0b565)

## Issue
1. Whenever traffic passes through Envoy, NetworkPolicy is unable to accept multiple CIDRs within the same port and protocol combination, resulting in the described issue where duplicate combinations of protocol and port lead to the problem.

2. In the mentioned scenario, when I attempted to add an "Allow All" rule, the request still received a 403 response. However, based on my reading of the Kubernetes documentation [doc](https://kubernetes.io/docs/concepts/services-networking/network-policies/#allow-all-egress-traffic) NetworkPolicy, when an "Allow All" rule is configured, it should ignore other rules. Nevertheless, this behavior did not occur in the case of Envoy. 

### Cilium Version

Client: 1.13.2 https://github.com/cilium/cilium/commit/8cb94c70f7105f29a69e754d2b8969117e681775 2023-04-17T23:19:21+02:00 go version go1.19.8 linux/amd64
Daemon: 1.13.2 https://github.com/cilium/cilium/commit/8cb94c70f7105f29a69e754d2b8969117e681775 2023-04-17T23:19:21+02:00 go version go1.19.8 linux/amd64

### Kernel Version

Linux 5.15.98-flatcar https://github.com/cilium/cilium/pull/1 SMP Thu Apr 13 03:16:20 -00 2023 x86_64 Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz GenuineIntel GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-18T19:08:10Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

### Anything else?

my-service CiliumEnvoyConfig
```yaml
apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:
  name: my-service
  namespace: my-ns
spec:
  backendServices:
    - name: my-service
      namespace: my-ns
  resources:
    - '@type': type.googleapis.com/envoy.config.listener.v3.Listener
      filterChains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typedConfig:
                '@type': >-
                  type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                httpFilters:
                  - name: envoy.filters.http.router
                    typedConfig:
                      '@type': >-
                        type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                rds:
                  routeConfigName: my-ns/my-service
                statPrefix: my-ns/my-service
      name: my-ns/my-service
    - '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
      name: my-ns/my-service
      virtualHosts:
        - domains:
            - '*'
          name: my-ns/my-service
          routes:
            - match:
                prefix: /
              requestHeadersToAdd:
                - header:
                    key: x-flow
                    value: mesh-weight
              responseHeadersToAdd:
                - header:
                    key: x-flow
                    value: mesh-weight
                - header:
                    key: x-envoy-details
                    value: '%RESPONSE_CODE_DETAILS%'
                - header:
                    key: x-envoy-flags
                    value: '%RESPONSE_FLAGS%'
              route:
                retryPolicy:
                  numRetries: 3
                  perTryTimeout: 6s
                  retryOn: reset
                weightedClusters:
                  clusters:
                    - name: my-ns/my-service
                      weight: 100
    - '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
      commonLbConfig:
        healthyPanicThreshold: {}
      connectTimeout: 5s
      name: my-ns/my-service
      outlierDetection:
        consecutiveLocalOriginFailure: 2
        splitExternalLocalOriginErrors: true
      type: EDS
  services:
    - listener: ''
      name: my-service
      namespace: my-ns
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
