### ISSUE TITLE
NodePort is blocked by networkpolicies

### ISSUE THREAD

**Issue by FJEANNOT** [cilium/cilium#26126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On a Scaleway Capsule Cluster with Cilium CNI, all NodePort services are working fine untill we add a NetworkPolicy (Standard kubernetes ressource, not the Cillium CRD). 

The network policies are the following
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
  namespace: namespace-name
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          namespace-name: namespace-name
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cluster-systems
  namespace: namespace-name
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          cluster-systems: "true"
  podSelector: {}
  policyTypes:
  - Ingress
```

These are working fine, but all the NodePorts seems to be blocked by Cilium after that. These are standard NodePorts exposing pods from the namespace to the outside world.

Deleting all the NetworkPolicies in the namespaces opens the NodePort again, so this definitely seems that the NetworkPolicies are causing it.

We tried to configure a CiliumNetworkPolicy for one redis pod with no success.

Here is the cilium configmap:
```
apiVersion: v1
data:
  auto-direct-node-routes: "false"
  bpf-lb-map-max: "65536"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: "0"
  cluster-name: default
  custom-cni-conf: "false"
  debug: "false"
  disable-cnp-status-updates: "true"
  enable-auto-protect-node-port-range: "true"
  enable-bandwidth-manager: "false"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "false"
  enable-bpf-tproxy: "true"
  enable-endpoint-health-checking: "true"
  enable-health-check-nodeport: "false"
  enable-health-checking: "true"
  enable-host-port: "true"
  enable-hubble: "false"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-l7-proxy: "true"
  enable-local-redirect-policy: "true"
  enable-node-port: "true"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  hubble-disable-tls: "false"
  hubble-listen-address: :4244
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  ipam: kubernetes
  k8s-api-server: https://[redacted].api.k8s.fr-par.scw.cloud:6443
  k8s-require-ipv4-pod-cidr: "true"
  k8s-require-ipv6-pod-cidr: "false"
  kube-proxy-replacement: partial
  kube-proxy-replacement-healthz-bind-address: ""
  masquerade: "true"
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  node-port-range: 30000,32767
  operator-api-serve-addr: 127.0.0.1:9234
  preallocate-bpf-maps: "false"
  procfs: /host/proc
  sidecar-istio-proxy-image: cilium/istio_proxy
  tunnel: vxlan
  wait-bpf-mount: "false"
kind: ConfigMap
metadata:
  labels:
    k8s.scw.cloud/cni: cilium
    k8s.scw.cloud/object: ConfigMap
    k8s.scw.cloud/system: cni
  name: cilium-config
  namespace: kube-system
```

Is this the standard behavior ? What could be blocking the NodePorts ?

### Cilium Version

Client: 1.13.2 8cb94c70 2023-04-17T23:19:21+02:00 go version go1.19.8 linux/amd64
Daemon: 1.13.2 8cb94c70 2023-04-17T23:19:21+02:00 go version go1.19.8 linux/amd64

### Kernel Version

Linux 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.0", GitCommit:"1b4df30b3cdfeaba6024e81e559a6cd09a089d65", GitTreeState:"clean", BuildDate:"2023-04-11T17:04:24Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20230612-155913.zip](https://github.com/cilium/cilium/files/11724129/cilium-sysdump-20230612-155913.zip)

### Relevant log output

```shell
There are no log outputs, all attempts to contact the NodePort end with a timeout.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi, I think that this is expected behaviour. 

This rule allows pods from the namespace with labels `cluster-systems: true` to access pods inside the namespace that the policy is installed:
```
  - from:
    - namespaceSelector:
        matchLabels:
          cluster-systems: "true"
```

Traffic from outside the cluster does not have these labels.

One step that could help to explore possible solutions here would be to use Hubble and `hubble observe` to see why Cilium drops the traffic.

Depending on whether you are able to use client source IP preservation techniques, it may be possible to write CIDR policies to allow traffic from the NodePorts on ingress, or alternatively you may need a Cilium policy that allows `fromEntities: world`.
