### ISSUE TITLE
CFP: Egress Policy to restrict traffic to specific set without blocking all 

### ISSUE THREAD

**Issue by tamilmani1989** [cilium/cilium#26135]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature request for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your feature request related to a problem?**

If so, please describe the problem

**Describe the feature you'd like**
The current implementation of Cilium lacks a mechanism to restrict egress traffic to specific endpoints without blocking all traffic. When the egress policy is enabled for an endpoint, it effectively goes into a default deny state for egress traffic. Even if an "allow-all" policy is enforced to counteract this behavior, it can introduce conflicts when other network policies are defined with restricted access. This feature is essential for cloud provider to enforce network policy at cluster level to restrict access to infrastructure components. This proposal aims to solve this issue and enhance cilium functionality.

Include any specific requirements you need

**(Optional) Describe your proposed solution**

Proposal Doc:  https://docs.google.com/document/d/1ZtHn4ZHtNFD-z5vQl0AckgCb14GSNPGDMzZchgRo1uI/edit?usp=sharing

Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.

**Comment by tamilmani1989** [comment]
commenting out for removing stale label

**Comment by tamilmani1989** [comment]
@joestringer can you please add pinned label to this issue?

**Comment by squeed** [comment]
I believe this is now possible.  You can use on-disk network policies to deny access to a cloud metadata service without setting an endpoint to default-deny.

```yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: deny-metadata-access
spec:
  endpointSelector:
    matchExpressions:
      - key: io.kubernetes.pod.namespace
        operator: NotIn
        values: ["kube-system"]
  enableDefaultDeny:
    egress: false
  egressDeny:
    - toCIDR: ["169.254.20.10/32"]
```

You can even use [on-disk network policies](https://docs.cilium.io/en/stable/security/policy/disk-based/#disk-based-cilium-network-policies) to prevent modification.
