### ISSUE TITLE
CFP: Add support for GRE-over-IP with host firewall

### ISSUE THREAD

**Issue by steveb05** [cilium/cilium#26178]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

We have some nodes using a GRE tunnel to communicate, however, this in combination with Cilium's host firewall makes the node unreachable, due to the fact that the host firewall currently does not support GRE-over-IP, causing the packets coming from the router to be dropped with the reason `CT: Unknown L4 protocol`.

**Describe the feature you'd like**

The ability to use Cilium's host firewall with GRE tunnels.

**Comment by sterchelen** [comment]
Guys, happy to help on this one. I would just need some guidance.
1. @steveb05 I would like to know your setup, to reproduce the behavior you're experiencing.
2. @joestringer do you have proposal design doc template? Or a previous proposal that we could take as an example.

**Comment by steveb05** [comment]
Thank you for your interest.

@sterchelen the setup I am using consists of Ubuntu 22.04.2 LTS and the kernel updated to version 6.1.31. I am running K3S v1.25.5, with kube-proxy, servicelb and flannel disabled. I have Cilium 1.13.3 deployed with helm, and metallb as a load balancer.

My values for Cilium:
```yaml
cluster:
  id: 0
  name: default

k8sServiceHost: "127.0.0.1"
k8sServicePort: "6443"

bpf:
  masquerade: true

ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDR: "10.43.0.0/16"
    clusterPoolIPv4MaskSize: 24

encryption:
  nodeEncryption: false

kubeProxyReplacement: "strict"

operator:
  replicas: 1

serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator

tunnel: vxlan

hostFirewall:
  enabled: false

policyEnforcementMode: always
policyAuditMode: false
extraConfig:
  allow-localhost: "policy"

bandwidthManager:
  enabled: true
  bbr: true
```

The tunnel is managed by another provider, however if you need help on how you can set up a similar one, let me know and I will be more than happy to write down the steps on how to do it.
