### ISSUE TITLE
 Layer 7 loadbalancing using Cilium Envoy / Ignoring invalid CiliumEnvoyConfig

### ISSUE THREAD

**Issue by philippmoritzer** [cilium/cilium#26358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm using layer 7 load balancing using envoy for GCP microservices-demo project, and while it does work for some services, it outputs this warning message. Then the load balancing does not work at all.

helmfile values: 
```
operator:
  replicas: 1
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
cni:
  binPath: /usr/libexec/cni
kubeProxyReplacement: strict
extraConfig:
  enable-envoy-config: "true"
loadBalancer:
  l7:
    backend: envoy
```
service annotations:
```

metadata:
  name: {{ .Values.checkoutService.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    service.cilium.io/lb-l7: enabled
```

### Cilium Version

1.13.2

### Kernel Version

6.2.6-76060206-generic

### Kubernetes Version

1.25.6

### Sysdump

[cilium-sysdump-20230619-164106.zip](https://github.com/cilium/cilium/files/11789273/cilium-sysdump-20230619-164106.zip)

### Relevant log output

```shell
level=warning msg="Ignoring invalid CiliumEnvoyConfig JSON (proto:\u00a0(line 1:405): unable to resolve \"type.googleapis.com/envoy.extensions.filters.http.router.v3.Router\": \"not found\"): {\n\t\"@type\": \"type.googleapis.com/envoy.config.listener.v3.Listener\",\n\t\"filterChains\": [\n\t\t{\n\t\t\t\"filterChainMatch\": {\n\t\t\t\t\"transportProtocol\": \"raw_buffer\"\n\t\t\t},\n\t\t\t\"filters\": [\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"envoy.filters.network.http_connection_manager\",\n\t\t\t\t\t\"typedConfig\": {\n\t\t\t\t\t\t\"@type\": \"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager\",\n\t\t\t\t\t\t\"httpFilters\": [\n\t\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\t\"name\": \"envoy.filters.http.router\",\n\t\t\t\t\t\t\t\t\"typedConfig\": {\n\t\t\t\t\t\t\t\t\t\"@type\": \"type.googleapis.com/envoy.extensions.filters.http.router.v3.Router\"\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t],\n\t\t\t\t\t\t\"rds\": {\n\t\t\t\t\t\t\t\"routeConfigName\": \"boutique/shippingservice\"\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\"statPrefix\": \"boutique/shippingservice\",\n\t\t\t\t\t\t\"upgradeConfigs\": [\n\t\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\t\"upgradeType\": \"websocket\"\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t],\n\t\t\t\t\t\t\"useRemoteAddress\": true\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t]\n\t\t}\n\t],\n\t\"listenerFilters\": [\n\t\t{\n\t\t\t\"name\": \"envoy.filters.listener.tls_inspector\",\n\t\t\t\"typedConfig\": {\n\t\t\t\t\"@type\": \"type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector\"\n\t\t\t}\n\t\t}\n\t],\n\t\"name\": \"boutique/shippingservice\"\n}" subsys=k8s-apis-cilium.io-v2
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by philippmoritzer** [comment]
I'm trying to activate L7 load balancing for the GCP microservices-demo project, unfortunately I've been having some trouble. Generally I feel like it kinda works though. My Kubernetes version is 26.5.1, I'm using Rancher desktop (changed the override.yaml in _lima config, specified CLI path in helm deployment). I'm using cilium 1.13.4. These are my values:

operator:  
  replicas: 1
cni:
  install: true
  binPath: /usr/libexec/cni
#l7Proxy: true #doesn't change anything
kubeProxyReplacement: strict
extraConfig:
 enable-envoy-config: "true"
loadBalancer:
  l7:
    backend: envoy

inside  my templates for the microservices-demo files I put these annotations for every deployment (except for http frontend and tcp-redis redis):

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.checkoutService.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    service.cilium.io/lb-l7: enabled
spec:
...

So when accessing the frontend now, I get an error

rpc error: code = FailedPrecondition desc = Can't access cart storage. 

This is not always the same error, though it changes from time to time, but always an RPC error. However when doing grpccurl onto the services, I get a response from the envoy proxy, so this seems to work fine. For hubble observability I get "Missed tail call" from the flows, which makes sense I guess. Using the loadgenerator or any kind of load testing tool (I was doing some loadtesting with JMeter) some calls process, some don't. If for example I only add loadbalancing to the checkoutservice the project seems to work. Any help would be greatly appreciated!Ah by the way, when I describe a pod I sometimes get this output, but it vanishes on restart. Cilium itself seems to be working fine though, I get hubble metrics that i can observe with cilium, and it works fine:

```
2124c68e6f46fdffca737aeba215ff6980c4fb1f9c": cni plugin not initialized
  Warning  NetworkNotReady         10m (x6 over 10m)      kubelet            network is not ready: container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
  Normal   Pulled                  9m46s                  kubelet            Container image "gcr.io/google-samples/microservices-demo/currencyservice:v0.6.0-native-grpc-probes" already present on machine
  Normal   Created                 9m46s                  kubelet            Created container server
  Normal   Started                 9m46s                  kubelet            Started container server
  Warning  Unhealthy               9m44s (x2 over 9m45s)  kubelet            Readiness probe failed: timeout: failed to connect service "10.0.0.192:7000" within 1s: context deadline exceeded
```

**Comment by philippmoritzer** [comment]
Still cannot seem to resolve the issue. When manualing defining envoy load balancing with following config:
```

apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:  
  name: cilium-envoy-lb-cartservice
  namespace: boutique  
spec:
  resources:
  - '@type': type.googleapis.com/envoy.config.listener.v3.Listener
    filterChains:
    - filterChainMatch:
        transportProtocol: raw_buffer
      filters:
      - name: envoy.filters.network.http_connection_manager
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          httpFilters:
          - name: envoy.filters.http.router
            typedConfig:
              '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          rds:
            routeConfigName: boutique/cartservice
          statPrefix: boutique/cartservice
          upgradeConfigs:
          - upgradeType: websocket
          useRemoteAddress: true
    listenerFilters:
    - name: envoy.filters.listener.tls_inspector
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
    name: boutique/cartservice
  - '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
    name: boutique/cartservice
    virtualHosts:
    - domains:
      - '*'
      name: boutique/cartservice
      routes:
      - match:
          prefix: /
        route:
          cluster: boutique/cartservice
          maxStreamDuration:
           maxStreamDuration: 0s
          timeout: 0s
  - '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
    connectTimeout: 10s
    name: boutique/cartservice
    outlierDetection:
      consecutiveLocalOriginFailure: 2
      splitExternalLocalOriginErrors: true
    type: EDS
    typedExtensionProtocolOptions:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        useDownstreamProtocolConfig:
          http2ProtocolOptions: {}
  services:
  - listener: ""
    name: cartservice
    namespace: boutique
```

this error appears:

rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 110
could not retrieve cart
