### ISSUE TITLE
CiliumNetworkPolicy don't validate port value

### ISSUE THREAD

**Issue by adamw-linadm** [cilium/cilium#26384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I spent a few hours today validating why network policy doesn't work and came across this:
```
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: dummy-app
  namespace: dummy
spec:
  endpointSelector:
    matchLabels:
      app: dummy-app
  egress:
    - toFQDNs:
        - matchPattern: "fake.example.com"
      toPorts:
        - ports:
          - port: "6581-6586"
```
 When I applied it, I'm get:
 ```
✗ kubectl apply -f dummy-app.yaml 
ciliumnetworkpolicy.cilium.io/dummy-app created
```
But cilium didn't create such policy:
```
root@node:/home/cilium# cilium policy get | grep dummy-app
root@node:/home/cilium#
```
When I try another apply I got:
```
 kubectl apply -f dummy-app.yaml
ciliumnetworkpolicy.cilium.io/dummy-app unchanged
```
So policy are known but not created/raised error on invalid data.

### Cilium Version

1.13.4

### Kernel Version

Linux  node 4.18.0-477.10.1.el8_8.x86_64 #1 SMP Tue May 16 07:35:04 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.26.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
