### ISSUE TITLE
After lb-ipam assigns IP, the external network cannot be accessed

### ISSUE THREAD

**Issue by w7team** [cilium/cilium#26456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "blue-pool"
spec:
  cidrs:
    - cidr: "118.25.148.170/30"
```
![image](https://github.com/cilium/cilium/assets/74588507/f3c30531-3c46-42cf-a06e-361bc40de7ea)

![image](https://github.com/cilium/cilium/assets/74588507/f085ebaa-6ac4-4e0c-b770-1149da79df11)

由于lb-ipam目前不能分配单个ip，我临时改成/30测试一下，发现在svc中ip是成功分配了，但是外网无法正常访问。我用的k3s，已经--disable=servicelb，想问下配合lb-ipam使用的话，是不是还需要安装一个独立的servicelb？

Since lb-ipam cannot assign a single ip at present, I temporarily changed it to /30 for testing, and found that the ip was successfully assigned in svc, but the external network cannot be accessed normally. The k3s I use already has --disable=servicelb. I would like to ask whether it is necessary to install an independent servicelb if it is used with lb-ipam?

### Cilium Version

cilium-cli: v0.14.7 compiled with go1.20.4 on linux/amd64
cilium image (default): v1.13.3
cilium image (stable): v1.13.4

### Kernel Version

5.14.0-202.el9.x86_64

### Kubernetes Version

k3s version v1.27.2+k3s1 (213d7ad4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
