### ISSUE TITLE
Failure using non-default ip pool when combining multi-pool with etcd

### ISSUE THREAD

**Issue by MaienM** [cilium/cilium#26621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've been playing around with multi-pool mode. I was using the following options + test resources, and it was all working as expected until I tried to use etcd.

Install:

```
helm install cilium cilium/cilium \
	--version=1.14.0-snapshot.4 \
	--namespace=cilium \
	--create-namespace \
	--set k8sServiceHost=192.168.50.3 \
	--set k8sServicePort=6443 \
	--set cni.install=false \
	--set-string extraConfig.write-cni-conf-when-ready= \
	--set ipam.mode=multi-pool \
	--set tunnel=disabled \
	--set autoDirectNodeRoutes=true \
	--set ipv4NativeRoutingCIDR=10.200.0.0/8 \
	--set endpointRoutes.enabled=true \
	--set-string extraConfig.enable-local-node-route=false \
	--set kubeProxyReplacement=strict \
	--set bpf.masquerade=true \
	--set ipam.operator.autoCreateCiliumPodIPPools.default.ipv4.cidrs='{10.200.0.0/16}' \
	--set ipam.operator.autoCreateCiliumPodIPPools.default.ipv4.maskSize=24 \
	--set ipam.operator.autoCreateCiliumPodIPPools.iot.ipv4.cidrs='{192.168.3.16/28}' \
	--set ipam.operator.autoCreateCiliumPodIPPools.iot.ipv4.maskSize=30
```

Resources:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: default-test
  template:
    metadata:
      labels:
        name: default-test
      annotations:
        ipam.cilium.io/ip-pool: default
    spec:
      containers:
        - name: toolbox
          args: ["tail", "-F", "/dev/null"]
          image: docker.io/wbitt/network-multitool
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iot-test
  template:
    metadata:
      labels:
        name: iot-test
      annotations:
        ipam.cilium.io/ip-pool: iot
    spec:
      containers:
        - name: toolbox
          args: ["tail", "-F", "/dev/null"]
          image: docker.io/wbitt/network-multitool
          imagePullPolicy: IfNotPresent
```

This works fine. When I add the following options to the install things break.

```
	--set identityAllocationMode=kvstore \
	--set etcd.enabled=true \
	--set etcd.ssl=true \
	--set etcd.endpoints='{https://192.168.50.10:2379,https://192.168.50.11:2379,https://192.168.50.12:2379}'
```

Once I do this the `default-test` pod still starts, but the `iot-test` pod is stuck on `ContainerCreating` with the message `pool not (yet) available`. Running `cilium status` shows that there is an issue updating a node: `controller ipam-sync-multi-pool is failing since 13s (68x): failed to update node spec: Operation cannot be fulfilled on ciliumnodes.cilium.io "neptune": the object has been modified; please apply your changes to the latest version and try again`.

### Cilium Version

cilium-cli: 0.14.3 compiled with go1.20.4 on linux/amd64
cilium image (default): v1.13.2
cilium image (stable): v1.13.4
cilium image (running): v1.14.0-snapshot.4

### Kernel Version

neptune.local: Linux neptune 6.1.31 # 1-NixOS SMP PREEMPT_DYNAMIC Tue May 30 13:03:33 UTC 2023 x86_64 GNU/Linux
sedna.local: Linux sedna 6.1.21 # 1-NixOS SMP Tue Jan  1 00:00:00 UTC 1980 aarch64 GNU/Linux

All other nodes are like sedna.

### Kubernetes Version

Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.2

### Sysdump

[cilium-sysdump-20230704-122112.zip](https://github.com/cilium/cilium/files/11948675/cilium-sysdump-20230704-122112.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
