### ISSUE TITLE
Observing ImagePullBackOff and CrashLoopBackoff in Kubernetes example with cluster built with kops running in AWS

### ISSUE THREAD

**Issue by natemurthy** [cilium/cilium#2662]
When following the [Getting Started](http://docs.cilium.io/en/latest/gettingstarted/minikube/#step-1-installing-cilium) docs for installing Cilium on Kubernetes, the pods created end up in either an `ImagePullBackOff` state or a `CrashLoopBackoff` state as follows:

```
$ kubectl get pods --namespace kube-system
NAME                              READY     STATUS             RESTARTS   AGE
cilium-gbz8v                      0/1       Error              0          1m
cilium-pxfz7                      0/1       CrashLoopBackOff   3          1m
cilium-z2cnm                      0/1       ImagePullBackOff   0          1m
...
```

### General Information

- Cilium version: Docker Image `cilium/cilium:stable`
- Kernel version: `4.4.111-k8s`
- Orchestration system version in use: Kubernetes 1.8.6
- Link to relevant artifacts: https://github.com/cilium/cilium/blob/master/examples/kubernetes/cilium.yaml

### How to reproduce the issue

Create a k8s cluster using:

```
kops create cluster \
  --cloud=aws \
  --name=<REDACTED> \
  --state=s3://<REDACTED> \
  --zones=us-west-2b \
  --node-count=2 \
  --node-size=t2.medium \
  --master-size=m4.large \
  --dns=private \
  --dns-zone=<REDACTED> \
  --dns-zone=<REDACTED> \
  --yes
```
After about 15 minutes the nodes will be up and DNS records will have been propagated. Execute comand:
```
$ kubectl create -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/kubernetes/cilium.yaml
```
and observe state of pods over a few minutes.

**Comment by tgraf** [comment]
@natemurthy What error does `kubectl` report if you run `kubectl -n kube-system logs cilium-gbz8v`?

**Comment by natemurthy** [comment]
Here are the logs from that pod:
```
$ kubectl -n kube-system logs cilium-gbz8v
level=info msg="     _ _ _"
level=info msg=" ___|_| |_|_ _ _____"
level=info msg="|  _| | | | | |     |"
level=info msg="|___|_|_|_|___|_|_|_|"
level=info msg="Cilium 1.0.0-rc4 0b608d5 2018-01-25T19:46:08+01:00 go version go1.9 linux/amd64"
level=fatal msg="kernel version: NOT OK: minimal supported kernel version is >= 4.8.0; kernel version that is running is: 4.4.111"
```
So looks like my nodes need a more recent kernel =/ I'm using `kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14` -- which explains the CrashLoopBackOff, but what about the ImagePullBackoff?

Let my try this out again with an AWS AMI built on a later kernel version...

**Comment by natemurthy** [comment]
Alright, so I upgraded my cluster to use the `coreos.com/CoreOS-stable-1576.5.0-hvm` image on my nodes which is built on the `4.14.11` Linux kernel. But now I see this in the logs:
```
$ kubectl -n kube-system logs cilium-7s9j9
level=info msg="     _ _ _"
level=info msg=" ___|_| |_|_ _ _____"
level=info msg="|  _| | | | | |     |"
level=info msg="|___|_|_|_|___|_|_|_|"
level=info msg="Cilium 1.0.0-rc4 0b608d5 2018-01-25T19:46:08+01:00 go version go1.9 linux/amd64"
level=info msg="clang (3.8.1) and kernel (4.14.11) versions: OK!"
level=info msg="linking environment: OK!"
level=info msg="bpf_requirements check: OK!"
level=fatal msg="Unable to setup kvstore" error="dial tcp 127.0.0.1:2379: getsockopt: connection refused"
```
Pod ending up in a crash loop again as a result.

**Comment by tgraf** [comment]
> Pod ending up in a crash loop again as a result.

Yes, the kernel is recent enough now. The only external dependency that Cilium has is a kvstore. It can be either consul or etcd.

Edit the cilium.yaml and modify `etcd-config` to point to one or more etcd nodes.

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: cilium-config
  namespace: kube-system
data:
  # This etcd-config contains the etcd endpoints of your cluster. If you use
  # TLS please make sure you uncomment the ca-file line and add the respective
  # certificate has a k8s secret, see explanation bellow in the comment labeled
  # "ETCD-CERT"
  etcd-config: |-
    ---
    endpoints:
    - http://127.0.0.1:2379
```
