### ISSUE TITLE
pod lost ciliumendpoints after restart docker daemon

### ISSUE THREAD

**Issue by QQGoblin** [cilium/cilium#26909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In my kubernetes environment, when I restart the docker of some nodes, it will cause some container services on these nodes to be inaccessible. In my kubernetes environment, when I restart the docker of some nodes, it will cause some container services on these nodes to be inaccessible.

![image](https://github.com/cilium/cilium/assets/80881214/2eb3af75-d966-4144-a783-589804b966d2)

![image](https://github.com/cilium/cilium/assets/80881214/ebf117ce-37e5-46b2-b19c-e0231ed2bb66)

After restarting docker, cilium did not generate ciliumendpoints for rccpdatabase-05e12e44-0644-5c10-ae78-8768463f5085-0

### Cilium Version

Client: 1.12.2 c7516b9 2022-09-14T15:25:06+02:00 go version go1.18.6 linux/amd64
Daemon: 1.12.2 c7516b9 2022-09-14T15:25:06+02:00 go version go1.18.6 linux/amd64

### Kernel Version

Linux 53d4f810-878d-5e80-88bb-36465ffba330 4.19.90-2107.6.0.0100.oe1.bclinux.x86_64 #1 SMP Wed Dec 1 19:59:44 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17", GitCommit:"8206683d1b72be8592759ce3d595efa3c7a568ec", GitTreeState:"clean", BuildDate:"2023-06-19T08:04:43Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17", GitCommit:"8206683d1b72be8592759ce3d595efa3c7a568ec", GitTreeState:"clean", BuildDate:"2023-06-19T08:04:33Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20230719-134737.zip](https://minio.lqingcloud.cn/public/cilium-sysdump-20230719-134737.zip)

### Relevant log output

```shell
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
Hi, Can you check if you are able to reproduce the issue with newer stable releases of cilium?

**Comment by QQGoblin** [comment]
Yes, I can reproduce this problem in the latest 1.12.11 version. I'm not sure if this issue is similar to the one mentioned in [[issues/17047](https://github.com/cilium/cilium/issues/17047)](https://github.com/cilium/cilium/issues/17047). 

 But I found that if I set the terminationGracePeriodSeconds property in the statefulset to 0 the problem occurs.

**Comment by QQGoblin** [comment]
> Hi, Can you check if you are able to reproduce the issue with newer stable releases of cilium?

Yes, I can reproduce this problem in the latest 1.12.11 version. I'm not sure if this issue is similar to the one mentioned in issues/17047.
But I found that if I set the terminationGracePeriodSeconds property in the statefulset to 0 the problem occurs.

**Comment by QQGoblin** [comment]
I ran the statefulset below for testing and pinned the pod to a specific node.
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    k8s-app: cep-statefulset
  name: cep-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cep-statefulset
  serviceName: cep-statefulset
  template:
    metadata:
      labels:
        k8s-app: cep-statefulset
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - image: traefik/whoami
        imagePullPolicy: IfNotPresent
        name: whoami
      nodeName: 78f20026-7cb7-5310-8ba4-586e361ae1cc
```
The problem can be reproduced by following steps:

1. When the container is in the running state, I shut down the docker service through systemctl stop docker.socket.
2. After waiting for a period of time, the container will enter the Pending state.
3. Start the docker service, and the container enters the running state again.
4. Check that the CiliumEndpoint corresponding to this container will disappear.
