### ISSUE TITLE
Problem with deploying both BGP Control Plane & Ingress with the helm `--wait` flag

### ISSUE THREAD

**Issue by vyas-n** [cilium/cilium#27000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I try to deploy the Cilium Helm chart into a k8s cluster using the `--wait` flag I have a chicken-and-egg problem with trying to enable both BGP Control Plane & Cilium Ingress.

Both of the keys to enable them are in the helm chart config:
```yaml
kubeProxyReplacement: strict
bgpControlPlane:
  enabled: true
ingressController:
  enabled: true
  loadbalancerMode: dedicated
```

But the BGP peering information is in a CRD
```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: 01-bgp-peering-policy
spec: # CiliumBGPPeeringPolicySpec
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: devzone-v2-wkr3
  virtualRouters: # []CiliumBGPVirtualRouter
    - localASN: <peering number>
      exportPodCIDR:  false
      serviceSelector:
        matchExpressions:
          - key: "somekey"
            operator: "NotIn"
            values: ["never-used-value"]
      neighbors: # []CiliumBGPNeighbor
        - peerAddress: "10.0.0.12/32"
          peerASN: <peering number>
        - peerAddress: "10.0.0.13/32"
          peerASN: <peering number>
```

Here's a graph showing the dependency loop:
```mermaid
graph TB
    subgraph HelmChart
        CRDs
        Loadbalancer --> Ingress
    end
    CRDs --> CiliumBGPPeeringPolicy --> Loadbalancer
```

So I can't apply the CiliumBGPPeeringPolicy Manifest until the Cilium Helm Chart is deployed, but I also can't deploy the Cilium Helm Chart because it can't launch the Loadbalancer that the default Ingress uses.

I'd like to be able to install Cilium with all of these features enabled using the Helm Chart.

I don't know of a way to do this, but some possible solutions:
- A method to install Cilium CRDs in a separate Helm Chart (this can enable me to apply the CRD before the Helm Chart
- A method to stop the Loadbalancer from deploying with the Helm Chart (so that I can deploy the Helm Chart successfully and provide the BGP information afterwards).
- A method to specify the CiliumBGPPeeringPolicy within the Helm Chart (so that Helm can handle the dependencies for these resources.

### Cilium Version

❯ cilium version
cilium-cli: v0.15.3 compiled with go1.20.6 on darwin/amd64
cilium image (default): v1.13.4
cilium image (stable): v1.13.4
cilium image (running): 1.13.4

Using Helm chart version: 1.13.4

### Kernel Version

Linux devzone-v2-wkr3 5.4.0-153-generic #170-Ubuntu SMP Fri Jun 16 13:43:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4+k0s", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-17T13:46:59Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

I don't think this is needed, but please tell me if it is and I can upload it.

### Relevant log output

```shell
I don't think this is needed, but let me know and I can upload it
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chancez** [comment]
> A method to stop the Loadbalancer from deploying with the Helm Chart (so that I can deploy the Helm Chart successfully and provide the BGP information afterwards).

As a temporary work around, try the following, I haven't tested it, but I think it will let you bypass this problem:

Configure `ingressController.service.type="nodePort"`. I can't remember if changing from nodePort -> loadBalancer is valid, but if it's not, I believe you should be able to delete the service, and then re-run helm upgrade after changing the type to `loadBalancer`.

I generally agree with your proposed ideas, though maybe we can use the CLI to install the CRDs.

**Comment by YutaroHayakawa** [comment]
Hi, thanks for your report!

> So I can't apply the CiliumBGPPeeringPolicy Manifest until the Cilium Helm Chart is deployed

I understand this part, but

> I also can't deploy the Cilium Helm Chart because it can't launch the Loadbalancer that the default Ingress uses

I don't understand this part.  Does this mean you are somehow relying on Ingress to bootstrap Cilium? I'm not an expert of Ingress use cases, so I think I'm missing something.

**Comment by vyas-n** [comment]
Hi @chancez & @YutaroHayakawa,

Thanks for your swift responses! 😄

> Does this mean you are somehow relying on Ingress to bootstrap Cilium?

Not really, just trying to enable the feature so that I can use Ingress in a dependent service. But when I enable the Ingress feature Cilium tries to setup a Loadbalancer. (I'm not sure why it does, but I'd be open to different ways to stop this Loadbalancer from starting since I don't need it to at this stage).

> Configure ingressController.service.type="nodePort"..., I believe you should be able to delete the service, and then re-run helm upgrade after changing the type to loadBalancer.

Thanks @chancez! I'm doing a similar mutation step to work around it for now (disabling ingress on first helm install, applying the BGP CRD, then helm applying the ingress).

I still want to keep this ticket open because I'm hoping to bootstrap my cluster without the mutation step.

**Comment by networkop** [comment]
@vyas-n you can set up a load-balancer _before_ you've got any `CiliumBGPPeeringPolicy` or even `CiliumLoadBalancerIPPool`. The load-balancer status would just remain `pending` until the IP is assigned from the pool. The BGP is not a dependency for the loadBalancer service either. BGP enables reachability for LB IPs but their lifecycle is completely independent.

**Comment by chancez** [comment]
@networkop the problem is the LB is being created by installing Cilium with the ingress feature enabled, and helm waits for all resources to be non-pending before the release is considered a success.

Cilium is installed and LB svc is created -- helm is waiting for the LB svc to be non-pending

At this point, the helm release is stuck until a CiliumBGPPeeringPolicy is configured. There's no way to pressed a `CiliumBGPPeeringPolicy` since the CRD isn't registered until the operator is installed. The operator is installed as part of the initial helm install, but if your using CI/etc, to deploy Cilium it will be stuck on the helm install and won't be able to proceed to creating the CiliumBGPPeeringPolicy.

**Comment by vyas-n** [comment]
@networkop True, but when deploying with helm. Helm blocks finishing the installation until the Loadbalancer is no longer in a `Pending` state

**Comment by networkop** [comment]
> Cilium is installed and LB svc is created -- helm is waiting for the LB svc to be non-pending

@chancez I thought this is the behavior if you use `--wait` flag? so without it, it should just deploy and return ( that's what I see at least)

I also think that LB SVC is dependent on the valid `CiliumLoadBalancerIPPool`, it should have no dependency on the `CiliumBGPPeeringPolicy `, which should still be a problem admittedly if helm waits

**Comment by vyas-n** [comment]
@networkop,

> I thought this is the behavior if you use --wait flag? so without it, it should just deploy and return

Thanks for pointing it out, I defaulted to using `--wait` as a way to check if the resources were deployed successfully, but removing that does workaround the dependency problem.

I still would like for one of the options I've mentioned before to be available in the long term. The `--wait` flag is really useful in checking for misconfigurations within Deployments & Integration Tests.

**Comment by networkop** [comment]
another option could be to run `helm template | kubectl apply -f -` but that's pretty much equivalent to `helm install` without `--wait`. 
Sadly, CRDs are managed by an operator, so normally you can't get them before you run a cilium-operator. You could, however, you what @chancez recommended above or:
* extract CRDs from a running cluster and apply them before you run `helm install`
* split `helm install` into two phases and only enable ingress in the second phase.
* use one of the gitops tools that would get you to your target state over a few reconciliation cycles.

**Comment by AndrStnz** [comment]
We are facing the "same" issue with rke2-cilium.
The cilium operator does not install the `CiliumBGPPeeringPolicy` CRD unless you uninstall it via HELM and reinstall it again.

This prevents us from enabling BGP with Cilium.

**Comment by wibed** [comment]
Bumping into this with talos aswell

**Comment by markormesher** [comment]
@AndrStnz @wibed I ran into the same issue today. If you restart the `cilium-operator` deployment, the CRDs will be created in your cluster.

**Comment by YutaroHayakawa** [comment]
Does anyone have a repro? When I test this with the [BGP Control Plane development environment](https://docs.cilium.io/en/latest/contributing/development/bgp_cplane/), I couldn't reproduce it. What I did was installing the Cilium with the instruction in the document with following modified Helm values.

```
routingMode: native

ipv6:
  enabled: true

bgpControlPlane:
  enabled: true

ipv4NativeRoutingCIDR: 10.0.0.0/8
ipv6NativeRoutingCIDR: fd00::/16

ipam:
  mode: kubernetes

k8s:
  requireIPv4PodCIDR: true
  requireIPv6PodCIDR: true

ingressController:
  enabled: true
  loadbalancerMode: dedicated

kubeProxyReplacement: strict
k8sServiceHost: <node IP>
k8sServicePort: 6443
```

With Helm's `--wait` option, it indeed starts to wait for the LB to become a non-pending state. However, I could see the Operator was already running at that point, so I could apply the following LBIPAM configuration.

```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "blue-pool"
spec:
  cidrs:
  - cidr: "10.0.10.0/24"
```

Then the operator assigned the VIP for the `cilium-ingress` service successfully, and Helm unblocked. There was no chicken and egg problem.

```
ks get svc
NAME             TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
cilium-ingress   LoadBalancer   10.2.102.154   10.0.10.215   80:32391/TCP,443:31307/TCP   8m48s
hubble-peer      ClusterIP      10.2.179.16    <none>        443/TCP                      8m48s
kube-dns         ClusterIP      10.2.0.10      <none>        53/UDP,53/TCP,9153/TCP       11m
```

I tested this with Cilium `v1.13.4`.

```
cilium version
cilium-cli: v0.15.23-53-g509702fb compiled with go1.22.0 on linux/amd64
cilium image (default): v1.15.1
cilium image (stable): v1.15.1
cilium image (running): 1.13.4
```
