### ISSUE TITLE
Cilium LRP causes deadlock on cilium-agent initialization

### ISSUE THREAD

**Issue by mhulscher** [cilium/cilium#27084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Original slack thread: https://cilium.slack.com/archives/C53TG4J4R/p1690295486904129

cilium-agent 1.14.0-rc.1 does not become ready when creating a new node in an existing EKS cluster. cilium-agent hangs for 3 minutes then restarts. However, during initial cluster creation with cilium, cilium does become ready. This leads me to believe that perhaps a manifest that was applied after cilium was installed is the culprit. Perhaps a CLRP, a CCNP, or something else.

This is a fresh installation; not an upgrade from a previous cilium version.

The sysdump was taken during  the 3 minute timeout, before cilium-agent restarted. The attached sysdump was collected with this command:

```
cilium sysdump --hubble-flows-count=0 --node-list ip-10-3-11-52.eu-west-1.compute.internal
```

The affected cilium pod is `cilium-xxf9n`. 

Installing cilium 1.13.4 with the same helm-values does not produce the same issue.

Helm values:

```
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: eks.amazonaws.com/compute-type
          operator: NotIn
          values:
          - fargate
agentNotReadyTaintKey: ignore-taint.cluster-autoscaler.kubernetes.io/cilium-not-ready
bpf:
  masquerade: false
  tproxy: true
cni:
  chainingMode: none
dnsProxy:
  endpointMaxIpPerHostname: 1000
  minTtl: 0
enableIPv4Masquerade: false
endpointHealthChecking:
  enabled: false
endpointStatus:
  enabled: true
  status: policy
eni:
  awsEnablePrefixDelegation: true
  ec2APIEndpoint: ec2.eu-west-1.amazonaws.com
  enabled: true
  eniTags: {}
  iamRole: arn:aws:iam::xxx:role/aio-a6uw-cilium-operator
  instanceTagsFilter: aws:eks:cluster-name=aio-a6uw
  updateEC2AdapterLimitViaAPI: true
extraConfig:
  api-rate-limit: |
    {"endpoint-create":"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true","endpoint-delete":"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true","endpoint-get":"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true","endpoint-list":"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true","endpoint-patch":"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true"}
healthChecking: false
hubble:
  enabled: true
  eventBufferCapacity: "8191"
  metrics:
    enableOpenMetrics: true
    enabled:
    - dns:query;labelsContext=source_namespace,source_workload
    - httpV2:exemplars=true;labelsContext=source_namespace,source_workload,source_app,destination_namespace,destination_workload,destination_app,traffic_direction
    serviceMonitor:
      enabled: true
      labels:
        system: "true"
  relay:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: k8s-app
              operator: In
              values:
              - hubble-relay
          topologyKey: topology.kubernetes.io/zone
    enabled: true
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
    replicas: 3
    resources:
      requests:
        cpu: 25m
    rollOutPods: true
    updateStrategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
  ui:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: k8s-app
              operator: In
              values:
              - hubble-ui
          topologyKey: topology.kubernetes.io/zone
    enabled: true
    ingress:
      className: ingress-nginx
      enabled: true
      hosts:
      - hubble.example.com
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
    replicas: 2
    resources:
      requests:
        cpu: 25m
    rollOutPods: true
    updateStrategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
ipam:
  mode: eni
k8sServiceHost: 89A9F0A0A873CD0391725073D30982C0.gr7.eu-west-1.eks.amazonaws.com
k8sServicePort: 443
kubeProxyReplacement: strict
l7Proxy: true
labels: k8s:!job-name k8s:!controller-uid
loadBalancer:
  serviceTopology: true
localRedirectPolicy: true
operator:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - cilium-operator
        topologyKey: topology.kubernetes.io/zone
  extraArgs:
  - --unmanaged-pod-watcher-interval=0
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
  priorityClassName: system-cluster-critical
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        system: "true"
  replicas: 2
  resources:
    requests:
      cpu: 25m
  rollOutPods: true
  tolerations:
  - key: node.kubernetes.io/not-ready
    operator: Exists
  - key: ignore-taint.cluster-autoscaler.kubernetes.io/cilium-not-ready
    operator: Exists
  - key: ignore-taint.cluster-autoscaler.kubernetes.io/dns-not-ready
    operator: Exists
pmtuDiscovery:
  enabled: true
policyEnforcementMode: default
priorityClassName: system-node-critical
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      system: "true"
resources:
  requests:
    cpu: 25m
svcSourceRangeCheck: "false"
tunnel: disabled
updateStrategy:
  type: OnDelete
```

### Cilium Version

1.14.0-rc.1

### Kernel Version

5.10.184-175.731.amzn2.aarch64

### Kubernetes Version

v1.26.6-eks-a5565ad

### Sysdump

[cilium-sysdump-20230726-134510.zip](https://github.com/cilium/cilium/files/12171965/cilium-sysdump-20230726-134510.zip)

### Relevant log output

```shell
cilium-xxf9n cilium-agent level=info msg="Iptables rules installed" subsys=iptables
cilium-xxf9n cilium-agent level=info msg="Adding new proxy port rules for cilium-dns-egress:21915" id=cilium-dns-egress subsys=proxy
cilium-xxf9n cilium-agent level=info msg="Iptables proxy rules installed" subsys=iptables
cilium-xxf9n cilium-agent level=info msg="Start hook executed" duration=7.216333696s function="cmd.newDaemonPromise.func1 (daemon_main.go:1646)" subsys=hive
cilium-xxf9n cilium-agent level=info msg="Start hook executed" duration="58.427µs" function="signal.provideSignalManager.func1 (cell.go:26)" subsys=hive
cilium-xxf9n cilium-agent level=info msg="Start hook executed" duration="674.383µs" function="auth.registerAuthManager.func1 (cell.go:106)" subsys=hive
cilium-xxf9n cilium-agent level=info msg="Start hook executed" duration="79.603µs" function="auth.registerGCJobs.func1 (cell.go:155)" subsys=hive
cilium-xxf9n cilium-agent level=info msg="Start hook executed" duration="6.728µs" function="*job.group.Start" subsys=hive
cilium-xxf9n cilium-agent level=info msg="Start hook executed" duration="11.487µs" function="utime.initUtimeSync.func1 (cell.go:34)" subsys=hive
cilium-xxf9n cilium-agent level=info msg="Start hook executed" duration="1.509µs" function="*job.group.Start" subsys=hive
cilium-xxf9n cilium-agent level=info msg="Start hook executed" duration="24.295µs" function="l2respondermap.newMap.func1 (l2_responder_map4.go:45)" subsys=hive
cilium-xxf9n cilium-agent level=info msg="Start hook executed" duration="2.256µs" function="*job.group.Start" subsys=hive
cilium-xxf9n cilium-agent level=info msg="Starting IP identity watcher" subsys=ipcache
cilium-xxf9n cilium-agent level=info msg="Initializing daemon" subsys=daemon
cilium-xxf9n cilium-agent level=info msg="Validating configured node address ranges" subsys=daemon
cilium-xxf9n cilium-agent level=info msg="Starting connection tracking garbage collector" subsys=daemon
cilium-xxf9n cilium-agent level=info msg="Initial scan of connection tracking completed" subsys=ct-gc
cilium-xxf9n cilium-agent level=info msg="Datapath signal listener running" subsys=signal
cilium-xxf9n cilium-agent level=error msg="Found two node IDs (0 and 34759) for the same node" ipAddr=10.1.118.92 nodeName=ip-10-1-231-113.eu-west-1.compute.internal subsys=linux-datapath
cilium-xxf9n cilium-agent level=fatal msg="Timed out waiting for pre-existing resources to be received; exiting" error="timed out after 3m0s, never received event for resource \"core/v1::Pods\"" subsys=k8s-watcher
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
