### ISSUE TITLE
CFP: Add PrometheusRules support to Helm chart

### ISSUE THREAD

**Issue by tongpu** [cilium/cilium#27113]
## Cilium Feature Proposal
        
**Is your proposed feature related to a problem?**

We recently faced the issue that we had to rotate our IPsec ahead of schedule and would have been happy for some recommended Prometheus alerting rules provided by the community.

**Describe the feature you'd like**

Add a set of community maintained  PrometheusRules to the Helm chart and allow the specification of custom rules via Helm chart values.

**Comment by youngnick** [comment]
Thanks for this issue @tongpu.

What sort of community rules are you looking for?

**Comment by sathieu** [comment]
Maybe an alert on `cilium_bpf_map_pressure` ?


NB: see closed PR https://github.com/cilium/cilium/pull/18560

**Comment by sathieu** [comment]
Example:

```yaml
name: CiliumBpfMapPressure
expr: (sum by (node, map_name) (cilium_bpf_map_pressure)) * 100 > 80
for: 1m
labels:
namespace: kube-system
severity: warning
annotations:
description: {{ printf "%.2f" $value }}% of Cilium map {{ $labels.map_name }} on node {{ $labels.node }} is filled
summary: Cilium map pressure is above 80%
```

and

```yaml
name: CiliumBpfMapPressure
expr: (sum by (node, map_name) (cilium_bpf_map_pressure)) * 100 > 95
for: 1m
labels:
namespace: kube-system
severity: critical
annotations:
description: {{ printf "%.2f" $value }}% of Cilium map {{ $labels.map_name }} on node {{ $labels.node }} is filled
summary: Cilium map pressure is above 95%
```
