### ISSUE TITLE
All of the remote-node ip’s are marked as world

### ISSUE THREAD

**Issue by kahirokunn** [cilium/cilium#27144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have enabled the following config and cnp, All of the remote-node ip’s are marked as world.

```yaml
enable-remote-node-identity: "true"
enable-well-known-identities: "true"
```

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  egress:
    - toEntities:
        - cluster
        - host
        - remote-node
    - toCIDR:
        - 169.254.169.254/32
    - toEndpoints:
        - matchLabels:
            'k8s:io.kubernetes.pod.namespace': kube-system
            'k8s:k8s-app': kube-dns
      toPorts:
        - ports:
            - port: '53'
              protocol: ANY
          rules:
            dns:
              - matchPattern: '*'
  endpointSelector:
    matchLabels:
      'k8s:io.cilium.k8s.policy.serviceaccount': metrics-server
```

### Cilium Version

Client: 1.13.4 4061cdfc 2023-06-14T03:37:39+00:00 go version go1.19.10 linux/arm64
Daemon: 1.13.4 4061cdfc 2023-06-14T03:37:39+00:00 go version go1.19.10 linux/arm64

### Kernel Version

Linux ip-10-0-68-131.ap-northeast-1.compute.internal 5.15.117 #1 SMP Thu Jul 6 03:51:44 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.3-eks-a5565ad", GitCommit:"78c8293d1c65e8a153bf3c03802ab9358c0e1a14", GitTreeState:"clean", BuildDate:"2023-06-16T17:32:40Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dylandreimerink** [comment]
Thanks for this report @kahirokunn, would you be able to grab a sysdump file and upload it please so we can better debug the issue? (Using https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection )?

**Comment by margamanterola** [comment]
@meyskens This sounds like the other issue you were investigating, doesn't it?

**Comment by christarazi** [comment]
@kahirokunn Are there any reproduction steps that you can provide?

**Comment by kahirokunn** [comment]
I am running with the following helm values.
Perhaps if we build a cilium with this, we can reproduce it.

```yaml
disableEnvoyVersionCheck: true
egressMasqueradeInterfaces: eth0
enable: true
enableIPv4Masquerade: false
endpointRoutes:
  enabled: true
endpointStatus:
  enabled: true
  status: policy health controllers log state
eni:
  awsEnablePrefixDelegation: true
  awsReleaseExcessIPs: true
  ec2APIEndpoint: ec2.ap-northeast-1.amazonaws.com
  enabled: true
  updateEC2AdapterLimitViaAPI: true
hostFirewall:
  enabled: true
enableIdentityMark: true
remoteNodeIdentity: true
wellKnownIdentities:
  enabled: true
hubble:
  metrics:
    enableOpenMetrics: true
    enabled:
    - drop
    - tcp
    - flow
    - flows-to-world
    - icmp
    - httpV2
    - port-distribution
  relay:
    enabled: true
    podDisruptionBudget:
      enabled: true
    prometheus:
      enabled: true
  rollOutPods: true
  ui:
    enabled: true
    podDisruptionBudget:
      enabled: true
ipam:
  mode: eni
k8sServiceHost: xxxx.yy.ap-northeast-1.eks.amazonaws.com
k8sServicePort: "443"
kubeProxyReplacement: strict
loadBalancer:
  algorithm: maglev
  mode: dsr
  serviceTopology: true
operator:
  podDisruptionBudget:
    enabled: true
  prometheus:
    enabled: true
  rollOutPods: true
priorityClassName: system-node-critical
prometheus:
  enabled: true
  metrics:
  - +cilium_bpf_syscall_duration_seconds
  - +cilium_bpf_map_pressure
  - +cilium_proxy_datapath_update_timeout_total
  - +cilium_fqdn_active_names
  - +cilium_fqdn_active_ips
  - +cilium_fqdn_alive_zombie_connections
  - +cilium_api_limiter_wait_history_duration_seconds
relay:
  rollOutPods: true
tunnel: disabled
```
