### ISSUE TITLE
1.14.0 - ExternalIPs on Services not working

### ISSUE THREAD

**Issue by spammads** [cilium/cilium#27151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Upgraded to 1.14.0.
Kube-Proxy replacement is enabled. Tunnel is disabled. Everything else is default-config.
Enabled externalIPs via:

```yaml
externalIPs:
  # -- Enable ExternalIPs service support.
  enabled: true
```

Added a service with:

```yaml
kind: Service
metadata:
  name: app
  namespace: default
spec:
  externalIPs:
  - 10.0.0.10
  ports:
  - name: http
    port: 9001
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: app
  type: ClusterIP
```

The App is not reachable. With 1.13.5 the exact same configuration works.
Appreciate your efforts. Great Cni.

### Cilium Version

1.14.0

### Kernel Version

6.1.41

### Kubernetes Version

1.27.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
