### ISSUE TITLE
Wrong port in cilium-envoy ServiceMonitor

### ISSUE THREAD

**Issue by pixiono** [cilium/cilium#27206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When installing the helmet chart with the following values, Envoy and a ServiceMonitor are deployed:
```
envoy:
  enabled: true
  image:
    repository: hdi-registry.we.decodeinsurance.de/tkp-mirror/cilium/cilium-envoy
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack-shared-dev-donkey
proxy:
  prometheus:
    enabled: true
```

However, the port of the ServiceMonitor does not match the port of the service:
- [ServiceMonitor: metrics](https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/cilium-envoy/servicemonitor.yaml#L25)
- [Service: envoy-metrics](https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/cilium-envoy/service.yaml#L23)

This leads to Prometheus not being able to scrape the metrics.

### Cilium Version

1.14.0

### Kernel Version

Not relevant

### Kubernetes Version

1.27

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
