### ISSUE TITLE
Valid CIDR Identities are getting released upon Cilium Agent restart

### ISSUE THREAD

**Issue by carnerito** [cilium/cilium#27210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have `CililiumClusterwideNetworkPolicy` deployed and Host Firewall enabled. Among other CCNPs that allow Cilium to function normally, I have CCNP that allows access from trusted subnets (private network, home VPN, etc...) and it looks like this:

````
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "whitelisted-cidrs"
spec:
  description: "Allow access from trusted CIDRs"
  nodeSelector:
    matchLabels: {}
  ingress:
  - fromCIDR:
    - "127.0.0.0/8"
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
    - "<trusted public ip>:32"
 ```` 

When this policy is applied for the first time everything works as expected. Problem occur 10 minutes after Cilium agent is restarted and is manifested by loosing connectivity to cluster from addresses defined in `whitelisted-cidrs` CCNP.

Since this is huge problem for me because I'm heavily relaying on Cilium Host Firewall feature, I did some investigation and these are my findings:
- Identities associated with CIDRs in `fromCIDR` list are cleared 10 minutes after Cilium agent starts
- [This part of code is responsible for 10 minutes delay](https://github.com/cilium/cilium/blob/b5013e1562dbfe442dd2011a5af46de9095315ff/daemon/cmd/daemon_main.go#L1757-L1771)
- What actually releases Identity is [localIdentityCache release function](https://github.com/cilium/cilium/blob/b5013e1562dbfe442dd2011a5af46de9095315ff/pkg/identity/cache/local.go#L122-L151)
- It releases Identity if refcount for provided Identity is equal to 1
- In Cilium versions prior to v1.14.0 this function is called only once, and it's called from that delayed goroutine from second bullet point, [here](https://github.com/cilium/cilium/blob/b5013e1562dbfe442dd2011a5af46de9095315ff/daemon/cmd/daemon_main.go#L1768)
- This call does not cause Identity to be released because at that point, refcount for given Identity is 2, as it is increased [here](https://github.com/cilium/cilium/blob/b5013e1562dbfe442dd2011a5af46de9095315ff/pkg/identity/cache/local.go#L88-L91) beforehand
- Difference between v1.14.0 and v.1.13.4 is that in v.1.14 release function is called once more when refcount is 1 which causes given Identity to be released which makes cluster unavailable
- Release function is called second time from ipcache.InjectLabels, [here](https://github.com/cilium/cilium/blob/b5013e1562dbfe442dd2011a5af46de9095315ff/pkg/ipcache/metadata.go#L332)
- Reason for this is changed logic inside `releaseIdentity` block, [here](https://github.com/cilium/cilium/blob/b5013e1562dbfe442dd2011a5af46de9095315ff/pkg/ipcache/metadata.go#L266-L284)
- This change is introduced in [this commit](https://github.com/cilium/cilium/commit/c96b9d81a8a679d77f9929e6ed32559a3d54108d)

After I figured out what is happening, I reverted logic in `releaseIdentity` to look like this:
```
	releaseIdentity:
		if entryExists {
			// ...
			if _, ok := idsToAdd[oldID.ID]; !
				previouslyAllocatedIdentities[prefix] = oldID
			}

			// ...
			if prefixInfo == nil && oldID.createdFromMetadata {
				entriesToDelete[prefix] = oldID
			}
		}
```

This change solved the issue, but since I'm new to Cilium code base, I'm not sure will this have some unwanted side effects. If this change looks good, I can submit PR.

### How to reproduce in local Kind cluster
- Checkout Cilium v1.14.0 tag
- Add following snippet to kind-values.yaml: 

````
extraArgs:
  - '--identity-restore-grace-period'
  - '2m'
hostFirewall:
  enabled: "true"
````
- Run `make kind && make kind-image && make kind-install-cilium`
- Apply CCNP with `fromCIDR` rule (like one from above)
- Restart Cilium Agent
- Wait for 2 minutes
- Cluster should become unavailable since fromCIDR identities are released

### Cilium Version

v1.14.0

### Kernel Version

.

### Kubernetes Version

v1.27.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kimma** [comment]
Chiming in to say i'm having the same problems.
Looks like any use of fromCIDR or toCIDR is impossible due to this.

The following network policy:
```
    - fromCIDR:
        - 10.0.0.0/8
        - 192.168.0.0/16
        - 2a0e:97c0:250::/44
        - 2a02:2c8:f000::/48
        - fd00::/8
      toPorts:
        - ports:
          - port: "8443"
            protocol: TCP
          - port: "8000"
            protocol: TCP
```

Should allow the following traffic, (and has worked flawlessly until upgrade) but it is now denied.
```
Ethernet	{Contents=[..14..] Payload=[..50..] SrcMAC=b6:6a:89:17:4f:7a DstMAC=ae:9d:38:b9:4a:77 EthernetType=IPv4 Length=0}
IPv4	{Contents=[..20..] Payload=[..28..] Version=4 IHL=5 TOS=0 Length=48 Id=0 Flags=DF FragOffset=0 TTL=61 Protocol=TCP Checksum=60901 SrcIP=10.12.123.10 DstIP=10.12.192.192 Options=[] Padding=[]}
TCP	{Contents=[..28..] Payload=[] SrcPort=53009 DstPort=8443(pcsync-https) Seq=3964054339 Ack=0 DataOffset=7 FIN=false SYN=true RST=false PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=65535 Checksum=44278 Urgent=0 Options=[TCPOption(MSS:1380 0x0564), TCPOption(SACKPermitted:), TCPOption(EndList:)] Padding=[0]}
CPU 08: MARK 0xc881a88a FROM 3257 DROP: 62 bytes, reason Policy denied, identity 16777228->136429, to endpoint 3257
```
