### ISSUE TITLE
Big packets dropped on Enabled encryption with K8s 1.23 using official AWS Docs

### ISSUE THREAD

**Issue by Alexlugovtsov** [cilium/cilium#27227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Trying to enable Encryption by wireguard in Amazon AWS EKS Cluster 1.23 with Cilium using  AWS Article
[Transparent encryption of node to node traffic on Amazon EKS using WireGuard and Cilium](https://aws.amazon.com/blogs/containers/transparent-encryption-of-node-to-node-traffic-on-amazon-eks-using-wireguard-and-cilium/)
When wireguard encryption is enabled, big packets (above 8K) stops to flow, before one small packet is transmitted, 
ones it did, big packets starts to flow, but before the connection is closed, after the connection is closed - big packets stops to flow again.

This is not working scenario for Big packets (8K and above) to pass:
```
helm install cilium cilium/cilium --version 1.13.5 \
  --namespace kube-system \
  --set cni.chainingMode=aws-cni \
  --set enableIPv4Masquerade=false \
  --set tunnel=disabled \
  --set endpointRoutes.enabled=true \
  --set encryption.enabled=true \
  --set encryption.type=wireguard \
  --set l7Proxy=false 
```

When try to install without cni.chainingMode DNS resolution stops working
```
encryption:
  enabled: true
  type: wireguard
hubble:
  relay:
    enabled: true
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
    - 192.168.0.0/16
operator:
  prometheus:
    enabled: true
prometheus:
  enabled: true
```

### Cilium Version

1.13.4/5 and 1.14.0

### Kernel Version

5.10.184

### Kubernetes Version

1.23

### Sysdump

[cilium-sysdump-20230803-184847.zip](https://github.com/cilium/cilium/files/12254378/cilium-sysdump-20230803-184847.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
