### ISSUE TITLE
ipam.operator.clusterPoolIPv4PodCIDRList custom value ignored in 1.14.0

### ISSUE THREAD

**Issue by Alexlugovtsov** [cilium/cilium#27245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when ipam.operator.clusterPoolIPv4PodCIDRList is set to any custom value 
the value is placed inside cilium-config, 
but not used in cilium pods
```
encryption:
  enabled: true
  type: wireguard
hubble:
  relay:
    enabled: true
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
    - 192.168.0.0/16
operator:
  prometheus:
    enabled: true
prometheus:
  enabled: true
```

### Cilium Version

1.14.0

### Kernel Version

5.15.117

### Kubernetes Version

1.27

### Sysdump

[cilium-sysdump-20230803-104507.zip](https://github.com/cilium/cilium/files/12249924/cilium-sysdump-20230803-104507.zip)

### Relevant log output

```shell
level=info msg="Restored router address from node_config" file=/var/run/cilium/state/globals/node_config.h ipv4=10.221.239.9 ipv6="<nil>" subsys=node
level=info msg="Initializing node addressing" subsys=daemon
level=info msg="Initializing cluster-pool IPAM" subsys=ipam v4Prefix=10.221.0.0/16 v6Prefix="<nil>"
```

### Anything else?

config is OK:
<img width="306" alt="image" src="https://github.com/cilium/cilium/assets/65892915/f1969781-becf-40b4-b221-1b1121cf46e1">

<img width="1110" alt="Screenshot 2023-08-03 at 13 51 48" src="https://github.com/cilium/cilium/assets/65892915/784c23c9-32f8-4989-b2e6-53253258b2f1">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
