### ISSUE TITLE
Preflight daemonset with wrong tolerations

### ISSUE THREAD

**Issue by ddellarocca** [cilium/cilium#27317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

By default the tolerations set for the preflight checks are:
```yaml
  tolerations:
    - key: node.kubernetes.io/not-ready
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
    - key: node.cloudprovider.kubernetes.io/uninitialized
      effect: NoSchedule
      value: "true"
    - key: CriticalAddonsOnly
      operator: "Exists"
```

Which are good but not enough, in particular if some nodes have a taint those won't be subject to the preflight check, the cilium daemonset have the following toleration:

```yaml
  tolerations:
  - operator: Exists
```

Which is more reasonable.

### Cilium Version

n/a

### Kernel Version

n/a

### Kubernetes Version

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
