### ISSUE TITLE
Upgrade to 13.5 chart requires kubeProxyReplacement 

### ISSUE THREAD

**Issue by ddellarocca** [cilium/cilium#27344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In GKE we installed Cilium with the initial version 1.11, so we had the following file containing our values:
```yaml
nodeinit:
  enabled: true
  reconfigureKubelet: true
  removeCbrBridge: true

cni:
  binPath: /home/kubernetes/bin

gke:
  enabled: true

ipam:
  mode: kubernetes

ipv4NativeRoutingCIDR: 10.5.64.0/18
upgradeCompatibility: "1.11"
```
We gradually upgraded cilium over time but we faced the following error upgrading from `1.12.12` to `1.13.5`:
```
Error: UPGRADE FAILED: execution error at (cilium/templates/cilium-configmap.yaml:58:5): kubeproxyReplacement must be explicitly set to a valid value (disabled, partial, or strict) to continue.
```
The problem comes from this statement: https://github.com/cilium/cilium/blob/9e29ea6f74af1e89866f224ec76013d6c0ba1fd5/install/kubernetes/cilium/templates/cilium-configmap.yaml#L35 which sets `$defaultKubeProxyReplacement` to an invalid value for `1.13`.
We set `kubeProxyReplacement: "disabled"`to continue with the update, since we are in a cluster with kube-proxy and it is the default value from 1.12, but it is not specified [here](https://docs.cilium.io/en/v1.13/operations/upgrade/#removed-options).

I think the error message and the docs can be improved for the users that fall in our use case.

### Cilium Version

n/a

### Kernel Version

n/a

### Kubernetes Version

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
