### ISSUE TITLE
CiliumNetworkPolicy blocks traffic forwarded between nodes in v1.14.0

### ISSUE THREAD

**Issue by scrayos** [cilium/cilium#27360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have previously run Cilium 1.11.19 with the same CiliumNetworkPolicy and it was running just fine. After upgrading to 1.13.x or now 1.14.0, node-to-node traffic was getting denied. We have a NodePort-Service running and load balance between the nodes through DNS Round-Robin. Only the connections that are assigned to the node which currently hosts the service can pass through. Every connection attempt that requires one node to forward the traffic to the other node is denied because of the policy. This was not the case in 1.11.19.

![image](https://github.com/cilium/cilium/assets/2124642/70e36c32-5d31-4b1e-b4d1-5c6b2ea3e2c5)

Once I drop this policy, everything works as expected again (but now everyone can reach the port as well).

### Cilium Version

v1.14.0

### Kernel Version

6.1.30-talos

### Kubernetes Version

1.27.4

### Anything else?

The cluster is running on Talos Linux through Helm with this values:

```yaml
bpf:
  masquerade: true
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
ipam:
  mode: kubernetes
k8sServiceHost: control.example.com
k8sServicePort: 6443
kubeProxyReplacement: true
securityContext:
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
upgradeCompatibility: "1.11"
```

The policy in question:

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: minecraft
  namespace: minecraft
spec:
  endpointSelector:
    matchLabels:
      agones.dev/role: gameserver
  ingress:
  - fromEndpoints:
    - {}
  - fromEntities:
    - cluster
  - fromCIDRSet:
    - cidr: x.x.x.x/32
    toPorts:
    - ports:
      - port: '25565'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
