### ISSUE TITLE
How do I use the service-based NetworkPolicy?

### ISSUE THREAD

**Issue by nkawaa** [cilium/cilium#27364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to allow communication between Pod and Service using a service-based NetworkPolicy.
but I can't.
what should I do?

![expected](https://github.com/cilium/cilium/assets/18389115/0b94402e-c3c0-4814-836a-5b316da205b4)

- I think there are two stumbling points.I would like to know what NetworkPolicy I should create for each of them...
  - When querying the DNS
  - When connecting to a resolved IP
- I have already read this page <https://docs.cilium.io/en/stable/security/policy/language/#services-based>

### Cilium Version

```basj
Client: 1.13.4 4061cdfc 2023-06-14T03:37:39+00:00 go version go1.19.10 linux/amd64
Daemon: 1.13.4 4061cdfc 2023-06-14T03:37:39+00:00 go version go1.19.10 linux/amd64
```

#### Cilium Installation Procedure

```bash
$ helm install --namespace kube-system cilium cilium/cilium --version 1.13.4 --set autoDirectNodeRoutes=true,bandwidthManager.enabled=true,cluster.id=0,cluster.name=kubernetes,encryption.nodeEncryption=false,ipv4NativeRoutingCIDR=172.20.148.1/22,k8sServiceHost=172.20.148.223,k8sServicePort=6443,kubeProxyReplacement=strict,operator.replicas=1,serviceAccounts.cilium.name=cilium,serviceAccounts.operator.name=cilium-operator,tunnel=disabled,hubble.relay.enabled=true,hubble.ui.enabled=true
```

### Kernel Version

Red Hat Enterprise Linux release 9.2 (Plow)
5.14.0-284.18.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Wed May 31 10:39:18 EDT 2023

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:28Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
```

#### kubernetes Installation Procedure

```bash
$ kubeadm init --config /work/kubeadm_no-kube-proxy-config.yaml --upload-certs 2>&1 | tee /work/k8s-install.log
```

```bash
$ vi kubeadm_no-kube-proxy-config.yaml
```

```yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
kubernetesVersion: v1.27.2
skipPhases:
  - addon/kube-proxy
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.27.2
apiServer:
  advertise-address: 172.20.148.221
  extraArgs:
    audit-policy-file: /etc/kubernetes/audit/policy.yaml
    audit-log-path: /var/log/kubernetes/kube-apiserver-audit.log
    audit-log-maxage: "7"
    audit-log-maxsize: "200"
  extraVolumes:
    - name: audit-policy
      hostPath: /etc/kubernetes/audit
      mountPath: /etc/kubernetes/audit
      pathType: DirectoryOrCreate
    - name: "audit-log"
      hostPath: /var/log/kubernetes
      mountPath: /var/log/kubernetes
      pathType: DirectoryOrCreate
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
```

#### red deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
  labels:
    color: red
spec:
  replicas: 1
  selector:
    matchLabels:
      color: red
  template:
    metadata:
      labels:
        color: red
    spec:
      containers:
      - name: red
        image: nginx:stable
        ports:
        - containerPort: 80
        stdin: true
        tty: true
```

#### podman container creation procedure

```bash
$ podman run -itd --name httpd -p 8080:80 docker.io/library/httpd
```

#### podman service and endpoint slice

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: podman-httpd
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: podman-httpd-slice
  labels:
    kubernetes.io/service-name: podman-httpd
addressType: IPv4
ports:
  - name: ''
    appProtocol: http
    protocol: TCP
    port: 8080
endpoints:
  - addresses:
      - "172.20.148.221"
---

```

#### Checking connections when NetworkPolicy is not yet in place

```bash
$ kubectl exec -it red-86857846b8-hg8tr bash
root@red-86857846b8-hg8tr:/# curl podman-httpd:8080
<html><body><h1>It works!</h1></body></html>
```

#### Cilium NetworkPolicy (It's not working)

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "service-based"
spec:
  endpointSelector:
    matchLabels:
      color: red
  egress:
  - toServices:
    - k8sService:
        serviceName: podman-httpd
    - k8sServiceSelector:
        selector:
          matchLabels:
            k8s-app: kube-dns
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by odinuge** [comment]
Hi,

This is most likely because you are not allowed to do DNS lookups. You can try connecting to the service IP directly, or even directly to `172.20.148.221`.

Your rule to allow access to `kube-dns` does not work as `.toServices` rules only applies to endpoints that are _not_ pods running in k8s; and I assume you run `kube-dns` as a pod.

**Comment by nkawaa** [comment]
thank you for your reply !! 

> I assume you run kube-dns as a pod.

Yes, you are right.

I have configured Networkpolicy as you suggested and DNS name resolution is now working. Thank you.
(I am checking with tcpdump).

However, I still can't seem to connect to the Podman container. What else should I fix?

My current NetworkPolicy is below

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-dns"
spec:
  endpointSelector:
    matchLabels:
      color: red
  egress:
    - toEndpoints:
      - matchLabels:
          "k8s:k8s-app": kube-dns
          "k8s:io.kubernetes.pod.namespace": kube-system
      toPorts:
        - ports:
          - port: "53"
            protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
----
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "service-based"
spec:
  endpointSelector:
    matchLabels:
      color: red
  egress:
  - toServices:
    - k8sService:
        serviceName: podman-httpd
```
