### ISSUE TITLE
GatewayClass ('io.cilium/gateway-controller') is not created despite `gatewayAPI.enabled: true`

### ISSUE THREAD

**Issue by James-Riordan** [cilium/cilium#27398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm installing Cilium via Helm Chart onto a KinD local cluster on a Mac.

I have pre-installed the relevant gateway CRDs (v0.7.1, although official documentation recommends v0.7.0) before installing Cilium via Helm Chart. Based on the Chart's templates, I see that the GatewayClass template is as follows, and should be installed as long as `gatewayAPI.enabled: true`:

```YAML
{{- if .Values.gatewayAPI.enabled -}}
{{- if .Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1beta1/GatewayClass" }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: cilium
spec:
  controllerName: io.cilium/gateway-controller
{{- end}}
{{- end}}
```

When I run `kubectl get gatewayclass`, nothing shows up. When I manually define the very same `GatewayClass`, everything runs just fine. I simply don't understand why the Helm Chart isn't installing the `GatewayClass` itself.

It may or may not have to do with the `{{- if .Values.gatewayAPI.enabled -}}` field, and the fact that I'm using `v0.7.1`. Either way, this is a bug that should be resolved.

### Cilium Version

Cilium: v1.14.0 
Gateway CRDs: v0.7.1

### Kernel Version

Darwin Kernel Version 22.5.0 | RELEASE_X86_64 x86_64

### Kubernetes Version

1.27.2

### Sysdump

🔍 Collecting sysdump with cilium-cli version: v0.15.0, args: [sysdump]
🔮 Detected Cilium installation in namespace "kube-system"
🔮 Detected Cilium operator in namespace "kube-system"
ℹ️ Failed to detect Cilium SPIRE installation - using Cilium namespace as Cilium SPIRE namespace: kube-system
🔍 Collecting Kubernetes nodes
🔍 Collect Kubernetes nodes
🔍 Collecting Kubernetes events
🔍 Collecting Kubernetes pods
🔍 Collect Kubernetes version
🔍 Collecting Kubernetes pods summary
🔍 Collecting Kubernetes namespaces
🔍 Collecting Kubernetes services
🔍 Collecting Kubernetes endpoints
🔍 Collecting Kubernetes network policies
🔍 Collecting Kubernetes leases
🔍 Collecting Cilium network policies
🔍 Collecting Cilium egress NAT policies
🔍 Collecting Cilium cluster-wide network policies
🔍 Collecting Cilium CIDR Groups
🔍 Collecting Cilium Egress Gateway policies
🔍 Collecting Cilium endpoints
🔍 Collecting Cilium local redirect policies
🔍 Collecting Cilium identities
🔍 Collecting Cilium endpoint slices
🔍 Collecting Cilium Node Configs
🔍 Collecting Cilium nodes
🔍 Collecting Ingresses
🔍 Collecting IngressClasses
🔍 Collecting CiliumClusterwideEnvoyConfigs
🔍 Collecting CiliumEnvoyConfigs
🔍 Collecting Cilium BGP Peering Policies
🔍 Collecting Cilium LoadBalancer IP Pools
🔍 Collecting Cilium Pod IP Pools
🔍 Checking if cilium-etcd-secrets exists in kube-system namespace
🔍 Collecting the Cilium configuration
🔍 Collecting the Cilium daemonset(s)
🔍 Collecting the Cilium Envoy configuration
🔍 Collecting the Cilium Envoy daemonset
🔍 Collecting the Hubble daemonset
🔍 Collecting the Hubble Relay configuration
⚠️ Daemonset "cilium-envoy" not found in namespace "kube-system" - this is expected if Envoy DaemonSet is not enabled
🔍 Collecting the Hubble Relay deployment
🔍 Collecting the Hubble UI deployment
🔍 Collecting the Cilium operator deployment
🔍 Collecting the 'clustermesh-apiserver' deployment
🔍 Collecting the CNI configuration files from Cilium pods
🔍 Collecting the CNI configmap
🔍 Collecting gops stats from Cilium pods
🔍 Collecting gops stats from Hubble pods
🔍 Collecting gops stats from Hubble Relay pods
🔍 Collecting bugtool output from Cilium pods
⚠️ Deployment "clustermesh-apiserver" not found in namespace "kube-system" - this is expected if 'clustermesh-apiserver' isn't enabled
🔍 Collecting profiling data from Cilium pods
🔍 Collecting logs from Cilium pods
🔍 Collecting logs from Cilium Envoy pods
🔍 Collecting logs from Cilium operator pods
🔍 Collecting logs from 'clustermesh-apiserver' pods
🔍 Collecting logs from Hubble pods
🔍 Collecting logs from Hubble Relay pods
🔍 Collecting logs from Hubble UI pods
🔍 Collecting bugtool output from Tetragon pods
🔍 Collecting logs from Cilium SPIRE server pods
🔍 Collecting logs from Cilium SPIRE agent pods
🔍 Collecting the Cilium SPIRE server statefulset
⚠️ StatefulSet "spire-server" not found in namespace "kube-system" - this is expected if SPIRE installation is not enabled
🔍 Collecting the Cilium SPIRE agent daemonset
Secret "cilium-etcd-secrets" not found in namespace "kube-system" - this is expected when using the CRD KVStore
🔍 Collecting the Cilium SPIRE agent configuration
⚠️ Daemonset "spire-agent" not found in namespace "kube-system" - this is expected if SPIRE installation is not enabled
🔍 Collecting the Cilium SPIRE server configuration
🔍 Collecting platform-specific data
🔍 Collecting kvstore data
🔍 Collecting Tetragon tracing policies
🔍 Collecting Cilium external workloads
🔍 Collecting GatewayClass entries
🔍 Collecting Gateway entries
🔍 Collecting ReferenceGrant entries
🔍 Collecting HTTPRoute entries
🔍 Collecting TLSRoute entries
🔍 Collecting GRPCRoute entries
🔍 Collecting TCPRoute entries
🔍 Collecting UDPRoute entries
🔍 Collecting Hubble flows from Cilium pods
I0809 13:59:49.689988   23291 request.go:696] Waited for 1.127942738s due to client-side throttling, not priority and fairness, request: GET:https://127.0.0.1:6443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dcilium
⚠️ ConfigMap "spire-agent" not found in namespace "kube-system" - this is expected if SPIRE installation is not enabled
⚠️ ConfigMap "spire-server" not found in namespace "kube-system" - this is expected if SPIRE installation is not enabled
I0809 13:59:59.889621   23291 request.go:696] Waited for 2.392460372s due to client-side throttling, not priority and fairness, request: GET:https://127.0.0.1:6443/api/v1/namespaces/kube-system/pods/cilium-x6g9h/log?container=apply-sysctl-overwrites&limitBytes=1073741824&sinceTime=2022-08-09T17%3A59%3A51Z&timestamps=true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by uablrek** [comment]
Got the same, and this in cilium-operator logs:
```
level=fatal msg="Failed to create gateway controller" error="no matches for kind \"TLSRoute\" in version \"gateway.networking.k8s.io/v1alpha2\"" subsys=gateway-controller
```
Perhaps we really should use v0.7.0?

**Comment by xtineskim** [comment]
hi @James-Riordan ! Do you recall the helm command that you used to install cilium?

**Comment by AnthonyPoschen** [comment]
i get the same issue @xtineskim 

```sh
	helm template cilium cilium/cilium --version 1.14.2 \
		--namespace kube-system \
		--set kubeProxyReplacement=true \
		--set gatewayAPI.enabled=true \
		--set bandwidthManager.bbr=true \
		--set bandwidthManager.enabled=true \
	        --set hubble.relay.enabled=true \
	        --set hubble.ui.enabled=true \
		--set priorityClassName=system-node-critical \
		--set ingressController.enabled=true \
		--set ingressController.loadbalancerMode=shared \
		--set loadBalancer.l7.backend=envoy \
		--set bgp.enabled=true \
		--set bgpControlPlane.enabled=true \
		--set ipam.mode=kubernetes \
		--set bpfClockProbe=true
```

**Comment by sayboras** [comment]
This is mainly the issue with `helm template` command, but not about Cilium chart. 

As far as I remembered, `helm template` didn't check the Capabilities from cluster, so you might need to pass extra flag --api-versions to obtain equivalent result as `helm install`.

**Comment by sayboras** [comment]
I am closing this issue, feel free to reopen if you think otherwise. Thanks.

**Comment by zimmertr** [comment]
@sayboras Do you know which specific `--api-versions` need to be included? The following doesn't produce a GatewayClass using Kustomize. Which is just `helm template` under the hood.

```yaml
resources:
  - resources/namespace.yml
  - resources/cilium_load_balancer_ip_pool.yml
  # https://docs.cilium.io/en/latest/network/servicemesh/gateway-api/gateway-api/#prerequisites
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.8.1/experimental-install.yaml

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    version: 1.15.0-pre.1 # https://artifacthub.io/packages/helm/cilium/cilium
    releaseName: cilium
    namespace: kube-system
    valuesFile: values.yml
    includeCRDs: true
    apiVersions:
      - gateway.networking.k8s.io/v1beta1
```
