### ISSUE TITLE
CiliumLocalRedirectPolicy causing lb4_services_v2 map sync errors 

### ISSUE THREAD

**Issue by ghost** [cilium/cilium#27410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We use deamonset to deploy coredns on every node (change from deployment to deamonset), and use LocalRedirectRule to redirect dns request to service to the local coredns pods. However, pods on one of the nodes cannot resolve dns with the service, with the pod IP it works well.

The log of agent on abnormal node shows  something like this: 
```
level=warning msg="Unable to delete service entry from BPF map" backendSlot=2 error="unable to delete element 172.16.0.10:53 from map cilium_lb4_services_v2: no such file or directory" subsys-map-lb svcKey="172.16.0.10:12568"
```
There are a lot of `Error while inserting service in LB map .. local-redirect services exists ... skip update for svc ...` errors for both normal and abnormal nodes.

Besides, `cilium status` gives that
```
Name                                       Last success       Last error        Count           Message
bpf-map-sync-cilium_lb4_services_v2         never             11m51s ago          1161           5 map sync errors
```

`cilium map get cilium_lb4_services_v2` shows no error

After checking and comparing the eBPF map of LB service, we found that the 0.0.0.0 [LocalRedirect] is absent in the node with problem. After manually adding this backend with bpftool, the problem is fixed. So I wonder that maybe there is a bug in this part.

`cilium bpf lb list | grep 172.16.0.10:53 -A 2`   
before adding:

```
172.16.0.10:53     172.40.128.51:53  (16192) (1)
```

after adding
```
172.16.0.10:53     0.0.0.0:0  (16192)  (0)  [LocalRedirect]
                   172.40.128.51:53  (16192) (1)
```

local redirect policy yaml:
```yaml
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: kube-dns-service
  namespace: kube-system
spec:
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: kube-dns
    toPorts:
    - name: dns-udp
      port: "53"
      protocol: UDP
    - name: dns-tcp
      port: "53"
      protocol: TCP
  redirectFrontend:
    serviceMatcher:
      namespace: kube-system
      serviceName: kube-dns
```

Note that this serviceMatcher not only the new daemonset, but also match the old deployment. The procedure of our operation is: 1. create daemonset  2. create local redirect rule 3. delete deployment.  **We find that the problem node is the one who runs the pod of old deployment.**

### Cilium Version

v1.11.17

### Kernel Version

5.10

### Kubernetes Version

1.24.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
