### ISSUE TITLE
Gateway API on EKS not working as expected

### ISSUE THREAD

**Issue by Smana** [cilium/cilium#27493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm not able to configure the gateway.

My Cilium configuration seems ok:
```console
cilium-cli config view | grep -w "enable-gateway-api"
enable-gateway-api                                true
enable-gateway-api-secrets-sync                   true
```

I followed [this guide](https://docs.cilium.io/en/latest/network/servicemesh/gateway-api/http/) and when I create the gateway along with the httproute it creates a loadbalancer:

```console
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/kubernetes/gateway/basic-http.yaml
gateway.gateway.networking.k8s.io/my-gateway created
httproute.gateway.networking.k8s.io/http-app-1 created

kubectl get svc
NAME                        TYPE           CLUSTER-IP       EXTERNAL-IP                                                                    PORT(S)        AGE
cilium-gateway-my-gateway   LoadBalancer   172.20.100.22    k8s-default-ciliumga-fa85db4e7d-83a59527c5457ff3.elb.eu-west-3.amazonaws.com   80:30311/TCP   4s
```

The HTTP route seems to be properly configured:

```console
kubectl describe httproutes.gateway.networking.k8s.io http-app-1 | grep -A20 'Status:'
Status:
  Parents:
    Conditions:
      Last Transition Time:  2023-08-15T08:32:55Z
      Message:               Service reference is valid
      Observed Generation:   1
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
      Last Transition Time:  2023-08-15T08:32:55Z
      Message:               Accepted HTTPRoute
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
    Controller Name:         io.cilium/gateway-controller
    Parent Ref:
      Group:      gateway.networking.k8s.io
      Kind:       Gateway
      Name:       my-gateway
      Namespace:  default
Events:           <none>
```

However, the gateway never gets ready:
```console
Status:
  Conditions:
    Last Transition Time:  2023-08-14T16:22:53Z
    Message:               Unable to create Service resource
    Observed Generation:   1
    Reason:                NoResources
    Status:                False
    Type:                  Accepted
    Last Transition Time:  2023-08-14T16:22:53Z
    Message:               Address is not ready
    Observed Generation:   1
    Reason:                ListenersNotReady
    Status:                False
    Type:                  Programmed
  Listeners:
    Attached Routes:  1
    Conditions:
      Last Transition Time:  2023-08-14T16:22:53Z
      Message:               Listener Programmed
      Observed Generation:   1
      Reason:                Programmed
      Status:                True
      Type:                  Programmed
      Last Transition Time:  2023-08-14T16:22:53Z
      Message:               Listener Accepted
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
    Name:                    web-gw
    Supported Kinds:
      Group:  gateway.networking.k8s.io
      Kind:   HTTPRoute
```

Even though the curl command reaches the envoy service, it returns a 404:

```console
curl --fail -s http://15.188.175.188/details/1 -vvv
* processing: http://15.188.175.188/details/1
*   Trying 15.188.175.188:80...
* Connected to 15.188.175.188 (15.188.175.188) port 80
> GET /details/1 HTTP/1.1
> Host: 15.188.175.188
> User-Agent: curl/8.2.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< date: Mon, 14 Aug 2023 16:36:18 GMT
< server: envoy
< content-length: 0
* The requested URL returned error: 404
* Closing connection
```

Am I missing something on EKS? Note that I'm using a Kyverno [workaround](https://github.com/Smana/cilium-gateway-api/blob/main/security/mycluster-0/custom-resources/echo-clusterpolicy.yaml) to set the annotations properly.

### Cilium Version

1.14.0

### Kernel Version

I'm not able to ssh to the instance right now but it's the latest bottlerocket AMI. I'll try to enable SSM.

### Kubernetes Version

1.27

### Sysdump

[cilium-sysdump-20230814-183832.zip](https://github.com/cilium/cilium/files/12337440/cilium-sysdump-20230814-183832.zip)

### Anything else?

I'm writing a blog post about Cilium with Gateway API on EKS. My code is [here](https://github.com/Smana/cilium-gateway-api) if you want to look at it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Smana** [comment]
I just tried again in order to try that with Amazon LInux instances (kernel version: 5.10.184-175.749.amzn2.x86_64). I got exactly the same behavior. The gateway is not properly configured, the status Programmed=False.

**Comment by sergeyshevch** [comment]
Same behaviour. Created dupe issue for this. Here is a resources

Gateway with status
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: rest-external
spec:
  gatewayClassName: cilium
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '*.myhost'
      name: web-gw
      port: 443
      protocol: HTTP
status:
  conditions:
    - lastTransitionTime: "2023-08-17T09:19:21Z"
      message: Unable to create Service resource
      observedGeneration: 2
      reason: NoResources
      status: "False"
      type: Accepted
    - lastTransitionTime: "2023-08-17T09:19:21Z"
      message: Address is not ready
      observedGeneration: 2
      reason: ListenersNotReady
      status: "False"
      type: Programmed
  listeners:
    - attachedRoutes: 1
      conditions:
        - lastTransitionTime: "2023-08-17T09:19:21Z"
          message: Listener Programmed
          observedGeneration: 2
          reason: Programmed
          status: "True"
          type: Programmed
        - lastTransitionTime: "2023-08-17T09:19:21Z"
          message: Listener Accepted
          observedGeneration: 2
          reason: Accepted
          status: "True"
          type: Accepted
      name: web-gw
      supportedKinds:
        - group: gateway.networking.k8s.io
          kind: HTTPRoute
```

Service
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  finalizers:
    - service.k8s.aws/resources
  labels:
    io.cilium.gateway/owning-gateway: rest-external
  name: cilium-gateway-rest-external
  namespace: gateway-api
  ownerReferences:
    - apiVersion: gateway.networking.k8s.io/v1beta1
      kind: Gateway
      name: rest-external
      uid: 66cbf2c8-67ff-44cd-aa66-862c922d8114
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.4.59.0
  clusterIPs:
    - 10.4.59.0
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerClass: service.k8s.aws/nlb
  ports:
    - name: port-443
      nodePort: 32762
      port: 443
      protocol: TCP
      targetPort: 443
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - hostname: actualhostname-1234567890.us-east-1.elb.amazonaws.com

```

**Comment by sergeyshevch** [comment]
@Smana I find another workaround on this issue. You need to slightly tune policy that you using (afaik also written by me)

```
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
              service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          spec:
            loadBalancerClass: service.k8s.aws/nlb # This is fixes issue
```

**Comment by Smana** [comment]
Well, it doesn't seem to work on my side even though I defined the loadBalancerClass.

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: echo-mycluster-0.cloud.ogenki.io
    policies.kyverno.io/last-applied-patches: |
      mutate-svc-annotations.mutate-cilium-gateway-echo-gateway.kyverno.io: added /metadata/annotations
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  labels:
    io.cilium.gateway/owning-gateway: echo-gateway
  name: cilium-gateway-echo-gateway
  namespace: echo
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.58.62
  clusterIPs:
  - 172.20.58.62
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerClass: service.k8s.aws/nlb
  ports:
  - name: port-80
    nodePort: 30131
    port: 80
  type: LoadBalancer
```

I have this error in the cilium-operator logs:

```console
cilium-operator-76c4f97d54-mtlbg cilium-operator level=error msg="Unable to create Service" controller=gateway error="Service \"cilium-gateway-echo-gateway\" is invalid: spec.loadBalancerClass: Invalid value: \"null\": may not change once set" resource=echo/echo-gateway subsys=gateway-controller
```
