### ISSUE TITLE
Hubble relay doesn't connect to hubble-peers when prometheus is enabled

### ISSUE THREAD

**Issue by thibaultserti** [cilium/cilium#27506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

With httpV2 prometheus metrics enabled, Hubble relay fails to connect to peer with the following issue
`level=warning msg="Failed to create peer client for peers synchronization; will try again after the timeout has expired" error="context deadline exceeded" subsys=hubble-relay target="hubble-peer.kube-system.svc.cluster.local:80"`

With the following values, it works and the connection happens:
```yaml
cluster:
  name: belt

hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - http
      - policy:sourceContext=app|workload-name|pod|reserved-identity;destinationContext=app|workload-name|pod|dns|reserved-identity;labelsContext=source_namespace,destination_namespace
      - flow:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity
      #- httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity
    enableOpenMetrics: true
    serviceMonitor:
      enabled: true

  tls:
    enabled: false

  relay:
    enabled: true
    prometheus:
      enabled: true
      port: 9966
      serviceMonitor:
        enabled: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

operator:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
```

I get this logs on hubble relay:
```yaml
level=info msg=Connecting address="192.168.1.41:4244" hubble-tls=false peer=belt/tycho subsys=hubble-relay
level=info msg=Connecting address="192.168.1.42:4244" hubble-tls=false peer=belt/pallas subsys=hubble-relay
level=info msg=Connecting address="192.168.1.43:4244" hubble-tls=false peer=belt/ceres subsys=hubble-relay
level=info msg=Connected address="192.168.1.43:4244" hubble-tls=false peer=belt/ceres subsys=hubble-relay
level=info msg=Connected address="192.168.1.42:4244" hubble-tls=false peer=belt/pallas subsys=hubble-relay
level=info msg=Connected address="192.168.1.41:4244" hubble-tls=false peer=belt/tycho subsys=hubble-relay
```

With this values, hubble relay doesn't connect with peers:

```yaml
cluster:
  name: belt

hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - http
      - policy:sourceContext=app|workload-name|pod|reserved-identity;destinationContext=app|workload-name|pod|dns|reserved-identity;labelsContext=source_namespace,destination_namespace
      - flow:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity
      - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity
    enableOpenMetrics: true
    serviceMonitor:
      enabled: true

  tls:
    enabled: false

  relay:
    enabled: true
    prometheus:
      enabled: true
      port: 9966
      serviceMonitor:
        enabled: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

operator:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
```

No firewall is enabled on the nodes:
```
$ ufw status
Status: inactive
```

I have checked everything is ok following this issue : https://github.com/cilium/cilium/issues/20130#issuecomment-1437045395
- Multiple reinstallation has been done either with Helm, the CLI or kubectl apply (via ArgoCD which I use for deploying everything) and each time
- No TLS is used because I use insecure (I tried with TLS too and doesn't work either)
- cluster domain is cluster.local

When I look if port 4244 (used by hubble-peers) is binded on the node, I get a result when prometheus is false:
```
# lsof -i -P -n | grep 4244
kube-apis    1485            root  299u  IPv6 125119759      0t0  TCP 192.168.1.41:6443->10.0.1.234:42446 (ESTABLISHED)
cilium-ag 1037115            root   55u  IPv6 158182034      0t0  TCP *:4244 (LISTEN)
cilium-ag 1037115            root   79u  IPv6 158187002      0t0  TCP 192.168.1.41:4244->192.168.1.42:33020 (ESTABLISHED)
```

When prometheus is true, there is nothing listening on :4244.

If I look in the chart, I see that this part are added to cilium-agent Daemonset when enabling prometheus metrics:
```
{{- if .Values.prometheus.enabled .Values.hubble.metrics.enabled}}
ports:
- name: peer-service
        containerPort: {{.Values.hubble.peerService.targetPort}}
        hostPort: {{.Values.hubble.peerService.targetPort}}
        protocol: TCP
{{- if.Values.prometheus.enabled}}
- name: prometheus
        containerPort: {{.Values.prometheus.port}}
        hostPort: {{.Values.prometheus.port}}
        protocol: TCP
```

I understand that cilium-agent runs with `hostNetwork: true` to bind its container port to the host port automatically so I don't get why it's explicitly added with hostPot in the ports section.

I'll gladly accept any help because it forces me to run Hubble without any of the useful features as L7 observability or policy verdict to achieve zero trust :/

### Cilium Version

1.14.0 with kube-proxy

### Kernel Version

Linux 5.15.0-76-generic

### Kubernetes Version

1.27.3 on Baremetal installed with kubeadm

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
