### ISSUE TITLE
CFP: unittest helm chart

### ISSUE THREAD

**Issue by tvonhacht-apple** [cilium/cilium#27514]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your proposed feature related to a problem?**

Making a helm chart change in any of the templates files, can not be tested until actually run against a cluster.
For example this simple change that was done, was hard to debug, because I could only really see rendered templates when deploying it to a cluster. https://github.com/cilium/cilium/pull/27229

**Describe the feature you'd like**

I want to be able to test helm chart locally without needing to run it against a cluster, easily see all areas my change is impacting the chart, as well as being able to validate via a check that no changes in helm-chart without updating snapshots have been done.

**Describe your proposed solution**

I would like to use [helm unittest](https://github.com/helm-unittest/helm-unittest), a common plugin used for testing helm charts in the open source community.
- write test file in pure YAML
- render locally
- create nothing on your cluster
- [wildcard selection for templates](https://github.com/helm-unittest/helm-unittest/blob/main/DOCUMENT.md#test-suite)
- [define values and release options](https://github.com/helm-unittest/helm-unittest/blob/main/DOCUMENT.md#test-job)
- [snapshot testing](https://github.com/cilium/cilium/issues/new?assignees=&labels=kind%2Ffeature&projects=&template=feature_template.md&title=CFP%3A+#snapshot-testing)
- [test suite code completion and validation](https://github.com/cilium/cilium/issues/new?assignees=&labels=kind%2Ffeature&projects=&template=feature_template.md&title=CFP%3A+#test-suite-code-completion-and-validation)

*Example unittest for `spire/agent/daemonset.yaml*

```yaml
# install/kubernetes/cilium/tests/spire/agent/daemonset.yaml
suite: spire agent daemonset
templates:
  - spire/agent/daemonset.yaml
tests:
  - it: Should not render
    asserts:
      - hasDocuments:
          count: 0

  - it: enabled
    set:
      authentication:
        mutual:
          spire:
            enabled: true
    asserts:
     - matchSnapshot: {}

## This would have been added to test the new flag as added by above PR referenced to test that rendered template with this settings works
  - it: tolerations
    set:
      authentication:
        mutual:
          spire:
            enabled: true
            agent:
              tolerations:
                - operator: Exists
    asserts:
     - matchSnapshot: {}
```

via `helm unittest --update -3 install/kubernetes/cilium/.` we could auto generate the snapshots and changes would be part of the PR, easy to review

```yaml
# install/kubernetes/cilium/tests/snapshots/spire/agent/daemonset.yaml.snap
enabled:
  1: |
    kind: DaemonSet
    metadata:
      name: spire-agent
      # ...
tolerations:
  1: |
    kind: DaemonSet
    metadata:
      name: spire-agent
      # ...
    spec:
      selector:
        matchLabels:
          app: spire-agent
      template:
        metadata:
          namespace: {{ .Values.authentication.mutual.spire.install.namespace }}
          labels:
            app: spire-agent
        spec:
          # ...
          tolerations:
             - operator: Exists
```

*PRB check*

```
helm unittest -3 install/kubernetes/cilium/.
```

**If this is approved, would be happy to create an initial setup with default tests for every object**

Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.
