### ISSUE TITLE
Grafana dashboard examples URL's are invalid

### ISSUE THREAD

**Issue by githubcdr** [cilium/cilium#27519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

THe example URL's for Grafana dashboards are linked to a parent file, instead of a valid json file. This prevents provisioning dashboards via Kustomize for example;

https://github.com/cilium/cilium/blob/main/examples/kubernetes/addons/prometheus/files/grafana-dashboards/cilium-dashboard.json

### Cilium Version

1.14.1

### Kernel Version

6.1

### Kubernetes Version

1.27.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by githubcdr** [comment]
This is the new (?) working location;

```
      cilium:
        cilium-dashboard:
          url: https://raw.githubusercontent.com/cilium/cilium/1.14.1/install/kubernetes/cilium/files/cilium-agent/dashboards/cilium-dashboard.json
          datasource: Prometheus
        cilium-operator-dashboard:
          url: https://raw.githubusercontent.com/cilium/cilium/1.14.1/install/kubernetes/cilium/files/cilium-operator/dashboards/cilium-operator-dashboard.json
          datasource: Prometheus
        hubble-dashboard:
          url: https://raw.githubusercontent.com/cilium/cilium/1.14.1/install/kubernetes/cilium/files/hubble/dashboards/hubble-dashboard.json
          datasource: Prometheus

```
