### ISSUE TITLE
Provide Cilium Mesh examples such as logging, load balancing, grayscale

### ISSUE THREAD

**Issue by tanjunchen** [cilium/cilium#27525]
## Cilium Feature Proposal
        
Cilium official website provides more Cilium Mesh usage examples for user reference and learning.

**Is your proposed feature related to a problem?**

Cilium Mesh usage document.

- [X] accesslog, According to the https://github.com/cilium/proxy/blob/main/envoy_build_config/extensions_build_config.bzl#L7-L13, accesslog is currently not supported.
- [X] circuit-breaker, https://github.com/cilium/cilium/pull/27641
- [X] traffic shifting, https://github.com/cilium/cilium/pull/27845

**Comment by tanjunchen** [comment]
How to configure and enable cilium envoy access_log, and the following configurations report errors.
```
apiVersion: cilium.io/v2
kind: CiliumClusterwideEnvoyConfig
metadata:
  name: cec-envoy-accesslog
spec:
  services:
    - name: echo-service-1
      namespace: default
    - name: echo-service-2
      namespace: default
  resources:
    - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
      name: envoy-lb-listener
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: envoy-lb-listener
                access_log:
                - name: envoy.access_loggers.stdout
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                rds:
                  route_config_name: lb_route
                use_remote_address: true
                skip_xff_append: true
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    - "@type": type.googleapis.com/envoy.config.route.v3.RouteConfiguration
      name: lb_route
      virtual_hosts:
        - name: "lb_route"
          domains: [ "*" ]
          routes:
            - match:
                prefix: "/"
              route:
                weighted_clusters:
                  clusters:
                    - name: "default/echo-service-1"
                      weight: 50
                    - name: "default/echo-service-2"
                      weight: 50
                retry_policy:
                  retry_on: 5xx
                  num_retries: 3
                  per_try_timeout: 1s
                regex_rewrite:
                  pattern:
                    google_re2: { }
                    regex: "^/foo.*$"
                  substitution: "/"
    - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
      name: "default/echo-service-1"
      connect_timeout: 5s
      lb_policy: ROUND_ROBIN
      type: EDS
      outlier_detection:
        split_external_local_origin_errors: true
        consecutive_local_origin_failure: 2
    - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
      name: "default/echo-service-2"
      connect_timeout: 3s
      lb_policy: ROUND_ROBIN
      type: EDS
      outlier_detection:
        split_external_local_origin_errors: true
        consecutive_local_origin_failure: 2
```
the output of envoy.
```
level=warning msg="Ignoring invalid CiliumEnvoyConfig JSON (proto: (line 1:355): unable to resolve \"type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog\": \"not found\"): {\n\t\"@type\": \"type.googleapis.com/envoy.config.listener.v3.Listener\",\n\t\"filter_chains\": [\n\t\t{\n\t\t\t\"filters\": [\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"envoy.filters.network.http_connection_manager\",\n\t\t\t\t\t\"typed_config\": {\n\t\t\t\t\t\t\"@type\": \"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager\",\n\t\t\t\t\t\t\"access_log\": [\n\t\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\t\"name\": \"envoy.access_loggers.stdout\",\n\t\t\t\t\t\t\t\t\"typed_config\": {\n\t\t\t\t\t\t\t\t\t\"@type\": \"type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog\"\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t],\n\t\t\t\t\t\t\"http_filters\": [\n\t\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\t\"name\": \"envoy.filters.http.router\",\n\t\t\t\t\t\t\t\t\"typed_config\": {\n\t\t\t\t\t\t\t\t\t\"@type\": \"type.googleapis.com/envoy.extensions.filters.http.router.v3.Router\"\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t],\n\t\t\t\t\t\t\"rds\": {\n\t\t\t\t\t\t\t\"route_config_name\": \"lb_route\"\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\"skip_xff_append\": true,\n\t\t\t\t\t\t\"stat_prefix\": \"envoy-lb-listener\",\n\t\t\t\t\t\t\"use_remote_address\": true\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t]\n\t\t}\n\t],\n\t\"name\": \"envoy-lb-listener\"\n}" subsys=k8s-apis-cilium.io-v2
```
