### ISSUE TITLE
Gateway API controller doesn't populate GatewayStatusAddress

### ISSUE THREAD

**Issue by sergeyshevch** [cilium/cilium#27558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When new service is created for GatewayAPI, GatewayAPI controller doesn't populate it's address in kind:Gateway status.

For example:

Gateway with status
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: rest-external
spec:
  gatewayClassName: cilium
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '*.myhost'
      name: web-gw
      port: 443
      protocol: HTTP
status:
  conditions:
    - lastTransitionTime: "2023-08-17T09:19:21Z"
      message: Unable to create Service resource
      observedGeneration: 2
      reason: NoResources
      status: "False"
      type: Accepted
    - lastTransitionTime: "2023-08-17T09:19:21Z"
      message: Address is not ready
      observedGeneration: 2
      reason: ListenersNotReady
      status: "False"
      type: Programmed
  listeners:
    - attachedRoutes: 1
      conditions:
        - lastTransitionTime: "2023-08-17T09:19:21Z"
          message: Listener Programmed
          observedGeneration: 2
          reason: Programmed
          status: "True"
          type: Programmed
        - lastTransitionTime: "2023-08-17T09:19:21Z"
          message: Listener Accepted
          observedGeneration: 2
          reason: Accepted
          status: "True"
          type: Accepted
      name: web-gw
      supportedKinds:
        - group: gateway.networking.k8s.io
          kind: HTTPRoute
```

Service
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  finalizers:
    - service.k8s.aws/resources
  labels:
    io.cilium.gateway/owning-gateway: rest-external
  name: cilium-gateway-rest-external
  namespace: gateway-api
  ownerReferences:
    - apiVersion: gateway.networking.k8s.io/v1beta1
      kind: Gateway
      name: rest-external
      uid: 66cbf2c8-67ff-44cd-aa66-862c922d8114
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.4.59.0
  clusterIPs:
    - 10.4.59.0
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerClass: service.k8s.aws/nlb
  ports:
    - name: port-443
      nodePort: 32762
      port: 443
      protocol: TCP
      targetPort: 443
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - hostname: actualhostname-1234567890.us-east-1.elb.amazonaws.com

```

### Cilium Version

1.14.1

### Kernel Version

n/a

### Kubernetes Version

v1.26.7-eks-2d98532          

### Sysdump

n/a

### Relevant log output

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
