### ISSUE TITLE
Host Firewall: egress policy cannot work

### ISSUE THREAD

**Issue by yingnanzhang666** [cilium/cilium#27677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Add CiliumClusterwideNetworkPolicy with egress policy, allow toCIDR "10.0.0.1/32". The policy definition is as following.
But it didn't drop the packets from host to any IPs outside the same node. Even the IP is not 10.0.0.1.
```
root@1000-worker:/# curl 192.168.210.30:8080
dest1-cb4dbf76b-k6nv
```
```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: ciliumhostpolicy
spec:
  egress:
  - toCIDR:
    - 10.0.0.1/32
    toPorts:
    - ports:
      - port: "8081"
        protocol: TCP
      - port: "80"
        protocol: TCP
      - port: "443"
        protocol: TCP
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
  ingress:
  - fromCIDR:
    - 192.168.0.0/16
    - 172.16.0.0/12
    - 10.0.0.0/8
    toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
  - fromEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: "10250"
        protocol: TCP
  nodeSelector:
    matchLabels:
      protected: "true"
```

The datapath for these packets is only call tc egress of eth0 (cil_to_netdev).
cil_to_netdev -> handle_to_netdev_ipv4 -> (1. resolve_srcid_ipv4, 2. ipv4_host_policy_egress).
If I understood correct, there's no mark for MARK_MAGIC_HOST, and it cannot get src id from ipcache in `resolve_srcid_ipv4` for the snat consideration. So, the src_id is 0 when it call ipv4_host_policy_egress. Then it return CTX_ACT_OK directly without any egress check if the src_id is not HOST_ID.
```
#ifdef ENABLE_HOST_FIREWALL
static __always_inline int
handle_to_netdev_ipv4(struct __ctx_buff *ctx, struct trace_ctx *trace, __s8 *ext_err)
{
	void *data, *data_end;
	struct iphdr *ip4;
	__u32 src_id = 0, ipcache_srcid = 0;

	if ((ctx->mark & MARK_MAGIC_HOST_MASK) == MARK_MAGIC_HOST)
		src_id = HOST_ID;

	if (!revalidate_data_pull(ctx, &data, &data_end, &ip4))
		return DROP_INVALID;

	src_id = resolve_srcid_ipv4(ctx, ip4, src_id, &ipcache_srcid, true);

	/* We need to pass the srcid from ipcache to host firewall. See
	 * comment in ipv4_host_policy_egress() for details.
	 */
	return ipv4_host_policy_egress(ctx, src_id, ipcache_srcid, ip4, trace, ext_err);
}
#endif /* ENABLE_HOST_FIREWALL */
#endif /* ENABLE_IPV4 */
```

### Cilium Version

cilium 1.14

### Kernel Version

kernel 5.15

### Kubernetes Version

kubernetes 1.18

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
