### ISSUE TITLE
NodePort not working with DSR-Geneve

### ISSUE THREAD

**Issue by avinakollu** [cilium/cilium#27700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi, we are using Cilium as a CNI on EKS without VPC CNI and kube proxy. We have a use case where we have to preserve Client IP for a service. After looking through the docs, we decided to go with DSR + Geneve. We use AWS LoadBalancer controller for provisioning load balancers. Here is our helm config:

```
ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDRList: ["7.0.0.0/8"]

kubeProxyReplacement: "true"

k8sServiceHost: "{{ eks_cluster_endpoint }}"

k8sServicePort: "443"

tunnel: geneve

loadBalancer:
  mode: dsr
  dsrDispatch: geneve

nodePort:
  enabled: true

hostPort:
  enabled: "true"
```

When we create services of type load balancer, the URL works intermittently. Upon further investigation, only the nodes which run the pods respond as expected. Is this expected? Is there some way to be able to listen on all NodePorts?

### Cilium Version

1.14.1

### Kernel Version

5.10

### Kubernetes Version

1.26 EKS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
