### ISSUE TITLE
N/S loadbalancing: Connect to stale backend in long lived TCP connection

### ISSUE THREAD

**Issue by ysksuzuki** [cilium/cilium#27726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. Create a StatufulSet with 3 replicas and setup a MySQL cluster (1 primary, 2 replicas). A primary pod has `moco.cybozu.com/role: primary` label, and replicas have `moco.cybozu.com/role: replica` label.

StatefulSet and Pods derived from it
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: test
    app.kubernetes.io/name: mysql
  name: moco-test
  namespace: dctest
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: test
      app.kubernetes.io/name: mysql
  serviceName: moco-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test
        app.kubernetes.io/name: mysql
    spec:
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/instance: test
    app.kubernetes.io/name: mysql
    moco.cybozu.com/role: primary
    statefulset.kubernetes.io/pod-name: moco-test-0
  name: moco-test-0
  namespace: dctest
spec:
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/instance: test
    app.kubernetes.io/name: mysql
    moco.cybozu.com/role: replica
    statefulset.kubernetes.io/pod-name: moco-test-1
  name: moco-test-1
  namespace: dctest
spec:
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/instance: test
    app.kubernetes.io/name: mysql
    moco.cybozu.com/role: replica
    statefulset.kubernetes.io/pod-name: moco-test-2
  name: moco-test-2
  namespace: dctest
spec:
```

2. Create 2 Loadbalancer services for primary and replicas

Loadbalancer services
```

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app.kubernetes.io/instance: test
    app.kubernetes.io/name: mysql
  name: moco-test-primary
  namespace: dctest
spec:
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Cluster
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  - name: mysqlx
    port: 33060
    protocol: TCP
    targetPort: mysqlx
  selector:
    app.kubernetes.io/instance: test
    app.kubernetes.io/name: mysql
    moco.cybozu.com/role: primary
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app.kubernetes.io/instance: test
    app.kubernetes.io/name: mysql
  name: moco-test-replica
  namespace: dctest
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  - name: mysqlx
    port: 33060
    protocol: TCP
    targetPort: mysqlx
  selector:
    app.kubernetes.io/instance: test
    app.kubernetes.io/name: mysql
    moco.cybozu.com/role: replica
  type: LoadBalancer
```

3. Connect to the MySQCluster through the primary Loadbalancer service

```
$ kubectl -n dctest get svc
NAME                      TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)              AGE
moco-test                 ClusterIP      None            <none>        3306/TCP,33060/TCP   25h
moco-test-primary         LoadBalancer   10.68.138.152   10.72.32.7    3306/TCP,33060/TCP   25h
moco-test-replica         LoadBalancer   10.68.197.210   10.72.32.8    3306/TCP,33060/TCP   24h

mysql -u moco-admin -h 10.72.32.7 -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 19805
Server version: 8.0.30 Source distribution

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select @@hostname;
+-------------+
| @@hostname  |
+-------------+
| moco-test-0 |
+-------------+
1 row in set (0.00 sec)
```
 
4. Switch the primary from `moco-test-0` to `moco-test-1`

`moco-test-1` has `moco.cybozu.com/role=primary` label, old primary `moco-test-0` has `moco.cybozu.com/role=replica` 
```
$ kubectl -n dctest get po --show-labels
moco-test-0                                               4/4     Running   0          25h   app.kubernetes.io/instance=test,app.kubernetes.io/name=mysql,moco.cybozu.com/role=replica,statefulset.kubernetes.io/pod-name=moco-test-0
moco-test-1                                               4/4     Running   0          25h   app.kubernetes.io/instance=test,app.kubernetes.io/name=mysql,moco.cybozu.com/role=primary,statefulset.kubernetes.io/pod-name=moco-test-1
moco-test-2                                               4/4     Running   0          25h   app.kubernetes.io/instance=test,app.kubernetes.io/name=mysql,moco.cybozu.com/role=replica,statefulset.kubernetes.io/pod-name=moco-test-2
```

5. MySQL client connects to the stale `moco-test-0`

```
mysql> select @@hostname;
+-------------+
| @@hostname  |
+-------------+
| moco-test-0 |
+-------------+
1 row in set (0.00 sec)
```

The client connects to the new backend after flushing CT maps.

```
$ kubectl -n kube-system exec cilium-s5lfb -- cilium bpf ct flush global
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
Flushed 79416 entries from /sys/fs/bpf/tc/globals/cilium_ct4_global
Flushed 35047 entries from /sys/fs/bpf/tc/globals/cilium_ct_any4_global

mysql> select @@hostname;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    20052
Current database: *** NONE ***

+-------------+
| @@hostname  |
+-------------+
| moco-test-1 |
+-------------+
1 row in set (0.01 sec)
```

### Cilium Version

1.14.1

### Kernel Version

Linux rack0-cs4 5.15.122-flatcar

### Kubernetes Version

$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"11902a838028edef305dfe2f96be929bc4d114d8", GitTreeState:"clean", BuildDate:"2023-06-14T09:56:58Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"11902a838028edef305dfe2f96be929bc4d114d8", GitTreeState:"archive", BuildDate:"2023-07-05T01:27:55Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}

### Anything else?

LB configs

```
$ cilium config view
bgp-announce-lb-ip                                true
bpf-lb-acceleration                               disabled
bpf-lb-algorithm                                  maglev
bpf-lb-external-clusterip                         false
bpf-lb-map-max                                    65536
bpf-lb-mode                                       snat
bpf-lb-sock                                       true
bpf-lb-sock-hostns-only                           true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
