### ISSUE TITLE
Ports not open on LB IP for outisde the cluster connection - intermittent issue

### ISSUE THREAD

**Issue by mccasian** [cilium/cilium#27722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have tested and re-tested the scenario multiple times, even recreated the k8s cluster from scratch a few times. I have some services which gets an LB IP from a pre-declared cilium ip pool, which are announced through L2AnnouncementPolicy; while the IP become immediately responsive to ARPing, the port remains closed when trying to access it from outside the cluster. Testing the port from any worker/master works.

The workaround is to delete and deploy the entire deployment+service again.

Let's take an example: homeassistant deployment(see sysdump logs)
I've created the cluster, setup everything using:

```
#/bin/bash
API_SERVER_IP=172.16.30.0
API_SERVER_PORT=6443
sudo kubeadm init --pod-network-cidr=10.244.0.0/16   --upload-certs   --control-plane-endpoint=${API_SERVER_IP} --ignore-preflight-errors=all --skip-phases=addon/kube-proxy --kubernetes-version 1.28.0

# install CILIUM_CLI
CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
CLI_ARCH=amd64
if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}

# add cilium repo
helm repo add cilium https://helm.cilium.io/

# Kubeadm default is 6443
helm install cilium cilium/cilium --version 1.14.1 \
    --namespace kube-system \
    --set k8sServiceHost=${API_SERVER_IP} \
    --set k8sServicePort=${API_SERVER_PORT} \
    --set l2announcements.enabled=true  \
    --set externalIPs.enabled=true  \
    --set k8sClientRateLimit.qps=10 \
    --set k8sClientRateLimit.burst=20 \
    --set ingressController.enabled=true \
    --set ingressController.loadbalancerMode=dedicated \
    --set kubeProxyReplacement=strict

# enable L2 clusterwide
cat <<EOF | kubectl apply -f -
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: cilium-l2-policy
  namespace: kube-system
spec:
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  interfaces:
  - ^eth[0-9]+
  externalIPs: true
  loadBalancerIPs: true
EOF

# configure the IP Pool
cat <<EOF | kubectl apply -f -
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: cilium-ip-pool
  namespace: cilium
spec:
  cidrs:
  - cidr: "172.16.30.0/24"
EOF

# patchj the ingress service labels
kubectl patch service -n kube-system cilium-ingress -p '{"spec": {"loadBalancerIP": "172.16.30.7"}}'
```

then I've deployed the homeassistant:
```
# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant

---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 2
        maxUnavailable: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
      namespace: homeassistant
    spec:
      hostNetwork: true
      containers:       
        - name: homeassistant
          image: homeassistant/home-assistant:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "756Mi"
              cpu: "2000m" # 0.5 CPU, 500m = 500 mili and 1000mili = 1CPU
          env:
            - name: "TZ"
              value: "Europe/Berlin"
          volumeMounts:
            - name: hostpath-volume
              mountPath: /config
      # enforce the eviction time to less than the standard 5 minutes for the current app
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 1
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 1
      hostAliases:
        - ip: "172.16.10.10"
          hostnames:
          - "mfileserver.home"
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 172.16.0.5
          - 172.16.0.6
        searches:
          - home
      volumes:
        - name: hostpath-volume
          persistentVolumeClaim:
            claimName: homeassistant-pvc


---

# PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-pv
  namespace: homeassistant
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /docker/homeassistant/

---

# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi

---

# service            
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant

spec:
  selector:
    app: homeassistant
  # externalIPs:
  #   - 172.16.30.38
  loadBalancerIP: 172.16.30.38
  ports:
    - protocol: TCP
      name: ha-port
      port: 8123
      targetPort: 8123
    - protocol: UDP # homekit
      name: homekit-std-port
      port: 5353
      targetPort: 5353
    - protocol: TCP # homekit
      name: configured-homekit-port
      port: 21063
      targetPort: 21063
    - protocol: TCP # homekit
      name: configured-homekit-port2
      port: 21064
      targetPort: 21064
    - protocol: TCP # homekit
      name: configured-homekit-port3
      port: 51827
      targetPort: 51827
  type: LoadBalancer
```

After a minute or so, the pod was ready, and the services was shown correctly:

```
Every 2.0s: kubectl get svc -A                                                                                                                                                                                     k8s-2: Sat Aug 26 16:17:44 2023

NAMESPACE              NAME                        TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)                                                                         AGE
default                kubernetes                  ClusterIP      10.96.0.1        <none>         443/TCP                                                                         46m
homeassistant          homeassistant               LoadBalancer   10.100.108.191   172.16.30.38   8123:32344/TCP,5353:31167/UDP,21063:31516/TCP,21064:30492/TCP,51827:32411/TCP   27m
```

ARPing was ok as soon as the service was shown in the list:
```
arping homeassistant.home
ARPING 172.16.30.38
60 bytes from 00:0c:29:6e:4d:4d (172.16.30.38): index=0 time=4.906 msec
60 bytes from 00:0c:29:6e:4d:4d (172.16.30.38): index=1 time=4.870 msec
```

but the port was not open when tried from my laptop, or from another machine in the network:
```
nc -vz homeassistant.home 8123
nc: connectx to homeassistant.home port 8123 (tcp) failed: Network is unreachable
```

However, if I try to do the same nc/telnet test from any of the workers or control-planes, it always works:
```
nc -vz homeassistant.home 8123
Connection to homeassistant.home (172.16.30.38) 8123 port [tcp/*] succeeded!
```

So I deleted the HomeAssistant deployment+service(using kubectl delete -f <all-in-one-file>) and recreated it... then it worked.

I have also tried to expose kubernetes dashboard but even if the pods are running and it shown correctly in the list of services, it's still not accesible from outside the cluster, only from inside. IP is answering to  ARPing but the port is closed. After multiple tries, i couldn't manage to make the dashboard service work.

This is how it looks from a worker node:
```
mccasian@k8s-6:~$ curl -k https://dashboard.k8s.home
<!--
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

.....
```

and this is from my laptop:
```
curl -k https://dashboard.k8s.home
curl: (28) Failed to connect to dashboard.k8s.home port 443 after 75000 ms: Couldn't connect to server
```

I was trying to look into the sysdump logs but I am not able to properly analyse and understand them.

Is there a possibility that I miss out something, or I configured something wrong?

### Cilium Version

1.14.1

### Kernel Version

5.15.0-79-generic

### Kubernetes Version

1.28.0

### Sysdump

[cilium-sysdump-20230826-160438.zip](https://github.com/cilium/cilium/files/12446078/cilium-sysdump-20230826-160438.zip)

### Anything else?

I suggest taking a look into logs for homeassistant deployment. First time I deployed it the port was not open. The second time it worked.

Also, I've deployed kubernetes-dashboard a few times, none of the times worked.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
