### ISSUE TITLE
Wireguard server cannot forward to cluster ip cidr

### ISSUE THREAD

**Issue by erikschul** [cilium/cilium#27758]
**(Vote on this issue 👍 if you would like this resolved as well)**

.
.
.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium works correctly, until I install a Wireguard server with the following routing rules:
```
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp = iptables -A FORWARD -o wg0 -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o cilium_host -j MASQUERADE
PostUp = iptables -t nat -A POSTROUTING -o enp7s0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -o wg0 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o cilium_host -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -o enp7s0 -j MASQUERADE
```
where `enp7s0` is the "internal ip" network interface.

I would like to connect my workstation to the cluster, and have access to the nodes (enp7s0), and cluster and service cidr (cilium_host).

I have a controlplane node (tainted) and 3 worker nodes, and a service/pod(nginx) running as a DaemonSet.

After applying the rules:
The worker nodes can curl pod ips and cluster ip.
The controlplane can curl the pod ips, but fails on the cluster ip.
Using these commands to observe:
```
tcpdump -ni eth0 -l port not 22 and port not 53
tcpdump -ni cilium_host -l port not 22 and port not 53
```
When running `curl 10.96.148.170` locally on each node, I found that worker nodes use `cilium_host`, but the control plane node is using `eth0`.
I assume this is caused by the changes in iptables.

The docs describe how [Cilium uses iptables](https://docs.cilium.io/en/stable/network/ebpf/iptables/), but it's unclear how I can safely modify the iptables rules. Also if I wanted to apply firewall rules.

1) What am I doing wrong? What's the right approach?

2) How can iptables rules be modified without unintentionally breaking Cilium functionality, and leaking packets intended for the service cidr to the internet?

### Cilium Version

1.14.0

### Kernel Version

Linux cp0 6.1.0-11-arm64 #1 SMP Debian 6.1.38-4 (2023-08-08) aarch64 GNU/Linux

### Kubernetes Version

1.28

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

Control plane taints:
```
taints:                                                                                                                                                                                                                                                                
- effect: NoSchedule                                                                                                                                                                                                                                                   
  key: node-role.kubernetes.io/control-plane                                                                                                                                                                                                                           
- effect: NoExecute                                                                                                                                                                                                                                                    
  key: node-role.kubernetes.io/control-plane  
```

Cilium helm values:
```
kubeProxyReplacement: "true",
ipam: {
    operator: { clusterPoolIPv4PodCIDRList: ["10.92.0.0/14"] },
},
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by erikschul** [comment]
Related: https://github.com/cilium/cilium/issues/26847

**Comment by erikschul** [comment]
1. The `cilium sysdump` contains a lot of information, that I'd have to inspect. So, unfortunately not. Are there specific files that you want to look at?
2. Yes it runs on the control plane (kubelet runs on the control plane node, and cilium ignores all taints)

But I reproduced the problem on the worker node as well.

I think the problem is with how iptables are used for routing the service cidr.
And that this line breaks that functionality `iptables -t nat -A POSTROUTING -o cilium_host -j MASQUERADE`.

The question is whether there's a way to correctly bridge a network (in this case `wg0`) to the service cidr (as configured by cilium).
I'm surprised that the load balancing functionality isn't implemented in eBPF and with routing tables, rather than iptables.
But maybe this is to support legacy networks that use kubeproxy.

**Comment by brb** [comment]
Why do you need `iptables -t nat -A POSTROUTING -o cilium_host -j MASQUERADE`? Can't you just set `bpf.lbExternalClusterIP=true`, and then install IP route "$CLUSTER_IP_CIDR via $ANY_REMOTE_NODE_IP_ADDR_IN_WG_NETWORK`?

**Comment by erikschul** [comment]
Hmm, enabling `lbExternalClusterIP` didn't solve it.

But it seems to cause Wireguard to set up the service route (in this case `10.96.2.8`).
```
default            192.168.0.1        UGScg             en0       
default            link#26            UCSIg           utun8       
10.88/24           10.88.0.2          UGSc            utun8       
10.88/16           link#26            UCS             utun8       
10.88.0.2          10.88.0.2          UH              utun8       
10.91/16           link#26            UCS             utun8       
10.92/14           link#26            UCS             utun8       
10.92.2.156        link#26            UHWIi           utun8       
10.96/16           link#26            UCS             utun8       
10.96.2.8          link#26            UHW3I           utun8    226
```

But `curl 10.96.2.8` timeouts.
I also tried
- adding `iptables -t nat -A POSTROUTING -o cilium_host -j MASQUERADE`
- running `ip route add 10.96.0.0/16 dev cilium_host`

Any thoughts?

What about `bpf.masquerade`?

**Comment by brb** [comment]
>Why do you need iptables -t nat -A POSTROUTING -o cilium_host -j MASQUERADE?

**Comment by erikschul** [comment]
I would like to access the service cidr from the wireguard connection:
Laptop -> Wireguard -> Kubernetes node with Cilium -> Service/ClusterIP -> Pod
I'm able to communicate directly with pod, but not via the Cluster IP.

It works with SSH/SOCKS (node/pod/cluster ip), but not with Wireguard (only node/pod works).

**Comment by erikschul** [comment]
Possibly it doesn't?

**Comment by erikschul** [comment]
I tried again, setting `bpf.lbExternalClusterIP=true`.
This caused the cluster ip cidr to become available across the cluster. I'm guessing the routing no longer happens via iptables .

I can curl a specific pod: `curl 10.96.70.200`

I then add the route as you suggested (forwarding to the local cilium_host interface)
```
ip route add 10.96.0.0/16 via 10.92.3.211 dev cilium_host proto kernel src 10.92.3.211 mtu 1400
```

but the cluster ip is still unavailable, curl timeout:
```
curl 10.96.70.200
```

Any other suggestions?

**Comment by erikschul** [comment]
Related https://github.com/cilium/cilium/issues/27758

**Comment by erikschul** [comment]
Related https://github.com/cilium/cilium/issues/26847

**Comment by erikschul** [comment]
Related https://github.com/cilium/cilium/issues/27878

**Comment by erikschul** [comment]
Also, after disabling `bpf.lbExternalClusterIP=true` (and verifying that the ConfigMap now has false by default), and rebooting the cluster, the cluster ip cidr is still unavailable to all nodes.
I assume that the iptables configuration is not rebuilt properly? Is this a bug?
Since I have no idea how to debug this, I'm forced to rebuild the cluster.

**Comment by jspaleta** [comment]
For reference, 
I have a gist detailing my working home lab setup using a k3s cluster with cilium egress gateway enabled that may be useful to read through. My setup is not experiencing the problems communicated here. I offer it as a good starting point for differential analysis to figure out what the problem is in the reported environment.

I do a detailed breakdown of connectivity tests using netcat on both sides of the tunnel to prove to myself the tunnel works and my workstation can get access to private pod IP addresses via the tunnel I setup.

https://gist.github.com/jspaleta/a708a519bf5d2fed357d8a91e0351e98


Based on my experience setting this up, I am suspicious of either overbroad routing rules in the wireguard configuration, or some sort of linux firewalling feature that is enabled. For example, docker running on my workstation was silently turning on a linux bridge firewalling feature that killed my connectivity test from my manually created bridge device i was using for testing from private network namespaces on the workstation. This is why I also use a dummy device test in my gist, as part of the differential analysis that helped me figure out the bridge firewalling feature was enabled.

**Comment by erikschul** [comment]
@jspaleta I don't see any `kind: Service` in your gist. Did you test connectivity to a cluster IP over a wireguard tunnel? That is the central problem that we're trying to solve.

**Comment by jspaleta** [comment]
In the environment I have available to test right now, I do not expect any node host level wireguard tunnel to work to access ClusterIP services because I can't interact with those services from the node's host network, there is no route into the cluster's service CIDR setup in the host network in my configuration.

The pods however do have a host networking route using the cilium_host interface, and this is sufficient to make egress gateway work using the wireguard tunnel in my setup.

**Comment by erikschul** [comment]
@jspaleta Could you provide your deployment so I can test it?

This is my deployment. It does not work when I try to curl a test application in the cluster ip cidr.

Kubernetes deployment:

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    mankindu.com/app: wireguard
  name: wireguard
  namespace: wireguard
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    mankindu.com/app: wireguard
  name: wireguard
  namespace: wireguard
stringData:
  wg0.conf: |
    [Interface]
    Address = 10.87.0.0/24
    ListenPort = 51820
    PrivateKey = qPNp5UTOFLOmjExQo/dosjfEYon9SRmRkuaX0zFQyk0=
    PostUp = iptables -A FORWARD -i %i -j ACCEPT
    PostUp = iptables -A FORWARD -o %i -j ACCEPT
    PostUp = iptables -A FORWARD -o %i -j ACCEPT
    PostUp = iptables -t nat -A POSTROUTING -o eth0@if45 -j MASQUERADE
    PostDown = iptables -t nat -D POSTROUTING -o eth0@if45 -j MASQUERADE
    PostDown = iptables -D FORWARD -i %i -j ACCEPT
    PostDown = iptables -D FORWARD -o %i -j ACCEPT
    PostDown = iptables -D FORWARD -o %i -j ACCEPT

    [Peer]
    PublicKey = FJafaeHZxuCotDYKBGmJX/HtP8/SnUrCXQzr3Gf0Dh8=
    AllowedIPs = 10.87.0.2
    PersistentKeepalive = 60
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mankindu.com/app: wireguard
  name: wireguard
  namespace: wireguard
spec:
  selector:
    matchLabels:
      name: wireguard
  template:
    metadata:
      labels:
        name: wireguard
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Berlin
            - name: PEERS
              value: example
          image: linuxserver/wireguard:latest
          name: wireguard
          ports:
            - containerPort: 51820
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
          volumeMounts:
            - mountPath: /etc/wireguard/
              name: config
      volumes:
        - name: config
          secret:
            secretName: wireguard
---
apiVersion: v1
kind: Service
metadata:
  labels:
    mankindu.com/app: wireguard
  name: wireguard
  namespace: wireguard
spec:
  ports:
    - name: wireguard
      nodePort: 31301
      port: 51820
      protocol: UDP
      targetPort: 51820
  selector:
    name: wireguard
  type: NodePort
```

Wireguard client:
```
[Interface]
PrivateKey = MLE++vliviqSSnqADXmN6QwHL8MamaM99SLWjbsGL0g=
Address = 10.87.0.2/24

[Peer]
PublicKey = HMLUxEicgn47SkJRQtaqsZ2bN4EfgmywsS0utqGMnxo=
AllowedIPs = 10.87.0.0/24,10.91.0.0/16,10.92.0.0/14,10.96.0.0/16
Endpoint = X.X.X.X:31301
PersistentKeepalive = 60
```

Obviously you need to update your endpoint X.X.X.X, and the relevant IP ranges
where, for me,:
10.87.0.0/24 - wireguard
10.91.0.0/16 - nodes
10.92.0.0/14 - pods
10.96.0.0/16 - cluster ip

**Comment by erikschul** [comment]
I got it to work by disabling kube-proxy-replacement, and installing kube-proxy.
It feels to me like a bug in kube-proxy-replacement, or a misconfiguration issue (and insufficient documentation).

@jspaleta If you get it to work, can you include your helm values?

And also your cilium status? e.g. the "KubeProxyReplacement Details:" from:
```
kubectl -n kube-system exec ds/cilium -- cilium status --verbose
```

**Comment by erikschul** [comment]
Cluster IP over wireguard was working when I disabled kube-proxy-replacement (`kubeProxyReplacement: "false"`), and installed `kube-proxy`.
But nodePort/hostPort didn't work.

But it breaks again (unable to curl a cluster ip over wireguard) when I enable nodePort/hostPort:
```
nodePort: { enabled: true, enableHealthCheck: false },
hostPort: { enabled: true },
```

Are there anyone from Cilium with more in-depth knowledge about how the kubeProxyReplacement works?

**Comment by erikschul** [comment]
Maybe the problem is that Cilium doesn't pick up the packets in PREROUTING?
I'm guessing that `lbExternalClusterIP` is supposed to enable that, but that it doesn't work, or requires other configuration parameters simultaneously?

![image](https://github.com/cilium/cilium/assets/128804597/104dcb70-4408-4136-981c-d3e76fa0ec35)

**Comment by erikschul** [comment]
I've also tried setting `devices`, but traffic is still being routed via `eth0` instead of `cilium_host`

```
kubeProxyReplacement: true
bpf:
  lbExternalClusterIP: true
devices:
  - enp7s0
  - eth0
  - wg+
``

**Comment by RichardSufliarsky** [comment]
We have same issue. Cluster IPs not accessible, Pod IPs work from VPN connection (VPN pod is running inside kubernetes cluster that we want to access) .

As a workaround we are accessing services exposed via "external IP" thanks to the MetalLB LoadBalancer (not a full example):
```
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement-ext
  namespace: metallb-system
spec:
  interfaces:
    - eth0
  ipAddressPools:
    - external
  nodeSelectors:
    - matchLabels:
        company.com/l2advertisement: external
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: external
  namespace: metallb-system
spec:
  addresses:
    - 10.1.2.3/32
  autoAssign: false
  avoidBuggyIPs: false
---
kind: Service
apiVersion: v1
metadata:
  name: openvpn
  namespace: openvpn
  labels:
    app: openvpn
  annotations:
    metallb.universe.tf/address-pool: external
    metallb.universe.tf/allow-shared-ip: external
    metallb.universe.tf/loadBalancerIPs: 10.1.2.3
spec:
  ports:
    - name: openvpn
      protocol: UDP
      port: 1234
      targetPort: openvpn
  selector:
    app: openvpn
  type: LoadBalancer
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: false
  ```

**Comment by NADESHIKON** [comment]
As reference to the slack discussion, changing kubeProxyReplacement to false is a temporary workaround.

**Comment by RichardSufliarsky** [comment]
@erikschul I have found solution to my issue.

It is in the documentation: https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#socket-loadbalancer-bypass-in-pod-namespace

And can be found also here in the docs (second note here https://docs.cilium.io/en/v1.13/network/istio/#setup-cilium):
You need to pass `--config bpf-lb-sock-hostns-only=true` to cilium CLI or `socketLB.hostNamespaceOnly` option with Helm. 

I applied the config only to the node that I needed and now my VPN client receives responds from service (ClusterIP):
```
apiVersion: cilium.io/v2alpha1
kind: CiliumNodeConfig
metadata:
  namespace: kube-system
  name: bpf-lb-sock-hostns-only
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: abc.def.xyz
  defaults:
    bpf-lb-sock-hostns-only: "true"
```

**Comment by erikschul** [comment]
@RichardSufliarsky Thanks for the investigative work. I'll try it out... but it seems a bit hacky, and hard to reason about what the consequences are. The guide notes don't sound related at all, so maybe this is just a configuration that coincidentally achieves what you wrote on slack: `When enabled, this circumvents socket rewrite in the connect() and sendmsg() syscall bpf hook and will pass the original packet to next stage of operation (e.g., stack in per-endpoint-routing mode) and re-enables service lookup in the tc bpf program.`

@cilium team: Couldn't this be enabled in a more obvious way, like `lbExternalClusterIP` for specific `devices`?
Or maybe called "exposeClusterIP" or similar.

**Comment by julianwiedmann** [comment]
> @julianwiedmann If this is unsupported functionality, should this be changed from bug to feature request?
> 

Feature proposal, yes :).

> It's still unclear to me what `lbExternalClusterIP` and `devices` is for, if it's not to allow this type of use case.

I would actually expect these config options to get you a good step [further](https://docs.cilium.io/en/latest/network/kubernetes/kubeproxy-free/#external-access-to-clusterip-services). Adjusting the `devices` option is needed so that your `wg0` interface has the relevant BPF programs for load-balancing attached. So chasing down why it doesn't work in your scenario might be worthwhile. It could be just a wireguard-specific quirk.

**Comment by RichardSufliarsky** [comment]
@erikschul it makes complete sense to me. Socket rewrite is done as soon as possible (service ClusterIP is immediately changed to PodIP of one of the service endpoints - loadbalancing) and packet does not need to travel up to the next stage of processing. But this doesn't work for special cases (like mine as I am introducing foreign network communication into the Pod directly).

From the docs:
_Cilium has built-in support for bypassing the socket-level loadbalancer and **falling back to the tc loadbalancer** at the veth interface **when** a custom redirection/operation **relies on the original ClusterIP** within pod namespace..._

And it makes sense to me also from the note for installation with Istio:
_Without this option, **when Cilium does service resolution via socket load balancing**, Istio sidecar **will be bypassed**, resulting in loss of Istio features including encryption and telemetry._

I don't think that `lbExternalClusterIP` has to do something with it as this is not external communication to cluster, it is already inside of the cluster (MASQUERADE is used to have an IP from internal CIDR) - but I can be completely mistaken.

**Comment by erikschul** [comment]
@RichardSufliarsky But this requires Wireguard to run inside a pod, right? I'll test it later, but I was hoping to run Wireguard on the host, so it would work independently of Kubernetes, but also allow interaction with Kubernetes.

**Comment by erikschul** [comment]
I confirm that it works for me as well.

Helm values:
```
socketLB: {
   hostNamespaceOnly: true,
},
```

StatefulSet (simultaneous pods during rollout could mess up iptables):
```
securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
```

Wireguard rules:
```
    PostUp = iptables -A FORWARD -i %i -j ACCEPT
    PostUp = iptables -A FORWARD -o %i -j ACCEPT
    PostUp = iptables -A FORWARD -o eth0 -j ACCEPT
    PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    PostDown = iptables -D FORWARD -i %i -j ACCEPT
    PostDown = iptables -D FORWARD -o %i -j ACCEPT
    PostDown = iptables -D FORWARD -o eth0 -j ACCEPT
    PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
```

Dockerfile (essentials):
```
FROM alpine:3.18.3
RUN apk add --no-cache wireguard-tools-wg-quick
```

**Comment by erikschul** [comment]
@cilium 
1) Can we document the helm values required in 
https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/
maybe in a section like "Enabling forwarding to Cluster IP from pods when using Wireguard, OpenVPN, Tailscale, and similar."

2) I suggest to keep this bug report as a feature request that this use-case will be officially supported (so it doesn't break in the future, i.e. changing the behavior of `hostNamespaceOnly`)

**Comment by erikschul** [comment]
Thanks @RichardSufliarsky !

**Comment by RichardSufliarsky** [comment]
@erikschul yes I have to run vpn service inside of the pod, but this was my goal (don't need anything special on the host itself).

I didn't modify helm values as I used this config only on one node `CiliumNodeConfig` where the openvpn pod is running.

values.yaml:
```
#bgp:
#  enabled: true
#  announce:
#    loadbalancerIP: true
bandwidthManager:
  enabled: true
hostFirewall:
  enabled: true
ipam:
  mode: kubernetes
k8sServiceHost: abc.def.xyz
k8sServicePort: 6443
kubeProxyReplacement: strict
loadBalancer:
  algorithm: maglev
  serviceTopology: true
  mode: hybrid
#  acceleration: native
tunnel: disabled
ipv4NativeRoutingCIDR: "172.18.0.0/16"
autoDirectNodeRoutes: true
bpf:
  masquerade: true
```
