### ISSUE TITLE
L2Announcement with externalTrafficPolicy: Local

### ISSUE THREAD

**Issue by ansarhun** [cilium/cilium#27800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have
* a `CiliumL2AnnouncementPolicy` configured to expose 2 `LoadBalancer` type services
* 2 `Service` one with `externalTrafficPolicy: Local` the other `externalTrafficPolicy: Cluster`

The service with the `Cluster` type works as expected.
The service with the `Local` type only works if I force the pod to the same node which have the lease for the given service.

I could see that the announcement worked and the node with the lease was exposed but if the pod is not running on that node with the lease it will not handle the traffic.

### Cilium Version

```
cilium-cli: v0.15.6 compiled with go1.21.0 on darwin/arm64
cilium image (default): v1.14.0
cilium image (stable): v1.14.1
cilium image (running): 1.14.1
```

### Kernel Version

`Linux k3s-worker-4 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux`

### Kubernetes Version

```
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.5+k0s
```

### Anything else?

When pod is on a different node:

```
❯ curl -vvvvvvv -k http://192.168.2.110:8443
*   Trying 192.168.2.110:8443...
* connect to 192.168.2.110 port 8443 failed: Operation timed out
* Failed to connect to 192.168.2.110 port 8443 after 75006 ms: Couldn't connect to server
* Closing connection 0
curl: (28) Failed to connect to 192.168.2.110 port 8443 after 75006 ms: Couldn't connect to server
```

When pod is running on the same node:

```
❯ curl -vvvvvvv -k http://192.168.2.110:8443
*   Trying 192.168.2.110:8443...
* Connected to 192.168.2.110 (192.168.2.110) port 8443 (#0)
> GET / HTTP/1.1
> Host: 192.168.2.110:8443
> User-Agent: curl/8.1.2
> Accept: */*
>
< HTTP/1.1 400
< Content-Type: text/plain;charset=UTF-8
< Connection: close
<
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
>I could see that the announcement worked and the node with the lease was exposed but if the pod is not running on that node with the lease it will not handle the traffic.

I wonder if that's expected with `externalTrafficPolicy: Local`. /cc @dylandreimerink

**Comment by dylandreimerink** [comment]
Hmm. So the L2Announcement feature doesn't "implement" `externalTrafficPolicy` as in, we ignore the setting at the present. That means that we might announce the IP from a node that doesn't have a pod for the service, thus violating the wish expressed with `externalTrafficPolicy`. 

The feature relies on the generic service LB functionality to forward traffic received for a given IP. It makes sense to me that when this field is set, any node with a local endpoint will prefer to forward to the local endpoint, but I do not know what is supposed to happen when traffic for a service reaches a node without local endpoint. This seems to indicate we drop the traffic in that case.

Most of the groundwork for implementing this feature has already been laid by https://github.com/cilium/cilium/pull/25477 so it should not be difficult to also implement this for L2 Announcements.

**Comment by mccasian** [comment]
I also want this, since I am struggling with the same issue.

**Comment by ansarhun** [comment]
As this issue is still present should I update something so it's not closed by stale bot?

**Comment by dylandreimerink** [comment]
Marked it as pinned so we don't have to keep it manually alive

**Comment by katlol** [comment]
This would be great to have to allow the ability to keep the original source IP

**Comment by kenlasko** [comment]
Just wondering if this is slated for any future Cilium version. This is the only thing holding me back from migrating to Cilium.

**Comment by kenlasko** [comment]
Wait, so I can get the real IP on the backend without using ```externalTrafficPolicy: Local```??? Just looked this up and will be testing in my lab. Thank you for pointing this out.

**Comment by daleckystepan** [comment]
Yes. I will share my config with you.
`
rke2-cilium:
  rollOutCiliumPods: true
  kubeProxyReplacement: true
  k8sServiceHost: 127.0.0.1
  k8sServicePort: 6443
  routingMode: tunnel
  tunnelProtocol: geneve
  bpf:
    hostLegacyRouting: false
    masquerade: true
  loadBalancer:
    algorithm: random
    mode: dsr
    dsrDispatch: geneve
  socketLB:
    enabled: true
    hostNamespaceOnly: true
  l2announcements:
    enabled: true
  k8sClientRateLimit:
    qps: 10
    burst: 20
  envoy:
    enabled: true
    rollOutPods: true
  operator:
    enabled: true
    rollOutPods: true
  ingressController:
    enabled: true
    loadbalancerMode: shared
    service:
      labels:
        app: cilium-ingressgateway
..
..
..
`

**Comment by kenlasko** [comment]
Thanks for the config. I tried it out, but once I enabled Geneve, everything stopped working. Pods were up, but no traffic was being passed. I suspect Geneve might not play well in a bare-metal environment. I will play around some more to see if I can figure it out, but it looks like I'm still holding out for support for ```externalTrafficPolicy: Local```

**Comment by daleckystepan** [comment]
I took few minutes on my cluster to settle. Sometimes I need to manually restart all Cilium pods in case of this big change. I have it also on-premise.

**Comment by kenlasko** [comment]
Tried it again. I think I might have forgotten to add ```tunnelProtocol: geneve```. This time it worked!  Then I tried AdGuard with ```externalTrafficPolicy: Cluster``` and I was able to get the real host IP instead of the node!  Friggin' fantastic! 

Thank you @daleckystepan for this amazing tip.  For anybody else who's trying this, I didn't use the entire config provided by @daleckystepan. I modified my existing one used for Talos:

```
rollOutCiliumPods: true
# routingMode: native             # Original
routingMode: tunnel               # New
tunnelProtocol: geneve            # New
ipv4NativeRoutingCIDR: 10.0.0.0/9
# autoDirectNodeRoutes: true      # Original
# tunnel: disabled                # Original
bpf:
  hostRouting: true
  masquerade: true
ipam:
  mode: kubernetes
cluster:
  name: lab
  id: 2
loadBalancer:                     # New
  mode: dsr                       # New
  dsrDispatch: geneve             # New
l2announcements:
  enabled: true
  leaseDuration: 6s
  leaseRenewDeadline: 2s
  leaseRetryPeriod: 200ms
envoy:
  enabled: true
  rollOutPods: true
externalIPs:
  enabled: true
extraEnv:
- name: TZ
  value: "America/Toronto"
kubeProxyReplacement: true
k8sServiceHost: localhost
k8sServicePort: 7445
securityContext:
  capabilities:
    ciliumAgent: 
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW 
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState: 
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
gatewayAPI:
  enabled: true
  secretsNamespace:
    create: true
    name: cilium
    sync: false
```
