### ISSUE TITLE
Cilium(1.14.0-rc.0) host firewall feature-set wrong Host firewall interface

### ISSUE THREAD

**Issue by BurlyLuo** [cilium/cilium#27810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

At cilium(1.14.0-rc0) with feature host firewall, when set the the device only with eth1, but after deploy the cilium, we can see
```
root@cilium-host-firewall-control-plane:~# cilium config view | grep device
devices                                        eth1
root@cilium-host-firewall-control-plane:~# exit
exit
root@2204:~/wcni-kind/split/cilium/cilium-host-firewall# kk exec -it ds/cilium -- cilium status 
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.27 (v1.27.3) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    Strict    [eth0 172.18.0.2 (Direct Routing), eth1 12.1.5.11]
Host firewall:           Enabled   [eth0, eth1]
CNI Chaining:            none
Cilium:                  Ok   1.14.0-rc.0 (v1.14.0-rc.0-08239f59)
NodeMonitor:             Listening for events on 128 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok   
IPAM:                    IPv4: 5/254 allocated from 10.0.0.0/24, 
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Host Routing:            BPF
Masquerading:            BPF   [eth0, eth1]   10.0.0.0/8 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       32/32 healthy
Proxy Status:            OK, ip 10.0.0.52, 0 redirects active on ports 10000-20000, Envoy: embedded
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 4095/4095 (100.00%), Flows/s: 14.64   Metrics: Disabled
Encryption:              Disabled        
Cluster health:          3/3 reachable   (2023-08-29T13:59:54Z)
root@2204:~/wcni-kind/split/cilium/cilium-host-firewall# 
```
and test this feature, that also influence the logical about the firewall due to it have an impact about the eth0 itself.
```
cat <<EOF | kubectl apply -f -
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "control-plane-apiserver"
spec:
  description: "permit kube-apiserver 6443"
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/control-plane: ""
  ingress:
  - toPorts:
    - ports:
      - port: "6443"
        protocol: TCP
EOF

cat <<EOF | kubectl apply -f -
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "default-deny"
spec:
  description: "block all traffic"
  nodeSelector: {}
  ingress:
  - fromEntities:
    - cluster
EOF
```
if test at eth0 interface, it's get blocked as well.
```
root@2204:~/wcni-kind/split/cilium/cilium-host-firewall# curl -m 1 -v 172.18.0.2
*   Trying 172.18.0.2:80...
* Connection timed out after 1000 milliseconds
* Closing connection 0
curl: (28) Connection timed out after 1000 milliseconds
root@2204:~/wcni-kind/split/cilium/cilium-host-firewall# 
```
it's kind + containerlab based environment, so you can pull this repo to reproduce the issue.
https://gitee.com/rowan-wcni/wcni-kind/tree/master/split/cilium/cilium-host-firewall
![image](https://github.com/cilium/cilium/assets/35321202/b451cb10-3bd6-4661-bc65-eedba746b98f)

### Cilium Version

```
v1.14.0-rc.0-08239f59
```

### Kernel Version

```
root@2204:~/wcni-kind/split/cilium/cilium-host-firewall# uname -r 
6.2.0-26-generic
```

### Kubernetes Version

```
root@2204:~/wcni-kind/split/cilium/cilium-host-firewall# k get nodes -o wide 
NAME                                 STATUS   ROLES           AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION     CONTAINER-RUNTIME
cilium-host-firewall-control-plane   Ready    control-plane   12h   v1.27.3   172.18.0.3    <none>        Debian GNU/Linux 11 (bullseye)   6.2.0-26-generic   containerd://1.7.1
cilium-host-firewall-worker          Ready    <none>          12h   v1.27.3   172.18.0.2    <none>        Debian GNU/Linux 11 (bullseye)   6.2.0-26-generic   containerd://1.7.1
cilium-host-firewall-worker2         Ready    <none>          12h   v1.27.3   172.18.0.4    <none>        Debian GNU/Linux 11 (bullseye)   6.2.0-26-generic   containerd://1.7.1
root@2204:~/wcni-kind/split/cilium/cilium-host-firewall# 
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
