### ISSUE TITLE
L7  Envoy service mesh does not load balance if service port and pod endpoint port don't match

### ISSUE THREAD

**Issue by sharkztex** [cilium/cilium#27935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We are new to Cilium and running a proof of concept on Proxy Load Balancing for Kubernetes Services https://docs.cilium.io/en/stable/network/servicemesh/envoy-load-balancing/.

Adding the annotation `service.cilium.io/lb-l7: enabled` creates the CEC and confirm that the Envoy configuration is listening on the pods endpoint ports `1433.`

```  {
     "endpoint_config": {
      "@type": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
      "endpoints": [
       {
        "locality": {},
        "lb_endpoints": [
         {
          "endpoint": {
           "address": {
            "socket_address": {
             "address": "10.8.8.16",
             "port_value": 1433
            }
           },
           "health_check_config": {}
          },
          "health_status": "HEALTHY",
          "load_balancing_weight": 1
         },
         {
          "endpoint": {
           "address": {
            "socket_address": {
             "address": "10.8.6.62",
             "port_value": 1433
            }
           },
           "health_check_config": {}
          },
          "health_status": "HEALTHY",
          "load_balancing_weight": 1
         },
         {
          "endpoint": {
           "address": {
            "socket_address": {
             "address": "10.8.38.94",
             "port_value": 1433
            }
           },
           "health_check_config": {}
          },
          "health_status": "HEALTHY",
          "load_balancing_weight": 1
         }
        ]
       }
      ],
```

The service port is `443` where the envoy annotation is applied.

```
  ports:
    - name: https
      protocol: TCP
      appProtocol: https
      port: 443
      targetPort: https
```
Attempting to access the service on the configured service port fails `Connection reset by peer in connection`. 

### Cilium Version

cilium-cli: v0.15.1 compiled with go1.20.4 on windows/amd64
cilium image (default): v1.13.4
cilium image (stable): v1.14.1
cilium image (running): 1.13.5

### Kernel Version

Linux 5.15.117 #1 SMP Sat Aug 5 00:48:44 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.12-eks-2d98532", GitCommit:"0aa16cf4fac4da27b9e9e9ba570b990867f6a3d8", GitTreeState:"clean", BuildDate:"2023-07-28T16:52:04Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}

### Anything else?

Not related, but we also find that adding the annotation to a service which has multiple ports defined, envoy only configures to one of the endpoint ports `8080`
```
    - name: http
      protocol: TCP
      appProtocol: http
      port: 8080
      targetPort: http
    - name: https
      protocol: TCP
      appProtocol: https
      port: 443
      targetPort: https
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sharkztex** [comment]
Figured out a work around, not familiar with Envoy but assume there is a issue on dynamic configuration to read Kubernetes services and Endpoints ports into the Envoy configuration if they don't match.
Using the example above for port `443` amending the created CEC `CiliumEnvoyConfig` and adding the port to the `listenerFilters` traffic is load balanced.
```
listenerFilters:
        - name: envoy.filters.listener.tls_inspector
          typedConfig:
            '@type': >-
              type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
          address:
            socketAddress:
              address: 0.0.0.0
              portValue: 443
```
