### ISSUE TITLE
Unable to whitelist endpoints based on namespace labels

### ISSUE THREAD

**Issue by isala404** [cilium/cilium#27930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I manage a Kubernetes cluster comprising approximately 50 namespaces, each housing various workloads. Within this cluster, I have designated a few 'control' namespaces, and my objective is to enable ingress from all pods within these 'control' namespaces to all the pods residing in other 'worker' namespaces.

To accomplish this, I utilized the https://editor.networkpolicy.io/ tool to generate a Cilium network policy. This network policy incorporates a 'From namespace filter' to specify the desired behavior. However, upon deploying this network policy to the cluster, it did not function as anticipated.

Following Kubernetes manifest to help replicate the issue.

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: server
---
apiVersion: v1
kind: Namespace
metadata:
  name: producer-1
  labels:
    allow-server-connection: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: producer-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: server
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: server
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
---    
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-access-to-server-pods
  namespace: server
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace.labels.allow-server-connection: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-producer
  namespace: producer-1
spec:
  selector:
    matchLabels:
      app: good-producer
  replicas: 1
  template:
    metadata:
      labels:
        app: good-producer
    spec:
      containers:
      - name: curl
        image: curlimages/curl
        command: ["/bin/sh", "-c", "while true; do curl nginx.server.svc.cluster.local; sleep 5; done"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-producer
  namespace: producer-2
spec:
  selector:
    matchLabels:
      app: bad-producer
  replicas: 1
  template:
    metadata:
      labels:
        app: bad-producer
    spec:
      containers:
      - name: curl
        image: curlimages/curl
        command: ["/bin/sh", "-c", "while true; do curl nginx.server.svc.cluster.local; sleep 5; done"]
```

### Cilium Version

v1.13.0 and v1.13.6

### Kernel Version

5.4.0-1106-azure

### Kubernetes Version

1.24.9

### Relevant log output

```shell
$ hubble observe -n server -f
Sep  4 08:50:02.994: producer-2/bad-producer-6c76d4587b-h2bwt:35464 (ID:5932) <> server/nginx-ff6774dc6-cpjx5:80 (ID:8353) policy-verdict:none INGRESS DENIED (TCP Flags: SYN)
Sep  4 08:50:02.994: producer-2/bad-producer-6c76d4587b-h2bwt:35464 (ID:5932) <> server/nginx-ff6774dc6-cpjx5:80 (ID:8353) Policy denied DROPPED (TCP Flags: SYN)
Sep  4 08:50:02.998: producer-1/good-producer-69f756497d-6784v:33776 (ID:7151) <> server/nginx-ff6774dc6-cpjx5:80 (ID:8353) policy-verdict:none INGRESS DENIED (TCP Flags: SYN)
Sep  4 08:50:02.998: producer-1/good-producer-69f756497d-6784v:33776 (ID:7151) <> server/nginx-ff6774dc6-cpjx5:80 (ID:8353) Policy denied DROPPED (TCP Flags: SYN)
```

### Anything else?

<img width="1800" alt="Screenshot 2023-09-04 at 15 32 04" src="https://github.com/cilium/cilium/assets/29277992/44427807-565e-49a4-b9c5-33ecc0c3dcf1">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Thanks for this issue @MrSupiri, and the great reproduction YAML.

Can I ask for some clarification about what you're aiming for though?

You said
> my objective is to enable ingress from all pods within these 'control' namespaces to all the pods residing in other 'worker' namespaces.

If you're aiming to control traffic _from_ the `system` namespace _to_ other namespaces, then you need an _egress_ policy, not an Ingress one.

Currently, the policy you provide controls connections _to_ pods running in the `system` namespace, not pods running in the other namespaces.

Could you clarify what about this setup is not working as you want?

**Comment by MrSupiri** [comment]
In the `system` namespaces (plural), we have a loose network policy that provides egress access to anywhere. However, within the `non-system` namespaces, we deny all ingress and egress traffic by default. Nonetheless, I would like to allow ingress traffic from any pod if it originates from a namespace labeled as `system`.

The YAML provided above reproduces the issue we are experiencing, although it's in a slightly different context. Is there a specific reason why the call from `producer-1/good-producer` cannot reach the `server/nginx`?

**Comment by youngnick** [comment]
I think that it's important to remember that each policy is enforced separately.

So, if `producer-1` and `producer-2` both have egress deny all policies, then that will deny all - the fact that the traffic is allowed by the `server` namespace doesn't matter because the traffic never gets to leave the `producer` pods. So you would also need the inverse policy somewhere (allowing _egress_ from namespaces with the label to the `server` namespace).

**Comment by MrSupiri** [comment]
Hi @youngnick,

Within the `producer-1` and `producer-2` namespaces, I did not include any Cilium nor Kubernetes network policies. Just to be sure, I added an egress policy to both namespaces as specified below. However, the requests coming from both `good-producer` and the `bad-producer` were still denied.

<details>

<summary>Updated Kubernetes YAMLs</summary>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: server
---
apiVersion: v1
kind: Namespace
metadata:
  name: producer-1
  labels:
    allow-server-connection: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: producer-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: server
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: server
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
---    
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-access-to-server-pods
  namespace: server
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace.labels.allow-server-connection: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-producer
  namespace: producer-1
spec:
  selector:
    matchLabels:
      app: good-producer
  replicas: 1
  template:
    metadata:
      labels:
        app: good-producer
    spec:
      containers:
      - name: curl
        image: curlimages/curl
        command: ["/bin/sh", "-c", "while true; do curl nginx.server.svc.cluster.local; sleep 5; done"]
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress
  namespace: producer-1
spec:
  endpointSelector: {}
  ingress:
    - {}
  egress:
    - toEntities:
        - cluster
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-producer
  namespace: producer-2
spec:
  selector:
    matchLabels:
      app: bad-producer
  replicas: 1
  template:
    metadata:
      labels:
        app: bad-producer
    spec:
      containers:
      - name: curl
        image: curlimages/curl
        command: ["/bin/sh", "-c", "while true; do curl nginx.server.svc.cluster.local; sleep 5; done"]
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress
  namespace: producer-2
spec:
  endpointSelector: {}
  ingress:
    - {}
  egress:
    - toEntities:
        - cluster
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
```

</details>

**Comment by youngnick** [comment]
Okay, sorry, I led you wrong the first time. I tried out this config, and found the problem.

In short:
* The `matchLabels` statement in the initial manifest was using `io.kubernetes.pod.namespace.labels.allow-server-connection: "true"`. The correct way to target this is `"k8s:io.cilium.k8s.namespace.labels.allow-server-connection": "true"` (double quotes to be sure that the `:` is escaped correctly). You can see this by getting a shell into a Cilium agent pod and doing `cilium endpoint list`, and then checking the labels visible there.
* However, when you don't specify an _explicit_ namespace in a `CiliumNetworkPolicy`, there's extra rules added - which confine the rule to only acting on endpoints in the `server` namespace. You can see this with `cilium policy get` on a node that's running the `nginx` pod.
* To get the result you want, you need a `CiliumClusterwideNetworkPolicy`:
```yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-access-to-server-pods-cw
spec:
  endpointSelector:
    matchLabels:
       "k8s:io.kubernetes.pod.namespace": "server"
  ingress:
    - fromEndpoints:
        - matchLabels:
            "k8s:io.cilium.k8s.namespace.labels.allow-server-connection": "true"
```

With that Policy in place, things work as you wanted - `good-producer` pods can access `http://nginx.server/`, but `bad-producer` pods cannot.

All the troubleshooting commands I've listed here were covered in the Policy troubleshooting page, available at https://docs.cilium.io/en/stable/security/policy/troubleshooting/. I think that you'll get a speedier resolution of your issue in the future if you spend some time with those docs.
