### ISSUE TITLE
Matching traffic from kube-apiserver does not work as expected

### ISSUE THREAD

**Issue by desy-hh** [cilium/cilium#27967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We are trying to write a NetworkPolicy which matches traffic originating from the `kube-apiserver`.
This is mainly to restrict access to an AdmissionWebhook service running in a seperate namespace as only the apiserver needs to access the webhook.
The cluster is an rke2 setup with project network isolation enabled which means traffic from `kube-system` to the `cert-manager` namespace is blocked because the namespaces are part of different _projects_.
To enable access to the webhook we set up a policy:
```YAML
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-cert-manager
  namespace: cert-manager
spec:
  endpointSelector:
    matchLabels:
      app: webhook
  ingress:
  - fromEntities:
    - kube-apiserver
```
This should match traffic coming from the _node_ the Apiserver Pod is running on  [1].
However, when inspecting traffic on the node running the webhook pod with `hubble`, the traffic originating from the apiserver seems to be assigned the `remote-node` identity and **not** the `kube-apiserver` identity, or even better the apiserver pod identity.
Ideally, we would be able to restrict access to the webhook by targeting the apiserver pod identity and _not_ the `remote-node` identity or the `kube-apiserver` identity.

[1]
https://docs.cilium.io/en/latest/gettingstarted/terminology/#special-identities

### Cilium Version

1.13.2
Chart Values:
```YAML
rke2-cilium:
  tunnel: "vxlan"
  egressGateway:
    enabled: true
    installRoutes: true
  bpf:
    masquerade: true
  enableIPv4Masquerade: true
  kubeProxyReplacement: strict
  k8sServiceHost: 127.0.0.1
  k8sServicePort: 6443
  l7Proxy: true
  nodePort:
    enabled: true
  hubble:
    enabled: true
```

### Kernel Version

5.15.0-78-generic (ubuntu 22)

### Kubernetes Version

1.27.4-rke2r1

### Sysdump

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
