### ISSUE TITLE
Cilium service list empty using kubernetes 1.9.3

### ISSUE THREAD

**Issue by eloycoto** [cilium/cilium#2800]
When I tried to add kubernetes 1.9 in CI I found the following issue: 

Kubectl service list: 
```
NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
kubernetes       ClusterIP   10.96.0.1       <none>        443/TCP           36m
test-nodeport    NodePort    10.98.134.30    <none>        10080:32578/TCP   7m
testds-service   ClusterIP   10.111.130.87   <none>        80/TCP            7m
```

Service list in cilium: 

```
root@k8s1:/home/vagrant#     for cilium in $(kubectl -n kube-system get pods --selector=k8s-app=cilium --output=jsonpath={.items..metadata.name}); do
>         echo "===============${cilium}==============="
>         kubectl -n kube-system exec $cilium cilium service list
>     done
===============cilium-6n9w9===============
ID   Frontend   Backend   
===============cilium-flqtf===============
ID   Frontend   Backend   
```

HTTP call to service works:
```
root@k8s1:/home/vagrant# curl http://10.111.130.87 -v
* Rebuilt URL to: http://10.111.130.87/
*   Trying 10.111.130.87...
* TCP_NODELAY set
* Connected to 10.111.130.87 (10.111.130.87) port 80 (#0)
> GET / HTTP/1.1
> Host: 10.111.130.87
> User-Agent: curl/7.55.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 13 Feb 2018 10:45:28 GMT
< Server: Apache/2.4.25 (Unix)
< Last-Modified: Mon, 11 Jun 2007 18:53:14 GMT
< ETag: "2d-432a5e4a73a80"
< Accept-Ranges: bytes
< Content-Length: 45
< Content-Type: text/html
< 
<html><body><h1>It works!</h1></body></html>
* Connection #0 to host 10.111.130.87 left intact
```

Error message: 
```
level=warning msg="Error while enabling k8s watcher" error="Unable to create custom resource definition: CustomResourceDefinition.apiextensions.k8s.io \"ciliumnetworkpolicies.cilium.io\" is invalid: [spec.validation.openAPIV3Schema.properties[EndpointSelector].$ref: Forbidden: $ref is not supported, spec.validation.$
penAPIV3Schema.properties[specs].items.$ref: Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[IngressRule].properties[toPorts].items.$ref: Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[IngressRule].properties[fromCIDR].items.$ref: Forbidden: $ref is not supp$
rted, spec.validation.openAPIV3Schema.properties[IngressRule].properties[fromCIDRSet].items.$ref: Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[IngressRule].properties[fromEndpoints].items.$ref: Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[IngressRule].p$
operties[fromRequires].items.$ref: Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[LabelSelector].properties[matchExpressions].items.$ref: Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[Service].properties[k8sService].$ref: Forbidden: $ref is not supported, $
pec.validation.openAPIV3Schema.properties[Service].properties[k8sServiceSelector].$ref: Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[L7Rules].properties[kafka].items.$ref: Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[L7Rules].properties[http].items.$ref$
 Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[EgressRule].properties[toCIDR].items.$ref: Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[EgressRule].properties[toCIDRSet].items.$ref: Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.propert$
es[EgressRule].properties[toPorts].items.$ref: Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[EgressRule].properties[toServices].items.$ref: Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[spec].$ref: Forbidden: $ref is not supported, spec.validation.openAPI$
3Schema.properties[Rule].properties[endpointSelector].$ref: Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[Rule].properties[ingress].items.$ref: Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[Rule].properties[labels].items.$ref: Forbidden: $ref is not suppo$
ted, spec.validation.openAPIV3Schema.properties[Rule].properties[egress].items.$ref: Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[ServiceSelector].properties[selector].$ref: Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[PortRule].properties[rules].$ref: $
orbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[PortRule].properties[ports].items.$ref: Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[CIDRRule].properties[cidr].$ref: Forbidden: $ref is not supported, spec.validation.openAPIV3Schema.properties[CIDRRule].prop$
rties[except].items.$ref: Forbidden: $ref is not supported]"                                                                                                                                                                                                                                                                  
```

manifest:
```
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: testds
  namespace: default
spec:
  template:
    metadata:
      labels:
        zgroup: testDS
    spec:
      containers:
      - name: web
        image: cilium/demo-httpd
        ports:
        - containerPort: 80
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: testclient
  namespace: default
spec:
  template:
    metadata:
      labels:
        zgroup: testDSClient
    spec:
      containers:
      - name: web
        image: cilium/demo-client
        command: [ "sleep" ]
        args:
          - "1000h"
---
apiVersion: v1
kind: Service
metadata:
  name: testds-service
spec:
  ports:
  - port: 80
  selector:
    zgroup: testDS
---

apiVersion: v1
kind: Service
metadata:
  name: test-nodeport
spec:
  type: NodePort
  ports:
  - port: 10080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    zgroup: testDS
```

Nodes:
```
root@k8s1:/home/vagrant# kubectl get nodes          
NAME      STATUS    ROLES     AGE       VERSION     
k8s1      Ready     master    41m       v1.9.3      
k8s2      Ready     <none>    23m       v1.9.3      
```
