### ISSUE TITLE
Regression in DSR for some setups

### ISSUE THREAD

**Issue by kvaster** [cilium/cilium#28187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We're using barebone dedicated servers on hetzner for our kubernetes cluster and out setup is:
* each server has static ip (L3 connectivity) - wan address, main ip for the server
* additionaly each server is connected to L2 internal network (called vswitch)
* several wan IP's are assigned to this L2 network - they are assigned/reassigned to servers by keepalived and used as 'load balancer' (i.e. they are used as external-ips to connect to ingress)

DSR is partially broken in some scenarios after following commit: https://github.com/cilium/cilium/commit/78f93188ae0e4a74c3794b517047e33b9c3984c5

Connectivity is broken in the following case: pod  1on node 1 connects to some service via external dns (which binds to external ips) and connect choose external-ip which is assigned to node 2 and service load balancer choose ingress pod (let it be pod 2) which is located exactlt on node 1. In this case pod 2 answer will have destination ip address which is locally assigned to node 1. It was all OK before moving DSR logic out of lxc - source ip address was changed to dsr one and packet was processed. After the change source ip address is unchanged after lxc and packet is consumed by localhost stack - and connectivity is broken.

* pod1 sends packet, src = pod1 internall address on node1, dst = external-ip on node2
* node1 performs masquerading to send packet to wan, src = node1 wan address, dst = external-ip on node2
* node2 receives packet and performs load balancing to service, src = node1 wan address, dst = pod2 internall address on node1
* node1 received packet and it is consumed by pod2, src = node 1 wan address, dst = pod2 internall address on node1
* pod2 sends answer, src = pod2 internall address on node1, dst = node 1 wan address

before change it was:
* node1 performs dsr, src = external-ip on node2, dst = node 1 wan address
* node1 receive packet and performs unmasquerading, src = external-ip on node2, dst = pod 1 internall address on node1
* pod1 receive answer

after change:
* after lxc processing there is no dsr and packet is treated as local and it never gets to to-netdev -> connectivity is broken

### Cilium Version

>= 1.13.3

### Kernel Version

Any, not related.
Tested on 6.5.1.

### Kubernetes Version

Any, not related.
Tested on 1.27.4.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kvaster** [comment]
Attaching my first attempt to fix this problem by myself. This is ipv4 only. This patch is for 1.13.7. With 1.14.2 it is the same, but it doesn't work with wireguard enabled (probably one more problem with local addresses...)

```
diff --git a/bpf/bpf_lxc.c b/bpf/bpf_lxc.c
index b28dc9f52f..7ecf38a8ec 100644
--- a/bpf/bpf_lxc.c
+++ b/bpf/bpf_lxc.c
@@ -1860,8 +1860,40 @@ skip_policy_enforcement:
 	if (ret == CT_NEW || ret == CT_REOPENED) {
 # ifdef ENABLE_DSR
 		/* Clear .dsr flag for old connections: */
-		if (ret == CT_REOPENED && ct_state->dsr)
-			ct_update_dsr(get_ct_map4(tuple), tuple, false);
+  		struct bpf_fib_lookup fib_params = {
+			.family		= AF_INET,
+			.ifindex	= ifindex,
+			.ipv4_src	= tuple->saddr,
+			.ipv4_dst	= tuple->daddr,
+		};
+
+		bool dsr = false;
+
+		if (fib_lookup(ctx, &fib_params, sizeof(fib_params), BPF_FIB_LOOKUP_DIRECT | BPF_FIB_LOOKUP_OUTPUT) == BPF_FIB_LKUP_RET_NOT_FWDED) {
+			__be32 addr = 0;
+			__be16 port = 0;
+			__s8 ext_err = 0;
+			int ret2;
+
+			if (!revalidate_data(ctx, &data, &data_end, &ip4))
+				return DROP_INVALID;
+
+			ret2 = nodeport_extract_dsr_v4(ctx, ip4, tuple, ETH_HLEN + ipv4_hdrlen(ip4), &addr, &port, &dsr);
+			if (ret2 != 0)
+				return ret2;
+
+			if (dsr) {
+				if (snat_v4_create_dsr(tuple, addr, port, &ext_err) < 0)
+					return DROP_INVALID;
+			}
+
+			ct_state_new.dsr = dsr;
+		}
+
+		if (ret == CT_REOPENED && ct_state->dsr != dsr)
+			ct_update_dsr(get_ct_map4(tuple), tuple, dsr);
+
+		if (!dsr)
 # endif /* ENABLE_DSR */
 		{
 			bool node_port =
```

**Comment by kvaster** [comment]
It seems that this patch works only for 'Legacy' host routing and does not work for 'BPF' host routing.

**Comment by brb** [comment]
@kvaster Thanks for the issue. Have you tried solving this issue with the Socket LB? The per-socket LB does the service translation on the client node w/o requiring to go through the DSR / bpf_host path.

**Comment by kvaster** [comment]
@brb, I have socket LB enabled:

```
k8sServiceHost: 10.117.12.100
nodePort:
  directRoutingDevice: wan0.4000

devices: wan+

containerRuntime:
  integration: auto

pmtuDiscovery:
  enabled: true
  
nodeport:
  enabled: true

k8sServicePort: 6443
kubeProxyReplacement: true
ipv4NativeRoutingCIDR: 10.244.0.0/16
masquerade: true

ipam:
  mode: kubernetes

bpf:
  masquerade: false

l7Proxy: false
encryption:
  enabled: true
  type: wireguard
  nodeEncryption: true

socketLB:
  enabled: true

externalIPs:
  enabled: true

tunnel: disabled
autoDirectNodeRoutes: true
loadBalancer:
  mode: dsr
```
