### ISSUE TITLE
HTTPRoute not accepted if namespace selector is used

### ISSUE THREAD

**Issue by tobiaskohlbau** [cilium/cilium#28186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Having the following scenario within a Gateway API enabled cluster:

A Gateway with multiple listeners for different hostnames. One of the listeners needs to allow a HTTPRoute from another namespace. Enabling a namespace selector for one listener breaks every HTTPRoute attached to the gateway.

Gateway definition:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: reproducer
spec:
  gatewayClassName: cilium
  listeners:
  - name: one
    protocol: HTTPS
    port: 443
    hostname: "one.example.org"
    tls:
      certificateRefs:
      - kind: Secret
        name: one-tls
  - name: two
    protocol: HTTPS
    port: 443
    hostname: "two.example.org"
    tls:
      certificateRefs:
      - kind: Secret
        name: two-tls
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
```

HTTPRoute:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: one
spec:
  parentRefs:
  - name: reproducer
    sectionName: one
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: one
      port: 80
```

The HTTP route gets rejected as soon as the second listener is added. The Gateway API specification states the following about _sectionName_:

> SectionName is the name of a section within the target resource. In the following resources, SectionName is interpreted as the following:
>
>Gateway: Listener Name. When both Port (experimental) and SectionName are specified, the name and port of the selected listener must match both specified values.

I read this as such setup of multiple restrictions within a gateway should be explicitly supported. Makes sense as otherwise bringing _allowedRoutes_ into each listener is meaningless.

I would interpret this as an oversight during implementation. Especially cause the [CheckGatewayMatchingSection](https://github.com/cilium/cilium/blob/8b7844deda7198f42948e48d50c4d0fde564e7d8/operator/pkg/gateway-api/routechecks/gateway_checks.go#L204-L207) already checks against _sectionName_. I would suggest [CheckGatewayAllowedForNamespace](https://github.com/cilium/cilium/blob/8b7844deda7198f42948e48d50c4d0fde564e7d8/operator/pkg/gateway-api/routechecks/gateway_checks.go#L28-L80) should get the same check. I've changed a local copy of cilium with the required check to exclude listeners not matching the _sectionName_ and everything is working as expected.

If the current behaviour gets confirmed as not intended I would like to submit a PR for this. The code is already done, but I want to confirm that this changes is welcomed.

### Cilium Version

1.14.2

### Kernel Version

Linux node 5.15.0-1037-raspi #40-Ubuntu SMP PREEMPT Fri Aug 25 16:42:00 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.5+k3s1

### Relevant log output

```shell
HTTPRoute is not allowed to attach to this Gateway due to namespace selector restrictions
```

### Anything else?

The current changes can be found [here](https://github.com/tobiaskohlbau/cilium/commit/103ea9b1230cf37f8cd98af19ae78208e6296052).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AnthonyPoschen** [comment]
im also coming across this issue trying to use a shared gateway. im also running cilium 1.14.2


```yaml
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: ingress
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-cluster
spec:
  gatewayClassName: cilium
  listeners:
    - name: http-one
      protocol: HTTP
      port: 80
      hostname: "one.example.com"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              toolkit.fluxcd.io/tenant: one
    - name: http-one-shorthand
      protocol: HTTP
      port: 80
      hostname: "o.home.arpa"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              toolkit.fluxcd.io/tenant: one
    - name: http-two
      protocol: HTTP
      port: 80
      hostname: "two.com"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
    - name: https-two
      protocol: HTTPS
      port: 443
      hostname: "two.com"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              toolkit.fluxcd.io/tenant: two
      tls:
        certificateRefs:
          - kind: Secret
            name: two-cert
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-redirect
  namespace: kube-system
spec:
  parentRefs:
    - name: ingress
      namespace: kube-system
      sectionName: http-two
  hostnames:
    - "two.com"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
```

i see the following on the http route
```
❯ kubectl get httproute -n kube-system -o yaml
apiVersion: v1
items:
- apiVersion: gateway.networking.k8s.io/v1beta1
  kind: HTTPRoute
  metadata:
    creationTimestamp: "2023-09-22T12:44:14Z"
    generation: 2
    labels:
      kustomize.toolkit.fluxcd.io/name: k8s
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: http-redirect
    namespace: kube-system
    resourceVersion: "12240966"
    uid: aadd9cb7-4414-4c72-9388-5a42c0bfc0f4
  spec:
    hostnames:
    - two.com
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ingress
      namespace: kube-system
      sectionName: http-two
    rules:
    - filters:
      - requestRedirect:
          scheme: https
          statusCode: 301
        type: RequestRedirect
      matches:
      - path:
          type: PathPrefix
          value: /
  status:
    parents:
    - conditions:
      - lastTransitionTime: "2023-09-22T12:46:00Z"
        message: HTTPRoute is not allowed to attach to this Gateway due to namespace
          selector restrictions
        observedGeneration: 2
        reason: NotAllowedByListeners
        status: "False"
        type: Accepted
      - lastTransitionTime: "2023-09-22T12:46:00Z"
        message: Service reference is valid
        observedGeneration: 2
        reason: ResolvedRefs
        status: "True"
        type: ResolvedRefs
      controllerName: io.cilium/gateway-controller
      parentRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        name: ingress
        namespace: kube-system
        sectionName: http-amfencing
kind: List
metadata:
  resourceVersion: ""
```

**Comment by AnthonyPoschen** [comment]
one thing to note as well when i switch the selector to "All"

The http redirect rule is also bound to the https listener and i get the https website redirecting in on itself constantly.

@tobiaskohlbau i suspect any patch should be a bit more holistic in it's checks as i believe its more broken than expected.

**Comment by sayboras** [comment]
thanks both for reporting this issue, temporarily assigned to myself so that I can triage this later.

**Comment by aleksanderaleksic** [comment]
Can confirm I have the same issue, adding my config as well if it is of any help.
With the config below I also get a redirect loop even if I use the `https` scheme.
```
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: public
  namespace: gateway-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - hostname: "*.example.com" #Replaced by kustomize
      name: example-com-tls
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: letsencrypt-tls
            kind: Secret
            group: ""
            namespace: gateway-system
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-filter-redirect
  namespace: gateway-system
spec:
  parentRefs:
    - name: public
      sectionName: http
  hostnames:
    - "*.example.com"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: books-app
  namespace: books
spec:
  hostnames:
  - books.example.com
  parentRefs:
    - name: public
      namespace: gateway-system
      kind: Gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /details
      backendRefs:
        - name: details
          port: 9080
    - matches:
        - headers:
            - type: Exact
              name: magic
              value: foo
          queryParams:
            - type: Exact
              name: great
              value: example
          path:
            type: PathPrefix
            value: /
          method: GET
      backendRefs:
        - name: productpage
          port: 9080

```

**Comment by sayboras** [comment]
:wave: Seems like the issue is fixed recently in main with the PR https://github.com/cilium/cilium/pull/27309. 

I have tried to test with the below manifest, but unable to replicate the issue.

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: reproducer
spec:
  gatewayClassName: cilium
  listeners:
  - name: one
    protocol: HTTPS
    port: 443
    hostname: "one.example.org"
    tls:
      certificateRefs:
      - kind: Secret
        name: one-tls
# Un-comment and apply again later
#  - name: two
#    protocol: HTTPS
#    port: 443
#    hostname: "two.example.org"
#    tls:
#      certificateRefs:
#      - kind: Secret
#        name: two-tls
#    allowedRoutes:
#      namespaces:
#        from: Selector
#        selector:
#          matchLabels:
#            kubernetes.io/metadata.name: kube-system
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: one
spec:
  parentRefs:
  - name: reproducer
    sectionName: one
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: details
      port: 9080
```


```shell
$ kg httproute one -o json | jqs
{
  "parents": [
    {
      "conditions": [
        {
          "lastTransitionTime": "2023-10-10T12:30:37Z",
          "message": "Accepted HTTPRoute",
          "observedGeneration": 2,
          "reason": "Accepted",
          "status": "True",
          "type": "Accepted"
        },
        {
          "lastTransitionTime": "2023-10-10T12:30:37Z",
          "message": "Service reference is valid",
          "observedGeneration": 2,
          "reason": "ResolvedRefs",
          "status": "True",
          "type": "ResolvedRefs"
        }
      ],
      "controllerName": "io.cilium/gateway-controller",
      "parentRef": {
        "group": "gateway.networking.k8s.io",
        "kind": "Gateway",
        "name": "reproducer",
        "sectionName": "one"
      }
    }
  ]
}
```

**Comment by sayboras** [comment]
The redirect loop issue might not be related to the issue reported in the first post.

I am watching the upstream issue, so I would have expected there would be some change in the upstream API.

https://github.com/kubernetes-sigs/gateway-api/issues/1185

**Comment by sayboras** [comment]
Thanks for your above manifest, let me give it a try.

**Comment by AnthonyPoschen** [comment]
> The redirect loop issue might not be related to the issue reported in the first post.
> 
> I am watching the upstream issue, so I would have expected there would be some change in the upstream API.
> 
> [kubernetes-sigs/gateway-api#1185](https://github.com/kubernetes-sigs/gateway-api/issues/1185)

im not sure if what i reported is related to that issue as the Origional post mentioned this as a workaround

>AFAIK to avoid this you'd need to create separate HTTPRoutes, one with the redirect and one without, and either bind them to separate Gateways or use a combination of allowedRoutes configuration and namespaced backendRefs to bind them to only one Listener on a single Gateway.

i believe my manifests above meet that condition of a HTTP route per listener to avoid a loop scenario so it wouldn't be related to that upstream issue which is more a feature request to modify behaviour when you intentionally loop back into the same listener.

**Comment by youngnick** [comment]
Thanks for the multiple manifests @AnthonyPoschen. It does look like we have a problem somewhere with the `sectionName` handling - in that last example, there should be no redirect loop because one HTTPRoute should be binding to the `http-example` Listener, and one to the `https-example` Listener.

@sayboras, this seems like it could probably use a conformance test upstream once we figure it out as well.

**Comment by sayboras** [comment]
I can reproduce this issue locally, working on how we can fix it now. Thanks a lot for your details.

**Comment by rouke-broersma** [comment]
@sayboras I am still getting this on 1.14.4 with this gateway config:

```yaml
spec:
  gatewayClassName: cilium
  listeners:
  - name: web-http
    protocol: HTTP
    port: 80
    hostname: '*.example.com'
    allowedRoutes:	
      namespaces:	
        from: Same
  - name: web-https
    protocol: HTTPS
    port: 443
    hostname: '*.example.com'
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - group: ''	
        kind: Secret	
        name: star-example-com-tls
  - name: ldaps
    protocol: TLS
    port: 636
    hostname: 'ldap.example.com'
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            use-private-gateway-ldaps: 'true'
    tls:
      mode: Terminate
      certificateRefs:
      - group: ''	
        kind: Secret	
        name: ldap-example-com-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tls-upgrade
spec:
  parentRefs:
  - name: private-gateway
    sectionName: web-http
  hostnames:
  - '*.example.com'
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        port: 443
```

Once I delete the listeners `ldaps` and `web-https` the `tls-upgrade` HTTPRoute deployed in the same namespace as the gateway is accepted. Once I delete `web-http` and `web-https` the `ldaps` listener accepts a TLSRoute from a namespace that has the label `use-private-gateway-ldaps: 'true'`. With all three listeners deployed all routes are denied.

Status of `tls-upgrade`:

```yaml
status:	
  parents:	
    - conditions:	
        - lastTransitionTime: '2023-11-26T13:22:30Z'	
          message: >-	
            HTTPRoute is not allowed to attach to this Gateway due to namespace	
            selector restrictions	
          observedGeneration: 1	
          reason: NotAllowedByListeners	
          status: 'False'	
          type: Accepted	
        - lastTransitionTime: '2023-11-26T13:22:30Z'	
          message: Service reference is valid	
          observedGeneration: 1	
          reason: ResolvedRefs	
          status: 'True'	
          type: ResolvedRefs	
      controllerName: io.cilium/gateway-controller	
      parentRef:	
        group: gateway.networking.k8s.io	
        kind: Gateway	
        name: private-gateway	
        sectionName: web-http
```

**Comment by tobiaskohlbau** [comment]
Unfortunately I'm unable to validate the fix myself as this was only for a homelab and I moved to a simpler setup. Maybe I will find time to recreate the setup.

**Comment by youngnick** [comment]
@rouke-broersma I don't think this fix is included in 1.14.4, it has not been backported yet. So it will be included in `main`, if you can test there, or it should be included in 1.14.5 when that is released (@sayboras has already marked the PR for backport).

**Comment by rouke-broersma** [comment]
@youngnick there are two issues and two mentioned PRs for this issue.

https://github.com/cilium/cilium/pull/27309 is the issue I'm having, and I think that was included in 1.14.2 so should be fixed, but I'm still hitting it in 1.14.4.

The other issue https://github.com/cilium/cilium/pull/29115 is not yet backported but I'm not hitting that issue.

**Comment by youngnick** [comment]
Thanks for that explanation @rouke-broersma. @sayboras, did you want to take another look here?

**Comment by sayboras** [comment]
Somehow this didn't come up in my GitHub notification, re-open the issue now.

**Comment by skillcoder** [comment]
Face same problem on [1.15.0-rc.0](https://github.com/cilium/cilium/releases/tag/v1.15.0-rc.0)
I have 2 listeners for different hostnames in different namespaces
This works:
```
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
        from: All
```
And this not:
```
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: argocd
```
