### ISSUE TITLE
cilium daemon hangs at "Restoring... endpoints" phase during startup with local-dns lrp applied

### ISSUE THREAD

**Issue by chestack** [cilium/cilium#28274]
### Cilium Version

v1.14.0

### Kernel Version

4.19.90

### Kubernetes Version

v1.26.4

### Relevant log output

cilium agent    **could not finish restoring endpoints** 
```
level=info msg="Enabling k8s event listener" subsys=k8s-watcher
level=info msg="Removing stale endpoint interfaces" subsys=daemon
level=info msg="Waiting until local node addressing before starting watchers depending on it" subsys=k8s-watcher
level=info msg="Skipping kvstore configuration" subsys=daemon
level=info msg="Restored router address from node_config" file=/var/run/cilium/state/globals/node_config.h ipv4=192.168.0.39 ipv6="<nil>" subsys=node
level=warning msg="Without socket lookup kernel functionality, BPF datapath cannot prevent potential loop caused by local-redirectservice translation. Needs kernel version >= 5.1" subsys=redirectpolicy
level=info msg="Restoring endpoints..." subsys=daemon

```

cilium agent    **could not finish adding local redirect policy**
```
level=info msg="  --enable-local-redirect-policy='true'" subsys=daemon
level=debug msg="waiting for cache to synchronize" kubernetesResource="crd:ciliumlocalredirectpolicies.cilium.io" subsys=k8s
level=debug msg="cache synced" kubernetesResource="crd:ciliumlocalredirectpolicies.cilium.io" subsys=k8s
level=debug msg="waiting for cache to synchronize" kubernetesResource="cilium/v2::CiliumLocalRedirectPolicy" subsys=k8s
level=debug msg="Error while inserting service in LB map" error="local-redirect service exists for frontend {{10.222.0.3 {TCP 53} 0} 0}, skip update for svc kube-system/coredns" k8sNamespace=kube-system k8sSvcName=coredns subsys=k8s-watcher
level=debug msg="Add CiliumLocalRedirectPolicy" ciliumLocalRedirectPolicyName=nodelocaldns k8sApiVersion=cilium.io/v2 k8sNamespace=kube-system k8sUID=76a588cd-d5b3-4e67-909a-378adfae697c subsys=k8s-watcher
level=warning msg="Without socket lookup kernel functionality, BPF datapath cannot prevent potential loop caused by local-redirectservice translation. Needs kernel version >= 5.1" subsys=redirectpolicy
level=debug msg="Add local redirect policy" k8sNamespace=kube-system k8sSvcID=kube-system/coredns lrpBackendPorts="[{{UDP 53} dns} {{TCP 53} dns-tcp}]" lrpFrontendType=1 lrpFrontends="[]" lrpLocalEndpointSelector="{\"matchLabels\":{\"any:k8s-app\":\"node-local-dns\"}}" lrpName=nodelocaldns lrpType=2 subsys=redirectpolicy
```

maybe  'restoring endpoints' and ‘adding local redirect policy’  run into deadlock

### Anything else?

```
apiVersion: "cilium.io/v2"
kind: CiliumLocalRedirectPolicy
metadata:
  name: "nodelocaldns"
  namespace: kube-system
spec:
  redirectFrontend:
    serviceMatcher:
      serviceName: coredns
      namespace: kube-system
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: node-local-dns
    toPorts:
      - port: "53"
        name: dns
        protocol: UDP
      - port: "53"
        name: dns-tcp
        protocol: TCP
```

local-dns lrp could be applied and works well  if cilium agent pod already running.

cilium agent pod is able to start to be ready if lrp deleted.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
