### ISSUE TITLE
cilium-operator delete CEC cilium-ingress when other ingressclass resources are created

### ISSUE THREAD

**Issue by ese** [cilium/cilium#28289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Having cilium up and running using its ingress feature all works fine. We have several ingress objects serving different services. 
We are also running other ingress controller listening for ingress resources with a specific ingressclass.

When we create an ingress resources with an ingressclass does not belong to cilium, the `ciliumEnvoyConfig` resource in `kube-system` called `cilium-ingress` is deleted making all ingress routing by cilium fail.

This CEC resource is recreated only if the `cilium-operator` pod is restarted 

In addition, we have also noticed that the `cilium-ingress` CEC is deleted and created every time cilium-operator is restarted. Could it be safer mantain a reconcilation loop with this object and just update it in case it already exists instead delete? Furthermore being a managed resource, I would expect it being recreated in case of accidental deletion or manipulation.

### Cilium Version

cilium image (running): v1.14.1

### Kernel Version

5.15.128

### Kubernetes Version

v1.27.4-eks-2d98532

### Relevant log output

```shell
level=debug msg="Handling ingress added event" ingress=test k8sNamespace=default subsys=ingress-controller

level=debug msg="Generated model for ingress" forcedShared=false ingress=test k8sNamespace=default model="REDACTED" subsys=ingress-controller

level=debug msg="Translated resources for ingress" ciliumEnvoyConfig=REDACTED endpoint=nil ingress=test k8sNamespace=default service=nil subsys=ingress-controller

level=debug msg="Deleted object which was no longer tracked" obj="&{{ } {cilium-ingress  kube-system  [....] subsys=ingress-controller

level=debug msg="Skipping ingress as it is not the cilium class or default" ingress=test k8sNamespace=default subsys=ingress-controller
```

### Anything else?

example ingress triggering the issue 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  annotations:
    kubernetes.io/ingress.class: core
  labels:
    app: example
  name: example-ingress
  namespace: default
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          service:
            name: serviceA
            port:
              number: 443
        path: /test
        pathType: ImplementationSpecific
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
