### ISSUE TITLE
when  kubeproxyreplace enable, cilium work with istio (sidecar mode) well

### ISSUE THREAD

**Issue by yylt** [cilium/cilium#28304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

deploy istio(1.18.2) and cilium(1.14.1),  cilium as default cni
test istio virtualService and DestnationRule and expect it not work, depend on https://docs.cilium.io/en/stable/network/servicemesh/istio/#cilium-configuration descriped, when kubeproxyreplacement enabled, istio should not work 

and cilium boot log is here:  https://gist.github.com/yylt/8794fa9a5219e62c35268c740b2225b8#file-bootlog

```
# cilium status
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.26+ (v1.26.4) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    True   [ens10 192.168.100.107, ens3 192.168.0.28 (Direct Routing)]
Host firewall:           Disabled
CNI Chaining:            none
Cilium:                  Ok   1.14.0 (v1.14.0-cb7859de)
NodeMonitor:             Listening for events on 8 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok   
IPAM:                    IPv4: 7/0 allocated, 
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Host Routing:            Legacy
Masquerading:            Disabled
Controller Status:       43/43 healthy
Proxy Status:            OK, ip 192.168.100.126, 0 redirects active on ports 10000-20000, Envoy: embedded
Global Identity Range:   min 256, max 65535
Hubble:                  Ok                Current/Max Flows: 4095/4095 (100.00%), Flows/s: 11.30   Metrics: Disabled
Encryption:              Disabled          
Cluster health:          10/10 reachable  

---
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
apiVersion: v1
data:
  auto-direct-node-routes: "false"
  bpf-map-dynamic-size-ratio: "0.0025"
  cgroup-root: /run/cilium/cgroupv2
  cluster-name: default
  custom-cni-conf: "true"
  debug: "false"
  disable-cnp-status-updates: "true"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "false"
  enable-endpoint-routes: "true"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv4-masquerade: "false"
  enable-ipv6: "false"
  enable-ipv6-masquerade: "false"
  enable-remote-node-identity: "true"
  enable-well-known-identities: "false"
  hubble-disable-tls: "true"
  hubble-listen-address: :4244
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  kube-proxy-replacement: "true"
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  preallocate-bpf-maps: "false"
  read-cni-conf: /tmp/cni-configuration/cni-config
  routing-mode: native
  sidecar-istio-proxy-image: cilium/istio_proxy
  tunnel: ""
  write-cni-conf-when-ready: /host/etc/cni/net.d/05-cilium.conf
```

below is istio test case 

```

---
apiVersion: v1
kind: Namespace
metadata:
  name: istiotest
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: istiotest
  labels:
    app: helloworld
    service: helloworld
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
  namespace: istiotest
  labels:
    app: helloworld
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v2
  namespace: istiotest
  labels:
    app: helloworld
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v2
  template:
    metadata:
      labels:
        app: helloworld
        version: v2
    spec:
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v2
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
  namespace: istiotest
spec:
  hosts:
  - helloworld
  http:
  - route:
    - destination:
        host: mockserver
        subset: v1
      weight: 50
    - destination:
        host: mockserver
        subset: v2
      weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld
  namespace: istiotest
spec:
  host: helloworld
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  namespace: istiotest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
      - name: sleep
        image: docker.io/curlimages/curl
        command: ["/bin/sleep", "infinity"] # while true; do curl mockserver;done
        imagePullPolicy: IfNotPresent
```
 
like discussion at https://github.com/istio/istio/issues/27619

### Cilium Version

```
$ cilium version
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
Client: 1.14.0 cb7859de 2023-09-18T16:07:41+08:00 go version go1.20.5 linux/amd64
Daemon: 1.14.0 cb7859de 2023-09-18T16:07:41+08:00 go version go1.20.5 linux/amd64
```

### Kernel Version

```
# uname -a
Linux eks.novalocal 4.19.90-25.27.v2101.ky10.x86_64 #1 SMP Fri May 26 15:05:05 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.4", GitCommit:"d9192c2e8ba99fbc7788120e5e79270a50f5e45f", GitTreeState:"clean", BuildDate:"2023-08-08T09:33:21Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.4", GitCommit:"d9192c2e8ba99fbc7788120e5e79270a50f5e45f", GitTreeState:"clean", BuildDate:"2023-08-08T09:32:55Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
