### ISSUE TITLE
Connectivity Test

### ISSUE THREAD

**Issue by jejikenwogu** [cilium/cilium#28329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm trying to get started with Cilium in an EKS cluster.  I installed Cilium using Helm and these values:
```
# -- Affinity for cilium-agent.
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - topologyKey: kubernetes.io/hostname
      labelSelector:
        matchLabels:
          k8s-app: cilium
    - topologyKey: kubernetes.io/hostname
      labelSelector:
        matchLabels:
          k8s-app: cilium
# adding nodeAffinity to fix connectivity test: external test pod
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cilium.io/no-schedule
          operator: NotIn
          values:
          - "true"

# -- Affinity for cilium-operator
operator:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchLabels:
            io.cilium/app: operator
# adding nodeAffinity to fix connectivity test: external test pod
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cilium.io/no-schedule
            operator: NotIn
            values:
            - "true"

eni:
  enabled: true
ipam:
  mode: eni
egressMasqueradeInterfaces: eth0
routingMode: native
~
```

I then start the connectivity test and it hangs on the health test.  Most other tests seem to complete fine.
```
23-09-29 2:42:50 ~ $ cilium connectivity test --test 'health' -v --all-flows
ℹ️  Monitor aggregation detected, will skip some flow validation steps
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for deployment cilium-test/client to become ready...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for deployment cilium-test/client2 to become ready...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for deployment cilium-test/echo-same-node to become ready...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for deployment cilium-test/echo-other-node to become ready...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for deployment cilium-test/echo-external-node to become ready...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for CiliumEndpoint for pod cilium-test/client-7dccdf9bdf-h9p5w to appear...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for CiliumEndpoint for pod cilium-test/client2-5fd767c97f-2fltx to appear...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for pod cilium-test/client-7dccdf9bdf-h9p5w to reach DNS server on cilium-test/echo-same-node-8bc9d945d-d4tk2 pod...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for pod cilium-test/client2-5fd767c97f-2fltx to reach DNS server on cilium-test/echo-same-node-8bc9d945d-d4tk2 pod...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for pod cilium-test/client-7dccdf9bdf-h9p5w to reach DNS server on cilium-test/echo-other-node-758b7cdd7d-ngxbw pod...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for pod cilium-test/client2-5fd767c97f-2fltx to reach DNS server on cilium-test/echo-other-node-758b7cdd7d-ngxbw pod...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for pod cilium-test/client-7dccdf9bdf-h9p5w to reach default/kubernetes service...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for pod cilium-test/client2-5fd767c97f-2fltx to reach default/kubernetes service...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for CiliumEndpoint for pod cilium-test/echo-other-node-758b7cdd7d-ngxbw to appear...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for CiliumEndpoint for pod cilium-test/echo-same-node-8bc9d945d-d4tk2 to appear...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for Service cilium-test/echo-other-node to become ready...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for Service cilium-test/echo-other-node to be synchronized by Cilium pod kube-system/cilium-rfbbg
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for Service cilium-test/echo-same-node to become ready...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for Service cilium-test/echo-same-node to be synchronized by Cilium pod kube-system/cilium-rfbbg
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for NodePort 100.66.155.69:32756 (cilium-test/echo-same-node) to become ready...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for NodePort 100.66.155.69:32206 (cilium-test/echo-other-node) to become ready...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for NodePort 100.66.142.63:32206 (cilium-test/echo-other-node) to become ready...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for NodePort 100.66.142.63:32756 (cilium-test/echo-same-node) to become ready...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for NodePort 100.66.167.15:32206 (cilium-test/echo-other-node) to become ready...
⌛ [arn:aws:eks:us-west-2:707472444021:cluster/pokern-johnej] Waiting for NodePort 100.66.167.15:32756 (cilium-test/echo-same-node) to become ready...
ℹ️  Skipping IPCache check
🔭 Enabling Hubble telescope...
⚠️  Unable to contact Hubble Relay, disabling Hubble telescope and flow validation: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:4245: connect: connection refused"
ℹ️  Expose Relay locally with:
   cilium hubble enable
   cilium hubble port-forward&
ℹ️  Cilium version: 1.14.2
🏃 Running tests...
[=] Skipping Test [no-policies] (skipped by user)
[=] Skipping Test [no-policies-extra] (skipped by user)
[=] Skipping Test [allow-all-except-world] (skipped by user)
[=] Skipping Test [client-ingress] (skipped by user)
[=] Skipping Test [client-ingress-knp] (skipped by user)
[=] Skipping Test [allow-all-with-metrics-check] (skipped by user)
[=] Skipping Test [all-ingress-deny] (skipped by user)
[=] Skipping Test [all-ingress-deny-knp] (skipped by user)
[=] Skipping Test [all-egress-deny] (skipped by user)
[=] Skipping Test [all-egress-deny-knp] (skipped by user)
[=] Skipping Test [all-entities-deny] (skipped by user)
[=] Skipping Test [cluster-entity] (skipped by user)
[=] Skipping Test [host-entity] (skipped by user)
[=] Skipping Test [echo-ingress] (skipped by user)
[=] Skipping Test [echo-ingress-knp] (skipped by user)
[=] Skipping Test [client-ingress-icmp] (skipped by user)
[=] Skipping Test [client-egress] (skipped by user)
[=] Skipping Test [client-egress-knp] (skipped by user)
[=] Skipping Test [client-egress-expression] (skipped by user)
[=] Skipping Test [client-egress-expression-knp] (skipped by user)
[=] Skipping Test [client-with-service-account-egress-to-echo] (skipped by user)
[=] Skipping Test [client-egress-to-echo-service-account] (skipped by user)
[=] Skipping Test [to-entities-world] (skipped by user)
[=] Skipping Test [to-cidr-external] (skipped by user)
[=] Skipping Test [to-cidr-external-knp] (skipped by user)
[=] Skipping Test [echo-ingress-from-other-client-deny] (skipped by user)
[=] Skipping Test [client-ingress-from-other-client-icmp-deny] (skipped by user)
[=] Skipping Test [client-egress-to-echo-deny] (skipped by user)
[=] Skipping Test [client-ingress-to-echo-named-port-deny] (skipped by user)
[=] Skipping Test [client-egress-to-echo-expression-deny] (skipped by user)
[=] Skipping Test [client-with-service-account-egress-to-echo-deny] (skipped by user)
[=] Skipping Test [client-egress-to-echo-service-account-deny] (skipped by user)
[=] Skipping Test [client-egress-to-cidr-deny] (skipped by user)
[=] Skipping Test [client-egress-to-cidr-deny-default] (skipped by user)
[=] Test [health]
  [-] Scenario [health/cilium-health]
  [.] Action [health/cilium-health/cilium-5l6h7]
⚠️  cilium-health probe failed: "command terminated with exit code 1", stdout: {"" '\x00' '\x00'}, retrying...
⚠️  cilium-health probe failed: "command terminated with exit code 1", stdout: {"" '\x00' '\x00'}, retrying...
⚠️  cilium-health probe failed: "command terminated with exit code 1", stdout: {"" '\x00' '\x00'}, retrying...
⚠️  cilium-health probe failed: "command terminated with exit code 1", stdout: {"" '\x00' '\x00'}, retrying...
⚠️  cilium-health probe failed: "command terminated with exit code 1", stdout: {"" '\x00' '\x00'}, retrying...
⚠️  cilium-health probe failed: "command terminated with exit code 1", stdout: {"" '\x00' '\x00'}, retrying...
⚠️  cilium-health probe failed: "command terminated with exit code 1", stdout: {"" '\x00' '\x00'}, retrying...
⚠️  cilium-health probe failed: "command terminated with exit code 1", stdout: {"" '\x00' '\x00'}, retrying...
⚠️  cilium-health probe failed: "command terminated with exit code 1", stdout: {"" '\x00' '\x00'}, retrying...
⚠️  cilium-health probe failed: "command terminated with exit code 1", stdout: {"" '\x00' '\x00'}, retrying...
⚠️  cilium-health probe failed: "command terminated with exit code 1", stdout: {"" '\x00' '\x00'}, retrying...
^CInterrupt received, cancelling tests...
⚠️  cilium-health probe failed: "context canceled", stdout: {"" '\x00' '\x00'}, retrying...
🟥 cilium-health probe on 'kube-system/cilium-5l6h7' failed: context canceled
  [.] Action [health/cilium-health/cilium-8td6s]
⚠️  cilium-health probe failed: "error sending request: Post \"https://239C5701E009F624C18F6E68563D6620.gr7.us-west-2.eks.amazonaws.com/api/v1/namespaces/kube-system/pods/cilium-8td6s/exec?command=cilium-health&command=status&command=--probe&command=-o%3Djson&container=cilium-agent&stderr=true&stdout=true\": dial tcp: lookup 239C5701E009F624C18F6E68563D6620.gr7.us-west-2.eks.amazonaws.com: operation was canceled", stdout: {"" '\x00' '\x00'}, retrying...
🟥 cilium-health probe on 'kube-system/cilium-8td6s' failed: error sending request: Post "https://239C5701E009F624C18F6E68563D6620.gr7.us-west-2.eks.amazonaws.com/api/v1/namespaces/kube-system/pods/cilium-8td6s/exec?command=cilium-health&command=status&command=--probe&command=-o%3Djson&container=cilium-agent&stderr=true&stdout=true": dial tcp: lookup 239C5701E009F624C18F6E68563D6620.gr7.us-west-2.eks.amazonaws.com: operation was canceled
  [.] Action [health/cilium-health/cilium-rfbbg]
⚠️  cilium-health probe failed: "error sending request: Post \"https://239C5701E009F624C18F6E68563D6620.gr7.us-west-2.eks.amazonaws.com/api/v1/namespaces/kube-system/pods/cilium-rfbbg/exec?command=cilium-health&command=status&command=--probe&command=-o%3Djson&container=cilium-agent&stderr=true&stdout=true\": dial tcp: lookup 239C5701E009F624C18F6E68563D6620.gr7.us-west-2.eks.amazonaws.com: operation was canceled", stdout: {"" '\x00' '\x00'}, retrying...
🟥 cilium-health probe on 'kube-system/cilium-rfbbg' failed: error sending request: Post "https://239C5701E009F624C18F6E68563D6620.gr7.us-west-2.eks.amazonaws.com/api/v1/namespaces/kube-system/pods/cilium-rfbbg/exec?command=cilium-health&command=status&command=--probe&command=-o%3Djson&container=cilium-agent&stderr=true&stdout=true": dial tcp: lookup 239C5701E009F624C18F6E68563D6620.gr7.us-west-2.eks.amazonaws.com: operation was canceled
connectivity test failed: context canceled
```

Any idea why my health check is getting stuck?

### Cilium Version

1.14.2

### Kernel Version

Laptop:
Darwin MacBook-Pro 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 arm64

k8s cluster:
Linux ip-100-66-142-51.usw2.zynga.com 5.4.226-129.415.amzn2.aarch64 #1 SMP Fri Dec 9 12:54:10 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

1.26

### Sysdump

[cilium-sysdump-20230929-035315.zip](https://github.com/cilium/cilium/files/12764414/cilium-sysdump-20230929-035315.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
