### ISSUE TITLE
helm, kustomize: mapping key "routing-mode" already defined

### ISSUE THREAD

**Issue by mkianpour** [cilium/cilium#28376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

An error happens when our ArgoCD wants to install `cilium 1.14.2`. We tried the same command as ArgoCD uses and we were able to reproduce the error.
The command is:
```kustomize build k8s-manifests/overlays/env/cilium --enable-helm```
The file that `kustomize` uses to install cilium has this configuration:
```
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: cilium
name: cilium
version: 1.14.2
repo: https://helm.cilium.io/
releaseName: cilium
valuesFile: ./value-overrides.yaml
namespace: kube-system
includeCRDs: true
```
and the `value-overrides.yaml` has the following:
```
eni:
  # -- Enable Elastic Network Interface (ENI) integration.
  enabled: true

ipam:
  # -- Configure IP Address Management mode.
  # ref: https://docs.cilium.io/en/stable/network/concepts/ipam/
  mode: "eni"

# -- Limit iptables-based egress masquerading to interface selector.
egressMasqueradeInterfaces: "eth0"

l7Proxy: false

encryption:
  # -- Enable transparent network encryption.
  enabled: true

  # -- Encryption method. Can be either ipsec or wireguard.
  type: wireguard

# -- Enable native-routing mode or tunneling mode.
# @default -- `"tunnel"`
routingMode: "native"
tunnel: "disabled"
kubeProxyReplacement: "strict"
k8sServiceHost: "foobar.us-east-1.eks.amazonaws.com"
k8sServicePort: "443"
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
```

The error we get is:
```Error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 100: mapping key "routing-mode" already defined at line 99
```

We didn't have this problem with `cilium 1.13.6`

### Cilium Version

1.14.2

### Kernel Version

Kubernetes

### Kubernetes Version

EKS 1.24

### Relevant log output

```shell
Error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 100: mapping key "routing-mode" already defined at line 99
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
