### ISSUE TITLE
AWS CNI Chaining with Wireguard Encryption on EKS 1.28 IPv6 cluster

### ISSUE THREAD

**Issue by archoversight** [cilium/cilium#28387]
### Test Category

Other

### Test Details

I was able to deploy Cillium on an EKS cluster (version 1.28) using aws-cni chaining with the Wireguard encryption and have traffic routed between pods be successfully encrypted.

values.yaml:
```
cni:
  chainingMode: aws-cni
enableIPv4Masquerade: false
enableIPv6Masquerade: false
ipv4:
  enabled: true
ipv6:
  enabled: true
tunnel: disabled
endpointRoutes:
  enabled: true
encryption:
  enabled: true
  type: wireguard
routingMode: native
```

```
helm install cilium cilium/cilium --version 1.14.2 --values values.yaml --namespace kube-system
```

```
kubectl get pods --all-namespaces -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,HOSTNETWORK:.spec.hostNetwork --no-headers=true | grep '<none>' | awk '{print "-n "$1" "$2}' | xargs -L 1 -r kubectl delete pod
```

### Time

It took about 1 hour to complete this test

### Test Status

Success: Test completed without issue

### Cilium Version

```% cilium version
cilium-cli: v0.15.8 compiled with go1.21.1 on darwin/arm64
cilium image (default): v1.14.1
cilium image (stable): v1.14.2
cilium image (running): 1.14.2
```

### Kernel Version

```
Linux hostname-masked 5.10.192-183.736.amzn2.aarch64 #1 SMP Wed Sep 6 21:15:30 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

### Kubernetes Version

```
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.1-eks-43840fb
```

### Related GitHub Issues

https://github.com/cilium/cilium/issues/15596 mentioned it may not work

### Other Feedback

I wanted to report a success with using the `aws-cni` CNI chaining in an `IPv6` EKS cluster.

I have not extensively tested anything but validating that traffic between the pods correctly enters the wireguard and comes out of it on the other end using 2 nodes running two pods.

My primary concern was pod to pod traffic and securing that on the wire. This is using IPv6 addresses directly from the VPC (/80 assigned to the eth0 ENI for pod allocation by aws-cni).

Node to node traffic on eth0 does not seem to be captured.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
