### ISSUE TITLE
EgressGateways does not route traffic to internet in AKS (BYOCNI) environment

### ISSUE THREAD

**Issue by dbeltman** [cilium/cilium#28422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We are trying to implement the egress functionality from Cilium and take advantage of the Egress IP Policies. However we arent getting any traffic to go through when the policy is in effect. Disabling the policy almost immediately restores connection. 

### Installation steps taken:
- Create new AKS cluster: `az aks create -l  westeurope -g <redacted> -n cilium-testingcluster-3 --network-plugin none --generate-ssh-keys`
- Install cilium binary (1.15)
- Install cilium on cluster: `cilium install --version 1.14.2 --set azure.resourceGroup="${AZURE_RESOURCE_GROUP}"`
- Update cilium settings:
    ```
    helm upgrade cilium cilium/cilium --version 1.14.2 \
   --namespace kube-system \
   --reuse-values \
   --set egressGateway.enabled=true \
   --set bpf.masquerade=true \
   --set kubeProxyReplacement=true \
   --set l7Proxy=false
    ```
- Verify configmap was updated with settings
- Restart cilium pods to make sure settings are picked up:
  ```
  kubectl rollout restart ds cilium -n kube-system
  kubectl rollout restart deploy cilium-operator -n kube-system
  ```
- Run `cilium status`
  ```
        /¯¯\
    /¯¯\__/¯¯\    Cilium:             OK
    \__/¯¯\__/    Operator:           OK
    /¯¯\__/¯¯\    Envoy DaemonSet:    disabled (using embedded mode)
    \__/¯¯\__/    Hubble Relay:       disabled
        \__/       ClusterMesh:        disabled

    

    Deployment             cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
    DaemonSet              cilium             Desired: 3, Ready: 3/3, Available: 3/3
    Containers:            cilium-operator    Running: 2
                        cilium             Running: 3
    Cluster Pods:          11/11 managed by Cilium
    Helm chart version:    1.14.2
    Image versions         cilium             quay.io/cilium/cilium:v1.14.2@sha256:6263f3a3d5d63b267b538298dbeb5ae87da3efacf09a2c620446c873ba807d35: 3
                        cilium-operator    quay.io/cilium/operator-generic:v1.14.2@sha256:52f70250dea22e506959439a7c4ea31b10fe8375db62f5c27ab746e3a2af866d: 2

    /root > smc-dienst-klantcluster-poc-cil-bin3# k get pods -A|grep -i cil
    kube-system         cilium-2r4nt                             1/1     Running   0          2m8s
    kube-system         cilium-5j6kd                             1/1     Running   0          2m8s
    kube-system         cilium-node-init-2tmg7                   1/1     Running   0          2m8s
    kube-system         cilium-node-init-b2d9c                   1/1     Running   0          2m8s
    kube-system         cilium-node-init-w7jvg                   1/1     Running   0          2m8s
    kube-system         cilium-operator-5ccfbdf746-c2wf7         1/1     Running   0          74s
    kube-system         cilium-operator-5ccfbdf746-kf6hn         1/1     Running   0          2m8s
    kube-system         cilium-t589d                             1/1     Running   0          2m8s
  ```
- Label node for egress
    ```
    k get nodes -A -o wide
    NAME                                STATUS   ROLES   AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
    aks-nodepool1-64570510-vmss000000   Ready    agent   12m   v1.26.6   10.224.0.5    <none>        Ubuntu 22.04.3 LTS   5.15.0-1041-azure   containerd://1.7.5-1
    aks-nodepool1-64570510-vmss000001   Ready    agent   12m   v1.26.6   10.224.0.4    <none>        Ubuntu 22.04.3 LTS   5.15.0-1041-azure   containerd://1.7.5-1
    aks-nodepool1-64570510-vmss000002   Ready    agent   12m   v1.26.6   10.224.0.6    <none>        Ubuntu 22.04.3 LTS   5.15.0-1041-azure   containerd://1.7.5-1

    k label nodes aks-nodepool1-64570510-vmss000000 egress-node=true
    node/aks-nodepool1-64570510-vmss000000 labeled
    ```
- Deploy a pod that sets routes on the gateway node:
    ```
    containers:
      - args:
        - for i in $EGRESS_IPS; do ip address add ${i} dev eth0; done; sleep 10000000
        command:
        - /bin/sh
        - -c
        env:
        - name: EGRESS_IPS
          value: 10.224.0.11/16
    ```

### Our setup:

A CiliumEgressGatewayPolicy as follows:
```
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egress-rvdk
spec:
  selectors:
  - podSelector:
      matchLabels:
        io.kubernetes.pod.namespace: egress-test
  destinationCIDRs:
  - 0.0.0.0/0
  egressGateway:
    # Specify which node should act as gateway for this policy.
    nodeSelector:
      matchLabels:
        egress-node: "true"
    # Specify the IP address used to SNAT traffic matched by the policy.
    # It must exist as an IP associated with a network interface on the instance.
    egressIP: 10.224.0.11
```
Route table on gateway node:
```
default via 10.224.0.1 dev eth0 proto dhcp src 10.224.0.5 metric 100
10.0.0.0/24 via 10.0.1.77 dev cilium_host proto kernel src 10.0.1.77 mtu 1450
10.0.1.0/24 via 10.0.1.77 dev cilium_host proto kernel src 10.0.1.77
10.0.1.77 dev cilium_host proto kernel scope link
10.0.2.0/24 via 10.0.1.77 dev cilium_host proto kernel src 10.0.1.77 mtu 1450
10.224.0.0/16 dev eth0 proto kernel scope link src 10.224.0.5 metric 100
10.224.0.1 dev eth0 proto dhcp scope link src 10.224.0.5 metric 100
168.63.129.16 via 10.224.0.1 dev eth0 proto dhcp src 10.224.0.5 metric 100
169.254.169.254 via 10.224.0.1 dev eth0 proto dhcp src 10.224.0.5 metric 100
```

### Testing steps:
- TCPDump on gateway node
- In a pod that matches the EgressPolicy:
  ```
  # curl https://8.8.8.8
  ```
- Watch tcpump
    - We see traffic coming from the EgressIP set in the EgressPolicy
        ```
        # tcpdump -nni eth0|grep 10.224.0.11
        tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
        listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
        13:31:00.786937 IP 10.224.0.11.60962 > 8.8.8.8.443: Flags [S], seq 1277873017, win 64860, options [mss 1410,sackOK,TS val 58899456 ecr 0,nop,wscale 7], length 0
        ```
- Get no response from the curl command, outgoing traffic seems to be blocked.  
    ```
    curl: (28) Failed to connect to 8.8.8.8 port 443 after 129308 ms: Couldn't connect to server
    ```
- Spinning up another pod that does not fit the policy criteria (another namespace), allows the traffic to flow as normal:
    ```
    curl -v --connect-timeout 3 https://8.8.8.8|head -6
    * processing: https://8.8.8.8
    *   Trying 8.8.8.8:443...
    * Connected to 8.8.8.8 (8.8.8.8) port 443
    ```

### Question
We are wondering if we are taking the correct route, especially in regards to the routing on the gateway node. The pod we deploy to add the routing on the gateway might not be the right solution. 

Does anyone have any pointers/experience running Cilium EgressGateway in AKS?

If any other info is needed we are happy to provide

### Cilium Version

1.14.2

### Kernel Version

5.15.0-1041-azure

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"1c745e3abf44f47ce024a71ab98bdb3abb64986d", GitTreeState:"clean", BuildDate:"2023-07-28T23:53:49Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20231005-134846.zip](https://github.com/cilium/cilium/files/12819204/cilium-sysdump-20231005-134846.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
