### ISSUE TITLE
failed SNI validation on toFQDNs policies silently drops connections

### ISSUE THREAD

**Issue by riuvshyn** [cilium/cilium#28451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium silently drops connections if SNI fails for `toFQDNs` egress policy

I am trying to create policy to allow argocd repo server to connect to internal helm charts repository `charts.int.org`

the policy:
```
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: egress-fqdn-internal-charts
  namespace: argocd
spec:
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: argocd
      app.kubernetes.io/name: argocd-repo-server
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: "UDP"
            - port: "53"
              protocol: "TCP"
          rules:
            dns:
              - matchName: "charts.int.org"
    - toFQDNs:
        - matchName: "charts.int.org"
      toPorts:
        - ports:
            - port: "443"
              protocol: "TCP"
          serverNames:
          - "charts.int.org"
```

With this policy argocd repo server is getting connection reset by peer errors but `nothing appear on hubble nor hubble metrics`.
After doing some investigation I've noticed that this might by caused by SNI validation because if I remove block:
```
          serverNames:
          - "charts.int.org"
```
everything just works.

It might be happening due to the fact that in my infra `charts.int.org` is a CNAME for the artifactory `artifactory.int.org`
`dig charts.int.org`:
```
;; ANSWER SECTION:
charts.int.org.	30	IN	CNAME	artifactory.int.org.
artifactory.int.org.		30	IN	CNAME	artifactory-nlb-xxx.elb.eu-central-1.amazonaws.com.
artifactory-nlb-xxx.elb.eu-central-1.amazonaws.com. 3 IN A	xxx.xx.xx.xxx
artifactory-nlb-xxx.elb.eu-central-1.amazonaws.com. 3 IN A	xxx.xx.xx.xxx
artifactory-nlb-xxx.elb.eu-central-1.amazonaws.com. 3 IN A	xxx.xx.xx.xxx
```

`dig artifactory.int.org`:
```
;; ANSWER SECTION:
artifactory.int.org.		2	IN	CNAME	artifactory-nlb-xxx.elb.eu-central-1.amazonaws.com.
artifactory-nlb-xxx.elb.eu-central-1.amazonaws.com. 12 IN A xxx.xx.xx.xxx
artifactory-nlb-xxx.elb.eu-central-1.amazonaws.com. 12 IN A xxx.xx.xx.xxx
artifactory-nlb-xxx.elb.eu-central-1.amazonaws.com. 12 IN A xxx.xx.xx.xxx
```

Error I am getting on argocd repo server:
```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm pull --destination /tmp/1be41f62-99cf-4d1f-aff5-ddc44d2e4f4f --version 6.40.0 --repo https://charts.int.org grafana` failed exit status 1: Error: Get "[https://artifactory.int.org:443/artifactory/api/helm/helm-virtual/grafana/grafana-6.40.0.tgz](https://artifactory.int.org/artifactory/api/helm/helm-virtual/grafana/grafana-6.40.0.tgz)": read tcp 100.64.136.231:38862->xxx.xx.xx.xxx:443: read: connection reset by peer
```

As I've mentioned already removing `serverNames` from the policy fixes the problem and argocd repo server can actually connect to the helm repo.

### Cilium Version

`1.14.1`

### Kernel Version

`5.15.0-1045-aws`

### Kubernetes Version

1.26.9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
