### ISSUE TITLE
CiliumEgressGatewayPolicy doesn't use secondary network at the node to send the outgoing message

### ISSUE THREAD

**Issue by MahenRajput** [cilium/cilium#28498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

secondary interface(eth1) for egress towards 10.40* network.
Primary interface is eth0 which is on 10.60* network. Node IP is at 10.60.*
Configured egress gatway policy.

```
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egress-sample
spec:
  selectors:
  - podSelector:
      matchLabels:
        app: myapp
        io.kubernetes.pod.namespace: myns
  destinationCIDRs:
  - "0.0.0.0/0"
  egressGateway:
    nodeSelector:
      matchLabels:
        # The following label selects which node will act as egress gateway for
        # this policy
        egress-node: "true"
    # IP used to masquerade traffic leaving the cluster
    egressIP: 10.40.10.65
```

After configuring the EgressGatewayPolicy, the egress list at cilium is as follows:

```
Source IP       Destination CIDR   Egress IP     Gateway IP
192.168.0.38    0.0.0.0/0          10.40.10.65   10.60.61.141
192.168.0.133   0.0.0.0/0          10.40.10.65   10.60.61.141
192.168.0.234   0.0.0.0/0          10.40.10.65   10.60.61.141
```

For a curl request coming from eth1 at 10.40.10.65, the response is going via eth0 instead of eth1 interface.
the route details are:

```
default via 10.60.0.1 dev eth0 proto static
10.40.0.0/16 dev eth1 proto kernel scope link src 10.40.10.65
10.60.0.0/16 dev eth0 proto kernel scope link src 10.60.61.141
192.168.0.0/24 via 192.168.0.72 dev cilium_host proto kernel src 192.168.0.72
192.168.0.72 dev cilium_host proto kernel scope link
```

### Cilium Version

```
root@master1:/home/cilium# cilium version
Client: 1.14.2 a6748946 2023-09-09T20:59:33+00:00 go version go1.20.8 linux/amd64
Daemon: 1.14.2 a6748946 2023-09-09T20:59:33+00:00 go version go1.20.8 linux/amd64
```

### Kernel Version

5.4.0-162-generic

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.7-eks-4721010", GitCommit:"b77d9473a02fbfa834afa67d677fd12d690b195f", GitTreeState:"clean", BuildDate:"2022-06-27T22:22:16Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17-eks-712c388", GitCommit:"712c388560b1f37c31e49df13e94942c8b91a026", GitTreeState:"archive", BuildDate:"2023-02-22T13:26:30Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

### Relevant log output

```shell
cilium-operator-98df655dd-5wmzq   1/1     Running   0              88m     10.60.61.141    master1   <none>           <none>
cilium-operator-98df655dd-gdfs4   0/1     Pending   0              88m     <none>          <none>    <none>           <none>
cilium-v6tr7                      1/1     Running   0              88m     10.60.61.141    master1   <none>           <none>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
