### ISSUE TITLE
CFP: Support OSPF for advertising routes to the network

### ISSUE THREAD

**Issue by jobo-prod** [cilium/cilium#28530]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

In our company network, we are routing via OSPF. Hence, we cannot use Cilium's BGP control plane for advertising `LoadBalancer` services.

**Describe the feature you'd like**

Supporting other common routing protocols like OSPF should enable more people to make use of the LB IPAM feature (in a relatively easy way) in private cloud environments. At this time, there is the option to run [BIRD](https://docs.cilium.io/en/stable/network/bird/) daemons with somewhat hard-coded routes. It should be able to handle different protocols, like OSPF (I have not yet tested this). However, it would be a great improvement in UX, having Cilium integrate natively in different kinds of routing infrastructure.

**(Optional) Describe your proposed solution**

To my understanding, it should be possible to have an optional OSPF control plane (maybe mutually exclusive with the existing BGP CP). Where in BGP, the Kubernetes cluster is represented as an autonomous system (AS) with virtual BGP routers at its borders, it might be modeled similarly in OSPF, as an "Area" with virtual border routers.

A possible solution could be having an OSPF control plane just configure and deploy BIRD daemons on given nodes, if a new implementation of the protocol is not desired.

**Comment by harsimran-pabla** [comment]
My initial thought is to treat OSPF independently from BGP CP, as configuration CRDs are going to be drastically different. Cilium uses gobgp as BGP implementation, for it to speak OSPF natively, support for alternative routing daemons will need to be considered.

As a workaround, you can consider configuring a routing daemon on the node which speaks both BGP and OSPF ( like FRR ). Configure Cilium BGP CP to set up peering with node-local BGP instance. OSPF can be configured to set up peering with upstream routers. Redistribute BGP routes into OSPF on the node's local router.

**Comment by squeed** [comment]
A quick survey of the ecosystem shows that none of kube-router, kube-vip, or MetalLB support OSPF. It seems that a pure go implementation of OSPF is lacking.

I think it's unlikely that Cilium will support OSPF in the near-to-medium term without an upstream implementation of OSPF. The project as-is doesn't have the resources to implement it from the ground-up.

I'm sorry I couldn't give you the answer you wanted.

**Comment by bauerjs1** [comment]
Thank you for looking in to it, seems totally legit to me.

I actually haven't thought of using an additional virtual router like FRR, to redistribute Ciliums routes into another protocol domain. Thanks for pointing that out @harsimran-pabla!

**Comment by danieljkemp** [comment]
> Thank you for looking in to it, seems totally legit to me.
> 
> I actually haven't thought of using an additional virtual router like FRR, to redistribute Ciliums routes into another protocol domain. Thanks for pointing that out @harsimran-pabla!
> 
> If this is a legit sub-topic for the documentation pages or a blog post maybe, I can post the necessary FRR configuration here after I got that to work.

Hey, did you ever get that working?

I gave a crack at it but the cilium-> FRR config isn't connecting properly

Thanks!

**Comment by bauerjs1** [comment]
@danieljkemp unfortunately we're still on this. Might have the same problem, we can't seem to get these routes into FRR (we tried BIRD as well). As a workaround for now, we're thinking about static routes for the LB-IPs to all K8s nodes, as Cilium should do some re-routing to the actual pods internally, anyway. Packets might need to make an additional hop in this case.

As we're still using Cilium v13, we might look into this again in the future, hoping it will be easier to debug.

Cheers!

**Comment by danieljkemp** [comment]
oh I actually got this working! Took some doing

here is the configmap I used, a little messy but hey it worked :)

```
  start.sh: |
    #!/bin/bash
    sed "s/NODE_IP/$NODE_IP/" /tmp/frr/frr-temp > /etc/frr/frr.conf
    cp /tmp/frr/daemons /etc/frr/
    cp /tmp/frr/vtysh.conf /etc/frr/
    /sbin/tini -- /usr/lib/frr/docker-start
  frr-temp: |
    debug bgp updates
    log stdout debugging
    allow-reserved-ranges
    access-list all permit any
    route-map set-nexthop permit 10
      match ip address all
      set ip next-hop NODE_IP
    !
    router bgp 64512
      bgp allow-martian-nexthop
      no bgp ebgp-requires-policy
      bgp router-id NODE_IP
      neighbor 127.0.0.1 remote-as 64512
      neighbor 127.0.0.1 route-map set-nexthop in
      neighbor 127.0.0.1 soft-reconfiguration inbound
    !
    router ospf
      network 10.0.100.0/24 area 0
      redistribute bgp
    !
  daemons: |
    bgpd=yes
    ospfd=yes
    ospf6d=no
    ripd=no
    ripngd=no
    isisd=no
    pimd=no
    ldpd=no
    nhrpd=no
    eigrpd=no
    babeld=no
    sharpd=no
    pbrd=no
    bfdd=no
    fabricd=no
    vrrpd=no
    vtysh_enable=yes
    zebra_options="  -A 127.0.0.1 -s 90000000"
    bgpd_options="   -A 127.0.0.1 -p 179"
    ospfd_options="  -A 127.0.0.1"
```

**Comment by bauerjs1** [comment]
Oh wow, that is great news! Thanks for sharing the config and for the quick reply!

I guess you are using the `quay.io/frrouting/frr` image for this, right?

**Comment by danieljkemp** [comment]
yup! Also I found the notes to explain the frr config a bit better:

```
# Required for bgp to listen on 127.0.0.1
allow-reserved-ranges

# Route map needs a list
access-list all permit any

# Here we override the next hop to be that of the node's IP,
#   otherwise BGP will see it as coming over 127.0.0.1 which is not very helpful
route-map set-nexthop permit 10
  match ip address all
  set ip next-hop NODE_IP
!

# Setting a local ASN
router bgp 64512
  # The localhost nexthop won't make it to the route-map config 
  #  as it counts as a martian nexthop and would be rejected otherwise
  bgp allow-martian-nexthop

  # Gotta be honest I forget what this does and the docs don't make it clear either!
  no bgp ebgp-requires-policy

  # Connect as the node's IP to Cilium
  bgp router-id NODE_IP
  neighbor 127.0.0.1 remote-as 64512

  # Finally set the nexthop of the route correctly
  neighbor 127.0.0.1 route-map set-nexthop in

  # Should allow for cleaner restarts of FRR
  neighbor 127.0.0.1 soft-reconfiguration inbound
!
```

**Comment by rissson** [comment]
For anyone looking to do this with bird, here it is:

```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: default
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  virtualRouters:
    - localASN: 64512
      exportPodCIDR: true
      neighbors:
        - peerAddress: 127.0.0.1/32
          peerPort: 180
          peerASN: 64512
          gracefulRestart:
            enabled: true
        - peerAddress: ::1/128
          peerPort: 180
          peerASN: 64512
          gracefulRestart:
            enabled: true
      serviceSelector:
        matchExpressions:
          # All services
          - key: invalid
            operator: NotIn
            values:
              - invalid
```

On each node, add an annotation with `cilium.io/bgp-virtual-router.64512: router-id=127.0.0.1`

And then the bird config:
```
router id NODE_IP;

timeformat base         iso long;
timeformat log          iso long;
timeformat protocol     iso long;
timeformat route        iso long;

log stderr all;
debug protocols all;

protocol device {};

protocol bgp bgp4 {
  local 127.0.0.1 port 180 as 64512;
  neighbor 127.0.0.1 as 64512;
  graceful restart;

  ipv4 {
    import all;
    export none;
  };
}

protocol bgp bgp6 {
  local ::1 port 180 as 64512;
  neighbor ::1 as 64512;
  graceful restart;

  ipv6 {
    import all;
    export none;
  };
}

protocol ospf v3 ospf4 {
  graceful restart on;

  ipv4 {
    import none;
    export all;
  };

  area 0.0.0.0 {
    interface "OSPF_INTERFACE" {};
  };
}

protocol ospf v3 ospf6 {
  graceful restart on;

  ipv6 {
    import none;
    export all;
  };

  area 0.0.0.0 {
    interface "OSPF_INTERFACE" {};
  };
}
```
and the startup script:
```bash
#!/usr/bin/env bash

set -xeuo pipefail

# shellcheck disable=SC2010
sed -e "s/NODE_IP/${NODE_IP}/" -e "s/OSPF_INTERFACE/$(ls -l /sys/class/net | grep -v virtual | awk '{ print $9 }' | tail -n1)/" /config/bird.conf > /etc/bird/bird.conf

exec bird -f -R
```

**Comment by christian-2** [comment]
>   local 127.0.0.1 port 180 as 64512;
>   neighbor 127.0.0.1 as 64512;

May I please ask which version of BIRD you are using and what you get for `birdc show protocols all` and `birdc show interfaces`?

The reason I am asking is that I  am also trying to create a BGP session between both BIRD and the a Cilium Virtual BGP Router both running on a single host and ultimately to tie Cilium into surrounding OSPF. What I am currently observing is that BIRD comes up but that its protocol `bgp` remains in state `Idle` and is apparently not yet listening on port `tcp/179`. I am also observing `Ignored` for interface `lo` (apparently hardwired into BIRD in `sysdep/linux/netlink.c`).

I can also ask the question in Cilium's Slack channel in case you are active there.

**Comment by rissson** [comment]
> > local 127.0.0.1 port 180 as 64512;
> > neighbor 127.0.0.1 as 64512;
> 
> May I please ask which version of BIRD you are using

`image: ghcr.io/akafeng/bird:2.14` (well seems like I need to update to 2.15).

> and what you get for `birdc show protocols all` and `birdc show interfaces`?

<details>
<summary>`k exec -it bird-7qmqk -- birdc show protocols all`</summary>
```
BIRD 2.14 ready.
Name       Proto      Table      State  Since         Info
device1    Device     ---        up     2024-03-08 14:39:06

bgp4       BGP        ---        up     2024-03-08 15:13:49  Established
  BGP state:          Established
    Neighbor address: 127.0.0.1
    Neighbor AS:      64512
    Local AS:         64512
    Neighbor ID:      127.0.0.1
    Local capabilities
      Multiprotocol
        AF announced: ipv4
      Route refresh
      Graceful restart
        Restart time: 120
        AF supported: ipv4
        AF preserved:
      4-octet AS numbers
      Enhanced refresh
      Long-lived graceful restart
    Neighbor capabilities
      Multiprotocol
        AF announced: ipv4 ipv6
      Route refresh
      Extended next hop
        IPv6 nexthop: ipv4
      Graceful restart
        Restart time: 120
        Restart recovery
        AF supported: ipv4 ipv6
        AF preserved: ipv4 ipv6
      4-octet AS numbers
      Hostname: k3s-1.fsn.lama.tel
    Session:          internal multihop AS4
    Source address:   127.0.0.1
    Hold timer:       64.202/90
    Keepalive timer:  3.960/30
  Channel ipv4
    State:          UP
    Table:          master4
    Preference:     100
    Input filter:   ACCEPT
    Output filter:  REJECT
    Routes:         2 imported, 0 exported, 2 preferred
    Route change stats:     received   rejected   filtered    ignored   accepted
      Import updates:              5          0          0          2          3
      Import withdraws:            1          0        ---          0          1
      Export updates:              5          5          0        ---          0
      Export withdraws:            1        ---        ---        ---          0
    BGP Next hop:   127.0.0.1
    IGP IPv4 table: master4

bgp6       BGP        ---        up     2024-03-08 15:13:45  Established
  BGP state:          Established
    Neighbor address: ::1
    Neighbor AS:      64512
    Local AS:         64512
    Neighbor ID:      127.0.0.1
    Local capabilities
      Multiprotocol
        AF announced: ipv6
      Route refresh
      Graceful restart
        Restart time: 120
        AF supported: ipv6
        AF preserved:
      4-octet AS numbers
      Enhanced refresh
      Long-lived graceful restart
    Neighbor capabilities
      Multiprotocol
        AF announced: ipv4 ipv6
      Route refresh
      Extended next hop
        IPv6 nexthop: ipv4
      Graceful restart
        Restart time: 120
        Restart recovery
        AF supported: ipv4 ipv6
        AF preserved: ipv4 ipv6
      4-octet AS numbers
      Hostname: k3s-1.fsn.lama.tel
    Session:          internal multihop AS4
    Source address:   ::1
    Hold timer:       44.869/90
    Keepalive timer:  21.907/30
  Channel ipv6
    State:          UP
    Table:          master6
    Preference:     100
    Input filter:   ACCEPT
    Output filter:  REJECT
    Routes:         9 imported, 0 exported, 9 preferred
    Route change stats:     received   rejected   filtered    ignored   accepted
      Import updates:             17          0          0          7         10
      Import withdraws:            1          0        ---          0          1
      Export updates:             17         17          0        ---          0
      Export withdraws:            1        ---        ---        ---          0
    BGP Next hop:   ::1
    IGP IPv6 table: master6

ospf4      OSPF       master4    up     2024-03-08 14:39:06  Running
  Channel ipv4
    State:          UP
    Table:          master4
    Preference:     150
    Input filter:   REJECT
    Output filter:  ACCEPT
    Routes:         0 imported, 2 exported, 0 preferred
    Route change stats:     received   rejected   filtered    ignored   accepted
      Import updates:            109          0        109          0          0
      Import withdraws:           80          0        ---        107          0
      Export updates:              3          0          0        ---          3
      Export withdraws:            1        ---        ---        ---          1

ospf6      OSPF       master6    up     2024-03-08 14:39:06  Running
  Channel ipv6
    State:          UP
    Table:          master6
    Preference:     150
    Input filter:   REJECT
    Output filter:  ACCEPT
    Routes:         0 imported, 9 exported, 0 preferred
    Route change stats:     received   rejected   filtered    ignored   accepted
      Import updates:            229          0        229          0          0
      Import withdraws:          148          0        ---        303          0
      Export updates:             10          0          0        ---         10
      Export withdraws:            1        ---        ---        ---          1
```
</details>

<details>
<summary>`k exec -it bird-7qmqk -- birdc show interfaces`</summary>
```
BIRD 2.14 ready.
lo up (index=1)
	MultiAccess AdminUp LinkUp Loopback Ignored MTU=65536
	127.0.0.1/8 (Preferred, scope host)
	::1/128 (Preferred, scope host)
ens3 up (index=2)
	MultiAccess Broadcast Multicast AdminUp LinkUp MTU=1500
	172.28.1.11/26 (Preferred, scope site)
	2001:67c:17fc:101::11/64 (Preferred, scope univ)
	fe80::5054:ff:fef5:5a2a/64 (Preferred, scope link)
	2001:67c:17fc:101:5054:ff:fef5:5a2a/64 (scope univ)
cilium_net up (index=3)
	MultiAccess Broadcast Multicast AdminUp LinkUp MTU=1500
	fe80::2cd7:c2ff:feb5:29e5/64 (Preferred, scope link)
cilium_host up (index=4)
	MultiAccess Broadcast Multicast AdminUp LinkUp MTU=1500
	172.28.128.4/32 (Preferred, scope site)
	2001:67c:17fc:110::c272/128 (Preferred, scope univ)
lxc_health up (index=2888)
	MultiAccess Broadcast Multicast AdminUp LinkUp MTU=1500
	fe80::9892:5eff:fe25:dc49/64 (Preferred, scope link)
lxcf628958c6638 up (index=3156)
	MultiAccess Broadcast Multicast AdminUp LinkUp MTU=1500
	fe80::646e:b7ff:fea4:f0a9/64 (Preferred, scope link)
[a bunch of other lcx interfaces for each pod running on that node]
```
</details>

> The reason I am asking is that I am also trying to create a BGP session between both BIRD and the a Cilium Virtual BGP Router both running on a single host and ultimately to tie Cilium into surrounding OSPF.

Yes that is exactly what my setup is (albeit with many nodes, but bird and cilium collocated on the same node).

> What I am currently observing is that BIRD comes up but that its protocol `bgp` remains in state `Idle` and is apparently not yet listening on port `tcp/179`.

Well, bird should listen on port 180 with the setup described, otherwise you get cilium _and_ bird trying to listen to 179 which won't go well.

Also note that I updated my comment above to slightly change the startup script to get the ospf interface more accurately, and to include the daemonset I use for bird.

**Comment by j-shade** [comment]
Hi @rissson , firstly - thanks for posting your BIRD config, I am attempting to get it to work internally. Have you tried your BIRD config with later versions of cillium and the 'newer' method of using `CiliumBGPClusterConfig` etc?

I have applied your configs above, enabled cilium bgp control plane and deployed the following:

```yaml
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - ExternalIP
          - LoadBalancerIP
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  transport:
    peerPort: 180
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  bgpInstances:
  - name: "instance-64512"
    localASN: 64512
    peers:
    - name: "peer-64512-bird"
      peerASN: 64512
      peerAddress: 127.0.0.1
      peerConfigRef:
        name: "cilium-peer"
```

However for BGP im facing an issue i cant figure out:
```
2024-08-06 00:49:16 <TRACE> bgp4: Connecting to 127.0.0.1 from local address 127.0.0.1 
2024-08-06 00:49:16 <TRACE> bgp4: Connection lost (Connection refused)│
2024-08-06 00:49:16 <TRACE> bgp4: Connect delayed by 5 seconds
```

From what i can tell, cilium's BGP is operating, and from ciliums side is seeing BIRD as a peer.  Has anyone got the new BGP method to work with BIRD/FRR?

**Comment by harsimran-pabla** [comment]
Hi @j-shade , I'd suggest removing the transport section if it is not required. Let defaults be picked up ( ephemeral source port and 179 destination port ). Some issues have been reported with its usage.

**Comment by j-shade** [comment]
Hi @harsimran-pabla , thankyou for the suggestion. I have tried as you've said and removed the transport peer option and left BIRD to run on the default port of 179.

This has resulted in a new BIRD error:
```
2024-08-07 02:54:11 <TRACE> bgp4: Got OPEN(as=64512,hold=240,id=<NODE_IP_REDACTED>)
2024-08-07 02:54:11 <RMT> bgp4: Error: Bad BGP identifier: c0a80639
```

With Cilium agent:
```
cilium-agent time="2024-08-07T02:53:35Z" level=warning msg="sent notification" Data="bad BGP identifier <NODE_IP_REDACTED>" Key=127.0.0.1 Topic=Peer asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane 
```

**Comment by harsimran-pabla** [comment]
Error sounds like both BIRD and Cilium are using same router-id for BGP session. Cilium auto configures router ID based on node IP, which might be the case for BIRD as well. I'd suggest changing one of them and see if it resolves the issue.

**Comment by j-shade** [comment]
Thanks @harsimran-pabla , that was my thought too - however for this to be an ibgp mesh I was under the assumption they'd have to be the same/similar as posted above. I am happy to take suggestions/feedback on the following to get it to work more nicely.

Just an update - I reverted back to FRR with the following daemonset:

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: frr-system
### The Start Script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frr-start-script
  namespace: frr-system
data:
  start.sh: |
    #!/bin/bash
    sed "s/NODE_IP/$NODE_IP/" /tmp/frr/frr.conf > /etc/frr/frr.conf
    cp /tmp/frr/daemons /etc/frr/
    cp /tmp/frr/vtysh.conf /etc/frr/
    /sbin/tini -- /usr/lib/frr/docker-start
### The frr configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frr-config
  namespace: frr-system
data:
  frr.conf: |
    debug bgp neighbor-events
    debug bgp updates
    #debug bgp zebra

    log stdout debugging
  
    # Required for bgp to listen on 127.0.0.1
    allow-reserved-ranges

    # Route map needs a list
    access-list all permit any

    # Here we override the next hop to be that of the node's IP,
    #   otherwise BGP will see it as coming over 127.0.0.1 which is not very helpful
    route-map set-nexthop permit 10
      match ip address all
      set ip next-hop NODE_IP
    !

    # Setting a local ASN
    router bgp 64512
      # The localhost nexthop won't make it to the route-map config 
      #  as it counts as a martian nexthop and would be rejected otherwise
      bgp allow-martian-nexthop

      # Gotta be honest I forget what this does and the docs don't make it clear either!
      no bgp ebgp-requires-policy

      # Connect as the node's IP to Cilium
      bgp router-id NODE_IP
      neighbor 127.0.0.1 remote-as 64512

      # Finally set the nexthop of the route correctly
      neighbor 127.0.0.1 route-map set-nexthop in

      # Should allow for cleaner restarts of FRR
      neighbor 127.0.0.1 soft-reconfiguration inbound
    !

    router ospf
      network 10.0.0.0/24 area 0.0.0.0
      redistribute bgp
    !
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frr-daemons
  namespace: frr-system
data:
  daemons: |
    bgpd=yes
    ospfd=yes
    ospf6d=no
    ripd=no
    ripngd=no
    isisd=no
    pimd=no
    ldpd=no
    nhrpd=no
    eigrpd=no
    babeld=no
    sharpd=no
    pbrd=no
    bfdd=no
    fabricd=no
    vrrpd=no
    vtysh_enable=yes
    zebra_options="  -A 127.0.0.1 -s 90000000"
    bgpd_options="   -A 127.0.0.1 -p 179"
    ospfd_options="  -A 127.0.0.1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frr-vtysh-config
  namespace: frr-system
data:
  vtysh.conf: |
    ! Configuration file for vtysh
    ! It contains global configuration options for vtysh
    service integrated-vtysh-config
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: frr-daemonset
  namespace: frr-system
  labels:
    app: frr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frr-daemonset
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frr-daemonset
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: frr-daemonset
              topologyKey: kubernetes.io/hostname
      dnsPolicy: ClusterFirst
      hostNetwork: true  # Enable host networking to access host IP
      containers:
      - name: frr
        image: quay.io/frrouting/frr:10.1.0
        command: ["/bin/bash", "/tmp/frr/start.sh"]
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP  # Fetch the node's IP address
        volumeMounts:
        - name: start-script
          mountPath: /tmp/frr/start.sh
          subPath: start.sh
          readOnly: true
        - name: frr-config
          mountPath: /tmp/frr/frr.conf
          subPath: frr.conf
          readOnly: true
        - name: frr-daemons-config
          mountPath: /tmp/frr/daemons
          subPath: daemons
          readOnly: true
        - name: vtysh-config
          mountPath: /tmp/frr/vtysh.conf
          subPath: vtysh.conf
          readOnly: true
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - SYS_ADMIN
      volumes:
      - name: start-script
        configMap:
          name: frr-start-script
      - name: frr-config
        configMap:
          name: frr-config
      - name: frr-daemons-config
        configMap:
          name: frr-daemons
      - name: vtysh-config
        configMap:
          name: frr-vtysh-config
```

and the following Cilium BGP Config:

```yaml
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "CiliumPodIPPool"
      selector:
        matchExpressions:
        - {key: somekey, operator: NotIn, values: ['never-used-value']}
    - advertisementType: "PodCIDR"
    - advertisementType: "Service"
      service:
        addresses:
          - ClusterIP
          - ExternalIP
          - LoadBalancerIP
      selector:
        matchExpressions:
        - {key: somekey, operator: NotIn, values: ['never-used-value']}
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  bgpInstances:
  - name: "instance-64512"
    localASN: 64512
    peers:
      - name: "peer-64512"
        peerASN: 64512
        peerAddress: 127.0.0.1
        peerConfigRef:
          name: "cilium-peer"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPNodeConfigOverride
metadata:
  name: k8s-01
spec:
  bgpInstances:
    - name: "instance-64512"
      routerID: "127.0.0.1"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPNodeConfigOverride
metadata:
  name: k8s-02
spec:
  bgpInstances:
    - name: "instance-64512"
      routerID: "127.0.0.1"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPNodeConfigOverride
metadata:
  name: k8s-03
spec:
  bgpInstances:
    - name: "instance-64512"
      routerID: "127.0.0.1"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "default-ip-pool"
spec:
  allowFirstLastIPs: "No"
  blocks:
    - cidr: "10.0.0.1/24"
```

with BGP Control plane enabled in the settings, and no legacy configuration and it started to work.
