### ISSUE TITLE
CFP: Propagate labels from dedicated Ingress to LB service

### ISSUE THREAD

**Issue by log1cb0mb** [cilium/cilium#28576]
## Cilium Feature Proposal
        
**Describe the feature you'd like**

Dedicated ingress controller mode: Cilium adds only single fixed label `cilium.io/ingress: "true"` to automated LB service however it would be highly advantageous to extend support for propagating user defined labels from the Ingress to the load balancer service. These propagated labels could serve as [LB IPAM Service Selectors](https://docs.cilium.io/en/stable/network/lb-ipam/#service-selectors), enabling the allocation of IP addresses from various IP pools.

Ultimate goal/use case here is to be able to use different IP pools for cilium's dedicated ingress controller services and/or be able to control service announcement with BGP CP based on service matching labels.

**(Optional) Describe your proposed solution**

* Currently cilium operator can propagate certain annotations from Ingress to LB service, similar logic could be implemented to propagate labels.
* Alternative would be to implement annotation based service selector or pool allocation feature under LB IPAM.

**Comment by danehans** [comment]
> These propagated labels could serve as [LB IPAM Service Selectors](https://docs.cilium.io/en/stable/network/lb-ipam/#service-selectors), enabling the allocation of IP addresses from various IP pools.

Note that LB IPAM supports two special purpose selector fields that don’t match on labels but instead match `.meta.name` and/or `.meta.namespace`. In the following example, the CiliumLoadBalancerIPPool will match all LB services in namespace `foo`:

```yaml
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "blue-pool"
spec:
  cidrs:
  - cidr: "20.0.10.0/24"
  serviceSelector:
    matchLabels:
      "io.kubernetes.service.namespace": "foo"
```
