### ISSUE TITLE
Helm chart: broken spire setup

### ISSUE THREAD

**Issue by rauanmayemir** [cilium/cilium#28599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```
authentication:
  enabled: true
  mutual:
    spire:
      enabled: true
      install:
        enabled: true
        agent:
          labels:
            k8s-app: cilium-spire-agent
        server:
          labels:
            k8s-app: cilium-spire-server
```

Setting `labels` as above will break the helm install with:

```
Error: YAML parse error on cilium/templates/spire/agent/daemonset.yaml: error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context
```

### Cilium Version

1.14.2

### Kernel Version

-

### Kubernetes Version

-

### Anything else?

Not setting labels will allow helm install to happen.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
