### ISSUE TITLE
LB-IPAM switch `CiliumLoadBalancerIPPool.Spec.AllowFirstLastIPs` from default `Yes` to default `No`

### ISSUE THREAD

**Issue by dylandreimerink** [cilium/cilium#28591]
Old LB-IPAM behavior was to always reserve the first and last IP of a CIDR, this feature has now been made optional with the `CiliumLoadBalancerIPPool.Spec.AllowFirstLastIPs` field. If not specified, we still default to `Yes` in v1.15. However, it is desirable to have this default to `No`. 

Once the v1.15 branch has been forked we can apply this change. Docs and CRD comments should be updated accordingly and a note should be added to the upgrade guide that users should explicitly set this value on their policies if they do not want the changed default behavior.

**Comment by nicklasfrahm** [comment]
Minor note on this one. The `CiliumLoadBalancerIPPool` does not seem to calculate the available IPs correctly if the prefix length is `/32`. 

```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: public
spec:
  cidrs:
  - cidr: "1.2.3.4/32"
```

I created a `CiliumLoadBalancerIPPool` for the `Gateway` `LoadBalancer` and it stays in `Pending`. I see this:

```
$ k get ippools
NAME     DISABLED   CONFLICTING   IPS AVAILABLE   AGE
public   false      False         0               28m
```
