### ISSUE TITLE
Docs: GKE Helm installation is missing important information

### ISSUE THREAD

**Issue by djfinnoy** [cilium/cilium#28656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I installed Cilium via Helm on a fresh GKE cluster, using the Helm input values documented [here](https://docs.cilium.io/en/stable/installation/k8s-install-helm/):

```
nodeinit:
  enabled: true
  reconfigureKubelet: true
  removeCbrBridge: true
  restartPods: true
cni:
  binPath: "/home/kubernetes/bin"
gke:
  enabled: true
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 10.42.0.0/16
```

This led to problems with the `cilium-operator` pods crashlooping; they could not reach the Kubernetes api.
Then I read [this page](https://docs.cilium.io/en/stable/network/concepts/routing/#id6) of the docs, and added the following values via Helm:

```
routingMode: native
endpointRoutes:
  enabled: true
```

After doing this, Cilium worked as expected.

I am now unsure whether this configuration for `routingMode` and `endpointRoutes` is required with GKE, or if they are only required with my setup for some reason.

If they are required, they should probably be incorporated into the Helm installation docs. If not, I would be grateful if someone could clarify what those values do, and why I need them.

### Cilium Version

v1.14.2

### Kernel Version

not sure, cluster not accessible right now.

### Kubernetes Version

v1.27.4-gke.900

### Anything else?

My GKE network has three IP CIDR ranges, one for services, one for pods, and one for everything else.
The CIDR passed to `ipv4NativeRoutingCIDR` is the one reserved for pods.

When `cilium-operator` was crashlooping, it was trying to reach an IP address from the other CIDR ranges.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
