### ISSUE TITLE
Helm chart does not support Hubble UI lon GKE Dataplane v2

### ISSUE THREAD

**Issue by dwalker-sabiogroup** [cilium/cilium#28708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After deploying a GKE cluster with [Dataplane v2](https://cloud.google.com/kubernetes-engine/docs/concepts/dataplane-v2) enabled and observability configured I am able to see the cilium CNI and hubble relay pods running.

When following the [documentation](https://docs.cilium.io/en/latest/gettingstarted/hubble/) to install helm standalone with the following values

```yaml
agent: false
operator:
  enabled: false
cni:
  install: false
hubble:
  enabled: false
  relay:
    enabled: false
    tls:
      server:
        enabled: true
  ui:
    enabled: true
    standalone:
      enabled: true
      tls:
        certsVolume:
          projected:
            defaultMode: 0400
            sources:
              - secret:
                  name: hubble-relay-client-certs
                  items:
                    - key: tls.crt
                      path: client.crt
                    - key: tls.key
                      path: client.key
                    - key: ca.crt
                      path: hubble-relay-ca.crt
```

Hubble UI is deployed into the cluster but when trying to access the service no flows are shown and the pod logs show the following error

```
hubble authentication handshake failed: tls: failed to verify certificate: x509: certificate is valid for *.kube-system.svc.cluster.local, not ui.hubble-relay.cilium.io
```

From the GCP configuration [docs](https://cloud.google.com/kubernetes-engine/docs/how-to/configure-dpv2-observability) the following environment variable needs to be set

```yaml
            - name: TLS_RELAY_SERVER_NAME
              value: relay.kube-system.svc.cluster.local
```

However this is hardcoded in the [helm chart](https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/hubble-ui/deployment.yaml#L104-L105) to ` ui.hubble-relay.cilium.io`

### Cilium Version

- gke.gcr.io/cilium/hubble-relay:v1.12.10-gke.11
- gke.gcr.io/cilium/cilium:v1.12.10-gke.11

### Kernel Version

[GKE with Dataplane v2](https://cloud.google.com/kubernetes-engine/docs/concepts/dataplane-v2)

### Kubernetes Version

v1.27.3-gke.100

### Anything else?

As a workaround manually editing the deployment to set 

```yaml
            - name: TLS_RELAY_SERVER_NAME
              value: relay.kube-system.svc.cluster.local
```

resolves the issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
