### ISSUE TITLE
Host endpoint policy for coredns is not applied to allow healthcecks

### ISSUE THREAD

**Issue by ekarlso** [cilium/cilium#28753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have built 1.15-pre.1 and dropped the commit 5ddea63038aaf17211bf48a22dd910a83ac870fe due to issues with policies not being applied correctly.

I have policies for the host being applied that should allow traffic to **kube-system/coredns** but it is not applied when checking `bpf policy get <coredns ep id>`

I have applied the following rule in my hosts egress, note that if I remove the `io.cilium.k8s.policy.serviceaccount: coredns` I do see rules generated for the other endpoints listed below such as talos-vmtoolsd and flux for :8080 and :8181 but never coredns.

```yaml
- toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        io.cilium.k8s.policy.serviceaccount: coredns
  toPorts:
    - ports:
        - port: "8080"
          protocol: TCP
        - port: "8181"
          protocol: TCP
```

flow.json
```json
{
  "flow": {
    "time": "2023-10-23T22:00:59.157805673Z",
    "uuid": "a5510b50-5ca9-4160-b2e8-b1c651212503",
    "verdict": "AUDIT",
    "ethernet": {
      "source": "96:ac:ba:4e:aa:7a",
      "destination": "96:ac:ba:4e:aa:7a"
    },
    "IP": {
      "source": "172.17.22.70",
      "destination": "172.17.22.78",
      "ipVersion": "IPv4"
    },
    "l4": {
      "TCP": {
        "source_port": 33080,
        "destination_port": 8080,
        "flags": {
          "SYN": true
        }
      }
    },
    "source": {
      "identity": 1,
      "labels": [
        "cidr:0.0.0.0/0",
        "cidr:128.0.0.0/1",
        "cidr:128.0.0.0/2",
        "cidr:160.0.0.0/3",
        "cidr:160.0.0.0/4",
        "cidr:168.0.0.0/5",
        "cidr:172.0.0.0/10",
        "cidr:172.0.0.0/11",
        "cidr:172.0.0.0/6",
        "cidr:172.0.0.0/7",
        "cidr:172.0.0.0/8",
        "cidr:172.0.0.0/9",
        "cidr:172.16.0.0/12",
        "cidr:172.16.0.0/13",
        "cidr:172.16.0.0/14",
        "cidr:172.16.0.0/15",
        "cidr:172.16.0.0/16",
        "cidr:172.16.0.0/17",
        "cidr:172.16.0.0/18",
        "cidr:172.16.0.0/19",
        "cidr:172.16.0.0/20",
        "cidr:172.16.0.0/21",
        "cidr:172.16.0.0/22",
        "cidr:172.16.0.0/23",
        "cidr:172.16.0.0/24",
        "cidr:172.16.0.0/25",
        "cidr:172.16.0.112/28",
        "cidr:172.16.0.112/29",
        "cidr:172.16.0.112/30",
        "cidr:172.16.0.114/31",
        "cidr:172.16.0.114/32",
        "cidr:172.16.0.64/26",
        "cidr:172.16.0.96/27",
        "cidr:172.17.0.0/16",
        "cidr:172.17.0.0/17",
        "cidr:172.17.0.0/18",
        "cidr:172.17.0.0/19",
        "cidr:172.17.16.0/20",
        "cidr:172.17.16.0/21",
        "cidr:172.17.20.0/22",
        "cidr:172.17.22.0/23",
        "cidr:172.17.22.0/24",
        "cidr:172.17.22.0/25",
        "cidr:172.17.22.64/26",
        "cidr:172.17.22.64/27",
        "cidr:172.17.22.64/28",
        "cidr:172.17.22.64/29",
        "cidr:172.17.22.68/30",
        "cidr:172.17.22.70/31",
        "cidr:172.17.22.70/32",
        "reserved:host"
      ]
    },
    "destination": {
      "ID": 925,
      "identity": 112,
      "namespace": "kube-system",
      "labels": [
        "k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system",
        "k8s:io.cilium.k8s.policy.cluster=default",
        "k8s:io.cilium.k8s.policy.serviceaccount=coredns",
        "k8s:io.kubernetes.pod.namespace=kube-system",
        "k8s:k8s-app=kube-dns"
      ],
      "pod_name": "coredns-7b969b5db8-7hb9z",
      "workloads": [
        {
          "name": "coredns",
          "kind": "Deployment"
        }
      ]
    },
    "Type": "L3_L4",
    "node_name": "ftlk8s02-default-md0-69689754d9xbp68c-hx7vp",
    "event_type": {
      "type": 5
    },
    "traffic_direction": "EGRESS",
    "is_reply": false,
    "Summary": "TCP Flags: SYN"
  },
  "node_name": "ftlk8s02-default-md0-69689754d9xbp68c-hx7vp",
  "time": "2023-10-23T22:00:59.157805673Z"
}
```

`cilium endpoint list` on host with coredns
```ENDPOINT   POLICY (ingress)   POLICY (egress)    IDENTITY   LABELS (source:key[=value])                                                            IPv6   IPv4            STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                                                 
50         Disabled (Audit)   Disabled (Audit)   1          k8s:node.cluster.x-k8s.io/esxi-host=172.16.50.31                                                              ready   
                                                            k8s:node.kubernetes.io/instance-type=vsphere-vm.cpu-2.mem-16gb.os-linux                                               
                                                            reserved:host                                                                                                         
625        Disabled (Audit)   Disabled (Audit)   112        k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system                    172.17.22.188   ready   
                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                              
                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                                       
                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                           
                                                            k8s:k8s-app=kube-dns                                                                                                  
1295       Disabled (Audit)   Disabled (Audit)   20732      k8s:app=notification-controller                                                               172.17.22.182   ready   
                                                            k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/instance=flux-system                                             
                                                            k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/part-of=flux                                                     
                                                            k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/version=v2.1.1                                                   
                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=flux-system                                            
                                                            k8s:io.cilium.k8s.namespace.labels.kustomize.toolkit.fluxcd.io/name=flux-system                                       
                                                            k8s:io.cilium.k8s.namespace.labels.kustomize.toolkit.fluxcd.io/namespace=flux-system                                  
                                                            k8s:io.cilium.k8s.namespace.labels.pod-security.kubernetes.io/warn-version=latest                                     
                                                            k8s:io.cilium.k8s.namespace.labels.pod-security.kubernetes.io/warn=restricted                                         
                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                              
                                                            k8s:io.cilium.k8s.policy.serviceaccount=notification-controller                                                       
                                                            k8s:io.kubernetes.pod.namespace=flux-system                                                                           
2693       Disabled           Disabled (Audit)   53571      k8s:app=talos-vmtoolsd                                                                        172.17.22.148   ready   
                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system                                            
                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                              
                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                       
                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                           
3016       Disabled (Audit)   Disabled (Audit)   4          reserved:health                                                                               172.17.22.166   ready   
```

For the `bpf policy get 50` related to the host please see the attached bpf-policies.txt

### Cilium Version

1.15-pre.1 without the Drop lock commit 5ddea63038aaf17211bf48a22dd910a83ac870fe

```
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    disabled (using embedded mode)
 \__/¯¯\__/    Hubble Relay:       OK
    \__/       ClusterMesh:        disabled

DaemonSet              cilium             Desired: 9, Ready: 9/9, Available: 9/9
Deployment             hubble-ui          Desired: 1, Ready: 1/1, Available: 1/1
Deployment             cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
Deployment             hubble-relay       Desired: 1, Ready: 1/1, Available: 1/1
Containers:            cilium             Running: 9
                       hubble-ui          Running: 1
                       cilium-operator    Running: 2
                       hubble-relay       Running: 1
Cluster Pods:          23/23 managed by Cilium
Helm chart version:    1.15.0-pre.1
Image versions         cilium             registry.replaced.com/cilium/cilium:1.15-pre.1-no-lock: 9
                       hubble-ui          registry.replaced.com/cilium/hubble-ui:v0.12.0: 1
                       hubble-ui          registry.replaced.com/cilium/hubble-ui-backend:v0.12.0: 1
                       cilium-operator    registry.replaced.com/cilium/operator-generic:1.15-pre.1-no-lock: 2
                       hubble-relay       registry.replaced.com/cilium/hubble-relay:v1.14.2: 1
```

### Kernel Version

6.1.54-talos

### Kubernetes Version

1.28.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ekarlso** [comment]
I had forgotten to upload the bpf-policies.txt file, it's added now
[bpf-policies.txt](https://github.com/cilium/cilium/files/13185771/bpf-policies.txt)

**Comment by pchaigno** [comment]
Is it a host policy or a pod policy? Could you share the full policy?

**Comment by ekarlso** [comment]
Host policy:
```yaml
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: talos-base
spec:
  description: "Base host firewall policy for Talos"
  nodeSelector:
    matchLabels: {}

  ingress:
    - fromEndpoints:
        - matchLabels:
            app: talos-vmtoolsd
            io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "50000"
              protocol: TCP

    - fromEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            # Rancher monitoring Cilium operator metrics
            - port: "6942"
              protocol: TCP
              # Cilium Hubble relay
            - port: "4244"
              protocol: TCP

    - fromEntities:
        - remote-node
      toPorts:
        - ports:
            # Cilium WireGuard
            - port: "51871"
              protocol: UDP
              # Cilium VXLAN
            - port: "8472"
              protocol: UDP

    - fromEntities:
        - health
        - remote-node
      toPorts:
        - ports:
            # Inter-node Cilium cluster health checks (please also have a look at the appendix for further details)
            - port: "4240"
              protocol: TCP
            # Cilium cilium-agent health status API
            - port: "9876"
              protocol: TCP

    - fromEntities:
        - remote-node
        - host
      toPorts:
        - ports:
            - port: "9090"
              protocol: TCP

    - fromEntities:
        - kube-apiserver
      toPorts:
        - ports:
            # Kubelet
            - port: "10250"
              protocol: TCP

    - fromEntities:
        - kube-apiserver
        - host
        - remote-node
      icmps:
        - fields:
            - family: IPv4
              type: 8

    # Management traffic
    - fromCIDRSet:
        - cidrGroupRef: management
        - cidrGroupRef: cluster
      icmps:
        - fields:
            - family: IPv4
              type: 8

    - fromCIDRSet:
        - cidrGroupRef: management
        - cidrGroupRef: controlplane
      toPorts:
        - ports:
            # SSH
            - port: "50000"
              protocol: TCP

  egress:
    # Cilium Overlay
    - toEntities:
        - remote-node
        - kube-apiserver
      toPorts:
        - ports:
            # Cilium WireGuard
            - port: "51871"
              protocol: UDP
              # Cilium VXLAN
            - port: "8472"
              protocol: UDP

    # Cilium health icmp
    - toEntities:
        - health
        - kube-apiserver
        - host
        - remote-node
      icmps:
        - fields:
            - family: IPv4
              type: 8

    - toEntities:
        - health
        - kube-apiserver
        - host
        - remote-node
      toPorts:
        - ports:
            # Inter-node Cilium cluster health checks (please also have a look at the appendix for further details)
            - port: "4240"
              protocol: TCP
            # Cilium cilium-agent health status API
            - port: "9876"
              protocol: TCP

    # Allow traffic to NTP
    - toCIDRSet:
        - cidr: x.x.x.x/32
      toPorts:
        - ports:
            - port: "123"
              protocol: UDP

    # Allow traffic to DNS
    - toCIDRSet:
        - cidr: x.x.x.x/32
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP

    # Allow registry
    - toCIDRSet:
        - cidr: x.x.x.x/32
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP

    # Allow traffic to kube-apiserver via VIP
    - toCIDRSet:
        - cidr: x.x.x.x/32
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: cert-manager
      toPorts:
        - ports:
            - port: "6080"
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: flux-system
      toPorts:
        - ports:
            - port: "9440"
              protocol: TCP
            - port: "9090"
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            io.cilium.k8s.policy.serviceaccount: hubble-ui
      toPorts:
        - ports:
            - port: "8081"
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            io.cilium.k8s.policy.serviceaccount: hubble-relay
      toPorts:
        - ports:
            - port: "4245"
              protocol: TCP

    # Allow healthchecks
    - toEndpoints:
        - {}
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            io.cilium.k8s.policy.serviceaccount: coredns
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
            - port: "8181"
              protocol: TCP
```
