### ISSUE TITLE
Gateway API - RequestRedirect loops indefinately scheme change from http to https

### ISSUE THREAD

**Issue by red-lichtie** [cilium/cilium#28796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Trying to set up a redirect but the redirect repeats.

### Cilium Version

1.14.3

### Kernel Version

6.1.54

### Kubernetes Version

v1.28.2

### Sysdump

[cilium-sysdump-20231025-201203.zip](https://github.com/cilium/cilium/files/13169293/cilium-sysdump-20231025-201203.zip)

### Relevant log output

```shell
$ curl -vL http://podinfo.home.svc/


* processing: http://podinfo.home.svc/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.168.76.225:80...
* Connected to podinfo.home.svc (192.168.76.225) port 80
> GET / HTTP/1.1
> Host: podinfo.home.svc
> User-Agent: curl/8.2.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< location: https://podinfo.home.svc:443/
< date: Wed, 25 Oct 2023 18:15:56 GMT
< server: envoy
< content-length: 0
< 
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host podinfo.home.svc left intact
* Clear auth, redirects to port from 80 to 443
* Issue another request to this URL: 'https://podinfo.home.svc:443/'
*   Trying 192.168.76.225:443...
* Connected to podinfo.home.svc (192.168.76.225) port 443
* ALPN: offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [6 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [1401 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / TLS_CHACHA20_POLY1305_SHA256
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: [NONE]
*  start date: Oct 25 16:43:44 2023 GMT
*  expire date: Jan 23 16:43:44 2024 GMT
*  subjectAltName: host "podinfo.home.svc" matched cert's "*.home.svc"
*  issuer: MyIssuer
*  SSL certificate verify ok.
* using HTTP/1.x
} [5 bytes data]
> GET / HTTP/1.1
> Host: podinfo.home.svc
> User-Agent: curl/8.2.1
> Accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [214 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [214 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
< HTTP/1.1 301 Moved Permanently
< location: https://podinfo.home.svc:443/
< date: Wed, 25 Oct 2023 18:15:56 GMT
< server: envoy
< content-length: 0
...
* Connection #1 to host podinfo.home.svc left intact
* Maximum (50) redirects followed
curl: (47) Maximum (50) redirects followed
...
```

### Anything else?

There is a second bug regarding "hostnames" and wildcards. As far as I understand it, I should be able to define it as "*.home.svc" but it doesn't match "podinfo.home.svc".

[v1beta1.HTTPRoute](https://gateway-api.sigs.k8s.io/spec#gateway.networking.k8s.io/v1beta1.HTTPRoute)

CRD:
```yaml
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: main-gateway
  namespace: default
spec:
  gatewayClassName: cilium
  addresses:
    - value: 192.168.76.225
  listeners:
    - protocol: HTTPS
      port: 443
      name: prod-tls-gw
      hostname: "*.home.svc"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              shared-gateway-access: "true"
      tls:
        certificateRefs:
          - kind: Secret
            group: ""
            name: main-gateway
    - protocol: HTTP
      port: 80
      name: prod-web-gw
      hostname: "*.home.svc"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              shared-gateway-access: "true"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-filter-redirect
  namespace: default
spec:
  parentRefs:
    - kind: Gateway
      name: main-gateway
      namespace: default
  hostnames:
    - podinfo.home.svc
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dylandreimerink** [comment]
> There is a second bug regarding "hostnames" and wildcards. As far as I understand it, I should be able to define it as "*.home.svc" but it doesn't match "podinfo.home.svc".

I recommend making a separate issue with a minimal reproducer that way we can track them independently in case one issue takes longer to resolve than the other.

**Comment by red-lichtie** [comment]
I am following the example from the Gateway API site.

> Redirect filters can substitute various URL components independently. For example, to issue a permanent redirect (301) from HTTP to HTTPS, configure requestRedirect.statusCode=301 and requestRedirect.scheme="https"

[https://gateway-api.sigs.k8s.io/guides/http-redirect-rewrite/#redirects](https://gateway-api.sigs.k8s.io/guides/http-redirect-rewrite/#redirects)

I can only imagine that the people who wrote the specification, expect the implementation to recognize that there is only a scheme change and only do it when required.

**Comment by red-lichtie** [comment]
The redirect was on both the 80 and the 443 listeners, my definition was incomplete.

Giving the services all `sectionName: prod-tls-gw` and only the redirect  route `sectionName: prod-web-gw` fixed the issue.

It would be nice if the example in the documentation reflected the use of `sectionName` to identify which listener should have the redirect applied to it.

**Comment by DonOtuseGH** [comment]
> Giving the services all `sectionName: prod-tls-gw` and only the redirect route `sectionName: prod-web-gw` fixed the issue.

Hi @red-lichtie,

i run into the same issue using cilium 1.14.4 gateway api (redirect loop, because http/https listener both doing the 301 redirect). tried to understand what you mean by that ^^^, but didn't get it.
 
I've the following simple [test setup](https://gist.github.com/DonOtuseGH/a4336da7bf99a8e34f5bd5c57942f610), maybe you could have a look and give me a hint, what i'm doing wrong?

Thanks and best regards, Don.

**Comment by fulljackz** [comment]
Hi @DonOtuseGH , @red-lichtie ,

I'm also trying to do a 301 redirect from http to https following the same doc and I have the same redirect loop issue.

Did one of you achieved to solve this issue (@DonOtuseGH) ?

Regards,

**Comment by julian-perge** [comment]
Necroing this thread to say that I am thoroughly convinced Cilium cannot do http-to-https redirect with the Kubernetes Gateway API without running into an infinite redirect loop _if the cert is provisioned through AWS ACM_.

I've looked at at all these links/issues:

https://github.com/kubernetes-sigs/gateway-api/issues/1185
https://github.com/kubernetes-sigs/gateway-api/issues/2455
https://github.com/kubernetes-sigs/gateway-api/issues/2809
https://github.com/cilium/cilium/issues/25357
https://github.com/cilium/cilium/issues/27493
https://github.com/cilium/cilium/issues/28796
https://www.reddit.com/r/kubernetes/comments/196w65h/gateway_api_and_redirect_loops/

And none of the suggestions/examples worked. I've even tried https://www.gateway-api-controller.eks.aws.dev/latest/ which is AWS' own Gateway controller implementation, but their docs are absolute garbage and examples even more so on setting up what I'm trying to achieve: Have ExternalDNS on an external LoadBalancer that Cilium then allows me to route to. HTTPS works without any issues, but as soon as I add the `type: RequestRedirect` filter, boom, infinite redirect loop. Browsers _can_ automatically upgrade HTTP to HTTPS connections, but this cannot and should not be relied on by any means.

The Cilium docs need to be updated saying that if you enable Cilium's Gateway API setting and are looking to do http-to-https redirect, _it does not work with certs provisioned by AWS ACM_, and only certs available in your cluster will work, and they will _only_ work if you have the `tls:` section in your `Gateway` resource.

This has been an unbelievably infuriating rabbit-hole to go down, only to find out that Cilium does not allow http-to-https redirect for AWS ACM certs, only internal ones.

If someone, anyone, wants to point me in the right direction on this, PLEASE, I would be eternally grateful. Until then, back to the bloatware that is Istio...

**Comment by red-lichtie** [comment]
Sorry for not getting back with my solution.
Here the gateway definition (podinfo/gateway.yaml):
```yaml
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: podinfo-gateway
  namespace: default
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTPS
      port: 443
      name: podinfo-tls-gw
      hostname: "podinfo.home.svc"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: podinfo-gateway
    - protocol: HTTP
      port: 80
      name: podinfo-web-gw      # HTTP listener owns the redirect route
      hostname: "podinfo.home.svc"
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: podinfo
  namespace: default
spec:
  parentRefs:
    - kind: Gateway
      name: podinfo-gateway
      namespace: default
      sectionName: podinfo-tls-gw
  hostnames:
    - podinfo.home.svc
  rules:
    - backendRefs:
        - name: podinfo
          port: 9898
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: podinfo-redirect
  namespace: default
spec:
  parentRefs:
    - kind: Gateway
      name: podinfo-gateway
      namespace: default
      sectionName: podinfo-web-gw  # parent has to be the HTTP listener
  hostnames:
    - "podinfo.home.svc"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
...

```
I hope this helps someone.
