### ISSUE TITLE
Hubble: User info is missing from URLs when observing L7 HTTP flows

### ISSUE THREAD

**Issue by ioandr** [cilium/cilium#28798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This issue is related to https://github.com/cilium/cilium/issues/23887, in which we are gradually adding support to Cilium to redact sensitive data fields when observing L7 flows with Hubble.

Before extending Cilium's HTTP parser and configuration to _conditionally_ redact sensitive, user-provided information in URLs (e.g., password), I wanted to understand the existing mechanism and verify that sensitive data is _always_ redacted by Cilium's HTTP parser. The corresponding logic can be found here:

https://github.com/cilium/cilium/blob/main/pkg/hubble/parser/seven/http.go#L38

In a nutshell, if the `user:pass@` part exists in the URL of an HTTP request, I was expecting Cilium's HTTP parser to redact the password and print the username:

```yaml
...
    "l7": {
      "type": "RESPONSE",
      "latency_ns": "666414",
      "http": {
        "code": 200,
        "method": "POST",
        "url": "http://user:HUBBLE_REDACTED@host/path",  <---
        "protocol": "HTTP/1.1",
...
```

Instead, what I observed was that the `user:pass@` part was completely missing from the "calculated" URL in the flow, as shown below:

```yaml
...
    "l7": {
      "type": "RESPONSE",
      "latency_ns": "666414",
      "http": {
        "code": 200,
        "method": "POST",
        "url": "http://host/path",  <---
        "protocol": "HTTP/1.1",
...
```

### Cilium Version

```
cilium-cli: v0.15.11 compiled with go1.21.3 on linux/amd64
cilium image (default): v1.14.2
cilium image (stable): v1.14.3
cilium image (running): 1.14.3
```

### Kernel Version

```
root@kind-control-plane:/home/cilium# uname -a
Linux kind-control-plane 6.2.0-34-generic #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

## Development environment

1. Create a `kind` Kubernetes cluster with 2 nodes (control plane and worker) via `make`
2. Deploy Cilium via the `cilium` CLI
3. Enable Hubble via the `cilium` CLI 
4. Deploy sample application from https://docs.cilium.io/en/stable/gettingstarted/demo/#starwars-demo via `kubectl`
5. Port forward the Hubble relay service via the `cilium` CLI
6. Apply Cilium network policy from https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/minikube/sw_l3_l4_l7_policy.yaml via `kubectl`
7. Observe HTTP flows with `hubble observe --pod deathstar --protocol http -o json -f | jq`
8. Send sample HTTP request with user info (username and password) in the URL from the `tiefighter` Pod to the `deathstar` one with: `kubectl exec tiefighter -- curl -s -XPOST -v user:pass@deathstar.default.svc.cluster.local/v1/request-landing`

## Investigation/Debugging

1. After a bit of searching it seems that it's not Cilium's HTTP parser's fault that user info is not detected in URLs. 

   The [decodeHTTP()](https://github.com/cilium/cilium/blob/main/pkg/hubble/parser/seven/http.go#L19) method receives an `accesslog.LogRecordHTTP` that it only reads, not modifies. In turn, this record is set via `r.HTTP` when `decodeHTTP()` is invoked in https://github.com/cilium/cilium/blob/main/pkg/hubble/parser/seven/parser.go#L359. In turn, `r` is a `LogRecord` struct that contains the [LogRecordHTTP](https://github.com/cilium/cilium/blob/main/pkg/proxy/accesslog/record.go#L195) field for HTTP log records which, in turn, contains the full URL, possibly containing user info.

   However, when the HTTP log record and tags are created in https://github.com/cilium/cilium/blob/main/pkg/envoy/accesslog_server.go#L176 I see that we compute the URL **without** parsing and setting user info (we only set scheme, host and path):

   ```go
	l7tags = logger.LogTags.HTTP(&accesslog.LogRecordHTTP{
		Method:          httpLogEntry.Method,
		Code:            int(httpLogEntry.Status),
		URL:             ParseURL(httpLogEntry.Scheme, httpLogEntry.Host, httpLogEntry.Path),  <--
		Protocol:        GetProtocol(httpLogEntry.HttpProtocol),
		Headers:         GetNetHttpHeaders(httpLogEntry.Headers),
		MissingHeaders:  GetNetHttpHeaders(httpLogEntry.MissingHeaders),
		RejectedHeaders: GetNetHttpHeaders(httpLogEntry.RejectedHeaders),
	})
   ``` 

   Based on the above, it does not make sense how Cilium's HTTP parser is supposed to parse and detect user info in the URL of the provided `accesslog.LogRecordHTTP`. Does this mean that we will have to extend `HTTPLogEntry` of the Cilium API defined in:

   https://github.com/cilium/cilium/blob/main/vendor/github.com/cilium/proxy/go/cilium/api/accesslog.pb.go#L181

   I see that this file is auto-generated. BTW, I could not locate the referenced source file: `cilium/api/accesslog.proto` Feel free to provide feedback on the above and correct me if any assumptions are not correct. 

2. I was able to "short-circuit" Envoy to always include the `user:pass@` part in observed URLs, even if it is not actually present in the URL of the HTTP request. I did so by modifying the following line https://github.com/cilium/cilium/blob/main/pkg/envoy/accesslog.go#L19 to:

```diff
- u, err := url.Parse(fmt.Sprintf("%s://%s/%s", scheme, host, strings.TrimPrefix(path, "/")))
+ u, err := url.Parse(fmt.Sprintf("%s://%s:%s@%s/%s", scheme, "user", "pass", host, strings.TrimPrefix(path, "/")))
```

After this I was able to see the password getting redacted by Cilium's HTTP parser:

```yaml
      "http": {
        "code": 200,
        "method": "POST",
        "url": "http://user:HUBBLE_REDACTED@deathstar.default.svc.cluster.local/v1/request-landing",   <---
        "protocol": "HTTP/1.1",
```

This probably allows me to focus on extending Cilium's configuration mechanism to conditionally redact user info in HTTP flows, rather than ensuring that user info is present in observed URLs, if specified.

@rolinh @lambdanis @chancez @nathanjsweet @nbusseneau (cc-ing you since you were recently involved in https://github.com/cilium/cilium/pull/26724) 
@ChrsMark (cc-ing you for visibility)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
