### ISSUE TITLE
CiliumNetworkPolicy drop action notify pod that traffic has been dropped

### ISSUE THREAD

**Issue by spal-x** [cilium/cilium#28802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have a CiliumClusterwideNetworkPolicy prohibiting certain pods from accessing outside the cluster (only pods with label my.label/cluster-outside-access can negotitate with entities outside the cluster)
```yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
  name: egress-world
spec:
  egress:
  - toEntities:
    - world
  endpointSelector:
    matchLabels:
      my.label/cluster-outside-access: "true"
```
Actual behavior: the pod connection is closed by a timeout corresponding to the kernel settings.
The question is: is it possible to achieve behavior similar to a typical firewall - a RESET is sent to the client if sending traffic is not provided for by the policy?

### Cilium Version

1.13.2

### Kernel Version

5.14.0-168.el9.x86_64

### Kubernetes Version

kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.27.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
