### ISSUE TITLE
Spire beta: enforcing authentication breaks audit mode

### ISSUE THREAD

**Issue by HanssenKai** [cilium/cilium#28824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when installing cilium with values
```
authentication:
  mutual:
    spire:
      install:
        enabled: true
      enabled: true 

policyAuditMode: true
```

and using network policy to enforce mTLS via `authentication.mode: required`, the traffic shows as AUDIT even though it would be allowed with policyAuditMode set to false. It seems the mTLS handshakes aren't done in audit mode, so perhaps audit mode should assume successful mTLS handshakes?

hubble from foo to bar:
Oct 26 12:25:36.736: minimal/foo:53578 -> minimal/bar:80 L3-Only FORWARDED (TCP Flags: SYN)
Oct 26 12:25:36.736: minimal/foo:53578 -> minimal/bar:80 L3-Only FORWARDED (TCP Flags: SYN)
Oct 26 12:25:36.736: minimal/foo:53578 -> minimal/bar:80 to-endpoint FORWARDED (TCP Flags: SYN)
Oct 26 12:25:36.736: minimal/foo:53578 <- minimal/bar:80 to-endpoint FORWARDED (TCP Flags: ACK, RST)

hubble from bar to foo
Oct 26 12:25:37.959: minimal/bar:43728 -> minimal/foo:80 L3-Only AUDIT (TCP Flags: SYN)
Oct 26 12:25:37.959: minimal/bar:43728 -> minimal/foo:80 L3-Only FORWARDED (TCP Flags: SYN)
Oct 26 12:25:37.959: minimal/bar:43728 -> minimal/foo:80 to-endpoint FORWARDED (TCP Flags: SYN)
Oct 26 12:25:37.959: minimal/bar:43728 <- minimal/foo:80 to-endpoint FORWARDED (TCP Flags: ACK, RST)

### Cilium Version

1.14.2

### Kernel Version

6.1.44-talos

### Kubernetes Version

1.26.0

### Sysdump

[cilium-sysdump-20231026-195550.zip](https://github.com/cilium/cilium/files/13181038/cilium-sysdump-20231026-195550.zip)

### Anything else?

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: foo
specs:
- endpointSelector:
    matchLabels:
      app: foo
  ingress:
  - fromEndpoints:
    - {}
  egress:
  - toEndpoints:
    - matchLabels:
        app: bar
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: bar
specs:
- endpointSelector:
    matchLabels:
      app: bar
  ingress:
  - fromEndpoints:
    - {}
  egress:
  - toEndpoints:
    - matchLabels:
        app: foo
    authentication:
      mode: "required"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
