### ISSUE TITLE
Cannot communicate Kubernetes API Server in EKS start 1.14

### ISSUE THREAD

**Issue by DingGGu** [cilium/cilium#28882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Start Cilium 1.14, Certain pods cannot connect to control plane.
You know, EKS provider control plane host 172.20.0.1:443.

Example of cluster-autoscaler's log:
```
F1031 04:36:45.526866       1 main.go:508] Failed to get nodes from apiserver: Get "https://172.20.0.1:443/api/v1/nodes": dial tcp 172.20.0.1:443: i/o timeout
```

1. Symptoms of cannot connect to with kube-apiserver occur on a node-by-node basis. When one of the nodes becomes unable to communicate and is “contagious” to other nodes when it is drain problem node.
2. Restart problem pod can solve error, not always. However the symptom recurs 2 to 5 days later.
3. I confirmed that there was no problem in 1.13.
4. I confirmed that the same problem occurs in EKS 1.26 to 1.28.
5. I confirmed that the same problem occurs in Cilium 1.14.0 ~ 1.14.3

### Cilium Version

```
Client: 1.14.3 252a99ef 2023-10-18T18:21:56+03:00 go version go1.20.10 linux/amd64
Daemon: 1.14.3 252a99ef 2023-10-18T18:21:56+03:00 go version go1.20.10 linux/amd64
```

### Kernel Version

```
Linux ip-10-74-107-86 5.15.0-1045-aws #50~20.04.1-Ubuntu SMP Wed Sep 6 17:29:11 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.9-eks-f8587cb", GitCommit:"2e0997b730999ec918be56b8ed945394905673c5", GitTreeState:"clean", BuildDate:"2023-09-18T22:09:26Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

I can't provide sysdump to public. Please understand.

```
# vaules.yaml for helm
k8sServiceHost: <<EKS_API_SERVER_HOST>>
k8sServicePort: 443

eni:
  enabled: true
ipam:
  mode: eni
tunnel: disabled
kubeProxyReplacement: true
bpf:
  masquerade: true
loadBalancer:
  serviceTopology: true

cni:
  exclusive: false # for istio

envoy:
  enabled: true
```

### Anything else?

Somebody get same error. you can find in comment reaction.
https://github.com/cilium/cilium/issues/20679#issuecomment-1677199340

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
