### ISSUE TITLE
Cilium IPTables mode allows ClusterIP Traffic to get outside the cluster

### ISSUE THREAD

**Issue by QuinnBast** [cilium/cilium#28904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've killed some Nodes in my cluster that have a Kafka ClusterIP service running with a hostPath PV attached to them. The cluster is providing a cluster internal IP address for the service, `10.106.242.70`. But because I took the node offline, my service has no backend to provide service to it (as I would expect). However, in this scenario, Cilium is still resolving the service's IP address and telling the pods that they should talk to `10.106.242.70`. But since there is nothing listening there, the traffic is escaping my local network and ends up flooding our corporate network trying to access this `10.*` IP address that doesn't exist.

Cilium shows outgoing requests to the world:

> Oct 30 17:48:40.922: ns/myPod:56940 (ID:43137) -> kafka/kafka-cluster-kafka-bootstrap:9092 (world) to-stack FORWARDED (TCP Flags: SYN)

However, my Service:
```
spec:
  clusterIP: 10.106.242.70
  clusterIPs:
  - 10.106.242.70
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-replication
    port: 9091
    protocol: TCP
    targetPort: 9091
  - name: tcp-clients
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    strimzi.io/cluster: kafka-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: kafka-cluster-kafka
  sessionAffinity: None
  type: ClusterIP
```

Has an `Endpoint` and `EndpointSlice` that are both being marked as `NotReady`:

Endpoint:
```
subsets:
- notReadyAddresses:
  - ip: 10.0.1.234
    nodeName: ic-calian-worker-1
    targetRef:
      kind: Pod
      name: kafka-cluster-kafka-2
      namespace: kafka
      uid: 2eaf03a1-0860-4099-8277-d427569c9885
  ports:
  - name: tcp-clients
    port: 9092
    protocol: TCP
  - name: tcp-replication
    port: 9091
    protocol: TCP
```

EndpointSlice:
```
endpoints:
- addresses:
  - 10.0.1.234
  conditions:
    ready: false
    serving: false
    terminating: false
  nodeName: worker-1
  targetRef:
    kind: Pod
    name: kafka-cluster-kafka-2
    namespace: kafka
    uid: 2eaf03a1-0860-4099-8277-d427569c9885
```

Additionally, we can specifically see that the IPTable rules on our host machines explicity indicate that there is a `DROP` rule in the iptables for the host which should be blocking any traffic destined for the `10.106.242.70` IP address (see the last 3 rules):

```
$ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N CILIUM_FORWARD
-N CILIUM_INPUT
-N CILIUM_OUTPUT
-N KUBE-EXTERNAL-SERVICES
-N KUBE-FIREWALL
-N KUBE-FORWARD
-N KUBE-KUBELET-CANARY
-N KUBE-NODEPORTS
-N KUBE-PROXY-CANARY
-N KUBE-SERVICES
-A INPUT -m comment --comment "cilium-feeder: CILIUM_INPUT" -j CILIUM_INPUT
-A INPUT -m comment --comment "kubernetes health check service ports" -j KUBE-NODEPORTS
-A INPUT -m conntrack --ctstate NEW -m comment --comment "kubernetes externally-visible service portals" -j KUBE-EXTERNAL-SERVICES
-A INPUT -j KUBE-FIREWALL
-A FORWARD -m comment --comment "cilium-feeder: CILIUM_FORWARD" -j CILIUM_FORWARD
-A FORWARD -m comment --comment "kubernetes forwarding rules" -j KUBE-FORWARD
-A FORWARD -m conntrack --ctstate NEW -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A FORWARD -m conntrack --ctstate NEW -m comment --comment "kubernetes externally-visible service portals" -j KUBE-EXTERNAL-SERVICES
-A OUTPUT -m comment --comment "cilium-feeder: CILIUM_OUTPUT" -j CILIUM_OUTPUT
-A OUTPUT -m conntrack --ctstate NEW -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -j KUBE-FIREWALL
-A CILIUM_FORWARD -o cilium_host -m comment --comment "cilium: any->cluster on cilium_host forward accept" -j ACCEPT
-A CILIUM_FORWARD -i cilium_host -m comment --comment "cilium: cluster->any on cilium_host forward accept (nodeport)" -j ACCEPT
-A CILIUM_FORWARD -i lxc+ -m comment --comment "cilium: cluster->any on lxc+ forward accept" -j ACCEPT
-A CILIUM_FORWARD -i cilium_net -m comment --comment "cilium: cluster->any on cilium_net forward accept (nodeport)" -j ACCEPT
-A CILIUM_INPUT -m mark --mark 0x200/0xf00 -m comment --comment "cilium: ACCEPT for proxy traffic" -j ACCEPT
-A CILIUM_OUTPUT -m mark --mark 0xa00/0xfffffeff -m comment --comment "cilium: ACCEPT for proxy return traffic" -j ACCEPT
-A CILIUM_OUTPUT -m mark --mark 0x800/0xe00 -m comment --comment "cilium: ACCEPT for l7 proxy upstream traffic" -j ACCEPT
-A CILIUM_OUTPUT -m mark ! --mark 0xe00/0xf00 -m mark ! --mark 0xd00/0xf00 -m mark ! --mark 0xa00/0xe00 -m mark ! --mark 0x800/0xe00 -m mark ! --mark 0xf00/0xf00 -m comment --comment "cilium: host->any mark as from host" -j MARK --set-xmark 0xc00/0xf00
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
-A KUBE-FIREWALL ! -s 127.0.0.0/8 -d 127.0.0.0/8 -m comment --comment "block incoming localnet connections" -m conntrack ! --ctstate RELATED,ESTABLISHED,DNAT -j DROP
-A KUBE-FORWARD -m conntrack --ctstate INVALID -j DROP
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x4000/0x4000 -j ACCEPT
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding conntrack rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-SERVICES -d 10.106.242.70/32 -p tcp -m comment --comment "kafka/kafka-cluster-kafka-bootstrap:tcp-clients has no endpoints" -m tcp --dport 9092 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.106.242.70/32 -p tcp -m comment --comment "kafka/kafka-cluster-kafka-bootstrap:tcp-replication has no endpoints" -m tcp --dport 9091 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.103.51.209/32 -p tcp -m comment --comment "kafka/kafka-cluster-zookeeper-client:tcp-clients has no endpoints" -m tcp --dport 2181 -j REJECT --reject-with icmp-port-unreachable
```

However, despite this, the traffic is getting sent to the world and our corporate network is getting flooded with requests to this IP address that doesn't exist.

### Cilium Version

Client: 1.12.3 1c466d2 2022-10-12T11:33:37+01:00 go version go1.18.6 linux/amd64
Daemon: 1.12.3 1c466d2 2022-10-12T11:33:37+01:00 go version go1.18.6 linux/amd64

### Kernel Version

Linux worker-2 5.15.0-43-generic #46~20.04.1-Ubuntu SMP Thu Jul 14 15:20:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:47:37Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

My machines don't have internet to be able to easily do this...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
