### ISSUE TITLE
Using local redirect policy on host network daemonset backends, the service become not accessible from node and host network pod

### ISSUE THREAD

**Issue by ghost** [cilium/cilium#28918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We deploy coredns as daemonset with `hostNetwork: true`, create service name `kube-dns` for the daemonset. Then use the following CiliumLocalRedirectPolicy to make dns request send to the same node with client pod. However, for client pods which configured as `hostNetwork: true` as well, requests to the service get no reponses. This is same for requests from the host node.

Non-hostnetwork client pod works well with the clrp coredns.

I think these requests to service IP are not translated in cgroup sockops `sock4_skip_xlate_if_same_netns`(maybe?), so the requests are sent to gateway as route table point out.

This is no effects whether coredns daemonset's annotations contain `policy.cilium.io/no-track-port` or not

clrp
```
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: kube-dns-service
  namespace: kube-system
spec:
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: kube-dns
    toPorts:
    - name: dns
      port: "5353"
      protocol: UDP
    - name: dns-tcp
      port: "5353"
      protocol: TCP
  redirectFrontend:
    serviceMatcher:
      namespace: kube-system
      serviceName: kube-dns
```

cilium-config
```
apiVersion: v1
data:
  arping-refresh-period: 30s
  auto-direct-node-routes: "true"
  bpf-lb-algorithm: maglev
  bpf-lb-external-clusterip: "false"
  bpf-lb-map-max: "65536"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: "0"
  cluster-name: default
  cluster-pool-ipv4-cidr: <...>
  cluster-pool-ipv4-mask-size: "25"
  cni-uninstall: "false"
  custom-cni-conf: "true"
  debug: "false"
  disable-cnp-status-updates: "true"
  disable-endpoint-crd: "false"
  enable-auto-protect-node-port-range: "true"
  enable-bandwidth-manager: "true"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "true"
  enable-endpoint-health-checking: "true"
  enable-endpoint-routes: "false"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-host-legacy-routing: "false"
  enable-host-reachable-services: "true"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv4-masquerade: "true"
  enable-ipv6: "false"
  enable-ipv6-masquerade: "true"
  enable-k8s-terminating-endpoint: "true"
  enable-l2-neigh-discovery: "true"
  enable-l7-proxy: "true"
  enable-local-node-route: "true"
  enable-local-redirect-policy: "true"
  enable-metrics: "true"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  hubble-disable-tls: "true"
  hubble-listen-address: :4244
  hubble-metrics: dns drop tcp flow port-distribution icmp http
  hubble-metrics-server: :9091
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  install-no-conntrack-iptables-rules: "false"
  ipam: cluster-pool
  ipv4-native-routing-cidr: <...>
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: ""
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: :6942
  preallocate-bpf-maps: "false"
  routing-mode: native
  sidecar-istio-proxy-image: cilium/istio_proxy
  tunnel: ""
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
```

### Cilium Version

1.14.3

### Kernel Version

5.10

### Kubernetes Version

1.24.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
