### ISSUE TITLE
IPv4 conntrack map global lookup failed: Success when using Gateway API

### ISSUE THREAD

**Issue by TECHNOFAB11** [cilium/cilium#28979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I tried to get the Gateway API working. I created a Gateway and HTTPRoute which worked fine but then I realized that the LoadBalancer service did not get an IP. I discovered that single-IP LB-IPAM pools don't work and thus upgraded to pre.2. Then that worked and the LoadBalancer received the single IP. When I tried to access the IP, that was the reponse:
```
< HTTP/1.1 500 Internal Server Error
< date: Fri, 03 Nov 2023 18:17:11 GMT
< server: envoy
< content-length: 0
```

I checked the logs and the only thing i was able to find is the `failed: Success` message getting logged shortly after every request I made. 
I'm using NixOS so there is nothing installed that isn't needed and the firewall there is really closed down by default, that already resulted in some issues some time ago, so that's a possibility. 

### Cilium Version

cilium-cli: v0.15.8 compiled with go1.21.0 on linux/amd64
cilium image (default): v1.14.1
cilium image (stable): v1.14.3
cilium image (running): unknown. Unable to obtain cilium version, no cilium pods found in namespace "kube-system"

I used the Helm Chart version 1.15.0-pre.2, so cilium should be the same version. `cilium status` is fine so not sure why it can't obtain the cilium version

### Kernel Version

Linux <hostname> 6.1.61 #1-NixOS SMP Thu Nov  2 08:35:33 UTC 2023 aarch64 GNU/Linux

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "1970-01-01T01:01:01Z"
  compiler: gc
  gitCommit: bd04941a294793ec92e8703d5e5da14107902e88
  gitTreeState: clean
  gitVersion: v1.27.6+k3s1
  goVersion: go1.20.10
  major: "1"
  minor: "27"
  platform: linux/arm64
  kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "1970-01-01T01:01:01Z"
  compiler: gc
  gitCommit: bd04941a294793ec92e8703d5e5da14107902e88
  gitTreeState: clean
  gitVersion: v1.27.6+k3s1
  goVersion: go1.20.10
  major: "1"
  minor: "27"
  platform: linux/arm64
```

### Sysdump

[cilium-sysdump-20231103-191556.zip](https://github.com/cilium/cilium/files/13253438/cilium-sysdump-20231103-191556.zip)

### Relevant log output

```shell
level=info msg="[cilium.bpf_metadata: IPv4 conntrack map global lookup failed: Success" subsys=envoy-filter threadID=65
```

### Anything else?

Helm Values:
```nix
kubeProxyReplacement = true;
k8sServiceHost = "10.0.0.214";
k8sServicePort = 6443;
l2announcements.enabled = true;
ipam.operator.clusterPoolIPv4PodCIDRList = "10.42.0.0/16";
nodePort.enabled = true;
gatewayAPI.enabled = true;
operator.replicas = 1;
loadBalancer.l7.backend = "envoy";
prometheus.enabled = true;
hubble = {
  relay.enabled = true;
  ui.enabled = true;
  tls.auto.method = "cronJob";
};
clustermesh.apiserver.tls.auto.method = "cronJob";
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
