### ISSUE TITLE
Gateway API BackendRef filters support

### ISSUE THREAD

**Issue by tomaszkiewicz** [cilium/cilium#29080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While trying to get KNative Serving working with Cilium Gateway API (I'm aware it's in alpha in KNative, but I want to make it working with Cilium as I like the project :) ) I've found issue with backendRef filters support - https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.HTTPBackendRef .

Let's consider sample HTTPRoute, which is simplified example of what KNative Serving creates, but with added some of my troubleshooting steps:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  [...]
  name: httpbin2.default.172.20.5.10.sslip.io
  namespace: default
spec:
  hostnames:
  - httpbin2.default.172.20.5.10.sslip.io
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cilium-gateway
    namespace: default
  rules:
  - backendRefs:
    - filters:
      - requestHeaderModifier:
          set:
          - name: Knative-Serving-Revision
            value: httpbin-00001
          - name: Knative-Serving-Namespace
            value: default
# added by me
          - name: X-Set-In-BackendRefs
            value: "true"
# end of added by me
        type: RequestHeaderModifier
      group: ""
      kind: Service
      name: httpbin-00001
      port: 80
      weight: 100
# added by me
    filters:
    - requestHeaderModifier:
        set:
        - name: X-Set-In-Filters
          value: "true"
      type: RequestHeaderModifier
# end of added by me
    matches:
    - path:
        type: PathPrefix
        value: /
```

The key part is `spec.rules[0].backendRefs.filters` as this is the part that KNative Serving creates.

Now let's execute curl:

```sh
~> curl "http://httpbin2.default.172.20.5.10.sslip.io/headers" -H "Knative-Serving-Revision: httpbin-00001" -H "Knative-Serving-Namespace: default" -H "x-test: 123"
{
  "headers": {
    "Accept": "*/*",
    "Forwarded": "for=192.168.1.229;proto=http, for=10.42.1.44",
    "Host": "httpbin2.default.172.20.5.10.sslip.io",
    "K-Proxy-Request": "activator",
    "User-Agent": "curl/7.68.0",
    "X-Envoy-Internal": "true",
    "X-Set-In-Filters": "true",
    "X-Test": "123"
  }
}
```

As you can see:, X-Set-In-Filters is set correctly, but  X-Set-In-BackendRefs is not set at all as well as other headers in backendRef.filters.

That behaviour/lack of support makes impossible to run KNative Serving on Cilium as required headers (as you can see in curl command above) as missing thus KNative cannot route to correct revision.

### Cilium Version

cilium-cli: v0.15.13 compiled with go1.21.3 on linux/amd64
cilium image (default): v1.14.2
cilium image (stable): v1.14.3
cilium image (running): 1.14.3

### Kernel Version

Doesn't matter for the case.

### Kubernetes Version

1.27.7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chaunceyjiang** [comment]
I'll try to fix this issue.

**Comment by acelinkio** [comment]
I am looking to setup Cilium/Knative via gatewayapi.  I got Cilium (1.15-rc0) gateway controller working with the release of gatewayapi v1.0.  Also have Knative (1.12.3) functioning with kourier ingress controller.

So I am in a good place to start tinkering and hopefully adding Cilium to Knative's testing suit. https://github.com/knative-extensions/net-gateway-api/issues/553

**Comment by Enealor** [comment]
acelinkio and I tested the gateway API with the above configuration. As tomaszkiewicz describes, the backend filters are not supported. When using the above configuration, the headers added as part of the backend reference are not added to the Envoy configuration, which results in the missing headers. I looked through the code for [ingesting the http route](https://github.com/cilium/cilium/blob/v1.15.0-rc.0/operator/pkg/model/ingestion/gateway.go#L105-L217
). I see that the top-level filters for each rule (spec.rules[].filters) are [added](https://github.com/cilium/cilium/blob/v1.15.0-rc.0/operator/pkg/model/ingestion/gateway.go#L162), but cannot find where the backend filters (spec.rules[].backendRefs[].filters) are added. The current conformance tests also do not cover the scenario where the backendRef item has filters.

I think the fix is to inspect the backendRefs for this optional key during the HTTPRoute creation for each backend, but I am not familiar enough with the code to find where this occurs.

**Comment by acelinkio** [comment]
Hey @chaunceyjiang !  Happy New Year!

Have you had a chance to work on this?  Would be awesome to fully transition to gateway resources!  Let us know we can best assist with this effort.  

Thanks!

**Comment by chaunceyjiang** [comment]
Hi, @acelinkio Happy New Year!

> Have you had a chance to work on this? 

Yes.


Currently I'm still learning `envoy`. I will finish this work as soon as possible.

**Comment by chaunceyjiang** [comment]
Hi, @acelinkio @tomaszkiewicz @Enealor Happy New Year !

I have implemented this feature and it has passed local testing successfully. Could you please help test this feature based on my PR?

**Comment by acelinkio** [comment]
Hey Chauncy!

Using helm chart 1.15.0-rc.0, I overwrote the container image generated from your PR workflows (https://github.com/cilium/cilium/actions/runs/7399979212/job/20132600608) by specifying the following values
```
operator:
    image:
      override: "quay.io/cilium/operator-generic-ci:a199ad6584be1047dc480e82b87d0e54ad008c24"
```

I was able to successfully set headers using via BackendRef filters!

**Comment by tomaszkiewicz** [comment]
@acelinkio is it the only change you made? I also tried to test on my original setup with above override and I still have no proper headers...

**Comment by chaunceyjiang** [comment]
Can you share your HTTPRoute ? @tomaszkiewicz

**Comment by tomaszkiewicz** [comment]
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  annotations:
    networking.internal.knative.dev/rollout: '{"configurations":[{"configurationName":"httpbin","percent":100,"revisions":[{"revisionName":"hello-00001","percent":100}],"stepParams":{}}]}'
    networking.knative.dev/ingress.class: gateway-api.ingress.networking.knative.dev
    serving.knative.dev/creator: system:admin
    serving.knative.dev/lastModifier: system:admin
  labels:
    networking.knative.dev/visibility: ""
    serving.knative.dev/route: httpbin
    serving.knative.dev/routeNamespace: default
    serving.knative.dev/service: httpbin
  name: httpbin2.default.172.20.5.10.sslip.io
  namespace: default
spec:
  hostnames:
  - httpbin2.default.172.20.5.10.sslip.io
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cilium-gateway
    namespace: default
  rules:
  - backendRefs:
    - filters:
      - requestHeaderModifier:
          set:
          - name: Knative-Serving-Revision
            value: httpbin-00001
          - name: Knative-Serving-Namespace
            value: default
          - name: X-Set-In-BackendRefs
            value: "true"
        type: RequestHeaderModifier
      group: ""
      kind: Service
      name: httpbin-00001
      port: 80
      weight: 100
    filters:
    - requestHeaderModifier:
        set:
        - name: Knative-Serving-Revision
          value: httpbin-00001
        - name: Knative-Serving-Namespace
          value: default
        - name: X-Set-In-Filters
          value: "true"
      type: RequestHeaderModifier
    matches:
    - path:
        type: PathPrefix
        value: /
```
