### ISSUE TITLE
Gateway API RequestRedirect picks wrong port with multiple listeners

### ISSUE THREAD

**Issue by meyskens** [cilium/cilium#29099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When setting a `RequestRedirect` filter in an HTTPRoute the response sends back the port of the 1st listener defined in the gateway no matter what port or protocol was used. This causes redirects to be incorrectly forwarded eg. from HTTPS on 443 to HTTPS on port 80 as this was the first listener set.

### Cilium Version

v1.15.0-pre.1

### Kernel Version

6.1.0-rpi4-rpi-v8

### Kubernetes Version

v1.26.10

### Relevant log output
Config:

```yaml
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: go2rtc
spec:
  gatewayClassName: cilium
  listeners:
  - name: http
    protocol: HTTP
    port: 80
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate 
      certificateRefs:
      - kind: Secret
        group: ""
        name: go2rtc-tls
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: go2rtc-public
spec:
  parentRefs:
  - name: go2rtc
  hostnames:
  - "blinken.rpi.maartje.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
      - type: RequestRedirect
        requestRedirect:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /home
  - matches:
    - path:
        type: PathPrefix
        value: /home
      method: GET
    backendRefs:
    - name: go2rtc-home
      port: 80

```
Curl output:
```
maartje@maartje-XPS-9315 ~ [SIGINT]> curl https://blinken.rpi.maartje.dev -v
> GET / HTTP/1.1
> Host: blinken.rpi.maartje.dev
> User-Agent: curl/7.81.0
> Accept: */*
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< location: https://blinken.rpi.maartje.dev:80/home
< date: Fri, 10 Nov 2023 10:12:31 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host blinken.rpi.maartje.dev left intact
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chaunceyjiang** [comment]
Hi @sayboras 

Have you already started this task? If not, I would like to resolve this issue.

**Comment by sayboras** [comment]
:wave: 

Can you help to check if this has been resolved in main branch after https://github.com/cilium/cilium/pull/29115?

**Comment by chaunceyjiang** [comment]
hi, @sayboras  After testing based on commit log: bb9931cf200965a6b9b01b56cd15461c162f01a6, I believe that this issue has not been modified.



```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: tls-gateway
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    hostname: "bookinfo.cilium.rocks"
    name: web-gw
    allowedRoutes:
      namespaces:
        from: Same
  - name: https-1
    protocol: HTTPS
    port: 443
    hostname: "bookinfo.cilium.rocks"
    tls:
      certificateRefs:
      - kind: Secret
        name: demo-cert
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: https-app-route-1
spec:
  parentRefs:
  - name: tls-gateway
  hostnames:
  - "bookinfo.cilium.rocks"
  rules:
  - matches:
      - path:
          type: PathPrefix
          value: /
    filters:
      - type: RequestRedirect
        requestRedirect:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /details
  - matches:
    - path:
        type: PathPrefix
        value: /details
    backendRefs:
    - name: http-echo
      port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo
  labels:
    app: http-echo
spec:
  selector:
    app: http-echo
  type: ClusterIP
  ports:
    - name: http-port
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
  labels:
    app: http-echo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
        - name: http-echo
          image: jmalloc/echo-server
          args: [ "-version", "v2" ]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
```




<img width="759" alt="image" src="https://github.com/cilium/cilium/assets/17962021/63ca53d2-5847-4723-a7c9-f4c63796f5b6">



<img width="873" alt="image" src="https://github.com/cilium/cilium/assets/17962021/12a6cfb0-e5fb-4006-9065-12e78763d3fa">


According to my understanding, the place I marked with a red line should be `https://bookinfo.cilium.rocks:443/details`. 

Am I right?

**Comment by chaunceyjiang** [comment]
``` shell
kubectl get ciliumenvoyconfigs cilium-gateway-tls-gateway -oyaml

[...]
  - '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
    name: listener-insecure
    virtualHosts:
    - domains:
      - bookinfo.cilium.rocks
      - bookinfo.cilium.rocks:*
      name: bookinfo.cilium.rocks
      routes:
      - match:
          pathSeparatedPrefix: /details
        route:
          cluster: default:http-echo:8080
      - match:
          prefix: /
        redirect:
          portRedirect: 80
          prefixRewrite: /details
          responseCode: FOUND
  - '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
    name: listener-secure
    virtualHosts:
    - domains:
      - bookinfo.cilium.rocks
      - bookinfo.cilium.rocks:*
      name: bookinfo.cilium.rocks
      routes:
      - match:
          pathSeparatedPrefix: /details
        route:
          cluster: default:http-echo:8080
      - match:
          prefix: /
        redirect:
          portRedirect: 80          # Perhaps it should be 443?
          prefixRewrite: /details
          responseCode: FOUND
```

**Comment by chaunceyjiang** [comment]
Hi @sayboras @meyskens Could you please take a look at my test results?

**Comment by aaronmondal** [comment]
Ran into this on cilium `0.14.0` with Gateway API resources v1.0-experimental-install. That issue seems fixed with the latest release. With two http listeners on two different ports 1.14.4 binds the `HTTPRoute`s to both listeners. 1.15.0-pre.3 correctly attaches one route to each listener. Note the `Attached Routes` in the output of `kubectl describe gtw`:

```yaml
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: native-link-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: cache
      protocol: HTTP
      port: 50051
    - name: scheduler
      protocol: HTTP
      port: 50052
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute  # TODO(aaronmondal): Set to GRPCRoute
metadata:
  name: native-link-cache-route
spec:
  parentRefs:
    - name: native-link-gateway
      sectionName: cache
  rules:
    - backendRefs:
      - name: native-link-cas
        port: 50051
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute  # TODO(aaronmondal): Set to GRPCRoute
metadata:
  name: native-link-scheduler-route
spec:
  parentRefs:
    - name: native-link-gateway
      sectionName: scheduler
  rules:
    - backendRefs:
      - name: native-link-scheduler
        port: 50052
```

With Cilium 1.14.4:

```
Name:         native-link-gateway
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1
Kind:         Gateway
Metadata:
  Creation Timestamp:  2023-12-10T20:10:40Z
  Generation:          1
  Resource Version:    230066
  UID:                 30158f4c-98da-4334-b41b-d634ba2522cf
Spec:
  Gateway Class Name:  cilium
  Listeners:
    Allowed Routes:
      Namespaces:
        From:  Same
    Name:      cache
    Port:      50051
    Protocol:  HTTP
    Allowed Routes:
      Namespaces:
        From:  Same
    Name:      scheduler
    Port:      50052
    Protocol:  HTTP
Status:
  Addresses:
    Type:   IPAddress
    Value:  172.20.255.200
  Conditions:
    Last Transition Time:  2023-12-10T20:10:40Z
    Message:               Gateway successfully scheduled
    Observed Generation:   1
    Reason:                Accepted
    Status:                True
    Type:                  Accepted
    Last Transition Time:  2023-12-10T20:10:40Z
    Message:               Gateway successfully reconciled
    Observed Generation:   1
    Reason:                Programmed
    Status:                True
    Type:                  Programmed
  Listeners:
    Attached Routes:  2  <------------------------- HERE
    Conditions:
      Last Transition Time:  2023-12-10T20:10:40Z
      Message:               Listener Programmed
      Observed Generation:   1
      Reason:                Programmed
      Status:                True
      Type:                  Programmed
      Last Transition Time:  2023-12-10T20:10:40Z
      Message:               Listener Accepted
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
    Name:                    cache
    Supported Kinds:
      Group:          gateway.networking.k8s.io
      Kind:           HTTPRoute
    Attached Routes:  2  <------------------------- HERE
    Conditions:
      Last Transition Time:  2023-12-10T20:10:40Z
      Message:               Listener Programmed
      Observed Generation:   1
      Reason:                Programmed
      Status:                True
      Type:                  Programmed
      Last Transition Time:  2023-12-10T20:10:40Z
      Message:               Listener Accepted
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
    Name:                    scheduler
    Supported Kinds:
      Group:  gateway.networking.k8s.io
      Kind:   HTTPRoute
Events:       <none>
```

With Cilium 1.15.0-pre.3:

```
Name:         native-link-gateway
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1
Kind:         Gateway
Metadata:
  Creation Timestamp:  2023-12-10T20:24:42Z
  Generation:          1
  Resource Version:    259220
  UID:                 36c5bec9-0111-4c3d-8741-8c257bd81704
Spec:
  Gateway Class Name:  cilium
  Listeners:
    Allowed Routes:
      Namespaces:
        From:  Same
    Name:      cache
    Port:      50051
    Protocol:  HTTP
    Allowed Routes:
      Namespaces:
        From:  Same
    Name:      scheduler
    Port:      50052
    Protocol:  HTTP
Status:
  Addresses:
    Type:   IPAddress
    Value:  172.20.255.200
  Conditions:
    Last Transition Time:  2023-12-10T20:24:42Z
    Message:               Gateway successfully scheduled
    Observed Generation:   1
    Reason:                Accepted
    Status:                True
    Type:                  Accepted
    Last Transition Time:  2023-12-10T20:24:42Z
    Message:               Gateway successfully reconciled
    Observed Generation:   1
    Reason:                Programmed
    Status:                True
    Type:                  Programmed
  Listeners:
    Attached Routes:  1  <------------------------- HERE
    Conditions:
      Last Transition Time:  2023-12-10T20:24:42Z
      Message:               Listener Programmed
      Observed Generation:   1
      Reason:                Programmed
      Status:                True
      Type:                  Programmed
      Last Transition Time:  2023-12-10T20:24:42Z
      Message:               Listener Accepted
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2023-12-10T20:24:42Z
      Message:               Resolved Refs
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Name:                    cache
    Supported Kinds:
      Group:          gateway.networking.k8s.io
      Kind:           HTTPRoute
    Attached Routes:  1  <------------------------- HERE
    Conditions:
      Last Transition Time:  2023-12-10T20:24:42Z
      Message:               Listener Programmed
      Observed Generation:   1
      Reason:                Programmed
      Status:                True
      Type:                  Programmed
      Last Transition Time:  2023-12-10T20:24:42Z
      Message:               Listener Accepted
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2023-12-10T20:24:42Z
      Message:               Resolved Refs
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Name:                    scheduler
    Supported Kinds:
      Group:  gateway.networking.k8s.io
      Kind:   HTTPRoute
Events:       <none>
```

**Comment by aaronmondal** [comment]
But yeah it seems that all traffic is still forwarded to the first route. I keep hitting `50051` even trying to connect to `50052`. It seems that the forwarding to the `backendRef` is broken.

I believe the following config should allow `xxx:50051/cache` and `xxx:50052/scheduler` and nothing else:

```yaml
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: native-link-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: cache
      protocol: HTTP
      port: 50051
    - name: scheduler
      protocol: HTTP
      port: 50052
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute  # TODO(aaronmondal): Set to GRPCRoute
metadata:
  name: native-link-cache-route
spec:
  parentRefs:
    - name: native-link-gateway
      sectionName: cache
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /cache
      backendRefs:
        - name: native-link-cas
          port: 50051
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute  # TODO(aaronmondal): Set to GRPCRoute
metadata:
  name: native-link-scheduler-route
spec:
  parentRefs:
    - name: native-link-gateway
      sectionName: scheduler
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /scheduler
      backendRefs:
        - name: native-link-scheduler
          port: 50052
```

However, we get the following script illustrates that this doesn't work (the last two work, but they should fail):

```bash
printf "
!!! Expecting failure, WORKS
"
curl http://172.20.255.200:50051 -v

printf "
!!! Expecting pass, WORKS
"
curl http://172.20.255.200:50051/cache -v

printf "
!!! Expecting pass, WORKS
"
curl http://172.20.255.200:50052/scheduler -v

printf "
!!! Expecting failure, BROKEN
"
curl http://172.20.255.200:50052/cache -v

printf "
!!! Expecting failure, BROKEN
"
curl http://172.20.255.200:50051/scheduler -v
```
```
!!! Expecting failure, BROKEN
*   Trying 172.20.255.200:50052...
* Connected to 172.20.255.200 (172.20.255.200) port 50052
> GET /cache HTTP/1.1
> Host: 172.20.255.200:50052
> User-Agent: curl/8.4.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< grpc-status: 12
< content-type: application/grpc
< content-length: 0
< date: Sun, 10 Dec 2023 22:33:36 GMT
< x-envoy-upstream-service-time: 0
< server: envoy
< 
* Connection #0 to host 172.20.255.200 left intact

!!! Expecting failure, BROKEN
*   Trying 172.20.255.200:50051...
* Connected to 172.20.255.200 (172.20.255.200) port 50051
> GET /scheduler HTTP/1.1
> Host: 172.20.255.200:50051
> User-Agent: curl/8.4.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< grpc-status: 12
< content-type: application/grpc
< content-length: 0
< date: Sun, 10 Dec 2023 22:33:36 GMT
< x-envoy-upstream-service-time: 0
< server: envoy
< 
* Connection #0 to host 172.20.255.200 left intact
```

Also, all traffic is sent to the first `backendRef` service and nothing is hitting the second `backendRef` service.

It seems that the gateway mashes all ports together and effectively acts as a global redirect from all matched routes to the first `backendRef` service.
