### ISSUE TITLE
Gateway APIs - Cannot interact with Load Balanced service

### ISSUE THREAD

**Issue by larivierec** [cilium/cilium#29144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using the service to communicate with the underlying service, we are unable to.
Cilium should use the Host header to indicate where to make the request.

I attempted to get some ideas/help on slack, i think it may have been too overwhelming in a chat context to have all this output and information.

You can see below that from the logs, it seems to not be based on the host header at all.
If this is intended, we can close the ticket.

Some key information, if I use my k8s_gateway resolver with the new CRDs it works locally because I don't believe it goes to the `cilium-gateway-cilium-external.infrastructure.svc`

The Gateway

```yaml
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-external
  namespace: infrastructure
  annotations:
    external-dns.alpha.kubernetes.io/target: ingress.example.tld
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: "192.168.40.21" # not supported in cilium yet
  listeners:
    - name: http-1
      protocol: HTTP
      port: 80
      hostname: "*.example.tld"
      allowedRoutes:
        namespaces:
          from: All
    - name: https-1
      protocol: HTTPS
      port: 443
      hostname: "*.example.tld"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: wildcard-cert-tls
```

the route

```yaml
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: echo.example.tld
    external-dns.alpha.kubernetes.io/target: dummy
    external-dns.alpha.kubernetes.io/ttl: "120"
  name: echo-server
  namespace: default
spec:
  hostnames:
  - echo.example.tld
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cilium-external
    namespace: infrastructure
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: echo-server
      namespace: default
      port: 8080
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
```
provisioned load balancers

```bash
NAME                             TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                      AGE
cilium-gateway-cilium-external   LoadBalancer   10.43.16.37     192.168.40.5   80:32557/TCP,443:30093/TCP   43h
cilium-gateway-cilium-internal   LoadBalancer   10.43.222.149   192.168.40.6   80:32484/TCP,443:31535/TCP   3d6h
```

insecure access -> Status 503
```bash
curl: (35) Recv failure: Connection reset by peer
/ # curl -v [http://cilium-gateway-cilium-external.infrastructure.svc:80](http://cilium-gateway-cilium-external.infrastructure.svc/) -H "Host: echo.example.tld"
*   Trying 10.43.16.37:80...
* Connected to cilium-gateway-cilium-external.infrastructure.svc (10.43.16.37) port 80
> GET / HTTP/1.1
> Host: echo.example.tld
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Sat, 11 Nov 2023 20:54:11 GMT
< server: envoy
<
* Connection #0 to host cilium-gateway-cilium-external.infrastructure.svc left intact
upstream connect error or disconnect/reset before headers. reset reason: connection timeout/
```

secure access -> ssl error
```bash
/ # curl -v [https://cilium-gateway-cilium-external.infrastructure.svc:443](https://cilium-gateway-cilium-external.infrastructure.svc/) -H "Host: echo.example.tld"
*   Trying 10.43.16.37:443...
* Connected to cilium-gateway-cilium-external.infrastructure.svc (10.43.16.37) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* Recv failure: Connection reset by peer
* OpenSSL SSL_connect: Connection reset by peer in connection to cilium-gateway-cilium-external.infrastructure.svc:443
* Closing connection
curl: (35) Recv failure: Connection reset by peer
```

If there's anything else I can do or provide, let me know, i'd be happy to

### Cilium Version

v1.15.0-pre.2

### Kernel Version

Linux k3s-worker-gpu-1 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.28.3+k3s2

### Relevant log output

```shell
level=debug msg="[tls:onServerName(), requestedServerName: cilium-gateway-cilium-external.infrastructure.svc" subsys=envoy-filter threadID=247
level=debug msg="[EGRESS POD IP: 10.42.1.183, destination IP: 10.43.16.37" subsys=envoy-misc threadID=247
level=debug msg="[cilium.bpf_metadata: Using conntrack map global" subsys=envoy-filter threadID=247
level=debug msg="[cilium.ipcache: 10.43.16.37 has ID 2" subsys=envoy-filter threadID=247
level=debug msg="[cilium.ipcache: 10.42.1.78 has ID 8" subsys=envoy-filter threadID=247
level=debug msg="[Cilium SocketOption(): source_identity: 8, ingress: false, port: 443, pod_ip: 10.42.1.78, source_addresses: /10.42.1.78:0/, mark: 80b00 (magic mark: b00, cluster: 0, ID: 8), proxy_id: 0" subsys=envoy-filter threadID=247
level=debug msg="[closing connection from 10.42.1.183:49852: no matching filter chain found" subsys=envoy-conn_handler threadID=247
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
