### ISSUE TITLE
CiliumIngress controller timeout in AWS ENI mode

### ISSUE THREAD

**Issue by anwbtom** [cilium/cilium#29235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

# Problem description
We're using the cilium ingress controller to handle ingress towards Kubernetes, this works great on all nodes, except if the ingress being hit is the worker-node also hosting the target pod.
When using NodePort this issue doesn't occur, Host-legacy routing or not doesn't seem to alter the behavior, to make sure its not AWS level, we tested this with all Security groups in play allowing all traffic from/to 0.0.0.0/0.

Think I've collected all the necessary information if more information is needed, or some configuration change/test is needed please let me know.

## Testing setup
We've tested this with or without a separate envoy-pod as well just to rule those sort of changes out.
Also when ssh-ing into the node, the pod does respond through curl.

We've used the bookinfo example ingress (described on the documentation page about Kubernetes ingress) as a testcase for this issue, no cilium or kubernetes networkpolicies are in play.
With this very simple ingress configuration:
``` yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: bookinfo
spec:
  ingressClassName: cilium
  rules:
  - host: hi.c1.were-testing.com
    http:
      paths:
      - backend:
          service:
            name: productpage
            port:
              number: 9080
        path: /
        pathType: Prefix
```

Helm values used during install
``` yaml
autoDirectNodeRoutes: true
bpf:
  hostLegacyRouting: true
  masquerade: true
  tproxy: true
cluster:
  name: c1
cni:
  configMap: cilium-cni
  customConf: true
  uninstall: false
debug:
  enabled: false
  verbose: policy
endpointRoutes:
  enabled: true
eni:
  awsEnablePrefixDelegation: true
  awsReleaseExcessIPs: true
  enabled: true
  eniTags:
    Cluster: c1
    Name: c1-cilium
    Target: pod
    cluster.k8s.amazonaws.com/name: c1
  iamRole: arn:aws:iam::{redacted}:role/eks/c1/app/cilium-c1
envoy:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 60s
      labels:
        release: prometheus-community
hubble:
  enabled: true
  metrics:
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - flows-to-world
    - port-distribution
    - icmp
    - httpV2
    interval: 60s
    serviceMonitor:
      enabled: true
      interval: 60s
      labels:
        release: prometheus-community
  relay:
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 60s
        labels:
          release: prometheus-community
  ui:
    enabled: true
ingressController:
  default: true
  enabled: true
  loadbalancerMode: shared
  service:
    insecureNodePort: 32080
    secureNodePort: 32443
    type: NodePort
ipam:
  mode: eni
ipv4NativeRoutingCIDR: {private_cidr}.208.0/21
k8sServiceHost: {redacted}.gr7.eu-central-1.eks.amazonaws.com
k8sServicePort: 443
kubeProxyReplacement: true
l7:
  backend: envoy
loadBalancer:
  mode: dsr
operator:
  priorityClassName: default-priority
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 60s
      labels:
        release: prometheus-community
  tolerations:
  - effect: NoSchedule
    key: operator
    operator: Exists
  - effect: PreferNoSchedule
    key: allowOnCoreCluster
    operator: Equal
    value: "true"
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 60s
    labels:
      release: prometheus-community
routingMode: native
```
## Testing results
To test what's was happening we used a simple oneliner like (as can be seen only 1 fails):
``` bash
for ip in $(kubectl --context c1 -n cilium get pods -owide | grep "envoy" | awk '{print $6}'); do echo "Node: ${ip}" && curl -IH "Host: hi.c1.were-testing.com" http://${ip}:32443; done
Node: {private_cidr}.213.207
HTTP/1.1 200 OK
content-type: text/html; charset=utf-8
content-length: 1683
server: envoy
date: Fri, 17 Nov 2023 08:06:25 GMT
x-envoy-upstream-service-time: 5

Node: {private_cidr}.213.216
HTTP/1.1 200 OK
content-type: text/html; charset=utf-8
content-length: 1683
server: envoy
date: Fri, 17 Nov 2023 08:06:25 GMT
x-envoy-upstream-service-time: 5

Node: {private_cidr}.213.219
HTTP/1.1 200 OK
content-type: text/html; charset=utf-8
content-length: 1683
server: envoy
date: Fri, 17 Nov 2023 08:06:25 GMT
x-envoy-upstream-service-time: 5

Node: {private_cidr}.213.209
HTTP/1.1 200 OK
content-type: text/html; charset=utf-8
content-length: 1683
server: envoy
date: Fri, 17 Nov 2023 08:06:25 GMT
x-envoy-upstream-service-time: 5

Node: {private_cidr}.213.180
HTTP/1.1 503 Service Unavailable
content-length: 91
content-type: text/plain
date: Fri, 17 Nov 2023 08:06:30 GMT
server: envoy
```

During the above run, it can be seen that the only 503 is from the node currently housing the pod:
``` bash
kubectl --context c1 -n bookinfo get pods -owide
NAME                              READY   STATUS    RESTARTS   AGE   IP               NODE                                              NOMINATED NODE   READINESS GATES
productpage-v1-7c8c6678b7-wwx82   1/1     Running   0          16m   {private_cidr}.210.136   ip-{private_cidr}-213-180.eu-central-1.compute.internal   <none>           <none>
```

All health between the nodes is fine:
```
==== detail from pod cilium-fjcgd , on node ip-{private_cidr}-213-216.eu-central-1.compute.internal
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.28+ (v1.28.3-eks-4f4795d) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideEnvoyConfig", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumEnvoyConfig", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Secrets", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    True   [eth0 {private_cidr}.213.216 (Direct Routing), eth1 {private_cidr}.211.11]
Host firewall:           Disabled
CNI Chaining:            none
Cilium:                  Ok   1.14.4 (v1.14.4-87dd2b64)
NodeMonitor:             Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok
IPAM:                    IPv4: 8/16 allocated,
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Host Routing:            Legacy
Masquerading:            BPF   [eth0, eth1]   {private_cidr}.208.0/21 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       43/43 healthy
Proxy Status:            OK, ip {private_cidr}.211.176, 0 redirects active on ports 10000-20000, Envoy: external
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 4095/4095 (100.00%), Flows/s: 9.75   Metrics: Ok
Encryption:              Disabled
Cluster health:          5/5 reachable   (2023-11-17T08:19:26Z)

==== detail from pod cilium-tvm46 , on node ip-{private_cidr}-213-209.eu-central-1.compute.internal
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.28+ (v1.28.3-eks-4f4795d) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideEnvoyConfig", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumEnvoyConfig", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Secrets", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    True   [eth0 {private_cidr}.213.209 (Direct Routing), eth1 {private_cidr}.211.137]
Host firewall:           Disabled
CNI Chaining:            none
Cilium:                  Ok   1.14.4 (v1.14.4-87dd2b64)
NodeMonitor:             Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok
IPAM:                    IPv4: 9/32 allocated,
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Host Routing:            Legacy
Masquerading:            BPF   [eth0, eth1]   {private_cidr}.208.0/21 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       51/51 healthy
Proxy Status:            OK, ip {private_cidr}.211.210, 0 redirects active on ports 10000-20000, Envoy: external
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 4095/4095 (100.00%), Flows/s: 16.74   Metrics: Ok
Encryption:              Disabled
Cluster health:          5/5 reachable   (2023-11-17T08:19:15Z)

==== detail from pod cilium-9s9lh , on node ip-{private_cidr}-213-207.eu-central-1.compute.internal
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.28+ (v1.28.3-eks-4f4795d) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideEnvoyConfig", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumEnvoyConfig", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Secrets", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    True   [eth0 {private_cidr}.213.207 (Direct Routing)]
Host firewall:           Disabled
CNI Chaining:            none
Cilium:                  Ok   1.14.4 (v1.14.4-87dd2b64)
NodeMonitor:             Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok
IPAM:                    IPv4: 11/32 allocated,
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Host Routing:            Legacy
Masquerading:            BPF   [eth0]   {private_cidr}.208.0/21 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       53/53 healthy
Proxy Status:            OK, ip {private_cidr}.211.77, 0 redirects active on ports 10000-20000, Envoy: external
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 4095/4095 (100.00%), Flows/s: 16.69   Metrics: Ok
Encryption:              Disabled
Cluster health:          5/5 reachable   (2023-11-17T08:18:50Z)

==== detail from pod cilium-rv5v6 , on node ip-{private_cidr}-213-219.eu-central-1.compute.internal
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.28+ (v1.28.3-eks-4f4795d) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideEnvoyConfig", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumEnvoyConfig", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Secrets", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    True   [eth0 {private_cidr}.213.219 (Direct Routing), eth1 {private_cidr}.211.107]
Host firewall:           Disabled
CNI Chaining:            none
Cilium:                  Ok   1.14.4 (v1.14.4-87dd2b64)
NodeMonitor:             Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok
IPAM:                    IPv4: 11/32 allocated,
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Host Routing:            Legacy
Masquerading:            BPF   [eth0, eth1]   {private_cidr}.208.0/21 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       62/62 healthy
Proxy Status:            OK, ip {private_cidr}.211.196, 0 redirects active on ports 10000-20000, Envoy: external
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 4095/4095 (100.00%), Flows/s: 34.37   Metrics: Ok
Encryption:              Disabled
Cluster health:          5/5 reachable   (2023-11-17T08:19:23Z)

==== detail from pod cilium-74hjq , on node ip-{private_cidr}-213-180.eu-central-1.compute.internal
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.28+ (v1.28.3-eks-4f4795d) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideEnvoyConfig", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumEnvoyConfig", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Secrets", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    True   [eth0 {private_cidr}.213.180 (Direct Routing), eth1 {private_cidr}.210.109]
Host firewall:           Disabled
CNI Chaining:            none
Cilium:                  Ok   1.14.4 (v1.14.4-87dd2b64)
NodeMonitor:             Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok
IPAM:                    IPv4: 9/32 allocated,
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Host Routing:            Legacy
Masquerading:            BPF   [eth0, eth1]   {private_cidr}.208.0/21 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       51/51 healthy
Proxy Status:            OK, ip {private_cidr}.210.88, 1 redirects active on ports 10000-20000, Envoy: external
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 4095/4095 (100.00%), Flows/s: 13.88   Metrics: Ok
Encryption:              Disabled
Cluster health:          5/5 reachable   (2023-11-17T08:17:37Z)
```

When observing traffic to hubble working vs non-working:
**working**: 
```
hubble observe -f --from-identity 8 --to-identity 56860
Nov 17 08:30:16.839: {private_cidr}.211.219:34341 -> bookinfo/productpage-v1-7c8c6678b7-wwx82:9080 to-proxy FORWARDED (TCP Flags: SYN)
Nov 17 08:30:16.839: {private_cidr}.208.26:53150 -> bookinfo/productpage-v1-7c8c6678b7-wwx82:9080 http-request FORWARDED (HTTP/1.1 GET http://hi.c1.were-testing.com/)
Nov 17 08:30:16.840: {private_cidr}.213.180:51360 -> bookinfo/productpage-v1-7c8c6678b7-wwx82:9080 to-endpoint FORWARDED (TCP Flags: SYN)
Nov 17 08:30:16.840: {private_cidr}.213.180:51360 -> bookinfo/productpage-v1-7c8c6678b7-wwx82:9080 to-endpoint FORWARDED (TCP Flags: ACK)
Nov 17 08:30:16.840: {private_cidr}.213.180:51360 -> bookinfo/productpage-v1-7c8c6678b7-wwx82:9080 to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Nov 17 08:30:16.845: {private_cidr}.213.180:51360 -> bookinfo/productpage-v1-7c8c6678b7-wwx82:9080 to-endpoint FORWARDED (TCP Flags: ACK, FIN)
```
**non-working**:  
```
hubble observe -f --from-identity 8 --to-identity 56860
Nov 17 09:37:21.382: {private_cidr}.210.94:37443 -> bookinfo/productpage-v1-7c8c6678b7-wwx82:9080 to-proxy FORWARDED (TCP Flags: SYN)
```

Endpoint list on node housing the bookinfo pod:
```
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                           IPv6   IPv4             STATUS
           ENFORCEMENT        ENFORCEMENT
271        Disabled           Disabled          1          k8s:eks.amazonaws.com/capacityType=ON_DEMAND                                                                  ready
                                                           k8s:eks.amazonaws.com/nodegroup-image=ami-016e05d25cd3b692d
                                                           k8s:eks.amazonaws.com/nodegroup=c1-worker-2023111706460799250000001e
                                                           k8s:eks.amazonaws.com/sourceLaunchTemplateId=lt-084185009d33ee286
                                                           k8s:eks.amazonaws.com/sourceLaunchTemplateVersion=1
                                                           k8s:node.kubernetes.io/instance-type=t3.small
                                                           k8s:topology.kubernetes.io/region=eu-central-1
                                                           k8s:topology.kubernetes.io/zone=eu-central-1b
                                                           reserved:host
554        Disabled           Disabled          56860      k8s:app=productpage                                                                          {private_cidr}.210.136   ready
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=bookinfo
                                                           k8s:io.cilium.k8s.policy.cluster=c1
                                                           k8s:io.cilium.k8s.policy.serviceaccount=bookinfo-productpage
                                                           k8s:io.kubernetes.pod.namespace=bookinfo
                                                           k8s:version=v1
950        Disabled           Disabled          33431      k8s:app.kubernetes.io/name=hubble-ui                                                         {private_cidr}.210.92    ready
                                                           k8s:app.kubernetes.io/part-of=cilium
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cilium
                                                           k8s:io.cilium.k8s.namespace.labels.name=cilium
                                                           k8s:io.cilium.k8s.policy.cluster=c1
                                                           k8s:io.cilium.k8s.policy.serviceaccount=hubble-ui
                                                           k8s:io.kubernetes.pod.namespace=cilium
                                                           k8s:k8s-app=hubble-ui
1255       Disabled           Disabled          44360      k8s:eks.amazonaws.com/component=coredns                                                      {private_cidr}.210.86    ready
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system
                                                           k8s:io.cilium.k8s.policy.cluster=c1
                                                           k8s:io.cilium.k8s.policy.serviceaccount=coredns
                                                           k8s:io.kubernetes.pod.namespace=kube-system
                                                           k8s:k8s-app=kube-dns
2182       Disabled           Disabled          4          reserved:health                                                                              {private_cidr}.210.132   ready
2789       Disabled           Disabled          55731      k8s:app.kubernetes.io/instance=karpenter                                                     {private_cidr}.210.84    ready
                                                           k8s:app.kubernetes.io/name=karpenter
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=karpenter
                                                           k8s:io.cilium.k8s.namespace.labels.name=karpenter
                                                           k8s:io.cilium.k8s.policy.cluster=c1
                                                           k8s:io.cilium.k8s.policy.serviceaccount=karpenter
                                                           k8s:io.kubernetes.pod.namespace=karpenter
3141       Disabled           Disabled          20152      k8s:app=trust-manager                                                                        {private_cidr}.210.81    ready
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cert-manager
                                                           k8s:io.cilium.k8s.namespace.labels.name=cert-manager
                                                           k8s:io.cilium.k8s.policy.cluster=c1
                                                           k8s:io.cilium.k8s.policy.serviceaccount=trust-manager
                                                           k8s:io.kubernetes.pod.namespace=cert-manager
3366       Disabled           Disabled          29570      k8s:app=gatekeeper                                                                           {private_cidr}.210.87    ready
                                                           k8s:chart=gatekeeper
                                                           k8s:control-plane=controller-manager
                                                           k8s:gatekeeper.sh/operation=webhook
                                                           k8s:gatekeeper.sh/system=yes
                                                           k8s:heritage=Helm
                                                           k8s:io.cilium.k8s.namespace.labels.admission.gatekeeper.sh/ignore=no-self-managing
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=gatekeeper-system
                                                           k8s:io.cilium.k8s.namespace.labels.name=gatekeeper-system
                                                           k8s:io.cilium.k8s.namespace.labels.pod-security.kubernetes.io/audit-version=latest
                                                           k8s:io.cilium.k8s.namespace.labels.pod-security.kubernetes.io/audit=restricted
                                                           k8s:io.cilium.k8s.namespace.labels.pod-security.kubernetes.io/enforce-version=v1.24
                                                           k8s:io.cilium.k8s.namespace.labels.pod-security.kubernetes.io/enforce=restricted
                                                           k8s:io.cilium.k8s.namespace.labels.pod-security.kubernetes.io/warn-version=latest
                                                           k8s:io.cilium.k8s.namespace.labels.pod-security.kubernetes.io/warn=restricted
                                                           k8s:io.cilium.k8s.policy.cluster=c1
                                                           k8s:io.cilium.k8s.policy.serviceaccount=gatekeeper-admin
                                                           k8s:io.kubernetes.pod.namespace=gatekeeper-system
                                                           k8s:release=gatekeeper
```

bpf endpoint list on the same node:  
```
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
IP ADDRESS         LOCAL ENDPOINT INFO
{private_cidr}.210.87:0    id=3366  sec_id=29570 flags=0x0000 ifindex=39  mac=2E:F6:68:BF:33:14 nodemac=06:32:87:85:AA:8B
{private_cidr}.210.88:0    (localhost)
{private_cidr}.210.84:0    id=2789  sec_id=55731 flags=0x0000 ifindex=25  mac=DE:3E:96:C6:16:4C nodemac=6A:B6:3D:0C:74:40
{private_cidr}.210.136:0   id=554   sec_id=56860 flags=0x0000 ifindex=45  mac=46:52:99:AA:F0:DA nodemac=56:AF:26:5D:3C:1E
{private_cidr}.210.92:0    id=950   sec_id=33431 flags=0x0000 ifindex=11  mac=2E:13:4E:B3:5D:BF nodemac=0A:76:9E:B0:97:EB
{private_cidr}.210.86:0    id=1255  sec_id=44360 flags=0x0000 ifindex=9   mac=6A:AB:B8:ED:8A:F7 nodemac=2E:2B:4C:5E:5F:14
{private_cidr}.210.132:0   id=2182  sec_id=4     flags=0x0000 ifindex=41  mac=16:F1:9E:FA:8D:30 nodemac=62:23:E6:1E:E0:11
{private_cidr}.213.180:0   (localhost)
{private_cidr}.210.81:0    id=3141  sec_id=20152 flags=0x0000 ifindex=37  mac=CE:E0:EA:DF:93:3E nodemac=02:72:26:27:17:3F
{private_cidr}.210.109:0   (localhost)
```

### Cilium Version

1.14.4

### Kernel Version

5.10.198-187.748.amzn2.x86_64

### Kubernetes Version

1.28

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
