### ISSUE TITLE
cilium get endpoint fails with "Failed to decode nested JSON"

### ISSUE THREAD

**Issue by dctrwatson** [cilium/cilium#29247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Running `cilium get endpoint <id>` results in:
```
Error: Failed to decode nested JSON: invalid character 'M' looking for beginning of object key string (
{MatchLabels:map[string]string{k8s.foo: bar,k8s.io.kubernetes.pod.namespace: default,},MatchExpressions:[]LabelSelectorRequirement{},}
)
```

If using `yaml` output, it's fine.

### Cilium Version

Client: 1.14.4 87dd2b64 2023-11-09T15:02:52-05:00 go version go1.20.11 linux/amd64
Daemon: 1.14.4 87dd2b64 2023-11-09T15:02:52-05:00 go version go1.20.11 linux/amd64

### Kernel Version

5.15.0-1049-aws #54~20.04.1-Ubuntu SMP Fri Oct 6 22:04:33 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.24.17-eks-4f4795d

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment]
Is this occurring on every single possible endpoint or it just happened on a single one? If the latter, could you provide the K8s pod YAML for that endpoint so that we can reproduce it?

**Comment by dctrwatson** [comment]
It's occurring on any endpoint that has a `NetworkPolicy` with the spec like:
```
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
         foo: bar
  ingress:
  - from:
    - podSelector:
        matchLabels:
          foo: bar
    - namespaceSelector: {}
      podSelector:
        matchExpressions:
        - key: instance
          operator: DoesNotExist
  podSelector:
    matchLabels:
  	  instance: abc123
```

**Comment by christarazi** [comment]
The networkpolicy spec would not trigger this behavior. Most likely the full labelset of the pod might if you are able to share that.

**Comment by dctrwatson** [comment]
> The networkpolicy spec would not trigger this behavior.

Somehow it does.... because without the policy, the endpoint is fine

I can reproduce by:
`kubectl run curl --rm -it --command sh --image=curlimages/curl -l app=curl`

I can `get endpoint` for the pod okay, but then once I apply:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: curl
  name: curl
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: curl
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: curl
  podSelector:
    matchLabels:
      app: curl
  policyTypes:
  - Ingress
  - Egress
```

```
# cilium endpoint get 237
Error: Failed to decode nested JSON: invalid character 'M' looking for beginning of object key string (
{MatchLabels:map[string]string{k8s.app: curl,k8s.io.kubernetes.pod.namespace: default,},MatchExpressions:[]LabelSelectorRequirement{},}
)
```

**Comment by christarazi** [comment]
Interesting. Thanks for the info. It must be triggering in a different way then I presumed.

**Comment by christarazi** [comment]
I'm able to reproduce on `main` as well.

**Comment by christarazi** [comment]
When I did my incomplete bisection, I noted that it went as far back as v1.12, so this has been broken for quite some time AFAICT.

**Comment by dctrwatson** [comment]
> When I did my incomplete bisection, I noted that it went as far back as v1.12, so this has been broken for quite some time AFAICT.

huh, I could've sworn I've used this command on and since v1.12 🤷 

Glad it's reproducible though

**Comment by carnerito** [comment]
I'm experiencing the same issue with 1.14.9. I have the following two policies:

```
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "allow-within-namespace"
  namespace: "monitoring"
spec:
  description: "Allows ingress/egress communication within the namespace"
  endpointSelector: {}
  ingress:
    - fromEndpoints:
      - {}
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "prometheus-access"
  namespace: monitoring
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: ingress-nginx
      toPorts:
        - ports:
            - port: '9090'
              protocol: TCP
          rules:
            http:
              - headerMatches:
                - name: "X-Real-Ip"
                  value: "192.168.10.10"
```

When just one policy of these two is applied it works as expected, Prometheus running in the 'monitoring' namespace is accessible only from within namespace or through Nginx ingress from the '192.168.10.10' address. But, when both policies are applied I'm getting the error described in this issue when I try to get the Prometheus endpoint ID, and none of the policies are active, everything is allowed. I'm using default policy enforcement mode.
