### ISSUE TITLE
Egress timeout when connect with HTTPS in dind (docker in docker)

### ISSUE THREAD

**Issue by gawsoftpl** [cilium/cilium#29266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. I prepare gitlab runner (helm gitlab/gitlab-runner)  in kubernetes with cilium.
2. I setup EgressGatewayPolicy to setup that all nodes in my cluster connect with one ip for outside traffic.
3. Everything works fine direct in gitlab-runner pod and other pods.
4. But there is a problem with dind (docker in docker). 
When I run dind as service in gitlab runner pod I cant connect with outside **https** endpoints. Http works fine. 
**Connection stuck on TLS handshake, Server hello step.**
Http, ping works fine

**When I run dind with network=host everything works fine, when I run with network with bridge https stuck.**

```yml
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egress-master-ip
spec:
  # Specify which pods should be subject to the current policy.
  # Multiple pod selectors can be specified.
  selectors:
  - podSelector:
      matchLabels:
        # The following label selects default namespace
        io.kubernetes.pod.namespace: gitlab-runners

  # Specify which destination CIDR(s) this policy applies to.
  # Multiple CIDRs can be specified.
  destinationCIDRs:
  - "0.0.0.0/0"

  # Configure the gateway node.
  egressGateway:
    # Specify which node should act as gateway for this policy.
    nodeSelector:
      matchLabels:
        kubernetes.io/hostname: gitlab-runners-cloud-master
```

Cilium config helm values file:
```yml

kubeProxyReplacement: "strict"
autoDirectNodeRoutes: false

global:
  encryption:
    enabled: true
    nodeEncryption: true

nodeinit:
  enabled: true
  removeCbrBridge: true

operator:
  replicas: 1

egressGateway:
  enabled: true
  
bpf:
  masquerade: true

l7Proxy: false

ipam:
  mode: "kubernetes"


```

Gitlab pipeline for docker
```yml
.docker-compose-test:
  image: docker:dind
  stage: integration_test
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_CERT_PATH: /certs/client
  before_script:
    - docker info
    - docker-compose version
  after_script:
    - docker-compose down || true
    
docker-compose-test-local:
  extends:
    - .docker-compose-test
  services:
    - name: docker:dind 
      command: ["--registry-mirror", "http://docker-registry-mirror:5000"]
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_BUILDKIT: 0
```

### Cilium Version

1.14.4

### Kernel Version

Linux 5.4.0-166-generic #183-Ubuntu SMP Mon Oct 2 11:28:33 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.28 k3s

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gawsoftpl** [comment]
I resolve this issue:
I add mtu=1450 for docker dind

```yaml
docker-compose-test-local:
  extends:
    - .docker-compose-test
  services:
    - name: docker:dind 
      command: ["--registry-mirror", "http://docker-registry-mirror:5000", "--mtu=1450"]
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_BUILDKIT: 0
```
