### ISSUE TITLE
CFP: Support kube-apiserver load balancing (like kube-vip)

### ISSUE THREAD

**Issue by klausenbusk** [cilium/cilium#29323]
## Cilium Feature Proposal
        
I have asked on [Slack](https://cilium.slack.com/archives/C1MATJ5U5/p1699950372386889) but I did not get much response.

**Is your proposed feature related to a problem?**

This is basically the same as https://github.com/metallb/metallb/issues/168, but I could not find a similar issue for Cilium. I'm allowing myself to quote said issue.

> MetalLB (Cilium in this case) cannot reliably provide a load-balancer for the Kubernetes apiserver, because of circular dependencies.
>
> In a working HA cluster, the setup is: you have N machines with apiserver, and a load-balancer providing a single IP for all of them. Then, you configure all your kubelets to talk to the LB IP, and voila! Miracle.
>
> But how do you configure the LB? The Kubernetes documentation basically says "use a magic load-balancer in the sky, outside your cluster, and it will be fine." That doesn't work for bare metal clusters, we don't have magic load-balancers in the sky.

You can use kube-vip + Cilium, but it gets complicated, especially if you want to use BGP for both, due to BGP's [Connection Collision Detection](https://www.rfc-editor.org/rfc/rfc4271#section-6.8), a separate subnet must be allocated for kube-vip and Cilium respectively.

**Describe the feature you'd like**

I want Cilium to be able to load balance the kube-apiserver endpoint, so I don't need kube-vip. This is easier said than done tho:

> What about just configuring a LoadBalancer Service in k8s? MetalLB (Cilium) would create and advertise the LB IP, and everything works, right? No, because now you have a circular dependency:
> 1. Kubelet cannot talk to the control plane until MetalLB has started and configured the LB IP
> 2. ... But MetalLB (Cilium) cannot start until kubelet can talk to the control plane and discover that it should be running the pod!
>
> So, MetalLB (Cilium) cannot be used to control the LB IP for the apiserver.

**(Optional) Describe your proposed solution**

https://github.com/metallb/metallb/issues/168 has a few suggestions on how this can be done.

**Comment by klausenbusk** [comment]
@lmb unfortunately, I don't think I can get time for this, so it is more of a feature request. It may also be a bigger task and I'm not sure there is a simple solution or how much work it is implementing a simple solution.

**Comment by brb** [comment]
Related - https://github.com/cilium/cilium/pull/28741.

**Comment by 0xAlcibiades** [comment]
This is definitely a pain point for running in proxy-less mode/with native routing on bare metal. I'd be interested to hear more about how folks are doing this with kubevip.

**Comment by tsuzu** [comment]
How do you think about adding another field in `CiliumBGPVirtualRouter` to advertise statically configured routes?

**Comment by Jeansen** [comment]
Maybe I am missing something, but i just moved vom Calico with MetalLB and Kube-VIP to Cilium. That was vor historical reasons. I started out with MetalLB, then added more ControlPlane Nodes with the help of Kube-VIP during initial Setup. Now I removed MetalLB and Calico in favor of Cilium, but I kept the static setup with Kube-VIP. Works without problems, so far .... Anyway, having something like this in Cilium as well, would be great.

**Comment by KarmaPoliceT2** [comment]
+1 for this feature

**Comment by JamesLavin** [comment]
First, THANK YOU for Cilium! It's brilliant and fast. I came over from Calico & Flannel a couple years ago and never looked back.

I've long had two HAProxy load balancers pointing to my three control plane node API server endpoints. I have keepalived configured to always point the VIP assigned to my Kubernetes API server at one of of my two load balancers. I've long believed this meant I had redundancy, but I discovered today that when the VIP fails over and gets advertised by my other load balancer, which has an identical HAProxy config, `kubectl get node` and `cilium status` both hang. Would LOVE to see this feature. (I'm running on bare metal, not in a cloud.)

**Comment by klausenbusk** [comment]
> Right now, we only have three ways to overcome this issue, right?

In the past I used a solution similar to the [approach used by kubespray](https://github.com/kubernetes-sigs/kubespray/blob/9ec9b3a202ab15f7577cfd755df9b11881edde83/docs/operations/ha-mode.md#kube-apiserver) (nginx on each non-master node as a static pod for load balancing listening on localhost). I did run it on each node (including master nodes) in my case if I recall correctly.

That does not solve the issue for external clients, but you could maybe create a regular `LoadBalancer` service for that case.

**Comment by LMSSonos** [comment]
I am going to try this here https://documentation.suse.com/suse-edge/3.0/html/edge/guides-metallb-kubernetes.html - should solve the issue or am I wrong?

**Comment by ashtonian** [comment]
I think we are closer with https://github.com/cilium/cilium/pull/37601

**Comment by ashtonian** [comment]
To support cluster bootstrapping it would be nice to support other ports as well or allow passthrough to the underlying host of an announced ip, for example rke2 uses port 9345 for node registration. 

A potentially hacky way to do this would be to get cilium to create endpoint slices that could then be referenced by a kubernetes service. I'm willing to work towards this if its desired. I'm currently trying to orient around the repo to see how viable this is and where it would go. This worked with a manual endpoint slice and corresponding service to bootstrap a rke2 cluster without using kube vip leveraging ciliums bgp feature. 

Create a CRD 
```yaml
apiVersion: cilium.io
kind: CiliumHostEndpoints # Does not exist,
metadata:
  name: multi-port-daemon
spec:
  namespace: default      # Where the generated EndpointSlice will live
  nodeSelector:           # Node selector to target where to expose these endpoints
    matchLabels:
      my-daemon: "true"
  ports:
    - name: http
      hostPort: 8080
      protocol: TCP
      healthCheck:         # Optional health check similar to a pod health check
        type: HTTP
        path: /health
        intervalSeconds: 10
        timeoutSeconds: 2
    - name: metrics
      hostPort: 9000
      protocol: TCP
```

Which cilium would take and make something like the following which could be referenced by a service.
```yaml
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: multi-port-daemon
  namespace: default
  labels:
    kubernetes.io/service-name: multi-port-daemon
    cilium.io/host-endpoints: "true"
addressType: IPv4
ports:
  - name: http
    port: 8080
    protocol: TCP
  - name: metrics
    port: 9000
    protocol: TCP
endpoints:
  - addresses:
      - "10.1.1.5"       # node IP
    conditions:
      ready: true
    nodeName: "node-1"
  - addresses:
      - "10.1.2.7"      # node IP
    conditions:
      ready: true
    nodeName: "node-2"
```

From there the consumer could leverage typical service features like bgp/l2 announcements. 


I've tested this with a statically defined Endpoint slice and it works. 
```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "poolio"
spec:
  blocks:
  - cidr: "10.46.0.0/24"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
  namespace: kube-system
spec:
  bgpInstances:
  - name: "instance-65001"
    localASN: 65001
    # localPort: 179   # (Optional) If you want to *listen* for inbound sessions.
    peers:
    - name: "peer-10-42-0-1"
      peerASN: 65000
      peerAddress: "10.42.0.1"
      peerConfigRef:
        name: cilium-peer
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: service-lb-ips
  namespace: kube-system
  labels:
    advertise: "bgp"
spec:
  advertisements:
  - advertisementType: "Service"
    service:
      addresses:
        - ExternalIP
        - LoadBalancerIP
    selector:
      matchExpressions:
      - { key: somekey, operator: NotIn, values: ["never-used-value"] }
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
  namespace: kube-system
spec:
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  ebgpMultihop: 4
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: node-daemon
  namespace: default
  labels:
    kubernetes.io/service-name: node-daemon
addressType: IPv4
ports:
  - name: api
    port: 6443
    protocol: TCP
  - name: registration
    port: 9345
    protocol: TCP
endpoints:
  - addresses:
      - "10.42.0.50"
    conditions:
      ready: true
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    io.cilium/lb-ipam-ips: 10.46.0.60
  name: node-daemon
  namespace: default
spec:
  ports:
  - name: api
    port: 6443
    targetPort: 6443
    protocol: TCP
  - name: registration
    port: 9345
    targetPort: 9345
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 10.46.0.60
---
```

**Comment by borkmann** [comment]
(wip draft on kube-apiserver lb https://github.com/cilium/cilium/pull/38872)

**Comment by ttc0419** [comment]
With https://github.com/cilium/cilium/pull/37601 landed, I think it's the time to review this feature. A working solution I can think of:

1. Install kubelet with only one of the api server endpoint
2. Configure the kubernetes service LB
3. Reconfigure kubelet with the kubernetes service VIP

Since the https://github.com/cilium/cilium/pull/37601 allow cilium itself not using the VIP directly, the circular dependency should be now gone. Maybe it's the time to allow the VIP to load balance the kubernetes service?

**Comment by brb** [comment]
> Reconfigure kubelet with the kubernetes service VIP

Mind elaborating about this step? Is it possible to automate this?

**Comment by ttc0419** [comment]
> > Reconfigure kubelet with the kubernetes service VIP
> 
> Mind elaborating about this step? Is it possible to automate this?

Just replace the kubelet's api server's address to the kubernetes service cluster ip after the cilium pod is ready on the node, you can use ansible to automate this.

**Comment by Elegant996** [comment]
@brb Wouldn't this work with #37601? Something like:

```
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api-external
  namespace: default
spec:
  type: LoadBalancer
  selector:
	component: kube-apiserver
  ports:
	- protocol: TCP
	  port: 443
	  targetPort: 6443
```

One could then follow the cilium documentation to advertise this over BGP. The only real step would be the need to specify one of the control-planes manually when applying the service and BGP configs, but this is needed to deploy any CNI or initial configs if you don't have an external LB.

Any reboot of the cluster would use the control planes listed in `k8s.apiServerURLs` to re-establish the cluster and go immediately back to advertising over BGP.

We use haproxy here but if it's this simple, it could be worth switching to BGP on API to free up resources.

**Comment by brb** [comment]
It should work. Please give it a try.

**Comment by djds** [comment]
This is totally possible with layer 2 as well even on k3s without any actual kube-apiserver pods:

```yaml
# values.yaml
k8s:
  requireIPv4PodCIDR: true
  apiServerURLs: >
    https://192.168.0.10:6443
    https://192.168.0.11:6443
    https://192.168.0.12:6443
kubeProxyReplacement: true
```

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-api-external
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: kubernetes-api-external
spec:
  blocks:
    - cidr: "192.168.1.10/32"
  serviceSelector:
    matchLabels:
      "io.kubernetes.service.name": kubernetes-api-external
      "io.kubernetes.service.namespace": kubernetes-api-external
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api-external
  namespace: kubernetes-api-external
spec:
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: kubernetes-api-external
  namespace: kubernetes-api-external
  labels:
    kubernetes.io/service-name: kubernetes-api-external
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.0.10
      - 192.168.0.11
      - 192.168.0.12
ports:
  - name: https
    port: 6443
    protocol: TCP
```
