### ISSUE TITLE
Migrating to a new Gateway Fails to Properly Update HTTPRoute

### ISSUE THREAD

**Issue by maxtacu** [cilium/cilium#29407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We are experiencing an issue in our EKS cluster when migrating from an old gateway to a new one in our HTTPRoute configuration. Upon updating the gateway name in the `parentRefs` section of our HTTPRoute, the expected behaviour is for external-dns to recognise this change and update the DNS configuration in AWS Route53 accordingly. However, this update is not being recognised, leading to traffic still being routed through the old gateway. 
### Detailed Description:
Our setup involves two existing gateways, referred to as "external" and "internal". We attempted to migrate the HTTPRoute from the "external" gateway to the "internal" gateway by updating the spec.parentRefs.name field in our HTTPRoute configuration.  
Initially, the HTTPRoute `spec` was configured as follows:
```
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external
```
We updated it to:
```
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: internal
```
After this change, we observed that the `.status` of the HTTPRoute reflected both the old and new gateways, instead of only the new gateway. This status did not trigger external-dns to update the DNS records in Route53, resulting in traffic continuing to flow through the old "external" gateway.
The `status` block after the update was as follows:
```
Status:
  Parents:
    Conditions:
      Message:               Accepted HTTPRoute
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Message:               Service reference is valid
      Observed Generation:   1
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Controller Name:         io.cilium/gateway-controller
    Parent Ref:
      Group:      gateway.networking.k8s.io
      Kind:       Gateway
      Name:       external
      Namespace:  gateway-api
    Conditions:
      Message:               Accepted HTTPRoute
      Observed Generation:   2
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Message:               Service reference is valid
      Observed Generation:   2
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Controller Name:         io.cilium/gateway-controller
    Parent Ref:
      Group:      gateway.networking.k8s.io
      Kind:       Gateway
      Name:       internal
      Namespace:  gateway-api
```
As a workaround, we found that deleting and recreating the HTTPRoute with the new gateway configuration prompts external-dns to correctly update the DNS record in Route53, thus directing traffic to the "internal" gateway. 

### Expected Behavior:
Updating the gateway reference in the HTTPRoute configuration should result in the .status being updated to reflect only the new gateway, and this change should trigger external-dns to update the DNS configuration in AWS Route53.

### Actual Behavior:
The update to the gateway reference results in the .status reflecting both old and new gateways, and does not trigger external-dns to update Route53, causing traffic to continue routing through the old gateway.

### Steps to Reproduce:
- Create two gateways in an EKS cluster.
- Configure an HTTPRoute with one gateway.
- Update the HTTPRoute to reference the second gateway.
- Observe the `.status` of the HTTPRoute and the corresponding behaviour of external-dns with AWS Route53.

### Kernel Version

Bottlerocket OS 1.15.0
Kernel 5.15.128

### Kubernetes Version

v1.27.7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Hmm, that behavior is actually within how the Gateway API spec says controllers are supposed to handle HTTPRoutes that fall out of scope - they may choose to remove the status, because it's out of scope, but they don't have to. You can see from the Observed Generation field being different on the old status that it's stale (the `metadata.generation` field is automatically set by Kubernetes whenever the `.spec` is updated).

It's weird that external-dns doesn't handle this case though - it should be checking both statuses, and taking action accordingly.

**Comment by sergeyshevch** [comment]
@youngnick Also the previous gateway has this route too. So we found it in CiliumEnvoyConfig for both gateways

**Comment by youngnick** [comment]
So the change to the `parentRef` meant that the config showed up in the CEC for the _new_ Gateway, as was _not_ removed from the old CEC? If that's the case, then yes, there would be a problem.

Could you share a sysdump or at least the full spec of both Gateways and the HTTPRoute? Strip identifying info if needed, but it will be difficult to check this out without a way to reproduce.

**Comment by sergeyshevch** [comment]
Yes. It was in both old and new CEC. @maxtacu Can you share info here?

**Comment by maxtacu** [comment]
@youngnick here are manifests. 

httproute:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: rest-api
spec:
  hostnames:
  - someapi.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: external
    namespace: gateway-api
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: rest-api
      port: 8080
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /rest-api
```
old gateway:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: internal
  namespace: gateway-api
spec:
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchExpressions:
          - key: simple.life/team
            operator: In
            values:
            - backend
    name: web-gw
    port: 443
    protocol: HTTP
```
new gateway:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: external
  namespace: gateway-api
spec:
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: https
    port: 443
    protocol: HTTP
```
