### ISSUE TITLE
Cilium removes agent-not-ready taint too early

### ISSUE THREAD

**Issue by rissson** [cilium/cilium#29405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have cilium configured to chain to AWS VPC CNI in an IPv6-only EKS cluster (additional version and configuration information at the bottom).

When creating a new node, pods scheduled on it are not able to reach cluster services that have endpoints on other nodes. What happens is:

- a new node is created with the `node.cilium.io/agent-not-ready` taint set to `NoExecute`
- AWS VPC CNI and cilium pods are scheduled on that node
- AWS VPC CNI takes a pretty long time to start
- the cilium pod is marked as ready, even though the AWS VPC CNI pod is not ready yet and cilium is still outputting logs like `level=info msg="Failed to write CNI config file (will retry): failed to render CNI configuration file: could not find existing CNI config for chaining no matching CNI configurations found (will retry)" subsys=cni-config`
- the taint on the node is removed and pods get scheduled to it
- pods cannot reach services and thus some end up CrashLoopBackoff-ing
- cilium finally writes the CNI config
- pods scheduled on that node are then able to start
- pods that were previously scheduled need to be deleted, they don't get access to other services after a restart

What we suspect is that the taint is being removed too early by the cilium-operator.

This issue started appearing after an AWS VPC CNI upgrade (`v1.14.1-eksbuild.1` to `v1.15.3-eksbuild.1`) that made it significantly slower to start.

Upgrading from cilium `1.12.3` to `1.14.4` did not resolve the issue.

AWS VPC CNI version: `v1.15.3-eksbuild.1`, with no particular configuration

Cilium Helm values:

```yaml
ipv4:
  enabled: false
ipv6:
  enabled: true
cni:
  chainingMode: aws-cni
  exclusive: false
enableIPv4Masquerade: false
enableIPv6Masquerade: false
routingMode: native
tunnel: disabled
endpointRoutes:
  enabled: true

kubeProxyReplacement: strict
k8sServiceHost: <API server URL>
k8sServicePort: 443
socketLB:
  hostNamespaceOnly: true

annotateK8sNode: true

bpf:
  clockProbe: true
  preallocateMaps: true

bandwidthManager:
  enabled: true

containerRuntime:
  integration: auto

# Hubble and prometheus values removed for brevity
```

Logs pasted below are the agent logs.

### Cilium Version

Client: 1.14.4 87dd2b64 2023-11-09T15:02:52-05:00 go version go1.20.11 linux/arm64
Daemon: 1.14.4 87dd2b64 2023-11-09T15:02:52-05:00 go version go1.20.11 linux/arm64

### Kernel Version

Linux 5.10.198-187.748.amzn2.aarch64 #1 SMP Tue Oct 24 19:49:48 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.2-eks-c12679a", GitCommit:"002c6bc4e142b1f48b9405140e559194a094dcff", GitTreeState:"clean", BuildDate:"2023-05-22T20:23:13Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
