### ISSUE TITLE
Packets to hostNetwork pods like envoy always contain RST flag

### ISSUE THREAD

**Issue by TECHNOFAB11** [cilium/cilium#29406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I tried using the Gateway API but Envoy always returns 
```
upstream connect error or disconnect/reset before headers. reset reason: connection timeout
```

After sniffing on the "cilium_host" network I found a lot of packets from the backend service to envoy (10.42.0.246) which never arrive and get retransmitted a bunch. I then tried to ping and curl the IP from a busybox pod once with `hostNetwork: true` and once with it disabled but these packets also show up in wireshark with "no response found". The envoy pod/whatever might not respond to ICMP but it should definetely accept/receive the TCP responses from backend services.
Completely disabled all IPtables rules to rule that out, the packets did still not arrive successfully.

### Cilium Version

cilium-cli: 0.15.11 compiled with go1.21.3 on linux/amd64
cilium image (default): v1.14.2
cilium image (stable): v1.14.4
cilium image (running): unknown. Unable to obtain cilium version, no cilium pods found in namespace "kube-system"

Image versions         
- cilium-operator    quay.io/cilium/operator-generic:v1.15.0-pre.2@sha256:e5506ddf0665307cf4012a9fbe3f1a51c722b63a12e7abd357119b7c2d1f68af: 1
- cilium-envoy       quay.io/cilium/cilium-envoy:v1.27.2-ab187719b71b513150f30209569695adf16ec869@sha256:2b590be37624547d638a578a3f31278d3be53a1a2649ba888a9f15771628521e: 1
- hubble-relay       quay.io/cilium/hubble-relay:v1.15.0-pre.2@sha256:74b20caf534472e274eb020e8ceaf4abfe8d6540c282cb648eb4e0420bccf782: 1
- cilium             quay.io/cilium/cilium:v1.15.0-pre.2@sha256:7f077c49ce091428b04de006d5f4cb01b8e32d63dc1d45fa3e372d624681e836: 1
- hubble-ui          quay.io/cilium/hubble-ui:v0.12.1@sha256:9e5f81ee747866480ea1ac4630eb6975ff9227f9782b7c93919c081c33f38267: 1
- hubble-ui          quay.io/cilium/hubble-ui-backend:v0.12.1@sha256:1f86f3400827a0451e6332262467f894eeb7caf0eb8779bd951e2caa9d027cbe: 1

### Kernel Version

Linux _ 6.5.10 #1-NixOS SMP PREEMPT_DYNAMIC Thu Nov  2 08:37:00 UTC 2023 x86_64 GNU/Linux

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "1970-01-01T01:01:01Z"
  compiler: gc
  gitCommit: bd04941a294793ec92e8703d5e5da14107902e88
  gitTreeState: clean
  gitVersion: v1.27.6+k3s1
  goVersion: go1.20.10
  major: "1"
  minor: "27"
  platform: linux/amd64
  kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "1970-01-01T01:01:01Z"
  compiler: gc
  gitCommit: bd04941a294793ec92e8703d5e5da14107902e88
  gitTreeState: clean
  gitVersion: v1.27.6+k3s1
  goVersion: go1.20.10
  major: "1"
  minor: "27"
  platform: linux/amd64
```

### Sysdump

[cilium-sysdump-20231127-154254.zip](https://github.com/cilium/cilium/files/13476596/cilium-sysdump-20231127-154254.zip)

### Relevant log output

```shell
Wireshark after trying to access HTTPRoute, :8080 is the backend service, 10.42.0.246:33979 is envoy:

[TCP Retransmission] 8080 → 33979 [SYN, ACK] Seq=0 Ack=1 Win=64308 Len=0 MSS=1410 SACK_PERM TSval=3338499822 TSecr=1724972011 WS=128
a bunch more retransmissions...
```

### Anything else?

Helm Chart values:
```nix
      kubeProxyReplacement = true;
      k8sServiceHost = "_";
      k8sServicePort = 6443;
      l2announcements.enabled = true;
      ipam.operator.clusterPoolIPv4PodCIDRList = "10.42.0.0/16";
      nodePort.enabled = true;
      gatewayAPI.enabled = true;
      operator.replicas = 1;
      loadBalancer.l7.backend = "envoy";
      prometheus.enabled = true;
      envoy.enabled = true;
      hubble = {
        relay.enabled = true;
        ui.enabled = true;
        tls.auto.method = "cronJob";
      };
      clustermesh.apiserver.tls.auto.method = "cronJob";
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
