### ISSUE TITLE
LB IPAM allocates IPs improperly from a subnet

### ISSUE THREAD

**Issue by stelucz** [cilium/cilium#29410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

LB IPAM can allocate IP outside of a subnet and `allowFirstLastIPs ` does not work properly.

Define orange and blue pools:
```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "orange-pool"
spec:
  blocks:
  - cidr: "10.0.12.0/29"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "blue-pool"
spec:
  blocks:
  - cidr: "10.0.11.0/29"
  allowFirstLastIPs: "Yes"
``` 

Create svcs: `for ((i=1;i<=10;i++)); do kubectl expose deploy rebel-base --type LoadBalancer --port 80 --name rb-svc-$i; done`

orage pool allocates `10.0.12.1 - 10.0.12.7`, however it should stop at `10.0.12.6` as `10.0.12.7` is broadcast and `allowFirstLastIPs` is not set to `Yes`:
```
k get svc | grep rb
rb-svc-1     LoadBalancer   192.168.127.172   10.0.12.1        80:31625/TCP   24s
rb-svc-10    LoadBalancer   192.168.58.216    <pending>        80:32741/TCP   22s
rb-svc-2     LoadBalancer   192.168.125.195   10.0.12.2        80:32020/TCP   24s
rb-svc-3     LoadBalancer   192.168.3.189     10.0.12.3        80:32395/TCP   23s
rb-svc-4     LoadBalancer   192.168.211.185   10.0.12.4        80:31607/TCP   23s
rb-svc-5     LoadBalancer   192.168.105.98    10.0.12.5        80:31267/TCP   23s
rb-svc-6     LoadBalancer   192.168.191.239   10.0.12.6        80:30834/TCP   23s
rb-svc-7     LoadBalancer   192.168.121.110   10.0.12.7        80:32025/TCP   23s
rb-svc-8     LoadBalancer   192.168.166.110   <pending>        80:32615/TCP   23s
rb-svc-9     LoadBalancer   192.168.131.36    <pending>        80:30320/TCP   22s
```

blue pool allocates `10.0.11.0 - 10.0.11.8`, but `10.0.11.8` is outside of `10.0.11.0/29` subnet:
```
k get svc | grep rb
rb-svc-1     LoadBalancer   192.168.78.240    10.0.11.0        80:31289/TCP   4m55s
rb-svc-10    LoadBalancer   192.168.137.224   <pending>        80:32256/TCP   4m53s
rb-svc-2     LoadBalancer   192.168.22.154    10.0.11.1        80:31355/TCP   4m55s
rb-svc-3     LoadBalancer   192.168.224.186   10.0.11.2        80:31182/TCP   4m54s
rb-svc-4     LoadBalancer   192.168.59.215    10.0.11.3        80:31251/TCP   4m54s
rb-svc-5     LoadBalancer   192.168.198.39    10.0.11.4        80:30343/TCP   4m54s
rb-svc-6     LoadBalancer   192.168.14.169    10.0.11.5        80:31548/TCP   4m54s
rb-svc-7     LoadBalancer   192.168.98.202    10.0.11.6        80:32534/TCP   4m54s
rb-svc-8     LoadBalancer   192.168.93.220    10.0.11.7        80:31281/TCP   4m53s
rb-svc-9     LoadBalancer   192.168.19.181    10.0.11.8        80:30436/TCP   4m53s
```

Just a small idea, `allowFirstLastIPs: "Yes"` i would expect to be set to `true` or `false` as most other options.

### Cilium Version

1.15.0-pre.2

### Kernel Version

6.2.0-37-generic

### Kubernetes Version

v1.27.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
