### ISSUE TITLE
External traffic routing to L2 aware LB broke in 1.14.4

### ISSUE THREAD

**Issue by roosmaa** [cilium/cilium#29491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrading from 1.14.3 to 1.14.4 the requests from outside of the cluster to a Cilium L2 based LB IP stopped getting through (started getting dropped).

### Cilium Version

1.14.4

### Kernel Version

Linux version 6.1.51-talos (@buildkitsandbox) (gcc (GCC) 12.3.0, GNU ld (GNU Binutils) 2.40) #1 SMP PREEMPT_DYNAMIC

Talos v1.5.2

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.1", GitCommit:"8dc49c4b984b897d423aab4971090e1879eb4f23", GitTreeState:"clean", BuildDate:"2023-08-24T11:16:30Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20231129-184850.zip](https://github.com/cilium/cilium/files/13503969/cilium-sysdump-20231129-184850.zip)

### Anything else?

My homelab router is setup in 10.22.0.0/19 subnet, which I divide to smaller subnets between the physical hosts and services. The IPs (from 10.22.22.0/24 pool) assigned to the services are 10.22.22.1 and 10.22.22.2. All the machines are connected via the router in bridge mode. I can see the expected ARP table in the router with the service IPs being listed with pyhsical node MACs (ie the ARP broadcast seems to work). The packets are sent to the physical machine, but from there on they seem to get dropped.

The traffic flow:

```
Computer -> Main router -> Homelab router (10.22.0.1) -> Kubernetes node  -/-> Pod

#  ->  = success
# -/-> = failure
```

Rolling back to v1.14.3 restores previous behaviour where everything just works.

Cilium helm-chart inputs:

```yaml
  cni:
    # Store generated CNI configuration in non-standard path to work-around multus-cni issues
    confPath: /etc/cni/net.d/cilium.d
    exclusive: false
  rollOutCiliumPods: true
  operator:
    rollOutPods: true
    replicas: 1
  tunnel: disabled
  ipv4NativeRoutingCIDR: "10.26.0.0/16"
  autoDirectNodeRoutes: true
  
  l2announcements:
    enabled: true

  # Due to L2 announcements these limits need tweaking, see also:
  # https://docs.cilium.io/en/stable/network/l2-announcements/#sizing-client-rate-limit
  k8sClientRateLimit:
    qps: 8 # for ~15 services
    burst: 15

  # Talos configuration overrides
  ipam:
    mode: kubernetes
  kubeProxyReplacement: true
  securityContext:
    capabilities:
      ciliumAgent: ["CHOWN","KILL","NET_ADMIN","NET_RAW","IPC_LOCK","SYS_ADMIN","SYS_RESOURCE","DAC_OVERRIDE","FOWNER","SETGID","SETUID"]
      cleanCiliumState: ["NET_ADMIN","SYS_ADMIN","SYS_RESOURCE"]
  cgroup:
    autoMount:
      enabled: false
    hostRoot: /sys/fs/cgroup
  # use kube-prism
  k8sServiceHost: localhost
  k8sServicePort: 7445
```

Talos networking related config:

```yaml
cluster:
  allowSchedulingOnControlPlanes: true
  
  network:
    # Disable bundled CNI to use Cilium 
    cni:
      name: none
    # Assign new subnets
    podSubnets:
      - 10.26.0.0/16
    serviceSubnets:
      - 10.43.0.0/16
  # Disable kube-proxy as Cilium alternative is used 
  proxy:
    disabled: true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
