### ISSUE TITLE
FIB lookup failed (BPF_FIB_LKUP_RET_FRAG_NEEDED actually) when making a TCP connecting from a Nebula peer due to small MTU size.

### ISSUE THREAD

**Issue by fangpenlin** [cilium/cilium#29583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have a Kubernetes running with Cilium as the network backbone. I also have [Nebula](https://github.com/slackhq/nebula) network running in the Kubernetes nodes and devices in the same network. I tried to make a simple curl to one of the pod running in the cluster like this:

```bash
curl http://10.20.0.11:3000/login -v
```

Instead of returning the page, the curl command returns part of the page and hangs there forever. I open Wireshark to see what's going on with the TCP packages, and it seems like some TCP packages go through, but probably due to some missing packages, the TCP stream stuck at some point:

![image](https://github.com/cilium/cilium/assets/201615/39eba268-e369-4211-955c-2ecdba50bf7b)

When I run the `cilium monitor -t drop` command, I can then see somehow TCP packages were dropped due to "FIB lookup failed".

```
xx drop (FIB lookup failed, 8) flow 0x37fc47cb to endpoint 0, ifindex 386, file bpf_lxc.c:1272, , identity 108153->world: 10.20.0.11:3000 -> 100.64.50.1:53096 tcp ACK
xx drop (FIB lookup failed, 8) flow 0x37fc47cb to endpoint 0, ifindex 386, file bpf_lxc.c:1272, , identity 108153->world: 10.20.0.11:3000 -> 100.64.50.1:53096 tcp ACK
xx drop (FIB lookup failed, 8) flow 0x37fc47cb to endpoint 0, ifindex 386, file bpf_lxc.c:1272, , identity 108153->world: 10.20.0.11:3000 -> 100.64.50.1:53096 tcp ACK
xx drop (FIB lookup failed, 8) flow 0x37fc47cb to endpoint 0, ifindex 386, file bpf_lxc.c:1272, , identity 108153->world: 10.20.0.11:3000 -> 100.64.50.1:53096 tcp ACK
xx drop (FIB lookup failed, 8) flow 0x37fc47cb to endpoint 0, ifindex 386, file bpf_lxc.c:1272, , identity 108153->world: 10.20.0.11:3000 -> 100.64.50.1:53096 tcp ACK
xx drop (FIB lookup failed, 8) flow 0x37fc47cb to endpoint 0, ifindex 386, file bpf_lxc.c:1272, , identity 108153->world: 10.20.0.11:3000 -> 100.64.50.1:53096 tcp ACK
xx drop (FIB lookup failed, 8) flow 0x37fc47cb to endpoint 0, ifindex 386, file bpf_lxc.c:1272, , identity 108153->world: 10.20.0.11:3000 -> 100.64.50.1:53096 tcp ACK
xx drop (FIB lookup failed, 8) flow 0x37fc47cb to endpoint 0, ifindex 386, file bpf_lxc.c:1272, , identity 108153->world: 10.20.0.11:3000 -> 100.64.50.1:53096 tcp ACK
xx drop (FIB lookup failed, 8) flow 0x37fc47cb to endpoint 0, ifindex 386, file bpf_lxc.c:1272, , identity 108153->world: 10.20.0.11:3000 -> 100.64.50.1:53096 tcp ACK
xx drop (FIB lookup failed, 8) flow 0x37fc47cb to endpoint 0, ifindex 386, file bpf_lxc.c:1272, , identity 108153->world: 10.20.0.11:3000 -> 100.64.50.1:53096 tcp ACK
xx drop (FIB lookup failed, 8) flow 0xbc71f449 to endpoint 0, ifindex 386, file bpf_lxc.c:1272, , identity 108153->world: 10.20.0.11:3000 -> 100.64.50.1:53096 tcp ACK
xx drop (FIB lookup failed, 8) flow 0xf5ef1a09 to endpoint 0, ifindex 386, file bpf_lxc.c:1272, , identity 108153->world: 10.20.0.11:3000 -> 100.64.50.1:53096 tcp ACK
xx drop (FIB lookup failed, 8) flow 0x1f68fbd5 to endpoint 0, ifindex 386, file bpf_lxc.c:1272, , identity 108153->world: 10.20.0.11:3000 -> 100.64.50.1:53096 tcp ACK
xx drop (FIB lookup failed, 8) flow 0x42fa4c03 to endpoint 0, ifindex 386, file bpf_lxc.c:1272, , identity 108153->world: 10.20.0.11:3000 -> 100.64.50.1:53096 tcp ACK
xx drop (FIB lookup failed, 8) flow 0x1a7dbf2a to endpoint 0, ifindex 386, file bpf_lxc.c:1272, , identity 108153->world: 10.20.0.11:3000 -> 100.64.50.1:53096 tcp ACK
xx drop (FIB lookup failed, 8) flow 0x24d65040 to endpoint 0, ifindex 386, file bpf_lxc.c:1272, , identity 108153->world: 10.20.0.11:3000 -> 100.64.50.1:53096 tcp ACK
xx drop (FIB lookup failed, 8) flow 0x34578b39 to endpoint 0, ifindex 386, file bpf_lxc.c:1272, , identity 108153->world: 10.20.0.11:3000 -> 100.64.50.1:53096 tcp ACK
xx drop (FIB lookup failed, 8) flow 0xb37b679c to endpoint 0, ifindex 386, file bpf_lxc.c:1272, , identity 108153->world: 10.20.0.11:3000 -> 100.64.50.1:53096 tcp ACK
```

Certainly there's a path for the package to go back to the original sender via Nebula interface, not sure why Cilium drops the package. Here's the result of `ip r`:

```
default via 192.168.50.1 dev wlp1s0 proto dhcp src 192.168.50.254 metric 600
10.20.0.0/24 via 10.20.0.84 dev cilium_host proto kernel src 10.20.0.84
10.20.0.84 dev cilium_host proto kernel scope link
10.20.1.0/24 via 192.168.50.119 dev wlp1s0 proto 17
10.40.0.0/16 dev nebula.nebula0 scope link
100.64.0.0/10 dev nebula.nebula0 proto kernel scope link src 100.64.10.2 mtu 1300
192.168.50.0/24 dev wlp1s0 proto kernel scope link src 192.168.50.254 metric 600
```

and the result of `ip r get 100.64.50.1` also shows that there's a route back:

```
100.64.50.1 dev nebula.nebula0 src 100.64.10.2 uid 1000
    cache mtu 1300
```

Here's my developing device nebula config:

```
firewall:
  inbound:
  - host: any
    port: any
    proto: any
  outbound:
  - host: any
    port: any
    proto: any
lighthouse:
  am_lighthouse: false
  hosts:
  - 100.64.0.1
  - 100.64.0.2
listen:
  host: 0.0.0.0
  port: 0
logging:
  level: info
pki:
  ca: ca.crt
  cert: node.crt
  key: node.key
punchy:
  punch: true
  respond: true
relay:
  am_relay: false
  relays:
  - 100.64.0.1
  - 100.64.0.2
  use_relays: true
static_host_map:
  100.64.0.1:
  - my-light-house0:4242
  100.64.0.2:
  - my-light-house1:4242
tun:
  dev: nebula.nebula0
  disabled: false
  unsafe_routes:
  - route: 10.10.0.0/16
    via: 100.64.10.1
  - route: 10.20.1.0/24
    via: 100.64.10.1
  - route: 10.20.0.0/24
    via: 100.64.10.2
```

### Cilium Version

cilium-cli: 0.15.8 compiled with go1.20.8 on linux/amd64
cilium image (default): v1.14.1
cilium image (stable): v1.14.4
cilium image (running): 1.14.4

### Kernel Version

Linux em680-00 6.1.55 #1-NixOS SMP PREEMPT_DYNAMIC Sat Sep 23 09:11:13 UTC 2023 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2

### Anything else?

I saw there are other similar bug reports, such as 

#29567 
#29413
#25822
#12824

but since there's no Nebula involved, not sure if it's the same issue. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
