### ISSUE TITLE
Data race in SelectorCache.GetNetsLocked()

### ISSUE THREAD

**Issue by lefterisALEX** [cilium/cilium#29604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We noticed that cilium agents are restarting recently and in the logs we see that this is happening when a networkpolicy is added or deleted.

```
evel=info msg="NetworkPolicy successfully removed" k8sApiVersion= k8sNamespace=de-fulfillment-de-shop-order-prod k8sNetworkPolicyName=de-shop-order labels="[k8s:io.cilium.k8s.policy.derived-from=NetworkPolicy k8s:io.cilium.k8s.policy.name=de-shop-order k8s:io.cilium.k8s.policy.namespace=de-fulfillment-de-shop-order-prod k8s:io.cilium.k8s.policy.uid=c575f6f5-da0a-48ba-a933-6383432bfceb]" subsys=k8s-watcher
level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
level=info msg="Policy Add Request" ciliumNetworkPolicy="[&{EndpointSelector:{\"matchLabels\":{\"k8s:io.kubernetes.pod.namespace\":\"de-fulfillment-de-shop-order-prod\"},\"matchExpressions\":[{\"key\":\"k8s:app\",\"operator\":\"In\",\"values\":[\"de-shop-order\",\"de-shop-order-worker\",\"de-shop-order-scheduler\"]}]} NodeSelector:{} Ingress:[] IngressDeny:[] Egress:[{EgressCommonRule:{ToEndpoints:[] ToRequires:[] ToCIDR: ToCIDRSet:[10.23.100.128/32] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc0018097e0 requirements:0xc0019f95d8 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{cidr.10.23.100.128/32: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]} ToPorts:[{Ports:[{Port:44414 Protocol:TCP}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:<nil>} {Ports:[{Port:44259 Protocol:TCP}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:<nil>}] ToFQDNs:[] ICMPs:[]} {EgressCommonRule:{ToEndpoints:[] ToRequires:[] ToCIDR: ToCIDRSet:[10.12.40.0/21] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc0015a6420 requirements:0xc0019f9728 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{cidr.10.12.40.0/21: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]} ToPorts:[{Ports:[{Port:9094 Protocol:TCP}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:<nil>}] ToFQDNs:[] ICMPs:[]} {EgressCommonRule:{ToEndpoints:[] ToRequires:[] ToCIDR: ToCIDRSet:[10.12.48.0/21] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc0015a6940 requirements:0xc0019f97b8 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{cidr.10.12.48.0/21: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]} ToPorts:[{Ports:[{Port:9094 Protocol:TCP}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:<nil>}] ToFQDNs:[] ICMPs:[]} {EgressCommonRule:{ToEndpoints:[] ToRequires:[] ToCIDR: ToCIDRSet:[10.12.56.0/21] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc0015a6a40 requirements:0xc0019f98c0 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{cidr.10.12.56.0/21: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]} ToPorts:[{Ports:[{Port:9094 Protocol:TCP}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:<nil>}] ToFQDNs:[] ICMPs:[]} {EgressCommonRule:{ToEndpoints:[] ToRequires:[] ToCIDR: ToCIDRSet:[10.37.101.23/32] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc0015a6b00 requirements:0xc0019f9998 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{cidr.10.37.101.23/32: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]} ToPorts:[{Ports:[{Port:8443 Protocol:TCP}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:<nil>}] ToFQDNs:[] ICMPs:[]} {EgressCommonRule:{ToEndpoints:[] ToRequires:[] ToCIDR: ToCIDRSet:[144.44.0.0/16] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc0015a6c20 requirements:0xc0019f9a88 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{cidr.144.44.0.0/16: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]} ToPorts:[{Ports:[{Port:8098 Protocol:TCP}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:<nil>}] ToFQDNs:[] ICMPs:[]} {EgressCommonRule:{ToEndpoints:[] ToRequires:[] ToCIDR: ToCIDRSet:[172.16.0.0/12] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc0015a6cc0 requirements:0xc0019f9b30 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{cidr.172.16.0.0/12: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]} ToPorts:[{Ports:[{Port:8098 Protocol:TCP}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:<nil>}] ToFQDNs:[] ICMPs:[]} {EgressCommonRule:{ToEndpoints:[] ToRequires:[] ToCIDR: ToCIDRSet:[10.75.0.0/16] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc0015a6da0 requirements:0xc0019f9bf0 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{cidr.10.75.0.0/16: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]} ToPorts:[{Ports:[{Port:8098 Protocol:TCP}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:<nil>}] ToFQDNs:[] ICMPs:[]} {EgressCommonRule:{ToEndpoints:[] ToRequires:[] ToCIDR: ToCIDRSet:[10.12.40.0/21] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc0015a6ec0 requirements:0xc0019f9cc8 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{cidr.10.12.40.0/21: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]} ToPorts:[{Ports:[{Port:5432 Protocol:TCP}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:<nil>}] ToFQDNs:[] ICMPs:[]} {EgressCommonRule:{ToEndpoints:[] ToRequires:[] ToCIDR: ToCIDRSet:[10.12.48.0/21] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc0015a6f40 requirements:0xc0019f9da0 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{cidr.10.12.48.0/21: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]} ToPorts:[{Ports:[{Port:5432 Protocol:TCP}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:<nil>}] ToFQDNs:[] ICMPs:[]} {EgressCommonRule:{ToEndpoints:[] ToRequires:[] ToCIDR: ToCIDRSet:[10.12.56.0/21] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc0015a7040 requirements:0xc0019f9e60 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{cidr.10.12.56.0/21: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]} ToPorts:[{Ports:[{Port:5432 Protocol:TCP}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:<nil>}] ToFQDNs:[] ICMPs:[]} {EgressCommonRule:{ToEndpoints:[] ToRequires:[] ToCIDR: ToCIDRSet:[10.12.40.0/21] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc0015a7240 requirements:0xc0019f9f50 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{cidr.10.12.40.0/21: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]} ToPorts:[{Ports:[{Port:6379 Protocol:TCP}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:<nil>}] ToFQDNs:[] ICMPs:[]} {EgressCommonRule:{ToEndpoints:[] ToRequires:[] ToCIDR: ToCIDRSet:[10.12.48.0/21] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc0015a7560 requirements:0xc00112a060 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{cidr.10.12.48.0/21: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]} ToPorts:[{Ports:[{Port:6379 Protocol:TCP}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:<nil>}] ToFQDNs:[] ICMPs:[]} {EgressCommonRule:{ToEndpoints:[] ToRequires:[] ToCIDR: ToCIDRSet:[10.12.56.0/21] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc0015a7600 requirements:0xc00112a240 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{cidr.10.12.56.0/21: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]} ToPorts:[{Ports:[{Port:6379 Protocol:TCP}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:<nil>}] ToFQDNs:[] ICMPs:[]} {EgressCommonRule:{ToEndpoints:[] ToRequires:[] ToCIDR: ToCIDRSet:[10.128.191.7/32] ToEntities:[] ToServices:[] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc0015a7800 requirements:0xc00112a318 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{cidr.10.128.191.7/32: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]} ToPorts:[{Ports:[{Port:587 Protocol:TCP}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:<nil>}] ToFQDNs:[] ICMPs:[]}] EgressDeny:[] Labels:[k8s:io.cilium.k8s.policy.derived-from=NetworkPolicy k8s:io.cilium.k8s.policy.name=de-shop-order k8s:io.cilium.k8s.policy.namespace=de-fulfillment-de-shop-order-prod k8s:io.cilium.k8s.policy.uid=2473e2e5-c352-4a10-acd7-68e06246b057] Description:}]" policyAddRequest=92120ab2-cfa0-426a-9e07-44a3475f94b2 subsys=daemon
level=info msg="NetworkPolicy successfully added" k8sApiVersion= k8sNetworkPolicyName=de-shop-order subsys=k8s-watcher
level=error msg="Timed out waiting for datapath updates of FQDN IP information; returning response" subsys=daemon
level=error msg="Timed out waiting for datapath updates of FQDN IP information; returning response" subsys=daemon
level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
fatal error: concurrent map read and map write

goroutine 51559 [running]:
github.com/cilium/cilium/pkg/policy.(*SelectorCache).GetNetsLocked(0x4fcd9e?, 0x4fd13f?)
        /go/src/github.com/cilium/cilium/pkg/policy/selectorcache.go:1119 +0x68
github.com/cilium/cilium/pkg/policy.getNets({0x358a4a0?, 0xc000ad37a0?}, 0xa6?)
```

[cilium-qrk2t.log](https://github.com/cilium/cilium/files/13547458/cilium-qrk2t.log)

Another example:

```
level=info msg="CEP deleted, calling endpointDeleted" CEPName=kiara-system-test-features-microfronten111/ldap-f87649d76-hvjrp CESName=ces-yvtpl68cx-sdtgl subsys=k8s-watcher
level=info msg="CEP deleted, calling endpointDeleted" CEPName=kiara-system-test-features-microfronten111/gval-radim-6f7f98ffdf-2569x CESName=ces-yp79l89kf-ysg7m subsys=k8s-watcher
level=info msg="CEP deleted, calling endpointDeleted" CEPName=kiara-system-test-features-microfronten111/auth-56d855dd6-xh85f CESName=ces-52m786fyk-zshbw subsys=k8s-watcher
level=info msg="CEP deleted, calling endpointDeleted" CEPName=kiara-system-test-features-microfronten111/auth-56d855dd6-qwgxl CESName=ces-52m786fyk-zshbw subsys=k8s-watcher
level=info msg="CEP deleted, calling endpointDeleted" CEPName=kiara-system-test-features-microfronten111/mq-5d776bc5d9-vvxwk CESName=ces-jyw6tf9zg-7ftfk subsys=k8s-watcher
level=info msg="CEP deleted, calling endpointDeleted" CEPName=kiara-system-test-features-microfronten111/gval-7ff8b75fd5-pw5cc CESName=ces-mtssctpgc-pbds6 subsys=k8s-watcher
level=info msg="CEP deleted, calling endpointDeleted" CEPName=kiara-system-test-features-microfronten111/gval-moose-7c686b979f-5c2r8 CESName=ces-z4ldtqthl-6ztwy subsys=k8s-watcher
level=info msg="CEP deleted, calling endpointDeleted" CEPName=kiara-system-test-features-microfronten111/mysql-869f5d69d-tvl9f CESName=ces-qtpk2fy2c-z28zz subsys=k8s-watcher
level=info msg="CEP deleted, calling endpointDeleted" CEPName=kiara-system-test-features-microfronten111/web-gval-59b7d77c7f-dbshp CESName=ces-t5yrszvnj-bmhy4 subsys=k8s-watcher
level=info msg="NetworkPolicy successfully removed" k8sApiVersion= k8sNamespace=kiara-system-test-features-microfronten111 k8sNetworkPolicyName=np-default labels="[k8s:io.cilium.k8s.policy.derived-from=NetworkPolicy k8s:io.cilium.k8s.policy.name=np-default k8s:io.cilium.k8s.policy.namespace=kiara-system-test-features-microfronten111 k8s:io.cilium.k8s.policy.uid=9fd24259-33f9-4faf-a6ed-c2f51bb71538]" subsys=k8s-watcher
level=info msg="CEP deleted, calling endpointDeleted" CEPName=kiara-system-test-features-microfronten111/web-manager-7d7f48b7f6-5tkfc CESName=ces-fcs5p5lch-fy7zx subsys=k8s-watcher
level=info msg="CEP deleted, calling endpointDeleted" CEPName=kiara-system-test-features-microfronten111/web-root-5758867d89-98mwk CESName=ces-rqkzn2d5b-hy4k8 subsys=k8s-watcher
level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
fatal error: concurrent map read and map write

goroutine 10771 [running]:
github.com/cilium/cilium/pkg/policy.(*SelectorCache).GetNetsLocked(0x4fcd9e?, 0x4fd13f?)
        /go/src/github.com/cilium/cilium/pkg/policy/selectorcache.go:1119 +0x68
  ```

[cilium-rwqn6.log](https://github.com/cilium/cilium/files/13547496/cilium-rwqn6.log)

Maybe related with https://github.com/cilium/cilium/issues/24021 ?
### Cilium Version

1.12.15

### Kernel Version

5.10.198-187.748.amzn2.x86_64 

### Kubernetes Version

v1.24.17-eks-4f4795d

### Sysdump

I got the `cilium-sysdump` and size is 1.5G , i can share a URL in a private message to download if needed. 

### Relevant log output

```shell
─ cilium sysdump
🔍 Collecting sysdump with cilium-cli version: v0.14.1, args: [sysdump]
🔮 Detected Cilium installation in namespace "kube-system"
🔮 Detected Cilium operator in namespace "kube-system"
🔍 Collecting Kubernetes nodes
⚠️ Detected a large cluster (84 nodes)
⚠️ Consider using a node filter, a custom log size limit and/or a custom log time range to decrease the size of the sysdump
⚠️ Waiting for 5s before continuing
🔍 Collect Kubernetes nodes
🔍 Collect Kubernetes version
🔍 Collecting Kubernetes events
🔍 Collecting Kubernetes pods
🔍 Collecting Kubernetes namespaces
🔍 Collecting Kubernetes services
🔍 Collecting Kubernetes endpoints
🔍 Collecting Kubernetes pods summary
🔍 Collecting Kubernetes network policies
🔍 Collecting Kubernetes leases
🔍 Collecting Cilium network policies
🔍 Collecting Cilium cluster-wide network policies
🔍 Collecting Cilium egress NAT policies
🔍 Collecting Cilium local redirect policies
🔍 Collecting Cilium Egress Gateway policies
🔍 Collecting Cilium endpoints
🔍 Collecting Cilium endpoint slices
🔍 Collecting Cilium nodes
🔍 Collecting Cilium identities
🔍 Collecting Cilium Node Configs
🔍 Collecting Ingresses
🔍 Collecting CiliumClusterwideEnvoyConfigs
🔍 Collecting CiliumEnvoyConfigs
🔍 Collecting Cilium BGP Peering Policies
🔍 Collecting Cilium LoadBalancer IP Pools
🔍 Collecting Cilium etcd secret
🔍 Collecting the Cilium configuration
🔍 Collecting the Cilium daemonset(s)
🔍 Collecting the Hubble daemonset
🔍 Collecting the Hubble Relay configuration
🔍 Collecting the Hubble Relay deployment
🔍 Collecting the Hubble UI deployment
🔍 Collecting the Cilium operator deployment
🔍 Collecting the 'clustermesh-apiserver' deployment
🔍 Collecting the CNI configuration files from Cilium pods
🔍 Collecting the CNI configmap
🔍 Collecting gops stats from Cilium pods
🔍 Collecting gops stats from Hubble pods
🔍 Collecting gops stats from Hubble Relay pods
⚠️ Deployment "clustermesh-apiserver" not found in namespace "kube-system" - this is expected if 'clustermesh-apiserver' isn't enabled
🔍 Collecting bugtool output from Cilium pods
🔍 Collecting profiling data from Cilium pods
🔍 Collecting logs from Cilium pods
🔍 Collecting logs from Cilium operator pods
🔍 Collecting logs from 'clustermesh-apiserver' pods
🔍 Collecting logs from Hubble pods
I1204 14:56:31.189565   77455 request.go:696] Waited for 1.094421201s due to client-side throttling, not priority and fairness, request: GET:https://AA3053773B5CEE61EBDD3BFEC5CA9708.sk1.eu-west-1.eks.amazonaws.com/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dclustermesh-apiserver
🔍 Collecting logs from Hubble Relay pods
🔍 Collecting logs from Hubble UI pods
🔍 Collecting bugtool output from Tetragon pods
🔍 Collecting platform-specific data
🔍 Collecting kvstore data
🔍 Collecting Tetragon tracing policies
🔍 Collecting Cilium external workloads
🔍 Collecting Hubble flows from Cilium pods

⚠️ Failed to unarchive 'cilium-bugtool' output for "cilium-98wj2": reading file in tar archive: /var/folders/9w/_s515ddn4px8855zkfkmp9yr0000gn/T/2232329086/cilium-sysdump-20231204-145623/cilium-bugtool-cilium-98wj2-20231204-145623/cmd/state/74/bpf_netdev_eth0.o: writing file: unexpected EOF

⚠️ Failed to unarchive 'cilium-bugtool' output for "cilium-cd925": reading file in tar archive: /var/folders/9w/_s515ddn4px8855zkfkmp9yr0000gn/T/2232329086/cilium-sysdump-20231204-145623/cilium-bugtool-cilium-cd925-20231204-145623/cmd/state/templates/e5f81f17af4620a530eebc3af1cedb3a87c6998b874c46cf67ef9d7624d16e25/bpf_lxc.o: writing file: unexpected EOF
⚠️ Failed to unarchive 'cilium-bugtool' output for "cilium-b89p8": reading file in tar archive: /var/folders/9w/_s515ddn4px8855zkfkmp9yr0000gn/T/2232329086/cilium-sysdump-20231204-145623/cilium-bugtool-cilium-b89p8-20231204-145623/cmd/state/651/template.o: writing file: unexpected EOF
I1204 15:03:49.185270   77455 request.go:696] Waited for 1.155086609s due to client-side throttling, not priority and fairness, request: GET:https://AA3053773B5CEE61EBDD3BFEC5CA9708.sk1.eu-west-1.eks.amazonaws.com/api/v1/namespaces/kube-system/pods/cilium-lg4mt/log?container=mount-cgroup&limitBytes=1073741824&sinceTime=2022-12-04T13%3A56%3A31Z&timestamps=true
I1204 15:03:59.186405   77455 request.go:696] Waited for 3.564973957s due to client-side throttling, not priority and fairness, request: GET:https://AA3053773B5CEE61EBDD3BFEC5CA9708.sk1.eu-west-1.eks.amazonaws.com/api/v1/namespaces/kube-system/pods/cilium-pf2ng/log?container=mount-bpf-fs&limitBytes=1073741824&sinceTime=2022-12-04T13%3A56%3A31Z&timestamps=true

I1204 15:04:09.386536   77455 request.go:696] Waited for 3.430898369s due to client-side throttling, not priority and fairness, request: GET:https://AA3053773B5CEE61EBDD3BFEC5CA9708.sk1.eu-west-1.eks.amazonaws.com/api/v1/namespaces/kube-system/pods/cilium-qnhbk/log?container=cilium-agent&limitBytes=1073741824&previous=true&sinceTime=2022-12-04T13%3A56%3A31Z&timestamps=true
I1204 15:04:19.586088   77455 request.go:696] Waited for 3.522866605s due to client-side throttling, not priority and fairness, request: GET:https://AA3053773B5CEE61EBDD3BFEC5CA9708.sk1.eu-west-1.eks.amazonaws.com/api/v1/namespaces/kube-system/pods/cilium-slj65/log?container=cilium-agent&limitBytes=1073741824&sinceTime=2022-12-04T13%3A56%3A31Z&timestamps=true
I1204 15:04:29.785891   77455 request.go:696] Waited for 3.5638857s due to client-side throttling, not priority and fairness, request: GET:https://AA3053773B5CEE61EBDD3BFEC5CA9708.sk1.eu-west-1.eks.amazonaws.com/api/v1/namespaces/kube-system/pods/cilium-wwfc7/log?container=apply-sysctl-overwrites&limitBytes=1073741824&sinceTime=2022-12-04T13%3A56%3A31Z&timestamps=true
⚠️ The following tasks failed, the sysdump may be incomplete:
⚠️ [5] Collecting Kubernetes pods summary: failed to collect Kubernetes pods summary: expected a single kind of resource (got 7)
⚠️ [12] Collecting Cilium egress NAT policies: failed to collect Cilium egress NAT policies: the server could not find the requested resource
⚠️ [13] Collecting Cilium Egress Gateway policies: failed to collect Cilium Egress Gateway policies: the server could not find the requested resource (get ciliumegressgatewaypolicies.cilium.io)
⚠️ [19] Collecting Cilium Node Configs: failed to collect Cilium Node configs: the server could not find the requested resource (get ciliumnodeconfigs.cilium.io)
⚠️ [21] Collecting CiliumClusterwideEnvoyConfigs: failed to collect CiliumClusterwideEnvoyConfigs: the server could not find the requested resource (get ciliumclusterwideenvoyconfigs.cilium.io)
⚠️ [22] Collecting CiliumEnvoyConfigs: failed to collect CiliumEnvoyConfigs: the server could not find the requested resource (get ciliumenvoyconfigs.cilium.io)
⚠️ [23] Collecting Cilium BGP Peering Policies: failed to collect Cilium BGP Peering policies: the server could not find the requested resource (get ciliumbgppeeringpolicies.cilium.io)
⚠️ [24] Collecting Cilium LoadBalancer IP Pools: failed to collect Cilium LoadBalancer IP Pools: the server could not find the requested resource (get ciliumbgppeeringpolicies.cilium.io)
⚠️ [50] Collecting Tetragon tracing policies: failed to collect Tetragon tracing policies: the server could not find the requested resource (get tracingpolicies.cilium.io)
⚠️ Please note that depending on your Cilium version and installation options, this may be expected
🗳 Compiling sysdump

✅ The sysdump has been saved to cilium-sysdump-20231204-145623.zip
```

### Anything else?

*Helm values*
```
USER-SUPPLIED VALUES:
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64
        - key: eks.amazonaws.com/compute-type
          operator: NotIn
          values:
          - fargate
bpf:
  hostRouting: false
  masquerade: true
  tproxy: true
cni:
  chainingMode: none
  configMap: cni-configuration
  customConf: true
  uninstall: false
devices: eth0
enableCiliumEndpointSlice: true
endpointHealthChecking:
  enabled: false
eni:
  ec2APIEndpoint: ec2.eu-west-1.amazonaws.com
  enabled: true
  updateEC2AdapterLimitViaAPI: true
extraConfig:
  api-rate-limit: |
    {"endpoint-create":"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true","endpoint-delete":"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true","endpoint-get":"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true","endpoint-list":"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true","endpoint-patch":"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true"}
healthChecking: false
hubble:
  enabled: true
  eventBufferCapacity: "8191"
  metrics:
    enabled: null
    serviceMonitor:
      enabled: true
      labels:
        tcloud-system: "true"
  relay:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: k8s-app
              operator: In
              values:
              - hubble-relay
          topologyKey: kubernetes.io/hostname
    enabled: true
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
    replicas: 3
    rollOutPods: true
    securityContext:
      seccompProfile:
        type: RuntimeDefault
    tolerations:
    - key: node.cilium.io/agent-not-ready
      operator: Exists
    - key: node.kubernetes.io/dns-not-ready
      operator: Exists
  ui:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: k8s-app
              operator: In
              values:
              - hubble-ui
          topologyKey: kubernetes.io/hostname
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      hosts:
      - hubble.xxx.xxx.xxx
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
    replicas: 3
    rollOutPods: true
    securityContext:
      seccompProfile:
        type: RuntimeDefault
    tolerations:
    - key: node.cilium.io/agent-not-ready
      operator: Exists
    - key: node.kubernetes.io/dns-not-ready
      operator: Exists
ipam:
  mode: eni
k8sServiceHost: xxxxxx.sk1.eu-west-1.eks.amazonaws.com
k8sServicePort: 443
kubeProxyReplacement: strict
l7Proxy: true
labels: k8s:!job-name k8s:!controller-uid k8s:!io.cilium.k8s.namespace.labels.cost.tcloud.kubernetes.io/*
loadBalancer:
  serviceTopology: true
localRedirectPolicy: true
operator:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: io.cilium/app
            operator: In
            values:
            - operator
          - key: name
            operator: In
            values:
            - cilium-operator
        topologyKey: kubernetes.io/hostname
  extraArgs:
  - --unmanaged-pod-watcher-interval=0
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  priorityClassName: system-cluster-critical
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        tcloud-system: "true"
  replicas: 3
  rollOutPods: true
  tolerations:
  - key: node.cilium.io/agent-not-ready
    operator: Exists
  - key: node.kubernetes.io/not-ready
    operator: Exists
  - key: node.kubernetes.io/dns-not-ready
    operator: Exists
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
priorityClassName: system-node-critical
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      tcloud-system: "true"
svcSourceRangeCheck: "false"
tunnel: disabled
updateStrategy:
  type: OnDelete
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
