### ISSUE TITLE
To world traffic incorrectly denied by network policy when enabling DNS observability

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#29666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After applying a CiliumNetworkPolicy \[1\] allowing traffic to coredns and world entities only, as well as enabling DNS observability, all traffic towards external addresses gets incorrectly dropped. This issue reproduces only on main, and in case the network policy includes the DNS observability rule.

Relevant `cilium monitor` drop event:
```
Policy verdict log: flow 0xe0ba5513 local EP ID 556, remote ID 16777217, proto 6, egress, action deny, auth: disabled, match none, 10.244.1.111:55102 -> 216.58.204.132:80 tcp SYN
xx drop (Policy denied) flow 0xe0ba5513 to endpoint 0, ifindex 8, file bpf_lxc.c:1289, , identity 37740->16777217: 10.244.1.111:55102 -> 216.58.204.132:80 tcp SYN
```

Corresponding ipcache entry:
```
216.58.204.132/32               identity=16777217 encryptkey=0 tunnelendpoint=0.0.0.0
```

Identities:
```
16777217   cidr:216.58.204.132/32
           reserved:world-ipv4
16777218   cidr:2a00:1450:4002:403::2004/128
           reserved:world-ipv6
```

With v1.14, instead, the ipcache entry is not present, and the `cilium monitor` output reads:

```
Policy verdict log: flow 0xba9162c local EP ID 3165, remote ID world, proto 6, egress, action allow, auth: disabled, match L3-Only, 10.20.1.244:35236 -> 142.251.209.4:80 tcp SYN
-> stack flow 0xba9162c , identity 61645->world state new ifindex 0 orig-ip 0.0.0.0: 10.20.1.244:35236 -> 142.251.209.4:80 tcp SYN
```

Tested on the dual stack kind cluster created with:
```
KIND_CLUSTER_NAME=kind make kind && make kind-image && make kind-install-cilium
```

\[1\]:

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: to-world
spec:
  endpointSelector: {}
  egress:
    - toEntities:
        - world
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
```

### Cilium Version

Tip of main (https://github.com/cilium/cilium/commit/d1128cf948979de7433385b2101a98404d99c64f). Stable versions are not affected.

### Sysdump

[cilium-sysdump-20231206-143252.zip](https://github.com/cilium/cilium/files/13583486/cilium-sysdump-20231206-143252.zip)

### Anything else?

Marked as release blocker given that it is a regression from v1.14.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HSoulat** [comment]
@giorio94 can you let me know with wchich 1.14.X version you've done the test ?
I'm facing a similar issue in 1.14.5 version but 1.14.2 seems not impacted.

**Comment by giorio94** [comment]
This regression is also affecting the IPsec upgrade/downgrade workflows on main now (not related to IPsec, but it is the only action running the full connectivity suite more than once):

```
❌ 1/54 tests failed (1/541 actions), 17 tests skipped, 1 scenarios skipped:
Test [to-entities-world]:
  ❌ to-entities-world/pod-to-world/http-to-one.one.one.one-0: cilium-test/client-59bddc8c5-k5s6z (10.244.1.211) -> one.one.one.one-http (one.one.one.one:80)
```

**Comment by squeed** [comment]
The bug is that the generated identities have `reserved:world:ipv4` but not `reserved:world`. I'll look in to why.

**Comment by squeed** [comment]
There is a strange bug; an identity is being allocated for the name but policy maps are not being updated. I probably broke this. I'm investigating.

**Comment by squeed** [comment]
This is strange; an identity is being allocated (by the ipcache) but it is not making it down in to the policy maps. Somewhere, an incremental update is not being processed.

Investigating.

**Comment by squeed** [comment]
No, this is not a missed identity. It is the `world` policy identity generating an incorrect selector for `reserved:world`, when it should select `reserved:world-ipv4` and `reserved:world-ipv6`

**Comment by squeed** [comment]
So, the policy listed above, which contains the following selector:

```yaml
  egress:
    - toEntities:
        - world
```

is parsed to this SelectorCache:
```
&LabelSelector{MatchLabels:map[string]string{reserved.world: ,},MatchExpressions:[]LabelSelectorRequirement{},}
```

However, `reserved:world` needs to be unconditionally added.

I'll have a fix shortly.
