### ISSUE TITLE
Authentication service not reachable from ext_authz envoy filter

### ISSUE THREAD

**Issue by hleal18** [cilium/cilium#29831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I’ve been experimenting with cilium mesh, specifically with the ext_authz filter configuration through the CEC manifests. I have the requirement of enforcing basic-auth for traffic directed to certain workloads. Right now I’m fulfilling that requirement through istio envoyfilters but I’m considering the whole feature-set and power of cilium mesh to see if it’s feasible as a replacement in a sidecar-less fashion.

First, the [guide](https://docs.cilium.io/en/latest/network/servicemesh/envoy-traffic-management/) was used as inspiration on how to setup the `CiliumClusterwideEnvoyConfig` manifest: define a listener, route and cluster resources. In this same manifest I added ext_authz filter with details about redirecting the traffic to the proper authentication service.

The initial iteration of the experiment consisted of: nginx deployment as the target; curl pod as the client & auth service, all of them deployed on the same namespace.

The following manifest was used as a result:

```jsx
apiVersion: cilium.io/v2
kind: CiliumClusterwideEnvoyConfig
metadata:
  name: nginx-deployment-1
spec:
	services:
	  - name: nginx-deployment-1
	    namespace: default
  resources:
    - '@type': type.googleapis.com/envoy.config.listener.v3.Listener
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                '@type': >-
                  type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                http_filters:
                  - name: envoy.filters.http.ext_authz
                    typed_config:
                      '@type': >-
                        type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                      http_service:
                        path_prefix: /auth/port
                        server_uri:
                          cluster: default/auth
                          timeout: 15s
                          uri: >-
                            http://auth.default.svc.cluster.local:3000
                  - name: envoy.filters.http.router
                    typed_config:
                      '@type': >-
                        type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                rds:
                  route_config_name: lb_route
                stat_prefix: envoy-lb-listener
      name: envoy-lb-listener
    - '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
      name: lb_route
      virtual_hosts:
        - domains:
            - '*'
          name: lb_route
          routes:
            - match:
                prefix: /
              route:
                cluster: default/nginx-deployment-1
    - '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
      connect_timeout: 15s
      lb_policy: ROUND_ROBIN
      name: default/auth
      type: EDS
    - '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
      connect_timeout: 15s
      lb_policy: ROUND_ROBIN
      name: default/nginx-deployment-1
      type: EDS

```

The `nginx-deployment-1` service was accessed through a pod on the same namespace with the `curl` utility:

```jsx
kubectl exec -it <pod-name> -- curl -v <http://<basic-auth-credentials>@nginx-deployment-1:80/>

```

Expected response if credentials are correct: `nginx` page, otherwise a `401 - Unauthorized` error.

This setup works as expected and the request is routed to the auth service for credential validation and then it goes through to the destination if credentials were valid.

However, the auth service needs to be in its own namespace, and when tweaking the manifest to reference the `authentication/auth` service instead of the `default/auth` the request doesn’t seem to be redirected at all. This time all requests return `403 - Forbidden` , even if credentials were valid. In this setup: client and destination are on the same `default` namespace but the auth service is now located on the `authentication` namespace, the auth service doesn’t seem to be reachable even if having the EDS cluster definition there with the proper namespace.

The relevant changes were applied to the EDS cluster entry to reference `authentication/auth` and the `http_service.server_uri.cluster: authentication/auth` .

I was expecting the authentication request to get properly routed to the authentication service located on a different namespace.

A solution that seems to work is to add the `authentication/auth` service to the `spec.services` . However we’re not fully sure if that is the intended usage of the `spec.services` attribute. 

Apart from that we’ve observed that in this setup, adding the `authentication/auth` service entry to the manifest, and then deleting it, it doesn’t return the state of the envoy config to the previous state. Without that service entry on the manifest, according to what we’ve seen, the `authentication/auth` was expected to be unreachable, nonetheless it was still accessible after the process of: adding the service entry to the `spec.services` selector and then deleting it.

Restarting the cilium agents and envoy proxies fixes the apparent envoy misconfiguration and makes the `authentication/auth` to be unreachable. The unpredictability with these `spec.services` updates makes us think that there’s probably something wrong when reconciling these kinds of updates aside from not knowing what’s the expected behavior of this configuration.

### Cilium Version

1.14.3

### Kernel Version

5.15.109

### Kubernetes Version

v1.27.3-gke.100

### Sysdump

[cilium-sysdump-20231211-121108.zip](https://github.com/cilium/cilium/files/13652617/cilium-sysdump-20231211-121108.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
@hleal18 I had a chat with @mhofstetter, he mentioned that v1.15 has significant improvements to CEC reconciliation. Would you be willing to give that a try? (There are some release candidates, and we should be shipping it soon).

**Comment by hleal18** [comment]
I had a look at the 1.15.0-rc.1 version. Multiple things to comment:
* Using this new version now I have to add the auth service to the CEC `spec.services` selector even if that svc is located in the same namespace as the destination. Previously that requirement was only needed when the auth service was deployed in a different namespace. This means the original manifest attached on the issue no longer works and need to tweak the `spec.services` attribute; otherwise requests won’t get routed to the auth service in the same namespace.
* Not sure if the previous is the intended behavior because looks like the requirement to add services other than the destination svc on the CEC `spec.services` selector may lead to unexpected issues where the L7 filter is not enforced as expected, like the following issue I also reported: https://github.com/cilium/cilium/issues/29832 (unless there’s a more appropriate way to configure it).
* The reconciliation issue persists. Adding a service entry to the `spec.services` selector allow requests to get routed to the auth service. Deleting the svc entry shows that things still work even though requests should have returned 403. Restarting cilium agents and cilium-envoy pods allowed the envoy config to go back to the initial state of requests not routed to the auth service and returning 403.

**Comment by sakirma** [comment]
@hleal18 Sorry for opening an old issue, but I was wondering what your final solution is for setting up ext_authz with cilium. 
It is almost impossible to find a good example and this is the most recent topic about ext_authz that I can find.

For instance, you have set `path_prefix`, which is I assume the path to the auth service that you are using. But on the logs of envoy it prepends to the actual endpoint of the service which I am calling`':path', '/token/validate/health'`. So /health in this case is the endpoint of the service that I want to call.
So something is not adding up and there is no solution for this. On other issues of other projects they mention `'/token/validate?path=/health`. So adding `?path=`. But this also didn't fix it for me.
All in all, I would love to see your current configuration and maybe even adding it to the official documentation as an example :D

**Comment by danielloader** [comment]
Would appreciate if there was a custom resource akin to Istio's AuthorizationPolicy that could configure traffic to be passed to an ext_authz filter service hosted inside the mesh.

**Comment by sastcsgh** [comment]
I also can't seem to get the ext_authz filter working as it should.. I'll second the request for an easy way to configure Envoy Filters, in our case on a specific Gateway or HTTPRoute Instance, preferably similar to the way it works in Envoy Gateway, for example.

**Comment by wei840222** [comment]
This config works for me.
Cilium version: 1.18.2

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-ext-authz
  namespace: identity-aware-proxy
  labels:
    app.kubernetes.io/name: envoy-ext-authz
    app.kubernetes.io/instance: identity-aware-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy-ext-authz
      app.kubernetes.io/instance: identity-aware-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: envoy-ext-authz
        app.kubernetes.io/instance: identity-aware-proxy
    spec:
      containers:
        - name: envoy-ext-authz
          image: registry-gitea.home-infra.weii.cloud/wei840222/envoy.ext_authz-996235dfdb6b15510ff0afade09d5522@sha256:0ba5f014e909c971e60dc6005a4b66329ed946be3108e59675b84966f40ab385
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-ext-authz
  namespace: identity-aware-proxy
  labels:
    app.kubernetes.io/name: envoy-ext-authz
    app.kubernetes.io/instance: identity-aware-proxy
spec:
  selector:
    app.kubernetes.io/name: envoy-ext-authz
    app.kubernetes.io/instance: identity-aware-proxy
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: grpc
---
apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:
  name: gatus-envoy-ext-authz
  namespace: gatus
spec:
  services:
    - name: gatus
      namespace: gatus
    - name: envoy-ext-authz
      namespace: identity-aware-proxy
  resources:
    - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
      name: gatus-envoy-ext-authz-listener
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                commonHttpProtocolOptions:
                  maxStreamDuration: 0s
                stat_prefix: gatus-envoy-ext-authz-listener
                streamIdleTimeout: 300s
                upgradeConfigs:
                  - upgradeType: websocket
                rds:
                  route_config_name: gatus-envoy-ext-authz-route
                use_remote_address: true
                http_filters:
                  - name: envoy.filters.http.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                      transport_api_version: V3
                      grpc_service:
                        envoy_grpc:
                          cluster_name: identity-aware-proxy/envoy-ext-authz
                      failure_mode_allow: false
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    - "@type": type.googleapis.com/envoy.config.route.v3.RouteConfiguration
      name: gatus-envoy-ext-authz-route
      virtual_hosts:
        - name: gatus-envoy-ext-authz-route
          domains:
            - "*"
          routes:
            - match:
                prefix: /
              route:
                cluster: gatus/gatus
                maxStreamDuration:
                  maxStreamDuration: 0s
    - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
      name: gatus/gatus
      edsClusterConfig:
        serviceName: gatus/gatus:80
      outlierDetection:
        splitExternalLocalOriginErrors: true
      type: EDS
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          commonHttpProtocolOptions:
            idleTimeout: 3600s
          explicit_http_config:
            httpProtocolOptions: {}
    - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
      name: identity-aware-proxy/envoy-ext-authz
      type: EDS
      connect_timeout: 3s
      lb_policy: ROUND_ROBIN
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
```
