### ISSUE TITLE
External traffic to service with CiliumEnvoyConfig CRD doesn’t get routed through the L7 proxy when using istio-ingressgateway

### ISSUE THREAD

**Issue by hleal18** [cilium/cilium#29832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have a setup where we’re testing the capabilities of cilium mesh to integrate it through a sidecar-less mode while having Istio to provide external traffic capabilities with the ingress gateway, via the Gateway, and Virtual Service resources.

We’ve followed the guide on load-balancing and url-rewrite for cilium mesh through the CiliumEnvoyConfig CRD which worked well for us when used for workloads within the cluster itself, however, we are experiencing issues when connections originate from outside the cluster, routed via the Istio gateways.

We tweaked this experiment with the same CEC CRD to verify if external traffic would also get properly routed through the L7 proxy. We’ve configured the Istio ingress gateway to expose a specific service on a path, such as `http://<lb-ip>/echo-service-1` .

However, when trying `curl -v http://<lb-ip>/echo-service-1` routing works okay to the referenced service, but it is not load-balancing traffic across both backends; the echo-service-1 deployment handles all traffic.

We’ve also tweaked the network policies as recommended in the guide to select the Istio ingress gateway pods. We also tried to delete the network policies in case these were interfering with the connection, however, both options made no difference.

The network policies adapted to select the `istio-system/istio-ingressgateway` deployment and used in this experiment:

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: istio-egress-l7-http
  namespace: istio-system
spec:
  endpointSelector:
    matchLabels:
      app: istio-ingressgateway
  egress:
    # Allow GET / requests towards echo pods.
    - toEndpoints:
        - matchLabels:
            k8s:kind: echo
            k8s:io.kubernetes.pod.namespace: default
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
          rules:
            http:
              - method: "GET"
                path: "/echo-service-1"
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: istio-egress-only-dns
  namespace: istio-system
spec:
  endpointSelector:
    matchLabels:
      app: istio-ingressgateway
  egress:
    - toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
      toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: coredns
```

We tracked incoming traffic for echo-service-1 and echo-service-2 pods through Hubble and all of the traffic routed through the `istio-ingressgateway` svc was still reaching the former. The filter was still not enforced despite Hubble showing traffic being routed through the L7 proxy.

An alternative that looked promising was to add the `istio-system/istio-ingressgateway` to the CEC service selector attribute. This fixed the issue for the services exposed via `echo-service-1` path, traffic was now being load-balanced as per the filter. The problem now is that it was also enforcing the filter to the other routes pointing to different workloads. At the end some of the workloads behind the istio-ingressgateway svc were unreachable due to all traffic now being redirected to the `echo-service-1` service.

Taking into account that the `VirtualService` manifest is referencing the `echo-service-1` service and this service is also part of the CEC service selector, I’d have expected this configuration to be enough so the L7 filter is enforced for all traffic aimed at that service. However, when traffic first goes through the istio-ingressgateway→echo-service-1 (as it happens with external traffic), looks like it’s not enforcing the L7 filter that we created. But if we exec into the `istio-ingressgateway` pod and curl the `echo-service-1.default` endpoint, traffic gets load-balanced just fine.

I’d like to know if this is an expected behavior or if I am overlooking something.

The CEC manifest used was the same one from the [guide](https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/kubernetes/servicemesh/envoy/envoy-traffic-management-test.yaml). The `spec.services` were tweaked at some point to add the `istio-system/istio-ingressgateway` entry to it as previously mentioned.

I attach the CEC manifest used for reference with the `services` selector targeting the `istio-system/istio-ingressgateway` svc:

```
apiVersion: cilium.io/v2
kind: CiliumClusterwideEnvoyConfig
metadata:
  name: envoy-lb-listener
spec:
  services:
    - name: echo-service-1
      namespace: default
    - name: echo-service-2
      namespace: default
    - name: istio-ingressgateway
      namespace: istio-system
  resources:
    - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
      name: envoy-lb-listener
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: envoy-lb-listener
                rds:
                  route_config_name: lb_route
                use_remote_address: true
                skip_xff_append: true
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    - "@type": type.googleapis.com/envoy.config.route.v3.RouteConfiguration
      name: lb_route
      virtual_hosts:
        - name: "lb_route"
          domains: [ "*" ]
          routes:
            - match:
                prefix: "/"
              route:
                weighted_clusters:
                  clusters:
                    - name: "default/echo-service-1"
                      weight: 50
                    - name: "default/echo-service-2"
                      weight: 50
                retry_policy:
                  retry_on: 5xx
                  num_retries: 3
                  per_try_timeout: 1s
                regex_rewrite:
                  pattern:
                    google_re2: { }
                    regex: "^/foo.*$"
                  substitution: "/"
    - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
      name: "default/echo-service-1"
      connect_timeout: 5s
      lb_policy: ROUND_ROBIN
      type: EDS
      outlier_detection:
        split_external_local_origin_errors: true
        consecutive_local_origin_failure: 2
    - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
      name: "default/echo-service-2"
      connect_timeout: 3s
      lb_policy: ROUND_ROBIN
      type: EDS
      outlier_detection:
        split_external_local_origin_errors: true
        consecutive_local_origin_failure: 2
```

### Cilium Version

1.14.3

### Kernel Version

5.15.109

### Kubernetes Version

v1.27.3-gke.100

### Sysdump

[cilium-sysdump-20231211-122048.zip](https://github.com/cilium/cilium/files/13652713/cilium-sysdump-20231211-122048.zip)

### Anything else?

Istio version used was 1.18.5 deployed with the ‘demo’ profile, which comes with the Istio components including the ingress gateways.

Manifests used for configuring external traffic to the echo-service-1 service:

- Gateway

```jsx
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: http
        number: 80
        protocol: HTTP

```

- VirtualService

```jsx
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo-service-1
  namespace: default
spec:
  gateways:
    - gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            exact: /echo-service-1
      route:
        - destination:
            host: echo-service-1
            port:
              number: 8080

```

Cilium was installed with the following values using the Cilium CLI:
```
envoy:
  enabled: true
envoyConfig:
  enabled: true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
