### ISSUE TITLE
ClusterMesh with NodeEncryption(beta) enabled on all nodes is failing.

### ISSUE THREAD

**Issue by jspaleta** [cilium/cilium#29872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This is most likely a documentation bug.

Attempting a clustermesh configuration between 2 kind clusters with node encryption enabled on all nodes and the clustermesh fails to establish. 

node encryption for all nodes was achieved by changing the node-encryption-opt-out-labels extraConfig value to a non-matching string.

Failing config:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: empire-cluster-1
nodes:
- role: control-plane
- role: worker
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
  serviceSubnet: "10.11.0.0/16"
  podSubnet: "10.10.0.0/16"
```

```
cluster:
  name: empire-1
  id: 1  
encryption:
  enabled: true
  type: wireguard
  nodeEncryption: true
kubeProxyReplacement: true
l7Proxy: false

extraConfig:
  node-encryption-opt-out-labels: hmm
```

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: empire-cluster-2
nodes:
- role: control-plane
- role: worker
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
  serviceSubnet: "10.21.0.0/16"
  podSubnet: "10.20.0.0/16"
```

```
cluster:
  name: empire-2
  id: 2  
encryption:
  enabled: true
  type: wireguard
  nodeEncryption: true
kubeProxyReplacement: true
l7Proxy: false

extraConfig:
  node-encryption-opt-out-labels: hmm
```

If the `node-encryption-opt-out-labels` config is removed so the default opt-out label that matches control-plane nodes is used instead clustermesh is established and node-to-node encryption between worker nodes in both clusters is confirmed by watching tcpdump on cilium_wg0

### Cilium Version

```
$ cilium version
cilium-cli: v0.15.17 compiled with go1.21.4 on linux/amd64
cilium image (default): v1.14.4
cilium image (stable): v1.14.4
cilium image (running): 1.14.4
```

### Kernel Version

```
$ uname -a
Linux msi 5.14.0-361.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Aug 24 13:40:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
$ kind version
kind v0.20.0 go1.20.4 linux/amd64
```

```
$ kubectl version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
