### ISSUE TITLE
Cilium does not take care of Pod IPAM with cluster-pool-ipv4-cidr specified

### ISSUE THREAD

**Issue by outductor** [cilium/cilium#29881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I see `v4Prefix=10.0.0.0/24` in the log, even though I configured the cluster pool ipv4. FWIW, My kubeadm config also include this pod cidr.

```
$ kubectl logs -n kube-system cilium-6qm4v | grep ipv4
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
level=info msg="  --bpf-lb-rss-ipv4-src-cidr=''" subsys=daemon
level=info msg="  --cluster-pool-ipv4-cidr='10.96.128.0/18'" subsys=daemon
level=info msg="  --cluster-pool-ipv4-mask-size='24'" subsys=daemon
level=info msg="  --enable-ipv4='true'" subsys=daemon
level=info msg="  --enable-ipv4-big-tcp='false'" subsys=daemon
level=info msg="  --enable-ipv4-egress-gateway='false'" subsys=daemon
level=info msg="  --enable-ipv4-fragment-tracking='true'" subsys=daemon
level=info msg="  --enable-ipv4-masquerade='true'" subsys=daemon
level=info msg="  --ipv4-native-routing-cidr=''" subsys=daemon
level=info msg="  --ipv4-node='auto'" subsys=daemon
level=info msg="  --ipv4-pod-subnets=''" subsys=daemon
level=info msg="  --ipv4-range='auto'" subsys=daemon
level=info msg="  --ipv4-service-loopback-address='169.254.42.1'" subsys=daemon
level=info msg="  --ipv4-service-range='auto'" subsys=daemon
level=info msg="  --k8s-require-ipv4-pod-cidr='false'" subsys=daemon
level=info msg="  --local-router-ipv4=''" subsys=daemon
level=info msg="Received own node information from API server" ipAddr.ipv4=192.168.32.11 ipAddr.ipv6="<nil>" k8sNodeIP=192.168.32.11 labels="map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:seichi-onp-k8s-cp-1 kubernetes.io/os:linux node-role.kubernetes.io/control-plane: node.kubernetes.io/exclude-from-external-load-balancers:]" nodeName=seichi-onp-k8s-cp-1 subsys=k8s v4Prefix=10.0.0.0/24 v6Prefix="<nil>"
level=info msg="Restored router address from node_config" file=/var/run/cilium/state/globals/node_config.h ipv4=10.0.0.186 ipv6="<nil>" subsys=node
```

```
$ kubectl -n kube-system exec -t ds/cilium -c cilium-agent -- cilium status
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.27 (v1.27.8) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    Strict   [ens18 192.168.0.21, ens19 192.168.18.21, ens20 192.168.32.21 (Direct Routing)]
Host firewall:           Disabled
CNI Chaining:            none
Cilium:                  Ok   1.14.5 (v1.14.5-85db28be)
NodeMonitor:             Listening for events on 6 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok
IPAM:                    IPv4: 17/254 allocated from 10.0.3.0/24,
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Host Routing:            Legacy
Masquerading:            IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:       113/113 healthy
Proxy Status:            OK, ip 10.0.3.249, 0 redirects active on ports 10000-20000, Envoy: embedded
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 4095/4095 (100.00%), Flows/s: 69.52   Metrics: Disabled
Encryption:              Disabled
Cluster health:          6/6 reachable   (2023-12-14T08:42:21Z)
```

```yaml
kubeProxyReplacement: strict
k8sServiceHost: 192.168.32.100
k8sServicePort: 8443
bgpControlPlane:
  enabled: true
pprof:
  enabled: true
loadBalancer:
  algorithm: maglev
encryption:
  nodeEncryption: false
ipv4:
  enabled: true
ipv6:
  enabled: false
ipam:
  mode: cluster-pool
  operator:
    # -- IPv4 CIDR list range to delegate to individual nodes for IPAM.
    clusterPoolIPv4PodCIDRList: ["10.96.128.0/18"]
    # -- IPv4 CIDR mask size to delegate to individual nodes for IPAM.
    clusterPoolIPv4MaskSize: 24
```

### Cilium Version

1.14.5

### Kernel Version

```
$ uname -a
Linux seichi-onp-k8s-cp-1 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.8
Kustomize Version: v5.0.1
Server Version: v1.27.8
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
