### ISSUE TITLE
API Gateway TCPRoute - Adding TCPRoute for Logstash and Filebeat

### ISSUE THREAD

**Issue by madushanTHAMB** [cilium/cilium#29924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello everyone ! i tried to put a filebeat on a server and send logs to my logstash service from my K8S cluster. 
Here my code for the API GATEWAY for cilium. So it's listening on HTTP and HTTPS but can't find 5044 TCP.
I follow this documentation : https://gateway-api.sigs.k8s.io/guides/tcp/ 
``` yaml
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: cilium
  labels:
    site: ach
spec:
  gatewayClassName: cilium
  listeners:
  - name: https
    port: 443
    protocol: TLS
    tls:
      mode: Passthrough
    allowedRoutes:
      namespaces:
        from: All
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: logstash
    port: 5044
    protocol: TCP
    allowedRoutes:
      kinds:
      - kind: TCPRoute
      namespaces:
        from: All`
```        
 So i don't really know if the TCPRoute are working or not, but when i'm creating a gateway with only listening 5044 TCP, it's said : "level=error msg="Unable to translate resources" controller=gateway error="model source can't be empty" resource=cilium/tcp-gateway subsys=gateway-controller" 
 
 Here are my routes : 
```yaml
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: test-kibana
  namespace: eck
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: cilium
  hostnames:
  - "test-kibana..com"
  rules:
  - backendRefs:
    - name: kibana-service
      port: 5601
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: test-logstash
  namespace: eck
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: cilium
  rules:
  - backendRefs:
    - name: logstash-service
      port: 5044
 ```
 If someone has sucessfully find a way to create TCPRoute correctly, i hope you will help me !
 
Thanks you very much for your help guys !

### Cilium Version

V1.14.5

### Kernel Version

5.15.0-88-generic

### Kubernetes Version

v1.28.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
