### ISSUE TITLE
CFP: BGP Control Plane - add ExternalIPs support

### ISSUE THREAD

**Issue by defo89** [cilium/cilium#29990]
## Cilium Feature Proposal

We are evaluating running Cilium with BGP Control Plane in baremetal environment. In current setup, a BGP controller (runs on every node per Daemonset) advertises all services that have `.spec.externalIPs` configured.

In case of cilium, PodCIDR announcement works out of the box but no services are announced with following policy:

```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: bgp-peering-policy-foo
spec:
 virtualRouters:
 - localASN: 65000
   exportPodCIDR: true
   serviceSelector:
      matchExpressions:
         - key: somekey
           operator: NotIn
           values: ["never-used-value"]
   neighbors:
    - peerAddress: "10.1.1.1/32"
      peerASN: 65001
      eBGPMultihopTTL: 10
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
```

As far as I understand, currently Cilium would only advertise services of type `LoadBalancer` AND [if the IP is set](https://github.com/cilium/cilium/blob/main/pkg/bgpv1/manager/reconciler/lb_service.go#L315-L318) in `.Status.LoadBalancer.Ingress.IP`.

In our environment Service ExternalIPs are part of application charts, there is no controller to set the status:
```
apiVersion: v1
kind: Service
metadata:
  name: foo-nginx-controller
  namespace: kube-system
spec:
  clusterIP: 100.127.1.2
  clusterIPs:
  - 100.127.1.2
  externalIPs:
  - 10.2.2.2
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    nodePort: 32111
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 31112
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

Include any specific requirements you need

Would you consider advertising `.spec.ExternalIPs` in services of type `LoadBalancer` and `NodePort`?

Since there already is an option [enable-external-ips](https://github.com/cilium/cilium/blob/main/pkg/option/config.go#L139-L140), maybe this feature would be a good addition to it?

**Comment by squeed** [comment]
Makes a lot of sense, very good idea. This is exactly what [ExternalIPs](https://kubernetes.io/docs/concepts/services-networking/service/#external-ips) are meant for.

**Comment by YutaroHayakawa** [comment]
@defo89 Thanks for your suggestion. Here's my implementation proposal (cc: @cilium/sig-bgp). I don't have any cycle to take this task. Anyone can take an implementation task based on this. Any concern or API spec change should be solved before implementation.

## Implementation Proposal

Extend the existing CiliumBGPPeeringPolicy like the following:

```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
spec:
  nodeSelector:
    matchLabels:
      rack: rack0
  virtualRouters:
  - localASN: 64512
    exportExternalIP: true <= New
    serviceSelector:
      matchLabels:
        app: foo
    neighbors:
    - peerAddress: '10.0.0.1/32'
      peerASN: 64512
```

When the exportExternalIP flag is set to true, Cilium advertises all `spec.externalIPs` (as a /32 for IPv4 and /128 for IPv6) assigned to the Services selected with `serviceSelector` and the existing Type Load Balancer ingress IP advertisement. While the existing `serviceSelector` only works for the Type Load Balancer services, it should also work for `ClusterIP` and `NodePort` services.

## Discussion

With the interface described above, there's no way to disable ExternalIP advertisement. Do we want to support such a feature? If so, how? As a reference, KubeRouter supports it with per Service annotation (https://github.com/cloudnativelabs/kube-router/blob/master/docs/user-guide.md#advertising-ips).

**Comment by YutaroHayakawa** [comment]
This kind of API change might be preferable, as we discussed in the ClusterIP issue (https://github.com/cilium/cilium/issues/30875#issuecomment-1959024146).

```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
spec:
  nodeSelector:
    matchLabels:
      rack: rack0
  virtualRouters:
  - localASN: 64512
    serviceSelector:
      matchLabels:
        app: foo
    serviceAdvertisements: <= new
    - LoadBalancerIP
    - ClusterIP
    neighbors:
    - peerAddress: '10.0.0.1/32'
      peerASN: 64512
```
