### ISSUE TITLE
Support AWS Security Groups with security group rules ingress from another security group for Network Policies

### ISSUE THREAD

**Issue by franceschongg** [cilium/cilium#30032]
I'm looking to convert pod security groups over to either Network Policies or Cilium Network Policies.

Currently, both those CRs will support CIDR ranges, but with AWS Security Groups, there's an ability to have a security group rule for ingress that references another security group. This is common when it's an ec2 security group allowing ingress from the alb security group. 

The feature request I'd like is to support the case where a security group can have another security group as the ingress. 

Is this something that could be supported? It doesn't have to be in the Network Policy, it could also be at the Cilium Network Policy.

**Comment by squeed** [comment]
Interesting; can you explain this a bit more? (I like this idea; I sometimes think labels can be too finicky).

Would it be something like

```yaml
kind: CiliumNetworkPolicy
spec:
  endpointSelector:
    matchLabels:
      env: dev
  ingress:
    - fromPolicy:
        name: "storage"
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "storage"
spec:
  endpointSelector:
    matchLabels:
      storage: "true"
```

**Comment by franceschongg** [comment]
I was thinking it would be something like this 


```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l4-rule"
spec:
  endpointSelector:
    matchLabels:
      role: backend
  ingress:
  - fromEndpoints:
    awsSecurityGroups:
      - yourAWSSecurityGroupID
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
```
