### ISSUE TITLE
openstack loadbalancer public ip address

### ISSUE THREAD

**Issue by robkooper** [cilium/cilium#30058]
I have an openstack kubernetes cluster with 2 floating ip addresses that are set up for the loadbalancer. The way this is set up is a private ip address that is used in the cluster that is associated with a public external floating ip address. Leveraging of L2 announcement the private address can be associated with a service of type load balancer. When I try to connect with the external ip address it correctly be able to reach the service, all good.

What I'd like is for the service to have the status to reflect the public ip address, not the private address. This will allow for example external-dns to send the public ip address to the DNS server.

I can do this for nginx:
```
controller:
  extraArgs:
    publish-status-address: PUBLIC_IP_ADDRESS
  publishService:
    enabled: false
  service:
    externalTrafficPolicy: Local
    loadBalancerIP: PRIVATE_IP_ADDRESS
```
and for traefik:
```
service:
  externalIP:
    - PUBLIC_IP_ADDRESS
  spec:
    loadBalancerIP: PRIVATE_IP_ADDRESS
```

Can i do something like this with cilium? I know I can pick the private ip address using, but I could not find a way to specify the address to be used for the status update of a service.
```
ingressController:
  service:
    loadBalancerIP: PRIVATE_IP_ADDRESS
```

**Comment by snovak7** [comment]
I have this working scenario with ingress controller, no luck with gateway api yet

```yaml
ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  service:
    loadBalancerIP: PRIVATE_IP_ADDRESS
```

note, that you want shared mode, so it doesn't allocate new IP for each ingress
