### ISSUE TITLE
FQDN policy cannot work when enabling well-known identities

### ISSUE THREAD

**Issue by yingnanzhang666** [cilium/cilium#30051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the cluster with `--enable-well-known-identities=true`, (kind cluster as a example)
create toFQDNs policy as following:
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-fqdn
  namespace: local-path-storage
spec:
  endpointSelector:
    matchLabels:
      app: local-path-provisioner
  egress:
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        "k8s:k8s-app": kube-dns
    toPorts:
      - ports:
         - port: "53"
           protocol: ANY
        rules:
          dns:
            - matchPattern: "*"
  - toFQDNs:
    - matchName: "google.com"
```
the well-known id (112) for coredns was added into ipcache.
```
root@kind-worker2:/home/cilium# cilium bpf ipcache list
IP PREFIX/ADDRESS   IDENTITY
172.18.0.3/32       identity=6 encryptkey=0 tunnelendpoint=0.0.0.0
172.18.0.5/32       identity=7 encryptkey=0 tunnelendpoint=0.0.0.0
10.244.0.96/32      identity=6 encryptkey=0 tunnelendpoint=172.18.0.5
10.244.1.47/32      identity=4 encryptkey=0 tunnelendpoint=172.18.0.3
===>>> 10.244.2.99/32      identity=112 encryptkey=0 tunnelendpoint=0.0.0.0
10.244.3.139/32     identity=6 encryptkey=0 tunnelendpoint=172.18.0.4
10.244.1.191/32     identity=6 encryptkey=0 tunnelendpoint=172.18.0.3
10.244.2.167/32     identity=1 encryptkey=0 tunnelendpoint=0.0.0.0
0.0.0.0/0           identity=2 encryptkey=0 tunnelendpoint=0.0.0.0
172.18.0.4/32       identity=6 encryptkey=0 tunnelendpoint=0.0.0.0
===>>> 10.244.2.119/32     identity=112 encryptkey=0 tunnelendpoint=0.0.0.0
10.244.2.132/32     identity=13229 encryptkey=0 tunnelendpoint=0.0.0.0
10.244.3.28/32      identity=4 encryptkey=0 tunnelendpoint=172.18.0.4
172.18.0.2/32       identity=1 encryptkey=0 tunnelendpoint=0.0.0.0
10.244.0.250/32     identity=4 encryptkey=0 tunnelendpoint=172.18.0.5
10.244.2.210/32     identity=4 encryptkey=0 tunnelendpoint=0.0.0.0
```
But the policy for allowing dns query to coredns cannot be added to policy bpf map.
```
root@kind-worker2:/home/cilium# cilium bpf policy list
Endpoint ID: 14
Path: /sys/fs/bpf/tc/globals/cilium_policy_00014

POLICY   DIRECTION   LABELS (source:key[=value])   PORT/PROTO   PROXY PORT   AUTH TYPE   BYTES   PACKETS   PREFIX
Allow    Ingress     reserved:unknown              ANY          NONE         disabled    0       0         0
Allow    Ingress     reserved:host                 ANY          NONE         disabled    0       0         0
```

Which caused by that well-known identities were not added into selectorcache.

The identity.InitWellKnown() is called in starthook " • cmd.newDaemonPromise.func1 (cmd/daemon_main.go:1683)".
But init id cache is in constructor "newPolicyTrifecta". When it is called, InitWellKnown() is still not execute.

### Cilium Version

tested on 1.14 and master

### Kernel Version

5.15

### Kubernetes Version

1.23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
