### ISSUE TITLE
BGP CP:  PodCIDRs are not advertised

### ISSUE THREAD

**Issue by wenzt** [cilium/cilium#30056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

bgp has established, but peer can not get advertised route.
```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: 01-bgp-peering-policy
spec: # CiliumBGPPeeringPolicySpec
 nodeSelector:
  matchLabels:
   kubernetes.io/os: linux
 virtualRouters: # []CiliumBGPVirtualRouter
 - localASN: 65999
   exportPodCIDR: true
   neighbors: # []CiliumBGPNeighbor
    - peerAddress: '10.13.1.254/32'
      peerASN: 4200121001
      eBGPMultihopTTL: 10
      connectRetryTimeSeconds: 1
      holdTimeSeconds: 3
      keepAliveTimeSeconds: 1
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
```

```
cilium-agent logs:
level=debug msg="sent update" Key=10.13.1.254 State=BGP_FSM_ESTABLISHED Topic=Peer asn=65999 attributes="[{Origin: i} 65999 {Nexthop: 10.13.1.51}]" component=gobgp.BgpServerInstance nlri="[10.16.1.0/28]" subsys=bgp-control-plane withdrawals="[]"
level=debug msg="Controller func execution time: 97.271µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=4783a936-5b60-4b34-acd6-c4bc4411304d
level=debug msg="received update" Key=10.13.1.254 Topic=Peer asn=65999 attributes="[]" component=gobgp.BgpServerInstance nlri="[]" subsys=bgp-control-plane withdrawals="[]"
```
Why received update atrributes and nlri is empty?

### Cilium Version

1.14.5

### Kernel Version

4.19.91

### Kubernetes Version

1.21

### Relevant log output

```shell
level=info msg="Peer Up" Key=10.13.1.254 State=BGP_FSM_OPENCONFIRM Topic=Peer asn=65999 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=debug msg="state changed" Key=10.13.1.254 Topic=Peer asn=65999 component=gobgp.BgpServerInstance new=BGP_FSM_ESTABLISHED old=BGP_FSM_OPENCONFIRM reason=open-msg-negotiated subsys=bgp-control-plane
level=info msg="type:STATE peer:{conf:{local_asn:65999 neighbor_address:\"10.13.1.254\" peer_asn:4200121001} state:{local_asn:65999 neighbor_address:\"10.13.1.254\" peer_asn:4200121001 session_state:ESTABLISHED router_id:\"10.150.37.2\"} transport:{local_address:\"10.13.1.51\" local_port:15523 remote_port:179}}"
level=debug msg="sent update" Key=10.13.1.254 State=BGP_FSM_ESTABLISHED Topic=Peer asn=65999 attributes="[{Origin: i} 65999 {Nexthop: 10.13.1.51}]" component=gobgp.BgpServerInstance nlri="[10.16.1.0/28]" subsys=bgp-control-plane withdrawals="[]"
level=debug msg="Controller func execution time: 97.271µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=4783a936-5b60-4b34-acd6-c4bc4411304d
level=debug msg="received update" Key=10.13.1.254 Topic=Peer asn=65999 attributes="[]" component=gobgp.BgpServerInstance nlri="[]" subsys=bgp-control-plane withdrawals="[]"
level=debug msg="EOR received" AddressFamily=ipv4-unicast Key=10.13.1.254 Topic=Peer asn=65999 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=debug msg=sent Key=10.13.1.254 State=BGP_FSM_ESTABLISHED Topic=Peer asn=65999 component=gobgp.BgpServerInstance data="&{{[] 19 4} 0x6584828}" subsys=bgp-control-plane
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
