### ISSUE TITLE
Monitoring all dns ingress/egress using hubble not working.

### ISSUE THREAD

**Issue by chary1112004** [cilium/cilium#30068]
## Cilium Feature Proposal
        
Hi, since we are facing that is high transfer data (received and transmitted) through nat gateway (aws) then we are trying to understand **all dns ingress/egress** that the inner pod communicate with.

I have tried to using hubble however it seems not scan all ingress/egress?

```
$ helm upgrade --install  cilium cilium/cilium --version 1.14.5 \
  --namespace kube-system \
  --set cni.chainingMode=aws-cni \
  --set cni.exclusive=false \
  --set enableIPv4Masquerade=false \
  --set routingMode=native \
  --set endpointRoutes.enabled=true \
   --set hubble.relay.enabled=true \
   --set hubble.ui.enabled=true \
  --set global.hubble.enabled=true \
  --set global.hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,http}" \
  --set global.prometheus.enabled=true \
  --set global.operatorPrometheus.enabled=true
```

Enable dns visibility follow video https://cilium.io/use-cases/network-flow-logs/
$ kubectl apply -f dns-visibility.yaml -n kube-system
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: dns-visibility
spec:
  endpointSelector:
    matchLabels: {}
  egress:
  - toEntities:
    - all
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        "k8s:k8s-app": kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"
```

We saw amount of data transfer in grafana dashboard in specific pod **kube-system/aws-node-...** however there is no return in command:
**$ hubble observe --pod kube-system/aws-node-d2qhk -f**

Any solution to resolve this issue would be very much appreciated!
