### ISSUE TITLE
Cilium Ingress Controller responds with "403 Access denied" in `policyAuditMode=true` after upgrade to cilium v1.14.5

### ISSUE THREAD

**Issue by mcflis** [cilium/cilium#30073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrading cilium from `v1.14.3` to `v1.14.5`, requests to the cilium ingress controller are dropped with 
```
Dec 30 09:32:45.423: 192.168.30.2:58682 (ingress) -> kube-system/cilium-ingress:80 (world) http-request DROPPED (HTTP/1.1 GET http://podinfo.my.domain/)
Dec 30 09:32:45.423: 192.168.30.2:58682 (ingress) <- kube-system/cilium-ingress:80 (world) http-response FORWARDED (HTTP/1.1 403 0ms (GET http://podinfo.my.domain/))
```
as soon as the endpoint `reserved:ingress` switches from "default allow" to "default deny" even though cilium runs in policy audit mode (helm value: `policyAuditMode=true`).

Before I've started to test with `policyAuditMode=true`, I've set up cilium to run with
```yaml
policyEnforcementMode: always
hostFirewall:
  enabled: true
extraConfig:
  allow-localhost: policy
```
and proper `CiliumNetworkPolicies` and `CiliumClusterwideNetworkPolicies` in place (ingress working as expected in `v1.14.3` and `v1.14.4`)

Maybe the issue is related to the changes from https://github.com/cilium/cilium/pull/28126

### Cilium Version

1.14.5

### Kernel Version

Linux talos-worker-1 6.1.61-talos #1 SMP Wed Nov  8 10:43:23 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

v1.26.4

### Anything else?

I've used this policy to switch the ingress endpoint to default deny:
```yaml
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "allow-icmp-echo-requests"
specs:
  - endpointSelector:
      matchLabels: {}
    ingress:
      - icmps:
          - fields:
              - type: 8
                family: IPv4
              - type: 128
                family: IPv6
    egress:
      - icmps:
          - fields:
              - type: 8
                family: IPv4
              - type: 128
                family: IPv6
  - nodeSelector:
      matchLabels: {}
    ingress:
      - icmps:
          - fields:
              - type: 8
                family: IPv4
              - type: 128
                family: IPv6
    egress:
      - icmps:
          - fields:
              - type: 8
                family: IPv4
              - type: 128
                family: IPv6
```

The endpoint id of the `reserved:ingress` endpoint is 519.
I've obtained endpoint details with `cilium endpoint get 519` (inside the cilium-agent container) before the automatic switch of the policy enforcement mode to `default deny`:
<details>
  <summary>Show/Hide</summary>
 
  ```json
[
  {
    "id": 519,
    "spec": {
      "label-configuration": {},
      "options": {
        "ConntrackAccounting": "Enabled",
        "ConntrackLocal": "Disabled",
        "Debug": "Disabled",
        "DebugLB": "Disabled",
        "DebugPolicy": "Disabled",
        "DropNotification": "Enabled",
        "MonitorAggregationLevel": "Medium",
        "PolicyAuditMode": "Enabled",
        "PolicyVerdictNotification": "Enabled",
        "SourceIPVerification": "Enabled",
        "TraceNotification": "Enabled"
      }
    },
    "status": {
      "controllers": [
        {
          "configuration": {
            "error-retry": true,
            "error-retry-base": "2s"
          },
          "name": "endpoint-519-regeneration-recovery",
          "status": {
            "last-failure-timestamp": "0001-01-01T00:00:00.000Z",
            "last-success-timestamp": "0001-01-01T00:00:00.000Z"
          },
          "uuid": "e2b2e633-d5c3-4c2a-9d80-f37947d7d73b"
        },
        {
          "configuration": {
            "error-retry": true,
            "interval": "5m0s"
          },
          "name": "resolve-identity-519",
          "status": {
            "last-failure-timestamp": "0001-01-01T00:00:00.000Z",
            "last-success-timestamp": "2023-12-30T08:02:33.408Z",
            "success-count": 98
          },
          "uuid": "cbeff185-e3a8-4e3b-869c-e26b26191a88"
        },
        {
          "configuration": {
            "error-retry": true,
            "interval": "10s"
          },
          "name": "sync-to-k8s-ciliumendpoint (519)",
          "status": {
            "last-failure-timestamp": "0001-01-01T00:00:00.000Z",
            "last-success-timestamp": "2023-12-30T08:04:35.575Z",
            "success-count": 2924
          },
          "uuid": "37d3cbe5-989b-4d5f-9e03-fd5dfe8e3fb2"
        }
      ],
      "external-identifiers": {
        "pod-name": "/"
      },
      "health": {
        "bpf": "OK",
        "connected": true,
        "overallHealth": "OK",
        "policy": "OK"
      },
      "identity": {
        "id": 8,
        "labels": [
          "reserved:ingress"
        ]
      },
      "labels": {
        "derived": [
          "reserved:ingress"
        ],
        "realized": {},
        "security-relevant": [
          "reserved:ingress"
        ]
      },
      "log": [
        {
          "code": "OK",
          "message": "Successfully regenerated endpoint program (Reason: policy rules added)",
          "state": "ready",
          "timestamp": "2023-12-30T07:58:20Z"
        }
      ],
      "networking": {
        "addressing": [
          {
            "ipv4": "10.244.6.214"
          }
        ]
      },
      "policy": {
        "proxy-statistics": [],
        "realized": {
          "allowed-egress-identities": [
            0
          ],
          "allowed-ingress-identities": [
            0
          ],
          "build": 67,
          "denied-egress-identities": null,
          "denied-ingress-identities": null,
          "id": 8,
          "l4": {
            "egress": [],
            "ingress": []
          },
          "policy-enabled": "none",
          "policy-revision": 67
        },
        "spec": {
          "allowed-egress-identities": [
            0
          ],
          "allowed-ingress-identities": [
            0
          ],
          "build": 67,
          "denied-egress-identities": null,
          "denied-ingress-identities": null,
          "id": 8,
          "l4": {
            "egress": [],
            "ingress": []
          },
          "policy-enabled": "none",
          "policy-revision": 67
        }
      },
      "realized": {
        "label-configuration": {},
        "options": {
          "ConntrackAccounting": "Enabled",
          "ConntrackLocal": "Disabled",
          "Debug": "Disabled",
          "DebugLB": "Disabled",
          "DebugPolicy": "Disabled",
          "DropNotification": "Enabled",
          "MonitorAggregationLevel": "Medium",
          "PolicyAuditMode": "Enabled",
          "PolicyVerdictNotification": "Enabled",
          "SourceIPVerification": "Enabled",
          "TraceNotification": "Enabled"
        }
      },
      "state": "ready"
    }
  }
]
  ```
</details>

And then after the switch to `default deny`, I've tried to obtain endpoint details once more, but I got an error:
```
Error: Failed to decode nested JSON: invalid character 'M' looking for beginning of object key string (
{MatchLabels:map[string]string{},MatchExpressions:[]LabelSelectorRequirement{},}
)
```

So, I had to use curl to obtain endpoint details with `curl --unix-socket /var/run/cilium/cilium.sock http://localhost/v1/endpoint/519`:
<details>
  <summary>Show/Hide</summary>
 
  ```json
{
  "id": 519,
  "spec": {
    "label-configuration": {},
    "options": {
      "ConntrackAccounting": "Enabled",
      "ConntrackLocal": "Disabled",
      "Debug": "Disabled",
      "DebugLB": "Disabled",
      "DebugPolicy": "Disabled",
      "DropNotification": "Enabled",
      "MonitorAggregationLevel": "Medium",
      "PolicyAuditMode": "Enabled",
      "PolicyVerdictNotification": "Enabled",
      "SourceIPVerification": "Enabled",
      "TraceNotification": "Enabled"
    }
  },
  "status": {
    "controllers": [
      {
        "configuration": {
          "error-retry": true,
          "error-retry-base": "2s"
        },
        "name": "endpoint-519-regeneration-recovery",
        "status": {
          "last-failure-timestamp": "0001-01-01T00:00:00.000Z",
          "last-success-timestamp": "0001-01-01T00:00:00.000Z"
        },
        "uuid": "e2b2e633-d5c3-4c2a-9d80-f37947d7d73b"
      },
      {
        "configuration": {
          "error-retry": true,
          "interval": "5m0s"
        },
        "name": "resolve-identity-519",
        "status": {
          "last-failure-timestamp": "0001-01-01T00:00:00.000Z",
          "last-success-timestamp": "2023-12-30T09:22:33.422Z",
          "success-count": 114
        },
        "uuid": "cbeff185-e3a8-4e3b-869c-e26b26191a88"
      },
      {
        "configuration": {
          "error-retry": true,
          "interval": "10s"
        },
        "name": "sync-to-k8s-ciliumendpoint (519)",
        "status": {
          "last-failure-timestamp": "0001-01-01T00:00:00.000Z",
          "last-success-timestamp": "2023-12-30T09:25:55.945Z",
          "success-count": 3412
        },
        "uuid": "37d3cbe5-989b-4d5f-9e03-fd5dfe8e3fb2"
      }
    ],
    "external-identifiers": {
      "pod-name": "/"
    },
    "health": {
      "bpf": "OK",
      "connected": true,
      "overallHealth": "OK",
      "policy": "OK"
    },
    "identity": {
      "id": 8,
      "labels": [
        "reserved:ingress"
      ]
    },
    "labels": {
      "derived": [
        "reserved:ingress"
      ],
      "realized": {},
      "security-relevant": [
        "reserved:ingress"
      ]
    },
    "log": [
      {
        "code": "OK",
        "message": "Successfully regenerated endpoint program (Reason: policy rules added)",
        "state": "ready",
        "timestamp": "2023-12-30T09:09:50Z"
      }
    ],
    "networking": {
      "addressing": [
        {
          "ipv4": "10.244.6.214"
        }
      ]
    },
    "policy": {
      "proxy-statistics": [],
      "realized": {
        "allowed-egress-identities": null,
        "allowed-ingress-identities": null,
        "build": 81,
        "denied-egress-identities": null,
        "denied-ingress-identities": null,
        "id": 8,
        "l4": {
          "egress": [
            {
              "derived-from-rules": [
                [
                  "k8s:io.cilium.k8s.policy.derived-from=CiliumClusterwideNetworkPolicy",
                  "k8s:io.cilium.k8s.policy.name=allow-icmp-echo-requests",
                  "k8s:io.cilium.k8s.policy.uid=0862cc33-463e-4ce2-a0bb-8fedef061b97"
                ]
              ],
              "rule": "{\"port\":8,\"protocol\":\"ICMP\",\"l7-rules\":[{\"\\u0026LabelSelector{MatchLabels:map[string]string{},MatchExpressions:[]LabelSelectorRequirement{},}\":null}]}"
            },
            {
              "derived-from-rules": [
                [
                  "k8s:io.cilium.k8s.policy.derived-from=CiliumClusterwideNetworkPolicy",
                  "k8s:io.cilium.k8s.policy.name=allow-icmp-echo-requests",
                  "k8s:io.cilium.k8s.policy.uid=0862cc33-463e-4ce2-a0bb-8fedef061b97"
                ]
              ],
              "rule": "{\"port\":128,\"protocol\":\"ICMPV6\",\"l7-rules\":[{\"\\u0026LabelSelector{MatchLabels:map[string]string{},MatchExpressions:[]LabelSelectorRequirement{},}\":null}]}"
            }
          ],
          "ingress": [
            {
              "derived-from-rules": [
                [
                  "k8s:io.cilium.k8s.policy.derived-from=CiliumClusterwideNetworkPolicy",
                  "k8s:io.cilium.k8s.policy.name=allow-icmp-echo-requests",
                  "k8s:io.cilium.k8s.policy.uid=0862cc33-463e-4ce2-a0bb-8fedef061b97"
                ]
              ],
              "rule": "{\"port\":8,\"protocol\":\"ICMP\",\"l7-rules\":[{\"\\u0026LabelSelector{MatchLabels:map[string]string{},MatchExpressions:[]LabelSelectorRequirement{},}\":null}]}",
              "rules-by-selector": {
                "&LabelSelector{MatchLabels:map[string]string{},MatchExpressions:[]LabelSelectorRequirement{},}": [
                  [
                    "k8s:io.cilium.k8s.policy.derived-from=CiliumClusterwideNetworkPolicy",
                    "k8s:io.cilium.k8s.policy.name=allow-icmp-echo-requests",
                    "k8s:io.cilium.k8s.policy.uid=0862cc33-463e-4ce2-a0bb-8fedef061b97"
                  ]
                ]
              }
            },
            {
              "derived-from-rules": [
                [
                  "k8s:io.cilium.k8s.policy.derived-from=CiliumClusterwideNetworkPolicy",
                  "k8s:io.cilium.k8s.policy.name=allow-icmp-echo-requests",
                  "k8s:io.cilium.k8s.policy.uid=0862cc33-463e-4ce2-a0bb-8fedef061b97"
                ]
              ],
              "rule": "{\"port\":128,\"protocol\":\"ICMPV6\",\"l7-rules\":[{\"\\u0026LabelSelector{MatchLabels:map[string]string{},MatchExpressions:[]LabelSelectorRequirement{},}\":null}]}",
              "rules-by-selector": {
                "&LabelSelector{MatchLabels:map[string]string{},MatchExpressions:[]LabelSelectorRequirement{},}": [
                  [
                    "k8s:io.cilium.k8s.policy.derived-from=CiliumClusterwideNetworkPolicy",
                    "k8s:io.cilium.k8s.policy.name=allow-icmp-echo-requests",
                    "k8s:io.cilium.k8s.policy.uid=0862cc33-463e-4ce2-a0bb-8fedef061b97"
                  ]
                ]
              }
            }
          ]
        },
        "policy-enabled": "audit-both",
        "policy-revision": 81
      },
      "spec": {
        "allowed-egress-identities": null,
        "allowed-ingress-identities": null,
        "build": 81,
        "denied-egress-identities": null,
        "denied-ingress-identities": null,
        "id": 8,
        "l4": {
          "egress": [
            {
              "derived-from-rules": [
                [
                  "k8s:io.cilium.k8s.policy.derived-from=CiliumClusterwideNetworkPolicy",
                  "k8s:io.cilium.k8s.policy.name=allow-icmp-echo-requests",
                  "k8s:io.cilium.k8s.policy.uid=0862cc33-463e-4ce2-a0bb-8fedef061b97"
                ]
              ],
              "rule": "{\"port\":8,\"protocol\":\"ICMP\",\"l7-rules\":[{\"\\u0026LabelSelector{MatchLabels:map[string]string{},MatchExpressions:[]LabelSelectorRequirement{},}\":null}]}"
            },
            {
              "derived-from-rules": [
                [
                  "k8s:io.cilium.k8s.policy.derived-from=CiliumClusterwideNetworkPolicy",
                  "k8s:io.cilium.k8s.policy.name=allow-icmp-echo-requests",
                  "k8s:io.cilium.k8s.policy.uid=0862cc33-463e-4ce2-a0bb-8fedef061b97"
                ]
              ],
              "rule": "{\"port\":128,\"protocol\":\"ICMPV6\",\"l7-rules\":[{\"\\u0026LabelSelector{MatchLabels:map[string]string{},MatchExpressions:[]LabelSelectorRequirement{},}\":null}]}"
            }
          ],
          "ingress": [
            {
              "derived-from-rules": [
                [
                  "k8s:io.cilium.k8s.policy.derived-from=CiliumClusterwideNetworkPolicy",
                  "k8s:io.cilium.k8s.policy.name=allow-icmp-echo-requests",
                  "k8s:io.cilium.k8s.policy.uid=0862cc33-463e-4ce2-a0bb-8fedef061b97"
                ]
              ],
              "rule": "{\"port\":8,\"protocol\":\"ICMP\",\"l7-rules\":[{\"\\u0026LabelSelector{MatchLabels:map[string]string{},MatchExpressions:[]LabelSelectorRequirement{},}\":null}]}",
              "rules-by-selector": {
                "&LabelSelector{MatchLabels:map[string]string{},MatchExpressions:[]LabelSelectorRequirement{},}": [
                  [
                    "k8s:io.cilium.k8s.policy.derived-from=CiliumClusterwideNetworkPolicy",
                    "k8s:io.cilium.k8s.policy.name=allow-icmp-echo-requests",
                    "k8s:io.cilium.k8s.policy.uid=0862cc33-463e-4ce2-a0bb-8fedef061b97"
                  ]
                ]
              }
            },
            {
              "derived-from-rules": [
                [
                  "k8s:io.cilium.k8s.policy.derived-from=CiliumClusterwideNetworkPolicy",
                  "k8s:io.cilium.k8s.policy.name=allow-icmp-echo-requests",
                  "k8s:io.cilium.k8s.policy.uid=0862cc33-463e-4ce2-a0bb-8fedef061b97"
                ]
              ],
              "rule": "{\"port\":128,\"protocol\":\"ICMPV6\",\"l7-rules\":[{\"\\u0026LabelSelector{MatchLabels:map[string]string{},MatchExpressions:[]LabelSelectorRequirement{},}\":null}]}",
              "rules-by-selector": {
                "&LabelSelector{MatchLabels:map[string]string{},MatchExpressions:[]LabelSelectorRequirement{},}": [
                  [
                    "k8s:io.cilium.k8s.policy.derived-from=CiliumClusterwideNetworkPolicy",
                    "k8s:io.cilium.k8s.policy.name=allow-icmp-echo-requests",
                    "k8s:io.cilium.k8s.policy.uid=0862cc33-463e-4ce2-a0bb-8fedef061b97"
                  ]
                ]
              }
            }
          ]
        },
        "policy-enabled": "audit-both",
        "policy-revision": 81
      }
    },
    "realized": {
      "label-configuration": {},
      "options": {
        "ConntrackAccounting": "Enabled",
        "ConntrackLocal": "Disabled",
        "Debug": "Disabled",
        "DebugLB": "Disabled",
        "DebugPolicy": "Disabled",
        "DropNotification": "Enabled",
        "MonitorAggregationLevel": "Medium",
        "PolicyAuditMode": "Enabled",
        "PolicyVerdictNotification": "Enabled",
        "SourceIPVerification": "Enabled",
        "TraceNotification": "Enabled"
      }
    },
    "state": "ready"
  }
}
  ```
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adippl** [comment]
I'm having similar issue. 
Upgrade from 1.14.4 to 1.14.5 breaks ingress despite audit mode being enabled.

I'm running cilium on single node test cluster. 
OS: gentoo
Kernel: 6.1.69-gentoo-dist
kubernetes 1.28.2

my helm values
```
cluster:
  name: kubernetes
kubeProxyReplacement: true
k8sServiceHost: 10.0.5.90
k8sServicePort: 6443
operator:
  replicas: 1
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
tunnel: vxlan
encryption:
  enabled: true
  type: wireguard
hubble:
  peerService:
    clusterDomain: REMOVED
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      className: "cilium"
      hosts:
        - REMOVED
      labels: {}
      tls: 
       - secretName: REMOVED
         hosts:
           - REMOVED
ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
ipam:
  mode: "cluster-pool"
  ciliumNodeUpdateRate: "15s"
  operator:
    clusterPoolIPv4PodCIDRList: ["10.206.0.0/16"]
    clusterPoolIPv4MaskSize: 24
ipv4:
  enabled: true
ipv6:
  enabled: false
hostFirewall:
extraConfig:
hostServices:
  enabled: true
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true
```

**Comment by adippl** [comment]
issue is also present on cilium 1.15.0-rc.0

**Comment by rauanmayemir** [comment]
I’m surprised people haven’t been experiencing this before, I’ve been seing this for a while now: #28254.

**Comment by hwaastad** [comment]
Hi, came upon this issue my self.
My setup is
Following CCNP default-deny
```
spec:
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: '53'
              protocol: UDP
          rules:
            dns:
              - matchPattern: '*'
  endpointSelector:
    matchExpressions:
      - key: io.kubernetes.pod.namespace
        operator: NotIn
        values:
          - kube-system
          -
```

And then I have a haproxy-ingress and a gateway httproute

CNP for ingress:
```
endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: <ingress-namespace>      
```

CNP for gateway (shared):
```
  endpointSelector: {}
  ingress:
    - fromEntities:
        - ingress
```

For <= 1.14.4 all is OK
For 1.14.5, gateway/envoy is failing with 403 Access Denied, ingress still OK.

**Comment by squeed** [comment]
@jrajahalme -- could you take a look at this? It seems like the backport of https://github.com/cilium/cilium/pull/28126 may have caused a regression.

**Comment by rauanmayemir** [comment]
This is also the case on `v1.15.0`. (my yesterday attempt to upgrade lead to a disaster and an all-out outage)
I even tried to disable host firewall and unset policy changes (i.e use helm default), the issue still persisted.

Also, `cilium-envoy` was flooded with this message:

```
cilium.bpf_metadata: IPv4 conntrack map global lookup failed: Success
```

**Comment by gadiener** [comment]
Same issue on v1.15.0 and I also see `cilium.bpf_metadata: IPv4 conntrack map global lookup failed: Success` in the envoy logs

**Comment by adippl** [comment]
Issue exists on 1.14.7 and 1.15.1

**Comment by adippl** [comment]
Longer version of log generated while trying to curl ingress service.
```
level=info msg="[cilium.bpf_metadata: IPv4 conntrack map global lookup failed: No such file or directory" subsys=envoy-filter threadID=67
level=warning msg="[cilium.bpf_metadata (egress): No policy found for 10.206.0.16" subsys=envoy-config threadID=67
level=warning msg="[[C81] cilium.network: Cilium Socket Option not found" subsys=envoy-filter threadID=67
level=info msg="Envoy: Accepted access log connection" subsys=envoy-manager
level=info msg="Envoy: Closing access log connection" subsys=envoy-manager
level=warning msg="[cilium.l7policy: Cilium Socket Option not found" subsys=envoy-filter threadID=67
```

`cilium monitor -t policy-verdict` doesn't show any denied connections.

curl output
```
* IPv6: (none)
* IPv4: 10.0.5.68
*   Trying 10.0.5.68:443...
* Connected to grafana.k8s3.REMOVED (10.0.5.68) port 443
* ALPN: curl offers http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [6 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [3989 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / RSASSA-PSS
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=grafana.k8s3.REMOVED
*  start date: Jan  6 15:43:55 2024 GMT
*  expire date: Apr  5 15:43:54 2024 GMT
*  subjectAltName: host "grafana.k8s3.REMOVED" matched cert's "grafana.k8s3.REMOVED"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
* using HTTP/1.x
} [5 bytes data]
> GET / HTTP/1.1
> Host: grafana.k8s3.REMOVED
> User-Agent: curl/8.5.0
> Accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [230 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [230 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
< HTTP/1.1 500 Internal Server Error
< date: Mon, 19 Feb 2024 14:58:07 GMT
< server: envoy
< content-length: 0
< 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host grafana.k8s3.REMOVED left intact

```


These config options don't seem to matter because disabling them doesn't change the outcome.
```
hostFirewall:
  enabled: true
extraConfig:
  allow-localhost: policy
```

Could this issue be related to this commit? d59aadc1def642694b461ae51fcfe3ce29ca6bc9

**Comment by youngnick** [comment]
Okay, for _some_ of these cases, I think that we may be having a similar issue to #28254, where traffic _from_ the recently introduced `ingress` identity _to_ the Service IPs is not being allowed, because the default deny is catching it.

When I replicated this scenario locally in a kind cluster, this CCNP resolved the issue:

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-ingress-to-cluster
  namespace: default
spec:
  endpointSelector:
    matchExpressions:
    - key: reserved:ingress
      operator: Exists
  egress:
  - toEntities:
    - cluster
```

Could I ask that the folks affected here try this and see if it fixes their issue?

However, I'm not sure about the interaction between `policyEnforcementMode: always` and `policyAuditMode=true,`, so I'm not sure if this will also fix the initial cause of this issue. But hopefully this should help us get closer if we can see what happens.

Thanks!

**Comment by hwaastad** [comment]
> Okay, for _some_ of these cases, I think that we may be having a similar issue to #28254, where traffic _from_ the recently introduced `ingress` identity _to_ the Service IPs is not being allowed, because the default deny is catching it.
> 
> When I replicated this scenario locally in a kind cluster, this CCNP resolved the issue:
> 
> ```yaml
> apiVersion: "cilium.io/v2"
> kind: CiliumClusterwideNetworkPolicy
> metadata:
>   name: allow-ingress-to-cluster
>   namespace: default
> spec:
>   endpointSelector:
>     matchExpressions:
>     - key: reserved:ingress
>       operator: Exists
>   egress:
>   - toEntities:
>     - cluster
> ```
> 
> Could I ask that the folks affected here try this and see if it fixes their issue?
> 
> However, I'm not sure about the interaction between `policyEnforcementMode: always` and `policyAuditMode=true,`, so I'm not sure if this will also fix the initial cause of this issue. But hopefully this should help us get closer if we can see what happens.
> 
> Thanks!
> 
> Edit: Although we are allowing to `cluster` in this policy, and not `world`, even though the Hubble flow above _says_ world, the L7 filtering actually chooses a backend _first_, then makes a policy decision. But that isn't reflected correctly in Hubble, which still thinks that the flow is going to the _VIP_, which will be a non-cluster address. So this is why the above Policy can work.

Hmm, my inital testing (on cilium 1.15.1) does'nt seem to work. I cannot see any drops in hubble. I will continue testing.

/hw

**Comment by adippl** [comment]
I've just tried to update my cluster to 1.15.2 without success.

using this ccnp doesn't help. 
Ingress doesn't work, there are no drops in hubble. 

I have this in my logs
```
-> Request http from 0 ([reserved:ingress]) to 0 ([reserved:world]), identity 8->2, verdict Denied GET https://app.REMOVED/ => 0
-> Response http to 0 ([reserved:ingress]) from 0 ([reserved:world]), identity 2->8, verdict Forwarded GET https://app.REMOVED/ => 403
```

**Comment by youngnick** [comment]
@adippl, as I said above, this is because the ingress identity is now used as a _source identity_ when the flows get to Envoy, so if there is no network policy to allow the ingress identity to get to the endpoint, then traffic will be 403d.

The lines you've posted look like drops in Hubble to me. On 1.15.2, the first flow is being Denied, and then the second flow shows the 403 occcuring. Note that the identity is now `world`, which as far as Cilium is concerned means "outside the cluster's network", so without something to tell Cilium more about those addresses, the deny-all policy will block this traffic.

**Comment by hwaastad** [comment]
Hi, at least for my situation, I needed to exclude ingress identity from default-deny.
```
endpointSelector:
  matchExpressions:
    - key: io.kubernetes.pod.namespace
       operator: NotIn
       values:
         - kube-system
         - ...
    - key: ingress
       operator: DoesNotExist
```

**Comment by rauanmayemir** [comment]
@hwaastad Can you share your `default-deny` ccnp/cnp?

**Comment by hwaastad** [comment]
@rauanmayemir probably bad policy to update history, but anyways, added som more info to my previous example.

**Comment by youngnick** [comment]
Folks, it seems like we've got this relatively nailed down as being mainly centred on the new `ingress` identity. Are there any other changes to the docs you'd like to see? If so, what are they? If not, we may be able to close this one out?

**Comment by rauanmayemir** [comment]
I'm planning a [potentially] painful upgrade in a week or two, will check if this resolves my previous issue.

**Comment by 0xalex88** [comment]
Just trying out cilium on eks 1.29 with policyEnforcementMode=always and I've encountered the same issue

```
May  3 21:01:52.883: 10.0.30.107:20148 (ingress) -> kube-system/cilium-ingress:31849 (world) http-request DROPPED (HTTP/1.1 GET http://xxx.us-west-2.elb.amazonaws.com/subgraphs/)
May  3 21:01:52.883: 10.0.30.107:20148 (ingress) <- kube-system/cilium-ingress:31849 (world) http-response FORWARDED (HTTP/1.1 403 0ms (GET http://xxx.us-west-2.elb.amazonaws.com/subgraphs/))
```

These are the cluster policies I have in place
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: kube-system
  namespace: kube-system
spec:
  description: Allow kube-system endpoints to connect anywhere and receive 
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - {}
    - fromEntities:
        - cluster
    - fromEntities:
        - world
  egress:
    - toEntities:
        - cluster
    - toEntities:
        - world
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: kube-dns-cluster-ingress
spec:
  description: Policy for ingress allow to kube-dns from all Cilium managed endpoints in the cluster
  endpointSelector:
    matchLabels:
      k8s:io.kubernetes.pod.namespace: kube-system
      k8s-app: kube-dns
  ingress:
  - fromEndpoints:
    - {}
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: kube-dns-cluster-egress
spec:
  description: Policy for egress allow to kube-dns from all Cilium managed endpoints in the cluster
  endpointSelector: {}
  egress:
  - toEndpoints:
      - matchLabels:
          io.kubernetes.pod.namespace: kube-system
          k8s-app: kube-dns
    toPorts:
      - ports:
          - port: "53"
            protocol: UDP
        rules:
          dns:
            - matchPattern: "*"
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: cilium-health-checks-cluster-ingress
spec:
  endpointSelector:
    matchLabels:
      'reserved:health': ''
  ingress:
    - fromEntities:
      - remote-node
  egress:
    - toEntities:
      - remote-node
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-ingress-to-cluster
spec:
  endpointSelector:
    matchExpressions:
      - key: reserved:ingress
        operator: Exists
  egress:
    - toEntities:
      - cluster
```

the last one being the one from this issue. Also the app that has the ingress that's trying to be reached has
```
        - fromEntities:
            - world
            - ingress
```

In this case it seems that the ingress entity is trying to connect to the kube-system/cilium-ingress endpoint (that I don't see with `kubectl get cep`)

**Comment by 0xalex88** [comment]
Fixed it by changing the suggested ingress policy to
```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-ingress-egress
spec:
  endpointSelector:
    matchExpressions:
    - key: reserved:ingress
      operator: Exists
  ingress:
    - fromEntities:
        - world
  egress:
    - toEntities:
      - cluster
```
is this the right thing to do?

I think in the doc would be nice to show a somehow "hardened" setup with a deny all by default, that allows core components like dns/hubble/kubernetes-api/ingresses to be functioning and shows an example on how to expose a service in another namespace to the world with an ingress
