### ISSUE TITLE
Error using multiple allowRoutes namespaces in Gateway

### ISSUE THREAD

**Issue by acelinkio** [cilium/cilium#30085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When creating a gateway with multiple listeners, there is an issue when sections use different allowedRoutes configurations.  The section allowing routes from all namespaces is not honored and receive a `NotAllowedByListeners` status.

One of the sections is setup to allowRoutes from the same namespace and the other section should allow all. 
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: cilium-gateway
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    name: http
    allowedRoutes:
      kinds:
        - kind: HTTPRoute
      namespaces:
        from: Same
  - protocol: HTTPS
    port: 443
    name: https
    tls:
      certificateRefs:
      - kind: Secret
        name: wildcard-production
        namespace: cilium-secrets
    allowedRoutes:
      namespaces:
        from: All
```

Then create a redirect HTTPRoute for the http listener
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: httpsredirect-internalgw
  namespace: cilium-gateway
spec:
  parentRefs:
    - name: internal
      namespace: cilium-gateway
      sectionName: http
  rules:
    - filters:
        - requestRedirect:
            scheme: https
            statusCode: 301
          type: RequestRedirect
```

And another HTTPRoute for the HTTPS listener in another namespace
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: httpbin
  namespace: test-zone
spec:
  parentRefs:
  - name: internal
    namespace: cilium-gateway
    sectionName: https
  hostnames:
  - "httpbin.test.tld"
  rules:
  - backendRefs:
    - name: httpbin
      port: 80
```

The httpbin HTTPRoute then returns
```
status:
  parents:
    - conditions:
        - lastTransitionTime: '2024-01-02T17:58:26Z'
          message: >-
            HTTPRoute is not allowed to attach to this Gateway due to namespace
            restrictions
          observedGeneration: 1
          reason: NotAllowedByListeners
          status: 'False'
          type: Accepted
        - lastTransitionTime: '2024-01-01T16:30:55Z'
          message: Service reference is valid
          observedGeneration: 1
          reason: ResolvedRefs
          status: 'True'
          type: ResolvedRefs
      controllerName: io.cilium/gateway-controller
      parentRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        name: internal
        namespace: cilium-gateway
        sectionName: https
```

### Cilium Version

1.15.0-rc.0

### Kernel Version

```
uname -a
Linux rockchip1 5.10.160-rockchip #21 SMP Mon Nov 20 00:36:42 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

### Kubernetes Version

1.29.0+k3s1

### Anything else?

Gateway Custom Resource Definition https://github.com/kubernetes-sigs/gateway-api/blob/v1.0.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chaunceyjiang** [comment]
```
    allowedRoutes:
      kinds:
        - kind: HTTPRoute
      namespaces:
        from: Same               # It seems to be because you set the Same parameter?

```

**Comment by acelinkio** [comment]
The gateway spec is designed to allow that to be set per listener. 

In my example, I set the http listener to Same and the https listener to All
```
spec.listeners[0].allowedRoutes.namespaces.from = Same       #http
spec.listeners[1].allowedRoutes.namespaces.from = All        #https
```

Then the HTTPRoutes selects which listener to attach to via sectionName.
```
spec:
  parentRefs:
  - name: internal
    namespace: cilium-gateway
    sectionName: https
```

**Comment by acelinkio** [comment]
I am changing two gateways in my commit.  That's why there are two instances of Same being changed in my reference commits.

Retested and confirmed that the HTTPRoutes are getting `NotAllowedByListeners` error.

**Comment by chaunceyjiang** [comment]
Can you test this case for me? Put HTTPS before HTTP.
@acelinkio 
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: cilium-gateway
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTPS
    port: 443
    name: https
    tls:
      certificateRefs:
      - kind: Secret
        name: wildcard-production
        namespace: cilium-secrets
    allowedRoutes:
      namespaces:
        from: All
  - protocol: HTTP
    port: 80
    name: http
    allowedRoutes:
      kinds:
        - kind: HTTPRoute
      namespaces:
        from: Same


```

**Comment by chaunceyjiang** [comment]
Yes. you are right! @acelinkio 
```
│ status:                                                                                                                                                                        │
│   parents:                                                                                                                                                                     │
│   - conditions:                                                                                                                                                                │
│     - lastTransitionTime: "2024-01-04T06:47:30Z"                                                                                                                               │
│       message: HTTPRoute is not allowed to attach to this Gateway due to namespace                                                                                             │
│         restrictions                                                                                                                                                           │
│       observedGeneration: 1                                                                                                                                                    │
│       reason: NotAllowedByListeners                                                                                                                                            │
│       status: "False"                                                                                                                                                          │
│       type: Accepted                                                                                                                                                           │
│     - lastTransitionTime: "2024-01-04T06:47:30Z"                                                                                                                               │
│       message: Service reference is valid                                                                                                                                      │
│       observedGeneration: 1                                                                                                                                                    │
│       reason: ResolvedRefs                                                                                                                                                     │
│       status: "True"                                                                                                                                                           │
│       type: ResolvedRefs                                                                                                                                                       │
│     controllerName: io.cilium/gateway-controller
```
I can reproduce this issue.

**Comment by chaunceyjiang** [comment]
I will try to fix this issue.

**Comment by chaunceyjiang** [comment]
Hi @acelinkio 
Can you help test this patch #30100? 

I've self-tested and it seems to be working normally.
``` yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: header-http-echo
  namespace: kube-system
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cilium-gw
    namespace: default
    sectionName: web-gw-echo2
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: echo-2
      port: 8090
      weight: 1
    filters:
    - requestHeaderModifier:
        add:
        - name: my-header-name-all
          value: my-header-value-all
      type: RequestHeaderModifier
    matches:
    - path:
        type: PathPrefix
        value: /add-a-request-header
status:
  parents:
  - conditions:
    - lastTransitionTime: "2024-01-04T09:34:00Z"
      message: Accepted HTTPRoute
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-01-04T06:47:30Z"
      message: Service reference is valid
      observedGeneration: 1
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    controllerName: io.cilium/gateway-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: cilium-gw
      namespace: default
      sectionName: web-gw-echo2
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  creationTimestamp: "2024-01-03T14:16:01Z"
  generation: 4
  name: cilium-gw
  namespace: default
spec:
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: web-gw-echo
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: All
    name: web-gw-echo2
    port: 8080
    protocol: HTTP
```
