### ISSUE TITLE
Hubble metrics' "httpV2:exemplars=true;" does not work.

### ISSUE THREAD

**Issue by devkoriel** [cilium/cilium#30099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In Cilium 1.13.x, when I enabled hubble metrics like below,
```
metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flows-to-world
      - port-distribution
      - icmp
      - "flow:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      - "kafka:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
    enableOpenMetrics: true
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus
```

I could see the OpenMetrics-formatted metrics including traceid in hubble-metrics service. However, after upgrading to 1.14.5, traceID isn't being found in it so that not being able to visualize exemplars in Grafana dashboards.

## Local

```
cilium-cli: v0.15.11-25-ge33d2c51 compiled with go1.21.3 on darwin/arm64
cilium image (default): v1.14.3
cilium image (stable): v1.14.5
cilium image (running): 1.14.5
```

## Remote

```
Client: 1.14.5 85db28be 2023-12-11T14:30:29+01:00 go version go1.20.12 linux/amd64
Daemon: 1.14.5 85db28be 2023-12-11T14:30:29+01:00 go version go1.20.12 linux/amd64
```

### Kernel Version

`Linux ip-10-133-52-162 5.10.0-26-cloud-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

```
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4
```

### Relevant log output

```shell
Nothing I've got. Especially related to exemplars-included metrics.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
