### ISSUE TITLE
CFP: SPIRE Helm Chart

### ISSUE THREAD

**Issue by kfox1111** [cilium/cilium#30106]
## Cilium Feature Proposal
        
When the Cilium chart gained SPIRE support, there wasn't really an upstream Helm chart.

There is one now (https://github.com/spiffe/helm-charts-hardened) and it might simplify both parties maintenance if we could embed the upstream SPIRE chart into the Cilium chart. This would also make all the advanced configuration options from the SPIRE chart available to Cilium users (different upstream drivers, tpm support, easy federation config, etc) without having to reimplement that functionality into the Cilium chart directly.

**Comment by ishuar** [comment]
If this is decided to have a feature, I would be happy to contribute.

What I have understood is that if we proceed, then basically cilium chat needs an dependency in `chart.yaml` , `values .yaml` file adjustments accordingly as per the upstream chart and cleanup up current spire resources from the existing chart.

**Comment by kfox1111** [comment]
Are there any features that the upstream chart doesn't have that are needed by Cilium?

Was looking into support for the admin api socket for the spire-agent and saw it was needed by Cilium. Anything else still needed?

**Comment by sayboras** [comment]
> Anything else still needed?

Basically, the upstream chart offers some other the components that might not be related to Cilium, we only need barebone spire server and spire agent.

Another main point is to have the ability to bootstrap Cilium related identities via init script directly (but not via crds).

https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/files/spire/init.bash

**Comment by sayboras** [comment]
> Looks like its running as a sidecar to the server? We support extraContainers specified on the server, so I think that would work for loading the init script.

IIRC, we might need `shareProcessNamespace` flag enabled for init container.

> Looks like we also would need [admin_ids](https://github.com/cilium/cilium/blob/v1.15.1/install/kubernetes/cilium/templates/spire/server/configmap.yaml#L28)

yes, the IDs should match with what was initialized in the script.

> Do you know why [use_token_review_api_validation=true](https://github.com/cilium/cilium/blob/v1.15.1/install/kubernetes/cilium/templates/spire/server/configmap.yaml#L45)

Good point, I don't think it's required, but need to test it out.

**Comment by kfox1111** [comment]
shareProcessNamespace is true already in the chart so that's covered.

We just merged spire server support for admin_ids and agent support for authorized_delegates

So if the use_token_review_api_validation=true isn't needed, I think it should be usable by the next release.

**Comment by ishuar** [comment]
@sayboras please assign it to me if it's available to workup on.
-  [issuecomment](https://github.com/cilium/cilium/issues/30106#issuecomment-1890807772)

**Comment by sayboras** [comment]
Thanks for your interest working on this issue, the current CI should provide enough coverage IMO.

**Comment by ishuar** [comment]
@sayboras and @kfox1111 , by any chance is this a blocker??

upstream Spire chart requires [`kubeVersion: ">=1.21.0-0"`](https://github.com/spiffe/helm-charts-hardened/blob/main/charts/spire/Chart.yaml#L23C1-L23C26) but Cillium chart has [`kubeVersion: ">= 1.16.0-0"`](https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/Chart.yaml#L7C1-L7C27) requirements. 

Won't adding SPIRE upstream chart creates a dependency on `kubeVersion: ">=1.21.0-0"`?

**Comment by kfox1111** [comment]
We used to support older. I think we bumped up the minimum requirements when we added ingress support so we didn't have to conditional the:
```
apiVersion: networking.k8s.io/v1
```

As its 1.21+.

So it may not require much work to support older again if that is desirable.

**Comment by sayboras** [comment]
> Cillium chart has [kubeVersion: ">= 1.16.0-0"](https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/Chart.yaml#L7C1-L7C27) requirements.

I don't think it's the blocker

**Comment by ishuar** [comment]
> I don't think it's the blocker. The reason of having 1.16 in chart.yaml is just to run old CI jobs.

so if I understood it right, it's safe to keep the same dependency on `kubeversion` i.e. `>=1.21.0` in the Cillium chart as well?

**Comment by sayboras** [comment]
Historically, we need to keep it with 1.16 for old CI jobs, however, we actually bump the k8s versions in CI recently. I need to check if there is any left over hanging around, will get back to you on this.

From the end user perspective, it will not have any impact imo.

**Comment by sayboras** [comment]
Just a note that I have bumped the k8s version in main branch to 1.21+

**Comment by ishuar** [comment]
Unfortunately, it's taking longer than expected due to  personal matters and my availability is very  limited. 😞

**Comment by kfox1111** [comment]
No worries. If there is anything I can do to help, please let me know.

**Comment by ishuar** [comment]
Thank you @kfox1111  

While working on https://github.com/cilium/cilium/pull/32716, I'm unsure how to introduce this container since the upstream chart does not support such a container configuration.
- Relevant file: https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/spire/server/statefulset.yaml#L45-L53

Additionally, I have uncertainties about this section: [link](https://github.com/cilium/cilium/pull/32716/files#diff-0ea42ad21164b19bec1732225e254d3096d1e4040481c00053669287d81015feR3445-R3452)


Please feel free to share any other feedback 😇

**Comment by kfox1111** [comment]
Hi @ishuar,

Interesting. It looks like its injecting a script to configure the entries in the spire db. We might be able to add a feature to do that. But, there is another feature already in the chart that may be a nicer fit.

The chart uses the spire-controller-manager out of the box, so all the entries can be dynamically managed via Kubernetes CR's. It can even create them as part of the chart: https://spiffe.io/docs/latest/spire-helm-charts-hardened-about/identifiers/

maybe some config like:
```
spire-server:
  controllerManager:
    identities:
      clusterSPIFFEIDs:
        cilium-agent:
          spiffeIDTemplate: spiffe://{{ .TrustDomain }}/cilium-agent
          namespaceSelector:
            matchExpressions:
            - key: "kubernetes.io/metadata.name"
              operator: In
              values: ["cilium-system"]
          podSelector:
            matchLabels:
              app: cilium
              component: agent
```
might work?

**Comment by kfox1111** [comment]
Actually, I thought about this some more....

There are some folks that will want to helm install the spire chart separately from cilium. In that case, we'd need a solution to the integration issue too.

I think the raw spire CR's will work for that case (https://github.com/spiffe/spire-controller-manager/blob/main/docs/clusterspiffeid-crd.md). It will tell spire how to add the entries for cilium.

So, what if we converted the init script to a set of spire CR's in the chart? In both cases, embedded spire and standalone spire, it should be able to receive the config from the cilium chart then and configure it to work with cilium.

**Comment by Brightside56** [comment]
This may contain irrelevant things (like using aws rds/kms or leftovers), but it's working on my testbed with https://github.com/spiffe/helm-charts-hardened/tree/main/charts/spire. Cilium is issuing Cilium identities for mutual auth, workloads are also using SPIRE (via SPIFFE workload API) to issue JWT-SVIDs
```
spire:
  spire-server:
    enabled: true
    adminIDs:
      - spiffe://<some.trust.domain>/ns/cilium/sa/cilium-operator
    replicaCount: 3

    controllerManager:
      enabled: true
      # without this CRs for controller manager are requiring class
      watchClassless: true
      identities:
        clusterSPIFFEIDs:
          default:
            enabled: false

    keyManager:
      awsKMS:
        region: eu-west-1

    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: <some-arn>

    nodeAttestor:
      k8sPSAT:
        enabled: true
        serviceAccountAllowList:
          - spire-system:spire-agent

    dataStore:
      sql:
        databaseType: aws_postgres
        host: <some-rds-host>
        region: eu-west-1
        username: spire
        databaseName: spire
        options:
          - sslmode: require
          - search_path: spire
        maxOpenConns: 100
        maxIdleConns: 2
        connMaxLifetime: 0

    keyManager:
      disk:
        enabled: false
      awsKMS:
        enabled: true
        keyIdentifierValue:
          enabled: true
          identifier: spire-server-key

    dataStorage:
      size: 10Gi

    service:
      type: ClusterIP
      port: 8081

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000

  spiffe-csi-driver:
    enabled: false

  spiffe-oidc-discovery-provider:
    enabled: true
    bundleSource: ConfigMap
    tls:
      spire:
        enabled: false

  spire-agent:
    enabled: true
    # I'm not sure all of these need to be specified
    authorizedDelegates:
      - spiffe://<some.trust.domain>/cilium-agent
      - spiffe://<some.trust.domain>/ns/cilium/sa/cilium
      - spiffe://<some.trust.domain>/ns/cilium/sa/cilium-operator
    server:
      address: spire-server
      port: 8081

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: eks.amazonaws.com/compute-type
              operator: NotIn
              values:
                - fargate

    nodeAttestor:
      k8sPSAT:
        enabled: true

    workloadAttestors:
      k8s:
        enabled: true
      unix:
        enabled: true

    sockets:
      hostBasePath: /run/spire/sockets
      admin:
        enabled: true
        mountOnHost: true
        
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    tolerations:
      - operator: Exists

    podSecurityContext:
      runAsNonRoot: false
      runAsUser: 0

    securityContext:
      privileged: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL

  global:
    spire:
      trustDomain: <some.trust.domain>
      clusterName: <some>
      jwtIssuer: https://spire-server.spire.svc.cluster.local
```
on Cilium's side I have
```
cilium:
            ...
            authentication:
              mutual:
                spire:
                  enabled: true
                  install:
                    enabled: false
                  serverAddress: spire-server.spire-system.svc:8081
                  trustDomain: <some.trust.domain>
                  adminSocketPath: /run/spire/sockets/csi.spiffe.io/admin/admin.sock
                  agentSocketPath: /run/spire/agent-sockets/spire-agent.sock
                  connectionTimeout: 30s
```
Cilium does need mainly:

1. correct socket paths
2. correct trust domain (same as set for SPIRE)
3. adminIDs for SPIRE (in order to allow Cilium manage identities)
