### ISSUE TITLE
EKS Cilium in Overlay with ALB and webhooks: Address is not allowed 

### ISSUE THREAD

**Issue by brianschroeder** [cilium/cilium#30111]
Hello, I am currently running cilium in overlay mode in my EKS cluster.

I am attempting to use an ALB for an ingress and when attempting to create I get the following error:

Error from server (InternalError): error when creating ".\\manifests\\test-deployments.yaml": Internal error occurred: failed calling webhook "vingress.elbv2.k8s.aws": failed to call webhook: Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/validate-networking-v1-ingress?timeout=10s": Address is not allowed

I am using terraform and helm to deploy the deployments

Cilium.tf

```
resource "helm_release" "cilium" {
  count      = var.deploy_cilium ? 1 : 0
  name       = "cilium"
  repository = "https://helm.cilium.io/"
  chart      = "cilium"
  namespace  = "kube-system"
  version    = "1.14.5"
  set {
    name  = "egressMasqueradeInterfaces"
    value = "eth0"
  }
  set {
    name  = "nodeinit.enabled"
    value = "true"
  }

  wait = false

  depends_on = [module.eks, null_resource.add_cilium_repo, null_resource.remove_vpc_cni]
}
```

addon-loadbalancer.tf

```
resource "helm_release" "alb-controller" {
  name       = "aws-load-balancer-controller"
  repository = "https://aws.github.io/eks-charts"
  chart      = "aws-load-balancer-controller"
  namespace  = "kube-system"
  depends_on = [
    kubernetes_service_account.awslb-service-account
  ]

  set {
    name  = "region"
    value = var.aws_region
  }

  set {
    name  = "vpcId"
    value = var.vpc_id
  }

  set {
    name  = "serviceAccount.create"
    value = "false"
  }

  set {
    name  = "serviceAccount.name"
    value = "aws-load-balancer-controller"
  }

  set {
    name  = "clusterName"
    value = "${var.product_area}-${var.environment}${var.aws_region_abbr}-${var.deployment_name}-eks"
  }

  set {
    name  = "hostNetwork"
    value = false
  }
}
```

I did confirm I added the NSG rule for the control plane to talk to the nodes

    ingress_allow_access_from_control_plane = {
      type                          = "ingress"
      protocol                      = "tcp"
      from_port                     = 9443
      to_port                       = 9443
      source_cluster_security_group = true
      description                   = "Allow access from control plane to webhook port of AWS load balancer controller"
    }
    
Ingress yaml:
```
 apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpserver-service
            port:
              number: 80
```

Note: I also tried to use hostNetwork=true for the alb but ran into an issue where the ALB could not speak with the pods over the ENI because cilium is in overlay mode vs chaining. Thanks

### Cilium Version

1.14.5

### Kubernetes Version

1.28

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
