### ISSUE TITLE
Gateway address field not functional

### ISSUE THREAD

**Issue by acelinkio** [cilium/cilium#30123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Gateway API aims to reduce the use of vendor specific annotations and provide a standard for all gateway controllers to honor.  Part of that standard is to allow for the creation of load balancers via Gateway custom resource and assign listening addresses.  Traditionally this has been done via annotations on Kubernetes services, such as `io.cilium/lb-ipam-ips: 192.168.1.50`.  

Cilium does not appear to support assigning addresses via Gateway custom resource.  This was tested via the following:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: cilium-gateway
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    name: http
    allowedRoutes:
      kinds:
        - kind: HTTPRoute
      namespaces:
        from: All
  addresses:
    - type: IPAddress
      value: "192.168.1.50"
```

### Cilium Version

1.15.0-rc.0

### Kernel Version

Linux rockchip2 5.10.160-rockchip #21 SMP Mon Nov 20 00:36:42 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

1.29.0+k3s1

### Anything else?

Gateway Custom Resource Definition on Addresses:
https://github.com/kubernetes-sigs/gateway-api/blob/v1.0.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml#L57-L120

Gateway example for setting addresses:
https://github.com/kubernetes-sigs/gateway-api/blob/v1.0.0/examples/standard/gateway-addresses.yaml

Related issues:
https://github.com/cilium/cilium/issues/25357 - Discussion about Gateway API standard for propagating annotations
https://github.com/cilium/cilium/pull/27636 - Workaround submissions for specifying annotations to child objects

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
