### ISSUE TITLE
CiliumNetworkPolicy: match endpoint by namespace label does not work

### ISSUE THREAD

**Issue by Mugenor** [cilium/cilium#30149]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

I'm using minikube, [hierarchical namespaces](https://github.com/kubernetes-sigs/hierarchical-namespaces) and cilium. I'm trying to make seamless network connectivity between K8S namespaces within the same root namespace. 

To achieve this I mark namespaces with a label (let's say it's tenant=team-a), configure hnc to propagate network policies and create network policy similar to only allow ingress traffic from namespaces with label tenant=team-a  (created using https://editor.networkpolicy.io):
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: tenant-connectivity
  namespace: team-a
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace.labels.tenant: team-a
```

This network policy propagated successfully (it appears and applied to child namespaces), but in the end this network policy blocks traffic between namespaces

If I replace it with similar vanilla network policy, everything works as expected:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tenant-connectivity
  namespace: team-a
spec:
  podSelector:
    matchLabels:
      {}
  policyTypes:
  - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              tenant: team-a
``` 

I've tried to debug it a bit and found out that if I exec into cilium pod and run `cilium policy get` then I get this policy equivalent (namespace is app1 because of propagation done by HNC):
```
{
    "endpointSelector": {
      "matchLabels": {
        "k8s:io.kubernetes.pod.namespace": "app1"
      }
    },
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "any:io.kubernetes.pod.namespace.labels.tenant": "team-a",
              "k8s:io.kubernetes.pod.namespace": "app1"
            }
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "io.cilium.k8s.policy.derived-from",
        "value": "CiliumNetworkPolicy",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.name",
        "value": "tenant-connectivity",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.namespace",
        "value": "app1",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.uid",
        "value": "37a10511-67cd-46a8-b05c-2a77d777d04a",
        "source": "k8s"
      }
    ]
  }
```

If I understand it correctly, cilium implicitly adds label to match pods within the namespace in "fromEndpoints.matchLabels" field and it breaks the filter.

I'm new to cilium, let me know if I'm just using it incorrectly. But I would assume this to work, since I'm trying to use policy provided by network policy editor.

### Cilium Version

```
cilium-cli: v0.15.18 compiled with go1.21.5 on darwin/arm64
cilium image (default): v1.14.4
cilium image (stable): v1.14.5
cilium image (running): 1.14.5
```

### Kernel Version

```
docker@minikube:~$ uname -a
Linux minikube 6.4.16-linuxkit #1 SMP PREEMPT Thu Nov 16 10:49:20 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

```
-> % minikube version
minikube version: v1.32.0
commit: 8220a6eb95f0a4d75f7f2d7b14cef975f050512d
```

### Kubernetes Version

```
-> % kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3
```

### Sysdump

[cilium-sysdump-20240109-133233.zip](https://github.com/cilium/cilium/files/13873161/cilium-sysdump-20240109-133233.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EItanya** [comment]
Hello 👋 

That does seem strange!

Can you get the `cilium policy get` when using the `NetworkPolicy` I'm curious to see the difference, and it could be a good starting point to check the code difference.

**Comment by Mugenor** [comment]
Hello @EItanya 

Thank you for the response.
Here it is:
```
{
    "endpointSelector": {
      "matchLabels": {
        "k8s:io.kubernetes.pod.namespace": "app1"
      }
    },
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "k8s:io.cilium.k8s.namespace.labels.tenant": "team-a"
            }
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "io.cilium.k8s.policy.derived-from",
        "value": "NetworkPolicy",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.name",
        "value": "tenant-connectivity",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.namespace",
        "value": "app1",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.uid",
        "value": "742e08ac-3669-4fca-bbc9-ddeb43e81f36",
        "source": "k8s"
      }
    ]
  }
```

**Comment by EItanya** [comment]
You're definitely right that it's adding an implicit namespace match, lemme see if I can dig around and find something

**Comment by EItanya** [comment]
So this isn't THE answer, but it's definitely what's happening. Here's the offending code.

https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/utils/utils.go#L77-L98

**Comment by EItanya** [comment]
Ok, I have a solution for you, but it may not be the one you want. `CNP` is a namespaced rule, which means that be default it will only allow traffic from the namespace in question. I took your policy and converted it into a `CCNP` and got the result I believe you were looking for.

yaml
```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: tenant-connectivity
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s.io.kubernetes.pod.namespace.labels.tenant: team-a
```

policy from daemon
```
[
  {
    "endpointSelector": {},
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "any:k8s.io.kubernetes.pod.namespace.labels.tenant": "team-a"
            },
            "matchExpressions": [
              {
                "key": "k8s:io.kubernetes.pod.namespace",
                "operator": "Exists"
              }
            ]
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "io.cilium.k8s.policy.derived-from",
        "value": "CiliumClusterwideNetworkPolicy",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.name",
        "value": "tenant-connectivity",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.uid",
        "value": "04b6652f-2777-43d1-be94-78f46001c5fb",
        "source": "k8s"
      }
    ]
  }
]
```

**Comment by Mugenor** [comment]
Using simple NetworkPolicy as a workaround seams more straightforward compared to CCNP, but thank you for the suggestion. 
Or is there a problem with usage of NetworkPolicy that I don't see?

Nevertheless, I would assume CNP to work in a similar way to how NetworkPolicy does and not to add implicit constraints anywhere except `endpointSelector`. 
Plus online editor produces CNP which does not what you would expect.

Do you consider that as a bug that should be fixed?

**Comment by odinuge** [comment]
Hi,

I think the policy you would need to do what you want here is roughly this;

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: tenant-connectivity
  namespace: team-a
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.cilium.k8s.namespace.labels.tenant: team-a
          matchExpressions:
            - key: io.kubernetes.pod.namespace
              operator: Exists

```

It seems like the https://editor.networkpolicy.io/ is wrong about this in general. When selecting pods based on labels on the namespace, the key should be `io.cilium.k8s.namespace.labels.*` not `io.kubernetes.pod.namespace.labels.*`.

Also, as seen in the code [EItanya](https://github.com/EItanya) refer to, you have to have at least one `matchLabels` or `matchExpressions` on the label key `io.kubernetes.pod.namespace` in order to remove the default rule of only selecting endpoints inside the namespace of the `CNP`. So having an expression on `io.kubernetes.pod.namespace` and `Exists`, you will select all pods in the cluster, and then you can add more expressions/matchLabel's to filter down. If this is fully intended behavior on the cilium side is another thing, but its been like this for quite a long time now; but I agree its a bit confusing.

**Comment by squeed** [comment]
@odinuge  / @EItanya nice debugging, thanks.

You are certainly right that this is, at best, totally unintuitive. We should probably remove the implicit namespace match for `io.cilium.k8s.namespace.labels.*` selectors as well.

The question is (maybe @christarazi can chime in): this is theoretically making the policy engine more permissive, and could thus allow traffic that was previously denied. Now, the intent of such a policy is quite clear -- including how our documentation is written. But, we need to be very careful before opening something up unexpectedly.

I'll add this as an agenda item in the [community meeting](https://docs.google.com/document/d/1Y_4chDk4rznD6UgXPlPvn3Dc7l-ZutGajUv1eF0VDwQ/edit).

**Comment by squeed** [comment]
The result of the discussion was that - in this case - the user intent is quite clear, and the chances of this somehow enabling traffic that was not intended is minimal. So, we should add the special case for `io.cilium.k8s.namespace.labels.*` and, when a selector is present with this prefix, not add an explicit namespace name selector.

Thanks everyone for the enlightening discussion :-).

**Comment by Mugenor** [comment]
@squeed 
Thank you for providing the resolution!
I would be happy to contribute to this one.
Just in case: is there a more detailed description for the fix, which I should be aware of?

**Comment by rickymulder** [comment]
Just making sure this doesn't go stale - When trying to use in a multi-tenant openshift cluster, there are common policies recommended on the official docs that would break if used as CiliumNetworkPolicy

https://docs.openshift.com/container-platform/4.12/networking/network_policy/about-network-policy.html
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-ingress
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
  podSelector: {}
  policyTypes:
  - Ingress
 ```

**Comment by otahirs** [comment]
Hi, even though the issue is fixed, and policy similar to the following works properly
```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
  metadata:
  name: tenant-policy
spec:
  endpointSelector: {} 
  ingress:
    - fromEndpoints:
        - matchLabels: {}  
    - fromEndpoints:
      - matchLabels:
          "io.cilium.k8s.namespace.labels.tenant": "team-a"  
  egress:
    - toEndpoints:
      - matchLabels:
          "io.cilium.k8s.namespace.labels.tenant": "team-a"  

```
The docs has not been updated and this paragraph contradicts the current functionality
https://docs.cilium.io/en/latest/security/policy/kubernetes/#namespace-specific-information
