### ISSUE TITLE
Egress gateway doesn't support failover between nodes

### ISSUE THREAD

**Issue by JackMyers001** [cilium/cilium#30157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

According to the [Cilium docs on Egress gateways](https://docs.cilium.io/en/latest/network/egress-gateway/#selecting-and-configuring-the-gateway-node), *"In case multiple nodes are a match for the given set of labels, the first node in lexical ordering based on their name will be selected."*

This clearly means that Cilium *does* support multiple nodes being configured for an Egress gateway, but only the first node will be used. I would expect that if the first node was to go down, Cilium would start routing traffic through the second node, but from my testing this never happens; all traffic is dropped until the first node comes back online.

For example, say I have three nodes (`nodeA`, `nodeB` and `nodeC`), and I have the following `CiliumEgressGatewayPolicy`:

```yaml
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egress-gateway-test
spec:
  selectors:
    - podSelector:
        matchLabels:
          use-egress-gateway: "true"

  destinationCIDRs:
    - "0.0.0.0/0"

  egressGateway:
    interface: enp4s0.150
    nodeSelector:
      matchLabels:
        has-egress-gateway: "true"
```

Assuming the interface `enp4s0.150` exists on all three nodes and all nodes have the label `has-egress-gateway=true`, this `CiliumEgressGatewayPolicy` will apply for all nodes. As per the docs, all traffic from all pods running on all nodes that match the `podSelector` and `destinationCIDR` will route through `nodeA`.

However, if `nodeA` goes down (gracefully or otherwise), the traffic will *never* start being routed through `nodeB`; it will be dropped until `nodeA` comes back online.

Is this intended / expected? Is there a way to configure Egress gateways for HA / failover between nodes?

### Cilium Version

Tested in v1.14.5 and v.1.15.0-rc.0

### Kernel Version

Linux 6.1.69-talos

### Kubernetes Version

v1.29.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
