### ISSUE TITLE
CFP: BGP Control Plane automatic Router ID assignment for IPv6 single stack setup

### ISSUE THREAD

**Issue by YutaroHayakawa** [cilium/cilium#30333]
### Problem

In IPv4 and dual-stack environments, the Cilium BGP Control Plane derives the Router ID from the IPv4 address assigned to the node. However, in the IPv6 single-stack environment, there's no IPv4 address to use, so users must specify the Router ID manually for each virtual router for each Node.

```
$ kubectl annotate node <node-name> cilium.io/bgp-virtual-router.64512="router-id=10.0.0.1"
```

This is a big operational overhead because users must manage the assignment by themselves.

#### User Interface

The basic idea is to provide a pool of Router IDs like `10.0.0.0/16` in advance, and the Cilium Operator manages the assignment as we do for the IPAMs. A design decision we need to make here is how to provide the Router ID.

**Option1: Via Helm configuration**

Provide Router ID pool through Cilium operator's configuration like `bgpControlPlane.routerIDPool=10.0.0.0/16` which will ultimately rendered as a `cilium-config` ConfigMap entry. This is easy to implement, but changing or extending the range requires operator restart.

**Option2: Via CRD**

We can either extend `CiliumBGPPeeringPolicy` or introduce another CRD like `CiliumBGPRouterIDPool` and provide a Router ID from there. It's more complicated in terms of the implementation, but adding/deleting a range can be done dynamically without operator restart.

In my personal opinion, option 1 should be enough for most cases because the uniqueness of the Router ID needs to be guaranteed only within AS these days [RFC6286](https://datatracker.ietf.org/doc/html/rfc6286). Thus, it's easy for operators to allocate a large range. Also, it is possible to start from option 1 and support option 2 later.

#### Retaining Router ID over restart

~~The operator and agent must retain the Router ID over restart. This is important for Graceful Restart. In some implementations, when the Router ID of the restarting node changes, the Graceful Restart fails.~~

The operator can persist the assignment by writing assigned Router ID to either `CiliumNode` object or `CiliumBGPNodeConfig` object in [BGP Control Plane v2](https://docs.google.com/document/d/1mqmzlDeVKmNjsnDnnHTeoiW6JcItYMyDyuOM7SYoDi4/edit#heading=h.5mwz58y9syps).

**Comment by kishiguro** [comment]
@YutaroHayakawa How about assign unique 32 bit id to the instance.NewServerWithConfig() or gobgp.NewGoBGPServer()?  we may have slice for it and use slice's index + 1 or index + 10.0.0.1 as router-id.  Since we only need unique identification, having IPAM feels little bit overkill to me.

**Comment by iandrewt** [comment]
Proxmox implemented something similar for their SDN solution by deriving a router ID from the last 4 bytes of the interface's MAC address. I think having this as an option with a disclaimer that all nodes sharing an ASN need to have unique MAC addresses could solve for the stateless router-id configuration. There would probably also need to be a restriction on only allowing this setup with private range ASNs

https://git.proxmox.com/?p=pve-network.git;a=commit;h=7638f25336ab2c05edc8b0c306176b356da1a98e

**Comment by kishiguro** [comment]
@iandrewt thanks for the insight.  we can do same approach.  let me play around with my code.

**Comment by YutaroHayakawa** [comment]
@iandrewt Thanks for your input! I guess it only guarantee uniqueness when all routers in the AS follows that convention (and there's no MAC duplication), but with that caveat, that sounds like an attractive solution. Maybe, we can make a choice of stateful vs stateless to users through Helm options.

```
bgpControlPlane:
  enabled: true
  routerIDAllocation:
    mode: idPool # choice: idPool, mac
    idPool: 10.0.0.0/16 # Only valid when the mode=idPool
```

**Comment by iandrewt** [comment]
I like that idea - starting with stateless but designing the config in a way that makes it non-breaking to add stateful later (like above) should help get a usable version of this feature out sooner, since I'd figure that's lower effort than the stateful method

**Comment by yushoyamaguchi** [comment]
```
bgpControlPlane:
  enabled: true
  ipv6RouterIDAllocation:
    mode: idPool # choice: idPool, mac-address
    idPool: 10.0.0.0/16 # Only valid when the mode=idPool
```

@YutaroHayakawa 

Can I implement this feature, firstly?
When using idPool, cilium-operator assign router-id to make it work, right?

**Comment by YutaroHayakawa** [comment]
@yushoyamaguchi Thanks! Please do. Regarding the above example configuration, the mode should be `id-pool` and `mac-address`. Just following the style of the rest of the Helm values. We'd suggest working for the `mac-address` mode first, since it's easier to implement.

Here I have some suggestion for the implementation:

**BGPv1 vs BGPv2**

At the time I wrote this issue, I was assuming the BGPv1 (the one uses CiliumBGPPeeringPolicy), but we're not adding any new feature to BGPv1 because we are moving to BGPv2 (the one uses CiliumBGPClusterConfig), so let's implement this feature only for BGPv2.

**Multi instance consideration**

BGPv2 is capable of having multiple BGP instances and each of them should get a router-id. I think there's no problem for having the same router-id for all instances. The only exception is when users specify the same localASN for multiple instances. Since router-id should be unique within the same AS, this is an error. However, I think this is a rare case in practice, so we can safely say it is not supported and report an error in some way (log or in the `status.condition` in the `CiliumBGPClusterConfig`.

```
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  bgpInstances:
  - name: "instance-65000"
    localASN: 65000
    ...
  - name: "instance-65001"
    localASN: 65001
    ...
```

**Which interface should we use for router-id generation**

`mac-address` mode generates the router-id from interface's MAC address. The question is which interface. I think we can take the mac address of the `cilium_host` interface. This interface is guaranteed to be present in Cilium (essentially, it's an "loopback interface" of Cilium) so we don't have to think about finding the sufficient one.

It's veth, so the MAC address is [random](https://github.com/torvalds/linux/blob/2ba9f676d0a2e408aef14d679984c26373bf37b7/include/linux/etherdevice.h#L229-L241). If it collides with the different router in the same AS, users can reboot the node to draw a different MAC address.

@harsimran-pabla @rastislavs If you have any concern about the above direction, please feel free to make a comment.

**Comment by yushoyamaguchi** [comment]
@YutaroHayakawa 

Thank you for your comment.

> users can reboot the node to draw a different MAC address.

I felt this is quite difficult for some users...
Is it unavoidably necessary to restart the node itself to get a different MAC address?
For example, is it possible to remake `cilium_host` by cilium-agent?

**Comment by YutaroHayakawa** [comment]
I just mentioned it as a last resort of in case of collision. It's super rare I'd say. There were nice article explains that.

https://zenn.dev/masap/articles/6ee6b6a1fb9cb0

It's quite hard to change the MAC address at runtime. Depending on the setup, it may make a traffic disruption.

**Comment by yushoyamaguchi** [comment]
I understand.
Thank you so much.

**Comment by harsimran-pabla** [comment]
Hi @yushoyamaguchi , in my view, default mode should be mac-address. Which is more user friendly and does not require idPool to be specified by the user. Implementing default mode first will make upgrades smoother, as changing default mode in-between Cilium version is not practical. 

What is not clear to me is behavior when using IPv4 only or dual-stack modes. Does `ipv6RouterIDAllocation` configuration have no effect which cilium node has IPv4 address?

**Comment by harsimran-pabla** [comment]
I think following logic makes most sense to me : 

Helm values 

Instead of `mac-address`, use `auto` and drop IPv6 prefix from router id allocation name. 

```
bgpControlPlane:
  enabled: true
  routerIDAllocation:
    mode: id-pool # choice: id-pool, auto
    idPool: 10.0.0.0/16 # Only valid when the mode=idPool
```

Implementation logic

`auto` setting should be default, and follows this logic
- Only takes effect if router-id field in CiliumBGPNodeConfig object is missing.
- If ipv4 address is allocated to node, use that for router-id ( current logic )
- If no ipv4 address found, use mac-address to generate router-id. ( on IPv6 only nodes )

`id-pool` setting should be applicable regardless of v4/dual-stack/v6 nodes. This implementation will go in operator. And used to set router-id field in CiliumBGPNodeConfig object. Per node router-id override from `CiliumBGPNodeConfigOverride` CRD should take precedence.

**Comment by yushoyamaguchi** [comment]
@harsimran-pabla 
Thank you for your comment.
I'll implement default mode and make PR firstly, before implementing `id-pool` mode.

About item names and how it is applied, I understood your suggestion and felt it is good.
I'll implement as below.
```
bgpControlPlane:
  enabled: true
  routerIDAllocation:
    mode: auto # default
```

**Comment by YutaroHayakawa** [comment]
Hmm, applying this to IPv4 sounds good. However, the name "auto" sounds a bit odd to me because both the default behavior and "id-pool" assigns router-id automatically. Maybe "stateless" vs "id-pool" or "default" vs "id-pool"?

**Comment by yushoyamaguchi** [comment]
@YutaroHayakawa @harsimran-pabla 
I felt `default` may be more kind for users who use Cilium **without** implementation internals concern.
Can I use `default` ?

**Comment by harsimran-pabla** [comment]
No objection to using `mode: default`.

**Comment by yushoyamaguchi** [comment]
@YutaroHayakawa  @harsimran-pabla 

I want to implement checking Multi-Instance and emitting error.
ref : middle of https://github.com/cilium/cilium/issues/30333#issuecomment-2508934082

Current my plan is below.
- Having key-value-store about Instance-LocalASN set in `struct BGPRouterManager` 
- If there are multiple Instances of same ASN, `registerBGPInstance()` returns error with proper error message.
- These procedures are implemented in this part (https://github.com/cilium/cilium/blob/6d23ed5f6bd3df7e6a27f854319aadb4b795eff2/pkg/bgpv1/manager/manager.go#L869)

Does it looks reasonable?
Please tell me if there are more efficient ways.

**Comment by harsimran-pabla** [comment]
> Having key-value-store about Instance-LocalASN set in struct BGPRouterManager

Is this necessary, BGP instances are available [here](https://github.com/cilium/cilium/blob/6d23ed5f6bd3df7e6a27f854319aadb4b795eff2/pkg/bgpv1/manager/manager.go#L145). Each instances should have router-id under `Global` settings.

**Comment by harsimran-pabla** [comment]
> If there are multiple Instances of same ASN, registerBGPInstance() returns error with proper error message.

I think this is reasonable, we should highlight this in the documentation as well.

**Comment by yushoyamaguchi** [comment]
@harsimran-pabla 

When `registerBGPInstance()` returns error in second instance, peer of the first instance has broken.
Is it undesired, right?

<details><summary>A part of BGP config</summary>

```
  bgpInstances:
    - name: "instance-65002" # First Instance. Its peer also be broken.
      localASN: 65002
      peers:
        - name: "peer-65000"
          peerAddress: fd00:10:0:2::1
          peerASN: 65000
          peerConfigRef:
            name: "cilium-peer"
    - name: "instance-65002-dummy" # Dummy Instance. It should be discarded.
      localASN: 65002
      peers:
        - name: "peer-65003"
          peerAddress: fd00:10:0:2::3 # Dummy peer
          peerASN: 65003
          peerConfigRef:
            name: "cilium-peer"
```
</details>
