### ISSUE TITLE
cilium-pre-flight-check crashloop when a lot of CNP are checked due to readyness probe

### ISSUE THREAD

**Issue by splattner** [cilium/cilium#30379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

we have around 5800 Cilium Network Policies on our cluster. The preflight check does some checking with all of them which takes some time. Unfortunately the readyness probe is set to:

``` 
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/ready-validate-cnp
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1

```

and therefore the pod is terminated before the checks are done. This results in a crash loop and a hanging cilium installation.
The values cannot be changed in the helm chart.

Workaround:
manually change the deployment during the helm installation and e.g. increase initialDelaySeconds: 5

### Cilium Version

1.14.5

### Kernel Version

Linux aks-default-21235459-vmss000000 5.15.0-1053-azure #61-Ubuntu SMP Tue Nov 21 14:16:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.28.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
