### ISSUE TITLE
CiliumEnvoyConfig limits number of HTTP connections to upstream endpoints to number of CPU cores

### ISSUE THREAD

**Issue by carnerito** [cilium/cilium#30406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When CiliumEnvoyConfig (example bellow) is deployed for some service, number of connections Envoy will open to each of endpoints for that service is equal to cpu cores (which is also Envoy concurrency config value). I have confirmed this by changing number of vCPUs on test VMs.

When there are more inflight requests than the number of CPU cores * number of upstream endpoints (pods) each subsequent request will fail and client will receive 503 error `upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: immediate connect error: Cannot assign requested address`.

I'm testing with HTTP/1.1 protocol, and acording to [envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/connection_pooling#http-1-1) number of connections to upstream host are capped by circuit breker limit, so I’ve tried to set circuit_breakear with max_connections threshold, but it didn’t help.

What else did I tried:
- Changing Cluster type from EDS to ORIGINAL_DST solved the connection limit issue. I'm not sure why this is the case, but I'm sure that this is not valid solution :)
- `connection_pool_per_downstream_connection: true` to cluster configuration solves the issue, but I'm not sure this is acceptable performance wise (I'll perform HTTP benchmark later)

```
apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:
  name: envoy-lb-listener
  namespace: playground
spec:
  resources:
  - '@type': type.googleapis.com/envoy.config.listener.v3.Listener
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          rds:
            route_config_name: lb_route
          skip_xff_append: true
          stat_prefix: envoy-lb-listener
          use_remote_address: true
    name: envoy-lb-listener
  - '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
    name: lb_route
    virtual_hosts:
    - domains:
      - '*'
      name: lb_route
      routes:
      - match:
          prefix: /
        route:
          cluster: playground/web-app
          retry_policy:
            num_retries: 2
            retry_back_off:
              base_interval: 0.5s
              max_interval: 2s
            retry_on: 5xx,connect-failure
  - '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
     circuit_breakers:
      # Disable Circuit Breaker
        thresholds:
          - max_connections: 1000000000
            max_pending_requests: 1000000000
            max_requests: 1000000000
            max_retries: 1000000000
            max_connection_pools: 1000000000    
    connect_timeout: 5s
    lb_policy: ROUND_ROBIN
    # This solves the connection limit issue
    # connection_pool_per_downstream_connection: true
    name: playground/web-app
    type: EDS
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        useDownstreamProtocolConfig:
          http2ProtocolOptions: {}
  services:
  - name: web-app
    namespace: playground
```

### Cilium Version

Client: 1.14.5 85db28be 2023-12-11T14:30:29+01:00 go version go1.20.12 linux/amd64
Daemon: 1.14.5 85db28be 2023-12-11T14:30:29+01:00 go version go1.20.12 linux/amd64

### Kernel Version

5.15.0-91-generic

### Kubernetes Version

Client Version: v1.27.6
Kustomize Version: v5.0.1
Server Version: v1.28.5+k3s1

### Relevant log output

```shell
cilium-envoy pod debug logs:

cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][42][trace][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:292] ConnPoolImplBase 0x3584f95fe3c0, ready_clients_.size(): 0, busy_clients_.size(): 1, connecting_clients_.size(): 0, connecting_stream_capacity_: 0, num_active_streams_: 1, pending_streams_.size(): 1 per upstream preconnect ratio: 1
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][64][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:250] item added to deferred deletion list (size=1)
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][42][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:145] creating a new connection (connecting=0)
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][95][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:145] creating a new connection (connecting=0)
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.156][92][trace][http] [external/envoy/source/common/http/filter_manager.cc:1129] [C887277][S16502693713554032993] encode headers called: filter=cilium.l7policy status=0
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][64][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:250] item added to deferred deletion list (size=2)
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][64][debug][router] [external/envoy/source/common/router/router.cc:1220] [C889416][S2469953664952234906] upstream reset: reset reason: connection failure, transport failure reason: immediate connect error: Cannot assign requested address
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][64][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:250] item added to deferred deletion list (size=3)
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][64][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:250] item added to deferred deletion list (size=4)
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][42][trace][filter] [./cilium/socket_option.h:103] Set socket (768) option SO_MARK to e730900 (magic mark: 900, id: 3699, cluster: 0), src: 10.42.0.188:34530
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][92][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1596] [C887277][S16502693713554032993] encoding headers via codec (end_stream=false):
cilium-envoy-42ttq cilium-envoy ':status', '503'
cilium-envoy-42ttq cilium-envoy 'content-length', '198'
cilium-envoy-42ttq cilium-envoy 'content-type', 'text/plain'
cilium-envoy-42ttq cilium-envoy 'date', 'Wed, 24 Jan 2024 07:37:05 GMT'
cilium-envoy-42ttq cilium-envoy 'server', 'envoy'
cilium-envoy-42ttq cilium-envoy
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][64][trace][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:131] not creating a new connection, shouldCreateNewConnection returned false.
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][64][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:250] item added to deferred deletion list (size=5)
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][95][trace][filter] [./cilium/socket_option.h:103] Set socket (770) option SO_MARK to e730900 (magic mark: 900, id: 3699, cluster: 0), src: 10.42.0.188:33828
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][92][trace][connection] [external/envoy/source/common/network/connection_impl.cc:483] [C887277] writing 135 bytes, end_stream false
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][64][trace][connection] [external/envoy/source/common/network/connection_impl.cc:568] [C905567] socket event: 3
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][64][debug][connection] [external/envoy/source/common/network/connection_impl.cc:580] [C905567] raising immediate error
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][42][debug][connection] [external/envoy/source/common/network/connection_impl.h:92] [C905568] current connecting state: true
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][92][trace][http] [external/envoy/source/common/http/filter_manager.cc:1292] [C887277][S16502693713554032993] encode data called: filter=cilium.l7policy status=0
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][42][debug][client] [external/envoy/source/common/http/codec_client.cc:57] [C905568] connecting
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][42][debug][connection] [external/envoy/source/common/network/connection_impl.cc:939] [C905568] connecting to 10.42.0.226:8080
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][92][trace][http] [external/envoy/source/common/http/conn_manager_impl.cc:1606] [C887277][S16502693713554032993] encoding data via codec (size=198 end_stream=true)
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][92][trace][connection] [external/envoy/source/common/network/connection_impl.cc:483] [C887277] writing 198 bytes, end_stream false
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][42][debug][connection] [external/envoy/source/common/network/connection_impl.cc:963] [C905568] immediate connect error: Cannot assign requested address
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][42][trace][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:131] not creating a new connection, shouldCreateNewConnection returned false.
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][92][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:250] item added to deferred deletion list (size=8)
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][42][trace][http] [external/envoy/source/common/http/filter_manager.cc:539] [C889982][S16384660390850752374] decode headers called: filter=envoy.filters.http.upstream_codec status=4
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][64][debug][connection] [external/envoy/source/common/network/connection_impl.cc:250] [C905567] closing socket: 0
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][95][debug][connection] [external/envoy/source/common/network/connection_impl.h:92] [C905569] current connecting state: true
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][42][trace][connection] [external/envoy/source/common/network/connection_impl.cc:568] [C905568] socket event: 3
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][64][trace][connection] [external/envoy/source/common/network/connection_impl.cc:423] [C905567] raising connection event 0
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][43][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:526] [C885002] completed header: key=X-Scheme value=https
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][43][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:526] [C885002] completed header: key=User-Agent value=Go-http-client/1.1
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][76][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:145] creating a new connection (connecting=1)
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][42][debug][connection] [external/envoy/source/common/network/connection_impl.cc:580] [C905568] raising immediate error
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][92][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:250] item added to deferred deletion list (size=9)
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][43][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:820] [C885002] onHeadersCompleteBase
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][42][debug][connection] [external/envoy/source/common/network/connection_impl.cc:250] [C905568] closing socket: 0
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][64][debug][client] [external/envoy/source/common/http/codec_client.cc:107] [C905567] disconnect. resetting 0 pending requests
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][92][trace][misc] [external/envoy/source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x3584f12b3a40 for 3600000ms, min is 3600000ms
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][42][trace][connection] [external/envoy/source/common/network/connection_impl.cc:423] [C905568] raising connection event 0
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][64][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:484] [C905567] client disconnected, failure reason: immediate connect error: Cannot assign requested address
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][42][debug][client] [external/envoy/source/common/http/codec_client.cc:107] [C905568] disconnect. resetting 0 pending requests
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][43][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:526] [C885002] completed header: key=Accept-Encoding value=gzip
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][76][trace][filter] [./cilium/socket_option.h:103] Set socket (554) option SO_MARK to e730900 (magic mark: 900, id: 3699, cluster: 0), src: 10.42.0.188:35238
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][43][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:1142] [C885002] Server: onHeadersComplete size=11
cilium-envoy-42ttq cilium-envoy [2024-01-24 07:37:06.157][64][trace][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:131] not creating a new connection, shouldCreateNewConnection returned false.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
