### ISSUE TITLE
Incorrect DerivedFromRules for a policy key in Egress PolicyMap

### ISSUE THREAD

**Issue by skmatti** [cilium/cilium#30469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have added extra logs in https://github.com/skmatti/cilium/pull/1 at https://github.com/cilium/cilium/blob/d72e63048361bcbe85be260c390fdecbc4ad9ff7/pkg/policy/l4.go#L621 and https://github.com/cilium/cilium/blob/d72e63048361bcbe85be260c390fdecbc4ad9ff7/pkg/policy/repository.go#L768 to debug the issue.

#### Steps to reproduce the issue:

1. Create a server and client pod

```
kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-1
spec:
  selector:
    matchLabels:
      app: server-1
  replicas: 2
  template:
    metadata:
      labels:
        app: server-1
    spec:
      containers:
      - command:
        - /agnhost
        - netexec
        - --http-port=8080
        image: registry.k8s.io/e2e-test-images/agnhost:2.39
        name: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-1
spec:
  selector:
    matchLabels:
      app: client-1
  replicas: 1
  template:
    metadata:
      labels:
        app: client-1
    spec:
      containers:
      - command:
        - /agnhost
        - pause
        image: registry.k8s.io/e2e-test-images/agnhost:2.39
        name: client
EOF
```

2. Create two egress network policies for the client pod (one to allow just public traffic and other to allow just in-cluster traffic)

```
kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-public
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: client-1
  egress:
  - to:
    - ipBlock:
        cidr: 1.1.1.1/32
    - ipBlock:
        cidr: 8.8.8.8/32
  policyTypes:
  - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-in-cluster
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: client-1
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: server-1
  policyTypes:
  - Egress
EOF
```

Both policies have same L4 filter so they are grouped together when computing policies for the client pod:

```
{"identity":33868,"key":"0/ANY","level":"info","msg":"resolveL4EgressPolicy","subsys":"policy","value":{"port":0,"protocol":"ANY","l7-rules":[{"\u0026LabelSelector{MatchLabels:map[string]string{cidr.1.1.1.1/32: ,},MatchExpressions:[]LabelSelectorRequirement{},}":null},{"\u0026LabelSelector{MatchLabels:map[string]string{cidr.8.8.8.8/32: ,},MatchExpressions:[]LabelSelectorRequirement{},}":null},{"\u0026LabelSelector{MatchLabels:map[string]string{k8s.app: server-1,k8s.io.kubernetes.pod.namespace: default,},MatchExpressions:[]LabelSelectorRequirement{},}":null}]}}
```

The side effect of this is that the DerivedFromRules for the policy key with server's identity is incorrect:

```
{"endpointID":3279,"key":{"Identity":3217,"DestPort":0,"Nexthdr":0,"TrafficDirection":1},"level":"info","msg":"L4Filter to MapState","subsys":"policy","value":{"ProxyPort":0,"IsDeny":false,"AuthType":0,"DerivedFromRules":[[{"key":"io.cilium.k8s.policy.derived-from","value":"NetworkPolicy","source":"k8s"},{"key":"io.cilium.k8s.policy.name","value":"allow-in-cluster","source":"k8s"},{"key":"io.cilium.k8s.policy.namespace","value":"default","source":"k8s"},{"key":"io.cilium.k8s.policy.uid","value":"eb3e688d-b28a-4dd1-90cf-e4b8a5f6234e","source":"k8s"}],[{"key":"io.cilium.k8s.policy.derived-from","value":"NetworkPolicy","source":"k8s"},{"key":"io.cilium.k8s.policy.name","value":"allow-public","source":"k8s"},{"key":"io.cilium.k8s.policy.namespace","value":"default","source":"k8s"},{"key":"io.cilium.k8s.policy.uid","value":"3855cb0d-2768-464e-9314-eb9cb62f4fc2","source":"k8s"}]]}}
```

This entry is for egress traffic from the client pod to the server pod so it matches the network policy `allow-in-cluster`. The network policy `allow-public` does not match this traffic.

However,`DerivedFromRules` contains both network policies instead of just `allow-in-cluster`. 

This issue seems to have been fixed in 1.14+ in https://github.com/cilium/cilium/pull/23811

Is there a plan to backport this fix to 1.13?

### Cilium Version

1.13.8

### Kernel Version

N/A

### Kubernetes Version

1.28.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
