### ISSUE TITLE
Mismatching entries from CiliumNetworkPolicy -> Applied to "bpf policy" entries

### ISSUE THREAD

**Issue by ekarlso** [cilium/cilium#30552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am trying to apply a simple nginx deployment and a test container using netshoot to probe it. 

The nginx container should have access to kube-dns via the following CNP
```yaml
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: nginx
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      app: nginx
  egress:
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
  ingress:
    - fromEntities:
        - ingress
    - fromEndpoints:
        - matchLabels:
            run: tmp-shell
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
```

I would then expect to see a set of policy entries installed on the nginx endpoint on a given node but it seems I get way more entries then what there should be and also `ingress` rules are totally ignored from my CNP.
```yaml
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                  IPv6   IPv4            STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                                      
39         Disabled           Disabled          1          k8s:node.cluster.x-k8s.io/esxi-host=172.16.50.33                                                    ready   
                                                           k8s:node.kubernetes.io/instance-type=vsphere-vm.cpu-4.mem-16gb.os-linux                                     
                                                           reserved:host                                                                                               
277        Disabled           Disabled          755        k8s:app=talos-vmtoolsd                                                              172.17.16.178   ready   
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system                                  
                                                           k8s:io.cilium.k8s.policy.cluster=default                                                                    
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                             
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                                 
286        Disabled           Disabled          4          reserved:health                                                                     172.17.16.184   ready   
1109       Enabled            Enabled           23748      k8s:app=nginx                                                                       172.17.16.168   ready   
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                      
                                                           k8s:io.cilium.k8s.policy.cluster=default                                                                    
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                             
                                                           k8s:io.kubernetes.pod.namespace=default                                                                     
1558       Disabled           Disabled          1905       k8s:app.kubernetes.io/name=hubble-ui                                                172.17.16.164   ready   
                                                           k8s:app.kubernetes.io/part-of=cilium                                                                        
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system                                  
                                                           k8s:io.cilium.k8s.policy.cluster=default                                                                    
                                                           k8s:io.cilium.k8s.policy.serviceaccount=hubble-ui                                                           
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                                 
                                                           k8s:k8s-app=hubble-ui                                                                                       
2875       Disabled           Disabled          8          reserved:ingress                                                                    172.17.16.144   ready   
```

```yaml
POLICY   DIRECTION   LABELS (source:key[=value])                                                  PORT/PROTO   PROXY PORT   AUTH TYPE   BYTES   PACKETS   PREFIX   
Allow    Ingress     reserved:ingress                                                             ANY          NONE         disabled    7148    65        0        
Allow    Egress      k8s:io.cilium.k8s.policy.cluster=default                                     53/TCP       41873        disabled    0       0         24       
                     k8s:io.cilium.k8s.policy.serviceaccount=kube-dns                                                                                              
                     k8s:io.kubernetes.pod.namespace=kube-system                                                                                                   
                     k8s:k8s-app=kube-dns                                                                                                                          
Allow    Egress      k8s:io.cilium.k8s.policy.cluster=default                                     53/UDP       41873        disabled    0       0         24       
                     k8s:io.cilium.k8s.policy.serviceaccount=kube-dns                                                                                              
                     k8s:io.kubernetes.pod.namespace=kube-system                                                                                                   
                     k8s:k8s-app=kube-dns                                                                                                                          
Allow    Egress      k8s:eks.amazonaws.com/component=kube-dns                                     53/TCP       41873        disabled    0       0         24       
                     k8s:io.cilium.k8s.policy.cluster=default                                                                                                      
                     k8s:io.cilium.k8s.policy.serviceaccount=kube-dns                                                                                              
                     k8s:io.kubernetes.pod.namespace=kube-system                                                                                                   
                     k8s:k8s-app=kube-dns                                                                                                                          
Allow    Egress      k8s:eks.amazonaws.com/component=kube-dns                                     53/UDP       41873        disabled    0       0         24       
                     k8s:io.cilium.k8s.policy.cluster=default                                                                                                      
                     k8s:io.cilium.k8s.policy.serviceaccount=kube-dns                                                                                              
                     k8s:io.kubernetes.pod.namespace=kube-system                                                                                                   
                     k8s:k8s-app=kube-dns                                                                                                                          
Allow    Egress      k8s:io.cilium.k8s.policy.cluster=default                                     53/TCP       41873        disabled    0       0         24       
                     k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                                                               
                     k8s:io.kubernetes.pod.namespace=kube-system                                                                                                   
                     k8s:k8s-app=kube-dns                                                                                                                          
Allow    Egress      k8s:io.cilium.k8s.policy.cluster=default                                     53/UDP       41873        disabled    0       0         24       
                     k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                                                               
                     k8s:io.kubernetes.pod.namespace=kube-system                                                                                                   
                     k8s:k8s-app=kube-dns                                                                                                                          
Allow    Egress      k8s:eks.amazonaws.com/component=coredns                                      53/TCP       41873        disabled    0       0         24       
                     k8s:io.cilium.k8s.policy.cluster=default                                                                                                      
                     k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                                                               
                     k8s:io.kubernetes.pod.namespace=kube-system                                                                                                   
                     k8s:k8s-app=kube-dns                                                                                                                          
Allow    Egress      k8s:eks.amazonaws.com/component=coredns                                      53/UDP       41873        disabled    0       0         24       
                     k8s:io.cilium.k8s.policy.cluster=default                                                                                                      
                     k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                                                               
                     k8s:io.kubernetes.pod.namespace=kube-system                                                                                                   
                     k8s:k8s-app=kube-dns                                                                                                                          
Allow    Egress      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system   53/TCP       41873        disabled    0       0         24       
                     k8s:io.cilium.k8s.policy.cluster=default                                                                                                      
                     k8s:io.cilium.k8s.policy.serviceaccount=kube-dns                                                                                              
                     k8s:io.kubernetes.pod.namespace=kube-system                                                                                                   
                     k8s:k8s-app=kube-dns                                                                                                                          
Allow    Egress      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system   53/UDP       41873        disabled    0       0         24       
                     k8s:io.cilium.k8s.policy.cluster=default                                                                                                      
                     k8s:io.cilium.k8s.policy.serviceaccount=kube-dns                                                                                              
                     k8s:io.kubernetes.pod.namespace=kube-system                                                                                                   
                     k8s:k8s-app=kube-dns                                                                                                                          
Allow    Egress      k8s:eks.amazonaws.com/component=kube-dns                                     53/TCP       41873        disabled    0       0         24       
                     k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system                                                                    
                     k8s:io.cilium.k8s.policy.cluster=default                                                                                                      
                     k8s:io.cilium.k8s.policy.serviceaccount=kube-dns                                                                                              
                     k8s:io.kubernetes.pod.namespace=kube-system                                                                                                   
                     k8s:k8s-app=kube-dns                                                                                                                          
Allow    Egress      k8s:eks.amazonaws.com/component=kube-dns                                     53/UDP       41873        disabled    0       0         24       
                     k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system                                                                    
                     k8s:io.cilium.k8s.policy.cluster=default                                                                                                      
                     k8s:io.cilium.k8s.policy.serviceaccount=kube-dns                                                                                              
                     k8s:io.kubernetes.pod.namespace=kube-system                                                                                                   
                     k8s:k8s-app=kube-dns                                                                                                                          
Allow    Egress      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system   53/TCP       41873        disabled    0       0         24       
                     k8s:io.cilium.k8s.policy.cluster=default                                                                                                      
                     k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                                                               
                     k8s:io.kubernetes.pod.namespace=kube-system                                                                                                   
                     k8s:k8s-app=kube-dns                                                                                                                          
Allow    Egress      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system   53/UDP       41873        disabled    0       0         24       
                     k8s:io.cilium.k8s.policy.cluster=default                                                                                                      
                     k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                                                               
                     k8s:io.kubernetes.pod.namespace=kube-system                                                                                                   
                     k8s:k8s-app=kube-dns                                                                                                                          
Allow    Egress      k8s:eks.amazonaws.com/component=coredns                                      53/TCP       41873        disabled    0       0         24       
                     k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system                                                                    
                     k8s:io.cilium.k8s.policy.cluster=default                                                                                                      
                     k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                                                               
                     k8s:io.kubernetes.pod.namespace=kube-system                                                                                                   
                     k8s:k8s-app=kube-dns                                                                                                                          
Allow    Egress      k8s:eks.amazonaws.com/component=coredns                                      53/UDP       41873        disabled    0       0         24       
                     k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system                                                                    
                     k8s:io.cilium.k8s.policy.cluster=default                                                                                                      
                     k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                                                               
                     k8s:io.kubernetes.pod.namespace=kube-system                                                                                                   
                     k8s:k8s-app=kube-dns               
```

### Cilium Version

CI Image 4ffe587f5f70cedecee442aa27cb4b03b63c167e

### Kernel Version

Talos (v1.6.3) -> 6.1.74-talos

### Kubernetes Version

1.28.5

### Anything else?

My config is 
```yaml
---
k8s:
  requireIPv4PodCIDR: true
  requireIPv6PodCIDR: false

# bpf:
#   masquerade: true

# ipMasqAgent:
#   enabled: true

devices:
  - eth0

ipv4:
  enabled: true
ipv6:
  enabled: false

enableIPv4BIGTCP: false
enableIPv4Masquerade: true

enableIPv6BIGTCP: false
enableIPv6Masquerade: false

localRedirectPolicy: true

# installNoConntrackIptablesRules: true

ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 172.17.16.0/20
    clusterPoolIPv4MaskSize: 26

    clusterPoolIPv6PodCIDRList: []
    clusterPoolIPv6MaskSize: 128
    autoCreateCiliumPodIPPools: {}

labels: k8s:!io.cilium.k8s.namespace.labels.kustomize.*

# debug:
#   enabled: false
#   verbose: policy

# hostPort:
#   enabled: true

# nodePort:
#   enabled: true

enableIdentityMark: true
remoteNodeIdentity: true
wellKnownIdentities:
  enabled: true

endpointStatus:
  enabled: true
  status: policy health controllers log state

hostFirewall:
  enabled: true # enable host policies
extraConfig:
  allow-localhost: policy # enable policies for local host

hubble:
  enabled: true
  metrics:
    enableOpenMetrics: true

    enabled:
      - drop
      - tcp
      - flow
      - flows-to-world
      - icmp
      - httpV2
      - port-distribution

  relay:
    enabled: true
    rollOutPods: true

    image:
      useDigest: false

    prometheus:
      enabled: true

    securityContext:
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
          - ALL
  ui:
    enabled: true
    rolloutPods: true

    backend:
      image:
        tag: v0.12.0
        useDigest: false

      securityContext:
        seccompProfile:
          type: RuntimeDefault
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65535
        capabilities:
          drop:
            - ALL

    frontend:
      image:
        tag: v0.12.0
        useDigest: false

      securityContext:
        seccompProfile:
          type: RuntimeDefault
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65535
        capabilities:
          drop:
            - ALL

prometheus:
  enabled: true

routingMode: native
ipv4NativeRoutingCIDR: "172.17.16.0/20"
autoDirectNodeRoutes: true

kubeProxyReplacement: true
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445

ingressController:
  enabled: false
  default: true

gatewayAPI:
  enabled: true

l2announcements:
  enabled: true

rolloutCiliumPods: true

image:
  useDigest: false
  repository: quay.io/cilium/cilium-ci
  tag: 4ffe587f5f70cedecee442aa27cb4b03b63c167e

operator:
  replicas: 2
  rolloutPods: true

  prometheus:
    enabled: false

  securityContext:
    seccompProfile:
      type: RuntimeDefault
    allowPrivilegeEscalation: false
    # runAsNonRoot: true
    # runAsUser: 65534
    capabilities:
      drop:
        - ALL
  image:
    useDigest: false
    repository: quay.io/cilium/operator
    suffix: "-ci"
    tag: 4ffe587f5f70cedecee442aa27cb4b03b63c167e

policyEnforcementMode: default
policyAuditMode: false
# policyCIDRMatchMode: nodes

k8sClientRateLimit:
  qps: 45
  burst: 60

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

securityContext:
  # -- User to run the pod with
  runAsUser: 0
  # -- Run the pod with elevated privileges
  privileged: false

  capabilities:
    # -- Capabilities for the `mount-cgroup` init container
    mountCgroup:
      # Only used for 'mount' cgroup
      - SYS_ADMIN
      # Used for nsenter
      - SYS_CHROOT
      - SYS_PTRACE
    # -- capabilities for the `apply-sysctl-overwrites` init container
    applySysctlOverwrites:
      # Required in order to access host's /etc/sysctl.d dir
      - SYS_ADMIN
      # Used for nsenter
      - SYS_CHROOT
      - SYS_PTRACE
    # -- Capabilities for the `cilium-agent` container
    ciliumAgent:
      # Use to set socket permission
      - CHOWN
      # Used to terminate envoy child process
      - KILL
      # Used since cilium modifies routing tables, etc...
      - NET_ADMIN
      # Used since cilium creates raw sockets, etc...
      - NET_RAW
      # Used since cilium monitor uses mmap
      - IPC_LOCK
      # We need it for now but might not need it for >= 5.11 specially
      # for the 'SYS_RESOURCE'.
      # In >= 5.8 there's already BPF and PERMON capabilities
      - SYS_ADMIN
      # Could be an alternative for the SYS_ADMIN for the RLIMIT_NPROC
      - SYS_RESOURCE
      # Both PERFMON and BPF requires kernel 5.8, container runtime
      # cri-o >= v1.22.0 or containerd >= v1.5.0.
      # If available, SYS_ADMIN can be removed.
      - PERFMON
      - BPF
      # Allow discretionary access control (e.g. required for package installation)
      - DAC_OVERRIDE
      # Allow to set Access Control Lists (ACLs) on arbitrary files (e.g. required for package installation)
      - FOWNER
      # Allow to execute program that changes GID (e.g. required for package installation)
      - SETGID
      # Allow to execute program that changes UID (e.g. required for package installation)
      - SETUID
    # -- Capabilities for the `clean-cilium-state` init container
    cleanCiliumState:
      # Most of the capabilities here are the same ones used in the
      # cilium-agent's container because this container can be used to
      # uninstall all Cilium resources, and therefore it is likely that
      # will need the same capabilities.
      # Used since cilium modifies routing tables, etc...
      - NET_ADMIN
      # We need it for now but might not need it for >= 5.11 specially
      # for the 'SYS_RESOURCE'.
      # In >= 5.8 there's already BPF and PERMON capabilities
      - SYS_ADMIN
      # Could be an alternative for the SYS_ADMIN for the RLIMIT_NPROC
      - SYS_RESOURCE
      # Both PERFMON and BPF requires kernel 5.8, container runtime
      # cri-o >= v1.22.0 or containerd >= v1.5.0.
      # If available, SYS_ADMIN can be removed.
      - PERFMON
      - BPF
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
