### ISSUE TITLE
CFP: `HTTPRoute` `ExtensionRef` support for arbitrary L7 Envoy filters 

### ISSUE THREAD

**Issue by GreenCappuccino** [cilium/cilium#30587]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your proposed feature related to a problem?**

Currently, trying to use an HTTPRoute in conjunction with additional Envoy filters (via CiliumEnvoyConfig) is difficult. This is a common use case when needing to provide authentication to a service like via the [OAuth2 Envoy filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter).

**Describe the feature you'd like**

I would like Cilium to add an EnvoyFilter resource for use as an [`HTTPRoute` `ExtensionRef`](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPRouteFilterType). There is similar behavior present in the [Envoy Gateway implementation of HTTPRoute](https://github.com/AliceProxy/gateway/blob/main/examples/kubernetes/authn/jwt.yaml), where it allows a reference to a CRD for each possible filter. This is a far more ergonomic way of defining envoy filters, and is a stable part of the Gateway API.

**(Optional) Describe your proposed solution**

Possibly create a new CRD, maybe `CiliumEnvoyHTTPFilter`, which can specify (multiple?) envoy filters, that can be the target of an HTTPRoute filter. The format can be similar to `CiliumEnvoyConfig` but scoped to Envoy HTTP filters. This filter will be merged into the filterchain during reconciliation of the HTTPRoute.

Example:
```yaml
apiVersion: cilium.io/vX
kind: CiliumEnvoyHTTPFilter
metadata:
  name: oauth2-example
spec:
  - name: envoy.filters.http.oauth2
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.oauth2.v3.OAuth2
      config:
        token_endpoint:
          cluster: oauth
          uri: oauth.com/token
          timeout: 3s
        authorization_endpoint: https://oauth.com/oauth/authorize/
        redirect_uri: "%REQ(x-forwarded-proto)%://%REQ(:authority)%/callback"
        redirect_path_matcher:
          path:
            exact: /callback
        signout_path:
          path:
            exact: /signout
        credentials:
          client_id: foo
          token_secret:
            name: token
            sds_config:
              path: "/etc/envoy/token-secret.yaml"
          hmac_secret:
            name: hmac
            sds_config:
              path: "/etc/envoy/hmac.yaml"
        # (Optional): defaults to 'user' scope if not provided
        auth_scopes:
          - user
          - openid
          - email
        # (Optional): set resource parameter for Authorization request
        resources:
          - oauth2-resource
          - http://example.com
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: example
spec:
  parentRefs:
    - name: eg
  hostnames:
    - www.example.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /foo
      filters:
        - type: ExtensionRef
          extensionRef:
            group: cilium.io
            kind: CiliumEnvoyHTTPFilter
            name: oauth2-example
      backendRefs:
        - name: backend
          port: 3000
```
The ergonomics of this are much better, and is, from what I understand, what the `ExtensionRef` system was created for.
