### ISSUE TITLE
Gateway API: "spec.infrastructure" doesn't work as expected since 1.15.0

### ISSUE THREAD

**Issue by Smana** [cilium/cilium#30590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello, I just upgraded the Cilium version to 1.15.0 in order to remove a [hack with Kyverno](https://github.com/cilium/cilium/issues/27493#issuecomment-1685380426) that allowed to add annotations to the LoadBalancer service.
Fortunately, with the 1.15 version, it should be possible to use `spec.infrastructure` for that.

```yaml
 infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: gitops-${cluster_name}.priv.${domain_name}
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: TCP
```

The gateways stays in the status `Unknow` and cilium LoadBalancer **services are not created anymore**.

```console
kubectl get gateway -n infrastructure 
NAME               CLASS    ADDRESS   PROGRAMMED   AGE
platform-private   cilium             Unknown      7m59s
platform-public    cilium             Unknown      7m59s
```

I [discussed on Slack](https://cilium.slack.com/archives/C1MATJ5U5/p1706736683267539) about this, and we double checked that I was using the proper version of the Gateway API CRDs (experimental)

* [Here is the PR ](https://github.com/Smana/demo-cloud-native-ref/pull/108) I'm working on.
* The [Helm values](https://github.com/Smana/demo-cloud-native-ref/blob/main/terraform/eks/helm_values/cilium.yaml) used to deploy Cilium. 

Let me know if you need any further details.

Regards,
Smana

### Cilium Version

```console
helm list -n kube-system | grep cilium
cilium                          kube-system     1               2024-02-01 09:11:10.614174978 +0100 CET deployed        cilium-1.15.0                        1.15.0
```

```console
kubectl get ds -o wide -n kube-system cilium
NAME     DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE   CONTAINERS     IMAGES                                                                                                  SELECTOR
cilium   3         3         3       3            3           kubernetes.io/os=linux   17m   cilium-agent   quay.io/cilium/cilium:v1.15.0@sha256:9cfd6a0a3a964780e73a11159f93cc363e616f7d9783608f62af6cfdf3759619   k8s-app=cilium
```

### Kernel Version

the one used on amazon linux EKS, (I'm gonna update this issue as soon as I have a new cluster running)

### Kubernetes Version

1.29 (eks)

### Sysdump

[cilium-sysdump-20240206-084722.zip](https://github.com/cilium/cilium/files/14176256/cilium-sysdump-20240206-084722.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
