### ISSUE TITLE
Prometheus can't scrape serviceMonitor job

### ISSUE THREAD

**Issue by HsiuyaTsao** [cilium/cilium#30594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello , I am following the instructions on the docs https://docs.cilium.io/en/stable/observability/metrics/#cilium-metrics

When I install cilium and trying to enable Monitoring & Metric, instead of scrape_configs, I found that serviceMonitor can't be scaped by prometheus. 

Here's my install command
`helm upgrade --install cilium cilium/cilium --version 1.14.5 --namespace kube-system -f values.yaml`

Here's my values.yaml
```yaml
hubble:
  enabled: true

  relay:
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true

  metrics:
    serviceMonitor:
      enabled: true

    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - tcp
      - flows-to-world
      - port-distribution
      - icmp
      - "flow:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

operator:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
```

### Cilium Version

1.14.0

### Kernel Version

5.15.0-91-generic

### Kubernetes Version

1.27

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
