### ISSUE TITLE
Node lost all network connectivity on agent stop (and restart)

### ISSUE THREAD

**Issue by Jean-Daniel** [cilium/cilium#30609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm running cilium in a self-hosted Kubernetes cluster, and as soon as a cilium agent is stopped, the corresponding node lost all connectivity.

The only way I found to restore the network connectivity was to remove the tc filters (`knet-cluster` is a simple eth device renamed at boot time):

```
tc filter del dev knet-cluster egress
tc filter del dev knet-cluster ingress
```

As the node has no connectivity at all, trying to restart a cilium-agent make it loop indefinitely waiting to `Establishing connection to apiserver" host="https://master.k8s:6443`.

Tell me what you need that may help you reproduce/understand the issue ? 

### Cilium Version

Client: 1.15.0 2db45c46 2024-01-31T18:58:02+01:00 go version go1.21.6 linux/amd64
Daemon: 1.15.0 2db45c46 2024-01-31T18:58:02+01:00 go version go1.21.6 linux/amd64

### Kernel Version

`Linux worker-3.cluster 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

or 

`Linux master-1.cluster 6.5.0-15-generic #15~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 12 18:54:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

```
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.6
```

### Sysdump

sysdump contains only one node cilium-bugtool report to fit size, but the bug occurs on all nodes.

[cilium.tgz](https://github.com/cilium/cilium/files/14145201/cilium.tgz)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@Jean-Daniel thank you for opening the GH issue
> Tell me what you need that may help you reproduce/understand the issue ?

A reproducible with steps would be appreciated. Thank you!

**Comment by Jean-Daniel** [comment]
I was waiting to make sure the upgrade to 1.15 did not solved my issue.

I'm working on a reduced setup that reproduce this issue and will let you know.

**Comment by Jean-Daniel** [comment]
### Create a single node k8s cluster

Create a KVM virtual machine with a single eth port and running Ubuntu 22.04

Install `cri-o` from `https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.28/xUbuntu_22.04/`

Install `cri-o-runc` from `https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/`


### Create an external api server load balancer

Deploy a simple TCP proxy (nginx, haproxy, …) that redirect https traffic to the cluster node from elsewhere (`kube-lb.lan` in this setup).


### Deploy a single node k8s cluster using kubeadm on the VM

```
kubeadm init --config kubeadm.yaml --ignore-preflight-errors=Swap --upload-certs
```

using the following kubeadm.yaml file

```
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "10.65.0.51"
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/crio/crio.sock
  imagePullPolicy: IfNotPresent
  kubeletExtraArgs:
    node-ip: "10.65.0.51"
skipPhases:
- addon/kube-proxy
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
apiServer:
  certSANs:
    - "kube-lb.lan"
    - "10.65.0.50"
  extraArgs:
    bind-address: "::"

controllerManager:
  extraArgs:
    cluster-cidr: "10.192.0.0/16"

etcd:
  local:
    dataDir: /var/lib/etcd

featureGates:
  PublicKeysECDSA: true
  RootlessControlPlane: true

networking:
  serviceSubnet: "10.196.0.0/16"

---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
featureGates:
  NodeSwap: true
cgroupDriver: systemd
failSwapOn: false
address: "::"
```


### Deploy Cilium


```
cilium install --version 1.15.0 --values cilium.yaml
```

cilium.yaml:

```
k8sServiceHost: "kube-lb.lan"
k8sServicePort: 443

bpf:
  autoMount:
    enabled: false

hubble:
  enabled: false

ipam:
  operator:
    clusterPoolIPv4PodCIDRList: ["10.192.0.0/16"]
    clusterPoolIPv4MaskSize: 24

kubeProxyReplacement: "true"

routingMode: "native"

ipv4NativeRoutingCIDR: "10.192.0.0/16"

operator:
  replicas: 1

```


### Try to restart cilium agent

```
kubectl -n kube-system rollout restart daemonset cilium
```

The cilium agent is stopped, and the node lost all network connectivity.
cilium try to restart but loop try to reconnect to the api-server

```
Establishing connection to apiserver" host="https://kube-lb.lan
```

To restore network connectivity run the following command

```
tc filter del dev enp1s1 egress
```

### Other Information

I also attach a sysdump of cilium deployed using this simple setting.
[cilium-sysdump-20240205-125544.zip](https://github.com/cilium/cilium/files/14165232/cilium-sysdump-20240205-125544.zip)
