### ISSUE TITLE
CFP: Expose configurable Envoy Access Logs for L7 observability and Gateway API

### ISSUE THREAD

**Issue by bdecoste** [cilium/cilium#30667]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

Unable to expose or configure the Envoy Access Logs described here: https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage

Enabling debug logging is too verbose for use in a production environment, but require the ability to track Envoy on a per-request basis. 

**Describe the feature you'd like**

Expose configurable Envoy Access Logs for L7 observability and Gateway API

**(Optional) Describe your proposed solution**

Add Helm values for configurable (i.e. be able to configure specific access log operators, json or string format, etc) Envoy access logging.

**Comment by jmenan** [comment]
Hello
Is this CFP planned?

regards

**Comment by samyakjain-sib** [comment]
Hello,

We also have the requirement for shipping the access logs. Do we have any ETA on this?

Thanks!

**Comment by alb-dev** [comment]
It would be create if could have access logs indeed. One criteria for us is to track access on cluster entry and not on applicationlevel

**Comment by shenshouer** [comment]
Any plan for access log?

**Comment by infakt-pk** [comment]
This feauture would be much appreciated especially in world without ingress-nginx

**Comment by bilkoua** [comment]
We’re still waiting

**Comment by kposborne** [comment]
A decent workaround is using hubble export for these flow logs, when configured like this, they appear in the cilium pod stdout as json: (see https://github.com/cilium/cilium/issues/31357#issuecomment-3746772007 for reference)
```
    hubble:  
      export:
        dynamic:
          enabled: true
          config:
            enabled: true
            content:
              # https://docs.cilium.io/en/stable/_api/v1/flow/README/
              - name: "l7-http-stdout"
                filePath: "/dev/stdout"
                # imaginative value for stream to not rotate /dev/stdout
                fileMaxSizeMb: 2137
                fileMaxBackups: 0
                fieldMask:
                  - time
                  - verdict
                  - IP
                  - l7.type
                  - l7.latency_ns
                  - l7.http.code
                  - l7.http.method
                  - l7.http.url
                  - l7.http.protocol
                  - Summary
                  - destination.pod_name
                  - destination.namespace
                  - source.pod_name
                  - source.namespace
                # https://github.com/cilium/cilium/blob/main/pkg/monitor/api/types.go#L51
                includeFilters:
                  - event_type:
                      - type: 129
```
