### ISSUE TITLE
Transparent encryption changes pod network behavior on k8s foreground delete

### ISSUE THREAD

**Issue by khartld** [cilium/cilium#30683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

With enabled encryption, if a pod is deleted with foreground deletion (background deletion does not cause this), the terminating pod is immediately isolated from pods running on other worker nodes.
The expected standard behavior would be that the pod is still able to connect to other pods during the shutdown grace period. This is necessary in some cases to gracefully complete or offload work.

To replicate this, you can create some k8s cluster with and without encryption enabled and a pod setup, where one pod continuously tries to connect to another pod running on a different node. Then delete the pod which connects to the other pod with foreground deletion and observe that the terminating pod is not able to reach the other pod anymore.

This was my test setup:
```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: curl-test-deployment
  labels:
    app: curl-test
    curl-test: curl-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-test
  template:
    metadata:
      labels:
        app: curl-test
    spec:
      affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: curl-test
                  operator: In
                  values:
                  - curl-test
              topologyKey: "kubernetes.io/hostname"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 40
      containers:
        - name: ping-container
          ports:
          - containerPort: 8080
          image: quay.io/cilium/alpine-curl:v1.5.0@sha256:7b286939730d8af1149ef88dba15739d8330bb83d7d9853a23e5ab4043e2d33c
          env:
            - name: CURL_TARGET
              value: nginx-service:80
          command: ["/bin/sh"]
          args: ["-c", "while true; do curl -sS --fail --connect-timeout 5 $CURL_TARGET; sleep 1;  done;"]
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 500Mi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: proxy
    curl-test: curl-test
spec:
  affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: curl-test
              operator: In
              values:
              - curl-test
          topologyKey: "kubernetes.io/hostname"
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-web-svc
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 500m
        memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
```

### Cilium Version

1.14.6

### Kernel Version

Linux 6.5.0-14-generic #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.26.10 & v1.27.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@khartld can you share how you are installing Cilium?

**Comment by khartld** [comment]
In my local tests I created a kind cluster with config
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
#networking:
  disableDefaultCNI: true   # do not install kindnet
  kubeProxyMode: none       # do not run kube-proxy
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
```

And installed Cilium via helm via helm with these values:
 ```
 image:
  pullPolicy: IfNotPresent
ipam:
  mode: kubernetes

# required for runnig without kube-proxy
kubeProxyReplacement: strict
k8sServiceHost: kind-control-plane # use master node in kind network
k8sServicePort: 6443               # use api server port

l7Proxy: false # does not cause problem, but is required for wireguard
encryption:
  enabled: true
  type: wireguard
 ```

Not completely sure about our production setup, but there we also use the helm chart in combination with ArgoCD
