### ISSUE TITLE
single ip allocation and use of multiple ports on multiple service not working as expected

### ISSUE THREAD

**Issue by vstoppe** [cilium/cilium#30692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am testing out ippools, single ip allocation to multiple services and using multiple ports on a single loadbalancer ip. I started with pihole dns/dhcp and reduced the problem to minimal manifests. Even when staying close to the examples in the [documentation](https://docs.cilium.io/en/stable/network/lb-ipam/) nothing works as expected. Do I overlook something, or have I found an error in an untested software constellation? I saved all manifests in a [public github repo](https://github.com/vstoppe/cilium-service-test).

Quick summery:
* lbipam.cilium.io/ips does not allocate same ips
* .spec.loadBalancerIP and lbipam.cilium.io/sharing-key lead to already_allocated failure

Installation parameters for K3s: 
```
export INSTALL_K3S_EXEC="--disable servicelb --disable=traefik --flannel-backend=none --disable-network-policy --disable-kube-proxy"
```

My helm manifest for cilium:

```yaml
repo: https://helm.cilium.io
chart: cilium
targetNamespace: kube-system
version: 1.15.0
bootstrap: true
valuesContent: |-
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true
ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
policyEnforcementMode: "default"
hostFirewall:
  enabled: false
operator:
  replicas: 1
nodeinit:
  enabled: true
nodePort:
  enabled: true # <= necessary for cilium ingress
  enableHealthCheck: true

kubeProxyReplacement: true
k8sServiceHost: 10.1.1.4
k8sServicePort: 6443
l7Proxy: true  # <== for cilium ingress

l2announcements:
  enabled: true
```

My ippool:

```yaml
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "service-net-services"
spec:
  blocks:
  - cidr: "20.0.10.0/29"
  serviceSelector:
    matchLabels:
      service: net
```

Now I define two services which share an ip but use different ports:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: service-dhcp
  namespace: service-test
  labels:
    service: net
  annotations:
    lbipam.cilium.io/sharing-key: service
    lbipam.cilium.io/ips: 20.0.10.1
spec:
  type: LoadBalancer
  ports:
  - port: 67
    protocol: UDP
```

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: service-dns
  namespace: service-test
  labels:
    service: net
  annotations:
    lbipam.cilium.io/sharing-key: service
    lbipam.cilium.io/ips: 20.0.10.1
spec:
  type: LoadBalancer
  ports:
  - port: 53
    protocol: UDP
```

The result looks quite suprising for me, because I would expect the use of one ip for both services:

```
kubectl get services
NAME           TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
service-dns    LoadBalancer   10.43.151.131   20.0.10.1     53:31384/UDP   34m
service-dhcp   LoadBalancer   10.43.219.110   20.0.10.2     67:30295/UDP   22m
```

Btw: If I activate another ippool without a serivceSelector one of the services gets an ip the other pool!

It gets even more interesting when I switch the ip allocation from the annotation "lbipam.cilium.io/ips:" to the deprecated .spec.loadBalancerIP method:

```
NAME           TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
service-dhcp   LoadBalancer   10.43.126.5   20.0.10.1     67:30425/UDP   26s
service-dns    LoadBalancer   10.43.29.55   <pending>     53:30886/UDP   23s
```

While the service-dhp has the following status:

```
  - lastTransitionTime: "2024-02-09T19:54:14Z"
    message: ""
    reason: satisfied
    status: "True"
    type: cilium.io/IPAMRequestSatisfied
  loadBalancer:
    ingress:
    - ip: 20.0.10.1
```

The service-dns is conflicting:

```
  - lastTransitionTime: "2024-02-09T19:54:17Z"
    message: The IP '20.0.10.1' is already allocated to another service
    reason: already_allocated
    status: "False"
    type: cilium.io/IPAMRequestSatisfied
```

Am I missing something or do we have an odd constellations of software/versions?

### Cilium Version

cilium-cli: 0.15.12 compiled with go1.21.4 on darwin/amd64
cilium image (default): v1.14.2
cilium image (stable): v1.14.6
cilium image (running): 1.15.0

### Kernel Version

Linux irix 6.1.0-16-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5+k3s1

### Sysdump

🔍 Collecting sysdump with cilium-cli version: 0.15.12, args: [sysdump]
🔮 Detected Cilium installation in namespace "kube-system"
🔮 Detected Cilium operator in namespace "kube-system"
ℹ️ Failed to detect Cilium SPIRE installation - using Cilium namespace as Cilium SPIRE namespace: kube-system
🔍 Collecting Kubernetes nodes
🔮 Detected Cilium features: map[cidr-match-nodes:Disabled cni-chaining:Disabled:none enable-envoy-config:Enabled enable-gateway-api:Disabled enable-ipv4-egress-gateway:Disabled endpoint-routes:Disabled ingress-controller:Enabled ipv4:Enabled ipv6:Disabled mutual-auth-spiffe:Disabled wireguard-encapsulate:Disabled]
🔍 Collect Kubernetes nodes
🔍 Collecting Kubernetes events
🔍 Collecting Kubernetes pods
🔍 Collecting Kubernetes services
🔍 Collecting Kubernetes pods summary
🔍 Collect Kubernetes version
🔍 Collecting Kubernetes namespaces
🔍 Collecting Kubernetes network policies
🔍 Collecting Kubernetes endpoints
🔍 Collecting Kubernetes metrics
🔍 Collecting Kubernetes leases
🔍 Collecting Cilium network policies
🔍 Collecting Cilium cluster-wide network policies
🔍 Collecting Cilium Egress Gateway policies
🔍 Collecting Cilium egress NAT policies
🔍 Collecting Cilium CIDR Groups
🔍 Collecting Cilium local redirect policies
🔍 Collecting Cilium endpoint slices
🔍 Collecting Cilium endpoints
🔍 Collecting Cilium nodes
🔍 Collecting Cilium identities
🔍 Collecting Cilium Node Configs
🔍 Collecting Ingresses
🔍 Collecting IngressClasses
🔍 Collecting Cilium BGP Peering Policies
🔍 Collecting Cilium LoadBalancer IP Pools
🔍 Collecting Cilium Pod IP Pools
🔍 Checking if cilium-etcd-secrets exists in kube-system namespace
🔍 Collecting the Cilium configuration
🔍 Collecting the Cilium daemonset(s)
🔍 Collecting the Cilium Node Init daemonset
🔍 Collecting the Cilium Envoy configuration
🔍 Collecting the Cilium Envoy daemonset
🔍 Collecting the Hubble daemonset
🔍 Collecting the Hubble Relay configuration
🔍 Collecting the Hubble Relay deployment
🔍 Collecting the Hubble UI deployment
🔍 Collecting the Cilium operator metrics
🔍 Collecting the Cilium operator deployment
🔍 Collecting the clustermesh metrics
🔍 Collecting the 'clustermesh-apiserver' deployment
🔍 Collecting the CNI configmap
🔍 Collecting the CNI configuration files from Cilium pods
🔍 Collecting gops stats from Cilium pods
🔍 Collecting gops stats from Hubble pods
🔍 Collecting gops stats from Hubble Relay pods
⚠️ Daemonset "cilium-envoy" not found in namespace "kube-system" - this is expected if Envoy DaemonSet is not enabled
🔍 Collecting bugtool output from Cilium pods
🔍 Collecting profiling data from Cilium pods
🔍 Collecting logs from Cilium pods
🔍 Collecting logs from Cilium Envoy pods
🔍 Collecting logs from Cilium Node Init pods
🔍 Collecting logs from Cilium operator pods
⚠️ Deployment "clustermesh-apiserver" not found in namespace "kube-system" - this is expected if 'clustermesh-apiserver' isn't enabled
🔍 Collecting logs from 'clustermesh-apiserver' pods
🔍 Collecting logs from Hubble pods
🔍 Collecting logs from Hubble Relay pods
Secret "cilium-etcd-secrets" not found in namespace "kube-system" - this is expected when using the CRD KVStore
🔍 Collecting logs from Hubble UI pods
I0209 21:15:39.921495   22359 request.go:697] Waited for 1.055431075s due to client-side throttling, not priority and fairness, request: GET:https://irix:6443/api/v1/namespaces/kube-system/configmaps/cilium-envoy-config
🔍 Collecting platform-specific data
🔍 Collecting kvstore data
🔍 Collecting Cilium external workloads
🔍 Collecting Hubble flows from Cilium pods
🔍 Collecting bugtool output from Tetragon pods
🔍 Collecting Tetragon PodInfo custom resources
🔍 Collecting Tetragon tracing policies
🔍 Collecting Helm values from the release
🔍 Collecting CiliumClusterwideEnvoyConfigs
🔍 Collecting CiliumEnvoyConfigs
⚠️ The following tasks failed, the sysdump may be incomplete:
⚠️ [13] Collecting Cilium egress NAT policies: failed to collect Cilium egress NAT policies: the server could not find the requested resource
⚠️ [14] Collecting Cilium Egress Gateway policies: failed to collect Cilium Egress Gateway policies: the server could not find the requested resource (get ciliumegressgatewaypolicies.cilium.io)
⚠️ [16] Collecting Cilium local redirect policies: failed to collect Cilium local redirect policies: the server could not find the requested resource (get ciliumlocalredirectpolicies.cilium.io)
⚠️ [18] Collecting Cilium endpoint slices: failed to collect Cilium endpoint slices: the server could not find the requested resource (get ciliumendpointslices.cilium.io)
⚠️ [24] Collecting Cilium BGP Peering Policies: failed to collect Cilium BGP Peering policies: the server could not find the requested resource (get ciliumbgppeeringpolicies.cilium.io)
⚠️ [31] Collecting the Cilium Envoy configuration: failed to collect the Cilium Envoy configuration: configmaps "cilium-envoy-config" not found
⚠️ [61] Collecting Tetragon PodInfo custom resources: failed to collect Tetragon PodInfo: the server could not find the requested resource (get podinfo.cilium.io)
⚠️ [62] Collecting Tetragon tracing policies: failed to collect Tetragon tracing policies: the server could not find the requested resource (get tracingpolicies.cilium.io)
⚠️ Please note that depending on your Cilium version and installation options, this may be expected
🗳 Compiling sysdump
✅ The sysdump has been saved to cilium-sysdump-20240209-211538.zip

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Seems similar to #30700. Marking for folks to review.

**Comment by HungrySharkNet** [comment]
Everything turned out to be prosaically simple. You, like me, looked at the latest documentation, but you need stable.
I'm using version 1.15.4 and the annotation "io.cilium/lb-ipam-sharing-key: default" worked for me

In the latest, “lbipam.cilium.io/sharing-key” is indicated: “1234” and it doesn’t work (that’s exactly what I have)

**Comment by HungrySharkNet** [comment]
And sharing-key only works starting from version 1.16 (it is now in dev)

**Comment by usma0118** [comment]
facing same on 1.16.2.

```
    io.cilium/lb-ipam-sharing-key: "pi-hole"
    io.cilium/lb-ipam-ips: "192.100.1.152"

    lbipam.cilium.io/sharing-key: "pi-hole"    
    lbipam.cilium.io/ips: "192.100.1.152"
```

Trying with both annotations... 

```
status:
  conditions:
  - lastTransitionTime: "2024-09-29T17:09:12Z"
    message: The IP '192.100.1.152' is already allocated to another service with a
      different sharing key
    reason: already_allocated_different_sharing_key
    status: "False"
    type: cilium.io/IPAMRequestSatisfied
  loadBalancer: {}
```
