### ISSUE TITLE
Load balancer services with shared key was not taken in consider when Cilium reconcile during initial state

### ISSUE THREAD

**Issue by stevefan1999-personal** [cilium/cilium#30700]
>A real world example would be adding two services with a shared key by annotating the services with the same value on `io.cilium/lb-ipam-sharing-key`. Then you would confirm that the two services are sharing the same IP.
After restarting Cilium (for example, node reboot), then the external IP sharing is suddenly lost, even though they are listening on different ports.

_Originally posted by @stevefan1999-personal in https://github.com/cilium/cilium/issues/30078#issuecomment-1936966801_

Reproduction steps:
1. Create a simple Nginx service, e.g.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
  annotations:
    io.cilium/lb-ipam-sharing-key: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
```
Duplicate another yaml that uses the same sharing key but different ports:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-8080
  namespace: default
  labels:
    app: nginx
  annotations:
    io.cilium/lb-ipam-sharing-key: default
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
```
2. Ensure that the behavior is correct, i.e. both load balancer services are sharing the same IP
3. Restart Cilium
4. Expect to see the IPs are still shared, but actual behavior is that the IP has been exhausted and no allocation is available

It is suspected that this would only happen on single node Kubernetes, as Cilium itself runs as a DaemonSet, and while the sharing key state might be replicated to other daemon sets on different nodes, it might just work as usual under the radar.

So, this is probably a special case, since having a single node means all the shared memory would be gone. 

It is suggested to have a CiliumLoadBalancerIPAllocation CRD to save that information down as a recovery or do full rescanning of load balancers annotations, if that is the case.

As full restart of Cilium is a pretty common operation (e.g. Node maintenance, eviction, Cilium helm chart upgrade), I think this problem can plague many small K8S hosters (like me) to not expect the service gone down due to host rebooting.
