### ISSUE TITLE
CiliumEgressGatewayPolicy seems not working as expected with IPSec VPN.

### ISSUE THREAD

**Issue by surryr** [cilium/cilium#30747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Egress traffic is not going through the expected IP address. 

Cillium is install with the following command (to on-prem k0s cluster with single node for the test purposes).
```
helm upgrade cilium cilium/cilium \
   --namespace kube-system \
   --reuse-values \
   --version 1.15.0 \
   --set egressGateway.enabled=true \
   --set bpf.masquerade=true \
   --set k8sNetworkPolicy.enabled=false \
   --set kubeProxyReplacement=true \
   --set operator.replicas=1 \
   --set enableCiliumEndpointSlice=false \
   --set l7Proxy=false
```

`cilium-dbg bpf egress list` Reports expected status. 
```
Source IP   Destination CIDR   Egress IP      Gateway IP
10.0.0.83   10.99.6.101/32     172.18.157.1   x.x.x.x
```

where x.x.x.x is correct node IP

`CiliumEgressGatewayPolicy`

```
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egress-policy
spec:
  selectors:
  - podSelector:
      matchLabels:
        app: someapp
  destinationCIDRs:
  - "10.99.6.101/32"
  egressGateway:
    nodeSelector:
      matchLabels:
        kubernetes.io/hostname: node.hostname
    egressIP: 172.18.157.1
```

Network interface (second IP is ipsec tunnel to the external network):
```
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether fa:16:3e:4e:84:c5 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    inet x.x.x.x/32 metric 100 scope global dynamic ens3
       valid_lft 86232sec preferred_lft 86232sec
    inet 172.18.157.1/32 brd 172.18.157.1 scope global ens3
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:fe4e:84c5/64 scope link
       valid_lft forever preferred_lft forever
```

I have installed route on the node as well: `ip route add 10.99.6.101 via 172.18.157.1 dev ens3` 
As the result I can run telnet from the node itself. 
`telnet 172.18.157.1 9130`
But the same command times out when I'm trying to do the same from the pod with ip `10.0.0.83`.

### Cilium Version

```
cilium-cli: v0.15.22 compiled with go1.21.6 on darwin/arm64
cilium image (default): v1.15.0
cilium image (stable): v1.14.6
cilium image (running): 1.15.0
```

### Kernel Version

```
Linux hostname 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

k version
```
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.6+k0s
```

This is on-premise k0s installation.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Thanks for this report @surryr.

Would you please be able to upload a sysdump (as in https://docs.cilium.io/en/stable/operations/troubleshooting/#reporting-a-problem )? Then I can mark this for the right team's attention.

**Comment by surryr** [comment]
Hi
Please find the sysdump attached
[cilium-sysdump-20240214-141921.zip](https://github.com/cilium/cilium/files/14279875/cilium-sysdump-20240214-141921.zip)

**Comment by surryr** [comment]
I also tried to change a bit my configuration on the node. Instead of having 2 ip address on the network interface, I have created separate interface:
```
ip addr show vtilwp
4: vtilwp@NONE: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip a.a.a.a peer b.b.b.b
    inet 172.18.157.1/32 scope global vtilwp
       valid_lft forever preferred_lft forever
    inet6 fe80::200:5efe:c6f4:96af/64 scope link
       valid_lft forever preferred_lft forever
```
and change Policy accordingly:
```
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: lwp-connection-policy
spec:
  selectors:
  - podSelector:
      matchLabels:
        route: lwp
  destinationCIDRs:
  - "10.99.6.101/32"
  egressGateway:
    nodeSelector:
      matchLabels:
        kubernetes.io/hostname: node.hostname
    interface: vtilwp
```
I can do telnet from the node directly after adding appropriate route. But I still can't access target ip from the pod.
