### ISSUE TITLE
ToFQDN: consider shortcutting wildcard selector

### ISSUE THREAD

**Issue by squeed** [cilium/cilium#30810]
Consider this CiliumNetwokPolicy.

```yaml
spec:
  egress:
    - toFQDNs:
      - matchPattern: '*'
```

This will cause an identity to be allocated for every IP ever resolved by the subject pod(s). This is mostly needless; all traffic is allowed (as long as it was looked up by DNS first). We should consider replacing this with a `toEntities: ["world"]` selector.

The only disadvantage is that the above policy does require a DNS request before allowing traffic to an IP in question, whereas an allow-all-world policy would not.
