### ISSUE TITLE
Ingress Network Policy drop connection between pods

### ISSUE THREAD

**Issue by aminmr** [cilium/cilium#30825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I used the network policy on version 1.14.4 and everything works fine. But after upgrading to version 1.15.x  then network policy not working fine and drop connection between pods in one namespace. This is a sample network policy that causes this problem:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace-communication
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
   - from:
     - namespaceSelector:
         matchLabels:
           kubernetes.io/metadata.name: ingress-nginx
       podSelector:
         matchLabels:
           app.kubernetes.io/instance: ingress-nginx
```
Exactly I think the section podSelector: {} caused this problem because deleting the section related to ingress-nginx the problem still appears

### Cilium Version

1.14.4
1.15.x(1.15.0,1.15.1)

### Kernel Version

5.10.0-26-amd64

### Kubernetes Version

1.25.6

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
