### ISSUE TITLE
Cilium l2announce creates unnesesary leases for services without LoadBalancerIP or ExternalIP

### ISSUE THREAD

**Issue by adippl** [cilium/cilium#30841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium installed with l2announcements.enabled=true creates `cilium-l2announce` lease for every service in the cluster despite only 2 services having LoadBalancerIP.
This creates a lot of excessive load on the api. I assume it's unintentional bug.

relevant helm values
```
l2announcements:
  enabled: true
l2podAnnouncements:
  enabled: false
k8sClientRateLimit:
  qps: 50
  burst: 100
```
https://docs.cilium.io/en/v1.14/network/l2-announcements/#sizing-client-rate-limit 
Documentation mentions rising k8sClientRateLimit but I didn't expect that I would have to size it including services which are not even announced via l2.  

Number of all services in cluster
```
# kubectl get svc -A --no-headers |wc -l
51
```

Cilium creates lease for every service
```
# kubectl -n kube-system get lease |grep cilium-l2announce |wc -l
51
```
Only 2 services actually need to be announced and would require a lock
```
kubectl get svc -A |grep LoadBalancer |wc -l
2
```

### Cilium Version

1.14.7

### Kernel Version

Linux ghw-kw1 6.6.13-gentoo-dist #1 SMP PREEMPT_DYNAMIC Sat Jan 20 14:30:33 -00 2024 x86_64 Intel(R) N100 GenuineIntel GNU/Linux

### Kubernetes Version

Client Version: v1.28.5
Server Version: v1.28.2

### Anything else?

Full cilium helm values file:
```
cluster:
  name: kubernetes
kubeProxyReplacement: true
k8sServiceHost: 10.0.5.90
k8sServicePort: 6443

operator:
  replicas: 1
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
tunnelProtocol: vxlan
encryption:
  enabled: true
  type: wireguard
  nodeEncryption: true

hubble:
  peerService:
    clusterDomain: k8s3.acmelab.top
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      className: "cilium"
      hosts:
        - hubble.k8s3.test.cluster
      labels: {}
      tls: 
       - secretName: hubble.k8s3.test.cluster
         hosts:
           - hubble.k8s3.test.cluster

dashboards:
  enabled: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      prometheus: main


ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  service:
    loadBalancerIP: 10.0.5.68

ipam:
  mode: "cluster-pool"
  ciliumNodeUpdateRate: "15s"
  operator:
    clusterPoolIPv4PodCIDRList: ["10.206.0.0/16"]
    clusterPoolIPv4MaskSize: 24

ipv4:
  enabled: true
ipv6:
  enabled: false

hostFirewall:
extraConfig:
hostServices:
  enabled: true
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true


l2announcements:
  enabled: true
l2podAnnouncements:
  enabled: false
k8sClientRateLimit:
  qps: 50
  burst: 100
  ```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
