### ISSUE TITLE
CFP: ClusterIP advertisement with BGP Control Plane

### ISSUE THREAD

**Issue by YutaroHayakawa** [cilium/cilium#30875]
## Cilium Feature Proposal

Support advertising ClusterIP with BGP Control Plane        

**Is your proposed feature related to a problem?**

Currently, the BGP Control Plane is missing the support of the ClusterIP advertisement. While ClusterIP is not intended to be used for NS load balancing, there are several implementations that support that (e.g., Calico, KubeRouter). Having ClusterIP support helps users migrate from existing implementations.

Also, Cilium already supports NS load balancing with ClusterIP from the data plane's perspective (https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#external-access-to-clusterip-services) but is missing a control plane to make connectivity.

**Describe the feature you'd like**

Support advertising ClusterIP of the Services with BGP Control Plane.

**(Optional) Describe your proposed solution**

Extend the existing `CiliumBGPPeeringPolicy` like the following:

```yaml
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
spec:
  nodeSelector:
    matchLabels:
      rack: rack0
  virtualRouters:
  - localASN: 64512
    exportClusterIP: true <= New
    serviceSelector:
      matchLabels:
        app: foo
    neighbors:
    - peerAddress: '10.0.0.1/32'
      peerASN: 64512
```

~~When the `exportClusterIP` flag is set to `true`, Cilium advertises all ClusterIPs (as a /32 for IPv4 and /128 for IPv6) assigned to the Services selected with `serviceSelector` and the existing Type Load Balancer ingress IP advertisement. While the existing `serviceSelector` only works for the Type Load Balancer services, it should also work for `ClusterIP` and `NodePort` services.~~

Now, this one is the most preferable option: https://github.com/cilium/cilium/issues/30875#issuecomment-1959024146

**Discussion**

With the interface described above, there's no way to disable ClusterIP advertisement. Do we want to support such a feature? If so, how? As a reference, KubeRouter supports it with per Service annotation (https://github.com/cloudnativelabs/kube-router/blob/master/docs/user-guide.md#advertising-ips).

**Comment by rastislavs** [comment]
I would have two topics for discussion related to this:

1. What about `NodePort` services, which automatically get `clusterIP` assigned as well? Should those be announced as well? To me it would make sense, as apart from allocating nodeport, they work the same as `ClusterIP` services.

3. Should the `internalTrafficPolicy` configured on the `ClusterIP` service have any impact on BGP advertisements? Should it be handled the same as `externalTrafficPolicy` on `LoadBalancer` services? Maybe we should prevent routing traffic to nodes without endpoints in such case, to not cause drops:

> For pods on nodes with no endpoints for a given Service, the Service behaves as if it has zero endpoints (for Pods on this node) even if the service does have endpoints on other nodes.

(Source: https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/)

**Comment by YutaroHayakawa** [comment]
I agree that we should make it work with `NodePort` (I also mentioned it in the original desc). 

Also, I don't have any objection to supporting `internalTrafficPolicy`, but I would say it's not necessary from day1 and we can separate it into different task.

**Comment by YutaroHayakawa** [comment]
cc: @cilium/sig-bgp

**Comment by chaunceyjiang** [comment]
This is a very interesting feature, I want to try implementing this feature.

**Comment by YutaroHayakawa** [comment]
> Announcements of /32 networks are suitable for most cases, but I would like to be able to announce /24 /16 networks

Agree. However, the challenge here is obtaining the ClusterIP range assigned to the cluster. As far as I know, it only exists on the command line option of the API server, and it is hard to get it through API.

**Comment by YutaroHayakawa** [comment]
@chaunceyjiang Thanks! We first need to agree on API changes. After that, you can take an implementation task.

**Comment by YutaroHayakawa** [comment]
We can think of another API design like this.

```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
spec:
  nodeSelector:
    matchLabels:
      rack: rack0
  virtualRouters:
  - localASN: 64512
    serviceSelector:
      matchLabels:
        app: foo
    exportServiceClusterIP: # <= new
      selector:
        matchLabels:
          app: foo
    neighbors:
    - peerAddress: '10.0.0.1/32'
      peerASN: 64512
```

The benefit of this design is that users can choose which service can advertise LoadBalancer IP and which service can advertise ClusterIP. Also, it can be mapped naturally to the `CiliumBGPAdvertisement` resource of [BGPv2 API](https://docs.google.com/document/d/1mqmzlDeVKmNjsnDnnHTeoiW6JcItYMyDyuOM7SYoDi4/edit#heading=h.5mwz58y9syps). So, that would make migration easier.

**Comment by YutaroHayakawa** [comment]
Another idea would be

```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
spec:
  nodeSelector:
    matchLabels:
      rack: rack0
  virtualRouters:
  - localASN: 64512
    serviceSelector:
      matchLabels:
        app: foo
    serviceAdvertisements: <= new
    - LoadBalancerIP
    - ClusterIP
    neighbors:
    - peerAddress: '10.0.0.1/32'
      peerASN: 64512
```

And make only `LoadBalancerIP` a default. With this interface we can easily extend with [ExternalIP support](https://github.com/cilium/cilium/issues/29990#issuecomment-1955959190) as well.
