### ISSUE TITLE
Gateway API not passing TLS certificate

### ISSUE THREAD

**Issue by kenlasko** [cilium/cilium#30922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am testing switching from using Traefik to Cilium Gateway API, but I can't seem to get it working. The gateway is created properly with the appropriate certificate (tried both LetsEncrypt-generated and a Digicert cert). The route is created and the appropriate DNS entries are added via External-DNS, but whenever I try to go to a site, the certificate isn't being used.  This is similar to #29144 and #30720. Both of those started working on their own with seemingly no changes. I haven't been so lucky yet.  Everything seems to check out, but no dice.

This is a bare-metal installation on a brand-spanking new cluster using K3S on Ubuntu 22.04. 

### kubectl describe gateway tls -n cilium
```
Name:         tls
Namespace:    cilium
Labels:       app.kubernetes.io/instance=cilium
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1
Kind:         Gateway
Metadata:
  Creation Timestamp:  2024-02-22T20:52:47Z
  Generation:          10
  Resource Version:    342502
  UID:                 8a90c292-0dec-43e3-b603-cc0b76d5fbd2
Spec:
  Addresses:
    Type:              IPAddress
    Value:             192.168.1.14
  Gateway Class Name:  cilium
  Listeners:
    Allowed Routes:
      Namespaces:
        From:  All
    Hostname:  *.mydomain.com
    Name:      http
    Port:      80
    Protocol:  HTTP
    Allowed Routes:
      Namespaces:
        From:  All
    Hostname:  *.mydomain.com
    Name:      https
    Port:      443
    Protocol:  HTTPS
    Tls:
      Certificate Refs:
        Group:
        Kind:       Secret
        Name:       letsencrypt-wildcard-cert
        Namespace:  cilium
      Mode:         Terminate
Status:
  Addresses:
    Type:   IPAddress
    Value:  192.168.1.14
  Conditions:
    Last Transition Time:  2024-02-22T22:02:37Z
    Message:               Gateway successfully scheduled
    Observed Generation:   10
    Reason:                Accepted
    Status:                True
    Type:                  Accepted
    Last Transition Time:  2024-02-22T22:02:37Z
    Message:               Gateway successfully reconciled
    Observed Generation:   10
    Reason:                Programmed
    Status:                True
    Type:                  Programmed
  Listeners:
    Attached Routes:  0
    Conditions:
      Last Transition Time:  2024-02-22T22:02:37Z
      Message:               Listener Programmed
      Observed Generation:   10
      Reason:                Programmed
      Status:                True
      Type:                  Programmed
      Last Transition Time:  2024-02-22T22:02:37Z
      Message:               Listener Accepted
      Observed Generation:   10
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2024-02-22T22:02:37Z
      Message:               Resolved Refs
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Name:                    http
    Supported Kinds:
      Group:          gateway.networking.k8s.io
      Kind:           HTTPRoute
    Attached Routes:  1
    Conditions:
      Last Transition Time:  2024-02-22T22:02:37Z
      Message:               Listener Programmed
      Observed Generation:   10
      Reason:                Programmed
      Status:                True
      Type:                  Programmed
      Last Transition Time:  2024-02-22T22:02:37Z
      Message:               Listener Accepted
      Observed Generation:   10
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2024-02-22T22:02:37Z
      Message:               Resolved Refs
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Name:                    https
    Supported Kinds:
      Group:  gateway.networking.k8s.io
      Kind:   HTTPRoute
Events:       <none>
```

### kubectl describe httproute falco -n falco
```
Name:         falco
Namespace:    falco
Labels:       app.kubernetes.io/instance=falco-security
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1
Kind:         HTTPRoute
Metadata:
  Creation Timestamp:  2024-02-22T21:47:59Z
  Generation:          1
  Resource Version:    331789
  UID:                 8d0500d3-ef93-4441-946a-a726f7aef02d
Spec:
  Hostnames:
    test-falco.mydomain.com
  Parent Refs:
    Group:         gateway.networking.k8s.io
    Kind:          Gateway
    Name:          tls
    Namespace:     cilium
    Section Name:  https
  Rules:
    Backend Refs:
      Group:
      Kind:       Service
      Name:       falco-security-falcosidekick-ui
      Namespace:  falco
      Port:       2802
      Weight:     1
    Matches:
      Path:
        Type:   PathPrefix
        Value:  /
Status:
  Parents:
    Conditions:
      Last Transition Time:  2024-02-22T21:47:59Z
      Message:               Accepted HTTPRoute
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2024-02-22T21:47:59Z
      Message:               Service reference is valid
      Observed Generation:   1
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Controller Name:         io.cilium/gateway-controller
    Parent Ref:
      Group:         gateway.networking.k8s.io
      Kind:          Gateway
      Name:          tls
      Namespace:     cilium
      Section Name:  https
Events:              <none>
```

```
$ curl -vi https://test-falco.mydomain.com:443
*   Trying 192.168.1.14:443...
* Connected to test-falco.mydomain.com (192.168.1.14) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to test-falco.mydomain.com:443
* Closing connection 0
* TLSv1.0 (OUT), TLS header, Unknown (21):
* TLSv1.3 (OUT), TLS alert, decode error (562):
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to test-falco.mydomain.com:443
```

```
$ openssl s_client -connect test-falco.mydomain.com:443
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 328 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
```

### Cilium Version

1.15.1

### Kernel Version

6.5.0-18-generic

### Kubernetes Version

Client Version: v1.28.7
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.6+k3s2

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanMnM** [comment]
@kenlasko any chance you have masquerading turned on firewall / firewalld side? Only reason i ask is i managed to fix an issue that gave me very similar results by turning that off on the nodes.

**Comment by kenlasko** [comment]
I don't have any firewall installed on Ubuntu. Its just a minimal server installation with only the basics installed to support K3S. However, I do have BPF masquerading on, which I believe is a requirement for eBPF functionality. Here's my ```values.yaml```, just in case its helpful. My original setup used ```native``` routingMode, but I changed it to ```tunnel``` so I could maintain source IP info for apps that need it (thanks to someone who posted in #27800:

```
rollOutCiliumPods: true
# routingMode: native             # Original
routingMode: tunnel               # New
tunnelProtocol: geneve            # New
ipv4NativeRoutingCIDR: 10.0.0.0/9
# autoDirectNodeRoutes: true      # Original
# tunnel: disabled                # Original
bpf:
  hostRouting: true
  masquerade: true
ipam:
  mode: kubernetes
cluster:
  name: home
  id: 0
loadBalancer:                     # New
  mode: dsr                       # New
  dsrDispatch: geneve             # New
l2announcements:
  enabled: true
  leaseDuration: 6s
  leaseRenewDeadline: 2s
  leaseRetryPeriod: 200ms
envoy:
  enabled: true
  rollOutPods: true
externalIPs:
  enabled: true
extraEnv:
- name: TZ
  value: "America/Toronto"
kubeProxyReplacement: true
k8sServiceHost: localhost
k8sServicePort: 6444

hubble:
  peerService:
    clusterDomain: cluster.local
  relay:
    enabled: true

  ui:
    enabled: true

gatewayAPI:
  enabled: true
  secretsNamespace:
    create: false
    name: cilium
    sync: false
```

**Comment by RyanMnM** [comment]
Strange, might be different to what i was getting then.

I'm on native routing and what i can only assume so far is that because i had BPF masquerading on as well as masquerading on my FW / network stack it was clashing there and giving me similar results to the issues here.

**Comment by kenlasko** [comment]
I'm assuming there's something with my config that's causing this. I even went through the lab examples which ended up with exactly the same behaviour.

**Comment by RyanMnM** [comment]
A few TCPDumps on the node(s) that hold the lease if you are announcing them and the one running the pod itself is what helped me narrow down the issue. Not sure if something similar can shine a light on something for you.

**Comment by kenlasko** [comment]
Thanks for the tips @RyanMnM. Unfortunately, neither a TCPDump or looking at the Cilium logs on the node advertising the IP address shows anything helpful.

**Comment by AnthonyPoschen** [comment]
@kenlasko i am experiencing identical issue to you. got the same results from your initial debug steps.

**Comment by kenlasko** [comment]
Glad I'm not the only one. Hopefully, others will chime in with similar experiences and start to attract some attention.

**Comment by kenlasko** [comment]
Finally solved this one! I had to add this to my gateway configuration under ```spec```:
```
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.1.14
```
As soon as I added this, everything worked as expected.  For reference, here's my entire working gateway config:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tls
  namespace: cilium
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.1.14
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    hostname: "*.mydomain.com"
    allowedRoutes: 
      namespaces:
        from: All
  - name: https
    protocol: HTTPS
    port: 443
    hostname: "*.mydomain.com"
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: letsencrypt-wildcard-cert
        namespace: cilium
    allowedRoutes: 
      namespaces:
        from: All
```
