### ISSUE TITLE
hubble-relay pod restarts, when hubble.tls.auto.method is certmanager

### ISSUE THREAD

**Issue by fmunteanu** [cilium/cilium#30941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I installed Cilium 1.15.1 with Helm on a k3s cluster with 8 nodes (3 cp + 5 workers), running on Ubuntu 22.04. Everything works as expected, except `hubble-relay` pod keeps on restarting, when I switch the `hubble.tls.auto.method` from `helm` to `certmanager`. I use the Cloudflare API to generate the certificates with a `ClusterIssuer`. The main problem is related to `hubble-relay-client-certs` secret missing two certificates, `tls.crt` and `ca.crt`, which explains why the `hubble-relay` pod restarts:

```
$ kubectl describe secret hubble-relay-client-certs-4wqx9 -n kube-system
Name:         hubble-relay-client-certs-4wqx9
Namespace:    kube-system
Labels:       cert-manager.io/next-private-key=true
              controller.cert-manager.io/fao=true
Annotations:  <none>

Type:  Opaque

Data
====
tls.key:  1704 bytes
```

### Cilium Install Steps
Install Cilium with Helm on a tainted k3s cluster, using the following chart values:

```
bgpControlPlane:
  enabled: true
enableCiliumEndpointSlice: true
envoy:
  enabled: true
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi
  rollOutPods: true
externalIPs:
  enabled: true
gatewayAPI:
  default: true
  enabled: true
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: 10.42.0.0/16
hubble:
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
k8sClientRateLimit:
  burst: 100
  qps: 50
k8sServiceHost: 127.0.0.1
k8sServicePort: 6444
kubeProxyReplacement: true
l2announcements:
  enabled: true
loadBalancer:
  l7:
    backend: envoy
operator:
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  rollOutPods: true
rollOutCiliumPods: true
```

Apply a `CiliumL2AnnouncementPolicy` and `CiliumLoadBalancerIPPool` manifest.

Install cert-manager, using the following chart values:

```
extraArgs:
  - --feature-gates=ExperimentalGatewayAPISupport=true
installCRDs: true
prometheus:
  serviceMonitor:
    enabled: true
    namespace: kube-system
```

On Cloudflare website, create an API token and set the correct permissions:

![image](https://github.com/cilium/cilium/assets/19806136/5925e4aa-5d66-4bcd-b1ae-72c7f7743e71)

Create a `cloudflare-api-token` secret and related `ClusterIssuer`:

```
$ kubectl describe ClusterIssuer -n kube-system
Name:         cloudflare-cluster-issuer
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  cert-manager.io/v1
Kind:         ClusterIssuer
Metadata:
  Creation Timestamp:  2024-02-24T04:00:37Z
  Generation:          1
  Resource Version:    2987
  UID:                 65e08959-ac23-41b2-8ba9-ad31c9f031fd
Spec:
  Acme:
    Email:  email@domain.com
    Private Key Secret Ref:
      Name:  cloudflare-tls-key
    Server:  https://acme-v02.api.letsencrypt.org/directory
    Solvers:
      dns01:
        Cloudflare:
          API Token Secret Ref:
            Key:   token
            Name:  cloudflare-api-token
Status:
  Acme:
    Last Private Key Hash:  [removed]
    Last Registered Email:  email@domain.com
    Uri:                    https://acme-v02.api.letsencrypt.org/acme/acct/[removed]
  Conditions:
    Last Transition Time:  2024-02-24T04:00:38Z
    Message:               The ACME account was registered with the ACME server
    Observed Generation:   1
    Reason:                ACMEAccountRegistered
    Status:                True
    Type:                  Ready
Events:                    <none>
```

Update the Cilium helm chart with the following options (`ingressController.loadbalancerMode` set by default to `dedicated`, `peerService.clusterDomain` set by default to `cluster.local`):

```
hubble:
  tls:
    auto:
      certManagerIssuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: cloudflare-cluster-issuer
      method: certmanager
ingressController:
  enabled: true
  service:
    loadBalancerIP: 192.168.4.17
```

Deploy a `whoami` application and test the `Ingress` and certificates issued by LetsEncrypt:

```
$ cat whoami.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
  selector:
    app: whoami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - image: containous/whoami
          imagePullPolicy: Always
          name: whoami
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-cluster-issuer
spec:
  ingressClassName: cilium
  rules:
     - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80
  tls:
    - hosts:
        - whoami.domain.com
      secretName: cloudflare-tls-whoami

$ kubectl apply whoami.yaml
$ curl -I https://whoami.domain.com
HTTP/1.1 200 OK
date: Thu, 22 Feb 2024 22:00:00 GMT
content-length: 381
content-type: text/plain; charset=utf-8
x-envoy-upstream-service-time: 3
server: envoy
```

The `cilium-ingress-whoami` service is created properly as `LoadBalancer` with a proper external IP. Certificate is also issued properly, so there are no configuration issues.

Changing the `hubble.tls.auto.method` to `certmanager` breaks also hubble-ui, port forward example:

![307499383-4f56358b-6ac8-4374-9056-916070f8df3f](https://github.com/cilium/cilium/assets/19806136/2e03eeaf-756a-4fdb-b1dd-61c888122dbd)

As soon as I revert back `hubble.tls.auto.method` to default `helm` chart setting, hubble-ui becomes functional, port-forward example:

![307515850-442c468b-e3ec-45c0-908b-76d20d19ce5d](https://github.com/cilium/cilium/assets/19806136/63d02995-cd5c-42e1-a73f-508cf9db2e61)

I don't understand why `hubble-relay-client-certs` secret is missing the required certificates when `hubble.tls.auto.method` is set to `certmanager`, is there a configuration I missed?

### Cilium Version

1.15.1

### Kernel Version

```
Linux apollo 5.15.0-1047-raspi #50-Ubuntu SMP PREEMPT Fri Feb 9 13:48:00 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

### Kubernetes Version

v1.29.1+k3s

### Sysdump

[cilium-sysdump-20240223-232255.zip](https://github.com/cilium/cilium/files/14391751/cilium-sysdump-20240223-232255.zip)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fmunteanu** [comment]
The issue was related to the rate-limiter imposed by LetsEncrypt in [production](https://letsencrypt.org/docs/duplicate-certificate-limit/), you can only generate up to 5 certificates per week. I was testing the cluster deployment several time, which triggered the imposed limit. Switching to Staging addressed the issue, until I'm ready to deploy the cluster in production.

**Comment by glrf** [comment]
I suspect the issue is that the issuer used for the Hubble certificates needs to be able to create certificates under the `cilium.io` domain name. Let's Encrypt will not issue you a certificate for `cilium.io`, so your issuer will not be able to create the certificates.

For example the hubble-relay client cert requests a certificate for `*.hubble-relay.cilium.io` (See https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/hubble/tls-certmanager/relay-client-secret.yaml#L16) If this makes sense is debatable, but in practice this means you will need to use a self-signed CA to issue certificates for Hubble (assuming you don't control `cilium.io`).

I can also see Kubernetes events in your sysdump that fit this:

```
- count: 9
  eventTime: null
  firstTimestamp: "2024-02-24T04:01:03Z"
  involvedObject:
    apiVersion: acme.cert-manager.io/v1
    kind: Challenge
    name: hubble-relay-client-certs-1-925148139-3015362437
    namespace: kube-system
    resourceVersion: "3262"
    uid: e523531a-7b1f-4cfa-91be-d1d1743162f1
  lastTimestamp: "2024-02-24T04:22:12Z"
  message: 'Error presenting challenge: Found no Zones for domain _acme-challenge.hubble-relay.cilium.io.
    (neither in the sub-domain nor in the SLD) please make sure your domain-entries
    in the config are correct and the API key is correctly setup with Zone.read rights.'
```

Could you try to use a self-signed Issuer and see if this fixes the problem?

**Comment by fmunteanu** [comment]
@glrf I apologize for the delayed response. My goal is to use Cloudflare certificates issued by cert-manager. Can you please let me know what additional changes I need to perform, in order to accomplish this requirement? Thank you.

**Comment by glrf** [comment]
As far as I can tell, it's currently not possible to change the domain, so you won't be able to use certificates issued by letsencrypt.

You can use cert-manager and an internal CA to issue the certificates. The certificates are only used internally. See https://cert-manager.io/docs/configuration/selfsigned/. In this case there is also no trust issues as all component have access to the same certificate and can verify it.

**Comment by fmunteanu** [comment]
Thank you, @glrf. The reason I ask is because I fail to understand why I would be presented with an optional `certmanager` chart setting, instead of default `helm` setting, which I believe creates a local CA by default.

Can you please explain what would be the advantage of using the `certmanager` chart setting?

**Comment by glrf** [comment]
The documentation explains this quite well: https://docs.cilium.io/en/v1.15/gettingstarted/hubble-configuration/#tls-certificates

The the default `helm` setting automatically generates certificates, but does not automatically renew the certificates. It does re-generate the certificates on every helm upgrade, which should prevent expired certificates in most cases, but that might not be desirable either. Using certgen does automatically renew the certificates using a cronjob, but using cert-manager is definitely the most robust solution.

**Comment by fmunteanu** [comment]
Thank you for the useful details, @glrf. Looking at the documentation, I'm asked that my issuer is be able to create certificates under the `cilium.io` domain name:

![image](https://github.com/cilium/cilium/assets/19806136/525ff523-c6cf-4732-91e3-234ec97d9b0b)

Going forward with your suggestion, I already have `cert-manager` installed with CRD's enabled and a functional `ClusterIssuer`, in place. These are the steps I do:

- Perform initial cilium setup with helm, then disable `hubble.tls.enabled: false`
- Install `cert-manager` with helm and set a `ClusterIssuer`, tested and functional
- Enable `hubble.tls.enabled: true`

Based on documentation, this should suffice. From your above answer, it looks like is not. From my understanding, I need to setup another self signed `ClusterIssuer`:

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}
```

Which I presume will be assigned to:

```
  tls:
    auto:
      certManagerIssuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: selfsigned-cluster-issuer
      method: certmanager
```

Please let me know if my logic is correct.

**Comment by glrf** [comment]
> Based on documentation, this should suffice.

No, because your current `ClusterIssuer` isn't able to create certificates unde the `cilium.io` domain name.

> From my understanding, I need to setup another self signed ClusterIssuer

I had to double check myself, but no. Directly using a self-signed ClusterIssuer doesn't work, as the helm chart creates two certificates that need to have the same CA, the rely client cerificate and the hubble server certificate. This isn't the case if the certificates are self-signed

However, you can [Boostrap a CA Issuer](https://cert-manager.io/docs/configuration/selfsigned/#bootstrapping-ca-issuers), using a self-signed issuer. So basically

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-selfsigned-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: my-selfsigned-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: my-ca-issuer
spec:
  ca:
    secretName: root-secret
```

And then in the helm values

```
  tls:
    auto:
      certManagerIssuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: my-ca-issuer
      method: certmanager
```

**Comment by fmunteanu** [comment]
Thank you @glrf for your precious help, I addressed all issues. During the initial cilium helm chart install, I define:

```
hubble:
  tls:
    auto:
      enabled: false
```

Which produces an error:

```
Error: execution error at (cilium/templates/hubble/tls-provided/server-secret.yaml:14:47): missing hubble.tls.server.cert
```

What I did is leave the default chart setting to `true` and after I deploy `cert-manager` and create the cluster issuers and certificate you mentioned above, I updated the related cilium `hubble.tls` settings:

```
      hubble:
        tls:
          auto:
            certManagerIssuerRef:
              group: cert-manager.io
              kind: ClusterIssuer
              name: hubble-cluster-issuer
            method: certmanager
```

I tested the procedure and the above approach works, I'm attaching a [post-deployment dump](https://github.com/cilium/cilium/files/15001726/cilium-sysdump-20240416-152151.zip), for reference.

Final customized helm chart settings, after cilium update:

```
~$ helm get values cilium -n kube-system
USER-SUPPLIED VALUES:
autoDirectNodeRoutes: true
bandwidthManager:
  enabled: true
dashboards:
  enabled: true
enableCiliumEndpointSlice: true
envoy:
  enabled: true
  prometheus:
    serviceMonitor:
      enabled: true
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi
  rollOutPods: true
externalIPs:
  enabled: true
gatewayAPI:
  enabled: true
hubble:
  metrics:
    dashboards:
      enabled: true
    enabled:
    - dns:query;ignoreAAAA
    - drop
    - flow
    - httpV2
    - icmp
    - port-distribution
    - tcp
    serviceMonitor:
      enabled: true
  peerService:
    clusterDomain: cluster.local
  relay:
    enabled: true
    prometheus:
      serviceMonitor:
        enabled: true
    replicas: "2"
    resources:
      limits:
        cpu: 400m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 64Mi
    retryTimeout: 10s
    rollOutPods: true
  tls:
    auto:
      certManagerIssuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: hubble-cluster-issuer
      method: certmanager
  ui:
    enabled: true
    rollOutPods: true
ingressController:
  enabled: true
  service:
    loadBalancerIP: 192.168.4.17
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: 10.42.0.0/16
ipv4NativeRoutingCIDR: 10.42.0.0/16
k8sClientRateLimit:
  burst: "100"
  qps: "50"
k8sServiceHost: 127.0.0.1
k8sServicePort: "6444"
kubeProxyReplacement: true
l2announcements:
  enabled: true
l2podAnnouncements:
  enabled: true
  interface: eth0
operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi
  rollOutPods: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
rollOutCiliumPods: true
routingMode: native

~$ cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    OK
 \__/¯¯\__/    Hubble Relay:       OK
    \__/       ClusterMesh:        disabled

Deployment             cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
Deployment             hubble-ui          Desired: 1, Ready: 1/1, Available: 1/1
DaemonSet              cilium-envoy       Desired: 8, Ready: 8/8, Available: 8/8
DaemonSet              cilium             Desired: 8, Ready: 8/8, Available: 8/8
Deployment             hubble-relay       Desired: 2, Ready: 2/2, Available: 2/2
Containers:            cilium             Running: 8
                       cilium-operator    Running: 2
                       hubble-ui          Running: 1
                       cilium-envoy       Running: 8
                       hubble-relay       Running: 2
Cluster Pods:          76/76 managed by Cilium
Helm chart version:
Image versions         hubble-relay       quay.io/cilium/hubble-relay:v1.15.4@sha256:03ad857feaf52f1b4774c29614f42a50b370680eb7d0bfbc1ae065df84b1070a: 2
                       cilium             quay.io/cilium/cilium:v1.15.4@sha256:b760a4831f5aab71c711f7537a107b751d0d0ce90dd32d8b358df3c5da385426: 8
                       cilium-operator    quay.io/cilium/operator-generic:v1.15.4@sha256:404890a83cca3f28829eb7e54c1564bb6904708cdb7be04ebe69c2b60f164e9a: 2
                       hubble-ui          quay.io/cilium/hubble-ui-backend:v0.13.0@sha256:1e7657d997c5a48253bb8dc91ecee75b63018d16ff5e5797e5af367336bc8803: 1
                       hubble-ui          quay.io/cilium/hubble-ui:v0.13.0@sha256:7d663dc16538dd6e29061abd1047013a645e6e69c115e008bee9ea9fef9a6666: 1
                       cilium-envoy       quay.io/cilium/cilium-envoy:v1.27.4-21905253931655328edaacf3cd16aeda73bbea2f@sha256:d52f476c29a97c8b250fdbfbb8472191a268916f6a8503671d0da61e323b02cc: 8
```

Maybe the `cert-manager` part of [documentation](https://docs.cilium.io/en/v1.15/gettingstarted/hubble-configuration/#tls-certificates) can be revisited, to clarify further this issue where disabling `hubble.tls` is not required when `rollOutPods` are enabled? Also, your above certificate setup example should be included into documentation, it is very useful.

This is the related PR part, where I implemented your suggestions. So far, these are the cilium deployment steps I perform:

- Deploy a K3S cluster on 8 bare-metal nodes (3 control-planes and 5 workers)
- Deploy cilium helm chart with a basic configuration
- Implement Cloudflare domain requirements, then install `argo-cd`, `cert-manager`, `longhorn` and `sealed-secrets`
- Setup the cilium gateway routes for all needed frontends
- Update cilium helm chart settings to enable several post-install features, including Hubble TLS with `cert-manager`

Hubble UI, for reference:

![image](https://github.com/cilium/cilium/assets/19806136/ac20d4a6-23d9-4b84-92ef-6dd0c9bc9694)
