### ISSUE TITLE
matchPattern numbers or letters

### ISSUE THREAD

**Issue by anutator** [cilium/cilium#31031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I try to add pattern to match 5 names

 ip-vm-kafka01.node.example.tech
 ip-vm-kafka02.node.example.tech
 ip-vm-kafka03.node.example.tech
 ip-vm-kafka04.node.example.tech
 ip-vm-kafka05.node.example.tech

```yaml
  egress:
  - toFQDNs:
    - matchPattern: ip-vm-kafka0[1-5].node.example.tech
    toPorts:
    - ports:
      - port: "9092"
    - ports:
      - port: "9093"

```

, but I gen an error.

`The CiliumNetworkPolicy "crm-core" is invalid: spec.egress[0].toFQDNs[0].matchPattern: Invalid value: "ip-vm-kafka0[1-5].node.example.tech": spec.egress[0].toFQDNs[0].matchPattern in body should match '^([-a-zA-Z0-9_*]+[.]?)+$'`

How should I make pattern for number 1,2,3, 4,5 or for numbers 1,3,5,7?

### Cilium Version

1.13.8

### Kernel Version

5.14.0-362.13.1.el9_3.x86_64

### Kubernetes Version

v1.27.9

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
