### ISSUE TITLE
Cilium Daemon set crash on "panic: runtime error: invalid memory address or nil pointer dereference" after few requests

### ISSUE THREAD

**Issue by matan-cohen** [cilium/cilium#31071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Implmented Cilium as a full kubeProxy & CNI Replacement on EKS cluster. 
Aiming to work with Gateway API CRDs.

While performing several successful HTTP requests to backend service , cilium Daemon set is crashing after few requests(one digit count):
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5fb794]

goroutine 1630 [running]:
net/url.(*URL).String(0x0)
	/usr/local/go/src/net/url/url.go:810 +0x34
github.com/cilium/cilium/pkg/hubble/parser/seven.decodeHTTP({0x3928cce, 0x7}, 0xc003903680, 0xc00029c660)
	/go/src/github.com/cilium/cilium/pkg/hubble/parser/seven/http.go:41 +0x405
github.com/cilium/cilium/pkg/hubble/parser/seven.decodeLayer7(0x192?, 0xc0037f9bc0?)
	/go/src/github.com/cilium/cilium/pkg/hubble/parser/seven/parser.go:360 +0x2b9
github.com/cilium/cilium/pkg/hubble/parser/seven.(*Parser).Decode(0xc00024de30, 0xc0021bf6c0, 0xc0038ff380)
	/go/src/github.com/cilium/cilium/pkg/hubble/parser/seven/parser.go:149 +0xbc5
github.com/cilium/cilium/pkg/hubble/parser.(*Parser).Decode(0xc00029c740, 0xc003903810)
	/go/src/github.com/cilium/cilium/pkg/hubble/parser/parser.go:145 +0x2e5
github.com/cilium/cilium/pkg/hubble/observer.(*LocalObserverServer).Start(0xc0008528c0)
	/go/src/github.com/cilium/cilium/pkg/hubble/observer/local_observer.go:133 +0xe6
created by github.com/cilium/cilium/daemon/cmd.(*Daemon).launchHubble in goroutine 1532
	/go/src/github.com/cilium/cilium/daemon/cmd/hubble.go:211 +0x1bdb
```

Cilium installed with the following options:
```
      eni.enabled: true 
      ipam.mode: eni 
      kubeProxyReplacement: true
      nodePort.enabled: true
      egressMasqueradeInterfaces: eth0 
      routingMode: native
      k8sServiceHost: <KUBEAPI SERVER>
      k8sServicePort: 443
      auto-create-cilium-node-resource: "true"
      gatewayAPI.enabled: true 
      hubble.enabled: true
      hubble.relay.enabled: true 
      hubble.ui.enabled: true
      envoy.enabled: true
```

HTTP Route
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name:  <name>
spec:
  hostnames:
  - <hostname>
  parentRefs:
  - name: stm-gateway
    namespace: stm
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /monitoring/v1/test
    filters:
      - type: RequestHeaderModifier
        requestHeaderModifier:
          add:
            - name: X-Forwarded-Proto
              value: https
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
    backendRefs:
    - name: <service_name>
      port: 80
```
Gateway resource:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: test-gateway
spec:
  gatewayClassName: cilium
  infrastructure: 
    annotations:
      service.kubernetes.io/topology-aware-hints: Auto
      service.kubernetes.io/topology-aware-routing: Auto
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: businessunit=shared,system=kubernetes
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-scheme: internal
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <CERT_ARN>
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: port-443
  listeners:
  - protocol: HTTP
    port: 80
    name: http
    allowedRoutes:
       namespaces:
        from: Same
    hostname: <hostname>
  - protocol: HTTP
    port: 443
    name: https
    allowedRoutes:
       namespaces:
        from: Same
    hostname: <hostname>
```

### Cilium Version

cilium image (stable): v1.15.1
cilium image (running): 1.15.1

### Kernel Version

5.10.198-187.748.amzn2.x86_64

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.5-eks-5e0fdde", GitCommit:"e78a4be9da4c375a87a109e0f4a5f4a8d2bc17c0", GitTreeState:"clean", BuildDate:"2024-01-02T20:34:46Z", GoVersion:"go1.20.12", Compiler:"gc", Platform:"linux/amd64"}

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
