### ISSUE TITLE
l2podAnnouncements - Node return traffic to the network during POD termination leading to duplicate IP addresses

### ISSUE THREAD

**Issue by camrossi** [cilium/cilium#31079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am working on a design to integrate Cilium in L2 mode for both Pods and Service Advertisement.
The current Topology is pretty straight forward where all the nodes are placed in 1 VLAN and said VLAN is configured with 2 Subnets:

- Node: 192.168.11.1/24
- PODs: 10.56.0.1/16

What I see happening that if a node receives a packet for a POD IP that is being terminated the node instead of dropping it it will send it back to the switch resulting in duplicate IP addresses. 
Here the detailed series of events:

1. Let's assume I have 2 PODs running on 2 nodes that are communicating
<img width="828" alt="image" src="https://github.com/cilium/cilium/assets/16535101/e167ce43-e0bb-44ca-beab-0404732718b0">
The switch will learn the IP/Mac Biding as per the above figure

2. Now I terminate the POD `10.56.229.5` on `talos-31i-xek`
3. Expectation: 
    - the switches will keep sending traffic for `10.56.229.5` to `talos-31i-xek`
    - `talos-31i-xek` will drop the traffic
4. Current Behaviour: 
    - the switches will keep sending traffic for `10.56.229.5` to `talos-31i-xek`
    -  `talos-31i-xek` sends the traffic BACK to the switch using it's MAC address as source for `10.56.224.108 ` resulting in IP address flaps as `10.56.224.108 ` keeps also sending traffic from talos-61n-wue

I *think* this behaviour happens while the pod is being terminated only and under load but not 100% sure. 

Here an example

1. Start wget in a loop to generate lots of traffic
```
POD - 10.56.224.108
/ # while true
> do
> wget 10.56.229.5:8080 -o /dev/null
> done
```
2. delete the pod:
```
kgpwide  goldpinger-zxjm7
goldpinger-zxjm7   1/1     Running   0          6m46s   10.56.229.5     talos-31i-xek   <none>           <none>
kdelp goldpinger-zxjm7 
```
Traffic Catures:
- One the Node talos-31i-xek 
- Packet 5: `10.56.224.108` sends traffic to `10.56.229.5` with Destination mac of `02:ad:ca:00:02:66` and the SRC Mac address is `00:22:bd:f8:19:ff` that is my switch SVI
<img width="417" alt="image" src="https://github.com/cilium/cilium/assets/16535101/0a3769b0-b9a0-4557-a2c7-086c99a1493e">

- Packet 6: `talos-31i-xek` sends the traffic back to the switch (Dest mac `00:22:bd:f8:19:ff`) and uses its mac address as source `02:ad:ca:00:02:66`
<img width="922" alt="image" src="https://github.com/cilium/cilium/assets/16535101/35f8b7c1-930f-4e0b-9bda-33fc4b895490">

- Now we go in an loop where the switch will send the traffic back to the node and the node back to the switch and so on. 

Cilium has been configured as following:
```
helm upgrade --install \
    cilium \
    cilium/cilium \
    --version 1.15.1 \
    --namespace kube-system \
    --set=kubeProxyReplacement=true \
    --set=securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
    --set=securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
    --set=cgroup.autoMount.enabled=false \
    --set=cgroup.hostRoot=/sys/fs/cgroup \
    --set=k8sServiceHost=localhost \
    --set l2announcements.enabled=true \
    --set l2podAnnouncements.enabled=true \
    --set l2podAnnouncements.interface=eth0 \
    --set ipam.mode=multi-pool \
    --set routingMode=native \
    --set enableIPv4Masquerade=false \
    --set ipv4NativeRoutingCIDR='10.56.0.0/16' \
    --set ipam.operator.autoCreateCiliumPodIPPools.default.ipv4.cidrs='{10.56.224.0/19}' \
    --set ipam.operator.autoCreateCiliumPodIPPools.default.ipv4.maskSize=27 \
    --set hubble.tls.auto.enabled=true \
    --set hubble.tls.auto.method=helm \
    --set hubble.relay.enabled=true \
    --set hubble.ui.enabled=true \
    --set k8sServiceHost=127.0.0.1 \
    --set=k8sServicePort=7445 
```

This issues dose not seems to happen consistently... I am not 100% sure what's the trigger yet but also when it happens on clusters with lots of pods it pretty much brings down the cluster as communication is disrupted and loop prevention mechanics are also getting triggered on the switch blocking the offending IP. 

**UPDATE: 5/Mar/24** 
I figured out what is the issue I think: 

On a node that is **NOT**experiencing the issue the allocated POD pool also has a corresponding routes pointing to `cilium_host`

```
 kubectl get ciliumnode -o yaml  talos-u3z-0g1  | yq .spec.addresses,.spec.ipam
- ip: 192.168.11.249
  type: InternalIP
- ip: 10.56.0.86
  type: CiliumInternalIP
pools:
  allocated:
    - cidrs:
        - 10.56.0.0/24
      pool: default
  requested:
    - needed:
        ipv4-addrs: 8
      pool: default


talosctl -n 192.168.11.249  get routes | grep 10.56
192.168.11.249   network     RouteStatus   inet4//10.56.0.86/32/0                                     1         10.56.0.86/32                                    cilium_host   0
192.168.11.249   network     RouteStatus   inet4/10.56.0.86/10.56.0.0/24/0                            1         10.56.0.0/24                    10.56.0.86       cilium_host   0
192.168.11.249   network     RouteStatus   local/inet4//10.56.0.86/32/0                               1         10.56.0.86/32                                    cilium_host   0
```

On a node that **IS** experiencing the issue the allocated POD pool  and the routing are not in sync:

```
kubectl get ciliumnode -o yaml talos-r6c-zrq | yq .spec.addresses,.spec.ipam
- ip: 192.168.11.129
  type: InternalIP
- ip: 10.56.3.80
  type: CiliumInternalIP
pools:
  allocated:
    - cidrs:
        - 10.56.3.0/24
      pool: default
  requested:
    - needed:
        ipv4-addrs: 16
      pool: default

talosctl -n 192.168.11.129  get routes  | grep 10.56
192.168.11.129   network     RouteStatus   inet4//10.56.3.80/32/0                                         1         10.56.3.80/32                                    cilium_host       0
192.168.11.129   network     RouteStatus   inet4/10.56.3.80/10.56.76.0/24/0                               1         10.56.76.0/24                   10.56.3.80       cilium_host       0
192.168.11.129   network     RouteStatus   local/inet4//10.56.3.80/32/0                                   1         10.56.3.80/32                                    cilium_host       0
```
In the logs I can see that we select as `IPv4 allocation prefix: 10.56.76.0/24` but then the pods are running in `10.56.3.0/24` 
```
level=info msg="  --ipv4-native-routing-cidr='10.56.0.0/16'" subsys=daemon
level=info msg="Node addresses updated" device=cilium_host node-addresses="10.56.2.67 (cilium_host), fe80::b083:5fff:fe88:cf49 (cilium_host)" subsys=node-address
level=info msg="Received own node information from API server" ipAddr.ipv4=192.168.11.129 ipAddr.ipv6="<nil>" k8sNodeIP=192.168.11.129 labels="map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:talos-r6c-zrq kubernetes.io/os:linux type:kvm]" nodeName=talos-r6c-zrq subsys=daemon v4Prefix=10.56.76.0/24 v6Prefix="<nil>"
level=info msg="Restored router address from node_config" file=/var/run/cilium/state/globals/node_config.h ipv4=10.56.2.67 ipv6="<nil>" subsys=node
level=warning msg="Unable to restore endpoint, ignoring" ciliumEndpointName=loop/busybox2 endpointID=4073 error="Failed to re-allocate IP of endpoint: unable to reallocate 10.56.2.117 IPv4 address: IP 10.56.2.117 not in range of any pod CIDR" subsys=daemon
level=warning msg="Unable to restore router IP from filesystem" error="IP 10.56.2.67 not in range of any pod CIDR" ipAddr=10.56.2.67 subsys=daemon
level=info msg="  Internal-Node IPv4: 10.56.3.80" subsys=daemon
level=info msg="  IPv4 allocation prefix: 10.56.76.0/24" subsys=daemon
level=info msg="  IPv4 native routing prefix: 10.56.0.0/16" subsys=daemon
level=info msg="  - 10.56.2.67" subsys=daemon

kgpwide -A | grep talos-r6c-zrq
kube-system   cilium-2grnb                            1/1     Running   0             14m    192.168.11.129   talos-r6c-zrq   <none>           <none>
kube-system   hubble-ui-6548d56557-m2pth              2/2     Running   0             14m    10.56.3.218      talos-r6c-zrq   <none>           <none>
loop          busybox3                                1/1     Running   0             6m2s   10.56.3.141      talos-r6c-zrq   <none>           <none>

```

So what I think is happening is that if a pod is running on the node we accept the packet but if the POD is not there we route it back to the switches as we are following the default route.
If I manually add the `missing` routes to the nodes i.e adding `10.56.3.0/24` to `talos-r6c-zrq` the behaviour is correct and there is no more a loop. 

So I think the issue is in fact with the CIDR allocation logic with the `Multi-Pool` ipam.mode. 

Reading the doc again I see that for Multi-Pool we should set `endpointRoutes.enabled=true` I tried with this as well but same behaviour as the nodes are returning the traffic back to the switches. With `endpointRoutes.enabled=true` the routes pointing to `cilium_host` for the POD CIDR allocated to the node is not there at all. 

** Update 06/Mar/24:**
Tested with `ipam.mode=cluster-pool` and  seems to be working fine. I test with a 100 nodes clusters with ~500 pods and there is no issue.

### Cilium Version

1.15.1

### Kernel Version

 kgno -o wide talos-61n-wue
NAME            STATUS   ROLES    AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE         KERNEL-VERSION   CONTAINER-RUNTIME
talos-61n-wue   Ready    <none>   22h   v1.29.1   192.168.11.81   <none>        Talos (v1.6.4)   6.1.74-talos     containerd://1.7.13

### Kubernetes Version

v1.29.1

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
