### ISSUE TITLE
CFP: Provide support to advertised routes as a summarized address when doing router advertistment

### ISSUE THREAD

**Issue by tbotnz** [cilium/cilium#31116]
## Cilium Feature Proposal
        
Support advertising services as summarized routes

**Is your proposed feature related to a problem?**

I was deploying cillium with bgp control plane + bgp service advertisment and was requested by an external network team to advertise a /24 for all services instead of individual /32's (per service)

**Describe the feature you'd like**

Allow cilium to summarize service advertisements  

**(Optional) Describe your proposed solution**

provide a summarization option under the CiliumLoadBalancerIPPool which summarizes any address to the pool supernet when advertised

```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lab-pool"
spec:
  summarize: true <------- new option which will then summarize any service to the block address when advertised
  blocks:
  - cidr: "10.100.11.0/24"
```
