### ISSUE TITLE
Gateway API implementation does not correctly distinguish TLSRoutes with same hostname on different ports

### ISSUE THREAD

**Issue by timoreimann** [cilium/cilium#31122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Consider the following Gateway API setup with a single gateway where two TLSRoutes are configured using the same hostnames but _different ports_:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: cilium
spec:
  controllerName: io.cilium/gateway-controller

---

apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  namespace: default
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: TLS
      name: app1
      port: 14443
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All
    - protocol: TLS
      name: app2
      port: 18443
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All

---

apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    name: app1
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443

---

apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    name: app2
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443

---

apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: app1
  namespace: default
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: default
      sectionName: app1
      name: gateway
      port: 14443
  hostnames:
    - myserver.cilium.rocks
  rules:
    - backendRefs:
        - kind: Service
          name: app1
          namespace: default
          port: 443
          weight: 1

---

apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: app2
  namespace: default
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: default
      sectionName: app2
      port: 18443
      name: gateway
  hostnames:
    - myserver.cilium.rocks
  rules:
    - backendRefs:
        - kind: Service
          name: app2
          namespace: default
          port: 443
          weight: 1
```

With two corresponding deployments in place, this should cause requests targeting port 14443 to be forwarded to `app1` and requests targeting port 18443 to be forwarded to port `app2`. However, what happens is that requests are sent towards exactly one of the two (and sometimes none) depending on the order by which the TLSRoutes were added/removed.

Moreover, if TLSRoute `app2` is removed, I believe requests to port 18443 should start to fail. However, they continue to be forwarded to `app1` in that case.

I believe this to be a bug in Cilium's Gateway API implementation which should be able to tell the two apart by port, but it seems to rely on the hostname / SNI header routing only. See also [the GatewaySpec reference](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1alpha2.Gateway) which talks about how listeners must be distinct (which, admittedly, isn't exactly a light read IMHO).

### Cilium Version

v1.14.7

### Kernel Version

`Linux pool-o2awt 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux`

### Kubernetes Version

1.29.1

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
