### ISSUE TITLE
HTTPRoute results in "no healthy upstream" on Alert Manager and Prometheus

### ISSUE THREAD

**Issue by kenlasko** [cilium/cilium#31212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After successfully getting the Gateway API working in my environment, I've converted all my Traefik IngressRoutes to HTTPRoutes. More than 30 have been successfully converted with no issues. However, the HTTPRoutes for Alert Manager and Prometheus do not work (Grafana does).  The routes are created successfully, but when I try to connect to alertmanager.mydomain.com or prometheus.mydomain.com, I get the text ```no healthy upstream```  Inspecting the result shows its throwing a ```503 Service Unavailable``` error.

AlertManager/Prometheus/Grafana were deployed using the Prometheus-Community **kube-prometheus-stack** Helm chart.

### Original Traefik Config
```
kind: IngressRoute
apiVersion: traefik.io/v1alpha1
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
    external-dns.alpha.kubernetes.io/target: k3s.mydomain.com
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints: 
  - websecure
  routes:
  - match: Host(`alertmanager.mydomain.com`) 
    kind: Rule
    services:
    - name: alertmanager-operated
      port: 9093
    middlewares:
    - name: traefik-security
      namespace: traefik
  tls:
    options:
      name: tls-options-clientauth
      namespace: traefik
```

### HTTPRoute
(The same format has worked for 30+ other conversions)
```
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  parentRefs:
  - name: tls
    namespace: cilium
    sectionName: https
  hostnames:
  - "test-alertmanager.mydomain.com"
  rules:
  - backendRefs:
    - name: alertmanager-operated
      namespace: monitoring
      kind: Service
      port: 9093
```

### Cilium Version

1.15.1

### Kernel Version

6.5.0-18-generic

### Kubernetes Version

Client Version: v1.28.7
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.7+k3s1

### Sysdump

Too big to add

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
