### ISSUE TITLE
Ingress and Gateway API fail to work on kind cluster in 1.16.0-pre.0

### ISSUE THREAD

**Issue by jspaleta** [cilium/cilium#31269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Neither Ingress nor Gateway API appear to work as expected following documented examples using the 1.16.0-pre.0 when run on docker based clusters like Kind or Talos using either metalLB or kube-vip for assigning external IP addresses.

Symptom is no external IP address assigned to either gateway or ingress.

Works fine downgrading to 1.15.1 using exact same setup that files with the 1.16 prerelease.

Prerelease works fine when tested in a k3s cluster with physical hosts with separate kernels using k3s's provided loadbalancer

Haven't tested with VMs yet.

### Cilium Version

1.16.0-pre.0

### Kernel Version

Linux carbon 6.7.4-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Feb  5 22:21:14 UTC 2024 x86_64 GNU/Linux

### Kubernetes Version

Server Version: v1.29.2

### Regression

Yes a regression in the 1.16.0-pre.0 release
1.15.1 seems to works in all scenarios I've tested.

### Kind Cluster setup using kube-vip
```
kind create cluster --config kind-config.yaml
```
### wait for cluster to init 
```
kubectl apply -f https://kube-vip.io/manifests/rbac.yaml
kubectl create configmap --namespace kube-system kubevip --from-literal range-global=172.18.100.10-172.18.100.30
kubectl apply -f https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/main/manifest/kube-vip-cloud-controller.yaml
docker run --network host --rm ghcr.io/kube-vip/kube-vip:v0.5.7 manifest daemonset --services --inCluster --arp --interface eth0 | kubectl apply -f -

kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml

cilium install --version 1.16.0-pre.0 -f ./helm-values-ingress.yaml 
```
### 4 hours later
```
cilium version

```

```
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.11/samples/bookinfo/platform/kube/bookinfo.yaml
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.15/examples/kubernetes/servicemesh/basic-ingress.yaml
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.15/examples/kubernetes/gateway/basic-http.yaml
```

### Notice ingress and gateway failed to get docker network ipaddresse from kube-vip range
```
kubectl get ingress -A
NAMESPACE   NAME            CLASS    HOSTS   ADDRESS   PORTS   AGE
default     basic-ingress   cilium   *                 80      6s

kubectl get gateway -A
NAMESPACE   NAME         CLASS    ADDRESS   PROGRAMMED   AGE
default     my-gateway   cilium             Unknown      42s

```

### Destroy kind cluster and repeat steps above for Cilium 1.15.1
```
cilium version
cilium-cli: v0.15.23 compiled with go1.22.0 on linux/amd64
cilium image (default): v1.15.0
cilium image (stable): v1.15.1
cilium image (running): 1.15.1
```
### Notice ingress and gateway get assigned addresses as expected

```
kubectl get ingress -A
NAMESPACE   NAME            CLASS    HOSTS   ADDRESS         PORTS   AGE
default     basic-ingress   cilium   *       172.18.100.11   80      6s
```
```
kubectl get gateway -A
NAMESPACE   NAME         CLASS    ADDRESS         PROGRAMMED   AGE
default     my-gateway   cilium   172.18.100.12   True         94s
```

kind config:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  # port forward 80 on the host to 80 on this node
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
networking:
  disableDefaultCNI: true
  kubeProxyMode: "none"
```

Cilium helm values:
```
kubeProxyReplacement: true
ingressController:
  enabled: true
  default: true
  loadbalancerMode: dedicated

gatewayAPI:
  enabled: true
```

Cilium ingress manifest from cilium docs:
```
# Basic ingress for istio bookinfo demo application, which can be found in below
# https://raw.githubusercontent.com/istio/istio/release-1.11/samples/bookinfo/platform/kube/bookinfo.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: default
spec:
  ingressClassName: cilium
  rules:
  - http:
      paths:
      - backend:
          service:
            name: details
            port:
              number: 9080
        path: /details
        pathType: Prefix
      - backend:
          service:
            name: productpage
            port:
              number: 9080
        path: /
        pathType: Prefix
```

cilium gateway HTTProute config from cilium docs:
```
--
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: my-gateway
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    name: web-gw
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-app-1
spec:
  parentRefs:
  - name: my-gateway
    namespace: default
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /details
    backendRefs:
    - name: details
      port: 9080
  - matches:
    - headers:
      - type: Exact
        name: magic
        value: foo
      queryParams:
      - type: Exact
        name: great
        value: example
      path:
        type: PathPrefix
        value: /
      method: GET
    backendRefs:
    - name: productpage
      port: 9080
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
