### ISSUE TITLE
Can't use Cilium Gateway API together with sidecar based ServiceMesh with Gateway API GAMMA support.

### ISSUE THREAD

**Issue by jspaleta** [cilium/cilium#31274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'd like to use Cilium Gateway API for ingress and use a sidecar based linkerd service mesh implementation with (beta) support for Gateway API GAMMA  but it appears this isn't possible,

All the servicemesh implementations that currently have beta GAMMA support require cilium `socketLB.hostNamespaceOnly: true` but setting this feature appears to make cilium's gateway API fail to initialize gateways correctly. The gateway never gets assigned address.

ServiceMesh implementations with GAMMA support that require `socketLB.hostNamespaceOnly: true` include: kuma,linkerd, istio. I've done the bulk of my testing with linkerd. I expect all are impacted similarly.

Cilium ingress still works as expected in this configuration and the ingress does get an IP assigned from kube-vip in my kind cluster setup that I am testing with.
 

### Cilium Version

1.15.1

### Kernel Version

Linux carbon 6.7.4-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Feb  5 22:21:14 UTC 2024 x86_64 GNU/Linux

### Kubernetes Version

1.29.2

### Regression

I don't know if this is a regression or not.  I've only testing 1.15.1 so far.

### Relevant log output

```shell
kubectl get gateway -A
NAMESPACE   NAME                CLASS    ADDRESS   PROGRAMMED   AGE
deathstar   deathstar-gateway   cilium             Unknown      12s


kubectl get ingress -A
NAMESPACE   NAME                CLASS    HOSTS   ADDRESS          PORTS   AGE
deathstar   deathstar-ingress   cilium   *       172.18.210.106   80      27s

```

```
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: deathstar-gateway
  namespace: deathstar  
spec:
  gatewayClassName: cilium  #which of the available gateway classes we'll be using.
  listeners:
  - protocol: HTTP # Lets just listen for HTTP 
    port: 80 # listen on port 80
    name: web-gw
    # Can only attach HTTPRoutes from the same namespace (deathstar namespace)
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deathstar-ingress
  namespace: deathstar
spec:
  ingressClassName: cilium
  rules:
  - http:
      paths:
      - backend:
          service:
            name: access-denied
            port:
              number: 80
        path: /
        pathType: Prefix
  - http:
      paths:
      - backend:
          service:
            name: deathstar
            port:
              number: 80
        path: /v1/request-landing
        pathType: Prefix

```

cilium helm values
```
kubeProxyReplacement: true
ingressController:
  enabled: true
  default: true
  loadbalancerMode: dedicated
gatewayAPI:
  enabled: true
socketLB:
  hostNamespaceOnly: true
```
kind config
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: imperial-clustermesh
networking:
  disableDefaultCNI: true
  kubeProxyMode: "none"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  # port forward 80 on the host to 80 on this node
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
```
```


### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
