### ISSUE TITLE
Gateway API doesn't seem to like reusing gateway name in multiple namespaces in dedicated loadbalancer mode

### ISSUE THREAD

**Issue by jspaleta** [cilium/cilium#31270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Testing usins multiple gateway definitions I found that if I reused the gateway name the gateway status information concerning the external ip address is inconsistent with the loadbalance service when using dedicated loadbalancer mode.

### Cilium Version

1.15.1

Due to another bug with gatway API on Kind (#31269), I can't test 1.16.0-pre.0 

### Kernel Version

Linux carbon 6.7.4-200.fc39.x86_64 cilium/cilium#1 SMP PREEMPT_DYNAMIC Mon Feb  5 22:21:14 UTC 2024 x86_64 GNU/Linux

### Kubernetes Version

Server Version: v1.29.2

### Regression

I've only tested with 1.15.1 so far.

### Anything else?

Mismatch in expected address between gateway and loadbalancer service in namespace other

```
kubectl get gateway -A
NAMESPACE   NAME         CLASS    ADDRESS         PROGRAMMED   AGE
default     my-gateway   cilium   172.18.100.12   True         12m
other       my-gateway   cilium   172.18.100.12   True         5m27s
```
```
kubectl -n other get services 
NAME                        TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)        AGE
cilium-gateway-my-gateway   LoadBalancer   10.96.235.190   172.18.100.13   80:31459/TCP   6m10s
details                     ClusterIP      10.96.172.58    <none>          9080/TCP       13m
productpage                 ClusterIP      10.96.112.101   <none>          9080/TCP       13m
ratings                     ClusterIP      10.96.40.236    <none>          9080/TCP       13m
reviews                     ClusterIP      10.96.21.58     <none>          9080/TCP       13m
```
But if I change the gateway name to longer be the same as an existing gateway name...then I get what I expect.

```
kubectl get gateway -A
NAMESPACE   NAME            CLASS    ADDRESS         PROGRAMMED   AGE
default     my-gateway      cilium   172.18.100.12   True         16m
other       other-gateway   cilium   172.18.100.13   True         8s

kubectl -n other get services 
NAME                           TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)        AGE
cilium-gateway-other-gateway   LoadBalancer   10.96.160.207   172.18.100.13   80:30393/TCP   34s
details                        ClusterIP      10.96.172.58    <none>          9080/TCP       17m
productpage                    ClusterIP      10.96.112.101   <none>          9080/TCP       17m
ratings                        ClusterIP      10.96.40.236    <none>          9080/TCP       17m
reviews                        ClusterIP      10.96.21.58     <none>          9080/TCP       17m

```
### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jspaleta** [comment]
My kind setup is detailed in the referenced bug report.. but for completeness
```
kind create cluster --config kind-config.yaml


kubectl apply -f https://kube-vip.io/manifests/rbac.yaml
kubectl create configmap --namespace kube-system kubevip --from-literal range-global=172.18.100.10-172.18.100.30
kubectl apply -f https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/main/manifest/kube-vip-cloud-controller.yaml
docker run --network host --rm ghcr.io/kube-vip/kube-vip:v0.5.7 manifest daemonset --services --inCluster --arp --interface eth0 | kubectl apply -f -

kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
kubectl create ns other

cilium install --version 1.15.1 -f ./helm-values-ingress.yaml
cilium status --wait

kubectl apply -f bookinfo.yaml
kubectl apply -n other -f bookinfo.yaml

sleep 30
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.15/examples/kubernetes/servicemesh/basic-ingress.yaml
kubectl apply -f basic-http.yaml
kubectl apply -n other -f other-http.yaml
```

kind-config.yaml
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: simple-demo-cluster
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  # port forward 80 on the host to 80 on this node
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
networking:
  disableDefaultCNI: true
  kubeProxyMode: "none"

```

helm-values-ingress.yaml
```
kubeProxyReplacement: true
ingressController:
  enabled: true
  default: true
  loadbalancerMode: dedicated

gatewayAPI:
  enabled: true

```
