### ISSUE TITLE
`error:0A00010B:SSL` error occurred when using curl with Cilium network policy applied for egress http path

### ISSUE THREAD

**Issue by metalwhale** [cilium/cilium#31289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

First of all, I want to say thanks to everyone who contributed. Cilium is awesome, and I really appreciate your work.
Regarding this issue, I'm not sure if it's a bug. Please correct me if I'm wrong.

## Description
I want to create a `CiliumNetworkPolicy` to restrict egress from a pod, allowing access only to `https://github.com/trending` and blocking access to any other domains (such as `google.com`, `youtube.com`...) and any other paths of `https://github.com` (such as `/pricing`, `/features`...)

The policy worked normally with `http` requests but it failed with `https`, showing the following error message:
```
curl: (35) error:0A00010B:SSL routines::wrong version number
```

## How to reproduce
I'm using DOKS (DigitalOcean Kubernetes). I haven't tested with other k8s providers.
Follow these steps to reproduce:

### Step 1: create and connect to a DOKS cluster
You can refer to DOKS doc [here](https://docs.digitalocean.com/products/kubernetes/how-to/create-clusters/)

### Step 2: create a deployment
Run `kubectl apply -f deployment.yaml` (here `beach` is just the name of the deployment)
<details><summary><code>deployment.yaml</code></summary>

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beach
  labels:
    app: beach
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: beach
  template:
    metadata:
      labels:
        app: beach
    spec:
      containers:
        - name: beach
          image: ubuntu:22.04
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          stdin: true
          tty: true
```
</details>

### Step 3: Install `curl` inside the pod
Get inside the pod:
<pre>
kubectl exec -it <b>POD_NAME</b> -- bash
</pre>
Install `curl`:
```bash
apt update -y
apt install -y curl
```

### Step 4: create a Cilium network policy
Run `kubectl apply -f networkpolicy.yaml`
<details><summary><code>networkpolicy.yaml</code></summary>

```yaml
---
# See:
# - https://docs.cilium.io/en/v1.14/security/dns/
# - https://doc.crds.dev/github.com/cilium/cilium/cilium.io/CiliumNetworkPolicy/v2@1.14.4
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: beach-allow-github
spec:
  endpointSelector:
    matchLabels:
      app: beach
  egress:
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    - toFQDNs:
        - matchName: "github.com"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "80"
              protocol: TCP
          rules:
            http:
              - path: "/trending"
```
</details>

### Step 5: testing
The policy is working normally with `http` requests:
```bash
$ curl -I http://github.com/trending # whitelist
HTTP/1.1 301 Moved Permanently
...
$ curl -I http://github.com/pricing # access denied
HTTP/1.1 403 Forbidden
...
```
But the following error occurs with `https` requests, regardless of the paths:
```bash
$ curl -I https://github.com/trending -v
*   Trying 20.248.137.48:443...
* Connected to github.com (20.248.137.48) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* (5454) (IN), , Unknown (72):
* error:0A00010B:SSL routines::wrong version number
* Closing connection 0
curl: (35) error:0A00010B:SSL routines::wrong version number
```
The error disappears if I remove `rules.http.path` snippet from `networkpolicy.yaml` file and re-run the `kubectl apply -f` command.
<details><summary><code>rules.http.path</code> snippet</summary>

```yaml
          rules:
            http:
              - path: "/trending"
```
</details>

### Cilium Version

```
Client: 1.14.4 87dd2b64 2023-11-09T15:02:52-05:00 go version go1.20.11 linux/amd64
Daemon: 1.14.4 87dd2b64 2023-11-09T15:02:52-05:00 go version go1.20.11 linux/amd64
```

### Kernel Version

```
6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Server Version: version.Info{Major:"1", Minor:"29", GitVersion:"v1.29.1", GitCommit:"bc401b91f2782410b3fb3f9acf43a995c4de90d2", GitTreeState:"clean", BuildDate:"2024-01-17T15:41:12Z", GoVersion:"go1.21.6", Compiler:"gc", Platform:"linux/amd64"}
```

### Regression

I haven't tested with other versions of Cilium

### Sysdump

```
Error: unknown command "sysdump" for "cilium"
Run 'cilium --help' for usage.
unknown command "sysdump" for "cilium"
```
I can't run `cilium sysdump`. Perhaps I'm not using the latest version (?)

### Anything else?

`curl` version is:
```bash
$ curl -V
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
