### ISSUE TITLE
[question]  externalTrafficPolicy=Local doesn't work without KubeProxy, autoDirectNodeRoutes  and BGP data control

### ISSUE THREAD

**Issue by pando85** [cilium/cilium#31333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Probably I'm doing something wrong but I this configuration is not working and I would like to understand better why.
I have this configuration in helm:
```yaml
rollOutCiliumPods: true

serviceAccounts:
  # cert-manager used instead
  clustermeshcertgen:
    create: false
  hubblecertgen:
    create: false

k8sServiceHost: grigri.grigri
k8sServicePort: "6443"

securityContext:
  capabilities:
    ciliumAgent:
      # Use to set socket permission
      - CHOWN
      # Used to terminate envoy child process
      - KILL
      # Used since cilium modifies routing tables, etc...
      - NET_ADMIN
      # Used since cilium creates raw sockets, etc...
      - NET_RAW
      # Used since cilium monitor uses mmap
      - IPC_LOCK
      # Used in iptables. Consider removing once we are iptables-free
      - SYS_MODULE
      # Could be an alternative for the SYS_ADMIN for the RLIMIT_NPROC
      - SYS_RESOURCE
      # it should not be required for Kernel >= 5.8 but
      # it triggers the error `failed to create new netns: operation not permitted` without it
      - SYS_ADMIN
      # Both PERFMON and BPF requires kernel 5.8, container runtime
      # cri-o >= v1.22.0 or containerd >= v1.5.0.
      # If available, SYS_ADMIN can be removed.
      - PERFMON
      - BPF
      # Allow discretionary access control (e.g. required for package installation)
      - DAC_OVERRIDE
      # Allow to set Access Control Lists (ACLs) on arbitrary files (e.g. required for package installation)
      - FOWNER
      # Allow to execute program that changes GID (e.g. required for package installation)
      - SETGID
      # Allow to execute program that changes UID (e.g. required for package installation)
      - SETUID
    # -- Capabilities for the `mount-cgroup` init container
    cleanCiliumState:
      # Most of the capabilities here are the same ones used in the
      # cilium-agent's container because this container can be used to
      # uninstall all Cilium resources, and therefore it is likely that
      # will need the same capabilities.
      # Used since cilium modifies routing tables, etc...
      - NET_ADMIN
      # Used in iptables. Consider removing once we are iptables-free
      - SYS_MODULE
      # Could be an alternative for the SYS_ADMIN for the RLIMIT_NPROC
      - SYS_RESOURCE
      # Both PERFMON and BPF requires kernel 5.8, container runtime
      # cri-o >= v1.22.0 or containerd >= v1.5.0.
      # If available, SYS_ADMIN can be removed.
      - PERFMON
      - BPF

# If all nodes share a single L2 network, then this can be taken care of by enabling
# the option auto-direct-node-routes: true. Otherwise, an additional system component such as a BGP daemon must be run
autoDirectNodeRoutes: true

bgp:
  enabled: false

# -- This feature set enables virtual BGP routers to be created via
# CiliumBGPPeeringPolicy CRDs.
bgpControlPlane:
  enabled: true
  secretsNamespace:
    name: kube-system

containerRuntime:
  integration: containerd
  socketPath: /var/run/k3s/containerd/containerd.sock

kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: "0.0.0.0:10256"

hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - http
    serviceMonitor:
      enabled: true
      labels:
        release: monitoring
    dashboards:
      enabled: true
      annotations:
        grafana.grafana.com/dashboards.target-directory: /tmp/dashboards/cilium
      label: grafana_dashboard
  tls:
    enabled: true
    auto:
      enabled: true
      method: certmanager
      certManagerIssuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: internal
  relay:
    enabled: true
    rollOutPods: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        labels:
          release: monitoring
  ui:
    enabled: true
    rollOutPods: true
    ingress:
      enabled: true
      className: nginx-internal
      annotations:
        external-dns.alpha.kubernetes.io/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod-dns
      hosts:
        - &host XXXXXX.example.com
      tls:
        - secretName: hubble-tls-certificate
          hosts:
            - *host

ipv4NativeRoutingCIDR: "10.0.0.0/8"

loadBalancerIP:
  algorithm: maglev
  # DSR for TCP and SNAT for UDP
  mode: hybrid

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring
    trustCRDsExist: true
dashboards:
  enabled: true
  label: grafana_dashboard
  annotations:
    grafana.grafana.com/dashboards.target-directory: /tmp/dashboards/cilium

# -- Enable use of the remote node identity.
# ref: https://docs.cilium.io/en/v1.7/install/upgrade/#configmap-remote-node-identity
# Deprecated without replacement in 1.15. To be removed in 1.16.
remoteNodeIdentity: false

# Test if this is the cause of externalTrafficPolicy `Local` not working`
routingMode: native
operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: monitoring
  dashboards:
    enabled: true
    label: grafana_dashboard
    annotations:
      grafana.grafana.com/dashboards.target-directory: /tmp/dashboards/cilium

```

When I change my services to externalTrafficPolicy=Local they stop works.

I had previously MetalLB with flannel and MetalLB in BGP mode worked without problems. I know that's a totally different configuration but just to give the context that I know what is supposed to happen.

### Cilium Version

```
Image versions         cilium             quay.io/cilium/cilium:v1.15.1@sha256:351d6685dc6f6ffbcd5451043167cfa8842c6decf80d8c8e426a417c73fb56d4: 11
                       hubble-relay       quay.io/cilium/hubble-relay:v1.15.1@sha256:3254aaf85064bc1567e8ce01ad634b6dd269e91858c83be99e47e685d4bb8012: 1
                       cilium-operator    quay.io/cilium/operator-generic:v1.15.1@sha256:819c7281f5a4f25ee1ce2ec4c76b6fbc69a660c68b7825e9580b1813833fa743: 2
                       hubble-ui          quay.io/cilium/hubble-ui:v0.13.0@sha256:7d663dc16538dd6e29061abd1047013a645e6e69c115e008bee9ea9fef9a6666: 1
                       hubble-ui          quay.io/cilium/hubble-ui-backend:v0.13.0@sha256:1e7657d997c5a48253bb8dc91ecee75b63018d16ff5e5797e5af367336bc8803: 1
``` 
                     

### Kernel Version

```
k8s-odroid-c4-1 | CHANGED | rc=0 >>
Linux k8s-odroid-c4-1 6.1.63-current-meson64 #1 SMP PREEMPT Mon Nov 20 10:52:19 UTC 2023 aarch64 GNU/Linux
k8s-odroid-c4-2 | CHANGED | rc=0 >>
Linux k8s-odroid-c4-2 6.1.11-meson64 #23.02.2 SMP PREEMPT Sat Feb 18 00:07:55 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
k8s-amd64-1 | CHANGED | rc=0 >>
Linux k8s-amd64-1 5.15.0-97-generic #107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
k8s-odroid-hc4-3 | CHANGED | rc=0 >>
Linux k8s-odroid-hc4-3 6.1.11-meson64 #23.02.2 SMP PREEMPT Sat Feb 18 00:07:55 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
grigri | CHANGED | rc=0 >>
Linux grigri 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
k8s-rock64-1 | CHANGED | rc=0 >>
Linux k8s-rock64-1 5.15.93-rockchip64 #23.02.2 SMP PREEMPT Fri Feb 17 23:48:36 UTC 2023 aarch64 GNU/Linux
k8s-rock64-2 | CHANGED | rc=0 >>
Linux k8s-rock64-2 5.15.93-rockchip64 #23.02.2 SMP PREEMPT Fri Feb 17 23:48:36 UTC 2023 aarch64 GNU/Linux
k8s-rock64-3 | CHANGED | rc=0 >>
Linux k8s-rock64-3 5.15.52-rockchip64 #22.05.4 SMP PREEMPT Mon Jul 4 09:40:29 CEST 2022 aarch64 GNU/Linux
k8s-rock64-4 | CHANGED | rc=0 >>
Linux k8s-rock64-4 5.15.52-rockchip64 #22.05.4 SMP PREEMPT Mon Jul 4 09:40:29 CEST 2022 aarch64 GNU/Linux
k8s-rock64-5 | CHANGED | rc=0 >>
Linux k8s-rock64-5 5.15.76-rockchip64 #22.08.8 SMP PREEMPT Sun Oct 30 10:57:32 CET 2022 aarch64 GNU/Linux
k8s-rock64-6 | CHANGED | rc=0 >>
Linux k8s-rock64-6 5.15.52-rockchip64 #22.05.4 SMP PREEMPT Mon Jul 4 09:40:29 CEST 2022 aarch64 GNU/Linux
```

### Kubernetes Version

```
Server Version: v1.28.6+k3s2
```

### Anything else?

Advertising is doing good in the write nodes

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dylandreimerink** [comment]
Do you happen to have a sysdump or output of `cilium-dbg bgp routes advertised` output from one of the nodes with a pod for the given service?

**Comment by pando85** [comment]
I cannot run it until the weekend but I will do it.

Thanks for the quick response.

**Comment by pando85** [comment]
```
root@grigri:/home/cilium# cilium-dbg bgp routes advertised
(Defaulting to `ipv4 unicast` AFI & SAFI, please see help for more options)

VRouter   Peer            Prefix              NextHop         Age      Attrs
64513     192.168.192.1   192.168.193.1/32    192.168.192.2   10m59s   [{Origin: i} {AsPath: 64513} {Nexthop: 192.168.192.2}]   
64513     192.168.192.1   192.168.193.10/32   192.168.192.2   10m59s   [{Origin: i} {AsPath: 64513} {Nexthop: 192.168.192.2}]   
64513     192.168.192.1   192.168.193.2/32    192.168.192.2   10m59s   [{Origin: i} {AsPath: 64513} {Nexthop: 192.168.192.2}]   
64513     192.168.192.1   192.168.193.3/32    192.168.192.2   10m59s   [{Origin: i} {AsPath: 64513} {Nexthop: 192.168.192.2}]   
64513     192.168.192.1   192.168.193.4/32    192.168.192.2   10m59s   [{Origin: i} {AsPath: 64513} {Nexthop: 192.168.192.2}]   
64513     192.168.192.1   192.168.193.7/32    192.168.192.2   10m59s   [{Origin: i} {AsPath: 64513} {Nexthop: 192.168.192.2}]   
64513     192.168.192.1   192.168.193.8/32    192.168.192.2   10m59s   [{Origin: i} {AsPath: 64513} {Nexthop: 192.168.192.2}]   
64513     192.168.192.1   192.168.193.9/32    192.168.192.2   10m59s   [{Origin: i} {AsPath: 64513} {Nexthop: 192.168.192.2}]   
```
`192.168.193.10/32` is using `externalTrafficPolicy=Local`. The rest no.

**Comment by pando85** [comment]
Why when I do this the nextHop is different?:
```
» cilium-cli bgp routes
(Defaulting to `available ipv4 unicast` routes, please see help for more options)

Errors by retrieving routes: failed to fetch bgp state from cilium-l7b56: (error with exec request (pod=kube-system/cilium-l7b56, container=cilium-agent): error dialing backend: proxy error from 127.0.0.1:6443 while dialing 192.168.192.46:10250, code 502: 502 Bad Gateway)

Node          VRouter   Prefix              NextHop         Age      Attrs
grigri        64513     192.168.193.0/24    192.168.192.1   35m22s   [{Origin: i} {AsPath: 64512} {Nexthop: 192.168.192.1} {Med: 0}]   
              64513     192.168.193.1/32    0.0.0.0         35m28s   [{Origin: i} {Nexthop: 0.0.0.0}]                                  
              64513     192.168.193.10/32   0.0.0.0         21m33s   [{Origin: i} {Nexthop: 0.0.0.0}]                                  
              64513     192.168.193.2/32    0.0.0.0         35m28s   [{Origin: i} {Nexthop: 0.0.0.0}]                                  
              64513     192.168.193.3/32    0.0.0.0         35m28s   [{Origin: i} {Nexthop: 0.0.0.0}]                                  
              64513     192.168.193.4/32    0.0.0.0         35m28s   [{Origin: i} {Nexthop: 0.0.0.0}]                                  
              64513     192.168.193.7/32    0.0.0.0         35m28s   [{Origin: i} {Nexthop: 0.0.0.0}]                                  
              64513     192.168.193.8/32    0.0.0.0         35m28s   [{Origin: i} {Nexthop: 0.0.0.0}]                                  
              64513     192.168.193.9/32    0.0.0.0         35m28s   [{Origin: i} {Nexthop: 0.0.0.0}]                                  
k8s-amd64-1   64513     192.168.193.0/24    192.168.192.1   33m58s   [{Origin: i} {AsPath: 64512} {Nexthop: 192.168.192.1} {Med: 0}]   
              64513     192.168.193.1/32    0.0.0.0         34m7s    [{Origin: i} {Nexthop: 0.0.0.0}]                                  
              64513     192.168.193.2/32    0.0.0.0         34m7s    [{Origin: i} {Nexthop: 0.0.0.0}]                                  
              64513     192.168.193.3/32    0.0.0.0         34m7s    [{Origin: i} {Nexthop: 0.0.0.0}]                                  
              64513     192.168.193.4/32    0.0.0.0         34m7s    [{Origin: i} {Nexthop: 0.0.0.0}]                                  
              64513     192.168.193.7/32    0.0.0.0         34m7s    [{Origin: i} {Nexthop: 0.0.0.0}]                                  
              64513     192.168.193.8/32    0.0.0.0         34m7s    [{Origin: i} {Nexthop: 0.0.0.0}]                                  
              64513     192.168.193.9/32    0.0.0.0         34m7s    [{Origin: i} {Nexthop: 0.0.0.0}]      
```
And trace route do:
```
traceroute to 192.168.193.3 (192.168.193.3), 30 hops max, 60 byte packets
 1  _gateway (192.168.76.254)  9.705 ms  9.679 ms  9.673 ms
 2  grigri.grigri (192.168.192.2)  5.668 ms  9.966 ms  9.927 ms
 3  pfsense.grigri (192.168.192.1)  9.605 ms  9.608 ms  9.602 ms
 4  * grigri.grigri (192.168.192.2)  9.855 ms  9.850 ms
 5  pfsense.grigri (192.168.192.1)  9.581 ms  9.554 ms  9.550 ms
 6  grigri.grigri (192.168.192.2)  9.818 ms * *
 7  pfsense.grigri (192.168.192.1)  2.623 ms  2.833 ms  4.510 ms
 8  * * *
 9  pfsense.grigri (192.168.192.1)  4.161 ms  4.363 ms  4.377 ms
10  * * *
11  pfsense.grigri (192.168.192.1)  4.292 ms  2.729 ms  3.248 ms
12  * * *
13  pfsense.grigri (192.168.192.1)  3.270 ms  4.652 ms  3.174 ms
14  * * *
15  pfsense.grigri (192.168.192.1)  4.413 ms  3.216 ms  3.459 ms
16  * * *
17  pfsense.grigri (192.168.192.1)  3.962 ms  3.921 ms  3.932 ms
18  * * *
19  pfsense.grigri (192.168.192.1)  6.088 ms  6.654 ms  6.855 ms
20  * * *
21  pfsense.grigri (192.168.192.1)  3.728 ms  3.630 ms  3.596 ms
22  * * *
23  pfsense.grigri (192.168.192.1)  5.069 ms  4.854 ms  4.825 ms
24  * * *
25  pfsense.grigri (192.168.192.1)  4.380 ms  5.082 ms  5.999 ms
26  * * *
27  pfsense.grigri (192.168.192.1)  4.984 ms  4.312 ms  3.574 ms
28  * * *
29  pfsense.grigri (192.168.192.1)  6.309 ms  6.289 ms  6.254 ms
30  * * *
```
`192.168.192.1` and `192.168.76.254` are the same router.

**Comment by pando85** [comment]
I tested it also with `routingMode: tunnel` and `autoDirectNodeRoutes: false`. Same result.

**Comment by pando85** [comment]
I did some fixes:
- I installed kube-router (with chart from https://charts.enix.io/) for advertising services:
  ```yaml
  kubeRouter:
  cni:
    install: false

  router:
    enabled: true
    enableOverlay: true
    enableIbgp: true
    enableCni: false
    clusterAsn: 64513
    advertiseLoadbalancerIp: true
    advertiseExternalIp: true
    advertiseClusterIp: true

  firewall:
    enabled: false
  serviceProxy:
    enabled: false

  ```
- I removed `192.168.193.0/24` subnet from BGP advertised and now I get:
  ```
  root@grigri:/home/cilium# cilium-dbg bgp routes advertised
  (Defaulting to `ipv4 unicast` AFI & SAFI, please see help for more options)

  VRouter   Peer            Prefix              NextHop         Age      Attrs
  64513     192.168.192.1   192.168.193.1/32    192.168.192.2   31m17s   [{Origin: i} {AsPath: 64513} {Nexthop: 192.168.192.2}]   
  64513     192.168.192.1   192.168.193.10/32   192.168.192.2   30m23s   [{Origin: i} {AsPath: 64513} {Nexthop: 192.168.192.2}]   
  64513     192.168.192.1   192.168.193.2/32    192.168.192.2   31m17s   [{Origin: i} {AsPath: 64513} {Nexthop: 192.168.192.2}]   
  64513     192.168.192.1   192.168.193.3/32    192.168.192.2   31m17s   [{Origin: i} {AsPath: 64513} {Nexthop: 192.168.192.2}]   
  64513     192.168.192.1   192.168.193.4/32    192.168.192.2   31m17s   [{Origin: i} {AsPath: 64513} {Nexthop: 192.168.192.2}]   
  64513     192.168.192.1   192.168.193.7/32    192.168.192.2   31m17s   [{Origin: i} {AsPath: 64513} {Nexthop: 192.168.192.2}]   
  64513     192.168.192.1   192.168.193.8/32    192.168.192.2   31m17s   [{Origin: i} {AsPath: 64513} {Nexthop: 192.168.192.2}]   
  64513     192.168.192.1   192.168.193.9/32    192.168.192.2   1m2s     [{Origin: i} {AsPath: 64513} {Nexthop: 192.168.192.2}] 
  ```

  In my FRR routes with all services configured with `externalTrafficPolicy=Local`:
  ```
  BGP table version is 48, local router ID is 192.168.192.1, vrf id 0
  Default local pref 100, local AS 64512
  Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
                i internal, r RIB-failure, S Stale, R Removed
  Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
  Origin codes:  i - IGP, e - EGP, ? - incomplete
  RPKI validation codes: V valid, I invalid, N Not found

      Network          Next Hop            Metric LocPrf Weight Path
  *= 192.168.193.1/32 192.168.192.11                  0      0 64513 i
  *>                  192.168.192.2                   0      0 64513 i
  *> 192.168.193.2/32 192.168.192.2                   0      0 64513 i
  *> 192.168.193.3/32 192.168.192.2                   0      0 64513 i
  *= 192.168.193.4/32 192.168.192.31                  0      0 64513 i
  *>                  192.168.192.2                   0      0 64513 i
  *= 192.168.193.7/32 192.168.192.42                  0      0 64513 i
  *=                  192.168.192.32                  0      0 64513 i
  *=                  192.168.192.44                  0      0 64513 i
  *=                  192.168.192.46                  0      0 64513 i
  *=                  192.168.192.45                  0      0 64513 i
  *=                  192.168.192.43                  0      0 64513 i
  *=                  192.168.192.23                  0      0 64513 i
  *=                  192.168.192.41                  0      0 64513 i
  *=                  192.168.192.31                  0      0 64513 i
  *=                  192.168.192.11                  0      0 64513 i
  *>                  192.168.192.2                   0      0 64513 i
  *> 192.168.193.8/32 192.168.192.2                   0      0 64513 i
  *> 192.168.193.9/32 192.168.192.2                   0      0 64513 i
  *> 192.168.193.10/32
                      192.168.192.2                   0      0 64513 i
  ```
But I still get no response from outside the cluster.

My current Cilium configuration:
```
debug:
  enabled: true

rollOutCiliumPods: true

serviceAccounts:
  # cert-manager used instead
  clustermeshcertgen:
    create: false
  hubblecertgen:
    create: false

k8sServiceHost: grigri.grigri
k8sServicePort: "6443"

securityContext:
  capabilities:
    ciliumAgent:
      # Use to set socket permission
      - CHOWN
      # Used to terminate envoy child process
      - KILL
      # Used since cilium modifies routing tables, etc...
      - NET_ADMIN
      # Used since cilium creates raw sockets, etc...
      - NET_RAW
      # Used since cilium monitor uses mmap
      - IPC_LOCK
      # Used in iptables. Consider removing once we are iptables-free
      - SYS_MODULE
      # Could be an alternative for the SYS_ADMIN for the RLIMIT_NPROC
      - SYS_RESOURCE
      # it should not be required for Kernel >= 5.8 but
      # it triggers the error `failed to create new netns: operation not permitted` without it
      - SYS_ADMIN
      # Both PERFMON and BPF requires kernel 5.8, container runtime
      # cri-o >= v1.22.0 or containerd >= v1.5.0.
      # If available, SYS_ADMIN can be removed.
      - PERFMON
      - BPF
      # Allow discretionary access control (e.g. required for package installation)
      - DAC_OVERRIDE
      # Allow to set Access Control Lists (ACLs) on arbitrary files (e.g. required for package installation)
      - FOWNER
      # Allow to execute program that changes GID (e.g. required for package installation)
      - SETGID
      # Allow to execute program that changes UID (e.g. required for package installation)
      - SETUID
    # -- Capabilities for the `mount-cgroup` init container
    cleanCiliumState:
      # Most of the capabilities here are the same ones used in the
      # cilium-agent's container because this container can be used to
      # uninstall all Cilium resources, and therefore it is likely that
      # will need the same capabilities.
      # Used since cilium modifies routing tables, etc...
      - NET_ADMIN
      # Used in iptables. Consider removing once we are iptables-free
      - SYS_MODULE
      # Could be an alternative for the SYS_ADMIN for the RLIMIT_NPROC
      - SYS_RESOURCE
      # Both PERFMON and BPF requires kernel 5.8, container runtime
      # cri-o >= v1.22.0 or containerd >= v1.5.0.
      # If available, SYS_ADMIN can be removed.
      - PERFMON
      - BPF

# If all nodes share a single L2 network, then this can be taken care of by enabling
# the option auto-direct-node-routes: true. Otherwise, an additional system component such as a BGP daemon must be run
autoDirectNodeRoutes: true
# if autoDirectNodeRoutes is false then the following cannot be used
ipv4NativeRoutingCIDR: "10.0.0.0/8"

bgp:
  enabled: false

# -- This feature set enables virtual BGP routers to be created via
# CiliumBGPPeeringPolicy CRDs.
bgpControlPlane:
  enabled: true
  secretsNamespace:
    name: kube-system

containerRuntime:
  integration: containerd
  socketPath: /var/run/k3s/containerd/containerd.sock

kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: "0.0.0.0:10256"

loadBalancer:
  standalone: false
  algorithm: maglev
  # DSR for TCP and SNAT for UDP
  mode: hybrid
  acceleration: best-effort

nodePort:
  # enabled cause kubeProxyReplacement is true
  enabled: true

hostPort:
  # enabled cause kubeProxyReplacement is true
  enabled: true

socketLB:
  # enabled cause kubeProxyReplacement is true
  enabled: true

hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - http
    serviceMonitor:
      enabled: true
      labels:
        release: monitoring
    dashboards:
      enabled: true
      annotations:
        grafana.grafana.com/dashboards.target-directory: /tmp/dashboards/cilium
      label: grafana_dashboard
  tls:
    enabled: true
    auto:
      enabled: true
      method: certmanager
      certManagerIssuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: internal
  relay:
    enabled: true
    rollOutPods: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        labels:
          release: monitoring
  ui:
    enabled: true
    rollOutPods: true
    ingress:
      enabled: true
      className: nginx-internal
      annotations:
        external-dns.alpha.kubernetes.io/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod-dns
      hosts:
        - &host hubble.internal.grigri.cloud
      tls:
        - secretName: hubble-tls-certificate
          hosts:
            - *host

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring
    trustCRDsExist: true
dashboards:
  enabled: true
  label: grafana_dashboard
  annotations:
    grafana.grafana.com/dashboards.target-directory: /tmp/dashboards/cilium

# -- Enable use of the remote node identity.
# ref: https://docs.cilium.io/en/v1.7/install/upgrade/#configmap-remote-node-identity
# Deprecated without replacement in 1.15. To be removed in 1.16.
remoteNodeIdentity: false

#tunnelProtocol: vxlan

# -- Enable native-routing mode or tunneling mode.
# Possible values:
#   - ""
#   - native
#   - tunnel
# @default -- `"tunnel"`
#routingMode: tunnel
# # Test if this is the cause of externalTrafficPolicy `Local` not working`
routingMode: native

# -- Configure VXLAN and Geneve tunnel port.
# @default -- Port 8472 for VXLAN, Port 6081 for Geneve
#tunnelPort: 8472

operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: monitoring
  dashboards:
    enabled: true
    label: grafana_dashboard
    annotations:
      grafana.grafana.com/dashboards.target-directory: /tmp/dashboards/cilium

```

**Comment by pando85** [comment]
I fallback to MetalLB configuration combined with Cilium and `externalTrafficPolicy: Local` doesn't work.

I guess that the error should be related with my Cilium CNI configuration and not with BGP control plane.

**Comment by pando85** [comment]
The problem was related with the kube-proxy replacement. It was not working correctly. I disabled it and enabled again kube-proxy.

**Comment by ThisIsntTheWay** [comment]
Reopening this because I am facing the same issue, although I am not using any BGP but have an otherwise similar infrastructure.  
Unfortunately, disabling and re-enabling `kube-proxy-replacement` didn't work for me.  

I am running an HA k3s `v1.28.7+k3s1` cluster with Cilium `v1.14.4` and using MetalLB as the service load balancer.  
IPs are advertised through L2.

Setting `externalTrafficPolicy: Local` renders services inaccessible outside the cluster (a timeout occurs).  
Traffic isn't even captured in hubble, so I guess it's being dropped/lost very early on already...?

Hubble observation when `externalTrafficPolicy: Cluster`:
```bash
$ hubble observe flows -n ingress-nginx --from-identity world
Apr 19 18:10:36.691: 10.43.3.140:56588 (world) -> ingress-nginx/ingress-nginx-controller-rhjjq:80 (ID:42517) to-overlay FORWARDED (TCP Flags: ACK)
Apr 19 18:10:36.691: 10.43.3.140:56588 (world) -> ingress-nginx/ingress-nginx-controller-rhjjq:80 (ID:42517) to-overlay FORWARDED (TCP Flags: ACK)
Apr 19 18:10:36.694: 10.43.3.140:56588 (world) -> ingress-nginx/ingress-nginx-controller-rhjjq:80 (ID:42517) to-overlay FORWARDED (TCP Flags: ACK, FIN)
```

Hubble observation when `externalTrafficPolicy: Local`:
```bash
$ hubble observe flows -n ingress-nginx --from-identity world
# No output
```

### Troubleshooting info
Sysdump: [cilium-sysdump-20240419-201607.zip](https://github.com/cilium/cilium/files/15044316/cilium-sysdump-20240419-201607.zip)
Helm values Cilium:
```yaml
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: ["10.43.0.0/16"]
k8sClientRateLimit:
  qps: 32.5
  burst: 37
bpf:
  masquerade: true
egressGateway:
  enabled: true
l7Proxy: false
kubeProxyReplacement: true
devices: eth+
```

k3s config YAML:
```yaml
flannel-backend: none
disable-network-policy: true
disable-kube-proxy: true
disable:
- traefik
- servicelb
```
