### ISSUE TITLE
CFP: BackendTLSPolicy for Cilium Gateway API and HTTPRoutes

### ISSUE THREAD

**Issue by dhaugli** [cilium/cilium#31352]
## Cilium Feature Proposal
        
We have a need to be able to use BackendTLSPolicy in Cilium Gateway API for HTTProutes to our services, which is defined in the Gateway API standard in Kubernetes: [https://gateway-api.sigs.k8s.io/api-types/backendtlspolicy/?h=backendtlspolicy](https://gateway-api.sigs.k8s.io/api-types/backendtlspolicy/?h=backendtlspolicy)

**Describe the feature you'd like**

We are currently experiencing issues when using Cilium Gateway API, especially for services that has its own TLS already pre-configured.

**Comment by kenlasko** [comment]
Am I to assume that Cilium Gateway API does not currently support BackendTLSPolicy for HTTPRoutes as of 1.15.2? That would explain why its not working for me after following the Gateway API docs on configuring it.  I don't get any errors, but I also don't see any **Status** in the BackendTLSPolicy object.

I also would like to see this implemented.

**Comment by OevreFlataeker** [comment]
I make the same observation like @kenlasko - I "think" I configured everything correct(?) but it just does not seem to work. I try to do terminate-and-reencrypt on my gateway to my backend service but the backend keeps on saying I am talking http to it instead of https as specified via the BackendTLSPolicy

**Comment by RyanMnM** [comment]
Having the same issue as @OevreFlataeker where a backend service is expecting a HTTPS connection but is only getting a HTTP one from the gateway.

I can get this working with the below but I then loose the use of the signed certificate from Cert-Manager and only the Self Signed from the service is presented.

| Listener Protocol | TLS Mode | Route Type Supported |
|-------------------|-------------|----------------------|
| TLS | Passthrough | TLSRoute |

**Comment by OevreFlataeker** [comment]
Could you kindly provide a full example what you did so I can check this with my setup? (Still beginner...) Thanks!

**Comment by kenlasko** [comment]
Here's my config:

```
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kubeapi
  namespace: cilium
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.1.14
  listeners:
  - name: https
    protocol: TLS
    port: 443
    hostname: "k3s.mydomain.com"
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: letsencrypt-wildcard-cert
        namespace: cilium
    allowedRoutes: 
      namespaces:
        from: All

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kubeapi
  namespace: default
spec:
  parentRefs:
  - name: kubeapi
    namespace: cilium
    sectionName: https
  hostnames:
  - "k3s.mydomain.com"
  rules:
  - backendRefs:
    - name: kubernetes
      namespace: default
      group: ""
      kind: Service
      port: 443

---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: BackendTLSPolicy
metadata:
  name: k3s-tls-policy
  namespace: default
spec:
  targetRef:
    kind: Service
    name: kubernetes
    group: ""
    namespace: default
  tls:
    caCertRefs: 
      - kind: ConfigMapReference
        name: kube-root-ca.crt
        group: ""
    hostname: k3s.ucdialplans.com
```

Everything gets created, but the **BackendTLSPolicy** object doesn't have a **Status** like every other Gateway API object, which implies that its not actually active at all. The spec for BackendTLSPolicy states that **Status** should be there.

This would make sense as it appears that **BackendTLSPolicy** has yet to be implemented in Cilium.
