### ISSUE TITLE
Endpoint context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by fcj78** [cilium/cilium#31382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I installed my new cluster with kubeadm on premise.

Kubernetes version : 1.29.2
Cilium version : 1.15.1
Kernel version control plane : 5.15.0-100-generic
Kernel version workers : 6.7.6-arch1-1
ip_forward is enable on all workers and control plane

My cluster : 

1 control plane : 
      IP 1 : 172.16.10.10/24 -> internet
      IP 2 : 192.168.10.201/24 -> Shared L2

3 workers : 
      worker 1 : 
          IP 1 : 172.16.10.210/24 -> internet
          IP 2 : 192.168.10.236/24 -> Shared L2

      worker 2 : 
          IP 1 : 172.16.10.220/24 -> internet
          IP 2 : 192.168.10.218/24 -> Shared L2

      worker 3 : 
          IP 1 : 172.16.10.230/24 -> internet
          IP 2 : 192.168.10.154/24 -> Shared L2

```
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
 advertiseAddress: 192.168.10.201
 bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: stable
clusterName: "mycluster"
apiServer:
 certSANs:
 - "mycluster.mydomain.com"
controlPlaneEndpoint: "mycluster.mydomain.com:6443"
networking:
 dnsDomain: "mydomain"
```
kubeadm init --config=kubeadm-config.yaml --skip-phases=addon/kube-proxy

And this my cilium configuration : 

```
cluster:
 id: 0
 name: mycluster
encryption:
 nodeEncryption: false
kubeProxyReplacement: true
gatewayAPI:
 enabled: true
bpf:
 masquerade: true
ipam:
 mode: "cluster-pool"
 operator:
  clusterPoolIPv4PodCIDRList:
  - "10.10.0.0/16"
ipv4NativeRoutingCIDR: "10.10.0.0/16"
k8sServiceHost: "mycluster.mydomain.com"
k8sServicePort: "6443"
l2announcements:
 enabled: true
devices: "eth0" # IP1
externalIPs:
 enabled: true
hubble:
 peerService:
  clusterDomain: "mydomain"
 relay:
  enabled: true
  podLabels: {site: mysite}
 ui:
  enabled: true
operator:
 replicas: 1
serviceAccounts:
 cilium:
  name: cilium
 operator:
  name: cilium-operator
routingMode: native
autoDirectNodeRoutes: true
```

After this deployment, this is my endpoints status : 

```
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
Probe time:   2024-03-13T15:42:36Z
Nodes:
  mycluster/worker2 (localhost):
    Host connectivity to 192.168.10.218:
      ICMP to stack:   OK, RTT=433.057µs
      HTTP to agent:   OK, RTT=618.389µs
    Endpoint connectivity to 10.10.0.138:
      ICMP to stack:   OK, RTT=506.758µs
      HTTP to agent:   OK, RTT=669.128µs
  mycluster/master1:
    Host connectivity to 192.168.10.201:
      ICMP to stack:   OK, RTT=717.085µs
      HTTP to agent:   OK, RTT=1.009761ms
    Endpoint connectivity to 10.10.1.73:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.10.1.73:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  mycluster/worker1:
    Host connectivity to 192.168.10.236:
      ICMP to stack:   OK, RTT=1.255544ms
      HTTP to agent:   OK, RTT=2.936239ms
    Endpoint connectivity to 10.10.2.10:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.10.2.10:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  mycluser/worker3:
    Host connectivity to 192.168.10.154:
      ICMP to stack:   OK, RTT=1.113117ms
      HTTP to agent:   OK, RTT=2.586088ms
    Endpoint connectivity to 10.0.0.75:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.0.0.75:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

On my control plane/workers, I have my Cilium routes.

```
10.10.0.0/24 via 192.168.10.218 dev eth1 proto kernel 
10.10.1.0/24 via 10.10.1.220 dev cilium_host proto kernel src 10.10.1.220 
10.10.1.220 dev cilium_host proto kernel scope link 
10.10.2.0/24 via 192.168.10.236 dev eth1 proto kernel 
```

From my control plane i can ping my workers and i can ping all cilium_host interface, but i can't ping cilium endpoint. However, from my worker, I can ping its local endpoint.

Do you have any idea what's going on ?

Thank you

### Cilium Version

1.15.1

### Kernel Version

Kernel version control plane : 5.15.0-100-generic
Kernel version workers : 6.7.6-arch1-1

### Kubernetes Version

1.29.2

### Regression

1.14.3

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
[Uploading cilium-sysdump-20240314-143604.zip…]()

**Comment by dylandreimerink** [comment]
Thanks for this report, would you be able to grab a sysdump file and upload it please so we can better debug the issue? (Using https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection)

**Comment by fcj78** [comment]
Normally you have the sysdump in my first comment, don't hesitate if you need additional information.

**Comment by sunilkbp** [comment]
I am also hitting same issue with cilium in my network :

root@hrcstg-k8s-node-1:/home/cilium# cilium-health status
Probe time:   2024-06-27T13:43:13Z
Nodes:
  hrcstg-k8s-node-1 (localhost):
    Host connectivity to 10.125.16.84:
      ICMP to stack:   OK, RTT=644.596µs
      HTTP to agent:   OK, RTT=1.33443ms
    Endpoint connectivity to 192.168.128.4:
      ICMP to stack:   Connection timed out
      HTTP to agent:   OK, RTT=789.218µs
  hrcstg-k8s-node-2:
    Host connectivity to 10.125.16.85:
      ICMP to stack:   OK, RTT=1.036884ms
      HTTP to agent:   OK, RTT=2.163953ms
    Endpoint connectivity to 192.168.129.103:
      ICMP to stack:   OK, RTT=1.449ms
      HTTP to agent:   Get "http://192.168.129.103:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  hrcstg-k8s-node-3:
    Host connectivity to 10.125.16.86:
      ICMP to stack:   OK, RTT=722.9µs
      HTTP to agent:   OK, RTT=2.923732ms
    Endpoint connectivity to 192.168.130.121:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://192.168.130.121:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  hrcstg-k8s-node-4:
    Host connectivity to 10.125.16.87:
      ICMP to stack:   OK, RTT=1.23566ms
      HTTP to agent:   OK, RTT=3.383449ms
    Endpoint connectivity to 192.168.131.170:
      ICMP to stack:   OK, RTT=1.355989ms
      HTTP to agent:   Get "http://192.168.131.170:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  hrcstg-k8s-node-5:
    Host connectivity to 10.125.16.88:
      ICMP to stack:   OK, RTT=990.785µs
      HTTP to agent:   OK, RTT=2.813248ms
    Endpoint connectivity to 192.168.133.51:
      ICMP to stack:   OK, RTT=1.055131ms
      HTTP to agent:   Get "http://192.168.133.51:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  hrcstg-k8s-node-6:
    Host connectivity to 10.125.16.89:
      ICMP to stack:   OK, RTT=1.320136ms
      HTTP to agent:   OK, RTT=3.506632ms
    Endpoint connectivity to 192.168.132.227:
      ICMP to stack:   OK, RTT=1.406974ms
      HTTP to agent:   Get "http://192.168.132.227:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
root@hrcstg-k8s-node-1:/home/cilium# 

Facing endpoint communication issue with cilium. 

Cilium log show: 
level=debug msg="Greeting failed" error="Get \"http://192.168.129.103:4240/hello\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" host="http://192.168.129.103:4240" ipAddr=192.168.129.103 nodeName=hrcstg-k8s-node-2 path="Via L3" subsys=health-server
level=debug msg="Failed to probe: Get \"http://192.168.129.103:4240/hello\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" ipAddr=192.168.129.103 nodeName=hrcstg-k8s-node-2 port=4240 subsys=health-server
level=debug msg="Greeting host" host="http://192.168.130.121:4240" ipAddr=192.168.130.121 nodeName=hrcstg-k8s-node-3 path="Via L3" subsys=health-server
level=debug msg="Handling request for /healthz" subsys=health-server

Need help for this issue. we are hitting this issue consistently in one of the cluster. 

[cilium_node1.log](https://github.com/user-attachments/files/16018795/cilium_node1.log)

**Comment by FilipeNas** [comment]
same problem here

**Comment by lucian1094** [comment]
Same problem, cilium v1.16.2 kubernetes 1.28.2

**Comment by gengmenglong** [comment]
same problem, I can't find of a solution to this problem

gml@ubuntu-master:/Users/gml/menglong/kubernetes/cilium$ uname -a
Linux ubuntu-master 6.11.9-orbstack-00279-g4cf512143f2e #60 SMP Mon Nov 18 05:48:29 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

ubuntu-master:/Users/gml/menglong/kubernetes/cilium$ kubectl -n kube-system exec -ti cilium-d7sm7 -- cilium-health status
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
Probe time:   2025-02-08T01:42:15Z
Nodes:
  ubuntu-master (localhost):
    Host connectivity to 198.19.249.226:
      ICMP to stack:   OK, RTT=1.324678ms
      HTTP to agent:   OK, RTT=432.571µs
    Endpoint connectivity to 10.244.0.108:
      ICMP to stack:   OK, RTT=1.335179ms
      HTTP to agent:   OK, RTT=810.759µs
  ubuntu-node:
    Host connectivity to 198.19.249.15:
      ICMP to stack:   OK, RTT=1.32001ms
      HTTP to agent:   OK, RTT=629.604µs
    Endpoint connectivity to 10.244.3.233:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.244.3.233:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  ubuntu-node1:
    Host connectivity to 198.19.249.20:
      ICMP to stack:   OK, RTT=1.251249ms
      HTTP to agent:   OK, RTT=5.699444ms
    Endpoint connectivity to 10.244.2.226:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.244.2.226:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by jqlynchien713** [comment]
I was facing the same problem as deploying cilium in EKS, but it turns out that the settings for my security group didn't even allow UDP 8472 ingress. By default the module i used to build up EKS only allow all TCP ingress in security groups. Hope this help someone, it really takes me a lot of time to debug this issue 🥲

**Comment by arefg** [comment]
I had this exact problem, and ports between nodes are all open and I can see the traffic flow on my firewall to VXLAN port on nodes, but the weird thing is that only ping traverses between pods on different hosts and all other traffics including Cilium's "HTTP to agent" times out (Even between worker nodes on the same L2 network). There is no policy or any other non-default configuration in-place and this is a fresh installation of Kubernetes and Cilium. I have used "Cilium monitor", "hubble observe" and "tcpdump" and I can see the source is sending SYN to the destination, but on the destination, nothing is received. After a week of searching and not finding any solution to this, I gave up on VXLAN and switched to BGP and it's working now. (Linux Kernel 6.8.0-58, Ubuntu 24.04.2, Cilium 1.17.3)

**Comment by eremcan** [comment]
We are also having same issue. 
watch -n 1 kubectl -n kube-system exec -ti cilium-nkgjm -- cilium-health status --verbose
we were testing out if some packages are dropped via ebpf 
root@nebula-m01:~# kubectl -n kube-system exec -ti cilium-kqvl9 -- cilium-dbg monitor --type drop
xx drop (Unsupported L3 protocol) flow 0x0 to endpoint 0, ifindex 9, file bpf_lxc.c:1493, , identity 2430->unknown: fe80::8c7c:aff:fece:aceb -> ff02::2 RouterSolicitation
there are no packages dropped for every second on any policy by Ebpf. 

(Ubuntu 24.04.2, Cilium 1.16.3)
@arefg How did you switch vxlan to bgp? Our Values yaml like below,
```
ipam:
  mode: "kubernetes"
kubeProxyReplacement: true
bpf:
  preallocateMaps: true
envoy:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  resources:
    limits:
      cpu: 1000m
      memory: 8Gi
    requests:
      cpu: 100m
      memory: 512Mi
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
prometheus:
  enabled: false
  port: 9966
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9963"
  serviceMonitor:
    enabled: false
    trustCRDsExist: false
dashboards:
  enabled: false
  label: grafana_dashboard
  namespace: ~
  labelValue: "1"
  annotations: {}
nodePort:
  enabled: true
  range: "40000,42767"
k8sServiceHost: "xxx"
k8sServicePort: "6443"
operator:
  resources:
    limits:
      cpu: 1000m
      memory: 8Gi
    requests:
      cpu: 100m
      memory: 512Mi
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  prometheus:
    enabled: false
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9963"
    serviceMonitor:
      enabled: false
    dashboards:
      enabled: false
hubble:
  enabled: false
  metrics:
    enableOpenMetrics: false
    enabled:
    - dns:query;ignoreAAAA
    - drop:sourceContext=identity|app;destinationContext=identity|app
    - tcp
    - icmp
    - port-distribution
    - "flow:sourceContext=identity|namespace|pod|pod-name|dns|ip|reserved-identity|workload|workload-name|app;destinationContext=identity|namespace|pod|pod-name|dns|ip|reserved-identity|workload|workload-name|app"
    - "httpV2:exemplars=true;labelsContext=source_ip,source_workload,source_namespace,source_app,destination_workload,destination_ip,destination_namespace,destination_pod,destination_app,traffic_direction;sourceContext=reserved-identity|identity|namespace|pod|workload-name|ip|app|pod-name|dns;sourceEgressContext=reserved-identity|identity|namespace|pod|workload-name|ip|app|pod-name|dns;sourceIngressContext=reserved-identity|identity|namespace|pod|workload-name|ip|app|pod-name|dns;destinationIngressContext=reserved-identity|identity|namespace|pod|workload-name|ip|app|pod-name|dns;destinationEgressContext=reserved-identity|identity|namespace|pod|workload-name|ip|app|pod-name|dns;destinationContext=reserved-identity|identity|namespace|pod|workload-name|ip|app|pod-name|dns"
    serviceMonitor:
      enabled: false
    dashboards:
      enabled: false
      annotations:
        grafana_folder: "Hubble"
  relay:
    enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 5Gi
      requests:
        cpu: 100m
        memory: 256Mi
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    prometheus:
      enabled: false
      port: 9966
      serviceMonitor:
        enabled: false
  ui:
    backend:
      resources:
        limits:
          cpu: 300m
          memory: 3Gi
        requests:
          cpu: 50m
          memory: 256Mi
    frontend:
      resources:
        limits:
          cpu: 300m
          memory: 3Gi
        requests:
          cpu: 50m
          memory: 256Mi
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    enabled: false
  exporter:
    prometheus:
      enabled: false
      port: 9091
  dashboards:
    enabled: false
  serviceMonitor:
    enabled: false
l7Proxy: true
bgpControlPlane:
  enabled: true
# -- Agent resource limits & requests
resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 100m
    memory: 512Mi
# -- resources & limits for the agent init containers
initResources:
  limits:
    cpu: 1000m
    memory: 10Gi
  requests:
    cpu: 100m
    memory: 100Mi
startupProbe:
  # -- failure threshold of startup probe.
  # 105 x 2s translates to the old behaviour of the readiness probe (120s delay + 30 x 3s)
  failureThreshold: 105
  # -- interval between checks of the startup probe
  periodSeconds: 2
livenessProbe:
  # -- failure threshold of liveness probe
  failureThreshold: 3
  # -- interval between checks of the liveness probe
  periodSeconds: 30
readinessProbe:
  # -- failure threshold of readiness probe
  failureThreshold: 3
  # -- interval between checks of the readiness probe
  periodSeconds: 30
k8s:
  requireIPv4PodCIDR: true
hostPort:
  enabled: true

```
