### ISSUE TITLE
Cilium 1.15.2 does not start on Kubernetes 1.29 dual-stack cluster

### ISSUE THREAD

**Issue by RomLecat** [cilium/cilium#31463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium pods are crash looping with the following error:

```
level=fatal msg="failed to start: daemon creation failed: error while initializing daemon: failed while reinitializing datapath: failed to setup base devices: Failed to sysctl -w net.ipv6.conf.cilium_host.forwarding=1: could not open the sysctl file /proc/sys/net/ipv6/conf/cilium_host/forwarding: open /proc/sys/net/ipv6/conf/cilium_host/forwarding: read-only file system" subsys=daemon
```

### Cilium Version

1.15.2

### Kernel Version

6.1.0-17

### Kubernetes Version

1.29.3

### Anything else?

My values.yaml:

```
kubeProxyReplacement: True
k8sServiceHost: "<lb-dns>"
k8sServicePort: "6443"
auto-direct-node-routes: True
routing-mode: native
ipv6:
  enabled: True
ipv4NativeRoutingCIDR: "<ipv4-pod-net>"
ipv6NativeRoutingCIDR: "<ipv6-pod-net>"
bpf:
  masquerade: True
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
