### ISSUE TITLE
Bad performance between pods on different nodes

### ISSUE THREAD

**Issue by CrimsonFez** [cilium/cilium#31529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I get around 6-7 gbit/s when i run iperf3 on 2 pods, each on seperate nodes connected over 10gbe. I have MTU 9000 set on the host. On the hosts i get 9.9gbit/s as expected, but when iperf3 is running in pods I have decreased performance. Additionally, when I run one of the iperf3 on the host and the other on the pod I also have 9.9gbit/s (server on host and in pod has same result). 

It looks to me like when traffic stays in Cilium it is slow.

### Cilium Version

1.15.2

### Kernel Version

5.10

### Kubernetes Version

1.26.12

### Sysdump

[cilium-sysdump-20240320-125239.zip](https://github.com/cilium/cilium/files/14670678/cilium-sysdump-20240320-125239.zip)

### Anything else?

Here is my helm config
```yaml
upgradeCompatibility: 1.15.2
rollOutCiliumPods: true
kubeProxyReplacement: true
socketLB:
  hostNamespaceOnly: true
k8sServiceHost: 192.168.100.14
k8sServicePort: 6443
routingMode: native
autoDirectNodeRoutes: true
ipv4NativeRoutingCIDR: 10.0.0.0/8
bpf:
  masquerade: true
  hostLegacyRouting: false
hubble:
  enabled: false
MTU: 9000
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
