### ISSUE TITLE
CFP: Enhanced Authentication Support for Cilium

### ISSUE THREAD

**Issue by Tharsanan1** [cilium/cilium#31604]
### Introduction:
Cilium, while currently supporting the Gateway API specification[1], lacks crucial authentication functionalities. Authentication is paramount for securing APIs, ensuring only authorized users or systems access sensitive resources. This proposal aims to integrate authentication support into Cilium, through inspiration of the Envoy Gateway’s SecurityPolicy[2] Custom Resource Definition (CRD).

### Objective:
The primary goal of this proposal is to enhance Cilium's capabilities by enabling authentication functionalities. By doing so, Cilium operators will have the means to enforce robust authentication mechanisms for their API endpoints.

#### Helm Chart Modifications:

Upon installation of the Cilium Helm chart, modifications will be made to include the deployment of Envoy SecurityPolicy CRD within the cluster.

#### Cilium Operator Enhancements:

The Cilium Operator will be updated to monitor SecurityPolicy CRs within the cluster.
Upon detection of SecurityPolicy CRs, the operator will dynamically generate Envoy authentication filters[3].
Relevant route configurations based on Gateway API CRs will be applied to these authentication filters.

### Example scenario

Upon implementation of the proposed changes outlined in the proposal, consider the following scenario where a user creates the specified Custom Resource Definitions (CRDs) for the Gateway and SecurityPolicy:

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: default
spec:
  gatewayClassName: eg
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
---

apiVersion: cilium.io/v1
kind: SecurityPolicy
metadata:
  name: jwt-authn-policy
  namespace: default
spec:
  jwt:
    providers:
    - name: example
      remoteJWKS:
        uri: https://raw.githubusercontent.com/envoyproxy/gateway/main/examples/kubernetes/jwt/jwks.json
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
    namespace: default
```

As the Cilium Operator loads the relevant CRs for the gateway, it will also load the SecurityPolicy. Based on the SecurityPolicy specifications, the Operator will dynamically configure the Cilium Endpoint Controller (CEC) to include authentication filters. For instance, the generated CEC configuration may resemble the following snippet:

```
'@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          commonHttpProtocolOptions:
            maxStreamDuration: 0s
          httpFilters:
          - name: envoy.filters.http.JwtAuthentication
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
              providers:
                provider_funnel:
                  issuer: https://auth.funnel-labs.io/auth/realms/funnel
                  remote_jwks:
                    http_uri:
                      uri: https://raw.githubusercontent.com/envoyproxy/gateway/main/examples/kubernetes/jwt/jwks.json
                      cluster: "default/cec_name/auth_cluster"
                      timeout: 10s
                   forward_payload_header: x-jwt-payload
              rules:
                - match:
                    prefix: /
                  requires:
                    provider_name: auth_provider

```

[1] - https://docs.cilium.io/en/latest/network/servicemesh/gateway-api/gateway-api/
[2] - https://gateway.envoyproxy.io/v0.6.0/design/security-policy/
