### ISSUE TITLE
Star Wars Demo is broken in rc7

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3162]
* https://github.com/cilium/star-wars-demo/tree/master/v2 is broken in at least rc7
* it works fine on rc5.
* Policy is loaded, shows up in `cilium policy get` but is not enforced correctly
* It looks like an L7 wildcard is taking place

Policy
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "Deathstar Layer 7 policies"
metadata:
  name: "deathstar-l7"
spec:
  endpointSelector:
    matchLabels:
      class: deathstar
      org: empire
  ingress:
  - fromEndpoints:
    - matchLabels:
        class: spaceship
  - toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        http:
        - method: "GET"
          path: "/v1/"
        - method: "POST"
          path: "/v1/request-landing$"
```
