### ISSUE TITLE
The Gateway-API cannot specify the gateway listener by sectionName.

### ISSUE THREAD

**Issue by chaunceyjiang** [cilium/cilium#31717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Gateway-API cannot specify the gateway listener by name.

While using the gateway-api, I found that I was able to normally access the `details` service whether using port `80` or port `8080`. 

However, according to the `httproute` configuration, I should only be able to access the `details` service through port `80`, because I specified the `sectionName`.

``` yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: two-listeners
spec:
  gatewayClassName: cilium
  listeners:
  - name: http-unattached
    port: 8080
    protocol: HTTP
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
        from: All
  - name: http-1
    port: 80
    protocol: HTTP
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-route-4
spec:
  parentRefs:
  - kind: Gateway
    name: two-listeners
    namespace: default
    sectionName: http-1
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: details
      port: 9080
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /details

```

---
```
╰─➤  kubectl get gateway
NAME                                                CLASS    ADDRESS        PROGRAMMED   AGE
two-listeners                                       cilium   172.18.0.133   True         5h29m


/home # curl 172.18.0.133:80/details/1
{"id":1,"author":"William Shakespeare","year":1595,"type":"paperback","pages":200,"publisher":"PublisherA","language":"English","ISBN-10":"1234567890","ISBN-13":"123-1234567890"}

/home # curl 172.18.0.133:8080/details/1
{"id":1,"author":"William Shakespeare","year":1595,"type":"paperback","pages":200,"publisher":"PublisherA","language":"English","ISBN-10":"1234567890","ISBN-13":"123-1234567890"}
```
### Cilium Version

v1.15.3

### Kernel Version

Linux localhost 5.15.0-79-generic #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

``` shell
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.7", GitCommit:"84e1fc493a47446df2e155e70fca768d2653a398", GitTreeState:"clean", BuildDate:"2023-07-19T12:23:27Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-15T00:36:28Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
