### ISSUE TITLE
fromEntity 'kube-apiserver' not working on AKS/GKE

### ISSUE THREAD

**Issue by Pionerd** [cilium/cilium#31711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When trying to set up NetworkPolicies for our clusters, we ran into an issue with ValidatingWebhooks. Here the Kubernetes API needs to be able to call the webhook, which we allowed as follows:

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default
spec:
  endpointSelector: {}
  ingress:
[...]
    - fromEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "10250"
[...]
  egress:
[...]
```

However, the web hook cannot be reached (ArgoCD output on sync):
```
one or more objects failed to apply, reason: error when patching "/dev/shm/3539688072": Internal error occurred: failed calling webhook "validate.externalsecret.external-secrets.io": failed to call webhook: Post "https://external-secrets-webhook.external-secrets.svc:443/validate-external-secrets-io-v1beta1-externalsecret?timeout=5s": context deadline exceeded
```

Hubble shows the Source Identity of the dropped traffic as `remote-node` on AKS and `konnectivity-agent` on GKE. Adding `remote-node` to the `fromEntities` (AKS) or fromEndpoints `konnectivity-agent`(GKE) list resolved the issue.

### Cilium Version

1.15.3

### Kernel Version

Linux aks-spot-26938668-vmss00000J 5.15.0-1054-azure #62-Ubuntu SMP Mon Jan 15 15:51:19 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

AKS v1.28.5

### Sysdump

[cilium-sysdump-20240401-174035.zip](https://github.com/cilium/cilium/files/14825711/cilium-sysdump-20240401-174035.zip)

### Anything else?

On EKS the same call is correctly identified as coming from `kube-apiserver`. 

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
