### ISSUE TITLE
Pods interacting with kube API server get timeout but only on one node at a time

### ISSUE THREAD

**Issue by gabbler97** [cilium/cilium#31791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Good Morning Everyone!
I have an EKS cluster and cilium is installed on it.
After the install I have noticed some weird behaviour.
My pods which are interacting with the kube API server started to crashloopbackoff, but only on one specific node at a time.
```bash
k get pod -A -o wide | grep "("
backup                  node-agent-dh6tm                                             0/1     CrashLoopBackOff   6 (43s ago)    10m     172.24.2.7      ip-10-x-x-162   <none>           <none>
monitoring              datadog-jwgx6                                                3/4     Running            5 (73s ago)    10m     172.24.2.83     ip-10-x-x-162   <none>           <none>
storage-ebs             ebs-csi-node-sfkx6                                           1/3     CrashLoopBackOff   8 (21s ago)    4m25s   172.24.2.163    ip-10-x-x-162   <none>           <none>
storage-fsx             fsx-openzfs-csi-node-2tkw7                                   1/3     CrashLoopBackOff   12 (71s ago)   9m25s   172.24.2.251    ip-10-x-x-162   <none>           <none>
```

After I drain this node another one starts failing.

```bash
k get pod -A -o wide | grep "("
backup                  node-agent-7ksqr                                             0/1     CrashLoopBackOff    6 (2m23s ago)    11m     172.24.4.169    ip-10-x-x-77    <none>           <none>
monitoring              datadog-nrj96                                                3/4     Running             6 (27s ago)      11m     172.24.4.91     ip-10-x-x-77    <none>           <none>
storage-ebs             ebs-csi-node-xsq29                                           1/3     CrashLoopBackOff    12 (94s ago)     12m     172.24.4.197    ip-10-x-x-77    <none>           <none>
storage-fsx             fsx-openzfs-csi-node-qxfcp                                   1/3     CrashLoopBackOff    12 (2m24s ago)   12m     172.24.4.188    ip-10-x-x-77    <none>           <none>
```

If I put those daemonsets and deployments to hostnetwork true the issue is gone, but due to a huge amount of portfonclicts it is not a maintainable solution for me.
I have already tried to add ciliumnetworkpolicies like

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-from-remote-node
  namespace: storage-ebs
specs:
- endpointSelector:
    matchLabels: {}
  ingress:
  - fromEntities:
    - world
  egress:
  - toEntities:
    - world
```

I have a kyverno deployment also

```bash
k get pod -n kyverno
NAME                                                       READY   STATUS      RESTARTS   AGE
kyverno-admission-controller-6fcb5967cd-mfxbx              1/1     Running     0          22h
kyverno-background-controller-5f976676bf-gc8c8             1/1     Running     0          47h
kyverno-cleanup-admission-reports-28538430-6q5rw           0/1     Completed   0          21m
kyverno-cleanup-admission-reports-28538440-qm5g9           0/1     Completed   0          11m
kyverno-cleanup-admission-reports-28538450-tscgz           1/1     Running     0          63s
kyverno-cleanup-cluster-admission-reports-28538430-l67j5   0/1     Completed   0          21m
kyverno-cleanup-cluster-admission-reports-28538440-bvm9b   0/1     Completed   0          11m
kyverno-cleanup-cluster-admission-reports-28538450-bpdmq   1/1     Running     0          63s
kyverno-cleanup-controller-69d595dc5c-ngl7c                1/1     Running     0          59m
kyverno-reports-controller-c4ff878bd-bkbcn                 1/1     Running     0          2d
```

When I scaled down the kyverno-admission-controller to one replicas (I thought the timeout happens because of too much API requests at one time) it helped for a few hours but the issue came back.

I get the following error messages in the pods

```bash
k logs ebs-csi-node-775zv -n storage-ebs
Defaulted container "ebs-plugin" out of: ebs-plugin, node-driver-registrar, liveness-probe
I0405 08:52:12.308665       1 driver.go:83] "Driver Information" Driver="ebs.csi.aws.com" Version="v1.28.0"
I0405 08:52:12.308784       1 node.go:93] "regionFromSession Node service" region="eu-central-1"
I0405 08:52:12.308809       1 metadata.go:85] "retrieving instance data from ec2 metadata"
I0405 08:52:24.870306       1 metadata.go:88] "ec2 metadata is not available"
I0405 08:52:24.870333       1 metadata.go:96] "retrieving instance data from kubernetes api"
I0405 08:52:24.871040       1 metadata.go:101] "kubernetes api is available"
panic: error getting Node ip-10-x-x-77.eu-central-1.compute.internal: Get "https://172.20.0.1:443/api/v1/nodes/ip-10-x-x-77": dial tcp 172.20.0.1:443: i/o timeout

goroutine 1 [running]:
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.newNodeService(0xc00041cfc0)
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/node.go:96 +0x3b1
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.NewDriver({0xc000477ec0, 0xd, 0x4?})
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/driver.go:106 +0x3e6
main.main()
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/cmd/main.go:64 +0x595
```

Here are the cilium values

```yaml
egressMasqueradeInterfaces: eth0
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cni-plugin
          operator: NotIn
          values:
          - aws
image:
  repository: "${repository}/${remote_path}/cilium"
operator:
  image:
    repository: "${repository}/${remote_path}/operator"
hubble:
  enabled: true #enabled by default
%{ if hubble_ui }
  relay:
    enabled: true
    image:
      repository: "${repository}/${remote_path}/hubble-relay"
  ui:
    enabled: true
    backend:
      image:
        repository: "${repository}/${remote_path}/hubble-ui-backend"
    frontend:
      image:
        repository: "${repository}/${remote_path}/hubble-ui"
%{ endif }
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
    - 172.25.0.0/14
```

Helm version is
1.15.1

Thank you very much for your help in advance!

### Cilium Version

Helm
1.15.1
Images
operator-generic:v1.15.1@sha256:819c7281f5a4f25ee1ce2ec4c76b6fbc69a660c68b7825e9580b1813833fa743
cilium:v1.15.1@sha256:351d6685dc6f6ffbcd5451043167cfa8842c6decf80d8c8e426a417c73fb56d4
hubble-relay:v1.15.1@sha256:3254aaf85064bc1567e8ce01ad634b6dd269e91858c83be99e47e685d4bb8012
hubble-ui:v0.13.0@sha256:7d663dc16538dd6e29061abd1047013a645e6e69c115e008bee9ea9fef9a6666
hubble-ui-backend:v0.13.0@sha256:1e7657d997c5a48253bb8dc91ecee75b63018d16ff5e5797e5af367336bc8803

### Kernel Version

Linux ip-10-x-x-214.x.y.z 5.10.205-195.807.amzn2.x86_64 #1 SMP Tue Jan 16 18:28:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.27.9-eks-5e0fdde

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
