### ISSUE TITLE
Gateway API: Can't  get a GRPCRoute working

### ISSUE THREAD

**Issue by Smana** [cilium/cilium#31811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi everyone,

I installed Cilium on EKS and I wanted to test the [GRPCRoute](https://gateway-api.sigs.k8s.io/guides/grpc-routing/) of the Gateway API but I get an error:

```console
grpcurl -plaintext -proto ./demo.proto boutique-product.cloud.ogenki.io:443 hipstershop.ProductCatalogService/ListProducts                                                                  
ERROR:                                                                                                                                                                                        
  Code: Unimplemented                                                                                                                                                                         
  Message:  
```

I installed the experimental CRDs with GAPI enabled (everything else is working like a charm: HTTPRoute, Gateways...). I reproduced the environment of the Lab on advanced GAPI use cases with the [Google's microservices demo](https://github.com/GoogleCloudPlatform/microservices-demo) stack.

When I look at `Supported features` of the Gatewayclass, GRPC doesn't appear:
```yaml
kubectl get gatewayclasses -o yaml cilium
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
...
  supportedFeatures:
  - Gateway
  - HTTPRoute
  - HTTPRouteDestinationPortMatching
  - HTTPRouteHostRewrite
  - HTTPRouteMethodMatching
  - HTTPRoutePathRedirect
  - HTTPRoutePathRewrite
  - HTTPRoutePortRedirect
  - HTTPRouteQueryParamMatching
  - HTTPRouteRequestMirror
  - HTTPRouteRequestMultipleMirrors
  - HTTPRouteResponseHeaderModification
  - HTTPRouteSchemeRedirect
  - ReferenceGrant
  - TLSRoute
```

Here are the manifests that are being declared in [my repo](https://github.com/Smana/demo-cloud-native-ref/tree/demo_gapi/apps/base/onlineboutique)
```yaml
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: onlineboutique
  namespace: onlineboutique
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: boutique.${domain_name},boutique-product.${domain_name}
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  listeners:
    - name: https
      hostname: "boutique.${domain_name}"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - name: onlineboutique-tls
    - name: grpc
      hostname: "boutique-product.${domain_name}"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - name: onlineboutique-product-tls
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: productcatalogservice
  namespace: onlineboutique
spec:
  parentRefs:
    - namespace: onlineboutique
      name: onlineboutique
      sectionName: grpc
  hostnames:
    - "boutique-product.${domain_name}"
  rules:
    - matches:
        - method:
            service: hipstershop.ProductCatalogService
            method: ListProducts
      backendRefs:
        - name: productcatalogservice
          port: 3550
```

Note: using port-forward the command works

### Cilium Version

```console
cilium version
Client: 1.15.3 22dfbc58 2024-03-26T11:45:10+01:00 go version go1.21.8 linux/amd64
Daemon: 1.15.3 22dfbc58 2024-03-26T11:45:10+01:00 go version go1.21.8 linux/amd64
```

### Kernel Version

Amazon EKS Bottlerocket v1.29.1-eks-61c0bbb

### Kubernetes Version

`v1.29.1-eks-b9c9ed7`

### Sysdump

[cilium-sysdump-20240409-093535.zip](https://github.com/cilium/cilium/files/14915071/cilium-sysdump-20240409-093535.zip)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
Thanks for your issue. I have done a quick test with below manifest (no https), but unable to simulate.

Can you share the sysdump for further investigation? Thanks.

```shell
$ grpcurl -plaintext -proto ./demo.proto -authority=my-grpc-service.foo.com $lb:80 hipstershop.ProductCatalogService/ListProducts 
{
  "products": [
    {
      "id": "OLJCESPC7Z",
      "name": "Sunglasses",
      "description": "Add a modern touch to your outfits with these sleek aviator sunglasses.",
      "picture": "/static/img/products/sunglasses.jpg",
      "priceUsd": {
        "currencyCode": "USD",
        "units": "19",
        "nanos": 990000000
      },
      "categories": [
        "accessories"
      ]
    },
...
```

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: grpc
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    name: web-gw
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: products
spec:
  parentRefs:
    - namespace: default
      name: grpc
  hostnames:
    - my-grpc-service.foo.com
  rules:
    - matches:
        - method:
            service: hipstershop.ProductCatalogService
            method: ListProducts
      backendRefs:
        - name: productcatalogservice
          port: 3550
          
````
