### ISSUE TITLE
BGP: IPv6 peering not working (IPv4 works)

### ISSUE THREAD

**Issue by andsens** [cilium/cilium#31911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This is probably not a bug, and more likely a misconfiguration. I'm pretty green wrt BGP and this level of networking. I am writing here in the hopes that someone might be able to help.

I am trying to get IPv6 BGP peering set up via my Unifi USG. Ideally I would like to simply use a subnet from my ISP prefix so no translation has to take place, but I tried to simplify in order to rule out any confounding factors. That being said, the k8s node is still running inside a KVM (bridged with no guest filter), I am unable to run it on a bare-bones machine.

IPv4 BGP peering works just fine, but I am unable to route to any IPv6 address from any of the machines on my network.

I am using the following `BGPPeeringPolicy`:
```
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: router
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: k8s-nas.local
  virtualRouters:
  - exportPodCIDR: true
    localASN: 64600
    neighbors:
    - connectRetryTimeSeconds: 120
      eBGPMultihopTTL: 1
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      peerASN: 64700
      peerAddress: 10.192.205.1/32
      peerPort: 179
    serviceSelector:
      matchExpressions:
      - key: somekey
        operator: NotIn
        values:
        - never-used-value
```

and this `config.gateway.json`:
```
{
  "protocols": {
    "bgp": {
      "64700": {
        "neighbor": {
          "10.192.205.141": {
            "address-family": {
              "ipv6-unicast": "''"
            },
            "remote-as": "64600",
            "soft-reconfiguration": {
              "inbound": "''"
            }
          }
        }
      }
    }
  }
}
```

```
$ cilium bgp routes available ipv4 unicast`
Node            VRouter   Prefix         NextHop   Age       Attrs
k8s-nas.local   64600     10.32.0.0/24   0.0.0.0   1h0m45s   [{Origin: i} {Nexthop: 0.0.0.0}]
                64600     10.34.0.1/32   0.0.0.0   58m23s    [{Origin: i} {Nexthop: 0.0.0.0}]
                64600     10.34.0.2/32   0.0.0.0   57m48s    [{Origin: i} {Nexthop: 0.0.0.0}]
$ cilium bgp routes available ipv6 unicast
Node            VRouter   Prefix                     NextHop   Age       Attrs
k8s-nas.local   64600     fd24:28b4:307f:42::/112    ::        1h1m13s   [{Origin: i} {MpReach(ipv6-unicast): {Nexthop: ::, NLRIs: [fd24:28b4:307f:42::/112]}}]
                64600     fd24:28b4:307f:44::1/128   ::        58m51s    [{Origin: i} {MpReach(ipv6-unicast): {Nexthop: ::, NLRIs: [fd24:28b4:307f:44::1/128]}}]
                64600     fd24:28b4:307f:44::2/128   ::        58m16s    [{Origin: i} {MpReach(ipv6-unicast): {Nexthop: ::, NLRIs: [fd24:28b4:307f:44::2/128]}}]
```

On the USG:
```
$ show ip bgp
BGP table version is 0, local router ID is 10.192.205.1
Status codes: s suppressed, d damped, h history, * valid, > best, i - internal,
              r RIB-failure, S Stale, R Removed
Origin codes: i - IGP, e - EGP, ? - incomplete

   Network          Next Hop            Metric LocPrf Weight Path
*> 10.32.0.0/24     10.192.205.141                         0 64600 i
*> 10.34.0.1/32     10.192.205.141                         0 64600 i
*> 10.34.0.2/32     10.192.205.141                         0 64600 i

Total number of prefixes 3

$ show ipv6 bgp
BGP table version is 0, local router ID is 10.192.205.1
Status codes: s suppressed, d damped, h history, * valid, > best, i - internal,
              r RIB-failure, S Stale, R Removed
Origin codes: i - IGP, e - EGP, ? - incomplete

   Network          Next Hop            Metric LocPrf Weight Path
*  fd24:28b4:307f:42::/112
                    ::ffff:10.192.205.141
                                                           0 64600 i
*  fd24:28b4:307f:44::1/128
                    ::ffff:10.192.205.141
                                                           0 64600 i
*  fd24:28b4:307f:44::2/128
                    ::ffff:10.192.205.141
                                                           0 64600 i

Total number of prefixes 3
```

Like I said, I am fairly new to this, but that `Next Hop` in the USG IPv6 table doesn't look right.

I have read and tried #30773 to no avail (though that did help with actually getting the IPv6 table populated). I have over the last 2 weeks also fully read through [the docs regarding the BGP control plane](https://docs.cilium.io/en/stable/network/bgp-control-plane/) (probably about 5-10 times by now), but I just can't figure it out. Please help?

### Cilium Version

cilium-cli: v0.16.4 compiled with go1.22.1 on linux/amd64
cilium image (default): v1.15.3
cilium image (stable): v1.15.3
cilium image (running): 1.15.1

### Kernel Version

Linux k8s-nas.local 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

### Kubernetes Version

v1.28.8+k3s1 

### Sysdump

[cilium-sysdump-20240411-233231.zip](https://github.com/cilium/cilium/files/14951552/cilium-sysdump-20240411-233231.zip)

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
