### ISSUE TITLE
advertisedPathAttributes in CiliumBGPPeeringPolicy doesn't seem to apply to address from cidr defined in CiliumLoadBalancerIPPool>spec>bloks

### ISSUE THREAD

**Issue by hujun-open** [cilium/cilium#31947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I tried to use advertisedPathAttributes  to set localPreference of advertised LB IP route, however it seems it doesn't work for LB IP from cidr defined in CiliumLoadBalancerIPPool>spec>bloks; it works for cidr defined in CiliumLoadBalancerIPPool>spec>cirds, however CiliumLoadBalancerIPPool>spec>cirds is deprecated according to [the api doc](https://pkg.go.dev/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1#CiliumLoadBalancerIPPoolSpec)

following is my CiliumBGPPeeringPolicy, same policy works for `cirds`, but not for `blocks`
```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: 01-bgp-peering-policy
spec: # CiliumBGPPeeringPolicySpec
 nodeSelector:
   matchLabels:
     needbgp: "true"
 virtualRouters: # []CiliumBGPVirtualRouter
 - localASN: 100
   exportPodCIDR: true
   serviceSelector:
     matchExpressions:
       - {key: app, operator: In, values: ['nginx']}
   neighbors: # []CiliumBGPNeighbor
    - peerAddress: '192.168.250.99/32'
      peerASN: 100
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      advertisedPathAttributes:
      - selectorType: CiliumLoadBalancerIPPool
        selector:
          matchLabels:
            environment: production
        localPreference: 134
        communities
```

pool using `cidrs`, 
```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "blue-pool"
  labels:
    environment: production
spec:
  cidrs:
  - cidr: "10.99.10.0/24"
```
this is working:
```
root@vpc-master:~/cilium# cilium bgp routes advertised
(Defaulting to `ipv4 unicast` AFI & SAFI, please see help for more options)

Node           VRouter   Peer             Prefix          NextHop         Age      Attrs
vpc-master     100       192.168.250.99   10.0.1.0/24     192.168.250.1   19m50s   [{Origin: i} {AsPath: } {Nexthop: 192.168.250.1} {LocalPref: 100}]
               100       192.168.250.99   10.99.10.1/32   192.168.250.1   19m50s   [{Origin: i} {AsPath: } {Nexthop: 192.168.250.1} {LocalPref: 134} {Communities: 65001:100}]
vpc-worker-1   100       192.168.250.99   10.0.0.0/24     192.168.250.2   20m22s   [{Origin: i} {AsPath: } {Nexthop: 192.168.250.2} {LocalPref: 100}]
               100       192.168.250.99   10.99.10.1/32   192.168.250.2   20m22s   [{Origin: i} {AsPath: } {Nexthop: 192.168.250.2} {LocalPref: 134} {Communities: 65001:100}]

```

same pool using `blocks`, not working
```
root@vpc-master:~/cilium# cat svcpool.yaml
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "blue-pool"
  labels:
    environment: production
spec:
  blocks:
  - cidr: "10.99.10.0/24"

root@vpc-master:~/cilium# kubectl apply -f svcpool.yaml
ciliumloadbalancerippool.cilium.io/blue-pool configured
root@vpc-master:~/cilium# cilium bgp routes advertised
(Defaulting to `ipv4 unicast` AFI & SAFI, please see help for more options)

Node           VRouter   Peer             Prefix          NextHop         Age      Attrs
vpc-master     100       192.168.250.99   10.0.1.0/24     192.168.250.1   21m9s    [{Origin: i} {AsPath: } {Nexthop: 192.168.250.1} {LocalPref: 100}]
               100       192.168.250.99   10.99.10.1/32   192.168.250.1   21m9s    [{Origin: i} {AsPath: } {Nexthop: 192.168.250.1} {LocalPref: 100}]
vpc-worker-1   100       192.168.250.99   10.0.0.0/24     192.168.250.2   21m41s   [{Origin: i} {AsPath: } {Nexthop: 192.168.250.2} {LocalPref: 100}]
               100       192.168.250.99   10.99.10.1/32   192.168.250.2   21m41s   [{Origin: i} {AsPath: } {Nexthop: 192.168.250.2} {LocalPref: 100}]
```

### Cilium Version

v1.15.3

### Kernel Version

 6.1.0-18-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

### Kubernetes Version

v1.29.3

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
