### ISSUE TITLE
L7 Envoy service mesh - Cannot reach the service with multiple ports

### ISSUE THREAD

**Issue by khacminh** [cilium/cilium#31941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. Having a deployment **echo-server** serving echo on both REST and gRPC: REST port is 3000 and gRPC is port is 4000
2. Create a service with annotation: `service.cilium.io/lb-l7: enabled`

    ```yaml
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        name: echo-server
      annotations:
        service.cilium.io/lb-l7: enabled
      name: echo-server
      namespace: default
    spec:
      ports:
        - name: grpc
          port: 4000
          protocol: TCP
          targetPort: 4000
        - name: http
          port: 3000
          protocol: TCP
          targetPort: 3000
      selector:
        name: echo-server
    ```

Only the gRPC request can reach the service. The REST request return with error code 502.

### Cilium Version

1.15.3

### Kernel Version

5.10.198-187.748.amzn2.x86_64

### Kubernetes Version

EKS v1.29

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
