### ISSUE TITLE
cilium-operator creates LoadBalancer for other gateway class

### ISSUE THREAD

**Issue by networkhermit** [cilium/cilium#31978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium-operator creates LoadBalancer for other gateway class, this is unexpected. Might be related with #31591.

Steps to reproduce:

0. Enable cilium gatewayAPI support
```yaml
gatewayAPI:
  enabled: true
```

1. List gatewayclass in cluster.
```console
❯ kubectl get gatewayclass
NAME           CONTROLLER                                      ACCEPTED   AGE
cilium         io.cilium/gateway-controller                    True       6d21h
eg             gateway.envoyproxy.io/gatewayclass-controller   True       4d12h
istio          istio.io/gateway-controller                     True       268d
istio-remote   istio.io/unmanaged-gateway                      True       216d
```

2. Create some demo gateways of different gateway class

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-test
  namespace: default
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      port: 80
      protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg-test
  namespace: default
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      port: 80
      protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: istio-test
  namespace: default
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
```

```console
❯ kubectl apply -f test.yaml
gateway.gateway.networking.k8s.io/cilium-test created
gateway.gateway.networking.k8s.io/eg-test created
gateway.gateway.networking.k8s.io/istio-test created
```

3. Check created k8s services

```console
❯ kubectl -n default get svc
NAME                         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                        AGE
cilium-gateway-cilium-test   LoadBalancer   10.43.149.121   <pending>     80:31609/TCP                   3s
istio-test-istio             LoadBalancer   10.43.61.207    <pending>     15021:32485/TCP,80:32646/TCP   3s
kubernetes                   ClusterIP      10.43.0.1       <none>        443/TCP                        305d
```

4. Redeploy cilium-operator and check created k8s services again

```console
❯ kubectl rollout -n kube-system restart deployment cilium-operator
deployment.apps/cilium-operator restarted
```

```console
❯ kubectl -n default get svc
NAME                         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                        AGE
cilium-gateway-cilium-test   LoadBalancer   10.43.149.121   <pending>     80:31609/TCP                   15s
cilium-gateway-eg-test       LoadBalancer   10.43.82.79     <pending>     80:32546/TCP                   1s
cilium-gateway-istio-test    LoadBalancer   10.43.227.147   <pending>     80:30709/TCP                   1s
istio-test-istio             LoadBalancer   10.43.61.207    <pending>     15021:32485/TCP,80:32646/TCP   15s
kubernetes                   ClusterIP      10.43.0.1       <none>        443/TCP                        305d
```

We can see cilium-operator creates LoadBalancer for eg-test  and istio-test.

5. Aditional CiliumEnvoyConfigs are also unexpected created

```console
❯ kubectl -n default get cec
NAME                         AGE
cilium-gateway-cilium-test   3m51s
cilium-gateway-eg-test       3m37s
cilium-gateway-istio-test    3m37s
```

### Cilium Version

1.15.3

### Kernel Version

6.6.9

### Kubernetes Version

1.29.3

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
