### ISSUE TITLE
CFP: Support drop_reason_desc in flow filter

### ISSUE THREAD

**Issue by sathieu** [cilium/cilium#32051]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

We are using [hubble exporter](https://docs.cilium.io/en/latest/observability/hubble-exporter/) and want to exclude events with `drop_reason_desc` `UNSUPPORTED_L3_PROTOCOL`.

We tried:

```yaml
hubble:
  export:
  # ...
      dynamic:
        enabled: true
        config:
         # ...
          content:
          - name: principal
            # ...
            excludeFilters: 
            - drop_reason_desc:
              - UNSUPPORTED_L3_PROTOCOL
            - drop_reason:
              - "139" # UNSUPPORTED_L3_PROTOCOL
            - event_type:
              - type: 1
                match_sub_type: true
                sub_type: 139
```

Only third (event_type) way works, but this is not user-friendly. The two others fail to load.

**Describe the feature you'd like**

`drop_reason_desc` to be supported as filter type.

See: https://github.com/cilium/cilium/blob/aef6814f7e895d644234c679a956ef86c832a1b8/api/v1/flow/flow.pb.go#L2892-L2980
