### ISSUE TITLE
Clustermesh connect not working with ArgoCD

### ISSUE THREAD

**Issue by mayur2281** [cilium/cilium#32076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I deployed Cilium and Clustermesh API server using helm charts on ArgoCD. The issue is that i am unable to connect both these clusters as the cilium command is not able to find the helm release from my context. As we kow Apps deployed via ArgoCD do not have helm releases stored in kube configs. This is not a bug but a limitation. Pls help me in overcoming this limitation. 

### Cilium Version

v1.15.4

### Kernel Version

Darwin MacBook-Air.local 23.2.0 Darwin Kernel Version 23.2.0:

### Kubernetes Version

v1.28.5

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by giorio94** [comment]
Hi @mayur2281,

You can directly configure the [helm values `clustermesh.config`](https://github.com/cilium/cilium/blob/1d0750b01f2d5f5fa18a556fa11f24822181169d/install/kubernetes/cilium/values.yaml#L2838-L2865) settings to connect to the remote cluster, once you retrieved the relevant parameters, and in particular the IP/address associated with the remote clustermesh-apiserver LB service.

**Comment by mayur2281** [comment]
Thanks for the answer @giorio94. One more question: Can I add the context name in clustermesh.config.clusters if that context is present in ArgoCD?

**Comment by giorio94** [comment]
That should be the name that you configured in `cluster.name` for the given remote cluster.

**Comment by mayur2281** [comment]
Ah Got it. Thanks again

**Comment by mayur2281** [comment]
% cilium clustermesh status   
✅ Service "clustermesh-apiserver" of type "LoadBalancer" found
✅ Cluster access information is available:
  - 192.168.20.5:2379
✅ Deployment clustermesh-apiserver is ready
⚠️  1/1 nodes are not connected to all clusters [min:0 / avg:0.0 / max:0]
🔌 Cluster Connections:
  - primary-cluster: 1/1 configured, 0/1 connected
🔀 Global services: [ min:0 / avg:0.0 / max:0 ]
❌ 1 Errors:
  ❌ cilium-clb9j is not connected to cluster secondary-cluster: Waiting for initial connection to be established
  
  
I am able to add the config but unable to establish a connection!

This is my helm values: 
```yaml
aksbyocni:
  enabled: true
nodeinit:
  enabled: true
cluster: 
  name: primary-cluster
  id: 1
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: ["10.10.0.0/16"]
clustermesh:
  config:
    enabled: true
    clusters:
    - name: secondary-cluster
      ips:
      - 192.168.20.5
  useAPIServer: true
  apiserver:
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
operator:
  replicas: 1
```

**Comment by mayur2281** [comment]
remote-etcd-secondary-cluster   never          6m13s ago    1       timed out while waiting for etcd session. Ensure that etcd is running on [https://secondary-cluster.mesh.cilium.io:2379]
clustermesh.domain value is mesh.cilium.io, and i think the cilium agent isnt able to resolve this within the cluster.

**Comment by giorio94** [comment]
> clustermesh.domain value is mesh.cilium.io, and i think the cilium agent isnt able to resolve this within the cluster.

That is handled through host aliases configured on Cilium agents, so it is unlikely the problem.

Most likely, either `192.168.20.5` is unreachable from the Cilium agents, or the two clusters are using different CAs.

**Comment by mayur2281** [comment]
Ok, I get the problem. In which cluster do i setup the config? in the source or the destination cluster or both?

**Comment by giorio94** [comment]
Do you mean the clustermesh config? You need to configure that in both clusters, pointing to the other (you can also keep the config for the self cluster, that's automatically ignored).

**Comment by mayur2281** [comment]
When i do the clustermesh connect using the cli option this is the helm diff:

kube-system, cilium-clustermesh, Secret (v1) has been added:
```
+ # Source: cilium/templates/clustermesh-config/clustermesh-secret.yaml
+ apiVersion: v1
+ kind: Secret
+ metadata:
+   name: cilium-clustermesh
+   namespace: kube-system
+ data:
+   secondary-aks-cluster: '++++++++ # (321 bytes)'
+   secondary-aks-cluster.etcd-client-ca.crt: '++++++++ # (1127 bytes)'
+   secondary-aks-cluster.etcd-client.crt: '++++++++ # (924 bytes)'
+   secondary-aks-cluster.etcd-client.key: '++++++++ # (227 bytes)'
```
But in argocd this is the data part in the secret:
```
apiVersion: v1
data:
  secondary-aks-cluster: ++++++++
kind: Secret
  name: cilium-clustermesh
  namespace: kube-system
```
