### ISSUE TITLE
No healthy upstream for kube-prometheus-stack-grafana exposed through gateway

### ISSUE THREAD

**Issue by maagy** [cilium/cilium#32089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I use gateway API for service exposures. Usually cilium works well and services are accessible. There is however one exception - grafana. Web page reports 503 Service Unavailable with "no healthy upstream" content. 

I've tried to change the httproute backendRefs to kube-prometheus-stack-prometheus service and it worked. So I think it's configured correctly. Output of httproute description looks OK:

```
Name:         grafana
Namespace:    monitoring
Labels:       <none>
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1
Kind:         HTTPRoute
Metadata:
  Creation Timestamp:  2024-04-19T11:54:16Z
  Generation:          3
  Resource Version:    11625006
  UID:                 b4ba095c-3703-427c-9436-a2682fe521bc
Spec:
  Hostnames:
    omitted
  Parent Refs:
    Group:      gateway.networking.k8s.io
    Kind:       Gateway
    Name:       default-gateway
    Namespace:  default
  Rules:
    Backend Refs:
      Group:   
      Kind:    Service
      Name:    kube-prometheus-stack-grafana
      Port:    3000
      Weight:  1
    Matches:
      Path:
        Type:   PathPrefix
        Value:  /
Status:
  Parents:
    Conditions:
      Last Transition Time:  2024-04-19T12:05:07Z
      Message:               Accepted HTTPRoute
      Observed Generation:   3
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2024-04-19T12:05:07Z
      Message:               Service reference is valid
      Observed Generation:   3
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Controller Name:         io.cilium/gateway-controller
    Parent Ref:
      Group:      gateway.networking.k8s.io
      Kind:       Gateway
      Name:       default-gateway
      Namespace:  default
Events:           <none>
```

Could some headers or absence of headers break routing?

### Cilium Version

cilium-cli: v0.15.23 compiled with go1.22.0 on linux/amd64
cilium image (default): v1.15.0
cilium image (stable): v1.15.3
cilium image (running): 1.15.3

### Kernel Version

Linux d01 5.15.0-101-generic #111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.12+rke2r1", GitCommit:"12031002905c0410706974560cbdf2dad9278919", GitTreeState:"clean", BuildDate:"2024-03-15T20:45:44Z", GoVersion:"go1.21.8 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

### Regression

No other version of cilium tested.

### Sysdump

Sorry, I'm not willing to provide sysdump.

### Anything else?

Environment: self-hosted RKE2 kubernetes, kube-proxy replaced

Cilium installed with helm:
```
API_SERVER_IP=127.0.0.1
API_SERVER_PORT=6443
helm upgrade --install cilium cilium/cilium --version 1.15.3 --namespace kube-system --set kubeProxyReplacement=true --set k8sServiceHost=${API_SERVER_IP} --set k8sServicePort=${API_SERVER_PORT} --set hubble.relay.enabled=true --set hubble.ui.enabled=true --set operator.replicas=1 --set gatewayAPI.enabled=true --set l7-proxy.enabled=true --set socketLB.hostNamespaceOnly=true --set ingressController.loadbalancerMode=shared
```

Gateway:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-gateway
  namespace: default
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
spec:
  gatewayClassName: cilium
  listeners:
...
    - hostname: "..."
      name: https...
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ''
            kind: Secret
            name: grafana...
        mode: Terminate
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              shared-gateway-access: "true"
    - hostname: "..."
      name: http...
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              shared-gateway-access: "true"
...
```

Httproute:
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  parentRefs:
  - name: default-gateway
    namespace: default
  hostnames:
  - "..."
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: kube-prometheus-stack-grafana
      port: 3000
```

"monitoring" namespace has label shared-gateway-access set to "true".

Whole kube-prometheus-stack could be installed with helm like this:
```helm upgrade --install --create-namespace -n monitoring kube-prometheus-stack prometheus-community/kube-prometheus-stack -f values.yaml```

Note that I modified just persistence and some scrappings.

Grafana versions tested: 10.4.1, 11.0.0-preview.

Tested CRDs for gateway API from stable version, now I'm using the experimental version because I need to be able to set timeouts for httproutes (because of gradio queues). Both have same behavior.

Cilium status:
```
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    disabled (using embedded mode)
 \__/¯¯\__/    Hubble Relay:       OK
    \__/       ClusterMesh:        disabled

DaemonSet              cilium             Desired: 1, Ready: 1/1, Available: 1/1
Deployment             hubble-relay       Desired: 1, Ready: 1/1, Available: 1/1
Deployment             hubble-ui          Desired: 1, Ready: 1/1, Available: 1/1
Deployment             cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Containers:            cilium-operator    Running: 1
                       cilium             Running: 1
                       hubble-relay       Running: 1
                       hubble-ui          Running: 1
Cluster Pods:          97/97 managed by Cilium
Helm chart version:    1.15.3
Image versions         cilium-operator    quay.io/cilium/operator-generic:v1.15.3@sha256:c97f23161906b82f5c81a2d825b0646a5aa1dfb4adf1d49cbb87815079e69d61: 1
                       cilium             quay.io/cilium/cilium:v1.15.3@sha256:da74ab61d1bc665c1c088dff41d5be388d252ca5800f30c7d88844e6b5e440b0: 1
                       hubble-relay       quay.io/cilium/hubble-relay:v1.15.3@sha256:b9c6431aa4f22242a5d0d750c621d9d04bdc25549e4fb1116bfec98dd87958a2: 1
                       hubble-ui          quay.io/cilium/hubble-ui:v0.13.0@sha256:7d663dc16538dd6e29061abd1047013a645e6e69c115e008bee9ea9fef9a6666: 1
                       hubble-ui          quay.io/cilium/hubble-ui-backend:v0.13.0@sha256:1e7657d997c5a48253bb8dc91ecee75b63018d16ff5e5797e5af367336bc8803: 1
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
