### ISSUE TITLE
Gateway: Combining listeners with HTTPS and TLS protocol

### ISSUE THREAD

**Issue by vehagn** [cilium/cilium#32292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm trying to create a Gateway that combines both HTTPS and TLS listeners to proxy external services, but I'm met with 

```
Skipped a listener block: [spec.listeners[1].tls.certificateRef: Required value: listener has no certificateRefs, spec.listeners[1].tls.mode: Unsupported value: "Passthrough": supported values: "Terminate"]
```

from the Gateway resource when trying to add a TLS listener. From what I gather from the [Gateway API documentation](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.Gateway) I should be able to combine these two listener types.

The Gateway I'm trying to create is 

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: gateway
  annotations:
    cert-manager.io/issuer: cloudflare-issuer
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.1.221
  listeners:
    - name: https-gateway
      protocol: HTTPS
      port: 443
      hostname: "*.<DOMAIN>"
      tls:
        certificateRefs:
          - kind: Secret
            name: cert-stonegarden
      allowedRoutes:
        namespaces:
          from: All
    - name: proxmox-tls-passthrough
      protocol: TLS
      port: 443
      hostname: "proxmox.<DOMAIN>"
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All
```

with the following Routes

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  parentRefs:
    - name: gateway
      namespace: gateway
  hostnames:
    - "home-assistant.<DOMAIN>"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: home-assistant
          port: 80
```

```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: proxmox
  namespace: proxmox
spec:
  parentRefs:
    - name: gateway
      namespace: gateway
  hostnames:
    - "proxmox.<DOMAIN>"
  rules:
    - backendRefs:
        - name: proxmox
          port: 443
```

each having their own `Service` and `EndpointSlice` resources.

As a workaround I'm able to create two separate Gateways, one with each listener. This works, but I then have two different Gateways and consequently two IPs to maintain.

### Cilium Version

1.51.1

### Kernel Version

6.1.0-20-amd64

### Kubernetes Version

v1.29.3

### Anything else?

I encountered this issue trying to proxy both Home Assistant OS and Proxmox as external services through a Gateway.
If it's any help I've described it further in a blog post [here](https://blog.stonegarden.dev/articles/2024/04/k8s-external-services/).

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
HI @vehagn, can you give some more info about where you got that initial error from? I had a look at this and couldn't reproduce it with Cilium 1.15.1 and either Kubernetes 1.24 or 1.29. I created a similar Gateway and it was accepted by Cilium okay:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: default
spec:
  gatewayClassName: cilium
  listeners:
    - name: https-gateway
      protocol: HTTPS
      port: 443
      hostname: "*.test"
      tls:
        certificateRefs:
          - kind: Secret
            name: selfsigned
      allowedRoutes:
        namespaces:
          from: All
    - name: proxmox-tls-passthrough
      protocol: TLS
      port: 443
      hostname: "proxmox.test"
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All
```

**Comment by vehagn** [comment]
Thank you for looking into this @youngnick!

Seeing that you couldn't reproduce the error made me investigate further. 
I now think the issue lies with Cert-manager and not Cilium.

I tried to create the same `Gateway` as you did and did not experience any issues before I added 

```
  annotations:
    cert-manager.io/issuer: cloudflare-issuer
```

> can you give some more info about where you got that initial error from?

I got the error from the events for the Gateway. I initially only looked at them in the Argo CD Web GUI, but looking again now using `kubectl describe` I see that the source is `cert-manager-gateway-shim`.

I'll report the issue over at the Cert-manager repo and think this issue can be closed.

**Comment by vehagn** [comment]
I did some further digging and it appears that I'm able to connect a `TLSRoute` to a `Gateway` which only supports `HTTPRoute` kinds. I would expect this to throw some kind of error.

The involved resources are

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: test
  namespace: gateway
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTPS
      port: 443
      name: https-gateway
      hostname: "*.example.com"
      tls:
        certificateRefs:
          - kind: Secret
            name: test-cert
      allowedRoutes:
        namespaces:
          from: All
```

(Notice I've removed the TLS-listener)

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: test
  namespace: test
spec:
  parentRefs:
    - name: test
      namespace: gateway
  hostnames:
    - "test.example.com"
  rules:
    - backendRefs:
        - name: test-svc
          port: 443
```

Looking at the status of both they appear to have successfully linked

`❯ kubectl -n test get tlsroute test -oyaml | yq '.status'`

```yaml
parents:
  - conditions:
      - lastTransitionTime: "2024-05-04T08:35:56Z"
        message: Accepted TLSRoute
        observedGeneration: 1
        reason: Accepted
        status: "True"
        type: Accepted
      - lastTransitionTime: "2024-05-04T08:35:56Z"
        message: Service reference is valid
        observedGeneration: 1
        reason: ResolvedRefs
        status: "True"
        type: ResolvedRefs
    controllerName: io.cilium/gateway-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: test
      namespace: gateway
```

`❯ kubectl -n gateway get gateway test -oyaml | yq '.status'`

```yaml
addresses:
  - type: IPAddress
    value: 192.168.1.224
conditions:
  - lastTransitionTime: "2024-05-04T08:35:43Z"
    message: Gateway successfully scheduled
    observedGeneration: 1
    reason: Accepted
    status: "True"
    type: Accepted
  - lastTransitionTime: "2024-05-04T08:35:43Z"
    message: Gateway successfully reconciled
    observedGeneration: 1
    reason: Programmed
    status: "True"
    type: Programmed
listeners:
  - attachedRoutes: 1
    conditions:
      - lastTransitionTime: "2024-05-04T08:35:56Z"
        message: Invalid CertificateRef
        reason: Invalid
        status: "False"
        type: Programmed
      - lastTransitionTime: "2024-05-04T08:35:56Z"
        message: Listener Accepted
        observedGeneration: 1
        reason: Accepted
        status: "True"
        type: Accepted
      - lastTransitionTime: "2024-05-04T08:35:56Z"
        message: Invalid CertificateRef
        reason: InvalidCertificateRef
        status: "False"
        type: ResolvedRefs
    name: https-gateway
    supportedKinds:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
```

Ignoring the `Invalid CertificateRef` messages the `TLSRoute` appears to have been successfully accepted by the Gateway.

Is this the intended behaviour, or should I open a new issue?
