### ISSUE TITLE
Missing L4 wildcard if L4 is ommited

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3231]
The following rule:
```
endpointSelector:
    matchLabels:
        - {}
ingress:
    fromEndpoints:
        matchLabels:
          - {}
```

Should also wildcard all L4 but it currently doesn't.
