### ISSUE TITLE
Gateway API: TLSRoutes erroneously attaching to HTTPS-listeners

### ISSUE THREAD

**Issue by vehagn** [cilium/cilium#32371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Following up on #32292 with @youngnick.

Creating the following `Gateway` resource with a HTTPS-listener

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: test
  namespace: test
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTPS
      port: 443
      name: https-gateway
      hostname: "*.example.com"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: test-cert
```

and a `TLSRoute`

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: test
  namespace: test
spec:
  parentRefs:
    - name: test
      namespace: gateway
  hostnames:
    - "test.example.com"
  rules:
    - backendRefs:
        - name: test-svc
          port: 443
```

we see that the `TLSRoute` is successfully attached to the `Gateway` by looking at the status of both resources

`kubectl -n test get tlsroute test -oyaml | yq '.status'`

```yaml
parents:
  - conditions:
      - lastTransitionTime: "2024-05-04T08:35:56Z"
        message: Accepted TLSRoute
        observedGeneration: 1
        reason: Accepted
        status: "True"
        type: Accepted
      - lastTransitionTime: "2024-05-04T08:35:56Z"
        message: Service reference is valid
        observedGeneration: 1
        reason: ResolvedRefs
        status: "True"
        type: ResolvedRefs
    controllerName: io.cilium/gateway-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: test
      namespace: gateway
```

`kubectl -n test get gateway test -oyaml | yq '.status'`

```yaml
addresses:
  - type: IPAddress
    value: 192.168.1.224
conditions:
  - lastTransitionTime: "2024-05-04T08:35:43Z"
    message: Gateway successfully scheduled
    observedGeneration: 1
    reason: Accepted
    status: "True"
    type: Accepted
  - lastTransitionTime: "2024-05-04T08:35:43Z"
    message: Gateway successfully reconciled
    observedGeneration: 1
    reason: Programmed
    status: "True"
    type: Programmed
listeners:
  - attachedRoutes: 1
    conditions:
      - lastTransitionTime: "2024-05-04T08:35:56Z"
        message: Invalid CertificateRef
        reason: Invalid
        status: "False"
        type: Programmed
      - lastTransitionTime: "2024-05-04T08:35:56Z"
        message: Listener Accepted
        observedGeneration: 1
        reason: Accepted
        status: "True"
        type: Accepted
      - lastTransitionTime: "2024-05-04T08:35:56Z"
        message: Invalid CertificateRef
        reason: InvalidCertificateRef
        status: "False"
        type: ResolvedRefs
    name: https-gateway
    supportedKinds:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
```

According to the Gateway API spec this shouldn't be allowed.

As @youngnick [mentions](https://github.com/cilium/cilium/issues/32292#issuecomment-2095266239) in the above issue this should work with Cilium, but goes against the Gateway API spec.

I've tried a TLSRoute with a Gateway HTTPS-listener in both `tls.mode: Passthrough` and `tls.mode: Terminate`. They both appear to work. I especially wouldn't expect the `Terminate` one to work, though Nick gave a good explanation as to why it does in his comment.

### Cilium Version

1.51.1

### Kernel Version

6.1.0-20-amd64

### Kubernetes Version

v1.29.3

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vehagn** [comment]
Thanks again for looking into this @youngnick.

I did some more testing when trying to debug what I though was a Cert-manager issue, but I now unfortunately think is a shortcoming with Cilium. I've tried to summarise my testing in [this comment](https://github.com/cert-manager/cert-manager/issues/6985#issuecomment-2103580595) over at the Cert-manager GitHub. I can repeat it here if needed.

**Comment by youngnick** [comment]
Sorry, no updates as yet, although I think that @sayboras has some ideas for general Gateway API processing improvements that may help this. We didn't make the feature freeze for 1.16, so that's going to have to be a 1.17 change, sorry.

**Comment by youngnick** [comment]
still an issue, needs investigation.

**Comment by vehagn** [comment]
@youngnick 
Using Gateway API v1.3 and Cilium v1.17.6 I'm down to a single Gateway serving both `HTTPRoutes` and `TLSRoutes` and it appears that everything it working although both Route types attach to both listeners, e.g. with 19 `HTTPRoutes` and 3 `TLSRoutes` and the following `Gateway` 

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: gateway
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 192.168.1.220
  listeners:
    - protocol: TLS
      port: 443
      name: tls-passthrough
      hostname: "*.example.com"
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 443
      name: https-gateway
      hostname: "*.example.com"
      tls:
        certificateRefs:
          - kind: Secret
            name: cert-stonegarden
      allowedRoutes:
        namespaces:
          from: All
```

We can see that both listeners have 22 routes attached

```bash
kubectl -n gateway get gateway internal -oyaml | yq '.status'
```

```yaml
addresses:
  - type: IPAddress
    value: 192.168.1.220
conditions:
  - lastTransitionTime: "2025-07-19T19:27:27Z"
    message: Gateway successfully scheduled
    observedGeneration: 1
    reason: Accepted
    status: "True"
    type: Accepted
  - lastTransitionTime: "2025-07-19T19:27:27Z"
    message: Gateway successfully reconciled
    observedGeneration: 1
    reason: Programmed
    status: "True"
    type: Programmed
listeners:
  - attachedRoutes: 22
    conditions:
      - lastTransitionTime: "2025-07-19T20:35:37Z"
        message: Listener Programmed
        observedGeneration: 1
        reason: Programmed
        status: "True"
        type: Programmed
      - lastTransitionTime: "2025-07-19T20:35:37Z"
        message: Listener Accepted
        observedGeneration: 1
        reason: Accepted
        status: "True"
        type: Accepted
      - lastTransitionTime: "2025-07-19T20:35:37Z"
        message: Resolved Refs
        reason: ResolvedRefs
        status: "True"
        type: ResolvedRefs
    name: tls-passthrough
    supportedKinds:
      - group: gateway.networking.k8s.io
        kind: TLSRoute
  - attachedRoutes: 22
    conditions:
      - lastTransitionTime: "2025-07-19T20:35:37Z"
        message: Listener Programmed
        observedGeneration: 1
        reason: Programmed
        status: "True"
        type: Programmed
      - lastTransitionTime: "2025-07-19T20:35:37Z"
        message: Listener Accepted
        observedGeneration: 1
        reason: Accepted
        status: "True"
        type: Accepted
      - lastTransitionTime: "2025-07-19T20:35:37Z"
        message: Resolved Refs
        reason: ResolvedRefs
        status: "True"
        type: ResolvedRefs
    name: https-gateway
    supportedKinds:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
```

**Comment by youngnick** [comment]
Needs to be checked to see if recent refactors and changes have fixed it already.

**Comment by arybolovlev** [comment]
This issue seems to be resolved.

Cilium version:

```shell
$ cilium version
cilium-cli: v0.19.4 compiled with go1.26.3 on darwin/arm64
cilium image (default): v1.19.3
cilium image (stable): v1.19.5
cilium image (running): 1.19.5
```

Gateway and TLSRoute manifests:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: issue
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTPS
      port: 443
      name: https-gateway
      hostname: "*.example.com"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: issue
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: issue
spec:
  parentRefs:
    - name: issue
      namespace: default
  hostnames:
    - "test.example.com"
  rules:
    - backendRefs:
        - name: backend
          port: 443
```

TLSRoute was not accepted:

```yaml
status:
  parents:
  - conditions:
    - lastTransitionTime: "2026-06-22T10:49:14Z"
      message: 'No Listener with matching Protocol. Allowed protocols: [TLS]'
      observedGeneration: 1
      reason: NotAllowedByListeners
      status: "False"
      type: Accepted
    - lastTransitionTime: "2026-06-22T10:49:14Z"
      message: Service reference is valid
      observedGeneration: 1
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    controllerName: io.cilium/gateway-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: issue
      namespace: default
```

Related PR: https://github.com/cilium/cilium/pull/44397
