### ISSUE TITLE
CI: Conformance Ginkgo: Client pods not ready after timeout: `timed out waiting for pods with filter -l type=client to be ready: 8m0s timeout expired`

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#32404]
## CI failure

```

• Failure [1086.350 seconds]
K8sDatapathConfig
/home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:461
  High-scale IPcache
  /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:461
    Test ingress policy enforcement with GENEVE and endpoint routes [It]
    /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:515

    Client pods not ready after timeout
    Unexpected error:
        <*fmt.wrapError | 0xc003562e20>: 
        timed out waiting for pods with filter -l type=client to be ready: 8m0s timeout expired
        {
            msg: "timed out waiting for pods with filter -l type=client to be ready: 8m0s timeout expired",
            err: <*errors.errorString | 0xc003561e90>{
                s: "8m0s timeout expired",
            },
        }
    occurred

    /home/runner/work/cilium/cilium/test/k8s/datapath_configuration.go:695
```

Sysdump is too large to upload here.

https://github.com/cilium/cilium/actions/runs/8980253691

**Comment by mhofstetter** [comment]
catched another one and detected the following in the sysdump 

https://github.com/cilium/cilium/actions/runs/9107971706/job/25037869655

(inner sysdump [cilium-sysdump.zip](https://github.com/cilium/cilium/files/15332799/cilium-sysdump.zip))


```
kube-system         cilium-9n6jt                                 0/1     CrashLoopBackOff   4 (81s ago)     4m1s    172.18.0.2   kind-worker          <none>           <none>
```

```
    containerStatuses:
    - containerID: containerd://67dd5a15659f8ca69aed97b688564f8f8ac2bda6d4a235738c47055737125ac8
      image: quay.io/cilium/cilium-ci:4aa6a7fa004b3147bb0cf6f368bebb8f4df450df
      imageID: quay.io/cilium/cilium-ci@sha256:39c4823838cae593227de56881164efd72b15534cf82395999c83d2746c43d97
      lastState:
        terminated:
          containerID: containerd://67dd5a15659f8ca69aed97b688564f8f8ac2bda6d4a235738c47055737125ac8
          exitCode: 1
          finishedAt: "2024-05-16T07:32:49Z"
          message: |-
            time="2024-05-16T07:32:48Z" level=debug msg="NAME clang STATUS R PID 398 CPU: 118.75% MEM: 0.61% CMDLINE: [clang -I/var/run/cilium/state/globals -I/var/run/cilium/state/templates/baf7f5ca798fcaa63467381be04513cbeb161c9041d734680d12cf82541b2db0 -I/var/lib/cilium/bpf -I/var/lib/cilium/bpf/include -g -O2 --target=bpf -std=gnu89 -nostdinc -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -Wimplicit-int-conversion -Wenum-conversion -D__NR_CPUS__=4 -mcpu=v3 -c /var/lib/cilium/bpf/bpf_lxc.c -o -] MEM-EXT: RSS: 73 VMS: 125 Data: 20 Stack: 0 Locked: 0 Swap: 0" endpointID=2645 subsys=endpoint
            time="2024-05-16T07:32:48Z" level=debug msg="Load 1-min: 1.48 5-min: 3.11 15min: 2.79" subsys=loadinfo type=background
            time="2024-05-16T07:32:48Z" level=debug msg="Memory: Total: 11969 Used: 2138 (17.86%) Free: 2335 Buffers: 145 Cached: 7155" subsys=loadinfo type=background
            time="2024-05-16T07:32:48Z" level=debug msg="Swap: Total: 0 Used: 0 (NaN%) Free: 0" subsys=loadinfo type=background
            time="2024-05-16T07:32:48Z" level=debug msg="NAME cilium-agent STATUS S PID 1 CPU: 30.13% MEM: 1.17% CMDLINE: [cilium-agent --config-dir=/tmp/cilium/config-map] MEM-EXT: RSS: 140 VMS: 1308 Data: 108 Stack: 0 Locked: 0 Swap: 0" subsys=loadinfo type=background
            time="2024-05-16T07:32:48Z" level=debug msg="NAME clang STATUS R PID 398 CPU: 128.75% MEM: 0.61% CMDLINE: [clang -I/var/run/cilium/state/globals -I/var/run/cilium/state/templates/baf7f5ca
          reason: Error
          startedAt: "2024-05-16T07:32:36Z"
      name: cilium-agent
      ready: false
      restartCount: 4
      started: false
      state:
        waiting:
          message: back-off 1m20s restarting failed container=cilium-agent pod=cilium-9n6jt_kube-system(3726000e-e008-4b5c-b82d-55b295cf8cd6)
          reason: CrashLoopBackOff

```

another one (https://github.com/cilium/cilium/actions/runs/9101307271) with the same ending loglines in the `prev` logfile of the agents. (inner sysdump: [cilium-sysdump.zip](https://github.com/cilium/cilium/files/15332777/cilium-sysdump.zip))
