### ISSUE TITLE
Ingress paths with multiples match does not give precedence to the longest match

### ISSUE THREAD

**Issue by ese** [cilium/cilium#32467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Following an upgrade from Cilium version 1.14.1 to 1.14.2, we observed a change in ingress traffic routing behaviors under specific conditions involving multiple path matches.

**Issue Details:**
- **Ingress Configuration:**
  - Service A is configured with the path `/`.
  - Service B has two configurations: one with the path `/api` and another with the regex path `/(.*)/api`.

- **Observed Behavior:**
  - In version 1.14.1, ingress traffic that matched the regex path was correctly routed to Service B, likely due to the more specific path configuration.
  - After upgrading to 1.14.2, traffic intended for the third configuration (`/(.*)/api`) is incorrectly routed to Service A instead of Service B.

Additionally, from version 1.14.4 to 1.14.5, a new issue emerged when TLS is enabled on ingresses. With TLS, all requests are incorrectly routed to Service A, irrespective of the specified path.

These routing errors disrupt expected network traffic flow and service delivery within our Kubernetes environment.

steps and manifests to reproduce the issue:

`serviceA.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: a-service
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: http-port
  selector:
    app: a-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a-server
  template:
    metadata:
      labels:
        app: a-server
    spec:
      containers:
      - image: jmalloc/echo-server
        imagePullPolicy: Always
        name: echo-server
        ports:
        - containerPort: 8080
          name: http-port
          protocol: TCP
      restartPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: cilium
  name: servicea-default
  namespace: servicea
spec:
  ingressClassName: cilium
  rules:
  - host: shareddomain.local
    http:
      paths:
      - backend:
          service:
            name: a-service
            port:
              number: 80
        path: /
        pathType: Prefix
```

serviceB.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b-server
  template:
    metadata:
      labels:
        app: b-server
    spec:
      containers:
      - image: jmalloc/echo-server
        imagePullPolicy: Always
        name: echo-server
        ports:
        - containerPort: 8080
          name: http-port
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: b-service
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: http-port
  selector:
    app: b-server
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: cilium
  name: b-path
  namespace: serviceb
spec:
  ingressClassName: cilium
  rules:
  - host: shareddomain.local
    http:
      paths:
      - backend:
          service:
            name: b-service
            port:
              number: 80
        path: /api
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: cilium
  name: b-statics
  namespace: serviceb
spec:
  ingressClassName: cilium
  rules:
  - host: shareddomain.local
    http:
      paths:
      - backend:
          service:
            name: b-service
            port:
              number: 80
        path: /exact-path
        pathType: Exact
      - backend:
          service:
            name: b-service
            port:
              number: 80
        path: /(.*)/api
        pathType: Prefix
```

test.sh
```bash
#!/bin/bash

set -e

DOMAIN="shareddomain"
PROTOCOL="http"

curl -s ${PROTOCOL}://${DOMAIN}/ | grep a-deployment || echo "ERROR: / -> serviceA"
curl -s ${PROTOCOL}://${DOMAIN}/api/random | grep b-deployment || echo "ERROR: /api/X -> serviceB"
curl -s ${PROTOCOL}://${DOMAIN}/fr/api/random | grep b-deployment || echo "ERROR: /fr/api/X -> serviceB"
curl -s ${PROTOCOL}://${DOMAIN}/exact-path | grep b-deployment || echo "ERROR: /exact-path -> serviceB"
curl -s ${PROTOCOL}://${DOMAIN}/random | grep a-deployment || echo "ERROR: /random -> serviceA"
```

Ensure you change `shareddomain.local` for some domain reachable to your cluster

1.- Apply serviceA manifests in servicea namespace
```
kubectl create ns servicea
kubectl -n servicea apply -f servicea.yaml

kubectl create ns serviceb
kubectl -n serviceb apply -f serviceb.yaml
```

2.- Execute `test.sh` script for quick testing
```
output with 1.14.1

Request served by a-deployment-665985fc6-pngtd
Request served by b-deployment-7cd6564859-lrr8s
Request served by b-deployment-7cd6564859-lrr8s
Request served by b-deployment-7cd6564859-lrr8s
Request served by a-deployment-665985fc6-pngtd


output with cilium 1.14.2 and beyond

Request served by a-deployment-665985fc6-pngtd
Request served by b-deployment-7cd6564859-lrr8s
ERROR: /fr/api/X -> serviceB
Request served by b-deployment-7cd6564859-lrr8s
Request served by a-deployment-665985fc6-pngtd

```
 

Furthermore we have detected also a change betweent 1.14.4 to 1.14.5 where ingress is sent to the wrong service for most wide cases when you are using TLS for the ingresses. 

To reproduce this just add TLS config for the same example than before and all requests will end in service A despite the path you use in the request.

Manifests for TLS:

`serviceA.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: a-service
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: http-port
  selector:
    app: a-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a-server
  template:
    metadata:
      labels:
        app: a-server
    spec:
      containers:
      - image: jmalloc/echo-server
        imagePullPolicy: Always
        name: echo-server
        ports:
        - containerPort: 8080
          name: http-port
          protocol: TCP
      restartPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: cilium
    cert-manager.io/cluster-issuer: letsencrypt-cluster
  name: servicea-default
  namespace: servicea
spec:
  ingressClassName: cilium
  rules:
  - host: shareddomain.local
    http:
      paths:
      - backend:
          service:
            name: a-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
    - hosts:
      - shareddomain.local
      secretName: cert-shareddomain
```

serviceB.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b-server
  template:
    metadata:
      labels:
        app: b-server
    spec:
      containers:
      - image: jmalloc/echo-server
        imagePullPolicy: Always
        name: echo-server
        ports:
        - containerPort: 8080
          name: http-port
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: b-service
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: http-port
  selector:
    app: b-server
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: cilium
  name: b-path
  namespace: serviceb
spec:
  ingressClassName: cilium
  rules:
  - host: shareddomain.local
    http:
      paths:
      - backend:
          service:
            name: b-service
            port:
              number: 80
        path: /api
        pathType: Prefix
  tls:
    - hosts:
      - shareddomain.local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: cilium
  name: b-statics
  namespace: serviceb
spec:
  ingressClassName: cilium
  rules:
  - host: shareddomain.local
    http:
      paths:
      - backend:
          service:
            name: b-service
            port:
              number: 80
        path: /exact-path
        pathType: Exact
      - backend:
          service:
            name: b-service
            port:
              number: 80
        path: /(.*)/api
        pathType: Prefix
  tls:
    - hosts:
      - shareddomain.local
```

Change shareddomain.local with a domain that can reach the cluster and set PROTOCOL to https in the test.sh script

Results with TLS config:

```
For v1.14.1

Request served by a-deployment-665985fc6-pngtd
Request served by b-deployment-7cd6564859-lrr8s
Request served by b-deployment-7cd6564859-lrr8s
Request served by b-deployment-7cd6564859-lrr8s
Request served by a-deployment-665985fc6-pngtd

For v1.14.2, v.1.14.3, v1.14.4

Request served by a-deployment-665985fc6-pngtd
Request served by b-deployment-7cd6564859-lrr8s
ERROR: /fr/api/X -> serviceB
Request served by b-deployment-7cd6564859-lrr8s
Request served by a-deployment-665985fc6-pngtd

For v1.14.5 and beyond

Request served by a-deployment-665985fc6-pngtd
ERROR: /api/X -> serviceB
ERROR: /fr/api/X -> serviceB
ERROR: /exact-path -> serviceB
Request served by a-deployment-665985fc6-pngtd
```

### Cilium Version

1.14.2
1.14.5

### Kernel Version

6.1.84

### Kubernetes Version

v1.29.1-eks-61c0bbb

### Regression

1.14.1

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
Thanks for your issue, let me reproduce locally and get back to you soon.

**Comment by ese** [comment]
Could you reproduce the issue @sayboras ?

**Comment by sayboras** [comment]
:wave: 

I tried with main and 1.15 branch, but unable to simulate the above issue. My hunch is that the issue is  fixed by https://github.com/cilium/cilium/pull/29381. 

Appreciate if you can give it a crack with 1.15.x or main branch.

**Comment by youngnick** [comment]
Thanks for this issue @ese. To be honest, your setup is actually not supposed to be working at all!

Let me explain.

There are three types of path supported in Ingress:
- Exact
- Prefix
- ImplementationSpecific

Cilium defines ImplementationSpecific as Regex matching. And we are not supposed to be supporting Regex matching in Prefixes at all.

The reason this behavior changed in 1.14.2 is that we fixed the path sorting so that it is conformant with the upstream Ingress conformance tests, which mandate that paths are sorted in the order:
- Exact
- ImplementationSpecific
- Prefix

Within those classes, the matches are sorted in descending order of length. However, when putting regex matching characters in a prefix match, we haven't defined the behavior at all. That said, it should be sorting the longer match by characters first.

I strongly suggest using the ImplementationSpecific path type for any regex matches, as this will ensure that they get sorted correctly in the final Envoy config.

To be honest, we really should not be configuring Prefix paths containing regex characters, as I'm not sure what Envoy's behavior is here (from your issue, I suspect that all the characters to the right of the regex characters are ignored.)

**Comment by youngnick** [comment]
In terms of your TLS Passthrough issue, it seems like it's the same one as #32224? Could you do a test with 1.16.0-pre.2 and see if that corrects the TLS problem?

**Comment by ese** [comment]
Thanks @youngnick and @sayboras. Make sense what you comment about regex.

Regarding with TLS routing issue I tested and got the same behaviour from `1.14.5` until `1.16.0-pre.2` :(

To give more clear details, it happens when you have Ingress resources for the same domain in different namespaces, it works fine if the ingress rules are in the same namespace.

I can leave a simple example to reproduce the issue:

**Ingress with default backend**
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: cilium
    cert-manager.io/cluster-issuer: letsencrypt-cluster
  name: httpbin-default
  namespace: servicea
spec:
  ingressClassName: cilium
  rules:
  - host: shareddomain.local
    http:
      paths:
      - backend:
          service:
            name: a-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
    - hosts:
      - shareddomain.local
      secretName: httpbin-service-cert
```

**Ingress to catch `/api` requests**
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: cilium
    cert-manager.io/cluster-issuer: letsencrypt-cluster
  name: b-path
  namespace: serviceb
spec:
  ingressClassName: cilium
  rules:
  - host: shareddomain.local
    http:
      paths:
      - backend:
          service:
            name: b-service
            port:
              number: 80
        path: /api
        pathType: Prefix
  tls:
    - hosts:
      - shareddomain.local
      secretName: b-path-service-cert
```

Looking at CiliumEnvoyConfig `cilium-ingress` I notice the lack of routing config when Ingress resources has TLS enabled

This is how `cilium-ingress` routing looks like when you are using ingresses **with TLS**:
```
  - '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
    name: listener-insecure
    virtualHosts:
    - domains:
      - shareddomain.local
      - shareddomain.local:*
      name: shareddomain.local
      routes:
      - match:
          prefix: /
        redirect:
          httpsRedirect: true
  - '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
    name: listener-secure
    virtualHosts:
    - domains:
      - shareddomain.local
      - shareddomain.local:*
      name: shareddomain.local
      routes:
      - match:
          prefix: /
        route:
          cluster: servicea:a-service:80
          maxStreamDuration:
            maxStreamDuration: 0s
```
This is how `cilium-ingress` routing looks like when you are using ingresses **without TLS**:
```
  - '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
    name: listener-insecure
    virtualHosts:
    - domains:
      - shareddomain.local
      - shareddomain.local:*
      name: shareddomain.local
      routes:
      - match:
          pathSeparatedPrefix: /api
        route:
          cluster: serviceb:b-service:80
          maxStreamDuration:
            maxStreamDuration: 0s
      - match:
          prefix: /
        route:
          cluster: servicea:a-service:80
          maxStreamDuration:
            maxStreamDuration: 0s
```

As you can see the CEC with TLS config lack the routes for `/api`. Just remind this happens when you have Ingresses for `/` and  `/api` in different namespaces
