### ISSUE TITLE
Ingress controller load balancer can not connect to nodes

### ISSUE THREAD

**Issue by carlosrejano** [cilium/cilium#32556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have an EKS cluster where we are trying to use Cilium ingress controller and the load balancer created for the ingress can not always connect to the nodes.

What we see is that the load balancer can connect to some nodes during periods but is not a consistent behavior and there is no pattern between the nodes behind that it can connect and the ones that can not.

Checking directly in the nodes also connecting to the nodePort opened for the load balancer does not work so should not be a problem of security groups, anyway we tried opening traffic from every internal address and nothing, some nodes work and others not or even sometimes no nodes happen to be accessible by the load balancer.

I checked and all the nodes have this cilium LB configuration for the nodePort:
```
10.218.248.217:31799   0.0.0.0:0 (331) (0) [NodePort, l7-load-balancer]
0.0.0.0:31799          0.0.0.0:0 (333) (0) [NodePort, non-routable, l7-load-balancer]
10.0.243.9:31799       0.0.0.0:0 (330) (0) [NodePort, l7-load-balancer]
169.254.0.11:31799     0.0.0.0:0 (332) (0) [NodePort, l7-load-balancer]
```

Configuration values used:
```
cni:
  configMap: cni-config
  customConf: true
eni:
  enabled: true
  updateEC2AdapterLimitViaAPI: true
  awsEnablePrefixDelegation: true
  awsReleaseExcessIPs: true
egressMasqueradeInterfaces: eth0
policyEnforcementMode: "never"
ipam:
  mode: eni
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
tunnelProtocol: ""
nodePort:
  enabled: true
nodeinit:
  enabled: true
ingressController:
  enabled: true
```
cni-config configmap values:
```
    {
      "cniVersion":"0.3.1",
      "name":"cilium",
      "plugins": [
        {
          "cniVersion":"0.3.1",
          "type":"cilium-cni",
          "eni": {
            "subnet-ids": ["subnet-xxxxxx", "subnet-xxxxxx", "subnet-xxxxxxx"],
            "first-interface-index": 1
          }
        }
      ]
    }
```

### Cilium Version

We tried it in multiple versions:
- 1.14.1
- 1.15.4
- 1.16.0-pre.0

### Kernel Version

Linux 5.10.215-203.850.amzn2.aarch64 

### Kubernetes Version

v1.26.15

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
