### ISSUE TITLE
1.15.5: ebpf causing issues on Talos Linux (RPi4)

### ISSUE THREAD

**Issue by samip5** [cilium/cilium#32812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Kernel printed out a traceback regarding epbf and the cluster did not ready

### Cilium Version

1.15.5

### Kernel Version

Unable to gather

### Kubernetes Version

1.30.1

### Anything else?

![vlcsnap-2024-05-31-11h33m33s883](https://github.com/cilium/cilium/assets/1703002/e81da8fd-64d6-4336-a3be-a09f663e1c25)

Talos version: 1.7.4, Kubernetes 1.30.1

Values used:
```yaml
#autoDirectNodeRoutes: true
#bandwidthManager:
#  enabled: true
#  bbr: true
bpf:
  masquerade: false
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cluster:
  name: dev
  id: 10
containerRuntime:
  integration: containerd
enableRuntimeDeviceDetection: true
endpointRoutes:
  enabled: true
hubble:
  enabled: false
ipam:
  mode: kubernetes
ipv6:
  enabled: true
enableIPv6Masquerade: true
ipv4NativeRoutingCIDR: "10.42.0.0/16"
ipv6NativeRoutingCIDR: "2001:67c:1104:d000::/56"
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
loadBalancer:
  algorithm: maglev
  mode: dsr
localRedirectPolicy: true
operator:
  rollOutPods: true
  replicas: 1
rollOutCiliumPods: true
routingMode: native
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
```
### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
