### ISSUE TITLE
Fatal error in cilium-agent on 1.16.0-pre.3 with bandwidthManager + BBR

### ISSUE THREAD

**Issue by jackmaninov** [cilium/cilium#32909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Today I tried upgrading from 1.16.0-pre.2 (which I run for an unrelated fix that has probably been backported by now, but why mess with success?) to 1.16.0-pre.3, and I had cilium pods going into CrashLoopBackoff status. Looking at the logs, cilium-agent is dying with either of the following errors:

`time=2024-06-05T10:26:51Z level=error msg="Invoke failed" error="reconciler.Config[github.com/cilium/cilium/pkg/maps/bwmap.Edt].Table cannot be nil" function="bwmap.registerReconciler (.../maps/bwmap/cell.go:41)"`

or

`time="2024-06-05T10:27:16Z" level=fatal msg="failed to start: reconciler.Config[github.com/cilium/cilium/pkg/maps/bwmap.Edt].Table cannot be nil" subsys=daemon`

No other relevant errors or warnings.

Looking at the codebase I see it's related to bandwidthManager configuration. I have `bandwidthManager.enabled: true` and `.bbr: true` in my helm values, but otherwise no bandwidth related policies configured.. This was working fine under 1.16.0-pre.2, and I don't notice any new helm chart values related to bandwidthManager, so I'm at a loss what the source of this error could be.

I'm wondering if this could be a k8s 1.30 / Talos linux related issue. It can also be me using bandwidthManager improperly without fully understanding the implications of doing so (e.g. combined with wireguard encryption), but it has been working well for me in the past and providing latency improvements.

### Cilium Version

cilium-cli: v0.16.8 compiled with go1.22.3 on linux/amd64
cilium image (default): v1.15.5
cilium image (stable): v1.15.5
cilium image (running): unknown. Unable to obtain cilium version. Reason: release: not found

Ran into the issue on upgrade of 1.16.0-pre.2 to **1.16.0-pre.3** using argo-cd.

### Kernel Version

Linux version 6.6.32-talos (@buildkitsandbox) (gcc (GCC) 13.2.0, GNU ld (GNU Binutils) 2.42) #1 SMP Tue May 28 12:51:33 UTC 2024

### Kubernetes Version

Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0

### Relevant log output

```shell
cilium-dbg status output on previously working 1.16.0-pre.2 install:

VStore:                 Ok   Disabled
Kubernetes:              Ok   1.30 (v1.30.0) [linux/arm64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::
CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service
", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    True   [enx0************     ***************************** (Direct Routing)]
Host firewall:           Disabled
SRv6:                    Disabled
CNI Chaining:            none
CNI Config file:         successfully wrote CNI configuration file to /host/etc/cni/net.d/05-cilium.conflist
Cilium:                  Ok   1.16.0-pre.2 (v1.16.0-pre.2-1bc9e514)
NodeMonitor:             Listening for events on 128 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok   
IPAM:                    IPv4: 4/254 allocated from 10.244.3.0/24, 
ClusterMesh:             0/0 clusters ready, 0 global-services
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        EDT with BPF [BBR] [enx0*************]
Routing:                 Network: Tunnel [vxlan]   Host: BPF
Attach Mode:             TCX
Masquerading:            BPF   [enx00cbea9e64a2]   10.244.3.0/24 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       25/25 healthy
Proxy Status:            OK, ip 10.244.3.174, 0 redirects active on ports 10000-20000, Envoy: external
Global Identity Range:   min 65536, max 131071
Hubble:                  Ok              Current/Max Flows: 4095/4095 (100.00%), Flows/s: 8.14   Metrics: Ok
Encryption:              Wireguard       [NodeEncryption: Disabled, cilium_wg0 (Pubkey: ******************************, Port: 51871, Peers: 4)]
Cluster health:          5/5 reachable   (2024-06-05T12:09:59Z)
Modules Health:          Stopped(0) Degraded(0) OK(42)
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackmaninov** [comment]
My (slightly sanitized) cilium values: 

```
ipam:
  mode: kubernetes

kubeProxyReplacement: true
k8sServiceHost: localhost
k8sServicePort: 7445

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

encryption:
  enabled: true
  type: wireguard

ingressController:
  enabled: true
  loadbalancerMode: shared
  enforceHttps: false
  default: true
  defaultSecretNamespace: kube-system
  defaultSecretName: default-tls
  secretsNamespace:
    create: true
    name: cilium-secrets
  service:
    allocateLoadBalancerNodePorts: false

egressGateway:
  enabled: true

l7Proxy: true
bpf:
  masquerade: true

enableIPv4Masquerade: true

hubble:
  enabled: true
  relay:
    enabled: true
  tls:
    auto:
      enabled: true
      method: certmanager
      certValidityDuration: 1095
      certManagerIssuerRef:
        group: cert-manager.io
        kind: Issuer
        name: hubble-ca
  ui:
    enabled: true
    replicas: 1
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-cilium
        kubernetes.io/tls-acme: "true"
        acme.cert-manager.io/http01-edit-in-place: "true"
      hosts:
      - **********
      tls:
      - hosts:
        - **********
        secretName: ingress-hubble-ui-tls
  metrics:
    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction

policyAuditMode: false
nodePort:
  enabled: true
  enableHealthCheck: true

envoy:
  enabled: true
  prometheus:
    enabled: true
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy:
        - NET_BIND_SERVICE
        - CAP_NET_ADMIN
        - CAP_BPF
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE

gatewayAPI:
  enabled: true
  secretsNamespace: 
    name: cilium-secrets
  
bandwidthManager:
  enabled: true
  bbr: true

prometheus:
  enabled: true

operator:
  prometheus:
    enabled: true
      
hostPort:
  enabled: true

cluster:
  name: **********
  id: 1

authentication:
  mutual:
    spire:
      enabled: true
      install:
        enabled: true
        namespace: cilium-spire
        existingNamespace: true
        agent:
          tolerations: 
            - key: "ingress-only"
              effect: "NoSchedule"
              operator: "Exists"
            - key: "no-disk"
              effect: "NoSchedule"
              operator: "Exists"
            - key: "node-role.kubernetes.io/control-plane"
              effect: "NoSchedule"
              operator: "Exists"
```
