### ISSUE TITLE
CFP: Cilium kube-proxy IPIP termination

### ISSUE THREAD

**Issue by gyutaeb** [cilium/cilium#33020]
## Cilium Feature Proposal
        
**Is your proposed feature related to a problem?**

This issue occurs when using Cilium's kube-proxy replacement. When creating a load balancer service in Kubernetes, if this load balancer establishes a connection with the node by the method of an L3 IPIP tunnel(L3 DSR), the load balancer service does not work. This issue has occurred in our private cloud environment.

![image](https://github.com/cilium/cilium/assets/114049480/7db316c2-8777-4133-8cb6-70eb1edd4f77)

In the case of 'No kube-proxy replacement', there are no issues. because kube-proxy operates after the decapsulation of tunl0, so there are no problems. However, in the case of kube-proxy replacement, issues arise. This is because the bpf_host.o of the eth0 ingress tc filter runs before the tunnel device of eth0. from-netdev considers only the Outer IP Header to determine if a packet belongs to a service or not. Therefore, the service does not work.

**Describe your proposed solution**

To resolve this issue, we need to enhance bpf_host.c to consider the inner tuple. When the inner IP header and L4 tuple match the service in bpf_host.c, performing decapsulation resolves the issue. This approach has successfully resolved the issue in our private cloud. I would appreciate it if you could review the code in https://github.com/cilium/cilium/pull/33026. Thank you.

**Comment by gyutaeb** [comment]
Thank you for the review, @gentoo-root! I explain with an example.

1. We declare a load balancer service in Kubernetes as follows. We can check the load balancer IP in the status.
```
apiVersion: v1
kind: Service
metadata:
  name: gyu-example
  namespace: default
spec:
  clusterIP: 10.231.11.63
  clusterIPs:
  - 10.231.11.63
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31650
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gyu-example-server
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 20.0.0.20        <<<<<<<<<<<<<<<<<<<<<<<<< This is load balancer vip.
```

In this state, if we run `cilium service list`, we can see the service IP as you mentioned. And if the load balancer does not use L3 DSR, it will send requests to this service IP.

```
# kubectl -n kube-system exec -it cilium-jpgjl -c cilium-agent -- cilium service list
ID   Frontend             Service Type   Backend
1    40.0.0.40:31650      NodePort       1 => 10.240.1.100:8080 (active)
```
**However, if the load balancer uses L3 DSR, it does not NAT the request to the service IP. Instead, it encapsulates the client's request and sends it as follows:**

`| [outer] A (Load Balancer Interface IP) -> 40.0.0.40 (Node IP) |`
`| [inner] 10.0.0.10(Client)              -> 20.0.0.20 (Load Balancer VIP) |`

**And this inner tuple matches the `LoadBalancer` service IP. Because this feature handles the decapsulation of the outer tuple.** Also the reason why the L3 DSR load balancer worked correctly "without kube-proxy replacement" is that it matched this `LoadBalancer` service IP.
```
# kubectl -n kube-system exec -it cilium-jpgjl -c cilium-agent -- cilium service list
ID   Frontend             Service Type   Backend
3    20.0.0.20:80         LoadBalancer   1 => 10.240.1.100:8080 (active)
```

Traditionally, kube-proxy creates this `LoadBalancer` service to handle packets destined for the load balancer service IP(VIP) within the cluster. And to support this type of L3 DSR.

2. It's the same principle as mentioned before. By decapsulating the outer tuple, the inner tuple is processed by the code below. This also supports the external traffic policy.

https://github.com/cilium/cilium/blob/f5f1e5a22e6106bee5010746a504082c8101ecfa/bpf/bpf_host.c#L602-L607

To illustrate, it look like this:
![image](https://github.com/cilium/cilium/assets/114049480/f063c518-3820-46c7-be8f-9070a2c4c6e5)


If you have any further questions, please feel free to ask anytime :)
