### ISSUE TITLE
Cilium GwAPI N-S load balancing seems to be broken after GAMMA support was added

### ISSUE THREAD

**Issue by PhilipSchmid** [cilium/cilium#33039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I’m pretty sure a bug was introduced with the commits of https://github.com/cilium/cilium/pull/32744 because with [the commit right before](https://github.com/cilium/cilium/commit/1b987b6bd2434f4b7296a7cd1d031efe75db9160), Cilium GwAPI N-S load balancing still worked.

Detailed reproduction steps are described [here](https://github.com/cilium/cilium/pull/32873#issuecomment-2154379375) (open the `Detailed Instructions for GwAPI on AKS BYOCNI E2E Testing` panel).

Works (images from `envoy: Update to pick up fixes #56057`, see [here](https://github.com/cilium/cilium/actions/runs/9363029998/job/25773251880#step:4:1)):
```yaml
image:
  override: quay.io/cilium/cilium-ci:f1455dcbc0eeb0a04417535b76292d46f421063a@sha256:bb94a22dce766024c73514245293cc1234c5561de5bfad1dab0c22e56c701615
operator:
  image:
    override: quay.io/cilium/operator-generic-ci:f1455dcbc0eeb0a04417535b76292d46f421063a@sha256:31f5c971ce3daa82e730e5ed37ef2c886206d703c86b7b7e43a6f4ac085f336d

kubeProxyReplacement: "true"
k8sServiceHost: "etp-test-p-etp-test-philip-22716d-v42tmfk3.hcp.eastus2.azmk8s.io"
k8sServicePort: 443

ingressController:
  enabled: true
  loadbalancerMode: shared
gatewayAPI:
  enabled: true
```

Doesn’t work anymore (images from `Add GAMMA support to Cilium Operator #56084`, see [here](https://github.com/cilium/cilium/actions/runs/9365880992/job/25782532860#step:4:1)):
```yaml
image:
  override: quay.io/cilium/cilium-ci:b39cb9d491ec9f062bad752345f06cd94f89aaa4@sha256:294185e8dc5408aaee6e07b541e086460916403f5f59786b55d149ebd2779feb
operator:
  image:
    override: quay.io/cilium/operator-generic-ci:b39cb9d491ec9f062bad752345f06cd94f89aaa4@sha256:d3cf7b671db1a221b2e4135859ff5a6df7b817b4d403631544d928c88f561b12

kubeProxyReplacement: "true"
k8sServiceHost: "etp-test-p-etp-test-philip-22716d-v42tmfk3.hcp.eastus2.azmk8s.io"
k8sServicePort: 443

ingressController:
  enabled: true
  loadbalancerMode: shared
gatewayAPI:
  enabled: true
```

Both are installed via this:
```bash
cilium install --datapath-mode aks-byocni \
  --version v1.16.0-pre.3 \
  --helm-values=values-main-(working|broken).yaml
```

### Cilium Version

`main` branch

### Kernel Version

`5.15.0-1064-azure`

### Kubernetes Version

`v1.29.4`

### Sysdump

[cilium-sysdump-20240606-112013.zip](https://github.com/user-attachments/files/15782270/cilium-sysdump-20240606-112013.zip)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
