### ISSUE TITLE
Service-Proxy: all entries removed from a service when a single pod is terminating

### ISSUE THREAD

**Issue by nerzhul** [cilium/cilium#33063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have currently 10 clusters where cilium is deployed as a CNI, Kube-Proxy replacement and firewall features enabled. Routing is delegated to kube-router (and only part). We expose service type=LoadBalancers IPs with cilium using BGP+ECMP on the core routers.

On 9 of our 10 clusters all is working fine, but on single one there is a very very weird issue. It's not the biggest cluster. Both in externalTraffic = Local or Cluster, when a traefik pod from a service is terminating, all traefik pods are flushed from the service, as shown on cilium service list, whereas it should remain Running pods. BGP announce works well and continue to announce the pods as intended, but as service proxy has empty pool, all requests receive a ICMP: port-unreachable, which is logical, as the service proxy pool IP has empty backends. After 1/2 mins, the state became at the target. it's very weird and anoying.

Service definition

```yaml


apiVersion: v1
kind: Service
metadata:
  ...
spec:
  allocateLoadBalancerNodePorts: false
  clusterIP: 100.97.148.235
  clusterIPs:
  - 100.97.148.235
  externalTrafficPolicy: Local
  healthCheckNodePort: 31775
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: http3
    port: 443
    protocol: UDP
    targetPort: http3
  selector:
    app.kubernetes.io/instance: traefik-ingress-default
    app.kubernetes.io/name: traefik-ingress-controller
  sessionAffinity: None
  type: LoadBalancer
  
  
  ```

### Cilium Version

1.15.1-1.15.6

### Kernel Version

6.6.30

### Kubernetes Version

1.29.4-1.29.5

### Relevant log output

```shell
[$] via ❄️  impure (nix-shell) on ☁️  on ⛵ kubernetes-admin@cluster
❯ kubectl -n kube-system get pod -o wide |grep cilium-s27n7   
cilium-s27n7                                                                  1/1     Running   0               3h14m   10.xx.xx.10     vp-xxxx.vm.eu                                 <none>           <none>

[$] via ❄️  impure (nix-shell) on ☁️  on ⛵ kubernetes-admin@cluster 
❯ kubectl -n foundation-ingress get pod -o wide |grep vp-xxxx.vm.eu
traefik-ingress-controller-default-86499c4889-9skg7      1/1     Running   0               7d1h    100.92.150.46    vp-xxxx.vm.eu   <none>           <none>
traefik-ingress-controller-default-86499c4889-mzclv      1/1     Running   0               80s     100.92.150.214   vp-xxxx.vm.eu   <none>           <none>

---> terminating one pod <---
---> checking the service list <---

kubectl -n kube-system exec -ti  cilium-s27n7 -- cilium service list |grep 2...

Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
79    10.xx.yy.2:443        LoadBalancer   
<filtered out but ok>
595   10.xx.yy.2:443/i      LoadBalancer 

---> After 1 min <---

79    10.xx.yy.2:443        LoadBalancer   1 => 100.92.150.46:8443 (active)
```

### Anything else?

If you need more info tell me. It sounds like a bug in the service proxy whereas the BGP exposure part works as intended

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
