### ISSUE TITLE
NodeAddress controller can drop addresses on table update

### ISSUE THREAD

**Issue by npdgm** [cilium/cilium#33234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This issue was discovered on Talos clusters with the [Virtual IP](https://www.talos.dev/v1.7/talos-guides/network/vip/) feature enabled. Each control-plane node can be assigned the VIP address for high-availability access to the cluster API.
At any time we expect one node to have two IPs on it's main interface. Here the VIP is `10.0.0.10` and it is affected to node `k8s-xyz-cp-1`:
```
❯ talosctl get members
NODE        NAMESPACE   TYPE     ID                   VERSION   HOSTNAME             MACHINE TYPE   OS               ADDRESSES
10.0.0.11   cluster     Member   k8s-xyz-cp-1         2         k8s-xyz-cp-1         controlplane   Talos (v1.7.4)   ["10.0.0.10","10.0.0.11"]
10.0.0.11   cluster     Member   k8s-xyz-cp-2         2         k8s-xyz-cp-2         controlplane   Talos (v1.7.4)   ["10.0.0.12"]
10.0.0.11   cluster     Member   k8s-xyz-cp-3         3         k8s-xyz-cp-3         controlplane   Talos (v1.7.4)   ["10.0.0.13"]
10.0.0.11   cluster     Member   k8s-xyz-worker-a-1   1         k8s-xyz-worker-a-1   worker         Talos (v1.7.4)   ["10.0.0.21"]
10.0.0.11   cluster     Member   k8s-xyz-worker-b-1   1         k8s-xyz-worker-b-1   worker         Talos (v1.7.4)   ["10.0.0.22"]
10.0.0.11   cluster     Member   k8s-xyz-worker-c-1   1         k8s-xyz-worker-c-1   worker         Talos (v1.7.4)   ["10.0.0.23"]
```
Rebooting this node would reassign the address to an other node, causing the NodeAddress controller to process an update.

The problem can be found in the [`update` function of `nodeAddressController`](https://github.com/cilium/cilium/blob/97f4e25b9093ab19aadd2a60f4ee73c5d4e80f22/pkg/datapath/tables/node_address.go#L355), more specifically this section:
```go
	// Insert new addresses that did not exist.
	for addr := range new {
		if !existing.Has(addr) {
			updated = true
			n.NodeAddresses.Insert(txn, addr)
		}
	}

	// Remove addresses that were not part of the new set.
	for addr := range existing {
		// Ensure full device name match. 'device' may be a prefix of DeviceName, and we don't want
		// to delete node addresses of `cilium_host` because they are not on `cilium`.
		if prefixLen != len(addr.DeviceName) {
			continue
		}

		if !new.Has(addr) {
			updated = true
			n.NodeAddresses.Delete(txn, addr)
		}
	}
```
Let's take for example a node initialy having one address `10.0.0.11`. This `NodeAddress` will have `NodePort` and `Primary` to True as there was a single address.
Then when the  VIP `10.0.0.10` is added to the node, `getAddressesFromDevice` is likely to select this new address as primary and NodePort. Subsequently, a bug is triggered in the `update` function. In the first loop `10.0.0.11` will be re-inserted because it doesn't exist in the table with the same field values. Database will update the existing entry. Then in the second loop, because we don't check the live table but `existing`, the test is true for old field values and the freshly updated entry is deleted.

This bug is very noticiable with the Service LoadBalancer for hostNetwork Pods, as the Service endpoint for the Node bearing the VIP will be unreachable.
Restarting cilium-agent on the node will fix the issue as the bug cannot trigger when the table is empty.

I'm unsure how to fix this except by querying the table again before the deletion loop.
Perhaps there's a smarter approach to this?

### Cilium Version

Client: 1.15.6 a09e05e6b6 2024-06-08T21:31:01Z go version go1.21.11 linux/amd64
Daemon: 1.15.6 a09e05e6b6 2024-06-08T21:31:01Z go version go1.21.11 linux/amd64

### Kernel Version

Linux k8s-xyz-cp-2 6.6.32-talos #1 SMP Tue May 28 13:25:34 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.1

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npdgm** [comment]
`1.16.0-rc.0` is affected
However so far I could not reproduce the issue on `1.14.12` so it may have been introduced in the 1.15 branch

**Comment by npdgm** [comment]
Reproduction steps on the development environment:
1. Spin up the kind cluster
     [ `make kind-down` ]
     `make kind`
     `make kind-image`
     `make kind-install-cilium`
2. Check statedb for eth0 addresses
    ```bash
    for pod in $(kubectl -n kube-system get po -o NAME -l app.kubernetes.io/name=cilium-agent)
    do
       echo -e "\n# $pod"
       kubectl -n kube-system exec -c cilium-agent $pod -- cilium-dbg statedb node-addresses | grep eth0
    done
    ```
    Example:
    ```
    # pod/cilium-dkrc6
    172.25.0.3                  true       true      eth0
    fc00:c111::3                true       true      eth0

    # pod/cilium-pdjc7
    fc00:c111::2                true       true      eth0
    172.25.0.2                  true       true      eth0
    ```
3. Add an other address to the worker. Choosing an other subnet because we want it to be ordered before the node address, and `172.25.0.1` is not available.
    ```
    ❯ docker exec kind-worker ip -br a s dev eth0
    eth0@if162       UP             172.25.0.2/16 fc00:c111::2/64 fe80::42:acff:fe19:2/64 

    ❯ docker exec kind-worker ip a a 172.16.0.123/16 dev eth0
    
    ❯ docker exec kind-worker ip -br a s dev eth0
    eth0@if162       UP             172.25.0.2/16 172.16.0.123/16 fc00:c111::2/64 fe80::42:acff:fe19:2/64 
    ```
4. Check the statedb again
    Example:
    ```
    # pod/cilium-dkrc6
    172.25.0.3                  true       true      eth0
    fc00:c111::3                true       true      eth0

    # pod/cilium-pdjc7
    fc00:c111::2                true       true      eth0
    172.16.0.123                true       true      eth0
    ```
    `172.25.0.2` is missing!
5. Delete `172.16.0.123` and replace it with `172.25.0.123`, same subnet as original node IPs, but ordered after the main node address.
    ```
   ❯ docker exec kind-worker ip a d 172.16.0.123/16 dev eth0
   ❯ docker exec kind-worker ip a a 172.25.0.123/16 dev eth0
   ❯ docker exec kind-worker ip -br a s dev eth0
   eth0@if162       UP             172.25.0.2/16 172.25.0.123/16 fc00:c111::2/64 fe80::42:acff:fe19:2/64 
    ```
6. In this situation the statedb is correct
   ```
   # pod/cilium-dkrc6
   172.25.0.3                  true       true      eth0
   fc00:c111::3                true       true      eth0

   # pod/cilium-pdjc7
   fc00:c111::2                true       true      eth0
   172.25.0.2                  true       true      eth0
   172.25.0.123                false      false     eth0
   ```

**Comment by joamaki** [comment]
The issue here was that the set operations were performed on `NodeAddress` which not only included the IP address, but also the "NodePort" flag. When a new address was added the flag changed. The simplest fix for this is to swap the loops: first delete the existing addresses that are not part of the new set and then add the new ones in. I'll prepare a PR + backport to fix this.

**Comment by npdgm** [comment]
> The simplest fix for this is to swap the loops: first delete the existing addresses that are not part of the new set and then add the new ones in. I'll prepare a PR + backport to fix this.

Great! Thanks a lot.

> I'm still a bit puzzled by what impact this bug had. 

Sorry the report may have been confusing. It doesn't involve a LoadBalancer service in k8s, I'll explain.

Here's an example of Helm values for an install where the issue was first discovered. With this same set of values, 1.14 is fine, but 1.15 and 1.16 exhibit the issue.
`enableRuntimeDeviceDetection` was never set and left to defaults, so yes that was `false` with 1.15. But 1.16 with runtime detection had the exact same problem and behaviour regarding system VIPs.
```yaml
autoDirectNodeRoutes: true
bgpControlPlane:
  enabled: true
bpf:
  masquerade: true
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
endpointStatus:
  enabled: true
  status: policy health controllers log state
externalIPs:
  enabled: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 10.244.0.0/16
k8sServiceHost: localhost
k8sServicePort: 7445
kubeProxyReplacement: true
loadBalancer:
  acceleration: native
  algorithm: maglev
  mode: hybrid
monitor:
  enabled: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
routingMode: native
securityContext:
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
```

> A LoadBalancer service is essentially a NodePort + some static IPs. In your case was the VIP address specified as a LoadBalancer IP?

The VIP feature mentionned isn't managed by a k8s or LoadBalancer controller. An address is added/removed to a node main NIC by a system controller in Talos, just like `ip addr add` would. Should be the same with keepalived, carp, etc.
It's reproduced this way on the development stack in Kind, with the default Cilium config and `ip` commands. And the bug can be observed in statedb and various bpf maps already, no need to dig into Service bits it seems.

An affected Service can be of the ClusterIP type. **LoadBalancer is not required**.
The problem actually happens **when selected Pods are using hostNetwork**, so where Endpoints are Node addresses. Perhaps this is analogue to NodePorts in the datapath, I don't know.

The best example for this would be default Kubernetes API service:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
spec:
  clusterIP: 10.16.0.1
  clusterIPs:
  - 10.16.0.1
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    endpointslice.kubernetes.io/skip-mirror: "true"
  name: kubernetes
  namespace: default
subsets:
- addresses:
  - ip: 10.0.50.11
  - ip: 10.0.50.12
  - ip: 10.0.50.13
  ports:
  - name: https
    port: 6443
    protocol: TCP
```

```yaml
addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.0.50.11
  conditions:
    ready: true
- addresses:
  - 10.0.50.12
  conditions:
    ready: true
- addresses:
  - 10.0.50.13
  conditions:
    ready: true
kind: EndpointSlice
metadata:
  labels:
    kubernetes.io/service-name: kubernetes
  name: kubernetes
  namespace: default
ports:
- name: https
  port: 6443
  protocol: TCP
```

In these dumps, endpoints in `10.0.50.0/24` are node addresses, not from the PodCIDR.

The service is accessed with the Service port `443`.
