### ISSUE TITLE
dnsproxy rules in ciliumclusterwidenetworkpolicy does not respect the endpointselector

### ISSUE THREAD

**Issue by faelis** [cilium/cilium#33357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When deploying this ciliumclusterwidenetworkpolicy :

```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: sncf-allow-on-all-to-dns
spec:
  endpointSelector:
    matchExpressions:
      - key: "k8s-app"
        operator: "NotIn"
        values:
        - kube-dns
        - node-local-dns
      - key: "io.kubernetes.pod.namespace"
        operator: "NotIn"
        values:
        - "kube-system"
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s:k8s-app: node-local-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: TCP
      - port: "53"
        protocol: UDP
      rules:
        dns:
        - matchPattern: '*'
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s:k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: TCP
      - port: "53"
        protocol: UDP
      rules:
        dns:
        - matchPattern: '*'
```
A pod inside the 'kube-system' namespace other than 'kube-dns' or 'node-local-dns' can resolve 'github.com'. But cillium/hubble doesn't see the 'dns-request proxy' event between the pod and node-local-dns. And therefore, the toFQDNs netpol feature doesn't work.

The same netpol without this part :
```
      - key: "io.kubernetes.pod.namespace"
        operator: "NotIn"
        values:
        - "kube-system"
```
allow cilium/hubble to see the missing event, fixing the problem.

I thought that 'endpointselector' worked the same with dnsproxy or with the firewall. Am I wrong?

### Cilium Version

1.15.2

### Kernel Version

6.1.90

### Kubernetes Version

v1.29.1-eks-61c0bbb

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment]
According to the docs, multiple elements inside a `matchExpressions` are handled as an AND and **not** an OR.

https://docs.cilium.io/en/latest/security/policy/kubernetes/#match-expressions

**Comment by faelis** [comment]
Thanks @christarazi  :)

So why does the ANDed way seems to work only with the firewalling part of the netpol, and not with the DNS observability?

According to my first netpol :
A pod (other than node-local-dns) in the kube-system namespace should reach the endpoints in the egress (node-local-dns) -> it works => the matchexpression follow the ANDed way
But the DNS observability between this pod and node-local-dns doesn't show the dns-request event, even if the DNS resolution between them works fine.

Is this the normal behaviour?

**Comment by joestringer** [comment]
> According to my first netpol :
> A pod (other than node-local-dns) in the kube-system namespace should reach the endpoints in > the egress (node-local-dns) -> it works => the matchexpression follow the ANDed way
> But the DNS observability between this pod and node-local-dns doesn't show the dns-request event, even if the DNS resolution between them works fine.

Not quite. The policy doesn't select Pods in the kube-system namespace at all. The following snippet can be interpreted as "Apply the later egress/ingress rules to all Pod that are not kube-dns, not node-local dns, AND not in kube-system namespace".

```
  endpointSelector:
    matchExpressions:
      - key: "k8s-app"
        operator: "NotIn"
        values:
        - kube-dns
        - node-local-dns
      - key: "io.kubernetes.pod.namespace"
        operator: "NotIn"
        values:
        - "kube-system"
```

If the DNS requests for apps in kube-system are working at all, then that is either because you have another policy allowing that traffic, or no policy at all for those Pods.
