### ISSUE TITLE
Different behaviour for CNP creation vs CNP update

### ISSUE THREAD

**Issue by f1ko** [cilium/cilium#33432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

The behaviour of a CiliumNetworkPolicy is not consistent.
Creating a policy then editing it will result in a different behaviour compared to creating the final policy from scratch when using the following functionalities:
- toEndpoints/fromEndpoints
- toCIDR/fromCIDR
- toCIDRSet/fromCIDRSet
- toEntities/fromEntities

This issue is related to https://github.com/cilium/cilium/pull/29608 .

Versions before 1.16 are not affected but it should be treated as a release blocker for 1.16.0.

## How to reproduce

Create a pod:
```
kubectl run tmp-shell --rm -i --tty --image nicolaka/netshoot:v0.8 -- zsh
```

Apply the following policy:
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: test
spec:
  endpointSelector:
    matchLabels:
      run: tmp-shell
  egress:
  - toCIDR:
    - 1.1.1.1/32
    toPorts:
      - ports:
          - port: "80"
```

Inside the pod you can see that the result is as expected:
```
$ curl -m 1 1.1.1.1
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>cloudflare</center>
</body>
</html>

$ curl -m 1 1.1.1.2
curl: (28) Connection timed out after 1002 milliseconds
```

Now **update** the policy and include an empty `toEndpoints` list:
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: test
spec:
  endpointSelector:
    matchLabels:
      run: tmp-shell
  egress:
  - toCIDR:
    - 1.1.1.1/32
    toEndpoints: [] # <-- this
    toPorts:
      - ports:
          - port: "80"
```

Nothing changed:
```
$ curl -m 1 1.1.1.1
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>cloudflare</center>
</body>
</html>

$ curl -m 1 1.1.1.2
curl: (28) Connection timed out after 1002 milliseconds
```

Delete the policy:
```
kubectl delete cnp test
```

Apply the exact same policy again:
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: test
spec:
  endpointSelector:
    matchLabels:
      run: tmp-shell
  egress:
  - toCIDR:
    - 1.1.1.1/32
    toEndpoints: [] # <-- this
    toPorts:
      - ports:
          - port: "80"
```

The behaviour changed:
```
$ curl -m 1 1.1.1.1
curl: (28) Connection timed out after 1002 milliseconds

$ curl -m 1 1.1.1.2
curl: (28) Connection timed out after 1001 milliseconds
```

## Expected

The behaviour should be consistent regardless of the order of operation on a policy.
Following result is what a user should experience at all times for above policy with `toEndpoints: []` in 1.16:
```
$ curl -m 1 1.1.1.1
curl: (28) Connection timed out after 1002 milliseconds

$ curl -m 1 1.1.1.2
curl: (28) Connection timed out after 1001 milliseconds
```

### Cilium Version

```
# cilium-dbg version
Client: 1.16.0-rc.0 14c2b3d0 2024-06-17T16:32:13+02:00 go version go1.22.4 linux/arm64
Daemon: 1.16.0-rc.0 14c2b3d0 2024-06-17T16:32:13+02:00 go version go1.22.4 linux/arm64
```

### Kernel Version

aarch64 6.4.16

### Kubernetes Version

```
$ kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

### Regression

The behaviour for empty slices changed between 1.15 and 1.16 as per https://github.com/cilium/cilium/pull/29608 .
In 1.15 the behaviour is consistent at all times, regardless of the policy being updated or created.

### Anything else?

This is likely due to the [following snippet](https://github.com/cilium/cilium/blob/v1.16.0-rc.0/pkg/policy/api/zz_generated.deepequal.go#L204-L219): 

```
  if ((in.ToEndpoints != nil) && (other.ToEndpoints != nil)) || ((in.ToEndpoints == nil) != (other.ToEndpoints == nil)) {
    in, other := &in.ToEndpoints, &other.ToEndpoints
    if other == nil {
      return false
    }


    if len(*in) != len(*other) {
      return false
    } else {
      for i, inElement := range *in {
        if !inElement.DeepEqual(&(*other)[i]) {
          return false
        }
      }
    }
  }
```

Kudos to @JamesLaverack 

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
