### ISSUE TITLE
CFP: Support Layer 2 VPN Pods

### ISSUE THREAD

**Issue by mfilipiak** [cilium/cilium#33469]
#### Describe the feature you'd like

I have a need to implement Layer 2 or Layer 3 VPN gateways, which I can implement as pods. I typically need a number of different VPN types, but this could be a valid use case for a single VPN type but different configurations. For example, I might have 3 different Wireguard VPNs setup, and I'd like to be able to wire the default gateway of other pods in the cluster to use the configured gateway. 

Requirements:
* Should support Layer 2 routes
* Needs to support inter-node transport (when using an encapsulation config, like vxlan)

I thought this may be a unique use case, but I saw this exact thing asked in eCHO Episode 76:
https://www.youtube.com/live/zEQdgNGa7bg?si=-1cm84qyqm12923t&t=2671

I'd be happy to work on a PR if this is something that would be accepted

#### Describe your proposed solution

Today, it appears that the gateway is automatically resolved to be the NODE_MAC. It seems that when this feature is enabled, a lookup for the matching gateway could be performed instead and pushed for encapsulation through the vxlan interface. I haven't looked too closely to determine if additional ARP work is necessary or not. Maybe that information is already resolved due to the endpoint being in a BPF map. I have to do more homework, but that is the general thought.

```yaml
apiVersion: cilium.io/v2
kind: CiliumL2EgressGatewayPolicy
metadata:
  name: egress-sample
spec:
  # Specify which pods should be subject to the current policy.
  # Multiple pod selectors can be specified.
  selectors:
  - podSelector:
      matchLabels:
        org: empire
        class: mediabot
        # The following label selects default namespace
        io.kubernetes.pod.namespace: default

  # Specify which destination CIDR(s) this policy applies to.
  # Multiple CIDRs can be specified.
  destinationCIDRs:
  - "0.0.0.0/0"

  # Configure the gateway node.
  egressGateway:
    # Specify which node should act as gateway for this policy.
    podSelector:
      matchLabels:
        podName: myEgressPod
```
