### ISSUE TITLE
bpf: LPM lookup does not work with /32 prefix

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3352]
It is currently impossible to whitelist individual /32 for some reason, the following rule does not work:

``` yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "cidr-rule"
spec:
  endpointSelector:
    matchLabels:
     id: client1
  egress:
  - toCIDR:
    - 8.8.8.8/32
```

Whereas the same rule with a `/31` works:

``` yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "cidr-rule"
spec:
  endpointSelector:
    matchLabels:
     id: client1
  egress:
  - toCIDR:
    - 8.8.8.8/31
```
