### ISSUE TITLE
Cilium 1.15 too many open unix sockets

### ISSUE THREAD

**Issue by daleckystepan** [cilium/cilium#33542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium agent and envoy use so many open unix sockets and it increases overtime. It is because of envoy as restarting envoy fix it. It is visible on both containers because of privileged mode probably.

```
wc -l /proc/net/* | sort -h
...
...
...
    173 /proc/net/tcp
   1246 /proc/net/nf_conntrack
  12144 /proc/net/unix
```

And different cluster incl. screenshot
```
    199 /proc/net/tcp
    738 /proc/net/unix
   1573 /proc/net/nf_conntrack
```
<img width="1781" alt="Snímek obrazovky 2024-07-02 v 22 24 55" src="https://github.com/cilium/cilium/assets/36531759/2d9d37e9-7187-4603-a91d-bdaa38a7a51e">

### Cilium Version

1.15.5
1.15.4

### Kernel Version

Linux app-worker-dev-d556f601-qfnnq 5.14.0-427.18.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 28 06:27:02 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.28.10+rke2r1

### Regression

I don't know

### Sysdump

File size too big. Please let me know how should I proceed.

### Relevant log output

```shell
Haven't found anything interesting  in logs
```

### Anything else?
A lot of the unix sockets are `/var/run/cilium/envoy/sockets/admin.sock`

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daleckystepan** [comment]
Here is my config
```
rke2-cilium:
  kubeProxyReplacement: true
  k8sServiceHost: 127.0.0.1
  k8sServicePort: 6443
  routingMode: tunnel
  tunnelProtocol: geneve
  bpf:
    hostLegacyRouting: false
    masquerade: true
  loadBalancer:
    algorithm: random
    mode: dsr
    dsrDispatch: geneve
  gatewayAPI:
    enabled: true
  socketLB:
    enabled: true
    hostNamespaceOnly: true
  l2announcements:
    enabled: true
  k8sClientRateLimit:
    qps: 10
    burst: 20

  # Cilium agent configuration
  rollOutCiliumPods: true
  resources:
    requests:
      cpu: 25m
      memory: 256Mi
    limits:
      memory: 512Mi
  prometheus:
    enabled: ${cilium_prometheus}
    serviceMonitor:
      enabled: ${cilium_prometheus}

  envoy:
    enabled: true
    rollOutPods: true
    maxRequestsPerConnection: 100
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        memory: 512Mi
    prometheus:
      enabled: ${cilium_prometheus}
      serviceMonitor:
        enabled: ${cilium_prometheus}

  operator:
    enabled: true
    rollOutPods: true
    resources:
      requests:
        cpu: 25m
        memory: 128Mi
      limits:
        memory: 512Mi
    prometheus:
      enabled: ${cilium_prometheus}
      serviceMonitor:
        enabled: ${cilium_prometheus}

  ingressController:
    enabled: true
    loadbalancerMode: shared
    service:
      labels:
        app: cilium-ingressgateway
      annotations:
        io.cilium/lb-ipam-ips: "${cidrhost(lb_cidr,4)}"

  hubble:
    enabled: ${cilium_hubble}
    relay:
      enabled: ${cilium_hubble}
      rollOutPods: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          memory: 512Mi
    ui:
      enabled: ${cilium_hubble}
      rollOutPods: true
      frontend:
        resources:
          requests:
            cpu: 50m
            memory: 16Mi
          limits:
            memory: 32Mi
      backend:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 256Mi
      ingress:
        enabled: true
        className: ${ingress_class}
        annotations:
          cert-manager.io/cluster-issuer: ${cluster_issuer_name}
        tls:
          - secretName: hubble.${cluster_name}.${domain}-tls
            hosts:
              - hubble.${cluster_name}.${domain}
        hosts:
          - hubble.${cluster_name}.${domain}
```
