### ISSUE TITLE
Policy: Egress toEntities

### ISSUE THREAD

**Issue by eloycoto** [cilium/cilium#3358]
Policy: 
```
apiVersion: "cilium.io/v2"                                                 
kind: CiliumNetworkPolicy                                                  
description: "L7 policy for getting started using Kubernetes guide"        
metadata:                                                                  
  name: "rule1"                                                            
spec:                                                                      
  endpointSelector:                                                        
    matchLabels:                                                           
      id: app2                                                             
  egress:                                                                  
  - toEntities:                                                            
    - host                                                                 
    - world                                                                
```

Endpoint list: 
```
root@k8s1:~# cilium endpoint list      
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])               IPv6                 IPv4          STATUS        
           ENFORCEMENT        ENFORCEMENT                                                                                                             
3365       Disabled           Disabled          14418      k8s:id=app3                               f00d::a0a:0:0:d25    10.10.0.134   ready         
                                                           k8s:io.kubernetes.pod.namespace=default                                                    
                                                           k8s:zgroup=testapp                                                                         
11004      Disabled           Enabled           42143      k8s:id=app2                               f00d::a0a:0:0:2afc   10.10.0.51    ready         
                                                           k8s:io.kubernetes.pod.namespace=default                                                    
                                                           k8s:zgroup=testapp                                                                         
29898      Disabled           Disabled          23811      reserved:health                           f00d::a0a:0:0:74ca   10.10.0.172   ready         
42910      Disabled           Disabled          19304      k8s:id=app1                               f00d::a0a:0:0:a79e   10.10.0.18    ready         
                                                           k8s:io.kubernetes.pod.namespace=default                                                    
                                                           k8s:zgroup=testapp                                                                         
49508      Disabled           Disabled          19304      k8s:id=app1                               f00d::a0a:0:0:c164   10.10.0.187   ready         
                                                           k8s:io.kubernetes.pod.namespace=default                                                    
                                                           k8s:zgroup=testapp                                                                         
```
Endpoint config
```

root@k8s1:~# cilium endpoint get 11004
[
  {
    "addressing": {
      "ipv4": "10.10.0.51",
      "ipv6": "f00d::a0a:0:0:2afc"
    },
    "configuration": {
      "mutable": {
        "Conntrack": "Enabled",
        "ConntrackAccounting": "Enabled",
        "ConntrackLocal": "Disabled",
        "Debug": "Disabled",
        "DebugLB": "Disabled",
        "DropNotification": "Enabled",
        "EgressPolicy": "Enabled",
        "IngressPolicy": "Disabled",
        "NAT46": "Disabled",
        "TraceNotification": "Enabled"
      }
    },
    "container-id": "b26a9db591423c01ad6aacfb32be794efa1b4cb43f70d9c3691f62e88c679620",
    "container-name": "k8s_POD_app2-d8b88b867-7pq5f_default_d0d807af-3291-11e8-9fab-0800279ce2d5_0",
    "controllers": [
      {
        "configuration": {
          "error-retry": true,
          "interval": "5m0s"
        },
        "name": "resolve-identity-11004",
        "status": {
          "last-failure-timestamp": "0001-01-01T00:00:00.000Z",
          "last-success-timestamp": "2018-03-28T15:25:52.270Z",
          "success-count": 16
        },
        "uuid": "d2beaa93-3291-11e8-b085-0800279ce2d5"
      },
      {
        "configuration": {
          "error-retry": true,
          "interval": "5m0s"
        },
        "name": "sync-IPv4-identity-mapping (11004)",
        "status": {
          "last-failure-timestamp": "0001-01-01T00:00:00.000Z",
          "last-success-timestamp": "2018-03-28T15:25:52.374Z",
          "success-count": 16
        },
        "uuid": "d2c31200-3291-11e8-b085-0800279ce2d5"
      },
      {
        "configuration": {
          "error-retry": true,
          "interval": "5m0s"
        },
        "name": "sync-IPv6-identity-mapping (11004)",
        "status": {
          "last-failure-timestamp": "0001-01-01T00:00:00.000Z",
          "last-success-timestamp": "2018-03-28T15:25:52.374Z",
          "success-count": 16
        },
        "uuid": "d2c3133e-3291-11e8-b085-0800279ce2d5"
      },
      {
        "configuration": {
          "error-retry": true,
          "interval": "1m0s"
        },
        "name": "sync-identity-to-k8s-pod (11004)",
        "status": {
          "last-failure-timestamp": "0001-01-01T00:00:00.000Z",
          "last-success-timestamp": "2018-03-28T15:25:54.102Z",
          "success-count": 76
        },
        "uuid": "d2c3107b-3291-11e8-b085-0800279ce2d5"
      },
      {
        "configuration": {
          "error-retry": true,
          "interval": "10s"
        },
        "name": "sync-to-k8s-ciliumendpoint (11004)",
        "status": {
          "last-failure-timestamp": "0001-01-01T00:00:00.000Z",
          "last-success-timestamp": "2018-03-28T15:26:39.215Z",
          "success-count": 455
        },
        "uuid": "d26eeb66-3291-11e8-b085-0800279ce2d5"
      }
    ],
    "health": {
      "bpf": "OK",
      "connected": true,
      "overallHealth": "OK",
      "policy": "OK"
    },
    "host-mac": "9e:cd:4e:92:fb:7f",
    "id": 11004,
    "identity": {
      "id": 42143,
      "labels": [
        "k8s:id=app2",
        "k8s:zgroup=testapp",
        "k8s:io.kubernetes.pod.namespace=default"
      ],
      "labelsSHA256": "5a31f2981a1e5193550711093e9314b9d9b52dfb05bca3d62a78fe804e68d909"
    },
    "interface-index": 17,
    "interface-name": "lxcb26a9",
    "labels": {
      "custom": [],
      "disabled": [],
      "orchestration-identity": [
        "k8s:id=app2",
        "k8s:io.kubernetes.pod.namespace=default",
        "k8s:zgroup=testapp"
      ],
      "orchestration-info": [
        "container:annotation.kubernetes.io/config.seen=2018-03-28T14:10:49.044924482Z",
        "container:annotation.kubernetes.io/config.source=api",
        "container:io.kubernetes.container.name=POD",
        "container:io.kubernetes.docker.type=podsandbox",
        "container:io.kubernetes.pod.name=app2-d8b88b867-7pq5f",
        "container:io.kubernetes.pod.uid=d0d807af-3291-11e8-9fab-0800279ce2d5",
        "k8s:pod-template-hash=846446423"
      ]
    },
    "mac": "da:f5:b6:4b:ad:73",
    "pod-name": "default:app2-d8b88b867-7pq5f",
    "policy": {
      "allowed-ingress-identities": [
        1
      ],
      "build": 51,
      "cidr-policy": {
        "egress": [],
        "ingress": []
      },
      "id": 42143,
      "l4": {
        "egress": [],
        "ingress": []
      }
    },
    "policy-enabled": "egress",
    "policy-revision": 51,
    "proxy-policy-revision": 36,
    "proxy-statistics": [],
    "state": "ready",
    "status": [
      {
        "code": "OK",
        "message": "Successfully regenerated endpoint program due to endpoint policy updated & changes were needed",
        "state": "ready",
        "timestamp": "2018-03-28T15:25:47Z"
      }
    ]
  }
]
```

Monitor: 
```
xx drop (Policy denied (CIDR)) flow 0xa6a5196c to endpoint 0, identity 42143->0: 10.10.0.51:41674 -> 216.58.215.35:80 tcp SYN 
```
Call:
```
vagrant@k8s1:~/testing$ kubectl exec -ti app2-d8b88b867-7pq5f -- curl -s --connect-timeout 5 http://www.google.es 
command terminated with exit code 7                                                                               
```
