### ISSUE TITLE
Traffic drop due to local identity change

### ISSUE THREAD

**Issue by antonipp** [cilium/cilium#33772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v1.14.12 or higher

### What happened?

We are running Cilium 1.14.12 in GCP in a cluster with `enable-policy: always`. We had an incident with Cilium dropping traffic on one pod after a CNP was deleted in the cluster.

The affected deployment (let's call it "Deployment 1") was running with 3 pods on 3 different nodes and had a CNP looking like this:
```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: deployment-1
  namespace: namespace-1
specs:
[...]
- description: Egress to external services (mostly cloud services)
  egress:
  - toEntities:
    - world
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
  endpointSelector:
    matchLabels:
      app: deployment-1
[...]
```
The service in question was interacting with Google Cloud Storage via [Private Google Access](https://cloud.google.com/vpc/docs/configure-private-google-access-hybrid#config-choose-domain) (IPs in the `199.36.153.8/30` CIDR)

In parallel, there was "Deployment 2" running in "Namespace 2" on different nodes with a CNP looking like this:
```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: deployment-2
  namespace: namespace-2
specs:
[...]
- description: Enable Egress to blob storage in local region
  egress:
  - toCIDR:
    - 199.36.153.8/30
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
  endpointSelector: {}
[...]
```

At one point, Deployment 2 and its associated CNP were deleted in an expected clean-up operation. This was the only CNP in the cluster which explicitly targeted the `199.36.153.8/30` CIDR.

Right after the CNP was deleted, one Cilium agent out of 3 running on Deployment 1 nodes started reporting a big increase in traffic drops to the `199.36.153.8/30` IPs:
![image](https://github.com/user-attachments/assets/54344011-949b-4ec6-a498-ce97e9cbf3c6)

These drops only affected one pod in Deployment 1 and happened only on one Cilium agent.

When looking at the flow logs with `cilium monitor`:
```
# cilium monitor --from 69 --type drop
xx drop (Policy denied) flow 0xe8408cf3 to endpoint 0, ifindex 983, file bpf_lxc.c:1274, , identity 16379101->16777232: pod_ip_here:35596 -> 199.36.153.9:443 tcp SYN
xx drop (Policy denied) flow 0xb24b75db to endpoint 0, ifindex 983, file bpf_lxc.c:1274, , identity 16379101->16777232: pod_ip_here:54908 -> 199.36.153.9:443 tcp SYN
xx drop (Policy denied) flow 0x53d73396 to endpoint 0, ifindex 983, file bpf_lxc.c:1274, , identity 16379101->16777232: pod_ip_here:54772 -> 199.36.153.9:443 tcp SYN
xx drop (Policy denied) flow 0x3055012e to endpoint 0, ifindex 983, file bpf_lxc.c:1274, , identity 16379101->16777232: pod_ip_here:38978 -> 199.36.153.11:443 tcp SYN
xx drop (Policy denied) flow 0x48323591 to endpoint 0, ifindex 983, file bpf_lxc.c:1274, , identity 16379101->16777232: pod_ip_here:40304 -> 199.36.153.10:443 tcp SYN
```

`16379101` was the identity corresponding to "Deployment 1", however `16777232` was no longer a thing:
```
# cilium identity get 16777232
Error: Cannot get identity for given ID 16777232: [GET /identity/{id}][404] getIdentityIdNotFound
```

It for sure corresponded to an identity like this:
```
16777232   cidr:199.36.153.8/30
           reserved:world
```

So looks like despite the `16777232` identity having been released, the policy selector mechanism (not sure I'm using the exact terminology here) was still using `16777232` for `199.36.153.8/30` instead of falling back to identity `2` (`reserved:world`). This seems to have caused traffic drops.

We solved the issue by restarting the affected Cilium Agent. 

### How it happened?

We tried reproducing the problem by re-creating Deployment 1 and Deployment 2 in an isolated cluster and trying to delete / re-create the CNP in a loop but we never managed to reproduce the issue. The identity was correctly flip-flopping between the local identity for the CIDR and `2`:
```
Policy verdict log: flow 0x4f04be35 local EP ID 357, remote ID 16777478, proto 6, egress, action allow, auth: disabled, match L3-L4, pod_ip_here:60416 -> 199.36.153.9:443 tcp SYN
Policy verdict log: flow 0x9b7a6b14 local EP ID 357, remote ID 16777478, proto 6, egress, action allow, auth: disabled, match L3-L4, pod_ip_here:60426 -> 199.36.153.9:443 tcp SYN
Policy verdict log: flow 0xf5b3e4b1 local EP ID 357, remote ID 16777478, proto 6, egress, action allow, auth: disabled, match L3-L4, pod_ip_here:60428 -> 199.36.153.9:443 tcp SYN
Policy verdict log: flow 0xbdd6c4e5 local EP ID 357, remote ID world, proto 6, egress, action allow, auth: disabled, match L3-L4, pod_ip_here:60440 -> 199.36.153.9:443 tcp SYN
Policy verdict log: flow 0xd41361f7 local EP ID 357, remote ID world, proto 6, egress, action allow, auth: disabled, match L3-L4, pod_ip_here:40448 -> 199.36.153.9:443 tcp SYN
Policy verdict log: flow 0x5013313e local EP ID 357, remote ID world, proto 6, egress, action allow, auth: disabled, match L3-L4, pod_ip_here:40464 -> 199.36.153.9:443 tcp SYN
```

### Kernel Version

```
Linux 5.15.0-1063-gcp #71-Ubuntu SMP Wed Jun 12 20:37:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Server Version: v1.26.15
```

### Relevant log output

```shell
There were only two relevant logs from the affected pod (unfortunately we don't have debug logs):

msg="Deleted CiliumNetworkPolicy" ciliumNetworkPolicyName=deployment-2 k8sApiVersion=cilium.io/v2 k8sNamespace=namespace-2 level=info subsys=k8s-watcher time=2024-07-05T08:32:47.479358146Z
msg="UpdateIdentities: Skipping Delete of a non-existing identity" identity=16777232 level=warning subsys=policy time=2024-07-05T08:32:47.480478687Z
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by antonipp** [comment]
Unfortunately the pod and the node are already gone and we didn't get a chance to get an `ipcache` dump or get anything else... Let me know if you want me to try to find more information, we still have metrics.

**Comment by aditighag** [comment]
Hi! We would need a cilium sysdump to debug the issue further. In the meantime, you could also install a newer version of cilium.

**Comment by christarazi** [comment]
Given the relatively high identity value of `16379101`, my guess is there is a decent amount of churn in your cluster that is causing identities to be allocated/deallocated. It's possible that you might have had a policy that overlapped with selecting the `16379101` identity, but that's impossible to say without some history as to where `16379101` came from and what all the policies look like and what identities they select.

**Comment by rcanderson23** [comment]
FWIW we were seeing something very similar in our cluster consistently reproducible with `1.14.12`. Our CNP was:
```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: policy
spec:
  egressDeny:
  - toCIDR:
    - ...
  endpointSelector:
    matchLabels:
      role: auth
  ingressDeny:
  - fromCIDR:
    - ...
```

Traffic gets blocked when applied and continues to get blocked with removal, retrieving the ID from hubble and trying to query showed that it does not exist.

```
xx drop (Policy denied) flow 0xd1e75d49 to endpoint 0, ifindex 98, file bpf_lxc.c:1274, , identity 111666->16777401: 10.17.89.209:44912 -> 35.71.65.110:443 tcp SYN
xx drop (Policy denied) flow 0x62e06888 to endpoint 0, ifindex 122, file bpf_lxc.c:1274, , identity 89670->16777401: 10.17.89.219:49930 -> 35.71.64.117:443 tcp SYN
```
`cilium identity get 16777401` does not exist.

We upgraded to `1.14.13` and now traffic stops and continues as expected with the creation and deletion of the CNP. We think that https://github.com/cilium/cilium/pull/33120 is related.

**Comment by antonipp** [comment]
Thank you, that's a nice catch regarding https://github.com/cilium/cilium/pull/33120 !
We also just upgraded to `1.14.13` so hoping that we won't see this problem again.
In case it ever happens again, I'll make sure to get a sysdump in order to provide more information for debugging.

**Comment by jrajahalme** [comment]
This looks like a relevant in v1.16 and above:

https://github.com/cilium/cilium/commit/d056f67077ac76ff1d6755c43f61a9bb22a5844e

Note how the call to `UpdatePolicyMaps()` due to `idsToAdd` no longer contains the `idsToDelete`? This change may fix the bug, but on v1.15 and earlier `idsToDelete` is still included:

https://github.com/cilium/cilium/blob/v1.15/pkg/ipcache/metadata.go#L397-L399

**Comment by julianwiedmann** [comment]
> Thank you, that's a nice catch regarding [#33120](https://github.com/cilium/cilium/pull/33120) ! We also just upgraded to `1.14.13` so hoping that we won't see this problem again. In case it ever happens again, I'll make sure to get a sysdump in order to provide more information for debugging.

@antonipp given the lack of further updates here, I take it your problem was resolved with the upgrade to v1.14.13? :)

**Comment by pengfeiopen** [comment]
In a CiliumNetworkPolicy, if you write the CIDR as `cidr: 10.236.2.47/24`, it will cause the policy's matching range to be inaccurate. Specifically, this CIDR notation will have the following issues:

**Inaccurate CIDR Range**:

- `10.236.2.47/24` actually represents the entire `10.236.2.0/24` subnet, not just the single IP address `10.236.2.47`. Therefore, this CIDR will match all IP addresses in the range `10.236.2.0` to `10.236.2.255`.
- If your intention is to match only the single IP address `10.236.2.47`, you need to use a more precise CIDR notation, i.e., `10.236.2.47/32`.

**Potential Security Issues**:

- If the policy is inaccurate, it may allow or deny traffic that should not be allowed or denied, leading to potential security vulnerabilities. For example, if the intention is to allow traffic only from a specific IP address, but the CIDR range is too broad, it may allow traffic from the entire subnet.

**Policy Debugging Difficulties**:

- When debugging network policies, an inaccurate CIDR range can make it difficult to understand and resolve issues, as the traffic behavior may not match expectations.

The correct notation should be determined based on your requirements. If you only want to match the single IP address `10.236.2.47`, you should use the `/32` prefix:

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: example-cnp
spec:
  endpointSelector:
    matchLabels:
      app: my-app
  egress:
  - toCIDR:
    - "10.236.2.47/32"
  ingress:
  - fromCIDR:
    - "10.236.2.47/32"
```

This ensures that the policy matches only the single IP address `10.236.2.47`, and not the entire `10.236.2.0/24` subnet.
