### ISSUE TITLE
CiliumNetworkPolicy dropping traffic from endpoints in other clusters

### ISSUE THREAD

**Issue by LarryGF** [cilium/cilium#33822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

vv1.15.7 or higher

### What happened?

`CiliumNetworkPolicy` with clustermesh enabled  is dropping traffic from other clusters when using an `endpointSelector`. The docs suggest that this should be possible and that it should work when using clustermesh.

### How it happened?

I have the following:

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: whoami
  namespace: actions
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: whoami
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: traefik
```
This in theory should allow all traffic from the `traefik` namespace regardless of the cluster: this is not the case, it allows the traffic only when it's coming from the local traefik, but drops it when it comes from the remote traefik. If I change it to allow from `remote-node` works both from the local and remote clusters:
```
...
  ingress:
    - fromEntities:
        - remote-node
        - cluster
```

I can set the policies to audit mode and see that cilium is somehow removing the identity when the traffic is coming from the remote cluster and just treating it as `remote-node`:

Local traefik to local service:
```
Jul  9 16:51:19.077: traefik/traefik-rkwrp:36662 (ID:308271) -> actions/whoami-68689f484b-lvvpp:80 (ID:201017) to-stack FORWARDED (TCP Flags: ACK, FIN)
Jul  9 16:51:19.181: traefik/traefik-rkwrp:36662 (ID:308271) -> actions/whoami-68689f484b-lvvpp:80 (ID:201017) to-stack FORWARDED (TCP Flags: ACK)
```
Remote traefik to local service:
```
hubble observe flows -t policy-verdict
Jul  9 16:55:08.847: 172.22.0.31:56430 (remote-node) -> actions/whoami-68689f484b-lvvpp:80 (ID:201017) policy-verdict:none INGRESS AUDITED (TCP Flags: SYN)
Jul  9 16:55:09.021: 172.22.0.31:56444 (remote-node) -> actions/whoami-68689f484b-lvvpp:80 (ID:201017) policy-verdict:none INGRESS AUDITED (TCP Flags: SYN)
```

In theory I could allow traffic from `remote-node` and be done with it, but basically I'm allowing *all* traffic from every meshed cluster without applying any further restriction to it.

### Kernel Version

Kernel version
6.1.90+

### Kubernetes Version

Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2-gke.1447000

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
