### ISSUE TITLE
Using Cilium V1.16.0 External Access with DNS-Based Policies is not working properly

### ISSUE THREAD

**Issue by superzhu** [cilium/cilium#33875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0-rc.1 and lower than v1.17.0

### What happened?

While following the doc https://docs.cilium.io/en/latest/security/dns/, before running step 'kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/kubernetes-dns/dns-matchname.yaml', running command 'kubectl exec mediabot -- curl -I -s https://api.github.com | head -1' returns normal response; after applying dns policy, the same command hangs

### How can we reproduce the issue?

Here are the steps:
1. Create Kubernetes cluster using kind:
       kind create cluster --name test --config kind-config.yaml
       and content of kind-config.yaml is:
       
 ```
kind: Cluster
name: test
nodes:
  - role: control-plane
    image: "kindest/node:v1.30.2"
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "bgp=controlplane"
  - role: worker
    image: "kindest/node:v1.30.2"
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "bgp=65001"
  - role: worker
    image: "kindest/node:v1.30.2"
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "bgp=65001"
networking:
  ipFamily: ipv4
  #apiServerAddress: 127.0.0.1
  apiServerPort: 6443
  podSubnet: 10.1.0.0/16
  serviceSubnet: 172.20.0.0/16
  disableDefaultCNI: true
  kubeProxyMode: none
```
  
  2. Install Cilium using command:
      a) git clone Cilium repository
      b) git switch to branch 1.16.0-rc.2
      c) cd to ${patht to cilium}/install/kubernetes
      d)helm upgrade --install --namespace kube-system  cilium ./cilium -f ${path to custom value file}/cilium-values.yaml
      e) content of cilium-values.yaml
      

```
healthChecking: true
endpointHealthChecking:
  # -- Enable connectivity health checking between virtual endpoints.
  enabled: false

cluster:
  name: test
  id: 1

ipv4:
  enabled: true
enableIPv4BIGTCP: true
enableIPv6BIGTCP: false

ipv6:
  enabled: false

kubeProxyReplacement: "true"
# cluster name is test
k8sServiceHost: test-control-plane
k8sServicePort: 6443

routingMode: "native"
# -- Allows to explicitly specify the IPv4 CIDR for native routing.
ipv4NativeRoutingCIDR: "10.1.0.0/16"
enableIPv4Masquerade: true
autoDirectNodeRoutes: true
enableCiliumEndpointSlice: false
endpointRoutes:
  enabled: true

bpf:
  masquerade: true
  datapathMode: netkit

ipam:
  #mode: "cluster-pool"
  mode: "kubernetes"

  operator:
     # -- IPv4 CIDR list range to delegate to individual nodes for IPAM.
    clusterPoolIPv4PodCIDRList: ["10.1.0.0/16"]
    # -- IPv4 CIDR mask size to delegate to individual nodes for IPAM.
    clusterPoolIPv4MaskSize: 26

bgpControlPlane:
  enabled: true
operator:
  replicas: 1

  prometheus:
    enabled: true
```

3. Run command: kubectl create -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/kubernetes-dns/dns-sw-app.yaml
4. Run command: kubectl exec mediabot -- curl -I -s https://api.github.com | head -1
    Get normal output: HTTP/2 200
5. Run command: kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/kubernetes-dns/dns-matchname.yaml
6. Run command: kubectl exec mediabot -- curl -I -s https://api.github.com | head -1
    curl request hang here, after timeout, failure with exit code 6
    
 7 doing same above steps with Cilium v1.15.6/v1.15.7, just comment out bpf.datapathMode in cilium-values.yaml, no curl hang, everything is normal

### Cilium Version

Cilium v1.15.6/v1.15.7 --- are normal versions, no issue found with those version
Cilium  V1.16.0-rc.1/ V1.16.0-rc.2 with bpf.datapathMode=netkit, http request to external domain name hang

### Kernel Version

iUbuntu 6.8.0-38-generic x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 24.04)

### Kubernetes Version

Kubernetes v1.30.0
Kind version: kind v0.23.0 go1.21.10 linux/amd64

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
> 4. Run command: kubectl exec mediabot -- curl -I -s https://api.github.com | head -1
> Get normal output: HTTP/2 200
> 5. Run command: kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/kubernetes-dns/dns-matchname.yaml
> 6. Run command: kubectl exec mediabot -- curl -I -s https://api.github.com | head -1
curl request hang here, after timeout, failure with exit code 6

For step 6 did you mean to run this instead?

```
$ kubectl exec mediabot -- curl -I -s --max-time 5 https://support.github.com | head -1
```

The above reqeuest is what the documentation for the feature describes to do:
https://docs.cilium.io/en/v1.16.0-rc.2/security/dns/#apply-dns-egress-policy

When I try this, I get exit code 28. From `man curl` exit code 6 means it could not resolve the host. This implies a DNS issue.

I attempted to reproduce this without the netkit feature in my own kind environment on kernel 6.5, and I couldn't reproduce the issue. I ran through the full guide and it all worked with `v1.16.0-rc.2`.

**Comment by borkmann** [comment]
> d)helm upgrade --install --namespace kube-system cilium ./cilium -f ${path to custom value file}/cilium-values.yaml

@superzhu From your description, you basically attempted to do an in-place upgrade from veth to netkit. See Note in docs:

https://docs.cilium.io/en/latest/operations/performance/tuning/#netkit-device-mode

You either would have to use per-node config for newly joining nodes to the cluster, or create a cluster from scratch with netkit right away. The issue is that when you just set the config and do the upgrade, then the Pods themselves still will have veth because the CNI plugin cannot update them in place.

**Comment by superzhu** [comment]
@borkmann I am not doing Cilium upgrade, Whether I using Cilium V1.15.7 or Cilium v1.16.0-rc.2, I am setting up a fresh Kubernetes cluster

**Comment by superzhu** [comment]
@joestringer the request should be:
kubectl exec mediabot -- curl -I -s --max-time 5 https://api.github.com | head -1

**Comment by borkmann** [comment]
> @borkmann I am not doing Cilium upgrade, Whether I using Cilium V1.15.7 or Cilium v1.16.0-rc.2, I am setting up a fresh Kubernetes cluster

Okay, will try to repro locally on kind.

**Comment by superzhu** [comment]
@borkmann @joestringer When commented out Cilium configuration parameter '`bpf.datapathMode: netkit`', using Cilium v1.16.0-rc.2, running curl request: kubectl exec mediabot -- curl -I -s --max-time 5 https://api.github.com/ | head -1

before and after I apply the dns policy, I got normal response

**Comment by borkmann** [comment]
In our Cilium CI, we have several connectivity tests with netkit (17-22):
https://github.com/cilium/cilium/blob/main/.github/workflows/conformance-e2e.yaml#L280

What is you disable:
> endpointRoutes:
>  enabled: true

**Comment by superzhu** [comment]
> In our Cilium CI, we have several connectivity tests with netkit (17-22): https://github.com/cilium/cilium/blob/main/.github/workflows/conformance-e2e.yaml#L280
> 
> What if you disable the below?
> 
> > endpointRoutes:
> > enabled: true

I will do it now

**Comment by superzhu** [comment]
@joestringer @borkmann when using bpf.datapathMode:netkit and apply dns policy, I tried same curl request with different timeout value, get different exit code; FYI

```
$$ kubectl exec mediabot -- curl -I -s **--max-time 50** https://api.github.com/ --verbose
* Could not resolve host: api.github.com
* Closing connection 0
command terminated with exit code 6

$$ kubectl exec mediabot -- curl -I -s **--max-time 5** https://api.github.com/ --verbose
* Resolving timed out after 5000 milliseconds
* Closing connection 0
command terminated with exit code 28
```

**Comment by superzhu** [comment]
Test using Cilium V1.16.0, the issue still exists.

**Comment by borkmann** [comment]
Hey @superzhu this looks like a kernel regression since the netkit e2e tests in our CI all pass. See also main branch CI https://github.com/cilium/cilium/actions/runs/10178998366 (test 17-22 cover netkit). I'll see to find some cycles to debug.

**Comment by Lakers817** [comment]
Hi - I'm seeing a similar issue with my setup, coreDNS is timimg out when I set the flag `bpf.datapathMode=netkit` otherwise it
works fine without the netkit flag. 

I'm using version 1.16.0 and 1.15.4, following are the test run.


 Environment - AWS non-EKS dualstack cluster hardway setup - k8s 1.30
 Virtualization: xen
 Operating System: Ubuntu 24.04 LTS                
 Kernel: Linux 6.8.0-1010-aws
 Architecture: x86-64




➡️   When  --set bpf.datapathMode=netkit  is enabled.


ubuntu@ip-172-~/cilium$ kpo

NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE    IP                             NODE                  
kube-system   cilium-df569                       1/1     Running   0          3m4s   2600:[REDACTED]           ip-172-31-
kube-system   cilium-envoy-s6shf                 1/1     Running   0          3m4s   2600:[REDACTED]           ip-172-31-2
kube-system   cilium-operator-7f579fc87d-khjgv   1/1     Running   0          3m4s   2600:[REDACTED]           ip-172-31-2
👉️ kube-system   coredns-6d7ff78994-rb22b           0/1     Running   0          56s    2600:[REDACTED]           ip-172-31-2      


⛔️ ERROR : go:231: failed to list *v1.EndpointSlice: Get "https://[2600:[REDACTED]:443/apis/discovery.k8s.io/v1/endpointslices?limit=500&resourceVersion=0": dial tcp [2600:[REDACTED]]:443: i/o timeout
 [INFO] plugin/kubernetes: Trace[1221299684]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.27.4/tools/cache/reflector.


Normal   Created    50s (x2 over 111s)  kubelet            Created container coredns
  Normal   Started    50s (x2 over 111s)  kubelet            Started container coredns
  Warning  Unhealthy  48s (x2 over 109s)  kubelet            Readiness probe failed: Get "http://[2600:]:8181/ready": dial tcp [2600:]:8181: i/o timeout (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  46s                 kubelet            Liveness probe failed: Get "http://[2600::8080/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  0s (x13 over 110s)  kubelet            Readiness probe failed: Get "http://[2600:]:8181/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)


ubuntu@ip-172-31-:~/cilium$ kubectl exec -it cilium-df569 -n kube-system /bin/sh


# cilium status

KVStore:                Ok   etcd: 2/2 connected, leases=1, lock leases=1, has-quorum=true: https://[2600:1[REDACTED]b]:2379 - 3.4.5 (Leader); https://[2600:[REDACTED]]:2379 - 3.4.5
Kubernetes:             Ok   1.30 (v1.30.0) [linux/amd64]
Kubernetes APIs:        ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumNetworkPolicy", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   True   [enX0    172.31. 2600:[REDACTED] fe80::[REDACTED] (Direct Routing)]
Host firewall:          Disabled
SRv6:                   Disabled
CNI Chaining:           none
CNI Config file:        successfully wrote CNI configuration file to /host/etc/cni/net.d/05-cilium.conflist
Cilium:                 Ok   1.16.0 (v1.16.0-82999990)
NodeMonitor:            Listening for events on 15 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPAM:                   IPv4: 3/254 allocated from 10.200.0.0/24, IPv6: 3/254 allocated from 2600:[REDACTED]::/120
IPv4 BIG TCP:           Disabled
IPv6 BIG TCP:           Disabled
BandwidthManager:       Disabled
Routing:                Network: Native   Host: BPF
Attach Mode:            TCX
Device Mode:            netkit
Masquerading:           BPF   [enX0]   10.200.0.0/16 [IPv4: Enabled, IPv6: Enabled]
Controller Status:      30/31 healthy
  Name               Last success   Last error   Count   Message
cilium-health-ep   3m45s ago      4s ago       5       Get "http://10.200.0.71:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)   
Proxy Status:                                            OK, ip 10.200.0.233, 0 redirects active on ports 10000-20000, Envoy: external
Global Identity Range:                                   min 256, max 65535
Hubble:                                                  Ok                                       Current/Max Flows: 4095/4095 (100.00%), Flows/s: 23.23   Metrics: Disabled
Encryption:                                              Disabled                                 
Cluster health:                                          0/1 reachable                            (2024-08-03T12:42:13Z)
  Name                                                   IP                                       Node        Endpoints
  kubernetes/ip-172-31-2.ec2.internal (localhost)   172.31.248.41,2600:[REDACTED]   reachable   unreachable
Modules Health:                                          Stopped(0) Degraded(0) OK(35)


#  cilium-health status

Probe time:   2024-08-03T12:47:13Z
Nodes:
  kubernetes/ip-172-31-.ec2.internal (localhost):
    Host connectivity to 172.31.248.41:
      ICMP to stack:   OK, RTT=260.629µs
      HTTP to agent:   OK, RTT=274.696µs
    Endpoint connectivity to 10.200.0.71:
      ICMP to stack:   OK, RTT=253.859µs
      HTTP to agent:   Get "http://10.200.0.71:4240/hello": dial tcp 10.200.0.71:4240: connect: no route to host
      Secondary connectivity to 2600:[REDACTED]
        ICMP to stack:   OK, RTT=271.507µs
        HTTP to agent:   Get "http://[2600:[REDACTED]:4240/hello": dial tcp [2600:[REDACTED]:4240: connect: no route to host





➡️   Without setting the flag  --bpf.datapathMode=netkit 


ubuntu@ip-172-31-:~/cilium$ kpo

NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE   IP                             NODE                             
kube-system   cilium-6w2bm                       1/1     Running   0          54s   2600:[REDACTED]      ip-172-31.ec2.internal                
kube-system   cilium-envoy-62wpp                 1/1     Running   0          54s   2600:[REDACTED]      ip-172-31.ec2.internal                
kube-system   cilium-operator-7f579fc87d-jtnrj   1/1     Running   0          54s   2600:[REDACTED]       ip-172-31.ec2.internal                
👉️ kube-system   coredns-6d7ff78994-5gxdg           1/1     Running   0          2s    2600:[REDACTED]       ip-172-31.ec2.internal   


 ubuntu@ip-172-31-:~/cilium$ kubectl exec -it cilium-6w2bm -n kube-system /bin/sh

# cilium status

KVStore:                 Ok   etcd: 2/2 connected, leases=1, lock leases=1, has-quorum=true: https://[2600:[REDACTED]]:2379 - 3.4.5 (Leader); https://[2600:1[REDACTED]]:2379 - 3.4.5
Kubernetes:              Ok   1.30 (v1.30.0) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumNetworkPolicy", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    True   [enX0    172.31. 2600:[REDACTED] fe80::[REDACTED] (Direct Routing)]
Host firewall:           Disabled
SRv6:                    Disabled
CNI Chaining:            none
CNI Config file:         successfully wrote CNI configuration file to /host/etc/cni/net.d/05-cilium.conflist
Cilium:                  Ok   1.16.0 (v1.16.0-82999990)
NodeMonitor:             Listening for events on 15 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok   
IPAM:                    IPv4: 3/254 allocated from 10.200.0.0/24, IPv6: 3/254 allocated from 2600:[REDACTED]::/120
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Routing:                 Network: Native   Host: BPF
Attach Mode:             TCX
Device Mode:             veth
Masquerading:            BPF   [enX0]   10.200.0.0/16 [IPv4: Enabled, IPv6: Enabled]
Controller Status:       33/33 healthy
Proxy Status:            OK, ip 10.200.0.233, 0 redirects active on ports 10000-20000, Envoy: external
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 3881/4095 (94.77%), Flows/s: 27.46   Metrics: Disabled
Encryption:              Disabled        
Cluster health:          1/1 reachable   (2024-08-03T13:04:12Z)
Modules Health:          Stopped(0) Degraded(0) OK(35)

# cilium-health status
Probe time:   2024-08-03T13:05:12Z
Nodes:
  kubernetes/ip-172-31-.ec2.internal (localhost):
    Host connectivity to 172.31.:
      ICMP to stack:   OK, RTT=371.273µs
      HTTP to agent:   OK, RTT=270.244µs
    Endpoint connectivity to 10.200.0.179:
      ICMP to stack:   OK, RTT=304.395µs
      HTTP to agent:   OK, RTT=1.741856ms



➡️   When using cilium version 15.4 and native routing BPF 

ubuntu@ip-172-31-:~/cilium$ kpo

NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE   IP                             NODE     
kube-system   cilium-65gzl                       1/1     Running   0          75s    2600:[REDACTED]        ip-172-31.ec2.internal              
kube-system   cilium-operator-77897cfd6f-zqs57   1/1     Running   0          75s    2600:[REDACTED]        ip-172-31.ec2.internal              
kube-system   coredns-6d7ff78994-9txr4           1/1     Running   0          5s     2600:[REDACTED]        ip-172-31.ec2.internal              

 ubuntu@ip-172-31-:~/cilium$ kubectl exec -it cilium-65gzl -n kube-system /bin/sh

# cilium status

KVStore:                 Ok   etcd: 2/2 connected, leases=1, lock leases=1, has-quorum=true: https://[2600:[REDACTED]]:2379 - 3.4.5; https://[2600:1[REDACTED]]:2379 - 3.4.5 (Leader)
Kubernetes:              Ok   1.30 (v1.30.0) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumNetworkPolicy", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    Strict   [enX0    172.31.248.41  2600:[REDACTED] fe80::[REDACTED] (Direct Routing)]
Host firewall:           Disabled
SRv6:                    Disabled
CNI Chaining:            none
Cilium:                  Ok   1.15.4 (v1.15.4-9b3f9a8c)
NodeMonitor:             Listening for events on 15 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok   
IPAM:                    IPv4: 3/254 allocated from 10.200.0.0/24, IPv6: 3/254 allocated from 2600:[REDACTED]::/120
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Host Routing:            BPF
Masquerading:            BPF   [enX0]   10.200.0.0/16 [IPv4: Enabled, IPv6: Enabled]
Controller Status:       32/32 healthy
Proxy Status:            OK, ip 10.200.0.233, 0 redirects active on ports 10000-20000, Envoy: embedded
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 3459/4095 (84.47%), Flows/s: 24.48   Metrics: Disabled
Encryption:              Disabled        
Cluster health:          1/1 reachable   (2024-08-03T12:52:42Z)
Modules Health:          Stopped(0) Degraded(0) OK(11) Unknown(3)

# cilium-health status

Probe time:   2024-08-03T12:52:42Z
Nodes:
  kubernetes/ ip-172-31.ec2.internal (localhost):
    Host connectivity to 172.31.248.41:
      ICMP to stack:   OK, RTT=343.732µs
      HTTP to agent:   OK, RTT=228.478µs
    Endpoint connectivity to 10.200.0.179:
      ICMP to stack:   OK, RTT=358.021µs
      HTTP to agent:   OK, RTT=416.495µs

**Comment by superzhu** [comment]
@Lakers817 for the coredns timeout issue, version 1.15.4 does not support netkit yet, version 1.16.0 support it, with following configuration, no coredns timeout issue
```
routingMode: "native"
# -- Allows to explicitly specify the IPv4 CIDR for native routing.
ipv4NativeRoutingCIDR: "10.1.0.0/16"
enableIPv4Masquerade: true
autoDirectNodeRoutes: true
enableCiliumEndpointSlice: false
endpointRoutes:
  enabled: true

bpf:
  masquerade: true
  datapathMode: netkit
```
  But if change to 
  ```
endpointRoutes:
  enabled: false
```
will see Coredns timeout issue, cannot access Kubernetes service
