### ISSUE TITLE
Cannot forward proxied DNS lookup; bind: address already in use

### ISSUE THREAD

**Issue by drinnits** [cilium/cilium#33912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.15.7 and lower than v1.16.0

### What happened?

After upgrading cilium from 1.14.5 to 1.15.6 (and later 1.15.7) we see several error entries in cilium-agent pods like this.
```
time="2024-07-19T10:59:10Z" level=error msg="Cannot forward proxied DNS lookup" DNSRequestID=24675 dnsName=alertmanager.tmi.ct.company.prod.dom. endpointID=1544 error="failed to dial connection to 10.0.11.145:53: dial udp 10.0.13.39:42254->10.0.11.145:53: bind: address already in use" identity=16684 ipAddr="10.0.13.39:42254" subsys=fqdn/dnsproxy
```
It does not break our running environment but fills our log with errors.

### How can we reproduce the issue?

1. Install cilium with helm.
2. Use this values.

```yaml
certgen:
  image:
    pullPolicy: IfNotPresent
    repository: registry.co.company.prod.dom/quay.io/cilium/certgen
etcd:
  image:
    repository: registry.co.company.prod.dom/quay.io/cilium/cilium-etcd-operator
hubble:
  enabled: true
  eventQueueSize: "1024"
  metrics:
    enabled:
    - dns:query;ignoreAAAA
    - drop
    - tcp
    - flow
    - icmp
    - http
    serviceMonitor:
      enabled: true
      namespace: prometheus-operator
  relay:
    enabled: true
    image:
      repository: registry.co.company.prod.dom/quay.io/cilium/hubble-relay
  ui:
    backend:
      image:
        repository: registry.co.company.prod.dom/quay.io/cilium/hubble-ui-backend
    enabled: true
    frontend:
      image:
        repository: registry.co.company.prod.dom/quay.io/cilium/hubble-ui
      server:
        ipv6:
          enabled: false
    ingress:
      annotations:
        kubernetes.io/ingress.class: ingress-admin
      enabled: true
      hosts:
      - hubble.txu.ct.company.prod.dom
    proxy:
      image:
        repository: registry.co.company.prod.dom/hub.docker.com/envoyproxy/envoy
image:
  repository: registry.co.company.prod.dom/quay.io/cilium/cilium
monitor:
  enabled: false
nodeinit:
  image:
    repository: registry.co.company.prod.dom/quay.io/cilium/startup-script
operator:
  image:
    repository: registry.co.company.prod.dom/quay.io/cilium/operator
  prometheus:
    enabled: true
    port: 6942
    serviceMonitor:
      enabled: true
      namespace: prometheus-operator
preflight:
  image:
    repository: registry.co.company.prod.dom/quay.io/cilium/cilium
prometheus:
  enabled: true
  metrics: null
  serviceMonitor:
    enabled: true
    namespace: prometheus-operator
```

### Cilium Version

1.15.6

### Kernel Version

Linux ctxu1203 5.4.0-182-generic #202-Ubuntu SMP Fri Apr 26 12:29:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.7", GitCommit:"c8dcb00be9961ec36d141d2e4103f85f92bcf291", GitTreeState:"clean", BuildDate:"2024-02-14T10:32:14Z", GoVersion:"go1.21.7", Compiler:"gc", Platform:"linux/amd64"}

### Regression

1.14.5

### Relevant log output

```shell
time="2024-07-19T10:59:10Z" level=error msg="Cannot forward proxied DNS lookup" DNSRequestID=24675 dnsName=alertmanager.tmi.ct.company.prod.dom. endpointID=1544 error="failed to dial connection to 10.0.11.145:53: dial udp 10.0.13.39:42254->10.0.11.145:53: bind: address already in use" identity=16684 ipAddr="10.0.13.39:42254" subsys=fqdn/dnsproxy
```
```


### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
