### ISSUE TITLE
Newly added node failing to start Cilium. Exit code 2 

### ISSUE THREAD

**Issue by alekc** [cilium/cilium#33924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0-rc.1 and lower than v1.17.0

### What happened?

While adding a new node to the existing cluster (with cilium network up and running without issue), cilium agent on that node fails to start up properly and exits with code 2. Can't see anything relevant in the logs

### How can we reproduce the issue?

Cluster is created by the kubeadm (accross several clouds linked with tailscale mesh). Cilium installed by helm chart

Cilium config 
```
bpf:
  hostLegacyRouting: false
kubeProxyReplacement: true
k8sServiceHost: 'k8s.xxx.dev'
k8sServicePort: '6443'
loadBalancer:
  algorithm: maglev
maglev:
  tableSize: 65521
  hashSeed: wBvj/Dor3gNERm8G
cluster:
  name: kubernetes
cni:
  customConf: false
  uninstall: false
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.247.0.0/16
operator:
  replicas: 1
  unmanagedPodWatcher:
    restart: true
policyEnforcementMode: default
routingMode: tunnel
tunnelPort: 8473
tunnelProtocol: vxlan

```

### Cilium Version

1.15.7

### Kernel Version

Linux ionos-gw 5.15.0-116-generic #126-Ubuntu SMP Mon Jul 1 10:14:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.28.12

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
