### ISSUE TITLE
Gateway API: envoy doesn't proxy traffic to pod on EKS setup with kube-proxy replacement

### ISSUE THREAD

**Issue by Anton-Sagurov** [cilium/cilium#33967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0-rc.2 and lower than v1.17.0

### What happened?

1. The cilium was installed on EKS cluster:
- EKS cluster created with tainted node group in a private subnets according to cilium [documentation](https://docs.cilium.io/en/latest/installation/k8s-install-helm/): 
  ```yaml
    taints:
   - key: "node.cilium.io/agent-not-ready"
     value: "true"
     effect: "NoExecute"
  ```
- The kube-proxy was removed from the K8s cluster and nodes were restarted (so there are no affected netfilter/iptables rules)
- aws-node DaemonSet was patched:
  ```bash
  kubectl -n kube-system patch daemonset aws-node --type='strategic' -p='{"spec":{"template":{"spec":{"nodeSelector":{"io.cilium/aws-node-enabled":"true"}}}}}'
  ```
- Gateway API CRDs was installed from the experimental [release](https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/experimental-install.yaml)
- The cilium was installed with this command:
  ```bash
  API_SERVER_IP=10.10.70.92
  API_SERVER_PORT=443

  helm -n kube-system upgrade --install cilium cilium/cilium --version=1.16.0-rc.2 \
    --namespace kube-system \
    --set cluster.name=cilium-poc-eu-central-1-lab \
    --set eni.enabled=true \
    --set ipam.mode=eni \
    --set egressMasqueradeInterfaces=eth0 \
    --set routingMode=native \
    --set kubeProxyReplacement=true \
    --set k8sServiceHost=${API_SERVER_IP} \
    --set k8sServicePort=${API_SERVER_PORT} \
    --set gatewayAPI.enabled=true \
    --set debug.enabled=true \
    --set debug.verbose=envoy
  ```
  ```bash
  ❯ kb get pods -n kube-system
   NAME                                            READY   STATUS    RESTARTS   AGE
   aws-load-balancer-controller-54bf87d75b-4lgdm   1/1     Running   0          21h
   aws-load-balancer-controller-54bf87d75b-z2vg2   1/1     Running   0          21h
   cilium-6n7rb                                    1/1     Running   0          4h45m
   cilium-9kcl8                                    1/1     Running   0          4h45m
   cilium-envoy-9db96                              1/1     Running   0          4h45m
   cilium-envoy-bjz76                              1/1     Running   0          4h45m
   cilium-operator-5d89f56d77-7qh64                1/1     Running   0          4h45m
   cilium-operator-5d89f56d77-8m2mw                1/1     Running   0          4h45m
   coredns-6f6d89bcc9-69ln4                        1/1     Running   0          23h
   coredns-6f6d89bcc9-vjdrc                        1/1     Running   0          23h
  ```
2. We are using the aws-load-balancer-controller version - v2.8.1 (latest stable)
3. I followed the HTTP Route example: https://docs.cilium.io/en/latest/network/servicemesh/gateway-api/http/
4. I'm getting 2 possible results:
    ```bash
    root@debug-container:/# curl --fail -s -v http://k8s-default-ciliumga-fd30db23c8-8e567ded6ae4b244.elb.eu-central- 1.amazonaws.com/details/1
    * Host k8s-default-ciliumga-fd30db23c8-8e567ded6ae4b244.elb.eu-central-1.amazonaws.com:80 was resolved.
    * IPv6: (none)
    * IPv4: 10.10.65.136, 10.10.69.68
    *   Trying 10.10.65.136:80...

    root@debug-container:/# curl --fail -s -v http://k8s-default-ciliumga-fd30db23c8-8e567ded6ae4b244.elb.eu-central-1.amazonaws.com/details/1
    * Host k8s-default-ciliumga-fd30db23c8-8e567ded6ae4b244.elb.eu-central-1.amazonaws.com:80 was resolved.
    * IPv6: (none)
    * IPv4: 10.10.69.68, 10.10.65.136
    *   Trying 10.10.69.68:80...
    * Connected to k8s-default-ciliumga-fd30db23c8-8e567ded6ae4b244.elb.eu-central-1.amazonaws.com (10.10.69.68) port 80
    > GET /details/1 HTTP/1.1
    > Host: k8s-default-ciliumga-fd30db23c8-8e567ded6ae4b244.elb.eu-central-1.amazonaws.com
    > User-Agent: curl/8.5.0
    > Accept: */*
    > 
    < HTTP/1.1 200 OK
    < content-type: application/json
    < server: envoy
    < date: Tue, 23 Jul 2024 07:45:23 GMT
    < content-length: 178
    < x-envoy-upstream-service-time: 2
    < 
    * Connection #0 to host k8s-default-ciliumga-fd30db23c8-8e567ded6ae4b244.elb.eu-central-1.amazonaws.com left intact
    {"id":1,"author":"William Shakespeare","year":1595,"type":"paperback","pages":200,"publisher":"PublisherA","language":"English","ISBN-10":"1234567890","ISBN-13":"123-1234567890"} 
    ```
  - Either infinite trying to connect
  - Either successful response
5. I have my own simple example with the same issue:

    <details>
      <summary>Example With simple http server</summary>

      ```yaml
      ---
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: nginx-hello-config
        namespace: gwtest
      data:
        hello.conf: |
          server {
              listen 80;
              server_name localhost;
      
              location /hello {
                  alias /usr/share/nginx/html/index.html; 
              }
          
              error_page 404 /404.html;
              location = /404.html {
                  internal;
              }
          }
      ---
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: hello-page 
        namespace: gwtest
      data:
        index.html: |
      
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Hello Page</title>
          </head>
          <body>
              <h1>Hello, World!</h1>
              <p>Welcome to the Hello Page!</p>
          </body>
          </html>
      ---
      apiVersion: apps/v1
      kind: Deployment 
      metadata:
        name: simple-web-server
        namespace: gwtest
      spec:
        replicas: 1
        progressDeadlineSeconds: 600
        revisionHistoryLimit: 10
        selector:
          matchLabels:
            app: simple-web-server
        strategy:
          rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
          type: RollingUpdate
        template:
          metadata:
            creationTimestamp: null
            labels:
              app: simple-web-server
          spec:
            volumes:
            - name: nginx-hello-config
              configMap:
                name: nginx-hello-config
            - name: hello-page
              configMap:
                name: hello-page
            initContainers:
            - name: init-myservice
              image: busybox:1.28
              command: ['sh', '-c', "mkdir -p /usr/share/nginx/html/hello"]
            containers:
            - image: nginx:stable-perl
              imagePullPolicy: IfNotPresent
              name: web-server 
              ports:
              - containerPort: 80
                protocol: TCP
                name: http-nginx
              volumeMounts:
              - name: nginx-hello-config
                mountPath: /etc/nginx/conf.d/hello.conf
                subPath: hello.conf
              - name: hello-page
                mountPath: /usr/share/nginx/html/hello
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: simple-web-server
        namespace: gwtest
      spec:
        selector:
          app: simple-web-server
        type: ClusterIP
        internalTrafficPolicy: Local 
        ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: http-nginx
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: external-simple-web-server
        namespace: gwtest
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      spec:
        selector:
          app: simple-web-server
        type: LoadBalancer 
        internalTrafficPolicy: Cluster
        ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: http-nginx
      ---
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: http-nginx
        namespace: gwtest
      spec:
        parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: gateway
          namespace: gwtest
        rules:
        - backendRefs:
          - name: simple-web-server 
            port: 80 
          matches:
          - path:
              type: PathPrefix
              value: /hello
      ---
      apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      metadata:
        name: gateway 
        namespace: gwtest
      spec:
        infrastructure:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
            service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        gatewayClassName: cilium
        listeners:
        - name: http
          port: 80
          protocol: HTTP
          allowedRoutes:
            namespaces:
              from: Same 
      ```
    </details>

6. The result with my simple example:
    - 3 Services created:
    ```bash
    ❯ kb get svc -n gwtest
     NAME                         TYPE           CLUSTER-IP       EXTERNAL-IP                                                                      PORT(S)        AGE
     cilium-gateway-gateway       LoadBalancer   172.20.35.43     k8s-gwtest-ciliumga-7c276eb898-d0b28931870afa56.elb.eu-central-1.amazonaws.com   80:32529/TCP   4h24m
     external-simple-web-server   LoadBalancer   172.20.197.246   k8s-gwtest-external-f87c913f46-876fc372b3a6a045.elb.eu- central-1.amazonaws.com   80:30875/TCP   21h
     simple-web-server            ClusterIP      172.20.145.238   <none>                                                                           80/TCP         175m
    ```
    - External Service works fine:
    ```bash
    ❯ curl http://k8s-gwtest-external-f87c913f46-876fc372b3a6a045.elb.eu-central-1.amazonaws.com/hello/

    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Hello Page</title>
    </head>
    <body>
      <h1>Hello, World!</h1>
      <p>Welcome to the Hello Page!</p>
    </body>
    </html>
    ```
    - The gateway LoadBalancer gives 2 different result depending on what host was selected to connect:
    ```bash
    ❯ curl http://k8s-gwtest-ciliumga-7c276eb898-d0b28931870afa56.elb.eu-central-1.amazonaws.com/hello/

    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello Page</title>
    </head>
    <body>
       <h1>Hello, World!</h1>
       <p>Welcome to the Hello Page!</p>
    </body>
    </html>
    
    ❯ curl -v http://k8s-gwtest-ciliumga-7c276eb898-d0b28931870afa56.elb.eu-central-1.amazonaws.com/hello/
    * Host k8s-gwtest-ciliumga-7c276eb898-d0b28931870afa56.elb.eu-central-1.amazonaws.com:80 was resolved.
    * IPv6: (none)
    * IPv4: 52.29.178.81, 18.158.135.213
    *   Trying 52.29.178.81:80...
    * Connected to k8s-gwtest-ciliumga-7c276eb898-d0b28931870afa56.elb.eu-central-1.amazonaws.com (52.29.178.81) port 80
    > GET /hello/ HTTP/1.1
    > Host: k8s-gwtest-ciliumga-7c276eb898-d0b28931870afa56.elb.eu-central-1.amazonaws.com
    > User-Agent: curl/8.6.0
    > Accept: */*
    > 
    < HTTP/1.1 503 Service Unavailable
    < content-length: 19
    < content-type: text/plain
    < date: Tue, 23 Jul 2024 11:21:28 GMT
    < server: envoy
    < 
    * Connection #0 to host k8s-gwtest-ciliumga-7c276eb898-d0b28931870afa56.elb.eu-central-1.amazonaws.com left intact
    no healthy upstream% 
    ```

 7. Conclusion
    - As you may see I deploy 2 services: `external-simple-web-server` and `service.yaml`
    - The `external-simple-web-server` has type - **LoadBalancer** so the NLB is created for it with **internet-facing** scheme
    - The `simple-web-server` has type - **ClusterIP** and the HTTPRoute will use it as a **backendRef**
    
    **Here is the key difference** between gateway created service and `external-simple-web-server` LoadBalancer:  
    The Gateway created LoadBalancer:
    ![image](https://github.com/user-attachments/assets/d4b50493-6d3f-43b6-b05a-ac706e20db70)
    The external service created Load Balancer:
    ![image](https://github.com/user-attachments/assets/980e1594-6df0-4f25-a0ed-826be3c5afb8)

    **For some reason the envoy doesn't send the traffic to the node where the pod is running, but returns the 503 http code.**

    

### How can we reproduce the issue?

1. Follow the instruction to bootstrap an EKS cluster version 1.30: https://docs.cilium.io/en/latest/installation/k8s-install-helm/
2. Install Cilium version 1.16.0-rc.2
  ```bash
  kubectl apply -f gateway_crd/experimental-install.yaml
  
  kubectl -n kube-system patch daemonset aws-node --type='strategic' -p='{"spec":{"template":{"spec":{"nodeSelector":{"io.cilium/aws-node-enabled":"true"}}}}}'

  API_SERVER_IP=<internal_api_ip_address>
  API_SERVER_PORT=<port>

  helm -n kube-system upgrade --install cilium cilium/cilium --version=1.16.0-rc.2 \
    --namespace kube-system \
    --set cluster.name=cilium-poc-eu-central-1-lab \
    --set eni.enabled=true \
    --set ipam.mode=eni \
    --set egressMasqueradeInterfaces=eth0 \
    --set routingMode=native \
    --set kubeProxyReplacement=true \
    --set k8sServiceHost=${API_SERVER_IP} \
    --set k8sServicePort=${API_SERVER_PORT} \
    --set gatewayAPI.enabled=true \
    --set debug.enabled=true \
    --set debug.verbose=envoy
  ```
3. Prepare the AWS Load Balancer Controller serviceAccount:
    ```yaml
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: <AWS_IAM_ROLE_ARN_TO_ASSUME>
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: aws-load-balancer-controller
    name: aws-load-balancer-controller
    namespace: kube-system
    ```
4. Create AWS_IAM_ROLE_ARN_TO_ASSUME:
    <details>
      <summary>Trust Policy</summary>
      
      ```json
      {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Federated": "arn:aws:iam::734708892259:oidc-provider/oidc.eks.eu-central-1.amazonaws.com/id/F95922A0B1E6C50AD4380AF68BFD516F"
                },
                "Action": "sts:AssumeRoleWithWebIdentity",
                "Condition": {
                    "StringEquals": {
                        "oidc.eks.eu-central-1.amazonaws.com/id/F95922A0B1E6C50AD4380AF68BFD516F:sub": "system:serviceaccount:kube-system:aws-load-balancer-controller"
                    }
                }
            }
        ]
      }
      ```
    </details>

    <details>
      <summary>Policy</summary>

      ```json
      {
        "Statement": [
          {
            "Action": [
              "iam:CreateServiceLinkedRole",
              "elasticloadbalancing:DescribeTargetHealth",
              "elasticloadbalancing:DescribeTargetGroups",
              "elasticloadbalancing:DescribeTargetGroupAttributes",
              "elasticloadbalancing:DescribeTags",
              "elasticloadbalancing:DescribeSSLPolicies",
              "elasticloadbalancing:DescribeRules",
              "elasticloadbalancing:DescribeLoadBalancers",
              "elasticloadbalancing:DescribeLoadBalancerAttributes",
              "elasticloadbalancing:DescribeListeners",
              "elasticloadbalancing:DescribeListenerCertificates",
              "elasticloadbalancing:AddTags",
              "ec2:GetCoipPoolUsage",
              "ec2:DescribeVpcs",
              "ec2:DescribeTags",
              "ec2:DescribeSubnets",
              "ec2:DescribeSecurityGroups",
              "ec2:DescribeNetworkInterfaces",
              "ec2:DescribeInternetGateways",
              "ec2:DescribeInstances",
              "ec2:DescribeCoipPools",
              "ec2:DescribeAvailabilityZones",
              "ec2:DescribeAddresses",
              "ec2:DescribeAccountAttributes"
            ],
            "Effect": "Allow",
            "Resource": "*"
          },
          {
            "Action": [
              "wafv2:GetWebACLForResource",
              "wafv2:GetWebACL",
              "wafv2:DisassociateWebACL",
              "wafv2:AssociateWebACL",
              "waf-regional:GetWebACLForResource",
              "waf-regional:GetWebACL",
              "waf-regional:DisassociateWebACL",
              "waf-regional:AssociateWebACL",
              "shield:GetSubscriptionState",
              "shield:DescribeProtection",
              "shield:DeleteProtection",
              "shield:CreateProtection",
              "iam:ListServerCertificates",
              "iam:GetServerCertificate",
              "cognito-idp:DescribeUserPoolClient",
              "acm:ListCertificates",
              "acm:DescribeCertificate"
            ],
            "Effect": "Allow",
            "Resource": "*"
          },
          {
            "Action": [
              "ec2:RevokeSecurityGroupIngress",
              "ec2:AuthorizeSecurityGroupIngress"
            ],
            "Effect": "Allow",
            "Resource": "*"
          },
          {
            "Action": "ec2:CreateSecurityGroup",
            "Effect": "Allow",
            "Resource": "*"
          },
          {
            "Action": "ec2:CreateTags",
            "Condition": {
              "Null": {
                "aws:RequestTag/elbv2.k8s.aws/cluster": "false"
              },
              "StringEquals": {
                "ec2:CreateAction": "CreateSecurityGroup"
              }
            },
            "Effect": "Allow",
            "Resource": "arn:aws:ec2:*:*:security-group/*"
          },
          {
            "Action": [
              "ec2:DeleteTags",
              "ec2:CreateTags"
            ],
            "Condition": {
              "Null": {
                "aws:RequestTag/elbv2.k8s.aws/cluster": "true",
                "aws:ResourceTag/elbv2.k8s.aws/cluster": "false"
              }
            },
            "Effect": "Allow",
            "Resource": "arn:aws:ec2:*:*:security-group/*"
          },
          {
            "Action": [
              "ec2:RevokeSecurityGroupIngress",
              "ec2:DeleteSecurityGroup",
              "ec2:AuthorizeSecurityGroupIngress"
            ],
            "Condition": {
              "Null": {
                "aws:ResourceTag/elbv2.k8s.aws/cluster": "false"
              }
            },
            "Effect": "Allow",
            "Resource": "*"
          },
          {
            "Action": [
              "elasticloadbalancing:CreateTargetGroup",
              "elasticloadbalancing:CreateLoadBalancer"
            ],
            "Condition": {
              "Null": {
                "aws:RequestTag/elbv2.k8s.aws/cluster": "false"
              }
            },
            "Effect": "Allow",
            "Resource": "*"
          },
          {
            "Action": [
              "elasticloadbalancing:DeleteRule",
              "elasticloadbalancing:DeleteListener",
              "elasticloadbalancing:CreateRule",
              "elasticloadbalancing:CreateListener"
            ],
            "Effect": "Allow",
            "Resource": "*"
          },
          {
            "Action": [
              "elasticloadbalancing:RemoveTags",
              "elasticloadbalancing:AddTags"
            ],
            "Condition": {
              "Null": {
                "aws:RequestTag/elbv2.k8s.aws/cluster": "true",
                "aws:ResourceTag/elbv2.k8s.aws/cluster": "false"
              }
            },
            "Effect": "Allow",
            "Resource": [
              "arn:aws:elasticloadbalancing:*:*:targetgroup/*/*",
              "arn:aws:elasticloadbalancing:*:*:loadbalancer/net/*/*",
              "arn:aws:elasticloadbalancing:*:*:loadbalancer/app/*/*"
            ]
          },
          {
            "Action": [
              "elasticloadbalancing:RemoveTags",
              "elasticloadbalancing:AddTags"
            ],
            "Effect": "Allow",
            "Resource": [
              "arn:aws:elasticloadbalancing:*:*:listener/net/*/*/*",
              "arn:aws:elasticloadbalancing:*:*:listener/app/*/*/*",
              "arn:aws:elasticloadbalancing:*:*:listener-rule/net/*/*/*",
              "arn:aws:elasticloadbalancing:*:*:listener-rule/app/*/*/*"
            ]
          },
          {
            "Action": [
              "elasticloadbalancing:SetSubnets",
              "elasticloadbalancing:SetSecurityGroups",
              "elasticloadbalancing:SetIpAddressType",
              "elasticloadbalancing:ModifyTargetGroupAttributes",
              "elasticloadbalancing:ModifyTargetGroup",
              "elasticloadbalancing:ModifyLoadBalancerAttributes",
              "elasticloadbalancing:DeleteTargetGroup",
              "elasticloadbalancing:DeleteLoadBalancer"
            ],
            "Condition": {
              "Null": {
                "aws:ResourceTag/elbv2.k8s.aws/cluster": "false"
              }
            },
            "Effect": "Allow",
            "Resource": "*"
          },
          {
            "Action": [
              "elasticloadbalancing:RegisterTargets",
              "elasticloadbalancing:DeregisterTargets"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:elasticloadbalancing:*:*:targetgroup/*/*"
          },
          {
            "Action": [
              "elasticloadbalancing:SetWebAcl",
              "elasticloadbalancing:RemoveListenerCertificates",
              "elasticloadbalancing:ModifyRule",
              "elasticloadbalancing:ModifyListener",
              "elasticloadbalancing:AddListenerCertificates"
            ],
            "Effect": "Allow",
            "Resource": "*"
          }
        ],
        "Version": "2012-10-17"
      }
      ```

    </details>

6. Install AWS Load Balancer Controller: 
    ```bash
    helm install aws-load-balancer-controller eks/aws-load-balancer-controller --set clusterName=<clusterName> -n kube-system --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller
    ```
7. Run HTTP Route example: https://docs.cilium.io/en/latest/network/servicemesh/gateway-api/http/
8. In a namespace where example installed you will find these services:
    ```bash
    NAME                        TYPE           CLUSTER-IP       EXTERNAL-IP                                                                       PORT(S)        AGE
    cilium-gateway-my-gateway   LoadBalancer   172.20.7.113     k8s-default-ciliumga-fd30db23c8-8e567ded6ae4b244.elb.eu- 
    central-1.amazonaws.com   80:32514/TCP   3h21m
    details                     ClusterIP      172.20.147.24    <none>                                                                            9080/TCP       3h23m
    kubernetes                  ClusterIP      172.20.0.1       <none>                                                                            443/TCP        23h
    productpage                 ClusterIP      172.20.196.103   <none>                                                                            9080/TCP       3h23m
    ratings                     ClusterIP      172.20.226.248   <none>                                                                            9080/TCP       3h23m
    reviews                     ClusterIP      172.20.106.177   <none>                                                                            9080/TCP       3h23m
    ```
9. The NLB will be created with internal scheme, so you will need to deploy some container to be able to connect to the NLB hostname:
    ```yaml
    apiVersion: v1
    kind: Pod
    metadata:
      name: debug-container
    spec:
      containers:
      - name: debug-container
        image: "ubuntu:24.04"
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        args:
        - "120000"
    ```
10. Run 10-20 times command `curl http://$GATEWAY/details/1 | jq` - you will see the correct response and 503 http error from the envoy.

### Cilium Version

```
❯ cilium version
cilium-cli: v0.16.11 compiled with go1.22.4 on linux/amd64
cilium image (default): v1.15.6
cilium image (stable): v1.15.7
cilium image (running): 1.16.0-rc.2
```

### Kernel Version

6.1.94-99.176.amzn2023.x86_64 (Amazon Linux for EKS)

### Kubernetes Version

```
Server Version: version.Info{Major:"1", Minor:"30+", GitVersion:"v1.30.2-eks-db838b0", GitCommit:"04088714581f0ad0a9e2c81c6ecc36bdd30d4b53", GitTreeState:"clean", BuildDate:"2024-06-27T19:09:53Z", GoVersion:"go1.22.4", Compiler:"gc", Platform:"linux/amd64"}
```

### Anything else?

It looks like this issue might be related to my issue: https://github.com/cilium/cilium/issues/33906

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
