### ISSUE TITLE
BGPv2 Setting `CiliumBGPPeerConfig.transport` prevents connection establishment

### ISSUE THREAD

**Issue by juliusmh** [cilium/cilium#34016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

When specifying following `CiliumBGPPeerConfig`

```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  transport:
    peerPort: 179
  families:
    - afi: ipv4
      safi: unicast
```

Cilium is unable to establish a connection:

```
$ k -n kube-system exec cilium-6kvs9 -- cilium-dbg bgp peers
Local AS   Peer AS   Peer Address       Session   Uptime   Family         Received   Advertised
65001      65000     <redacted>:179   active    0s       ipv4/unicast   0          0
```

When removing the `spec.transport` object, or just `spec.transport.peerPort` 

```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
#  transport:
#    peerPort: 179
  families:
    - afi: ipv4
      safi: unicast
```

a connection can be established successfully:

```
$ k -n kube-system exec cilium-6kvs9 -- cilium-dbg bgp peers
Local AS   Peer AS   Peer Address       Session       Uptime   Family         Received   Advertised
65001      65000     <redacted>:179   established   6s       ipv4/unicast   0          0
```

As per the API, the default port should be 179 and from `cilium-dbg bgp peers` we can see that the peer address appears to be identical. 

What works:
- `transport: null`
- `transport: {localPort: 1024, peerPort: 179}`
- `transport: {localPort: 4444, peerPort: 179}`

What doesn't work:
- `transport: {}`
- `transport: {peerPort: 179}`
- `transport: {localPort: 179, peerPort: 179}`
- `transport: {localPort: 1023, peerPort: 179}`

There might be other reasons for why I can't use localPorts < 1024.

### How can we reproduce the issue?

1. Install cilium with
```
$ helm install cilium cilium/cilium --version 1.16 \
    --namespace kube-system \
    --set ipam.mode=cluster-pool \
    [...]
    --set bgpControlPlane.enabled=true \
    [...]
```

2. Configure BGP peers using
```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: test
spec:
  nodeSelector:
    matchLabels:
      topology.kubernetes.io/zone: eu-central-1c
  bgpInstances:
    - name: "test"
      localASN: 65001
      peers:
        - name: "test"
          peerASN: 65000
          peerAddress: <redacted>
          peerConfigRef:
            name: cilium-peer
```

and the config above.

### Cilium Version

1.16.0

### Kernel Version

5.10

### Kubernetes Version

v1.28.9-eks-036c24b

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Thanks for the detailed report. Would you be able to provide any error logs from Cilium with the bad configuration?

**Comment by juliusmh** [comment]
The cilium agent logs contain usual `info` level logs, e.g.:

```
[...]
time="2024-07-25T12:51:14Z" level=info msg="Registering BGP instance" instance=test subsys=bgp-control-plane
time="2024-07-25T12:51:14Z" level=info msg="Successfully registered BGP instance" instance=test subsys=bgp-control-plane
time="2024-07-25T12:51:15Z" level=info msg="Reconciling peers for instance" instance=test reconciler=Neighbor subsys=bgp-control-plane
time="2024-07-25T12:51:15Z" level=info msg="Adding peer" instance=test peer=cilium-peer reconciler=Neighbor subsys=bgp-control-plane
time="2024-07-25T12:51:15Z" level=info msg="Add a peer configuration" Key=<redacted> Topic=Peer asn=65001 component=gobgp.BgpServerInstance subsys=bgp-control-plane
time="2024-07-25T12:51:15Z" level=info msg="Neighbor soft reset out" Key=<redacted> Topic=Operation asn=65001 component=gobgp.BgpServerInstance subsys=bgp-control-plane
[...]
```

And this error when changing peer config but no prior connection was established:

```
time="2024-07-25T11:30:40Z" level=error msg="failed to close existing tcp connection" Key=<redacted> State=BGP_FSM_ACTIVE Topic=Peer asn=65000 component=gobgp.BgpServerInstance subsys=bgp-control-plane
```

Unfortunately I cannot provide you with a full `sysdump`.

**Comment by harsimran-pabla** [comment]
Hi @juliusmh, do you have a specific use case where setting local port is useful/required? 

If the local port is set manually, we encounter various issues (slow reconnect time, port bind errors etc). We are planning on removing this configuration option in the next release. It is marked as [deprecated in the main branch](https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/v2alpha1/bgp_peer_types.go#L127).

I will need to investigate these cases : 
```
transport: {}
transport: {peerPort: 179}
```

**Comment by juliusmh** [comment]
@harsimran-pabla we do not require a specific `localPort`, we were just toying with the available configuration options.

**Comment by harsimran-pabla** [comment]
Hi @juliusmh, I have been trying to reproduce this issue with [this lab](https://github.com/cilium/cilium/tree/main/contrib/containerlab/bgpv2/service) ( peer is FRR ) with the following transport configuration, but I have had no luck - peering is always successful.


One thing to note is that with the 1.16 version ( where the local port is not yet deprecated ), the default port of 179 will be configured when the structure is defined, but values are not set. 

```
transport: {}
transport: {peerPort: 179}
```

will be set as 
```
transport: {localPort:179, peerPort:179}
```

You can confirm this by checking `kubectl describe ciliumbgppeerconfigs.cilium.io/<peer-config-name>`.

It is no longer the case in latest change. If you think this is blocking you in some way and wants the fix to be backported to 1.16 let me know.

**Comment by YaroCabbage** [comment]
> deprecated in the main branch

I am currently trying to use BGP on the Vultr provider with Cilium. According to Vultr's [example](https://docs.vultr.com/high-availability-on-vultr-with-floating-ip-and-bgp), the provider communicates with a configurable node to transmit traffic, if I understood correctly.

While their example uses BIRD, I managed to use GoBGP in my experiments. It also required the ability to listen on port 179, meaning the node needed to have port 179 open for listening.

I've achieved some results with Cilium BGP, but after reading this issue, I am even more confused with what to do next. 

Here are the results I've achieved with Cilium:
- Addresses are issued from the address pool to services with the LoadBalancer type.<img width="389" alt="SCREEN2" src="https://github.com/user-attachments/assets/1c061d7e-a3c0-40a9-a3d0-3ec43869bdf3">
- BgpPeers are showing and established in the table, but received column is empty.<img width="987" alt="SCREEN1" src="https://github.com/user-attachments/assets/b7373b83-e183-49a6-a176-0a78fbf9e750">

When I tried setting a local port in BGP to listen on 179, the node disappeared from BgpPeers. As I understand, in the future it will not be possible to set up a local port. How, then, will it be possible to accomplish something like what Vultr suggests using BGP with Cilium?
<img width="977" alt="Снимок экрана 2024-08-07 в 17 56 54" src="https://github.com/user-attachments/assets/d3a01d09-558d-437f-a071-731be8a8b50b">

_If it helps, here are my configuration files:_
# ippool.yaml
```yaml
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lb-pool"
spec:
  blocks:
    - start: "95.179.134.40"
``` 
# bgp.yaml
```yaml
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      rack: rack0
  bgpInstances:
    - name: "instance-LOCALASNNUMBER"
      localASN: LOCALASNNUMBER
      peers:
        - name: "peer-A"
          peerASN: 64515
          peerAddress: 169.254.169.254
          peerConfigRef:
            name: "cilium-peer"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  authSecretRef: vultr-bgp-auth-secret

  gracefulRestart:
    enabled: true
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements-internal
  namespace: kube-system
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "PodCIDR"
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - { key: "service-type", operator: In, values: [ "internal" ] }
          - { key: somekey, operator: NotIn, values: [ 'never-used-value' ] }
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPNodeConfigOverride
metadata:
  name: vultr-worker1
spec:
  bgpInstances:
    - name: "instance-LOCALASNNUMBER"
      routerID: "199.247.31.65"
      localPort: 1790 # tried here to change to 179, but after that node disappeared from **BGP Peers** table
      peers:
        - name: "peer-A"
          localAddress: 169.254.169.254
``` 

Could you please clarify if the Vultr tutorial is a valid example for using the BGP feature with Cilium? I am struggling to reproduce the Vultr example and effectively use BGP with Cilium. 

[Here is the link to the Vultr tutorial on BGP](https://docs.vultr.com/high-availability-on-vultr-with-floating-ip-and-bgp)

Thank you!
