### ISSUE TITLE
An error occurred when enabling host network mode through Helm

### ISSUE THREAD

**Issue by jieshiyeskey** [cilium/cilium#34028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

 helm install cilium cilium -n kube-system
Error: INSTALLATION FAILED: 1 error occurred:
        * Service "cilium-ingress" is invalid: spec.externalTrafficPolicy: Invalid value: "Cluster": may only be set for externally-accessible services

### How can we reproduce the issue?

Turn on the following parameters, then install or update helm
ingressController:
  enabled: true
  hostNetwork:
    enabled: true

### Cilium Version

cilium-cli: v0.16.13 compiled with go1.22.5 on linux/amd64
cilium image (default): v1.15.6
cilium image (stable): v1.16.0
cilium image (running): 1.16.0

### Kernel Version

Linux cn-cp-1 6.6.0-34.0.0.41.oe2403.x86_64 #1 SMP Wed Jul 17 16:05:20 CST 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Whoops, we need to ignore the default ExternalTrafficPolicy when `ingressController.hostNetwork.enabled` is set.

As a quick workaround, you can set `ingressController.service.externalTrafficPolicy: ~` which should work.

**Comment by yellowhat** [comment]
@squeed 

I am using:

```yaml
ingressController:
  enabled: true
  default: true
  enforceHttps: true
  loadbalancerMode: dedicated
  service:
    externalTrafficPolicy: "~"
  # Configure the Envoy listeners to be exposed on the host network.
  hostNetwork:
    enabled: true
```

And getting:

```
execution error at (cilium/templates/validate.yaml:65:7): Cilium Ingress services of type 'LoadBalancer' or 'NodePort' need an externalTrafficPolicy set to 'Cluster' or 'Local'.
```

**Comment by yellowhat** [comment]
Logs from operator:

```console
time="2024-08-05T07:11:16Z"
level=error
msg="Reconciler error"
Ingress="{podinfo default}"
controller=ingresscontroller
Group=networking.k8s.io controller
Kind=Ingress
err
or="failed to create or update Service: Service \"cilium-ingress-podinfo\" is invalid: spec.externalTrafficPolicy: Invalid value: \"Cluster\": may only be set for externally-accessible services"
name=podinfo
namespace=default
reconcileID="\"bac56fb0-3368-4a43-a2c0-396a1d4d78e2\""
subsys=controller-runtime   
```

Even if I add the `annotations`:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo
  annotations:
    ingress.cilium.io/service-external-traffic-policy: Local
spec:
  ingressClassName: cilium
  rules:
    - host: <host>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: podinfo
                port:
                  name: http
```

```console
time="2024-08-05T07:13:02Z"
level=error
msg="Reconciler error"
Ingress="{podinfo default}"
controller=ingress
controllerGroup=networking.k8s.io
controllerKind=Ingress
err
or="failed to create or update Service: Service \"cilium-ingress-podinfo\" is invalid: spec.externalTrafficPolicy: Invalid value: \"Local\": may only be set for externally-accessible services"
name=podinfo
namespace=default
reconcileID="\"30bb5bd0-fe1d-479d-9c0a-e9c3f45be587\""
subsys=controller-runtime
```

or:

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo
  annotations:
    ingress.cilium.io/service-type: ClusterIP
    ingress.cilium.io/service-external-traffic-policy: Local
spec:
  ingressClassName: cilium
  rules:
    - host: <host>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: podinfo
                port:
                  name: http
```

```console
time="2024-08-05T07:15:14Z"
level=error
msg="Reconciler error"
Ingress="{podinfo default}"
controller=ingress
controllerGroup=networking.k8s.io
controllerKind=Ingress
err
or="failed to create or update Service: Service \"cilium-ingress-podinfo\" is invalid: spec.externalTrafficPolicy: Invalid value: \"Local\": may only be set for externally-accessible services"
name=podinfo
namespace=default
reconcileID="\"e9c79eeb-14ab-4c02-8ae7-214acb62cf40\""
subsys=controller-runtime
```

**Comment by willfindlay** [comment]
Hitting the same issue here with the same results as above when attempting the proposed workaround.

**Comment by yellowhat** [comment]
Still same error on 1.16.1

**Comment by nheimlich** [comment]
same issue for me as well ^

**Comment by willfindlay** [comment]
FWIW the following diff applied to the helm chart seems to enable the workaround proposed by @squeed.
```diff
diff --git a/install/kubernetes/cilium/templates/validate.yaml b/install/kubernetes/cilium/templates/validate.yaml
index 8bc687dbff..b7101df1a5 100644
--- a/install/kubernetes/cilium/templates/validate.yaml
+++ b/install/kubernetes/cilium/templates/validate.yaml
@@ -60,7 +60,7 @@
   {{- end }}
 {{- end }}

-{{- if and .Values.ingressController.enabled (or (eq .Values.ingressController.service.type "LoadBalancer") (eq .Values.ingressController.service.type "NodePort"))}}
+{{- if and .Values.ingressController.enabled (or (eq .Values.ingressController.service.type "LoadBalancer") (eq .Values.ingressController.service.type "NodePort")) (not .Values.ingressController.hostNetwork.enabled)}}
   {{- if not (or (eq .Values.ingressController.service.externalTrafficPolicy "Cluster") (eq .Values.ingressController.service.externalTrafficPolicy "Local")) }}
     {{ fail "Cilium Ingress services of type 'LoadBalancer' or 'NodePort' need an externalTrafficPolicy set to 'Cluster' or 'Local'." }}
   {{- end }}
```
With that patch, I can make the following values work:
```yaml
ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  hostNetwork:
    enabled: true
  service:
    type: LoadBalancer
    externalTrafficPolicy: "~"

```
Of course, given that this is just a workaround, it's probably not worth filing a PR for this. But you can apply this patch locally to unblock yourself.

**Comment by yellowhat** [comment]
@willfindlay after applying that patch, is the cilium-operator able to create actual services?

**Comment by willfindlay** [comment]
I'm using shared mode so it's just one service being created, but yes it works as expected for me.

**Comment by yellowhat** [comment]
Thanks for your suggestion.

Using your patch and:

```yaml
kubeProxyReplacement: true
k8sServiceHost: auto  # Value fetched from "cluster-info" ConfigMap in kube-public
ingressController:
  enabled: true
  default: true
  enforceHttps: false
  loadbalancerMode: shared
  hostNetwork:
    enabled: true
    sharedListenerPort: 8080
  service:
    # https://github.com/cilium/cilium/issues/34028
    externalTrafficPolicy: "~"
```

I am able to deploy the chart.

If I deploy a service and an ingress:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  labels:
    app: podinfo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: podinfo

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo
  annotations:
spec:
  ingressClassName: cilium
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: podinfo
                port:
                  name: http
```

```console
$ kubectl get svc
NAME         TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
podinfo      ClusterIP   10.3.179.26   <none>        8080/TCP   9m51s

$ kubectl get ingress
NAME      CLASS    HOSTS   ADDRESS   PORTS   AGE
podinfo   cilium   *                 80      9m53s

$ curl <public_ip>:8080
<works>
```

But the ingress ADDRESS is empty, this is a bit annoying if you set an host and use external-dns to update dns records.

**Comment by gelato** [comment]
Are there plans to merge this fix into the current Helmchart?

**Comment by Nenq** [comment]
still having the same issue on 1.16.3

**Comment by Toasterson** [comment]
This still happens in 1.16.4

**Comment by Toasterson** [comment]
Looking into the chart source code I also see why. 

https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/cilium-ingress-service.yaml#L26-L42

These lines add externalTrafficPolicy independent of the hostNetworkEnabled and if hostNetwork.enabled is true the type is defined as CluasterIP which is correct but according to k8s people incompatible with workaround. externalTrafficPolicy must evaluate to null so the if on line 40 removes the line altogether. The type ClusterIP is needed to workaround the validate check without a patch.

Something like this here works.
```
ingressController:
  service:
    externalTrafficPolicy: null
    type: ClusterIP
```

**Comment by backerman** [comment]
> Something like this here works.
> 
> ```
> ingressController:
>   service:
>     externalTrafficPolicy: null
>     type: ClusterIP
> ```

1.16.5 also fails OOB but this workaround still works.

**Comment by ThomasCardin** [comment]
Same problem. Using the chart version `1.17.0-pre.2`

**Comment by ktbvds** [comment]
same issue with helm chart 1.16.7

**Comment by parisnakitakejser** [comment]
> Looking into the chart source code I also see why.
> 
> https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/cilium-ingress-service.yaml#L26-L42
> 
> These lines add externalTrafficPolicy independent of the hostNetworkEnabled and if hostNetwork.enabled is true the type is defined as CluasterIP which is correct but according to k8s people incompatible with externalTrafficPolicy. as a workaround externalTrafficPolicy must evaluate to null so the if on line 40 removes the line altogether. The type ClusterIP is needed to workaround the validate check without a patch.
> 
> Something like this here works.
> 
> ```
> ingressController:
>   service:
>     externalTrafficPolicy: null
>     type: ClusterIP
> ```

Thanks, its still working in version 1.17.1 :)

**Comment by ullanar** [comment]
same here

**Comment by steadyk** [comment]
> Something like this here works.
> 
> ```
> ingressController:
>   service:
>     externalTrafficPolicy: null
>     type: ClusterIP
> ```

Setting `externalTrafficPolicy` to `null` seems to not work on my side. The policy was still present in the rendered Helm chart.

I've then used the following settings (based from the recommendations above):

```
ingressController:
  enabled: true
  default: true
  hostNetwork:
    enabled: true
  service:
    externalTrafficPolicy: "~"
    type: ClusterIP
```

This seems to work.

**Comment by sinner-** [comment]
hey @backerman @steadyk would you be able to help show an example of a working Service+Ingress definition? I can use your suggestion to get Cilium to deploy now but I can't get my Ingress to actually work :( 

I'm using: 

```
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: demo
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: demo
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: demo
spec:
  ingressClassName: cilium
  rules:
  - host: "app.example.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
---
``` 

but I can only hit the ClusterIP of the service :(

**Comment by steadyk** [comment]
Hey @sinner- , our current ingressController config looks like this:

```yaml
  ingressController:
    enabled: true
    default: true
    loadbalancerMode: shared
    hostNetwork:
      enabled: true
      sharedListenerPort: 80
    service:
      externalTrafficPolicy: "~"
      type: ClusterIP
```

Maybe this is helpful.

Also not sure if the host `app.example.com` is reachable without additional DNS configuration (e.g. via `/etc/hosts`).
We currently use the IP of our Kind cluster (via `nip.io`) for access (e.g. `example.<ip>.nip.io`).
