### ISSUE TITLE
gateway-api: GRPCRoute requires explicitly specifying methods names for gRPC routes to work

### ISSUE THREAD

**Issue by rauanmayemir** [cilium/cilium#34079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

`GRPCRoute` doesn’t support this kind of matching:
```
  rules:
    - matches:
        - method:
            service: package.name.version.Service
```

requests will fail with `Unimplemented (12): unknown service`.  `GRPCRoute` expects us to explicitly list methods like:
```
  rules:
    - matches:
        - method:
            service: package.name.version.Service
            method: SomeMethodName
        - method:
            service: package.name.version.Service
            method: AnotherMethodName
```

### How can we reproduce the issue?

Use any GRPCRoute without specifying `method` in a match rule.

### Cilium Version

any

### Kernel Version

any

### Kubernetes Version

any

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
