### ISSUE TITLE
Daemon Failing to Start on Bottlerocket Nodes

### ISSUE THREAD

**Issue by Alex-Waring** [cilium/cilium#34084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.15.7 and lower than v1.16.0

### What happened?

I'm running cilium on bottlerocket nodes and on startup the agents fail with the following:

```
level=info msg="Removed map pin at /sys/fs/bpf/tc/globals/cilium_ipcache, recreating and re-pinning map cilium_ipcache" file-path=/sys/fs/bpf/tc/globals/cilium_ipcache name=cilium_ipcache subsys=bpf
level=error msg="error while opening/creating BPF maps" error="initializing conntrack map cilium_ct4_global: creating map: map create: cannot allocate memory (without BTF k/v)" subsys=daemon
level=error msg="Start hook failed" error="daemon creation failed: error while opening/creating BPF maps: initializing conntrack map cilium_ct4_global: creating map: map create: cannot allocate memory (without BTF k/v)" function="cmd.newDaemonPromise.func1 (cmd/daemon_main.go:1685)" subsys=hive
level=info msg=Stopping subsys=hive
```

The nodes have some additional hardening with https://aws.amazon.com/blogs/containers/validating-amazon-eks-optimized-bottlerocket-ami-against-the-cis-benchmark/

I found https://github.com/cilium/cilium/issues/30437, but I don't see any memory issues

### How can we reproduce the issue?

1. Create a bootstrap container for bottlerocket as per https://aws.amazon.com/blogs/containers/validating-amazon-eks-optimized-bottlerocket-ami-against-the-cis-benchmark/, I've made a few changes to use alpine, and not use iptables-legacy
2. Deploy an EKS cluster on 1.29
3. Create a managed node group with the following settings:

```
# https://github.com/bottlerocket-os/bottlerocket/blob/develop/README.md#description-of-settings
[settings.kubernetes]
api-server = "${endpoint}"
cluster-certificate = "${cluster_auth_base64}"
cluster-name = "${cluster_name}"

# Enable kernel lockdown in "integrity" mode.
# This prevents modifications to the running kernel, even by privileged users.
[settings.kernel]
lockdown = "integrity"

[settings.kernel.modules.udf]
allowed = false

[settings.kernel.modules.sctp]
allowed = false

[settings.kernel.sysctl]
"net.ipv4.conf.all.send_redirects" = "0"
"net.ipv4.conf.default.send_redirects" = "0"
"net.ipv4.conf.all.accept_redirects" = "0"
"net.ipv4.conf.default.accept_redirects" = "0"
"net.ipv6.conf.all.accept_redirects" = "0"
"net.ipv6.conf.default.accept_redirects" = "0"
"net.ipv4.conf.all.secure_redirects" = "0"
"net.ipv4.conf.default.secure_redirects" = "0"
"net.ipv4.conf.all.log_martians" = "1"
"net.ipv4.conf.default.log_martians" = "1"

[settings.bootstrap-containers.cis-hardening]
source = "${bootstrap_image}"
mode = "always"
```
4. Deploy cilium with the following helm chart settings:
```
cni:
  chainingMode: aws-cni
  exclusive: false
bpf:
  ctTcpMax: "4194304"
  mapDynamicSizeRatio: "0.05"
  policyMapMax: "32768"
enableIPv4Masquerade: false
routingMode: "native"
endpointRoutes:
  enabled: true
hubble:
  metrics:
    enabled:
      - dns
      - "drop:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction;sourceContext=app|workload-name|reserved-identity|pod-name;destinationContext=app|workload-name|reserved-identity|pod-name"
      - "tcp:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction;sourceContext=app|workload-name|reserved-identity|pod-name;destinationContext=app|workload-name|reserved-identity|pod-name"
      - "flow:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction;sourceContext=app|workload-name|reserved-identity|pod-name;destinationContext=app|workload-name|reserved-identity|pod-name"
      - "httpV2:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction;sourceContext=app|workload-name|reserved-identity|pod-name;destinationContext=app|workload-name|reserved-identity|pod-name"
  relay:
    enabled: true
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
  tls:
    auto:
      enabled: true
      method: helm
prometheus:
  enabled: true
operator:
  prometheus:
    enabled: true
  replicas: 3
  topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          io.cilium/app: operator
      maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  extraArgs: ["--pod-restart-selector="]
endpointStatus:
  enabled: true
  status: policy
dnsProxy:
  endpointMaxIpPerHostname: "4000"
  idleConnectionGracePeriod: "20s"
  proxyResponseMaxDelay: "500ms"
  minTtl: 3600
resources:
  limits:
    cpu: 600m
    memory: 512Mi
  requests:
    cpu: 75m
    memory: 128Mi
envoy:
  enabled: true
  resources:
  limits:
    cpu: 600m
    memory: 512Mi
  requests:
    cpu: 75m
    memory: 128Mi
```

### Cilium Version

1.15.3

### Kernel Version

6.1

### Kubernetes Version

1.29.4-eks-036c24b

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell
level=info msg="Start hook executed" duration="3.11µs" function="*resource.resource[*k8s.Endpoints].Start" subsys=hive                                                                                                                                                                           │
│ level=info msg="Start hook executed" duration="42.11µs" function="*resource.resource[*v1.Pod].Start" subsys=hive                                                                                                                                                                                 │
│ level=info msg="Start hook executed" duration="2.8µs" function="*resource.resource[*v1.Namespace].Start" subsys=hive                                                                                                                                                                             │
│ level=info msg="Start hook executed" duration="89.482µs" function="*resource.resource[*v1.NetworkPolicy].Start" subsys=hive                                                                                                                                                                      │
│ level=info msg="Start hook executed" duration="2.65µs" function="*resource.resource[*cilium.io/v2.CiliumNetworkPolicy].Start" subsys=hive                                                                                                                                                        │
│ level=info msg="Start hook executed" duration="3.06µs" function="*resource.resource[*cilium.io/v2.CiliumClusterwideNetworkPolicy].Start" subsys=hive                                                                                                                                             │
│ level=info msg="Start hook executed" duration="12.721µs" function="*resource.resource[*cilium.io/v2alpha1.CiliumCIDRGroup].Start" subsys=hive                                                                                                                                                    │
│ level=info msg="Start hook executed" duration="33.45µs" function="*resource.resource[*cilium.io/v2alpha1.CiliumEndpointSlice].Start" subsys=hive                                                                                                                                                 │
│ level=info msg="Start hook executed" duration="8.37µs" function="*cell.reporterHooks.Start" subsys=hive                                                                                                                                                                                          │
│ level=info msg="Start hook executed" duration="108.881µs" function="*manager.manager.Start" subsys=hive                                                                                                                                                                                          │
│ level=info msg="Start hook executed" duration=910ns function="k8s.newServiceCache.func1 (pkg/k8s/service_cache.go:144)" subsys=hive                                                                                                                                                              │
│ level=info msg="Serving cilium node monitor v1.2 API at unix:///var/run/cilium/monitor1_2.sock" subsys=monitor-agent                                                                                                                                                                             │
│ level=info msg="Start hook executed" duration="342.145µs" function="agent.newMonitorAgent.func1 (pkg/monitor/agent/cell.go:61)" subsys=hive                                                                                                                                                      │
│ level=info msg="Start hook executed" duration="2.52µs" function="*resource.resource[*cilium.io/v2alpha1.CiliumL2AnnouncementPolicy].Start" subsys=hive                                                                                                                                           │
│ level=info msg="Start hook executed" duration="3.87µs" function="*cell.reporterHooks.Start" subsys=hive                                                                                                                                                                                          │
│ level=info msg="Start hook executed" duration="8µs" function="*job.group.Start" subsys=hive                                                                                                                                                                                                      │
│ level=info msg="Start hook executed" duration="169.222µs" function="envoy.newEnvoyAccessLogServer.func1 (pkg/envoy/cell.go:107)" subsys=hive                                                                                                                                                     │
│ level=info msg="Envoy: Starting access log server listening on /var/run/cilium/envoy/sockets/access_log.sock" subsys=envoy-manager                                                                                                                                                               │
│ level=info msg="Start hook executed" duration="101.242µs" function="envoy.newArtifactCopier.func1 (pkg/envoy/cell.go:178)" subsys=hive                                                                                                                                                           │
│ level=info msg="Start hook executed" duration="308.244µs" function="envoy.newEnvoyXDSServer.func1 (pkg/envoy/cell.go:65)" subsys=hive                                                                                                                                                            │
│ level=info msg="Start hook executed" duration="3.381µs" function="*cell.reporterHooks.Start" subsys=hive                                                                                                                                                                                         │
│ level=info msg="Envoy: Starting xDS gRPC server listening on /var/run/cilium/envoy/sockets/xds.sock" subsys=envoy-manager                                                                                                                                                                        │
│ level=info msg="Start hook executed" duration="262.524µs" function="signal.provideSignalManager.func1 (pkg/signal/cell.go:25)" subsys=hive                                                                                                                                                       │
│ level=info msg="Datapath signal listener running" subsys=signal                                                                                                                                                                                                                                  │
│ level=info msg="Start hook executed" duration="945.253µs" function="auth.registerAuthManager.func1 (pkg/auth/cell.go:112)" subsys=hive                                                                                                                                                           │
│ level=info msg="Start hook executed" duration="7.61µs" function="auth.registerGCJobs.func1 (pkg/auth/cell.go:162)" subsys=hive                                                                                                                                                                   │
│ level=info msg="Start hook executed" duration="18.691µs" function="*job.group.Start" subsys=hive                                                                                                                                                                                                 │
│ level=info msg="Start hook executed" duration="3.19µs" function="*cell.reporterHooks.Start" subsys=hive                                                                                                                                                                                          │
│ level=info msg="Setting IPv6 gso_max_size to 65536 and gro_max_size to 65536" device=eth0 subsys=big-tcp                                                                                                                                                                                         │
│ level=info msg="Setting IPv6 gso_max_size to 65536 and gro_max_size to 65536" device=eth1 subsys=big-tcp                                                                                                                                                                                         │
│ level=info msg="Start hook executed" duration="481.537µs" function="bigtcp.newBIGTCP.func1 (pkg/datapath/linux/bigtcp/bigtcp.go:240)" subsys=hive                                                                                                                                                │
│ level=info msg="Start hook executed" duration="2.941µs" function="*cell.reporterHooks.Start" subsys=hive                                                                                                                                                                                         │
│ level=info msg="Start hook executed" duration="183.112µs" function="*ipsec.keyCustodian.Start" subsys=hive                                                                                                                                                                                       │
│ level=info msg="Start hook executed" duration="1µs" function="*job.group.Start" subsys=hive                                                                                                                                                                                                      │
│ level=info msg="Inheriting MTU from external network interface" device=eth0 ipAddr=10.217.7.24 mtu=9001 subsys=mtu                                                                                                                                                                               │
│ level=info msg="Start hook executed" duration="420.646µs" function="mtu.newForCell.func1 (pkg/mtu/cell.go:40)" subsys=hive                                                                                                                                                                       │
│ level=info msg="Using Managed Neighbor Kernel support" subsys=daemon                                                                                                                                                                                                                             │
│ level=info msg="Removed map pin at /sys/fs/bpf/tc/globals/cilium_ipcache, recreating and re-pinning map cilium_ipcache" file-path=/sys/fs/bpf/tc/globals/cilium_ipcache name=cilium_ipcache subsys=bpf                                                                                           │
│ level=error msg="error while opening/creating BPF maps" error="initializing conntrack map cilium_ct4_global: creating map: map create: cannot allocate memory (without BTF k/v)" subsys=daemon                                                                                                   │
│ level=error msg="Start hook failed" error="daemon creation failed: error while opening/creating BPF maps: initializing conntrack map cilium_ct4_global: creating map: map create: cannot allocate memory (without BTF k/v)" function="cmd.newDaemonPromise.func1 (cmd/daemon_main.go:1685)" subs │
│ ys=hive                                                                                                                                                                                                                                                                                          │
│ level=info msg=Stopping subsys=hive
```


### Anything else?

Bottlerocket version 1.20.4-b6163b2a
### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
