### ISSUE TITLE
AWS load balancer access log annotations do not have effect 

### ISSUE THREAD

**Issue by hongbo-miao** [cilium/cilium#34116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

I am using v1.1.0 experimental Gateway API CRDs:

```
https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
```

I am trying to enable load balancer access log:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: hm-gateway-api-gateway
  namespace: production-hm-gateway-api
  labels:
    app.kubernetes.io/name: hm-gateway-api-gateway
    app.kubernetes.io/part-of: production-hm-gateway-api
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      # https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/annotations
      # https://cloud-provider-aws.sigs.k8s.io/service_controller
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-xx,subnet-xx,subnet-xx,subnet-xx
      # New load balancer access log annotation
      service.beta.kubernetes.io/aws-load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=hm-kubernetes-load-balancer-log-archer,access_logs.s3.prefix=hm-gateway-api-gateway
      # Legacy load balancer access log annotation
      # service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: "5"
      # service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
      # service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: hm-kubernetes-load-balancer-log-archer
      # service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: hm-gateway-api-gateway
  listeners:
    - name: http
      protocol: HTTP
      hostname: "*.internal.mydomain.com"
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      hostname: "*.internal.mydomain.com"
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: staging-hm-gateway-api-certificate
            namespace: production-hm-gateway-api
```

I can confirm these annotations work well

```yaml
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-xx,subnet-xx,subnet-xx,subnet-xx
```

However, both new load balancer access log annotation

```yaml
      # New load balancer access log annotation
      service.beta.kubernetes.io/aws-load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=hm-kubernetes-load-balancer-log-archer,access_logs.s3.prefix=hm-gateway-api-gateway
```

and legacy load balancer access log annotation

```yaml
      # Legacy load balancer access log annotation
      service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: "5"
      service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: hm-kubernetes-load-balancer-log-archer
      service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: hm-gateway-api-gateway
```

do not work. 🥲

![image](https://github.com/user-attachments/assets/54ec551d-7884-44af-af0a-5f17354e4e7b)

### How can we reproduce the issue?

Here is my Cilium Helm values.yaml
```yaml
eni:
  enabled: true
ipam:
  mode: eni
egressMasqueradeInterfaces: eth0
routingMode: native
kubeProxyReplacement: true
k8sServiceHost: xxx.gr7.us-west-2.eks.amazonaws.com
k8sServicePort: 443
l7Proxy: true
gatewayAPI:
  enabled: true
  gatewayClass:
    create: "true"
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
```

### Cilium Version

```
➜ cilium version --helm-release-name=hm-cilium --namespace=production-hm-cilium
cilium-cli: v0.16.13 compiled with go1.22.5 on darwin/arm64
cilium image (default): v1.15.6
cilium image (stable): v1.16.0
cilium image (running): 1.16.0
```

### Kernel Version

(Hmm, I am not sure where I should run this `uname -a`, in cilium-operator pod in EKS cluster?)

### Kubernetes Version

```sh
➜ kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2-eks-db838b0
```

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
