### ISSUE TITLE
[BGP] cilium agent ignore services updated when using multiple BGP Instance (virtualRouters)

### ISSUE THREAD

**Issue by Jean-Daniel** [cilium/cilium#34146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

When deploying a BGP configuration with multiple instance on the same node, for instance, on bgp instance to advertise pod IPs, and on to advertise services, only the first instance detects the services changes. Other instances do no detect services update and do not update their configuration.

This bug it present in both `CiliumBGPPeeringPolicy` and `CiliumBGPClusterConfig` 

I'm using the BGPPeeringPolicy version here because it is simpler:

```yaml
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: 01-bgp-peering-policy
spec:
 nodeSelector:
   matchExpressions:
     - key: node-role
       operator: In
       values: [ storage ]
 virtualRouters:
 - localASN: 65101
   exportPodCIDR: true
   neighbors:
    - peerAddress: '10.0.1.1/32'
      peerASN: 65102
 - localASN: 65200
   neighbors:
    - peerAddress: '10.0.2.1/32'
      peerASN: 65201
   serviceSelector:
     matchLabels:
       group: internal
```

Using that configuration, any Service update will be ignored by the cilium-agent, and only forcing a full refresh will update advertised addresses for the second router.

Note: If the order of the routers is change to put the router exposing the service first, it works, as the first router/instance properly get the changes.

### How can we reproduce the issue?

Deploying a simple kind cluster with cilium and BGP.

```
cilium install \
    --version v1.16.0 \
    --set ipam.mode=kubernetes \
    --set tunnel=disabled \
    --set ipv4NativeRoutingCIDR="10.0.0.0/8" \
    --set bgpControlPlane.enabled=true \
    --set k8s.requireIPv4PodCIDR=true
```

Configure BGP advertisement to expose LoadBalancer pods. Setup some services, and see that the advertisements are not updated.

### Cilium Version

cilium v1.16.0

### Kernel Version

not relevant

### Kubernetes Version

reproduced at least on 1.29 and 1.30

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
