### ISSUE TITLE
Egress to host does not work with toEndpoints/toEntities specified in the egress policy

### ISSUE THREAD

**Issue by ashwinp** [cilium/cilium#3415]
### Title

Egress to host does not work with toEndpoints/toEntities specified in the egress policy

### General Information

- Cilium version (run `cilium version`)
`v0.13.20`

### How to reproduce the issue
Used the following policy to allow the prometheus client to talk to an application running on the host:
```
- endpointSelector:
    matchLabels:
      "k8s:app": prometheus
      "k8s:io.kubernetes.pod.namespace": monitoring
  egress:
  - toEntities:
    - host
  - toEndpoints:
    - matchLabels:
        {}
    toPorts:
    - ports:
      - port: "9100"
        protocol: TCP
      - port: "10251"
        protocol: TCP
      - port: "10252"
        protocol: TCP
      - port: "10255"
        protocol: TCP
```
The traffic is dropped (L3 deny verdict in `cilium monitor`).

From the `cilium endpoint get` output:
```
"policy": {
       "allowed-egress-identities": [],
       "allowed-ingress-identities": [
         1
],
```

**Comment by joestringer** [comment]
@ashwinp can you also add the `cilium endpoint get` portions for L4? The above is only L3, but it looks like you have L4 policies.

**Comment by ianvernon** [comment]
Looks like allowed-egress-identities isn't populated because that is only for label-based L3 (not L3-dependent-L4)

**Comment by ianvernon** [comment]
I created a similar policy locally:
```
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ cat policy.yaml 
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "lolpolicy"
metadata:
  name: "lol"
specs:
- endpointSelector:
    matchLabels:
      id: app1
      "k8s:io.kubernetes.pod.namespace": default
  egress:
  - toEndpoints:
    - matchLabels:
        "reserved:host": ""
    toPorts:
    - ports:
      - port: "9100"
        protocol: TCP
      - port: "10251"
        protocol: TCP
      - port: "10252"
        protocol: TCP
      - port: "10255"
        protocol: TCP
```

Endpoint list:
```
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ cilium endpoint list | grep app1
6458       Disabled           Enabled           1924       k8s:id=app1                                   f00d::a00:0:0:193a   10.0.16.218    ready   
25917      Disabled           Enabled           1924       k8s:id=app1                                   f00d::a00:0:0:653d   10.0.100.129   ready 
```

Policy JSON of `cilium endpoint get 6458`:
```
    "policy": {
      "allowed-egress-identities": [],
      "allowed-ingress-identities": [
        1
      ],
      "build": 21,
      "cidr-policy": {
        "egress": [],
        "ingress": []
      },
      "id": 1924,
      "l4": {
        "egress": [
          {
            "derived-from-rules": [
              [
                "unspec:io.cilium.k8s.policy.name=lol",
                "unspec:io.cilium.k8s.policy.namespace=default"
              ]
            ],
            "rule": {
   "port": 9100,
   "protocol": "TCP"
 }
          },
          {
            "derived-from-rules": [
              [
                "unspec:io.cilium.k8s.policy.name=lol",
                "unspec:io.cilium.k8s.policy.namespace=default"
              ]
            ],
            "rule": {
   "port": 10251,
   "protocol": "TCP"
 }
          },
          {
            "derived-from-rules": [
              [
                "unspec:io.cilium.k8s.policy.name=lol",
                "unspec:io.cilium.k8s.policy.namespace=default"
              ]
            ],
            "rule": {
   "port": 10252,
   "protocol": "TCP"
 }
          },
          {
            "derived-from-rules": [
              [
                "unspec:io.cilium.k8s.policy.name=lol",
                "unspec:io.cilium.k8s.policy.namespace=default"
              ]
            ],
            "rule": {
   "port": 10255,
   "protocol": "TCP"
 }
          }
        ],
        "ingress": []
      }
    },
    "policy-enabled": "egress",
```

**Comment by ianvernon** [comment]
After discussion with Ashwin, this is the issue we are seeing with importing such a policy:
```
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ cat policy2.yaml 
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "lolpolicy"
metadata:
  name: "lol"
specs:
- endpointSelector:
    matchLabels:
      id: app1
      "k8s:io.kubernetes.pod.namespace": default
  egress:
  - toEntities:
    - host
  - toEndpoints:
    - matchLabels:
        {}
    toPorts:
    - ports:
      - port: "9100"
        protocol: TCP
      - port: "10251"
        protocol: TCP
      - port: "10252"
        protocol: TCP
      - port: "10255"
        protocol: TCP
```

@ashwinp  says from his side, the expected behavior is that since the policy has an empty endpoint selector to `toEndpoints` traffic should be allowed to all endpoints in all namespaces from endpoints in namespace default with label app1. 

However, when the policy is imported, the wildcard selector is replaced by the selector for the namespace default:
```
$ cilium policy get
[
  {
    "endpointSelector": {
      "matchLabels": {
        "any:id": "app1",
        "k8s:io.kubernetes.pod.namespace": "default"
      }
    },
    "egress": [
      {
        "toEntities": [
          "host"
        ]
      },
      {
        "toEndpoints": [
          {
            "matchLabels": {
              "k8s:io.kubernetes.pod.namespace": "default"
            }
          }
        ],
        "toPorts": [
          {
            "ports": [
              {
                "port": "9100",
                "protocol": "TCP"
              },
              {
                "port": "10251",
                "protocol": "TCP"
              },
              {
                "port": "10252",
                "protocol": "TCP"
              },
              {
                "port": "10255",
                "protocol": "TCP"
              }
            ]
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "io.cilium.k8s.policy.name",
        "value": "lol",
        "source": "unspec"
      },
      {
        "key": "io.cilium.k8s.policy.namespace",
        "value": "default",
        "source": "unspec"
      }
    ]
  }
]
```

This is odd; what is the expected behavior here on the Cilium side? Given that this is a CiliumNetworkPolicy, I would expect that we would respect the wildcard (allowing traffic to all namespaces), not just endpoints in the default namespace.

**Comment by ianvernon** [comment]
This bug has two issues associated with it;

* What is the expected behavior for wildcard endpoint selector? Should it only be to endpoints within the namespace for CiliumNetworkPolicy?
* It looks like traffic is being denied to the host entity despite the policy allowing it; this still needs to be triaged.

**Comment by tgraf** [comment]
@ashwinp This seems to have been fixed. I can no longer reproduce it.

**Comment by tgraf** [comment]
Discussed on slack, an egress policy across namespace must specify the destination namespace, e.g.
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-to-ns1"
spec:
  endpointSelector:
    matchLabels:
     {}
  egress:
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": ns1
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
```

The `toEntities` is working as expected with the latest release
