### ISSUE TITLE
Egress policy to two endpoints with the same toPort does not work

### ISSUE THREAD

**Issue by ashwinp** [cilium/cilium#3418]
### Title

Egress policy to two endpoints with the same toPort does not work

### General Information

- Cilium version (run `cilium version`)
`v0.13.20`

### How to reproduce the issue

Used the following policy:
```
- endpointSelector:
    matchLabels:
      "k8s:app": prometheus
      "k8s:io.kubernetes.pod.namespace": monitoring
  egress:
  # prometheus clients talk amongst themselves on port 9090
  - toEndpoints:
    - matchLabels:
        "k8s:app": prometheus
        "k8s:io.kubernetes.pod.namespace": monitoring
    toPorts:
    - ports:
      - port: "9090"
        protocol: TCP
  # prometheus clients scrapes cilium metrics on port 9090
  - toEndpoints:
    - matchLabels:
        "k8s:k8s-app": cilium
        "k8s:io.kubernetes.pod.namespace": kube-system
    toPorts:
    - ports:
      - port: "9090"
        protocol: TCP
```
The `cilium policy get` looks OK:
```
      {
        "toEndpoints": [
          {
            "matchLabels": {
              "k8s:app": "prometheus",
              "k8s:io.kubernetes.pod.namespace": "monitoring"
            }
          }
        ],
        "toPorts": [
          {
            "ports": [
              {
                "port": "9090",
                "protocol": "TCP"
              }
            ]
          }
        ]
      },
      {
        "toEndpoints": [
          {
            "matchLabels": {
              "k8s:io.kubernetes.pod.namespace": "kube-system",
              "k8s:k8s-app": "cilium"
            }
          }
        ],
        "toPorts": [
          {
            "ports": [
              {
                "port": "9090",
                "protocol": "TCP"
              }
            ]
          }
        ]
      },
```

```
kubectl exec -it -n kube-system cilium-rnh6f -- cilium bpf policy get 53711 | grep 9090 -A 1
Ingress     k8s:prometheus=k8s                                        9090/TCP     68065       96
            k8s:app=prometheus
--
  Egress      k8s:prometheus=k8s                                        9090/TCP     510798      690
            k8s:app=prometheus
```

As seen above, there are two egress rules with toPort 9090 going to two distinct endpoints (cilium and prometheus). The policy does not work, and prometheus is unable to scrape the cilium metrics.
