### ISSUE TITLE
CiliumNetworkPolicy did not correctly applied to services with type LoadBalancer

### ISSUE THREAD

**Issue by minhng99** [cilium/cilium#34204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

Hi, I'm trying to apply a CiliumNetworkPolicy to protect the `External IP` so that only a specific CIDR can access the exposed service and port with the following config:
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: service-firewall
  namespace: haproxy
spec:
  endpointSelector:
    matchLabels:
      app: crdb-cluster-sg
  ingress:
  # Allow Cluster-Wide access
  - fromEntities:
    - health
    - remote-node
    - cluster
    toPorts:
    - ports:
      - port: "26257"
        protocol: TCP
  # Allow from 172.19.128.17 access
  - fromCIDR:
    - 172.19.128.17/32
    toPorts:
    - ports:
      - port: "26257"
        protocol: TCP
```

The deployment is having the Service declared as follow:
```
apiVersion: v1
kind: Service
metadata:
  name: crdb-cluster-sg-external
  namespace: haproxy
  annotations:
    io.cilium/lb-ipam-ips: "172.19.128.47"
    lbipam.cilium.io/sharing-key: "*"
    lbipam.cilium.io/sharing-cross-namespace: "*"
spec:
  selector:
    app: crdb-cluster-sg
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 26257
    targetPort: 26257
    name: sql
```

But this didn't work as expected, for some reason in the denied log does not having the IP 172.19.128.17 but for some reason it's the Pod IP, maybe this is from Cilium services? But why does it marked as `world` entity? I'm sure that the IP `198.18` is only located in the K8s and didn't came from anywhere else in my network.

```
198.18.7.27:59096 (world) <> haproxy/crdb-cluster-sg-7f78976b66-tsl79:26257 (ID:19810) Policy denied DROPPED (TCP Flags: SYN)
```

I'm new to Cilium and K8s so excuse me if I've done something wrong with my setup.

### How can we reproduce the issue?

Cilium config:
```
helm upgrade --install cilium cilium/cilium --version 1.16.0 \
    --namespace kube-system \
    --set bpf.masquerade=true \
    --set k8sClientRateLimit.qps=100 \
    --set k8sClientRateLimit.burst=300 \
    --set ipv4.enabled=true \
    --set k8sServiceHost=172.19.128.50 \
    --set k8sServicePort=6443  \
    --set kubeProxyReplacement=true  \
    --set bandwidthManager.enabled=true \
    --set bandwidthManager.bbr=true \
    --set operator.replicas=3  \
    --set operator.prometheus.enabled=true \
    --set serviceAccounts.cilium.name=cilium  \
    --set serviceAccounts.operator.name=cilium-operator  \
    --set ipam.mode=kubernetes \
    --set ipam.operator.clusterPoolIPv4PodCIDR=198.18.0.0/16 \
    --set ipam.operator.clusterPoolIPv4PodCIDRList[0]="198.18.0.0/16" \
    --set ipam.operator.clusterPoolIPv4MaskSize=24 \
    --set tunnel=vxlan \
    --set hubble.enabled=true \
    --set hubble.relay.enabled=true \
    --set hubble.ui.enabled=true \
    --set hubble.peerService.clusterDomain="cluster-1.local" \
    --set hubble.metrics.enabled="{dns,drop,tcp,flow,icmp,http}" \
    --set prometheus.enabled=true \
    --set l2announcements.enabled=true \
    --set l2announcements.leaseDuration=3s \
    --set l2announcements.leaseRenewDeadline=1s \
    --set l2announcements.leaseRetryPeriod=200ms \
    --set externalIPs.enabled=true \
    --set hostFirewall.enabled=true \
    --set nodeSelectorLabels=true \
    --set ingressController.enabled=false
```

kubeadm init config:
```
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
controlPlaneEndpoint: "172.19.128.50"
clusterName: cluster-1.local
apiServer:
  certSANs:
  - "localhost"
  - "127.0.0.1"
  - "::1"
  - "172.19.128.50"
  - "172.19.128.51"
  - "172.19.128.52"
  - "172.19.128.53"
  - "k8s-sg-m"
  - "k8s-sg-m1"
  - "k8s-sg-m2"
  - "k8s-sg-m3"
networking:
  podSubnet: "198.18.0.0/16"
  serviceSubnet: "198.19.0.0/16"
  dnsDomain: "cluster-1.local"
etcd:
  external:
    endpoints:
    - "http://172.19.128.51:2379"
    - "http://172.19.128.52:2379"
    - "http://172.19.128.53:2379"
---
apiVersion: "kubeadm.k8s.io/v1beta3"
kind: InitConfiguration
skipPhases:
  - addon/kube-proxy
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
failSwapOn: false
featureGates:
  NodeSwap: true
memorySwap:
  swapBehavior: LimitedSwap
cgroupDriver: "systemd"
serializeImagePulls: false
maxParallelImagePulls: 8
containerLogMaxSize: "8Mi"
shutdownGracePeriod: 40s
imageMinimumGCAge: 5m
imageMaximumGCAge: 1h
```

### Cilium Version

v1.16.0

### Kernel Version

5.14.0-427.28.1.el9_4.x86_64

### Kubernetes Version

v1.30.3

### Relevant log output

```shell
Aug  6 12:18:17.023: 198.18.7.27:44088 (world) <> haproxy/crdb-cluster-sg-7f78976b66-rf5rd:26257 (ID:19810) policy-verdict:none INGRESS DENIED (TCP Flags: SYN)
Aug  6 12:18:17.023: 198.18.7.27:44088 (world) <> haproxy/crdb-cluster-sg-7f78976b66-rf5rd:26257 (ID:19810) Policy denied DROPPED (TCP Flags: SYN)
Aug  6 12:18:17.453: 198.18.7.27:52778 (world) <> haproxy/crdb-cluster-sg-7f78976b66-tsl79:26257 (ID:19810) policy-verdict:none INGRESS DENIED (TCP Flags: SYN)
Aug  6 12:18:17.453: 198.18.7.27:52778 (world) <> haproxy/crdb-cluster-sg-7f78976b66-tsl79:26257 (ID:19810) Policy denied DROPPED (TCP Flags: SYN)
Aug  6 12:18:18.780: 198.18.7.27:52786 (world) <> haproxy/crdb-cluster-sg-7f78976b66-rf5rd:26257 (ID:19810) policy-verdict:none INGRESS DENIED (TCP Flags: SYN)
Aug  6 12:18:18.780: 198.18.7.27:52786 (world) <> haproxy/crdb-cluster-sg-7f78976b66-rf5rd:26257 (ID:19810) Policy denied DROPPED (TCP Flags: SYN)
Aug  6 12:33:28.568: 198.18.7.27:59096 (world) <> haproxy/crdb-cluster-sg-7f78976b66-tsl79:26257 (ID:19810) policy-verdict:none INGRESS DENIED (TCP Flags: SYN)
Aug  6 12:33:28.568: 198.18.7.27:59096 (world) <> haproxy/crdb-cluster-sg-7f78976b66-tsl79:26257 (ID:19810) Policy denied DROPPED (TCP Flags: SYN)
Aug  6 12:33:29.581: 198.18.7.27:59096 (world) <> haproxy/crdb-cluster-sg-7f78976b66-tsl79:26257 (ID:19810) policy-verdict:none INGRESS DENIED (TCP Flags: SYN)
Aug  6 12:33:29.581: 198.18.7.27:59096 (world) <> haproxy/crdb-cluster-sg-7f78976b66-tsl79:26257 (ID:19810) Policy denied DROPPED (TCP Flags: SYN)
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by minhng99** [comment]
I've debug further and saw that when I use L2 Announcement, only the pods which located on the node doing the ARP announcement will get the correct `src-ip` address, otherwise it will see an IP address which located within the cluster.

I'm expecting Cilium to do Service load balance by using some sort of L3 NAT and not L7 proxy? but this mixed behaviour is so strange, maybe I've done something wrong with the L2 configuration?

```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "local-vlan"
spec:
  blocks:
  - start: "172.19.128.45"
    stop: "172.19.128.49"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-announcement-policy
  namespace: kube-system
spec:
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
      - key: topology.kubernetes.io/region
        operator: In
        values:
        - sg
  interfaces:
    - eth0
  externalIPs: true
  loadBalancerIPs: true

```
