### ISSUE TITLE
Egress to host does not work with policy containing toEndpoints `reserved:host` label

### ISSUE THREAD

**Issue by ashwinp** [cilium/cilium#3421]
### Title

Egress to host does not work with policy containing toEndpoints `reserved:host` label

### General Information

- Cilium version (run `cilium version`)
v0.13.20
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
k8s

### How to reproduce the issue

This is similar to GH #3415, but not quite the same. In this case, the rule explicitly specifies the `reserved:host` label. On the contrary, GH #3415 uses `toEntities: host` or uses a catch all label for `toEndpoints`.

Used the following policy to allow the prometheus client to talk to an application running on the host:
```
- endpointSelector:
    matchLabels:
      "k8s:app": prometheus
      "k8s:io.kubernetes.pod.namespace": monitoring
  egress:
  # Communication with node-exporter
  - toEndpoints:
    - matchLabels:
        "reserved:host": ""    
    toPorts:
    - ports:
      - port: "9100"
        protocol: TCP
      - port: "10251"
        protocol: TCP
      - port: "10252"
        protocol: TCP
      - port: "10255"
        protocol: TCP
```
