### ISSUE TITLE
External traffic to local pods does not get SNAT

### ISSUE THREAD

**Issue by tommasopozzetti** [cilium/cilium#34235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.15.7 and lower than v1.16.0

### What happened?

I use metallb to advertise LoadBalancer IPs via layer 2. For a service with `externalTrafficPolicy: Cluster`, if the node metallb picks to advertise the VIP happens to also run at least a replica of the workload behind the service, it appears cilium is not performing SNAT for the traffic that is received by that node and goes to the local pod (which is able to see the client IP directly in the source of the packets). For all other replicas on other nodes though, the expected load balancing SNAT behavior is experienced, where the source IP is the internal cilium interface of the node receiving the external traffic.
For `externalTrafficPolicy: Cluster` the expectation is that all traffic gets SNATted, irrespectively of whether the pod happens to be on the same node receiving external traffic or not.
Furthermore, because of this, it appears return packets from the pod are sometimes dropped by cilium with log `FIB lookup failed` (possibly because the FIB lookup for the client IP was never populated since that traffic was supposed to be SNATted?). This also happens only in very precise conditions, namely if there is no other traffic already ongoing between the client and the host receiving the traffic which would have populated the neighbor table on the host and only if the first connection hits that local pod (as if it instead happens to be load balanced to another replica on another node that interaction works fine and as part of that the FIB lookup for the client IP on the host receiving the traffic and doing load balancing gets populated correctly which then solves the issue for the subsequent connection to the local pod as well).

### How can we reproduce the issue?

1. Install cilium (here are the values for my install):
```yaml
logOptions:
  format: json
cni:
  exclusive: false
routingMode: "tunnel"
tunnelProtocol: "vxlan"
kubeProxyReplacement: "true"
enableIPv6Masquerade: false
bpf:
  masquerade: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
operator:
  prometheus:
    enabled: true
socketLB:
  hostNamespaceOnly: true
```
2. Install metallb and add an ippool in layer 2 advertisement mode (for simplicity of the test, force the pool to be only advertised by a single node of the cluster via node selector)
3. Create a LoadBalancer service with `externalTrafficPolicy: Cluster` pointing to a deployment with a single replica running on the same node that is advertising the VIP (I used https://github.com/stefanprodan/podinfo for this, installing the chart with the following values)
```yaml
replicaCount: 1
logLevel: debug
service:
  type: LoadBalancer
nodeSelector:
  somelabel: somevalue
```
4. Send some traffic to the service and observe the pod log the client IP address instead of the SNATted address.
5. Send some traffic from a random machine not in the Kubernetes cluster but in the same CIDR as the node running the service. Ensure it has never communicated with that node before. Observe the connection hang and Hubble report dropped packets due to FIB lookup failed

You can scale up the deployment and force different replicas on different nodes to see that all other replicas get the traffic properly SNATted while the one on the node receiving external traffic does not.

### Cilium Version

1.15.7

### Kernel Version

Linux 5.4.0-177-generic #197-Ubuntu SMP Thu Mar 28 22:45:47 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.28.5

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
