### ISSUE TITLE
It's not possible to set localPort on BGP instance to 179

### ISSUE THREAD

**Issue by YaroCabbage** [cilium/cilium#34248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### Permission issue occurs during start of BGP instance with localPort set to 179. 
The problem is that when I set local port to **1790**, the peer appears in bgp peers table, but when I use **port 179**, the peer **disappears**.

_vultr-worker1 appears with local port set to 1790_
<img width="978" alt="screen 2024-08-08 в 17 30 20" src="https://github.com/user-attachments/assets/1c37abfd-0f60-4b29-b248-726cb46e7042">

_vultr-worker1 disappears with local port set to 179_
<img width="969" alt="screen 2024-08-08 в 17 30 59" src="https://github.com/user-attachments/assets/ab43ca62-4260-41a7-8b21-93760e3242aa">

To clarify:
- When I'm not using CiliumBGPNodeConfigOverride, all peers are in place, but each of them has port 179 in a closed state when I try to reach them.
- When I'm using CiliumBGPNodeConfigOverride with port 1790, peers are in place and port 1790 is in an open state.
- When I'm using CiliumBGPNodeConfigOverride with port 179, the peer is not in place and port 179 is in a closed state. 

### How can we reproduce the issue?

1. Install cilium with it's cli util
```
cilium install \
    --set ipam.mode=kubernetes \
    --set kubeProxyReplacement=true \
    --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
    --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
    --set cgroup.autoMount.enabled=false \
    --set cgroup.hostRoot=/sys/fs/cgroup \
    --set k8sServiceHost=localhost \
    --set k8sServicePort=7445 \
    --set bgpControlPlane.enabled=true \
    --set hostFirewall.enabled=true
``` 
2. Setup BGP
### lbipam.yaml
```yaml
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lb-pool"
spec:
  blocks:
    - start: "95.179.134.40"
``` 
### bgp.yaml
```yaml
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      rack: rack0
  bgpInstances:
    - name: "instance-LOCALASNNUMBER"
      localASN: LOCALASNNUMBER
      peers:
        - name: "peer-A"
          peerASN: 64515
          peerAddress: 169.254.169.254
          peerConfigRef:
            name: "cilium-peer"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  authSecretRef: vultr-bgp-auth-secret

  gracefulRestart:
    enabled: true
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements-internal
  namespace: kube-system
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "PodCIDR"
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - { key: "service-type", operator: In, values: [ "internal" ] }
          - { key: somekey, operator: NotIn, values: [ 'never-used-value' ] }
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPNodeConfigOverride
metadata:
  name: vultr-worker1
spec:
  bgpInstances:
    - name: "instance-LOCALASNNUMBER"
      routerID: "199.247.31.65"
      localPort: 179
      peers:
        - name: "peer-A"
          localAddress: 169.254.169.254
``` 

### Cilium Version

cilium-cli: v0.16.14 compiled with go1.22.5 on darwin/amd64
cilium image (default): v1.16.0
cilium image (stable): v1.16.0
cilium image (running): 1.16.0

### Kernel Version

I'm using Talos OS 1.6.8
https://github.com/siderolabs/talos/releases/tag/v1.6.8

### Kubernetes Version

Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.1

### Sysdump

[cilium-sysdump-20240808-171650.zip](https://github.com/user-attachments/files/16549411/cilium-sysdump-20240808-171650.zip)

### Relevant log output

```shell
time="2024-08-07T20:51:35Z" level=debug msg="Controller func execution time: 702.074µs" name=link-cache subsys=controller uuid=5dc5ec35-7291-4af3-87c6-27ca078f813b
time="2024-08-07T20:51:35Z" level=debug msg="Handling request for /healthz" subsys=health-server
time="2024-08-07T20:51:37Z" level=debug msg="Controller func execution time: 1.861µs" name=bpf-map-sync-cilium_lxc subsys=controller uuid=68511ca4-ba8a-4aee-b554-ba44d1eda9d5
time="2024-08-07T20:51:38Z" level=debug msg="Reconciling BGP instances" bgp_node_config=vultr-worker1 diff="Registering: [] Withdrawing: [] Reconciling: [instance-4288000320]" subsys=bgp-control-plane
time="2024-08-07T20:51:38Z" level=debug msg="Begin preflight reconciliation" instance=instance-4288000320 reconciler=Preflight subsys=bgp-control-plane
time="2024-08-07T20:51:38Z" level=info msg="BGP instance local port modified" instance=instance-4288000320 listen_port=1790 new_port=179 reconciler=Preflight subsys=bgp-control-plane
time="2024-08-07T20:51:38Z" level=info msg="Recreating BGP instance for changes to take effect" instance=instance-4288000320 reconciler=Preflight subsys=bgp-control-plane
time="2024-08-07T20:51:38Z" level=info msg="Delete a peer configuration" Key=169.254.169.254 Topic=Peer asn=4288000320 component=gobgp.BgpServerInstance subsys=bgp-control-plane
time="2024-08-07T20:51:38Z" level=info msg="Peer Down" Key=169.254.169.254 Reason=dying State=BGP_FSM_ESTABLISHED Topic=Peer asn=4288000320 component=gobgp.BgpServerInstance subsys=bgp-control-plane
time="2024-08-07T20:51:38Z" level=debug msg="freed fsm.h" Key=169.254.169.254 State=BGP_FSM_ESTABLISHED Topic=Peer asn=4288000320 component=gobgp.BgpServerInstance subsys=bgp-control-plane
time="2024-08-07T20:51:38Z" level=error msg="Encountered error reconciling BGP instance, shutting down this server" error="failed to start BGP instance for instance-4288000320: failed starting BGP server: listen tcp4 0.0.0.0:179: bind: permission denied" instance=instance-4288000320 subsys=bgp-control-plane
time="2024-08-07T20:51:38Z" level=error msg="Encountered error during reconciliation" component=Controller.Run error="failed to reconcile BGPNodeConfig: encountered error reconciling BGP instances: [instance-4288000320]" subsys=bgp-control-plane
time="2024-08-07T20:51:40Z" level=debug msg="Controller func execution time: 2.073µs" name=node-neighbor-link-updater subsys=controller uuid=3848ead6-03fb-405f-8f65-115ae0ad1c8c
time="2024-08-07T20:51:40Z" level=debug msg="Controller func execution time: 172.976µs" name=daemon-validate-config subsys=controller uuid=164ad843-3510-4edc-9c14-325802eca502
time="2024-08-07T20:51:40Z" level=debug msg="Controller func execution time: 682.973µs" name=endpoint-gc subsys=controller uuid=d7438093-1104-4025-93b4-a2a543f2f26c
time=2024-08-07T20:51:40Z level=debug msg="Timer job triggered" module=agent.controlplane.auth name="auth gc-cleanup" func=auth.(*authMapGarbageCollector).cleanup
time="2024-08-07T20:51:40Z" level=debug msg="Cleaning up expired entries" gc_time="2024-08-07 20:51:40.876838896 +0000 UTC m=+43507.117599480" subsys=auth
time="2024-08-07T20:51:40Z" level=debug msg="Cleaning up entries which belong to deleted nodes" subsys=auth
time="2024-08-07T20:51:40Z" level=debug msg="Cleaning up entries which belong to deleted identities" subsys=auth
time="2024-08-07T20:51:40Z" level=debug msg="Cleaning up entries which no longer require authentication by a policy" subsys=auth
time=2024-08-07T20:51:40Z level=debug msg="Timer job finished" module=agent.controlplane.auth name="auth gc-cleanup" func=auth.(*authMapGarbageCollector).cleanup
time="2024-08-07T20:51:40Z" level=debug msg="Handling request for /healthz" subsys=health-server
```

### Anything else?

I tried to set node-port-bind-protection to false, but that didn't help resolve the issue.
Here is a little fresher relevant log:
```log
time="2024-08-08T14:43:39Z" level=debug msg="Reconciling BGP instances" bgp_node_config=vultr-worker1 diff="Registering: [] Withdrawing: [] Reconciling: [instance-4288000320]" subsys=bgp-control-plane
time="2024-08-08T14:43:39Z" level=debug msg="Begin preflight reconciliation" instance=instance-4288000320 reconciler=Preflight subsys=bgp-control-plane
time="2024-08-08T14:43:39Z" level=info msg="BGP instance local port modified" instance=instance-4288000320 listen_port=1790 new_port=179 reconciler=Preflight subsys=bgp-control-plane
time="2024-08-08T14:43:39Z" level=info msg="Recreating BGP instance for changes to take effect" instance=instance-4288000320 reconciler=Preflight subsys=bgp-control-plane
time="2024-08-08T14:43:39Z" level=info msg="Delete a peer configuration" Key=169.254.169.254 Topic=Peer asn=4288000320 component=gobgp.BgpServerInstance subsys=bgp-control-plane
time="2024-08-08T14:43:39Z" level=info msg="Peer Down" Key=169.254.169.254 Reason=dying State=BGP_FSM_ESTABLISHED Topic=Peer asn=4288000320 component=gobgp.BgpServerInstance subsys=bgp-control-plane
time="2024-08-08T14:43:39Z" level=debug msg="freed fsm.h" Key=169.254.169.254 State=BGP_FSM_ESTABLISHED Topic=Peer asn=4288000320 component=gobgp.BgpServerInstance subsys=bgp-control-plane
time="2024-08-08T14:43:39Z" level=error msg="Encountered error reconciling BGP instance, shutting down this server" error="failed to start BGP instance for instance-4288000320: failed starting BGP server: listen tcp4 0.0.0.0:179: bind: permission denied" instance=instance-4288000320 subsys=bgp-control-plane
time="2024-08-08T14:43:39Z" level=error msg="Encountered error during reconciliation" component=Controller.Run error="failed to reconcile BGPNodeConfig: encountered error reconciling BGP instances: [instance-4288000320]" subsys=bgp-control-plane
``` 

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
@harsimran-pabla I could swear you've just been poking at setting the `localPort` :grin:. Does that ring any bells for you?

**Comment by harsimran-pabla** [comment]
Hi @julianwiedmann, Yes, indeed. This is a somewhat different issue. I think we should have named the field in question to ListenPort instead of LocalPort. It is the port on which gobgp will listen to accept TCP connections. 

Hi @YaroCabbage 

Now coming to the issue, I think this is because gobgp is binding to port 179, in some cases ports < 1024 are privileged and Cilium process will require CAP_NET_BIND_SERVICE. 

I have also seen that docker by default sets `net.ipv4.ip_unprivileged_port_start=0`, so when testing using KIND and docker, we don't run into this issue. 


There are two solutions 
- Set correct capability for cilium process.
- Set unprivileged port start from 0 in Cilium pod.



Here is an example of setting CAP_NET_BIND_SERVICE

Cilium security context values when installing it : 

```
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_BIND_SERVICE   <<<<< new one added
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
```

Inside the Cilium pod we can see this capability set
```
root@bgpv2-cplane-dev-multi-homing-control-plane:/home/cilium# ps aux | grep cilium-agent
root           1  2.9  1.1 1408316 161696 ?      Ssl  13:54   0:07 cilium-agent --config-dir=/tmp/cilium/config-map
root         688  0.0  0.0   2880  1536 pts/0    S+   13:58   0:00 grep --color=auto cilium-agent
root@bgpv2-cplane-dev-multi-homing-control-plane:/home/cilium#

root@bgpv2-cplane-dev-multi-homing-control-plane:/home/cilium# getpcaps 1
1: cap_chown,cap_dac_override,cap_fowner,cap_kill,cap_setgid,cap_setuid,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_sys_admin,cap_sys_resource=ep

```

**Comment by YaroCabbage** [comment]
Hi @harsimran-pabla!
The LocalPort is now open, so the issue resolved! Thank you!

Unfortunately, the BGP setup still isn't working. I'm trying to figure out what's wrong.

Basic commands show that everything is fine, but pinging the reserved IP address returns a request timeout. The same configuration works fine on pure GoBGP. I've already checked everything...


<img width="977" alt="Снимок экрана 2024-08-09 в 22 15 42" src="https://github.com/user-attachments/assets/0766bf30-1815-4099-8fe4-6d24b99f759a">

<img width="800" alt="Снимок экрана 2024-08-09 в 22 14 48" src="https://github.com/user-attachments/assets/cc784d43-8083-497b-aa3a-81a6e82d3b28">

<img width="400" alt="Снимок экрана 2024-08-09 в 23 14 05" src="https://github.com/user-attachments/assets/f318afb9-265c-453a-9ce2-8ebcf63f596c">


Here is strange log extracted with kubectl, but my ip-pool looks fine 🧐
```
time="2024-08-09T20:03:56Z" level=warning msg="failed to parse IPAM pool CIDR " error="netip.ParsePrefix(\"\"): no '/'" subsys=bgp-control-plane
``` 
**ip-pool.yaml**
```yaml
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lb-pool"
spec:
  blocks:
    - start: "95.179.134.40"
  serviceSelector:
    matchExpressions:
      - { key: somekey, operator: NotIn, values: [ 'never-used-value' ] }
```

**Comment by YaroCabbage** [comment]
Hi @harsimran-pabla!
I've figured out why BGP wasn't working even after solving the previous issue. When I applied the start keyword with just one IP address, I encountered the following warning:
```
level=warning msg="failed to parse IPAM pool CIDR " error="netip.ParsePrefix(\"\"): no '/'"
``` 

**Configuration that caused such warning:**
```yaml
spec:
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lb-pool"
spec:
  blocks:
    - start: "95.179.134.40"
  serviceSelector:
    matchExpressions:
      - { key: somekey, operator: NotIn, values: [ 'never-used-value' ] }
``` 
 
I changed the configuration to the following, and it's working fine now:
```yaml
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lb-pool"
spec:
  blocks:
    - cidr: "95.179.134.40/32"
  serviceSelector:
    matchExpressions:
      - { key: somekey, operator: NotIn, values: [ 'never-used-value' ] }
``` 
 
The issue was that when I tried to ping this IP address (95.179.134.40), the command indicated that I was losing packets. This problem didn’t occur with GoBGP—ping worked fine with it. Surprisingly, when I accidentally tried to access the service through a browser, everything worked after changing the config! Apparently, Cilium blocks ICMP by default.
