### ISSUE TITLE
Cilium network policy is not being applied

### ISSUE THREAD

**Issue by mzameer777** [cilium/cilium#34252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We are running a kubeadm k8s cluster with Cilium 1.15.2. I installed cilium with policy enforcement mode as always, and also enabled policy audit mode to monitor the traffic in the cluster.  I can see request being audited 

`Policy verdict log: flow 0x0 local EP ID 1935, remote ID 7704, proto 6, ingress, action audit, auth: disabled, match none, 7.7.5.167:52096 -> 7.7.4.249:1024 tcp SYN`

I'm trying to apply a cilium network policy to whitelist this traffic flow

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "haproxy-network-policy"
  namespace: ingress-controller
spec:
  description: "haproxy network policy"
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: haproxy-ingress-controller-kubernetes-ingress
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: monitoring-kube-prometheus-prometheus
    toPorts:
    - ports:
      - port: "1024"
        protocol: "TCP"
```
     
After applying the policy I still see traffic between this endpoints being audited. 

I got the labels based on this command output
src:
```
kexec cilium ip list | grep -A 10 7.7.5.167

7.7.5.167/32                              k8s:app.kubernetes.io/instance=monitoring-kube-prometheus-prometheus          
                                          k8s:app.kubernetes.io/managed-by=prometheus-operator
                                          k8s:app.kubernetes.io/name=prometheus
                                          k8s:app.kubernetes.io/version=2.50.1
                                          k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=monitoring
                                          k8s:io.cilium.k8s.namespace.labels.name=monitoring
                                          k8s:io.cilium.k8s.namespace.labels.prometheusMonitoring=enabled
                                          k8s:io.cilium.k8s.policy.cluster=default
                                          k8s:io.cilium.k8s.policy.serviceaccount=monitoring-kube-prometheus-prometheus
                                          k8s:io.kubernetes.pod.namespace=monitoring
                                          k8s:operator.prometheus.io/name=monitoring-kube-prometheus-prometheus
```

dest:
```
7.7.4.249/32                              k8s:app.kubernetes.io/instance=haproxy-ingress-controller                                     custom-resource
                                          k8s:app.kubernetes.io/name=kubernetes-ingress
                                          k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=ingress-controller
                                          k8s:io.cilium.k8s.namespace.labels.name=ingress-controller
                                          k8s:io.cilium.k8s.policy.cluster=default
                                          k8s:io.cilium.k8s.policy.serviceaccount=haproxy-ingress-controller-kubernetes-ingress
                                          k8s:io.kubernetes.pod.namespace=ingress-controller
```

### How can we reproduce the issue?

Install cilium with helm with enforcement mode as always,  with policy audit mode as enabled and hostFirewall as enabled, and then install haproxy and prometheus.

### Cilium Version

Client: 1.15.2 7cf57829 2024-03-13T15:34:43+02:00 go version go1.21.8 linux/amd64
Daemon: 1.15.2 7cf57829 2024-03-13T15:34:43+02:00 go version go1.21.8 linux/amd64

### Kernel Version

4.18.0-513.24.1.el8_9.x86_64 #1 SMP Thu Apr 4 18:13:02 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
