### ISSUE TITLE
Egress to port 443 denied due to CIDR check, but there is no CIDR rule in the policy

### ISSUE THREAD

**Issue by ashwinp** [cilium/cilium#3427]
### Title

Egress to port 443 denied due to CIDR, but there is no CIDR rule in the policy

### General Information

- Cilium version (run `cilium version`)
`v0.13.20`

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
k8s

### How to reproduce the issue

Relevant rule:
```
- endpointSelector:
    matchLabels:
      "k8s:app": cloudwatch-exporter
      "k8s:io.kubernetes.pod.namespace": monitoring
  # Cloudwatch exporter talks to AWS API on port 443
  egress:
  - toPorts:
    - ports:
      - port: "443"
        protocol: TCP
```
From `cilium monitor` from the node running cloudwatch-exporter:
```
xx drop (Policy denied (CIDR)) flow 0x8acf7aee to endpoint 0, identity 29016->0: 172.203.118.32:42216 -> 54.240.254.162:443 tcp SYN
```
