### ISSUE TITLE
Error using multiple allowedRoutes.namespaces.from selectors on a gateway

### ISSUE THREAD

**Issue by nilsherzig** [cilium/cilium#34288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

Hi, there already exists a similar (not exactly the same) issue #30085, but it's closed and for another version. I hope it's okay to open a new issue.

My Problem:

While using more than one listener on a gateway, the allowedRoutes selector seems to fail. Resulting in no binds from otherwise working (while using no selector or only one listener) httpRoutes.

### How can we reproduce the issue?

My cilium config (inside argocd, look for `valuesObject` I just wanted to post the entire context just in case): 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cilium
      repoURL: https://helm.cilium.io/
      targetRevision: v1.16.0
      helm:
        valuesObject:
          k8sServiceHost: localhost
          k8sServicePort: 7445
          kubeProxyReplacement: true
          ipam:
            mode: kubernetes
          hubble:
            ui:
              enabled: true
            relay:
              enabled: true
          gatewayAPI:
            enabled: true
            hostNetwork:
              enabled: true
          cgroup:
            hostRoot: "/sys/fs/cgroup"
            autoMount:
              enabled: true
          bpf:
            hostLegacyRouting: false
          envoy:
            securityContext:
              capabilities:
                keepCapNetBindService: true
                envoy:
                  - NET_ADMIN
                  - NET_BIND_SERVICE
                  - SYS_ADMIN
          securityContext:
            capabilities:
              ciliumAgent:
                - CHOWN
                - KILL
                - NET_ADMIN
                - NET_RAW
                - IPC_LOCK
                - SYS_ADMIN
                - SYS_RESOURCE
                - DAC_OVERRIDE
                - FOWNER
                - SETGID
                - SETUID
              cleanCiliumState:
                - NET_ADMIN
                - SYS_ADMIN
                - SYS_RESOURCE
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

my gateway:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: shared-gateway
  namespace: infra
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: cilium
  listeners:
    - name: https-listener-argocd-dev-nilsherzig-com
      hostname: "argocd.dev.nilsherzig.com"
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: argocd-dev-nilsherzig-com
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: argocd

    - name: https-listener-nilsherzig-com
      hostname: "nilsherzig.com"
      protocol: HTTPS
      port: 9090
      tls:
        mode: Terminate
        certificateRefs:
          - name: nilsherzig-com
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: homepage
```

example httproute with status:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.networking.k8s.io/v1","kind":"HTTPRoute","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"base"},"name":"http-route-argocd","namespace":"argocd"},"spec":{"hostnames":["argocd.dev.nilsherzig.com"],"parentRefs":[{"name":"shared-gateway","namespace":"infra"}],"rules":[{"backendRefs":[{"name":"argocd-server","port":80}],"matches":[{"path":{"type":"PathPrefix","value":"/"}}]}]}}
  creationTimestamp: "2024-08-10T19:19:28Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: base
  name: http-route-argocd
  namespace: argocd
  resourceVersion: "818880"
  uid: a9bc7309-43e7-4459-9ba0-254c674f4898
spec:
  hostnames:
  - argocd.dev.nilsherzig.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: shared-gateway
    namespace: infra
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: argocd-server
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
status:
  parents:
  - conditions:
    - lastTransitionTime: "2024-08-10T19:27:53Z"
      message: HTTPRoute is not allowed to attach to this Gateway due to namespace
        selector restrictions
      observedGeneration: 1
      reason: NotAllowedByListeners
      status: "False"
      type: Accepted
    - lastTransitionTime: "2024-08-10T19:27:11Z"
      message: Service reference is valid
      observedGeneration: 1
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    controllerName: io.cilium/gateway-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: shared-gateway
      namespace: infra
```

If i set the `allowedRoutes.namespaes.from` key to `Any`, everything works and services can attach. It also works (for the matching routes) when I only have one listener in the gateway config (even with the selector rules). 

### Cilium Version

1.16.0

### Kernel Version

Talos: (v1.7, but sadly i have no idea how to get the uname output)
NixOS: `Linux laptop 6.6.44 #1-NixOS SMP PREEMPT_DYNAMIC Sat Aug  3 06:54:42 UTC 2024 x86_64 GNU/Linux`

### Kubernetes Version

Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.1

### Regression

Not entirely sure, since the issue I've linked above does not talk about selectors, but maybe 1.15.0 (including a backport to 1.14.0)?

### Sysdump

🔍 Collecting sysdump with cilium-cli version: 0.16.14, args: [sysdump]
🔮 Detected Cilium installation in namespace: "kube-system"
🔮 Detected Cilium operator in namespace: "kube-system"
ℹ️ Using default Cilium Helm release name: "cilium"
ℹ️ Failed to detect Cilium SPIRE installation - using Cilium namespace as Cilium SPIRE namespace: "kube-system"
🔍 Collecting Kubernetes nodes
🔮 Detected Cilium features: map[bpf-lb-external-clusterip:Disabled cidr-match-nodes:Disabled clustermesh-enable-endpoint-sync:Disabled cni-chaining:Disabled:none enable-bgp-control-plane:Disabled enable-envoy-config:Enabled enable-gateway-api:Enabled enable-ipsec:Disabled enable-ipv4-egress-gateway:Disabled enable-local-redirect-policy:Disabled endpoint-routes:Disabled ingress-controller:Disabled ipam:Disabled:kubernetes ipv4:Enabled ipv6:Disabled mutual-auth-spiffe:Disabled wireguard-encapsulate:Disabled]
🔍 Collecting tracing data from Cilium pods
🔍 Collect Kubernetes nodes
🔍 Collecting Kubernetes events
🔍 Collect Kubernetes version
🔍 Collecting Kubernetes pods
🔍 Collecting Kubernetes namespaces
🔍 Collecting Kubernetes services
🔍 Collecting Kubernetes pods summary
🔍 Collecting Kubernetes endpoints
🔍 Collecting Kubernetes network policies
🔍 Collecting Kubernetes metrics
🔍 Collecting Kubernetes leases
🔍 Collecting Cilium cluster-wide network policies
🔍 Collecting Cilium network policies
🔍 Collecting Cilium egress NAT policies
🔍 Collecting Cilium Egress Gateway policies
🔍 Collecting Cilium local redirect policies
🔍 Collecting Cilium endpoint slices
🔍 Collecting Cilium endpoints
🔍 Collecting Cilium CIDR Groups
🔍 Collecting Cilium nodes
🔍 Collecting Cilium identities
🔍 Collecting Ingresses
🔍 Collecting Cilium BGP Peering Policies
🔍 Collecting IngressClasses
🔍 Collecting Cilium Node Configs
🔍 Collecting Cilium LoadBalancer IP Pools
🔍 Collecting Cilium Pod IP Pools
🔍 Checking if cilium-etcd-secrets exists in kube-system namespace
🔍 Collecting the Cilium configuration
🔍 Collecting the Cilium daemonset(s)
🔍 Collecting the Cilium Node Init daemonset
🔍 Collecting the Cilium Envoy configuration
🔍 Collecting the Cilium Envoy daemonset
🔍 Collecting the Hubble daemonset
🔍 Collecting the Hubble Relay configuration
🔍 Collecting the Hubble Relay deployment
🔍 Collecting the Hubble UI deployment
🔍 Collecting the Hubble generate certs cronjob
🔍 Collecting the Hubble generate certs pod logs
🔍 Collecting the Hubble cert-manager certificates
🔍 Collecting the Cilium operator deployment
🔍 Collecting the Cilium operator metrics
⚠️ Daemonset "cilium-node-init" not found in namespace "kube-system" - this is expected if Node Init DaemonSet is not enabled
🔍 Collecting the clustermesh debug information, metrics and gops stats
🔍 Collecting the 'clustermesh-apiserver' deployment
🔍 Collecting the CNI configuration files from Cilium pods
🔍 Collecting the CNI configmap
🔍 Collecting gops stats from Cilium pods
⚠️ cronjob "hubble-generate-certs" not found in namespace "kube-system" - this is expected if auto TLS is not enabled or if not using hubble.auto.tls.method=cronjob
🔍 Collecting gops stats from Cilium-operator pods
🔍 Collecting gops stats from Hubble pods
🔍 Collecting gops stats from Hubble Relay pods
🔍 Collecting bugtool output from Cilium pods
⚠️ Deployment "clustermesh-apiserver" not found in namespace "kube-system" - this is expected if 'clustermesh-apiserver' isn't enabled
🔍 Collecting profiling data from Cilium pods
🔍 Collecting logs from Cilium pods
🔍 Collecting logs from Cilium Envoy pods
Secret "cilium-etcd-secrets" not found in namespace "kube-system" - this is expected when using the CRD KVStore
🔍 Collecting logs from Cilium Node Init pods
🔍 Collecting logs from Cilium operator pods
🔍 Collecting logs from 'clustermesh-apiserver' pods
🔍 Collecting logs from Hubble pods
🔍 Collecting logs from Hubble Relay pods
🔍 Collecting logs from Hubble UI pods
🔍 Collecting platform-specific data
🔍 Collecting kvstore data
🔍 Collecting Cilium external workloads
🔍 Collecting Hubble flows from Cilium pods
🔍 Collecting logs from Tetragon pods
🔍 Collecting logs from Tetragon operator pods
🔍 Collecting bugtool output from Tetragon pods
🔍 Collecting Tetragon configmap
🔍 Collecting Tetragon PodInfo custom resources
🔍 Collecting Tetragon tracing policies
🔍 Collecting Tetragon namespaced tracing policies
🔍 Collecting Helm metadata from the release
🔍 Collecting Helm values from the release
🔍 Collecting GatewayClass entries
🔍 Collecting Gateway entries
🔍 Collecting ReferenceGrant entries
🔍 Collecting HTTPRoute entries
🔍 Collecting TLSRoute entries
🔍 Collecting GRPCRoute entries
🔍 Collecting TCPRoute entries
🔍 Collecting UDPRoute entries
🔍 Collecting CiliumClusterwideEnvoyConfigs
🔍 Collecting CiliumEnvoyConfigs
⚠️ The following tasks failed, the sysdump may be incomplete:
⚠️ [13] Collecting Cilium egress NAT policies: failed to collect Cilium egress NAT policies: the server could not find the requested resource
⚠️ [14] Collecting Cilium Egress Gateway policies: failed to collect Cilium Egress Gateway policies: the server could not find the requested resource (get ciliumegressgatewaypolicies.cilium.io)
⚠️ [16] Collecting Cilium local redirect policies: failed to collect Cilium local redirect policies: the server could not find the requested resource (get ciliumlocalredirectpolicies.cilium.io)
⚠️ [18] Collecting Cilium endpoint slices: failed to collect Cilium endpoint slices: the server could not find the requested resource (get ciliumendpointslices.cilium.io)
⚠️ [24] Collecting Cilium BGP Peering Policies: failed to collect Cilium BGP Peering policies: the server could not find the requested resource (get ciliumbgppeeringpolicies.cilium.io)
⚠️ [68] Collecting Tetragon PodInfo custom resources: failed to collect podinfo (v1alpha1): the server could not find the requested resource
⚠️ [69] Collecting Tetragon tracing policies: failed to collect tracingpolicies (v1alpha1): the server could not find the requested resource
⚠️ [70] Collecting Tetragon namespaced tracing policies: failed to collect tracingpoliciesnamespaced (v1alpha1): the server could not find the requested resource
⚠️ [71] Collecting Helm metadata from the release: failed to get the helm metadata from the release: unable to retrieve helm meta from release cilium: release: not found
⚠️ [72] Collecting Helm values from the release: failed to get the helm values from the release: unable to retrieve helm value from release cilium: release: not found
⚠️ [78] Collecting GRPCRoute entries: failed to collect GRPCRoute entries: the server could not find the requested resource
⚠️ [79] Collecting TCPRoute entries: failed to collect TCPRoute entries: the server could not find the requested resource
⚠️ [80] Collecting UDPRoute entries: failed to collect UDPRoute entries: the server could not find the requested resource
⚠️ Please note that depending on your Cilium version and installation options, this may be expected
🗳 Compiling sysdump
✅ The sysdump has been saved to cilium-sysdump-20240810-214255.zip

[cilium-sysdump-20240810-214255.zip](https://github.com/user-attachments/files/16570718/cilium-sysdump-20240810-214255.zip)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
