### ISSUE TITLE
NetworkPolicy denies communication with EKS Pod Identity Agent

### ISSUE THREAD

**Issue by taraspos** [cilium/cilium#34387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.14.13 and lower than v1.15.0

### What happened?

When NetworkPolicies configured, pods can't communicate with EKS Pod Identity Agent on `http://169.254.170.23/v1/credentials`

`169.254.170.23:80` is actually port on the daemon set with `hostNetwork: true`:
- https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html#pod-id-considerations

Everything works with network policy like:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-policy
spec:
  egress:
  - {}
  podSelector:
    matchLabels:
      component: my-pod
  policyTypes:
  - Egress
```

But it stops working when any egress rule is added, for example:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-policy
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
  podSelector:
    matchLabels:
      component: my-pod
  policyTypes:
  - Egress
```

Hubble reports following:

```
my-test-pod:38762 (ID:97997) <> 169.254.170.23:80 (host) policy-verdict:none EGRESS DENIED (TCP Flags: SYN)
```

### How can we reproduce the issue?

1. Install cilium helm
2. Install [EKS Pod Identity helm](https://github.com/aws/eks-pod-identity-agent/tree/main/charts/eks-pod-identity-agent)
3. Create network policy like:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-policy
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
  podSelector:
    matchLabels:
      component: my-pod
  policyTypes:
  - Egress
```
4. Start a pod
5. Try calling an `http://169.254.170.23/v1/credentials` endpoint

```
kubectl debug test-pod --image curlimages/curl  -it -- curl http://169.254.170.23/v1/credentials --connect-timeout  7 -I
```

### Cilium Version

v1.14.13

### Kernel Version

```
Linux my-bottlerocket-node 6.1.77 #1 SMP PREEMPT_DYNAMIC Fri Feb 23 02:26:25 UTC 2024 x86_64 Linux
```

### Kubernetes Version

1.28

### Relevant log output

```shell
Aug 14 18:05:59.638: taras-test-pod:54768 (ID:97997) <> 169.254.170.23:80 (host) policy-verdict:none EGRESS DENIED (TCP Flags: SYN)
Aug 14 18:05:59.638: taras-test-pod:54768 (ID:97997) <> 169.254.170.23:80 (host) Policy denied DROPPED (TCP Flags: SYN)
Aug 14 18:06:00.686: taras-test-pod:54768 (ID:97997) <> 169.254.170.23:80 (host) policy-verdict:none EGRESS DENIED (TCP Flags: SYN)
Aug 14 18:06:00.686: taras-test-pod:54768 (ID:97997) <> 169.254.170.23:80 (host) Policy denied DROPPED (TCP Flags: SYN)
Aug 14 18:06:02.756: taras-test-pod:54768 (ID:97997) <> 169.254.170.23:80 (host) policy-verdict:none EGRESS DENIED (TCP Flags: SYN)
Aug 14 18:06:02.756: taras-test-pod:54768 (ID:97997) <> 169.254.170.23:80 (host) Policy denied DROPPED (TCP Flags: SYN)
```
```


### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Thanks for this issue @taraspos.

In this case, the NetworkPolicy objects you've given are working as directed - they're blocking _all_ egress from the pods, full stop. This will include IPs on the local machine. For this to work, you'll need to flip to using allow policies, and allowlisting the traffic you want - Cilium will deny any traffic that does not match a policy in that case.

More information is available in the Network Policy reference section of the Cilium documentation at https://docs.cilium.io/en/stable/security/policy/.

Please let us know if you need to know more.

**Comment by taraspos** [comment]
It seems like this issue might be related to the:
- https://github.com/cilium/cilium/issues/20550

**Comment by youngnick** [comment]
🤦 Yes, you're right.

However, I also agree that nodes being excluded from `ipBlock` would actually produce the outcome I was talking about. Is it possible for you to upgrade and see if 1.15 and see if that helps?

**Comment by taraspos** [comment]
Yes, I can confirm this works fine with Cilium 1.15

**Comment by youngnick** [comment]
Okay, it does seem likely that nodes being excluded from `ipBlock` produces the outcome you're looking for, and that changes in 1.15 remove that issue. Given that, what would you like for next steps to be?

**Comment by taraspos** [comment]
I believe we should be OK to resolve this then. If other users face the same problem, they should be able to find this issue.

**Comment by Pionerd** [comment]
Just as an addition, we use the following CNP successfully for External Secrets Operator using Pod Identity. The traffic to the mentioned IP is recognised as `host` traffic by Cilium 1.16 and the two ports are from the EKS Pod Identity docs:
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: aws
spec:
  endpointSelector: {}
  ingress:
    - {}
  egress:
    - toFQDNs:
        - matchName: sts.{{ $.Values.awsSecretsmanager.region }}.amazonaws.com
        - matchName: secretsmanager.{{ $.Values.awsSecretsmanager.region }}.amazonaws.com
        - matchName: api.ecr.{{ $.Values.awsSecretsmanager.region }}.amazonaws.com
      toPorts:
        - ports:
            - port: "443"
    - toEntities:
        - host
      toPorts:
        - ports:
            - port: "80"
            - port: "2703"
```
