### ISSUE TITLE
CiliumNetworkPolicy egress overrides CiliumClusterwideNetworkPolicy egress

### ISSUE THREAD

**Issue by eric-engberg** [cilium/cilium#34390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

I have a clusterwide egress policy for coredns that selects all endpoints.  If a CCNP and CNP both have `toEndpoints` the CCNP rule gets lost.  If CNP does not have `toEndpoints` the CCNP still applies.  I would expect that the CCNP and CNP array's to get merged.

These are the policies I have that are conflicting

```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: core-dns
specs:
  - endpointSelector:
      matchLabels:
        io.cilium.k8s.policy.serviceaccount: coredns
        k8s:io.kubernetes.pod.namespace: kube-system
    ingress:
      - fromEndpoints:
          - {}
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
  - endpointSelector:
      matchLabels: {}
    egress:
      - toEndpoints:
          - matchLabels:
              io.cilium.k8s.policy.serviceaccount: coredns
              k8s:io.kubernetes.pod.namespace: kube-system
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
            rules:
              dns:
                - matchPattern: "*"
```

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: argocd-redis-ha-haproxy
spec:
  description: Network policy for argocd redis-ha-proxy pods
  endpointSelector:
    matchLabels:
      app: redis-ha-haproxy
  ingress:
    - fromEndpoints:
        - matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - argocd-server
                - argocd-repo-server
                - argocd-application-controller
            - key: k8s:io.kubernetes.pod.namespace
              operator: In
              values:
                - argo
      toPorts:
        - ports:
            - port: "6379"
              protocol: TCP
  egress:
    # egress to redis-server
    - toEndpoints:
        - matchExpressions:
            - key: k8s:app
              operator: In
              values:
                - redis-ha
            - key: k8s:io.kubernetes.pod.namespace
              operator: In
              values:
                - argo
      toPorts:
        - ports:
            - port: "6379"
              protocol: TCP
            - port: "26379"
              protocol: TCP
```

### How can we reproduce the issue?

1. Create CCNP with an egress using toEndpoints that selects all endpoints
2. Create a CNP for a resource that contains a toEndpoints egress rule.
3. Observe that the CCNP rule no longer applies and traffic is dropped/audited.

### Cilium Version

1.16

### Kernel Version

Linux ip-10-0-156-208.ec2.internal 5.15.160 #1 SMP Tue Jul 16 23:47:08 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

EKS 1.27

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
