### ISSUE TITLE
Envoy Metrics missing 1.16.x

### ISSUE THREAD

**Issue by frittenlab** [cilium/cilium#34425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

I am using the Cilium helm chart to deploy Cilium. I upgraded from 15.7 to 16.1 today and the envoy service monitor stopped exporting metrics. I am using these helm values for envoy and prometheus:

```
 envoyConfig:
  enabled: true

# Enable envoy daemonset
envoy:
  enabled: true

# Enable prometheus metrics for cilium-envoy
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: monitoring
```

During the update to 16.1 the envoy service was removed which was used by the service monitor. This happened with this commit:

[helm: remove duplicate metrics for Envoy pod #33803](https://github.com/cilium/cilium/pull/33803)

I added the service back to my cluster manually. Now everything is working as expected and I have metrics again. Maybe there is something that I am missing here. I don't see how a service monitor can work without the corresponding service. 

### How can we reproduce the issue?

1 install 1.16.x helm chart with the service monitor enabled for envoy. 

### Cilium Version

1.16.1

### Kernel Version

5.15.0-118-generic   c

### Kubernetes Version

1.31.1

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
