### ISSUE TITLE
CFP: CCNP for endpoint `"reserved:kube-apiserver"` should automatically include host policy as well when host firewall is enabled

### ISSUE THREAD

**Issue by nebula-it** [cilium/cilium#34444]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

When adding a policy to allow `"reserved:kube-apiserver"` a policy targeting `kube-apiserver` endpoint is not enough, e.g: This policy below does not work
```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-api-server-from-toolbox-ingress
spec:
  endpointSelector:
    matchLabels:
      "reserved:kube-apiserver": ""
  ingress:
    - fromEndpoints:
        - matchLabels:
            network.policy.allowed-service: api-server
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
```
instead you have to use one targeting the host itself, like:
```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-api-server-from-toolbox-ingress-host
spec:
  nodeSelector:
    matchLabels:
      "node-role.kubernetes.io/control-plane": ""
  ingress:
    - fromEndpoints:
        - matchLabels:
            network.policy.allowed-service: api-server
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
```
**Describe the feature you'd like**

The first policy mentioned above (`allow-api-server-from-toolbox-ingress`) should take care of allowing the access on host level as well.
