### ISSUE TITLE
Gateway API - RequestRedirect loops indefinately scheme change from http to https

### ISSUE THREAD

**Issue by julian-perge** [cilium/cilium#34539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

A copy of #28796 as this is still an persisting issue. I've also tried the slack channel, but I have gotten zero replies. I genuinely have no idea why this is happening, other than I don't specify a `tls` section.

Existing issues/references:
- https://github.com/kubernetes-sigs/gateway-api/issues/1185
- https://github.com/kubernetes-sigs/gateway-api/issues/2455
- https://github.com/kubernetes-sigs/gateway-api/issues/2809
- https://github.com/cilium/cilium/issues/25357
- https://github.com/cilium/cilium/issues/27493
- https://github.com/cilium/cilium/issues/28796
- https://www.reddit.com/r/kubernetes/comments/196w65h/gateway_api_and_redirect_loops/

1. Not using experimental Gateway CRDs, although I've tried with the both standard and experimental CRDs.
2. Gateway also does not have the `tls` section, because my cert is a public ACM one, so I can't add the `tls` section.
3. The Gateway HTTP section I copied from [this reddit post](https://www.reddit.com/r/kubernetes/comments/196w65h/gateway_api_and_redirect_loops/), in hopes that it actually did something.
4. Adding `hostnames` to any of the relevant sections doesn't make a difference.
5. I'm trying to use external-dns annotations to not use my internet-facing ELB, but ELB or service DNS endpoint doesn't make a difference.

Relevant yamls:

Gateway:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: external
  namespace: kube-system
spec:
  gatewayClassName: cilium
  listeners:
    - name: shared-http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              https-upgrade: "true"
    - name: shared-https
      port: 443
      protocol: HTTPS
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: All
```

Service created from Gateway:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "<string list of my domains>"
    service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
    service.beta.kubernetes.io/aws-load-balancer-name: iac-test-k8s-cilium-external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<my public acm cert>"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  labels:
    gateway.networking.k8s.io/gateway-name: external
    io.cilium.gateway/owning-gateway: external
  name: cilium-gateway-external
  namespace: kube-system
  ownerReferences:
  - apiVersion: gateway.networking.k8s.io/v1
    controller: true
    kind: Gateway
    name: external
```

HTTPRoute request redirect:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: https-upgrade
  namespace: https-upgrade
  labels:
    https-upgrade: "true"
spec:
  parentRefs:
    - name: external
      namespace: kube-system
      sectionName: shared-http  # this doesn't seem to matter at all
      kind: Gateway
  hostnames:
    - "<my internet-facing elb>"
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
```

HTTPRoute 443 to my service:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: default
spec:
  hostnames:
  - "<my internet-facing elb>"
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: external
    namespace: kube-system
    sectionName: shared-https  # this doesn't seem to matter at all
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: api-gateway
      namespace: default
      port: 9000
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
```

### How can we reproduce the issue?

I also have the AWS Load Balancer controller installed in my cluster to provision an NLB instead of Classic, but both types of LBs produce the same result.

1. Provision a public AWS ACM cert
2. Create a gateway like above
  - no tls section since the cert is handling that
  - with or without hostnames property will produce the same results
3. Annotate the Service created by the Gateway with `service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <cert arn>`, and make it a internet-facing LB (Classic or NLB both produce the same results)
4. Create HTTPRoute with RequestRedirect filter like above.
5. Create separate Service with an endpoint, like the echo example.
6. Create HTTPRoute with `backendRef` like above for the second created Service.
7. Hit HTTP AWS ELB endpoint, view network logs in dev tools to see infinite redirect loop

### Cilium Version

v1.16.1

### Kernel Version

Linux ip-10-3-3-27.us-east-2.compute.internal 5.10.219-208.866.amzn2.x86_64 #1 SMP Tue Jun 18 14:00:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.31.0
Server Version: v1.30.2-eks-db838b0

### Sysdump

Can't due to my environment.

### Anything else?

Screenshot of what the network log looks like. You can see the first one is a HTTP, then the second one is HTTPS, but then continues HTTPS redirecting to HTTPS:

<img width="1060" alt="image" src="https://github.com/user-attachments/assets/eb0d0e76-054b-480e-b482-e935106b3a1e">

Logs were obfuscated to hide my IP and any info regarding my cluster, elb, etc...

[Explore-logs-2024-08-22 17_19_05.json](https://github.com/user-attachments/files/16719275/Explore-logs-2024-08-22.17_19_05.json)
[Explore-logs-2024-08-22 16_40_55.txt](https://github.com/user-attachments/files/16719276/Explore-logs-2024-08-22.16_40_55.txt)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julian-perge** [comment]
Coming back to this, I've more or less confirmed it's a bug in Cilium.

I setup an nginx pod to listen on port 80, and both http and https requests are showing up with the $scheme `http`, and the port is _always_ 80, even if it's a https request.

```
"GET /docs/swagger-ui/swagger-ui.css HTTP/1.1" 301 169 "http://api.mydomain.com" original_scheme="http" 80

"GET /docs/swagger-ui/swagger-ui.css HTTP/1.1" 301 169 "https://api.mydomain.com" original_scheme="http" 80
```

Cilium's logic in either the `Gateway` or `HTTPRoute` is straight up not respecting the `sectionName` and/or `port` of the `listeners` in the `Gateway`. Right now the nginx `ConfigMap` is setup like this, because I have not found a way to do so otherwise with Cilium/Gateway/HTTPRoute. Unfortunately this isn't super reliable, but at least it actually does the job.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-redirect-config
data:
  nginx.conf: |
    events {}

    http {

      server {
        listen 80 default_server;
        server_name *.mydomain.com;

        return 301 https://$host$request_uri;
      }
    }
```

**Comment by julian-perge** [comment]
> 👋
> 
> Sorry for late reply, I was occupied last week. Give me something to refresh my memory with linked issues, will get back to you soon.

Any update on this?

**Comment by truongnht** [comment]
I also had the same issue. @julian-perge look like NLB tls termination does not work well with cilium implementation. My same setup works fine with ingress-nginx.

**Comment by marcofranssen** [comment]
I'm using Cilium `1.16.4`. I did get the Gateway to work with redirect, however it doesn't use the statusCode as I defined it.

**Gateway**

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: platform
  namespace: kube-system
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-name: ${resource_prefix}-gateway
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-alpn-policy: HTTP2Preferred
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${gateway_acm_certificates}
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  listeners:
    - hostname: "*.${cluster_fqdn}"
      allowedRoutes:
        namespaces:
          from: Same
      name: http
      port: 80
      protocol: HTTP
    - hostname: "*.${cluster_fqdn}"
      allowedRoutes:
        namespaces:
          from: All
      name: https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - name: gateway-http-tls
            kind: Secret
        mode: Terminate
```

**Redirect Route**

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-to-https-redirect
  namespace: kube-system
spec:
  parentRefs:
    - name: platform
      sectionName: http
  hostnames:
    - "*.${cluster_fqdn}"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
```

**A route**

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-server
  namespace: default
spec:
  parentRefs:
    - name: platform
      sectionName: http
  hostnames:
    - "*.${cluster_fqdn}"
  rules:
    - backendRefs:
        - name: echo-server
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
```

Now when navigating to the http endpoint all works, except the redirect doesn't use a `301`. Somehow it just uses a `200`.

```shell
$ curl -vL http://echo.mydomain.tld
* Host echo.mydomain.tld:80 was resolved.
* IPv6: (none)
* IPv4: x.x.x.x, x.x.x.x, x.x.x.x
*   Trying x.x.x.x:80...
* Connected to echo.mydomain.tld (x.x.x.x) port 80
> GET / HTTP/1.1
> Host: echo.mydomain.tld
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< content-type: text/plain
< date: Tue, 26 Nov 2024 07:50:01 GMT
< content-length: 301
< x-envoy-upstream-service-time: 0
< server: envoy
< 
Request served by echo-server-6bf589584-cw8st

HTTP/1.1 GET /

Host: echo.mydomain.tld
Accept: */*
User-Agent: curl/8.7.1
X-Envoy-External-Address: x.x.x.x
X-Forwarded-For: x.x.x.x
X-Forwarded-Proto: http
X-Request-Id: 9cd19dbf-7e9c-4bc8-b269-1cf0df93a7a7
* Connection #0 to host x.x.x.x left intact
```

Some other weird behavior I observe is when defining the sectionName to be excplicitly `https` it fails the HTTPRoute.

**Comment by marcofranssen** [comment]
> [@marcofranssen](https://github.com/marcofranssen) - I have a similar configuration and have the correct status code returned. The only differences I see are the hostname formatting and having `scheme: "https"` instead of `scheme: https`. Although that might not be important.

It might be related to ACM certificate instead of LetsEncrypt. Nevertheless I think there must be a solution so people can effictively use the Gateway on a Amazon deployment.

**Comment by xadhatter** [comment]
I'm running into the same issue. Let's take TLS out of the equation. With the following setup I get an infinite redirect loop. It seems like Cilium is ignoring `spec.parentRefs.sectionName`.

**Gateway**
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: default
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  listeners:
    - name: http
      port: 80
      protocol: HTTP
    - name: http-alt
      port: 8080
      protocol: HTTP
```

**Redirect**
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-filter-redirect
  namespace: default
spec:
  parentRefs:
    - name: cilium-gateway
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            port: 8080
            statusCode: 301
```

**Route**
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin
  namespace: default
spec:
  parentRefs:
    - name: cilium-gateway
      sectionName: http-alt
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /anything
      backendRefs:
        - name: httpbin
          port: 8000
```

Hitting port `80` returns the correct `301 Moved Permanently`:

```shell
curl -s -D - http://my.domain:80/anything
HTTP/1.1 301 Moved Permanently
location: http://my.domain:8080/anything
date: Thu, 23 Jan 2025 20:01:25 GMT
server: envoy
content-length: 0
```

However, using port `8080` also incorrectly returns a `301`:

```shell
curl -s -D - http://my.domain:8080/anything
HTTP/1.1 301 Moved Permanently
location: http://my.domain:8080/anything
date: Thu, 23 Jan 2025 20:02:28 GMT
server: envoy
content-length: 0
```

If I remove the redirect filter the route for `httpbin` works on both listeners, even though it specifies `http-alt`. For example, the following should not work as it uses the `http` listner on port `80`:

```shell
curl -s -D - http://my.domain:80/anything
HTTP/1.1 200 OK
access-control-allow-credentials: true
access-control-allow-origin: *
content-type: application/json; charset=utf-8
date: Thu, 23 Jan 2025 20:06:29 GMT
content-length: 671
x-envoy-upstream-service-time: 0
server: envoy
```

**Comment by xadhatter** [comment]
[This change](https://github.com/cilium/cilium/commit/29ac8befb0541a0e10e7402f4fc8b6be7854aeb7) appears to be a fix, at least for the issue I described above.

**Comment by xadhatter** [comment]
It looks like `spec.listeners.allowedRoutes` on `Gateways` is also not honored. Moving the `Gateway` and `HTTPRoutes` to different namespaces and constraining the listeners results in the same issues.

```yaml
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: kube-system
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
        kinds:
          - kind: HTTPRoute
    - name: http-alt
      port: 8080
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: default
        kinds:
          - kind: HTTPRoute
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-filter-redirect
  namespace: kube-system
spec:
  parentRefs:
    - name: cilium-gateway
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            port: 8080
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin
  namespace: default
spec:
  parentRefs:
    - name: cilium-gateway
      sectionName: http-alt
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /anything
      backendRefs:
        - name: httpbin
          port: 8000
```

**Comment by xadhatter** [comment]
The `CiliumEnvoyConfig` being generated is not correct. Here is what is produced using the setup above. It defines a single listener and seems to completely ignore the route config for `httpbin`:
```yaml
...
spec:
  backendServices:
  - name: httpbin
    namespace: default
    number:
    - "8000"
  resources:
  - '@type': type.googleapis.com/envoy.config.listener.v3.Listener
    filterChains:
    - filterChainMatch:
        transportProtocol: raw_buffer
      filters:
      - name: envoy.filters.network.http_connection_manager
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          commonHttpProtocolOptions:
            maxStreamDuration: 0s
          httpFilters:
          - name: envoy.filters.http.grpc_web
            typedConfig:
              '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
          - name: envoy.filters.http.grpc_stats
            typedConfig:
              '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig
              emitFilterState: true
              enableUpstreamStats: true
          - name: envoy.filters.http.router
            typedConfig:
              '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          internalAddressConfig:
            cidrRanges:
            - addressPrefix: 10.0.0.0
              prefixLen: 8
            - addressPrefix: 172.16.0.0
              prefixLen: 12
            - addressPrefix: 192.168.0.0
              prefixLen: 16
            - addressPrefix: 127.0.0.1
              prefixLen: 32
          rds:
            routeConfigName: listener-insecure
          statPrefix: listener-insecure
          upgradeConfigs:
          - upgradeType: websocket
          useRemoteAddress: true
    listenerFilters:
    - name: envoy.filters.listener.proxy_protocol
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol
    - name: envoy.filters.listener.tls_inspector
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
    name: listener
    socketOptions:
    - description: Enable TCP keep-alive (default to enabled)
      intValue: "1"
      level: "1"
      name: "9"
    - description: TCP keep-alive idle time (in seconds) (defaults to 10s)
      intValue: "10"
      level: "6"
      name: "4"
    - description: TCP keep-alive probe intervals (in seconds) (defaults to 5s)
      intValue: "5"
      level: "6"
      name: "5"
    - description: TCP keep-alive probe max failures.
      intValue: "10"
      level: "6"
      name: "6"
  - '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
    name: listener-insecure
    virtualHosts:
    - domains:
      - '*'
      name: '*'
      routes:
      - match:
          prefix: /
        redirect:
          portRedirect: 8080
  - '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
    connectTimeout: 5s
    edsClusterConfig:
      serviceName: default/httpbin:8000
    name: default:httpbin:8000
    outlierDetection:
      splitExternalLocalOriginErrors: true
    type: EDS
    typedExtensionProtocolOptions:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        commonHttpProtocolOptions:
          idleTimeout: 60s
        explicitHttpConfig:
          httpProtocolOptions: {}
  services:
  - listener: ""
    name: cilium-gateway-cilium-gateway
    namespace: kube-system
    ports:
    - 80
    - 8080

```

If I add a `PathPrefix` to `http-filter-redirect` things get even stranger. Instead of sending a `301` a route is created to send a `500`:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-filter-redirect
  namespace: kube-system
spec:
  parentRefs:
    - name: cilium-gateway
      sectionName: http
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /redirect
    - filters:
        - type: RequestRedirect
          requestRedirect:
            port: 8080
            statusCode: 301
```

This results in:

```yaml
...
spec:
  backendServices:
  - name: httpbin
    namespace: default
    number:
    - "8000"
  resources:
  - '@type': type.googleapis.com/envoy.config.listener.v3.Listener
    filterChains:
    - filterChainMatch:
        transportProtocol: raw_buffer
      filters:
      - name: envoy.filters.network.http_connection_manager
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          commonHttpProtocolOptions:
            maxStreamDuration: 0s
          httpFilters:
          - name: envoy.filters.http.grpc_web
            typedConfig:
              '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
          - name: envoy.filters.http.grpc_stats
            typedConfig:
              '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig
              emitFilterState: true
              enableUpstreamStats: true
          - name: envoy.filters.http.router
            typedConfig:
              '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          internalAddressConfig:
            cidrRanges:
            - addressPrefix: 10.0.0.0
              prefixLen: 8
            - addressPrefix: 172.16.0.0
              prefixLen: 12
            - addressPrefix: 192.168.0.0
              prefixLen: 16
            - addressPrefix: 127.0.0.1
              prefixLen: 32
          rds:
            routeConfigName: listener-insecure
          statPrefix: listener-insecure
          upgradeConfigs:
          - upgradeType: websocket
          useRemoteAddress: true
    listenerFilters:
    - name: envoy.filters.listener.proxy_protocol
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol
    - name: envoy.filters.listener.tls_inspector
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
    name: listener
    socketOptions:
    - description: Enable TCP keep-alive (default to enabled)
      intValue: "1"
      level: "1"
      name: "9"
    - description: TCP keep-alive idle time (in seconds) (defaults to 10s)
      intValue: "10"
      level: "6"
      name: "4"
    - description: TCP keep-alive probe intervals (in seconds) (defaults to 5s)
      intValue: "5"
      level: "6"
      name: "5"
    - description: TCP keep-alive probe max failures.
      intValue: "10"
      level: "6"
      name: "6"
  - '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
    name: listener-insecure
    virtualHosts:
    - domains:
      - '*'
      name: '*'
      routes:
      - directResponse:
          body:
            inlineString: ""
          status: 500
        match:
          pathSeparatedPrefix: /redirect
      - match:
          prefix: /
        redirect:
          portRedirect: 8080
  - '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
    connectTimeout: 5s
    edsClusterConfig:
      serviceName: default/httpbin:8000
    name: default:httpbin:8000
    outlierDetection:
      splitExternalLocalOriginErrors: true
    type: EDS
    typedExtensionProtocolOptions:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        commonHttpProtocolOptions:
          idleTimeout: 60s
        explicitHttpConfig:
          httpProtocolOptions: {}
  services:
  - listener: ""
    name: cilium-gateway-cilium-gateway
    namespace: kube-system
    ports:
    - 80
    - 8080
```

Here is a quick summary of some calls:
| URL | Expected | Actual |
| --- | ------ | -------- |
| `http://my.domain:80/` | `404` | `301` to port `8080` |
| `http://my.domain:8080/` | `200` from `httpbin` | `301` to port `8080` (loop) |
| `http://my.domain:80/redirect` | `301` to port `8080` | `500` |
| `http://my.domain:8080/redirect` | `404` from `httpbin` | `500` |
| `http://my.domain:80/anything` | `404` | `301` to port `8080` |
| `http://my.domain:8080/anything` | `200` from `httpbin` | `301` to port `8080` (loop) |
