### ISSUE TITLE
Ingress: rules are ignored if defaultBackend is specified

### ISSUE THREAD

**Issue by judge-red** [cilium/cilium#34553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.15.7 and lower than v1.16.0

### What happened?

We have an ingress with the following `.spec`:
```
spec:
  defaultBackend:
    service:
      name: dashboard
      port:
        number: 80
  ingressClassName: cilium
  rules:
  - host: website.url
    http:
      paths:
      - backend:
          service:
            name: api
            port:
              number: 80
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: dashboard
            port:
              number: 80
        path: /
        pathType: Prefix
```

This doesn't work as expected, calls to `website.url/api` are sent to the `dashboard` service.

However, if we remove the `defaultBackend`, it starts working as expected.

We've previously used `ingress-nginx` as our ingress controller and this worked fine. 

### How can we reproduce the issue?

Install Cilium, enable the built-in ingress controller, create an ingress resource that has both a `defaultBackend` and `rules`. Try accessing a backend that is covered by a rule that is not identical to the defaultBackend.

### Cilium Version

```
cilium-cli: v0.16.15 compiled with go1.22.6 on darwin/arm64
cilium image (default): v1.16.0
cilium image (stable): v1.16.1
cilium image (running): 1.15.8
```

### Kernel Version

```
Linux sck-staging-scc-zhw-pool-ubuntu-jammy-0-5b88498ff6-8dx2b 5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.30.4
```

### Sysdump

~https://drive.switch.ch/index.php/s/84X8FAJ4nFrBS3t/download~
https://drive.switch.ch/index.php/s/veVExBHdHLRgINE/download

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
Thanks for your issue, this could be a bug in Cilium implementation.

**Comment by judge-red** [comment]
Hi @sayboras, thanks for having a look at this issue quickly. I'm new to how issues are handled in Cilium, does this mean someone is going to work on a fix shortly or could it take a while? Just wondering whether we should wait for like the next Cilium patch release, or rather go back to ingress-nginx for now and just be patient.

**Comment by sayboras** [comment]
:wave: 

Normally, it depends on how severe the issue is, and how much bandwidth/cycles we have, a lot of times, contributors are helping with the patches as well. :1st_place_medal: :+1: (Shout out to all the contributors).

I did a initial triage for this issue, but didn't have time to dig further to find out the related code paths. Will share my update here later (unless someone else is getting to it first).

**Comment by sayboras** [comment]
Just curious if you have tried with the latest release v1.16.1.

I am trying with main branch, but it seems working as expected

```
// Backend from http rules
$ curl --resolve "bookinfo.com:80:$lb" http://bookinfo.com/       
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Bookstore App</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="static/bootstrap/css/bootstrap.min.css">
...
$ curl --resolve "bookinfo.com:80:$lb" http://bookinfo.com/details/1
{"id":1,"author":"William Shakespeare","year":1595,"type":"paperback","pages":200,"publisher":"PublisherA","language":"English","ISBN-10":"1234567890","ISBN-13":"123-1234567890"}% 
...

// Default backend
$ curl http://$lb/                                                  
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Bookstore App</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="static/bootst
...
```


Ingress manifest

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: default
spec:
  ingressClassName: cilium
  defaultBackend:
    service:
      name: productpage
      port:
        number: 9080
  rules:
    - host: bookinfo.com
      http:
        paths:
          - backend:
              service:
                name: details
                port:
                  number: 9080
            path: /details
            pathType: Prefix
          - backend:
              service:
                name: productpage
                port:
                  number: 9080
            path: /
            pathType: Prefix
```

**Comment by judge-red** [comment]
No, I haven't. v1.15.8 is the latest we have anywhere at the moment. But I think I also haven't seen anything in the v1.16.0 or v1.16.1 changelogs that could have addressed this, but I didn't study the changelog in detail.

So if you can't reproduce it, I wonder - well, first of all of course whether I missed something in the changelog, but also - if some settings in Cilium could influence this.

Is this ingress turned into an envoy config somewhere that we could look at or some other way to debug why traffic is routed somewhere and not somewhere else?

**Comment by sayboras** [comment]
> Is this ingress turned into an envoy config somewhere that we could look at or some other way to debug why traffic is routed somewhere and not somewhere else?

There is a file called cilium-envoy.json in the sysdump, in which we can confirm the routing logic. I did take a look into attached sysdump, the only potential issue I got is two backends (dashboard and oauth), but it might be something else as you might probably simplify the configurations and names in issue description.

**Comment by judge-red** [comment]
I simplified the naming slightly for this bug report, yea. Instead of `api` it should be `kubermatic-api` and instead of `dashboard` it should be `kubermatic-dashboard`. This is the `kubermatic` ingress in the `kubermatic` namespace.

`oauth` is the namespace of another ingress resource. There are 6 ingresses (all with ingressClass=cilium) in this cluster. 4 have no `defaultBackend` defined at all, one has a `defaultBackend` but just a single rule that points at the same backend as the default backend, and finally the one discusses in my report here: it has a `defaultBackend`, one rule that points at the same backend plus one rule that points at another backend.

>  the only potential issue I got is two backends (dashboard and oauth)

So if you meant "default backends", that's true. But all backends combined would total to 7.

I couldn't find `cilium-envoy.json` in the sysdump, but I found `ciliumenvoyconfigs-20240823-174451.yaml`. I'm not familiar with Envoy, but I do see 7 backends. And ... oh no ... I just noticed I took the sysdump after finishing my testing, but apparently before reverting my temporary changes, so I think they `defaultBackend` this report is about is missing, and there's some strange domain/hostname used in the ingress 🤦‍♂️ Sorry about that, I'll upload a new sysdump momentarily.

**Comment by judge-red** [comment]
New sysdump: https://drive.switch.ch/index.php/s/veVExBHdHLRgINE

**Comment by judge-red** [comment]
Maybe more of a side note as I don't think this explains my problem but it's a first major difference I found between how ingress-nginx and Cilium handle the `defaultBackend` defined in an ingress resource.
- Cilium will treat every `defaultBackend` of every ingress it controls as 1) equal, 2) global (i.e. the host is `*`)
- ingress-nginx will treat the `defaultBackend` of an ingress as the default of the `/` path for every host that is defined in any rule in the same ingress (i.e. specific domains, _not_ `*`). If a `defaultBackend` is specified but no rules are defined in the same ingress, it will behave the same as Cilium, I think.

That's a major difference. I would intuitively expect ingress-nginx' approach, but I can't say Cilium is wrong. Furthermore, I don't think Kubernetes defined the correct behavior, so implementation specific behavior is acceptable.

However, I don't think this explain the issue I'm seeing. If I understand Envoy correctly, the `*` listener will not be used if another listener with a more specific domain matches, so it shouldn't cause the issue I'm seeing. Plus, we have two ingresses with a defaultBackend, so removing one would not have resolved my issue.

But maybe it's a puzzle piece in the solution, so I wanted to bring it up.

**Comment by sayboras** [comment]
Oh thanks a lot for your clarification. 

> That's a major difference. I would intuitively expect ingress-nginx' approach, but I can't say Cilium is wrong. Furthermore, I don't think Kubernetes defined the correct behavior, so implementation specific behavior is acceptable.

We have the Ingress conformance tests running in CI, as the tests are passing, I assume that Cilium implementation is following the below. It's not clear for the case of multiple default backends in multiple Ingress though :thinking:

https://github.com/kubernetes-sigs/ingress-controller-conformance/blob/d920ed36a0076e169a9a329a850844ab3a695ae8/features/default_backend.feature#L6-L7

**Comment by judge-red** [comment]
Yea, that's kind of what I meant - I think Kubernetes defined it vague enough such that ingress-nginx and Cilium are probably both conformant. But it should be fairly easy to come up with an example where the routing to a request will look very differently.

I don't think this is supposed to be implementation specific, but the definition isn't specific enough to avoid it.

Anyway, as I said, I don't think this can explain the behavior I'm seeing.

**Comment by judge-red** [comment]
Alright, so back to my issue and bug report. In the new sysdump, we can find the `kubermatic` ingress in the file `ciliumingresses-20240829-135539.yaml`, here's its `spec`:
```
  spec:
    defaultBackend:
      service:
        name: kubermatic-dashboard
        port:
          number: 80
    ingressClassName: cilium
    rules:
    - host: sck-staging.cloud.switch.ch
      http:
        paths:
        - backend:
            service:
              name: kubermatic-api
              port:
                number: 80
          path: /api
          pathType: Prefix
        - backend:
            service:
              name: kubermatic-dashboard
              port:
                number: 80
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - sck-staging.cloud.switch.ch
      secretName: kubermatic-tls
```

So for the host `sck-staging.cloud.switch.ch`, there's a rule each for the paths `/` and `/api`.

Now looking at the file `ciliumenvoyconfigs-20240829-135539.yaml`, we can find the backends for these rules:
```
    - name: kubermatic-api
      namespace: kubermatic
      number:
      - "80"
    - name: kubermatic-dashboard
      namespace: kubermatic
      number:
      - "80"
```

We can also find cluster definitions - honestly:
```
    - '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
      connectTimeout: 5s
      edsClusterConfig:
        serviceName: kubermatic/kubermatic-api:80
      name: kubermatic:kubermatic-api:80
      outlierDetection:
        splitExternalLocalOriginErrors: true
      type: EDS
      typedExtensionProtocolOptions:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          commonHttpProtocolOptions:
            idleTimeout: 60s
          useDownstreamProtocolConfig:
            http2ProtocolOptions: {}
    - '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
      connectTimeout: 5s
      edsClusterConfig:
        serviceName: kubermatic/kubermatic-dashboard:80
      name: kubermatic:kubermatic-dashboard:80
      outlierDetection:
        splitExternalLocalOriginErrors: true
      type: EDS
      typedExtensionProtocolOptions:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          commonHttpProtocolOptions:
            idleTimeout: 60s
          useDownstreamProtocolConfig:
            http2ProtocolOptions: {}
```

But looking at the RouteConfigurations, we have this one:
```
      - domains:
        - sck-staging.cloud.switch.ch
        - sck-staging.cloud.switch.ch:*
        name: sck-staging.cloud.switch.ch
        routes:
        - match:
            prefix: /
          route:
            cluster: kubermatic:kubermatic-dashboard:80
            maxStreamDuration:
              maxStreamDuration: 0s
```

... but there is none for the `/api` path? This sounds like our bug!

And indeed, when I removed the `defaultBackend` from the `kubermatic` ingress, this RouteConfiguration changes to the following:
```
    - domains:                        
      - sck-staging.cloud.switch.ch
      - sck-staging.cloud.switch.ch:*     
      name: sck-staging.cloud.switch.ch
      routes:                     
      - match:                                                                                           
          pathSeparatedPrefix: /api                                                                      
        route:                    
          cluster: kubermatic:kubermatic-api:80
          maxStreamDuration:        
            maxStreamDuration: 0s 
      - match:                                                                                           
          prefix: /   
        route:       
          cluster: kubermatic:kubermatic-dashboard:80
          maxStreamDuration:                
            maxStreamDuration: 0s
```

... no wonder it works as expected now :)
