### ISSUE TITLE
Private network interface not responding to pod IPs ARP queries

### ISSUE THREAD

**Issue by 0xalex88** [cilium/cilium#34556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Hi everyone, we're trying to create a cluster mesh between three AWS EKS clusters and a cluster running on dedicated servers.

Everything worked fine until we've switched from tunnel mode to native routing mode (we wanted to avoid the overhead since we have full routing via site-to-site VPNs).

While all the AWS EKS clusters pods can communicate between each other with no issues, the traffic that goes from/to a pod on the dedicated server cluster and the other clusters is dropped, for example:
 - dedicated cluster pod http request towards AWS: on the VPN gateway we see the SYN packet going to AWS, the ACK one coming back and then being nothing else
 - AWS pod http request towards the dedicated cluster pod: SYN packet reaches the gateway, gateway does an ARP request for the pod IP, but the host running that pod doesn't respond with the private interface MAC address
 - communications between pods within the dedicated server cluster: works

on AWS we use the ENI ipam mode and on the dedicated cluster the cluster-pool one.

Is cilium supposed to configure the pod IP/CIDR on the private network interface and/or bridge it with the cilium_host network interface? Or is there any way to tell it that the pod CIDR is natively routable through the private interface?

I've attached the helm config and the sysdump, please let me know if there's anything that I can provide to help troubleshooting

### How can we reproduce the issue?

Install cilium with the provided helm flags:

```yaml
cluster:
  name: "onprem"
  id: 4

ipv4:
  enabled: true

l2announcements:
  enabled: true
k8sClientRateLimit:
  qps: 10
  burst: 20
kubeProxyReplacement: true
k8sServiceHost: "10.16.0.3" # master IP
k8sServicePort: "6443"

ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList: ["10.16.32.0/19"]
    clusterPoolIPv4MaskSize: 26

k8s:
  requireIPv4PodCIDR: true

autoDirectNodeRoutes: true
routingMode: native
endpointRoutes:
  enabled: true

ipv4NativeRoutingCIDR: "10.16.32.0/19"

bpf:
  tproxy: true
  preallocateMaps: true
  masquerade: true
  lbExternalClusterIP: true

ipMasqAgent:
  enabled: true

enableIPv4Masquerade: true

externalIPs:
  enabled: true

securityContext: # Required by talos OS
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

operator:
  replicas: 1
  rollOutPods: true

rollOutCiliumPods: true

clustermesh:
  useAPIServer: true
  apiserver:
    kvstoremesh:
      enabled: false
    service:
      type: NodePort
  config:
    enabled: true

hubble:
  enabled: true
  ui:
    enabled: true
    rollOutPods: true
  relay:
    enabled: true
    rollOutPods: true

ingressController:
  enabled: true
  loadbalancerMode: shared
  default: true
  service:
    type: NodePort

policyEnforcementMode: "always"
```

### Cilium Version

1.16.1

### Kernel Version

6.6.28-talos (@buildkitsandbox) (gcc (GCC) 13.2.0, GNU ld (GNU Binutils) 2.42) #1 SMP Thu Apr 18 16:21:02 UTC 2024

### Kubernetes Version

1.30.0

### Sysdump

[cilium-sysdump-20240823-115643.zip](https://github.com/user-attachments/files/16732694/cilium-sysdump-20240823-115643.zip)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
