### ISSUE TITLE
Probes Calling to Localhost Fails as soon as L7 Network Policies are Configured

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [cilium/cilium#34564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.14.13 and lower than v1.15.0

### What happened?

My service has a startup probe which simply calls `localhost:18000`. As soon as I configure a L7 network policy on any port, the startup probe fails with the following error.

```
Warning  Unhealthy  5s (x2 over 10s)  kubelet            Startup probe failed: timeout: failed to connect service "localhost:18000" within 3s
```

This happens to any probes where it tries to connect to localhost. 

Here is the configured L7 network policy.

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-comm-my-service
spec:
  endpointSelector:
    matchLabels:
      service.name: my-service
  ingress:
    - fromEndpoints:
        - matchLabels:
            service.name: first-service
      toPorts:
        - ports:
            - port: "18000"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
        - matchLabels:
            service.name: another-service
      toPorts:
        - ports:
            - port: "18000"
              protocol: TCP
          rules:
            http: [{}] # L7 rule
    - toEndpoints:
        - matchLabels:
            service.name: other-service
      toPorts:
        - ports:
            - port: "9443"
              protocol: TCP
          rules:
            http: []
    - toFQDNs:
        - matchName: google.com
```

I even tried allowing communication to the port `18000` using ingress and egress rules from and to the `host`

```yaml
  ingress:
    - fromEntities:
        - host
      toPorts:
        - ports:
            - port: "18000"
              protocol: TCP
```

```yaml
  egress:
    - toEntities:
        - host
      toPorts:
        - ports:
            - port: "18000"
              protocol: TCP
```

However, this changed nothing.

### How can we reproduce the issue?

1. Create a service with a readiness/startup probe which communicates to the `/health` endpoint in localhost.
2. Apply a L7 rule on any of your service's port

### Cilium Version

1.14.12

### Kernel Version

5.15.0-1064-azure

### Kubernetes Version

1.28.5

### Relevant log output

```shell
Warning  Unhealthy  3s (x4 over 18s)  kubelet            Startup probe failed: timeout: failed to connect service "localhost:18000" within 3s
```

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
