### ISSUE TITLE
Upgrade 1.16.1 breaks networkpolicy on mode: eni

### ISSUE THREAD

**Issue by DingGGu** [cilium/cilium#34615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

## In my case
1. Destination pod was default deny ingress and egress in backend namespace.
2. backend application allow ingress from frontend namespace.
3. See below example of NetworkPolicy.

After upgrade Cilium 1.16.1 from 1.14.11.
Network policy does not work across workload.
A traffic flow got a timeout through frontend to backend.

I have two clusters, cluster has same workload except cilium version.
The cluster that cilium 1.14.11 is work well. otherwise not work.

## Information of cilium
1. There is difference status from cilium.

```
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.30+ (v1.30.3-eks-a18cd3a) [linux/amd64]
Kubernetes APIs:        ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumLocalRedirectPolicy", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   True   [ens5    (Direct Routing), pod-id-link0    169.254.170.23 fd00:ec2::23 , ens6   ]
Host firewall:          Disabled
SRv6:                   Disabled
CNI Chaining:           none
CNI Config file:        successfully wrote CNI configuration file to /host/etc/cni/net.d/05-cilium.conflist
Cilium:                 Ok   1.16.1 (v1.16.1-68579055)
NodeMonitor:            Listening for events on 48 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok
IPAM:                   IPv4: 31/42 allocated,
IPv4 BIG TCP:           Disabled
IPv6 BIG TCP:           Disabled
BandwidthManager:       Disabled
Routing:                Network: Native   Host: BPF
Attach Mode:            Legacy TC
Device Mode:            veth
Masquerading:           BPF   [ens5, pod-id-link0, ens6]  /16 [IPv4: Enabled, IPv6: Disabled]
Controller Status:      204/205 healthy
  Name                         Last success   Last error   Count   Message
  node-neighbor-link-updater   1h38m17s ago   1s ago       109     unable to determine next hop IPv4 address for pod-id-link0 (): remote node IP is non-routable
unable to determine next hop IPv4 address for ens6 (): remote node IP is non-routable
unable to determine next hop IPv4 address for pod-id-link0 (): remote node IP is non-routable
unable to determine next hop IPv4 address for ens6 (): remote node IP is non-routable
unable to determine next hop IPv4 address for pod-id-link0 (): remote node IP is non-routable
unable to determine next hop IPv4 address for ens6 (): remote node IP is non-routable
unable to determine next hop IPv4 address for pod-id-link0 (): remote node IP is non-routable
```
- You can see `pod-id-link0` network interface detected from cilium.
- As you know, pod-id-link0 is managed by EKS Pod Identity Agent.
- Also remote node IP is non-routable error was appeared. 1.14 does not have.

2. Identified source workload is showing remote node's primary ip.

Starting from 1.16, The source workload is identified by the primary IP of a remote node where the frontend pod is located, not the frontend pod IP.

```
# Cilium 1.16
Policy verdict log: flow 0x447c3041 local EP ID 2187, remote ID remote-node, proto 6, ingress, action deny, auth: disabled, match none, <redact-remote-node-primary-ip>:42230 -> <redact-backend>:3000 tcp SYN
xx drop (Policy denied) flow 0x447c3041 to endpoint 2187, ifindex 2, file bpf_lxc.c:2063, , identity remote-node->52757: <redact-remote-node-primary-ip>:42230 -> <redact-backend>:3000 tcp SYN
```

```
# Cilium 1.14
Policy verdict log: flow 0x991fc9c local EP ID 3333, remote ID 24596, proto 6, ingress, action allow, auth: disabled, match L3-Only, <redact-frontend>:42432 -> <redact-backend>:3000 tcp SYN
-> endpoint 3333 flow 0x991fc9c , identity 24596->32420 state new ifindex lxcebd9bc7161e3 orig-ip <redact-frontend>: <redact-frontend>:42432 -> <redact-backend>:3000 tcp SYN
-> network flow 0x2ab79045 , identity 32420->24596 state reply ifindex ens7 orig-ip 0.0.0.0: <redact-backend>:3000 -> <redact-frontend>:42432 tcp SYN, ACK
-> endpoint 3333 flow 0x991fc9c , identity 24596->32420 state established ifindex lxcebd9bc7161e3 orig-ip <redact-frontend>: <redact-frontend>:42432 -> <redact-backend>:3000 tcp ACK
-> endpoint 3333 flow 0x991fc9c , identity 24596->32420 state established ifindex lxcebd9bc7161e3 orig-ip <redact-frontend>: <redact-frontend>:42432 -> <redact-backend>:3000 tcp ACK
-> network flow 0x2ab79045 , identity 32420->24596 state reply ifindex ens7 orig-ip 0.0.0.0: <redact-backend>:3000 -> <redact-frontend>:42432 tcp ACK
```

I confirmed all workload is managed by Cilium.

### How can we reproduce the issue?

Install Cilium 1.16.1

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default
  namespace: backend
spec:
  endpointSelector:
    matchLabels: {}
  ingress: []
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s:k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: '*'
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: frontend
  namespace: backend
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: backend
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: frontend
```

### Cilium Version

1.16.1

### Kernel Version

```
Ubuntu 22.04
Linux ip-10-70-78-143 6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

EKS 1.30

### Regression

Rollback to 1.14 work properly.

### Anything else?

- EKS Pod Identity Agent using 169.254.170.23, and daemonset create Ethernet `pod-ip-link0` on each node. https://docs.aws.amazon.com/eks/latest/userguide/pod-id-agent-setup.html
- Starting from EKS 1.30, OS is upgraded to Amazon Linux 2023 from AL2, Ubuntu 22.04 from Ubuntu 20.04
- Maybe related with https://github.com/cilium/cilium/issues/34528

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
