### ISSUE TITLE
CI failure: guestbook cannot netcat to redis in spite of policy

### ISSUE THREAD

**Issue by eloycoto** [cilium/cilium#3462]
Jenkins failures: 
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/515/

[K8sValidatedPolicyTestGuestBookExamplescheckspolicyexample.zip](https://github.com/cilium/cilium/files/1868662/K8sValidatedPolicyTestGuestBookExamplescheckspolicyexample.zip)

**Comment by ianvernon** [comment]
Failure output:
```
/root/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:270
Web pod "guestbook-6b4d7" cannot connect to redis
Expected
    <bool>: false
to be true
/root/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/k8sT/Policies.go:591
```

**Comment by ianvernon** [comment]
From the Console Output (in Jenkins job link in the description), the following policies were imported into Cilium:

`test/k8sT/manifests/guestbook-policy-web.json`:
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "guestbook-web"
spec:
  endpointSelector:
    matchLabels:
      k8s-app.guestbook: web
  ingress:
  - fromEndpoints:
    - matchLabels:
        "reserved.world": ""
    toPorts:
    - ports:
      - port: "3000"
        protocol: TCP
```

any pod with label `k8s-app.guestbook:web` should be able to receive ingress from `reserved.world` on port 3000.

`test/k8sT/manifests/guestbook-policy-redis.json`

```
{
  "apiVersion": "networking.k8s.io/v1",
  "kind": "NetworkPolicy",
  "metadata": {
    "name": "guestbook-redis"
  },
  "spec": {
    "podSelector": {
      "matchLabels": {
        "k8s-app.guestbook": "redis"
      }
    },
    "ingress": [
      {
        "from": [
          {
            "podSelector": {
              "matchLabels": {
                "k8s-app.guestbook": "web"
              }
            }
          },
          {
            "podSelector": {
              "matchLabels": {
                "k8s-app.guestbook": "redis"
              }
            }
          }
        ],
        "ports": [
          {
            "protocol": "TCP",
            "port": 6379
          }
        ]
      }
    ]
  }
}
```

Thus, it is expected that any pod with label `k8s-app.guestbook=redis` can receive traffic from `k8s-app.guestbook=web` OR label  `k8s-app.guestbook=redis` on port 6379.

The function in the test that failed was:
```
testConnectivitytoRedis := func() {
			webPods, err := kubectl.GetPodsNodes(helpers.DefaultNamespace, "-l k8s-app.guestbook=web")
			Expect(err).To(BeNil(), "Cannot get web pods")

			for pod := range webPods {
				command := `nc redis-master 6379 <<EOF
							PING
							EOF`
				res := kubectl.ExecPodCmd(helpers.DefaultNamespace, pod, command)
				ExpectWithOffset(1, res.WasSuccessful()).To(BeTrue(),
					"Web pod %q cannot connect to redis", pod)
			}
		}
```

Which tests netcat onto port 6379 redis-master from pods with label  `k8s-app.guestbook=web`.
