### ISSUE TITLE
The error "upstream server temporarily disabled while SSL handshaking to upstream" occurs when the Nginx Porxy Cilium Gateway API is used

### ISSUE THREAD

**Issue by jieshiyeskey** [cilium/cilium#34657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

```
The error "upstream server temporarily disabled while SSL handshaking to upstream" occurs when the Nginx agent Cilium Gateway API is used
```

### How can we reproduce the issue?

1.Configure in cilium
```
gatewayAPI:
  enabled: true
  hostNetwork:
    enabled: true
    nodes:
      matchLabels:
        role: infra
        component: gateway-api
```
2. Refer to the official deployment of the bookinfo application
3. Write and apply Gateway and HTTPRoute (Note: A certificate has been added, and the certificate is applied for on a third-party platform.)

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  gatewayClassName: cilium
  listeners:
  - name: https-bookinfo
    port: 2443
    protocol: HTTPS
    hostname: "bookinfo.youlai.net"
    tls:
      certificateRefs:
      - kind: Secret
        name: tlscred
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bookinfo
spec:
  parentRefs:
  - name: bookinfo-gateway
  hostnames:
    - bookinfo.youlai.net
  rules:
  - matches:
    - path:
        type: Exact
        value: /productpage
    - path:
        type: PathPrefix
        value: /static
    - path:
        type: Exact
        value: /login
    - path:
        type: Exact
        value: /logout
    - path:
        type: PathPrefix
        value: /api/v1/products
    backendRefs:
    - name: productpage
      port: 9080
```
#### Use https://bookinfo.youlai.net:2344/productgpage to access is normal at the moment. (The domain name resolves to the IP address of the labeled node)

4.Proxy the above server on NGINX (Note: Certificate as above)
```
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log notice;
pid /run/nginx.pid;

include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    keepalive_timeout   65;
    types_hash_max_size 4096;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;


    include /etc/nginx/conf.d/*.conf;
    upstream cilium-pools-https {
       server 172.16.0.41:2443;
       server 172.16.0.42:2443;
       server 172.16.0.43:2443;
    }

    server {
        listen       80;
        listen       [::]:80;
        server_name  bookinfo.youlai.net;

        location / {
          return 301 https://$server_name$request_uri;
        }
    }

# Settings for a TLS enabled server.
   server {
        listen       443 ssl http2;
        listen       [::]:443 ssl http2;
        server_name  bookinfo.youlai.net;

        ssl_certificate "/etc/nginx/pki/youlai_net.crt";
        ssl_certificate_key "/etc/nginx/pki/youlai_net.key";
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  10m;


        location / {
          proxy_pass                              https://cilium-pools-https;
          proxy_http_version                      1.1;
          # proxy_ssl_name                        $host;
          # proxy_ssl_certificate                   "/etc/nginx/pki/youlai_net.crt";
          # proxy_ssl_certificate_key               "/etc/nginx/pki/youlai_net.key";
          # proxy_ssl_ciphers                        HIGH:!aNULL:!MD5;
          # proxy_ssl_trusted_certificate          "/etc/nginx/pki/youlai_net.crt";

          # proxy_ssl_verify                        on;
          # proxy_ssl_verify_depth                  2;
          # proxy_ssl_session_reuse                 on;
          # proxy_ssl_server_name                   on;

          proxy_cache_bypass                      $http_upgrade;
          proxy_set_header Upgrade                $http_upgrade;
          proxy_set_header Connection             "upgrade";
          proxy_set_header Host                   $host;
          proxy_set_header X-Real-IP              $remote_addr;
          proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto      $scheme;
          proxy_set_header X-Forwarded-Host       $host;
          proxy_set_header X-Forwarded-Port       $server_port;
        }
   }
}
```

### Cilium Version

```
cilium-cli:  compiled with go1.23.0 on linux/amd64
cilium image (default): v1.16.0
cilium image (stable): v1.16.1
cilium image (running): 1.16.1
```

### Kernel Version

```
Linux cn-cp-1 6.6.0-39.0.0.47.oe2403.x86_64 #1 SMP Wed Aug 28 15:00:00 CST 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.31.0
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
