### ISSUE TITLE
Can't get CiliumNetoworkPolicy to work as a firewall

### ISSUE THREAD

**Issue by bernardgut** [cilium/cilium#34776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?
EDIT: created a separate issue for tracking what is left of this issue here https://github.com/cilium/cilium/issues/34786 since I partly figured out the original issue. closing this one.

I tried many combinations but it essentially boils down to this :

I have an IPv6 only cluster with Cilium configured in kubernetes ipam, with dedicated kube-proxy loadbalancer replacement. 

I created a minio service from helm and since minio services exposes 2 ports (9000 for the service, and 9001 for the admin console), I created 2 ingresses `minio` (9000) and `minio-svc` (9001) when I do the following configuration to restrict access to 9001 :

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: minio-svc
  namespace: minio
  labels:
    app.kubernetes.io/instance: minio
spec:
  rules:
  - host: s3-svc.hostname.co
    http:
      paths:
      - backend:
          service:
            name: minio
            port:
              number: 9001
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - s3-svc.hostname.co
    secretName: s3-svc.hostname.co-tls
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: minio-svc-whitelist
  namespace: minio
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: minio
  ingress:
  - fromCIDR:
    - "192.168.200.0/24"
    - "2a02:XXXX:XXXX:2::/64"
  - toPorts:
    - ports:
      - port: "443"
        protocol: TCP
      - port: "80"
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: minio
  namespace: minio
spec:
  rules:
  - host: s3.hostname.co
    http:
      paths:
      - backend:
          service:
            name: minio
            port:
              number: 9000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - s3.hostname.co
    secretName: s3.hostname.co
```

This creates additional cilium-ingress-** svc for both ingresses as expected. However The policy doesn't work and the console is still available on the internet on the public endpoint  (tested with https://www.mythic-beasts.com/ipv6/health-check) :
```
Secure web server IPv6 connectivity
Trying to get https://s3-svc.hostname.co from 2a02:XXXX:XXXX:0:c0:0:0:5...
200 OK
```

shouldnt this show 401 ?

### How can we reproduce the issue?

1. Install cilium with helm with the following config (ignore commented lines)
```
# disable the kube-proxy
kubeProxyReplacement: true
# stacks settings
routingMode: native
ipv4:
  enabled: true
ipv4NativeRoutingCIDR: 10.229.0.0/16 # podSubnet
enableIPv4BIGTCP: true
#enableIPv4Masquerade: false
autoDirectNodeRoutes: true
ipv6:
  enabled: true
enableIPv6BIGTCP: true
#enableIPv6Masquerade: false
ipv6NativeRoutingCIDR: fd00:0:a:1000::/64 # podSubnet
# optimizations
bpf:
  # TODO: requires kernel 6.8+ Enable when available
  # datapathMode: netkit 
  masquerade: true
bandwidthManager:
  enabled: true
  bbr: true
ipam:
  mode: kubernetes
loadBalancer:
  algorithm: maglev
  #mode: hybrid # https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#direct-server-return-dsr
  # acceleration: best-effort # only enables XDP on devices that support it. Should work on HW devices. not on Wireguard
# if maglev is enabled:
maglev:
  tableSize: 4093 # default is 16381 but we have a small cluster. here we support up to 40 backends for 1 service
  hashSeed: 8vhAoJqAgVT0iVSP
# BGP
bgpControlPlane:
  enabled: true
# Ports Allowed
externalIPs:
  enabled: true
# Cilium
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETUID
      - SETGID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cgroup:
  hostRoot: /sys/fs/cgroup
  autoMount:
    enabled: false
# Enable Cilium Ingress Controller
ingressController:
  enabled: true
  default: true
  #loadbalancerMode: shared #TODO disable this if you go to IPv6
# Use KubePrism to access cluster API
k8sServiceHost: localhost
k8sServicePort: 7445
# OR
# Use IPv6 to access cluster API (for IPv6 only clusters)
#k8sServiceHost: ::1 # virtual IP
#k8sServicePort: 6443
# Enable Cilium Operator
operator:
  replicas: 1
# enable gatewayAPI
gatewayAPI:
  enabled: true
# Security
# disabled as it messes with drpd quorum
# encryption:
#   enabled: true
#   type: wireguard
#   strictMode:
#     enabled: true
#     cidr: 10.229.0.0/16 # podSubnet
    # TODO: enable IPv6 as well when Available

# Enable Hubble
hubble:
  enabled: true
...etc
```
2. create a minio deployment from bitnami, edit the default svc with SingleStack and IPv6
3. apply the above config to expose your ports.

### Cilium Version

quay.io/cilium/cilium:v1.16.1@sha256:0b4a3ab41a4760d86b7fc945b8783747ba27f29dac30dd434d94f2c9e3679f39

### Kernel Version

6.6.43-talos

### Kubernetes Version

1.30.1

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
