### ISSUE TITLE
East-west routed traffic using GAMMA goes through the `ingress` chain, preventing the use of network policies

### ISSUE THREAD

**Issue by marcin-ro** [cilium/cilium#34774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

I set up a small set of pods and services from scratch to try out east-west routing with network policies.  It turns out that when traffic goes through a Service with an HTTPRoute attached, it completely bypasses the egress network policy on the source pod, and arrives to the destination pod from the `ingress` entity effectively hiding the identity of the source pod and making the ingress network policy on the destination pod ineffective.

### How can we reproduce the issue?

I started with a cilium set up with gateway API enabled, and set up three pods: client, nginx, and httpbin.  nginx and httpbin have corresponding Services, s-nginx and s-httpbin, and I added an HTTPRoute to s-nginx so that requests with a specific header go to s-httpbin instead of the nginx pod.

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: marcin-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-nginx
  namespace: marcin-nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: s-nginx
  namespace: marcin-nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
      appProtocol: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-client
  namespace: marcin-nginx
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-httpbin
  namespace: marcin-nginx
spec:
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - name: httpbin
          image: mccutchen/go-httpbin
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: s-httpbin
  namespace: marcin-nginx
spec:
  selector:
    app: httpbin
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
      appProtocol: http
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: httpbin-allow-from-nginx
  namespace: marcin-nginx
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: marcin-nginx
  to:
  - group: ""
    kind: Service
    name: s-httpbin
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-to-httpbin
  namespace: marcin-nginx
spec:
  parentRefs:
  - kind: Service
    group: ""
    name: s-nginx
    port: 80
  rules:
  - matches:
    - headers:
      - type: Exact
        name: goto
        value: httpbin
    backendRefs:
    - name: s-httpbin
      namespace: marcin-nginx
      port: 80
  - backendRefs:
    - name: s-nginx
      port: 80
```

Then I `kubectl -n marcin-nginx exec -ti deployment/d-client -- /bin/bash` and try to `curl http://s-nginx`.  At this stage, things work as expected.  But then I tried to add network policies to control traffic at both ends (I experimented with multiple shapes of these, this is just a minimal one):

```
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: np-client
  namespace: marcin-nginx
spec:
  endpointSelector:
    matchLabels:
      app: client
  egress:
  - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          k8s-app: kube-dns
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: np-nginx
  namespace: marcin-nginx
spec:
  endpointSelector:
    matchLabels:
      app: nginx
  ingress: []
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: np-httpbin
  namespace: marcin-nginx
spec:
  endpointSelector:
    matchLabels:
      app: httpbin
  ingress: []
```

These policies are ineffective.  They kick in only after I `kubectl delete -n marcin-nginx httproute nginx-to-httpbin`.  Looking at hubble output, requests that go through a Service with an HTTPRoute attached sidestep any egress policies on the source pod and  arrive at the destination pod from the entity `ingress`.

### Cilium Version

1.16.0

### Kernel Version

`Linux [...] 6.1.97-104.177.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jul 16 15:18:45 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

EKS.

```
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.12-eks-2f46c53
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
