### ISSUE TITLE
Incorrect priority ordering between redirect and allow policies

### ISSUE THREAD

**Issue by hemanthmalla** [cilium/cilium#34834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.15.7 and lower than v1.16.0

### What happened?

When an endpoint has both allow and redirect policies applied to it, allow policy seems to be taking precedence over redirect. As a result redirection to DNS proxy is bypassed and breaks toFQDN policy in place.

Here are the two policies to repro the issue.

```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: cluster-egress-to-dns
specs:
  egress:
  - toCIDR:
    - 169.254.20.10/32
    toPorts:
    - ports:
      - port: "53"
  enableDefaultDeny:
    egress: false
  endpointSelector:
    matchLabels: {}
```

```
 apiVersion: cilium.io/v2
 kind: CiliumNetworkPolicy
 metadata:
   name: allow-blob-storage
 specs:
   egress:
   - toCIDR:
     - 169.254.20.10/32  # We only want to allow resolutions from NLD
     toPorts:
     - ports:
       - port: "53"
         protocol: ANY
       rules:
         dns:
         - matchPattern: '*'
   - toFQDNs:
     - matchPattern: '*.s3.amazonaws.com'
     toPorts:
     - ports:
       - port: "443"
         protocol: TCP
   endpointSelector: {}
```

```
root@<>:/home/cilium# cilium status --all-redirects
....
Proxy Status:           OK, ip <>, 6 redirects active on ports 10000-20000, Envoy: embedded
  Protocol            Redirect              Proxy Port
  cilium-dns-egress   1067:egress:SCTP:53   3541
  cilium-dns-egress   1067:egress:TCP:53    3541
  cilium-dns-egress   1067:egress:UDP:53    3541
  cilium-dns-egress   64:egress:SCTP:53     3541
  cilium-dns-egress   64:egress:TCP:53      3541
  cilium-dns-egress   64:egress:UDP:53      3541
Global Identity Range:   min 196608, max 262143
Hubble:                  Ok         Current/Max Flows: 4095/4095 (100.00%), Flows/s: 131.51   Metrics: Ok
Encryption:              Disabled
Cluster health:                     Probe disabled

# Notice that policy map has no proxy port entries
root@<>:/home/cilium# cilium bpf policy get 64 | grep 3541
root@<>:/home/cilium#
```

Note : We backported enableDefaultDeny to 1.15, but I don't think that that should matter here, I can work on a 1.16 repro if we think enableDefaultDeny can interfere with this.

On a quick look, merge function should have retained the proxy port https://github.com/cilium/cilium/blob/main/pkg/policy/mapstate.go#L904-L910 
But that doesn't seem to be the case here.

### How can we reproduce the issue?

Issue description has all the details.

### Cilium Version

1.15.8

### Kernel Version

6.5.0-1024-aws #24~22.04.1-Ubuntu

### Kubernetes Version

v1.28.11

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
