### ISSUE TITLE
NAT LRU Eviction due to Full Capacity

### ISSUE THREAD

**Issue by sugangli** [cilium/cilium#34833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.14.13 

### What happened?

This issue is intended to track a branch of the BPF SNAT improvements issue #31643, where we see LRU eviction due to full capacity.  As we discussed in the community meeting,   we might have a longer term goal and some short term enhancement we can look into.

Long term Goals:
1. The fundamental problem is that we store the NAT entries in pairs, but the LRU eviction is not aware of this context.  The connection will be interrupted if one of the entries is evicted.  So if we can combine the out-going entry with its response entry into a single one, we can permanently solve this problem.  AFAIU, this is still in idea phase,  and might have further impact beyond solving the eviction problem itself.
2. Kernel side eviction behavior improvement?

Short term Enhancements:

We may just restore the response entry whenever we do a out-going entry lookup.  However,  it comes with some cons:
1.  Since we are already at capacity,  this is likely to have domino effects on other connections. Maybe we can run reproduction or load test to see if this patch mitigate the issue. 
3. This is also relying on the outbound packet to re-establish SNAT, which might not be available all the time.

 

### How can we reproduce the issue?

Repro in #29305 applies here, but I will update with further repro steps once I starts to work on the PR mentioned above. 

### Cilium Version

v1.14+ 

### Kernel Version

5.10+

### Kubernetes Version

1.24+

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sugangli** [comment]
Reproduction with an ILB:

First, create a GKE cluster:
```
gcloud container clusters create server \
--node-taints node.cilium.io/agent-not-ready=true:NoExecute \
 --num-nodes 2 \
 --zone us-central1-c
```

Second, install OSS cilium onto the cluster:

```
cilium install --wait --chart-directory=install/kubernetes/cilium \
    --helm-set=image.repository="${CILIUM_IMAGE_REPOSITORY}/${CILIUM_TAG}" \
    --helm-set=image.useDigest=false \
    --helm-set=image.tag="${DOCKER_IMAGE_TAG}" \
    --context "${SERVER_CONTEXT}" \
    --set cluster.name=server \
    --set kubeProxyReplacement=true

```

Use a smaller NAT size by setting `bpf-nat-global-max` 

Deploy a ILB service and its NGINX backends:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-ilb-svc
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: nginx
  ports:
  - name: tcp-port
    protocol: TCP
    port: 80
    targetPort: 80





apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
```

Run the  python script in a VM  outside of this cluster to quickly open and close connections to the ILB.

```
import datetime
import socket
import sys

def main():
  while True:
    try:
      s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
      print("%s - connecting..." % str(datetime.datetime.now()))
      s.settimeout(2)
      # connect to ILB's VIP'
      s.connect(("10.128.0.81",80))
      print("  connected - sport %d" % s.getsockname()[1])
      s.close()
    except socket.timeout:
      print("Timeout at %s! Used local endpoint %s:%d" % (str(datetime.datetime.now()), s.getsockname()[0], s.getsockname()[1]), file=sys.stderr)
    except Exception as e:
      print(str(e))
      print("Used local endpoint %s:%d" % (s.getsockname()[0], s.getsockname()[1]))
      raise
        

if __name__=="__main__":
  main()

```

Before the NAT map is full,  we don't see any timeout from the client.

After the NAT map is full,  we start to see timeout. And we further narrow down to the following block by adding some check to bpf/lib/nat.h to make it visible to cilium monitor:

```
static __always_inline int
snat_v4_nat_handle_mapping(struct __ctx_buff *ctx,
                           struct ipv4_ct_tuple *tuple,
                           bool has_l4_header,
                           struct ipv4_nat_entry **state,
                           struct ipv4_nat_entry *tmp,
                           struct iphdr *ip4, __u32 off,
                           const struct ipv4_nat_target *target,
                           struct trace_ctx *trace,
                           __s8 *ext_err)
{
 …

   if (*state) {
                // Found a FWD NAT
                int ret;
                struct ipv4_ct_tuple rtuple = {};
                struct ipv4_nat_entry *rstate;
                /****** Check Rev NAT ******/
                set_v4_rtuple(tuple, *state, &rtuple);
                rstate = __snat_lookup(map, &rtuple);

                if (!rstate) {
                  // Rev NAT not found
                  send_trace_notify(ctx, TRACE_TO_OVERLAY, 997, 0, 0, 0,
                                    0, TRACE_PAYLOAD_LEN);
                }
                 /****** Check Rev NAT ******/
    …
   }
…
}

```

The trace can match up timeout we see in the client.
