### ISSUE TITLE
Host firewall - Egress CiliumClusterwideNetworkPolicy

### ISSUE THREAD

**Issue by singhjoga** [cilium/cilium#34956]
Hi All,
It is related to Cilium version 1.13.4 running in Kubernetes v1.28.10.
I want to allow all kind of Egress in my cluster. Cilium is currently running in Audit mode. I have the below policy created. But somehow, some of the egress traffic is not allowed:

Policy:
```
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: outgoing-allow-all
spec:
  nodeSelector: {}
  egress:
  - toEntities:
    - all
---
```

Below is an example of connections not being allowed:
```
Policy verdict log: flow 0x511166a7 local EP ID 2931, remote ID host, proto 17, egress, action audit, match none, 10.233.65.238:44209 -> 169.254.25.10:53 udp
Policy verdict log: flow 0x11309fed local EP ID 2931, remote ID host, proto 17, egress, action audit, match none, 10.233.65.238:46139 -> 169.254.25.10:53 udp
Policy verdict log: flow 0x7afbc543 local EP ID 2931, remote ID 44430, proto 6, egress, action audit, match none, 10.233.65.238:43520 -> 10.233.66.247:4245 tcp SYN`
```

However similar traffic is below allowed for some cases. Below is an example.
```
Policy verdict log: flow 0xbc30da5e local EP ID 3255, remote ID world, proto 6, egress, action allow, match all, 10.115.193.139:58530 -> 10.115.193.48:10051 tcp SYN
Policy verdict log: flow 0xb1a13846 local EP ID 3255, remote ID 16055, proto 6, egress, action allow, match L3-Only, 10.233.65.130:45964 -> 10.233.65.203:8081 tcp SYN
Policy verdict log: flow 0xd02c9cb0 local EP ID 3255, remote ID 63970, proto 6, egress, action allow, match L3-Only, 10.233.65.130:54458 -> 10.233.65.170:8080 tcp SYN

```
Am I missing something here?

Regards,

Joga
