### ISSUE TITLE
Issue in east-west traffic distribution using HTTPRoute which targets a service

### ISSUE THREAD

**Issue by devang704** [cilium/cilium#34977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Experiencing problems in east-west traffic distribution using HTTPRoute which targets a service.

I have deployed echo-server with two diffrent versions (something like v1 and v2), and created services like `echo-server-no-preview` and `echo-server-preview` which points to each of echo-server endpoints (versions v1 and v2).

I created one more service called "echo-server" which is referenced in HTTPRoute with perentRef and created HTTPRoute. 

![image](https://github.com/user-attachments/assets/ab14c5eb-1f40-4321-9562-5e2f3d79add0)

I discovered that while routing from the service `echo-server` using `http://echo-server:8080` with header `traffic: preview` and without header defined in HTTPRoute it doesnt route to specific backendref and request is redirected to random endpoints of echo-server.

### How can we reproduce the issue?

Deploy Cilium with Gateway API
Deploy two versions of echo-server (using Argo Rollout)
Create echo-server services
- echo-server
- echo-server-no-preview (points to echo-server version 1)
- echo-server-preview (points to echo-server version 2)

```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.test.io/name: echo-server
    app.test.io/teleport: enable
    app.test.io/type: workload
    app.kubernetes.io/instance: echo-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: echo-server
  name: echo-server
  namespace: test
spec:
  clusterIP: 172.20.85.254
  clusterIPs:
  - 172.20.85.254
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: echo-server
    app.kubernetes.io/name: echo-server
  sessionAffinity: None
  type: ClusterIP
--- 
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-server
  namespace: test
spec:
  parentRefs:
  - group: ""
    kind: Service
    name: echo-server
    namespace: test
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: echo-server-no-preview
      port: 8080
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
  - backendRefs:
    - group: ""
      kind: Service
      name: echo-server-preview
      port: 8080
      weight: 1
    matches:
    - headers:
      - name: traffic
        type: Exact
        value: preview
      path:
        type: PathPrefix
        value: /
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argo-rollouts.argoproj.io/managed-by-rollouts: echo-server
  labels:
    app.test.io/name: echo-server
    app.test.io/type: workload
    app.kubernetes.io/instance: echo-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: echo-server
  name: echo-server-no-preview
  namespace: test
spec:
  clusterIP: 172.20.29.107
  clusterIPs:
  - 172.20.29.107
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: echo-server
    app.kubernetes.io/name: echo-server
    rollouts-pod-template-hash: 6f6b68b544
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argo-rollouts.argoproj.io/managed-by-rollouts: echo-server
  labels:
    app.test.io/name: echo-server
    app.test.io/type: workload
    app.kubernetes.io/instance: echo-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: echo-server
  name: echo-server-preview
  namespace: test
spec:
  clusterIP: 172.20.69.44
  clusterIPs:
  - 172.20.69.44
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: echo-server
    app.kubernetes.io/name: echo-server
    rollouts-pod-template-hash: 79f9bc975c
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    rollout.argoproj.io/revision: "3"
  labels:
    app.test.io/name: echo-server
    app.test.io/type: workload
    app.kubernetes.io/instance: echo-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: echo-server
  name: echo-server
  namespace: test
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: echo-server
      app.kubernetes.io/name: echo-server
  strategy:
    blueGreen:
      activeService: echo-server-no-preview
      autoPromotionEnabled: false
      autoPromotionSeconds: 30
      previewReplicaCount: 1
      previewService: echo-server-preview
      scaleDownDelaySeconds: 30
  template:
    metadata:
      annotations:
        checksum/config: 59280e535a06801dc5cf6e7d46e642cf927133ab37c4278723d291db392e5cbc
      labels:
        app.test.io/name: echo-server
        app.test.io/type: workload
        app.kubernetes.io/instance: echo-server
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: echo-server
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: echo-server
        image: ealen/echo-server:0.9.2
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: echo-server
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: regcred
      securityContext: {}
      serviceAccountName: echo-server
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule 
```

### Cilium Version

1.16.1

### Kernel Version

5.10.223-212.873.amzn2.x86_64

### Kubernetes Version

v1.30.0

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
