### ISSUE TITLE
Cilium-Envoy stops receiving config updates once there is one invalid listener config with Gateway API

### ISSUE THREAD

**Issue by SantoDE** [cilium/cilium#34982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Once a gateway has an invalid config inside one of its listeners (i.e. missing TLS secret), it stops receiving routing configuration updates i.e. no new routes are being served (on the non TLS listener).

### How can we reproduce the issue?

1. Install cilium with helm and enable gateway api
2. Deploy a basic gateway 
````
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-gateway
  namespace: default
spec:
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: default-http
    port: 80
    protocol: HTTP
```
3. Deploy a simple HTTP Route
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami-route
  namespace: default
spec:
  hostnames:
  - whoami.cloud-native.rocks
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: default-gateway
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: whoami
      port: 80
      weight: 1
    matches:
    - path:
        type: Exact
        value: /
```
4. Patch Gateway with a (for that moment invalid config, as the referenced secret is missing)
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-gateway
  namespace: default
spec:
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: default-http
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: All
    hostname: whoami.cloud-native.rocks
    name: default-https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: whoami-cloud-native-rocks-certs
      mode: Terminate
```
5. Change HTTP Route to simulate a config change
```
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami-route
  namespace: default
spec:
  hostnames:
  - whoami.cloud-native.rocks
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: default-gateway
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: whoami
      port: 80
      weight: 1
    matches:
    - path:
        type: Exact
        value: /foobar
```
6. `curl` that new/changed endpoint on HTTP and get a 404

### Cilium Version

1.16.1

### Kernel Version

Linux ip-172-31-26-187.eu-central-1.compute.internal 6.1.97-104.177.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jul 16 15:18:45 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.30.4+k3s1

### Regression

It used to work with 1.15.X

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackmaninov** [comment]
I think I am seeing the same issue. 

For some reason under cilium 1.16.x, when the CiliumEnvoyConfig is being constructed for HTTPRoutes with TLS secrets, entries for the routes are added to virtualHosts under the `listener-secure` RouteConfiguration (th gateway CEC's .spec.resources.name = listener-secure, .'@type'=type.googleapis.com/envoy.config.route.v3.RouteConfiguration), but *not* the 
`listener-insecure` one. As a result, when a non-TLS request arrives, envoy reports like the following in its debug log:

```
[2024-10-08 10:08:46.857][14][debug][router] [external/envoy/source/common/router/router.cc:446] [Tags: "ConnectionId":"742","StreamId":"1809078164870312584"] no route match for URL '/'
```

When I downgrade to 1.15.9, the routes are added to virtualHosts on both `listener-secure` and `listener-insecure`, and non-TLS requests succeed.

@SantoDE, you seem to have already have constructed the minimum test case, maybe you can check if you have `whoami.cloud-native.rocks` under virtualHosts for only `listener-secure` or both it and `listener-insecure` in your CiliumEnvoyConfig?

**Comment by jackmaninov** [comment]
I am running on Talos v1.8.0, k8s v1.31.1 deploying cilium with argo-cd. My values.yaml:

```
upgradeCompatibility: '1.15'
ipam:
  mode: kubernetes

kubeProxyReplacement: true
k8sServiceHost: localhost
k8sServicePort: 7445

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

encryption:
  enabled: true
  type: wireguard

ingressController:
  enabled: false
  loadbalancerMode: shared
  enforceHttps: false
  default: true
  defaultSecretNamespace: kube-system
  defaultSecretName: default-tls
  secretsNamespace:
    create: true
    name: mysite-cilium-secrets
  service:
    allocateLoadBalancerNodePorts: false

egressGateway:
  enabled: true

l7Proxy: true
bpf:
  masquerade: true

enableIPv4Masquerade: true

hubble:
  enabled: true
  relay:
    enabled: true
  tls:
    auto:
      enabled: true
      method: certmanager
      certValidityDuration: 1095
      certManagerIssuerRef:
        group: cert-manager.io
        kind: Issuer
        name: hubble-ca
  ui:
    enabled: true
    replicas: 1
    ingress:
      enabled: false
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-cilium
        kubernetes.io/tls-acme: "true"
        acme.cert-manager.io/http01-edit-in-place: "true"
      hosts:
      - hubble.mysite.com
      tls:
      - hosts:
        - hubble.mysite.com
        secretName: ingress-hubble-ui-tls
  metrics:
    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true

policyAuditMode: false
nodePort:
  enabled: true
  enableHealthCheck: true

envoy:
  enabled: true
  rollOutPods: true
  connectTimeoutSeconds: 5
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy:
        - NET_BIND_SERVICE
        - CAP_NET_ADMIN
        - CAP_BPF
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE

gatewayAPI:
  enabled: true
  enableAppProtocol: true
  enableAlpn: true
  secretsNamespace: 
    name: mysite-cilium-secrets

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

dashboards:
  enabled: true

operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true
  rollOutPods: true

# for previous debug operator config
#
# imagePullSecrets:
#   - name: cilium-debug-pull-secret
# hostFirewall:
#   enabled: true

debug:
  enabled: true
  verbose: "datapath flow kvstore envoy"
      
hostPort:
  enabled: true

cluster:
  name: mysite
  id: 1

socketLB:
  enabled: true
  hostNamespaceOnly: true 
```

**Comment by SantoDE** [comment]
Sure @jackmaninov. I'll validate this afternoon but if memory serves me well, I saw the same in regards to envoy config. I'm quite sure we are hitting the same, since downgrading fixes it for me as well.

**Comment by gschei** [comment]
I have the same Issue, using cert-manager which attaches to Port 80 for ACME Http01 Challenge while other listeners have InvalidCertificateRef. Would be nice to get an update when a fix can be provided.

```
[2024-12-09 16:56:51.571][15][debug][router] [external/envoy/source/common/router/router.cc:446] [Tags: "ConnectionId":"14","StreamId":"16950019938598325183"] no route match for URL '/.well-known/acme-challenge/6SFkrMb0BY_Qdp_AfrSq2QKizCEpQ9K4XNDRdBcC0q0'
```
```
 Waiting for HTTP-01 challenge propagation: wrong status code '404', expected '200'
```

**Comment by jackmaninov** [comment]
Confirmed this issue is still present on 1.16.5.

**Comment by jackmaninov** [comment]
Please keep open, this is still preventing me upgrading Cilium.

Is there somewhere in the code that I can be recommended to look at to attempt to debug further?

**Comment by DimitriosLisenko** [comment]
I believe I'm hitting this bug as well.

My use-case is to integrate cert-manager with my gateway. In order to do that, according to the cert-manager docs, I need to add an annotation to the gateway and then populate the HTTPS listener with a secret name where the certificate should be - cert-manager will put the certificate into that secret later once it exists.

What happens is that the HTTPRoute for the challenge is created, but trying to access the challenge returns a 404 (it actually continues pointing to the existing HTTPRoute for port 80 rather than use the exact match for the challenge.
```
$ kubectl describe challenge
...
  Reason:      Waiting for HTTP-01 challenge propagation: wrong status code '404', expected '200'
...
```

To work around this issue, I had to add the "issue-temporary-certificate" annotation to the gateway:
```
metadata:
  annotations:
    cert-manager.io/issuer: ...
    cert-manager.io/issue-temporary-certificate: "true"
```

This annotation will cause cert-manager to generate a temporary self-signed certificate and stick it into the secret, at which point I assume the HTTPS listener config is now valid, and the challenge URL now works.

**Comment by arlyon** [comment]
Also appears on 1.17.1. Attempting to downgrade to 1.15.9 to check

**Comment by jackmaninov** [comment]
Was testing this evening with 1.18.0-pre.2 and can confirm there are still issues with routes attaching to my insecure listener. 

At some point since I first began facing this issue cert-manager began supporting the `cert-manager.io/issue-temporary-certificate: "true"` and `acme.cert-manager.io/http01-edit-in-place: "true"` annotations on gateways, so there is no longer an InvalidCertificateRef issue on the gateway. 

I can even recycle the generated certificate from a previous attempt, delete all HTTPRoutes and Gateways, restart cilium-operator and envoy, then re-add my test Gateway and HTTPRoute. I'll be left with the HTTPRoute successfully working for HTTPS (with a self-generated certificate), but no routes configured on `listener-insecure` despite them being reported as successfully  programmed/attached/resolved on gateway.status.listeners[].

I even find that if I create additional HTTPRoutes that target my insecure listener (by setting `port` and `sectionName` on their parentRefs section) using the same hostname as an HTTPS listener (but different PathPrefixes), Cilium will report them successfully reconciled, no errors in the cilium-operator log, but nothing is added to the CiliumEnvoyConfig and calls to them simply 404 on envoy.

**Comment by jfmatth** [comment]
Running Talos v1.10.1 and Cilium 1.17.4 and having this issue as well.

I found a very odd workaround, use two gateways, one soley for http and the other for all things https.  Weird that it worked, but it did 😮

**Comment by jackmaninov** [comment]
> I found a very odd workaround, use two gateways, one soley for http and the other for all things https. Weird that it worked, but it did 😮

Yes I can confirm this works for my use case as well. Kicking myself for not trying this as well at some point over the past months, now I can finally upgrade past 1.15.

**Comment by youngnick** [comment]
This may well be a bug in how we handle invalid HTTPRoutes, which I _think_ a planned refactor to the Gateway reconciler may fix. But the testing for the Gateway reconciler is pretty unwieldy at the moment, and requires a lot of finesse to understand and add to.

To explain more, currently there is one reconciler for HTTPRoutes that determines if they are valid, and one for Gateways that takes valid HTTPRoutes (as determined by the other reconciler) and reconciles them.

Clearly, we are also not handling partially-invalid configs properly (one invalid Listener should not stop the other Listeners from being reconciled). But the testing complexity makes it hard to tell if we're testing this properly.

So, I think the current plan is:
* move the Gateway reconciler to a new, testdata-based testing framework (that makes adding additional tests much easier). This will also make it easier to add a test that covers this partially-invalid case.
* refactor the Gateway reconciler so that there's only one reconciler, that updates HTTPRoute status when reconciling Gateway. (this is a little more technically correct anyway).

So thanks everyone for figuring out a workaround while we got to this, we will see what we can do about fixing it. But it's not a straightforward fix.

**Comment by jfmatth** [comment]
@youngnick Thank YOU for working on Cilium, and amazing product.

So if I hear you right, IF there are no invalid routes, it should work?

I've got my workaround AND looking at if Envoy will help here, but wanting to understand things a little.

**Comment by youngnick** [comment]
I _think_ so, but I'm not sure, haven't had a chance to replicate yet. If you could test that out for me, that would be amazing!

**Comment by jfmatth** [comment]
Ill do what I can and report back.

**Comment by jackmaninov** [comment]
In my experience having an invalid route is NOT a prerequisite to triggering the bug. I've done tests in the past similar to the workflow in the top post but referencing an existing Secret (a self-generated or a previously issued lets-encrypt certificate) and still been left with an HTTPRoute that is successfully connected to the HTTPS listener but not the HTTP one (despite Cilium saying it is).

**Comment by jfmatth** [comment]
Could the new version of cert-manager help here?  There were some specific changes in 1.18 that broke traditional http stuff, just curious

**Comment by youngnick** [comment]
The big changes in cert-manager 1.18 were for Ingress processing, not Gateway, I think.

**Comment by jfmatth** [comment]
Agree, tried it, no luck

**Comment by youngnick** [comment]
The key part here is having hostnames set in HTTPRoutes, it seems - when I reproduce using @SantoDE's original reproduction, if I remove the `hostnames` list from the YAML, this works correctly.

That helps me narrow this down a bit.

**Comment by jfmatth** [comment]
Just so I'm clear, if you remove the hostname from the HTTProute it creates a cert and works as expected?

**Comment by youngnick** [comment]
I haven't verified with cert-manager, only the minimal reproduction, but it does seem like that should work, yes. Still chasing down exactly what is happening.

**Comment by jfmatth** [comment]
Thanks @youngnick  ill check it out tonight :)

**Comment by youngnick** [comment]
I just tested with my repro, and yes, removing the hostnames from the routes does seem to work around this bug.

**Comment by jfmatth** [comment]
Hi @youngnick  can you post your configs here, the gateway and then the httproute.

I tried what you're saying and I still get 404 for the solver 🤕

**Comment by jfmatth** [comment]
For now, I've moved on to using Traefik as the Gateway API.  I still have Talos + Cilium, with Cilium the Kubeproxy replacement and full stack for Talos, works great.  Didn't want to wait for gateway to work with cert-manager.

My full setup: Talos + Cilium + Traefik + Cert-manager = Working 😄

**Comment by youngnick** [comment]
Sorry about the delay here, I've been working on the Gateway API refactor. Here is the test I've been using:

Create a default gateway:

`gateway-first.yaml`

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-gateway
  namespace: default
spec:
  gatewayClassName: cilium
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      name: default-http
      port: 80
      protocol: HTTP
      hostname: "echo.cloud-native.rocks"

```

Add the default HTTPRoute:

`httproute-first.yaml`

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo
  namespace: default
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: default-gateway
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: echo-a-internal
          port: 8080
          weight: 1
      matches:
        - path:
            type: Exact
            value: /
```

Then, check that everything works.

Then, add the new Route:

`httproute-second.yaml`

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: challenge
  namespace: default
spec:
  hostnames:
    - "echo.cloud-native.rocks"
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: default-gateway
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: echo-a-internal
          port: 8080
          weight: 1
      matches:
        - path:
            type: Exact
            value: /challenge

```

Then, curl `/challenge`, with the hostname `echo.cloud-native.rocks`. This may take a couple of attempts as things can take a few hundred milliseconds to converge.

Once that's done, patch the Gateway:

`gateway-second.yaml`

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-gateway
  namespace: default
spec:
  gatewayClassName: cilium
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      name: default-http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: All
      hostname: echo.cloud-native.rocks
      name: default-https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: whoami-cloud-native-rocks-certs
        mode: Terminate
```

Then, test again, and things should work.


I automated this with a script so that I could test variables about where to put hostnames etc:

`test.sh`

```bash
#!/bin/bash

function didPass () {
    if [ "$1" -eq 0 ] ; then
      echo "OK"
    else 
      echo "ERROR" 
    fi
}

kubectl delete -f gateway-first.yaml
kubectl delete -f httproute-first.yaml
kubectl delete -f httproute-second.yaml

sleep 2

kubectl apply -f /Users/ynick/src/isovalent/scratch/manifests/echo-basic/dep-a/

kubectl apply -f gateway-first.yaml

kubectl apply -f httproute-first.yaml

sleep 1

LBIP=$(kubectl get svc -o json | jq -r '.items[] | select(.metadata.name=="cilium-gateway-default-gateway") | .status.loadBalancer.ingress[0].ip')

echo "LBIP is '${LBIP}'"

echo "=== curl with no hostname, should fail"

curl --fail-with-body -s -o /dev/null "http://$LBIP/"

didPass $?

echo "=== curl with hostname, should succeed"

curl --fail-with-body -s -o /dev/null -H 'Host: echo.cloud-native.rocks' "http://$LBIP/"

INITIAL=$(didPass $?)

echo $INITIAL

echo "========== Adding extra route"

kubectl apply -f httproute-second.yaml

echo "=== curl with no hostname, should fail"
curl --fail-with-body -s -o /dev/null "http://$LBIP/"

didPass $?

echo "=== curl with hostname, should succeed"
curl --fail-with-body -s -o /dev/null -H 'Host: echo.cloud-native.rocks' "http://$LBIP/"
didPass $?


echo "=== curl /challenge with no hostname, should fail"

curl --fail-with-body -s -o /dev/null "http://$LBIP/challenge"

didPass $?

echo "=== curl /challenge with hostname, may fail"

curl --fail-with-body -s -o /dev/null -H 'Host: echo.cloud-native.rocks' "http://$LBIP/"

didPass $?

echo "=== Sleep for a bit"

sleep 0.1

echo "=== curl with no hostname, should fail"
curl --fail-with-body -s -o /dev/null "http://$LBIP/"

didPass $?

echo "=== curl with hostname, should succeed"
curl --fail-with-body -s -o /dev/null -H 'Host: echo.cloud-native.rocks' "http://$LBIP/"

didPass $?

echo "=== curl /challenge with no hostname, should fail"

curl --fail-with-body -s -o /dev/null "http://$LBIP/challenge"


echo "=== curl /challenge with hostname, should succeed"

curl --fail-with-body -s -o /dev/null -H 'Host: echo.cloud-native.rocks' "http://$LBIP/"

ROUTE2=$(didPass $?)

echo $ROUTE2


echo "========== updating Gateway"

kubectl apply -f gateway-second.yaml

echo "=== curl with no hostname, should fail"
curl --fail-with-body -s -o /dev/null "http://$LBIP/"

didPass $?

echo "=== curl with hostname, should succeed"
curl --fail-with-body -s -o /dev/null -H 'Host: echo.cloud-native.rocks' "http://$LBIP/"
didPass $?


echo "=== curl /challenge with no hostname, should fail"

curl --fail-with-body -s -o /dev/null "http://$LBIP/challenge"

didPass $?

echo "=== curl /challenge with hostname, may fail"

curl --fail-with-body -s -o /dev/null -H 'Host: echo.cloud-native.rocks' "http://$LBIP/"

didPass $?

echo "=== Sleep for a bit"

sleep 0.1

echo "=== curl with no hostname, should fail"
curl --fail-with-body -s -o /dev/null "http://$LBIP/"

didPass $?

echo "=== curl with hostname, should succeed"
curl --fail-with-body -s -o /dev/null -H 'Host: echo.cloud-native.rocks' "http://$LBIP/"

didPass $?

echo "=== curl /challenge with no hostname, should fail"

curl --fail-with-body -s -o /dev/null "http://$LBIP/challenge"

didPass $?

echo "=== curl /challenge with hostname, should succeed"

curl --fail-with-body -s -o /dev/null -H 'Host: echo.cloud-native.rocks' "http://$LBIP/"

GATEWAY2=$(didPass $?)

echo $GATEWAY2


echo "==== Report"
echo "$INITIAL | $ROUTE2 | $GATEWAY2"

```

This relies on a Deployment and Service called `echo-a` existing:

`echo-a.yaml`

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-basic-a
  labels:
    app: echo-basic-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-basic-a
  template:
    metadata:
      labels:
        app: echo-basic-a
    spec:
      containers:
      - name: echo-basic-a
        image: gcr.io/k8s-staging-gateway-api/echo-basic:v20240412-v1.0.0-394-g40c666fd
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 10m
---
apiVersion: v1
kind: Service
metadata:
  name: echo-a-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: echo-basic-a
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: echo-a-internal
spec:
  type: ClusterIP
  selector:
    app: echo-basic-a
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000

```
