### ISSUE TITLE
Failing no-unexpected-packet-drops test with INGRESS - TTL exceeded

### ISSUE THREAD

**Issue by audacioustux** [cilium/cilium#34995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

cilium connectivity test `no-unexpected-packet-drops` failing

```
❌ Found unexpected packet drops:
{
  "labels": {
    "direction": "INGRESS",
    "reason": "TTL exceeded"
  },
  "name": "cilium_drop_count_total",
  "value": 147
}
```

There're a few other tests failing, relevant logs below and full log here: https://gist.github.com/audacioustux/17f2c6a644a284755795f018633bf7c2

### How can we reproduce the issue?

1. install cilium with helm chart with values:
```json
{
  "egressMasqueradeInterfaces": "eth0",
  "eni": {
    "awsEnablePrefixDelegation": true,
    "enabled": true
  },
  "envoy": {
    "enabled": true,
    "rollOutPods": true
  },
  "gatewayAPI": {
    "enabled": true
  },
  "hubble": {
    "relay": {
      "enabled": true,
      "rollOutPods": true
    },
    "ui": {
      "enabled": true,
      "rollOutPods": true
    }
  },
  "ingressController": {
    "default": true,
    "enabled": true,
    "loadbalancerMode": "shared",
    "service": {
      "annotations": {
        "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
      }
    }
  },
  "ipam": {
    "mode": "eni"
  },
  "k8sClientRateLimit": {
    "burst": 200,
    "qps": 100
  },
  "k8sServiceHost": "xxx.gr7.ap-south-1.eks.amazonaws.com",
  "k8sServicePort": 443,
  "kubeProxyReplacement": "true",
  "operator": {
    "prometheus": {
      "enabled": true
    },
    "rollOutPods": true
  },
  "prometheus": {
    "enabled": true
  },
  "rollOutCiliumPods": true,
  "routingMode": "native"
}
```

### Cilium Version

1.16.1

### Kernel Version

Linux ip-10-0-214-82.ap-south-1.compute.internal 6.1.106-116.188.amzn2023.aarch64 #1 SMP Tue Aug 27 07:00:04 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

1.30

### Sysdump

[cilium-sysdump-20240920-184509.zip](https://github.com/user-attachments/files/17079757/cilium-sysdump-20240920-184509.zip)

### Relevant log output

```shell
ℹ️  Skipping IPCache check
🔭 Enabling Hubble telescope...
ℹ️  Hubble is OK, flows: 12285/12285, connected nodes: 3, unavailable nodes 0
ℹ️  Cilium version: 1.16.1
🏃[cilium-test-1] Running 102 tests ...
[=] [cilium-test-1] Test [no-unexpected-packet-drops] [1/102]
.
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/kubernetes/ip-10-0-116-205.ap-south-1.compute.internal]
  [-] Scenario [no-unexpected-packet-drops/no-unexpected-packet-drops]
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/kubernetes/ip-10-0-214-82.ap-south-1.compute.internal]
  ❌ Found unexpected packet drops:
{
  "labels": {
    "direction": "INGRESS",
    "reason": "TTL exceeded"
  },
  "name": "cilium_drop_count_total",
  "value": 147
}
.  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/kubernetes/ip-10-0-156-22.ap-south-1.compute.internal]
.  ❌ Found unexpected packet drops:
{
  "labels": {
    "direction": "INGRESS",
    "reason": "TTL exceeded"
  },
  "name": "cilium_drop_count_total",
  "value": 147
}
...
...
...
📋 Test Report [cilium-test-1]
❌ 5/64 tests failed (22/623 actions), 38 tests skipped, 0 scenarios skipped:
Test [no-unexpected-packet-drops]:
  ❌ no-unexpected-packet-drops/no-unexpected-packet-drops/kubernetes/ip-10-0-156-22.ap-south-1.compute.internal
  ❌ no-unexpected-packet-drops/no-unexpected-packet-drops/kubernetes/ip-10-0-214-82.ap-south-1.compute.internal
Test [pod-to-ingress-service-deny-all]:
  ❌ pod-to-ingress-service-deny-all/pod-to-ingress-service/curl-0: cilium-test-1/client3-67f959dd9b-nt5xj (10.0.252.71) -> cilium-test-1/cilium-ingress-other-node (cilium-ingress-other-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-all/pod-to-ingress-service/curl-1: cilium-test-1/client3-67f959dd9b-nt5xj (10.0.252.71) -> cilium-test-1/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-all/pod-to-ingress-service/curl-2: cilium-test-1/client-974f6c69d-zsj89 (10.0.129.220) -> cilium-test-1/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-all/pod-to-ingress-service/curl-3: cilium-test-1/client-974f6c69d-zsj89 (10.0.129.220) -> cilium-test-1/cilium-ingress-other-node (cilium-ingress-other-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-all/pod-to-ingress-service/curl-4: cilium-test-1/client2-57cf4468f-n6swt (10.0.172.12) -> cilium-test-1/cilium-ingress-other-node (cilium-ingress-other-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-all/pod-to-ingress-service/curl-5: cilium-test-1/client2-57cf4468f-n6swt (10.0.172.12) -> cilium-test-1/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test-1:80)
Test [pod-to-ingress-service-deny-ingress-identity]:
  ❌ pod-to-ingress-service-deny-ingress-identity/pod-to-ingress-service/curl-0: cilium-test-1/client2-57cf4468f-n6swt (10.0.172.12) -> cilium-test-1/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-ingress-identity/pod-to-ingress-service/curl-1: cilium-test-1/client2-57cf4468f-n6swt (10.0.172.12) -> cilium-test-1/cilium-ingress-other-node (cilium-ingress-other-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-ingress-identity/pod-to-ingress-service/curl-2: cilium-test-1/client3-67f959dd9b-nt5xj (10.0.252.71) -> cilium-test-1/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-ingress-identity/pod-to-ingress-service/curl-3: cilium-test-1/client3-67f959dd9b-nt5xj (10.0.252.71) -> cilium-test-1/cilium-ingress-other-node (cilium-ingress-other-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-ingress-identity/pod-to-ingress-service/curl-4: cilium-test-1/client-974f6c69d-zsj89 (10.0.129.220) -> cilium-test-1/cilium-ingress-other-node (cilium-ingress-other-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-ingress-identity/pod-to-ingress-service/curl-5: cilium-test-1/client-974f6c69d-zsj89 (10.0.129.220) -> cilium-test-1/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test-1:80)
Test [pod-to-ingress-service-deny-backend-service]:
  ❌ pod-to-ingress-service-deny-backend-service/pod-to-ingress-service/curl-0: cilium-test-1/client-974f6c69d-zsj89 (10.0.129.220) -> cilium-test-1/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-backend-service/pod-to-ingress-service/curl-1: cilium-test-1/client-974f6c69d-zsj89 (10.0.129.220) -> cilium-test-1/cilium-ingress-other-node (cilium-ingress-other-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-backend-service/pod-to-ingress-service/curl-2: cilium-test-1/client2-57cf4468f-n6swt (10.0.172.12) -> cilium-test-1/cilium-ingress-other-node (cilium-ingress-other-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-backend-service/pod-to-ingress-service/curl-3: cilium-test-1/client2-57cf4468f-n6swt (10.0.172.12) -> cilium-test-1/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-backend-service/pod-to-ingress-service/curl-4: cilium-test-1/client3-67f959dd9b-nt5xj (10.0.252.71) -> cilium-test-1/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-backend-service/pod-to-ingress-service/curl-5: cilium-test-1/client3-67f959dd9b-nt5xj (10.0.252.71) -> cilium-test-1/cilium-ingress-other-node (cilium-ingress-other-node.cilium-test-1:80)
Test [check-log-errors]:
  ❌ check-log-errors/no-errors-in-logs/kubernetes/kube-system/cilium-operator-67848cdb84-c4z75 (cilium-operator)
  ❌ check-log-errors/no-errors-in-logs/kubernetes/kube-system/cilium-operator-67848cdb84-l5h65 (cilium-operator)
```

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dhess** [comment]
We have exactly the same failures with Cilium v1.16.5 on 2 different clusters, all running on the same host network. One of the clusters contains bare metal workers with Proxmox-virtualized control planes, and on the other, all nodes are Proxmox-virtualized. We're running Talos v1.8.4 with Kubernetes 1.31.4. I've included our Cilium Helm chart values for one of the clusters below; the other is very similar, chiefly it's just the CIDRs that are different.

We've had these problems for quite awhile, prior to upgrading to Cilium v1.16.5, Talos v1.8.4, and Kubernetes 1.31.4.

As far as we can tell, the clusters are all functioning correctly. While we don't appear to be affected by the failures in the connectivity tests, we'd like to understand why they're occurring.

[We get a few additional failures on top of what OP sees due to L7 policies not supporting port ranges, but I assume these are expected with `l7Proxy: true` ?]

```yaml
cluster:
  name: cluster-a
  id: 1

clustermesh:
  useAPIServer: true
  apiserver:
    replicas: 3
    service:
      type: LoadBalancer
      loadBalancerClass: io.cilium/bgp-control-plane
      externalTrafficPolicy: Local
      annotations:
        io.cilium/lb-ipam-ips: 10.0.20.245
    tls:
      authMode: cluster
      auto:
        method: certmanager
        certValidityDuration: 90
        certManagerIssuerRef:
          group: cert-manager.io
          kind: ClusterIssuer
          name: cilium-issuer
    metrics:
      serviceMonitor:
        enabled: true
        interval: 30s
        kvstoremesh:
          interval: 30s
        etcd:
          interval: 30s
  config:
    enabled: true
    clusters:
      - name: cluster-b
        port: 2379
        ips:
          - 10.0.24.245
      - name: cluster-c
        port: 2379
        ips:
          - 10.64.70.245

updateStrategy:
  rollingUpdate:
    maxUnavailable: 1

upgradeCompatibility: "1.14"
kubeProxyReplacement: true
k8sServiceHost: localhost
k8sServicePort: 7445
ipam:
  mode: kubernetes

rollOutCiliumPods: true
operator:
  rollOutPods: true

bgpControlPlane:
  enabled: true

hostFirewall:
  enabled: false

# Fix for Talos.
# https://github.com/cilium/cilium/issues/21603#issuecomment-1453753820
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

l7Proxy: true

# Deploy Envoy as a daemonset, rather than as part of the Cilium agent
# pods.
envoy:
  enabled: true
  rollOutPods: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

gatewayAPI:
  enabled: true

ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  service:
    # Argo CD can't properly reconcile the ports on this service, so
    # we specify them. Here I've chosen whatever defaults the service
    # uses when they're not specified.
    insecureNodePort: 30332
    secureNodePort: 30235
    annotations:
      io.cilium/lb-ipam-ips: 10.0.20.253

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true

hubble:
  relay:
    enabled: true
    replicas: 3
    prometheus:
      serviceMonitor:
        enabled: true
  ui:
    enabled: true
  tls:
    auto:
      enabled: true
      method: certmanager
      certValidityDuration: 1095
      certManagerIssuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: cilium-issuer
  metrics:
    enableOpenMetrics: true
    enabled:
      - dns:labelsContext=source_namespace,destination_namespace
      - drop:labelsContext=source_namespace,destination_namespace
      - tcp:labelsContext=source_namespace,destination_namespace
      - port-distribution:labelsContext=source_namespace,destination_namespace
      - icmp:labelsContext=source_namespace,destination_namespace;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity
      - flow:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity;labelsContext=source_namespace,destination_namespace
      - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      - "policy:sourceContext=app|workload-name|pod|reserved-identity;destinationContext=app|workload-name|pod|dns|reserved-identity;labelsContext=source_namespace,destination_namespace"
    dashboards:
      enabled: true
    serviceMonitor:
      enabled: true

# Native, L2 direct routing.
routingMode: native
autoDirectNodeRoutes: true
# Seems required for clustermesh to work?
# ref:
# https://github.com/cilium/cilium/issues/31843
directRoutingSkipUnreachable: true
ipv4NativeRoutingCIDR: 10.0.0.0/8

loadBalancer:
  algorithm: maglev
  mode: dsr
  dsrDispatch: opt
  acceleration: native

maglev:
  hashSeed: [redacted]

bpf:
  masquerade: true

# Performance tweaks.
# https://docs.cilium.io/en/stable/operations/performance/tuning/
enableIPv4BIGTCP: true
enableIPv6BIGTCP: true
bandwidthManager:
  enabled: true
  bbr: true

dashboards:
  enabled: true

```

**Comment by dhess** [comment]
While looking at the failure logs for the `pod-to-ingress-service-deny-all` and `pod-to-ingress-service-deny-ingress-identity` tests, I noticed that all of the failing tests involved a privileged port. I then discovered that we'd missed the fact that Envoy needs a modified `securityContext` for this, plus an extra flag:

https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/#bind-to-privileged-port

We run Envoy as a daemonset, so I made the following changes to our configurations:

```yaml
envoy:
  enabled: true
  # Required to permit Envoy to bind to privileged ports.
  #
  # Ref:
  # https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/#bind-to-privileged-port
  securityContext:
   capabilities:
     keepCapNetBindService: true
     envoy:
       # Defaults.
       - NET_ADMIN
       - SYS_ADMIN

       # Required by Gateway (for privileged ports).
       - NET_BIND_SERVICE
  rollOutPods: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
```

I'm happy to report that the `pod-to-ingress-service-deny-all` and `pod-to-ingress-service-deny-ingress-identity` tests now pass.

@audacioustux Your config looks quite different to ours, not to mention that you're running on EKS while we're on bare metal with Talos, so this specific bit of YAML might not fix those issues for you, but I suspect that if you dig into the Cilium docs cited above and adapt them to your config, you'll get these 2 tests passing, as well.

**Comment by dhess** [comment]
@audacioustux Oh, one more thing regarding the failed log checks in your tests. You appear to have the same problem we had, which is that you've enabled the Gateway API, but your cluster is missing the required resources. We'd installed the Gateway CRDs, but hadn't updated them to v1.1.0 (experimental channel). We did that, and those tests now pass, as well.

**Comment by dhess** [comment]
> I'm happy to report that the pod-to-ingress-service-deny-all and pod-to-ingress-service-deny-ingress-identity tests now pass.

Unfortunately, I was premature in declaring victory. The tests passed because I hadn't enabled Hubble port-forwarding, so the flow validations didn't run. I've retried the test with Hubble enabled, and the tests still fail their flow validations :(

**Comment by gandro** [comment]
Still happening https://github.com/cilium/cilium/actions/runs/13562915410/job/37909644066

**Comment by figaw** [comment]
We still experience this.

**Comment by figaw** [comment]
We still experience this.

**Comment by thiagoabdo** [comment]
We are also experiencing this

Cilium 1.16.12 
EKS 1.31.9

here it is our config
```
                eni:
                  enabled: true
                  updateEC2AdapterLimitViaAPI: true
                  awsEnablePrefixDelegation: true
                  awsReleaseExcessIPs: true
                  iamRole: REDACTED
                ipam:
                  mode: "eni"
                  operator:
                    clusterPoolIPv4PodCIDRList: REDACTED

                egressMasqueradeInterfaces: "eth0"
                enableIPv4Masquerade: false
             
                routingMode: "native"

                resources:
                  limits:
                    memory: 2Gi
                  requests:
                    cpu: 100m
                    memory: 512Mi

                # Hubble
                hubble:
                  enabled: true
                  metrics:
                    enabled:
                      - dns
                      - drop:sourceContext=pod|app|dns|reserved-identity|ip;destinationContext=pod|app|dns|reserved-identity|ip;labelsContext=traffic_direction
                      - tcp
                      - flow:sourceContext=pod|app|dns|reserved-identity|ip;destinationContext=pod|app|dns|reserved-identity|ip;labelsContext=traffic_direction
                      - flows-to-world:port;sourceContext=pod|app|dns|reserved-identity|ip
                      - port-distribution
                      - icmp
                      - httpV2:sourceContext=pod|app|dns|reserved-identity|ip;destinationContext=pod|app|dns|reserved-identity|ip;labelsContext=traffic_direction
                  ui:
                    enabled: true
                    ingress:
                      enabled: true
                      hosts:
                        - REDACTED
                    backend:
                      resources:
                        limits:
                          cpu: 200m
                          memory: 256Mi
                        requests:
                          cpu: 10m
                          memory: 32Mi
                    frontend:
                      resources:
                        limits:
                          cpu: 200m
                          memory: 256Mi
                        requests:
                          cpu: 10m
                          memory: 32Mi

                  relay:
                    enabled: true
                    resources:
                      limits:
                        cpu: 200m
                        memory: 256Mi
                      requests:
                        cpu: 10m
                        memory: 32Mi

                # Prometheus
                prometheus:
                  enabled: true

                operator:
                  prometheus:
                    enabled: true
                  resources:
                    limits:
                      cpu: 200m
                      memory: 512Mi
                    requests:
                      cpu: 10m
                      memory: 64Mi

                policyAuditMode: false
                dnsProxy:
                  minTtl: 3600
                  idleConnectionGracePeriod: 30s

                kubeProxyReplacement: "true"
                k8sServiceHost: REDACTED
                k8sServicePort: 443

                upgradeCompatibility: "1.16"
                socketLB:
                  hostNamespaceOnly: "true"
                  terminatePodConnections: "true"
```
