### ISSUE TITLE
CFP: eBPF with bridge mode

### ISSUE THREAD

**Issue by ttc0419** [cilium/cilium#35011]
Most of time, cluster nodes are in a same datacenter, using bridge would have less network overhead compare to an overlay network. Please consider a bridge mode with eBPF, which combines the best from both worlds.

related: #20336

**Comment by joestringer** [comment]
Hi, have you tried configuring native routing? That doesn't involve overlays.

**Comment by camrossi** [comment]
I have been doing a lot of testing on this, and my use case is using Cilium for VMs connectivity (aka Kube Virt)
I am not sure if @ttc0419 and @stulzq are after this use case. 

I have the following requirements:

- VMs needs to be exposed directly on the network, this is due to the fact that said VMs needs to have their IP address assigned either Statically or via DHCP
- Support Live Migration for VMs
- Support Importing VMs with [Forklift](https://github.com/kubev2v/forklift): The VM disk is converted and imported "as is" so there is no change of changing the networking config
- Ability to connect to the VMs with SSH/RDP etc... in a simple way i.e. connecting to the VM IP address/dns name. Yes we can do this also by exposing the VM via a service but for legacy VM workloads this won't be well received by the end users

All the above can be done by using the bridge CNI, however chaining Cilium would allows us to get Visibility Via Hubble and also Apply network policies to the VMs traffic.


The good new is that all the above is actually working, the bad news is that is a very hacky solution:

###  Step 1: CNI Chaining: 

- Set  `cni.exclusive=false` in the Cilium HELM config, this is required or Cilium will disable Multus and nothing works.

Create a `NetworkAttachmentDefinition` and chain Cilium with Bridge:
```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan3701c
  namespace: vm3701
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br0
spec:
  config: |-
    {
    "name": "vlan3701c",
    "cniVersion": "0.4.0",
    "plugins": [
        {
            "type": "cnv-bridge",
            "bridge": "br0",
            "vlan": 3701
            
        },
       {
          "type": "cilium-cni",
          "chaining-mode": "generic-veth",
          "custom-cni-conf": "false"
        }
    ]
    }  
```

###  Step 2: Disable IP Spoofing Check

Since the VM IP is assigned by the network Cilium has no clue that my VM subnet is X (in my case X=`1.1.1.0/24`) and Cilium does IP SRC spoof check and will drop any traffic sourced from a subnet it does not recognise:

```
root@talos-3sj-8qn:/home/cilium# cilium-dbg monitor --type drop
Listening for events on 16 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
time="2024-09-26T05:13:22Z" level=info msg="Initializing dissection cache..." subsys=monitor
xx drop (Invalid source ip) flow 0x0 to endpoint 0, ifindex 124, file bpf_lxc.c:1427, , identity 12877->unknown: 1.1.1.14 -> 1.1.1.1 EchoRequest 
```

As far as I could tell the only way to disable `SourceIPVerification` is to connect to the Cilium POD on issue the following command:

`root@talos-3sj-8qn:/home/cilium#  cilium config SourceIPVerification=disabled`

Once this is done all works fine my VMs have connectivity however it is not a persistent config change, is there a way to set this in some ConfigMap ? 

### Policy Enforcement

It works as long as CIDR are used, the flows are all seen as external to the cluster and no POD selectors can be used but the below CiliumNetworkPolicy work pretty well and will allow SSH only between my 2 VMs

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: untitled-policy
  namespace: vm3701
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - {}
    - fromCIDRSet:
        - cidr: 1.1.1.0/24
      toPorts:
        - ports:
            - port: "22"
  egress:
    - toEndpoints:
        - {}
    - toCIDRSet:
        - cidr: 1.1.1.0/24
      toPorts:
        - ports:
            - port: "22"
```

and Hubble CLI works fine as well:

```
root@talos-3sj-8qn:/home/cilium# hubble observe  --ip 1.1.1.0/24
Oct  2 03:59:14.357: 1.1.1.15 (ID:16777217) <> 1.1.1.14 (ID:16777217) policy-verdict:none EGRESS DENIED (ICMPv4 EchoRequest)
Oct  2 03:59:14.357: 1.1.1.15 (ID:40106) <> 1.1.1.14 (ID:16777217) Policy denied DROPPED (ICMPv4 EchoRequest)

Oct  2 03:59:16.646: 1.1.1.15:51128 (ID:16777217) -> 1.1.1.14:22 (ID:16777217) policy-verdict:L3-L4 EGRESS ALLOWED (TCP Flags: SYN)
Oct  2 03:59:16.646: 1.1.1.15:51128 (ID:40106) -> 1.1.1.14:22 (ID:16777217) to-stack FORWARDED (TCP Flags: SYN)
Oct  2 03:59:16.646: 1.1.1.15:51128 (ID:40106) -> 1.1.1.14:22 (ID:16777217) policy-verdict:L3-Only INGRESS ALLOWED (TCP Flags: SYN)
```


###  Step 3: Hubble usage

Hubble UI is a bit more finicky to use... Apparently you HAVE to set a namespace in a filter... but no traffic is mapped to a namespace here... so the best I could do is something like this:

![Image](https://github.com/user-attachments/assets/df699034-9525-4cb3-a889-0afa12d76443)


The Visualisation is still quite messy but the flows are working just fine as long as you ignore the fact that there is not mapping to the PODs.


If we could have all of the above supported and polished this would be an amazing feature set as it gives us the ability to migrated existing VMs to KubeVirt and use Cilium for Visibility and Policy enforcement. 

RedHat is doing something similar with the fairly new OVN + OVS-Bridge chaining support but it lacks the Visibility that Hubble can provide us and is OVS based...

**Comment by ttc0419** [comment]
What I wanted is direct connection to pods, which can be achieved using direct native routing and L2 Pod announcements, closing.

**Comment by mvgijssel** [comment]
@camrossi it seems that `cilium config SourceIPVerification=disabled` is configurable and persistent through the Helm chart! I've setup my values.yaml like so:

```yaml
daemon:
  enableSourceIPVerification: false
```

**Comment by camrossi** [comment]
Thank you so much @mvgijssel  for this I will give it a try as well then the inability to have the config persistent was my main issue here.

**Comment by camrossi** [comment]
@mvgijssel  I tested it and it worked for me but I had to change a few things from the original testing I did:

1. Something changed in Cilium defaults and I had to add a vlan-bpf-bypass otherwise the traffic was dropped with a "VLAN ID" something drop reason
2. I am doing Egress GW in my cluster and this requires masquerade but if you do that then the VM traffic is also masqueraded as is not a Subnet that Cilium considered Directed Routing. In the end I just decided some nodes will just run VMs and did a per Node Config:

An example here:

```
apiVersion: cilium.io/v2
kind: CiliumNodeConfig
metadata:
  namespace: kube-system
  name: vms-no-masquerade
spec:
  nodeSelector:
    matchLabels:
     kubernetes.io/hostname: talos-zne-0m1
  defaults:
     enable-bpf-masquerade: "false"
     enable-ipv4-egress-gateway-ha: "false"
     vlan-bpf-bypass: "0"
```

Also disclaimer I am not using this in production is just to mess around at this stage and see what is possible :)
