### ISSUE TITLE
Cilium Ingress and Gateway services are not reachable through NodePort from the localhost/node

### ISSUE THREAD

**Issue by berkayoz** [cilium/cilium#35012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.15.7 and lower than v1.16.0

### What happened?

Cilium Ingress is not reachable from the host of the node in a hybrid kube-proxy setup. Cilium is configured with `nodePort.enabled=true` to keep kube-proxy running alongside Cilium in a hybrid mode. Ingress controller is configured with `ingressController.loadbalancerMode=shared`. MetalLB is used to provide LoadBalancer type services in the cluster.

For reproduction/example, we have a simple nginx deployment, a ClusterIP service and an ingress with `foo.bar.com` for the address. 
```
NAME             TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
cilium-ingress   LoadBalancer   10.152.183.217   10.94.106.5   80:32704/TCP,443:31260/TCP   68s
```

Performing a `curl -vk localhost:32704 -H "Host: foo.bar.com"` or `curl -vk <node-ip>:32704 -H "Host: foo.bar.com"` returns
```
*   Trying 127.0.0.1:32704...
* connect to 127.0.0.1 port 32704 failed: Connection refused
*   Trying ::1:32704...
* connect to ::1 port 32704 failed: Connection refused
* Failed to connect to localhost port 32704 after 0 ms: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 32704 after 0 ms: Connection refused
```

Performing a `curl -vk 10.94.106.5 -H "Host: foo.bar.com"` returns
```
*   Trying 10.94.106.5:80...
* connect to 10.94.106.5 port 80 failed: No route to host
* Failed to connect to 10.94.106.5 port 80 after 3084 ms: No route to host
* Closing connection 0
curl: (7) Failed to connect to 10.94.106.5 port 80 after 3084 ms: No route to host
```

These requests are successful and a response is returned if performed on another host. This host can be a node that is part of the cluster, so `curl -vk <other-node-ip>:32704 -H "Host: foo.bar.com"` is successful. 

The same issue is present for Gateway API resources and behavior is the same. The services for Gateway and Ingress should be reachable from the localhost/node.

This is somehow resolved and not observed when Cilium is configured with `socketLB.enabled=true` but this is not listed as a requirement in the docs.

### How can we reproduce the issue?

1. Get a single-node(or multi) Kubernetes cluster
2. Setup MetalLB and configure with free IP addresses
3. Install Cilium 1.15.8 with values
```
cni:
  binPath: /opt/cni/bin
  confPath: /etc/cni/net.d
disableEnvoyVersionCheck: true
gatewayAPI:
  enabled: true
ingressController:
  defaultSecretNamespace: kube-system
  defaultTLSSecret: ""
  enableProxyProtocol: false
  enabled: true
  loadbalancerMode: shared
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: 10.1.0.0/16
    clusterPoolIPv6PodCIDRList: ""
ipv4:
  enabled: true
ipv6:
  enabled: false
nodePort:
  enableHealthCheck: false
  enabled: true
operator:
  replicas: 1
  ```
4. Apply the [example ingress manifest](https://github.com/canonical/k8s-snap/blob/main/tests/integration/templates/ingress-test.yaml) and the [example gateway manifest](https://github.com/canonical/k8s-snap/blob/main/tests/integration/templates/gateway-test.yaml).
5. Try curling the NodePort or LoadBalancer ip from the local node.

### Cilium Version

```
cilium-cli: v0.16.18 compiled with go1.23.1 on linux/amd64
cilium image (default): v1.16.1
cilium image (stable): v1.16.1
cilium image (running): 1.15.8
```

### Kernel Version

```
Linux k8s-integration-d16e09-1 6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.31.1
```

### Sysdump

[cilium-sysdump-20240923-113129.zip](https://github.com/user-attachments/files/17096764/cilium-sysdump-20240923-113129.zip)

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
