### ISSUE TITLE
1.16.1 Helm ArgoCD install .spec.template.spec.securityContext.appArmorProfile: field not declared in schema

### ISSUE THREAD

**Issue by e3b0c442** [cilium/cilium#35046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

When attempting to install Cilium via ArgoCD using kustomize Helm chart generator, the following error `Failed to compare desired state to live state: failed to calculate diff: error calculating structured merge diff: error building typed value from live resource: .spec.template.spec.securityContext.appArmorProfile: field not declared in schema`.

Expected diff to behave normally.

There is apparent documentation for this issue, but the suggested fix does not work; even when enabling ServerSideApply, the issue manifests.

I tried setting the security contexts explicitly with empty objects, no improvement. I have also verified that the AppArmor feature is enabled in my k3s install, and adding the `--helm-kube-version` flag to `kustomize.buildOptions` to explicitly match my cluster version of 1.30.

### How can we reproduce the issue?

1. Install ArgoCD
2. Add application with ArgoCD, using kustomize HelmChartGenerator
3. Attempt to view Cilium app in ArgoCD

### Cilium Version

cilium-cli: v0.16.18 compiled with go1.23.1 on darwin/arm64
cilium image (default): v1.16.1
cilium image (stable): v1.16.1
cilium image (running): unknown. Unable to obtain cilium version. Reason: release: not found

### Kernel Version

Linux ichi-temp 6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.30.4+k3s1

### Sysdump

[cilium-sysdump-20240925-200033.zip](https://github.com/user-attachments/files/17140329/cilium-sysdump-20240925-200033.zip)

### Anything else?

Kustomization as exists in my GitOps repo:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/experimental-install.yaml
  - gtw.yaml
  - cbgpadvert.yaml
  - cbgpcluster.yaml
  - cbgppeer.yaml
  - ippool.yaml
helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    version: 1.16.1
    releaseName: cilium
    namespace: kube-system
    includeCRDs: true
    valuesInline:
      k8sServiceHost: 192.168.227.227
      k8sServicePort: 6443
      kubeProxyReplacement: "true"
      devices: br0
      ipam:
        operator:
          clusterPoolIPv4PodCIDRList: 
            - "10.42.0.0/16"
      gatewayAPI:
        enabled: true
      bgpControlPlane:
        enabled: true
      podSecurityContext: {}
      envoy:
        podSecurityContext: {}
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
