### ISSUE TITLE
UDP timeout when leaseholder different than pod node

### ISSUE THREAD

**Issue by prismatic-koi** [cilium/cilium#35071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

When testing DNS queries (using dig) to a l2announce load-balanced service (blocky DNS) which exposes UDP and TCP on port 53, UDP queries time out when the l2announce holder is different than the node where the pod is running. TCP queries are resolved successfully.

If the l2annouce leaseholder is the same as the node the pod is running on, UDP and TCP queries resolve successfully.

I long suspected I was experiencing this issue #9207 but having tested with cilium `v1.17.0-pre.0` and spending more time debugging, I have concluded that the resolution in pr #33434 makes no difference to the bug, though it may be related since only UDP traffic seem to timeout.

I have been able to temporarily 'resolve' the issue by editing the leases directly and setting the `holderIdentity` to the 'correct' node

Edit: I forgot to mention, my entire flux cluster configuration is publicly available to prod at and search [here](https://github.com/lucidph3nx/home-ops) if that is any use.

### How can we reproduce the issue?

cilium installed via helm (flux) using the following values:
(note, I have removed hubble config as it shouldnt be relevant)
```yaml
    autoDirectNodeRoutes: true
    bandwidthManager:
      enabled: true
    bpf:
      masquerade: true
    bgp:
      enabled: false
      announce:
        loadbalancerIP: true
    cluster:
      name: ${CLUSTER_NAME}
      id: 1
    enableRuntimeDeviceDetection: true
    endpointRoutes:
      enabled: true
    ipam:
      mode: kubernetes
    ipv4NativeRoutingCIDR: 10.42.0.0/16
    k8sServiceHost: ${CONTROLPLANE_IP}
    k8sServicePort: 6443
    kubeProxyReplacement: true
    nodePort:
      enabled: true
    l2announcements:
      enabled: true
      leaseDuration: 120s
      leaseRenewDeadline: 60s
      leaseRetryPeriod: 1s
    loadBalancer:
      algorithm: maglev
      mode: dsr
      protocolDifferentiation:
        enabled: true
    k8sClientRateLimit:
      qps: 80
      burst: 160
    localRedirectPolicy: true
    operator:
      rollOutPods: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true
    rollOutCiliumPods: true
    routingMode: native
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
```

the service in question looks something like this (I've removed a few labels and uuid/version pieces for brevity)
```yaml
apiVersion: v1                                                                                 
kind: Service                                                                                  
metadata:                                                                                      
  annotations:                                                                                 
    io.cilium/lb-ipam-ips: 10.87.42.11                                                         
    meta.helm.sh/release-name: blocky-primary                                                  
    meta.helm.sh/release-namespace: networking                                                                                             
  name: blocky-primary-dns                                                                     
  namespace: networking                                                                                                                                                                                     
spec:                                                                                          
  allocateLoadBalancerNodePorts: true                                                          
  clusterIP: 10.43.77.202                                                                      
  clusterIPs:                                                                                  
  - 10.43.77.202                                                                               
  externalTrafficPolicy: Cluster                                                               
  internalTrafficPolicy: Cluster                                                               
  ipFamilies:                                                                                  
  - IPv4                                                                                       
  ipFamilyPolicy: SingleStack                                                                  
  ports:                                                                                       
  - name: dns-tcp                                                                              
    nodePort: 32604                                                                            
    port: 53                                                                                   
    protocol: TCP                                                                              
    targetPort: 53                                                                             
  - name: dns-udp                                                                              
    nodePort: 32604                                                                            
    port: 53                                                                                   
    protocol: UDP                                                                              
    targetPort: 53                                                                             
  selector:                                                                                    
    app.kubernetes.io/component: blocky-primary                                                
    app.kubernetes.io/instance: blocky-primary                                                 
    app.kubernetes.io/name: blocky-primary                                                     
  sessionAffinity: None                                                                        
  type: LoadBalancer                                                                           
status:                                                                                        
  conditions:                                                                                  
  - lastTransitionTime: "2024-09-27T21:52:48Z"                                                 
    message: ""                                                                                
    reason: satisfied                                                                          
    status: "True"                                                                             
    type: cilium.io/IPAMRequestSatisfied                                                       
  loadBalancer:                                                                                
    ingress:                                                                                   
    - ip: 10.87.42.11                                                                          
      ipMode: VIP    
```

also, if at all relevant, here is my CiliumL2AnnoucementPolicy
```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy
spec:
  loadBalancerIPs: true
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
```

### Cilium Version

1.16.2
but I have also tested with v1.17.0-pre.0

### Kernel Version

Linux node0 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.31.1+k3s1

### Regression

never worked under cilium (worked with metallb until I switched to cilium about 1 year ago)

### Sysdump

[cilium-sysdump-20240928-110157.zip](https://github.com/user-attachments/files/17171352/cilium-sysdump-20240928-110157.zip)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
