### ISSUE TITLE
policy: incorrect policy computed for endpoint when L4-only policy and L7-policy are specified for the same port

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3509]
Consider the following rule

```
specs:
- endpointSelector:
    matchLabels:
      id: app1
  ingress:
  - fromEndpoints:
    - matchLabels:
        id: app2
    toPorts:
    - ports:
      - port: "9093"
        protocol: TCP
      rules:
        http:
        - method: ^GET$
          path: ^/metrics$
  - toPorts:
    - ports:
      - port: "9093"
        protocol: TCP
```

In tabular form, this equates to:
```
L3      |     L4   |  L7
--------|----------|--------------------
*.      | TCP/9093 |   *
--------|----------|--------------------
app2    | TCP/9093 |   GET ^/metrics
```

Based on the Cilium policy model, we expect that to collapse to the following:

```
L3     |     L4   |  L7
-------|----------|-------------------
*.     | TCP/9093 |   *
```

In other words, the L4-only rule here shadows the L3-L4-L7 rule. However, currently, in Cilium, this forces all inbound TCP traffic on port 9093 to get forwarded to the proxy, which only allows traffic to `GET ^/metrics`. 

Resolved policy for app1 endpoint:
```
   "policy": {
      "realized": {
        "allowed-egress-identities": [],
        "allowed-ingress-identities": [
          1
        ],
        "build": 9,
        "cidr-policy": {
          "egress": [],
          "ingress": []
        },
        "id": 7846,
        "l4": {
          "egress": [],
          "ingress": [
            {
              "derived-from-rules": [
                [
                  "unspec:io.cilium.k8s.policy.name=rule1",
                  "unspec:io.cilium.k8s.policy.namespace=default"
                ],
                [
                  "unspec:io.cilium.k8s.policy.name=rule1",
                  "unspec:io.cilium.k8s.policy.namespace=default"
                ]
              ],
              "rule": "{\n  \"port\": 9093,\n  \"protocol\": \"TCP\",\n  \"l7-rules\": [\n    {\n      \"any.id=app2,k8s.io.kubernetes.pod.namespace=default\": {\n        \"http\": [\n          {\n            \"path\": \"^/metrics$\",\n            \"method\": \"^GET$\"\n          }\n        ]\n      }\n    }\n  ]\n}"
            }
          ]
        },
        "policy-revision": 9
      }
    },
...
   "proxy-statistics": [
      {
        "location": "ingress",
        "port": 80,
        "protocol": "http",
        "statistics": {
          "requests": {},
          "responses": {}
        }
      },
      {
        "allocated-proxy-port": 15084,
        "location": "ingress",
        "port": 9093,
        "protocol": "http",
        "statistics": {
          "requests": {},
          "responses": {}
        }
      }
    ],
```

As one can see, all traffic is being redirected to the proxy on port 9093. Instead, no traffic should be directed to the proxy because we allow all L7 traffic implicitly with `toPorts` containing no L7-related policy, *despite the fact that there is another rule for the same port which has L7 policy*.

Change the policy resolving logic to correctly have the policy computed when L4-only policy and L3-L4-L7 policy are applied on the same port.
