### ISSUE TITLE
CiliumBGPAdvertisement not advertising LoadBalancerIPs, all other adverisements work as expected

### ISSUE THREAD

**Issue by starcraft66** [cilium/cilium#35121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

I applied the following config to my cluster:

```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool
spec:
  blocks:
  - cidr: "10.235.0.0/18"
  - cidr: "2a10:4741:37:88:3::/80"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: bgp-spike
spec:
  bgpInstances:
  - name: spike
    localASN: 64513
    peers:
    - name: 305-1700-gw-v4
      peerASN: 64512
      peerAddress: 172.17.51.1
      peerConfigRef:
        name: cilium-peer
    - name: 305-1700-gw-v6
      peerASN: 64512
      peerAddress: 2a10:4741:37:51::1
      peerConfigRef:
        name: cilium-peer
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  families:
  - afi: ipv4
    safi: unicast
    advertisements:
      matchLabels:
        advertise: "bgp"
  - afi: ipv6
    safi: unicast
    advertisements:
      matchLabels:
        advertise: "bgp"
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
  - advertisementType: "PodCIDR"
  - advertisementType: "Service"
    service:
      addresses:
      - ClusterIP
      - ExternalIP
      - LoadBalancerIP
    selector:
      matchExpressions:
      # All services
      - {key: somekey, operator: NotIn, values: ['never-used-value']}
 ```
 
 I used the following helm values:
 
 ```
 # This is installed by Nix
cni:
  install: false

# Enable BGP
bgpControlPlane:
  enabled: true

operator:
  # We only have one node
  replicas: 1

# Use the pod subnet slices distributed by kube-apiserver to each kubelet
# rather than reinventing the wheel with Cilium's native IPAM
ipam:
  mode: kubernetes

# Dual-stack
ipv4:
  enabled: true
ipv6:
  enabled: true

# No masquerading of any kind, this will be performed by the router at the edge for v4
enableIPv4Masquerade: false
enableIPv6Masquerade: false

# Have not been able to validate these
enableIPv4BIGTCP: false
enableIPv6BIGTCP: false

# No tunelling, native routing only
tunnelProtocol: ""

# Enable observability
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

# Enable Prometheus metrics
prometheus:
  enabled: true

kubeProxyReplacement: "true"
# k8s.305-1700.tdude.co
k8sServiceHost: "2a10:4741:37:51::8:1"
k8sServicePort: 443

# Enable native routing (no tunelling)
routingMode: native
# Cilium states that for native routing, all nodes need to have a route to other nodes
# so we can't just rely on the default route to get us there.
# https://docs.cilium.io/en/stable/network/concepts/routing/#id3
# All nodes are located on the same L2 segment so we can enable direct routes
# We should look into kube-router to get an equivalent
# of calico's cluster mesh
autoDirectNodeRoutes: true

# Enable direct server return to preserve the client's source IP
# when externalTrafficPolicy is set to Cluster (required to share
# a single IP between multiple LoadBalancer services targeting
# the pods on different nodes)
# https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#direct-server-return-dsr-with-ipv4-option-ipv6-extension-header
# https://github.com/cilium/cilium/issues/30700
loadBalancer:
  mode: dsr
  dsrDispatch: opt
  protocolDifferentiation:
    enabled: true
```

Debug info:

```
@Zecora:~/s/infrastructure (master) [$!?] ❯ k exec -it -n kube-system ds/cilium -- cilium-dbg bgp routes available ipv4 unicast
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init)
VRouter   Prefix              NextHop   Age        Attrs
64513     10.235.103.185/32   0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.104.224/32   0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.111.55/32    0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.112.78/32    0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.113.104/32   0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.114.144/32   0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.117.121/32   0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.119.115/32   0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.128.0/24     0.0.0.0   8h24m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.64.1/32      0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.64.2/32      0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.70.105/32    0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.71.84/32     0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.74.105/32    0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.81.229/32    0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.82.90/32     0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.85.224/32    0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.86.193/32    0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.95.132/32    0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
64513     10.235.97.136/32    0.0.0.0   8h21m16s   [{Origin: i} {Nexthop: 0.0.0.0}]   
@Zecora:~/s/infrastructure (master) [$!?] ❯ k exec -it -n kube-system ds/cilium -- cilium-dbg bgp routes available ipv6 unicast
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init)
VRouter   Prefix                        NextHop   Age        Attrs
64513     2a10:4741:37:88:1::2/128      ::        8h21m26s   [{Origin: i} {MpReach(ipv6-unicast): {Nexthop: ::, NLRIs: [2a10:4741:37:88:1::2/128]}}]      
64513     2a10:4741:37:88:1::a8a5/128   ::        8h21m26s   [{Origin: i} {MpReach(ipv6-unicast): {Nexthop: ::, NLRIs: [2a10:4741:37:88:1::a8a5/128]}}]   
64513     2a10:4741:37:88:1::d349/128   ::        8h21m26s   [{Origin: i} {MpReach(ipv6-unicast): {Nexthop: ::, NLRIs: [2a10:4741:37:88:1::d349/128]}}]   
64513     2a10:4741:37:88:2::/120       ::        8h24m26s   [{Origin: i} {MpReach(ipv6-unicast): {Nexthop: ::, NLRIs: [2a10:4741:37:88:2::/120]}}]       
@Zecora:~/s/infrastructure (master) [$!?] ❯ k exec -it -n kube-system ds/cilium -- cilium-dbg bgp route-policies               
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init)
VRouter   Policy Name                                                                            Type     Match Peers              Match Prefixes (Min..Max Len)            RIB Action   Path Actions
64513     305-1700-gw-v4-ipv4-PodCIDR                                                            export   172.17.51.1/32           10.235.128.0/24 (24..24)                 accept            
64513     305-1700-gw-v4-ipv4-Service-argocd-applicationset-controller-argocd-ClusterIP          export   172.17.51.1/32           10.235.114.144/32 (32..32)               accept            
64513     305-1700-gw-v4-ipv4-Service-argocd-dex-server-argocd-ClusterIP                         export   172.17.51.1/32           10.235.104.224/32 (32..32)               accept            
64513     305-1700-gw-v4-ipv4-Service-argocd-metrics-argocd-ClusterIP                            export   172.17.51.1/32           10.235.85.224/32 (32..32)                accept            
64513     305-1700-gw-v4-ipv4-Service-argocd-notifications-controller-metrics-argocd-ClusterIP   export   172.17.51.1/32           10.235.103.185/32 (32..32)               accept            
64513     305-1700-gw-v4-ipv4-Service-argocd-redis-argocd-ClusterIP                              export   172.17.51.1/32           10.235.95.132/32 (32..32)                accept            
64513     305-1700-gw-v4-ipv4-Service-argocd-repo-server-argocd-ClusterIP                        export   172.17.51.1/32           10.235.113.104/32 (32..32)               accept            
64513     305-1700-gw-v4-ipv4-Service-argocd-server-argocd-ClusterIP                             export   172.17.51.1/32           10.235.70.105/32 (32..32)                accept            
64513     305-1700-gw-v4-ipv4-Service-argocd-server-metrics-argocd-ClusterIP                     export   172.17.51.1/32           10.235.86.193/32 (32..32)                accept            
64513     305-1700-gw-v4-ipv4-Service-cert-manager-cert-manager-ClusterIP                        export   172.17.51.1/32           10.235.117.121/32 (32..32)               accept            
64513     305-1700-gw-v4-ipv4-Service-cert-manager-webhook-cert-manager-ClusterIP                export   172.17.51.1/32           10.235.71.84/32 (32..32)                 accept            
64513     305-1700-gw-v4-ipv4-Service-hubble-peer-kube-system-ClusterIP                          export   172.17.51.1/32           10.235.112.78/32 (32..32)                accept            
64513     305-1700-gw-v4-ipv4-Service-hubble-relay-kube-system-ClusterIP                         export   172.17.51.1/32           10.235.119.115/32 (32..32)               accept            
64513     305-1700-gw-v4-ipv4-Service-hubble-ui-kube-system-ClusterIP                            export   172.17.51.1/32           10.235.82.90/32 (32..32)                 accept            
64513     305-1700-gw-v4-ipv4-Service-kube-dns-kube-system-ClusterIP                             export   172.17.51.1/32           10.235.64.2/32 (32..32)                  accept            
64513     305-1700-gw-v4-ipv4-Service-kubernetes-default-ClusterIP                               export   172.17.51.1/32           10.235.64.1/32 (32..32)                  accept            
64513     305-1700-gw-v4-ipv4-Service-oauth2-proxy-traefik-ClusterIP                             export   172.17.51.1/32           10.235.74.105/32 (32..32)                accept            
64513     305-1700-gw-v4-ipv4-Service-traefik-dashboard-traefik-ClusterIP                        export   172.17.51.1/32           10.235.97.136/32 (32..32)                accept            
64513     305-1700-gw-v4-ipv4-Service-traefik-metrics-traefik-ClusterIP                          export   172.17.51.1/32           10.235.111.55/32 (32..32)                accept            
64513     305-1700-gw-v4-ipv4-Service-traefik-traefik-ClusterIP                                  export   172.17.51.1/32           10.235.81.229/32 (32..32)                accept            
64513     305-1700-gw-v4-ipv6-PodCIDR                                                            export   172.17.51.1/32           2a10:4741:37:88:2::/120 (120..120)       accept            
64513     305-1700-gw-v4-ipv6-Service-kube-dns-kube-system-ClusterIP                             export   172.17.51.1/32           2a10:4741:37:88:1::2/128 (128..128)      accept            
64513     305-1700-gw-v4-ipv6-Service-traefik-dashboard-traefik-ClusterIP                        export   172.17.51.1/32           2a10:4741:37:88:1::d349/128 (128..128)   accept            
64513     305-1700-gw-v4-ipv6-Service-traefik-traefik-ClusterIP                                  export   172.17.51.1/32           2a10:4741:37:88:1::a8a5/128 (128..128)   accept            
64513     305-1700-gw-v6-ipv4-PodCIDR                                                            export   2a10:4741:37:51::1/128   10.235.128.0/24 (24..24)                 accept            
64513     305-1700-gw-v6-ipv4-Service-argocd-applicationset-controller-argocd-ClusterIP          export   2a10:4741:37:51::1/128   10.235.114.144/32 (32..32)               accept            
64513     305-1700-gw-v6-ipv4-Service-argocd-dex-server-argocd-ClusterIP                         export   2a10:4741:37:51::1/128   10.235.104.224/32 (32..32)               accept            
64513     305-1700-gw-v6-ipv4-Service-argocd-metrics-argocd-ClusterIP                            export   2a10:4741:37:51::1/128   10.235.85.224/32 (32..32)                accept            
64513     305-1700-gw-v6-ipv4-Service-argocd-notifications-controller-metrics-argocd-ClusterIP   export   2a10:4741:37:51::1/128   10.235.103.185/32 (32..32)               accept            
64513     305-1700-gw-v6-ipv4-Service-argocd-redis-argocd-ClusterIP                              export   2a10:4741:37:51::1/128   10.235.95.132/32 (32..32)                accept            
64513     305-1700-gw-v6-ipv4-Service-argocd-repo-server-argocd-ClusterIP                        export   2a10:4741:37:51::1/128   10.235.113.104/32 (32..32)               accept            
64513     305-1700-gw-v6-ipv4-Service-argocd-server-argocd-ClusterIP                             export   2a10:4741:37:51::1/128   10.235.70.105/32 (32..32)                accept            
64513     305-1700-gw-v6-ipv4-Service-argocd-server-metrics-argocd-ClusterIP                     export   2a10:4741:37:51::1/128   10.235.86.193/32 (32..32)                accept            
64513     305-1700-gw-v6-ipv4-Service-cert-manager-cert-manager-ClusterIP                        export   2a10:4741:37:51::1/128   10.235.117.121/32 (32..32)               accept            
64513     305-1700-gw-v6-ipv4-Service-cert-manager-webhook-cert-manager-ClusterIP                export   2a10:4741:37:51::1/128   10.235.71.84/32 (32..32)                 accept            
64513     305-1700-gw-v6-ipv4-Service-hubble-peer-kube-system-ClusterIP                          export   2a10:4741:37:51::1/128   10.235.112.78/32 (32..32)                accept            
64513     305-1700-gw-v6-ipv4-Service-hubble-relay-kube-system-ClusterIP                         export   2a10:4741:37:51::1/128   10.235.119.115/32 (32..32)               accept            
64513     305-1700-gw-v6-ipv4-Service-hubble-ui-kube-system-ClusterIP                            export   2a10:4741:37:51::1/128   10.235.82.90/32 (32..32)                 accept            
64513     305-1700-gw-v6-ipv4-Service-kube-dns-kube-system-ClusterIP                             export   2a10:4741:37:51::1/128   10.235.64.2/32 (32..32)                  accept            
64513     305-1700-gw-v6-ipv4-Service-kubernetes-default-ClusterIP                               export   2a10:4741:37:51::1/128   10.235.64.1/32 (32..32)                  accept            
64513     305-1700-gw-v6-ipv4-Service-oauth2-proxy-traefik-ClusterIP                             export   2a10:4741:37:51::1/128   10.235.74.105/32 (32..32)                accept            
64513     305-1700-gw-v6-ipv4-Service-traefik-dashboard-traefik-ClusterIP                        export   2a10:4741:37:51::1/128   10.235.97.136/32 (32..32)                accept            
64513     305-1700-gw-v6-ipv4-Service-traefik-metrics-traefik-ClusterIP                          export   2a10:4741:37:51::1/128   10.235.111.55/32 (32..32)                accept            
64513     305-1700-gw-v6-ipv4-Service-traefik-traefik-ClusterIP                                  export   2a10:4741:37:51::1/128   10.235.81.229/32 (32..32)                accept            
64513     305-1700-gw-v6-ipv6-PodCIDR                                                            export   2a10:4741:37:51::1/128   2a10:4741:37:88:2::/120 (120..120)       accept            
64513     305-1700-gw-v6-ipv6-Service-kube-dns-kube-system-ClusterIP                             export   2a10:4741:37:51::1/128   2a10:4741:37:88:1::2/128 (128..128)      accept            
64513     305-1700-gw-v6-ipv6-Service-traefik-dashboard-traefik-ClusterIP                        export   2a10:4741:37:51::1/128   2a10:4741:37:88:1::d349/128 (128..128)   accept            
64513     305-1700-gw-v6-ipv6-Service-traefik-traefik-ClusterIP                                  export   2a10:4741:37:51::1/128   2a10:4741:37:88:1::a8a5/128 (128..128)   accept            
64513     allow-local                                                                            import                                                                     accept            
@Zecora:~/s/infrastructure (master) [$!?] ❯ k exec -it -n kube-system ds/cilium -- cilium-dbg bgp peers                        
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init)
Local AS   Peer AS   Peer Address             Session       Uptime     Family         Received   Advertised
64513      64512     172.17.51.1:179          established   8h24m37s   ipv4/unicast   20         21   
                                                                       ipv6/unicast   4          5    
64513      64512     2a10:4741:37:51::1:179   established   8h24m36s   ipv4/unicast   20         21   
                                                                       ipv6/unicast   4          5    
@Zecora:~/s/infrastructure (master) [$!?] ❯ kubectl get svc -A                               
NAMESPACE      NAME                                      TYPE           CLUSTER-IP                EXTERNAL-IP                      PORT(S)                                    AGE
argocd         argocd-applicationset-controller          ClusterIP      10.235.114.144            <none>                           7000/TCP,8080/TCP                          9h
argocd         argocd-dex-server                         ClusterIP      10.235.104.224            <none>                           5556/TCP,5557/TCP,5558/TCP                 9h
argocd         argocd-metrics                            ClusterIP      10.235.85.224             <none>                           8082/TCP                                   9h
argocd         argocd-notifications-controller-metrics   ClusterIP      10.235.103.185            <none>                           9001/TCP                                   9h
argocd         argocd-redis                              ClusterIP      10.235.95.132             <none>                           6379/TCP                                   9h
argocd         argocd-repo-server                        ClusterIP      10.235.113.104            <none>                           8081/TCP,8084/TCP                          9h
argocd         argocd-server                             ClusterIP      10.235.70.105             <none>                           80/TCP,443/TCP                             9h
argocd         argocd-server-metrics                     ClusterIP      10.235.86.193             <none>                           8083/TCP                                   9h
cert-manager   cert-manager                              ClusterIP      10.235.117.121            <none>                           9402/TCP                                   9h
cert-manager   cert-manager-webhook                      ClusterIP      10.235.71.84              <none>                           443/TCP                                    9h
default        kubernetes                                ClusterIP      10.235.64.1               <none>                           443/TCP                                    3d9h
kube-system    cilium-envoy                              ClusterIP      None                      <none>                           9964/TCP                                   3d8h
kube-system    hubble-peer                               ClusterIP      10.235.112.78             <none>                           443/TCP                                    3d8h
kube-system    hubble-relay                              ClusterIP      10.235.119.115            <none>                           80/TCP                                     3d8h
kube-system    hubble-ui                                 ClusterIP      10.235.82.90              <none>                           80/TCP                                     3d8h
kube-system    kube-dns                                  ClusterIP      10.235.64.2               <none>                           53/UDP,53/TCP,9153/TCP                     3d8h
traefik        oauth2-proxy                              ClusterIP      10.235.74.105             <none>                           80/TCP,44180/TCP                           9h
traefik        traefik                                   LoadBalancer   10.235.81.229             10.235.0.0,2a10:4741:37:88:3::   80:30904/TCP,443:30277/TCP,443:30277/UDP   9h
traefik        traefik-dashboard                         ClusterIP      2a10:4741:37:88:1::d349   <none>                           80/TCP                                     9h
traefik        traefik-metrics                           ClusterIP      10.235.111.55             <none>                           9100/TCP                                   9h
```
As you can see, `10.235.0.0` and `2a10:4741:37:88:3::` are not advertised to my router as expected.

### How can we reproduce the issue?

Install cilium with the above values and bgp configurations. Check routes received by router.

### Cilium Version

Client: 1.17.0-pre.0 d41440cb 2024-09-04T23:25:39+00:00 go version go1.23.0 linux/amd64
Daemon: 1.17.0-pre.0 d41440cb 2024-09-04T23:25:39+00:00 go version go1.23.0 linux/amd64

### Kernel Version

Linux spike 6.6.48 #1-NixOS SMP PREEMPT_DYNAMIC Thu Aug 29 15:33:59 UTC 2024 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.31.0

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
