### ISSUE TITLE
NetworkPolicy Not Honoring CIDR

### ISSUE THREAD

**Issue by moserke** [cilium/cilium#35212]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

When trying to apply a NetworkPolicy to a cluster running the cilium CNI, whenever I supply a CIDR in the policy it doesn't work.  

This policy fails to allow traffic through:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-rule
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 10250
          protocol: TCP
        - port: 443
          protocol: TCP
```

However this policy works:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-rule
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
      ports:
        - port: 10250
          protocol: TCP
        - port: 443
          protocol: TCP
```

Is the ipBlock not supported in the native k8s network policy?

### How can we reproduce the issue?

helm values:

encryption = {
        enabled        = true,
        type           = "wireguard",
        nodeEncryption = true
      },
      hostFirewall = {
        enabled = true
      },
      hubble = {
        enabled = false,
        relay = {
          enabled = false
        },
        ui = {
          enabled = false
        }
      },
      eni = {
        enabled                   = true
        awsReleaseExcessIPs       = true
        awsEnablePrefixDelegation = true
      },
      ipam = {
        mode = "eni"
      },
      enableIPv4Masquerade = false,
      enableIPv6Masquerade = false,
      routingMode          = "native",
      kubeProxyReplacement = true,
      k8sServicePort       = 443

### Cilium Version

1.16.2

### Kernel Version

Linux  6.1.109-118.189.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Sep 10 08:59:12 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.31

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by moserke** [comment]
I believe I have tracked this down a distinction between "world" and "cluster".  Leveraging the policy editor you can see the distinction, as well as in the documentation it defines "Allowing to world is identical to allowing to CIDR 0.0.0.0/0".  Based on this understanding I now know why it was not working.  However, I find this relatively esoteric and confusing to define 0.0.0.0/0 as everything EXCEPT things in the cluster.  It's much more logical to understand 0.0.0.0/0 to match ALL traffic regardless of where it is, as this CIDR mask covers any possible IP.

Given my use cases and needs I have switched over to the Cilium based policy definitions and away from the native NetworkPolicy objects, but wanted to follow up on this to close the loop.

![Image](https://github.com/user-attachments/assets/6b579292-8718-4b07-aa8a-98b41c3933ea)
![Image](https://github.com/user-attachments/assets/8ce1a438-7628-45dc-9c78-784eea4862f9)

**Comment by erikschul** [comment]
I think I faced the same issue (for hours). As with you, it worked when I only used `ports`, and stopped working when I added `ipBlock`.

@julianwiedmann 
In my opinion, this is a bug. The link you referred to lists several issues. But this CIDR (10.13.0.10) is not part of my podCIDR. ("where ipBlock belongs to podCIDR"), and the other issue is closed.
But in my opinion the issue is fairly straightforward, configuring an ipBlock should work?

> 
> I'm having an issue where I want prometheus to scrape the kube-apiserver, which is an external service (not a pod)
> but it gets EGRESS DENIED despite allowing everything.
> 
> kube-prometheus-stack/prometheus-kube-prometheus-stack-prometheus-0:51582 (ID:21354) <> 10.13.0.10:10250 (kube-apiserver) policy-verdict:none EGRESS DENIED (TCP Flags: SYN)
> kube-prometheus-stack/prometheus-kube-prometheus-stack-prometheus-0:51582 (ID:21354) <> 10.13.0.10:10250 (kube-apiserver) Policy denied DROPPED (TCP Flags: SYN)
> kube-prometheus-stack/kube-prometheus-stack-operator-5fdfd5d6bc-dwvgt:57034 (ID:57301) <> 10.13.0.10:6443 (kube-apiserver) policy-verdict:none EGRESS DENIED (TCP Flags: SYN)
> kube-prometheus-stack/kube-prometheus-stack-operator-5fdfd5d6bc-dwvgt:57034 (ID:57301) <> 10.13.0.10:6443 (kube-apiserver) Policy denied DROPPED (TCP Flags: SYN)
> kube-prometheus-stack/prometheus-kube-prometheus-stack-prometheus-0:45706 (ID:21354) <> 10.13.0.10:10259 (kube-apiserver) policy-verdict:none EGRESS DENIED (TCP Flags: SYN)
> 




```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: untitled-policy
  namespace: kube-prometheus-stack
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
    - from:
        - podSelector: {}
    - from:
        - namespaceSelector: {}
  egress:
    - to:
        - podSelector: {}
    - to:
        - namespaceSelector: {}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
```
