### ISSUE TITLE
CFP: Include CiliumNetworkPolicy to ensure connectivity between hubble-ui and hubble-relay

### ISSUE THREAD

**Issue by maxpain** [cilium/cilium#35348]
Hello. I deploy the Cilium Helm chart with `policyEnforcementMode: always`, and it would be convenient to optionally deploy `CiliumNetworkPolicy` to ensure connectivity between `hubble-ui` and `hubble-relay`.

**Comment by maxpain** [comment]
```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: hubble-relay
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      k8s-app: hubble-relay
  egress:
    - toEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "4244"
              protocol: TCP
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s-app: hubble-ui
```

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: hubble-ui
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      k8s-app: hubble-ui
  egress:
    - toEndpoints:
        - matchLabels:
            k8s-app: hubble-relay
```
