### ISSUE TITLE
cilium removes default routes on the master machine

### ISSUE THREAD

**Issue by mertcangokgoz** [cilium/cilium#35343]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Default routes are being deleted on my master machines behind NAT. I am losing machine access. I tried very hard to solve it but without success, I have nothing on my machine except 1 private ip. I set up my cluster in Hetzner and everything is fine and running smoothly.

It only removes the default routes that I use for cilium nat every day. 

I am looking for a solution to this situation.

### How can we reproduce the issue?

1. Reinstall cilium with helm
2. Change route mode to native

### Cilium Version

1.16.2

### Kernel Version

6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.1+k3s1

### Anything else?

I edited /etc/dhcpcd.conf to remove the option classless_static_routes line.

As a result the following situation occurred, cilium assigned another host as default gw, which I don't want.

![Image](https://github.com/user-attachments/assets/4c87fa02-a616-4e9f-8e23-fff24f0b30ad)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Sorry, given the volume of issues reported in Cilium I am unable to investigate a sysdump on your behalf. At the moment I'm not seeing any direct evidence that Cilium is the cause of this issue. There's certainly a chance it's caused by Cilium, but we would need to see for instance a log correlated with the time when the issue occurs in order to gain some confidence that it is Cilium making this change and not some other piece of software. I would also suggest inspecting broader system logs around that time to see whether there is any other evidence of activity from any other networking component on the system that may be correlated.

**Comment by mertcangokgoz** [comment]
I added the image for this reason, how can cilium_net be the default dateway on the master machine?

**Comment by joestringer** [comment]
I agree that per your image the Linux kernel is configured that way, what I don't yet understand is how that happens. The one peculiar thing actually when I look closer at the default route... there is this unusual `metric 1001003`. As far as I can tell, Cilium does not configure this specific metric value itself. That might be the hint we need to narrow down who is configuring the route.

It doesn't make sense to me that `cilium_net` is the default gateway, but I could be missing some context. Given that you've got tunneling mode enabled, at the very least I would expect that node-to-node traffic is routed via the "native" network interface attached directly to the network, not the `cilium_*` devices. Typically Cilium would be expected to route only traffic towards Pod IP ranges into such interfaces.

**Comment by mertcangokgoz** [comment]
I updated my helm configuration as below, but as I said I am sure that somehow cilium changed the default route settings. 

So how?

I didn't have this problem when I used flannel, but performance issues with it. switched to cilium and encountered this problem. don't have any log for now but I am trying to find it because it directly affects our services.


```yaml
routingMode: "tunnel"
tunnelProtocol: "geneve"

rollOutCiliumPods: true
priorityClassName: "system-node-critical"

ipam:
  mode: "kubernetes"
  operator:
    clusterPoolIPv4PodCIDRList: 10.244.0.0/16

kubeProxyReplacement: true

ipv4:
  enabled: true
ipv6:
  enabled: false

bandwidthManager:
  bbr: true

hubble:
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - http
  enabled: true
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
  tls:
    enabled: false

operator:
  replicas: 2
  rollOutPods: true
  priorityClassName: "system-node-critical"

hostFirewall:
  enabled: false
```
