### ISSUE TITLE
Ingress "force-https" annotation applies to all Ingresses for a given hostname

### ISSUE THREAD

**Issue by snovak7** [cilium/cilium#35347]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

With Cilium 1.16.1 with Cert Manager 1.15.x I added Cluster Issuer that would apply an annotation on resolver ingress template with `ingress.cilium.io/force-https: disabled`

### How can we reproduce the issue?

Install Cilium
Enable Ingress Controller
Setup Cert Manager with ClusterIssuer

```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    solvers:
      - http01:
          ingress:
            ingressClassName: cilium
            ingressTemplate:
              metadata:
                annotations:
                  ingress.cilium.io/force-https: disabled
```

### Cilium Version

1.16.1

### Kernel Version

5.14

### Kubernetes Version

1.30.4

### Sysdump

# cilium sysdump
Error: unknown command "sysdump" for "cilium-dbg"
Run 'cilium-dbg --help' for usage.
unknown command "sysdump" for "cilium-dbg"

### Relevant log output

No root ingress

$ curl -v -o- http://hostname.local/.well-known/acme-challenge/GwuRA1lujBcuyJDn4_nkBPhfOXoVacx7TfoaAJtNXQ4
*   Trying X.Y.Z.A:80...
* Connected to hostname.local (X.Y.Z.A) port 80 (#0)
> GET /.well-known/acme-challenge/GwuRA1lujBcuyJDn4_nkBPhfOXoVacx7TfoaAJtNXQ4 HTTP/1.1
> Host: hostname.local
> User-Agent: curl/7.76.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< location: https://hostname.local/.well-known/acme-challenge/GwuRA1lujBcuyJDn4_nkBPhfOXoVacx7TfoaAJtNXQ4
< date: Thu, 10 Oct 2024 15:02:37 GMT
< server: envoy
< content-length: 0
<
* Connection #0 to host hostname.local left intact

Root ingress with ingress.cilium.io/force-https: disabled

$ curl -v -o- http://hostname.local/.well-known/acme-challenge/GwuRA1lujBcuyJDn4_nkBPhfOXoVacx7TfoaAJtNXQ4
*   Trying X.Y.Z.A:80...
* Connected to hostname.local (X.Y.Z.A) port 80 (#0)
> GET /.well-known/acme-challenge/GwuRA1lujBcuyJDn4_nkBPhfOXoVacx7TfoaAJtNXQ4 HTTP/1.1
> Host: hostname.local
> User-Agent: curl/7.76.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< cache-control: no-cache, no-store, must-revalidate
< date: Thu, 10 Oct 2024 15:02:41 GMT
< content-length: 87
< content-type: text/plain; charset=utf-8
< x-envoy-upstream-service-time: 1
< server: envoy
<
* Connection #0 to host hostname.local left intact
GwuRA1lujBcuyJDn4_nkBPhfOXoVacx7TfoaAYtNXQ4.HJJ93uakKtthoKULHdbtgjlOENjr0rbor1MINt6_3zE

### Anything else?

My observation is that annotation works only on the ingress with / path

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
This seems related to the Ingress configuration as documented here: https://docs.cilium.io/en/stable/network/servicemesh/ingress/#supported-ingress-annotations (see `force-https`). Have you tried using the `ingressController.enforceHttps` helm setting?

**Comment by squeed** [comment]
@snovak7 gotcha. Just to pare this down to the simplest case, can you give some example Ingress resources that demonstrate the issue?

**Comment by snovak7** [comment]
@squeed it's really simple

On a fresh cluster with Cert Manager installed (hopefully have ingress controller setup) where Let's Encrypt can reach your ingress with default ingress controller setting enforceHttps set to true (as per default).

Now register an ingress to a simple application and http should force to https, and fail with connection reset, as there is no certificate present, of course this domain will fail with Let's Encrypt and will be in pending state.

now adding to the (Cluster)Issuer:

```yaml
ingressTemplate:
  metadata:
    annotations:
      ingress.cilium.io/force-https: disabled
```

this would build similar to example from cilium docs page with added annotation, and only /subpath prefix (without root)

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: default
  annotations:
    ingress.cilium.io/force-https: disabled
spec:
  ingressClassName: cilium
  rules:
  - http:
      paths:
      - backend:
          service:
            name: details
            port:
              number: 9080
        path: /details
        pathType: Prefix
```

you would expect that the PathPrefix would allowed to be accessed by http solver by non-secure port, but you're redirected to the https hostname ignoring the annotation.

---

Maybe if I complicate it a bit further with example of 2 ingresses that share the hostname:

1. the actual website/service, which we want to force to use only secure traffic
2. Ingress that wants to challenge cert manager with letsencrypt where we don't want to force the https for the  reason of a challenge
