### ISSUE TITLE
KubeProxyReplacement incompatible with Firewalld 1.2.1, 1.3.4

### ISSUE THREAD

**Issue by tzakrajs** [cilium/cilium#35388]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Cilium comes up cleanly and marks all nodes as Ready

With a default installation of Rocky/RHEL 9.4 (or 9.3/9.2/9.1):
UDP traffic from pods to internet and coredns Service endpoints work great via the cilium NAT rules 
ICMP traffic from pods to internet and coredns service endpoints also work great via the cilium NAT rules
TCP traffic from pods to internet, kube-apiserver Service endpoints, or coredns Service endpoints fail: unanswered SYN packet -- timeout

The moment I disable firewalld or downgrade to firewalld-1.1.1:
TCP traffic from pods to internet, kube-apiserver Service endpoints begins to work great

Why is cilium's KubeProxyReplacement interacting poorly with firewalld-1.2.1 and firewalld-1.3.4 but not firewalld-1.1.1?

Should I not be running a host firewall with cilium? Am I asking for trouble?

Thanks!

### How can we reproduce the issue?

This is reproducible with v1.15.9 and v.1.16.2 on Rocky/RHEL 9.4

```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  url: "https://github.com/cilium/charts/raw/master"
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.16.2"
      sourceRef:
        kind: HelmRepository
        name: cilium
  values:
    bpf:
      masquerade: true
    enableIPv4Masquerade: true
    enableIPv6Masquerade: false
    ipam:
      mode: kubernetes
    ipv4:
      enabled: true
    ipv6:
      enabled: false
    k8sServiceHost: 127.0.0.1 # OPTIONAL SEE BELOW**
    k8sServicePort: 8443 # OPTIONAL SEE BELOW**
    kubeProxyReplacement: true
    nativeRoutingCIDR: 172.16.0.0/12
    nodePort:
      enabled: true
    socketLB:
      enabled: true

```
**Running haproxy on each node 127.0.0.1:8443 pointing at control-plane k8s-apiserver endpoints, this is working dandy.

### Cilium Version

1.15.9 (also 1.15.7)
1.16.2

### Kernel Version

Have only reproduced on these kernels, maybe affects all 9 variants
5.14.0-162.12.1.el9_1.x86_64
5.14.0-362.8.1.el9_3.x86_64
5.14.0-427.37.1.el9_4.x86_64

Have been upgrading hoping to get past this but to no avail

### Kubernetes Version

Have seen on
1.21.12
1.29.6
1.31.1

Have been upgrading hoping to get past this but to no avail

### Regression

This used to work fine until firewalld was upgraded, everything seems to be fine until firewalld starts. I know this isn't strictly an issue with cilium, but it would be really nice if the default firewall of one of the most use operating systems was compatible with KubeProxyReplacement modes

### Sysdump

File uploading is failing here will try from another browser

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
