### ISSUE TITLE
CIDR network policy rule doesn't allow traffic from remote nodes in the cluster

### ISSUE THREAD

**Issue by lir1ka** [cilium/cilium#35401]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

I tried to secure my gatekepeer namespace. The gatekeeper manages and receives traffic only from the computer (kube is an api server). I am the one who needs an input/output network policy. the problem is that once the packets came from the master's IP address (10.1.0.11:443), once from the master's CIDR endpoint (198.18.0.1 or 198.18.0.2). 

```
Oct 15 10:53:22.292: gatekeeper-system/gatekeeper-controller-manager-8cfdfc7d4-mg266:57736 (ID:5303) <- 10.1.0.11:443 (kube-apiserver) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Oct 15 10:53:22.292: gatekeeper-system/gatekeeper-controller-manager-8cfdfc7d4-mg266:57736 (ID:5303) -> 10.1.0.11:443 (kube-apiserver) to-stack FORWARDED (TCP Flags: ACK)
Oct 15 10:53:22.338: 198.18.0.1:61504 (remote-node) <> gatekeeper-system/gatekeeper-controller-manager-8cfdfc7d4-mg266:8443 (ID:5303) policy-verdict:none INGRESS DENIED (TCP Flags: SYN)
Oct 15 10:53:22.338: 198.18.0.1:61504 (remote-node) <> gatekeeper-system/gatekeeper-controller-manager-8cfdfc7d4-mg266:8443 (ID:5303) Policy denied DROPPED (TCP Flags: SYN)
Oct 15 10:53:22.338: 198.18.0.1:61644 (remote-node) <> gatekeeper-system/gatekeeper-controller-manager-8cfdfc7d4-hxr4k:8443 (ID:5303) policy-verdict:none INGRESS DENIED (TCP Flags: SYN)
Oct 15 10:53:22.338: 198.18.0.1:61644 (remote-node) <> gatekeeper-system/gatekeeper-controller-manager-8cfdfc7d4-hxr4k:8443 (ID:5303) Policy denied DROPPED (TCP Flags: SYN)
```

this network policy does not work, but  `--enable-node-selector-labels=true` is set. 
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "test"
  namespace: gatekeeper-system
spec:
  description: "gatekeeper_rules"
  endpointSelector:
    matchLabels:
      app: gatekeeper
      release: gatekeeper
  ingress:
    - fromEntities:
      - kube-apiserver
    - fromEndpoints:
        - matchLabels:
            app: gatekeeper
            release: gatekeeper
    - fromCIDRSet:
      - cidr: 198.18.0.0/24
  egress:
    - toEntities:
      - kube-apiserver
    - toEndpoints:
        - matchLabels:
            app: gatekeeper
            release: gatekeeper
    - toCIDRSet:
      - cidr: 198.18.0.0/24
   
```
please help me, i tried to solve this about 2 months 

### How can we reproduce the issue?

1) install cilium
2) install gatekeeper
3) make cilium network policy

### Cilium Version

cilium-cli: v0.16.15 compiled with go1.22.5 on linux/amd64
cilium image (default): v1.16.0
cilium image (stable): v1.16.2

### Kernel Version

Linux vmfordeploy 5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.27.3

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Note that the identity of the source traffic is `remote-node`. That means you will need to grant ingress access to the entity `remote-node` in addition to the `kube-apiserver` entity you already have.

**Comment by lir1ka** [comment]
> Note that the identity of the source traffic is `remote-node`. That means you will need to grant ingress access to the entity `remote-node` in addition to the `kube-apiserver` entity you already have.

Sure, CIDR 198.18.0.0/24 - is endpoint CIDR of  kubernetes master node. But, i granted access from this remote node in my policy, you can see it in my policy, but nothing helps=(

**Comment by joestringer** [comment]
CIDR matches are designed primarily for matching peers outside the cluster, so by default it's not possible to use these statements to match traffic inside the cluster. There is however support for matching nodes with a CIDR policy rule, but it requires additional configuration. The documentation for that feature is [here](https://docs.cilium.io/en/stable/security/policy/language/#selecting-nodes-with-cidr-ipblock).

**Comment by ErikEngerd** [comment]
My environment:
- cilium version: 1.16.5
- k8s: 1.31.4
- nodes:  debian 12, kernel 6.1.0-16-amd64
- setup: kubeadm with api-server running in a pod 

I had a similar issue today with nginx that I have secure with network policies. I was getting the following error when applying an ingress rule:

```
Error from server (InternalError): error when creating "ingress.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "https://nginx-ingress-nginx-controller-admission.nginx.svc:443/networking/v1/ingresses?timeout=10s": context deadline exceeded
```

Also with hubble I saw the following error message
```
Dec 29 10:34:31.446: 10.220.1.15:48214 (remote-node) <> nginx/nginx-ingress-nginx-controller-v8jfd:8443 (ID:30757) policy-verdict:none INGRESS DENIED (TCP Flags: SYN)
```

My network policy already allows access from the API server
```
kind: CiliumNetworkPolicy
apiVersion: cilium.io/v2
metadata:
  name: cilium-api-server-access
  namespace: nginx
spec:
  endpointSelector:
    matchLabels: {} # all pods
  egress:
  - toEntities:
    - kube-apiserver
  - toPorts:
    - ports:
      - port: "6443"
        protocol: TCP
  ingress:
  - fromEntities:
    - kube-apiserver
  ```

After reading this issue and adding 'remote-node' to the fromEntities it started working. But why should I have to add this? And doesn't this open up access to nginx too much? I still think only the API server should require access.
