### ISSUE TITLE
CFP: Egress Gateway Additional Selectors

### ISSUE THREAD

**Issue by bck01215** [cilium/cilium#35409]
## Cilium Feature Proposal

We would like the ability to define egress gateways per node for pods matching labels. This would be beneficial as traffic could still detect the source node of the IP, but we could specify the desired egress for those pods for each node.

For example:
```yaml
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egress-node1
spec:
  selectors:
  - podSelector:
      matchLabels:
        test-gateway: "true"
  - nodeSelector: # <---- Desired feature
      matchLabels:
        kubernetes.io/hostname: node01
  destinationCIDRs:
  - "0.0.0.0/0"
  egressGateway:
    nodeSelector:
      matchLabels:
        kubernetes.io/hostname: node01
    egressIP: 10.0.1.10
```

**Comment by pchaigno** [comment]
Looks fine to me, but I think the syntax should be:
```
spec:
  selectors:
  - podSelector:
      matchLabels:
        test-gateway: "true"
    nodeSelector: # Note the lack of dash here.
      matchLabels:
        kubernetes.io/hostname: node01
```
Without the dash for `nodeSelector`, we make it clear that the `podSelector` AND the `nodeSelector` must match. With a dash, it's two separate entries and they will be interpreted separately (OR behavior). That syntax would match the network policies syntax.
