### ISSUE TITLE
policy-correlation: some network policies are not supported

### ISSUE THREAD

**Issue by huntergregory** [cilium/cilium#35416]
Using Cilium v1.17 (I don't recall the patch version), I noticed that the policy correlation feature (https://github.com/cilium/cilium/issues/26438) logs some network policies but not all.

According to my testing and the code:
https://github.com/cilium/cilium/blob/98ada1a1d3d3707fec737471ba11a7919f2c7259/pkg/policy/correlation/correlation.go#L130-L132

there is at least one policy type which is not supported:
- PolicyMatchL3L4
  ```yaml
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: l3-l4
  spec:
    podSelector:
      matchLabels:
        server: bad
    ingress:
    - from:
      - podSelector:
          matchLabels:
            server: good
      ports:
      - protocol: TCP
        port: 8080
  ```

I also observed that these were unsupported. Looking at the code, perhaps these are now supported:
- PolicyMatchL4Only
  ```yaml
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: l4-only
  spec:
    podSelector:
      matchLabels:
        server: bad
    ingress:
    - ports:
      - protocol: TCP
        port: 8080
  ```
- PolicyMatchL3Proto
  ```yaml
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: l3-proto
  spec:
    podSelector:
      matchLabels:
        server: bad
    ingress:
    - from:
      - podSelector:
          matchLabels:
            server: good
      ports:
      - protocol: TCP
  ```
