### ISSUE TITLE
cilium_unreachable_nodes metrics alert after upgrade to 1.15.9 or 1.15.10

### ISSUE THREAD

**Issue by m-sarti** [cilium/cilium#35414]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.15.7 and lower than v1.16.0

### What happened?

Upgrading from 1.14.15 to 1.15.9 or 1.15.10 the cilium_unreachable_nodes and cilium_unreachable_health_endpoints metrics report values ​​greater than zero for almost all nodes. The logs report nothing significant, there are no errors or warnings.
If you exclude this metric the cluster appears to have no problems.

### How can we reproduce the issue?

install cilium with helm:
`helm upgrade cilium cilium/cilium --version 1.15.9 --namespace=kube-system -f /tmp/values-1.15.yaml`

values as follow:
 
```
MTU: 9000
cluster:
  id: 6
  name: vin
encryption:
  enabled: true
  type: wireguard
hubble:
  enabled: false
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4MaskSize: "24"
    clusterPoolIPv4PodCIDRList: 10.6.0.0/15
k8sServiceHost: REDACTED
k8sServicePort: 8443
kubeProxyReplacement: true
l7Proxy: false
operator:
  prometheus:
    enabled: true
prometheus:
  enabled: true
socketLB:
  enabled: true
  hostNamespaceOnly: true
```

### Cilium Version

Client: 1.15.9 2ea0cf33 2024-09-20T08:44:59+00:00 go version go1.22.7 linux/amd64
Daemon: 1.15.9 2ea0cf33 2024-09-20T08:44:59+00:00 go version go1.22.7 linux/amd64

### Kernel Version

5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.10", GitCommit:"0fa26aea1d5c21516b0d96fea95a77d8d429912e", GitTreeState:"clean", BuildDate:"2024-01-17T13:38:41Z", GoVersion:"go1.20.13", Compiler:"gc", Platform:"linux/amd64"}

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
