### ISSUE TITLE
Using Gateway API as cilium-ingress's Loadbalancer is throwing 503

### ISSUE THREAD

**Issue by ferhatguneri** [cilium/cilium#35424]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

As cilium dedicated ingress ip can be used by only one ingress resource and since it is not a good solution (in every case) for fully automated microservices to be added into one ingress resource as multiple rules. So we would like to figure out the best way of using wildcard dns options for ingresses considering there are no external Loadbalancers. 

So gateway API handle wildcard hostname quite well but since Gateway API is not commonly used by all the software vendor helm charts we need to create manually gateway and http routes for applications. Which is not a good thing for an automation. We have tried a lot of combinations and we figure out when we use Gateway API as Loadbalancer of ingress controller it works just fine but when we try to add cilium ingress to backend of Gateway API, it just does not work and throw 503 error.

Gateway API as ingress-nginx's LB'. is 200 OK

Gateway API as cilium-ingress'S LB IS 503 Service Unavailable

Again, we are trying this because Gateway API itself is not global standard yet. And ingress does not solve wildcard hostname problem. So we will expect users to create their ingress resource as is but point DNS to Gateway API IP address which will act as Loadbalancer to isolate wildcard hostnames and their IP adresses.

### How can we reproduce the issue?

Try AppGW as Ingress Controller's Loadbalancer
```
apiVersion: v1
kind: Namespace
metadata:
  name: app2-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: app2-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: rancher/hello-world
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: app2-ns
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: app2
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  namespace: app2-ns
spec:
  ingressClassName: nginx
  rules:
  - host: "app2.abc.com"
    http:
      paths:
      - pathType: Prefix
        path: /hello-world
        backend:
          service:
            name: app2
            port:
              number: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: app2-gw-ns
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: app2-gw
  namespace: app2-gw-ns
spec:
  gatewayClassName: cilium
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app2-httproute
  namespace: app2-gw-ns
spec:
  hostnames:
  - "*.abc.com"
  parentRefs:
  - name: app2-gw
    namespace: app2-gw-ns
  rules:
  - backendRefs:
    - name: rke2-ingress-nginx-controller
      namespace: kube-system
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: app2-refgrant
  namespace: kube-system
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: app2-gw-ns
  to:
  - group: ""
    kind: Service
```
It Works!
```
GATEWAY_IP=$(kubectl get gateway -n app2-gw-ns app2-gw -o jsonpath='{.status.addresses[0].value}')
INGRESS_HOST=app2.abc.com
kubectl exec -n app2-ns -ti deploy/app2 -- curl --resolve $HTTPROUTE_HOST:80:$GATEWAY_IP http://$INGRESS_HOST:80/hello-world
```

Try AppGW as Cilium Ingress's Loadbalancer
```
apiVersion: v1
kind: Namespace
metadata:
  name: app3-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  namespace: app3-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3
        image: rancher/hello-world
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app3
  namespace: app3-ns
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: app3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app3
  namespace: app3-ns
spec:
  ingressClassName: cilium
  rules:
  - host: "app3.abc.com"
    http:
      paths:
      - pathType: Prefix
        path: /hello-world
        backend:
          service:
            name: app3
            port:
              number: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: app3-gw-ns
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: app3-gw
  namespace: app3-gw-ns
spec:
  gatewayClassName: cilium
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app3-httproute
  namespace: app3-gw-ns
spec:
  hostnames:
  - "*.abc.com"
  parentRefs:
  - name: app3-gw
    namespace: app3-gw-ns
  rules:
  - backendRefs:
    - name: cilium-ingress
      namespace: kube-system
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: app3-refgrant
  namespace: kube-system
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: app3-gw-ns
  to:
  - group: ""
    kind: Service
```
It Doesn't work!
```
GATEWAY_IP=$(kubectl get gateway -n app2-gw-ns app2-gw -o jsonpath='{.status.addresses[0].value}')
INGRESS_HOST=app2.abc.com
kubectl exec -n app2-ns -ti deploy/app2 -- curl --resolve $HTTPROUTE_HOST:80:$GATEWAY_IP http://$INGRESS_HOST:80/hello-world
```

### Cilium Version

1.16.1

### Kernel Version

5.14.0-427.37.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Sep 13 12:41:50 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Kubernetes RKE2 1.29.9

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
