### ISSUE TITLE
CiliumNetworkPolicy to allow Kubernetes API endpoint not working

### ISSUE THREAD

**Issue by bernardgut** [cilium/cilium#35459]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

It seems the 

```
egress:   
  - toServices:
    - k8sService:
        serviceName: kubernetes
        namespace: default
```

policy is ignored by Cilium as it is currently impossible for my services to connect to kubernetes API.

I also tried with 
```
egress:
- toEndpoints
      - matchLabels:
          io.kubernetes.pod.namespace: default
```

Nothing works.

### How can we reproduce the issue?

1. Deploy minio operator following [docs](https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/deploy-operator-helm.html) `helm install --namespace minio-operator --create-namespace operator minio-operator/operator`
2. Deploy a minio tenant following the [docs](https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/deploy-minio-tenant-helm.html) : `helm install --namespace minio-tenant --create-namespace --values values.yaml tenant minio-operator/tenant`
3. Check that everything works.
4. Create the following `egress` policy:
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "minio-tenant"
spec:
  description: "Egress: allow minio-operator,self. Ingress: Allow port-specific. Scope: Namespace."
  endpointSelector:
     matchLabels:
        io.kubernetes.pod.namespace: minio-tenant
  egress:
  - toEndpoints:
      # allow access to minio-operator
      - matchLabels:
          io.kubernetes.pod.namespace: minio-operator
  # allow access to CRDs for validation (mandatory)
  - toServices:
    - k8sService:
        serviceName: kubernetes
        namespace: default
```
5. Now check the logs of the one of the `minio-tenant` pods, specifically the init-container:
```
k logs -n minio-tenant tenant-pool-0-0 validate-arguments -f                                              
2024/10/21 18:03:27 validator.go:65: Get "https://[fd00:0:a:2000::1]:443/apis/minio.min.io/v2/namespaces/minio-tenant/tenants/tenant": dial tcp [fd00:0:a:2000::1]:443: i/o timeout
panic: Get "https://[fd00:0:a:2000::1]:443/apis/minio.min.io/v2/namespaces/minio-tenant/tenants/tenant": dial tcp [fd00:0:a:2000::1]:443: i/o timeout

goroutine 1 [running]:
github.com/minio/operator/sidecar/pkg/validator.Validate({0x7fff882b15f6, 0x6})
	github.com/minio/operator/sidecar/pkg/validator/validator.go:66 +0x6cb
main.startValidator(0xc00053b401?)
	github.com/minio/operator/sidecar/cmd/sidecar/validate.go:41 +0x2c
github.com/minio/cli.HandleAction({0x1978ea0?, 0x1e3c8b0?}, 0x8?)
	github.com/minio/cli@v1.24.2/app.go:492 +0x70
github.com/minio/cli.Command.Run({{0x1d2c0c0, 0x8}, {0x0, 0x0}, {0x2e23810, 0x1, 0x1}, {0x1d5718c, 0x25}, {0x0, ...}, ...}, ...)
	github.com/minio/cli@v1.24.2/command.go:242 +0x938
github.com/minio/cli.(*App).Run(0xc0005836c0, {0xc000138040, 0x4, 0x4})
	github.com/minio/cli@v1.24.2/app.go:260 +0xa7b
main.main()

```

Nothing works anymore. 

For reference: 
```
k get svc -n default                                                        
NAME         TYPE        CLUSTER-IP         EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   fd00:0:a:2000::1   <none>        443/TCP   42d
```

If you delete the above rule everything works again flawlessly

### Cilium Version

```
cilium -n cni status                                                          (⎈|sekops-omni-p0:default)
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    OK
 \__/¯¯\__/    Hubble Relay:       OK
    \__/       ClusterMesh:        disabled

DaemonSet              cilium-envoy       Desired: 3, Ready: 3/3, Available: 3/3
DaemonSet              cilium             Desired: 3, Ready: 3/3, Available: 3/3
Deployment             hubble-ui          Desired: 1, Ready: 1/1, Available: 1/1
Deployment             cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Deployment             hubble-relay       Desired: 1, Ready: 1/1, Available: 1/1
Containers:            cilium             Running: 3
                       hubble-ui          Running: 1
                       cilium-operator    Running: 1
                       hubble-relay       Running: 1
                       cilium-envoy       Running: 3
Cluster Pods:          74/74 managed by Cilium
Helm chart version:    
Image versions         hubble-ui          quay.io/cilium/hubble-ui-backend:v0.13.1@sha256:0e0eed917653441fded4e7cdb096b7be6a3bddded5a2dd10812a27b1fc6ed95b: 1
                       hubble-ui          quay.io/cilium/hubble-ui:v0.13.1@sha256:e2e9313eb7caf64b0061d9da0efbdad59c6c461f6ca1752768942bfeda0796c6: 1
                       cilium-operator    quay.io/cilium/operator-generic:v1.16.1@sha256:3bc7e7a43bc4a4d8989cb7936c5d96675dd2d02c306adf925ce0a7c35aa27dc4: 1
                       hubble-relay       quay.io/cilium/hubble-relay:v1.16.1@sha256:2e1b4c739a676ae187d4c2bfc45c3e865bda2567cc0320a90cb666657fcfcc35: 1
                       cilium-envoy       quay.io/cilium/cilium-envoy:v1.29.7-39a2a56bbd5b3a591f69dbca51d3e30ef97e0e51@sha256:bd5ff8c66716080028f414ec1cb4f7dc66f40d2fb5a009fff187f4a9b90b566b: 3
                       cilium             quay.io/cilium/cilium:v1.16.1@sha256:0b4a3ab41a4760d86b7fc945b8783747ba27f29dac30dd434d94f2c9e3679f39: 3
```

### Kernel Version

    kernelVersion: 6.6.54-talos

### Kubernetes Version

1.31.1

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
