### ISSUE TITLE
Cannot find socket /var/run/cilium/health.sock after upgrading to 1.16.4 and breaks cluster connectivity with hostFirewall, CNP and CCNP

### ISSUE THREAD

**Issue by sebastiangaiser** [cilium/cilium#35465]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Hey, we tried to upgrade vom 1.15.10 to 1.16.3 as suggested in https://github.com/cilium/cilium/pull/31511#issuecomment-2422033028. When doing this upgrade 

- helm upgrade to 1.16.3
- Using the later declared Helm values
- `kubectl delete pod` (just a single one) to update it
    - the upgraded agent is unreachable for other (non upgraded) nodes, but itself can see the others as healthy
    - `kubectl delete` another pod shows that now 2 are unhealthy
- from the log (when enabling debug mode) when e.g. a pod is upgraded/restarted:

```
time="2024-10-18T13:20:43Z" level=debug msg="Launching compiler" args="[-I/var/run/cilium/state/globals -I/var/run/cilium/state -I/var/lib/cilium/bpf -I/var/lib/cilium/bpf/include -g -O2 --target=bpf -std=gnu89 -nostdinc -Wall -Wextra -Werror -Wshadow
 -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -Wimplicit-int-conversion -Wenum-conversion -D__NR_CPUS__=32 -mcpu=v3 -DSECLABEL=2 -DTHIS_INTERFACE_MAC={.addr={0xa6,0x78,
0xd7,0xc2,0xd0,0x61}} -DCALLS_MAP=cilium_calls_overlay_2 -DDISABLE_LOOPBACK_LB -DNATIVE_DEV_IFINDEX=9 -DSECLABEL_IPV4=9 -DSECLABEL_IPV6=10 -c /var/lib/cilium/bpf/bpf_overlay.c -o -]" subsys=datapath-loader target=clang
time="2024-10-18T13:20:43Z" level=debug msg="Cannot find socket" error="stat /var/run/cilium/health.sock: no such file or directory" file-path=/var/run/cilium/health.sock subsys=cilium-health-launcher
time="2024-10-18T13:20:43Z" level=debug msg="Skipping probe for address" ipAddr="public-ip-placeholder" nodeName=server1-example.company.name primary=false subsys=health-server
time="2024-10-18T13:20:43Z" level=debug msg="Skipping probe for address" ipAddr=10.128.8.171 nodeName=server1-example.company.name primary=false subsys=health-server

...

time="2024-10-18T13:20:43Z" level=debug msg="Greeting successful" host="http://[private-ip-placeholder]:4240" ipAddr="private-ip-placeholder" nodeName=server1-example.company.name path="Via L3" rtt="117.66µs" subsys=health-server
time="2024-10-18T13:20:43Z" level=debug msg="Greeting host" host="http://10.128.8.15:4240" ipAddr=10.128.8.15 nodeName=server1-example.company.name path="Via L3" subsys=health-server
time="2024-10-18T13:20:43Z" level=debug msg="Greeting failed" error="Get \"http://10.128.8.15:4240/hello\": dial tcp 10.128.8.15:4240: connect: no route to host" host="http://10.128.8.15:4240" ipAddr=10.128.8.15 nodeName=server1-example.company.name path="Via L3" subsys=health-server
time="2024-10-18T13:20:43Z" level=debug msg="Failed to probe: Get \"http://10.128.8.15:4240/hello\": dial tcp 10.128.8.15:4240: connect: no route to host" ipAddr=10.128.8.15 nodeName=server1-example.company.name port=4240 subsys=health-server
time="2024-10-18T13:20:43Z" level=debug msg="Greeting host" host="http://[another-private-ip-placeholder::1992]:4240" ipAddr="another-private-ip-placeholder::1992" nodeName=server1-cloud.company.name path="Via L3" subsys=health-server
```

So it looks like the `health.sock` is never getting ready.

1. Do you have some ideas why the upgrade fails and what we could test to make it work?
2. Would it be better for the pod to crash out, if there is a “no such file” error happening? That would have saved us a lot of time, if we would have seen this error message earlier.

### How can we reproduce the issue?

1. upgrade vom 1.15.10 to 1.16.3 as suggested in https://github.com/cilium/cilium/pull/31511#issuecomment-2422033028
2. use the following Helm values:

```
MTU: 1280
envoy:
  enabled: false
bpf:
  masquerade: true
bgpControlPlane:
  enabled: true
kubeProxyReplacement: "true"
routingMode: "native"
updateStrategy:
  type: OnDelete
  rollingUpdate:
    maxUnavailable: 1
autoDirectNodeRoutes: false
bandwidthManager:
  enabled: true
hostFirewall:
  enabled: true
ipam:
  mode: "kubernetes"
ipv6:
  enabled: true
loadBalancer:
  algorithm: maglev
  mode: dsr
  dsrDispatch: geneve
tunnelProtocol: geneve
```

3. use a CCNP as host firewall

```
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: firewall
spec:
  nodeSelector: {}
  ingress:
    - fromEntities:
        - cluster
    - fromCIDRSet:
        - cidrGroupRef: vpn
      toPorts:
        - ports:
            - port: "6443"
    - fromCIDRSet:
        - cidrGroupRef: one-ccg
        - cidrGroupRef: second-ccg
      toPorts:
        - ports:
            - port: "6443"
            - port: "22"
    - fromCIDRSet:
        - cidrGroupRef: controlplane-private-ips
      toPorts:
        - ports:
            - port: "2379"
```

### Cilium Version

1.16.3

### Kernel Version

Linux server1-example.company.name 6.8.0-47-generic #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 21:40:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.31.2

### Regression

1.15.10 with a fix as suggested in https://github.com/cilium/cilium/pull/31511#issuecomment-2422033028

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
I see. You may struggle a bit to get traction on this issue since it is focusing on one specific symptom and not the overall problem that you have. By that, I mean that the debug message "cannot find socket `/var/run/cilium/health.sock`" is normal and expected. This does not indicate anything is wrong. I would suggest ignoring debug messages to begin with and go through the [troubleshooting guide](https://docs.cilium.io/en/stable/operations/troubleshooting/). You may want to start a fresh issue with the problem you observe "Cilium stays unhealthy after upgrade" and then investigate from there.

**Comment by sebastiangaiser** [comment]
@joestringer thank you for your answer. I've renamed the issue. You might be right that we focused on `one specific symptom`. The reason for this is that we couldn't find any error in the default log. After that we decided to increase the log level and found that error.

Nevertheless I ran the [tests as suggested by you](https://docs.cilium.io/en/stable/operations/troubleshooting/#cilium-connectivity-tests) and the connectivity tests are failing for cnp's:

```
  Normal   Started    3m4s (x2 over 4m9s)    kubelet            Started container pod-to-a-allowed-cnp-container
  Warning  Unhealthy  2m44s (x5 over 3m54s)  kubelet            Liveness probe failed: curl: (28) Resolving timed out after 5000 milliseconds
  Warning  Unhealthy  2m43s (x12 over 4m3s)  kubelet            Readiness probe failed: curl: (28) Resolving timed out after 5000 milliseconds
```
and 
```
  Normal   Started    42s (x2 over 107s)  kubelet            Started container pod-to-external-fqdn-allow-google-cnp-container
  Warning  Unhealthy  21s (x12 over 92s)  kubelet            Readiness probe failed: curl: (28) Resolving timed out after 5000 milliseconds
  Warning  Unhealthy  12s (x6 over 92s)   kubelet            Liveness probe failed: curl: (28) Resolving timed out after 5000 milliseconds
```

When running the same tests in our 1.15.10 cluster everything is working.

When executing `cilium-dbg status` on two nodes (one running 1.16.3, all the others 1.15.10) I can see the following:

```
# updated node 1.16.3
Hubble:                  Ok                Current/Max Flows: 4095/4095 (100.00%), Flows/s: 31.43   Metrics: Ok
Encryption:              Disabled          
Cluster health:          12/12 reachable
Modules Health:          Stopped(0) Degraded(0) OK(66)
```
```
# not updated node 1.15.10
Hubble:                          Ok                                       Current/Max Flows: 4095/4095 (100.00%), Flows/s: 77.66   Metrics: Ok
Encryption:                      Disabled                                 
Cluster health:                  11/12 reachable                          (2024-10-25T14:41:39Z)
  Name                           IP                                       Node          Endpoints
  broken-01-node.company.name   <private-v4-address>,<private-v6-address>   unreachable   reachable
Modules Health:                  Stopped(0) Degraded(0) OK(11)
```

We're using `hostFirewall.enabled: true` and the `CiliumClusterwideNetworkPolicy` as describe above. When deleting the `CiliumClusterwideNetworkPolicy` everything works of course 😄 
Does this help?

**Comment by joestringer** [comment]
Ah, so if I rephrase your report: Cilium reports that nodes are unreachable in the `cilium-dbg status` cluster connectivity health checks. Is that right?

It's not immediately obvious to me why the Cilium version change would change behavior for this. However, it may be helpful to use `hubble observe` over the course of a minute or more, on both the source node and on the destination node, to see whether Cilium is explicitly dropping any of the packets for this cilium-health component. This component uses ICMP and also TCP port 4240 (see also [this docs page on firewall rules to enable Cilium functionality](https://docs.cilium.io/en/v1.16/operations/system_requirements/#firewall-rules).

Looking at the CCNP, it seems likely to me that the policy is denying traffic for the cilium cluster connectivity health checker.

**Comment by sebastiangaiser** [comment]
Hey, I had a look for the health check port and can see the following:
```
$cilium-dbg monitor | grep 4240

# broken node 1.16.3
Policy verdict log: flow 0x6ed8e4d8 local EP ID 2218, remote ID remote-node, proto 6, ingress, action deny, auth: disabled, match none, [private-v6-ip-non-upgraded-node]:53160 -> [private-v6-ip-upgraded-node]:4240 tcp SYN
xx drop (Policy denied) flow 0x6ed8e4d8 to endpoint 0, ifindex 6, file bpf_host.c:423, , identity remote-node->unknown: [another-private-v6-ip-non-upgraded-node]:53160 -> [private-v6-ip-upgraded-node]:4240 tcp SYN

# working node 1.15.10
-> network flow 0xb58ce907 , identity health->remote-node state reply ifindex bond0.202 orig-ip 0.0.0.0: [private-v6-ip-non-upgraded-node]:4240 -> [private-v6-ip-non-upgraded-node]:53736 tcp ACK
-> endpoint 459 flow 0x84de4a27 , identity remote-node->health state established ifindex lxc_health orig-ip private-v6-ip-non-upgraded-node: [private-v6-ip-non-upgraded-node]:53736 -> [another-private-v6-ip-non-upgraded-node]:4240 tcp ACK
```

All other ports e.g. `8472` seams to not cause any drop action.
So for me it seams that `fromEntities[].cluster` is not catching the private node ips (v4 and v6) anymore. Cluster cidr's are still working? Has there something changed?

**Comment by sebastiangaiser** [comment]
@joestringer we tried to compare two nodes (upgraded/non-upgraded) and fount the following:

```
# non-upgraded node
cat /proc/2818/mounts | grep net
proc /host/proc/sys/net proc rw,nosuid,nodev,noexec,relatime 0 0
/dev/mapper/vg0-vg0--root /host/etc/cni/net.d ext4 rw,relatime,stripe=32 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs ro,relatime,size=127603300k,inode64,noswap 0 0
overlay /run/netns overlay rw,relatime,lowerdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/127/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/126/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/125/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/124/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/123/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/122/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/121/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/120/fs,upperdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1451/fs,workdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1451/work,uuid=on,nouserxattr 0 0
nsfs /run/netns/cilium-health nsfs rw 0 0


# upgraded node
cat /proc/5477/mounts | grep netns| wc -l
0
```

Do you see any scenario that the netns is not mounted?

**Comment by joestringer** [comment]
I wonder if you could compare the CiliumNode resources for upgraded node vs. non-upgraded node and see if there are any patterns in the IPs associated with the node? Are the IPs that experience the change in behaviour under the ciliumnode.spec.health field or are they under ciliumnode.spec.addresses?

**Comment by sebastiangaiser** [comment]
I'm not sure what you mean but both nodes are having the same format for `CiliumNode` :
```
spec:                                                                                                                                                                                                                                                                                                                 
  addresses:                                                                                                                                                                                                                                                                                                          
  - ip: <private-node-ipv4>                                                                                                                                                                                                                                                                                                  
    type: InternalIP                                                                                                                                                                                                                                                                                                  
  - ip: <private-node-ipv6>                                                                                                                                                                                                                                                                                      
    type: InternalIP                                                                                                                                                                                                                                                                                                  
  - ip: <public-node-ipv4>                                                                                                                                                                                                                                                                                                 
    type: ExternalIP                                                                                                                                                                                                                                                                                                  
  - ip: <public-node-ipv6>                                                                                                                                                                                                                                                                                    
    type: ExternalIP                                                                                                                                                                                                                                                                                                  
  - ip: <ipv4-from-pod-cidr-for-that-node>                                                                                                                                                                                                                                                                                                  
    type: CiliumInternalIP                                                                                                                                                                                                                                                                                            
  - ip: <ipv6-from-pod-cidr-for-that-node>                                                                                                                                                                                                                                                                                        
    type: CiliumInternalIP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  health:                                                                                                                                                                                                                                                                                                             
    ipv4: <ipv4-from-pod-cidr-for-that-node>                                                                                                                                                                                                                                                                                                 
    ipv6: <ipv6-from-pod-cidr-for-that-node>
```

**Comment by joestringer** [comment]
I'm struggling to correlate the reported values of CiliumNode in different fields with the hubble output since the IPs are obscured. Between the hubble observe cases that work vs. do not work, are they using an IP from the same section of the CiliumNode object?

**Comment by joestringer** [comment]
Good question. I'm aware that there were some changes to device detection that could impact the IP addresses associated with Nodes. Not sure exactly beyond that, but maybe a `git log -S InternalIP` could help to track down any related changes recently.

Broadly what I was thinking is that the cilium-health feature is making probes (a) from a node towards other node IPs and (b) from a node towards a Pod IP range for each other node.. so is it case (a) or case (b) that this issue is affecting? Then, linking back to your question if it's case (a) how is Cilium classifying that IP - is it an InternalIP or CiliumInternalIP when you experience the problem? Also is that different from the working case on the older release?

**Comment by sebastiangaiser** [comment]
Sorry for the long delay. I tested the same upgrade to 1.16.4 now with the same result that the updated node can't reach others.
I currently have the feeling that Node ips (internal and external/ipv4 and ipv6) are not considered as entity cluster, nor when allowed via a CCG.
After upgrading the node to 1.16.4 I also see no error messages in the container logs.
Can you please give me a hint how to proceed and debug this further?

**Comment by sebastiangaiser** [comment]
@joestringer I did another debugging session and found the following:

```
...
  updated-broken-host.company.name:
    Host connectivity to 172.20.16.29:
      ICMP to stack:   OK, RTT=510.712µs
      HTTP to agent:   Get "http://172.20.16.29:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
      Secondary connectivity to fd42:fed1:2861:1:ae16::29:
        ICMP to stack:   OK, RTT=461.03µs
        HTTP to agent:   Get "http://[fd42:fed1:2861:1:ae16::29]:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
    Endpoint connectivity to 10.128.2.175:
      ICMP to stack:   OK, RTT=493.74µs
      HTTP to agent:   OK, RTT=414.854µs
...
```

When digging in `cilium-dbg monitor` I found the following:
```
Policy verdict log: flow 0x94e0f0e5 local EP ID 3223, remote ID remote-node, proto 6, ingress, action deny, auth: disabled, match none, 172.20.17.56:52524 -> 172.20.16.29:4240 tcp SYN
xx drop (Policy denied) flow 0x94e0f0e5 to endpoint 0, ifindex 6, file bpf_host.c:890, , identity remote-node->unknown: 172.20.17.56:52524 -> 172.20.16.29:4240 tcp SYN
```

When now having a look for the endpoint `cilium-dbg endpoint get 3223`:
```
Error: Failed to decode nested JSON: invalid character 'M' looking for beginning of object key string (
{MatchLabels:map[string]string{cidr.<public-ip-from-ccg>/32: ,},MatchExpressions:[]LabelSelectorRequirement{},}
)
FATA[0000] execing command in container: command terminated with exit code 1
```

So for me this now seams so that parsing CCGs is not working properly.
When I replace the IPs in the CCNP with normal cidr in `fromCIDR` the node gets healthy.

In addition https://github.com/cilium/cilium/issues/29247 could be related.

**Comment by joestringer** [comment]
> When I replace the IPs in the CCNP with normal cidr in fromCIDR the node gets healthy.

That's an interesting development and implies there may be some regression in CCG, thanks for sharing! It's good that there is a mitigation by using `fromCIDR`, but obviously if CCG is not working then we should also fix that.

Scanning through the issue above I don't see any examples of the CCGs so it's hard to understand exactly how they are being used, but then at the same time given the output you see in `cilium-dbg endpoint get ...` it suggests that the basic parsing of CCGs is actually working, because otherwise I would not expect to see any content from CCGs show up in the `cilium-dbg endpoint get ...` output. You could probably also check `cilium-dbg policy selectors` to confirm that the CCG IPs show up there. Given the data you've shared already, I expect it'll show up there. Another comparison point would be to use `cilium-dbg identity list` and `cilium-dbg ip list` and search to see whether there are entries in these two areas for the same IP from the CCG which you experience problems with. 

The other thing I am not fully understanding yet is that in the hubble output you shared, the "Policy denied" results are reporting that the traffic is coming from `remote-node`. In order to enable this traffic, you would need to either (a) add a network policy that allows traffic with the entity `remote-node`, or (b) Use the `policy-cidr-match-mode=nodes` configuration option per [this part of the docs](https://docs.cilium.io/en/stable/security/policy/language/#selecting-nodes-with-cidr-ipblock). Are you using that feature?

I think the next step is to narrow down to a reproducible example where there is a netpol + CCG on Cilium v1.15.x that then no longer works after upgrade to v1.16.y.

**Comment by sebastiangaiser** [comment]
@joestringer thank you for your reply.

Here's an example with anonymised IPs:
```
apiVersion: cilium.io/v2alpha1
kind: CiliumCIDRGroup
metadata:
  name: my-ccg
spec:
  externalCIDRs:
  - 123.456.789.12/32
  - 123.456.789.13/32
  - 123.456.789.14/32
  - 1a:1b:1c:a::/64
  - 1a:1b:1c:b::/64
  - 1a:1b:1c:c::/64
```

E.g. `controlplane-private-ips` contains the private `/32` ipv4 addresses and private `/128` ipv6 addresses of all control plane nodes.

We have `policy-cidr-match-mode: ""` so I'm going to test the `nodes` setting.
