### ISSUE TITLE
probably MTU issue in an IPV6-only environment using BGP to announce externalIPs

### ISSUE THREAD

**Issue by j0ju** [cilium/cilium#35489]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

I am currently struggling with Cilium 1.16.2/k3s 1.30.5 in an IPv6 only environment. From the observations it looks like a MTU issue.

I was advised in the slack channel #kubernetes open an issue (https://cilium.slack.com/archives/C53TG4J4R/p1729629825447759)
Data dumps and config files are in the text field to reproduce the issue.

Node and CNI Networking generally works.
So node to internet, node to node, pod to internet, pod to svc, pod to pod works.
I have setuped route reflector (using eBGP different ASNs).

I like to annouce externalIPs via BGP. I deployed a SVC which I patched to have the external IP fd64::1. Announcement and traffic routing works as expected. All MTUs on path are 1500.

unfortunatly accessing the service e.g. with curl does not work if the content is "larger".
the tcp connection just stalls.

If I manually apply
`mtu 1492` to the route announced like:
```
fd64::1 via fe80::XXXX dev eth0 mtu 1492
```
it just works.
Connecting to the services on the node IPs itself does work, too.
Using kubectl/k9s port forwarding it works also.

You can see the packet sizes in a tcpdump: 
In a perfect world packet sizes would start low and increase to 1500, during the transfer of the tcp connection. 

In the broken case: 1500 is never reached, no packets emitted from the cilium node on the external interface (eth0) of the node anymore. 
(`-i any` does not show packets on other interfaces, too)
If I set MTU 1492 you see the packet size increase  to 1492.

Additionally I tried to patch the cilium-agent DaemonSet to force MTU 1492 with no success:
```
  ...
  containers:
  - name: cilium-agent
    args:
    - --config-dir=/tmp/cilium/config-map
    - --mtu=1492
    command:
    - cilium-agent
  ...
```

So I assume from the observations a wrong MTU is selected.
Where can I look to narrow this further down and get it working?

### How can we reproduce the issue?

Not a straight reproducer:

Each node of the cluster has only on interface with MTU 1500, only with one ULA and LL address on it.
The cluster has been bootstrapped with:
```
bgp:
  enabled: false
bgpControlPlane:
  enabled: true
bpf:
  hostLegacyRouting: false
  lbExternalClusterIP: true
  masquerade: false
debug:
  enabled: false
enableIPv4BIGTCP: false
enableIPv4Masquerade: false
enableIPv6BIGTCP: true
enableIPv6Masquerade: false
externalIPs:
  enabled: true
extraConfig:
  enable-ipv6-ndp: 'true'
  ipv6-mcast-device: eth0
  ipv6-service-range: fd64:6443:0:1:5::/112
hostPort:
  enabled: false
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv6MaskSize: 112
    clusterPoolIPv6PodCIDRList: fd64:6443:0:1:c::/96
ipv4:
  enabled: false
ipv6:
  enabled: true
k8sServiceHost: fd23::314:1
k8sServicePort: 6443
kubeProxyReplacement: true
nodePort:
  enabled: false
operator:
  replicas: 1
routingMode: native
```

These are the cilium resources for creating peerings per node:
```
kind: CiliumBGPClusterConfig
metadata:
  name: "bgp-rr"
spec:
  # TODO:
  #  * kubectl label nodes tpn1 cilium.bgp=true
  #  * kubectl annotate node tpn1 --overwrite cilium.io/bgp-virtual-router.65179="router-id=242.64.43.1"
  #  * kubectl annotate node tpn2 --overwrite cilium.io/bgp-virtual-router.65179="router-id=242.64.43.2"
 # ...

  nodeSelector:
    matchLabels:
      cilium.bgp-speaker: "True"
  bgpInstances:
  - name: "rr"
    localASN: 65179
    peers:
    - name: "rr"
      peerASN: 64179
      #peerAddress: fd23::314:bc
      peerAddress: fe80::bc%eth0
      peerConfigRef:
        name: "rr"


---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: "rr"
spec:
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
  - afi: ipv6
    safi: unicast
    advertisements:
      matchLabels:
        advertise: "cilium.bgp-speaker"


---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: "bgp-advertisements"
  labels:
    advertise: "cilium.bgp-speaker"
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - ExternalIP
      selector:
        matchExpressions: # []
          - { key: "bgp-advertise", operator: "In", values: [ "True" ] }
```

Patch/snippet: for a service to assign fd64::1 to an service.
```
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  labels:
    bgp-advertise: "True"
spec:
  externalIPs:
  - fd64::1
```

### Cilium Version

root@tpn1 | /opt/cilium > cilium version -n cilium
cilium-cli: v0.16.18 compiled with go1.23.1 on linux/arm64
cilium image (default): v1.16.1
cilium image (stable): v1.16.3
cilium image (running): 1.16.2

### Kernel Version

Linux tpn1 6.1.0-1025-rockchip #25-Ubuntu SMP Mon Aug 26 23:01:14 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
...
Linux tpn4 6.1.0-1025-rockchip #25-Ubuntu SMP Mon Aug 26 23:01:14 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

Client Version: v1.30.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.5+k3s1

### Sysdump

[cilium-sysdump-20241022-212806.zip](https://github.com/user-attachments/files/17482281/cilium-sysdump-20241022-212806.zip)

### Anything else?

```
root@tpn1 | ~ > sh -x dump.sh
+ ip -4 r
+ ip -6 r
fd23::314:1 dev eth0 proto kernel metric 256 pref medium
fd23::314:bc via fe80::bc dev eth0 proto bird metric 1000 pref medium
fd64:6443:0:1:5::/112 dev cilium_host proto kernel src fd64:6443:0:1:c::ad48 metric 1024 pref medium
fd64:6443:0:1:c::ad48 dev cilium_host proto kernel metric 256 pref medium
fd64:6443:0:1:c::/112 dev cilium_host proto kernel src fd64:6443:0:1:c::ad48 metric 1024 pref medium
fe80::/64 dev eth0 proto kernel metric 256 pref medium
fe80::/64 dev cilium_net proto kernel metric 256 pref medium
fe80::/64 dev lxc34559fde8ef7 proto kernel metric 256 pref medium
[...]
fe80::/64 dev lxceec71c409035 proto kernel metric 256 pref medium
default via fe80::1 dev eth0 proto bird metric 1000 pref medium
+ ip -br a
lo               UNKNOWN        127.0.0.1/8 ::1/128 
eth0             UP             fd23::314:1/128 fe80::314:1/64 
cilium_net@cilium_host UP             fe80::7c38:5eff:fe2f:834e/64 
cilium_host@cilium_net UP             fd64:6443:0:1:c::ad48/128 
lxc34559fde8ef7@if145 UP             fe80::ac3b:fcff:fe67:d296/64 
[...]
lxcc5fc88abcd30@if207 UP             fe80::88e4:acff:fe17:4d16/64 
lxc_health@if211 UP             fe80::942e:ebff:fe9a:85c/64 
+ cilium -n cilium bgp peers
Node   Local AS   Peer AS   Peer Address    Session State   Uptime    Family         Received   Advertised
tpn1   65179      64179     fe80::bc%eth0   established     2h1m23s   ipv6/unicast   2          2    
+ cilium -n cilium bgp routes available ipv6 unicast
Node   VRouter   Prefix        NextHop   Age       Attrs
tpn1   65179     fd64::1/128   ::        2h1m32s   [{Origin: i} {MpReach(ipv6-unicast): {Nexthop: ::, NLRIs: [fd64::1/128]}}]  
```

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
