### ISSUE TITLE
CFP: egressDeny to toFQDNSs

### ISSUE THREAD

**Issue by jasonumiker** [cilium/cilium#35494]
In some of our clusters it will be difficult to get to a default deny for egress traffic. What we were hoping to do instead is something like this:
```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: deny-except-app-test
spec:
  description: 'Block all traffic to this Memcache (except from app:test Pods)'
  egressDeny:
    - toFQDNs:
        - matchName: serverless-memcached-01.amazonaws.com
  endpointSelector:
    matchExpressions:
      - key: app
        operator: NotIn
        values:
          - test
```
Whereby you'd add the Cluster SG to the ElastiCache and then put this policy in to restrict access to everything that isn't what the thing that should have it with a NotIn endpointSelector.

This would be a good replacement for needing to implement AWS SecurityGroups for Pods for us.
