### ISSUE TITLE
Ingress slow via l2announcement VLAN Hetzner vSwitch

### ISSUE THREAD

**Issue by jlxq0** [cilium/cilium#35510]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Probably not a bug but me doing sth. wrong:

Regular ingress (e.g. via ingress-nginx) has ~10x less bandwidth than kubectl port-forward when using l2announcements in my VLAN.

### How can we reproduce the issue?

1. Hardware / network:
    - 3 dedicated (as in bare metal) servers. (They are with Hetzner.)
    - Each server has 1 GE NIC and 1 public IP address.
    - A "vSwitch" with an additional public /29 network.
2. Server setup:
    - Basically an out of the box Ubuntu 24.04 base install with a user added and swapoff and loading kernel modules. ([Ansible playbook](https://gist.github.com/jlxq0/ef5993ef11e54b13a98ea9e5556e4a58).)
3. Network setup Netplan of node 1. Nodes 2 and 3 are the same except for the main and private IP address and gateway:
```yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    eno1:
      mtu: 1400
      addresses:
        - 148.251.67.222/32 # This is the main (public) IP address of the node
      routes:
        - on-link: true
          to: 0.0.0.0/0
          via: 148.251.67.193 # This is the gateway
      nameservers:
        addresses:
          - 185.12.64.1
          - 185.12.64.2
  vlans:
    k3svlan01:
      id: 4002
      link: eno1
      mtu: 1400
      addresses:
        - 10.1.0.101/16 # This is the private IP address of the node
      routes:
        - to: 0.0.0.0/0
          via: 49.13.104.145 # This is the gateway of the VLAN (the one ordered extra for the vSwitch)
          table: 1
          on-link: true
      routing-policy:
        - from: 49.13.104.144/29 # This is the extra public subnet ordered for the vSwitch
          to: 10.42.0.0/16 # k3s --cluster-cidr
          table: 254
          priority: 0
        - from: 49.13.104.144/29
          to: 10.43.0.0/16 # k3s --service-cidr
          table: 254
          priority: 0
        - from: 49.13.104.144/29
          table: 1
          priority: 10
        - to: 49.13.104.144/29
          table: 1
          priority: 10
```

4. `/etc/hosts` for all:

```
127.0.0.1 localhost.localdomain localhost
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

10.1.0.101 k3s02node01.example.com k3s02node01
10.1.0.102 k3s02node02.example.com k3s02node02
10.1.0.103 k3s02node03.example.com k3s02node03
```

5. k3s installation:
```bash
sudo curl -sfL https://get.k3s.io | sh -s - server \
    --cluster-init \
    --write-kubeconfig-mode=644 \
    --tls-san=k3s02node01,k3s02node02,k3s02node03,k3s02node01.example.com,k3s02node02.example.com,k3s02node03.example.com,148.251.67.222,116.202.165.247,78.46.92.248 \
    --flannel-backend=none \
    --disable-network-policy \
    --disable=traefik \
    --disable-kube-proxy \
    --disable=servicelb \
    --node-ip=10.1.0.101
```

6. Join the other two:
```bash
sudo curl -sfL https://get.k3s.io | K3S_TOKEN=XXX sh -s - server \
    --server https://k3s02node01:6443 \
    --write-kubeconfig-mode=644 \
    --tls-san=k3s02node01,k3s02node02,k3s02node03,k3s02node01.example.com,k3s02node02.example.com,k3s02node03.example.com,148.251.67.222,116.202.165.247,78.46.92.248 \
    --flannel-backend=none \
    --disable-network-policy \
    --disable=traefik \
    --disable-kube-proxy \
    --disable=servicelb \
    --node-ip=10.1.0.102
```

7. Install Ciliium

```bash
helm install -n kube-system cilium cilium/cilium -f cilium.yaml
```

```yaml
#cilium.yaml
k8sServiceHost: localhost
k8sServicePort: 6443
kubeProxyReplacement: true

ipv4:
  enabled: true
ipv6:
  enabled: false

hubble:
  relay:
    enabled: true
  ui:
    enabled: true
ipam:
  mode: kubernetes

devices: k3svlan01
routingMode: native
ipv4NativeRoutingCIDR: 10.1.0.0/16
enableIPv4Masquerade: true
autoDirectNodeRoutes: true

l2announcements:
  enabled: true
  leaseDuration: 30s
  leaseRenewDeadline: 5s
  leaseRetryPeriod: 2m

```

8. Install ingress-nginx

```bash
helm install ingress-nginx ingress-nginx/ingress-nginx -n ingress-nginx --create-namespace
```

9. Add pool of addresses:

```
kubectl apply -f pool.yaml
```

```yaml
#pool.yaml
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "pool"
spec:
  blocks:
    - start: "49.13.104.146"
      stop: "49.13.104.150"
```

10. Add l2 policy:
```
kubectl apply -f l2-policy.yaml
```

```yaml
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2announcement-policy
spec:
  externalIPs: true
  loadBalancerIPs: true
```

11. Deploy any speedtest or other workload, expose a) via ingress and b) via portforward. Ingress will be painfully slow.

### Cilium Version

cilium-cli: v0.16.19 compiled with go1.23.2 on darwin/arm64
cilium image (default): v1.16.2
cilium image (stable): v1.16.3
cilium image (running): 1.16.3

### Kernel Version

Linux k3s02node01.example.com 6.8.0-47-generic #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 21:40:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.30.5+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.5+k3s1

### Regression

-

### Sysdump

[cilium-sysdump-20241023-175818.zip](https://github.com/user-attachments/files/17488925/cilium-sysdump-20241023-175818.zip)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
