### ISSUE TITLE
CFP: Clarify the intent for policies with default deny specified with no rules

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#35558]
## Problem

As of Cilium v1.16, in order to apply a default deny policy, a CNP or CCNP must have at least one rule in an `egress`, `egressDeny`, `ingress` or `ingressDeny` stanza.

Furthermore, in Cilium v1.16 there is a new `enableDefaultDeny` field which seems like it should be able to be used to enforce a default deny posture without listing any rules in one of the rule allow/deny fields. If this field is specified and describes that default deny should be enabled, but there are no rules, then the network policy does not enforce a default deny.

## Proposal A

This CFP proposes that the following network policy should enable a default deny posture even though it does not contain an `egress`, `egressDeny`, `ingress` or `ingressDeny` field.

```
apiVersion: cilium.io/v2                                                                                                                                                             
kind: CiliumClusterwideNetworkPolicy                                                                                                                                                 
metadata:                                                                                                                                                                            
  name: default-deny                                                                                                                                                                 
spec:                                                                                                                                                                                
  endpointSelector:                                                                                                                                                                  
    matchExpressions:                                                                                                                                                                
      - key: "io.kubernetes.pod.namespace"                                                                                                                                           
        operator: "NotIn"                                                                                                                                                            
        values:                                                                                                                                                                      
        - "kube-system"                                                                                                                                                              
  enableDefaultDeny:                                                                                                                                                                 
    egress: true                                                                                                                                                                     
    ingress: true
```

EDIT: Note that there are counter-proposals for different behavior in the discussion below.

**Comment by joestringer** [comment]
I believe that currently this is considered to be an invalid policy as it is not fully formed (does not contain an `egress`, `egressDeny`, `ingress` or `ingressDeny` field). Though I will also note that the cilium operator's network policy validator does not explicitly identify the network policy above as invalid, it just does not have any effect.

**Comment by squeed** [comment]
My instinct would be to reject empty policies at the apiserver. There should probably be a OneOf directive for Egress / EgressDeny / Ingress / IngressDeny stanzas.

One of the trickier things to understand in the Kubernetes style of network policy is the effect of empty fields. Does it select everything or nothing? Will setting this field change some sort of hidden local variable?

So, I'm generally in favor of preventing "should be a no-op" entry, much how Linux usually rejects unknown flags rather than ignoring them.

**Comment by joestringer** [comment]
That's certainly also an option. Personally when I read the YAML snippet posted in the issue description, the intent seems crystal clear to me.. though admittedly it could bring up some other semantic questions that are less obvious.

For instance, if we allowed there to be no ingress/egress stanzas, would that mean that the following also valid CNP? What does it mean?

```
apiVersion: cilium.io/v2                                                                                                                                                             
kind: CiliumClusterwideNetworkPolicy                                                                                                                                                 
metadata:                                                                                                                                                                            
  name: default-deny                                                                                                                                                                 
spec:                                                                                                                                                                                
  endpointSelector:                                                                                                                                                                  
    matchExpressions:                                                                                                                                                                
      - key: "io.kubernetes.pod.namespace"                                                                                                                                           
        operator: "NotIn"                                                                                                                                                            
        values:                                                                                                                                                                      
        - "kube-system"                                                                                                                                                              
  enableDefaultDeny: {}
```

I would interpret this one to be a complete no-op, and therefore I think it'd be helpful to reject this policy. Maybe that's speaking a bit to your instinct @squeed about requiring one of the Egress / EgressDeny / Ingress / IngressDeny stanzas.

**Comment by renyunkang** [comment]
If the `enableDefaultDeny` field in a Cilium Network Policy (CNP) is set to `{}` (an empty object), two solutions are possible: 

1) Strict validation with status updates
Treat an empty enableDefaultDeny as an invalid configuration. Reject the policy application, update the CNP status to reflect the validation failure, and provide a clear error message indicating the missing ingress and egress settings. 

2) Defaulting to ingress: false, egress: false. 
This means that default-deny behavior is disabled for both ingress and egress traffic. The policy would be applied without error, providing a smoother user experience. 

While both are viable, I personally favor Option 2, defaulting to disabling default-deny for both ingress and egress.

**Comment by joestringer** [comment]
@renyunkang are you considering the state of the `enableDefaultDeny: {}` field with or without rule statements like `ingress`, `egress`, etc?

For existing policies written without the `enableDefaultDeny` field, the behavior must not change. This is equivalent to installing the resource without the `enableDefaultDeny` field, and then if you retrieve the resource with the new schema, it translates the field to the empty value, `enableDefaultDeny: {}`. Since the existing policies would enable a default deny when there is at least one rule in an `ingress`, `egress`, etc stanza, this means that the `enableDefaultDeny: {}` field must not disable default deny for each direction. In order to disable default deny, you must explicitly set `enableDefaultDeny: ingress: false` (and/or equivalent egress statement).

As a general constraint of the system, if some configuration has no effect, then I think it can improve user experience for the resource to be rejected. For example the [resource described here](https://github.com/cilium/cilium/issues/35558#issuecomment-2445030199). This helps to communicate when the user has created a configuration that does not do what they intend to do.

**Comment by joestringer** [comment]
To align with @squeed's statements above, I think it would be simpler to just require a rule to be specified. Effectively that means there would be a small change from your post above @renyunkang : 

If the daemon has EnableNonDefaultDenyPolicies set to true:
-  One of the following must be configured: Ingress, IngressDeny, Egress, EgressDeny, ~EnableDefaultDeny.Ingress, or EnableDefaultDeny.Egress~. 

One of the benefits is that for this simpler expression it should be easier to embed this in the CRD validation so that the kube-apiserver enforces it, rather than having the cilium-agent enforce it after the resource is already configured. Better UX.

**Comment by renyunkang** [comment]
> To align with [@squeed](https://github.com/squeed)'s statements above, I think it would be simpler to just require a rule to be specified. Effectively that means there would be a small change from your post above [@renyunkang](https://github.com/renyunkang) :
> 
> If the daemon has EnableNonDefaultDenyPolicies set to true:
> 
> * One of the following must be configured: Ingress, IngressDeny, Egress, EgressDeny, ~EnableDefaultDeny.Ingress, or EnableDefaultDeny.Egress~.
> 
> One of the benefits is that for this simpler expression it should be easier to embed this in the CRD validation so that the kube-apiserver enforces it, rather than having the cilium-agent enforce it after the resource is already configured. Better UX.

The current description completely contradicts the CFP title. Is this modification consistent with the CFP proposal? Or should we revise the CFP proposal title?

**Comment by renyunkang** [comment]
With the following rule configured, what happens to ingress traffic?

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny
spec:
  endpointSelector:
    matchExpressions:
      - key: "io.kubernetes.pod.namespace"
        operator: "NotIn"
        values:
        - "kube-system"
  egress:
  - toFQDNs:
    - matchName: "api.github.com"
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        "k8s:k8s-app": kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"
  enableDefaultDeny:
    egress: true
    ingress: true
```

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny
spec:
  endpointSelector:
    matchExpressions:
      - key: "io.kubernetes.pod.namespace"
        operator: "NotIn"
        values:
        - "kube-system"
  egress:
  - toFQDNs:
    - matchName: "api.github.com"
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        "k8s:k8s-app": kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"
  enableDefaultDeny:
    egress: true
    ingress: false
```
Will setting `enableDefaultDeny.ingress` to `true` or `false` allow all ingress traffic in either case? @joestringer  @squeed

**Comment by joestringer** [comment]
> The current description completely contradicts the CFP title. Is this modification consistent with the CFP proposal? Or should we revise the CFP proposal title?

Sorry, I agree it contradicts the CFP title. I created the proposal to try to gather feedback but I don't hold a strong opinion that my original description of the solution is the right way. Probably if I were to rewrite the issue, I would reframe it to first describe:
- The problem: it's confusing that `enableDefaultDeny.egress`/`enableDefaultDeny.ingress` by itself has no effect
- A solution: my initial proposal was to change the semantics so that it takes effect.
- A different solution: @squeed's counter-proposal was that we just declare such policies to be invalid.

Your questions are super helpful to help us reason about what we think the right solution to the problem is. I think that the logical conclusion of Casey's proposal would be that the network policies you proposed in [your latest post](https://github.com/cilium/cilium/issues/35558#issuecomment-2503006466) should both be rejected, because they configure the `ingress` default deny posture but they do not contain any ingress rules.

**Comment by renyunkang** [comment]
Okay, based on your description, let's elaborate with an example: @joestringer  @squeed 

### **The problem:**

Before v1.16.0, the following rule allowed all ingress traffic:

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny
spec:
  endpointSelector:
    matchExpressions:
    - key: "io.kubernetes.pod.namespace"
      operator: "NotIn"
      values:
      - "kube-system"
  egress:
  - toFQDNs:
    - matchName: "api.github.com"
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        "k8s:k8s-app": kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"
```
After v1.16.0 introduced `enableDefaultDeny`, the above configuration, regardless of whether `enableDefaultDeny.ingress` is true or false, still allows all ingress traffic. This is confusing for users because the configuration has no effect.


### **Proposed Solutions:**

Solution 1: Change the semantics of enableDefaultDeny so that it takes effect as intended.
Solution 2: Declare the policy invalid.

### **My Understanding:**

Solution 1 is easy to understand.
How should Solution 2 be interpreted? Detecting invalid policies works well for policies like this:

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny
spec:
  endpointSelector:
    matchExpressions:
    - key: "io.kubernetes.pod.namespace"
      operator: "NotIn"
      values:
      - "kube-system"
  enableDefaultDeny:
    egress: true
    ingress: true
```
However, Solution 2 might not be suitable for the first example. Should we still use Solution 2 for the first example? Since there's no `ingress` or `ingressDeny` section, `enableDefaultDeny.ingress` cannot be configured, right?

> Your questions are super helpful to help us reason about what we think the right solution to the problem is. I think that the logical conclusion of Casey's proposal would be that the network policies you proposed in https://github.com/cilium/cilium/issues/35558#issuecomment-2503006466 should both be rejected, because they configure the ingress default deny posture but they do not contain any ingress rules.
>
> For existing policies written without the enableDefaultDeny field, the behavior must not change. 

Furthermore, if setting `enableDefaultDeny.ingress` to either `true` or `false` results in the rejection of all ingress traffic, will the behavior change for policies without the `enableDefaultDeny` field after users upgrade from v1.15.x or lower versions?
