### ISSUE TITLE
[Bug] Gateway API - Envoy not receiving replies - Connection timeout

### ISSUE THREAD

**Issue by modzilla99** [cilium/cilium#35559]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

I am running Cilium v1.16.3 on Talos Linux and wanted to use the Gateway API, but unfortunately it does not work. I can see correctly generated envoy configs and endoints configuration, but the client always gets a connection timeout.

```log
upstream connect error or disconnect/reset before headers. reset reason: connection timeout
```

When I do a tcpdump within the nginx container that is behind the httproute/service I can see that incoming traffic is correctly being forwarded to the container. It tries to send the ack back but never gets the answer.

### How can we reproduce the issue?

1. Deploy Talos Linux in version v1.18.1 and cilium on top with the following values:
```yaml
k8sServiceHost: localhost
k8sServicePort: 7445
debug:
  verbose: ""

cgroup:
  hostRoot: /sys/fs/cgroup
  autoMount:
    enabled: false

gatewayAPI:
  enabled: true
  externalTrafficPolicy: Local

envoy:
  enabled: true
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - PERFMON
      - BPF

loadBalancer:
  #acceleration: best-effort
  l7:
    backend: envoy

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

routingMode: native
autoDirectNodeRoutes: true
ipv4NativeRoutingCIDR: 172.16.0.0/16
kubeProxyReplacement: true

bpf:
  masquerade: true
ipMasqAgent:
  enabled: true
maglev:
  tableSize: 1021
  hashSeed: t2hrEio4Xm0RN6sO
endpointRoutes:
  enabled: true
nodeIPAM:
  enabled: true
ipam:
  mode: multi-pool
  operator:
    autoCreateCiliumPodIPPools:
      default:
        ipv4:
          cidrs:
          - 10.244.0.0/16
          maskSize: 27

securityContext:
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
```

2. Create the Gateway:
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: kube-system
spec:
  infrastructure:
    annotations: {}
  gatewayClassName: cilium
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
```
3. Create any deployment + service and expose it with an httproute
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx
  namespace: default
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cilium-gateway
    namespace: kube-system
  rules:
  - backendRefs:
    - kind: Service
      name: nginx
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
```

### Cilium Version

Tried multiple version almost all v1.16 and I belive, though not entirely sure, v1.15.3

### Kernel Version

6.6.54-talos

### Kubernetes Version

Happened on v1.30.3 and also v1.31.1

### Sysdump

[cilium-sysdump-20241025-230127.zip](https://github.com/user-attachments/files/17527575/cilium-sysdump-20241025-230127.zip)

### Relevant log output

tcpdump in container:

```log
/ # tcpdump -vnni eth0
tcpdump: listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
20:41:33.545783 IP (tos 0x0, ttl 64, id 21152, offset 0, flags [DF], proto TCP (6), length 60)
    10.244.0.4.42789 > 10.244.0.15.80: Flags [S], cksum 0x1629 (incorrect -> 0x4edc), seq 1697114994, win 62720, options [mss 8960,sackOK,TS val 4215463305 ecr 0,nop,wscale 7], length 0
20:41:33.545803 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    10.244.0.15.80 > 10.244.0.4.42789: Flags [S.], cksum 0x1629 (incorrect -> 0x7c5b), seq 3739839007, ack 1697114995, win 62636, options [mss 8960,sackOK,TS val 3831932243 ecr 4215463305,nop,wscale 7], length 0
20:41:34.552855 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    10.244.0.15.80 > 10.244.0.4.42789: Flags [S.], cksum 0x1629 (incorrect -> 0x786c), seq 3739839007, ack 1697114995, win 62636, options [mss 8960,sackOK,TS val 3831933250 ecr 4215463305,nop,wscale 7], length 0
20:41:34.552867 IP (tos 0x0, ttl 64, id 21153, offset 0, flags [DF], proto TCP (6), length 60)
    10.244.0.4.42789 > 10.244.0.15.80: Flags [S], cksum 0x1629 (incorrect -> 0x4aec), seq 1697114994, win 62720, options [mss 8960,sackOK,TS val 4215464313 ecr 0,nop,wscale 7], length 0
20:41:34.552877 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    10.244.0.15.80 > 10.244.0.4.42789: Flags [S.], cksum 0x1629 (incorrect -> 0x786c), seq 3739839007, ack 1697114995, win 62636, options [mss 8960,sackOK,TS val 3831933250 ecr 4215463305,nop,wscale 7], length 0
/ # ip nei
172.16.0.175 dev eth0 lladdr c6:2f:f5:57:25:0e used 0/0/0 probes 0 STALE
10.244.0.24 dev eth0 lladdr c6:2f:f5:57:25:0e ref 1 used 0/0/0 probes 1 REACHABLE
/ # ping 10.244.0.4
PING 10.244.0.4 (10.244.0.4): 56 data bytes
^C
--- 10.244.0.4 ping statistics ---
5 packets transmitted, 0 packets received, 100% packet loss
/ # # No neighbor entry populated? eBPF magic?
/ # ip nei
172.16.0.175 dev eth0 lladdr c6:2f:f5:57:25:0e used 0/0/0 probes 0 STALE
10.244.0.24 dev eth0 lladdr c6:2f:f5:57:25:0e ref 1 used 0/0/0 probes 1 DELAY
```

Hubble:
```
~ : hubble observe -f | grep ":80 "
Oct 25 21:05:59.074: 10.244.0.4:44281 (ingress) -> default/test-77bf9966d9-8ngzc:80 (ID:3730) to-endpoint FORWARDED (TCP Flags: SYN)
Oct 25 21:05:59.074: 10.244.0.4:44281 (ingress) <- default/test-77bf9966d9-8ngzc:80 (ID:3730) to-network FORWARDED (TCP Flags: SYN, ACK)
Oct 25 21:06:04.075: 172.16.0.175:39360 (ingress) -> 172.16.0.175:80 (world) http-request FORWARDED (HTTP/1.1 GET http://172.16.0.175/)
Oct 25 21:06:04.075: 172.16.0.175:39360 (ingress) <- 172.16.0.175:80 (world) http-response FORWARDED (HTTP/1.1 503 5001ms (GET http://172.16.0.175/))
Oct 25 21:06:05.176: 10.244.0.4:44281 (ingress) <- default/test-77bf9966d9-8ngzc:80 (ID:3730) to-network FORWARDED (TCP Flags: SYN, ACK)
```

Envoy:

```log
[2024-10-25 21:10:28.263][14][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:145] creating a new connection (connecting=0)
[2024-10-25 21:10:28.263][14][debug][connection] [external/envoy/source/common/network/connection_impl.h:98] [Tags: "ConnectionId":"8"] current connecting state: true
[2024-10-25 21:10:28.263][14][debug][client] [external/envoy/source/common/http/codec_client.cc:57] [Tags: "ConnectionId":"8"] connecting
[2024-10-25 21:10:28.263][14][debug][connection] [external/envoy/source/common/network/connection_impl.cc:1009] [Tags: "ConnectionId":"8"] connecting to 10.244.0.15:80
[2024-10-25 21:10:28.263][14][debug][connection] [external/envoy/source/common/network/connection_impl.cc:1028] [Tags: "ConnectionId":"8"] connection in progress
[2024-10-25 21:10:28.263][14][debug][filter] [cilium/l7policy.cc:129] cilium.l7policy: PAUSING until upstream connection has been established
```

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by modzilla99** [comment]
Any ideas?

**Comment by Jip-Hop** [comment]
I just tried with k0s:v1.31.2+k0s, gateway-api v1.2.0 and upcoming cilium version 1.17.0-pre.2 and did not run in to `upstream connect error or disconnect/reset before headers. reset reason: connection timeout` errors any more. You could try that. Or you could try to set `bpf.hostLegacyRouting: true` as a workaround. See https://github.com/cilium/cilium/issues/30510.

**Comment by taljacob2** [comment]
Hi I struggled with this issue for the past week. I finally fixed it in my system, hoping this may work for others.

### My Environment Setup

I have a single node of RockyLinux 9.5, with firewalld service turned on by default.

I initialized the kubeadm cluster with the following CIDR:

```
sudo kubeadm init --pod-network-cidr=10.244.0.0/16
```

### Solution That Worked for Me

In my case, I had to stop the firewalld service and disable it, **before** installing Cilium

```
sudo systemctl stop firewalld
sudo systemctl disable firewalld
```

Then, I installed Cilium Gateway CRDs:

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
```

Then I installed Cilium with the following helm command:

> SIDE NOTES:
>
> - Used `--set operator.replicas=1` because I have only a single node.
> - Enabled monitoring of prometheus + grafana + hubble ui

```
helm install cilium cilium/cilium --version 1.16.4 --namespace kube-system --set ipam.mode=kubernetes --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" --set ipam.operator.clusterPoolIPv4PodCIDRList=10.244.0.0/16 --set prometheus.enabled=true --set operator.prometheus.enabled=true --set hubble.enabled=true --set hubble.metrics.enableOpenMetrics=true --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction}" --set gatewayAPI.enabled=true --set kubeProxyReplacement=true --set gatewayAPI.hostNetwork.enabled=true --set operator.replicas=1 --set envoy.securityContext.capabilities.keepCapNetBindService=true --set envoy.securityContext.capabilities.envoy="{NET_BIND_SERVICE,NET_ADMIN,SYS_ADMIN}" --set loadBalancer.l7.backend=envoy --set hostFirewall.enabled=true --set externalIPs.enabled=true --set envoy.enabled=true --set bpf.masquerade=true --set debug.enabled=true --set debug.verbose=flow --set hubble.relay.enabled=true --set hubble.ui.enabled=true
```

I created a `gateway` namespace:

```
kubectl create ns gateway
```

I created a gateway:

`gateway.yaml`:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  namespace: gateway
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    name: http-1
    allowedRoutes:
      namespaces:
        from: All
```

```
kubectl apply -f gateway.yaml
```

I created a demo HTTPRoute for Hubble UI:

`http-route-hubble-ui.yaml`:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: hubble-ui
  namespace: kube-system
spec:
  parentRefs:
  - name: gateway
    namespace: gateway
  hostnames:
  - "hubble-ui.cilium.rocks"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
      - name: hubble-ui
        kind: Service
        port: 8081
```

```
kubectl apply -f http-route-hubble-ui.yaml
```

Then when I tried to access the `hubble-ui.cilium.rocks` I got this this 503 Service Unavailable issue with that error message.

And I found out that when I **exposed the service as a `LoadBalancer` type** it finally worked out:

```
kubectl expose deployment.apps/hubble-ui --type=LoadBalancer -n kube-system --dry-run=client -o yaml | kubectl replace -f -
```

And that resolved my issue:

![Image](https://github.com/user-attachments/assets/482b3b78-7d1d-45da-86b1-b11af09453a6)

So from now and on, I set all my services as `LoadBalancer` type for the services that I want to be accessed via the gateway.
