### ISSUE TITLE
Gateway API GatewayClass Reconciliation fails

### ISSUE THREAD

**Issue by Pixdigit** [cilium/cilium#35562]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

I deployed a single-node k8s cluster with kubeadm using the kube-proxy replacement. Cilium is deployed via helm chart (also see values in the attachments below). When I want to deploy a gateway it never gets ready as the gatewayclass stays pending.

### How can we reproduce the issue?

1. Start up a single-node cluster with kubeadm (`kubeadm init --control-plane-endpoint example.host --pod-network-cidr 10.10.0.0/16 --skip-phases=addon/kube-proxy`)
2. Apply the experimental version of the gateway-api (v1.2.0) as per documentation: `kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/experimental-install.yaml`
3. Deploy the helm chart (I'm using helmfile but the command should be equivalent):
   ```sh
   helm repo add cilium https://helm.cilium.io/
   helm repo update
   helm install cilium cilium/cilium --version 1.16.3 \
     --namespace kube-system
     -f values.yaml
   ```
   With the relevant values being:
   ```yaml
   ipv6:
       enabled: true
    
   operator:
       replicas: 1
       rollOutPods: true
    
   encryption:
       enabled: true
       type: wireguard
       nodeEncryption: true
       persistentKeepalive: 60s
    
   kubeProxyReplacement: "true"
   k8sServiceHost: "auto"
   k8sServicePort: "auto"
    
   ingressController:
       enabled: false
       default: true
    
   gatewayAPI:
       enabled: true
    
   rollOutCiliumPods: true
   ```

### Cilium Version

cilium-cli: v0.16.19 compiled with go1.23.1 on linux/amd64
cilium image (default): v1.16.2
cilium image (stable): v1.16.3
cilium image (running): 1.16.3

### Kernel Version

Linux example.host 6.10.11+bpo-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.10.11-1~bpo12+1 (2024-10-03) x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.30.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.6

Helm: version.BuildInfo{Version:"v3.16.1", GitCommit:"5a5449dc42be07001fd5771d56429132984ab3ab", GitTreeState:"clean", GoVersion:"go1.22.7"}

### Regression

I don't know. This is my first Cilium deployment.

### Sysdump

[cilium-sysdump-20241026-012504.zip](https://github.com/user-attachments/files/17528276/cilium-sysdump-20241026-012504.zip)

### Relevant log output

This error occurs multiple times:

```
time="2024-10-29T21:15:10Z" level=info msg="Reconciling GatewayClass" controller=gatewayclass resource=/cilium subsys=gateway-controller
time="2024-10-29T21:15:10Z" level=error msg="Failed to update GatewayClass status" controller=gatewayclass error="GatewayClass.gateway.networking.k8s.io \"cilium\" is invalid: [supportedFeatures[0]: Invalid value: \"string\": supportedFeatures[0] in body must be of type object: \"string\", supportedFeatures[1]: Invalid value: \"string\": supportedFeatures[1] in body must be of type object: \"string\", supportedFeatures[2]: Invalid value: \"string\": supportedFeatures[2] in body must be of type object: \"string\", supportedFeatures[3]: Invalid value: \"string\": supportedFeatures[3] in body must be of type object: \"string\", supportedFeatures[4]: Invalid value: \"string\": supportedFeatures[4] in body must be of type object: \"string\", supportedFeatures[5]: Invalid value: \"string\": supportedFeatures[5] in body must be of type object: \"string\", supportedFeatures[6]: Invalid value: \"string\": supportedFeatures[6] in body must be of type object: \"string\", supportedFeatures[7]: Invalid value: \"string\": supportedFeatures[7] in body must be of type object: \"string\", supportedFeatures[8]: Invalid value: \"string\": supportedFeatures[8] in body must be of type object: \"string\", supportedFeatures[9]: Invalid value: \"string\": supportedFeatures[9] in body must be of type object: \"string\", supportedFeatures[10]: Invalid value: \"string\": supportedFeatures[10] in body must be of type object: \"string\", supportedFeatures[11]: Invalid value: \"string\": supportedFeatures[11] in body must be of type object: \"string\", supportedFeatures[12]: Invalid value: \"string\": supportedFeatures[12] in body must be of type object: \"string\", supportedFeatures[13]: Invalid value: \"string\": supportedFeatures[13] in body must be of type object: \"string\", supportedFeatures[14]: Invalid value: \"string\": supportedFeatures[14] in body must be of type object: \"string\", status.supportedFeatures[0]: Invalid value: \"Gateway\": must be an object for an array of list-type map, <nil>: Invalid value: \"null\": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]" resource=/cilium subsys=gateway-controller
time="2024-10-29T21:15:10Z" level=error msg="Reconciler error" GatewayClass="{cilium }" controller=gatewayclass controllerGroup=gateway.networking.k8s.io controllerKind=GatewayClass error="GatewayClass.gateway.networking.k8s.io \"cilium\" is invalid: [supportedFeatures[0]: Invalid value: \"string\": supportedFeatures[0] in body must be of type object: \"string\", supportedFeatures[1]: Invalid value: \"string\": supportedFeatures[1] in body must be of type object: \"string\", supportedFeatures[2]: Invalid value: \"string\": supportedFeatures[2] in body must be of type object: \"string\", supportedFeatures[3]: Invalid value: \"string\": supportedFeatures[3] in body must be of type object: \"string\", supportedFeatures[4]: Invalid value: \"string\": supportedFeatures[4] in body must be of type object: \"string\", supportedFeatures[5]: Invalid value: \"string\": supportedFeatures[5] in body must be of type object: \"string\", supportedFeatures[6]: Invalid value: \"string\": supportedFeatures[6] in body must be of type object: \"string\", supportedFeatures[7]: Invalid value: \"string\": supportedFeatures[7] in body must be of type object: \"string\", supportedFeatures[8]: Invalid value: \"string\": supportedFeatures[8] in body must be of type object: \"string\", supportedFeatures[9]: Invalid value: \"string\": supportedFeatures[9] in body must be of type object: \"string\", supportedFeatures[10]: Invalid value: \"string\": supportedFeatures[10] in body must be of type object: \"string\", supportedFeatures[11]: Invalid value: \"string\": supportedFeatures[11] in body must be of type object: \"string\", supportedFeatures[12]: Invalid value: \"string\": supportedFeatures[12] in body must be of type object: \"string\", supportedFeatures[13]: Invalid value: \"string\": supportedFeatures[13] in body must be of type object: \"string\", supportedFeatures[14]: Invalid value: \"string\": supportedFeatures[14] in body must be of type object: \"string\", status.supportedFeatures[0]: Invalid value: \"Gateway\": must be an object for an array of list-type map, <nil>: Invalid value: \"null\": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]" name=cilium namespace= reconcileID="\"7f0f9feb-890d-4843-a250-cb7a5c1ce102\"" subsys=controller-runtime
```

### Anything else?

This is the manifest I use to deploy the Gateway:

```yaml
apiVersion: v1
kind: Pod
metadata:
    name: test-service
    labels:
        app: test-service
spec:
    containers:
        - name: test-service
          image: docker.io/library/nginx
          ports:
              - name: web
                containerPort: 8080
    tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          effect: "NoSchedule"
        - key: "CriticalAddonsOnly"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
    name: whoami

spec:
    type: LoadBalancer
    ports:
        - name: web
          port: 8080
          targetPort: web

    selector:
        app: test-service
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
    name: testing-gateway
    annotations:
        cert-manager.io/issuer: le-staging
spec:
    gatewayClassName: cilium
    listeners:
        - name: http
          protocol: HTTP
          port: 8080
          allowedRoutes:
              namespaces:
                  from: All

        - name: https
          protocol: HTTPS
          hostname: "example.host"
          port: 8443
          tls:
              mode: Terminate
              certificateRefs:
                  - name: example.host-tls-cert

          allowedRoutes:
              namespaces:
                  from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: test-httproute
spec:
    parentRefs:
        - name: testing-gateway
          sectionName: https
    hostnames:
        - "example.host"
    rules:
        - matches:
              - path:
                    type: PathPrefix
                    value: /
          backendRefs:
              - name: whoami
                port: 8080

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
