### ISSUE TITLE
Hubble metrics causes hubble relay pod not to work

### ISSUE THREAD

**Issue by tman5** [cilium/cilium#35655]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

When using talos linux and a helm deploy and hubble metrics are enabled, the hubble relay service crash loops. Removing the hubble metric config the relay service works properly. Here is the relay logs

### How can we reproduce the issue?

Using helm as the install with these values

```
kubeProxyReplacement: true
ipam:
  mode: kubernetes
prometheus:
  enabled: true
operator:
  prometheus:
    enabled: true
hubble:
  metrics:
    enableOpenMetrics: true
    enabled:
       - dns
       - drop
       - tcp
       - flow
       - port-distribution
       - icmp
       - httpV2:exemplars=true;labelsContext=source_ip
       - source_namespace
       - source_workload
       - destination_ip
       - destination_namespace
       - destination_workload
       - traffic_direction
  relay:
    enabled: true
  ui:
    enabled: true
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
k8sServiceHost: localhost
k8sServicePort: 7445
```

### Cilium Version

1.16.3

### Kernel Version

6.6.58-talos

### Kubernetes Version

1.31.2

### Sysdump

[cilium-sysdump-20241030-114135.zip](https://github.com/user-attachments/files/17575508/cilium-sysdump-20241030-114135.zip)

### Relevant log output

time="2024-10-30T15:37:32Z" level=info msg="Starting gRPC health server..." addr=":4222" subsys=hubble-relay
time="2024-10-30T15:37:32Z" level=info msg="Starting gRPC server..." options="{peerTarget:hubble-peer.kube-system.svc.cluster.local:443 dialTimeout:30000000000 retryTimeout:30000000000 listenAddress::4245 healthListenAddress::4222 metricsListenAddress: log:0xc0004001c0 serverTLSConfig:<nil> insecureServer:true clientTLSConfig:0xc0004d2e10 clusterName:default insecureClient:false observerOptions:[0x2218120 0x2218200] grpcMetrics:<nil> grpcUnaryInterceptors:[] grpcStreamInterceptors:[]}" subsys=hubble-relay
time="2024-10-30T15:38:02Z" level=warning msg="Failed to create peer client for peers synchronization; will try again after the timeout has expired" error="context deadline exceeded" subsys=hubble-relay target="hubble-peer.kube-system.svc.cluster.local:443"
time="2024-10-30T15:38:41Z" level=info msg="Stopping server..." subsys=hubble-relay

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by tman5** [comment]
Turned out to be a misconfiguration of the metrics for hubble to export. Should have been:

```
hubble:
  metrics:
    enableOpenMetrics: true
    enabled:
       - dns
       - drop
       - tcp
       - flow
       - port-distribution
       - icmp
       - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
```
