### ISSUE TITLE
CiliumNetworkPolicy doesn't allow incoming traffic despite fromCIDR whitelist.

### ISSUE THREAD

**Issue by adippl** [cilium/cilium#35682]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

I have a ssh server running on kubernetes which I would want to expose only to specific sources IPs.
My cluster blocks all traffic by default. 
I've tried to whitelist this traffic using CiliumNetworkPolicy

I expected that this poilcy would allow me to do this:
```
metadata:
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cgit-ssh-ingress-from-clients
  namespace: cgit
specs:
  - endpointSelector:
      matchLabels:
        pod-label: cgit-pod
    ingress:
    - fromCIDR:
      - 10.0.9.204/32
      toPorts:
      - ports:
        - port: '22'
          protocol: TCP
``` 

It doesn't work and produces these policy verdicts:
```
Policy verdict log: flow 0x0 local EP ID 1468, remote ID world, proto 6, ingress, action deny, auth: disabled, match none, 10.201.5.24:47472 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x0 local EP ID 1468, remote ID world, proto 6, ingress, action deny, auth: disabled, match none, 10.201.5.24:47472 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x40e228c8 local EP ID 89, remote ID 47864, proto 6, egress, action allow, auth: disabled, match L3-L4, 10.201.2.161:54648 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x40e228c8 local EP ID 1468, remote ID host, proto 6, ingress, action allow, auth: disabled, match L3-L4, 10.201.2.161:54648 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0xe6296142 local EP ID 89, remote ID 47864, proto 6, egress, action allow, auth: disabled, match L3-L4, 10.201.2.161:54664 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0xe6296142 local EP ID 1468, remote ID host, proto 6, ingress, action allow, auth: disabled, match L3-L4, 10.201.2.161:54664 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x0 local EP ID 1468, remote ID world, proto 6, ingress, action deny, auth: disabled, match none, 10.201.5.24:47472 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x0 local EP ID 1468, remote ID world, proto 6, ingress, action deny, auth: disabled, match none, 10.201.5.24:47472 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x0 local EP ID 1468, remote ID world, proto 6, ingress, action deny, auth: disabled, match none, 10.201.5.24:47472 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x0 local EP ID 1468, remote ID world, proto 6, ingress, action deny, auth: disabled, match none, 10.201.5.24:47472 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0xe85bf088 local EP ID 89, remote ID 47864, proto 6, egress, action allow, auth: disabled, match L3-L4, 10.201.2.161:54680 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0xe85bf088 local EP ID 1468, remote ID host, proto 6, ingress, action allow, auth: disabled, match L3-L4, 10.201.2.161:54680 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x598269df local EP ID 89, remote ID 47864, proto 6, egress, action allow, auth: disabled, match L3-L4, 10.201.2.161:54682 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x598269df local EP ID 1468, remote ID host, proto 6, ingress, action allow, auth: disabled, match L3-L4, 10.201.2.161:54682 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x0 local EP ID 1468, remote ID world, proto 6, ingress, action deny, auth: disabled, match none, 10.201.5.24:47472 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x0 local EP ID 1468, remote ID world, proto 6, ingress, action deny, auth: disabled, match none, 10.201.5.24:47472 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0xc775ce22 local EP ID 89, remote ID 47864, proto 6, egress, action allow, auth: disabled, match L3-L4, 10.201.2.161:39534 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0xc775ce22 local EP ID 1468, remote ID host, proto 6, ingress, action allow, auth: disabled, match L3-L4, 10.201.2.161:39534 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x8b4779e5 local EP ID 89, remote ID 47864, proto 6, egress, action allow, auth: disabled, match L3-L4, 10.201.2.161:39536 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x8b4779e5 local EP ID 1468, remote ID host, proto 6, ingress, action allow, auth: disabled, match L3-L4, 10.201.2.161:39536 -> 10.201.2.80:22 tcp SYN
```

I had to replace it with this policy to gain access to the ssh server:
```
metadata:
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cgit-ssh-ingress-from-clients
  namespace: cgit
specs:
  - endpointSelector:
      matchLabels:
        pod-label: cgit-pod
    ingress:
    - fromEntities:
      - world
      toPorts:
      - ports:
        - port: '22'
          protocol: TCP
```

With this policy everyone can connect to this service but it works. 
Policy verdicts
```
Policy verdict log: flow 0x0 local EP ID 1468, remote ID world, proto 6, ingress, action allow, auth: disabled, match L3-L4, 10.201.5.24:41106 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x6f822b9f local EP ID 89, remote ID 47864, proto 6, egress, action allow, auth: disabled, match L3-L4, 10.201.2.161:36164 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x6f822b9f local EP ID 1468, remote ID host, proto 6, ingress, action allow, auth: disabled, match L3-L4, 10.201.2.161:36164 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0xa016554c local EP ID 89, remote ID 47864, proto 6, egress, action allow, auth: disabled, match L3-L4, 10.201.2.161:36168 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0xa016554c local EP ID 1468, remote ID host, proto 6, ingress, action allow, auth: disabled, match L3-L4, 10.201.2.161:36168 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x4703efd9 local EP ID 89, remote ID 47864, proto 6, egress, action allow, auth: disabled, match L3-L4, 10.201.2.161:36170 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x4703efd9 local EP ID 1468, remote ID host, proto 6, ingress, action allow, auth: disabled, match L3-L4, 10.201.2.161:36170 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x2c639c7e local EP ID 89, remote ID 47864, proto 6, egress, action allow, auth: disabled, match L3-L4, 10.201.2.161:36172 -> 10.201.2.80:22 tcp SYN
Policy verdict log: flow 0x2c639c7e local EP ID 1468, remote ID host, proto 6, ingress, action allow, auth: disabled, match L3-L4, 10.201.2.161:36172 -> 10.201.2.80:22 tcp SYN
```

I'm testing from IP I've used in the network policy and I don't see any errors related to this poilcy in logs of cilium pods.
Could you explain what am I missing?

### How can we reproduce the issue?

Relevant cilium helm values:
```
kubeProxyReplacement: true

operator:
  replicas: 1
  prometheus:
    enabled: true
  dashboards:
    enabled: true
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
# use vxlan with wireguard encryption
tunnel-protocol: vxlan
encryption:
  enabled: true
  type: wireguard

hubble:
  peerService:
    # configure our custom cluster dnsDomain
    clusterDomain: k8s1.acmelab.top
  relay:
    enabled: true
  ui:
    enabled: true
    # expose hubble-ui via ingress-nginx
    ingress:
      enabled: true


ingressController:
  enabled: true
  default: false
  loadbalancerMode: shared


ipam:
  mode: "cluster-pool"
  ciliumNodeUpdateRate: "15s"
  operator:
    clusterPoolIPv4PodCIDRList: ["10.201.0.0/16"]
    clusterPoolIPv4MaskSize: 24


# use only ipv4
ipv4:
  enabled: true
ipv6:
  enabled: false

policyEnforcementMode: default
policyAuditMode: false
hostFirewall:
  enabled: true
extraConfig:
  allow-localhost: policy
hostServices:
  enabled: true
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true

prometheus:
  enabled: true

bgpControlPlane:
  enabled: true

envoy:
  enabled: false
```

### Cilium Version

cilium version
cilium-cli: v0.16.9 compiled with go1.22.3 on linux/amd64
cilium image (default): v1.15.5
cilium image (stable): v1.16.3
cilium image (running): 1.16.0

### Kernel Version

uname -a
Linux gh-k8s1-worker-3 6.6.30-gentoo-dist #1 SMP PREEMPT_DYNAMIC Thu May  2 17:09:53 -00 2024 x86_64 13th Gen Intel(R) Core(TM) i5-13500 GenuineIntel GNU/Linux

### Kubernetes Version

kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
