### ISSUE TITLE
CFP: Support JWT Verification for HTTPRoute of Gateway-API

### ISSUE THREAD

**Issue by chaunceyjiang** [cilium/cilium#35824]
## Cilium Feature Proposal

Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](https://slack.cilium.io) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your proposed feature related to a problem?**

Currently, we are using gateway-api to provide external services, but now Cilium seems not to support JWT verification. Similar to other gateway-api providers, they all provide such functionality.

istio:

https://istio.io/latest/docs/tasks/security/authentication/authn-policy/#end-user-authentication

envoy gateway:

https://gateway.envoyproxy.io/docs/tasks/security/jwt-authentication/
https://github.com/envoyproxy/gateway/blob/main/examples/kubernetes/jwt/jwt.yaml

contour:

https://projectcontour.io/docs/1.23/config/jwt-verification/

**Describe the feature you'd like**

Hope that Cilium can also provide similar functionality.

**(Optional) Describe your proposed solution**

It can be implemented through the [jwt_authn HTTP filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/jwt_authn_filter).

**Comment by chaunceyjiang** [comment]
@sayboras How do you think?

**Comment by sakirma** [comment]
At least a ciliumclusterwideenvoyconfig example would be perfect on the documentation.
@chaunceyjiang did you manage to get that working? I am currently working on implementing it myself

**Comment by chaunceyjiang** [comment]
My idea is to design a new CRD, similar to the following
```
apiVersion: cilium.io/v1
kind: CiliumRequestAuthentication
metadata:
  name: "jwt-example"
  namespace: foo
spec:
  targetRef:
    kind: Gateway
    group: gateway.networking.k8s.io
    name: httpbin-gateway
  jwtRules:
  - issuer: "testing@secure.cilium.io"
    jwksUri: "https://raw.githubusercontent.com/envoyproxy/gateway/main/examples/kubernetes/jwt/jwks.json"
```
