### ISSUE TITLE
hubble-relay is CrashLoopBackOff through `Hubble: Warning Server not initialized`

### ISSUE THREAD

**Issue by herbic1d3** [cilium/cilium#35849]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

hubble-relay can't connect, log example
```bash
time="2024-11-07T16:41:50Z" level=info msg="Starting gRPC health server..." addr=":4222" subsys=hubble-relay
time="2024-11-07T16:41:50Z" level=info msg="Starting gRPC server..." options="{peerTarget:hubble-peer.kube-system.svc.cluster.local:443 dialTimeout:30000000000 retryTimeout:30000000000 listenAddress::4245 healthListenAddress::4222 metricsListenAddress: log:0xc0005015e0 serverTLSConfig:<nil> insecureServer:true clientTLSConfig:0xc000994dc8 clusterName:default insecureClient:false observerOptions:[0x2218120 0x2218200] grpcMetrics:<nil> grpcUnaryInterceptors:[] grpcStreamInterceptors:[]}" subsys=hubble-relay
time="2024-11-07T16:42:20Z" level=warning msg="Failed to create peer client for peers synchronization; will try again after the timeout has expired" error="context deadline exceeded" subsys=hubble-relay target="hubble-peer.kube-system.svc.cluster.local:443"
time="2024-11-07T16:42:57Z" level=info msg="Stopping server..." subsys=hubble-relay
```
but main problem that hubbe isn't start
```bash
# cilium status
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.30 (v1.30.3) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    True      [eth0   10.0.3.29 fe80::4001:aff:fe00:31d (Direct Routing)]
Host firewall:           Enabled   [eth0]
SRv6:                    Disabled
CNI Chaining:            none
CNI Config file:         successfully wrote CNI configuration file to /host/etc/cni/net.d/05-cilium.conflist
Cilium:                  Ok   1.16.3 (v1.16.3-f2217191)
NodeMonitor:             Disabled
Cilium health daemon:    Ok   
IPAM:                    IPv4: 2/254 allocated from 10.244.1.0/24, 
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Routing:                 Network: Tunnel [vxlan]   Host: BPF
Attach Mode:             TCX
Device Mode:             veth
Masquerading:            BPF   [eth0]   10.244.1.0/24 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       20/20 healthy
Proxy Status:            OK, ip 10.244.1.135, 0 redirects active on ports 10000-20000, Envoy: external
Global Identity Range:   min 256, max 65535
Hubble:                  Warning Server not initialized
Encryption:              Disabled        
Cluster health:          5/5 reachable   (2024-11-07T16:24:34Z)
Modules Health:          Stopped(0) Degraded(0) OK(42)
```
through that, exists problem with 

### How can we reproduce the issue?

yalm configuration
```yaml
metadata:
  name: bm-rpc-eu-01-cilium
  namespace: argocd
  labels:
    kind: apps
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  source:
    repoURL: https://helm.cilium.io/
    targetRevision: 1.16.3
    chart: cilium
    helm:
      releaseName: cilium
      version: v3
      valuesObject:
        debug:
          enabled: true
        ipam:
          mode: kubernetes
        kubeProxyReplacement: true
        securityContext:
          capabilities:
            ciliumAgent:
              - CHOWN
              - KILL
              - NET_ADMIN
              - NET_RAW
              - IPC_LOCK
              - SYS_ADMIN
              - SYS_RESOURCE
              - DAC_OVERRIDE
              - FOWNER
              - SETGID
              - SETUID
            cleanCiliumState:
              - NET_ADMIN
              - SYS_ADMIN
              - SYS_RESOURCE
        cgroup:
          autoMount:
            enabled: false
          hostRoot: /sys/fs/cgroup
        devices:
          - eth0
          - bond0
        k8sServiceHost: bm-rpc-eu-01.eth.p2p.world
        k8sServicePort: 443
        hostFirewall:
          enabled: true
        loadBalancer:
          acceleration: disabled
        prometheus:
          enabled: true
        bpf:
          hostLegacyRouting: false
          masquerade: true
        hubble:
          enabled: true
          debug: true
          ui:
            enabled: true
          relay:
            enabled: true
          metrics:
            enabled:
              - dns
              - drop
              - tcp
              - flow
              - port-distribution
              - icmp
              - httpV2:exemplars=true;labelsContext=source_ip
              - source_namespace
              - source_workload
              - destination_ip
              - destination_namespace
              - destination_workload
              - traffic_direction
              - dns:labelsContext=source_namespace,destination_namespace
              - drop:labelsContext=source_namespace,destination_namespace
        MTU: 1330
        policyEnforcementMode: default
        policyAuditMode: true
  destination:
    name: bm-rpc-eu-01
    namespace: kube-system
  project: bm-rpc-eu-01
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
kind: Application
apiVersion: argoproj.io/v1alpha1
```

### Cilium Version

1.16.3 (v1.16.3-f2217191)

### Kernel Version

Talos (v1.7.6)  6.6.43-talos

### Kubernetes Version

Server Version: v1.30.3

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
`hubble-peer.kube-system.svc.cluster.local:443` is a service IP with `internalTrafficPolicy: Local`. It redirects to port 4244 on the same node, which is opened by the agent.

Can you verify that the agents are listening on that port, and that it is not blocked by NetworkPolicy, iptables, or anything else?

**Comment by herbic1d3** [comment]
cilium policy
```json
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "any:app.kubernetes.io/name": "hubble-relay",
              "any:app.kubernetes.io/part-of": "cilium",
              "any:k8s-app": "hubble-relay"
            },
            "matchExpressions": [
              {
                "key": "k8s:io.kubernetes.pod.namespace",
                "operator": "Exists"
              }
            ]
          }
        ],
        "toPorts": [
          {
            "ports": [
              {
                "port": "4244",
                "protocol": "TCP"
              }
            ]
          }
        ]
      }
    ],
```
cluster NetworkPolicy off

**Comment by AnjaSimons** [comment]
I have seen that hubble status in cilium is ok when I install cilium without hubble-relay, unix:///var/run/cilium/hubble.sock exists and runs, but when I enable hubble-relay then the hubble status is failed, because /var/run/cilium/hubble.sock is not found. So when run the command cilium-dbg status with hubble-relay enabled response on Hubble: "Warning: The hubble server is not initialized". So hubble-relay cannot reach the hubble-server.

**Comment by squeed** [comment]
It is likely that the traffic is being blocked; the Cilium pods are host-network and thus the usual NetworkPolicy rules do not apply. Can you check in Hubble to see if there are any drops.

You will probably have to write a policy that allows the `remote-node` and `host` entities.

**Comment by AnjaSimons** [comment]
> It is likely that the traffic is being blocked; the Cilium pods are host-network and thus the usual NetworkPolicy rules do not apply. Can you check in Hubble to see if there are any drops.
> 
> You will probably have to write a policy that allows the `remote-node` and `host` entities.

Can you check in Hubble to see if there are any drops.
this is not possible, because the hubble server is not initialized, so hubble status and all other hubble commands are not running.

I have the same problem, after upgrading the host system from Ubuntu 22.04 to 24.04. But I am not sure. I know, that I was able to run hubble-relay and hubble-ui once before some weeks. But I don't know all the environment changes. 
I use Kubernetes 1.31.x, 
these are the values for installing Cilium (I actually disabled hubble-relay and hubble-ui because of the disfunctional, but this are the only changes):
enableIPv4Masquerade: true
enableHostReachableServices: true
enableNodePort: true
nodePort:
  mode: snat
debug:
  enabled: true
  verbose: "datapath"
# Prometheus monitoring settings for Cilium and Hubble
monitoring:
  enabled: true
  prometheus:
    enabled: true
    # Use Prometheus integration with Cilium
    scrapeInterval: 15s  # Scrape metrics every 15 seconds
    port: 9090          # Default Prometheus port

# Add Prometheus support and configuration for monitoring Cilium and Hubble
prometheus:
  enabled: true
  serviceMonitor:
    trustCRDsExist: true  # Enables Prometheus Operator's ServiceMonitor resource to scrape Cilium metrics
  # Optional settings for the Prometheus service if you're exposing it externally
  service:
    type: NodePort  # Expose Prometheus via NodePort (adjust if you need another type)
    nodePort:
      port: 30900    # Set a specific NodePort for Prometheus metrics

# Enable eBPF metrics in Prometheus
ciliumMetrics:
  enabled: true  # Enable Cilium-specific metrics for Prometheus

# Enable OpenTelemetry integration (optional)
openTelemetry:
  enabled: false # Disable OpenTelemetry if not required

# Enable Cilium's built-in network policy enforcement
enablePolicy: true

# Add specific Cilium configuration for network observability
enableFlowLogs: true  # Enable flow logs for more detailed observability

# Optional: Enable more verbose debugging if needed
enableDebugLogging: true
kubeProxyReplacement: true
k8sServiceHost: my host ip
k8sServicePort: 6443
operator:
  replicas: 1
bpf:
  masquerade: true
policyAuditMode: true
hubble:
  enabled: true
  metrics:
    enableOpenMetrics: true
    enabled:
    - dns:query;ignoreAAAA
    - drop
    - tcp
    - flow
    - port-distribution
    - icmp
    - http
    - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
  relay:
    enabled: false
    dialTimeout: 20s
    retryTimeout: 10s
    tls:
      enabled: true
  ui:
    enabled: false
    service:
      type: NodePort
    frontend:
      server:
        ipv6:
          enabled: true
  tls:
    enabled: true

**Comment by squeed** [comment]
> this is not possible, because the hubble server is not initialized

You can execute hubble in the Cilium container. `kubectl -n kube-system exec -ti <<CILIUM POD>> -- bash` will get you an interactive terminal. There you can execute `hubble` directly, which will show all flows on that node.

**Comment by herbic1d3** [comment]
Thanks to all of you for your help :) Main problem was in 
```yaml
        hubble:
          metrics:
            enabled:
              - dns
              - drop
              - tcp
              - flow
              - port-distribution
              - icmp
              - httpV2:exemplars=true;labelsContext=source_ip
              - source_namespace
              - source_workload
              - destination_ip
              - destination_namespace
              - destination_workload
              - traffic_direction
              - dns:labelsContext=source_namespace,destination_namespace
              - drop:labelsContext=source_namespace,destination_namespace
```
I changed to 
```yaml
        hubble:
          metrics:
            enabled:
              - dns
              - drop
              - tcp
              - flow
              - port-distribution
              - icmp
              - dns:labelsContext=source_namespace,destination_namespace
              - drop:labelsContext=source_namespace,destination_namespace
              - httpV2:sourceContext=workload-name|pod-name|reserved-identity;destinationContext=workload-name|pod-name|reserved-identity;labelsContext=source_namespace,destination_namespace,traffic_direction
```
First of all it was my mistake with list of metrics and it's similar with issue https://github.com/cilium/cilium/issues/27506.
But anywhere the `hubble` wasn't started by that and there was a problem with the hubble-peers.

Issue resolved :)
