### ISSUE TITLE
CFP: Cilium ingress extent service LoadBalancer manifest

### ISSUE THREAD

**Issue by vintury** [cilium/cilium#35882]
## Cilium Feature Proposal

When creating an ingress, cilium creates a service with the LoadBalancer type. In Hetzner Cloud, to create a balancer, you also need to enter additional annotations, as indicated in the instructions: https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/docs/load_balancers.md#sample-service-with-networks
```
apiVersion: v1
kind: Service
metadata:
  name: example-service
  annotations:
    load-balancer.hetzner.cloud/location: hel1
    load-balancer.hetzner.cloud/use-private-ip: "true"
spec:
  selector:
    app: example
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
```

# At the moment, these annotations cannot be added through the cilium ingress maifest.
Without this annotation, the balancer cannot be created.
Error from log hcloud-cloud-controller-manager:
`
I1110 18:25:55.447052       1 event.go:389] "Event occurred" object="kube-system/cilium-ingress" fieldPath="" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.Create: neither load-balancer.hetzner.cloud/location nor load-balancer.hetzner.cloud/network-zone set"
`

# Current state:
cilium ingress manifest:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: default
spec:
  ingressClassName: cilium
  rules:
  - http:
      paths:
      - backend:
          service:
            name: details
            port:
              number: 9080
        path: /details
        pathType: Prefix
      - backend:
          service:
            name: productpage
            port:
              number: 9080
        path: /
        pathType: Prefix
```

kube service list
```
kubectl get service
NAME                           TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
cilium-ingress-basic-ingress   LoadBalancer   10.43.9.82     <pending>     80:30886/TCP,443:30419/TCP   5s
```
Detailed information about the problem on the service with the LoadBalancer type:
```
kkubectl describe  svc cilium-ingress-basic-ingress
Name:                     cilium-ingress-basic-ingress
Namespace:                default
Labels:                   cilium.io/ingress=true
Annotations:              <none>
Selector:                 <none>
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.43.9.82
IPs:                      10.43.9.82
Port:                     http  80/TCP
TargetPort:               80/TCP
NodePort:                 http  30886/TCP
Endpoints:
Port:                     https  443/TCP
TargetPort:               443/TCP
NodePort:                 https  30419/TCP
Endpoints:
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                  Age                From                Message
  ----     ------                  ----               ----                -------
  Normal   EnsuringLoadBalancer    19s (x3 over 34s)  service-controller  Ensuring load balancer
  Warning  SyncLoadBalancerFailed  18s (x3 over 34s)  service-controller  Error syncing load balancer: failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.Create: neither load-balancer.hetzner.cloud/location nor load-balancer.hetzner.cloud/network-zone set
```
# Expected state:
I expect that when creating an ingress there will be an option to pass annotations that will be added to the service.
For example:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: default
  annotations:
    load-balancer.hetzner.cloud/location: hel1
    load-balancer.hetzner.cloud/use-private-ip: "true"
spec:
  ingressClassName: cilium
  rules:
...
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    load-balancer.hetzner.cloud/location: hel1
    load-balancer.hetzner.cloud/use-private-ip: "true"
  labels:
    cilium.io/ingress: "true"
  name: cilium-ingress-basic-ingress
  namespace: default
spec:
...
  type: LoadBalancer
```
