### ISSUE TITLE
Cluster Mesh loses connection after pods restarting. Is this a bug or the default state?

### ISSUE THREAD

**Issue by JWebDev** [cilium/cilium#35975]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Hi, I don't understand yet if this is a bug or the default state. Or is there something wrong with my default settings.

The situation is simple, I have 2 clusters and I connect them using Clustermesh. Both clusters have the same Kubernetes versions, linux systems, settings and different CIDRs.
After installing and connecting the clusters everything is ok. But when I restartthe cilium pods, the Clustermesh connection disappears. Also accordingly it disappears if I do helm upgrade. For example, to turn off some prometheus endpoint.
Doesn't help neither operator restart nor apiserver. Only creating a new connection helps.

1. My question is this a bug or default state? 
2. What settings should I have and what should I pay attention to in order to prevent future loss of Clustermesh connection?
3. Or does it happen only if all cilium agents in the cluster are simultaneously restarted at the same time?

And yes, thanks for a good product that works. ))

### How can we reproduce the issue?

1. Install cilium with Helm
2. `helm upgrade -i cilium cilium/cilium --namespace kube-system -f app/cilium/values.yaml`
3. `cilium clustermesh connect --context cluster1--destination-context cluster2`
4. Default values for both cluster:
```
cluster:
  name: app
  id: 2

cni:
  install: false

certgen:
  generateCA: false

hubble:
  tls:
    enabled: false
  relay:
    enabled: true
    prometheus:
      enabled: true
  ui:
    enabled: true
    standalone:
      enabled: true

prometheus:
  enabled: true

envoy:
  enabled: false
  prometheus:
    enabled: false

clustermesh:
  useAPIServer: true
  enableEndpointSliceSynchronization: true

authentication:
  enabled: false
```

### Cilium Version

1.16.3

### Kernel Version

`Linux app 6.8.0-48-generic #48-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 14:04:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

v1.31.1

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
