### ISSUE TITLE
[connectivity-tests] - Throws segmentation violation -> "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by learnitall** [cilium/cilium#36018]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.3 and lower than v1.17.0

### What happened?

Running the `cilium connectivity test ` traceback with invalid memory address:

```
$ cilium connectivty test -n cilium-system
[....]
[=] [cilium-test-1] Test [client-egress-to-cidrgroup-deny] [50/105]
......
[=] [cilium-test-1] Test [client-egress-to-cidr-deny-default] [51/105]
......
[=] [cilium-test-1] Skipping test [clustermesh-endpointslice-sync] [52/105] (skipped by condition)
[=] [cilium-test-1] Test [health] [53/105]
....
[=] [cilium-test-1] Skipping test [north-south-loadbalancing] [54/105] (Feature node-without-cilium is disabled)
[=] [cilium-test-1] Test [pod-to-pod-encryption] [55/105]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3b8 pc=0x3039042]

goroutine 39573 [running]:
github.com/cilium/cilium/cilium-cli/connectivity/check.Pod.Address({0x0, 0x0, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0}, 0x1)
	/go/src/github.com/cilium/cilium-cli/vendor/github.com/cilium/cilium/cilium-cli/connectivity/check/peer.go:107 +0x62
github.com/cilium/cilium/cilium-cli/connectivity/tests.getInterNodeIface({0x55f1af0, 0xc0000df940}, 0xc0007f6c60, 0xc002a0a2c0, 0xc002a0a340, 0xc002a0a280, 0xc002a0a300, 0x1, 0x0)
	/go/src/github.com/cilium/cilium-cli/vendor/github.com/cilium/cilium/cilium-cli/connectivity/tests/encryption.go:54 +0x308
github.com/cilium/cilium/cilium-cli/connectivity/tests.testNoTrafficLeak({0x55f1af0, 0xc0000df940}, 0xc0007f6c60, {0x55cd218, 0xc000fbb6e0}, 0xc002a0a280, 0xc002a0a2c0, 0xc002a0a300, 0xc002a0a340, 0x0, ...)
	/go/src/github.com/cilium/cilium-cli/vendor/github.com/cilium/cilium/cilium-cli/connectivity/tests/encryption.go:303 +0x2bb
github.com/cilium/cilium/cilium-cli/connectivity/tests.(*podToPodEncryption).Run.func1(0x1)
	/go/src/github.com/cilium/cilium-cli/vendor/github.com/cilium/cilium/cilium-cli/connectivity/tests/encryption.go:279 +0x1a6
github.com/cilium/cilium/cilium-cli/connectivity/check.(*Test).ForEachIPFamily(0xc0007f6c60, 0xc002dcdc40)
	/go/src/github.com/cilium/cilium-cli/vendor/github.com/cilium/cilium/cilium-cli/connectivity/check/test.go:840 +0xd8
github.com/cilium/cilium/cilium-cli/connectivity/tests.(*podToPodEncryption).Run(0xc000fbb6e0, {0x55f1af0, 0xc0000df940}, 0xc0007f6c60)
	/go/src/github.com/cilium/cilium-cli/vendor/github.com/cilium/cilium/cilium-cli/connectivity/tests/encryption.go:274 +0x5fa
github.com/cilium/cilium/cilium-cli/connectivity/check.(*Test).Run(0xc0007f6c60, {0x55f1af0, 0xc0000df940}, 0x37)
	/go/src/github.com/cilium/cilium-cli/vendor/github.com/cilium/cilium/cilium-cli/connectivity/check/test.go:375 +0x664
github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).Run.func1()
	/go/src/github.com/cilium/cilium-cli/vendor/github.com/cilium/cilium/cilium-cli/connectivity/check/context.go:411 +0x99
created by github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).Run in goroutine 894
	/go/src/github.com/cilium/cilium-cli/vendor/github.com/cilium/cilium/cilium-cli/connectivity/check/context.go:405 +0x91

 ....
```

Implementation details:

* Wireguard encryption enabled
* Wireguard node-to-node encryption enabled
* KubeProxy replacement

### How can we reproduce the issue?

1. Deploy an EKS cluster without any CNI;
2. Deploy Cilium with the following options:

```yaml
bpf:
  hostLegacyRouting: false
  masquerade: true

clustermesh:
  replicas: 1
  useAPIServer: false
  apiserver:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      type: LoadBalancer
    tls:
      enabled: true
      auto:
        enabled: true
        method: cronJob

encryption:
  enabled: true
  nodeEncryption: true
  type: wireguard

eni:
  awsEnablePrefixDelegation: true
  enabled: true

envoy:
  enabled: true
  rollOutPods: true

externalWorkloads:
  enabled: false

gatewayAPI:
  enabled: false

ipam:
  mode: eni

hubble:
  enabled: false
  relay:
    enabled: false
  tls:
    enabled: true
    auto:
      enabled: true
      method: cronJob
operator:
  prometheus:
    enabled: false
  replicas: 1
  unmanagedPodWatcher:
    restart: true

devices: eth0
routingMode: native
k8sServiceHost: <KUBE_API_HOST>
k8sServicePort: 443
kubeProxyReplacement: true
```

3. Run `cilium connectivty test`

### Cilium Version

```
$ cilium version -n cilium-system 
cilium-cli: v0.16.20 compiled with go1.23.2 on linux/amd64
cilium image (default): v1.16.3
cilium image (stable): v1.16.3
cilium image (running): v1.16.3@sha256:62d2a09bbef840a46099ac4c69421c90f84f28d018d479749049011329aa7f28

```

### Kernel Version

Not available

### Kubernetes Version

```
$ kubectl version
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.28.13-eks-a737599

```

### Relevant log output

```shell

```

### Anything else?

Moved here from https://github.com/cilium/cilium-cli/issues/2859. Originally reported by @tchellomello. See https://cilium.slack.com/archives/CHQF00WMT/p1731341576343369.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
