### ISSUE TITLE
BGP announcement disappears after pod restarted/recreated

### ISSUE THREAD

**Issue by sca-** [cilium/cilium#36055]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.3 and lower than v1.17.0

### What happened?

There is a deployment with 1 pod. 
A `Service` object with `type: LoadBalancer` is pointed to this pod with manually set `loadBalancerIP` address.
There is bgp announcement present and `cilium bgp routes` cli command shows it.

After pod being manually deleted, it is re-created by deployment.
The announcement disappears while Pod is down and doesn't return until manual `Service` reconcile trigger (`Service` object update).

The most representative example is with two `LoadBalancer Service` objects pointed to single Pod.
One of them may recover after pod restart, the other not.

The bug is floating.

### How can we reproduce the issue?

1. on cilium 1.16.3
2. create a Pod (preferably with Deployment)
3. create Service `type: LoadBalancer` with manually set `loadBalancerIP`
4. randomly restart / delete Pod
5. try to catch missing announcement with `cilium bgp routes`

### Cilium Version

1.16.3

### Kernel Version

5.14.0-497.el9.x86_64

### Kubernetes Version

v1.29.0-rc.1.4076+f10c92d5d8e114-dirty

### Regression

1.14.16

### Cilium Sysdump
[File 55M](https://owncloud.tutu.ru/index.php/s/h3etIHy7Zyhp85v)

### Anything else?

Service №1 yaml
```yaml
kind: Service
apiVersion: v1
metadata:
  name: lb-1-service-unit
  namespace: testing-cluster-routes-testspace-testing
  creationTimestamp: '2024-11-19T17:00:50Z'
  labels:
    app: testsrv-http
spec:
  clusterIP: 172.30.226.132
  loadBalancerIP: 10.17.8.7
  externalTrafficPolicy: Local
  ipFamilies:
    - IPv4
  healthCheckNodePort: 31357
  ports:
    - name: main
      protocol: TCP
      port: 80
      targetPort: main
      nodePort: 31648
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.226.132
  allocateLoadBalancerNodePorts: true
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    name: testsrv-http-v20241119-193149
    unit: testsrv-http
status:
  loadBalancer:
    ingress:
      - ip: 10.17.8.7
  conditions:
    - type: cilium.io/IPAMRequestSatisfied
      status: 'True'
      lastTransitionTime: '2024-11-19T17:00:50Z'
      reason: satisfied
      message: ''

```

Service №2 yaml
```yaml
kind: Service
apiVersion: v1
metadata:
  name: lb-2-service-unit
  namespace: testing-cluster-routes-testspace-testing
  creationTimestamp: '2024-11-19T17:01:03Z'
  labels:
    app: testsrv-http
spec:
  clusterIP: 172.30.191.63
  loadBalancerIP: 10.17.8.8
  externalTrafficPolicy: Local
  ipFamilies:
    - IPv4
  healthCheckNodePort: 32654
  ports:
    - name: main
      protocol: TCP
      port: 80
      targetPort: main
      nodePort: 31733
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.191.63
  allocateLoadBalancerNodePorts: true
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    name: testsrv-http-v20241119-193149
    unit: testsrv-http
status:
  loadBalancer:
    ingress:
      - ip: 10.17.8.8
  conditions:
    - type: cilium.io/IPAMRequestSatisfied
      status: 'True'
      lastTransitionTime: '2024-11-19T17:01:03Z'
      reason: satisfied
      message: ''
```

BGP Routes before Pod restart
```
[20:57:57] ~ $ cilium -n cilium bgp routes
Node                                VRouter   Prefix            NextHop   Age          Attrs
hw-testing1-okd-master-01.tutu.ru   65000     10.128.6.0/23     0.0.0.0   106h33m30s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.241/32   0.0.0.0   106h33m30s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.242/32   0.0.0.0   106h33m30s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.243/32   0.0.0.0   106h33m30s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.0/32      0.0.0.0   106h33m30s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.1/32      0.0.0.0   106h33m30s   [{Origin: i} {Nexthop: 0.0.0.0}]   
hw-testing1-okd-master-02.tutu.ru   65000     10.128.4.0/23     0.0.0.0   106h37m36s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.241/32   0.0.0.0   106h37m36s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.242/32   0.0.0.0   106h37m36s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.243/32   0.0.0.0   106h37m36s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.0/32      0.0.0.0   106h37m36s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.1/32      0.0.0.0   106h37m36s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.2/32      0.0.0.0   71h24m44s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.3/32      0.0.0.0   71h22m44s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.5/32      0.0.0.0   71h18m44s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.7/32      0.0.0.0   13s          [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.8/32      0.0.0.0   13s          [{Origin: i} {Nexthop: 0.0.0.0}]   
hw-testing1-okd-master-03.tutu.ru   65000     10.128.8.0/23     0.0.0.0   106h34m34s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.241/32   0.0.0.0   106h34m34s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.242/32   0.0.0.0   106h34m34s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.243/32   0.0.0.0   106h34m34s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.0/32      0.0.0.0   106h34m34s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.1/32      0.0.0.0   106h34m34s   [{Origin: i} {Nexthop: 0.0.0.0}]   
hw-testing1-okd-worker-01.tutu.ru   65000     10.128.2.0/23     0.0.0.0   106h34m3s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.241/32   0.0.0.0   106h34m3s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.243/32   0.0.0.0   106h34m3s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.0/32      0.0.0.0   106h34m3s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.1/32      0.0.0.0   106h34m3s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.6/32      0.0.0.0   71h16m44s    [{Origin: i} {Nexthop: 0.0.0.0}]   
hw-testing1-okd-worker-02.tutu.ru   65000     10.128.0.0/23     0.0.0.0   106h36m15s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.241/32   0.0.0.0   106h36m15s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.243/32   0.0.0.0   106h36m15s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.0/32      0.0.0.0   106h36m15s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.1/32      0.0.0.0   106h36m15s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.4/32      0.0.0.0   71h20m44s    [{Origin: i} {Nexthop: 0.0.0.0}] 
```

BGP Routes during Pod restart
```
[20:58:04] ~ $ cilium -n cilium bgp routes
Node                                VRouter   Prefix            NextHop   Age          Attrs
hw-testing1-okd-master-01.tutu.ru   65000     10.128.6.0/23     0.0.0.0   106h33m37s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.241/32   0.0.0.0   106h33m37s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.242/32   0.0.0.0   106h33m37s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.243/32   0.0.0.0   106h33m37s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.0/32      0.0.0.0   106h33m37s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.1/32      0.0.0.0   106h33m37s   [{Origin: i} {Nexthop: 0.0.0.0}]   
hw-testing1-okd-master-02.tutu.ru   65000     10.128.4.0/23     0.0.0.0   106h37m43s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.241/32   0.0.0.0   106h37m43s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.242/32   0.0.0.0   106h37m43s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.243/32   0.0.0.0   106h37m43s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.0/32      0.0.0.0   106h37m43s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.1/32      0.0.0.0   106h37m43s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.2/32      0.0.0.0   71h24m51s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.3/32      0.0.0.0   71h22m51s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.5/32      0.0.0.0   71h18m51s    [{Origin: i} {Nexthop: 0.0.0.0}]   
hw-testing1-okd-master-03.tutu.ru   65000     10.128.8.0/23     0.0.0.0   106h34m41s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.241/32   0.0.0.0   106h34m41s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.242/32   0.0.0.0   106h34m41s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.243/32   0.0.0.0   106h34m41s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.0/32      0.0.0.0   106h34m41s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.1/32      0.0.0.0   106h34m41s   [{Origin: i} {Nexthop: 0.0.0.0}]   
hw-testing1-okd-worker-01.tutu.ru   65000     10.128.2.0/23     0.0.0.0   106h34m10s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.241/32   0.0.0.0   106h34m10s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.243/32   0.0.0.0   106h34m10s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.0/32      0.0.0.0   106h34m10s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.1/32      0.0.0.0   106h34m10s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.6/32      0.0.0.0   71h16m51s    [{Origin: i} {Nexthop: 0.0.0.0}]   
hw-testing1-okd-worker-02.tutu.ru   65000     10.128.0.0/23     0.0.0.0   106h36m22s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.241/32   0.0.0.0   106h36m22s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.243/32   0.0.0.0   106h36m22s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.0/32      0.0.0.0   106h36m22s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.1/32      0.0.0.0   106h36m22s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.4/32      0.0.0.0   71h20m51s    [{Origin: i} {Nexthop: 0.0.0.0}] 
```

BGP Routes after Pod restart
```
[20:58:29] ~ $ cilium -n cilium bgp routes
Node                                VRouter   Prefix            NextHop   Age          Attrs
hw-testing1-okd-master-01.tutu.ru   65000     10.128.6.0/23     0.0.0.0   106h34m2s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.241/32   0.0.0.0   106h34m2s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.242/32   0.0.0.0   106h34m2s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.243/32   0.0.0.0   106h34m2s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.0/32      0.0.0.0   106h34m2s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.1/32      0.0.0.0   106h34m2s    [{Origin: i} {Nexthop: 0.0.0.0}]   
hw-testing1-okd-master-02.tutu.ru   65000     10.128.4.0/23     0.0.0.0   106h38m8s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.241/32   0.0.0.0   106h38m8s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.242/32   0.0.0.0   106h38m8s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.243/32   0.0.0.0   106h38m8s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.0/32      0.0.0.0   106h38m8s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.1/32      0.0.0.0   106h38m8s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.2/32      0.0.0.0   71h25m16s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.3/32      0.0.0.0   71h23m16s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.5/32      0.0.0.0   71h19m16s    [{Origin: i} {Nexthop: 0.0.0.0}]   
hw-testing1-okd-master-03.tutu.ru   64600     10.17.11.241/32   0.0.0.0   106h35m6s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.242/32   0.0.0.0   106h35m6s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.243/32   0.0.0.0   106h35m6s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.0/32      0.0.0.0   106h35m6s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.1/32      0.0.0.0   106h35m6s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    65000     10.128.8.0/23     0.0.0.0   106h35m6s    [{Origin: i} {Nexthop: 0.0.0.0}]   
hw-testing1-okd-worker-01.tutu.ru   65000     10.128.2.0/23     0.0.0.0   106h34m35s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.241/32   0.0.0.0   106h34m35s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.243/32   0.0.0.0   106h34m35s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.0/32      0.0.0.0   106h34m35s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.1/32      0.0.0.0   106h34m35s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.6/32      0.0.0.0   71h17m16s    [{Origin: i} {Nexthop: 0.0.0.0}]   
hw-testing1-okd-worker-02.tutu.ru   65000     10.128.0.0/23     0.0.0.0   106h36m47s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.241/32   0.0.0.0   106h36m47s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.11.243/32   0.0.0.0   106h36m47s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.0/32      0.0.0.0   106h36m47s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.1/32      0.0.0.0   106h36m47s   [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.4/32      0.0.0.0   71h21m16s    [{Origin: i} {Nexthop: 0.0.0.0}]   
                                    64600     10.17.8.8/32      0.0.0.0   18s          [{Origin: i} {Nexthop: 0.0.0.0}]
```
(no `10.17.8.7` Announcement)
However, `Service` object `lb-1-service-unit` is still OK and showing `IPAMRequestSatisfied: true`

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
