### ISSUE TITLE
Cilium Cluster Wide Netowrk Policy for Kafka

### ISSUE THREAD

**Issue by AndreSannino** [cilium/cilium#36250]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.15.11 and lower than v1.16.0

### What happened?

1. I deployed Kafka on Kubernetes with 3 brokers labeled "app.kubernetes.io/name: kafka"
2. I deployed this rule CiliumClusterwideNetworkPolicy:
```yaml
`apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "kafka-policies"
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: kafka
  ingress:
  # KAFKA CONTROLLERS
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: kafka
    toPorts:
    - ports:
      - port: "9093"
        protocol: TCP
      - port: "9094"
        protocol: TCP
  # REDPANDA
  - fromEndpoints:
    - matchLabels:
        app: redpanda-console
    toPorts:
    - ports:
      - port: "9092"
        protocol: TCP
  # SERVIZIO PRODUCER
  - fromEndpoints:
    - matchLabels:
        app: producer
    toPorts:
    - ports:
      - port: "9092"
        protocol: TCP
      rules:
        kafka:
        - apiKey: "apiversions"
          topic: "TEST_KAFKA_NET"
        - apiKey: "metadata"
          topic: "TEST_KAFKA_NET"
        - apiKey: "produce"
          topic: "TEST_KAFKA_NET"
`
```
3. kubectl run kafka-producer --restart='Never' --image docker.io/bitnami/kafka:3.9.0-debian-12-r1 --namespace broker --labels="app=producer" --command -- sleep infinity
4. kubectl exec --tty -i kafka-producer --namespace broker -- bash 
5. kafka-console-producer.sh \
            --bootstrap-server kafka.broker.svc.cluster.local:9092 \
            --topic TEST_KAFKA_NET_2
6. I tried to publish some messagges and it worked. I shouldn't have been able to do it.

### How can we reproduce the issue?

1. I deployed Kafka on Kubernetes with 3 brokers labeled "app.kubernetes.io/name: kafka"
2. I deployed this rule CiliumClusterwideNetworkPolicy:
```yaml
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "kafka-policies"
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: kafka
  ingress:
  # KAFKA CONTROLLERS
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: kafka
    toPorts:
    - ports:
      - port: "9093"
        protocol: TCP
      - port: "9094"
        protocol: TCP
  # REDPANDA
  - fromEndpoints:
    - matchLabels:
        app: redpanda-console
    toPorts:
    - ports:
      - port: "9092"
        protocol: TCP
  # SERVIZIO PRODUCER
  - fromEndpoints:
    - matchLabels:
        app: producer
    toPorts:
    - ports:
      - port: "9092"
        protocol: TCP
      rules:
        kafka:
        - apiKey: "apiversions"
          topic: "TEST_KAFKA_NET"
        - apiKey: "metadata"
          topic: "TEST_KAFKA_NET"
        - apiKey: "produce"
          topic: "TEST_KAFKA_NET"
```
3. kubectl run kafka-producer --restart='Never' --image docker.io/bitnami/kafka:3.9.0-debian-12-r1 --namespace broker --labels="app=producer" --command -- sleep infinity
4. kubectl exec --tty -i kafka-producer --namespace broker -- bash 
5. kafka-console-producer.sh \
            --bootstrap-server kafka.broker.svc.cluster.local:9092 \
            --topic TEST_KAFKA_NET_2
6. I tried to publish some messagges and it worked. I shouldn't have been able to do it.

### Cilium Version

cilium-cli: v0.16.13 compiled with go1.22.5 on linux/amd64
cilium image (default): v1.15.6
cilium image (stable): v1.16.4
cilium image (running): 1.15.7

### Kernel Version

Linux version 5.15.0-87-generic

### Kubernetes Version

v1.29.6+k3s2

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
