### ISSUE TITLE
Lower Pod-Pod Same Node Throughput than Expected comparing Azure vs. Cilium

### ISSUE THREAD

**Issue by QxBytes** [cilium/cilium#36430]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.14.17 and lower than v1.15.0

### What happened?

# Expected Behavior
I expect the throughput of pod-pod same node on azure overlay to be the same as or worse than cilium because my cilium setup has no ebpf rules/programs to process and no iptable rules installed (see setup to see how this is achieved).

# Actual Behavior
After collecting the throughput and flamegraph three times, I notice that the azure overlay setup performs consistently better than the cilium one. By around 1.0 Gb/s (~5% difference).
The first image is the svg which can be opened in a new tab/zoomed into. The second image for each trial is a static screenshot zoomed into the iperf3 portion of the flamegraph.

Cilium trials:
1
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-40.00  sec   104 GBytes  22.4 Gbits/sec    0             sender
[  4]   0.00-40.00  sec   104 GBytes  22.4 Gbits/sec                  receiver
![Image](https://github.com/user-attachments/assets/04347a30-b4f3-4560-a81b-7302c609372a)
![Image](https://github.com/user-attachments/assets/1ceea72a-7ef7-4418-a7a5-b88d5375b02d)

2
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-40.00  sec   102 GBytes  21.8 Gbits/sec  914             sender
[  4]   0.00-40.00  sec   102 GBytes  21.8 Gbits/sec 
![Image](https://github.com/user-attachments/assets/a96d054f-28f8-44cb-8fb5-3585b507fdc4)
![Image](https://github.com/user-attachments/assets/c0ef95b5-f812-4663-866c-5838fbb93377)

3
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-40.00  sec   101 GBytes  21.6 Gbits/sec  1949             sender
[  4]   0.00-40.00  sec   101 GBytes  21.6 Gbits/sec                  receiver
![Image](https://github.com/user-attachments/assets/2b4c4de6-f251-4bdd-acd9-9cdf3aa813f0)
![Image](https://github.com/user-attachments/assets/d7953ffe-15c8-43db-b528-9693d862ff40)

Azure trials:
1
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-40.00  sec   107 GBytes  23.0 Gbits/sec  6714             sender
[  4]   0.00-40.00  sec   107 GBytes  23.0 Gbits/sec                  receiver
![Image](https://github.com/user-attachments/assets/99b85612-bcd6-4dae-a444-bf3c10fc3a27)
![Image](https://github.com/user-attachments/assets/04cbd675-0adb-42bd-ada3-c712a5a6cce4)

2
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-40.00  sec   107 GBytes  22.9 Gbits/sec  3392             sender
[  4]   0.00-40.00  sec   107 GBytes  22.9 Gbits/sec                  receiver
![Image](https://github.com/user-attachments/assets/662f8891-2e76-4fc1-80d1-71af67d43eb3)
![Image](https://github.com/user-attachments/assets/030f029e-8b04-4a15-84d9-66dc9a1bb350)

3
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-40.00  sec   106 GBytes  22.8 Gbits/sec  2370             sender
[  4]   0.00-40.00  sec   106 GBytes  22.8 Gbits/sec                  receiver
![Image](https://github.com/user-attachments/assets/78772a43-a9c5-4492-8058-b38efc5d74b3)
![Image](https://github.com/user-attachments/assets/37d7a64e-554d-4ff8-97ca-83e51d681048)

# Analysis
It seems like `skb_copy_datagram_iter` is taking longer in the cilium case than in the azure case. Due to this, there may be less time for carrying out networking functions under `tcp_cleanup_rbuf` for example, which may reduce throughput. I believe `skb_copy_datagram_iter` is related to copying data with respect to socket buffers, but I'm not sure if this is even related to cilium.

# Questions
- What could affect the performance of `skb_copy_datagram_iter`, or is this unrelated?
- Is there anything else added (ex: other processes, programs etc.) when cilium is enabled other than iptable rules or bpf programs attached to the nics that may affect performance?
- If we remove all bpf programs from nics and tell cilium to not add any iptable rules, is this expected to remove all overhead from cilium? If not, what could possibly be remaining?

### How can we reproduce the issue?

# Setup
I am currently comparing pod-pod throughput on the same node on azure overlay vs. cilium on aks with iperf3. 

For the clusters, they all have the same specs:
```
region: westus2
vm size: Standard_D64s_v3
node count: 2 (we only use one of the nodes)
k8s ver: 1.30
```
and I used this makefile:
```
https://github.com/Azure/azure-container-networking/blob/master/hack/aks/Makefile 
cilium cluster make target: overlay-byocni-nokubeproxy-up
- KUBE_PROXY_JSON_PATH=root/tmpsrc/kube-proxy.json
azure overlay make target: overlay-up
```

For the cilium setup, I bring up an azure overlay without kubeproxy cluster, and then apply daemonsets to install cilium. Then, I apply the configmap with `enable-host-legacy-routing: "true"`, and `install-iptables-rules: "false"`. For each setup, I create two pods on the same node. 

For the Cilium cluster, I **remove all bpf programs attached to the pod nics** since I do not want the bpf programs to reduce throughput.
To do this, on the node with the pods, I `ip route` to get the devices related to my two pods (based on the pod ips), and then for each device, I perform
```
tc filter del dev <dev name> ingress handle 0x1  prio 1 bpf
tc filter del dev <dev name> egress handle 0x1  prio 1 bpf
```
`tc filter show dev <dev name> egress`  (and ingress) for each nic is now empty

Then, for each setup (azure and cilium), I do the following:
- Start up `iperf3 -s` on one of the pods
- Start up `iperf3 -c <server pod ip> -t 40` on the other pod
- Capture a flame graph using the following:
```
wget https://raw.githubusercontent.com/brendangregg/FlameGraph/refs/heads/master/stackcollapse-perf.pl; wget https://raw.githubusercontent.com/brendangregg/FlameGraph/refs/heads/master/flamegraph.pl; chmod +x ./stackcollapse-perf.pl; chmod +x ./flamegraph.pl; rm out.perf-folded; rm perf.svg; rm perf.data; perf record -F 99 -a -g -- sleep 15; perf script | ./stackcollapse-perf.pl > out.perf-folded; ./flamegraph.pl out.perf-folded > perf.svg
```
- Measure performance

# Files
## Cilium Daemonset

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    meta.helm.sh/release-name: cilium
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
    k8s-app: cilium
  name: cilium
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: cilium
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/apply-sysctl-overwrites: unconfined
        container.apparmor.security.beta.kubernetes.io/cilium-agent: unconfined
        container.apparmor.security.beta.kubernetes.io/clean-cilium-state: unconfined
        container.apparmor.security.beta.kubernetes.io/mount-cgroup: unconfined
        prometheus.io/port: "9962"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        k8s-app: cilium
        kubernetes.azure.com/ebpf-dataplane: cilium
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/cluster
                operator: Exists
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                k8s-app: cilium
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - --config-dir=/tmp/cilium/config-map
        command:
        - cilium-agent
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CILIUM_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CILIUM_CLUSTERMESH_CONFIG
          value: /var/lib/cilium/clustermesh/
        image: mcr.microsoft.com/containernetworking/cilium/cilium:v1.14.15-241002
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            host: 127.0.0.1
            httpHeaders:
            - name: brief
              value: "true"
            path: /healthz
            port: 9879
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: cilium-agent
        ports:
        - containerPort: 9962
          hostPort: 9962
          name: prometheus
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            host: 127.0.0.1
            httpHeaders:
            - name: brief
              value: "true"
            path: /healthz
            port: 9879
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          capabilities:
            add:
            - CHOWN
            - KILL
            - NET_ADMIN
            - NET_RAW
            - IPC_LOCK
            - SYS_MODULE
            - SYS_ADMIN
            - SYS_RESOURCE
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
            drop:
            - ALL
          seLinuxOptions:
            level: s0
            type: spc_t
        startupProbe:
          failureThreshold: 105
          httpGet:
            host: 127.0.0.1
            httpHeaders:
            - name: brief
              value: "true"
            path: /healthz
            port: 9879
            scheme: HTTP
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/proc/sys/net
          name: host-proc-sys-net
        - mountPath: /host/proc/sys/kernel
          name: host-proc-sys-kernel
        - mountPath: /sys/fs/bpf
          mountPropagation: HostToContainer
          name: bpf-maps
        - mountPath: /var/run/cilium
          name: cilium-run
        - mountPath: /host/etc/cni/net.d
          name: etc-cni-netd
        - mountPath: /var/lib/cilium/clustermesh
          name: clustermesh-secrets
          readOnly: true
        - mountPath: /tmp/cilium/config-map
          name: cilium-config-path
          readOnly: true
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /run/xtables.lock
          name: xtables-lock
      dnsPolicy: ClusterFirst
      hostNetwork: true
      initContainers:
      - name: install-cni-binaries
        image: mcr.microsoft.com/containernetworking/cilium/cilium:v1.14.15-241002
        imagePullPolicy: IfNotPresent
        command:
          - "/install-plugin.sh"
        securityContext:
          seLinuxOptions:
            level: 's0'
            # Running with spc_t since we have removed the privileged mode.
            # Users can change it to a different type as long as they have the
            # type available on the system.
            type: 'spc_t'
          capabilities:
            drop:
              - ALL
        volumeMounts:
          - name: cni-path
            mountPath: /host/opt/cni/bin
      - command:
        - sh
        - -ec
        - |
          cp /usr/bin/cilium-mount /hostbin/cilium-mount;
          nsenter --cgroup=/hostproc/1/ns/cgroup --mount=/hostproc/1/ns/mnt "${BIN_PATH}/cilium-mount" $CGROUP_ROOT;
          rm /hostbin/cilium-mount
        env:
        - name: CGROUP_ROOT
          value: /run/cilium/cgroupv2
        - name: BIN_PATH
          value: /opt/cni/bin
        image: mcr.microsoft.com/containernetworking/cilium/cilium:v1.14.15-241002
        imagePullPolicy: IfNotPresent
        name: mount-cgroup
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
            - SYS_CHROOT
            - SYS_PTRACE
            drop:
            - ALL
          seLinuxOptions:
            level: s0
            type: spc_t
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /hostproc
          name: hostproc
        - mountPath: /hostbin
          name: cni-path
      - command:
        - sh
        - -ec
        - |
          cp /usr/bin/cilium-sysctlfix /hostbin/cilium-sysctlfix;
          nsenter --mount=/hostproc/1/ns/mnt "${BIN_PATH}/cilium-sysctlfix";
          rm /hostbin/cilium-sysctlfix
        env:
        - name: BIN_PATH
          value: /opt/cni/bin
        image: mcr.microsoft.com/containernetworking/cilium/cilium:v1.14.15-241002
        imagePullPolicy: IfNotPresent
        name: apply-sysctl-overwrites
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
            - SYS_CHROOT
            - SYS_PTRACE
            drop:
            - ALL
          seLinuxOptions:
            level: s0
            type: spc_t
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /hostproc
          name: hostproc
        - mountPath: /hostbin
          name: cni-path
      - args:
        - mount | grep "/sys/fs/bpf type bpf" || mount -t bpf bpf /sys/fs/bpf
        command:
        - /bin/bash
        - -c
        - --
        image: mcr.microsoft.com/containernetworking/cilium/cilium:v1.14.15-241002
        imagePullPolicy: IfNotPresent
        name: mount-bpf-fs
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /sys/fs/bpf
          mountPropagation: Bidirectional
          name: bpf-maps
      - command:
        - /init-container.sh
        env:
        - name: CILIUM_ALL_STATE
          valueFrom:
            configMapKeyRef:
              key: clean-cilium-state
              name: cilium-config
              optional: true
        - name: CILIUM_BPF_STATE
          valueFrom:
            configMapKeyRef:
              key: clean-cilium-bpf-state
              name: cilium-config
              optional: true
        image: mcr.microsoft.com/containernetworking/cilium/cilium:v1.14.15-241002
        imagePullPolicy: IfNotPresent
        name: clean-cilium-state
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
            - SYS_ADMIN
            - SYS_RESOURCE
            drop:
            - ALL
          seLinuxOptions:
            level: s0
            type: spc_t
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /sys/fs/bpf
          name: bpf-maps
        - mountPath: /run/cilium/cgroupv2
          mountPropagation: HostToContainer
          name: cilium-cgroup
        - mountPath: /var/run/cilium
          name: cilium-run
      - command:
        - bash
        - -cex
        - |
          export LD_LIBRARY_PATH=/host/lib/systemd:/host/usr/lib/aarch64-linux-gnu:/host/usr/lib/x86_64-linux-gnu
          export SYSTEMD_VERSION="$(/host/lib/systemd/systemd --version | head -n 1 | cut -d' ' -f2)"
          [[ $SYSTEMD_VERSION -ge 249 ]] && {
              mkdir -p /host/etc/systemd/networkd.conf.d
              echo -e "[Network]\nManageForeignRoutes=no\nManageForeignRoutingPolicyRules=no\n" \
                >/host/etc/systemd/networkd.conf.d/99-cilium-foreign-routes.conf
              chmod -R u+rwX,go+rX /host/etc/systemd/networkd.conf.d
            } || exit 0
        image: mcr.microsoft.com/cbl-mariner/base/core:2.0
        imagePullPolicy: IfNotPresent
        name: systemd-networkd-overrides
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/etc/systemd
          name: host-etc-systemd
        - mountPath: /host/lib/systemd
          name: host-lib-systemd
          readOnly: true
        - mountPath: /host/usr/lib
          name: host-usr-lib
          readOnly: true
      - name: block-wireserver
        image: mcr.microsoft.com/containernetworking/cilium/cilium:v1.14.15-241002
        imagePullPolicy: IfNotPresent
        command:
        - /bin/bash
        - -cx
        - |
          iptables -t mangle -C FORWARD -d 168.63.129.16 -p tcp --dport 80 -j DROP
          status=$?
          set -e
          if [ $status -eq 0 ]; then
            echo "Skip adding iptables as it already exists"
          else
            iptables -t mangle -I FORWARD -d 168.63.129.16 -p tcp --dport 80 -j DROP
          fi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            drop:
            - ALL
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cilium
      serviceAccountName: cilium
      terminationGracePeriodSeconds: 1
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /etc/systemd
          type: DirectoryOrCreate
        name: host-etc-systemd
      - hostPath:
          path: /lib/systemd
          type: DirectoryOrCreate
        name: host-lib-systemd
      - hostPath:
          path: /usr/lib
          type: DirectoryOrCreate
        name: host-usr-lib
      - hostPath:
          path: /var/run/cilium
          type: DirectoryOrCreate
        name: cilium-run
      - hostPath:
          path: /sys/fs/bpf
          type: DirectoryOrCreate
        name: bpf-maps
      - hostPath:
          path: /proc
          type: Directory
        name: hostproc
      - hostPath:
          path: /run/cilium/cgroupv2
          type: DirectoryOrCreate
        name: cilium-cgroup
      - hostPath:
          path: /opt/cni/bin
          type: DirectoryOrCreate
        name: cni-path
      - hostPath:
          path: /etc/cni/net.d
          type: DirectoryOrCreate
        name: etc-cni-netd
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
      - name: clustermesh-secrets
        secret:
          defaultMode: 256
          optional: true
          secretName: cilium-clustermesh
      - configMap:
          defaultMode: 420
          name: cilium-config
        name: cilium-config-path
      - hostPath:
          path: /proc/sys/net
          type: Directory
        name: host-proc-sys-net
      - hostPath:
          path: /proc/sys/kernel
          type: Directory
        name: host-proc-sys-kernel
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 2
    type: RollingUpdate

```
## Cilium Configmap
```
apiVersion: v1
data:
  agent-not-ready-taint-key: node.cilium.io/agent-not-ready
  arping-refresh-period: 30s
  auto-direct-node-routes: "false"
  bpf-lb-external-clusterip: "false"
  bpf-lb-map-max: "65536"
  bpf-lb-mode: snat
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  bpf-root: /sys/fs/bpf
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: "0"
  cluster-name: default
  debug: "false"
  disable-cnp-status-updates: "true"
  disable-endpoint-crd: "false"
  dnsproxy-enable-transparent-mode: "false"
  enable-auto-protect-node-port-range: "true"
  enable-bgp-control-plane: "false"
  enable-bpf-clock-probe: "true"
  enable-endpoint-health-checking: "false"
  enable-endpoint-routes: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-host-legacy-routing: "true"
  enable-hubble: "false"
  enable-ipv4: "true"
  enable-ipv4-masquerade: "false"
  enable-ipv6: "false"
  enable-ipv6-masquerade: "false"
  enable-k8s-terminating-endpoint: "true"
  enable-l2-neigh-discovery: "true"
  enable-l7-proxy: "false"
  enable-local-node-route: "false"
  enable-local-redirect-policy: "false"
  enable-metrics: "true"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-sctp: "false"
  enable-session-affinity: "true"
  enable-svc-source-range-check: "true"
  enable-vtep: "false"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  external-envoy-proxy: "false"
  identity-allocation-mode: crd
  install-iptables-rules: "false"
  install-no-conntrack-iptables-rules: "false"
  ipam: delegated-plugin
  k8s-client-burst: "10"
  k8s-client-qps: "5"
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: 0.0.0.0:10256
  local-router-ipv4: 169.254.23.0
  mesh-auth-enabled: "true"
  mesh-auth-gc-interval: 5m0s
  mesh-auth-queue-size: "1024"
  mesh-auth-rotated-identities-queue-size: "1024"
  metrics: +cilium_bpf_map_pressure
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  nodes-gc-interval: 5m0s
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: :9963
  preallocate-bpf-maps: "false"
  procfs: /host/proc
  prometheus-serve-addr: :9962
  proxy-connect-timeout: "2"
  proxy-max-connection-duration-seconds: "0"
  proxy-max-requests-per-connection: "0"
  remove-cilium-node-taints: "true"
  routing-mode: native
  set-cilium-is-up-condition: "true"
  set-cilium-node-taints: "true"
  sidecar-istio-proxy-image: cilium/istio_proxy
  synchronize-k8s-nodes: "true"
  tofqdns-dns-reject-response-code: refused
  tofqdns-enable-dns-compression: "true"
  tofqdns-endpoint-max-ip-per-hostname: "50"
  tofqdns-idle-connection-grace-period: 0s
  tofqdns-max-deferred-connection-deletes: "10000"
  tofqdns-min-ttl: "0"
  tofqdns-proxy-response-max-delay: 100ms
  unmanaged-pod-watcher-interval: "15"
  vtep-cidr: ""
  vtep-endpoint: ""
  vtep-mac: ""
  vtep-mask: ""
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"agent-not-ready-taint-key":"node.cilium.io/agent-not-ready","arping-refresh-period":"30s","auto-direct-node-routes":"false","bpf-lb-external-clusterip":"false","bpf-lb-map-max":"65536","bpf-lb-mode":"snat","bpf-map-dynamic-size-ratio":"0.0025","bpf-policy-map-max":"16384","bpf-root":"/sys/fs/bpf","cgroup-root":"/run/cilium/cgroupv2","cilium-endpoint-gc-interval":"5m0s","cluster-id":"0","cluster-name":"default","debug":"false","disable-cnp-status-updates":"true","disable-endpoint-crd":"false","dnsproxy-enable-transparent-mode":"false","enable-auto-protect-node-port-range":"true","enable-bgp-control-plane":"false","enable-bpf-clock-probe":"true","enable-endpoint-health-checking":"false","enable-endpoint-routes":"true","enable-health-check-nodeport":"true","enable-health-checking":"true","enable-host-legacy-routing":"true","enable-hubble":"false","enable-ipv4":"true","enable-ipv4-masquerade":"false","enable-ipv6":"false","enable-ipv6-masquerade":"false","enable-k8s-terminating-endpoint":"true","enable-l2-neigh-discovery":"true","enable-l7-proxy":"false","enable-local-node-route":"false","enable-local-redirect-policy":"false","enable-metrics":"true","enable-policy":"default","enable-remote-node-identity":"true","enable-sctp":"false","enable-session-affinity":"true","enable-svc-source-range-check":"true","enable-vtep":"false","enable-well-known-identities":"false","enable-xt-socket-fallback":"true","external-envoy-proxy":"false","identity-allocation-mode":"crd","install-iptables-rules":"false","install-no-conntrack-iptables-rules":"false","ipam":"delegated-plugin","k8s-client-burst":"10","k8s-client-qps":"5","kube-proxy-replacement":"strict","kube-proxy-replacement-healthz-bind-address":"0.0.0.0:10256","local-router-ipv4":"169.254.23.0","mesh-auth-enabled":"true","mesh-auth-gc-interval":"5m0s","mesh-auth-queue-size":"1024","mesh-auth-rotated-identities-queue-size":"1024","metrics":"+cilium_bpf_map_pressure","monitor-aggregation":"medium","monitor-aggregation-flags":"all","monitor-aggregation-interval":"5s","node-port-bind-protection":"true","nodes-gc-interval":"5m0s","operator-api-serve-addr":"127.0.0.1:9234","operator-prometheus-serve-addr":":9963","preallocate-bpf-maps":"false","procfs":"/host/proc","prometheus-serve-addr":":9962","proxy-connect-timeout":"2","proxy-max-connection-duration-seconds":"0","proxy-max-requests-per-connection":"0","remove-cilium-node-taints":"true","routing-mode":"native","set-cilium-is-up-condition":"true","set-cilium-node-taints":"true","sidecar-istio-proxy-image":"cilium/istio_proxy","synchronize-k8s-nodes":"true","tofqdns-dns-reject-response-code":"refused","tofqdns-enable-dns-compression":"true","tofqdns-endpoint-max-ip-per-hostname":"50","tofqdns-idle-connection-grace-period":"0s","tofqdns-max-deferred-connection-deletes":"10000","tofqdns-min-ttl":"0","tofqdns-proxy-response-max-delay":"100ms","unmanaged-pod-watcher-interval":"15","vtep-cidr":"","vtep-endpoint":"","vtep-mac":"","vtep-mask":""},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"cilium","meta.helm.sh/release-namespace":"kube-system"},"labels":{"app.kubernetes.io/managed-by":"Helm"},"name":"cilium-config","namespace":"kube-system"}}
    meta.helm.sh/release-name: cilium
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2024-11-23T00:07:41Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cilium-config
  namespace: kube-system
  resourceVersion: "4536557"
  uid: 4a22189c-e60a-4a63-b2dd-e712c973024b
```

### Cilium Version

```
$ cilium version
cilium-cli: v0.15.5 compiled with go1.20.4 on linux/amd64
cilium image (default): v1.14.0
cilium image (stable): v1.16.4
cilium image (running): unknown. Unable to obtain cilium version, no cilium pods found in namespace "kube-system"
```
Not sure why it says no cilium pods are found-- when I k get pods -A I do see cilium pods:
```
k exec -it cilium-9fmfn -n kube-system -- cilium status
Defaulted container "cilium-agent" out of: cilium-agent, install-cni-binaries (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), systemd-networkd-overrides (init), block-wireserver (init)
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.30 (v1.30.5) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    Strict   [eth0 10.10.0.4 (Direct Routing)]
Host firewall:           Disabled
CNI Chaining:            none
CNI Config file:         CNI configuration management disabled
Cilium:                  Ok   1.14.15 (v1.14.15-41a711dd4)
NodeMonitor:             Disabled
Cilium health daemon:    Ok
IPAM:                    IPv4: delegated to plugin,
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Host Routing:            Legacy
Masquerading:            Disabled
Controller Status:       39/39 healthy
Proxy Status:            No managed proxy redirect
Global Identity Range:   min 256, max 65535
Hubble:                  Disabled
Encryption:              Disabled
Cluster health:                     Probe disabled
```

### Kernel Version

```
Cilium:
root@aks-nodepool1-15288150-vmss000000:/# uname -a
Linux aks-nodepool1-15288150-vmss000000 5.15.0-1074-azure #83-Ubuntu SMP Wed Oct 2 18:14:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Azure:
root@aks-nodepool1-26026058-vmss000000:/# uname -a
Linux aks-nodepool1-26026058-vmss000000 5.15.0-1074-azure #83-Ubuntu SMP Wed Oct 2 18:14:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Cilium:
$ kubectl version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.30.5
Azure:
$ kubectl version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.30.6
```

### Sysdump

[cilium-sysdump-20241206-104350.zip](https://github.com/user-attachments/files/18042348/cilium-sysdump-20241206-104350.zip)

### Relevant log output

```shell

```

### Anything else?

If you need more trials, I have a couple more (and their corresponding flamegraphs), but they all show similar results.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
