### ISSUE TITLE
Cilium mTLS with SPIRE integration fails to find SPIRE admin socket on AWS EKS

### ISSUE THREAD

**Issue by prores-raypet** [cilium/cilium#36434]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

**Issue Description:**

We are experiencing an issue when deploying Cilium with mutual authentication (mTLS) backed by SPIRE on an AWS EKS cluster (version 1.31) running Cilium 1.6.4. While this setup works correctly in our local development environment (using k3d), it fails on the EKS cluster because the Cilium agent is unable to connect to the SPIRE server’s admin socket (`/run/spire/sockets/admin.sock`).

**What Happened:**

- We have configured Cilium and SPIRE to enable mTLS between workloads.
- On our local cluster (k3d-based), the Cilium agents successfully connect to the SPIRE server via `/run/spire/sockets/admin.sock`.
- On AWS EKS (v1.31) with Cilium 1.6.4, the Cilium agents consistently report an error:
  
  ```bash
  AuthCertificateProvider: Cannot connect to SPIRE server: "SPIRE admin socket (/run/spire/sockets/admin.sock) does not exist: stat /run/spire/sockets/admin.sock: no such file or directory"
  ```

- The SPIRE server and agents run within the `cilium-spire` namespace and appear to be configured similarly to our local setup. However, on EKS, the `/run/spire/sockets` directory remains empty inside the Cilium agent pods.

**What We Tried:**

- Verified that SPIRE server and agent configurations match the local environment.
- Ensured that the HostPath volumes for the SPIRE sockets are set up correctly (e.g., `hostPath: /var/run/spire-server/sockets` or `hostPath: /run/spire/sockets` with `DirectoryOrCreate`).
- Attempted to switch from Bottlerocket-based nodes to a different AMI in case of filesystem restrictions, but the issue persists.
- Redeployed from scratch multiple times, ensuring Cilium, SPIRE, and associated CRDs and ConfigMaps are aligned with documentation.
- Confirmed that on the local environment, the sockets appear correctly under `/run/spire/sockets`, and all Cilium agents can access them.
- On EKS, even after using a different base OS image (not Bottlerocket), the problem remains unchanged.

**Additional Context:**

- **Cilium version:** 1.6.4
- **Kubernetes/EKS version:** 1.31
- **Cloud Provider:** AWS EKS
- **Host OS:** Initially Bottlerocket (immutable filesystem), then switched to a different AMI without improvement.
- **Local Dev Env (working setup):** k3d cluster, identical Cilium and SPIRE Helm configurations.

**Questions:**

1. Are there known issues with Cilium’s SPIRE integration on EKS or with certain EKS AMIs?
2. Does Cilium require any specific filesystem permissions or SELinux/AppArmor configurations to create or access `/run/spire/sockets/admin.sock`?
3. Is there any recommended troubleshooting step or configuration setting we might be missing for the Cilium <-> SPIRE server communication on EKS?

### How can we reproduce the issue?

- **Cilium version:** 1.6.4
- **Kubernetes/EKS version:** 1.31
- **Cloud Provider:** AWS EKS
- **Host OS:** Initially Bottlerocket (immutable filesystem), then switched to a different AMI without improvement.
- **Helm deployment:**

```
envoyConfig:
  enabled: true
l7Proxy: true

kubeProxyReplacement: true

cni:
  chainingMode: "aws-cni"
  exclusive: false
  enableIPv4Masquerade: false

ipv4NativeRoutingCIDR: "REDACTED"

routingMode: "native"

endpointRoutes:
  enabled: true

envoy:
  enabled: true

tolerations:
  - operator: "Exists"

loadBalancer:
  l7:
    backend: envoy
hubble:
  enabled: true
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - http
  relay:
    enabled: true
  ui:
    enabled: true
authentication:
  mutual:
    spire:
      enabled: true
      install:
        enabled: true
        server:
          dataStorage:
            enabled: true
            size: 8Gi
            accessMode: ReadWriteOnce
            storageClass: gp3

```

### Cilium Version

- **Cilium version:** 1.6.4

### Kernel Version

-

### Kubernetes Version

- **Kubernetes/EKS version:** 1.31

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
