### ISSUE TITLE
Losing Network when node reboot

### ISSUE THREAD

**Issue by didlawowo** [cilium/cilium#36432]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

A bug happened!
when i reboot a node or restart rke2 server
i lose the dns connection / resolution

i have to rollout restart the daemonset to restore the situation (bug not found with 1.15)

### How can we reproduce the issue?

1 install with helm
2 reboot any node
3 see the logs for any pod to say connection timeout or refused with port 53

then restart cilium
situation resolve.

```
k8sServiceHost: "192.168.1.200"  # Différent de ""
k8sServicePort: "6443"  # Différent de ""

cluster:
  name: "rke2"  # Différent de "default"

image:
  tag: "v1.16.3"  # Différent de "v1.16.4"
  digest: "sha256:62d2a09bbef840a46099ac4c69421c90f84f28d018d479749049011329aa7f28"  # Différent

podAnnotations:
  ad.datadoghq.com/cilium-agent.logs: '[{"source": "cilium-agent", "service": "cilium-agent"}]'

rollOutCiliumPods: true  # Différent de false

encryption:
  enabled: true  # Différent de false
  type: wireguard  # Différent de ipsec

l2announcements:
  # Dans RKE2
  enabled: true
  leaseDuration: 15s
  leaseRenewDeadline: 5s
  leaseRetryPeriod: 2s

kubeProxyReplacement: "true"  # Différent de "false"

localRedirectPolicy: true  # Différent de false

logOptions:
  level: info
  format: json

bpf:
  masquerade: true  # Différent de null

envoy:
  image:
    tag: "v1.29.9-1728346947-0d05e48bfbb8c4737ec40d5781d970a550ed2bbd"  # Différent
    digest: "sha256:42614a44e508f70d03a04470df5f61e3cffd22462471a0be0544cf116f2c50ba"  # Différent

hubble:
  metrics:
    enabled:  # Différent de null
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - http
    enableOpenMetrics: true  # Différent de false
    dashboards:
      enabled: true  # Différent de false
      namespace: kube-monitoring  # Différent de null
  relay:
    enabled: true  # Différent de false
    rollOutPods: true  # Différent de false
    image:
      tag: "v1.16.3"  # Différent de "v1.16.4"
      digest: "sha256:feb60efd767e0e7863a94689f4a8db56a0acc7c1d2b307dee66422e3dc25a089"  # Différent
  ui:
    enabled: true  # Différent de false

operator:
  rollOutPods: true  # Différent de false
  image:
    tag: "v1.16.3"  # Différent de "v1.16.4"
    genericDigest: "sha256:6e2925ef47a1c76e183c48f95d4ce0d34a1e5e848252f910476c3e11ce1ec94b"  # Différent
    azureDigest: "sha256:2882aaf03c32525a99181b7c065b2bb19c03eba6626fc736aebe368d90791542"  # Différent
    awsDigest: "sha256:47f5abc5fa528472d3509c3199d7aab1e120833fb68df455e3b4476916385916"  # Différent
    alibabacloudDigest: "sha256:d80a785c0e807fc708264a3fcb19be404114f619fd756dd5214f4cad5a281898"  # Différent
  podAnnotations:
    ad.datadoghq.com/cilium-operator.logs: '[{"source": "cilium-operator", "service": "cilium-operator"}]'
  dashboards:
    enabled: true  # Différent de false
    namespace: kube-monitoring  # Différent de null

prometheus:
  enabled: true  # Différent de false

serviceNoBackendResponse: reject # Différent de "drop"
```

i'm also using poolLbIp and IPAM to provide Ip for loabbalaner on my cluster

```
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy-ray
spec:
  serviceSelector:
    matchLabels:
      app.kubernetes.io/name: traefik
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: DoesNotExist
  interfaces:
  - eth0
  - enp1s0
  - enp4s0
  - enp3s0
  - eno1
  externalIPs: true
  loadBalancerIPs: true
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: home-pool
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  blocks:
  - start: "192.168.1.240"
    stop: "192.168.1.246"
---
```

### Cilium Version

1.16.4

### Kernel Version

same problem on the three different kernel

### Kubernetes Version

1.31 rke2

### Regression

not append with previous version

### Relevant log output

```shell

```

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
