### ISSUE TITLE
ciliumpodippool can specify nodes or use multiple nodes

### ISSUE THREAD

**Issue by yunzck8s** [cilium/cilium#36480]
When I use ciliumpodippool to fix the IP of the pod, the node where the IP pool is located cannot be controlled. This is beyond expectations for me. I hope there is a field that can be configured.

Below is my configuration:

```
apiVersion: cilium.io/v2alpha1
kind: CiliumPodIPPool
metadata:
  name: mysql-pool
spec:
  ipv4:
    cidrs:
    - 10.0.0.100/30
    maskSize: 30
---
apiVersion: cilium.io/v2alpha1
kind: CiliumPodIPPool
metadata:
  name: redis-pool
spec:
  ipv4:
    cidrs:
    - 10.0.1.248/29
    maskSize: 29

```

I can see which node this ippool is in the operator log of cilium, and then I can specify the pod to be scheduled to the corresponding node, which is very bad.
