### ISSUE TITLE
Network broken when using an overlay network based on Wireguard, e.g. Netmaker

### ISSUE THREAD

**Issue by christian-schlichtherle** [cilium/cilium#36491]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

For almost three years, we are running an IoT project where some of the K8s nodes are placed at customer premises, typically behind a NAT gateway. Therefore, we need a VPN/SDN/overlay network to provide basic node-to-node connectivity even before we can install K8s, which is K3s in our case. Until recently, we have been using OpenVPN and Flannel successfully - it was an extremely robust solution.

However, OpenVPN has been slow and Flannel isn't the most advanced CNI plugin, so as part of a cloud migration from AWS to Hetzner, we also took the chance to swap out OpenVPN for initially Netbird and later Netmaker and Flannel for initially Calico, then Kube-Router and later Cilium. Unfortunately, this was the beginning of a weeks long journey of troubleshooting and analysing the root cause of frequent network outages which broke the entire cluster(s) several times a day.

Only recently we learned that these outages are caused be an unexpected interaction between Wireguard, which is used in both Netbird and Netmaker on one side and Cilium (but also Calico and Kube-Router) on the other side: One of Wireguard's strong points is its support for roaming - a peer can change its IP address anytime without breaking the tunnel. However, when Cilium is installed, the Wireguard endpoints would eventually change to pod IPs from the pod CIDR which is managed by Cilium. My understanding is that this should not happen thanks to masquerading the pod IPs when packets leave the node, but whatever I tried in the Cilium configuration it was always happening and when it happens it leads to the node-to-node connectivity being broken.

The only effective workaround I could figure out was to configure each device to use a "static endpoint" in our Netmaker dashboard which basically pins the endpoint IP to its public IP address and prevents it from picking up pod IPs. However, this inhibits roaming. Depending on the Internet provider's plan however, roaming may be required.

### How can we reproduce the issue?

Install at least two nodes which are connected via Netbird or Netmaker (Netbird may be easiest to start with, you can use their free cloud plan) and then install K3s with Cilium. This is `/etc/rancher/k3s/config.yaml` from the first K3s server:

```yaml
cluster-init: true
cluster-cidr: 10.192.0.0/12
cluster-dns: 10.208.0.10
disable:
- servicelb
- traefik
disable-cloud-controller: true
disable-kube-proxy: true
disable-network-policy: true
flannel-backend: none
kubelet-arg:
- cloud-provider=external
node-external-ip: ???.???.???.??? # redacted
node-ip: 172.24.0.10
node-taint:
- node-role.kubernetes.io/control-plane=:NoSchedule
service-cidr: 10.208.0.0/12
tls-san: 172.24.0.2
```

And this is `/var/lib/rancher/k3s/server/manifests/cilium.yaml` from the same server:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  bootstrap: true
  chart: cilium
  repo: https://helm.cilium.io
  targetNamespace: kube-system
  version: 1.16.4
  valuesContent: |
    MTU: 1420
    bpf:
      masquerade: true
      tproxy: true
    cluster:
      name: production
    devices: enp+ eth+ netmaker wlan+
    envoy:
      rolloutPods: true
      updateStrategy:
        rollingUpdate:
          maxUnavailable: 50%
    hubble:
      enabled: false
    ipMasqAgent:
      config:
        nonMasqueradeCIDRs:
          - 10.192.0.0/12
          - 10.208.0.0/12
        masqLinkLocal: true
      enabled: true
    ipam:
      mode: kubernetes
    k8s:
      requireIPv4PodCIDR: true
    k8sServiceHost: 172.24.0.2
    k8sServicePort: 6443
    kubeProxyReplacement: True
    operator:
      replicas: 1
      tolerations:
        - effect: NoSchedule
          key: node.kubernetes.io/not-ready
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
        - effect: NoSchedule
          key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
        - key: CriticalAddonsOnly
          operator: Exists
    rolloutCiliumPods: true
    updateStrategy:
      rollingUpdate:
          maxUnavailable: 50%
```

Again, this configuration is working if and only if Wireguard is configured to use a static endpoint, which you can configure using the Netmaker UI, but not the Netbird UI.

### Cilium Version

1.16.4. I tried 1.17.0-pre.3 too, and it made no difference.

### Kernel Version

On edge nodes: 5.15.137 from a vendor provided Ubuntu 24.04.1 LTS with a bunch of modules.
On cloud nodes 6.1.0-28-arm64 from a vanilla Debian 12 (bookworm) without additional modules.
All nodes are running ARM64 ISA.

### Kubernetes Version

1.31.3+k3s1

### Relevant log output

```shell
root@alfa-p0:/home/cilium# cilium-dbg status
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.31 (v1.31.3+k3s1) [linux/arm64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    True   [eth0    ???.???.???.??? 2a01:????:????:????::1 fe80::????:????:????:????, enp7s0   172.24.0.10 fe80::????:????:????:???? (Direct Routing), netmaker  100.66.0.4]
Host firewall:           Disabled
SRv6:                    Disabled
CNI Chaining:            none
CNI Config file:         successfully wrote CNI configuration file to /host/etc/cni/net.d/05-cilium.conflist
Cilium:                  Ok   1.16.4 (v1.16.4-03807242)
NodeMonitor:             Disabled
Cilium health daemon:    Ok   
IPAM:                    IPv4: 4/254 allocated from 10.192.0.0/24, 
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Routing:                 Network: Tunnel [vxlan]   Host: BPF
Attach Mode:             Legacy TC
Device Mode:             veth
Masquerading:            BPF (ip-masq-agent)   [eth0, enp7s0, netmaker]   10.192.0.0/24 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       29/29 healthy
Proxy Status:            OK, ip 10.192.0.103, 0 redirects active on ports 10000-20000, Envoy: external
Global Identity Range:   min 256, max 65535
Hubble:                  Disabled
Encryption:              Disabled          
Cluster health:          15/15 reachable   (2024-12-10T18:13:44Z)
Modules Health:          Stopped(0) Degraded(5) OK(53)
root@alfa-p0:/home/cilium# cat /host/etc/cni/net.d/05-cilium.conflist 

{
  "cniVersion": "0.3.1",
  "name": "cilium",
  "plugins": [
    {
       "type": "cilium-cni",
       "enable-debug": false,
       "log-file": "/var/run/cilium/cilium-cni.log"
    }
  ]
}root@alfa-p0:/home/cilium#
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
