### ISSUE TITLE
NetworkPolicy not work as expect with Gateway API

### ISSUE THREAD

**Issue by maodahua** [cilium/cilium#36509]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

We have a EKS cluster, the cluster we remove the Amazon VPC CNI already, so the Cilium is the only CNI for cluster. Also we enable the Gateway API for Cilium. 

There are a workload expose by the Gateway API, and we want to control the ingress traffic of pods. We want to keep the things simple. So try the NetworkPlicy first, instead of CiliumNetworkPolicy. The policy like below:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-gateway
  namespace: ns
spec:
  podSelector:
    matchLabels:
      app: abc
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gateway #This is the namespace which gateway(not include httproute) resources at.
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system #This is the namespace which Cilium at.
    - from:
        - podSelector: {}
    - from:
        - ipBlock:
            cidr: 10.100.16.0/22 #Allow from the VPC cidr, the host also running in the cidr, from logs I see deny so add this one.
```
The policy looks so OPEN, allow from the VPC cidr, from the [policy editor](https://editor.networkpolicy.io/) shows, it should works. But this is not work at all. Still can not access the pods from the domain name which bind to the gateway NLB.

I try some debug, login to the node which pods running cilium, using `hubble observe` to monitor the status. Can see some DROP logs:
```
10.50.17.136:33209 (ingress) <> ns/abc-5c4f9449d4-pwz4d:4000 (ID:406) policy-verdict:none INGRESS DENIED (TCP Flags: SYN)
10.50.17.136:33209 (ingress) <> ns/abc-5c4f9449d4-pwz4d:4000 (ID:406) Policy denied DROPPED (TCP Flags: SYN)
10.50.17.136:33209 (ingress) <> ns/abc-5c4f9449d4-pwz4d:4000 (ID:406) policy-verdict:none INGRESS DENIED (TCP Flags: SYN)
10.50.17.136:33209 (ingress) <> ns/abc-5c4f9449d4-pwz4d:4000 (ID:406) Policy denied DROPPED (TCP Flags: SYN)
```
And I try so many policies, both not work, except I open for all.

Till the end, what I can bypass this issue is use the CiliumNetworkPolicy below, and in the policy we allow from the entity `ingress`. 
```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-from-gateway
  namespace: ns
spec:
  endpointSelector:
    matchLabels:
      app: abc
  ingress:
    - fromEntities:
        - ingress
```
This is works, but I remember GKE DPv2 also using the Cilium as CNI, and they are not support the CiliumNetworkPolicy, just support in-tree NetworkPolicy by default. And from the Cilium logs I can see when I create the NetworkPolicy it will load as CiliumNetworkPolicy. So I think this might be a bug of Cilium. If not someone can let me know how to config the NetworkPolicy is also awesome.

### How can we reproduce the issue?

1. There is a EKS cluster, and replace the CNI to Cilium.
2. Enable the Gateway API feature of Cilium.
3. The workload expose by Gateway API with Amazon LBC.
4. Apply the policy below.
5. Access the workloads by your httproute host name.
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-gateway
  namespace: ns
spec:
  podSelector:
    matchLabels:
      app: abc
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gateway #This is the namespace which gateway(not include httproute) resources at.
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system #This is the namespace which Cilium at.
    - from:
        - podSelector: {}
    - from:
        - ipBlock:
            cidr: 10.100.16.0/22 #Allow from the VPC cidr, the host also running in the cidr, from logs I see deny so add this one.
```

### Cilium Version

cilium-cli: v0.16.20 compiled with go1.23.2 on darwin/amd64
cilium image (default): v1.16.3
cilium image (stable): v1.16.4
cilium image (running): 1.16.4

### Kernel Version

Linux ip-10-100-16-215.vpc.internal 6.1.115 #1 SMP Fri Nov 15 19:15:45 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

Client Version: v1.31.2-eks-94953ac
Kustomize Version: v5.4.2
Server Version: v1.30.6-eks-7f9249a

### Sysdump

I am asking approval for this, If really need, I will send later.

### Relevant log output

```shell

```

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
