### ISSUE TITLE
`toGroups` network policy feature only works with `eni.enabled`

### ISSUE THREAD

**Issue by sdickhoven** [cilium/cilium#36603]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

i added the following helm config to enable cilium operator in our eks cluster to interrogate the ec2 api.

```yaml
serviceAccounts:
  operator:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/eks-service=cilium@research1-east1-us-staging
```

iam permissions policy for the above iam role:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "ec2:Describe*",
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
```

when i tried to create a cilium network policy like this

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: my-app
spec:
  endpointSelector:
    matchLabels:
      k8s:app.kubernetes.io/name: my-app
  egress:
  - toGroups:
    - aws:
        securityGroupsIds:
        - sg-0f2146100a88d03c3
```

i got the following error:

```json
{
  "level": "error",
  "message": "Cannot create derivative rule. Installing deny-all rule.",
  "error": "Provider AWS is not registered",
  "subsys": "Groups"
}
```

we are using [irsa](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) here but static aws api credentials will give the same result.

### How can we reproduce the issue?

we are running cilium in [aws vpc cni chaining mode](https://docs.cilium.io/en/v1.16/installation/cni-chaining-aws-cni/#setting-up-a-cluster-on-aws):

```yaml
cni:
  chainingMode: aws-cni
  exclusive: false
enableIPv4Masquerade: false
routingMode: native
endpointRoutes:
  enabled: true
```

...which implies that we are **NOT** using

```yaml
eni:
  enabled: true
```

based on my research, the `toGroups` feature will only work if the `cilium/operator-aws` docker image is used and not if the `cilium/operator-generic` docker image is used.

however, the `cilium/operator-aws` docker image is currently only used if

```yaml
eni:
  enabled: true
```

...which we do not want/need.

just to ensure that my [irsa](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) / iam config is correct, i ran the following test workload using the `cilium-operator` service account in the kube-system namespace and everything worked as expected:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: testing-aws-pod
  namespace: kube-system
spec:
  containers:
  - name: aws-cli
    image: public.ecr.aws/aws-cli/aws-cli
    command:
    - sh
    - -c
    - sleep 3600
  serviceAccountName: cilium-operator
```

```
$ kubectl exec -ti -n kube-system testing-aws-pod -- aws ec2 describe-security-groups
...
```

so i know that the problem is **NOT** with anything iam / permission related.

i then removed the following config

```yaml
serviceAccounts:
  operator:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/eks-service=cilium@research1-east1-us-staging
```

and instead added this:

```yaml
eni:
  enabled: true
  iamRole: arn:aws:iam::111111111111:role/eks-service=cilium@research1-east1-us-staging
```

...which produced the following diff in `helm template` output:

```diff
536d535
>   auto-create-cilium-node-resource: "true"
567d565
>   ec2-api-endpoint: ""
606d603
>   eni-tags: '{}'
676d672
>   update-ec2-adapter-limit-via-api: "true"
13796c13792
>         - cilium-operator-aws
---
<         - cilium-operator-generic
13814c13810
>         image: 111111111111.dkr.ecr.us-east-1.amazonaws.com/quay/cilium/operator-aws:v1.16.4@sha256:355051bbebab73ea3067bb7f0c28cfd43b584d127570cb826f794f468e2d31be
---
<         image: 111111111111.dkr.ecr.us-east-1.amazonaws.com/quay/cilium/operator-generic:v1.16.4@sha256:c55a7cbe19fe0b6b28903a085334edb586a3201add9db56d2122c8485f7a51c5
```

however, this caused the cilium operator to crashloop because of

```json
{
  "level": "fatal",
  "msg": "cluster-pool allocator is not supported by this version of cilium-operator-aws",
  "subsys": "cilium-operator-aws"
}
```

i then added the following helm config to what i already had:

```yaml
ipam:
  mode: eni
```

at this point, the `toGroups` feature started working as expected and i got derived network policies in my cluster. 🎉 

however, i also got a lot of (expected) log spam along the lines of

```json
{
  "instanceID": "",
  "level": "warning",
  "msg": "Instance not found! Please delete corresponding ciliumnode if instance has already been deleted.",
  "name": "ip-192-0-2-194.ec2.internal",
  "subsys": "ipam"
}
{
  "level": "error",
  "msg": "BUG: Inconsistent CiliumNode state. The InstanceID is not known",
  "subsys": "eni"
}
```

so i was hoping that the helm chart and the "aws-flavored" cilium operator could be updated to support the `toGroups` feature for [aws vpc cni chaining mode](https://docs.cilium.io/en/v1.16/installation/cni-chaining-aws-cni/#setting-up-a-cluster-on-aws).

### Cilium Version

```
cilium-cli: v0.16.22 compiled with go1.23.4 on darwin/arm64
cilium image (default): v1.16.4
cilium image (stable): v1.16.4
cilium image (running): unknown. Unable to obtain cilium version. Reason: release: not found
```

not sure why the cilium cli is not reporting the running version. 🤷

maybe it's looking for the helm `Secret` / `ConfigMap` of the cilium install. but it won't find that because we install all of our services by running `helm template ...` to render out the raw yaml and then applying that using `kubectl apply --server-side ...`.

```
$ kubectl get ds -n kube-system cilium -o jsonpath="{.spec.template.spec.containers[0].image}"
111111111111.dkr.ecr.us-east-1.amazonaws.com/quay/cilium/cilium:v1.16.4@sha256:d55ec38938854133e06739b1af237932b9c4dd4e75e9b7b2ca3acc72540a44bf

$ kubectl get deploy -n kube-system cilium-operator -o jsonpath="{.spec.template.spec.containers[0].image}"
111111111111.dkr.ecr.us-east-1.amazonaws.com/quay/cilium/operator-generic:v1.16.4@sha256:c55a7cbe19fe0b6b28903a085334edb586a3201add9db56d2122c8485f7a51c5

$ kubectl get ds -n kube-system cilium-envoy -o jsonpath="{.spec.template.spec.containers[0].image}"
111111111111.dkr.ecr.us-east-1.amazonaws.com/quay/cilium/cilium-envoy:v1.30.7-1731393961-97edc2815e2c6a174d3d12e71731d54f5d32ea16@sha256:0287b36f70cfbdf54f894160082f4f94d1ee1fb10389f3a95baa6c8e448586ed
```

(using amazon ecr pull-through cache to pull images from `quay.io`... redacted account number)

### Kernel Version

6.1.109-118.189.amzn2023.aarch64
6.1.109-118.189.amzn2023.x86_64

### Kubernetes Version

```json
{
  "major": "1",
  "minor": "29+",
  "gitVersion": "v1.29.10-eks-7f9249a",
  "gitCommit": "d06fe5fa1c524ee5eb5d16bb9edc4dda6075f6c3",
  "gitTreeState": "clean",
  "buildDate": "2024-10-23T23:40:34Z",
  "goVersion": "go1.22.8",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

### Regression

unknown. i have only tried this with version 1.16.4

### Sysdump

File size too big: 25 MB are allowed, 25 MB were attempted to upload.

### Relevant log output

see above.

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
