### ISSUE TITLE
Strange behaviour using Argo Rollouts and Cilium Local Redirect Policy.

### ISSUE THREAD

**Issue by stanislawski0011** [cilium/cilium#36647]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.15.11 and lower than v1.16.0

### What happened?

We use Cilium (with kube-proxy replacement) as the CNI in our Kubernetes clusters, and we've been using Local Redirect Policies (LRPs) without issues.
Recently, we introduced Argo Rollouts with the NGINX Ingress Controller to enable canary deployments.
After enabling Argo Rollouts in environment with Cilium LRP's, we noticed multiple entries of the same service appearing in cilium service list. For example, with 8 rollout replicas, we see numerous identical backends listed under a single service entry. In a production scenario with 100 replicas, these entries can balloon up to around 3,000.
Example of 8 replicas:
```
875   10.254.250.54:5000     LocalRedirect   1 => 10.100.3.217:80 (active)      
                                             2 => 10.100.3.217:80 (active)      
                                             3 => 10.100.3.217:80 (active)      
                                             4 => 10.100.3.217:80 (active)      
                                             5 => 10.100.3.217:80 (active)      
                                             6 => 10.100.3.34:80 (active)       
                                             7 => 10.100.3.105:80 (active)      
                                             8 => 10.100.3.105:80 (active)      
                                             9 => 10.100.3.105:80 (active)      
                                             10 => 10.100.3.105:80 (active)     
                                             11 => 10.100.3.105:80 (active)     
                                             12 => 10.100.3.105:80 (active)     
                                             13 => 10.100.3.105:80 (active)     
                                             14 => 10.100.3.35:80 (active)      
                                             15 => 10.100.3.35:80 (active)      
                                             16 => 10.100.3.18:80 (active)      
                                             17 => 10.100.3.18:80 (active)      
                                             18 => 10.100.3.18:80 (active)      
                                             19 => 10.100.3.18:80 (active)      
                                             20 => 10.100.3.11:80 (active)      
                                             21 => 10.100.3.156:80 (active)
```

The Cilium logs show repeated errors like: `Unable to delete service entry from BPF map`.

Why did we look into this? When we attempted to enable rollouts in production, at the 75% canary stage, traffic distribution became uneven. By the final canary step (when the canary environment transitions to the stable environment), we started seeing 504 error codes from NGINX on approximately 40% of requests. It appears NGINX tried to route traffic to endpoints that no longer existed. Restarting Cilium resolved the issue. We also saw that the "Unable to delete service entry from BPF map errors". That production history with 504 error i cannot reproduce in staging environment.

Our cilium settings:
```  
  agent-not-ready-taint-key: node.cilium.io/agent-not-ready
  arping-refresh-period: 30s
  auto-direct-node-routes: "false"
  bpf-lb-external-clusterip: "false"
  bpf-lb-map-max: "65536"
  bpf-lb-sock: "false"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  bpf-root: /sys/fs/bpf
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: "0"
  cluster-name: cluster
  cluster-pool-ipv4-cidr: 10.100.0.0/16
  cluster-pool-ipv4-mask-size: "26"
  custom-cni-conf: "false"
  debug: "false"
  disable-cnp-status-updates: "true"
  disable-endpoint-crd: "false"
  enable-auto-protect-node-port-range: "true"
  enable-bgp-control-plane: "false"
  enable-bpf-clock-probe: "true"
  enable-endpoint-health-checking: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv4-masquerade: "true"
  enable-ipv6: "false"
  enable-ipv6-masquerade: "true"
  enable-k8s-terminating-endpoint: "true"
  enable-l2-neigh-discovery: "true"
  enable-l7-proxy: "true"
  enable-local-redirect-policy: "true"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-svc-source-range-check: "true"
  enable-vtep: "false"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  hubble-disable-tls: "false"
  hubble-listen-address: :4244
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  install-no-conntrack-iptables-rules: "false"
  ipam: cluster-pool
  k8s-api-server: https://10.83.143.9:6443
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: ""
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  nodes-gc-interval: 5m0s
  operator-api-serve-addr: 127.0.0.1:9234
  preallocate-bpf-maps: "false"
  procfs: /host/proc
  remove-cilium-node-taints: "true"
  set-cilium-is-up-condition: "true"
  sidecar-istio-proxy-image: cilium/istio_proxy
  skip-cnp-status-startup-clean: "false"
  synchronize-k8s-nodes: "true"
  tofqdns-dns-reject-response-code: refused
  tofqdns-enable-dns-compression: "true"
  tofqdns-endpoint-max-ip-per-hostname: "50"
  tofqdns-idle-connection-grace-period: 0s
  tofqdns-max-deferred-connection-deletes: "10000"
  tofqdns-min-ttl: "3600"
  tofqdns-proxy-response-max-delay: 100ms
  tunnel: vxlan
  unmanaged-pod-watcher-interval: "15"
  vtep-cidr: ""
  vtep-endpoint: ""
  vtep-mac: ""
  vtep-mask: ""
```

### How can we reproduce the issue?

1. Cluster with cilium installed from helm, with values:
```
ipv6:
    enabled: False
  rbac:
    create: true
  priorityClassName: system-node-critical
  cluster:
    # -- Name of the cluster. Only required for Cluster Mesh.
    name: default
    # -- (int) Unique ID of the cluster. Must be unique across all connected
    # clusters and in the range of 1 to 255. Only required for Cluster Mesh,
    # may be 0 if Cluster Mesh is not used.
    id: 0

  hubble:
    enabled: False
    relay:
      enabled: False
    ui:
      enabled: False
   
  ipam:
    operator:
      clusterPoolIPv4PodCIDR: "10.100.0.0/16"
      clusterPoolIPv6PodCIDR: "fd00:10:100::/112"
      clusterPoolIPv6MaskSize: 120

    
  devices: "ens+ eth+"
  bpf:
    masquerade: False
  kubeProxyReplacement: "strict"

  ipMasqAgent:
    enabled: False

```
2. Install argo rollouts: https://artifacthub.io/packages/helm/argo/argo-rollouts
3. kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-rollouts/master/docs/getting-started/nginx/rollout.yaml and scale replicas.
4. kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-rollouts/master/docs/getting-started/nginx/services.yaml
5. kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-rollouts/master/docs/getting-started/nginx/ingress.yaml
6. Add Cilium LRP like:
```
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  labels:
    name: rollouts-demo-canary
  name: rollouts-demo-canary
spec:
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        app: rollouts-demo
    toPorts:
    - port: "80"
      protocol: TCP
  redirectFrontend:
    serviceMatcher:
      namespace: default
      serviceName: rollouts-demo-canary
```
```
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  labels:
    name: rollouts-demo-stable
  name: rollouts-demo-stable
spec:
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        app: rollouts-demo
    toPorts:
      - port: "80"
        protocol: TCP
  redirectFrontend:
    serviceMatcher:
      namespace: default
      serviceName: rollouts-demo-stable
```
7. Change image in Rollout object to start canary.

### Cilium Version

To test if bug is depends on cilium version, on test environment I installed different versions, with highest:

```
cilium-cli: v0.13.0 compiled with go1.20 on darwin/amd64
cilium image (default): v1.13.0
cilium image (stable): v1.16.4
cilium image (running): v1.16.0
```

On production we have:
```
cilium-cli: v0.13.0 compiled with go1.20 on darwin/amd64
cilium image (default): v1.13.0
cilium image (stable): v1.16.4
cilium image (running): v1.12.5
```

### Kernel Version

5.17.4-200.fc35.x86_64

### Kubernetes Version

Server Version: v1.23.16

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
