### ISSUE TITLE
[1.16 on GKE] Upgrade to 1.16.x breaks `prometheus-to-sd` in kube-system containers

### ISSUE THREAD

**Issue by Pionerd** [cilium/cilium#36685]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

Since 1.16 was released, we have not been able to get this running correctly on GKE. After upgrading to 1.16.x (verified with the latest 1.16.5), the `prometheus-to-sd` containers start failing in the `kube-dns` and `event-exporter` pods in the `kube-system` namespace. 

When I was investigating this issue earlier, I noticed errors about not being able to get to GKE's metadata server, but I can't find those exact logs in the current situation. The errors in those two pods don't mean much to me (see below). 

What is interesting however is that the `cilium connectivity test` fails a test on the LocalRedirectPolicy. 

### How can we reproduce the issue?

Happens on upgrade from 1.15.x to 1.16.x. Tested multiple scenarios with these exact values. 

Please be aware that we (successfully, until now) create the LocalRedirectPolicies as described here: https://github.com/cilium/cilium/issues/28655

Relevant values:
```
# # TODO: remove `envoy.enabled` when setting upgradeCompatibility to 1.16
upgradeCompatibility: "1.15"

envoy:
  enabled: true
envoyConfig:
  enabled: true

# TODO: remove this
# Pending full kube-proxy deletion we need to set this flag to prevent overlapping health check ports
nodePort:
  enableHealthCheck: false

nodeinit:
  enabled: true
  reconfigureKubelet: true
  removeCbrBridge: true
  restartPods: true
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
cni:
  binPath: "/home/kubernetes/bin"
gke:
  enabled: true
ipam:
  mode: "kubernetes"
ipv4NativeRoutingCIDR: ${tf_ip_range_pods}

kubeProxyReplacement: true
k8sServiceHost: ${tf_module_gke_endpoint}
k8sServicePort: 443

# Pending:
# - https://github.com/cilium/cilium/issues/28821
# - https://github.com/cilium/cilium/issues/28820
# Should resolve an issue where NGINX pods (including Ingress and Grafana Loki Gateway) cannot handle DNS pods restarts.
socketLB:
  hostNamespaceOnly: true
  terminatePodConnections: true

# Performance improvements
bpf:
  masquerade: true
bandwidthManager:
  enabled: true
  bbr: true
enableIPv4BIGTCP: true

# BPF Routing combined with Workload Identity requires this beta functionality
# Please see https://github.com/cilium/cilium/issues/28655
localRedirectPolicy: true

# Related:
# - https://github.com/cilium/cilium/issues/19241
# - https://docs.cilium.io/en/stable/installation/taints/
agentNotReadyTaintKey: ignore-taint.cluster-autoscaler.kubernetes.io/cilium-agent-not-ready
```

### Cilium Version

1.16.x

### Kernel Version

Linux gke-dev-pio-gke-blue-spot-27f718d2-0rcm 6.6.44+ #1 SMP PREEMPT_DYNAMIC Sat Oct 19 09:33:41 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

GKE 1.30/1.31

### Regression

1.15.x

### Sysdump

[cilium-sysdump-20241218-112531.zip](https://github.com/user-attachments/files/18179632/cilium-sysdump-20241218-112531.zip)

### Relevant log output

```shell
# Cilium connectivity test results are flaky because of the crash of the DNS pods, but this was a significant result

❯ cilium connectivity test
............
[=] [cilium-test] Skipping test [pod-to-controlplane-host] [74/82] (skipped by condition)
[=] [cilium-test] Skipping test [pod-to-k8s-on-controlplane] [75/82] (skipped by condition)
[=] [cilium-test] Skipping test [pod-to-controlplane-host-cidr] [76/82] (skipped by condition)
[=] [cilium-test] Skipping test [pod-to-k8s-on-controlplane-cidr] [77/82] (skipped by condition)
[=] [cilium-test] Test [local-redirect-policy] [78/82]

  ℹ  📜 Applying CiliumLocalRedirectPolicy 'lrp-address-matcher' to namespace 'cilium-test'..
  ℹ  📜 Applying CiliumLocalRedirectPolicy 'lrp-address-matcher-skip-redirect-from-backend' to namespace 'cilium-test'..
  [-] Scenario [local-redirect-policy/lrp]
  🟥 Failed to ensure local redirect BPF entries: %!!(MISSING)w(MISSING) timeout while waiting for condition, last error: frontend [169.254.169.254:80] backend [10.120.64.92] mapping not found in BPF LB map [cilium-qt6zf] map[0.0.0.0:30431:[0.0.0.0:0 (28) (0) [NodePort, non-routable]  10.120.65.32:8080 (28) (1)] 0.0.0.0:30737:[0.0.0.0:0 (17) (0) [NodePort, non-routable]  10.120.65.125:8080 (17) (1)] 0.0.0.0:32559:[0.0.0.0:0 (25) (0) [NodePort, non-routable]  10.120.64.186:8080 (25) (1)] 0.0.0.0:4000:[10.120.64.186:8080 (30) (1) 0.0.0.0:0 (30) (0) [HostPort, non-routable] ] 10.120.4.50:30431:[10.120.65.32:8080 (27) (1) 0.0.0.0:0 (27) (0) [NodePort] ] 10.120.4.50:30737:[0.0.0.0:0 (16) (0) [NodePort]  10.120.65.125:8080 (16) (1)] 10.120.4.50:32559:[10.120.64.186:8080 (24) (1) 0.0.0.0:0 (24) (0) [NodePort] ] 10.120.4.50:4000:[0.0.0.0:0 (29) (0) [HostPort]  10.120.64.186:8080 (29) (1)] 10.121.0.10:53:[10.120.65.167:53 (21) (1)
0.0.0.0:0 (21) (0) [ClusterIP, non-routable] ] 10.121.0.1:443:[10.120.0.2:443 (14) (1) 0.0.0.0:0 (14) (0) [ClusterIP, non-routable] ] 10.121.1.197:8081:[0.0.0.0:0 (9) (0) [ClusterIP, non-routable]  10.120.65.184:8081 (9) (1)] 10.121.1.31:5556:[0.0.0.0:0 (7) (0) [ClusterIP, non-routable]  10.120.65.145:5556 (7) (1)] 10.121.1.31:5557:[10.120.65.145:5557 (6) (1) 0.0.0.0:0 (6) (0) [ClusterIP, non-routable] ] 10.121.1.37:6379:[0.0.0.0:0 (8) (0) [ClusterIP, non-routable]  10.120.65.71:6379 (8) (1)] 10.121.1.56:80:[0.0.0.0:0 (15) (0) [ClusterIP, non-routable]  10.120.65.125:8080 (15) (1)] 10.121.10.57:443:[0.0.0.0:0 (18) (0) [ClusterIP, InternalLocal, non-routable]  10.120.4.50:4244 (18) (1)] 10.121.11.193:443:[10.120.65.221:8080 (12) (1) 0.0.0.0:0 (12) (0) [ClusterIP, non-routable] ] 10.121.11.193:80:[0.0.0.0:0 (11) (0) [ClusterIP, non-routable]  10.120.65.221:8080 (11) (1)] 10.121.12.114:8084:[0.0.0.0:0 (10) (0) [ClusterIP, non-routable]  10.120.65.184:8084 (10) (1)] 10.121.13.38:8080:[0.0.0.0:0 (23) (0) [ClusterIP, non-routable]  10.120.64.186:8080 (23) (1)] 10.121.2.121:80:[0.0.0.0:0 (20) (0) [ClusterIP, non-routable]  10.120.65.31:8081 (20) (1)] 10.121.3.240:8082:[0.0.0.0:0 (1) (0) [ClusterIP, non-routable]  10.120.65.106:8082 (1) (1)] 10.121.3.34:8083:[10.120.65.221:8083 (13) (1) 0.0.0.0:0 (13) (0) [ClusterIP, non-routable] ] 10.121.5.132:8080:[0.0.0.0:0 (26) (0) [ClusterIP, non-routable]  10.120.65.32:8080 (26) (1)] 10.121.6.116:443:[10.120.65.231:10250 (22) (1) 0.0.0.0:0 (22) (0) [ClusterIP, non-routable] ] 10.121.7.161:80:[10.120.65.101:4245 (19) (1) 0.0.0.0:0 (19) (0) [ClusterIP, non-routable] ] 10.121.8.203:7000:[0.0.0.0:0 (4) (0) [ClusterIP, non-routable]  10.120.65.141:7000 (4) (1)] 10.121.9.156:8080:[10.120.65.141:8080 (5) (1) 0.0.0.0:0 (5) (0) [ClusterIP, non-routable] ] 169.254.169.254:80:[10.120.4.50:988 (2) (1) 0.0.0.0:0 (2) (0)
[LocalRedirect] ] 169.254.169.254:8080:[10.120.4.50:987 (3) (1) 0.0.0.0:0 (3) (0) [LocalRedirect] ] 169.254.169.255:80:[10.120.64.92:8080 (31) (1) 0.0.0.0:0 (31) (0) [LocalRedirect] ]]
  ℹ  📜 Deleting CiliumLocalRedirectPolicy 'lrp-address-matcher' from namespace 'cilium-test'..
  ℹ  📜 Deleting CiliumLocalRedirectPolicy 'lrp-address-matcher-skip-redirect-from-backend' from namespace 'cilium-test'..
[=] [cilium-test] Test [pod-to-pod-no-frag] [79/82]
.
[=] [cilium-test] Skipping test [host-firewall-ingress] [80/82] (skipped by condition)
[=] [cilium-test] Skipping test [host-firewall-egress] [81/82] (skipped by condition)
[=] [cilium-test] Test [check-log-errors] [82/82]
.........................
📋 Test Report [cilium-test]
❌ 1/49 tests failed (0/480 actions), 33 tests skipped, 0 scenarios skipped:
Test [local-redirect-policy]:

[cilium-test] 1 tests failed



=====================================
kube-dns / prometheus-to-sd container
=====================================
goroutine 34 [GC worker (idle)]:
runtime.gopark(0x2351fd5392f?, 0x4096cb?, 0x0?, 0x0?, 0x0?)
    /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000065750 sp=0xc000065730 pc=0x43dc2e
runtime.gcBgMarkWorker()
    /usr/local/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000657e0 sp=0xc000065750 pc=0x41eda5
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000657e8 sp=0xc0000657e0 pc=0x470a21
created by runtime.gcBgMarkStartWorkers in goroutine 1
    /usr/local/go/src/runtime/mgc.go:1219 +0x1c

goroutine 8 [GC worker (idle)]:
runtime.gopark(0x2351fd0e62d?, 0x0?, 0x0?, 0x0?, 0x0?)
    /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000065f50 sp=0xc000065f30 pc=0x43dc2e
runtime.gcBgMarkWorker()
    /usr/local/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc000065fe0 sp=0xc000065f50 pc=0x41eda5
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000065fe8 sp=0xc000065fe0 pc=0x470a21
created by runtime.gcBgMarkStartWorkers in goroutine 1
    /usr/local/go/src/runtime/mgc.go:1219 +0x1c

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x2351fd87f5c?, 0x0?, 0x0?, 0x0?, 0x0?)
    /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00005e750 sp=0xc00005e730 pc=0x43dc2e
runtime.gcBgMarkWorker()
    /usr/local/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc00005e7e0 sp=0xc00005e750 pc=0x41eda5
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005e7e8 sp=0xc00005e7e0 pc=0x470a21
created by runtime.gcBgMarkStartWorkers in goroutine 1
    /usr/local/go/src/runtime/mgc.go:1219 +0x1c

goroutine 36 [GC worker (idle)]:
runtime.gopark(0x2351fd825d8?, 0x0?, 0x0?, 0x0?, 0x0?)
    /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00005ef50 sp=0xc00005ef30 pc=0x43dc2e
runtime.gcBgMarkWorker()
    /usr/local/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc00005efe0 sp=0xc00005ef50 pc=0x41eda5
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005efe8 sp=0xc00005efe0 pc=0x470a21
created by runtime.gcBgMarkStartWorkers in goroutine 1
    /usr/local/go/src/runtime/mgc.go:1219 +0x1c

goroutine 50 [select, locked to thread]:
runtime.gopark(0xc0002d17a8?, 0x2?, 0xc9?, 0xde?, 0xc0002d17a4?)
    /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc0002d1638 sp=0xc0002d1618 pc=0x43dc2e
runtime.selectgo(0xc0002d17a8, 0xc0002d17a0, 0x0?, 0x0, 0x1?, 0x1)
    /usr/local/go/src/runtime/select.go:327 +0x725 fp=0xc0002d1758 sp=0xc0002d1638 pc=0x44e065
runtime.ensureSigM.func1()
    /usr/local/go/src/runtime/signal_unix.go:1014 +0x19f fp=0xc0002d17e0 sp=0xc0002d1758 pc=0x46787f
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0002d17e8 sp=0xc0002d17e0 pc=0x470a21
created by runtime.ensureSigM in goroutine 1
    /usr/local/go/src/runtime/signal_unix.go:997 +0xc8

goroutine 12 [syscall]:
runtime.notetsleepg(0x0?, 0x0?)
    /usr/local/go/src/runtime/lock_futex.go:236 +0x29 fp=0xc0002d1fa0 sp=0xc0002d1f68 pc=0x40f0a9
os/signal.signal_recv()
    /usr/local/go/src/runtime/sigqueue.go:152 +0x29 fp=0xc0002d1fc0 sp=0xc0002d1fa0 pc=0x46d169
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:23 +0x13 fp=0xc0002d1fe0 sp=0xc0002d1fc0 pc=0x76a713
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0002d1fe8 sp=0xc0002d1fe0 pc=0x470a21
created by os/signal.Notify.func1.1 in goroutine 1
    /usr/local/go/src/os/signal/signal.go:151 +0x1f

goroutine 13 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
    /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00005f6d0 sp=0xc00005f6b0 pc=0x43dc2e
runtime.chanrecv(0xc00007c120, 0x0, 0x1)
    /usr/local/go/src/runtime/chan.go:583 +0x3cd fp=0xc00005f748 sp=0xc00005f6d0 pc=0x409bed
runtime.chanrecv1(0x0?, 0x0?)
    /usr/local/go/src/runtime/chan.go:442 +0x12 fp=0xc00005f770 sp=0xc00005f748 pc=0x4097f2
main.main.func1()
    /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/prometheus-to-sd/main.go:112 +0x1d fp=0xc00005f7e0 sp=0xc00005f770 pc=0x15d5e5d
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005f7e8 sp=0xc00005f7e0 pc=0x470a21
created by main.main in goroutine 1
    /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/prometheus-to-sd/main.go:111 +0x205

rax    0x0
rbx    0x1
rcx    0x40720e
rdx    0x6
rdi    0x1
rsi    0xb
rbp    0xc000547ce0
rsp    0xc000547ca0
r8     0x0
r9     0x0
r10    0x0
r11    0x212
r12    0x0
r13    0xafa8a655c
r14    0xc0000061a0
r15    0x9
rip    0x40720e
rflags 0x212
cs     0x33
fs     0x0
gs     0x0
stream closed EOF for kube-system/kube-dns-7c846b4c7f-jm9hs (prometheus-to-sd)
```

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
