### ISSUE TITLE
With Cilium Network Policy Client IP is lost

### ISSUE THREAD

**Issue by rushi47** [cilium/cilium#36718]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

TLDR:  After applying cilium ingress network policy client ip gets lost.

Below is scenario, explained in detail:

Inside cluster during pod to pod communication, there are two pods running on different nodes. Let’s name them Pod - x on node - x and pod - y running on node - y. Pod - Y has ingress network policy attached, which allow only request on port and specific http route.

<details>
<summary> Example network policy attached on pod-y </summary>

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: ingress-test-ciliumnetworkpolicy
  namespace: rushi-test-ns
spec:
  endpointSelector:
    matchLabels:
      [app.kubernetes.io/instance:](http://app.kubernetes.io/instance:) rushi-test
  ingress:
toPorts:
ports:
port: "8000"
        protocol: TCP
      rules:
        http:
method: GET
          path: /bin/
```

</details>

When this network policy is applied or any policy, we noticed that Pod - X ip is masqueraded with Node - Y’s ip before request reaches Pod - Y.  Without network policy, Pod-X ip is visible in Pod-Y. Tested this on cilium + vpc cni (chaining mode) and also on native routing mode in both cases we noticed similar behaviour. 

Can understand that, as cilium agent is in charge applying of network policies,  it applies the network policies on node level and does NAT. But is there way to preserve the Client IP during pod communication, I was assuming network policy behavior should be transparent, at least during pod to pod communication inside cluster.

### How can we reproduce the issue?

• Create two pods on separate nodes

```
k run -i --tty --rm utils-2 --image=praqma/network-multitool --overrides='{"apiVersion": "v1", "kind": "Pod", "spec": {"nodeSelector": { "kubernetes.io/hostname": "node-name" }}}' --namespace=rushi-test-ns -- /bin/bash
```

• Make request from pod without network policy, you will see ip address of client.

• Apply network policy on any pod

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: ingress-test-ciliumnetworkpolicy
  namespace: rushi-test-ns
spec:
  endpointSelector:
    matchLabels:
      [app.kubernetes.io/instance:](http://app.kubernetes.io/instance:) rushi-test
  ingress:
toPorts:
ports:
port: "8000"
        protocol: TCP
      rules:
        http:
method: GET
          path: /bin/
```

* Make request again from pod without network policy to pod with network policy, you will see destination pod's node ip address

### Cilium Version

```
cilium version
Client: 1.16.1 68579055 2024-08-13T13:29:59Z go version go1.23.1 linux/amd64
Daemon: 1.16.1 68579055 2024-08-13T13:29:59Z go version go1.23.1 linux/amd64
```

### Kernel Version

```
uname -a
Linux ip-XXXXXX.us-west-2.compute.internal 5.XXXXX.amzn2.aarch64 #1 SMP Wed Oct 23 17:17:31 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

### Kubernetes Version

```
Client Version: v1.25.9
Kustomize Version: v4.5.7
Server Version: v1.30.6-eks-7f9249a
```

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
