### ISSUE TITLE
CoreDNS external queries fail after upgrading to 1.16.5

### ISSUE THREAD

**Issue by kenlasko** [cilium/cilium#36737]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

After upgrading to 1.16.5, CoreDNS pods stop forwarding DNS queries to the next hop DNS server.  Any DNS queries to the outside world fail, and cause various issues in my cluster. Downgrading back to 1.16.4 immediately resolves the issue. 

This occurred on a single-node cluster operating in Oracle Cloud. Another bare-metal 6-node cluster upgraded without issue. The main difference between the two are that the Oracle cluster is running Cilium Envoy, while the bare-metal cluster is not.

I see constant errors in my CoreDNS pods like:
```
[INFO] 10.244.0.38:41485 - 15314 "A IN hooks.slack.com. udp 33 false 512" - - 0 2.000258485s
[ERROR] plugin/errors: 2 hooks.slack.com. A: read udp 10.244.0.27:54684->169.254.116.108:53: i/o timeout
[INFO] 10.244.0.38:41485 - 48588 "AAAA IN hooks.slack.com. udp 33 false 512" - - 0 2.000263845s
[ERROR] plugin/errors: 2 hooks.slack.com. AAAA: read udp 10.244.0.27:34832->169.254.116.108:53: i/o timeout
[INFO] 10.244.0.38:41485 - 15314 "A IN hooks.slack.com. udp 33 false 512" - - 0 2.001438855s  
```

### How can we reproduce the issue?

1. Install Cilium with Helm using this `values.yaml`
```
rollOutCiliumPods: true
routingMode: tunnel
tunnelProtocol: geneve
ipv4NativeRoutingCIDR: 10.0.0.0/9
bpf:
  hostRouting: true
  masquerade: true
ipam:
  mode: kubernetes
  operator:
    clusterPoolIPv4PodCIDRList: 
    - 10.42.0.0/16
cluster:
  name: cloud
  id: 1
loadBalancer:
  mode: dsr
  dsrDispatch: geneve
l2announcements:
  enabled: true
  leaseDuration: 6s
  leaseRenewDeadline: 2s
  leaseRetryPeriod: 200ms
operator:
  replicas: 1
envoy:
  enabled: true
  rollOutPods: true
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy:
      - NET_BIND_SERVICE
      - NET_ADMIN
      - SYS_ADMIN
externalIPs:
  enabled: true
extraEnv:
- name: TZ
  value: "America/Toronto"
kubeProxyReplacement: true
k8sServiceHost: localhost
k8sServicePort: 7445
securityContext:
  capabilities:
    ciliumAgent: 
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW 
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState: 
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
resources:
  requests:
    cpu: 100m
    memory: 250Mi
  limits:
    cpu: 400m
    memory: 400Mi

hubble:
  peerService:
    clusterDomain: cluster.local
  relay:
    enabled: true
    resources:
      requests:
        cpu: 15m
        memory: 25Mi
      limits:
        cpu: 50m
        memory: 50Mi   
  ui:
    enabled: true

gatewayAPI:
  enabled: true
  hostNetwork:
    enabled: true
  secretsNamespace:
    create: false
    name: cilium
    sync: true
```

### Cilium Version

1.16.5

### Kernel Version

Talos OS v1.9.0  Kernel version: 6.12.5

### Kubernetes Version

1.32.0

### Regression

1.16.4

### Sysdump

[cilium-sysdump-20241219-130409.zip](https://github.com/user-attachments/files/18201776/cilium-sysdump-20241219-130409.zip)

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by reyvonger** [comment]
I encountered the same issue on talos.dev

**Comment by sfackler** [comment]
I'm also seeing the same issue on a Talos node. The Talos dns-resolve-cache logs show that it is receiving the requests and resolving them successfully, so it seems like the response just isn't making it back to the CoreDNS pod.

**Comment by kenlasko** [comment]
I have two clusters with fairly similar configs. A single-node Oracle server, and a 6-node bare-metal cluster. Both my clusters use Talos. Only my single-node "cluster" is seeing the issue. The only thing I see different between the two Cilium-wise is Envoy is running on Oracle while my bare-metal one is not.

**Comment by kenlasko** [comment]
I found the source of the issue. Turns out there's another difference between my Oracle and bare-metal clusters: forwardKubeDNSToHost](https://www.talos.dev/v1.9/talos-guides/network/host-dns/#forwarding-kube-dns-to-host-dns). This feature is enabled by default on clusters created with Talos 1.8.0 or later. My Oracle cluster was created post 1.8.0 and included this. My bare-metal cluster was created before 1.8.0 and does not have this.

I patched my Oracle cluster with the following and after restarting the CoreDNS pods, DNS resolution started working without issue.
```
machine:
  features:
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: false
```

If you other fine fellows have the same results, I will bring this up with the Talos folks.
