### ISSUE TITLE
Presumed spurious packet drop test failures

### ISSUE THREAD

**Issue by dhess** [cilium/cilium#36771]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.5 and lower than v1.17.0

### What happened?

`cilium connectivity test` is reporting dropped packets during the `no-unexpected-packet-drops` test:

```
  [-] Scenario [no-unexpected-packet-drops/no-unexpected-packet-drops]
[=] [cilium-test-1] Test [no-unexpected-packet-drops] [1/108]
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/worker-b]
.  ❌ Found unexpected packet drops:
{
  "labels": {
    "direction": "EGRESS",
    "reason": "FIB lookup failed"
  },
  "name": "cilium_drop_count_total",
  "value": 322
}
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/worker-c]
.  ❌ Found unexpected packet drops:
{
  "labels": {
    "direction": "EGRESS",
    "reason": "FIB lookup failed"
  },
  "name": "cilium_drop_count_total",
  "value": 20
}
{
  "labels": {
    "direction": "EGRESS",
    "reason": "TTL exceeded"
  },
  "name": "cilium_drop_count_total",
  "value": 6732
}
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/worker-d]
.  ❌ Found unexpected packet drops:
{
  "labels": {
    "direction": "EGRESS",
    "reason": "FIB lookup failed"
  },
  "name": "cilium_drop_count_total",
  "value": 1
}
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/lhr1-clustera-cp02]
.  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/lhr1-clustera-cp01]
.  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/worker-a]
.  ❌ Found unexpected packet drops:
{
  "labels": {
    "direction": "EGRESS",
    "reason": "FIB lookup failed"
  },
  "name": "cilium_drop_count_total",
  "value": 23
}
{
  "labels": {
    "direction": "EGRESS",
    "reason": "TTL exceeded"
  },
  "name": "cilium_drop_count_total",
  "value": 159908
}
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/lhr1-clustera-cp03]
.
📋 Test Report [cilium-test-1]
❌ 1/1 tests failed (4/7 actions), 107 tests skipped, 0 scenarios skipped:
Test [no-unexpected-packet-drops]:
  ❌ no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/worker-b
  ❌ no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/worker-c
  ❌ no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/worker-d
  ❌ no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/worker-a
[=] [cilium-test-1] Skipping test [no-policies] [2/108] (skipped by user)
...
```

However, while running `hubble observe -f -t drop` on the worker nodes during the test, the only drops we see are from the Tailscale operator, which is sending SSDP multicast packets:

```
Dec 23 13:31:19.674: tailscale/ts-vault-active-qkzq5-0:41855 (ID:69155) <> 239.255.255.250:1900 (world) TTL exceeded DROPPED (UDP)
Dec 23 13:31:19.674: tailscale/ts-vault-active-qkzq5-0:41855 (ID:69155) <> 239.255.255.250:1900 (world) TTL exceeded DROPPED (UDP)
```

In fact, in previous runs of the test, 1 of the worker nodes was not running any Tailscale pods, and the test did not report any drops on that node. (This was reproducible across multiple runs of the test.)

We see similar behavior in 2 other clusters which are both running the Tailscale operator.

Does the `no-unexpected-packet-drops` test look for *any* drops, irrespective of the app ID? In other words, could drops from sources unrelated to the test trigger a test failure for this test?

### How can we reproduce the issue?

`cilium connectivity test --test-namespace cilium-test --verbose --test "no-unexpected-packet-drops"`

### Cilium Version

On the host initiating the connectivity test:

`cilium-cli: 0.16.21 compiled with go1.23.3 on darwin/arm64`

On cluster nodes:

```
Client: 1.16.5 ad688277 2024-12-12T20:18:31+00:00 go version go1.22.10 linux/amd64
Daemon: 1.16.5 ad688277 2024-12-12T20:18:31+00:00 go version go1.22.10 linux/amd64
```

### Kernel Version

`Linux worker-a 6.6.64-talos #1 SMP Wed Dec 11 15:33:07 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`v1.31.4`

### Regression

Not as far as I'm aware.

### Sysdump

[cilium-sysdump-20241223-133706.zip](https://github.com/user-attachments/files/18229907/cilium-sysdump-20241223-133706.zip)

### Relevant log output

```shell
 cilium --context admin@cluster-a connectivity test --test-namespace cilium-test --verbose --test "no-unexpected-packet-drops"                     
ℹ️  Monitor aggregation detected, will skip some flow validation steps
ℹ️  Skipping tests that require a node Without Cilium
⌛ [cluster-a] Waiting for deployment cilium-test-1/client to become ready...
⌛ [cluster-a] Waiting for deployment cilium-test-1/client2 to become ready...
⌛ [cluster-a] Waiting for deployment cilium-test-1/echo-same-node to become ready...
⌛ [cluster-a] Waiting for deployment cilium-test-1/client3 to become ready...
⌛ [cluster-a] Waiting for deployment cilium-test-1/echo-other-node to become ready...
⌛ [cluster-a] Waiting for pod cilium-test-1/client-b65598b6f-npcqw to reach DNS server on cilium-test-1/echo-same-node-799fbb4f76-hwjjq pod...
⌛ [cluster-a] Waiting for pod cilium-test-1/client2-84576868b4-j5mv2 to reach DNS server on cilium-test-1/echo-same-node-799fbb4f76-hwjjq pod...
⌛ [cluster-a] Waiting for pod cilium-test-1/client3-75555c5f5-hrjhp to reach DNS server on cilium-test-1/echo-same-node-799fbb4f76-hwjjq pod...
⌛ [cluster-a] Waiting for pod cilium-test-1/client-b65598b6f-npcqw to reach DNS server on cilium-test-1/echo-other-node-757d5b66fd-zwvpc pod...
⌛ [cluster-a] Waiting for pod cilium-test-1/client2-84576868b4-j5mv2 to reach DNS server on cilium-test-1/echo-other-node-757d5b66fd-zwvpc pod...
⌛ [cluster-a] Waiting for pod cilium-test-1/client3-75555c5f5-hrjhp to reach DNS server on cilium-test-1/echo-other-node-757d5b66fd-zwvpc pod...
⌛ [cluster-a] Waiting for pod cilium-test-1/client-b65598b6f-npcqw to reach default/kubernetes service...
⌛ [cluster-a] Waiting for pod cilium-test-1/client2-84576868b4-j5mv2 to reach default/kubernetes service...
⌛ [cluster-a] Waiting for pod cilium-test-1/client3-75555c5f5-hrjhp to reach default/kubernetes service...
⌛ [cluster-a] Waiting for Service cilium-test-1/echo-other-node to become ready...
⌛ [cluster-a] Waiting for Service cilium-test-1/echo-other-node to be synchronized by Cilium pod kube-system/cilium-26zt8
⌛ [cluster-a] Waiting for Service cilium-test-1/echo-other-node to be synchronized by Cilium pod kube-system/cilium-cxhmw
⌛ [cluster-a] Waiting for Service cilium-test-1/echo-same-node to become ready...
⌛ [cluster-a] Waiting for Service cilium-test-1/echo-same-node to be synchronized by Cilium pod kube-system/cilium-cxhmw
⌛ [cluster-a] Waiting for Service cilium-test-1/echo-same-node to be synchronized by Cilium pod kube-system/cilium-26zt8
⌛ [cluster-a] Retrieving service cilium-test-1/cilium-ingress-same-node ...
⌛ [cluster-a] Retrieving service cilium-test-1/cilium-ingress-other-node ...
⌛ [cluster-a] Waiting for NodePort 10.0.8.9:31711 (cilium-test-1/echo-other-node) to become ready...
⌛ [cluster-a] Waiting for NodePort 10.0.8.9:30973 (cilium-test-1/echo-same-node) to become ready...
⌛ [cluster-a] Waiting for NodePort 10.0.8.8:31711 (cilium-test-1/echo-other-node) to become ready...
⌛ [cluster-a] Waiting for NodePort 10.0.8.8:30973 (cilium-test-1/echo-same-node) to become ready...
⌛ [cluster-a] Waiting for NodePort 10.0.8.19:31711 (cilium-test-1/echo-other-node) to become ready...
⌛ [cluster-a] Waiting for NodePort 10.0.8.19:30973 (cilium-test-1/echo-same-node) to become ready...
⌛ [cluster-a] Waiting for NodePort 10.0.8.10:31711 (cilium-test-1/echo-other-node) to become ready...
⌛ [cluster-a] Waiting for NodePort 10.0.8.10:30973 (cilium-test-1/echo-same-node) to become ready...
⌛ [cluster-a] Waiting for NodePort 10.0.8.20:31711 (cilium-test-1/echo-other-node) to become ready...
⌛ [cluster-a] Waiting for NodePort 10.0.8.20:30973 (cilium-test-1/echo-same-node) to become ready...
⌛ [cluster-a] Waiting for NodePort 10.0.8.21:30973 (cilium-test-1/echo-same-node) to become ready...
⌛ [cluster-a] Waiting for NodePort 10.0.8.21:31711 (cilium-test-1/echo-other-node) to become ready...
⌛ [cluster-a] Waiting for NodePort 10.0.8.22:31711 (cilium-test-1/echo-other-node) to become ready...
⌛ [cluster-a] Waiting for NodePort 10.0.8.22:30973 (cilium-test-1/echo-same-node) to become ready...
⌛ [cluster-a] Waiting for DaemonSet cilium-test-1/host-netns-non-cilium to become ready...
⌛ [cluster-a] Waiting for DaemonSet cilium-test-1/host-netns to become ready...
ℹ️  Skipping IPCache check
🔭 Enabling Hubble telescope...
⚠️  Unable to contact Hubble Relay, disabling Hubble telescope and flow validation: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:4245: connect: connection refused"
ℹ️  Expose Relay locally with:
   cilium hubble enable
   cilium hubble port-forward&
ℹ️  Cilium version: 1.16.5
🏃[cilium-test-1] Running 108 tests ...
  [-] Scenario [no-unexpected-packet-drops/no-unexpected-packet-drops]
[=] [cilium-test-1] Test [no-unexpected-packet-drops] [1/108]
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/worker-b]
.  ❌ Found unexpected packet drops:
{
  "labels": {
    "direction": "EGRESS",
    "reason": "FIB lookup failed"
  },
  "name": "cilium_drop_count_total",
  "value": 322
}
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/worker-c]
.  ❌ Found unexpected packet drops:
{
  "labels": {
    "direction": "EGRESS",
    "reason": "FIB lookup failed"
  },
  "name": "cilium_drop_count_total",
  "value": 20
}
{
  "labels": {
    "direction": "EGRESS",
    "reason": "TTL exceeded"
  },
  "name": "cilium_drop_count_total",
  "value": 6732
}
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/worker-d]
.  ❌ Found unexpected packet drops:
{
  "labels": {
    "direction": "EGRESS",
    "reason": "FIB lookup failed"
  },
  "name": "cilium_drop_count_total",
  "value": 1
}
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/lhr1-clustera-cp02]
.  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/lhr1-clustera-cp01]
.  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/worker-a]
.  ❌ Found unexpected packet drops:
{
  "labels": {
    "direction": "EGRESS",
    "reason": "FIB lookup failed"
  },
  "name": "cilium_drop_count_total",
  "value": 23
}
{
  "labels": {
    "direction": "EGRESS",
    "reason": "TTL exceeded"
  },
  "name": "cilium_drop_count_total",
  "value": 159908
}
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/lhr1-clustera-cp03]
.
📋 Test Report [cilium-test-1]
❌ 1/1 tests failed (4/7 actions), 107 tests skipped, 0 scenarios skipped:
Test [no-unexpected-packet-drops]:
  ❌ no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/worker-b
  ❌ no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/worker-c
  ❌ no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/worker-d
  ❌ no-unexpected-packet-drops/no-unexpected-packet-drops/cluster-a/worker-a
[=] [cilium-test-1] Skipping test [no-policies] [2/108] (skipped by user)
[=] [cilium-test-1] Skipping test [no-policies-from-outside] [3/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [no-policies-extra] [4/108] (skipped by user)
[=] [cilium-test-1] Skipping test [allow-all-except-world] [5/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-ingress-knp] [7/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-ingress] [6/108] (skipped by user)
[=] [cilium-test-1] Skipping test [allow-all-with-metrics-check] [8/108] (skipped by user)
[=] [cilium-test-1] Skipping test [all-ingress-deny] [9/108] (skipped by user)
[=] [cilium-test-1] Skipping test [all-ingress-deny-from-outside] [10/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [all-ingress-deny-knp] [11/108] (skipped by user)
[=] [cilium-test-1] Skipping test [all-egress-deny] [12/108] (skipped by user)
[=] [cilium-test-1] Skipping test [cluster-entity-multi-cluster] [16/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [all-egress-deny-knp] [13/108] (skipped by user)
[=] [cilium-test-1] Skipping test [all-entities-deny] [14/108] (skipped by user)
[=] [cilium-test-1] Skipping test [cluster-entity] [15/108] (skipped by user)
[=] [cilium-test-1] Skipping test [host-entity-ingress] [18/108] (skipped by user)
[=] [cilium-test-1] Skipping test [host-entity-egress] [17/108] (skipped by user)
[=] [cilium-test-1] Skipping test [echo-ingress] [19/108] (skipped by user)
[=] [cilium-test-1] Skipping test [echo-ingress-from-outside] [20/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [echo-ingress-knp] [21/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-ingress-icmp] [22/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress] [23/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-knp] [24/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-expression] [25/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-expression-port-range] [26/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-expression-knp] [27/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-with-service-account-egress-to-echo-port-range] [30/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-expression-knp-port-range] [28/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-with-service-account-egress-to-echo] [29/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-to-echo-service-account-port-range] [32/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-to-echo-service-account] [31/108] (skipped by user)
[=] [cilium-test-1] Skipping test [to-entities-world] [33/108] (skipped by user)
[=] [cilium-test-1] Skipping test [to-cidr-external] [35/108] (skipped by user)
[=] [cilium-test-1] Skipping test [to-entities-world-port-range] [34/108] (skipped by user)
[=] [cilium-test-1] Skipping test [to-cidr-external-knp] [36/108] (skipped by user)
[=] [cilium-test-1] Skipping test [seq-from-cidr-host-netns] [37/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [echo-ingress-from-other-client-deny] [38/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-ingress-from-other-client-icmp-deny] [39/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-to-echo-deny-port-range] [41/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-to-echo-deny] [40/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-to-echo-expression-deny] [43/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-ingress-to-echo-named-port-deny] [42/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-to-echo-expression-deny-port-range] [44/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-with-service-account-egress-to-echo-deny] [45/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-with-service-account-egress-to-echo-deny-port-range] [46/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-to-echo-service-account-deny] [47/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-to-cidr-deny] [49/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-to-echo-service-account-deny-port-range] [48/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-to-cidrgroup-deny] [50/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-to-cidrgroup-deny-by-label] [51/108] (requires Cilium version >=1.17.0 but running 1.16.5)
[=] [cilium-test-1] Skipping test [client-egress-to-cidr-deny-default] [52/108] (skipped by user)
[=] [cilium-test-1] Skipping test [clustermesh-endpointslice-sync] [53/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [health] [54/108] (skipped by user)
[=] [cilium-test-1] Skipping test [pod-to-pod-encryption] [56/108] (skipped by user)
[=] [cilium-test-1] Skipping test [north-south-loadbalancing] [55/108] (Feature node-without-cilium is disabled)
[=] [cilium-test-1] Skipping test [pod-to-pod-with-l7-policy-encryption] [57/108] (Feature encryption-pod is disabled)
[=] [cilium-test-1] Skipping test [node-to-node-encryption] [58/108] (skipped by user)
[=] [cilium-test-1] Skipping test [seq-egress-gateway] [59/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [egress-gateway-excluded-cidrs] [60/108] (Feature enable-ipv4-egress-gateway is disabled)
[=] [cilium-test-1] Skipping test [seq-egress-gateway-with-l7-policy] [61/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [pod-to-node-cidrpolicy] [62/108] (Feature cidr-match-nodes is disabled)
[=] [cilium-test-1] Skipping test [north-south-loadbalancing-with-l7-policy] [63/108] (Feature node-without-cilium is disabled)
[=] [cilium-test-1] Skipping test [north-south-loadbalancing-with-l7-policy-port-range] [64/108] (Feature node-without-cilium is disabled)
[=] [cilium-test-1] Skipping test [echo-ingress-l7] [65/108] (skipped by user)
[=] [cilium-test-1] Skipping test [echo-ingress-l7-via-hostport] [66/108] (skipped by user)
[=] [cilium-test-1] Skipping test [echo-ingress-l7-named-port] [67/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-l7-method] [68/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-l7-method-port-range] [69/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-l7] [70/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-l7-port-range] [71/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-l7-named-port] [72/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-l7-tls-deny-without-headers] [73/108] (Feature secret-backend-k8s is disabled)
[=] [cilium-test-1] Skipping test [client-egress-l7-tls-headers] [74/108] (Feature secret-backend-k8s is disabled)
[=] [cilium-test-1] Skipping test [client-egress-l7-tls-headers-port-range] [75/108] (Feature secret-backend-k8s is disabled)
[=] [cilium-test-1] Skipping test [client-egress-tls-sni] [76/108] (skipped by user)
[=] [cilium-test-1] Skipping test [client-egress-l7-tls-headers-sni] [77/108] (Feature secret-backend-k8s is disabled)
[=] [cilium-test-1] Skipping test [client-egress-l7-set-header] [78/108] (Feature secret-backend-k8s is disabled)
[=] [cilium-test-1] Skipping test [client-egress-l7-set-header-port-range] [79/108] (Feature secret-backend-k8s is disabled)
[=] [cilium-test-1] Skipping test [echo-ingress-auth-always-fail] [80/108] (Feature mutual-auth-spiffe is disabled)
[=] [cilium-test-1] Skipping test [echo-ingress-auth-always-fail-port-range] [81/108] (Feature mutual-auth-spiffe is disabled)
[=] [cilium-test-1] Skipping test [echo-ingress-mutual-auth-spiffe] [82/108] (Feature mutual-auth-spiffe is disabled)
[=] [cilium-test-1] Skipping test [echo-ingress-mutual-auth-spiffe-port-range] [83/108] (Feature mutual-auth-spiffe is disabled)
[=] [cilium-test-1] Skipping test [pod-to-ingress-service] [84/108] (skipped by user)
[=] [cilium-test-1] Skipping test [pod-to-ingress-service-deny-all] [85/108] (skipped by user)
[=] [cilium-test-1] Skipping test [pod-to-ingress-service-deny-ingress-identity] [86/108] (skipped by user)
[=] [cilium-test-1] Skipping test [pod-to-ingress-service-deny-backend-service] [87/108] (skipped by user)
[=] [cilium-test-1] Skipping test [pod-to-ingress-service-allow-ingress-identity] [88/108] (skipped by user)
[=] [cilium-test-1] Skipping test [outside-to-ingress-service] [89/108] (Feature node-without-cilium is disabled)
[=] [cilium-test-1] Skipping test [outside-to-ingress-service-deny-world-identity] [90/108] (Feature node-without-cilium is disabled)
[=] [cilium-test-1] Skipping test [outside-to-ingress-service-deny-cidr] [91/108] (Feature node-without-cilium is disabled)
[=] [cilium-test-1] Skipping test [outside-to-ingress-service-deny-all-ingress] [92/108] (Feature node-without-cilium is disabled)
[=] [cilium-test-1] Skipping test [dns-only] [93/108] (skipped by user)
[=] [cilium-test-1] Skipping test [to-fqdns] [94/108] (skipped by user)
[=] [cilium-test-1] Skipping test [pod-to-controlplane-host] [95/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [pod-to-k8s-on-controlplane] [96/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [pod-to-controlplane-host-cidr] [97/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [pod-to-k8s-on-controlplane-cidr] [98/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [local-redirect-policy] [99/108] (Feature enable-local-redirect-policy is disabled)
[=] [cilium-test-1] Skipping test [local-redirect-policy-with-node-dns] [100/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [pod-to-pod-no-frag] [101/108] (skipped by user)
[=] [cilium-test-1] Skipping test [seq-bgp-control-plane-v1] [102/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [seq-bgp-control-plane-v2] [103/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [multicast] [104/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [strict-mode-encryption] [105/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [host-firewall-ingress] [106/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [host-firewall-egress] [107/108] (skipped by condition)
[=] [cilium-test-1] Skipping test [check-log-errors] [108/108] (skipped by user)
[cilium-test-1] 1 tests failed
```

### Anything else?

Cilium Helm values:

```yaml
cluster:
  name: cluster-a
  id: 1

clustermesh:
  useAPIServer: true
  apiserver:
    replicas: 3
    service:
      type: LoadBalancer
      loadBalancerClass: io.cilium/bgp-control-plane
      externalTrafficPolicy: Local
      annotations:
        io.cilium/lb-ipam-ips: 10.0.20.245
    tls:
      authMode: cluster
      auto:
        method: certmanager
        certValidityDuration: 90
        certManagerIssuerRef:
          group: cert-manager.io
          kind: ClusterIssuer
          name: cilium-issuer
    metrics:
      serviceMonitor:
        enabled: true
        interval: 30s
        kvstoremesh:
          interval: 30s
        etcd:
          interval: 30s
  config:
    enabled: true
    clusters:
      - name: cluster-b
        port: 2379
        ips:
          - 10.0.24.245
      - name: cluster-c
        port: 2379
        ips:
          - 10.64.70.245

updateStrategy:
  rollingUpdate:
    maxUnavailable: 1

upgradeCompatibility: "1.14"
kubeProxyReplacement: true
k8sServiceHost: localhost
k8sServicePort: 7445
ipam:
  mode: kubernetes

rollOutCiliumPods: true
operator:
  rollOutPods: true

bgpControlPlane:
  enabled: true

hostFirewall:
  enabled: false

# Fix for Talos.
# https://github.com/cilium/cilium/issues/21603#issuecomment-1453753820
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

l7Proxy: true

# Deploy Envoy as a daemonset, rather than as part of the Cilium agent
# pods.
envoy:
  enabled: true
  # Required to permit Envoy to bind to privileged ports.
  #
  # Ref:
  # https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/#bind-to-privileged-port
  securityContext:
   capabilities:
     keepCapNetBindService: true
     envoy:
       # Defaults.
       - NET_ADMIN
       - SYS_ADMIN

       # Required by Gateway (for privileged ports).
       - NET_BIND_SERVICE
  rollOutPods: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

gatewayAPI:
  enabled: true

ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  service:
    # Argo CD can't properly reconcile the ports on this service, so
    # we specify them. Here I've chosen whatever defaults the service
    # uses when they're not specified.
    insecureNodePort: 30332
    secureNodePort: 30235
    annotations:
      io.cilium/lb-ipam-ips: 10.0.20.253

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true

hubble:
  relay:
    enabled: true
    replicas: 3
    prometheus:
      serviceMonitor:
        enabled: true
  ui:
    enabled: true
  tls:
    auto:
      enabled: true
      method: certmanager
      certValidityDuration: 1095
      certManagerIssuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: cilium-issuer
  metrics:
    enableOpenMetrics: true
    enabled:
      - dns:labelsContext=source_namespace,destination_namespace
      - drop:labelsContext=source_namespace,destination_namespace
      - tcp:labelsContext=source_namespace,destination_namespace
      - port-distribution:labelsContext=source_namespace,destination_namespace
      - icmp:labelsContext=source_namespace,destination_namespace;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity
      - flow:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity;labelsContext=source_namespace,destination_namespace
      - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      - "policy:sourceContext=app|workload-name|pod|reserved-identity;destinationContext=app|workload-name|pod|dns|reserved-identity;labelsContext=source_namespace,destination_namespace"
    dashboards:
      enabled: true
    serviceMonitor:
      enabled: true

# Native, L2 direct routing.
routingMode: native
autoDirectNodeRoutes: true
# Seems required for clustermesh to work?
# ref:
# https://github.com/cilium/cilium/issues/31843
directRoutingSkipUnreachable: true
ipv4NativeRoutingCIDR: 10.0.0.0/8

loadBalancer:
  algorithm: maglev
  mode: dsr
  dsrDispatch: opt
  acceleration: native

maglev:
  hashSeed: [redacted]

bpf:
  masquerade: true

# Performance tweaks.
# https://docs.cilium.io/en/stable/operations/performance/tuning/
enableIPv4BIGTCP: true
enableIPv6BIGTCP: true
bandwidthManager:
  enabled: true
  bbr: true

dashboards:
  enabled: true

```

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
