### ISSUE TITLE
CFP: Requesting support for 'metadata' annotation propagation from Gateway-API's 'Gateway' class to the Service of type 'LoadBalancer'

### ISSUE THREAD

**Issue by am-i-helpful** [cilium/cilium#36792]
## Cilium Feature Proposal

Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](https://slack.cilium.io) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your proposed feature related to a problem?**

Yes, I am experiencing a problem related to challenges with automatic provisioning of an external LB with the help of my cloud-controller-manager, which is relying on the Cilium gateway API for the same in my K8s cluster. I am working with the Cilium Gateway-API v1.1.1, and having difficulty with the way how Gateway resource is bundling the service, especially that there is no way to migrate the annotations within the Gateway resource to the Service of type 'LoadBalancer', which would automatically result in the provisioning of the external load-balancer by the cloud-controller-manager (hcloud in my case).

Example: Gateway resource configuration
```
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
  namespace: my-test
  # add some LB annotations: https://github.com/vitobotta/hetzner-k3s/blob/main/docs/Load_balancers.md#load-balancers
  annotations:
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/use-private-ip: "true"
spec:
  gatewayClassName: cilium
  listeners:
  - name: web-gw
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
```

This successfully outputs:
-> `kubectl get svc cilium-gateway-my-gateway -n my-test`
```
NAME                          TYPE         CLUSTER-IP     EXTERNAL-IP     PORT(S)         AGE
cilium-gateway-my-gateway   LoadBalancer   192.168.245.249   <pending>     80:32753/TCP   67s
```

Unfortunately, the corresponding 'LoadBalancer' type service doesn't have the same annotations within the metadata, which results in hccm manager to not provision an external LB (these annotations are necesaary for hcloud to provision an external LB, but I don't see any reason why the annotations are not migrated as well by the Cilium GatewayAPI controller):
-> `kubectl get svc cilium-gateway-my-gateway -n my-test -o yaml`
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-12-25T15:24:16Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    gateway.networking.k8s.io/gateway-name: my-gateway
    io.cilium.gateway/owning-gateway: my-gateway
  name: cilium-gateway-my-gateway
  namespace: my-test
  ownerReferences:
  - apiVersion: gateway.networking.k8s.io/v1
    controller: true
    kind: Gateway
    name: my-gateway
    uid: d8772f05-b2c4-47c7-93da-3d01f4ce5dc7
  resourceVersion: "180269"
  uid: c9750da7-2bd8-458b-94fc-ce08ca017490
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 192.168.245.249
  clusterIPs:
  - 192.168.245.249
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-80
    nodePort: 32753
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}

```
**Describe the feature you'd like**

I would expect that the annotations added within metadata in the 'Gateway' resource (https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.Gateway) should also propagate to the 'Service' of type 'LoadBalancer', which is not happening currently unfortunately, thereby resulting in the external-LB to not be provisioned (by hcloud in this case).

**(Optional) Describe your proposed solution**

I have not dove deeper into the solution, but if I find the missing code within the Cilium repository, I will share it in the comment. For now, I think I can temporarily manage with manually patching the created Service with the required annotations. But, it would be great that these annotations are also migrated from the 'Gateway' resource to the corresponding 'Service' of type 'LoadBalancer'. 
```
kubectl annotate service <service-name> load-balancer.hetzner.cloud/location=nbg1
kubectl annotate service <service-name> load-balancer.hetzner.cloud/use-private-ip="true"
```
