### ISSUE TITLE
vlan filter drops 802.1q packets in vpc cni chaining mode

### ISSUE THREAD

**Issue by sdickhoven** [cilium/cilium#36803]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.5 and lower than v1.17.0

### What happened?

we use [security groups for pods](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html) in our eks clusters... which implies that we're running cilium in [vpc cni chaining mode](https://docs.cilium.io/en/v1.16/installation/cni-chaining-aws-cni/#setting-up-a-cluster-on-aws):

```yaml
cni:
  chainingMode: aws-cni
  exclusive: false
enableIPv4Masquerade: false
routingMode: native
endpointRoutes:
  enabled: true
```

the vpc cni is configured like so:

```json
{
  "enableNetworkPolicy": "false",
  "env": {
    "AWS_VPC_K8S_CNI_EXTERNALSNAT": "true",
    "ENABLE_POD_ENI": "true",
    "POD_SECURITY_GROUP_ENFORCING_MODE": "standard"
  }
}
```

after running cilium for a few weeks, we encountered a number of pods that kept crashlooping because they couldn't communicate with anything (dns timeouts).

these pods did **not** have "dns snooping" enabled (i.e. **no** l7 dns network policies)... so this has nothing to do with proxy redirects.

after a lot of digging, we saw that the dns timeouts were correlated with drops due to "VLAN traffic disallowed by VLAN filter".

([security groups for pods](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html) uses a vlan trunk to provision logical enis with dedicated security groups)

a bit of googling turned up this:

https://docs.cilium.io/en/stable/configuration/vlan-802.1q/

so i added the following to our helm config and the drops (and dns timeouts) went away and the crashlooping pods recovered without further ado. 🎉 

```yaml
bpf:
  vlanBypass: [0]
```

i guess the behavior is expected and agrees with the documentation that states:

>if `eth0.4000` is controlled by Cilium and has an eBPF program attached, then VLAN tag `4000` will be allowed on device `eth0`

since the vlan subinterface is **not** managed by cilium, it makes sense that cilium would block 802.1q tagged packets on the physical interface.

however, since the physical interface is _also_ **not** managed by cilium, i wonder if this behavior might be unintended. 🤷 

if this behavior is correct and intended then maybe it would make sense to update the documentation [here](https://docs.cilium.io/en/v1.16/installation/cni-chaining-aws-cni/#enabling-security-groups-for-pods-eks) to add the following option to `helm install`:

```
--set bpf.vlanBypass={0}
```

also note that setting the env var

```sh
DISABLE_TCP_EARLY_DEMUX=true
```

for the `aws-node` daemon set is only necessary when using

```sh
POD_SECURITY_GROUP_ENFORCING_MODE=strict
```

### How can we reproduce the issue?

deploy cilium in aws vpc cni chaining mode:

```yaml
cni:
  chainingMode: aws-cni
  exclusive: false
enableIPv4Masquerade: false
routingMode: native
endpointRoutes:
  enabled: true
```

configure the vpc cni like so:

```json
{
  "enableNetworkPolicy": "false",
  "env": {
    "AWS_VPC_K8S_CNI_EXTERNALSNAT": "true",
    "ENABLE_POD_ENI": "true",
    "POD_SECURITY_GROUP_ENFORCING_MODE": "standard"
  }
}
```

create a few pods with a `SecurityGroupPolicy`:

```yaml
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: sdickhoven-test-delete-me
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: sdickhoven-test-delete-me
  securityGroups:
    groupIds:
    - sg-aaaaaaaaaaaaaaaaa # cluster sg
    - sg-bbbbbbbbbbbbbbbbb # pod sg

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdickhoven-test-delete-me
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: sdickhoven-test-delete-me
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sdickhoven-test-delete-me
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:24.04
        command:
        - sh
        - -c
        - |
          apt update    # this generates traffic
          sleep 3600
```

cycle pods a few times and watch the metric `cilium_drop_count_total{reason="VLAN traffic disallowed by VLAN filter"}`

### Cilium Version

```
cilium-cli: v0.16.22 compiled with go1.23.4 on darwin/arm64
cilium image (default): v1.16.4
cilium image (stable): v1.16.5
cilium image (running): unknown. Unable to obtain cilium version. Reason: release: not found
```

not sure why the cilium cli is not reporting the running version. 🤷

maybe it's looking for the helm `Secret` / `ConfigMap` of the cilium install. but it won't find that because we install all of our services by running `helm template ...` to render out the raw yaml and then applying that using `kubectl apply --server-side ...`.

```
$ kubectl get ds -n kube-system cilium -o jsonpath="{.spec.template.spec.containers[0].image}"
111111111111.dkr.ecr.us-east-1.amazonaws.com/quay/cilium/cilium:v1.16.5@sha256:758ca0793f5995bb938a2fa219dcce63dc0b3fa7fc4ce5cc851125281fb7361d

$ kubectl get deploy -n kube-system cilium-operator -o jsonpath="{.spec.template.spec.containers[0].image}"
111111111111.dkr.ecr.us-east-1.amazonaws.com/quay/cilium/operator-generic:v1.16.5@sha256:f7884848483bbcd7b1e0ccfd34ba4546f258b460cb4b7e2f06a1bcc96ef88039

$ kubectl get ds -n kube-system cilium-envoy -o jsonpath="{.spec.template.spec.containers[0].image}"
111111111111.dkr.ecr.us-east-1.amazonaws.com/quay/cilium/cilium-envoy:v1.30.8-1733837904-eaae5aca0fb988583e5617170a65ac5aa51c0aa8@sha256:709c08ade3d17d52da4ca2af33f431360ec26268d288d9a6cd1d98acc9a1dced
```

(using amazon ecr pull-through cache to pull images from quay.io... redacted account number)

### Kernel Version

6.1.109-118.189.amzn2023.aarch64
6.1.109-118.189.amzn2023.x86_64

### Kubernetes Version

```json
{
  "major": "1",
  "minor": "29+",
  "gitVersion": "v1.29.10-eks-7f9249a",
  "gitCommit": "d06fe5fa1c524ee5eb5d16bb9edc4dda6075f6c3",
  "gitTreeState": "clean",
  "buildDate": "2024-10-23T23:40:34Z",
  "goVersion": "go1.22.8",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

### Regression

unknown. i have only tried this with version 1.16.4 & 1.16.5

### Sysdump

File size too big: 25 MB are allowed, 25 MB were attempted to upload.

### Relevant log output

```shell
n/a
```

### Anything else?

```
$ kubectl get pod sdickhoven-test-delete-me-58449df7bf-55flx -o jsonpath="{.metadata.annotations.vpc\.amazonaws\.com/pod-eni}" | jq -r
[
  {
    "eniId": "eni-0c1a6112ca008c99e",
    "ifAddress": "12:39:59:07:ac:b9",
    "privateIp": "10.0.13.24",
    "ipv6Addr": "",
    "vlanId": 2,
    "subnetCidr": "10.0.0.0/20",
    "subnetV6Cidr": "2600:ffff:ffff:ffff::/64"
  }
]
```

```
# ip address show
...
3: ens8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    link/ether 12:2f:0b:e0:c9:5f brd ff:ff:ff:ff:ff:ff
    altname enp0s8
    inet 10.0.13.209/20 brd 10.0.15.255 scope global ens8
       valid_lft forever preferred_lft forever
    inet6 fe80::102f:bff:fee0:c95f/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
...
34: vlan.eth.2@ens8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP group default qlen 1000
    link/ether 12:39:59:07:ac:b9 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::1039:59ff:fe07:acb9/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
```

```
# ip -d link show vlan.eth.2
34: vlan.eth.2@ens8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 12:39:59:07:ac:b9 brd ff:ff:ff:ff:ff:ff promiscuity 0 allmulti 0 minmtu 0 maxmtu 65535 
    vlan protocol 802.1Q id 2 <REORDER_HDR> numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 tso_max_size 65536 tso_max_segs 65535 gro_max_size 65536 
```

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
