### ISSUE TITLE
Hubble Relay timeout

### ISSUE THREAD

**Issue by adamcirillo** [cilium/cilium#36979]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.0 and lower than v1.18.0

### What happened?

Hubble relay does not start up logs show the following errors and does not start up

### How can we reproduce the issue?

I installed cilium with helm, i've attached my values below as well same config works on 1.16.5

helm install cilium cilium/cilium --version 1.17.0-rc.1 --namespace=kube-system -f cilium.yaml

```
cni:
  exclusive: false

cluster:
  name: "adamhome"
  id: 1

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

operator:
  prometheus:
    enabled: true
  serviceMonitor:
    enabled: true
  replicas: 2

ipam:
  mode: kubernetes
ipv4:
  enabled: true
ipv6:
  enabled: true

ingressController:
  enabled: true

bpf:
  masquerade: true

loadBalancer:
  algorithm: "maglev"
  acceleration: "best-effort"
  mode: snat
l2announcements:
  enabled: true

routingMode: native
ipv4NativeRoutingCIDR: "10.1.1.0/24"
ipv6NativeRoutingCIDR: "FD10::10:1:1:0/120"
autoDirectNodeRoutes: true
enableIPv4Masquerade: true
enableIPv6Masquerade: true

clustermesh:
  useAPIServer: true
  apiserver:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      kvstoremesh:
        enabled: true
      etcd:
        enabled: true

hubble:
  tls:
    auto:
      enabled: true
  relay:
    enabled: true
    tls:
      auto:
        enabled: true
    prometheus:
      enabled: true
      port: 9966
      serviceMonitor:
        enabled: true
  ui:
    enabled: true
  peerService:
    clusterDomain: k8s01.cluster.local
  metrics:
    enableOpenMetrics: true
    serviceMonitor:
      enabled: true
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - "dns:labelsContext=source_namespace,destination_namespace"
      - "drop:labelsContext=source_namespace,destination_namespace"
      - "httpV2:sourceContext=workload-name|pod-name|reserved-identity;destinationContext=workload-name|pod-name|reserved-identity;labelsContext=source_namespace,destination_namespace,traffic_direction"

externalWorkloads:
  enabled: true
  
etcd:
  clusterDomain: k8s01.cluster.local

kubeProxyReplacement: true

socketLB:
  hostNamespaceOnly: true

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

k8sServiceHost: localhost
k8sServicePort: 7445
```

### Cilium Version

1.17.0-rc.1 also had the same problem on 1.17.0-rc.0

### Kernel Version

Talos Linux 1.9.1
6.12.6-talos

### Kubernetes Version

1.32

### Regression

the same install works fine on 1.16.5

### Sysdump

[cilium-sysdump-20250115-082924.zip](https://github.com/user-attachments/files/18416421/cilium-sysdump-20250115-082924.zip)

### Relevant log output

```shell
2025-01-14 21:26:49.112Z time="2025-01-14T21:26:49.112802615Z" level=info msg="Starting gRPC health server..." addr=":4222" subsys=hubble-relay
2025-01-14 21:26:49.113Z time="2025-01-14T21:26:49.112882414Z" level=info msg="Starting metrics server..." address=":9966" subsys=hubble-relay
2025-01-14 21:26:49.113Z time="2025-01-14T21:26:49.113103411Z" level=info msg="Starting gRPC server..." options="{peerTarget:hubble-peer.kube-system.svc.k8s01.cluster.local.:443 retryTimeout:30000000000 listenAddress::4245 healthListenAddress::4222 metricsListenAddress::9966 log:0xc0003dc1c0 serverTLSConfig:<nil> insecureServer:true clientTLSConfig:0xc000c06480 clusterName:adamhome insecureClient:false observerOptions:[0x2d8ea80 0x2d8eb60] grpcMetrics:0xc00072a1c0 grpcUnaryInterceptors:[0x2df3380] grpcStreamInterceptors:[0x2df35e0]}" subsys=hubble-relay
2025-01-14 21:26:49.118Z time="2025-01-14T21:26:49.118749254Z" level=info msg="Failed to create peer notify client for peers change notification; will try again after the timeout has expired" connection timeout=30s error="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 10.101.19.152:443: connect: connection refused\"" subsys=hubble-relay
2025-01-14 21:27:19.121Z time="2025-01-14T21:27:19.121001506Z" level=info msg="Failed to create peer notify client for peers change notification; will try again after the timeout has expired" connection timeout=30s error="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 10.101.19.152:443: connect: connection refused\"" subsys=hubble-relay
```

### Anything else?

this is a fresh install on a 1 control plane 2 node cluster, only running coredns and hubble metrics on the server besides cilium.
i also tried using tunnel mode as well same results

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by yuito-it** [comment]
I have same trouble.
`hubble-relay` is not ready.

**Comment by JPaja** [comment]
+1 

I see that tls.secretsBackend got deprecated recently. Could this be cause of issue?
https://docs.cilium.io/en/stable/security/tls-visibility/#configuring-tls-interception

**Comment by artemistomaras** [comment]
Same here upgrading from 1.16.6 with

```yaml
upgradeCompatibility: "v1.16"
prometheus:
  enabled: true
encryption:
  enabled: true
  nodeEncryption: true
  type: wireguard
hubble:
  enabled: true
  export:
    # --- Defines max file size of output file before it gets rotated.
    fileMaxSizeMb: 100
    # --- Defines max number of backup/rotated files.
    fileMaxBackups: 5
    # --- Static exporter configuration.
    # Static exporter is bound to agent lifecycle.
    static:
      enabled: true
      filePath: /var/run/cilium/hubble/events.log
      fieldMask: [ ]
      # - time
      # - source
      # - destination
      # - verdict
      allowList: [ ]
      # - '{"verdict":["DROPPED","ERROR"]}'
      denyList: [ ]
  metrics:
    enableOpenMetrics: true
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - port-distribution
    - icmp
    - http
  relay:
    enabled: true
  ui:
    enabled: true
ipam:
  mode: kubernetes
k8sServiceHost: 127.0.0.1
k8sServicePort: 6444
kubeProxyReplacement: true
operator:
  replicas: 1
  prometheus:
    enabled: true
  resources:
    requests:
      memory: 128Mi
resources:
  requests:
    memory: 512Mi
routingMode: tunnel
tunnelProtocol: vxlan
tls:
  secretsBackend: "local"
```

only thing worked is to downgrade to 1.16.9. @JPaja did you make it work?
