### ISSUE TITLE
CFP: Allow customization of Hubble UI ingress backend in helm chart

### ISSUE THREAD

**Issue by cf-sewe** [cilium/cilium#37012]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

The Hubble UI ingress template currently hardcodes the backend service configuration to `hubble-ui`. This makes it impossible to integrate Hubble UI with authentication proxies (like OAuth2-Proxy or Authentik) or custom routing setups without managing a separate ingress resource outside of the Helm chart.

Organizations that require authentication for Hubble UI access must currently:
1. Disable the built-in ingress
2. Manage their own ingress resource
3. Maintain this configuration separately from the Helm release

**Describe the feature you'd like**

Add the ability to fully customize the backend configuration in the Hubble UI ingress through Helm values. This would allow users to:

1. Optionally override the entire backend configuration
2. Direct traffic through authentication proxies
3. Maintain configuration within the Helm release

Example configuration:
```yaml
hubble:
  ui:
    ingress:
      backend:
        service:
          name: authentik-outpost
          port:
            number: 9000
```

**Describe your proposed solution**

1. Add a new optional `backend` field to `hubble.ui.ingress` values
2. Update the ingress template to use this configuration when provided
3. Maintain default behavior when no override is specified

Template changes would look like:
```yaml
backend:
{{- if $.Values.hubble.ui.ingress.backend }}
  {{- toYaml $.Values.hubble.ui.ingress.backend | nindent 14 }}
{{- else }}
  service:
    name: hubble-ui
    port:
      name: http
{{- end }}
```

This follows Kubernetes API structure and maintains backward compatibility while giving users full control over their ingress configuration.
