### ISSUE TITLE
CiliumNetworkPolicy CRD validation doesn't enforce not using ToServices & ToPorts together

### ISSUE THREAD

**Issue by jaredledvina** [cilium/cilium#37057]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.5 and lower than v1.17.0

### What happened?

Currently, the CiliumNetworkPolicy validation doesn't enforce the unsupported use of `ToServices` and `ToPorts`. The UX is painful for users as they can create a CNP that does do that succesfully, if they `k describe` the CNP, it'll show as validated succesfully. It's only if they check the `cilium-agent` logs that they'll discover: `Invalid CiliumNetworkPolicy spec: Combining ToServices and ToPorts is not supported yet`. This is particularly confusing when the CNP contains many `specs`'s and the entire thing isn't imported because of this one issue. 

### How can we reproduce the issue?

1. Create a CNP with a rule stanza like:
```yaml
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: example
  namespace: example-namespace
  labels:
    example: true
specs:
  - description: "Egress to special service one"
    endpointSelector:
      matchLabels:
        - example: true
    egress:
    - toServices:
      - k8sService:
          serviceName: special-service-one
          namespace: example-k8s
      toPorts:
      - ports:
        - port: "443"
          protocol: TCP
```
2. Observe that it's accepted by the `kube-apiserver` but that the `cilium-agent`'s cannot import it. 

### Cilium Version

# cilium version
Client: 1.16.5 111f93b812 2025-01-10T14:01:15-05:00 go version go1.22.10 linux/arm64
Daemon: 1.16.5 111f93b812 2025-01-10T14:01:15-05:00 go version go1.22.10 linux/arm64

### Kernel Version

Linux ip-10-128-52-162 6.8.0-1021-aws #23~22.04.1-Ubuntu SMP Tue Dec 10 16:31:58 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

❯ kubectl version
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.31.2-dd.1

### Regression

N/A

### Sysdump

N/A

### Relevant log output

```shell
{"ciliumNetworkPolicyName":"snip","error":"Invalid CiliumNetworkPolicy specs: Combining ToServices and ToPorts is not supported yet","k8sApiVersion":"","k8sNamespace":"snip-k8s","level":"warning","msg":"Unable to add CiliumNetworkPolicy","subsys":"policy-k8s-watcher","time":"2025-01-17T20:34:35.074245037Z"}
```

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
