### ISSUE TITLE
CFP: Support helm diff on all secrets

### ISSUE THREAD

**Issue by Javex** [cilium/cilium#37065]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

When running `helm diff upgrade cilium cilium/cilium --version 1.16.5 --namespace kube-system -f values.yaml` on an existing installation, three diffs are produced:

```yaml
kube-system, cilium-ca, Secret (v1) has changed:
  # Source: cilium/templates/cilium-ca-secret.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    name: cilium-ca
    namespace: kube-system
  data:
-   ca.crt: '-------- # (1127 bytes)'
-   ca.key: '-------- # (1679 bytes)'
+   ca.crt: '++++++++ # (1127 bytes)'
+   ca.key: '++++++++ # (1675 bytes)'

kube-system, hubble-relay-client-certs, Secret (v1) has changed:
  # Source: cilium/templates/hubble/tls-helm/relay-client-secret.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    name: hubble-relay-client-certs
    namespace: kube-system
  data:
-   ca.crt: '-------- # (1127 bytes)'
-   tls.crt: '-------- # (1200 bytes)'
-   tls.key: '-------- # (1675 bytes)'
+   ca.crt: '++++++++ # (1127 bytes)'
+   tls.crt: '++++++++ # (1200 bytes)'
+   tls.key: '++++++++ # (1675 bytes)'
  type: kubernetes.io/tls

kube-system, hubble-server-certs, Secret (v1) has changed:
  # Source: cilium/templates/hubble/tls-helm/server-secret.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    name: hubble-server-certs
    namespace: kube-system
  data:
-   ca.crt: '-------- # (1127 bytes)'
-   tls.crt: '-------- # (1220 bytes)'
-   tls.key: '-------- # (1679 bytes)'
+   ca.crt: '++++++++ # (1127 bytes)'
+   tls.crt: '++++++++ # (1216 bytes)'
+   tls.key: '++++++++ # (1679 bytes)'
  type: kubernetes.io/tls
```

This is expected, because without `--dry-run=server`, the `lookup` function can't be used to determine if there is a diff here (for security reasons). However, when running the command above with this flag, there are still two diffs `helm diff upgrade cilium cilium/cilium --version 1.16.5 --namespace kube-system -f values.yaml`

```yaml
kube-system, hubble-relay-client-certs, Secret (v1) has changed:
  # Source: cilium/templates/hubble/tls-helm/relay-client-secret.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    name: hubble-relay-client-certs
    namespace: kube-system
  data:
    ca.crt: 'REDACTED # (1127 bytes)'
-   tls.crt: '-------- # (1200 bytes)'
-   tls.key: '-------- # (1675 bytes)'
+   tls.crt: '++++++++ # (1200 bytes)'
+   tls.key: '++++++++ # (1679 bytes)'
  type: kubernetes.io/tls

kube-system, hubble-server-certs, Secret (v1) has changed:
  # Source: cilium/templates/hubble/tls-helm/server-secret.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    name: hubble-server-certs
    namespace: kube-system
  data:
    ca.crt: 'REDACTED # (1127 bytes)'
-   tls.crt: '-------- # (1220 bytes)'
-   tls.key: '-------- # (1679 bytes)'
+   tls.crt: '++++++++ # (1220 bytes)'
+   tls.key: '++++++++ # (1675 bytes)'
  type: kubernetes.io/tls
```

The reason for this is that `lookup` is used in https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/_helpers.tpl#L79 to fetch `commonCA` values if they already exist, but https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/hubble/tls-helm/relay-client-secret.yaml and https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/hubble/tls-helm/server-secret.yaml still run their own `genSignedCert` to produce new values.

**Describe the feature you'd like**

My proposal is that the templates add their own `lookup` calls to check if those secrets already exist and if they do, don't  generate new secrets. I suspect this is not just a `diff` request and that each `helm upgrade` call actually generates new secret values, but I haven't validated on the backend.
