### ISSUE TITLE
Cilium in IPv6 only mode with hostFirewall breaks IPv4 networking on host.

### ISSUE THREAD

**Issue by m00nwtchr** [cilium/cilium#37105]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.5 and lower than v1.17.0

### What happened?

When running Cilium in IPv6 only mode (on an IPv6 only cluster), neither ingress or egress IPv4 connectivity works on the host. There are no Host Policies installed in the cluster, which means that all IPv6 traffic is allowed, but it seems that cilium is blocking all IPv4 traffic by default.

### How can we reproduce the issue?

`cilium install -f values.yaml`
```yaml
cluster:
  name: default
hostFirewall:
  enabled: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
ipam:
  operator:
    clusterPoolIPv6MaskSize: 72
    clusterPoolIPv6PodCIDRList:
      - 2001:cafe:42::/56
ipv4:
  enabled: false
# ipv4NativeRoutingCIDR: 10.42.0.0/16
ipv6:
  enabled: true
ipv6NativeRoutingCIDR: 2001:cafe:42::/56
enableIPv6Masquerade: true
k8sServiceHost: ::1
k8sServicePort: 6444
kubeProxyReplacement: true
operator:
  replicas: 1
policyAuditMode: false
policyEnforcementMode: default
prometheus:
  enabled: true
routingMode: native
bandwidthManager:
  enabled: true
  bbr: true
bpf:
  masquerade: true
k8s:
  requireIPv6PodCIDR: true
  requireIPv4PodCIDR: false
autodirectnoderoutes: true
```

### Cilium Version

1.16.5

### Kernel Version

Linux 6.12.9-hardened1-1-hardened #1 SMP PREEMPT_DYNAMIC Fri, 10 Jan 2025 19:27:38 +0000 x86_64 GNU/Linux

### Kubernetes Version

Server Version: v1.31.4+k3s1

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
