### ISSUE TITLE
Cilium can't find kube-apiserver entities

### ISSUE THREAD

**Issue by hans-fischer** [cilium/cilium#37298]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.0 and lower than v1.18.0

### What happened?

I have a kubernetes clsuer build with kubeadm on proxmox-vms. I've setup a small cluster with 3 nodes, all of them are worker nodes with api-server included.
Now I want to setup generell network deny rules to realy make use of network policies.

My thoughts are: I can not controll the ingress of internet-services, so I deny them by default.
I can controll ingress inside the cluster, so I allow egress to everywhere in the cluster but do not permit ingress by default. This way I only need to setup ingress inside the cluster. Each application set who is allow to conntect and takes this responsiblity. I reach for example a cluster-external NAS, there must be a egress rule to allow that.

My two rules to start are:
Egress:
```
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  # we can not limit ingress outside of the cluster so we limit egress outside of the cluster
  name: "default-deny-egress"
spec:
  endpointSelector: {}
  egress:
  # All traffic to a pod inside of the cluster is allowed
  - toEndpoints:
    - matchLabels: {}
  - toEntities:
    - cluster
```

Ingress:
```
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  # we can not limit ingress outside of the cluster so we limit egress outside of the cluster
  name: "default-deny-ingress"
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
  # All traffic to a pod from kube-system is allowed
  - fromEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": "kube-system"
  - fromEntities:
    - kube-apiserver   # DOES NOT WORK TO ALLOW TRAFFIC FROM API-SERVERS TO ALL SERVICES
    - remote-node       # THIS WORKS
  # allow localhost connections in general
  - fromCIDR:
    - 127.0.0.1/32
  # All traffic from a pod with the label gnp/egress-any is allowed
  - fromEndpoints:
    - matchLabels:
        gnp/egress-any: ""
```

I would to know where I can investigate further to make the entirty "kube-apiserver" working. 
How does cilium look this information up?

### How can we reproduce the issue?

1. Freshly installed Kubernetes
2. Install cilium
3. Install my two network rules
4. install metrics-server
5. wathc api-server logs

### Cilium Version

cilium:v1.16.6

### Kernel Version

Linux k8s-stage-delta 6.8.0-51-generic #52-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec  5 13:09:44 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.31.0

### Sysdump

[cilium-sysdump-20250128-090947.zip](https://github.com/user-attachments/files/18570128/cilium-sysdump-20250128-090947.zip)

### Relevant log output

```shell
E0127 20:46:41.439387       1 remote_available_controller.go:448] "Unhandled Error" err="v1beta1.metrics.k8s.io failed with: failing or missing response from https://10.253.55.224:443/apis/metrics.k8s.io/v1beta1: Get \"https://10.253.55.224:443/apis/metrics.k8s.io/v1beta1\": context deadline exceeded" logger="UnhandledError"
```

### Anything else?

Thank you for your great work. Looking forward to switch from cilico to cilium.
Because you dont have a enterprise-paywall and allow me to setup network-policies with DNS lookup. 

Love that!

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
