### ISSUE TITLE
CiliumL2AnnouncementPolicy creates lease outside of nodeSelector scope

### ISSUE THREAD

**Issue by adriankurtasinski** [cilium/cilium#37329]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.6 and lower than v1.17.0

### What happened?

When I create CiliumL2AnnouncementPolicy with nodeSelector for specified nodes sometimes lease is created on node from zone-1 L2 announcement is working correctly.

The problem is that lease is created randomly not respecting nodeSelector and when it's created outside zone-1 DC it will not respond to ARP request.

### How can we reproduce the issue?

CiliumL2AnnouncementPolicy:

```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: cilium-l2-announcement-policy-zone-1
spec:
  externalIPs: true
  interfaces:
  - ens19
  loadBalancerIPs: true
  nodeSelector:
    matchExpressions:
    - key: topology.kubernetes.io/zone
      operator: In
      values:
      - zone-1
  serviceSelector:
    matchLabels:
      app: istio-ingress
```

or

```yaml
  nodeSelector:
    matchLabels:
      topology.kubernetes.io/zone: zone-1
```

### Cilium Version

16.6

### Kernel Version

Linux 6.8.0-51-generic

### Kubernetes Version

v1.30.4

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by angeloxx** [comment]
We are experiencing a similar issue. We use a **nodeSelector** with three conditions and rely on these labels to cordon nodes and migrate leases across the available nodes. 

Initially, all ingress nodes match the CiliumL2AnnouncementPolicy, and with Cilium version 1.16.5, the leases are evenly distributed among all nodes. However, when one of the ingress nodes changes its label (to cordon it and migrate the service), the Cilium agent only migrates 30-50% of the leases to the remaining nodes without any clear explanation. The old nodes, that doesn't matches the selector, continues to hold the lease.

Our policy is:
```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  generation: 1
  name: net-172.25.164.0-22
spec:
  externalIPs: true
  interfaces:
  - eth0
  loadBalancerIPs: true
  nodeSelector:
    matchExpressions:
    - key: network.company.com/tier.ingress
      operator: In
      values:
      - tier-2
    - key: network.company.com/subnet
      operator: In
      values:
      - net-172.25.164.0-22
    - key: network.company.com/ingress.active
      operator: In
      values:
      - "true"
  serviceSelector:
    matchLabels:
      network.company.com/subnet: net-172.25.164.0-22
``` 
and we use **network.company.com/ingress.active** to enable/disable nodes. The effect is similar to the described in the ticket, leases continues to be announced by the wrong nodes.
