### ISSUE TITLE
Inconsistent Policy Map State for Endpoints with Same Identity

### ISSUE THREAD

**Issue by vipul-21** [cilium/cilium#37334]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.6 and lower than v1.17.0

### What happened?

On creating the Azure BYOCNI with cilium, seeing inconsistent results to the policy map of endpoints with same identity. We deployed a set of nginx pods and applied the policy that selects all the endpoints. On checking the policy state(attached screenshot) we are seeing difference in the map state for same set of identities.

![Image](https://github.com/user-attachments/assets/37e5c366-af0b-4be5-b2fe-81acf1c15d77)

![Image](https://github.com/user-attachments/assets/4fcf1283-f943-4652-830c-a5f9826f3620)

### How can we reproduce the issue?

1. Create an Azure BYO CNI cluster using the doc: https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/
2. Manually deploy cilium daemonset and operator deployment with config maps.(files are attached)
3. Deployed the nginx pods through a script(`deploy-daemonset.sh`) and deployed the cilium network policy(`cnp-test-1.yaml`)
4. Once the policy is applied, we run the `cilium bpf policy list`, and observe differences in the map state for different endpoints. These endpoints have the same identity, so one would expect that the policy application is consistent. If the issue doesn't appear at first attempt, edit the CNP to remove the fromEntities part in the ingress, and then add it back.
```
# cnp-test-1.yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-from-nodes
  namespace: cilium-policy-test    
spec:
  endpointSelector: {}  # Matches all pods in the cluster
  ingress:
    - fromEntities:
      - host
      - remote-node
    - toPorts:
      - ports: 
        - port: "53"
          protocol: TCP
        - port: "443"
          protocol: TCP
        - port: "53"
          protocol: UDP
        - port: "443"
          protocol: UDP
        - port: "53"
          protocol: SCTP
        - port: "443"
          protocol: SCTP 
    - fromCIDR:
      - "10.0.0.0/8"
      toPorts:
      - ports:
        - port: "53"
          protocol: TCP
        - port: "53"
          protocol: UDP
        - port: "53"
          protocol: SCTP
        - port: "443"
          protocol: TCP
        - port: "443"
          protocol: UDP
        - port: "443"
          protocol: SCTP            

```

```
# deploy-daemonset.sh
for (( i=1; i<=10; i++ ))
do
    cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset-$i
  namespace: cilium-policy-test
spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
EOF
done

```
Note: The ports in the policy map and the ports of nginx pods are not same as this is just a test deployment.
[cilium-ds.json](https://github.com/user-attachments/files/18593380/cilium-ds.json)

[cilium-configmap.json](https://github.com/user-attachments/files/18593377/cilium-configmap.json)

[cilium-operator-deployment.json](https://github.com/user-attachments/files/18593371/cilium-operator-deployment.json)

### Cilium Version

1.16.5 (The drop down of cilium version does not have an option that selects 1.16.5 version)

### Kernel Version

5.15.0-1078-azure

### Kubernetes Version

1.30.7

### Sysdump

[cilium-sysdump-20250129-120302.zip](https://github.com/user-attachments/files/18593790/cilium-sysdump-20250129-120302.zip)

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
