### ISSUE TITLE
Getting "no healthy upstream" from ingress in Kind

### ISSUE THREAD

**Issue by ernado** [cilium/cilium#37456]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.0 and lower than v1.18.0

### What happened?

I'm getting `no healthy upstream` from ingress, but pods are alive.

Also, some ingresses work and some does not with no differences between them.
For example, "hubble.localhost" works for me.

### How can we reproduce the issue?

I'm using following kind config:
```yaml
# _hack/vega.kind.yml
---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  disableDefaultCNI: true
  podSubnet: 10.1.0.0/16
  serviceSubnet: 10.100.1.0/24
  kubeProxyMode: none
  dnsSearch: []
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        apiVersion: kubeadm.k8s.io/v1beta2
        kind: InitConfiguration
        nodeRegistration:
          taints: []
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 8080
        hostPort: 80
        listenAddress: 127.0.0.1
        protocol: TCP
```
Ingress controller configured as follows:
```yaml
# _hack/cilium.yml
# ...
ingressController:
  enabled: true
  loadbalancerMode: shared
  default: true
  enforceHttps: false
  hostNetwork:
    enabled: true
    sharedListenerPort: 8080
  service:
    externalTrafficPolicy: null
    type: ClusterIP
# ...
```

I've tried to create smaller reproducer but failed, everything works fine in simpler environment.
Anyway, here is my toy PaaS where I've reproduced this issue:

https://github.com/go-faster/vega/tree/no-upstream-repro

Requrements: kind, kubectl, helm, cilium cli, docker, go

```bash
git clone -b no-upstream-repro https://github.com/go-faster/vega.git
cd vega

helm repo add cilium https://helm.cilium.io
helm repo add clickhouse-operator https://docs.altinity.com/clickhouse-operator/
helm repo add faster https://go-faster.github.io/charts
helm repo add grafana https://grafana.github.io/helm-charts
helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo add vm https://victoriametrics.github.io/helm-charts/
helm repo add nats https://nats-io.github.io/k8s/helm/charts/
helm repo add minio-operator https://operator.min.io

helm repo update

# this will compile application, setup kind cluster and install a lot of stuff
# with helm like grafana
#
# See https://github.com/go-faster/vega/blob/no-upstream-repro/cmd/vega-install/main.go
go run ./cmd/vega-install

export KUBECONFIG=_out/kubeconfig.yml
kubectl -n vega rollout status --timeout=2m deployment api
kubectl get pods -n vega -l vega.app=vega.api
kubectl -n vega describe ingress api 
```

```console
$ curl -v http://vega.localhost
* Host vega.localhost:80 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:80...
* connect to ::1 port 80 from ::1 port 49898 failed: Connection refused
*   Trying 127.0.0.1:80...
* Connected to vega.localhost (127.0.0.1) port 80
> GET / HTTP/1.1
> Host: vega.localhost
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< content-length: 19
< content-type: text/plain
< date: Wed, 05 Feb 2025 22:40:35 GMT
< server: envoy
< 
* Connection #0 to host vega.localhost left intact
no healthy upstream
```

### Cilium Version

```console
$ cilium -n cilium version
cilium-cli: v0.16.24 compiled with go1.23.4 on linux/amd64
cilium image (default): v1.16.6
cilium image (stable): v1.17.0
cilium image (running): 1.17.0
```

### Kernel Version

```console
$ uname -a
Linux nexus 6.8.0-52-generic #53-Ubuntu SMP PREEMPT_DYNAMIC Sat Jan 11 00:06:25 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```console
$ kubectl version
Client Version: v1.32.1
Kustomize Version: v5.5.0
Server Version: v1.32.0
```

### Sysdump

[cilium-sysdump-20250206-014235.zip](https://github.com/user-attachments/files/18680147/cilium-sysdump-20250206-014235.zip)

### Relevant log output

```shell

```

### Anything else?

```console
$ kubectl -n vega describe ingress api 
Name:             api
Labels:           <none>
Namespace:        vega
Address:          
Ingress Class:    cilium
Default backend:  <default>
Rules:
  Host            Path  Backends
  ----            ----  --------
  vega.localhost  
                  /   api:80 (10.1.1.144:8080)
Annotations:      <none>
Events:           <none>
```
```yaml
# _hack/k8s/ingress.yml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: vega
spec:
  ingressClassName: cilium
  rules:
    - host: vega.localhost
      http:
        paths:
          - backend:
              service:
                name: api
                port:
                  number: 80
            path: /
            pathType: Prefix

````

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
