### ISSUE TITLE
DNS Resolution and Inter-Pod Communication not working with cilium deployed in aws-cni chaining mode and SecurityGroupPolicy deployed

### ISSUE THREAD

**Issue by themoonraker13** [cilium/cilium#37475]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.6 and lower than v1.17.0

### What happened?

We are looking to lock down inbound/outbound traffic to/from our pods and hence exploring Security Group for Pods. 

I have deployed a test pod that has a security group associated with it based on the official AWS documentation [here](https://docs.aws.amazon.com/eks/latest/userguide/sg-pods-example-deployment.html).

However, the pod is unable to access the nginx app/service deployed:
```
# curl my-service
curl: (6) Could not resolve host: my-service
```

On using the IP address of the service, the pod was able to access the service:
```
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

This led me to investigate DNS and I found that it would not resolve any internal/external domains
```
root@my-deployment-69bcff5557-4pl6c:/# nslookup my-service
;; connection timed out; no servers could be reached


root@my-deployment-69bcff5557-4pl6c:/# nslookup google.com
;; connection timed out; no servers could be reached


root@my-deployment-69bcff5557-4pl6c:/#
```

On checking, the pod traffic I noticed that it is indeed reaching out to the coredns service:
```
$ hubble observe --server localhost:4245 --pod my-deployment-69bcff5557-4pl6c
default/my-deployment-69bcff5557-4pl6c:57600 (ID:28368) -> kube-system/coredns-6869fd76cf-7fzth:53 (ID:46427) to-stack FORWARDED (UDP)
default/my-deployment-69bcff5557-4pl6c:55191 (ID:28368) -> kube-system/coredns-6869fd76cf-smrv4:53 (ID:46427) to-stack FORWARDED (UDP)
default/my-deployment-69bcff5557-4pl6c:55191 (ID:28368) -> kube-system/coredns-6869fd76cf-smrv4:53 (ID:46427) to-endpoint FORWARDED (UDP)
default/my-deployment-69bcff5557-4pl6c:55191 (ID:28368) <- kube-system/coredns-6869fd76cf-smrv4:53 (ID:46427) to-stack FORWARDED (UDP)
```

Moreover, the pod is also not able to communicate with any other pods in the network!

### How can we reproduce the issue?

1. [Install cilium with AWS CNI chaining mode](https://docs.cilium.io/en/stable/installation/cni-chaining-aws-cni/#aws-vpc-cni-plugin)
2. [Enable security group for pods](https://docs.cilium.io/en/stable/installation/cni-chaining-aws-cni/#enabling-security-groups-for-pods-eks)
3. Deploy SecurityGroupPolicy and a test application as discussed [here](https://docs.aws.amazon.com/eks/latest/userguide/sg-pods-example-deployment.html)
4. Exec into the deployed pod and run the tests I've discussed above (hitting app/service, nslookup, observe pod traffic using hubble, reaching other pods, etc.)

**NOTE:** I've also tried setting inbound/outbound rules on the pod security group to allow all traffic from the world, but that didn't help either.

### Cilium Version

1.16.3

We've deployed cilium using helm with following config params:
```
      source:
        repoURL: https://helm.cilium.io
        chart: cilium
        targetRevision: "1.16.3"
        helm:
          passCredentials: false
          releaseName: cilium
          parameters:
            - name: "cni.chainingMode"
              value: "aws-cni"
            - name: "cni.exclusive"
              value: "false"
            - name: "enableIPv4Masquerade"
              value: "false"
            - name: "routingMode"
              value: "native"
            - name: "endpointRoutes.enabled"
              value: "true"
            - name: "encryption.enabled"
              value: "true"
            - name: "encryption.type"
              value: "wireguard"
            - name: "hubble.relay.enabled"
              value: "true"
            - name: "hubble.ui.enabled"
              value: "true"
            - name: "envoy.prometheus.enabled"
              value: "false"
            - name: "l2NeighDiscovery.enabled"
              value: "false"
            - name: logOptions.format
              value: json
```

**NOTE: We have disable `l2NeighDiscovery` to avoid errors and excessive mem usage with cilium 1.16.0-3. See https://github.com/cilium/cilium/issues/34020 for more details!

### Kernel Version

6.1.119-129.201.amzn2023.aarch6

### Kubernetes Version

1.31

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
