### ISSUE TITLE
Error in template when using `envoy.log.format_json` with Helm Chart

### ISSUE THREAD

**Issue by arthur-leclerc** [cilium/cilium#37470]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.0 and lower than v1.18.0

### What happened?

Hi, 👋🏻 

Since this PR https://github.com/cilium/cilium/pull/36820/, when we use `envoy.log.format_json` with the Helm chart, we get the following error when Helm generate `bootstrap-config.json` file:

```
error converting YAML to JSON: yaml: line 216: did not find expected key
```

It seems that the new yaml template is not right [here](https://github.com/cilium/cilium/pull/36820/files#diff-628a1c76addc87d7b68d12832e9dce309a4eafb490ac466c54db01af496b4854R278-R283).

Currently, the template gives this [result](https://helm-playground.com/#t=LQhQEMAdIGwSwMbgC5wPYDsAyaDmBhTAMzlwC5QACSmPAMTQCcBbFC66gb0%2BEriMoA6AGrgYAVwCmAZ0GSMANzQBPQbVyCiTVsgD6AK2mZKAXxNUOhzAxZtKAIm5DREmXMUq1eTdpQGjGJQAPpTIaABSAaYm9hZcPJSSMNKS0XGhkgAeyDY6ZA5OImJSsvJKquo%2BtsjRsRyU3LzyACbRQA&v=LQhQFMDsDcHsE8BcoAEKA2sDmy1oGawBOAtgIYAuiKA5DanoaZQPoBWAzrJLnmgCaVw1GgFIAmsFEkp-ACqi5AOlHh6fNBQAWRcGX4sAlvxGiK6jVwCuRAMbgW6Q5GG1RHRKIDEFvunDQ4Oim6L54mFhY4ESmkGFoJOAcHGRRpmw0QA):

```yaml
---
applicationLogConfig:
  logFormat:
    jsonFormat: "{"date":"%Y-%m-%dT%T.%e","level":"%l","logger":"%n","message":"%j","source_line":"%s:%#","thread_id":"%t"}"
```

It should give this [result](https://helm-playground.com/#t=LQhQEMAdIGwSwMbgC5wPYDsAyaDmBhTAMzlwC5QACSmPAMTQCcBbFC66gb0%2BEriMoA6AGrgYAVwCmAZ0GSMANzQBPQbVyCiTVsgD6AK2mZKAXxNUOhzAxZtK3SsjQBNcMxhDREmXMUq1eJraKAZGGJQAPpQYcBgAJvLIlABspuYc9jyUkjDSkmkW1MiSAB7INjpklABEDiJiUrLySqrqQbZJZtWFmbzycWlAA&v=LQhQFMDsDcHsE8BcoAEKA2sDmy1oGawBOAtgIYAuiKA5DanoaZQPoBWAzrJLnmgCaVw1GgFIAmsFEkp-ACqi5AOlHh6fNBQAWRcGX4sAlvxGiK6jVwCuRAMbgW6Q5GG1RHRKIDEFvunDQ4Oim6L54mFhY4ESmkGFoJOAcHGRRpmw0QA) if I'm not mistaken:

```yaml
---
applicationLogConfig:
  logFormat:
    jsonFormat: 
      date: '%Y-%m-%dT%T.%e'
      level: '%l'
      logger: '%n'
      message: '%j'
      source_line: '%s:%#'
      thread_id: '%t'
```

This template change should resolve the issue:

```diff
---
applicationLogConfig:
  logFormat:
    {{- if .Values.envoy.log.format_json }}
-    jsonFormat: "{{ .Values.envoy.log.format_json | toJson }}"
+    jsonFormat: {{ toYaml .Values.envoy.log.format_json | nindent 6 }}
    {{- else }}
    textFormat: "{{ .Values.envoy.log.format }}"
    {{- end }}
```

### How can we reproduce the issue?

values.yaml

```yaml
envoy:
  log:
    format_json:
      date: '%Y-%m-%dT%T.%e'
      thread_id: '%t'
      source_line: '%s:%#'
      level: '%l'
      logger: '%n'
      message: '%j'
```

### Cilium Version

1.17.0

### Kernel Version

NaN

### Kubernetes Version

Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.31.4-eks-2d5f260

### Regression

v1.17.0-rc.0

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
