### ISSUE TITLE
Hubble is not working

### ISSUE THREAD

**Issue by SaymonPhoenix** [cilium/cilium#37480]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.6 and lower than v1.17.0

### What happened?

Hubble UI doesn't show any connections other than Ingress > Hubble UI in namespace kube-system

![Image](https://github.com/user-attachments/assets/e643c82a-584a-4f0e-9934-7c7082b7284b)

![Image](https://github.com/user-attachments/assets/b6ddf91f-2abd-45fe-9020-4193dc77e5ad)

### How can we reproduce the issue?

1. Install Cilium with Hubble enabled using Helm
2. Install demo app cilium (https://docs.cilium.io/en/stable/gettingstarted/demo/#starwars-demo)
3. Go to Ingress Hubble UI
4. Only Ingress > Hubble UI connection is shown in namespace kube-system
Values ​​with which Cilium was installed:
```yaml
rollOutCiliumPods: true
l2announcements:
  enabled: true
externalIPs:
  enabled: true
hostPort:
  enabled: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      hosts:
        - hubble-ui.example.com
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - http
devices: eth0
kubeProxyReplacement: true
k8sServiceHost: 10.10.10.10
k8sServicePort: 6443
operator:
  replicas: 1
ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  service:
    loadBalancerIP: 10.10.10.11
```

### Cilium Version

1.15.13
1.16.6
1.17.0

### Kernel Version

6.1.90-1-generic

### Kubernetes Version

v1.29.10

### Sysdump

[cilium-sysdump-20250207-144859.zip](https://github.com/user-attachments/files/18705985/cilium-sysdump-20250207-144859.zip)

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
