### ISSUE TITLE
Coredns fails connecting to kubernetes api

### ISSUE THREAD

**Issue by kperreau** [cilium/cilium#37537]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.0 and lower than v1.18.0

### What happened?

When I set `bpf.masquerade` to true, the CoreDNS service can no longer query the Kubernetes API.
However, it works if I disable it with `bpf.masquerade: false` or if I enable `bpf.hostLegacyRouting: true`.

I would like to fully benefit from the improved performance that Cilium could provide by enabling BPF and BBR. However, the option that makes it work (`hostLegacyRouting`) prevents me from fully leveraging these performance gains and enabling BBR.
So, my goal is to make it work with the options `bpf.masquerade: true` and `bpf.hostLegacyRouting: false`.

_I know there are already a few issues on this topic, but none have really helped me fix my problem or provided a clear answer. I'm giving it a shot by creating my own issue._

### How can we reproduce the issue?

I'm using helm to install Cilium.

Here is my config:
```yaml
cni:
  binPath: /var/snap/microk8s/current/opt/cni/bin
  confPath: /var/snap/microk8s/current/args/cni-network
  customConf: false
  logFile: /var/snap/microk8s/current/var/run/cilium/cilium-cni.log
daemon:
  runPath: /var/snap/microk8s/current/var/run/cilium
cgroup:
  hostRoot: /var/snap/microk8s/current/var/run/cilium/cgroupv2

ipam:
  operator:
    clusterPoolIPv4PodCIDRList: ["10.1.0.0/16"]
    clusterPoolIPv4MaskSize: 24

k8sServiceHost: "127.0.0.1"
k8sServicePort: "16443"
kubeProxyReplacement: "true"

bandwidthManager:
  enabled: true
  bbr: true # can't be true if hostLegacyRouting is enabled

routingMode: native
ipv4NativeRoutingCIDR: "10.1.0.0/16"
enableIPv4Masquerade: true
autoDirectNodeRoutes: true

bpf:
  masquerade: true # works if i turn it off
  datapathMode: netkit
  tproxy: true
  preallocateMaps: true
  hostLegacyRouting: false # works if i turn it on
ipMasqAgent:
  enabled: true
  config:
    masqLinkLocal: true
    nonMasqueradeCIDRs:
      - 10.0.0.0/8
      - 192.168.0.0/16
l2announcements:
  enabled: true
externalIPs:
  enabled: true

rollOutCiliumPods: true
```

### Cilium Version

Client: 1.17.0 c2bbf787 2025-01-31T15:05:59+01:00 go version go1.23.5 linux/amd64
Daemon: 1.17.0 c2bbf787 2025-01-31T15:05:59+01:00 go version go1.23.5 linux/amd64

### Kernel Version

6.8.0-52-generic

### Kubernetes Version

1.32.0

### Relevant log output

```shell
[INFO] plugin/kubernetes: pkg/mod/k8s.io/client-go@v0.31.2/tools/cache/reflector.go:243: failed to list *v1.Namespace: Get "https://10.152.183.1:443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 10.152.183. │
[ERROR] plugin/kubernetes: Unhandled Error                                                                                                                                                                                
[INFO] plugin/kubernetes: pkg/mod/k8s.io/client-go@v0.31.2/tools/cache/reflector.go:243: failed to list *v1.Service: Get "https://10.152.183.1:443/api/v1/services?limit=500&resourceVersion=0": dial tcp 10.152.183.1:44 │
[ERROR] plugin/kubernetes: Unhandled Error                                                                                                                                                                                
[INFO] plugin/kubernetes: pkg/mod/k8s.io/client-go@v0.31.2/tools/cache/reflector.go:243: failed to list *v1.EndpointSlice: Get "https://10.152.183.1:443/apis/discovery.k8s.io/v1/endpointslices?limit=500&resourceVersio │
[ERROR] plugin/kubernetes: Unhandled Error                                                                                                                                                                                
[INFO] plugin/ready: Still waiting on: "kubernetes"
```

### Anything else?

I'm using microk8s (v1.32.0) on ubuntu-server (Ubuntu 24.04.1 LTS) in ha-cluster 3 nodes.

kube service api: `10.152.183.1`
coredns version: `1.12.0`

### Clusters nodes
```
miniserv-1: 192.168.1.10
miniserv-2: 192.168.1.11
miniserv-3: 192.168.1.12
```

### Some microk8s confs/args
```
--cluster-cidr=10.1.0.0/16
--service-cluster-ip-range=10.152.183.0/24
--secure-port=16443
--cluster-dns=10.152.183.10
```

### Cilium status
```
$ cilium status
KVStore:                 Disabled
Kubernetes:              Ok         1.32 (v1.32.0) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    True   [enp87s0    192.168.1.12 2a01:e0a:b5d:9a30:5a47:caff:fe7a:b220 fe80::5a47:caff:fe7a:b220 (Direct Routing)]
Host firewall:           Disabled
SRv6:                    Disabled
CNI Chaining:            none
CNI Config file:         successfully wrote CNI configuration file to /host/etc/cni/net.d/05-cilium.conflist
Cilium:                  Ok   1.17.0 (v1.17.0-c2bbf787)
NodeMonitor:             Listening for events on 20 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok
IPAM:                    IPv4: 19/254 allocated from 10.1.2.0/24,
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        EDT with BPF [BBR] [enp87s0]
Routing:                 Network: Native   Host: BPF
Attach Mode:             TCX
Device Mode:             netkit
Masquerading:            BPF (ip-masq-agent)   [enp87s0]   10.1.0.0/16 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       123/123 healthy
Proxy Status:            OK, ip 10.1.2.157, 0 redirects active on ports 10000-20000, Envoy: external
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 2369/4095 (57.85%), Flows/s: 22.94   Metrics: Disabled
Encryption:              Disabled
Cluster health:          3/3 reachable   (2025-02-10T20:37:06Z)
Name                     IP              Node   Endpoints
Modules Health:          Stopped(0) Degraded(0) OK(111)
```

### Ip routes
```
$ ip route show
default via 192.168.1.254 dev enp87s0 proto static
10.1.0.0/24 via 192.168.1.10 dev enp87s0 proto kernel
10.1.1.0/24 via 192.168.1.11 dev enp87s0 proto kernel
10.1.2.0/24 via 10.1.2.157 dev cilium_host proto kernel src 10.1.2.157
10.1.2.157 dev cilium_host proto kernel scope link
10.152.183.1 via 192.168.1.254 dev enp87s0
192.168.1.0/24 dev enp87s0 proto kernel scope link src 192.168.1.12
```

Calling the API directly from the node works, but it times out from a pod inside the Kubernetes cluster.
```
# Directly from the node
$ curl -k https://10.152.183.1:443
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
