### ISSUE TITLE
check-log-errors triggers on fallback values for hubble-ui backend

### ISSUE THREAD

**Issue by Dutchy-** [cilium/cilium#37546]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.0 and lower than v1.18.0

### What happened?

1. Install cilium with helm (template)
2. Run connectivity test

It triggers on

```
  ❌ Found 5 logs in aks-dsolv-test/kube-system/hubble-ui-77555d5dcf-xnwln (backend) matching list of errors that must be investigated:
time="2025-02-11T06:12:18Z" level=warning msg="using fallback value for env var" fallback=false var=TLS_TO_RELAY_ENABLED (1 occurrences)
time="2025-02-11T06:12:18Z" level=warning msg="using fallback value for env var" fallback=false var=CORS_ENABLED (1 occurrences)
time="2025-02-11T06:12:18Z" level=warning msg="using fallback value for env var" fallback=false var=E2E_TEST_MODE (1 occurrences)
time="2025-02-11T06:12:18Z" level=warning msg="using fallback value for env var" fallback= var=E2E_LOGFILES_BASEPATH (1 occurrences)
time="2025-02-11T06:12:18Z" level=warning msg="using fallback value for env var" fallback=false var=GOPS_ENABLED (1 occurrences)
```

I was able to work around this issue by adding this to the backend configuration.

```
        extraEnv:
          - name: TLS_TO_RELAY_ENABLED
            value: "false"
          - name: CORS_ENABLED
            value: "false"
          - name: E2E_TEST_MODE
            value: "false"
          - name: E2E_LOGFILES_BASEPATH
            value: ""
          - name: GOPS_ENABLED
            value: "false"
```

I expect a helm install to never complain about issues like this

### How can we reproduce the issue?

Install cilium with helm using:

```
helm template --namespace kube-system -f values.yaml . | kubectl apply -f -
```

and Chart.yaml

```
apiVersion: v2
name: cilium
description: Cilium
type: application
kubeVersion: ">= 1.19.0-0"
version: "1.0.0"
keywords:
  - cilium

dependencies:
  - name: cilium
    version: "1.17.0"
    repository: "https://helm.cilium.io"
```

and values

```
cilium:
  namespaceOverride: kube-system
  aksbyocni:
    enabled: true
  hubble:
    enabled: true
    relay:
      enabled: true
    ui:
      enabled: true
```

and then run the connectivity test

### Cilium Version

Cilium version installed: v1.17.0

Cilium cli version:

```
❯ cilium version
cilium-cli: v0.16.24 compiled with go1.23.5 on darwin/arm64
cilium image (default): v1.16.6
cilium image (stable): v1.17.0
cilium image (running): unknown. Unable to obtain cilium version. Reason: release: not found
```

### Kernel Version

I'm going to guess my kernel versions are not relevant here

### Kubernetes Version

```
❯ kubectl version
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.3
```

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
