### ISSUE TITLE
LRP: skipRedirectFromBackend not working for ipv6

### ISSUE THREAD

**Issue by ysksuzuki** [cilium/cilium#37575]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.0 and lower than v1.18.0

### What happened?

It seems that the `skipRedirectFromBackend`  in CLRP is not working correctly for IPv6. When a backend sends a packet to the frontend, the redirection should be skipped if `skipRedirectFromBackend` is true. However, instead of skipping the redirection, the packet loops back to the backend.

### How can we reproduce the issue?

1. Install Cilium with LRP enabled
2. Apply CLRP and CNP
```yaml
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: lrp-address-matcher-skip-redirect-from-backend-v6
  namespace: cilium-test-1
spec:
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        lrp: backend
    toPorts:
    - name: tcp-8080
      port: "8080"
      protocol: TCP
  redirectFrontend:
    addressMatcher:
      ip: fd00::169:254:169:255
      toPorts:
      - name: tcp
        port: "80"
        protocol: TCP
  skipRedirectFromBackend: true
---
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: lrp-address-matcher-skip-redirect-from-backend-v4
  namespace: cilium-test-1
spec:
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        lrp: backend
    toPorts:
    - name: tcp-8080
      port: "8080"
      protocol: TCP
  redirectFrontend:
    addressMatcher:
      ip: 169.254.169.255
      toPorts:
      - name: tcp
        port: "80"
        protocol: TCP
  skipRedirectFromBackend: true
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: client-egress-to-cidr-lrp-deny
  namespace: cilium-test-1
spec:
  egressDeny:
  - toCIDRSet:
    - cidr: 169.254.169.255/32
    - cidr: fd00::169:254:169:255/128
  endpointSelector:
    matchLabels:
      any:lrp: backend
```

3. curl from the backend to the frontend address

```
# For ipv4, the redirect from backend is skipped and dropped via CNP
$ kubectl -n cilium-test-1 exec lrp-backend-5dc456df96-skphd -- curl -s http://169.254.169.255:80

$ kubectl -n kube-system exec cilium-g5xqq  -- cilium monitor -t drop
xx drop (Policy denied by denylist) flow 0x305f8dd1 to endpoint 0, ifindex 16, file bpf_lxc.c:1354, , identity 10753->16777224: 10.244.1.36:60822 -> 169.254.169.255:80 tcp SYN
xx drop (Policy denied by denylist) flow 0xa7fd5082 to endpoint 0, ifindex 16, file bpf_lxc.c:1354, , identity 10753->16777224: 10.244.1.36:60822 -> 169.254.169.255:80 tcp SYN

# For ipv6, the redirect from backend isn't skipped
$ kubectl -n cilium-test-1 exec lrp-backend-5dc456df96-skphd -- curl -s http://[fd00::169:254:169:255]:80
<html>
  <head>
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
      integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="style.css" />
    <title>JSON Server</title>
  </head>


$ kubectl -n kube-system exec cilium-g5xqq  -- cilium service list
46   [fd00::169:254:169:255]:80/TCP   LocalRedirect   1 => [fd00:10:244:1::9dd5]:8080/TCP (active)   
47   169.254.169.255:80/TCP           LocalRedirect   1 => 10.244.1.36:8080/TCP (active) 
```

### Cilium Version

1.18.0-dev

### Kernel Version

6.8.0-52-generic

### Kubernetes Version

v1.30.0

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
