### ISSUE TITLE
Cilium fails to run on new node with Ubuntu 22.04 Jammy with FIPS kernel

### ISSUE THREAD

**Issue by mainak90** [cilium/cilium#37594]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.15.13 and lower than v1.16.0

### What happened?

Running this on a test environment. 
1. Cilium version tested --> `1.13.16` , `1.14.17` , `1.15.8` 
2. Operating system: Ubuntu 2204 Jammy with `5.15.0-1077-aws-fips` kernel on the node that fails. 
3. Debug mode enabled and for all flow kvstore envoy datapath policy.
4. Running in a kubeadm based env. Installed with helm templating. 
Cilium config 
```
dnsProxy:
  endpointMaxIpPerHostname: 250

bpf:
  lbMapMax: 131072

ipam:
  mode: kubernetes
keepDeprecatedLabels: true
kubeProxyReplacement: disabled


updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 10%

proxy:
  prometheus:
    port: 9095
pprof:
  enabled: true
iptablesRandomFully: true
prometheus:
  enabled: true
  port: 9090
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
upgradeCompatibility: "1.7"
```

# Issue
Cilium dies after running for a few minutes. 
kubectl describe points to a graceful shutdown, seems like the hive subsystem just got a healthz check failure. But the reason seems to be be very difficult to ascertain. 
What I have done so far ? 
1. Checked containerd logs, containerd logs seems to mimic mostly what we see in cilium logs.
2. Cilium just randomly dies, the healthz endpoint just starts dropping an HTTP retcode 000 instead of 200 and thats when the hive subsystem stops the container and it restarts and the cycle continues.
3. Happens on all versions I have tested of cilium, I tested 1.13.16, 1.14.17, 1.15.8 and it all behaves the same.
4. Many times the kubelet logs as well as the /var/run/cilium/cilium-cni.log in the node complains that it cannot find socket on /var/run/cilium/cilium.sock but I think thats mostly due to the side effect of the container restart, as part of the graceful shutdown of the cilium agent container.
5. I tried to add the cni config directly into containerd /etc/containerd/config.toml no help anyhow.
6. The sandbox restart generally happens it seems because the network namespace gets recreated whenever cilium pods restart(till they reach a crashbackloopoff) and they then force the other pod sandboxes to update.

Logs: 

[cilium-agent.log](https://github.com/user-attachments/files/18774343/cilium-agent.log)

Sysdump: 
Have created sysdump which is too large to upload for now, will upload it if requested.

### How can we reproduce the issue?

1. Install cilium with helm
2. Use Ubuntu jammy with specified kernel version

### Cilium Version

1.15.8, 1.14.17, 1.13.16

### Kernel Version

5.15.0-1077-aws-fips

### Kubernetes Version

1.26.5

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
