### ISSUE TITLE
Helm: YAML-to-JSON Conversion Error Due to Improper Escaping in Envoy Log Config

### ISSUE THREAD

**Issue by kahirokunn** [cilium/cilium#37655]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.0 and lower than v1.18.0

### What happened?

When configuring the Envoy log settings in the Cilium Helm chart as shown below:

```yaml
envoy:
  log:
    defaultLevel: error
    format_json:
      date: "%Y-%m-%dT%T.%e"
      thread_id: "%t"
      source_line: "%s:%#"
      level: "%l"
      logger: "%n"
      message: "%j"
```

the generated ConfigMap fails with the following error:

```
# Source: cilium/templates/cilium-envoy/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-envoy-config
  namespace: default
data:
  # Keep the key name as bootstrap-config.json to avoid breaking changes
  bootstrap-config.json: |
    {"Error":"error converting YAML to JSON: yaml: line 216: did not find expected key"}
```

This error indicates that there is an issue with escaping the log format strings during the YAML-to-JSON conversion. The expected output should correctly escape these values.

### How can we reproduce the issue?

1. Configure the Helm values for Envoy logging as shown above.
2. Deploy the Cilium Helm chart.
3. Observe the YAML-to-JSON conversion error in the generated ConfigMap.

### Cilium Version

quay.io/cilium/cilium:v1.17.1@sha256:8969bfd9c87cbea91e40665f8ebe327268c99d844ca26d7d12165de07f702866

### Kernel Version

`Linux ip-10-0-52-232.ap-northeast-1.compute.internal 6.1.124 #1 SMP Sat Jan 25 00:17:43 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux`

### Kubernetes Version

Server Version: v1.30.8-eks-2d5f260

### Relevant log output

```shell

```

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
