### ISSUE TITLE
static policy watcher ignores files with multiple YAML objects

### ISSUE THREAD

**Issue by radhupr** [cilium/cilium#37724]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.1 and lower than v1.18.0

### What happened?

We have couple of cilium cluster wide network policies  (for worker, coredns and konnectivity agent) which are added as static policies with below config
```
extraArgs:
  - --static-cnp-path=/policies
extraHostPathMounts:
  - name: static-policies
    mountPath: /policies
    hostPath: /data/k0s/cilium
    hostPathType: Directory
```
Recently we bumped the version from 1.16.6 to 1.17.1. While in dev cluster we had policy enforce mode `never` it didnt give any error/issues. But while upgrading other clusters which had policy enforce mode `always` failed the static policy to be taken into use. 
We tried to switch to enable/disable the enforce mode in 1.17.1 version but it didnt work. At the end, we had to add the static policies to the cluster and apply them manually to get it working.
Could you check whats breaking the static policy behavior in new version?

### How can we reproduce the issue?

1. Install cilium 1.16.6, have policy enforce mode 'always' and load some static cilium cluster wide network policies
2. Upgrade cilium to 1.17.x 
3. Notice that the static policies are not taken into effect

### Cilium Version

1.17.1

### Kernel Version

Red Hat Enterprise Linux release 8.10 (Ootpa) (4.18.0-553.16.1.el8_10.x86_64)

### Kubernetes Version

v1.30.3

### Relevant log output

```shell
Connection / polciies defined in the static policies fail. Eg: connection failing from our cilium agent logs

stream logs failed Get "https://10.25.216.7:10250/containerLogs/kube-system/cilium-smc9s/cilium-agent?follow=true&sinceSeconds=300&tailLines=100&timestamps │
│ stream logs failed Get "https://10.25.216.7:10250/containerLogs/kube-system/cilium-smc9s/cilium-agent?follow=true&sinceSeconds=300&tailLines=100&timestamps │
│ stream logs failed Get "https://10.25.216.7:10250/containerLogs/kube-system/cilium-smc9s/cilium-agent?follow=true&sinceSeconds=300&tailLines=100&timestamps │
```

### Anything else?

Other testing done:
- Version bump from 1.16.6 -> 1.17.x with policy enforce `never` and after upgrade add enforcement ,  everything works fine

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by tamilmani1989** [comment]
I tried testing upgrade from 1.16.6 to 1.17.1 with static policies and its working as expected. I followed these steps you mentioned:
> Install cilium 1.16.6, have policy enforce mode 'always' and load some static cilium cluster wide network policies
Upgrade cilium to 1.17.x
Notice that the static policies are not taken into effect


can you share more details on your network policies and what `cilium bpf policy get <cilium_endpoint_id>` looks before and after upgrade? <cilium_endpoint_id> is cep id of impacted pod. you have to exec to cilium agent pod to run above cmd.

**Comment by tamilmani1989** [comment]
Thanks @radhupr . I guess this `cilium bpf policy get 1433` is after 1.17 upgrade and I don't see anything for egress (which i guess is an issue). can you share the same before upgrade while running 1.16.6. Also, can you please share cilium agent logs?

**Comment by radhupr** [comment]
There is egress for endpoint 1433 ( as I said, it was filtered first few lines as the output was too long)

`Allow    Egress      reserved:unknown                                                                     ANY          NONE         disabled    612299543   4487249   0`

The cilium agent logs just give the connection timeout as I mentioned in the initial bug report
```
 stream logs failed Get "https://10.25.216.7:10250/containerLogs/kube-system/cilium-smc9s/cilium-agent?follow=true&sinceSeconds=300&tailLines=100&timestamps │
│ stream logs failed Get "https://10.25.216.7:10250/containerLogs/kube-system/cilium-smc9s/cilium-agent?follow=true&sinceSeconds=300&tailLines=100&timestamps │
```

**Comment by radhupr** [comment]
Attaching the full policy list for worker and konnectivity-agent from 16.6 and 17.1 version

[v16.6.txt](https://github.com/user-attachments/files/18891167/v16.6.txt)
[v17.1.txt](https://github.com/user-attachments/files/18891168/v17.1.txt)

**Comment by tamilmani1989** [comment]
@radhupr i see entries for ingress rules present static policy yaml in both 1.6.6 and 1.17 for worker node. For example, one of static policy rules is that ingress to port `10250` should be allowed from konnectivity agent to worker node and this rule exists in both version. so could confirm static policies are getting loaded.
```
Allow    Ingress     k8s:io.cilium.k8s.namespace.labels.field.cattle.io/projectId=p-djsv4                 10250/TCP    NONE         disabled    1071442      12461     24
                     k8s:io.cilium.k8s.namespace.labels.goldilocks.fairwinds.com/enabled=true
                     k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system
                     k8s:io.cilium.k8s.namespace.labels.owner=PrivateCloudKubernetes
                     k8s:io.cilium.k8s.policy.cluster=default
                     k8s:io.cilium.k8s.policy.serviceaccount=konnectivity-agent
                     k8s:io.kubernetes.pod.namespace=kube-system

```

The difference I see is for egress rules enforced on konnectivity pod between 1.16 and 1.17

In 1.16, there are egress rules for allowing all pods within cluster i guess (because of "cluster" entity) but in 1.17 egress allowed only to remote node, coredns and apiserver (are there any other pods running in cluster?). so my guess is either conflicting egress policies for konnectivity or to-cluster not resolving to all pods or policy rules not getting updated after new pods created. can you share all network policies that could affect konnecivity pod (selecting as endpoint selector) since i noticed some other rules in bpf map exists for same pod.

**Comment by radhupr** [comment]
@tamilmani1989 Sorry for delay in coming back to this. Attached file where we have konnectivity-agent endpoint mentioned under network policies. Let me know if you need any other input from my side.

**Comment by tamilmani1989** [comment]
@squeed Thanks for pointing out. I assume you point to multiple cnp objects defined in same yaml. I wanted to confirm if  that's the same issue @radhupr hitting here since they mentioned it worked in 1.16 but not from 1.17. Handling multiple cnp objects in a file is not supported from the time this feature was added. @radhupr can you confirm if all CNP objects are defined in one yaml file or its yaml per cnp.

**Comment by radhupr** [comment]
@tamilmani1989 The policies were in separate files on our side. 
```
#static-cnp-worker.yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: static-worker
spec:
  nodeSelector:
    matchLabels:
      node.kubernetes.io/worker: "true"
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s:k8s-app: konnectivity-agent
    toPorts:
    - ports:
      - port: "10250"
        protocol: TCP
  egress:
  - toEntities:
    - all
---
#static-cnp-konnectivity.yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: static-konnecivity
spec:
  endpointSelector:
    matchLabels:
      k8s:io.kubernetes.pod.namespace: kube-system
      k8s:k8s-app: konnectivity-agent
  egress:
    - toEntities:
      - cluster
---
#static-cnp-coredns.yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: static-coredns
spec:
  endpointSelector:
    matchLabels:
      k8s:io.kubernetes.pod.namespace: kube-system
      k8s:k8s-app: kube-dns
  ingress:
  - fromEntities:
    - cluster
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      - port: "9153"
        protocol: TCP
  egress:
  - toEntities:
    - kube-apiserver
    - host
  - toCIDR:
    - 1.1.1.1/32
    - 8.8.8.8/32

```

**Comment by tamilmani1989** [comment]
i will try repro with exact network policy and let know.

**Comment by tamilmani1989** [comment]
I'm able to repro the issue. I guess it's something to do with policy refactor done in 1.17 https://github.com/cilium/cilium/commit/b79b627c01fcca1cf7c2c4c620c9f9cd162bb5cb. I couldn't repro the same issue in 1.16.8.  @squeed in new code path, is it possible that rules got added even before identity of endpoint got resolved?

In working case, i noticed identity is resolved while in non-working case, identity is empty. To repro, I placed the policy files in specific path and then restarted cilium agent. Directory policies getting loaded on bootup didn't resolve identity and thus rules are missing in endpoint policy map


**In working case: (usually places files after cilium agent got into running state)**

time=2025-04-15T22:27:57Z level=info msg="Upserted policy to repository" module=agent.controlplane.policy resource=file//tm/static-cnp-container.yaml policyRevision=10 deletedRules=1 `identity=[56382]`

**Non-working case (Agent bootup and loads policy from directory)**

time=2025-04-15T22:24:17Z level=info msg="Upserted policy to repository" module=agent.controlplane.policy resource=file//tm/static-cnp-container.yaml policyRevision=3 deletedRules=0 `identity=[]`

**Comment by squeed** [comment]
@tamilmani1989 it's OK if policies are loaded before endpoints are added, as we scan the set of policies when endpoints are generated.

I wonder if any of the namespace-shortcut code is to blame here.

**Comment by anubhabMajumdar** [comment]
@squeed  Can I pick this up?

**Comment by anubhabMajumdar** [comment]
As @tamilmani1989 mentioned, this issue happens on startup (before agent is ready). Once agent is running, if we delete/re-create the `cwnp` again, it reconciles with Identity.

```bash
cilium-agent time=2025-05-22T00:01:14Z level=info msg="Directory policy watcher started" module=agent.controlplane.policy-directory-watcher
cilium-agent time=2025-05-22T00:01:14Z level=info msg="Processing policy updates" module=agent.controlplane.policy count=1
cilium-agent time=2025-05-22T00:01:14Z level=info msg="inserting ipcache metadata for CIDR prefixes from policy" module=agent.controlplane.policy count=2
cilium-agent time=2025-05-22T00:01:14Z level=info msg="Upserted policy to repository" module=agent.controlplane.policy resource=file//policies/cwnp.yaml policyRevision=2 deletedRules=0 identity=]
cilium-agent time=2025-05-22T00:01:14Z level=info msg="Policy repository updates complete, triggering endpoint updates" module=agent.controlplane.policy policyRevision=2
cilium-agent time=2025-05-22T00:02:05Z level=info msg="Processing policy updates" module=agent.controlplane.policy count=1
cilium-agent time=2025-05-22T00:02:05Z level=info msg="Deleted policy from repository" module=agent.controlplane.policy resource=file//policies/cwnp.yaml policyRevision=3 deletedRules=1 identity=[30341]
cilium-agent time=2025-05-22T00:02:05Z level=info msg="Policy repository updates complete, triggering endpoint updates" module=agent.controlplane.policy policyRevision=3
cilium-agent time=2025-05-22T00:02:05Z level=info msg="pruning stale policy CIDR prefix ipcache metadata entries" module=agent.controlplane.policy count=2
cilium-agent time=2025-05-22T00:02:18Z level=info msg="Processing policy updates" module=agent.controlplane.policy count=1
cilium-agent time=2025-05-22T00:02:18Z level=info msg="inserting ipcache metadata for CIDR prefixes from policy" module=agent.controlplane.policy count=2
cilium-agent time=2025-05-22T00:02:18Z level=info msg="Upserted policy to repository" module=agent.controlplane.policy resource=file//policies/cwnp.yaml policyRevision=4 deletedRules=0 identity=[30341]
cilium-agent time=2025-05-22T00:02:18Z level=info msg="Policy repository updates complete, triggering endpoint updates" module=agent.controlplane.policy policyRevision=4
cilium-agent time=2025-05-22T00:02:20Z level=info msg="All policy resources synchronized!" module=agent.controlplane.policy-k8s-watcher

```

**Comment by joestringer** [comment]
@anubhabMajumdar It looks like this is assigned to @tamilmani1989 so I'd suggest coordinating together to avoid duplicate work, but other than that yeah I think it would be great to have more eyes on this problem.

**Comment by tamilmani1989** [comment]
@anubhabMajumdar please go ahead and i can share more context on this issue if required.

**Comment by anubhabMajumdar** [comment]
I think this has got something to do with the labels.
```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: static-coredns
spec:
  endpointSelector:
    matchLabels:
      k8s:io.kubernetes.pod.namespace: kube-system
      k8s:k8s-app: kube-dns
  ingress:
  - fromEntities:
    - cluster
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      - port: "9153"
        protocol: TCP
  egress:
  - toEntities:
    - kube-apiserver
    - host
  - toCIDR:
    - 1.1.1.1/32
    - 8.8.8.8/32
```

Above doesn't work as reported, but when I apply to a demo pod I created in `kube-system` , it works as expected.

```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: static-coredns
spec:
  endpointSelector:
    matchLabels:
      k8s:io.kubernetes.pod.namespace: kube-system
      k8s:app: demo
...
```
