### ISSUE TITLE
interaction between Cilium IPAM mode and kube-controller-manager allocate-node-cidrs

### ISSUE THREAD

**Issue by rptaylor** [cilium/cilium#37759]
When kube-controller-manager runs with `--allocate-node-cidrs=true`, then it assigns podCIDR ranges to nodes.
If Cilium is running in any IPAM mode except Kubernetes Host Scope, it completely ignores those node podCIDR ranges and instead assigns  podCIDRs to `ciliumnodes`, which generally do not match what kube-controller-manager is assigning.
So IIUC, use of allocate-node-cidrs is at best irrelevant and liable to cause confusion and apparent (but not actual) conflicts in this case.  (https://github.com/cilium/cilium/issues/17277#issuecomment-1020315648)

Cilium docs relating to allocate-node-cidrs:
1. [Kubernetes Host Scope](https://docs.cilium.io/en/stable/network/concepts/ipam/kubernetes/#kubernetes-host-scope) says `--allocate-node-cidrs=true` is required - makes sense for k8s host scope
2.  [requirements.rst](https://github.com/cilium/cilium/blob/main/Documentation/network/kubernetes/requirements.rst) says using `--allocate-node-cidrs` is highly recommended, but AFAICT this is an orphaned .rst file not referenced anywhere
3. [Installation with external etcd](https://docs.cilium.io/en/stable/installation/k8s-install-external-etcd/#requirements) says  `--allocate-node-cidrs` is recommended - why ? How does external etcd relate to the IPAM mode or `--allocate-node-cidrs` ?

Kubernetes clarification about the usage of this option :
- https://github.com/kubernetes/kubernetes/issues/119066
- https://github.com/kubernetes/kubernetes/pull/126784/files

However, beyond the observation that it seems irrelevant and confusing to enable this when using Cilium Cluster Scope IPAM, it also appears detrimental, for the same reason as these Calico-related issues, namely kube-controller-manager can mistakenly think that there are not enough CIDRs available for a node, and generate error events with the CIDRNotAvailable condition:
- https://github.com/projectcalico/calico/issues/7722
- https://github.com/kubernetes-sigs/kubespray/pull/10639/files

Long story short, it seems to me that allocate-node-cidrs should always be disabled and explicitly _not_ recommended , for every Cilium IPAM mode except k8s Host Scope where it is required. Can anyone confirm?

**Comment by an-ky** [comment]
Hi, are there new insights about this? We setup a new cluster using k0s and Cilium at it works fine but we have 
`Normal  CIDRNotAvailable  4m40s (x4051 over 9d)  cidrAllocator  Node yggdrasil00 status is now: CIDRNotAvailable` messages for all our (worker) nodes.

The cluster was installed using k0sctl with the following configuration:

```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s_jotunheim
  user: k0s_jotunheim-admin
spec:
  hosts:
  - ssh:
      address: 10.16.2.2
      user: ***
      port: 22
    role: controller
    dataDir: /var/lib
    privateAddress: 10.16.2.2
  - ssh:
      address: 10.16.2.3
      user: ***
      port: 22
    role: controller
    dataDir: /var/lib
    privateAddress: 10.16.2.3
  - ssh:
      address: 10.16.2.4
      user: ***
      port: 22
    role: controller
    dataDir: /var/lib
    privateAddress: 10.16.2.4
  - ssh:
      address: 10.16.3.2
      user: ***
      port: 22
    role: worker
    dataDir: /var/lib
  - ssh:
      address: 10.16.3.3
      user: ***
      port: 22
    role: worker
    dataDir: /var/lib
  - ssh:
      address: 10.16.3.4
      user: ***
      port: 22
    role: worker
    dataDir: /var/lib
  k0s:
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s_jotunheim
      spec:
        api:
          sans:
          - 10.16.2.2
          - 10.16.2.3
          - 10.16.2.4
          - 10.16.2.254
        network:
          serviceCIDR: "10.240.0.0/12"
          clusterDomain: cluster.local
          provider: custom
          calico: null
          podSecurityPolicy:
            defaultPolicy: 00-k0s-privileged
          telemetry:
            enabled: true
          installConfig:
            users:
              etcdUser: etcd
              kineUser: kube-apiserver
              konnectivityUser: konnectivity-server
              kubeAPIserverUser: kube-apiserver
              kubeSchedulerUser: kube-scheduler
          images:
            konnectivity:
              image: k8s.gcr.io/kas-network-proxy/proxy-agent
              version: v0.0.25
            metricsserver:
              image: k8s.gcr.io/metrics-server/metrics-server
              version: v0.5.0
            coredns:
              image: k8s.gcr.io/coredns/coredns
              version: v1.12.0
          konnectivity:
            agentPort: 8132
            adminPort: 8133
          kubeProxy:
            disabled: true
          nodeLocalLoadBalancing:
            enabled: true
            type: EnvoyProxy
          controlPlaneLoadBalancing:
            enabled: true
            type: Keepalived
            keepalived:
              vrrpInstances:
              - virtualIps: ["10.16.2.254/24"]
                authPass: k0scplb
          storage:
            type: etcd
        extensions:
          helm:
            repositories:
            - name: cilium
              url: https://helm.cilium.io/
            - name: jetstack 
              url: https://charts.jetstack.io
            - name: democratic-csi
              url: https://democratic-csi.github.io/charts/
            - name: argo
              url: https://argoproj.github.io/argo-helm
            charts:
            - name: cert-manager
              chartname: jetstack/cert-manager
              namespace: cert-manager
              version: "v1.16.2"
              values: |
                crds:
                  enabled: true
            - name: cilium
              chartname: cilium/cilium
              version: "v1.17.2"
              namespace: "kube-system"
              values: |
                bgpControlPlane:
                  enabled: false
                kubeProxyReplacement: true
                k8sServiceHost: 10.16.2.2
                k8sServicePort: 6443
                ingressController:
                  enabled: true
                  loadbalancerMode: "shared"
                  default: true
                nodeIPAM:
                  enabled: true
                defaultLBServiceIPAM: nodeipam
                gatewayAPI:
                  enabled: true
                ipam:
                  mode: cluster-pool
                  operator:
                    clusterPoolIPv4PodCIDRList:
                    - "10.224.0.0/16"
                    clusterPoolIPv4PodCIDRMaskSize: "24"
                hubble:
                  relay:
                    enabled: true
                  ui:
                    enabled: true
                  peerService:
                    clusterDomain: cluster.local
```
