### ISSUE TITLE
cilium-agent cannot map IP to identity if node has no IPv4 address

### ISSUE THREAD

**Issue by EmilyShepherd** [cilium/cilium#37791]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.1 and lower than v1.18.0

### What happened?

When running in an IPv6 environment, using native routing, cilium-agent still requires a Node to have an IPv4 address on its manifest, even though this does not appear to be necessary.

### How can we reproduce the issue?

1.  Deploy Helm with routing=native, ipv4.enabled=false
2. Create a Node with an IPv6 address(es) but no IPv4 address:

```
apiVersion: v1
kind: Node
...
status:
  addresses:
  - address: "2001:0db8:85a3:0000:0000:8a2e:0370:7334"
    type: InternalIP
```

3. Start a Pod. Cilium will fail to create it
4. Add a dud IPv4 address to the Node:

```
apiVersion: v1
kind: Node
...
status:
  addresses:
  - address: "2001:0db8:85a3:0000:0000:8a2e:0370:7334"
    type: InternalIP
  - address: "203.0.113.23"
    type: InternalIP
```

5. Pod will now be able to be scheduled (NB: Due to a separate issue, #37790, cilium-agent needs to be restarted after step 4)

When in native routing mode, this IPv4 address does not appear to actually be used anywhere, it just needs to exist. In our cluster, we tested this theory by adding the exact same IPv4 address to every Node manifest. This was an IPv4 address that was not actually assigned to any ports in the host net, and wasn't routable. Despite this, cilium is able to route pod-to-pod, pod-to-service, outside-to-service, and correctly enforce NetworkPolicies.

It seems that, in the case that native routing is being used at least, it would be acceptable to drop this requirement?

The relevant code is here: https://github.com/cilium/cilium/blob/ff7d6771e95fcb62a866c814741aa8e8be8915ec/pkg/endpoint/policy.go#L983C3-L983C5

### Cilium Version

1.17.1

### Kernel Version

6.6.2

### Kubernetes Version

v1.29.8

### Relevant log output

```shell

```

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by netops2devops** [comment]
Hi @EmilyShepherd can you please share the helm `key: values` that you are using for IPv6 native routing? I am running an IPv6 only k3s cluster with Cilium 1.17.1 and have not observed this problem. All my nodes are in the same L2 segment. 

Operating system: Ubuntu 22.04.5 LTS
Kernel Version: 5.15.0-133-generic
k3s version: v1.31.6+k3s1

Here's what my helm config looks like for example.

```
autoDirectNodeRoutes: true
ipam:
  operator:
    clusterPoolIPv6PodCIDRList: 2001:db8:dead:beef::/104
ipv4:
  enabled: false
ipv6:
  enabled: true
ipv6NativeRoutingCIDR: 2001:db8:dead:beef::/64
k8sServiceHost: localhost
k8sServicePort: 6444
kubeProxyReplacement: true
routingMode: native
```

and here's my k3s config.yaml file 

```
---
cluster-init: true
write-kubeconfig-mode: "0644"
flannel-backend: none
disable-network-policy: true
disable-kube-proxy: true
service-cidr: 2001:db8:dead:beef:cafe::/112
disable:
  - traefik
  - metrics-server
  - servicelb
```

As you may already know there are some Cilium specific defaults which are implied with the above config bits. One of the most important ones being `ipam.mode` which in my case defaults to `cluster-pool`

**Comment by EmilyShepherd** [comment]
Hi @netops2devops, my helm values:

```
bpf:
  lbExternalClusterIP: true
  masquerade: false
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
disableEndpointCRD: true
enableIPv6Masquerade: false
etcd:
  enabled: true
  endpoints:
  - [REDACTED]
  ssl: true
hostFirewall:
  enabled: false
identityAllocationMode: kvstore
ipam:
  mode: kubernetes
ipv4:
  enabled: false
ipv6:
  enabled: true
k8sServiceHost: localhost
k8sServicePort: 6444
kubeProxyReplacement: true
l2NeighDiscovery:
  enabled: false
routingMode: native
```

Could you show the Node manifest for one of the nodes in your cluster?
