### ISSUE TITLE
After upgrading to v1.17.1 from v1.16, Failed to start with `No IPv6 support on node as ipv6 address is nil`

### ISSUE THREAD

**Issue by jungeonkim** [cilium/cilium#37817]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.1 and lower than v1.18.0

### What happened?

```
time="2025-02-23T06:17:49.806446531Z" level=error msg="No IPv6 support on node as ipv6 address is nil" ipAddr.ipv4=10.0.0.* ipAddr.ipv6="<nil>" nodeName=node-1 subsys=daemon
time="2025-02-23T06:17:49.806464032Z" level=error msg="unable to connect to get node spec from apiserver" error="node node-1 does not have an IPv6 address" subsys=daemon
time="2025-02-23T06:17:49.806830253Z" level=info msg="Waiting for all endpoints' goroutines to be stopped." subsys=daemon
time="2025-02-23T06:17:49.806857642Z" level=info msg="All endpoints' goroutines stopped." subsys=daemon
```
After agent is terminated.

I did a little bit of debugging

In v1.16.x, ```setDefaultPrefix``` in ```pkg/node/address.go``` sets the v6 address before ```if option.Config.EnableIPv6 && nodeIP6 == nil {``` is executed.
But, in v1.17.2, ```setDefaultPrefix```  is executed later.

### How can we reproduce the issue?

helm values.yaml
```yaml
autoDirectNodeRoutes: true
bgpControlPlane:
  enabled: true
  v2Enabled: false
enableIPv4Masquerade: false
enableIPv6Masquerade: false
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: 10.0.0.0/16
    clusterPoolIPv6PodCIDRList: fd00::/108
ipv6:
  enabled: true
k8sServiceHost: 172.16.0.1
k8sServicePort: "6443"
kubeProxyReplacement: "true"
routingMode: native
envoy:
  enabled: false
```

If I roll back to v1.16.7 everything works fine.

### Cilium Version

v1.17.1

### Kernel Version

6.8.0-53-generic #55-Ubuntu

### Kubernetes Version

v1.32.2

### Regression

v1.16.7

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
