### ISSUE TITLE
BGP: wrong IPv6 addresses advertised over IPv4

### ISSUE THREAD

**Issue by sbogomolov** [cilium/cilium#37831]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.1 and lower than v1.18.0

### What happened?

When trying to advertise both IPv4 and IPv6 routes via one IPv4 peer wrong IPv6 address is advertised as next hop.

Peer configuration:
```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
  - afi: ipv4
    safi: unicast
    advertisements:
      matchLabels:
        advertise: bgp
  - afi: ipv6
    safi: unicast
    advertisements:
      matchLabels:
        advertise: bgp
```

Cluster config:
```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: DoesNotExist
  bgpInstances:
  - name: instance-65530
    localASN: 65530
    peers:
    - name: peer-65530-ipv4
      peerASN: 65530
      peerAddress: 192.168.50.1
      peerConfigRef:
        name: cilium-peer
```

PCAP capture of the IPv6 route advertisement:
![Image](https://github.com/user-attachments/assets/06687e2b-f41f-4bd8-aab7-6bbc4316c6fa)

Next hop here is IPv4 address mapped to IPv6 (instead of the correct IPv6 address).

P.S. When I configure two BGP peers (IPv4 peer to advertise IPv4 routes and IPv6 peer to advertise IPv6 routes) - everything works as expected.

### How can we reproduce the issue?

- Configure BGP peer and cluster as described
- Use router that supports multiprotocol extension on the other end (I use Mikrotik RB5009).
- Capture BGP packets exchanged between the peers

### Cilium Version

Client: 1.17.1 d6c9f9e8 2025-02-12T10:19:21+00:00 go version go1.23.6 linux/amd64
Daemon: 1.17.1 d6c9f9e8 2025-02-12T10:19:21+00:00 go version go1.23.6 linux/amd64

### Kernel Version

6.12.13-talos

### Kubernetes Version

v1.32.2

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
