### ISSUE TITLE
multipool ipam: nodes can't get ranges from it

### ISSUE THREAD

**Issue by pasztorl** [cilium/cilium#37946]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.1 and lower than v1.18.0

### What happened?

Configured default multipool resource, then some nodes can get ip range others not.

### How can we reproduce the issue?

Here is the related helm config
```
...
ipam:
  mode: multi-pool
  operator:
    multiPoolPreAllocation: false
    autoCreateCiliumPodIPPools:
      default:
        ipv4:
          cidrs:
            - 10.207.0.0/24
          maskSize: 28
```
There are 8 node, two got range:
```
...
  ipam:
    pools:
      allocated:
        - cidrs:
            - 10.207.0.0/28
          pool: default
      requested:
        - needed:
            ipv4-addrs: 8
          pool: default
```
```
...
  ipam:
    pools:
      allocated:
        - cidrs:
            - 10.207.0.16/28
            - 10.207.0.32/28
          pool: default
      requested:
        - needed:
            ipv4-addrs: 16
          pool: default
...
```
others not:
```
  ipam:
    pools: {}
```

on nodes that can't get pools cilium log:
```
time="2025-03-02T15:19:49.716483724Z" level=info msg="Creating or updating CiliumNode resource" node=n4c1r1 subsys=nodediscovery
time="2025-03-02T15:19:49.72074059Z" level=info msg="Retrieved node information from kubernetes node" nodeName=n4c1r1 subsys=daemon
time="2025-03-02T15:19:49.720748344Z" level=warning msg="Waiting for k8s node information" error="required IPv4 PodCIDR not available" subsys=daemon
```

in cilium operator log there is nothing about pool requests. can i increase the loglevel somehow?

### Cilium Version

1.17.1

### Kernel Version

6.8.x

### Kubernetes Version

1.31.x

### Regression

1.16.7 works the same.

### Relevant log output

```shell

```

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
