### ISSUE TITLE
XDP and DSR do not establish connection to NodePort without a backend pod

### ISSUE THREAD

**Issue by verdel** [cilium/cilium#37961]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

v1.16.5

### What happened?

1. I created an RKE2 cluster in Rancher on VMware vSphere VM with one master node and two worker nodes in plain L2 network. We use vmxnet3 VM adapters:
```
kubectl get node -o wide
NAME                               STATUS   ROLES                       AGE     VERSION          INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
control-vl584-l9ld5                Ready    control-plane,etcd,master   7m13s   v1.30.9+rke2r1   10.236.2.27   10.236.2.27   Ubuntu 24.04.2 LTS   6.8.0-53-generic   containerd://1.7.23-k3s2
worker-gw-528xw-bjwtl              Ready    worker                      3m23s   v1.30.9+rke2r1   10.236.2.29   10.236.2.29   Ubuntu 24.04.2 LTS   6.8.0-53-generic   containerd://1.7.23-k3s2
worker-gw-528xw-c982r              Ready    worker                      3m21s   v1.30.9+rke2r1   10.236.2.28   10.236.2.28   Ubuntu 24.04.2 LTS   6.8.0-53-generic   containerd://1.7.23-k3s2
```
2. Cilium was installed from the Helm chart v1.16.5 with the following parameters:
```yaml
autoDirectNodeRoutes: true
bandwidthManager:
  bbr: true
  enabled: true
bpf:
  hostLegacyRouting: false
  masquerade: true
cni:
  chainingMode: none
enableIPv4BIGTCP: true
envoy:
  enabled: false
externalIPs:
  enabled: true
global:
  cattle:
    clusterId: c-m-z8zwv8gf
  clusterCIDR: 10.42.0.0/16
  clusterCIDRv4: 10.42.0.0/16
  clusterDNS: 10.43.0.10
  clusterDomain: cluster.local
  rke2DataDir: /var/lib/rancher/rke2
  serviceCIDR: 10.43.0.0/16
  systemDefaultIngressClass: ingress-nginx
hubble:
  enabled: false
ipv4NativeRoutingCIDR: 10.42.0.0/16
k8sServiceHost: localhost
k8sServicePort: "6443"
kubeProxyReplacement: true
l2announcements:
  enabled: true
  leaseDuration: 3s
  leaseRenewDeadline: 1s
  leaseRetryPeriod: 200ms
loadBalancer:
  acceleration: native
  algorithm: maglev
  mode: hybrid
nodePort:
  enabled: true
routingMode: native
```
```
CNI Chaining:           none
IPv4 BIG TCP:           Enabled   [65536]
BandwidthManager:       EDT with BPF [BBR] [ens33]
Routing:                Network: Native   Host: BPF
Masquerading:           BPF   [ens33]   10.42.0.0/16 [IPv4: Enabled, IPv6: Disabled]
KubeProxyReplacement Details:
  Status:                 True
  Socket LB:              Enabled
  Socket LB Tracing:      Enabled
  Socket LB Coverage:     Full
  Devices:                ens33  10.236.2.29 (Direct Routing)
  Mode:                   Hybrid
    DSR Dispatch Mode:    IP Option/Extension
  Backend Selection:      Maglev (Table Size: 16381)
  Session Affinity:       Enabled
  Graceful Termination:   Enabled
  NAT46/64 Support:       Disabled
  XDP Acceleration:       Native
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Enabled (Range: 30000-32767)
  - LoadBalancer:   Enabled
  - externalIPs:    Enabled
  - HostPort:       Enabled
```
3. A deployment with one replica of Nginx was created:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: test
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
        - name: my-nginx
          image: nginx
          ports:
            - containerPort: 80
```
4. A service with NodePort type for Nginx was created (:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service-nodeport
  namespace: test
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: my-nginx
  type: NodePort
```
5. Here are all the k8s resources that interest us:
```shell
kubectl get node,pod,service -o wide
NAME                                    STATUS   ROLES                       AGE   VERSION          INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
node/control-vl584-l9ld5                Ready    control-plane,etcd,master   14m   v1.30.9+rke2r1   10.236.2.27   10.236.2.27   Ubuntu 24.04.2 LTS   6.8.0-53-generic   containerd://1.7.23-k3s2
node/worker-gw-528xw-bjwtl              Ready    worker                      10m   v1.30.9+rke2r1   10.236.2.29   10.236.2.29   Ubuntu 24.04.2 LTS   6.8.0-53-generic   containerd://1.7.23-k3s2
node/worker-gw-528xw-c982r              Ready    worker                      10m   v1.30.9+rke2r1   10.236.2.28   10.236.2.28   Ubuntu 24.04.2 LTS   6.8.0-53-generic   containerd://1.7.23-k3s2

NAME                           READY   STATUS    RESTARTS   AGE     IP            NODE                               NOMINATED NODE   READINESS GATES
pod/my-nginx-fdd6574f7-kjfb2   1/1     Running   0          2m19s   10.42.1.129   worker-gw-528xw-bjwtl                <none>           <none>

NAME                          TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE     SELECTOR
service/my-service-nodeport   NodePort   10.43.203.150   <none>        80:31638/TCP   2m10s   run=my-nginx
```
6. The pod is running on the worker node `worker-gw-528xw-bjwtl` with the external address `10.236.2.29`. If I make a curl request to the NodePort - 31638 of this node, everything works fine. But if I make a request to the address of the second worker node, which does not have the nginx pod - `worker-gw-528xw-c982r` (10.236.2.28), the connection fails
```shell
> curl -v http://10.236.2.29:31638
* Rebuilt URL to: http://10.236.2.29:31638/
*   Trying 10.236.2.29...
* TCP_NODELAY set
* Connected to 10.236.2.29 (10.236.2.29) port 31638 (#0)
> GET / HTTP/1.1
> Host: 10.236.2.29:31638
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.27.4
< Date: Mon, 03 Mar 2025 13:21:56 GMT
< Content-Type: text/html
< Content-Length: 615
< Last-Modified: Wed, 05 Feb 2025 11:06:32 GMT
< Connection: keep-alive
< ETag: "67a34638-267"
< Accept-Ranges: bytes
<
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

> curl -v http://10.236.2.28:31638
* Rebuilt URL to: http://10.236.2.28:31638/
*   Trying 10.236.2.28...
* TCP_NODELAY set
```

If we use SNAT mode instead of DSR, the issue persists.

### How can we reproduce the issue?

Install Cilium from the Helm chart v1.16.5 with the following parameters:

```yaml
autoDirectNodeRoutes: true
bandwidthManager:
  bbr: true
  enabled: true
bpf:
  hostLegacyRouting: false
  masquerade: true
cni:
  chainingMode: none
enableIPv4BIGTCP: true
envoy:
  enabled: false
externalIPs:
  enabled: true
global:
  cattle:
    clusterId: c-m-z8zwv8gf
  clusterCIDR: 10.42.0.0/16
  clusterCIDRv4: 10.42.0.0/16
  clusterDNS: 10.43.0.10
  clusterDomain: cluster.local
  rke2DataDir: /var/lib/rancher/rke2
  serviceCIDR: 10.43.0.0/16
  systemDefaultIngressClass: ingress-nginx
hubble:
  enabled: false
ipv4NativeRoutingCIDR: 10.42.0.0/16
k8sServiceHost: localhost
k8sServicePort: "6443"
kubeProxyReplacement: true
l2announcements:
  enabled: true
  leaseDuration: 3s
  leaseRenewDeadline: 1s
  leaseRetryPeriod: 200ms
loadBalancer:
  acceleration: native
  algorithm: maglev
  mode: hybrid
nodePort:
  enabled: true
routingMode: native
```

### Cilium Version

v1.16.5-ad688277

### Kernel Version

6.8.0-53-generic

### Kubernetes Version

v1.30.9+rke2r1

### Sysdump

[cilium-sysdump-20250303-162547.zip](https://github.com/user-attachments/files/19053949/cilium-sysdump-20250303-162547.zip)

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
