### ISSUE TITLE
CiliumNetworkPolicy does not marshal to JSON correctly

### ISSUE THREAD

**Issue by squeed** [cilium/cilium#38010]
(I recall seeing some duplicate issues, but I can't find them now)

If you create this sort of network policy:

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-client-to-dns
spec:
  endpointSelector:
    matchLabels:
      app: client
```

but in Go, then serialize to yaml or json, you get
```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-client-to-dns
spec:
  endpointSelector:
    matchLabels:
      any:app: client
```

Note the added `any:app` in the endpointSelector, which is wrong.

We should ensure that policy API types are (practically) unchanged through json -> type -> json conversion
