### ISSUE TITLE
Multiple consecutive retries of updating taints and conditions for a node failed

### ISSUE THREAD

**Issue by alexbescond** [cilium/cilium#38059]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.1 and lower than v1.18.0

### What happened?

Hi there,

Since the upgrade of v1.17.1, we have a ton of such warn logs:

```
level=warn msg="Multiple consecutive retries of updating taints and conditions for a node failed, will retry" module=operator.operator-controlplane.leader-lifecycle.legacy-cell subsys=watchers nodeName=XXXXXX error="Node.core \"XXXXX\" not found"
```

These nodes are indeed already removed by Karpenter.

How can we fix it?

![Image](https://github.com/user-attachments/assets/14faed79-4cea-4589-91fd-655e95289179)

### How can we reproduce the issue?

Helm values:

```
cni:
  chainingMode: aws-cni
  exclusive: false
enableIPv4Masquerade: false
routingMode: native
endpointRoutes:
  enabled: true
dnsProxy:
  endpointMaxIpPerHostname: 500
```

### Cilium Version

1.17.1

### Kernel Version

5.10.234-225.895.amzn2.aarch64

### Kubernetes Version

1.29 and 1.30

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
