### ISSUE TITLE
`CiliumBGPPeerConfig` Always Reports MissingAuthSecret in v1.17.1

### ISSUE THREAD

**Issue by schwankner** [cilium/cilium#38073]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.1

### What happened?

In Cilium version 1.17.1 and 1.18.0-pre.0, the CiliumBGPPeerConfig always reports a "MissingAuthSecret" error, regardless of whether a secret is present or not and irrespective of the namespace (tested with both kube-system and cilium-secrets). This occurs even when no secret is configured in the CiliumBGPPeerConfig. With the exact same configuration, everything works flawlessly in version 1.16.6.

The operator pod is able to locate the secret, and in the "Reconciling secret", it consistently outputs action=ignored. I'm installing Cilium on a new Talos Linux single-node cluster using the Cilium CLI, but I also encountered the same problem when deploying via Helm. However, if I install version 1.16.6, everything functions as expected.

I suspect this issue might be related to [Issue #35650](https://github.com/cilium/cilium/issues/35650).

### How can we reproduce the issue?

1. Install clean talos linux
2. Install cilium via cli 
```
cilium install \
    --version 1.17.1 \
    --set ipam.mode=kubernetes \
    --set kubeProxyReplacement=false \
    --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
    --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
    --set cgroup.autoMount.enabled=false \
    --set bgpControlPlane.enabled=true \
    --set bgpControlPlane.secretNamespace.name=kube-system \
    --set cgroup.hostRoot=/sys/fs/cgroup
```
3. kubectl apply -n kube-system -f IPPool.yaml
```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "pool"
  namespace: kube-system
spec:
  allowFirstLastIPs: "No"
  blocks:
  - cidr: "10.0.61.0/24"
```
4. kubectl apply -n kube-system -f BGPAuthSecret.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: bgp-auth-secret
  namespace: kube-system
type: Opaque
data:
  password: YXNkZg==
```
5. kubectl apply -n kube-system -f BGPPeerConfig.yaml
```
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  authSecretRef: bgp-auth-secret
  ebgpMultihop: 1
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
```
6. kubectl apply -n kube-system -f BGPClusterConfig.yaml
```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  bgpInstances:
  - name: "k8s-64512"
    localASN: 64512
    peers:
    - name: "opnsense-65501"
      peerASN: 65501
      peerAddress: 10.0.60.254
      peerConfigRef:
        name: "cilium-peer"
```
6. kubectl apply -n kube-system -f BGPAdvertisements.yaml
```
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - { key: somekey, operator: NotIn, values: [ 'never-used-value' ] }

```

### Cilium Version

1.17.1 and 1.18.0-pre.0

### Kernel Version

Unknown (using Talos Linux)

### Kubernetes Version

v1.32.2

### Regression

In 1.16.6 it worked fine.

### Sysdump

[cilium-sysdump-20250307-172935.zip](https://github.com/user-attachments/files/19130023/cilium-sysdump-20250307-172935.zip)

### Relevant log output

```shell
$ kubectl describe CiliumBGPPeerConfig cilium-peer -n kube-system                                                                  ○ admin@dev 16:19:33

Name:         cilium-peer
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  cilium.io/v2alpha1
Kind:         CiliumBGPPeerConfig
Metadata:
  Creation Timestamp:  2025-03-07T16:21:59Z
  Generation:          1
  Resource Version:    997
  UID:                 9de93188-0c27-4986-a060-3f6dfc35d2a7
Spec:
  Auth Secret Ref:  bgp-auth-secret
  Ebgp Multihop:    1
  Families:
    Advertisements:
      Match Labels:
        Advertise:  bgp
    Afi:            ipv4
    Safi:           unicast
  Graceful Restart:
    Enabled:               true
    Restart Time Seconds:  15
Status:
  Conditions:
    Last Transition Time:  2025-03-07T16:21:59Z
    Message:
    Observed Generation:   1
    Reason:                MissingAuthSecret
    Status:                False
    Type:                  cilium.io/MissingAuthSecret
Events:                    <none>

$ kubectl logs cilium-operator-f4589588d-f7kl9 -n kube-system
[...]
time="2025-03-07T16:18:34.982147067Z" level=info msg=" - !:etcd_node" subsys=labels-filter
time="2025-03-07T16:18:34.982166402Z" level=info msg="Final node label prefixes to be used for identity evaluation:" subsys=labels-filter
time="2025-03-07T16:18:34.982185107Z" level=info msg="Initialization complete" subsys=cilium-operator-generic
time=2025-03-07T16:18:34Z level=info msg="Start hook executed" module=operator.operator-controlplane function=cmd.(*legacyOnLeader).onStart duration=629.951395ms
time=2025-03-07T16:18:34Z level=info msg="Starting CRD identity garbage collector" module=operator.operator-controlplane.leader-lifecycle.k8s-identities-gc interval=15m0s
time=2025-03-07T16:18:34Z level=info msg="Start hook executed" module=operator.operator-controlplane function="identitygc.registerGC.func1 (.../operator/identitygc/gc.go:116)" duration=7.51041ms
time=2025-03-07T16:18:34Z level=info msg="Start hook executed" module=operator.operator-controlplane function=*job.group.Start duration=6.056µs
time=2025-03-07T16:18:34Z level=info msg="Start hook executed" module=operator.operator-controlplane function=*job.group.Start duration=1.963µs
time=2025-03-07T16:18:34Z level=info msg="Starting to garbage collect stale CiliumEndpoint custom resources" module=operator.operator-controlplane.leader-lifecycle.k8s-endpoints-gc
time=2025-03-07T16:18:34Z level=info msg="Start hook executed" module=operator.operator-controlplane function=*endpointgc.GC.Start duration=103.547µs
time=2025-03-07T16:18:34Z level=info msg="Start hook executed" module=operator.operator-controlplane function=*job.group.Start duration=19.317µs
time=2025-03-07T16:18:34Z level=info msg="Start hook executed" module=operator.operator-controlplane function=*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.CiliumNetworkPolicy].Start duration=10.908µs
time=2025-03-07T16:18:34Z level=info msg="Start hook executed" module=operator.operator-controlplane function=*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.CiliumClusterwideNetworkPolicy].Start duration=6.056µs
time=2025-03-07T16:18:34Z level=info msg="Start hook executed" module=operator.operator-controlplane function=*job.group.Start duration=18.705µs
time=2025-03-07T16:18:35Z level=info msg="Starting Controller" module=operator.operator-controlplane.leader-lifecycle.controller-runtime controller=secret controllerGroup="" controllerKind=Secret
time=2025-03-07T16:18:35Z level=info msg="Starting workers" module=operator.operator-controlplane.leader-lifecycle.controller-runtime controller=secret controllerGroup="" controllerKind=Secret "worker count"=1
time=2025-03-07T16:18:35Z level=info msg="Reconciling secret" module=operator.operator-controlplane.leader-lifecycle.secret-sync controller=secret-syncer resource=kube-system/bootstrap-token-0gdaia
time=2025-03-07T16:18:35Z level=info msg="Successfully reconciled Secret" module=operator.operator-controlplane.leader-lifecycle.secret-sync controller=secret-syncer resource=kube-system/bootstrap-token-0gdaia action=ignored
time=2025-03-07T16:18:35Z level=info msg="Reconciling secret" module=operator.operator-controlplane.leader-lifecycle.secret-sync controller=secret-syncer resource=kube-system/cilium-ca
time=2025-03-07T16:18:35Z level=info msg="Successfully reconciled Secret" module=operator.operator-controlplane.leader-lifecycle.secret-sync controller=secret-syncer resource=kube-system/cilium-ca action=ignored
time=2025-03-07T16:18:35Z level=info msg="Reconciling secret" module=operator.operator-controlplane.leader-lifecycle.secret-sync controller=secret-syncer resource=kube-system/hubble-server-certs
time=2025-03-07T16:18:35Z level=info msg="Successfully reconciled Secret" module=operator.operator-controlplane.leader-lifecycle.secret-sync controller=secret-syncer resource=kube-system/hubble-server-certs action=ignored
time=2025-03-07T16:18:35Z level=info msg="Reconciling secret" module=operator.operator-controlplane.leader-lifecycle.secret-sync controller=secret-syncer resource=kube-system/sh.helm.release.v1.cilium.v1
time=2025-03-07T16:18:35Z level=info msg="Successfully reconciled Secret" module=operator.operator-controlplane.leader-lifecycle.secret-sync controller=secret-syncer resource=kube-system/sh.helm.release.v1.cilium.v1 action=ignored
time="2025-03-07T16:18:35.083080469Z" level=info msg="CiliumNodes caches synced with Kubernetes" subsys=cilium-operator-generic
time=2025-03-07T16:19:34Z level=info msg="Cilium pod running for node; marking accordingly" module=operator.operator-controlplane.leader-lifecycle.legacy-cell subsys=watchers nodeName=sffb-k8s101
time=2025-03-07T16:21:59Z level=info msg="Reconciling secret" module=operator.operator-controlplane.leader-lifecycle.secret-sync controller=secret-syncer resource=kube-system/bgp-auth-secret
time=2025-03-07T16:21:59Z level=info msg="Successfully reconciled Secret" module=operator.operator-controlplane.leader-lifecycle.secret-sync controller=secret-syncer resource=kube-system/bgp-auth-secret action=ignored
time=2025-03-07T16:21:59Z level=info msg="LB-IPAM done initializing" module=operator.operator-controlplane.leader-lifecycle.lbipam
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
