### ISSUE TITLE
Cilium Gateway API should expose Envoy Proxy settings

### ISSUE THREAD

**Issue by bardiharborow** [cilium/cilium#38089]
The Cilium Gateway API should expose a mechanism to modify the Envoy proxy settings.

An example of a configuration snippet configuring TLS curves one might want to specify through the Gateway API:
```yaml
          transportSocket:
            name: envoy.transport_sockets.tls
            typedConfig:
              '@type': >-
                type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              commonTlsContext:
                tls_params:
                  ecdh_curves:
                    - X25519MLKEM768
                    - X25519Kyber768Draft00
                    - X25519
                    - P-256
```
