### ISSUE TITLE
CFP: Support Node Labels in Cilium IPAM Multi-Pool Allocator

### ISSUE THREAD

**Issue by acudovs** [cilium/cilium#38102]
## Description

We are migrating from Calico to Cilium and encountered an issue with the differences in IPAM allocation methods.

Our setup in Calico relies on **native routing** with **BGP** announcements and multiple IP pools, which are assigned to nodes based on their labels (locations). For example:

```
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: default-ipv4-ippool
spec:
  blockSize: 26
  cidr: 10.0.0.0/16
  nodeSelector: !has(network.example.com/ippool)
  vxlanMode: Never
---
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: datacenter2-pool
spec:
  blockSize: 26
  cidr: 10.1.0.0/16
  nodeSelector: has(network.example.com/ippool) && network.example.com/ippool=='datacenter2'
  vxlanMode: Never
```

During node provisioning, we label nodes in Datacenter2 with `network.example.com/ippool: datacenter2`, allowing Calico to allocate pod IPs from the appropriate pool.

## Problem Statement

Cilium cannot allocate PodCIDRs based on node labels, a feature that exists in Calico. The available allocators in https://github.com/cilium/cilium/tree/main/pkg/ipam/allocator do not support this functionality.

## Alternatives Considered

The only workaround found is to use `ipam.mode: kubernetes` and manually assign `spec.podCIDR` in node objects, which shifts IP management responsibility away from the CNI.

## Cilium Feature Proposal

We propose adding support for node labels in the Multi-Pool allocator to enable assigning PodCIDRs based on node attributes. This would allow users to retain a similar setup to Calico without manually managing CIDRs.

## Slack Discussion

https://cilium.slack.com/archives/C1MATJ5U5/p1741513279751249

## Questions

Would it be beneficial to introduce this feature in future releases?

Are there any existing workarounds within Cilium, other than using `ipam.mode: kubernetes`, that would enable similar behavior?

**Comment by gandro** [comment]
Is this a duplicate of https://github.com/cilium/cilium/issues/27131?

In particular, it is (thanks to https://github.com/cilium/cilium/pull/28818) possible to set a per-node default pool by setting `ipam-default-ip-pool` in a `CiliumNodeConfig` which allows you to overwrite the Cilium ConfigMap on nodes matching certain node labels.

It's not well documented (PRs welcome!), but I believe this should cover your usecase?

**Comment by acudovs** [comment]
PR https://github.com/cilium/cilium/pull/38135

**Comment by acudovs** [comment]
@gandro 

I discovered strange behavior while testing multi-pool with native routing and BGP. Network connections from other pods to pods running on Cilium nodes returned a TTL exceeded error.

```
ping 10.44.0.43
PING 10.44.0.43 (10.44.0.43) 56(84) bytes of data.
From 10.10.26.2 icmp_seq=1 Time to live exceeded
```

While the cluster-pool previously worked as expected, I compared the Cilium agent logs, CiliumNode resources, and routing tables on the same node running cluster-pool versus multi-pool.

The reason connections are not working is that the Cilium agent in multi-pool mode uses an auto-generated IPv4 allocation range and adds an invalid route to the routing table. As a result, incoming packets to the pod IP are sent back to the default route instead of the pod, and after a loop, the TTL exceeded error occurs.

## cluster-pool

**CiliumNode**
```
apiVersion: cilium.io/v2
kind: CiliumNode
spec:
  addresses:
  - ip: 10.10.26.14
    type: InternalIP
  - ip: 10.44.0.17
    type: CiliumInternalIP
  health:
    ipv4: 10.44.0.5
  ipam:
    podCIDRs:
    - 10.44.0.0/26
    pools: {}
```

**ip route**
```
10.44.0.0/26 via 10.44.0.17 dev cilium_host proto kernel src 10.44.0.17
```

**cilium-agent logs**
```
time="2025-03-12T12:54:59.743716524Z" level=info msg="Received own node information from API server" ipAddr.ipv4=10.10.26.14 ipAddr.ipv6="<nil>" k8sNodeIP=10.10.26.14 labels="map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:ktestcluster10-t kubernetes.io/os:linux network.evolution.com/bgppeer:rix3 network.evolution.com/cni:cilium node-role.evolutiongaming.com/os-version:ol9 node-role.kubernetes.io/worker:true]" nodeName=ktestcluster10-t subsys=daemon v4Prefix=10.44.0.0/26 v6Prefix="<nil>"

time="2025-03-12T12:55:00.101936651Z" level=info msg="Initializing cluster-pool IPAM" subsys=ipam v4Prefix=10.44.0.0/26 v6Prefix="<nil>"

time="2025-03-12T12:55:00.103435006Z" level=info msg="  IPv4 allocation prefix: 10.44.0.0/26" subsys=daemon
```

## multi-pool

**CiliumNode**
```
apiVersion: cilium.io/v2
kind: CiliumNode
spec:
  addresses:
  - ip: 10.10.26.14
    type: InternalIP
  - ip: 10.44.0.42
    type: CiliumInternalIP
  health:
    ipv4: 10.44.0.33
  ipam:
    pools:
      allocated:
      - cidrs:
        - 10.44.0.0/26
        pool: default
      requested:
      - needed:
          ipv4-addrs: 16
        pool: default

```

**ip route**
```
10.14.0.0/16 via 10.44.0.42 dev cilium_host proto kernel src 10.44.0.42
```

**cilium-agent logs**
```
time="2025-03-12T13:09:26.1053747Z" level=info msg="Received own node information from API server" ipAddr.ipv4=10.10.26.14 ipAddr.ipv6="<nil>" k8sNodeIP=10.10.26.14 labels="map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:ktestcluster10-t kubernetes.io/os:linux network.evolution.com/bgppeer:rix3 network.evolution.com/cni:cilium node-role.evolutiongaming.com/os-version:ol9 node-role.kubernetes.io/worker:true]" nodeName=ktestcluster10-t subsys=daemon v4Prefix="<nil>" v6Prefix="<nil>"

time="2025-03-12T13:09:26.10790285Z" level=info msg="Using autogenerated IPv4 allocation range" subsys=node v4Prefix=10.14.0.0/16

time="2025-03-12T13:09:26.648280173Z" level=info msg="  IPv4 allocation prefix: 10.14.0.0/16" subsys=daemon
```

I'm trying to figure out how to fix the issue. If you have any ideas, it would be helpful.
