### ISSUE TITLE
IPs from CiliumLoadBalancerIPPool not getting assigned to the API Gateway resource

### ISSUE THREAD

**Issue by cloudvlad** [cilium/cilium#38123]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.1 and lower than v1.18.0

### What happened?

The Gateway resources was unable to get an IP address from the IP pool defined in the Cilium's CR `CiliumLoadBalancerIPPool`.
The created resource was from type `ClusterIP`.

### How can we reproduce the issue?

1. Create a Kubernetes cluster (with `kubeadm`)
```shell
sudo kubeadm init --config kubeadm_init.yaml --skip-phases=addon/kube-proxy
```
**Note:** This was done according to [this](https://docs.cilium.io/en/stable/installation/k8s-install-kubeadm/) documentation.

2. Deploy the K8s API Gateway CRDs
(The ones described [here](https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/#prerequisites).)

3. Deploy the Cilium Helm chart in the **kube-system** namespace
```shell
helm upgrade --install networking . --values values.yaml -n kube-system
```

```yaml
cilium:
  enabled: true
  kubeProxyReplacement: "true"
  gatewayAPI:
    enabled: true
    gatewayClass:
      create: "true"
    hostNetwork:
      enabled: true
```

**Notes:** 
- This namespace was used as it is used in the setup in [this](https://docs.cilium.io/en/stable/installation/k8s-install-kubeadm/) guide.
-  The Cilium Helm chart is part of an umbrella chart. It is the only chart there right now.
- The Value overrides were based on the arguments of [this](https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/#prerequisites) API Gateway guide

4. Create custom resources
Two resources were created:
```yaml
# templates/gateway.yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: cilium-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
```

```yaml
# templates/lb-ip-pool.yaml
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "machine-public-ips"
spec:
  blocks:
    - cidr: "1.2.3.4/32"
```

5. (Optional) Trying the `io.cilium/lb-ipam-ips` annotation
I really wanted the IP address to be assigned automatically, however this didn't work either:
```yaml
# templates/gateway.yaml
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: "1.2.3.4" #  tried also "1.2.3.4/32"
```

6. (Optional) Manually Creating LoadBalancer
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
```

The created resource gets an IP from the pool defined in the `CiliumLoadBalancerIPPool` CR instance and the number of available IP addresses is decremented with 1. (for mask /32  it changes from 1 to 0)

### Cilium Version

1.17.1

### Kernel Version

6.8.0-55-generic

### Kubernetes Version

1.32.0

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by zozo6015** [comment]
You need to create a Cilium L2 Announcement policy or configure BGP if you have some router/switch that supports that.

**Comment by cloudvlad** [comment]
Hmm, sorry for not double-checking the entire chain to ensure everything is okay

I had to enable some networking in the meantime, so I was still using the old configurations.

The GatewayClass's Accepted field is set to `true`, and the controller is `io.cilium/gateway-controller`
However, the Gateway resource is not functioning as expected:
```
Name:         cilium-gateway                                                                                                                                                                  
Namespace:    kube-system                                                                                                                                                                     
Labels:       app.kubernetes.io/managed-by=Helm                                                                                                                                               
Annotations:  meta.helm.sh/release-name: cilium                                                                                                                                               
              meta.helm.sh/release-namespace: kube-system                                                                                                                                     
API Version:  gateway.networking.k8s.io/v1                                                                                                                                                    
Kind:         Gateway                                                                                                                                                                         
Metadata:                                                                                                                                                                                     
  Creation Timestamp:  2025-03-17T21:17:55Z                                                                                                                                                   
  Generation:          1                                                                                                                                                                      
  Resource Version:    29794                                                                                                                                                                  
  UID:                 022fdf4d-dc95-4fa6-9289-f8b8d40022ba                                                                                                                                   
Spec:                                                                                                                                                                                         
  Gateway Class Name:  cilium                                                                                                                                                                 
  Listeners:                                                                                                                                                                                  
    Allowed Routes:                                                                                                                                                                           
      Namespaces:                                                                                                                                                                             
        From:  All                                                                                                                                                                            
    Hostname:  my-domain.net                                                                                                                                                                  
    Name:      http                                                                                                                                                                           
    Port:      80                                                                                                                                                                             
    Protocol:  HTTP                                                                                                                                                                           
Status:                                                                                                                                                                                       
  Conditions:                                                                                                                                                                                 
    Last Transition Time:  1970-01-01T00:00:00Z                                                                                                                                               
    Message:               Waiting for controller                                                                                                                                             
    Reason:                Pending                                                                                                                                                            
    Status:                Unknown                                                                                                                                                            
    Type:                  Accepted                                                                                                                                                           
    Last Transition Time:  1970-01-01T00:00:00Z                                                                                                                                               
    Message:               Waiting for controller                                                                                                                                             
    Reason:                Pending                                                                                                                                                            
    Status:                Unknown                                                                                                                                                            
    Type:                  Programmed                                                                                                                                                         
Events:                    <none> 
```

I tried deploying it in the `kube-system` namespace, as well as the one where I am deploying workload that is supposed to respond to `my-domain.net`

I would really appreciate any advice

**Comment by zozo6015** [comment]
Could you take out the nodeSelector from the L2AnnouncementPolicy? I would use the suggestion from the documentation to have the nodeSelector being configured to any node that is not control-plane.  Something like this:

```
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
```

If you want to control what service is getting the ip addresses assigned you might want to add some serviceSelectors and then on the gateway side you can use something like:

```
spec:
  infrastructure:
    labels:
      key: value
```

Also look at the leases to make sure your L2AnnouncementPolicy is creating the lease properly. That should tell you on which node the ip address will be announced.

```
kubectl get leases -A
```

**Comment by cloudvlad** [comment]
Thank you, Zozo,

I know it’s bad practice, but I crrently have only one node serving as both the control plane ,and the worker node
 In this case, I don’t want to ignore this node since it's the only one available

As for the second thing, I assume there will be one Gateway, which means one Load Balancer and, and one external IP
So I hoped the Gateway to create its Loadbalnacer which will consume it

I checked the leases in the cluster. looks good to me
```
kube-node-lease   castle                                                      castle                                                                     4h56m
kube-system       apiserver-shymr7q7noqvcfhvwubexvyxn4                        apiserver-shymr7q7noqvcfhvwubexvyxn4_b04c39c0-f083-4d79-b352-bfbc5c6f7e73   4h56m
<... several more ...>
```

About the service, created by the Gateway - it is not created. Not quite sure why.
Btw this Gateway can be used by any namespace as per my understanding:
```yaml
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
```

Notes:
- Just wanted to emphasize on the fact that I am using a custom names for the in the Kubeadm configuration file:
Can the problem be related to that?
```
nodeRegistration:
  name: castle
...
clusterName: my-castle
...
networking:
  dnsDomain: my-castle.net
```

**Comment by zozo6015** [comment]
Then maybe you just take out the nodeSelector completely. Also check the cilium operator maybe you get some info there why the LoadBalancer service is not being created.

**Comment by zozo6015** [comment]
What you get if you run `kubectl get gatewayclass`?

The TLSROUTE CRDS are required for the cilium gatewayclass to be accepted for quite a few versions now.

**Comment by cloudvlad** [comment]
the output of `kubectl get gateways`:
```
NAME     CONTROLLER                     ACCEPTED   AGE
cilium   io.cilium/gateway-controller   True       79m
```

About this error `cannot bind '0.0.0.0:80': Permission denied` which I pasted above:
the fix was to disable the node protection:
```
cilium:
  nodePort:
    bindProtection: false
```

Now Im running into:
```
time=2025-03-19T10:35:38Z level=info msg="Successfully reconciled Secret" module=operator.operator-controlplane.leader-lifecycle.secret-sync controller=secret-syncer resource=kube-system/sh.
helm.release.v1.cilium.v18 action=ignored
...
time=2025-03-19T10:35:38Z level=info msg="Reconciler error" module=operator.operator-controlplane.leader-lifecycle.controller-runtime controller=gateway controllerGroup=gateway.networking.k8
s.io controllerKind=Gateway Gateway.name=my-gateway Gateway.namespace=default namespace=default name=my-gateway reconcileID=beae9807-92cf-46d7-b03f-1c769031d0f7 error="failed to update Gatew
ay status: Operation cannot be fulfilled on gateways.gateway.networking.k8s.io \"my-gateway\": the object has been modified; please apply your changes to the latest version and try again"
...
time=2025-03-19T10:35:38Z level=info msg="Reconciling Gateway" module=operator.operator-controlplane.leader-lifecycle.gateway-api controller=gateway resource=default/my-gateway
```

**Comment by egrosdou01** [comment]
For anyone facing similar issues, I tested RKE2 v1.31.9+rke2r1 with Cilium v1.17.3. Initially, I bootstrapped the cluster using the below Cilium Helm Chart values.

```
externalIPs:
  enabled: true
gatewayAPI:
  enabled: true
k8sClientRateLimit:
  burst: 40
  qps: 20
kubeProxyReplacement: true
l2announcements:
  enabled: true
```

While the RKE2 cluster installation was ongoing, I deployed the Gateway API CRDs. Check out the Cilium documentation [here](https://docs.cilium.io/en/v1.17/network/servicemesh/gateway-api/gateway-api/#gs-gateway-api).

Once the cluster was in a "Ready" state, I updated the Helm chart values and included the below.

```
gatewayAPI:
  enabled: true
  gatewayClass:
    create: "true"
```

The above changed allowed the creation of the Cilium GatewayClass. 

For my setup, the `CiliumLoadBalancerIPPool` and the `CiliumL2AnnouncementPolicy` were created. Find the information in the link below.
-  [L2 Announcements](https://docs.cilium.io/en/v1.17/network/l2-announcements/#l2-announcements)

After that, the Gateway resources had the PROGRAMMED section set to True.
