### ISSUE TITLE
Node IPAM LB and HostNetwork Ingress Controller not working

### ISSUE THREAD

**Issue by stearz** [cilium/cilium#38175]
### The use-case:
I want to use cilium as the CNI on a Kubernetes cluster running on Talos at an edge location.

I don't have the ability to influence networking at the edge location, so I wanted to use Cilium's Node IPAM LB and the host network Ingress Controller to expose services to the outside world.

### The issue:
Unfortunately Node IPAM LB is not working (LoadBalancer services do not get an external IP address)
Additionally the ingress controller seems to be configurable only with one port. - Is there a way to serve HTTP and HTTPS with the cilium ingress controller then?

### Versions used:
- Talos: v1.9.2
- Kubernetes: 1.30.2
- Cilium Helm Chart: 1.17.1

### Steps for local reproduction:
Run Talos with this cluster-patch.yaml:
```
cluster:
  network:
    cni:
      name: none
  proxy:
    disabled: true
```

Install Cilium with the Helm Chart:
```
export CILIUM_VERSION=1.17.1
helm repo add cilium https://helm.cilium.io/
helm repo update

helm template \
    cilium \
    cilium/cilium \
    --version "$CILIUM_VERSION" \
    --namespace kube-system \
    --set kubeProxyReplacement=true \
    --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID,NET_BIND_SERVICE}" \
    --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
    --set cgroup.autoMount.enabled=false \
    --set cgroup.hostRoot=/sys/fs/cgroup \
    --set gatewayAPI.enabled=true \
    --set gatewayAPI.enableAlpn=true \
    --set gatewayAPI.enableAppProtocol=true \
    --set ingressController.enabled=true \
    --set ingressController.loadbalancerMode=shared \
    --set ingressController.default=true \
    --set ingressController.hostNetwork.enabled=true \
    --set ingressController.hostNetwork.sharedListenerPort="443" \
    --set ingressController.service.externalTrafficPolicy=null \
    --set ingressController.service.type=ClusterIP \
    --set envoy.securityContext.capabilities.keepCapNetBindService=true \
    --set envoy.securityContext.capabilities.envoy="{NET_ADMIN,SYS_ADMIN,NET_BIND_SERVICE}" \
    --set encryption.enabled=true \
    --set encryption.type=wireguard \
    --set encryption.nodeEncryption=true \
    --set ipam.mode=kubernetes \
    --set nodeIPAM.enabled=true \
    --set defaultLBServiceIPAM=nodeipam \
    --set operator.replicas=1 \
    --set k8sServiceHost=localhost \
    --set k8sServicePort=7445 > cilium.yaml

kubectl apply -f cilium.yaml
```

Create a hello-world LoadBalancer service:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:latest
        ports:
        - containerPort: 8080
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-lb
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 4711
      targetPort: 8080
  type: LoadBalancer
```

### Expectation:
The service `hello-world-lb` should be accessible on the IP address of the Talos node on port 4711.

**Comment by MrFreezeex** [comment]
Hello regarding the node ipam issue, could you send the dump of the service load balancer (and in particular his status) also the logs of the cilium operator would be helpful. Thanks!

**Comment by stearz** [comment]
Here is the output of a `kubectl get service hello-world-lb -o yaml`:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"hello-world-lb","namespace":"default"},"spec":{"ports":[{"port":4711,"protocol":"TCP","targetPort":8080}],"selector":{"app":"hello-world"},"type":"LoadBalancer"}}
  creationTimestamp: "2025-03-13T12:02:38Z"
  name: hello-world-lb
  namespace: default
  resourceVersion: "69091"
  uid: 076c01be-fb39-40f9-ace8-3ebe03d85335
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.101.115.116
  clusterIPs:
  - 10.101.115.116
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32717
    port: 4711
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

Attached is the log output of the cilium-operator pod:

[cilium-operator.log](https://github.com/user-attachments/files/19243015/cilium-operator.log)

Let me know if you need more information.

**Comment by MrFreezeex** [comment]
Could you check if you have any nodes (as of the Node resource in Kubernetes) that match the following condition:
- is not being deleted (deletion timestamp field should be zero)
- Does not have the label "node.kubernetes.io/exclude-from-external-load-balancers"
- Does not have the taint "ToBeDeletedByClusterAutoscaler"?

**Comment by stearz** [comment]
Thank you for showing me the right direction. I was able to solve this:

As we are deploying a single-node cluster we had to remove the node label `node.kubernetes.io/exclude-from-external-load-balancers` by patching the Talos machine config:

```
machine:
  nodeLabels:
    node.kubernetes.io/exclude-from-external-load-balancers:
      $patch: delete
```
