### ISSUE TITLE
Gateway with TCP/UDP listener not working.

### ISSUE THREAD

**Issue by zozo6015** [cilium/cilium#38192]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.1 and lower than v1.18.0

### What happened?

Running a local cluster using k0s with cilium cni. 
Configured gateway-api. Gateway with HTTP protocol works fine. When tried to combined HTTP listeners with TCP and UDP listeners. Gateway was accepted and configured but the Loadbalancer service only had port 80 configured. Then configured a new Gateway with TCP listener  only with the following configuration:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: dns-gateway
  namespace: kube-system
spec:
  gatewayClassName: cilium
  listeners:
    - allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              enable-public: 'true'
        kinds:
        - kind: TCPRoute
      name: dns-tcp
      port: 53
      protocol: TCP      
```

The gateway was not accepted. In the operator logs I can see the following error:

```
time=2025-03-13T23:19:33Z level=info msg="Reconciling Gateway" module=operator.operator-controlplane.leader-lifecycle.gateway-api controller=gateway resource=kube-system/dns-gateway
time=2025-03-13T23:19:33Z level=error msg="Unable to translate resources" module=operator.operator-controlplane.leader-lifecycle.gateway-api controller=gateway resource=kube-system/dns-gateway error="model source can't be empty"
time=2025-03-13T23:19:33Z level=error msg="Reconciler error" module=operator.operator-controlplane.leader-lifecycle.controller-runtime controller=gateway controllerGroup=gateway.networking.k8s.io controllerKind=Gateway Gateway.name=dns-gateway Gateway.namespace=kube-system namespace=kube-system name=dns-gateway reconcileID=c48b76ef-b7b1-4098-adc6-097651e6667a error="model source can't be empty"
time=2025-03-13T23:19:33Z level=info msg="Reconciling Gateway" module=operator.operator-controlplane.leader-lifecycle.gateway-api controller=gateway resource=kube-system/dns-gateway
time=2025-03-13T23:19:33Z level=error msg="Unable to translate resources" module=operator.operator-controlplane.leader-lifecycle.gateway-api controller=gateway resource=kube-system/dns-gateway error="model source can't be empty"
time=2025-03-13T23:19:33Z level=error msg="Reconciler error" module=operator.operator-controlplane.leader-lifecycle.controller-runtime controller=gateway controllerGroup=gateway.networking.k8s.io controllerKind=Gateway Gateway.name=dns-gateway Gateway.namespace=kube-system namespace=kube-system name=dns-gateway reconcileID=b42d3520-78c8-4019-8fe4-9cbe6cc2dcbf error="model source can't be empty"
```

### How can we reproduce the issue?

install cilium with cilium cli with following options:

```
cilium upgrade --version 1.17.1 --set l2announcements.enabled=true \
  --set externalIPs.enabled=true \
  --set kubeProxyReplacement=true --set l2-announcements-lease-duration=3s --set l2-announcements-renew-deadline=1s --set l2-announcements-retry-period=500ms --set prometheus.enabled=true --set operator.prometheus.enabled=true --set gatewayAPI.enabled=true
``` 

deploy all the CRD's required for the gateway-api. Create a gateway with the above configuration.

### Cilium Version

1.17.1

### Kernel Version

Linux zolab-worker1 6.11.0-1009-raspi #9-Ubuntu SMP PREEMPT_DYNAMIC Tue Feb 18 07:50:20 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

❯ kubectl version
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.32.2+k0s

### Sysdump

[cilium-sysdump-20250314-012504.zip](https://github.com/user-attachments/files/19238144/cilium-sysdump-20250314-012504.zip)

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
