### ISSUE TITLE
CFP: Add support for excluding address ranges from CiliumCIDRGroups

### ISSUE THREAD

**Issue by solidDoWant** [cilium/cilium#38208]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

I'd like to create a CIDR group that encompasses the Internet, but includes my intranet, link-local networks, and other reserved IP space. This is doable today, but even the most compact form of "/0 subnet - reserved subnets" is a pretty large list. This is both difficult to read, and difficult to maintain.

**Describe the feature you'd like**

I would like the ability to specify one or more subnets, and then exclude specific subnets from the specified CIDRs. This would turn the below resource:

```yaml
---
apiVersion: cilium.io/v2alpha1
kind: CiliumCIDRGroup
metadata:
  name: internet
spec:
  # Public IP space without private subnets
  # Script:
  # python -c 'reserved=["10.0.0.0/8","172.16.0.0/12","192.168.0.0/16"];from netaddr import IPSet,IPNetwork;world=IPSet(IPNetwork("0.0.0.0/0"));excluded=IPSet([IPNetwork(n) for n in reserved]); [print(f"   - {n}") for n in (world ^ excluded).iter_cidrs()]'
  # This will look much worse when/if I add additional reserved IP space (https://en.wikipedia.org/wiki/Reserved_IP_addresses)
  externalCIDRs:
   - 0.0.0.0/5
   - 8.0.0.0/7
   - 11.0.0.0/8
   - 12.0.0.0/6
   - 16.0.0.0/4
   - 32.0.0.0/3
   - 64.0.0.0/2
   - 128.0.0.0/3
   - 160.0.0.0/5
   - 168.0.0.0/6
   - 172.0.0.0/12
   - 172.32.0.0/11
   - 172.64.0.0/10
   - 172.128.0.0/9
   - 173.0.0.0/8
   - 174.0.0.0/7
   - 176.0.0.0/4
   - 192.0.0.0/9
   - 192.128.0.0/11
   - 192.160.0.0/13
   - 192.169.0.0/16
   - 192.170.0.0/15
   - 192.172.0.0/14
   - 192.176.0.0/12
   - 192.192.0.0/10
   - 193.0.0.0/8
   - 194.0.0.0/7
   - 196.0.0.0/6
   - 200.0.0.0/5
   - 208.0.0.0/4
   - 224.0.0.0/3
```

into something like:

```yaml
---
apiVersion: cilium.io/v2alpha1
kind: CiliumCIDRGroup
metadata:
  name: internet
spec:
  externalCIDRs:
    - 0.0.0.0/0
  exceptCIDRs:
   - 10.0.0.0/8
   - 172.16.0.0/12
   - 192.168.0.0/16
```

This functionality already exists on Cilium netpols via the `except` field, but the the excluded addresses must be specified on every policy, which is difficult to maintain and prone to mistakes.

**(Optional) Describe your proposed solution**

See above

**Comment by solidDoWant** [comment]
not stale

**Comment by solidDoWant** [comment]
not stale

**Comment by solidDoWant** [comment]
Not stale
This bot really sucks

**Comment by solidDoWant** [comment]
not stale
asked about this on slack in hopes that it can be either accepted or closed, or at least have the bot disabled on it.

**Comment by joestringer** [comment]
Could you speak a bit about how you would like to use this group referring to Internet range IPs?

**Comment by solidDoWant** [comment]
Thanks for taking a look Joe. I have some workloads that are untrusted, but that I want to have internet access. Examples of this include:
* VPN gateways
* Relay (e.g. TOR) exit tunnels/nodes
* Untrusted, publicly available services (e.g. video game servers)
* CI/CD tools like Flux that need to download Helm chart, Kubernetes manifests from lots of different internet sites but not local services

I'd like to use this group to limit access to only services publicly available on the internet, and nothing local.

**Comment by squeed** [comment]
Unfortunately this sort of thing is somewhat difficult to do with the current implementation of CiliumCIDRGroups. (This is because it is only possible to have exclusions with selectors, not labels).

However, you can solve your problem another way, thanks to the magic of label selectors. First of all, create a CCG with your internal CIDRs. Then, create a policy that selects `reserved:world` but not `cidrgroup:io.cilium.policy.cidrgroupname/internal`. This will "hole-punch" `world` correctly.

Something like this:
```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumCIDRGroup
metadata:
  name: internal
spec:
  externalCIDRs:
    - "192.0.2.0/24"

---

apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-world-not-internal
spec:
  endpointSelector: {}
  egress:
  - toEndpoints:
    - matchExpressions:
      - key: cidrgroup:io.cilium.policy.cidrgroupname/internal
        operator: DoesNotExist
      - key: "reserved:world"
        operator: Exists
```

I've verified that this permits traffic to world IPs but not those in the `internal` CCG.
