### ISSUE TITLE
Missing Routes after 1.17

### ISSUE THREAD

**Issue by Seljuke** [cilium/cilium#38215]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.1 and lower than v1.18.0

### What happened?

I was testing out cilium with dual-stack configuration using [k3s-ansible](https://github.com/k3s-io/k3s-ansible) installation. Cluster with Cilium 1.16.8 works fine but after I reset the nodes and try to create a new cluster with Cilium 1.17.2 Coredns hangs at 0/1 running state  with `dial tcp 10.43.0.1:443: i/o timeout` errors. 

All cilium agents are running without  errors in their logs, only difference I can find is Cilium add routes to the control node on version 1.16 but doesn't add them on 1.17.2. 

### How can we reproduce the issue?

1. Create 3 vm with official Ubuntu Server 24.04.2 iso
2. Install k3s version v.1.32.2+k3s1(tried with 1.31 also same result) using below server config file
```
  tls-san:
    - 192.168.178.11
  flannel-backend: none
  disable-network-policy: true
  disable-kube-proxy: true
  default-local-storage-path: /srv/k3s-local-storage
  disable:
  - traefik
  - servicelb
  cluster-cidr: 10.42.0.0/16,fd01::/48
  service-cidr: 10.43.0.0/16,fd02::/112
```
3- Install Cilium 1.17.2 with helm chart. Values:
```
operator:
  replicas: 1
kubeProxyReplacement: true
k8sServiceHost: 192.168.178.11
k8sServicePort: 6443
gatewayAPI:
  enabled: true
routingMode: native
ipv4NativeRoutingCIDR: "10.42.0.0/16"
ipv6NativeRoutingCIDR: "fd01::/48"
autoDirectNodeRoutes: true
ipv4:
  enabled: true
ipv6:
  enabled: true
socketLB:
  hostNamespaceOnly: true
  enabled: true
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList: "10.42.0.0/16"
    clusterPoolIPv4MaskSize: 24
    clusterPoolIPv6PodCIDRList: "fd01::/48"
    clusterPoolIPv6MaskSize: 64
bpf:
  masquerade: true
k8sClientRateLimit:
  qps: 32
  burst: 60
```

### Cilium Version

1.17.2

### Kernel Version

6.8.0-55-generic

### Kubernetes Version

v1.32.2+k3s1

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
