### ISSUE TITLE
Cilium Gateway API with NodePort not working on K3s - Gateway Service remains ClusterIP

### ISSUE THREAD

**Issue by jlxq0** [cilium/cilium#38227]
**Description:**

I am trying to set up a simple Gateway API example using NodePort with Cilium on a K3s cluster. The Gateway is successfully programmed, and the HTTPRoute is attached, but the Cilium Gateway controller does not create a NodePort service. Instead, it creates a ClusterIP service, preventing external access via NodePort. (Which I need to point my external load balancer at.)

**Environment:**

*   K3s: v1.31.6+k3s1
*   Cilium: 1.18.0-pre.0
*   Gateway API: v1.2.1
*   Operating System: Debian GNU/Linux 12 (bookworm)
*   Kernel: 6.1.0-31-amd64
*   Container Runtime: containerd://2.0.2-k3s2

**Setup:**

I have a 3-node K3s cluster on Proxmox on a Hetzner dedicated server. Each node has its own dedicated IP address.

I installed K3s with the following commands:

```bash
sudo curl -sfL https://get.k3s.io | sh -s - server \
    --cluster-init \
    --write-kubeconfig-mode=644 \
    --disable=traefik \
    --flannel-backend=none \
    --disable-network-policy \
    --disable-kube-proxy \
    --disable=servicelb
```

and

```bash
sudo curl -sfL https://get.k3s.io | K3S_TOKEN=***redacted*** sh -s - server \
    --server https://cp2.lindner.earth:6443 \
    --write-kubeconfig-mode=644 \
    --disable=traefik \
    --flannel-backend=none \
    --disable-network-policy \
    --disable-kube-proxy \
    --disable=servicelb
```

Then I installed the Cilium CRDs:

```bash
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/experimental-install.yaml
```

And Cilium:

```bash
helm install -n kube-system cilium cilium/cilium -f cilium.yaml --version 1.18.0-pre.0
```

My cilium values are:

```
k8sServiceHost: ***redacted***
k8sServicePort: 6443
kubeProxyReplacement: true

data:
  debug: true

ipam:
  mode: "kubernetes"
  operator:
    clusterPoolIPv4PodCIDR: 10.42.0.0/16
    clusterPoolIPv4MaskSize: 24

operator:
  replicas: 2
  rollOutPods: true
  rollOutCiliumPods: true

gatewayAPI:
  enabled: true
  hostNetwork:
    enabled: true

nodePort:
  enabled: true

envoy:
  enabled: true
  securityContext:
    capabilities:
      envoy:
        - NET_ADMIN
        - PERFMON
        - BPF
        - NET_BIND_SERVICE
      keepCapNetBindService: true

externalEnvoyProxy: false

securityContext:
  capabilities:
    keepCapNetBindService: true

ipv4:
  enabled: true

ipv6:
  enabled: false

bpf:
  lbExternalClusterIP: true

socketLB:
  hostNamespaceOnly: true

hubble:
  relay:
    enabled: true
  ui:
    enabled: true
```

I've set up a GatewayClassConfig, GatewayClass, and Gateway with the following YAML:

```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: nodeport-gateway-config
  namespace: default
spec:
  service:
    type: NodePort
```

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium-nodeport
spec:
  controllerName: io.cilium/gateway-controller
  parametersRef:
    group: cilium.io
    kind: CiliumGatewayClassConfig
    name: nodeport-gateway-config
    namespace: default
```

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
spec:
  gatewayClassName: cilium-nodeport
  listeners:
    - name: http
      protocol: HTTP
      port: 80
```

I also have a Nginx static site with:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-nginx
  labels:
    app: static-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-nginx
  template:
    metadata:
      labels:
        app: static-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: static-nginx
spec:
  selector:
    app: static-nginx
  ports:
    - port: 80
      targetPort: 80
      name: http
```

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: static-nginx-route
spec:
  parentRefs:
    - name: cilium-gateway
      kind: Gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: static-nginx
          port: 80
```

**Observed Behavior:**

*   The Gateway is successfully programmed, and the HTTPRoute is attached.
*   However, the Cilium Gateway controller creates a `ClusterIP` service instead of a `NodePort` service for the gateway.
*   As a result, external access to the application via NodePort is not possible through the Gateway API.

```bash
kubectl get gateways.gateway.networking.k8s.io -A -o wide
```

```
NAMESPACE   NAME             CLASS             ADDRESS   PROGRAMMED   AGE
default     cilium-gateway   cilium-nodeport             True         25m
```

```bash
kubectl describe gateway cilium-gateway -n default
```

```
Name:         cilium-gateway
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1
Kind:         Gateway
Metadata:
  Creation Timestamp:  2025-03-17T06:01:35Z
  Generation:          1
  Resource Version:    3028
  UID:                 1fc26814-29a6-4597-864e-fe7f5179e284
Spec:
  Gateway Class Name:  cilium-nodeport
  Listeners:
    Allowed Routes:
      Namespaces:
        From:  Same
    Name:      http
    Port:      80
    Protocol:  HTTP
Status:
  Conditions:
    Last Transition Time:  2025-03-17T06:01:38Z
    Message:               Gateway successfully scheduled
    Observed Generation:   1
    Reason:                Accepted
    Status:                True
    Type:                  Accepted
    Last Transition Time:  2025-03-17T06:01:38Z
    Message:               Gateway successfully reconciled
    Observed Generation:   1
    Reason:                Programmed
    Status:                True
    Type:                  Programmed
  Listeners:
    Attached Routes:  1
    Conditions:
      Last Transition Time:  2025-03-17T06:01:38Z
      Message:               Listener Programmed
      Observed Generation:   1
      Reason:                Programmed
      Status:                True
      Type:                  Programmed
      Last Transition Time:  2025-03-17T06:01:38Z
      Message:               Listener Accepted
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2025-03-17T06:01:38Z
      Message:               Resolved Refs
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Name:                    http
    Supported Kinds:
      Group:  gateway.networking.k8s.io
      Kind:   HTTPRoute
Events:       <none>
```

```bash
kubectl get svc -n default -l gateway.networking.k8s.io/gateway-name=cilium-gateway
```

```
NAME                            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
cilium-gateway-cilium-gateway   ClusterIP   10.43.173.22   <none>        80/TCP    41m
```

**Troubleshooting Steps Taken:**

*   Verified that the `CiliumGatewayClassConfig` is correctly configured for NodePort.
*   Checked Cilium agent and operator logs for any errors or warnings related to service creation, NodePort, or the Gateway API controller.
*   Checked events on the Gateway for any errors or warnings.
*   Modified the `CiliumGatewayClassConfig` to explicitly define the ports.

**Expected Behavior:**

The Cilium Gateway controller should create a NodePort service for the gateway, allowing external access to the application via NodePort.

**Additional Information:**

*   I am using a pre-release version of Cilium (1.18.0-pre.0).
*   I have disabled Traefik, ServiceLB, and Kube-Proxy in my K3s setup.
*   Flannel is disabled, and Cilium is managing the network.

**Comment by jonsch318** [comment]
I'm no expert but your `hostNetwork` option is likely the culprit. 
```
gatewayAPI:
  enabled: true
  hostNetwork:
    enabled: true
```

The docs say:
Host network mode allows you to expose the Cilium Gateway API Gateway directly on the host network. This is useful in cases where a LoadBalancer Service is unavailable, such as in development environments or environments with cluster-external loadbalancers.
Once enabled, the host network port for a Gateway can be specified via spec.listeners.port. The port must be unique per Gateway resource and you should choose a port number higher than 1023 (see [Bind to privileged port](https://docs.cilium.io/en/latest/network/servicemesh/gateway-api/gateway-api/#bind-to-privileged-port)).
