### ISSUE TITLE
[egressGateway] NATed while the destination is on ipv4NativeRoutingCIDR

### ISSUE THREAD

**Issue by pasztorl** [cilium/cilium#38221]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.1 and lower than v1.18.0

### What happened?

cilium bpf nat list

```
TCP OUT10.15.0.8:443 -> 10.15.5.1:58471 XLATE_SRC 80.77.124.102:50034 Created=465sec ago NeedsCT=1
```
where
10.15.0.8 is the pod
10.15.5.1 is a vpn client on wg1 interface
ipv4NativeRoutingCIDR set to 10.0.0.0/8

The packet then never goes through on wg1.
If i delete the CilliumEgressPolicy they can communicate.

I think CilliumEgressPolicy should not NAT packets targeted to ipv4NativeRoutingCIDR. Am I miss something?

### How can we reproduce the issue?

helm values:
```
autoDirectNodeRoutes: true
bandwidthManager:
  enabled: true
bgpControlPlane:
  secretsNamespace:
    create: false
    name: network
bpf:
  datapathMode: netkit
  hostLegacyRouting: false
  lbExternalClusterIP: true
  masquerade: true
cluster:
  id: 1
  name: test-example-com
clusterDomain: k8s.test.example.com
cni:
  exclusive: false
dashboards:
  enabled: true
devices: public private wg+
egressGateway:
  enabled: true
enableIPv4Masquerade: true
enableRuntimeDeviceDetection: true
endpointRoutes:
  enabled: true
envoyConfig:
  secretsNamespace:
    create: false
    name: network
externalIPs:
  enabled: true
gatewayAPI:
  enabled: false
  secretsNamespace:
    create: false
    name: network
hostFirewall:
  enabled: true
hostPort:
  enabled: true
ingressController:
  enabled: false
  secretsNamespace:
    create: false
    name: network
ipam:
  mode: multi-pool
  operator:
    autoCreateCiliumPodIPPools:
      default:
        ipv4:
          cidrs:
          - 10.207.0.0/19
          maskSize: 28
    dashboards:
      enabled: true
      namespace: monitoring
    multiPoolPreAllocation: true
    prometheus:
      enabled: true
      labels:
        release: prometheus
      metricRelabelings: null
ipv4NativeRoutingCIDR: 10.0.0.0/8
ipv6:
  enabled: false
k8s:
  requireIPv4PodCIDR: true
  requireIPv6PodCIDR: false
k8sServiceHost: kube-api.test.example.com
k8sServicePort: 443
kubeProxyReplacement: true
l7Proxy: true
loadBalancer:
  acceleration: best-effort
  algorithm: maglev
  mode: dsr
nodePort:
  enabled: true
operator:
  dashboards:
    enabled: true
    namespace: monitoring
  prometheus:
    enabled: true
    interval: 60s
    labels:
      release: prometheus
    metricRelabelings: null
  replicas: 1
  rollOutPods: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 60s
    labels:
      release: prometheus
routing-mode: native
routingMode: native
secretsNamespace:
  create: false
  sync: false
socketLB:
  enabled: true
  hostNamespaceOnly: true
tls:
  secretsNamespace:
    create: false
    name: network
```

CiliumPodIPPool:
```
apiVersion: cilium.io/v2alpha1
kind: CiliumPodIPPool
metadata:
  name: test-example-com
spec:
  ipv4:
    cidrs:
      - 10.15.0.0/22
    maskSize: 27
```

EgressGatewayPolicy:

```
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: '$NAMESPACE-$SERVICE_NAME'
spec:
  selectors:
    - podSelector:
        matchLabels:
          io.kubernetes.pod.namespace: '$NAMESPACE'
  destinationCIDRs:
    - "0.0.0.0/0"
  egressGateway:
    nodeSelector:
      matchLabels:
        kubernetes.io/hostname: '$HOSTNAME'
    egressIP: '$IP'
```

### Cilium Version

1.17.2

### Kernel Version

6.8.0-55

### Kubernetes Version

1.32.2

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
