### ISSUE TITLE
AWS EKS Cilium CNI Not Working

### ISSUE THREAD

**Issue by elJoeyJojo** [cilium/cilium#38339]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.15.15 and lower than v1.16.0

### What happened?

I tried using the solution recommended in bug: https://github.com/cilium/cilium/issues/33780
But I still can't configure an EKS Cluster as Cilium as the CNI as the Nodes keep getting this error:

```
 Ready            False   Wed, 19 Mar 2025 12:13:50 -0600   Wed, 19 Mar 2025 12:08:32 -0600   KubeletNotReady              container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
```
I followed this documentation: https://isovalent.com/blog/post/eks-byocni-cilium/ 

### How can we reproduce the issue?

This is my eksctl version 

```
eksctl version
0.205.0-dev+9e5300e5a.2025-02-28T20:09:09Z
```

This is my Cluster Config 

```eksctl create cluster -f eksctl_cluster```

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cilium
  region: us-east-1
  version: "1.29"

iam:
  withOIDC: true

addonsConfig:
  disableDefaultAddons: true
addons:
  - name: coredns
```

Then I installed Cilium using Helm (listed below) and after that I tried setting up the NodeGroup

This is my NodeGroup Config

```eksctl create nodegroup -f eksctl_nodegroup.yaml```

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cilium
  region: us-east-1

managedNodeGroups:
  - name: cilium
    instanceType: t3a.medium
    desiredCapacity: 2
    privateNetworking: true
```

### Cilium Version

I tried using different versions and it didn't work.

```
 helm install cilium cilium/cilium --version 1.15.6 \
  --namespace kube-system \
  --set eni.enabled=true \
  --set ipam.mode=eni \
  --set egressMasqueradeInterfaces=eth0 \
  --set routingMode=native \
  --set kubeProxyReplacement=true \
  --set k8sServiceHost=${API_SERVER_IP} \
  --set k8sServicePort=${API_SERVER_PORT}
```

### Kernel Version

6.1

It's using AWS EC2 Intaances

### Kubernetes Version

1.29

### Relevant log output

```shell
Pods keep crashing because there is no CNI


NAMESPACE     NAME                               READY   STATUS                  RESTARTS      AGE
kube-system   cilium-bfvng                       0/1     Init:CrashLoopBackOff   5 (55s ago)   4m
kube-system   cilium-operator-7d46c6f4c7-9czdv   0/1     CrashLoopBackOff        5 (37s ago)   7m6s
kube-system   cilium-operator-7d46c6f4c7-bnqbh   0/1     CrashLoopBackOff        5 (34s ago)   7m6s
kube-system   cilium-sr747                       0/1     Init:CrashLoopBackOff   5 (51s ago)   3m56s
kube-system   coredns-54d6f577c6-5n8xm           0/1     Pending                 0             144m
kube-system   coredns-54d6f577c6-gxnzq           0/1     Pending
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
