### ISSUE TITLE
GAMMA (Gateway API for Service Mesh) not working as expected

### ISSUE THREAD

**Issue by dverzolla** [cilium/cilium#38415]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.2 and lower than v1.18.0

### What happened?

While trying to use GAMMA for east-west gateway, cilium does not work as expected.
I have found three awkward behaviors:

1. HTTPRoute 
`spec.hostnames` are not working. Does not matter what hostname I set, cilium does match any.

2. parentRefs
`spec.parentRefs` GAMMA expects a ClusterIP service as parentRefs. In other GAMMA implementation (e.g.: linkerd) the created service does not expect a service with `selector`. I have tried the same approach and does not work. I have took another approach, adding a dummy selector and GAMMA worked as expected (almost). More in (3)

3. HTTPRoute stop working
When I create a HTTPRoute like mentioned in (2), cilium start flowing traffic from the parentRefs to HTTPRoute. However, if I create a second HTTPRoute with a different PathPrefix, the second take precedence over the first.

### How can we reproduce the issue?

Helm:
```yaml
# values.yaml
kubeProxyReplacement: true
gatewayAPI:
  enabled: true
ingressController:
  enabled: true
nodePort:
  enabled: true
externalIPs:
  enabled: true
hubble:
  enabled: true
  ui:
    enabled: true
  relay:
    enabled: true
```

echo test
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: gamma
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-mars
  namespace: gamma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-mars
  template:
    metadata:
      labels:
        app: backend-mars
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo
        args:
          - "-listen=:8080"
          - "-text=hello from the backend MARS!"
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-venus
  namespace: gamma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-venus
  template:
    metadata:
      labels:
        app: backend-venus
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo
        args:
          - "-listen=:8080"
          - "-text=hello from the backend VENUS!"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: parent-svc
  namespace: gamma
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    label: dummy
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc-mars
  namespace: gamma
spec:
  selector:
    app: backend-mars
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc-venus
  namespace: gamma
spec:
  selector:
    app: backend-venus
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-gamma
  namespace: gamma
spec:
  hostnames:
  - mars
  - venus
  parentRefs:
    - group: ""
      kind: Service
      name: parent-svc
      port: 80
      namespace: gamma
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/mars"
      backendRefs:
        - group: ""
          kind: Service
          name: backend-svc-mars
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: "/venus"
      backendRefs:
        - group: ""
          kind: Service
          name: backend-svc-venus
          port: 80
```

the tests:

```
# curl -H "Host: mars" http://parent-svc/mars
hello from the backend MARS!
# curl -H "Host: venus" http://parent-svc/venus
hello from the backend VENUS!
```

Trigger the bug:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-gamma-bug-trigger
  namespace: gamma
spec:
  hostnames:
  - bug
  parentRefs:
    - group: ""
      kind: Service
      name: parent-svc
      port: 80
      namespace: gamma
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/bug"
      backendRefs:
        - group: ""
          kind: Service
          name: backend-svc-mars
          port: 80
```

After applying the `httproute-gamma-bug-trigger`, curl stop working:

```
/ # curl -v -H "Host: mars" http://parent-svc/mars
* Host parent-svc:80 was resolved.
* IPv6: (none)
* IPv4: 10.100.114.157
*   Trying 10.100.114.157:80...
* Connected to parent-svc (10.100.114.157) port 80
* using HTTP/1.x
> GET /mars HTTP/1.1
> Host: mars
> User-Agent: curl/8.11.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 404 Not Found
< date: Fri, 21 Mar 2025 19:52:26 GMT
< server: envoy
< content-length: 0
<
* Connection #0 to host parent-svc left intact
/ # curl -v -H "Host: venus" http://parent-svc/venus
* Host parent-svc:80 was resolved.
* IPv6: (none)
* IPv4: 10.100.114.157
*   Trying 10.100.114.157:80...
* Connected to parent-svc (10.100.114.157) port 80
* using HTTP/1.x
> GET /venus HTTP/1.1
> Host: venus
> User-Agent: curl/8.11.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 404 Not Found
< date: Fri, 21 Mar 2025 19:52:41 GMT
< server: envoy
< content-length: 0
<
* Connection #0 to host parent-svc left intact
```

### Cilium Version

`v1.17.2`

### Kernel Version

`Linux controlplane 6.8.0-1019-oracle #20-Ubuntu SMP Fri Jan 17 21:19:50 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux`

### Kubernetes Version

`v1.32.1`

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mikemorris** [comment]
> HTTPRoute
spec.hostnames are not working. Does not matter what hostname I set, cilium does match any.

This may be intentional per context in https://github.com/kubernetes-sigs/gateway-api/issues/2885, but is an expectation I expect we'll try to correct in an upcoming Gateway API release (won't make it in for 1.3 as this should be accompanied by conformance tests and addressing https://github.com/kubernetes-sigs/gateway-api/issues/3581, but hopefully we can get this fixed in the upstream Gateway API spec for 1.4).

**Comment by mikemorris** [comment]
>parentRefs
spec.parentRefs GAMMA expects a ClusterIP service as parentRefs. In other GAMMA implementation (e.g.: linkerd) the created service does not expect a service with selector. I have tried the same approach and does not work. I have took another approach, adding a dummy selector and GAMMA worked as expected (almost).

Only ClusterIP services are actually expected to be supported by GAMMA currently per https://gateway-api.sigs.k8s.io/geps/gep-1294/?h=xro#allowed-service-types.

**Comment by dverzolla** [comment]
> > HTTPRoute
> > spec.hostnames are not working. Does not matter what hostname I set, cilium does match any.
> 
> This may be intentional per context in [kubernetes-sigs/gateway-api#2885](https://github.com/kubernetes-sigs/gateway-api/issues/2885), but is an expectation I expect we'll try to correct in an upcoming Gateway API release. It won't make it in for 1.3 as we're cutting a release candidate imminently and this should be accompanied by conformance tests and addressing [kubernetes-sigs/gateway-api#3581](https://github.com/kubernetes-sigs/gateway-api/issues/3581), but hopefully we can get this fixed in the upstream Gateway API spec for 1.4.

@mikemorris thanks for answering. In our use case `hostnames` has a matching purpose and I will keep my eyes on this, even willing to help documenting or making tests.

**Comment by dverzolla** [comment]
> > parentRefs
> > spec.parentRefs GAMMA expects a ClusterIP service as parentRefs. In other GAMMA implementation (e.g.: linkerd) the created service does not expect a service with selector. I have tried the same approach and does not work. I have took another approach, adding a dummy selector and GAMMA worked as expected (almost).
> 
> Only ClusterIP services are actually expected to be supported by GAMMA currently per https://gateway-api.sigs.k8s.io/geps/gep-1294/?h=xro#allowed-service-types.

Reading my text again I noted that I mixed `ClusterIP` and `selector` and this lead to a different understanding.
I know that GAMMA expects ClusterIP and that's ok. What I was saying is that `service.spec.selector` could not be needed (at least that's how linkerd it's working in my current cluster setup).

In my current cluster setup (linkerd) we use one service `parentRefs`, that centralizes all east-west routing. 
And them we have several HTTPRoutes tied to this service.

```yaml
# this does work with linkerd and does not work with cilium
kind: Service
apiVersion: v1
metadata:
  name: internal
spec:
  type: ClusterIP
  ports:
  - name: internal
    protocol: TCP
    port: 80
    targetPort: 80
```

To work with cilium I needed to add a dummy selector pointing to nowhere.

```yaml
# this does work with cilium
kind: Service
apiVersion: v1
metadata:
  name: internal
spec:
  selector:
    dummy: label
  type: ClusterIP
  ports:
  - name: internal
    protocol: TCP
    port: 80
    targetPort: 80
```

The dummy selector works "fine", but only if I create a big HTTPRoute with all matches inside it.
If I create several different HTTPRoutes, using the same matches of the big one, HTTPRoute works only for the last one I create. Pretty weird.
