### ISSUE TITLE
Gateway reconciler fails if experimental TLSRoute CRD is not installed

### ISSUE THREAD

**Issue by evanebb** [cilium/cilium#38420]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.2 and lower than v1.18.0

### What happened?

I am trying to use the Gateway API implementation in Cilium. According to the official documentation, the experimental Gateway API CRDs are not required if you are not going to use TLSRoutes: https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/#prerequisites

![Image](https://github.com/user-attachments/assets/4896987c-47ec-4f44-bd05-2db6949d751e)

However, if I install the standard channel CRDs and create a Gateway using the `cilium` GatewayClass, I see errors in the logs related to TLSRoutes (see logs section further below) and the Gateway keeps indefinitely waiting for the controller:

```
kubectl -n default get gateways.gateway.networking.k8s.io test-gateway
NAME           CLASS    ADDRESS   PROGRAMMED   AGE
test-gateway   cilium             Unknown      2m9s

kubectl -n default describe gateways.gateway.networking.k8s.io test-gateway
Name:         test-gateway
<snip>
Status:
  Conditions:
    Last Transition Time:  1970-01-01T00:00:00Z
    Message:               Waiting for controller
    Reason:                Pending
    Status:                Unknown
    Type:                  Accepted
    Last Transition Time:  1970-01-01T00:00:00Z
    Message:               Waiting for controller
    Reason:                Pending
    Status:                Unknown
    Type:                  Programmed
Events:                    <none>
```

After installing the experimental CRDs (including TLSRoute), the Gateway starts working as expected.

The issue seems to happen right here: https://github.com/cilium/cilium/blob/375906fd1196c0c3416d2f0ad59593be5f1a4ea3/operator/pkg/gateway-api/gateway_reconcile.go#L95-L99

It tries to retrieve TLSRoutes, which it cannot do because the CRD does not exist.

I expect that either the code needs to be modified to not try to retrieve TLSRoutes if the CRD does not exist, or the documentation needs to be changed to indicate that the experimental CRDs are required.

### How can we reproduce the issue?

1. Install the API gateway CRDs from the standard release channel, which does not include the `TLSRoute` CRD (tested with both version 1.2.0 and 1.2.1)
```shell
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/standard-install.yaml
```
2. Install Cilium 1.17.2 with the Gateway API enabled according to https://docs.cilium.io/en/v1.17/network/servicemesh/gateway-api/gateway-api/#installation. For full reference, I use Helm with the following values:
```yaml
bgpControlPlane:
  enabled: true
kubeProxyReplacement: true
k8sServiceHost: k8s-prod
k8sServicePort: 6443
gatewayAPI:
  enabled: true
```
3. Create a Gateway using the `cilium` GatewayClass and some resources to use it, I used the following test NGINX deployment:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: test-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      port: 80
      protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-test-route
spec:
  parentRefs:
    - kind: Gateway
      name: test-gateway
  rules:
    - backendRefs:
        - name: nginx-test-svc
          port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-deploy
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-svc
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      protocol: TCP
```
4. Observe errors in the logs regarding TLSRoutes (see log section further below), and see that the created Gateway does not get an address and will wait indefinitely for the controller.

To 'fix' this, install the experimental Gateway API CRDs and observe that it'll start working as expected:

```shell
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/experimental-install.yaml
kubectl rollout restart -n kube-system deployment cilium-operator
```

Log output afterward:
```
time=2025-03-22T19:26:53Z level=info msg="Successfully reconciled Gateway" module=operator.operator-controlplane.leader-lifecycle.gateway-api controller=gateway resource=prod/lab-gateway
time=2025-03-22T19:26:53Z level=info msg="Reconciling Gateway" module=operator.operator-controlplane.leader-lifecycle.gateway-api controller=gateway resource=default/test-gateway
```

And the Gateway now has an address assigned and works as expected:
```shell
kubectl -n default get gateways.gateway.networking.k8s.io
NAME           CLASS    ADDRESS       PROGRAMMED   AGE
test-gateway   cilium   172.16.21.0   True         15m

kubectl -n default describe gateways.gateway.networking.k8s.io test-gateway
Name:         test-gateway
<snip>
Status:
  Addresses:
    Type:   IPAddress
    Value:  172.16.21.0
  Conditions:
    Last Transition Time:  2025-03-22T19:26:53Z
    Message:               Gateway successfully scheduled
    Observed Generation:   1
    Reason:                Accepted
    Status:                True
    Type:                  Accepted
    Last Transition Time:  2025-03-22T19:26:53Z
    Message:               Gateway successfully reconciled
    Observed Generation:   1
    Reason:                Programmed
    Status:                True
    Type:                  Programmed
```

### Cilium Version

1.17.2

### Kernel Version

6.8.0-55-generic

### Kubernetes Version

1.31.4

### Regression

Nope, not as far as I know.

### Relevant log output

```shell
time=2025-03-22T19:13:59Z level=info msg="Reconciling Gateway" module=operator.operator-controlplane.leader-lifecycle.gateway-api controller=gateway resource=default/test-gateway
time=2025-03-22T19:13:59Z level=error msg="Unable to list TLSRoutes" module=operator.operator-controlplane.leader-lifecycle.gateway-api controller=gateway resource=default/test-gateway error="no kind is registered for the type v1alpha2.TLSRouteList in scheme \"k8s.io/client-go/kubernetes/scheme/register.go:83\""
time=2025-03-22T19:13:59Z level=error msg="Reconciler error" module=operator.operator-controlplane.leader-lifecycle.controller-runtime controller=gateway controllerGroup=gateway.networking.k8s.io controllerKind=Gateway Gateway.name=test-gateway Gateway.namespace=default namespace=default name=test-gateway reconcileID=4470c0c4-2bd6-41b9-8a81-00834a2d1da0 error="no kind is registered for the type v1alpha2.TLSRouteList in scheme \"k8s.io/client-go/kubernetes/scheme/register.go:83\""
```

### Anything else?

Previous PRs related to this:
- https://github.com/cilium/cilium/pull/34212
- https://github.com/cilium/cilium/pull/34817

Comment in a different issue of someone who seemingly ran into the same thing: https://github.com/cilium/cilium/issues/38123#issuecomment-2731163560

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by nueavv** [comment]
I enabled the Gateway API first and then tried to install the CRDs separately, but the GatewayClass wasn't created.  
Would it make sense to automatically install the CRDs during the Helm installation if they're missing?

**Comment by syedazeez337** [comment]
I am able to replicate this issue in my lab environment. Currently fixing it locally and will be raising a pull request with the fix.

**Comment by ifoughal** [comment]
same issue here; the TLS crude is not installed on my lab, TLS is disabled, yet I get the TLS CRD error from the operator:
```
no kind is registered for the type v1alpha2.TLSRouteList in scheme \"k8s.io/client-go/kubernetes/scheme/register.go:83\
```

my gateway is using HTTP only.

**Comment by ifoughal** [comment]
> I enabled the Gateway API first and then tried to install the CRDs separately, but the GatewayClass wasn't created. Would it make sense to automatically install the CRDs during the Helm installation if they're missing?

In my case, I forced its installation by setting `gatewayAPI.gatewayClass.create: true`

Doing so, creates the GatewayClass by installing the CRDS autoamtically. But then I hit this issue; the workaround was to install the experimental CRDS. Not sure exactly about the root cause tho.... as the TLS CRD was not installed, neither was I using TLS routes/gateways.

**Comment by Sawangg** [comment]
Currently facing the same issue even tho I'm only using HTTPRoutes.   
I started by enabling Cilium's gateway support with `gatewayAPI.enabled=true` and installed the standard CRDs with the following 
```sh
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/latest/download/standard-install.yaml
```

I ran into this issue and had to switch to the experimental CRDs using
```sh
 kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/latest/download/experimental-install.yaml
```

Cilium's doc should probably tell the user to install TLSRoute even if this feature is still experimental.

**Comment by egrosdou01** [comment]
For anyone facing similar issues, I tested RKE2 v1.31.9+rke2r1 with Cilium v1.17.3. Initially, I bootstrapped the cluster using the below Cilium Helm Chart values.

```
externalIPs:
  enabled: true
gatewayAPI:
  enabled: true
k8sClientRateLimit:
  burst: 40
  qps: 20
kubeProxyReplacement: true
l2announcements:
  enabled: true
```

While the RKE2 cluster installation was ongoing, I deployed the Gateway API CRDs. Check out the Cilium documentation [here](https://docs.cilium.io/en/v1.17/network/servicemesh/gateway-api/gateway-api/#gs-gateway-api).

Once the cluster was in a "Ready" state, I updated the Helm chart values and included the below.

```
gatewayAPI:
  enabled: true
  gatewayClass:
    create: "true"
```

The above changed allowed the creation of the Cilium GatewayClass. 

For my setup, the `CiliumLoadBalancerIPPool` and the `CiliumL2AnnouncementPolicy` were created. Find the information in the link below.
-  [L2 Announcements](https://docs.cilium.io/en/v1.17/network/l2-announcements/#l2-announcements)

After that, the Gateway resources had the PROGRAMMED section set to True.
