### ISSUE TITLE
CFP: Adding AWS EC2 Nodes to an Existing On-Prem Kubernetes Cluster

### ISSUE THREAD

**Issue by acudovs** [cilium/cilium#38432]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

We are running a hybrid Kubernetes cluster with half of the nodes located on-premises and the other half running on AWS EC2 instances. The two environments are connected via AWS Direct Connect. The on-prem nodes have been migrated to Cilium.

Currently, there is no documented way to add AWS EC2 nodes to an existing on-premises Kubernetes cluster running Cilium with Multi-pool IPAM. Since the Cilium operator can only run a single IPAM mode at a time, this creates challenges in managing hybrid clusters.

In my case, the cluster uses Cilium with:
- Native routing datapath
- BGP Control Plane
- Multi-pool IPAM
- Kube-proxy replacement mode

I initially explored using [AWS ENI](https://docs.cilium.io/en/stable/network/concepts/ipam/eni/) IPAM, but the Cilium operator was already running Multi-pool IPAM.

**Describe the feature you'd like**

Document a recommended way to add AWS EC2 nodes to an existing on-premises Kubernetes cluster running Cilium with Multi-pool IPAM.

Support for hybrid IPAM modes. Ideally, Cilium should allow different IPAM modes for different node groups: Multi-pool IPAM for on-prem nodes and AWS ENI IPAM for AWS nodes.

Better integration with AWS VPC CNI in CNI chaining mode. The current implementation still allocates pod CIDRs unnecessarily when using AWS VPC CNI in a chained setup. For e.g., reuse a [noOpAllocator](https://github.com/cilium/cilium/blob/1.17.2/pkg/ipam/noop_allocator.go) for CNI chaining mode.

Ability to disable [AWS iptables cleanup](https://github.com/cilium/cilium/blob/1.17.2/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L217-L225) when chaining mode is set per node, not globally. Currently, the Helm chart only disables AWS iptables cleanup if `chainingMode` is configured globally. An additional condition would be useful.

**(Optional) Describe your proposed solution**

To work around the issue, I successfully added AWS nodes using [AWS VPC CNI Chaining](https://docs.cilium.io/en/latest/installation/cni-chaining-aws-cni/) and CiliumNodeConfig.

To prevent unnecessary IP allocations, I defined a dummy IP pool. The AWS nodes allocate IPs from this pool, but these IPs are not used.

```
apiVersion: cilium.io/v2alpha1
kind: CiliumPodIPPool
metadata:
  name: link-local
spec:
  ipv4:
    cidrs:
      - 169.254.0.0/16
    maskSize: 30
```

CiliumNodeConfig:

```
apiVersion: cilium.io/v2
kind: CiliumNodeConfig
metadata:
  name: aws-cni-chaining
  namespace: kube-system
spec:
  defaults:
    ipam-default-ip-pool: link-local
    ipam-multi-pool-pre-allocation: link-local=1
    cni-chaining-mode: aws-cni
    cni-exclusive: "false"
    enable-bgp-control-plane: "false"
    enable-host-legacy-routing: "true"
    enable-endpoint-health-checking: "false"
    install-no-conntrack-iptables-rules: "false"
  nodeSelector:
    matchLabels:
      network/cni: aws-cni
```

Additionally, I had to modify the Helm chart to prevent the deletion of AWS iptables rules by removing this block:
https://github.com/cilium/cilium/blob/1.17.2/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L217-L225

**Questions**

Should my current solution using AWS VPC CNI chaining and a dummy IP pool be considered a recommended setup for hybrid clusters?

Are there any other recommended approaches for handling hybrid clusters with mixed IPAM modes?

Is there a way to enable AWS ENI IPAM only for EC2 nodes while keeping Multi-pool IPAM for on-prem nodes? For e.g., run multiple Cilium operators without conflicts: one for Multi-pool IPAM and another for AWS ENI IPAM?
