### ISSUE TITLE
CFP: When using sharing-cross-namespace, the used ports check should be ignored across namespaces

### ISSUE THREAD

**Issue by ifoughal** [cilium/cilium#38459]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

Currently when deploying an 2 ingresses for 2 different namespaces, the services ports are checks to ensure that we are not using the same ports, otherwise the loadbalancer IP would not be allocated. This test should be ignored when the same port is used on different namespaces.

**Describe the feature you'd like**
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-1
  namespace: app-1
  annotations:
    lbipam.cilium.io/ips: "10.10.10.1"
    lbipam.cilium.io/sharing-key: "1234"
    lbipam.cilium.io/sharing-cross-namespace: "*"
    ingress.cilium.io/service-external-traffic-policy: Cluster
   
spec:
  ingressClassName: cilium
  rules:
  - host: frontend-A
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: frontend-A-service
            port:
              name: http

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-2
  namespace: app-2
  annotations:
    lbipam.cilium.io/ips: "10.10.10.1"
    lbipam.cilium.io/sharing-key: "1234"
    lbipam.cilium.io/sharing-cross-namespace: "*"
    ingress.cilium.io/service-external-traffic-policy: Cluster
   
spec:
  ingressClassName: cilium
  rules:
  - host: frontend-B
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: frontend-B-service
            port:
              name: http

```

in this example, when we apply these 2 ingresses, the loadblaancer IP allocation would succeed for the first ingress, but the second ingress would hang on in pending state.

wherease, when se change the port to something else, the IP gets allocated. This leads me to believe that the allocation checks fail as it thinks that the same port is used, but since we are running on different namespaces as 
well as using the `lbipam.cilium.io/sharing-cross-namespace: "*"` annotation, the check must pass. 

When using the same port/protocol, we get:

```yaml
status:
  conditions:
  - lastTransitionTime: "2025-03-24T16:19:38Z"
    message: 'The IP ''10.10.10.1'' is already allocated to an incompatible service.
      Reason: same port and protocol'
    reason: already_allocated_incompatible_service
    status: "False"
    type: cilium.io/IPAMRequestSatisfied
```
