### ISSUE TITLE
Unable to delete maglev lookup table 120: delete: key does not exist

### ISSUE THREAD

**Issue by ifoughal** [cilium/cilium#38516]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.2 and lower than v1.18.0

### What happened?

After installing cilium using helm/cilium-cli install, i encouter this error log when running cilium status; this persists after multiple reinstall attempts. Even after a cluster reset.

```
Errors:                cilium             cilium-pcp54    controller sync-lb-maps-with-k8s-services is failing since 7s (4x): Unable to remove service &{hash:��
Bv� frontend:{L3n4Addr:{AddrCluster:{addr:{addr:{hi:0 lo:281470853874184} z:{value:0xc00016fe90}} clusterID:0} L4Addr:{Protocol:TCP Port:30447} Scope:0} ID:120} backends:[] backendByHash:map[] svcType:NodePort svcForwardingMode: svcExtTrafficPolicy:Cluster svcIntTrafficPolicy:Cluster svcNatPolicy:NONE sessionAffinity:false sessionAffinityTimeoutSec:0 svcHealthCheckNodePort:0 healthcheckFrontendHash: svcName:{Namespace: Name: Cluster:} loadBalancerAlgorithm:0 svcSourceRangesPolicy: loadBalancerSourceRanges:[] l7LBProxyPort:0 LoopbackHostport:false restoredFromDatapath:true restoredBackendHashes:map[] annotations:map[]}: Unable to delete maglev lookup table 120: delete: key does not exist
```

Sometimes restarting the ds & deployments fixes it, but it is not consistent and sometimes requires multiple attempts. and even then it would require at least 10 to 20 minutes to go up again and no longer display the maglev error.

```
kubectl rollout restart -n kube-system ds/cilium ds/cilium-envoy deployment/cilium-operator
```

### How can we reproduce the issue?

```bash
cilium install --version $CILIUM_VERSION \
        --set ipv4NativeRoutingCIDR=${CONTROLPLANE_SUBNET} \
        --set k8sServiceHost=auto \
        --values ./cilium/values.yaml \
        --set maglev.hashSeed="${HASH_SEED}"
```

values.yaml:
```yaml
kubeProxyReplacement: true
gatewayAPI:
  enabled: true

routingMode: native

ingressController:
  enabled: false

endpointRoutes:
  enabled: true

bpf:
  hostLegacyRouting: false
  masquerade: true

loadBalancer:
  mode: dsr
  dsrDispatch: opt
  protocolDifferentiation:
    enabled: true
  algorithm: maglev
  l7:
    backend: envoy

maglev:
  tableSize: 65521

```

### Cilium Version

1.17.1

### Kernel Version

Almalinux 9.5    5.14.0-503.33.1.el9_5.x86_64  

### Kubernetes Version

1.32.3

### Sysdump

[cilium-sysdump-20250326-110651.zip](https://github.com/user-attachments/files/19464750/cilium-sysdump-20250326-110651.zip)

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
