### ISSUE TITLE
Cilium removes existing routes on table 200 on startup

### ISSUE THREAD

**Issue by nocturo** [cilium/cilium#38531]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.8 and lower than v1.17.0

### What happened?

# Issue Description

## Problem
When migrating from MetalLB to Cilium BGP control plane for external IPs, I discovered that Cilium is removing our critical return path routes on startup. Specifically, Cilium is emptying a custom routing table (table 200) that is required for the BGP return path to work correctly.

## Environment
- Previous solution: MetalLB (worked correctly with our routing setup)
- Current solution: Cilium BGP control plane
- Network setup includes custom routing tables and policy-based routing for return traffic

### Network Configuration
```yaml
bond2.2616:
    id: '2616'
    link: bond2
    mtu: '1500'
    addresses:
      - 100.64.200.24/24
    routes:
    -   table: 200
        to: 0.0.0.0/0
        via: 100.64.200.1
    routing-policy:
    -   from: 1.2.3.0/26
        table: 200
```

### Cilium BGP Configuration
```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  bgpInstances:
  - localASN: 64512
    name: instance-64512
    peers:
    - name: peer-64512-2
      peerASN: 64512
      peerAddress: 100.64.200.2
      peerConfigRef:
        group: cilium.io
        kind: CiliumBGPPeerConfig
        name: cilium-peer
    - name: peer-64512-3
      peerASN: 64512
      peerAddress: 100.64.200.3
      peerConfigRef:
        group: cilium.io
        kind: CiliumBGPPeerConfig
        name: cilium-peer
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/ingress: "true"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  labels:
    bgp: public
  name: public-ips
spec:
  blocks:
  - cidr: 1.2.3.4/32
  - cidr: 1.2.3.5/32
  disabled: false
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: ingress
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  authSecretRef: cilium-bgp-password
  ebgpMultihop: 1
  families:
  - advertisements:
      matchLabels:
        advertise: bgp
    afi: ipv4
    safi: unicast
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  timers:
    connectRetryTimeSeconds: 120
    holdTimeSeconds: 180
    keepAliveTimeSeconds: 60
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  labels:
    advertise: bgp
  name: cilium-bgp-advertisements
spec:
  advertisements:
  - advertisementType: Service
    selector:
      matchLabels:
        app.kubernetes.io/name: haproxy-ingress
    service:
      addresses:
      - ExternalIP
      - LoadBalancerIP
```

### Routes
```
# cilium bgp routes
(Defaulting to `available ipv4 unicast` routes, please see help for more options)
VRouter   Prefix            NextHop   Age      Attrs
64512     1.2.3.4/32   0.0.0.0   20m48s   [{Origin: i} {Nexthop: 0.0.0.0}]
64512     1.2.3.5/32   0.0.0.0   20m48s   [{Origin: i} {Nexthop: 0.0.0.0}]
```

## Expected Behavior
Cilium should preserve existing routes in custom routing tables, especially those that are critical for the BGP return path.

## Actual Behavior
Upon startup, Cilium removes our return path route, resulting in an empty routing table and breaking the BGP return path functionality.

## Questions
1. Is this intended behavior or a bug?
2. Is there a way to configure Cilium to preserve these custom routes?
3. If this is a bug, what additional information would help in troubleshooting?

Thank you for looking into this issue!

### How can we reproduce the issue?

Have custom route table setup and setup BGP control plane.

### Cilium Version

rke2-cilium-1.16.501 (app version 1.16.5)

### Kernel Version

6.8.0-53-generic

### Kubernetes Version

v1.32.1+rke2r1

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
