### ISSUE TITLE
Address not assign to gateway

### ISSUE THREAD

**Issue by kamilcieslak5100** [cilium/cilium#38559]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.2 and lower than v1.18.0

### What happened?

Ip not assigned to gw

### How can we reproduce the issue?

Hi, I install cillum with config:

```
USER-SUPPLIED VALUES:
cilium:
  externalIPs:
    enabled: true
  gatewayAPI:
    enabled: true
    gatewayClass:
      create: true
    hostNetwork:
      enabled: true
  kubeProxyReplacement: true
  l2announcements:
    enabled: true
  nodePort:
    bindProtection: false
cni:
  exclusive: false
```

Also I add gateway
```
k.cieslak@pladb-011542:~/code/ptv-images$ kubectl get gateway -A
NAMESPACE      NAME                 CLASS   ADDRESS   PROGRAMMED   AGE
istio-system   istio-prom-gateway   istio             False        20m
k.cieslak@pladb-011542:~/code/ptv-images$ kubectl describe gateway istio-prom-gateway -n istio-system
Name:         istio-prom-gateway
Namespace:    istio-system
Labels:       <none>
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1
Kind:         Gateway
Metadata:
  Creation Timestamp:  2025-03-27T14:43:46Z
  Generation:          1
  Resource Version:    2544
  UID:                 550cd620-6f48-4c8d-b00b-a391f8874226
Spec:
  Gateway Class Name:  istio
  Listeners:
    Allowed Routes:
      Namespaces:
        From:  Same
    Hostname:   (my hiden dns name)
    Name:      http
    Port:      80
    Protocol:  HTTP
    Allowed Routes:
      Namespaces:
        From:  Same
    Hostname:   (my hiden dns name)
    Name:      https
    Port:      443
    Protocol:  HTTPS
    Tls:
      Certificate Refs:
        Group:  
        Kind:   Secret
        Name:   istio-prom-tls-credential
      Mode:     Terminate
Status:
  Conditions:
    Last Transition Time:  2025-03-27T14:43:47Z
    Message:               Resource accepted
    Observed Generation:   1
    Reason:                Accepted
    Status:                True
    Type:                  Accepted
    Last Transition Time:  2025-03-27T14:43:47Z
    Message:               Assigned to service(s) (mi hiden dns name):443 and (my hiden dns name):80, but failed to assign to all requested addresses: address pending for hostname " (my hiden dns namel"
    Observed Generation:   1
    Reason:                AddressNotAssigned
    Status:                False
    Type:                  Programmed
  Listeners:
    Attached Routes:  2
    Conditions:
      Last Transition Time:  2025-03-27T14:43:47Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2025-03-27T14:43:47Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                NoConflicts
      Status:                False
      Type:                  Conflicted
      Last Transition Time:  2025-03-27T14:43:47Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                Programmed
      Status:                True
      Type:                  Programmed
      Last Transition Time:  2025-03-27T14:43:47Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Name:                    http
    Supported Kinds:
      Group:          gateway.networking.k8s.io
      Kind:           HTTPRoute
      Group:          gateway.networking.k8s.io
      Kind:           GRPCRoute
    Attached Routes:  1
    Conditions:
      Last Transition Time:  2025-03-27T14:43:47Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2025-03-27T14:43:47Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                NoConflicts
      Status:                False
      Type:                  Conflicted
      Last Transition Time:  2025-03-27T14:43:47Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                Programmed
      Status:                True
      Type:                  Programmed
      Last Transition Time:  2025-03-27T14:43:47Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Name:                    https
    Supported Kinds:
      Group:  gateway.networking.k8s.io
      Kind:   HTTPRoute
      Group:  gateway.networking.k8s.io
      Kind:   GRPCRoute
Events:       <none>

```

I dont see IP, and its not assignet to my service, what i am doing wrong?

CiliumLoadBalancerIPPool:
```
        state: absent
        definition:
          apiVersion: "cilium.io/v2alpha1"
          kind: CiliumLoadBalancerIPPool
          metadata:
            name: "pool"
          spec:
            cidrs:
              - cidr: "192.168.55.0/24"
```
CiliumL2AnnouncementPolicy:
```
        state: present
        definition:
          apiVersion: "cilium.io/v2alpha1"
          kind: CiliumL2AnnouncementPolicy
          metadata:
            name: l2policy
          spec:
            loadBalancerIPs: true
            externalIPs: true
            interfaces:
              - ens224
```

### Cilium Version

cilium          kube-system     1               2025-03-27 15:41:18.441930896 +0100 CET deployed        cilium-1.16.1   1.16.1     

### Kernel Version

6.8.0-52-generic 

### Kubernetes Version

v1.30.7

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
