### ISSUE TITLE
Cannot acces service outside nodees in cluster

### ISSUE THREAD

**Issue by kamilcieslak5100** [cilium/cilium#38577]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.2 and lower than v1.18.0

### What happened?

`A` bug happened!

### How can we reproduce the issue?

Hi, I install cillum with config:

I have second interface ens224 for cillium.

USER-SUPPLIED VALUES:
```
cilium:
  externalIPs:
    enabled: true
  gatewayAPI:
    enabled: true
    gatewayClass:
      create: true
    hostNetwork:
      enabled: true
  kubeProxyReplacement: true
  l2announcements:
    enabled: true
  nodePort:
    bindProtection: false
cni:
  exclusive: false
```
Also I add gateway

CiliumLoadBalancerIPPool:

```
        state: present
        definition:
          apiVersion: "cilium.io/v2alpha1"
          kind: CiliumLoadBalancerIPPool
          metadata:
            name: "pool"
          spec:
            cidrs:
              - cidr: "x.x.x.x/24"
```
CiliumL2AnnouncementPolicy:

```
        state: present
        definition:
          apiVersion: "cilium.io/v2alpha1"
          kind: CiliumL2AnnouncementPolicy
          metadata:
            name: l2policy
          spec:
            loadBalancerIPs: true
            externalIPs: true
            interfaces:
              - ens224
```

cillium status:
```
kubectl exec -n kube-system cilium-g5qns -- cilium status
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.30 (v1.30.11) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    False   
Host firewall:           Disabled
SRv6:                    Disabled
CNI Chaining:            none
CNI Config file:         successfully wrote CNI configuration file to /host/etc/cni/net.d/05-cilium.conflist
Cilium:                  Ok   1.16.1 (v1.16.1-68579055)
NodeMonitor:             Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok   
IPAM:                    IPv4: 4/254 allocated from 10.0.0.0/24, 
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Routing:                 Network: Tunnel [vxlan]   Host: Legacy
Attach Mode:             TCX
Device Mode:             veth
Masquerading:            IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:       30/30 healthy
Proxy Status:            OK, ip 10.0.0.132, 0 redirects active on ports 10000-20000, Envoy: external
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 2329/4095 (56.87%), Flows/s: 4.12   Metrics: Disabled
Encryption:              Disabled        
Cluster health:          2/2 reachable   (2025-03-28T13:06:32Z)
Modules Health:          Stopped(0) Degraded(0) OK(40)
```

Kernel modules added:
```

modprobe ip6table_filter -v
modprobe xt_socket -v
modprobe iptable_raw -v
modprobe iptable_nat -v
modprobe iptable_filter -v
modprobe iptable_mangle -v
```

curl outside not workig:
```
kubectl get svc
NAME         TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)        AGE
kubernetes   ClusterIP      10.96.0.1       <none>           443/TCP        14m
nginx        LoadBalancer   10.108.14.129   x.x.x.x   80:32277/TCP   10m
wget x.x.x.x
--2025-03-28 14:11:37--  http://x.x.x.x
Connecting to x.x.x.x:80... 

```
### Cilium Version

cilium kube-system 1 2025-03-27 15:41:18.441930896 +0100 CET deployed cilium-1.16.1 1.16.1

### Kernel Version

6.8.0-52-generic

### Kubernetes Version

v1.30.7

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
