### ISSUE TITLE
cilium on k3d - gateway pending - Waiting for controller. error in operator logs is invalid: listeners[0].supportedKinds[0].group: Invalid value: \"Unknown\": listeners[0].supportedKinds[0].group in body should match regex

### ISSUE THREAD

**Issue by UriZafrir** [cilium/cilium#38582]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.2 and lower than v1.18.0

### What happened?

hi,
I've installed gateway CRDs, and set up a gateway.
it looks similar to #38420 , but when I install the tlsroute crd the gateway is still not created, and i get the following errors from the operator logs:

```
time=2025-03-28T14:45:10Z level=info msg="Reconciling Gateway" module=operator.operator-controlplane.leader-lifecycle.gateway-api controller=g │
│ ateway resource=gateway/cilium-gateway                                                                                                         │
│ time=2025-03-28T14:45:10Z level=error msg="Unable to translate resources" module=operator.operator-controlplane.leader-lifecycle.gateway-api c │
│ ontroller=gateway resource=gateway/cilium-gateway error="model source can't be empty"                                                          │
│ time=2025-03-28T14:45:10Z level=error msg="Reconciler error" module=operator.operator-controlplane.leader-lifecycle.controller-runtime control │
│ ler=gateway controllerGroup=gateway.networking.k8s.io controllerKind=Gateway Gateway.name=cilium-gateway Gateway.namespace=gateway namespace=g │
│ ateway name=cilium-gateway reconcileID=a25cfbfc-08a2-4ced-962f-c856a4ca3447 error="failed to update Gateway status while handling the reconcil │
│ e error: model source can't be empty: Gateway.gateway.networking.k8s.io \"cilium-gateway\" is invalid: listeners[0].supportedKinds[0].group: I │
│ nvalid value: \"Unknown\": listeners[0].supportedKinds[0].group in body should match '^$|^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]* │
│ a-z0-9[])?)*$'"                  
```
I did try to add them, but It didn't apply it:

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: http
      port: 80
      name: http-gateway
      allowedRoutes:
        namespaces:
          from: All
      supportedKinds:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
```

Not sure it's relevant, but I am able to create a load balancer

![Image](https://github.com/user-attachments/assets/0868a516-17ea-4ca3-8b35-4b4a9aed9f81)

this is the status of the gateway:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.networking.k8s.io/v1","kind":"Gateway","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"gateway">
  creationTimestamp: "2025-03-28T14:38:32Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: gateway
  name: cilium-gateway
  namespace: gateway
  resourceVersion: "10833"
  uid: bda2ba7a-ffa6-4d13-9a29-a6c1f20899a1
spec:
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http-gateway
    port: 80
    protocol: http
status:
  conditions:
  - lastTransitionTime: "1970-01-01T00:00:00Z"
    message: Waiting for controller
    reason: Pending
    status: Unknown
    type: Accepted
  - lastTransitionTime: "1970-01-01T00:00:00Z"
    message: Waiting for controller
    reason: Pending
    status: Unknown

```

gatewayclassis valid:
```
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  creationTimestamp: "2025-03-28T13:51:48Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: cilium
  name: cilium
  resourceVersion: "7381"
  uid: a2f8cad1-4c8f-4115-a561-ba293793df57
spec:
  controllerName: io.cilium/gateway-controller
  description: The default Cilium GatewayClass
status:
  conditions:
  - lastTransitionTime: "2025-03-28T14:05:39Z"
    message: Valid GatewayClass
    observedGeneration: 1
    reason: Accepted
    status: "True"
    type: Accepted
```                     

                                                                                         │

### How can we reproduce the issue?

create k3d cluster
this is the config:

```
apiVersion: k3d.io/v1alpha3
kind: Simple
name: cloudnative-tools-testing
servers: 1
agents: 2
image: rancher/k3s:v1.29.15-k3s1 # same as `--image rancher/k3s:v1.20.4-k3s1`
options:
    k3s:
        extraArgs:
            - arg: --disable=traefik
              nodeFilters:
                - server:*
            - arg: --disable=servicelb
              nodeFilters:
                - server:*
            - arg: --disable-network-policy
              nodeFilters:
                - server:*
            - arg: --flannel-backend=none
              nodeFilters:
                - server:*
```

use it:
```
k3d cluster create --config ./cluster.config.yaml

helm repo add cilium https://helm.cilium.io/

docker exec -it k3d-cloudnative-tools-testing-server-0 mount bpffs /sys/fs/bpf -t bpf && \
    docker exec -it k3d-cloudnative-tools-testing-server-0 mount --make-shared /sys/fs/bpf
docker exec -it k3d-cloudnative-tools-testing-agent-0 mount bpffs /sys/fs/bpf -t bpf && \
    docker exec -it k3d-cloudnative-tools-testing-agent-0 mount --make-shared /sys/fs/bpf
docker exec -it k3d-cloudnative-tools-testing-agent-1 mount bpffs /sys/fs/bpf -t bpf && \
    docker exec -it k3d-cloudnative-tools-testing-agent-1 mount --make-shared /sys/fs/bpf

helm install cilium cilium/cilium --version 1.18.0-pre.0 -n kube-system \
  --set kubeProxyReplacement=true \
  --set l2announcements.enabled=true \
  --set externalIPs.enabled=true \
  --set operator.rollOutPods=true \
  --set operator.rollOutCiliumPods=true \
  --set k8sClientRateLimit.qps=50 \
  --set k8sClientRateLimit.burst=200 \
  --set gatewayAPI.enabled=true \
  --set hostNetwork.enabled=true \
  --set envoy.securityContext.capabilities.keepCapNetBindService=true
```

create a gateway:

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: http
      port: 80
      name: http-gateway
      allowedRoutes:
        namespaces:
          from: All
```

### Cilium Version

1.17.2

### Kernel Version

6.6.79

### Kubernetes Version

v1.29.15+k3s1

### Sysdump

[cilium-sysdump-20250328-181754.zip](https://github.com/user-attachments/files/19508158/cilium-sysdump-20250328-181754.zip)

### Relevant log output

```shell
time=2025-03-28T14:45:10Z level=info msg="Reconciling Gateway" module=operator.operator-controlplane.leader-lifecycle.gateway-api controller=g │
│ ateway resource=gateway/cilium-gateway                                                                                                         │
│ time=2025-03-28T14:45:10Z level=error msg="Unable to translate resources" module=operator.operator-controlplane.leader-lifecycle.gateway-api c │
│ ontroller=gateway resource=gateway/cilium-gateway error="model source can't be empty"                                                          │
│ time=2025-03-28T14:45:10Z level=error msg="Reconciler error" module=operator.operator-controlplane.leader-lifecycle.controller-runtime control │
│ ler=gateway controllerGroup=gateway.networking.k8s.io controllerKind=Gateway Gateway.name=cilium-gateway Gateway.namespace=gateway namespace=g │
│ ateway name=cilium-gateway reconcileID=a25cfbfc-08a2-4ced-962f-c856a4ca3447 error="failed to update Gateway status while handling the reconcil │
│ e error: model source can't be empty: Gateway.gateway.networking.k8s.io \"cilium-gateway\" is invalid: listeners[0].supportedKinds[0].group: I │
│ nvalid value: \"Unknown\": listeners[0].supportedKinds[0].group in body should match '^$|^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]* │
│ a-z0-9[])?)*$'"
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by phudtran** [comment]
Also experiencing the same issue with Kind

Kind config

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0"
  - containerPort: 443
    hostPort: 443
    listenAddress: "0.0.0.0"
  - containerPort: 32000
    hostPort: 32000
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30900
    hostPort: 30900
    listenAddress: "0.0.0.0"
    protocol: tcp
networking:
  disableDefaultCNI: true
  podSubnet: "10.10.0.0/16"
  kubeProxyMode: "none"
```

Cilium install

```
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/experimental-install.yaml
	cilium install \
		--version 1.17.3 \
		--namespace kube-system \
		--set image.pullPolicy=IfNotPresent \
		--set ipam.mode=kubernetes \
		--set gatewayAPI.enabled=true \
		--set nodePort.enabled=true \
		--set kubeProxyReplacement=true \
		--set k8sServiceHost=kind-control-plane \
		--set k8sServicePort=6443
```

Gateway and GRPCRoute

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: service-gateway
spec:
  gatewayClassName: cilium
  listeners:
  - name: grpc
    protocol: GRPC
    port: 50051
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: service1-route
spec:
  parentRefs:
  - name: service-gateway
  hostnames:
  - "${SERVICE_URL}"
  rules:
  - matches:
    - method:
        service: Service1
        method: test
    backendRefs:
    - name: service-1
      port: ${GRPC_PORT}
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: service2-route
spec:
  parentRefs:
  - name: service-gateway
  hostnames:
  - "${SERVICE_URL}"
  rules:
  - matches:
    - method:
        service: Service2
        method: test
    backendRefs:
    - name: service-2
      port: 50051
```

kubectl describe gateway service-gateway
```
Name:         service-gateway
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1
Kind:         Gateway
Metadata:
  Creation Timestamp:  2025-04-17T11:10:33Z
  Generation:          1
  Resource Version:    602
  UID:                 ee70a757-fed5-4ac5-9f0d-4b0d086412c9
Spec:
  Gateway Class Name:  cilium
  Listeners:
    Allowed Routes:
      Namespaces:
        From:  Same
    Name:      grpc
    Port:      50051
    Protocol:  GRPC
Status:
  Conditions:
    Last Transition Time:  1970-01-01T00:00:00Z
    Message:               Waiting for controller
    Reason:                Pending
    Status:                Unknown
    Type:                  Accepted
    Last Transition Time:  1970-01-01T00:00:00Z
    Message:               Waiting for controller
    Reason:                Pending
    Status:                Unknown
    Type:                  Programmed
Events:                    <none>
```

cilium operator log error
```
time=2025-04-17T11:11:02Z level=info msg="Reconciling Gateway" module=operator.operator-controlplane.leader-lifecycle.gateway-api controller=gateway resource=default/service-gateway
time=2025-04-17T11:11:02Z level=error msg="Unable to translate resources" module=operator.operator-controlplane.leader-lifecycle.gateway-api controller=gateway resource=default/service-gateway error="model source can't be empty"
time=2025-04-17T11:11:02Z level=error msg="Reconciler error" module=operator.operator-controlplane.leader-lifecycle.controller-runtime controller=gateway controllerGroup=gateway.networking.k8s.io controllerKind=Gateway Gateway.name=service-gateway Gateway.namespace=default namespace=default name=service-gateway reconcileID=0fc7bd02-9dcc-43fa-9bb0-2d2152c4c93e error="failed to update Gateway status while handling the reconcile error: model source can't be empty: Gateway.gateway.networking.k8s.io \"service-gateway\" is invalid: status.listeners[0].supportedKinds[0].group: Invalid value: \"Unknown\": listeners[0].supportedKinds[0].group in body should match '^$|^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'"x
```
