### ISSUE TITLE
Cilium Gateway API Not Working - App Inaccessible Externally

### ISSUE THREAD

**Issue by plsnotracking** [cilium/cilium#38606]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.2 and lower than v1.18.0

## Cilium Gateway API Not Working - App Inaccessible Externally

Hey!

I'm trying to set up Cilium as an API Gateway to expose my ArgoCD instance using the Gateway API. I've followed the Cilium documentation and some online guides, but I'm running into trouble accessing ArgoCD from outside my cluster.

**Here's my setup:**

* **Kubernetes Cluster:** 1.32
* **Cilium Version:** 1.17.2
* **Gateway API Enabled:** `gatewayAPI: true` in Cilium Helm chart.
* **Gateway API YAMLs Installed:** Yes, from the Kubernetes Gateway API repository.

**My YAML Configurations:**

`GatewayClass.yaml`
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium
  namespace: gateway-api
spec:
  controllerName: io.cilium/gateway-controller
```

`gateway.yaml`
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: gateway-api
spec:
  addresses:
  - type: IPAddress
    value: 64.x.x.x
  gatewayClassName: cilium
  listeners:
    - protocol: HTTP
      port: 80
      name: http-gateway
      hostname: "*.domain.dev"
      allowedRoutes:
        namespaces:
          from: All
```

`HTTPRoute`
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway-api
  hostnames:
    - argocd-gateway.domain.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
      - name: argo-cd-argocd-server
        port: 80
```

`ip-pool.yaml`
```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-load-balancer-ip-pool
  namespace: cilium
spec:
  blocks:
    - start: 192.168.1.2
      stop: 192.168.1.99
    - start: 64.x.x.x # My Public IP Range (Redacted for privacy here)
```

Symptoms:

cURL from OCI instance:
```shell
 curl http://argocd-gateway.domain.dev -kv
* Host argocd-gateway.domain.dev:80 was resolved.
* IPv6: (none)
* IPv4: 64.x.x.x
*   Trying 64.x.x.x:80...
* Connected to argocd-gateway.domain.dev (64.x.x.x) port 80
> GET / HTTP/1.1
> Host: argocd-gateway.domain.dev
> User-Agent: curl/8.5.0
> Accept: */*
>
< HTTP/1.1 200 OK
```

cURL from dev machine: curl http://argocd-gateway.domain.dev from my local machine (outside the cluster) just times out or gives "connection refused".

What I've Checked (So Far):

**DNS**: I've configured an A record for argocd-gateway.domain.dev pointing to 64.x.x.x.

**Firewall**: I've checked my basic firewall rules and port 80 should be open for incoming traffic to 64.x.x.x. (Re-verify your firewall rules, especially if you're on a cloud provider).

What I Expect:

I expect to be able to access the ArgoCD UI by navigating to http://argocd-gateway.domain.dev in my browser.

Questions for the Community:

- What am I missing in my configuration?
- Are there any specific Cilium commands I should run to debug this further?
- Any other ideas on what could be preventing external access?

Any help or suggestions would be greatly appreciated! Thanks in advance!

### How can we reproduce the issue?

`values.yaml`

```YAML
encryption:
  # -- Enable transparent network encryption.
  enabled: true
  # -- Encryption method. Can be either ipsec or wireguard.
  type: wireguard
externalIPs:
  enabled: true
ipam:
  # -- Configure IP Address Management mode.
  # ref: https://docs.cilium.io/en/stable/network/concepts/ipam/
  operator:
    # -- IPv4 CIDR list range to delegate to individual nodes for IPAM.
    clusterPoolIPv4PodCIDRList: ["10.42.0.0/16"]
# -- Configure L2 announcements
l2announcements:
  # -- Enable L2 announcements
  enabled: true
operator:
  # -- Roll out cilium-operator pods automatically when configmap is updated.
  rollOutPods: true
  # -- Number of replicas to run for the cilium-operator deployment
  replicas: 1
  # prometheus enables serving metrics on the configured port at /metrics
  prometheus:
    enabled: false
    port: 6942
    serviceMonitor:
      # Enable service monitors.
      # This requires the prometheus CRDs to be available (see https://github.com/prometheus-operator/prometheus-operator/blob/master/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml)
      ##
      enabled: false
      namespace: kube-prometheus-stack
      # Additional annotations to add to the ServiceMonitor.
      labels:
        release: kube-prometheus-stack

# -- Configure the kube-proxy replacement in Cilium BPF datapath
# Valid options are "true" or "false".
# ref: https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/
kubeProxyReplacement: "true"
# -- (string) Kubernetes service host - use "auto" for automatic lookup from the cluster-info ConfigMap
k8sServiceHost: "127.0.0.1"
# @schema
# type: [string, integer]
# @schema
# -- (string) Kubernetes service port
k8sServicePort: "6443"
# -- Roll out cilium agent pods automatically when configmap is updated.
rollOutCiliumPods: true

# prometheus enables serving metrics on the configured port at /metrics
prometheus:
  enabled: false
  port: 9090
  # serviceMonitor enables the required service monitors to be used with
  # Prometheus
  serviceMonitor:
    # Enable service monitors.
    # This requires the prometheus CRDs to be available (see https://github.com/prometheus-operator/prometheus-operator/blob/master/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml)
    ##
    enabled: false
    # namespace is the Kubernetes namespace where Prometheus expects to find
    # service monitors configured:
    namespace: "kube-prometheus-stack"
    # Additional annotations to add to the ServiceMonitor.
    labels:
      release: kube-prometheus-stack

hostPort:
  # -- Enable hostPort service support.
  enabled: true

gatewayAPI:
  # -- Enable support for Gateway API in cilium
  # This will automatically set enable-envoy-config as well.
  enabled: true
envoy:
  enabled: true
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy:
        - NET_BIND_SERVICE
        - PERFMON
        - BPF
        - NET_ADMIN
  # Note that some of these apply to either cilium-agent or cilium-envoy.
  prometheus:
    # -- Enable prometheus metrics for cilium-envoy
    enabled: true
    serviceMonitor:
      # -- Enable service monitors.
      # This requires the prometheus CRDs to be available (see https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml)
      # Note that this setting applies to both cilium-envoy _and_ cilium-agent
      # with Envoy enabled.
      enabled: false
      # namespace is the Kubernetes namespace where Prometheus expects to find
      # service monitors configured:
      namespace: "kube-prometheus-stack"
      # Additional annotations to add to the ServiceMonitor.
      labels:
        release: kube-prometheus-stack

# Configuration for types of authentication for Cilium (beta)
authentication:
  # -- Enable authentication processing and garbage collection.
  # Note that if disabled, policy enforcement will still block requests that require authentication.
  # But the resulting authentication requests for these requests will not be processed, therefore the requests not be allowed.
  enabled: true
  # -- Buffer size of the channel Cilium uses to receive authentication events from the signal map.
  queueSize: 1024
  # -- Buffer size of the channel Cilium uses to receive certificate expiration events from auth handlers.
  rotatedIdentitiesQueueSize: 1024
  # -- Interval for garbage collection of auth map entries.
  gcInterval: "5m0s"
  # Configuration for Cilium's service-to-service mutual authentication using TLS handshakes.
  # Note that this is not full mTLS support without also enabling encryption of some form.
  # Current encryption options are WireGuard or IPsec, configured in encryption block above.
  mutual:
    # -- Port on the agent where mutual authentication handshakes between agents will be performed
    port: 4250
    # -- Timeout for connecting to the remote node TCP socket
    connectTimeout: 5s
    # Settings for SPIRE
    spire:
      # -- Enable SPIRE integration (beta)
      enabled: true
      install:
        # -- Enable SPIRE installation.
        # This will only take effect only if authentication.mutual.spire.enabled is true
        enabled: true
        # -- SPIRE namespace to install into
        namespace: cilium
        # -- SPIRE namespace already exists. Set to true if Helm should not create, manage, and import the SPIRE namespace.
        existingNamespace: true
```

### Cilium Version

`1.17.2`

### Kernel Version

`Linux instance-20250205-1120 6.8.0-1022-oracle #23-Ubuntu SMP Wed Feb 19 21:10:25 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux`

### Kubernetes Version

`1.32`

### Relevant log output

```shell

```

### Anything else?

I saw the gateway get the IP assigned correctly.

`gateway-api          cilium-gateway          cilium          64.x.x.x          True               27h`

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by syedazeez337** [comment]
Hi there,

I've reproduced and investigated this issue with the Gateway API in Cilium 1.17.2. You're right that there's a problem with the Gateway API implementation in this version.

## Issue Reproduction
I was able to reproduce the exact issue you described:
1. Gateway status shows "Unknown" for PROGRAMMED status
2. No services are created for the Gateway
3. ArgoCD is not accessible externally

## Root Cause
The issue is related to the Gateway API implementation in Cilium 1.17.2. The Gateway controller is not properly processing Gateway resources, resulting in the Gateway not being programmed and no services being created for external access.

## Solution
I've found that this issue is fixed in the latest development version of Cilium (1.18.0-dev). By installing Cilium from the source code with enhanced Gateway API settings, I was able to successfully program the Gateway and create the necessary resources for external access.

Here's what worked for me:

1. Clone the Cilium repository to get the latest development version:
   ```bash
   git clone https://github.com/cilium/cilium.git
   cd cilium
   ```

2. Install Cilium from the latest development version with enhanced Gateway API settings:
   ```bash
   cd install/kubernetes
   helm install cilium ./cilium --namespace kube-system -f values.yaml
   ```

   With these key settings in values.yaml:
   ```yaml
   gatewayAPI:
     enabled: true
     hostNetwork:
       enabled: true
     secretsNamespace:
       create: true
       name: "cilium-secrets"
   envoy:
     enabled: true
   ```

After implementing this solution:
1. The Gateway status changed from "Unknown" to "True" for the PROGRAMMED status
2. A service was created for the Gateway
3. The HTTPRoute was properly configured and attached to the Gateway

This solution will be available to all users when Cilium 1.18.0 is officially released. In the meantime, you can either:
1. Install Cilium from the source code as described above
2. Use Cilium's Ingress support instead of Gateway API
3. Use a different Gateway API implementation

I hope this helps! Let me know if you need any clarification or have further questions.
