### ISSUE TITLE
Layer 7 policy and EnableDefaultDeny=false interact badly

### ISSUE THREAD

**Issue by squeed** [cilium/cilium#38676]
Network policy supports the [EnableDefaultDeny=false directive](https://docs.cilium.io/en/stable/security/policy/intro/#policy-mode-default), which allows users to write policies that can never deny, only allow. This is useful for enabling broad-based policies (e.g. intercept all dns, always allow Prometheus, etc), without risking being the "first" policy that switches a pod to default deny.

However, under-the-hood, this is implemented as just adding a blanket allow-all. Which works fine for L3/L4 policies, but does not play nicely with L7.

The problem is that a policy with `EnableDefaultDeny: false` but L7 allows will deny all other L7 requests. The following example shows one that should allow everything, but blocks DNS queries except for `example.com`.

```yaml
  enableDefaultDeny:
    egress: false
  egress:
  - toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "example.com"
        # - matchPattern: "*"
```

The immediate workaround is to manually include the L7 allow-all, be it DNS or HTTP. But we should handle this correctly in the policy engine.
