### ISSUE TITLE
The strange behavior of the java debugger(jdb) and cilium with no kube-proxy

### ISSUE THREAD

**Issue by snap87** [cilium/cilium#38705]
Hello. 
Cluster k8s 1.26.14
cilium version is 1.17.2
Installed by helm with values:
```
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
k8sServiceHost: "10.0.40.50"
k8sServicePort: "6443"
cluster.name: "kubernetes"
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: "0.0.0.0:10256" 
ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDRList: ["10.245.0.0/16"]
tunnelProtocol: "geneve"

```

I have a java application in k8s pod (one pod only) that works on ports 8080 and a debugger launched in it on port 9999. Both ports are packed through a NodePort and if I connect a debugger through the kubectl port-forward, then there are no problems. 
If I connect the java-debugger (terminal jdb utility)to the direct address of the Nodeport (k8s worker ip:32000) or type of LoadBalancer(:9999), then it does not work. Those. The packages shows that they reach the application, but then everything is. He just freezes. At the same time, in the neighboring same cluster where Cilium does not replace Kube-Proxy  we don't have any problems.
 At the same time, when i try curl -XGET ip:32001(port 8080) -Nodeport or telnet (:9999) -LoadBalancer i do not have any problem.
Only when i connect jdb to Nodeport or LoadBalancer service with no kube-proxy.
This problem in any connect jdb to any application in my cluster with kube-proxy.
Can you help me?
