### ISSUE TITLE
Invalid Cilium netpols are marked as valid when using `specs`

### ISSUE THREAD

**Issue by solidDoWant** [cilium/cilium#38795]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.2 and lower than v1.18.0

### What happened?

When using Cilium network policies with multiple rules (`CiliumNetworkPolicy` and `CiliumClusterwideNetworkPolicy` resources with "specs" field set), only the last `specs` entry is used for validation. This means that if there are multiple rules, say "invalid rule" and "valid rule", and the last rule is valid, the entire policy will be marked as "Valid" via `status.conditions`. The impact here is that if users deploy a netpol under these conditions, then they will incorrectly think that traffic is allowed or denied, when instead, the identities selected by the invalid rule(s) are not actually affected by the netpol.

### How can we reproduce the issue?

1. Deploy this netpol:

    ```yaml
    ---
    apiVersion: cilium.io/v2
    kind: CiliumNetworkPolicy
    metadata:
      name: bug-example-policy
    specs:
      - description: Invalid rule
        endpointSelector:
          matchLabels:
            some-label: some-value
        ingress:
          # This is invalid, because Cilium does not currently support setting both `fromEndpoints` and `fromEntities` in the same rule.
          - fromEndpoints:
              - matchLabels:
                  some-selector-label: some-selector-value
            fromEntities:
              - host
            toPorts:
              - ports:
                  - port: "1234"
                    protocol: TCP
      - description: Valid rule
        endpointSelector:
          matchLabels:
            some-other-label: some-other-value
        egress:
          - {}
        ingress:
          - {}
    ```

2. Check the status

### Cilium Version

1.17.2

### Kernel Version

N/A

### Kubernetes Version

1.31.2

### Relevant log output

```shell

```

### Anything else?

Here's the policy reporting that it is valid:

```console
$ kubectl apply -f /tmp/netpol.yaml 
ciliumnetworkpolicy.cilium.io/bug-example-policy created
$ kubectl get ciliumnetworkpolicies.cilium.io bug-example-policy 
NAME                 AGE   VALID
bug-example-policy   16s   True
```

If I remove the "Valid rule" rule, the status shows that the policy is in fact invalid:

```console
$ kubectl delete -f /tmp/netpol.yaml 
ciliumnetworkpolicy.cilium.io "bug-example-policy" deleted
$ kubectl apply -f /tmp/netpol.yaml 
ciliumnetworkpolicy.cilium.io/bug-example-policy created
$ kubectl get ciliumnetworkpolicies.cilium.io bug-example-policy 
NAME                 AGE   VALID
bug-example-policy   2s    False
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
