### ISSUE TITLE
Cilium Key Allocation Failure on High-Load Clusters

### ISSUE THREAD

**Issue by neverlless** [cilium/cilium#38809]
I am currently managing several Kubernetes clusters, all running version 1.31.4, with Cilium version 1.15.9. I am encountering a recurring issue on two of my high-load clusters. When using `identity-allocation-mode: kvstore`, I observe the following error after a few minutes: `msg="Key allocation attempt failed" error="no more available IDs in configured space"`. This problem does not occur on other clusters where I also use `kvstore`, nor does it occur when I use `crd`.

I attempted to resolve the issue by adjusting the `identity-gc-interval` and `identity-heartbeat-timeout` settings, but these changes did not help. Additionally, with `crd`, I have noticed that identities, such as those created for a CronJob, persist for over an hour even though the jobs themselves complete within two minutes. These identities remain in the system for several hours, despite the `identity-gc-interval` being set to 15 minutes and the jobs no longer existing in the cluster.

I would like to understand the root cause of the problem and find a way to use `kvstore` effectively on high-load clusters.

```yaml
{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-schedule-job
spec:
  schedule: '*/1 * * * *'
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: schedule-job
            app.kubernetes.io/instance: {{ .Release.Name }}
            job-type: static-scheduler
        spec:
          containers:
            - name: job-run
              image: {{ .Values.container.name }}:{{ .Values.container.tag }}
              command: {{ toJson .Values.cronjob.command }}
              args: {{ toJson .Values.cronjob.args }}
              resources:
                {{ toYaml .Values.cronjob.resources | indent 14 }}
              envFrom:
                - configMapRef:
                    name: {{ .Release.Name }}-cm
              restartPolicy: Never
{{- end }}
```
