### ISSUE TITLE
Unable to use Envoy listener in ingress CiliumNetworkPolicy

### ISSUE THREAD

**Issue by ghost** [cilium/cilium#38811]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.2 and lower than v1.18.0

### What happened?

**Description:**

I was following the lab on the Cilium page for [Cilium Envoy L7 Proxy](https://isovalent.com/labs/cilium-envoy-l7-proxy/). The lab demonstrates an example of using a CiliumNetworkPolicy to allow HTTP (80/TCP) and HTTPS (443/TCP) traffic to DNS names matching *.github.com, redirecting this traffic through an Envoy listener defined within the egress section.

Here is the example CiliumNetworkPolicy from the lab:

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: proxy-policy
spec:
  endpointSelector: {}
  egress:
    - toEntities:
        - cluster
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    - toFQDNs:
        - matchPattern: "*.github.com"
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
          listener:
            envoyConfig:
              kind: "CiliumEnvoyConfig"
              name: "proxy-envoy"
            name: "proxy-listener"
```

**Problem:**

I am trying to achieve a similar setup, but for **ingress** traffic. I want to use an Envoy listener within an ingress CiliumNetworkPolicy to handle incoming traffic.

According to the Cilium CRD documentation for CiliumNetworkPolicy (as linked: https://doc.crds.dev/github.com/cilium/cilium/cilium.io/CiliumNetworkPolicy/v2@1.16.6#spec-ingress-toPorts-listener-envoyConfig), it appears that the listener field with envoyConfig should be supported within the **ingress.toPorts** section.

However, when I attempt to apply a CiliumNetworkPolicy with an Envoy listener defined in the ingress section, I receive an error from the Cilium agent:
`time="2025-04-08T15:02:03.529350235Z" level=warning msg="Unable to add CiliumNetworkPolicy" ciliumNetworkPolicyName=proxy-policy error="Invalid CiliumNetworkPolicy spec: Listener is not allowed on ingress (proxy-listener)" k8sApiVersion= k8sNamespace=default subsys=policy-k8s-watcher`

**Questions/Request for Help:**

1. Is it indeed possible to use the listener field with envoyConfig in the ingress.toPorts section of a CiliumNetworkPolicy?
2.  Could there be a specific configuration requirement or a known limitation that I am encountering?
3. What could be causing the Cilium agent to throw an error in this scenario?

If this is not achievable, please advise me on how to proxy all ingress traffic directed to the namespace labeled team: team-a to an Envoy listener created using a **CiliumEnvoyConfig**.

### How can we reproduce the issue?

Try using an arbitrary CiliumNetworkPolicy Ingress rule with Envoy configuration, for example:
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: policy-1
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: namespace-1
      toPorts: 
        - listener:
            envoyConfig:
              kind: "CiliumEnvoyConfig"
              name: "proxy-envoy"
            name: "proxy-listener"
```

### Cilium Version

v1.17.2

### Kernel Version

Linux minikube 6.8.0-57-generic

### Kubernetes Version

v1.26.3

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
