### ISSUE TITLE
Cilium doesn't support chaining with Kube-OVN on IPv6

### ISSUE THREAD

**Issue by SkalaNetworks** [cilium/cilium#38825]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.2 and lower than v1.18.0

### What happened?

IPv6 connectivity between pods using Kube-OVN chained with Cilium doesn't work because of NDP filtering in Cilium's eBPF programs.

### How can we reproduce the issue?

1. Install Cilium with Helm and those values:
```yaml
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cni:
  chainingMode: generic-veth
  configMap: cilium-chaining-config
  customConf: true
  exclusive: false
daemon:
  enableSourceIPVerification: false
devices: eth+ ovn0 genev_sys_6081 vxlan_sys_4789
enableIPv4Masquerade: false
enableIPv6Masquerade: false
enableIdentityMark: false
enableRuntimeDeviceDetection: true
envoy:
  enabled: false
forceDeviceDetection: true
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      annotations: {}
      className: xxx
      enabled: true
      hosts:
      - xxxx
ipam:
  mode: kubernetes
ipv4:
  enabled: true
ipv6:
  enabled: true
k8s:
  requireIPv4PodCIDR: true
  requireIPv6PodCIDR: true
k8sNetworkPolicy:
  enabled: false
k8sServiceHost: localhost
k8sServicePort: 7445
kubeProxyReplacement: false
routingMode: native
securityContext:
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
  ```
2. Install Kube-OVN in chaining mode with Cilium
3. Schedule pods, try to use their IPv6 to join one another across different nodes (ping for example)
4. Witness "no route to host" errors

### Cilium Version

Client: 1.16.8 dc65ba9b 2025-03-13T18:00:10+00:00 go version go1.23.7 linux/amd64
Daemon: 1.16.8 dc65ba9b 2025-03-13T18:00:10+00:00 go version go1.23.7 linux/amd64

### Kernel Version

6.12.18-talos

### Kubernetes Version

Talos v1.32.3

### Regression

Not a regression, it was probably never supported

### Sysdump

[sysdump.zip](https://github.com/user-attachments/files/19664396/sysdump.zip)

### Relevant log output

```shell
Apr  9 09:42:44.151: kube-system/kube-ovn-pinger-h6wlk (ID:46323) <> ff02::1:ff00:1 (world-ipv6) Unknown L3 target address DROPPED (ICMPv6 NeighborSolicitation)
Apr  9 09:42:44.284: argocd-system/argocd-redis-ha-haproxy-66fb656d-9jzrc:45640 (ID:43502) -> argocd-system/argocd-redis-ha-server-0:26379 (ID:24403) to-endpoint FORWARDED (TCP Flags: SYN)
Apr  9 09:42:44.284: argocd-system/argocd-redis-ha-server-0 (ID:24403) <> ff02::1:ff00:32 (world-ipv6) Unknown L3 target address DROPPED (ICMPv6 NeighborSolicitation)
Apr  9 09:42:44.439: argocd-system/argocd-redis-ha-haproxy-66fb656d-5nnxl:36456 (ID:43502) <- argocd-system/argocd-redis-ha-server-0:26379 (ID:24403) to-stack FORWARDED (TCP Flags: SYN, ACK)
Apr  9 09:42:44.470: argocd-system/argocd-redis-ha-haproxy-66fb656d-5nnxl:46958 (ID:43502) -> argocd-system/argocd-redis-ha-server-1:6379 (ID:24403) to-stack FORWARDED (TCP Flags: SYN)
Apr  9 09:42:44.695: argocd-system/argocd-redis-ha-haproxy-66fb656d-5nnxl:52566 (ID:43502) <- argocd-system/argocd-redis-ha-server-0:26379 (ID:24403) to-stack FORWARDED (TCP Flags: SYN, ACK)
Apr  9 09:42:44.695: argocd-system/argocd-redis-ha-haproxy-66fb656d-5nnxl:48864 (ID:43502) <- argocd-system/argocd-redis-ha-server-0:6379 (ID:24403) to-stack FORWARDED (TCP Flags: SYN, ACK)
Apr  9 09:42:44.695: argocd-system/argocd-redis-ha-haproxy-66fb656d-5nnxl:52574 (ID:43502) <- argocd-system/argocd-redis-ha-server-0:26379 (ID:24403) to-stack FORWARDED (TCP Flags: SYN, ACK)
Apr  9 09:42:44.951: argocd-system/argocd-redis-ha-server-0 (ID:24403) <> ff02::1:ff00:33 (world-ipv6) Unknown L3 target address DROPPED (ICMPv6 NeighborSolicitation)
```

### Anything else?

Basically, considering the following assumptions:
- Cilium is L3 oriented (just like K8s)
- Kube-OVN has support for L2 networks accross nodes (so-called "Subnets")
- Cilium filters NDP discovery requests on the basis that:
  - The pods emit them to try to get the MAC of their "router" (which is the node itself)
  - The pods emit them to try to get the MAC of an endpoint on the same node (they belong to the same subnet within the podCIDR of the cluster)

... it seems like cross-node IPv6 connection is impossible.

This bit of code gives clues at to why:
https://github.com/cilium/cilium/blob/53c8b1cf1158e48ddeb629119e7ea46dd49f1a37/bpf/lib/icmp6.h

First off, the other we see in Hubble about NDP being dropped (preventing Pods from getting the MAC of their remote counterpart to start talking to them) is called "DROP_UNKNOWN_TARGET" and elided as ACTION_UNKNOWN_ICMP6_NS here: https://github.com/cilium/cilium/blob/53c8b1cf1158e48ddeb629119e7ea46dd49f1a37/bpf/lib/icmp6.h#L42C9-L42C32

This error is returned by https://github.com/cilium/cilium/blob/53c8b1cf1158e48ddeb629119e7ea46dd49f1a37/bpf/lib/icmp6.h#L349

This function seems to look at the NDP discovery and only accepts it if:
- it is trying to get the MAC of the "router" from the POV of that Pod (which should be the node)
- it is trying to get the MAC of a known endpoint (which I think can only co-exist on the same node, but I can be wrong?)

Because Kube-OVN has allocated a big IPv6 PodCIDR to all my pods, regardless of the node they sit on, IPs allocated to each pods are not prefixed in /128 or /32 for IPv4.

So if my Kube-OVN subnet is fd00::/112, a pod on node A can have IP fd00::a/112 and on B fd00::b/112. The pod has a route in the shape of "fd00::/112 dev eth0", whereas Cilium would allocate IP fd00::a/128 and a default route to the node's router.

This works on IPv4 because the eBPF filter doesn't seem to run any particular check to my knowledge, whereas the NDP one doesn't like what it sees, as it doesn't respect any rule (we're basically dealing with an L2 network stretched across multiple nodes, which Cilium doesn't support)

I'm not sure if this behaviour is wanted, considering IPv4 ranges on Kube-OVN work fine because of the lack of checks.

I know Kube-OVN adopts a fundamentally different approach to networking in K8s compared to Cilium, but it's doing so for good reasons which make it fit for usages such as plugging VMs through Kubevirt in a cluster. Cilium handles other things much better and combining the two through chaining is pretty logical to me.

I don't know if adding an option to disable L3 target checks in NDP solicitations could be a possibility, but it would surely fix my issues.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
