### ISSUE TITLE
Overlapping port-range policies don't play well with proxylib (Duplicate port error)

### ISSUE THREAD

**Issue by squeed** [cilium/cilium#38840]
## The problem:

When creating policies with overlapping port ranges, Envoy will NACK the policy, **but only if proxylib is enabled**.

## Example

Create this policy:
```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: portrange-proxylib-bug
specs:
- endpointSelector: {}
  ingress:
    - fromEndpoints:
      - matchLabels:
          name: client
      toPorts:
        - ports:
          - port: "8080"
            endPort: 8081
            protocol: "TCP"

- endpointSelector: {}
  ingressDeny:
    - fromEntities: ["all"]
      toPorts:
        - ports:
          - port: "8080"
            protocol: "TCP"

```

It will work, and traffic will flow as expected.

Then, create this policy:

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "client-egress-tls-sni"
specs:
- description: "TLS SNI policy"
  endpointSelector:
    matchLabels:
      kind: client
  egress:
  - toPorts:
    - ports:
      - port: "443"
        protocol: "TCP"
      serverNames:
      - "example.com"
```

This will cause Envoy to enable proxylib. From then on, all policy updates will fail with

```
2025-04-09T15:15:37.621364696Z time="2025-04-09T15:15:37.620802785Z" level=warning msg="NACK received for versions after 39 and up to 40; waiting for a version update before sending again" subsys=xds xdsAckedVersion=39 xdsClientNode="host~127.0.0.2~libcilium-2~localdomain" xdsDetail="NPDS: Client host~127.0.0.2~libcilium-2~localdomain rejecting invalid policy on /var/run/cilium/envoy/sockets/xds.sock: NPDS: Duplicate port number 8080 in (rule: port:8080  rules:{deny:true}) (config: [port:8080  end_port:8081 port:8080  rules:{deny:true}])" xdsNonce=40 xdsStreamID=5 xdsTypeURL=type.googleapis.com/cilium.NetworkPolicy
```
