### ISSUE TITLE
Gateway API - HTTPRoute responseHeaderModifier filter - No-op on header 'server'

### ISSUE THREAD

**Issue by clearly-tyler-whitney** [cilium/cilium#38936]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.2 and lower than v1.18.0

### What happened?

Attempts at removing or manipulating Envoy's `server` response header (value: `envoy`) via this facility are roundly ineffective.

In the instructions to reproduce, I attempt to `remove` it entirely, however the `set` and `add` directives were also tried. Also attempted: singling out `server` from the header name(s) array. I have found no combination which "works" to suggest any further nuance exists.

Vanilla response (no `responseHeaderModifier` directives configured):
```
$ curl -ksLD - https://test.domain.com -o /dev/null
HTTP/1.1 200 OK
x-powered-by: Express
access-control-allow-origin: *
content-security-policy: frame-ancestors 'none'
content-type: text/html; charset=utf-8
content-length: 54196
etag: W/"d3b4-+wFWg3x3vUh7gw8DwT7tEO7SxBA"
date: Mon, 14 Apr 2025 16:32:44 GMT
x-envoy-upstream-service-time: 769
server: envoy
```

Expected:
```
$ curl -ksLD - https://test.domain.com -o /dev/null
HTTP/1.1 200 OK
access-control-allow-origin: *
content-security-policy: frame-ancestors 'none'
content-type: text/html; charset=utf-8
content-length: 54196
etag: W/"d3b4-+wFWg3x3vUh7gw8DwT7tEO7SxBA"
date: Mon, 14 Apr 2025 16:32:44 GMT
```

Received:
```
$ curl -ksLD - https://test.domain.com -o /dev/null
HTTP/1.1 200 OK
access-control-allow-origin: *
content-security-policy: frame-ancestors 'none'
content-type: text/html; charset=utf-8
content-length: 54196
etag: W/"d3b4-+wFWg3x3vUh7gw8DwT7tEO7SxBA"
date: Mon, 14 Apr 2025 16:32:44 GMT
server: envoy
```

### How can we reproduce the issue?

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: domain-com
  namespace: test
spec:
  hostnames:
  - test.domain.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: my-gateway
    namespace: default
    sectionName: web-gw-https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: foo
      port: 3001
      weight: 1
    filters:
    - responseHeaderModifier:
        remove:
        - server
        - x-powered-by
        - x-envoy-upstream-service-time
      type: ResponseHeaderModifier
    matches:
    - path:
        type: PathPrefix
        value: /
```
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  name: my-gateway
  namespace: default
spec:
  addresses:
  - type: IPAddress
    value: 10.7.68.1
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    hostname: test.domain.com
    name: web-gw
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: All
    hostname: test.domain.com
    name: web-gw-https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: web-gw-tls
      mode: Terminate
```
Helm values:
```
bandwidthManager:
  enabled: true
bgpControlPlane:
  enabled: true
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cluster:
  name: test
envoy:
  nodeSelector:
    ciliumEnvoy: enabled
gatewayAPI:
  enableAlpn: false
  enabled: true
hubble:
  enabled: true
  metrics:
    enableOpenMetrics: true
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - port-distribution
    - icmp
    - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
  relay:
    enabled: true
  ui:
    enabled: true
ingressController:
  loadbalancerMode: shared
ipam:
  mode: kubernetes
k8sServiceHost: localhost
k8sServicePort: 7445
kubeProxyReplacement: true
loadBalancer:
  l7:
    backend: envoy
operator:
  prometheus:
    enabled: true
  replicas: 1
prometheus:
  enabled: true
routingMode: tunnel
securityContext:
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
tunnelProtocol: vxlan
```

### Cilium Version

```
cilium-cli: v0.18.3 compiled with go1.24.2 on linux/amd64
cilium image (default): v1.17.2
cilium image (stable): v1.17.2
cilium image (running): 1.17.2
```

### Kernel Version

`Linux cilium-test-node-00 6.12.18-talos #1 SMP Tue Mar 11 15:15:12 UTC 2025 x86_64 Linux`

### Kubernetes Version

```
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.32.3
```

### Relevant log output

```shell

```

### Anything else?

[Slack discussion](https://cilium.slack.com/archives/C02QKQDTVDX/p1744639958065689)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by simplyatul** [comment]
Per [this](https://github.com/envoyproxy/envoy/issues/14421), setting ```ServerHeaderTransformation``` to PASS_THROUGH in Envoy should fix this issue. 
I do not see any cilium config using which it can be passed. 
Most probably this may require some code changes.

**Comment by youngnick** [comment]
This is not a Cilium bug - Envoy does not allow this header to be changed using header editing operations.

In order to remove this, we would need to add a flag to configure Envoy's HTTPConnectionManager to set "server_header_transformation" to `PASS_THROUGH`. https://github.com/envoyproxy/envoy/issues/14421 is an example issue from the Envoy repo.

Envoy, like many proxies, does not allow some headers to be edited. "Server" and "Host" are two examples.

If we were to do this, it would require a PR to add this, both as a global flag, and as a setting in CiliumGatewayClassConfig.

**Comment by r3m8** [comment]
We need this feature to comply with OWASP recommendations. I have proposed this PR #43812, which works internally.

I based the code on the previous comment by @youngnick (it works with both global flag and CiliumGatewayClassConfig).

```yaml
helm upgrade --install cilium ./install/kubernetes/cilium \
   [...]
   --set gatewayAPI.enabled=true \
   --set operator.extraArgs[0]="--gateway-api-server-header-transformation=PASS_THROUGH"
```

```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: test-gateway-config
  namespace: default
spec:
  envoy:
    serverHeaderTransformation: PASS_THROUGH
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: test-gateway-class
spec:
  controllerName: io.cilium/gateway-controller
  parametersRef:
    group: cilium.io
    kind: CiliumGatewayClassConfig
    name: test-gateway-config
    namespace: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: test-gateway-config
spec:
  gatewayClassName: test-gateway-class
  [...]
```
