### ISSUE TITLE
CFP: Cilium/Hubble to report the node info for the flow

### ISSUE THREAD

**Issue by liyihuang** [cilium/cilium#38932]
## Cilium Feature Proposal

When users observe their flow, they usually can see the source and destination pod info. I'm hoping we could also see the node info on the source and destionation node for the following reason

Most cloud provider charge a price for the inter az traffic, people could use https://kubernetes.io/docs/concepts/services-networking/topology-aware-routing/ or KPR with this feature in cilium to reduce their networking cost to let the pod choosing the intra az dst. If we could put the node info in the Hubble, that will give users better visibility since most of the k8s provider will put the az info in the k8s nodes.

For the following example, we can see the nodes are from `topology.kubernetes.io/zone: us-central1-a`. If we could have the src and dst nodes in the Hubble flow, with Hubble users can know what are the inter az traffic is and how to avoid those. After applying the topology-aware-routing, people can use Hubble to verify if that's aligned with their expectations.

```
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    node.gke.io/last-applied-node-taints: ""
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2025-04-14T10:23:17Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: e2-custom-2-4096
    beta.kubernetes.io/os: linux
    cloud.google.com/gke-boot-disk: pd-standard
    cloud.google.com/gke-container-runtime: containerd
    cloud.google.com/gke-cpu-scaling-level: "2"
    cloud.google.com/gke-logging-variant: DEFAULT
    cloud.google.com/gke-max-pods-per-node: "110"
    cloud.google.com/gke-memory-gb-scaling-level: "4"
    cloud.google.com/gke-nodepool: default-pool
    cloud.google.com/gke-os-distribution: cos
    cloud.google.com/gke-preemptible: "true"
    cloud.google.com/gke-provisioning: preemptible
    cloud.google.com/gke-stack-type: IPV4
    cloud.google.com/machine-family: e2
    cloud.google.com/private-node: "false"
    failure-domain.beta.kubernetes.io/region: us-central1
    failure-domain.beta.kubernetes.io/zone: us-central1-a
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux
    node.kubernetes.io/instance-type: e2-custom-2-4096
    topology.gke.io/zone: us-central1-a
    topology.kubernetes.io/region: us-central1
    topology.kubernetes.io/zone: us-central1-a
```
**Describe the feature you'd like**

If we could include the nodes label or at least related labels like `topology.gke.io/zone` etc in Hubble flow, then users can use those keys to query their log to know what the inter az traffic are, can those got optimized so they can save the inter az traffic cost.
