### ISSUE TITLE
bpf: Server Memory Exhaustion Caused by Unnecessary Map Creation in DistributedLRU

### ISSUE THREAD

**Issue by nueavv** [cilium/cilium#39070]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.3 and lower than v1.18.0

### What happened?

According to the tuning guide, I enabled distributedLRU and set mapDynamicSizeRatio to 0.08. As soon as these settings took effect, the system began creating an excessive number of maps—especially:

- cilium_ct4_global
- cilium_ct_any4_global
- cilium_lb4_reverse_sk
- cilium_nodeport_neigth4
- cilium_snat_v4_external

These maps consumed all available memory and caused the server to crash. Additionally, when I disabled distributedLRU, only one instance of each of these maps was created.

On a server with 64 GB of RAM, using mapDynamicSizeRatio = 0.08 should have limited dynamic map allocation to around 0.08 × 64 GB ≈ 5 GB, and even if you doubled that for safety, it would only be ≈ 10 GB. It’s therefore puzzling how it ended up consuming the entire 64 GB.

### How can we reproduce the issue?

```yaml
k8sServiceHost: "auto"
bpf:
  mapDynamicSizeRatio: 0.08
  masquerade: true
  lbAlgorithmAnnotation: false
distributedLRU:
  enabled: true
bpfClockProbe: true
cni:
  exclusive: false

socketLB:
  enabled: true 
  hostNamespaceOnly: true

hubble:
  relay:
    enabled: true
ipam:
  mode: "kubernetes"
kubeProxyReplacement: "true"
localRedirectPolicy: true
loadBalancer:
  algorithm: maglev
  mode: snat
  serviceTopology: true
nodePort:
  enabled: true
policyAuditMode: false
envoy:
  enabled: false
```

```sh
helm install cilium cilium/cilium --version 1.17.2 -n kube-system --values my-values.yaml
```

### Cilium Version

1.17.2

### Kernel Version

5.14.0-503.19.1.el9_5.x86_64

### Kubernetes Version

1.31.4

### Relevant log output

```shell

```

### Anything else?

OS: Rocky Linux 9.5
mem size: 64G

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
