### ISSUE TITLE
Dedicated cilium ingress not reachable from inside cluster

### ISSUE THREAD

**Issue by adippl** [cilium/cilium#39085]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.3 and lower than v1.18.0

### What happened?

I have issue with cilium blocking traffic to cilium ingress coming from inside cluster and I cannot unlock it with CNP.
General scenario looks like this. 
1. I expose some service via cilium ingress (mainly for managed TLS from cert-manager)
2. Ingress works fine for connection from outside cluster
3. Connection from inside of the cluster are blocked.

My connection get blocked between pod opening the connection and cilium ingress. 

This is how it looks in hubble:
In this case one of the pods tries to connect to app exposed via ingress and fails.
Source and destination descriptions in hubble are really strange:
Source is `reserved:ingress` and destination is `reserved:world`
(10.0.9.151 is IP from cilium ciliumloadbalancerippool)
![Image](https://github.com/user-attachments/assets/b08091e7-8847-4652-b826-41f4779c1808)

I've encountered this issue with s3 server behind ingress and loki server.
I think it's general cilium issue. I've had 3 different client applications failing to connect to these ingress exposed applications.
I've tried to create different cilium network policies to whitelist this traffic but I cannot find a way to 

### How can we reproduce the issue?

1. Create locked down k8s cluster with cilum
relevant cilium helm values:
```
policyEnforcementMode: default
policyAuditMode: false
hostFirewall:
  enabled: true
extraConfig:
  allow-localhost: policy
hostServices:
  enabled: true
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true


```

2. expose service via cilium ingress in dedicated mode (dedicated mode may or may not be relevant)
```
Example of ingress I'm using
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s3-ingress
  namespace: s3-rgw
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    ingress.cilium.io/force-https: "disabled"
    ingress.cilium.io/loadbalancer-mode: "dedicated"
spec:
  ingressClassName: cilium
  rules:
  - host: s3.domain.example
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: haproxy
            port:
              number: 80
  tls:
  - hosts:
    - s3.domain.example
    secretName: s3.domain.example

```
3. Try to connect to ingress service from inside cluster

### Cilium Version

1.17.3

### Kernel Version

6.12.16-gentoo-dist

### Kubernetes Version

v1.32.2

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
