### ISSUE TITLE
Share LB not working as expected

### ISSUE THREAD

**Issue by cloudcafetech** [cilium/cilium#39172]
I want to use common LB for different service name and protocol but rest all same as below.

```
apiVersion: v1
kind: Service
metadata:
  name: secondary-dns-tcp
  labels:
    k8s-app: secondary-dns
  annotations:
    "lbipam.cilium.io/sharing-key": "1234"
spec:
  type: LoadBalancer
  selector:
    k8s-app: secondary-dns
  ports:
  - port: 53
    name: dns-tcp
    protocol: TCP
    targetPort: 5353
---
apiVersion: v1
kind: Service
metadata:
  name: secondary-dns-udp
  labels:
    k8s-app: secondary-dns
  annotations:
    "lbipam.cilium.io/sharing-key": "1234"
spec:
  type: LoadBalancer
  selector:
    k8s-app: secondary-dns
  ports:
  - port: 53
    name: dns-udp
    protocol: UDP
    targetPort: 5353
```

But its taking different LB IP

```
root@ubuntu2004:~# k get svc
NAME                TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)        AGE
secondary-dns-tcp   LoadBalancer   10.102.141.143   192.168.0.33   53:31033/TCP   5s
secondary-dns-udp   LoadBalancer   10.98.33.114     192.168.0.34   53:32115/UDP   5s
```

- LB pool

```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: vm-lb-pool
spec:
  blocks:
  - cidr: "192.168.0.32/27"
```

**Comment by spal-x** [comment]
Seems like you have conflicting ports. Until a certain version, cilium did not differentiate protocols in services. Are you sure you are  using the correct cilium version?

**Comment by cloudcafetech** [comment]
>Are you sure you are using the correct cilium version?

 Which version my requirements will fulfill? 

I am using v1.16.6

**Comment by spal-x** [comment]
> > Are you sure you are using the correct cilium version?
> 
> Which version my requirements will fulfill?
> 
> I am using v1.16.6

Based on
https://github.com/cilium/cilium/pull/34691
You need 1.17.

**Comment by cloudcafetech** [comment]
Tested with 1.17.1

```
root@ubuntu2004:~# cilium status
E0429 14:16:57.874581   30833 websocket.go:296] Unknown stream id 1, discarding message
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    disabled (using embedded mode)
 \__/¯¯\__/    Hubble Relay:       disabled
    \__/       ClusterMesh:        disabled

DaemonSet              cilium                   Desired: 1, Ready: 1/1, Available: 1/1
Deployment             cilium-operator          Desired: 1, Ready: 1/1, Available: 1/1
Containers:            cilium                   Running: 1
                       cilium-operator          Running: 1
                       clustermesh-apiserver
                       hubble-relay
Cluster Pods:          3/3 managed by Cilium
Helm chart version:
Image versions         cilium             rancher/mirrored-cilium-cilium:v1.17.1: 1
                       cilium-operator    rancher/mirrored-cilium-operator-generic:v1.17.1: 1


root@ubuntu2004:~# k get svc
NAME                TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)        AGE
kubernetes          ClusterIP      10.96.0.1        <none>         443/TCP        11m
secondary-dns-tcp   LoadBalancer   10.100.102.188   192.168.0.33   53:31361/TCP   5m13s
secondary-dns-udp   LoadBalancer   10.96.142.120    192.168.0.34   53:30430/UDP   5m13s

root@ubuntu2004:~# k get po -A
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS      AGE
kube-system   cilium-operator-58bbb656d-pqc9s                         1/1     Running     0             12m
kube-system   cilium-sbcs7                                            1/1     Running     0             12m
kube-system   cloud-controller-manager-ubuntu2004                     1/1     Running     0             12m
kube-system   etcd-ubuntu2004                                         1/1     Running     0             12m
kube-system   helm-install-rke2-cilium-v6rqs                          0/1     Completed   0             13m
kube-system   helm-install-rke2-coredns-7lrbq                         0/1     Completed   0             13m
kube-system   helm-install-rke2-metrics-server-x64bs                  0/1     Completed   0             13m
kube-system   helm-install-rke2-multus-f87b2                          0/1     Completed   0             13m
kube-system   helm-install-rke2-runtimeclasses-hs4kr                  0/1     Completed   0             13m
kube-system   kube-apiserver-ubuntu2004                               1/1     Running     0             13m
kube-system   kube-controller-manager-ubuntu2004                      1/1     Running     0             12m
kube-system   kube-scheduler-ubuntu2004                               1/1     Running     0             12m
kube-system   rke2-coredns-rke2-coredns-6d54d78648-r88sd              1/1     Running     0             12m
kube-system   rke2-coredns-rke2-coredns-autoscaler-596dcdf688-k7hbx   1/1     Running     0             12m
kube-system   rke2-metrics-server-58ff89f9c7-b9svc                    1/1     Running     0             9m34s
kube-system   rke2-multus-hth4q                                       1/1     Running     4 (10m ago)   12m
kube-system   rke2-multus-rke2-whereabouts-wxp5f                      1/1     Running     0             12m

```

with below helm values

```
    operator:
      replicas: 1
    kubeProxyReplacement: true
    k8sServiceHost: "localhost"
    k8sServicePort: "6443"
    ipam:
      mode: kubernetes
    cni:
      exclusive: false
    l2announcements:
      enabled: true
    externalIPs:
      enabled: true
    socketLB:
      hostNamespaceOnly: true
    ingressController:
      enabled: true
    gatewayAPI:
      enabled: false
```
