### ISSUE TITLE
Clustermesh connectivity test suite gets stuck: Waiting for Service ... to be synchronized

### ISSUE THREAD

**Issue by EM-Savard** [cilium/cilium#39175]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.3 and lower than v1.18.0

### What happened?

I'm encountering an issue where the Cilium cluster mesh connectivity test suite (`cilium connectivity test --context $CLUSTER1 --multi-cluster $CLUSTER2`) gets stuck in the initializing stage when trying to synchronize services between clusters (_Waiting for Service ... to be synchronized_).  The issue occurs after successful Cilium installation via Helm on both clusters and proper clustermesh configuration. Despite the test failure, the actual clustermesh functionality works correctly as evidenced by: successful `healthy cilium status` on both clusters, successful `cilium clustermesh status`, successful multi-cluster service discovery confirmed via `cilium-dbg service list`, and services with global annotation successfully failing over between clusters. Required firewall rules have been correctly configured for Cilium, and we are still experiencing this issue even with an ANY-ANY rule on our firewall (which eliminates firewall restrictions as a potential cause)!

See the logs below to understand the issue 😉 

### How can we reproduce the issue?

1. Install `cilium` with Helm with following value files on 2 clusters minimum
```yaml
cluster:
  name: cluster-1
  id: 1

gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true

ipam:
  mode: kubernetes

kubeProxyReplacement: true

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

k8sServiceHost: localhost
k8sServicePort: 7445

gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true

tls:
  ca:
    cert: <CERT>
    key: <PRIVATE_KEY>

clustermesh:
  useAPIServer: true
  apiserver:
    service:
      type: NodePort
      nodePort: 31379 # different port for each cluster in the clustermesh

  config:
    enabled: true
    clusters:
      - name: cluster-1
        port: 31379 # different port for each cluster in the clustermesh
        ips: <CLUSTER_1_NODES_IP> # list
      - name: cluster-2
        port: 31380 # different port for each cluster in the clustermesh
        ips: <CLUSTER_2_NODES_IP> # list
      - name: cluster-3
        port: 31381 # different port for each cluster in the clustermesh
        ips: <CLUSTER_3_NODES_IP> # list
```

2. Run: `cilium connectivity test --context $CLUSTER1 --multi-cluster $CLUSTER2`

### Cilium Version

cilium-cli: v0.18.3 compiled with go1.24.2 on darwin/arm64
cilium image (default): v1.17.2
cilium image (stable): v1.17.3
cilium image (running): 1.17.3

### Kernel Version

Cilium runs on [Talos Linux](https://www.talos.dev/) OS: `1.9.4`

### Kubernetes Version

Kubernetes version: `1.31.2`

### Relevant log output

```shell
# ERROR: `cilium connectivity test --context $CLUSTER1 --multi-cluster $CLUSTER2`


➜ cilium connectivity test --context $CLUSTER1 --multi-cluster $CLUSTER2
ℹ️  Monitor aggregation detected, will skip some flow validation steps
ℹ️  Skipping tests that require a node Without Cilium
⌛ [mamba-mtl02-klab] Waiting for deployment cilium-test-1/client to become ready...
⌛ [mamba-mtl02-klab] Waiting for deployment cilium-test-1/client2 to become ready...
⌛ [mamba-mtl02-klab] Waiting for deployment cilium-test-1/echo-same-node to become ready...
⌛ [mamba-mtl42-klab] Waiting for deployment cilium-test-1/echo-other-node to become ready...
⌛ [mamba-mtl02-klab] Waiting for pod cilium-test-1/client-b65598b6f-8j9jg to reach DNS server on cilium-test-1/echo-same-node-799fbb4f76-zbgnf pod...
⌛ [mamba-mtl02-klab] Waiting for pod cilium-test-1/client2-84576868b4-xdbsp to reach DNS server on cilium-test-1/echo-same-node-799fbb4f76-zbgnf pod...
⌛ [mamba-mtl02-klab] Waiting for pod cilium-test-1/client2-84576868b4-xdbsp to reach DNS server on cilium-test-1/echo-other-node-757d5b66fd-xr4h9 pod...
⌛ [mamba-mtl02-klab] Waiting for pod cilium-test-1/client-b65598b6f-8j9jg to reach DNS server on cilium-test-1/echo-other-node-757d5b66fd-xr4h9 pod...
⌛ [mamba-mtl02-klab] Waiting for pod cilium-test-1/client-b65598b6f-8j9jg to reach default/kubernetes service...
⌛ [mamba-mtl02-klab] Waiting for pod cilium-test-1/client2-84576868b4-xdbsp to reach default/kubernetes service...
⌛ [mamba-mtl02-klab] Waiting for Service cilium-test-1/echo-same-node to become ready...
⌛ [mamba-mtl02-klab] Waiting for Service cilium-test-1/echo-same-node to be synchronized by Cilium pod kube-system/cilium-bwbxr
⌛ [mamba-mtl42-klab] Waiting for Service cilium-test-1/echo-same-node to be synchronized by Cilium pod kube-system/cilium-z8hz4
timeout reached waiting for service cilium-test-1/echo-same-node to appear in Cilium pod kube-system/cilium-z8hz4 (last error: service not yet synchronized)


# SUCCESSFULL: `cilium status` for both clusters

➜ cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    OK
 \__/¯¯\__/    Hubble Relay:       disabled
    \__/       ClusterMesh:        OK

DaemonSet              cilium                   Desired: 5, Ready: 5/5, Available: 5/5
DaemonSet              cilium-envoy             Desired: 5, Ready: 5/5, Available: 5/5
Deployment             cilium-operator          Desired: 2, Ready: 2/2, Available: 2/2
Deployment             clustermesh-apiserver    Desired: 1, Ready: 1/1, Available: 1/1
Containers:            cilium                   Running: 5
                       cilium-envoy             Running: 5
                       cilium-operator          Running: 2
                       clustermesh-apiserver    Running: 1
                       hubble-relay
Cluster Pods:          7/7 managed by Cilium
Helm chart version:    1.17.3
Image versions         cilium                   quay.io/cilium/cilium:v1.17.3@sha256:1782794aeac951af139315c10eff34050aa7579c12827ee9ec376bb719b82873: 5
                       cilium-envoy             quay.io/cilium/cilium-envoy:v1.32.5-1744305768-f9ddca7dcd91f7ca25a505560e655c47d3dec2cf@sha256:a01cadf7974409b5c5c92ace3d6afa298408468ca24cab1cb413c04f89d3d1f9: 5
                       cilium-operator          quay.io/cilium/operator-generic:v1.17.3@sha256:8bd38d0e97a955b2d725929d60df09d712fb62b60b930551a29abac2dd92e597: 2
                       clustermesh-apiserver    quay.io/cilium/clustermesh-apiserver:v1.17.3@sha256:98d5feaf67dd9b5d8d219ff5990de10539566eedc5412bcf52df7592


# SUCCESSFULL: `cilium clustermesh status` for both clusters

➜ cilium clustermesh status
⚠️  Service type NodePort detected! Service may fail when nodes are removed from the cluster!
✅ Service "clustermesh-apiserver" of type "NodePort" found
✅ Cluster access information is available:
  - 10.10.10.1:31379
✅ Deployment clustermesh-apiserver is ready
ℹ️  KVStoreMesh is enabled
E0425 16:14:02.499162   81496 websocket.go:296] Unknown stream id 1, discarding message

✅ All 5 nodes are connected to all clusters [min:2 / avg:2.0 / max:2]
✅ All 1 KVStoreMesh replicas are connected to all clusters [min:2 / avg:2.0 / max:2]

🔌 Cluster Connections:
  - cluster-2: 5/5 configured, 5/5 connected - KVStoreMesh: 1/1 configured, 1/1 connected
  - cluster-3: 5/5 configured, 5/5 connected - KVStoreMesh: 1/1 configured, 1/1 connected

🔀 Global services: [ min:3 / avg:3.0 / max:3 ]
```

### Anything else?

We have enabled NodePort service type because it's the only way that the nodes could discover themselves on our network.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
