### ISSUE TITLE
Pods are not able to reach Cilium-managed LoadBalancer IP

### ISSUE THREAD

**Issue by DaruZero** [cilium/cilium#39198]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.3 and lower than v1.18.0

### What happened?

I am running Cilium as a kube-proxy replacement in a k3s cluster (on-prem), with native routing and DSR. I am also using the LB IPAM feature with L2 announcements to assign a VIP to my LoadBalancer Services.

Almost everything works perfectly: I can reach Pods via the LoadBalancer IP from any host (both within and without the k8s cluster), and Pods can reach each other using service DNS; the problem is when I try to connect from a Pod to the LoadBalancer IP, as the packets get dropped. This happens from any pod, whether it is pointed to from the service or not.

A simple example would be to deploy e.g. a database server and a client, in different namespaces. From the client I can connect to the server via the internal service DNS names, like `mongo-01.mongodb.svc.cluster.local` just fine, but if I try to use the IP assigned to the LoadBalancer service, then the host is unreachable

### How can we reproduce the issue?

1. Setup k3s cluster (any number of nodes) without kube-proxy
   ```yaml
   disable:
     - traefik
     - servicelb
     - local-storage
   disable-helm-controller: true
   disable-network-policy: true
   disable-kube-proxy: true
   flannel-backend: none
   ```
2. Install latest Cilium Helm chart with the following values
   ```yaml
   autoDirectNodeRoutes: true
   bpf:
     masquerade: true
   endpointHealthChecking:
     enabled: true
   externalIPs:
     enabled: true
   healthChecking: true
   hubble:
     relay:
       enabled: true
     ui:
       enabled: true
   ipam:
     mode: kubernetes
     operator:
       clusterPoolIPv4PodCIDRList: 10.42.0.0/16
   ipv4NativeRoutingCIDR: 10.42.0.0/16
   k8sClientRateLimit:
     burst: 75
     qps: 50
   k8sServiceHost: k8s.kubelab.alea.lab
   k8sServicePort: 6443
   kubeProxyReplacement: true
   l2announcements:
     enabled: true
     leaseDuration: 3s
     leaseRenewDeadline: 1s
     leaseRetryPeriod: 200ms
   l7Proxy: false
   loadBalancer:
     mode: dsr
   nodePort:
     enabled: true
   routingMode: native
   socketLB:
     enabled: true
     hostNamespaceOnly: true
   tunnelProtocol: ""
   ```
3. Create L2 announcement policy and IP pools
4. Create a Deployment with >1 replicas and a Service of type LoadBalancer that points to it
5. Exec into one of the Pods and try to ping/netcat the external IP of the Service

### Cilium Version

```
cilium-cli: v0.18.3 compiled with go1.24.2 on linux/amd64
cilium image (default): v1.17.2
cilium image (stable): v1.17.3
cilium image (running): 1.17.3
```

### Kernel Version

```
Linux kubelab-w07 5.15.0-307.178.5.el8uek.x86_64 #2 SMP Wed Mar 19 13:00:52 PDT 2025 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.32.3+k3s1
```

### Sysdump

_file is too big_

### Relevant log output

```shell

```

### Anything else?

I followed the troubleshooting guide of L2 announcements, but every check passes. I do have the correct leases, and the correct network devices are selected.

I tried with both `bpf.masquerade=true` and `bpf.masquerade=false`. The only difference is that, from _outside_ the cluster, the ping command has different results: when `true` the packets are simply lost, when `false` I get the `Time to live exceeded` error from the announcing node IP before the packets are dropped. Netcat works in both cases. 

I doubt that this is an actual Cilium bug, more likely I am just missing some configuration

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by borkmann** [comment]
A sysdump would help to have some more infos, e.g. on the service table. When you say:

> the problem is when I try to connect from a Pod to the LoadBalancer IP, as the packets get dropped. This happens from any pod, whether it is pointed to from the service or not.

Are you able to connect to the LB service from a client outside the cluster but in the same L2 or is that non-functional too?

Cc @dylandreimerink

**Comment by dylandreimerink** [comment]
> when I try to connect from a Pod to the LoadBalancer IP, as the packets get dropped. This happens from any pod, whether it is pointed to from the service or not.

Right. That is because the ARP reply is implemented in the `from-netdev` eBPF program, which only gets triggered for external traffic entering the node, not pod traffic. 

This should make sense since LoadBalancer services are mean to be uses this way (traditionally implemented in a LB external to the cluster, which forwards traffic to the node port). Pods are supposed to use the ClusterIP which should work just fine. 

In theory, Cilium should already have all of the info to make the LB decision without ARP. Not sure if its intentional or not that we do not translate the LoadBalancer IP for pod-to-service traffic. I recall having seen similar issues with L2/BGP, but I will have to go dig though some issues.

**Comment by DaruZero** [comment]
Yes, a client outside the cluster and in the same L2 can connect just fine to a service behind a VIP.

Now I have tinkered a bit with the Cilium configuration and somehow I got it to work also for clients inside the cluster that use the VIP to connect to other services inside the cluster. I think the key was setting  `bpf.masquerade: false`, but I'm not totally sure. These are my current helm values for cilium:
```yaml
autoDirectNodeRoutes: true
bpf:
  masquerade: false
endpointHealthChecking:
  enabled: true
externalIPs:
  enabled: true
healthChecking: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
ipam:
  mode: kubernetes
  operator:
    clusterPoolIPv4PodCIDRList: 10.42.0.0/16
ipv4NativeRoutingCIDR: 10.42.0.0/16
k8sClientRateLimit:
  burst: 200
  qps: 170
k8sServiceHost: k8s.kubelab.alea.lab
k8sServicePort: 6443
kubeProxyReplacement: true
l2announcements:
  enabled: true
  leaseDuration: 3s
  leaseRenewDeadline: 1.5s
  leaseRetryPeriod: 1s
l7Proxy: false
loadBalancer:
  mode: dsr
nodePort:
  enabled: true
routingMode: native
socketLB:
  enabled: true
  hostNamespaceOnly: true
tunnelProtocol: ""
```

The only thing not working properly from outside the cluster is when i try to `ping` the VIP: I get a `Time to live exceeded` error.
`traceroute` shows the packets being bounced between the lease holder (10.3.3.15) and the node with the pod (10.3.3.18)
```
traceroute to 10.3.3.26 (10.3.3.26), 30 hops max, 60 byte packets
 1  _gateway (10.4.0.254)  0.469 ms  0.406 ms  0.464 ms
 2  10.3.3.15 (10.3.3.15)  1.185 ms  1.103 ms  1.216 ms
 3  10.3.3.18 (10.3.3.18)  1.190 ms  1.188 ms  1.059 ms
 4  10.3.3.15 (10.3.3.15)  1.076 ms  1.117 ms  1.128 ms
 5  10.3.3.18 (10.3.3.18)  1.203 ms  1.254 ms  1.074 ms
 6  * * *
 7  * * *
 8  * * *
 9  * * *
10  * * *
11  * 10.3.3.18 (10.3.3.18)  1.696 ms  1.576 ms
12  10.3.3.15 (10.3.3.15)  1.515 ms  1.512 ms  1.498 ms
13  10.3.3.18 (10.3.3.18)  2.003 ms *  1.939 ms
14  10.3.3.15 (10.3.3.15)  2.040 ms  2.022 ms *
15  10.3.3.18 (10.3.3.18)  1.986 ms * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * 10.3.3.18 (10.3.3.18)  2.615 ms  2.400 ms
22  10.3.3.15 (10.3.3.15)  2.352 ms  2.310 ms  2.269 ms
23  10.3.3.18 (10.3.3.18)  2.206 ms  2.285 ms  2.200 ms
24  10.3.3.15 (10.3.3.15)  2.318 ms *  2.067 ms
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * 10.3.3.15 (10.3.3.15)  2.042 ms  1.943 ms
```
The only reason I can think of to justify this behavior is that at L3 the node with the lease knows to route packets to the node with the pod, while the node with the pod expects L4 packets in order to know how to forward them to pods.
Still kind of weird though, as it could throw off someone during troubleshooting

PS sysdump is too large to upload in a comment
