### ISSUE TITLE
cilium endpoint goes into not-ready state after editing l7 rule from http to kafka

### ISSUE THREAD

**Issue by manalibhutiyani** [cilium/cilium#3926]
Reported by @michi-covalent 

my policy had an error where the l7 rule was supposed to be kafka but it was http instead:
   ```
     rules:
          http:
          - {}
```
i used kubectl edit cnp and modified the rule to:
```
        rules:
          kafka:
          - {}
```
but after the the endpoint went to not-ready state and it didn't come back.

**Comment by manalibhutiyani** [comment]
This is similar to trying to import conflicting policies.

This is the error we get in cilium
```
level=info msg="Policy imported via API, recalculating..." policyRevision=10
level=info msg="Imported CiliumNetworkPolicy" ciliumNetworkPolicyName=rule1 k8sApiVersion= k8sNamespace=default
level=warning msg="Generating BPF for endpoint failed, keeping stale directory." containerID=0e60275c89 endpointID=60670 file-path=/var/run/cilium/state/60670_next_fail policyRevision=8
level=warning msg="Regeneration of endpoint program failed" containerID=0e60275c89 endpointID=60670 error="Unable to allocate ingress redirects: invalid type \"kafka\", must be of type \"http\"" policyRevision=8
level=warning msg="Generating BPF for endpoint failed, keeping stale directory." containerID=0e60275c89 endpointID=60670 file-path=/var/run/cilium/state/60670_next_fail policyRevision=8
level=warning msg="Regeneration of endpoint program failed" containerID=0e60275c89 endpointID=60670 error="Unable to allocate ingress redirects: invalid type \"kafka\", must be of type \"http\"" policyRevision=8
level=warning msg="Generating BPF for endpoint failed, keeping stale directory." containerID=40ce20098d endpointID=15124 file-path=/var/run/cilium/state/15124_next_fail policyRevision=8
level=warning msg="Regeneration of endpoint program failed" containerID=40ce20098d endpointID=15124 error="Unable to allocate ingress redirects: invalid type \"kafka\", must be of type \"http\"" policyRevision=8
level=info msg="Endpoint policy recalculated" containerID=cilium-loc endpointID=29898 policyRevision=10
level=info msg="Endpoint policy recalculated" containerID=b88a150128 endpointID=48896 policyRevision=10
level=info msg="Endpoint policy recalculated" containerID=d31839ee4b endpointID=29381 policyRevision=10
level=info msg="Endpoint policy recalculated" containerID=b88a150128 endpointID=48896 policyRevision=10
```

Ideally ` kubectl edit cnp ` should have failed stating this error. Do we expect to delete the endpoint altogether along with closing the envoy proxy redirect and regenerate the endpoint with Kafka rules?

This is similar to trying to apply 2 conflicting policies like so:

```
Manalis-MBP:cilium manalibhutiyani$ cat ~/Desktop/dummy_policy.yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "L7 policy to restrict access to specific HTTP call"
metadata:
  name: "rule1"
spec:
  endpointSelector:
    matchLabels:
      org: empire
      class: deathstar
  ingress:
  - fromEndpoints:
    - matchLabels:
        org: empire
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        http:
        - {}
Manalis-MBP:cilium manalibhutiyani$ cat ~/Desktop/dummy_policy-kafka.yaml 
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "L7 policy to restrict access to specific kafka call"
metadata:
  name: "rule2"
spec:
  endpointSelector:
    matchLabels:
      org: empire
      class: deathstar
  ingress:
  - fromEndpoints:
    - matchLabels:
        org: empire
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        kafka:
        - {}
Manalis-MBP:cilium manalibhutiyani$ 
```

Output after applying
```

Manalis-MBP:cilium manalibhutiyani$ kubectl create -f ~/Desktop/dummy_policy.yaml 
ciliumnetworkpolicy "rule1" created
Manalis-MBP:cilium manalibhutiyani$ kubectl create -f ~/Desktop/dummy_policy-kafka.yaml 
ciliumnetworkpolicy "rule2" created
Manalis-MBP:cilium manalibhutiyani$ 

```

kubectl suceeds but cilium endpoint goes in` not-ready` state with cilium logs:

```
level=info msg="Imported CiliumNetworkPolicy" ciliumNetworkPolicyName=rule1 k8sApiVersion= k8sNamespace=default
level=info msg="Endpoint policy recalculated" containerID=d31839ee4b endpointID=29381 policyRevision=14
level=info msg="Endpoint policy recalculated" containerID=cilium-loc endpointID=29898 policyRevision=14
level=info msg="Endpoint policy recalculated" containerID=40ce20098d endpointID=15124 policyRevision=14
level=info msg="Endpoint policy recalculated" containerID=0e60275c89 endpointID=60670 policyRevision=14
level=info msg="Policy imported via API, recalculating..." policyRevision=15
level=info msg="Imported CiliumNetworkPolicy" ciliumNetworkPolicyName=rule2 k8sApiVersion= k8sNamespace=default
level=warning msg="Error while handling policy updates for endpoint" error="15124: Cannot merge conflicting L7 parsers (kafka/http)"
level=warning msg="Error while handling policy updates for endpoint" error="60670: Cannot merge conflicting L7 parsers (kafka/http)"
level=info msg="Endpoint policy recalculated" containerID=d31839ee4b endpointID=29381 policyRevision=15
level=info msg="Endpoint policy recalculated" containerID=cilium-loc endpointID=29898 policyRevision=15
```
