### ISSUE TITLE
Error while updating MTU for endpoint

### ISSUE THREAD

**Issue by marcocondrache** [cilium/cilium#39342]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.3 and lower than v1.18.0

### What happened?

Cilium pod agent constantly reports an error:

`cilium-agent time=2025-05-05T20:09:15Z level=error msg="error while updating MTU for endpoint" module=agent.datapath.mtu netns=cni-30cc5654-9d08-ba33-b297-82ca1f85e183 error="set netns: invalid argument (terminating OS thread)"`

### How can we reproduce the issue?

1. Install cilium with helm
2. Use those values:

```yaml
ipam:
  mode: kubernetes

k8s:
  requireIPv4PodCIDR: true

kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256

k8sServiceHost: 127.0.0.1
k8sServicePort: 7445

routingMode: native
ipv4NativeRoutingCIDR: 10.42.0.0/16
installNoConntrackIptablesRules: true

autoDirectNodeRoutes: true

cni:
  exclusive: false

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

l2announcements:
  enabled: true

endpointRoutes:
  enabled: true

loadBalancer:
  mode: dsr
  algorithm: maglev

gatewayAPI:
  enabled: true
  enableAlpn: true
  xffNumTrustedHops: 1

rollOutCiliumPods: true

bandwidthManager:
  enabled: true
  bbr: true

envoy:
  enabled: true
  rollOutEnvoyPods: true

operator:
  replicas: 1
  rollOutPods: true

bpfClockProbe: true

bpf:
  masquerade: true
  datapathMode: netkit
  preallocateMaps: true

encryption:
  enabled: true
  type: wireguard

enableIPv4BIGTCP: true
enableIPv6BIGTCP: true

hubble:
  enabled: false

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - PERFMON
      - BPF
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
```

### Cilium Version

1.17.3

### Kernel Version

Linux queen 6.12.25-talos #1 SMP Fri Apr 25 13:53:58 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

v1.33.0

### Sysdump

[cilium-sysdump-20250505-221428.zip](https://github.com/user-attachments/files/20047920/cilium-sysdump-20250505-221428.zip)

### Relevant log output

```shell
cilium-agent time=2025-05-05T20:09:15Z level=error msg="error while updating endpoint" module=agent.datapath.mtu netns=cni-30cc5654-9d08-ba33-b297-82ca1f85e183 error="set netns: invalid argument (terminating OS thread)"
```

### Anything else?

I don't know if this error is related, but my L2 announcements aren't working. I can't confirm if the node correctly answers ARP requests; I can send requests, but I never receive a response.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
