### ISSUE TITLE
DNS resolution timeout while upgrading cilium

### ISSUE THREAD

**Issue by faelis** [cilium/cilium#39391]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.3 and lower than v1.18.0

### What happened?

While upgrading the cilium chart from 1.17.1 to 1.17.3, we lost the DNS resolution for +/- 1min on some of our critical clusters.
It look likes DNS request forwarded to envoy dropped when the envoy pod is recreated.

During our test, we managed to reproduce the bug, and removing the `rule.dns` block on every networkpolicies seems to mitigate it.

That seems to be related to [13194](https://github.com/cilium/cilium/issues/13194) (and all of its related issues).

### How can we reproduce the issue?

1. Create an minimalist cluster with coredns and the cilium chart version 1.17.1 with this values.yaml :
```yaml
aksbyocni: 
  enabled: true
nodeinit:
  enabled: true
  image:
    repository: "registry.xxx/04228.proxy.quay.io/cilium/startup-script"
    useDigest: false
imagePullSecrets:
  - name: 04228.prod
prometheus:
  enabled: true
image:
  repository: "registry.xxx/04228.proxy.quay.io/cilium/cilium"
  useDigest: false
podAnnotations:
  ad.datadoghq.com/cilium-agent.check_names: '["cilium"]'
  ad.datadoghq.com/cilium-agent.init_configs: '[{}]'
  ad.datadoghq.com/cilium-agent.logs: |
    [
      {
        "source": "cilium-agent",
        "service": "cilium-agent",
        "log_processing_rules": [{
          "type": "include_at_match",
          "name": "error_logs",
          "pattern" : ".*error.*"
        }]
    }]
  ad.datadoghq.com/cilium-agent.instances: |
    [
      {
        "agent_endpoint": "http://%%host%%:9962/metrics",
        "use_openmetrics": "true"
      }
    ]
resources:
  requests:
    cpu: 100m
    memory: 256Mi
operator:
  priorityClassName: "system-cluster-critical"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  image:
    repository: "registry.xxx/04228.proxy.quay.io/cilium/operator"
    useDigest: false
  prometheus:
    enabled: true
  podAnnotations:
    ad.datadoghq.com/cilium-operator.check_names: '["cilium"]'
    ad.datadoghq.com/cilium-operator.init_configs: '[{}]'
    ad.datadoghq.com/cilium-operator.logs: |
      [
        {
          "source": "cilium-operator",
          "service": "cilium-operator",
          "log_processing_rules": [{
            "type": "include_at_match",
            "name": "error_logs",
            "pattern" : ".*error.*"
          }]
        }
      ]
    ad.datadoghq.com/cilium-operator.instances: |
      [
        {
          "operator_endpoint": "http://%%host%%:9963/metrics",
          "use_openmetrics": "true"
        }
      ]
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
ipam: 
  operator:
    clusterPoolIPv4PodCIDRList:
    - 100.64.0.0/17
kubeProxyReplacement: true
nodePort:
  enableHealthCheck: false
rollOutCiliumPods: true
k8sServicePort: 443
localRedirectPolicy: true
priorityClassName: "system-node-critical"
hubble:
  relay:
    image:
      repository: "registry.xxx/04228.proxy.quay.io/cilium/hubble-relay"
      useDigest: false
  ui:
    backend:
      image:
        repository: "registry.xxx/04228.proxy.quay.io/cilium/hubble-ui-backend"
        useDigest: false
    frontend:
      image:
        repository: "registry.xxx/04228.proxy.quay.io/cilium/hubble-ui"
        useDigest: false
envoy:
  image:
    repository: "registry.xxx/04228.proxy.quay.io/cilium/cilium-envoy"
    useDigest: false
loadBalancer:
  serviceTopology: true
```
2. Apply these netwoks policies :
```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-to-cluster-web
  namespace: default
spec:
  egress:
  - toEntities:
    - cluster
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
    - ports:
      - port: "80"
        protocol: TCP
  endpointSelector: {}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-to-kube-dns
  namespace: default
spec:
  egress:
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
      rules:
        dns:
        - matchPattern: '*'
  endpointSelector: {}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-from-to-world
  namespace: default
spec:
  egress:
  - toEntities:
    - world
  endpointSelector: {}
  ingress:
  - fromEntities:
    - world
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-from-to-namespace
  namespace: default
spec:
  egress:
  - toEndpoints:
    - {}
  endpointSelector: {}
  ingress:
  - fromEndpoints:
    - {}
 ```
3. Run an alpine pod in default namespace that run this :
```bash
while true; do
nslookup google.com
done
```
4. Upgrade the cilium chart to version 1.17.3
5. The nslookup will throw timeout during less that 1min when the local envoy pod rollout
6. Removing this block from the 'allow-to-kube-dns' policy mitigate the bug :
```yaml
      rules:
        dns:
        - matchPattern: '*'
```

### Cilium Version

from 1.17.1 to 1.17.3

### Kernel Version

5.15.x

### Kubernetes Version

AKS - v1.31.x

### Sysdump

As we use argo to deploy and manage cilium, there is no helm release in the cluster and therefore I didn't managed to create a sysdump.

### Relevant log output

```shell

```

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
