### ISSUE TITLE
Gateway API: Overzealous "Invalid CertificateRef" in Gateway object

### ISSUE THREAD

**Issue by josemaia** [cilium/cilium#39425]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.9 and lower than v1.17.0

### What happened?

Running my own setup with a custom ClusterIssuer (following [cert-manager docs](https://cert-manager.io/docs/contributing/external-issuers/)), I created a Gateway with a standard 443/80 setup, matching HTTPRoute and a Certificate object creating the secret to protect it via TLS.

The issuer successfully creates a cert, the cert is placed in its namespace and copied over to the cilium secrets namespace. However, describing the Gateway object I always get the status on the listener indicating an invalid CertificateRef

```yaml
  - attachedRoutes: 1
    conditions:
    - lastTransitionTime: "2025-05-08T08:57:45Z"
      message: Invalid CertificateRef
      reason: Invalid
      status: "False"
      type: Programmed
    - lastTransitionTime: "2025-05-08T08:57:45Z"
      message: Listener Accepted
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2025-05-08T08:57:45Z"
      message: Invalid CertificateRef
      reason: InvalidCertificateRef
      status: "False"
      type: ResolvedRefs
```

Even though this message is showing, the CiliumEnvoyConfig looks good, the Gateway is properly accessible and using `cilium-dbg envoy admin certs` shows the cert correctly.

### How can we reproduce the issue?

1. cilium 1.16.x installed via helm, with Gateway API enabled
2. certificate issued by a custom CA (self-signed may be enough to emulate this?)
3. create gateway object (see attachment for a censored version of the sample I was using)

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: josemaia-gateway
  namespace: logging
spec:
  infrastructure:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  gatewayClassName: cilium
  listeners:
    - name: josemaia-http
      port: 80
      protocol: HTTP
      hostname: "josemaia.apps.mycluster.azure"
      allowedRoutes:
        namespaces:
          from: All
    - name: josemaia-https
      port: 443
      protocol: HTTPS
      hostname: "josemaia.apps.mycluster.azure"
      tls:
        certificateRefs:
          - name: josemaia-gateway-tls
            namespace: logging
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: josemaia-httproute
  namespace: logging
spec:
  parentRefs:
    - name: josemaia-gateway
      namespace: logging
  hostnames:
    - "josemaia.apps.mycluster.azure"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: alloy
          port: 12345
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: josemaia-gateway-tls
  namespace: logging
spec:
  commonName: josemaia.apps.mycluster.azure
  dnsNames:
    - josemaia.apps.mycluster.azure
  issuerRef:
    kind: ClusterIssuer
    name: my-custom-cluster-issuer
    group: cert-manager.pki.mycompany.com
  secretName: josemaia-gateway-tls
  privateKey:
    rotationPolicy: Always
  subject:
    countries:
    - DE
    localities:
    - Munich
    organizationalUnits:
    - PKI
    organizations:
    - My Company
    provinces:
    - Bavaria
```

### Cilium Version

```
Client: 1.16.9 bf7387b2 2025-04-09T16:58:08+00:00 go version go1.23.8 linux/amd64
Daemon: 1.16.9 bf7387b2 2025-04-09T16:58:08+00:00 go version go1.23.8 linux/amd64
```

### Kernel Version

```
Linux aks-default-21447123-vmss00007G 5.15.0-1084-azure #93-Ubuntu SMP Sat Mar 15 14:12:29 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: v1.30.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.11
```

### Regression

First observed yesterday.

### Relevant log output

```shell

```

### Anything else?

Let me know if anything else (cilium config or cilium envoy config?) would be useful to share.

relevant excerpt
```yaml
  enable-gateway-api: "true"
  enable-gateway-api-alpn: "false"
  enable-gateway-api-app-protocol: "false"
  enable-gateway-api-proxy-protocol: "false"
  enable-gateway-api-secrets-sync: "true"
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
