### ISSUE TITLE
Gateway API with ALPN enbled won't GRPC

### ISSUE THREAD

**Issue by bittrance** [cilium/cilium#39484]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.3 and lower than v1.18.0

### What happened?

GRPC traffic is not routed properly when ALPN is enabled.

### How can we reproduce the issue?

```
cat > ./kind-cluster-no-cni.yaml <<EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
EOF
kind create cluster --config ./kind-cluster-no-cni.yaml
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/experimental-install.yaml
helm upgrade --install cilium cilium/cilium \
              --version 1.17.3 \
              --namespace kube-system \
              --set image.pullPolicy=IfNotPresent \
              --set ipam.mode=kubernetes \
              --set gatewayAPI.enabled=true \
              --set nodePort.enabled=true \
              --set kubeProxyReplacement=true \
              --set k8sServiceHost=kind-control-plane \
              --set k8sServicePort=6443
helm upgrade --install \
              cert-manager jetstack/cert-manager \
              --namespace cert-manager \
              --create-namespace \
              --version v1.17.0 \
              --set crds.enabled=true
kubectl apply -f https://raw.githubusercontent.com/bittrance/kubernetes-experiments/26dd80d517864735a2695101008a0e9123da65df/oidc-federation/selfsigned-ca.yaml
kubectl apply -f https://gist.githubusercontent.com/bittrance/80b897fb6b96154b772e710f6a10d330/raw/df2c1e02b877769201ba3484fabd7bc9495dfccb/hello-grpc.yaml
```

With this setup, as expected, there is no ALPN:

```
openssl s_client -connect cilium-gateway-hello-grpc.hello-grpc.test:443 -alpn h2
...
No ALPN negotiated
...
```

Still, with grpcurl, I can interact with the "hello-grpc" service. Given that HTTP/2 demands ALPN, this is a bit odd, but may be because of https://github.com/grpc/grpc-go/issues/434? Anyway, this demonstrates that the GRPCRoute and the backing service works.

```
$ grpcurl -proto greetings.proto -insecure -d '{"name": "Bittrance", "delay_ms": 1}' cilium-gateway-hello-grpc.hello-grpc.test:443 greetings.GreetMe/Send
{
  "greeting": "Hello Bittrance!"
}
```

However, when I add `gatewayAPI.enableAlpn=true` to the Cilium Helm chart, I do get ALPN negotiation:

```
openssl s_client -connect cilium-gateway-hello-grpc.hello-grpc.test:443 -alpn h2
...
ALPN protocol: h2
...
```

However, the "hello-grpc" service is no longer available:

```
$ grpcurl -proto greetings.proto -insecure -d '{"name": "Bittrance", "delay_ms": 1}' cilium-gateway-hello-grpc.hello-grpc.test:443 greetings.GreetMe/Send
ERROR:
  Code: Unavailable
  Message: upstream connect error or disconnect/reset before headers. reset reason: protocol error
```
The GRPCRoute seems healthy:
```
status:
  parents:
  - conditions:
    - lastTransitionTime: "2025-05-11T09:08:34Z"
      message: Accepted GRPCRoute
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2025-05-11T09:08:34Z"
      message: Service reference is valid
      observedGeneration: 1
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    controllerName: io.cilium/gateway-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: hello-grpc
      sectionName: https
```
Envoy config is here https://gist.github.com/bittrance/51b0f89ef3f2892bb01dd49c64be5bf7

### Cilium Version

cilium-cli: v0.18.3 compiled with go1.24.2 on linux/amd64
cilium image (default): v1.17.2
cilium image (stable): v1.17.3
cilium image (running): 1.17.3

### Kernel Version

Linux dev-andqvi 6.8.0-59-generic #61-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 11 23:16:11 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.31.0

### Regression

I'm not sure if this is a regression on https://github.com/cilium/cilium/issues/31811 or if testing in that issue was not thorough enough?

### Relevant log output

```shell
The only bit I can find that might be related (or indeed non-info) is:

[2025-05-11 09:09:04.157][13][warning][config] [external/envoy/source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:130] gRPC config: initial fetch timed out for type.googleapis.com/envoy.config.route.v3.RouteConfiguration
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
