### ISSUE TITLE
cilium eni mode eks

### ISSUE THREAD

**Issue by devopscaxsol** [cilium/cilium#39519]
Hello All ,

I am facing error in cilium operator pods post deployment using helm. I am having values yaml like below.

ERROR is "2025-05-14T03:50:21.332431967Z" level=fatal msg="eni allocator is not supported by this version of cilium-operator-generic" subsys=cilium-operator-generic

I am trying to setup on aws eks cluster.

```
ipam:
  mode: "eni"     
  

policyEnforcementMode: "default"


kubeProxyReplacement: true
enableXTSocketFallback: true


aws:
  enabled: true
  enablePrefixDelegation: true        

routingMode: "native"                 

hostServices:
  enabled: true
operator:
  enabled: true
  # aws:
  #   enabled: true
  useGenericDeployment: false

operatorSpecific:
  aws:
    enabled: true

```

Command I am using for installation is 

```
kubectl delete daemonset aws-node -n kube-system

kubectl delete daemonset kube-proxy -n kube-system

helm install cilium cilium/cilium --version 1.17.3   -n kube-system -f values_cilium.yaml

```
