### ISSUE TITLE
Cilium Gateway API with NodePort and TLS not working - connection refused on NodePort

### ISSUE THREAD

**Issue by zoonderkins** [cilium/cilium#39599]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.3 and lower than v1.18.0

### What happened?

Based on this issue https://github.com/cilium/cilium/issues/38227

I'm experiencing an issue with Cilium Gateway API when using NodePort and TLS. While HTTP Gateway works correctly with NodePort, the HTTPS Gateway fails with connection refused errors when trying to access it via the NodePort.
Environment:
k0s: v1.32.4+k0s
Cilium: v1.17.3
Gateway API: v1.3.0/v1.3.1
Operating System: Debian GNU/Linux 12 (bookworm)
Container Runtime: containerd://1.7.27
VPS: Contabo VPS with public ipv4

I've configured Cilium with Gateway API support and set up a GatewayClass with CiliumGatewayClassConfig to use NodePort.
My configuration:

```yaml
# GatewayClass with CiliumGatewayClassConfig
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium-nodeport
spec:
  controllerName: io.cilium/gateway-controller
  description: Cilium GatewayClass with NodePort service type
  parametersRef:
    group: cilium.io
    kind: CiliumGatewayClassConfig
    name: cilium-nodeport-config
    namespace: prod

---
apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: cilium-nodeport-config
  namespace: prod
spec:
  service:
    type: NodePort

# HTTPS Gateway using the GatewayClass
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: k8s-dashboard-gateway
  namespace: prod
  annotations:
    cert-manager.io/issuer: buypass-issuer
spec:
  gatewayClassName: cilium-nodeport
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    hostname: "k8s.edoo.dev"
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      certificateRefs:
      - kind: Secret
        name: k8s-edoo-dev-tls
```

**Observed Behavior:**

- The Gateway is programmed successfully and shows as "True" for both "Accepted" and "Programmed" conditions
- The service is created with type LoadBalancer but has a NodePort assigned (32547)
- When trying to access the NodePort externally, I get "Connection refused"
- HTTP Gateways work correctly with the same setup (only TLS gateways fail)
- Cilium logs show warnings: level=warning msg="service not found" k8sNamespace=prod k8sSvcName=cilium-gateway-k8s-dashboard-gateway obj="89.xxx.xx.138:32547/ANY" subsys=k8s-watcher

**Troubleshooting Steps Taken:**

- Confirmed the node firewall allows traffic on port 32547
- Verified that the HTTP gateway works correctly (both internal and external access)
- Checked cert-manager certificates are valid and properly created
- Tried connecting from inside the cluster and got TLS handshake errors
- Examined Cilium logs and found "service not found" warnings for the gateway service
- Tried recreating the gateway multiple times

**Expected Behavior:**

- The HTTPS Gateway should bind to the NodePort and accept connections on that port, just like the HTTP Gateway does.
- This issue appears to be similar to #38227, where there's a problem with Cilium Gateway API's NodePort implementation when TLS is involved.

---

I try with HTTP solution
```export KUBECONFIG=./k0s-color-cluster.config && kubectl run -it --rm -n prod curl --image=curlimages/curl --restart=Never -- curl -v http://cilium-gateway-k8s-dashboard-http-gateway.prod.svc.cluster.local:80```

I got 
```
d>victoria</td><td class=status-running>Running</td><td>k0s-color-worker-1</td></tr><tr><td>vmks-k
ube-state-metrics-5987f4b4d-2hxfs</td><td>victoria</td><td class=status-running>Running</td><td>k0s
-color-worker-1</td></tr><tr><td>vmks-prometheus-node-exporter-nw66n</td><td>victoria</td><td class
=status-running>Running</td><td>k0s-color-worker-1</td></tr><tr><td>vmks-victoria-metrics-operator-
8448f486c9-bsw7v</td><td>victoria</td><td class=status-running>Running</td><td>k0s-color-worker-1</
td></tr><tr><td>vmsingle-vmks-victoria-metrics-k8s-stack-85cdb84cb5-x45f6</td><td>victoria</td><td
class=status-running>Running</td><td>k0s-color-worker-1</td></tr><tr><td>vmalertmanager-vmks-victor
ia-metrics-k8s-stack-0</td><td>victoria</td><td class=status-running>Running</td><td>k0s-color-work
er-2</td></tr><tr><td>vmks-grafana-58f78b886c-cwqkt</td><td>victoria</td><td class=status-running>R
unning</td><td>k0s-color-worker-2</td></tr><tr><td>vmks-prometheus-node-exporter-n4567</td><td>vict
oria</td><td class=status-running>Running</td><td>k0s-color-worker-2</td></tr></tbody></table></div
></article></main><footer class=site-footer><p>&copy; 2025 K8s Dashboard</p></footer></div></body><
/html>* Connection #0 to host cilium-gateway-k8s-dashboard-http-gateway.prod.svc.cluster.local left
 intact
pod "curl" deleted
```

I try with HTTPS solution
```
export KUBECONFIG=./k0s-color-cluster.config && kubectl run -it --rm -n prod curl-ssl --image=curlimages/curl --restart=Never -- curl -v -k https://cilium-gateway-k8s-dashboard-gateway.prod.svc.cluster.local:443
```

I got 
```
* Host cilium-gateway-k8s-dashboard-gateway.prod.svc.cluster.local:443 was resolved.
* IPv6: (none)
* IPv4: 10.97.130.7
*   Trying 10.97.130.7:443...
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* Recv failure: Connection reset by peer
* TLS connect error: error:00000000:lib(0)::reason(0)
* OpenSSL SSL_connect: Connection reset by peer in connection to cilium-gateway-k8s-dashboard-gatew
ay.prod.svc.cluster.local:443
* closing connection #0
curl: (35) Recv failure: Connection reset by peer
pod "curl-ssl" deleted
pod prod/curl-ssl terminated (Error)

```

Cilium Logs
```
export KUBECONFIG=./k0s-color-cluster.config && kubectl logs -n kube-system -l k8s-app=cilium --tail 50 | grep -i gateway

time="2025-05-18T13:39:01.157318371Z" level=warning msg="service not found" k8sNamespace=prod k8sSv
cName=cilium-gateway-k8s-dashboard-gateway obj="10.111.74.175:443/ANY" subsys=k8s-watcher
time="2025-05-18T13:39:01.157409972Z" level=warning msg="service not found" k8sNamespace=prod k8sSv
cName=cilium-gateway-k8s-dashboard-gateway obj="89.xxx.xxx.138:32547/ANY" subsys=k8s-watcher
time="2025-05-18T13:39:01.157423087Z" level=warning msg="service not found" k8sNamespace=prod k8sSv
cName=cilium-gateway-k8s-dashboard-gateway obj="0.0.0.0:32547/ANY" subsys=k8s-watcher
time="2025-05-18T13:32:01.833214475Z" level=info msg="Adding new proxy port rules for prod/cilium-g
ateway-k8s-dashboard-http-gateway/listener:14320" id=prod/cilium-gateway-k8s-dashboard-http-gateway
/listener subsys=proxy
time="2025-05-18T13:39:01.153426953Z" level=warning msg="service not found" k8sNamespace=prod k8sSv
cName=cilium-gateway-k8s-dashboard-gateway obj="10.111.74.175:443/ANY" subsys=k8s-watcher
time="2025-05-18T13:39:01.153520146Z" level=warning msg="service not found" k8sNamespace=prod k8sSv
cName=cilium-gateway-k8s-dashboard-gateway obj="89.xxx.xx.140:32547/ANY" subsys=k8s-watcher
time="2025-05-18T13:39:01.153547518Z" level=warning msg="service not found" k8sNamespace=prod k8sSv
cName=cilium-gateway-k8s-dashboard-gateway obj="0.0.0.0:32547/ANY" subsys=k8s-watcher
```

Final try access from public internet

```curl -v -k https://89.xxx.xx.138:32547
*   Trying 89.xxx.138:32547...
* connect to 89.xxx.138 port 32547 from 192.168.102.237 port 51195 failed: Connection refused
* Failed to connect to 89.xxx.138 port 32547 after 197 ms: Couldn't connect to server
* Closing connection
curl: (7) Failed to connect to 89.xxx.138 port 32547 after 197 ms: Couldn't connect to server
```

### How can we reproduce the issue?

1. Install cilium with cli

# Get Cilium CLI

```bash
CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
CLI_ARCH=amd64
if [ "$(uname -m)" = "arm64" ]; then CLI_ARCH=arm64; fi
curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-darwin-${CLI_ARCH}.tar.gz{,.sha256sum}
shasum -a 256 -c cilium-darwin-${CLI_ARCH}.tar.gz.sha256sum
sudo tar xzvfC cilium-darwin-${CLI_ARCH}.tar.gz /usr/local/bin
rm cilium-darwin-${CLI_ARCH}.tar.gz{,.sha256sum}
```

# Install Cilium

```bash
cilium install --version 1.17.3 --namespace kube-system \
  --set gatewayAPI.enabled=true \
  --set hubble.enabled=true \
  --set hubble.relay.enabled=true \
  --set hubble.ui.enabled=true \
  --set kubeProxyReplacement=true
```

# Install Gateway API

```bash
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml
```
2. Install the Nodeport CRD

```yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.3
  name: ciliumgatewayclassconfigs.cilium.io
spec:
  group: cilium.io
  names:
    categories:
    - cilium
    kind: CiliumGatewayClassConfig
    listKind: CiliumGatewayClassConfigList
    plural: ciliumgatewayclassconfigs
    shortNames:
    - cgcc
    singular: ciliumgatewayclassconfig
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=="Accepted")].status
      name: Accepted
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .spec.description
      name: Description
      priority: 1
      type: string
    name: v2alpha1
    schema:
      openAPIV3Schema:
        description: |-
          CiliumGatewayClassConfig is a Kubernetes third-party resource which
          is used to configure Gateways owned by GatewayClass.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: Spec is a human-readable of a GatewayClass configuration.
            properties:
              description:
                description: Description helps describe a GatewayClass configuration
                  with more details.
                maxLength: 64
                type: string
              service:
                description: |-
                  Service specifies the configuration for the generated Service.
                  Note that not all fields from upstream Service.Spec are supported
                properties:
                  allocateLoadBalancerNodePorts:
                    description: Sets the Service.Spec.AllocateLoadBalancerNodePorts
                      in generated Service objects to the given value.
                    type: boolean
                  externalTrafficPolicy:
                    default: Cluster
                    description: Sets the Service.Spec.ExternalTrafficPolicy in generated
                      Service objects to the given value.
                    type: string
                  ipFamilies:
                    description: Sets the Service.Spec.IPFamilies in generated Service
                      objects to the given value.
                    items:
                      description: |-
                        IPFamily represents the IP Family (IPv4 or IPv6). This type is used
                        to express the family of an IP expressed by a type (e.g. service.spec.ipFamilies).
                      type: string
                    type: array
                    x-kubernetes-list-type: atomic
                  ipFamilyPolicy:
                    description: Sets the Service.Spec.IPFamilyPolicy in generated
                      Service objects to the given value.
                    type: string
                  loadBalancerClass:
                    description: Sets the Service.Spec.LoadBalancerClass in generated
                      Service objects to the given value.
                    type: string
                  loadBalancerSourceRanges:
                    description: Sets the Service.Spec.LoadBalancerSourceRanges in
                      generated Service objects to the given value.
                    items:
                      type: string
                    type: array
                    x-kubernetes-list-type: atomic
                  loadBalancerSourceRangesPolicy:
                    default: Allow
                    description: |-
                      LoadBalancerSourceRangesPolicy defines the policy for the LoadBalancerSourceRanges if the incoming traffic
                      is allowed or denied.
                    enum:
                    - Allow
                    - Deny
                    type: string
                  trafficDistribution:
                    description: Sets the Service.Spec.TrafficDistribution in generated
                      Service objects to the given value.
                    type: string
                  type:
                    default: LoadBalancer
                    description: Sets the Service.Spec.Type in generated Service objects
                      to the given value.
                    type: string
                type: object
            type: object
          status:
            description: Status is the status of the policy.
            properties:
              conditions:
                description: Current service state
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
            type: object
        required:
        - metadata
        type: object
    served: true
    storage: true
    subresources:
      status: {}
```

### Application GatewayAPI+HTTPRoute yaml

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium-nodeport
spec:
  controllerName: io.cilium/gateway-controller
  description: Cilium GatewayClass with NodePort service type
  parametersRef:
    group: cilium.io
    kind: CiliumGatewayClassConfig
    name: cilium-nodeport-config
    namespace: prod
---
apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: cilium-nodeport-config
  namespace: prod
spec:
  service:
    type: NodePort 
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: k8s-dashboard-gateway
  namespace: prod
  annotations:
    cert-manager.io/issuer: buypass-issuer
spec:
  gatewayClassName: cilium-nodeport
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    hostname: "k8s.edoo.dev"
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      certificateRefs:
      - kind: Secret
        name: k8s-edoo-dev-tls 
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: k8s-dashboard-route
  namespace: prod
spec:
  parentRefs:
  - name: k8s-dashboard-gateway
  hostnames:
  - "k8s.edoo.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: hugo-site
      port: 80 
```

### Cilium Version

❯ cilium version
cilium-cli: v0.18.3 compiled with go1.24.2 on darwin/amd64
cilium image (default): v1.17.2
cilium image (stable): v1.17.4
cilium image (running): 1.17.3

### Kernel Version

Linux k0s-color-worker-1 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.37-1 (2023-07-03) x86_64 GNU/Linux

### Kubernetes Version

v1.32.3

### Sysdump

[cilium-sysdump-20250518-215216.zip](https://github.com/user-attachments/files/20273164/cilium-sysdump-20250518-215216.zip)

### Relevant log output

```shell
❯ cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    OK
 \__/¯¯\__/    Hubble Relay:       OK
    \__/       ClusterMesh:        disabled

DaemonSet              cilium                   Desired: 2, Ready: 2/2, Available: 2/2
DaemonSet              cilium-envoy             Desired: 2, Ready: 2/2, Available: 2/2
Deployment             cilium-operator          Desired: 1, Ready: 1/1, Available: 1/1
Deployment             hubble-relay             Desired: 1, Ready: 1/1, Available: 1/1
Deployment             hubble-ui                Desired: 1, Ready: 1/1, Available: 1/1
Containers:            cilium                   Running: 2
                       cilium-envoy             Running: 2
                       cilium-operator          Running: 1
                       clustermesh-apiserver
                       hubble-relay             Running: 1
                       hubble-ui                Running: 1
Cluster Pods:          45/50 managed by Cilium
Helm chart version:    1.17.3
Image versions         cilium             quay.io/cilium/cilium:v1.17.3@sha256:1782794aeac951af139315c10eff34050aa7579c12827ee9ec376bb719b82873: 2
                       cilium-envoy       quay.io/cilium/cilium-envoy:v1.32.5-1744305768-f9ddca7dcd91f7ca25a505560e655c47d3dec2cf@sha256:a01cadf7974409b5c5c92ace3d6afa298408468ca24cab1cb413c04f89d3d1f9: 2
                       cilium-operator    quay.io/cilium/operator-generic:v1.17.3@sha256:8bd38d0e97a955b2d725929d60df09d712fb62b60b930551a29abac2dd92e597: 1
                       hubble-relay       quay.io/cilium/hubble-relay:v1.17.3@sha256:f8674b5139111ac828a8818da7f2d344b4a5bfbaeb122c5dc9abed3e74000c55: 1
                       hubble-ui          quay.io/cilium/hubble-ui-backend:v0.13.2@sha256:a034b7e98e6ea796ed26df8f4e71f83fc16465a19d166eff67a03b822c0bfa15: 1
                       hubble-ui          quay.io/cilium/hubble-ui:v0.13.2@sha256:9e37c1296b802830834cc87342a9182ccbb71ffebb711971e849221bd9d59392: 1
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
