### ISSUE TITLE
is it possible to enable encryption for part of the nodes?

### ISSUE THREAD

**Issue by kohn** [cilium/cilium#39655]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.4 and lower than v1.18.0

### What happened?

I try to use enable encryption for part of cluster with:
```
apiVersion: cilium.io/v2
kind: CiliumNodeConfig
metadata:
  namespace: kube-system
  name: enable-wiregurad-for-system
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: node1
  defaults:
    enable-wireguard: "true"
```
Then after cilium daemonset restarted, I can see the node1 has cilium_wg0 and cilium-dbg shows the encryption for this node is enabled. But inside pod of node1, I cant connect to any of other pods.

Nettrace shows the outgoing package is dropped:
[1815596.092268] [kfree_skb           ] UDP: node1:51827 -> apiserver:8472 *reason: 0, __init_scratch_end+0x2b886a47* *packet is dropped by kernel*

My question is, is it by design? Why is the packet dropped?

### How can we reproduce the issue?

1. Install cililum
2. apply the ciliumnodeconfig above
3. inside pod in node1, curl k8s-apiserver svc(e.g. 172.20.0.1)

### Cilium Version

1.17.2

### Kernel Version

5.15.0-117-generic #127-Ubuntu SMP

### Kubernetes Version

1.30

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
