### ISSUE TITLE
Pod networking impaired on AL2023 nodes in public subnets on v1.15

### ISSUE THREAD

**Issue by mselim00** [cilium/cilium#39684]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.15.17 and lower than v1.16.0

### What happened?

Pods fail simple networking tasks like curling google.com when using an AL2023 node in a public subnet.

A user of the amazon EKS AMI indicated they were impacted by this issue, but I'm not familiar enough to diagnose myself. We use the [Amazon VPC CNI](https://github.com/aws/amazon-vpc-cni-k8s) for our applications and testing.

### How can we reproduce the issue?

Slight modification of set up guide at: https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/ 
1. Create a cluster and node groups
```
cat <<EOF >eks-config.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cilium-on-al2023
  region: us-west-2

managedNodeGroups:
- name: al2023-public
  desiredCapacity: 1
  amiFamily: AmazonLinux2023
  taints:
   - key: "node.cilium.io/agent-not-ready"
     value: "true"
     effect: "NoExecute"
- name: al2023-private
  desiredCapacity: 1
  amiFamily: AmazonLinux2023
  privateNetworking: true
  taints:
   - key: "node.cilium.io/agent-not-ready"
     value: "true"
     effect: "NoExecute"
- name: al2-public
  desiredCapacity: 1
  amiFamily: AmazonLinux2
  taints:
   - key: "node.cilium.io/agent-not-ready"
     value: "true"
     effect: "NoExecute"
- name: al2-private
  desiredCapacity: 1
  amiFamily: AmazonLinux2
  privateNetworking: true
  taints:
   - key: "node.cilium.io/agent-not-ready"
     value: "true"
     effect: "NoExecute"
EOF
```

2. Install v0.18.3 of the cilium CLI (latest stable at time of writing)
```
CILIUM_CLI_VERSION=v0.18.3
CLI_ARCH=amd64
if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
```

3. Install v1.15.17 of the CNI, latest in the 1.15 branch at time of writing 
```
cilium install --version 1.15.17
cilium status --wait 
```

4. Create a job to curl google on each node
```
OPERATING_SYSTEMS=("al2023" "al2")
OPTIONS=("public" "private")
for OS in ${OPERATING_SYSTEMS[@]}; do
  for OPTION in ${OPTIONS[@]}; do
    echo $OS $OPTION
    NODEGROUP_NAME="$OS-$OPTION"
    cat <<EOF >test-$NODEGROUP_NAME.yaml 
apiVersion: batch/v1
kind: Job
metadata:
  name: curl-external-$NODEGROUP_NAME
spec:
 template:
   spec:
      affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
               nodeSelectorTerms:
                - matchExpressions:
                   - key: alpha.eksctl.io/nodegroup-name
                     operator: In
                     values:
                     - $NODEGROUP_NAME
      containers:
        - name: curl-external
          image: public.ecr.aws/amazonlinux/amazonlinux:2023
          command: ['curl', 'google.com']
      restartPolicy: Never
EOF
    kubectl create -f test-$NODEGROUP_NAME.yaml 
  done
done 
```

5. Follow the jobs to completion
```
kubectl get jobs -w
```

You should see that all jobs except the al2023 public one succeed. The al2023 public one should timeout and give a failed to connect error.

### Cilium Version

cilium-cli: v0.18.3 compiled with go1.24.2 on linux/amd64
cilium image (default): v1.17.2
cilium image (stable): v1.17.4
cilium image (running): 1.15.17

### Kernel Version

Linux ip-192-168-36-134.us-west-2.compute.internal 6.1.134-152.225.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Wed May  7 09:10:59 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.32.3-eks-4096722

### Regression

Not a regression - it does not appear the 1.15 branch ever supported this configuration (the initial commit predates [EKS AL2023 support](https://aws.amazon.com/blogs/containers/amazon-eks-optimized-amazon-linux-2023-amis-now-available/))

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
