### ISSUE TITLE
Helm chart - cni.exclusive false not being honored

### ISSUE THREAD

**Issue by jstewart612** [cilium/cilium#39695]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.4 and lower than v1.18.0

### What happened?

Cilium and Istio CNI are spam updating 05-cilium.conf despite cni-exclusive being set false:

[jstewart@crimfw13 ~ (⎈|nuc:N/A)]$ kubectl get cm -n kube-system cilium-config -o yaml | grep cni-exclusive
  cni-exclusive: "false"
[jstewart@crimfw13 ~ (⎈|nuc:N/A)]$

### How can we reproduce the issue?

Installed cilium 1.17.4 helm chart with following Helm values:

```
    bpf:
      hostLegacyRouting: false
      masquerade: true
    cluster:
      name: nuc
      id: 2
    clustermesh:
      apiserver:
        metrics:
          serviceMonitor:
            enabled: true
        service:
          type: LoadBalancer
        tls:
          authMode: cluster
          server:
            extraDnsNames:
              - "*.home.thecrimsontint.com"
      config:
        enabled: true
        domain: home.thecrimsontint.com
        clusters:
          - name: turingpi
            address: cilium-turingpi.home.thecrimsontint.com
            port: 2379
          - name: nuc
            address: cilium-nuc.home.thecrimsontint.com
            port: 2379
      useAPIServer: true
    cni:
      customConf: false
      exclusive: false
      uninstall: false
    envoy:
      prometheus:
        serviceMonitor:
          enabled: true
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList:
        - 10.51.0.0/16
    hubble:
      enabled: true
      metrics:
        enableOpenMetrics: true
        enabled:
          - dns
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
        serviceMonitor:
          enabled: true
      relay:
        enabled: true
        prometheus:
          serviceMonitor:
            enabled: true
      ui:
        enabled: true
    k8sServiceHost: 10.251.0.100
    k8sServicePort: 6443
    kubeProxyReplacement: true
    l2announcements:
      enabled: true
    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      replicas: 1
      unmanagedPodWatcher:
        restart: true
    policyEnforcementMode: default
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    routingMode: tunnel
    socketLB:
      hostNamespaceOnly: true
    tunnelPort: 8473
    tunnelProtocol: vxlan
```

Install istio-cni 1.26.0 helm chart with the following options:

```
        global:
          logAsJson: true
        profile: ambient
```

Watch the istio-cni pod logs and the cilium DS pod logs constantly spam update the 05-cilium.conf file

### Cilium Version

1.17.4

### Kernel Version

5.14.0-503.40.1.el9_5.x86_64

### Kubernetes Version

k3s 1.33.0

### Relevant log output

```shell
cilium-cw2cd cilium-agent time="2025-05-23T23:14:38.902925723Z" level=info msg="Generating CNI configuration file with mode none" subsys=cni-config                cilium-cw2cd cilium-agent time="2025-05-23T23:14:38.90314509Z" level=info msg="Activity in /host/etc/cni/net.d/, re-generating CNI configuration" subsys=cni-configcilium-cw2cd cilium-agent time="2025-05-23T23:14:38.90317053Z" level=info msg="Activity in /host/etc/cni/net.d/, re-generating CNI configuration" subsys=cni-configcilium-cw2cd cilium-agent time="2025-05-23T23:14:38.903185466Z" level=info msg="Activity in /host/etc/cni/net.d/, re-generating CNI configuration" subsys=cni-config                                                                                                                                                                  cilium-cw2cd cilium-agent time="2025-05-23T23:14:38.903211302Z" level=info msg="Activity in /host/etc/cni/net.d/, re-generating CNI configuration" subsys=cni-config                                                                                                                                                                  cilium-cw2cd cilium-agent time="2025-05-23T23:14:38.904437522Z" level=info msg="Wrote CNI configuration file to /host/etc/cni/net.d/05-cilium.conflist" subsys=cni-config                                                                                                                                                             cilium-cw2cd cilium-agent time="2025-05-23T23:14:38.904494104Z" level=info msg="Generating CNI configuration file with mode none" subsys=cni-config                cilium-cw2cd cilium-agent time="2025-05-23T23:14:38.904438079Z" level=info msg="Activity in /host/etc/cni/net.d/, re-generating CNI configuration" subsys=cni-config                                                                                                                                                                  cilium-cw2cd cilium-agent time="2025-05-23T23:14:38.904528807Z" level=info msg="Activity in /host/etc/cni/net.d/, re-generating CNI configuration" subsys=cni-config                                                                                                                                                                  cilium-cw2cd cilium-agent time="2025-05-23T23:14:38.904576456Z" level=info msg="Generating CNI configuration file with mode none" subsys=cni-config                cilium-br5x6 cilium-agent time="2025-05-23T23:14:38.989022871Z" level=info msg="Activity in /host/etc/cni/net.d/, re-generating CNI configuration" subsys=cni-config                                                                                                                                                                  cilium-br5x6 cilium-agent time="2025-05-23T23:14:38.989049326Z" level=info msg="Activity in /host/etc/cni/net.d/, re-generating CNI configuration" subsys=cni-config                                                                                                                                                                  cilium-br5x6 cilium-agent time="2025-05-23T23:14:38.989054973Z" level=info msg="Activity in /host/etc/cni/net.d/, re-generating CNI configuration" subsys=cni-config                                                                                                                                                                  cilium-br5x6 cilium-agent time="2025-05-23T23:14:38.989057817Z" level=info msg="Activity in /host/etc/cni/net.d/, re-generating CNI configuration" subsys=cni-config                                                                                                                                                                  cilium-br5x6 cilium-agent time="2025-05-23T23:14:38.989063826Z" level=info msg="Activity in /host/etc/cni/net.d/, re-generating CNI configuration" subsys=cni-config                                                                                                                                                                  cilium-br5x6 cilium-agent time="2025-05-23T23:14:38.989078109Z" level=info msg="Generating CNI configuration file with mode none" subsys=cni-config                cilium-br5x6 cilium-agent time="2025-05-23T23:14:38.98923732Z" level=info msg="Activity in /host/etc/cni/net.d/, re-generating CNI configuration" subsys=cni-configcilium-br5x6 cilium-agent time="2025-05-23T23:14:38.98926659Z" level=info msg="Activity in /host/etc/cni/net.d/, re-generating CNI configuration" subsys=cni-configcilium-br5x6 cilium-agent time="2025-05-23T23:14:38.989290385Z" level=info msg="Activity in /host/etc/cni/net.d/, re-generating CNI configuration" subsys=cni-config                                                                                                                                                                  cilium-br5x6 cilium-agent time="2025-05-23T23:14:38.98929603Z" level=info msg="Activity in /host/etc/cni/net.d/, re-generating CNI configuration" subsys=cni-configcilium-br5x6 cilium-agent time="2025-05-23T23:14:38.994334307Z" level=info msg="Wrote CNI configuration file to /host/etc/cni/net.d/05-cilium.conflist" subsys=cni-config
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
