### ISSUE TITLE
MTU issue for large UDP packets with native routing and DSR

### ISSUE THREAD

**Issue by DaruZero** [cilium/cilium#39690]
### Is there an existing issue for this?

- [x] I have searched the existing issues: this is very similar to #32601 

### Version

equal or higher than v1.17.4 and lower than v1.18.0

### What happened?

The situation is almost the same as the one in the other issue: I have an environment with native routing and DSR, with a UDP (SIP) service with 3 endpoints running on 3 different nodes. There are some large (>2000) UDP packets being sent from outside the cluster to one of the endpoint, which get correctly fragmented following the ICMP instructions sent by path MTU discovery. Luckily pmtu accounts for the 8 bytes header added for DSR, but it does not for any other possible header (like VLAN tags). This causes the packet to possibly be higher than the default network MTU and being dropped.
I am not really sure which entity is dropping the packets, as I don't see them reaching Cilium. I've read somewhere that some routers drop packets with unknown options headers when they receive too many of them, so that might be a problem.
I also tried to set Cilium's MTU to 1450, but the problem perists.

Things seems to work when client and k8s cluster are on the same network, but if they are on two different VLANs (which can of course reach each other) then the packet is that bit larger that gets dropped, or at least this is my assumption

### How can we reproduce the issue?

1. Install Cilium with the following values on a multi-node k3s cluster
   ```yaml
   k8sServiceHost: k8s.kubelab.alea.lab
   k8sServicePort: 6443
   kubeProxyReplacement: true
   ipv4NativeRoutingCIDR: "10.42.0.0/16"
   ipam:
     mode: kubernetes
     operator:
       clusterPoolIPv4PodCIDRList: "10.42.0.0/16"
   bpf:
     masquerade: false
   nodePort:
     enabled: true
   externalIPs:
     enabled: true
   l7Proxy: false
   
   hubble:
     relay:
       enabled: true
     ui:
       enabled: true
   
   l2announcements:
     enabled: true
     leaseDuration: 3s
     leaseRenewDeadline: 1.5s
     leaseRetryPeriod: 1s
   k8sClientRateLimit:
     qps: 170
     burst: 200
   
   healthChecking: true
   endpointHealthChecking:
     enabled: true
   
   tunnelProtocol: ""
   routingMode: native
   loadBalancer:
     mode: dsr
     dsrDispatch: opt
   socketLB:
     enabled: true
     hostNamespaceOnly: true
   
   autoDirectNodeRoutes: true
   
   MTU: 0
   pmtuDiscovery:
     enabled: true

   ```
2. Create a Cilium L2 announcement policy and LoadBalancer IP Pool
3. Deploy a UDP server with 3 replicas, and expose it with a LoadBalancer service
4. Send a UDP packet to the Loadbalancer IP with a size higher than 1500

### Cilium Version

cilium-cli: v0.18.3 compiled with go1.24.2 on linux/amd64
cilium image (default): v1.17.2
cilium image (stable): v1.17.3
cilium image (running): 1.17.3

### Kernel Version

Linux kubelab-w07 5.15.0-307.178.5.el8uek.x86_64 #2 SMP Wed Mar 19 13:00:52 PDT 2025 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.32.3+k3s1

### Sysdump

_file is too large_

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
