### ISSUE TITLE
 Documentation Request: Add `egressDeny` Example in CiliumNetworkPolicy

### ISSUE THREAD

**Issue by anishbista60** [cilium/cilium#39697]
Hi Cilium team,

I noticed that while the `egressDeny` field can be used in `CiliumNetworkPolicy`, it is not documented in the official Cilium documentation.

For example, the documentation provides the following policy to allow egress traffic from pods with the label `role=frontend` to those with `role=backend`:
[https://docs.cilium.io/en/stable/security/policy/language/#simple-egress-allow](https://docs.cilium.io/en/stable/security/policy/language/#simple-egress-allow)

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-egress-example"
spec:
  endpointSelector:
    matchLabels:
      role: frontend
  egress:
    - toEndpoints:
        - matchLabels:
            role: backend
```

However, when I want to **restrict** egress traffic from `frontend` to `backend`, I learned that I could use the `egressDeny` field as shown below:

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "deny-egress-example"
spec:
  endpointSelector:
    matchLabels:
      role: frontend
  egressDeny:
    - toEndpoints:
        - matchLabels:
            role: backend
```

This functionality is not covered in the documentation, and the absence of any mention of `egressDeny` makes it difficult for users to discover and confidently use this feature.

**Request:**
Please consider adding an example and explanation for `egressDeny` in the [policy language documentation](https://docs.cilium.io/en/stable/security/policy/language/), similar to the existing `egress` examples. This would help improve clarity around deny-based rules.

Thanks for all the great work on Cilium!
