### ISSUE TITLE
Cilium in Overlay mode, IPSEC and Kube-proxy free - Not encrypting traffic

### ISSUE THREAD

**Issue by it-rubenrebelo** [cilium/cilium#39752]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.4 and lower than v1.18.0

### What happened?

Cilium v1.17.4 in overlay mode, kube-proxy free and ipsec is not encrypting traffic though cilium-dbg encrypt status says everything is ok.

Cilium sysdump in attachment.

[cilium-sysdump-20250527-171016.zip](https://github.com/user-attachments/files/20462879/cilium-sysdump-20250527-171016.zip)

My cilium values:
```yaml
authentication:
  mutual:
    spire:
      enabled: false
      install:
        agent:
          tolerations:
          - effect: NoExecute
            key: node.cilium.io/agent-not-ready
            operator: Exists
          - effect: NoExecute
            key: node.kubernetes.io/not-ready
            operator: Exists
          - effect: NoExecute
            key: node.kubernetes.io/unreachable
            operator: Exists
        enabled: false
        server:
          tolerations:
          - effect: NoExecute
            key: node.cilium.io/agent-not-ready
            operator: Exists
          - effect: NoExecute
            key: node.kubernetes.io/not-ready
            operator: Exists
          - effect: NoExecute
            key: node.kubernetes.io/unreachable
            operator: Exists
cluster:
  name: eks-cluster-main
cni:
  configMap: cni-configuration
  customConf: true
  install: true
devices: eth+
egressMasqueradeInterfaces: eth+
enableIPv4Masquerade: true
encryption:
  enabled: true
  ipsec:
    encryptedOverlay: false
    interface: eth0
extraArgs:
- ""
hubble:
  enabled: true
  metrics:
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - icmp
  relay:
    enabled: true
    tolerations:
    - effect: NoExecute
      key: node.cilium.io/agent-not-ready
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
  ui:
    enabled: true
    tolerations:
    - effect: NoExecute
      key: node.cilium.io/agent-not-ready
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4MaskSize: 22
    clusterPoolIPv4PodCIDRList:
    - 100.65.0.0/22
    - 100.65.4.0/22
k8sServiceHost: XXXXXX.gr7.eu-central-1.eks.amazonaws.com
k8sServicePort: 443
kubeProxyReplacement: true
operator:
  extraArgs:
  - --pod-restart-selector=
serviceAccounts:
  operator:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::554575895663:role/eks-cluster-main-cilium
    name: cilium-operator
tolerations:
- effect: NoExecute
  key: node.cilium.io/agent-not-ready
  operator: Exists
- effect: NoExecute
  key: node.kubernetes.io/not-ready
  operator: Exists
- effect: NoExecute
  key: node.kubernetes.io/unreachable
  operator: Exists
tunnelPort: 8472
tunnelProtocol: vxlan
```

### How can we reproduce the issue?

I'm installing cilium with helm in my EKS, installing version v1.17.4 in kube-system namespace. Using the following customconfigmap I'm telling Cilium to connect to my pod
```
subnet{
  "cniVersion":"0.3.1",
  "name":"cilium",
  "plugins": [
    {
      "cniVersion":"0.3.1",
      "type":"cilium-cni",
      "eni": {
        "first-interface-index": 1,
        "subnet-tags":{
          "Usage":"pods"
        }
      }
    }
  ]
}
```

These are the values I'm using:
```yaml
authentication:
  mutual:
    spire:
      enabled: false
      install:
        agent:
          tolerations:
          - effect: NoExecute
            key: node.cilium.io/agent-not-ready
            operator: Exists
          - effect: NoExecute
            key: node.kubernetes.io/not-ready
            operator: Exists
          - effect: NoExecute
            key: node.kubernetes.io/unreachable
            operator: Exists
        enabled: false
        server:
          tolerations:
          - effect: NoExecute
            key: node.cilium.io/agent-not-ready
            operator: Exists
          - effect: NoExecute
            key: node.kubernetes.io/not-ready
            operator: Exists
          - effect: NoExecute
            key: node.kubernetes.io/unreachable
            operator: Exists
cluster:
  name: eks-cluster-main
cni:
  configMap: cni-configuration
  customConf: true
  install: true
devices: eth+
egressMasqueradeInterfaces: eth+
enableIPv4Masquerade: true
encryption:
  enabled: true
  ipsec:
    encryptedOverlay: false
    interface: eth0
extraArgs:
- ""
hubble:
  enabled: true
  metrics:
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - icmp
  relay:
    enabled: true
    tolerations:
    - effect: NoExecute
      key: node.cilium.io/agent-not-ready
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
  ui:
    enabled: true
    tolerations:
    - effect: NoExecute
      key: node.cilium.io/agent-not-ready
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4MaskSize: 22
    clusterPoolIPv4PodCIDRList:
    - 100.65.0.0/22
    - 100.65.4.0/22
k8sServiceHost: 3229C359AF221258B2CC51B0933B0F5A.gr7.eu-central-1.eks.amazonaws.com
k8sServicePort: 443
kubeProxyReplacement: true
operator:
  extraArgs:
  - --pod-restart-selector=
serviceAccounts:
  operator:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::554575895663:role/eks-cluster-main-cilium
    name: cilium-operator
tolerations:
- effect: NoExecute
  key: node.cilium.io/agent-not-ready
  operator: Exists
- effect: NoExecute
  key: node.kubernetes.io/not-ready
  operator: Exists
- effect: NoExecute
  key: node.kubernetes.io/unreachable
  operator: Exists
tunnelPort: 8472
tunnelProtocol: vxlan
```

### Cilium Version

v1.17.4

### Kernel Version

bottlerocket OS in EKS

### Kubernetes Version

1.29

### Sysdump

[cilium-sysdump-20250527-171016.zip](https://github.com/user-attachments/files/20463072/cilium-sysdump-20250527-171016.zip)

### Relevant log output

```shell

```

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
