### ISSUE TITLE
Memory reported is incorrect

### ISSUE THREAD

**Issue by JulesClaussen** [cilium/cilium#39775]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.4 and lower than v1.18.0

### What happened?

The reported memory appears to be incorrect. In the given example, the memory reported is around 570 MiB, while the one from the dump is 24 MB. Sometimes the memory reported goes up to 2 or 4 GB.
I'm not sure why, but I can't attach my heap profile. See the screenshot for more details.

<img width="1467" alt="Image" src="https://github.com/user-attachments/assets/4a742e55-dc4d-4de4-93d1-99929096ae6c" />

It is actually quite weird. Some pods start with a really small memory showed (like 80MB), other with 1, 2 or even 4Gb. 
Unfortunately, I cannot start the debug tool, as I have the following error
`Failed to create debug directory Get "http://localhost:6060/debug/pprof/trace?seconds=30": dial tcp [::1]:6060: connect: connection refused`

### How can we reproduce the issue?

1. Start an EKS Cluster with VPC CNI (coredns, and kubeproxy). Disable aws-vpc CNI network policies.
2. Install Cilium with the following values:
```
      cni:
        chainingMode: aws-cni
        exclusive: false

      enableIPv4Masquerade: false
      routingMode: native

      endpointRoutes:
        enabled: true

      envoy:
        enabled: false

      hubble:
        enabled: false

      endpointHealthChecking:
        enabled: false

      healthChecking: false

      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"

      operator:
        resources:
          requests:
            cpu: "20m"
            memory: "100Mi"

      bpf:
        distributedLRU:
          enabled: true
        mapDynamicSizeRatio: 0.08
        masquerade: true
        monitorInterval: "15s"

      bpfClockProbe: true
```

### Cilium Version

1.17.4

### Kernel Version

Running on Bottlerocket 1.39.1
`Linux ip-10-12-114-134.eu-west-1.compute.internal 6.1.134 #1 SMP PREEMPT_DYNAMIC Thu May  1 19:24:58 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

```
Client Version: v1.33.1
Kustomize Version: v5.6.0
Server Version: v1.32.3-eks-bcf3d70
```

### Sysdump

[cilium-sysdump-20250528-184600.zip](https://github.com/user-attachments/files/20492065/cilium-sysdump-20250528-184600.zip)

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
