### ISSUE TITLE
LoadBalancer does not listen external IP when `routingMode: tunnel`

### ISSUE THREAD

**Issue by kolserdav** [cilium/cilium#39804]
I connect nodes from different networks using WireGuard. Thanks to this configuration 
```yaml
k8sServiceHost: 10.8.0.1
k8sServicePort: 6443

routingMode: tunnel
autoDirectNodeRoutes: false
#ipv4NativeRoutingCIDR: 10.3.0.0/16
kubeProxyReplacement: true
kubeProxyReplacementConfiguration:
  enabled: true
  healthzBindAddr: "0.0.0.0:10256"

ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDRList: ["10.3.0.0/16"] 
    clusterPoolIPv4MaskSize: 22

enableIPv4Masquerade: true
bpf:
  masquerade: true
```
 I managed to achieve connectivity of pods between each other. However, now the problem is that LoadBalancer is not accessible via external IP although `externalIPs` is specified correctly.

I have not found ready-made configurations of setup `cilium`  for combining nodes from different networks into a cluster. Therefore, I am trying to build it myself using GPT, but I have encountered such a problem that I can no longer cope with it myself. I ask for help from the community.
