### ISSUE TITLE
Slack invite link request

### ISSUE THREAD

**Issue by rajali** [cilium/cilium#39810]
Hi,

I tried so sign-up [Cilium & eBPF Slack](https://slack.cilium.io/) to get some help on Cilium network policies and envoy config.

I  tried 

- "https://cilium.herokuapp.com/" but this does not work anymore.
- And signing up from [Cilium & eBPF Slack](https://slack.cilium.io/)

So far, no luck.

Please send through an invitation.

Thank you,

Ali

**Comment by sandipkumardey** [comment]
Hi @rajali, what exactly do you want here? Can you explain the issue in detail? If you need our official slack channel, here is the invite. [Here](cilium.slack.com).

**Comment by rajali** [comment]
thanks @sandipkumardey  for sharing the link. It is the same link I shared above.
This gives me this
```
It looks like there isn’t an account on Cilium & eBPF tied to this email address.
```

Alternatively, you can send an invite to email address please at rajali@live.com.au.

I am running Cilium deployed through helm chart v1.17.3 on an EKS cluster.

The issue I am facing is related to usage of "CiliumClusterwideEnvoyConfig" to setup corporate proxy cluster/listener and referring it under the "CiliunNetworkPolicy". Running a test pod in the namespace of the this CiliunNetworkPolicy trying to do a curl to external FQDN to see if the traffic is forwarded to the proxy setup in CiliumClusterwideEnvoyConfig or not. I also tried going the through the L7 proxy lab at Cilium labs which had a similar example of using a proxy server for internet traffic--but it didn't help to resolve my issue. the example used "CiliumEnvoyConfig" instead.

This is how I am referring the CiliumClusterwideEnvoyConfig under the CiliunNetworkPolicy.
```
- toFQDNs:
      - matchPattern: "acm-pca.*.amazonaws.com" 
     toPorts:
     - ports:
       - port: "443"
         protocol: TCP
      listener: 
        envoyConfig:
          kind: CiliumClusterwideEnvoyConfig
          name: "global-corporate-proxy" 
        name: "corporate-proxy-listener"
```

The traffic is denied when used as above and when the above listener is removed I can see that the traffic is allowed  while checking it using
```
kubectl -n kube-system exec -it <cilium-pod> -- cilium monitor --type=policy-verdict
```

The above shows logs as below, when listener is not added. As seen below it is above to resolve the IP address
```
Policy verdict log: flow 0x412aaf51 local EP ID 3824, remote ID 16777228, proto 6, egress, action allow, auth: disabled, match L3-L4,10.170.9.39:57748 -> 3.104.244.161:443 tcp SYN
```

let me know if there is any documentation around this similar setup.
