### ISSUE TITLE
endpoint regeneration deadlock after enabling kvstore

### ISSUE THREAD

**Issue by pasteley** [cilium/cilium#39846]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.4 and lower than v1.18.0

### What happened?

**Env**
- Cilium running on bare-metal
- Native routing, IPv6-only setup

**Problem description**

After enabling `kvstore` (in order to migrate from `identyAloctationMode = crd`), all endpoints across all nodes began regenerating but never completed. They appear to be stuck in `unconditionalLock`.

**Observed behavior**

Although the endpoints are present in `/var/run/cilium/state/` and `cilium identity list` returns the expected output, attempting to list endpoints results in the following errors:
```
/home/cilium# cilium bpf endpoint list
IP ADDRESS                            LOCAL ENDPOINT INFO
<NODE_IPV6_ADDRESS>  (localhost)
fc99::1:0                               (localhost)

/home/cilium# cilium endpoint list
Error: cannot get endpoint list: Cilium API client timeout exceeded

/home/cilium# cilium endpoint get 1164
Error: Cannot get endpoint 1164: Get "http://localhost/v1/endpoint/1164": context deadline exceeded
```

It reveals that all goroutins locking on the same RWMutex of the Endpoint struct on `0xc000cd1408`

<details>
  <summary>locks in gops stack</summary>

```
goroutine 560 [sync.RWMutex.RLock, 7 minutes]:
sync.runtime_SemacquireRWMutexR(0x10000c00398cc40?, 0xff?, 0x0?)
	/usr/local/go/src/runtime/sema.go:100 +0x25
sync.(*RWMutex).RLock(...)
	/usr/local/go/src/sync/rwmutex.go:72
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).rlockAlive(0xc000cd1408)
	/go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:32 +0x39
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).GetSecurityIdentity(0xc000cd1408)
	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:704 +0x37
github.com/cilium/cilium/pkg/auth.(*authMapGarbageCollector).cleanupEndpoints(0xc0020b2210, {0x0?, 0x0?})
	/go/src/github.com/cilium/cilium/pkg/auth/authmap_gc.go:430 +0x1c5
github.com/cilium/cilium/pkg/auth.(*authMapGarbageCollector).cleanup(0xc0020b2210, {0x55e7e98, 0xc000a2f320})
	/go/src/github.com/cilium/cilium/pkg/auth/authmap_gc.go:79 +0x5e
github.com/cilium/hive/job.(*jobTimer).start(0xc002019920, {0x55e7e98, 0xc000a2f320}, 0x0?, {0x55f1d20, 0xc002019680}, {{{0xc000f52760, 0x1, 0x1}}, 0xc001021630, ...})
	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/job/timer.go:191 +0x473
created by github.com/cilium/hive/job.(*group).Start.func1 in goroutine 1
	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/job/job.go:161 +0x174

goroutine 2101 [sync.Mutex.Lock, 11 minutes]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/sema.go:95 +0x25
sync.(*Mutex).lockSlow(0xc000cd1460)
	/usr/local/go/src/sync/mutex.go:173 +0x15d
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:92
sync.(*RWMutex).Lock(0x0?)
	/usr/local/go/src/sync/rwmutex.go:148 +0x31
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).lockAlive(0xc000cd1408)
	/go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:17 +0x2a
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).identityLabelsChanged(0xc000cd1408, {0x55e7ed0, 0xc003264ff0})
	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:2150 +0x48
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).runIdentityResolver.func1({0x55e7ed0?, 0xc003264ff0?})
	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:2133 +0x33
github.com/cilium/cilium/pkg/controller.(*controller).runController(0xc003267540, {{{0x4eba4bd, 0x10}}, {0x0, 0x0}, 0xc000d16f00, 0x0, 0x50f1e10, 0x45d964b800, 0x0, ...})
	/go/src/github.com/cilium/cilium/pkg/controller/controller.go:251 +0x8a
created by github.com/cilium/cilium/pkg/controller.(*Manager).createControllerLocked in goroutine 2092
	/go/src/github.com/cilium/cilium/pkg/controller/manager.go:115 +0x43d

goroutine 2770 [sync.Mutex.Lock, 9 minutes]:
sync.runtime_SemacquireMutex(0xc0001daa08?, 0xd0?, 0x0?)
	/usr/local/go/src/runtime/sema.go:95 +0x25
sync.(*Mutex).lockSlow(0xc000cd1460)
	/usr/local/go/src/sync/mutex.go:173 +0x15d
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:92
sync.(*RWMutex).Lock(0x50000c0035854c0?)
	/usr/local/go/src/sync/rwmutex.go:148 +0x31
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).lockAlive(0xc000cd1408)
	/go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:17 +0x2a
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).SetRegenerateStateIfAlive(0xc000cd1408, 0xc0015ddef0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:606 +0x25
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).RegenerateIfAlive(0xc000cd1408, 0xc0015ddef0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:704 +0x32
github.com/cilium/cilium/pkg/endpointmanager.(*endpointManager).RegenerateAllEndpoints.func1(0xc0011e3160?)
	/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:587 +0x25
created by github.com/cilium/cilium/pkg/endpointmanager.(*endpointManager).RegenerateAllEndpoints in goroutine 521
	/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:586 +0x18f

goroutine 3343 [sync.Mutex.Lock, 7 minutes]:
sync.runtime_SemacquireMutex(0x4d5cac0?, 0xc0?, 0xc005a9cc78?)
	/usr/local/go/src/runtime/sema.go:95 +0x25
sync.(*Mutex).lockSlow(0xc000cd1460)
	/usr/local/go/src/sync/mutex.go:173 +0x15d
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:92
sync.(*RWMutex).Lock(0x0?)
	/usr/local/go/src/sync/rwmutex.go:148 +0x31
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).unconditionalLock(...)
	/go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:51
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).K8sNamespaceAndPodNameIsSet(0xc000cd1408)
	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1392 +0x37
github.com/cilium/cilium/daemon/cmd.(*endpointCreationManager).EndCreateRequest(0xc0011f9520, 0xc000cd1408)
	/go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:294 +0x46
github.com/cilium/cilium/daemon/cmd.(*endpointCreationManager).CancelCreateRequest(0xc005a9cda0?, 0xc000cd1408)
	/go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:315 +0x18
github.com/cilium/cilium/daemon/cmd.(*Daemon).deleteEndpointRelease(0xc0004c6008, 0xc000cd1408, 0x1)
	/go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:760 +0x45
github.com/cilium/cilium/daemon/cmd.(*Daemon).deleteEndpoint(...)
	/go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:774
github.com/cilium/cilium/daemon/cmd.(*Daemon).deleteEndpointByContainerID(0xc0004c6008, {0xc002293500, 0x40})
	/go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:843 +0x4fe
github.com/cilium/cilium/daemon/cmd.deleteEndpointHandler(0xc0004c6008, {0xc002bed680, 0xc0011a9890})
	/go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:139 +0x267
github.com/cilium/cilium/daemon/cmd.(*apiHandler[...]).Handle(0xc00076d0f0, {0xc002bed680?, 0xc0011a9890?})
	/go/src/github.com/cilium/cilium/daemon/cmd/api_handlers.go:68 +0x7c
github.com/cilium/cilium/api/v1/server/restapi/endpoint.(*DeleteEndpoint).ServeHTTP(0xc00236e750, {0x55c9700, 0xc005ca1d70}, 0xc002bed680)
	/go/src/github.com/cilium/cilium/api/v1/server/restapi/endpoint/delete_endpoint.go:58 +0x143
github.com/go-openapi/runtime/middleware.(*Context).RoutesHandler.NewOperationExecutor.func1({0x55c9700, 0xc005ca1d70}, 0xc002bed680)
	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0x53
net/http.HandlerFunc.ServeHTTP(0xc0028ba900?, {0x55c9700?, 0xc005ca1d70?}, 0xc005a9d778?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
github.com/go-openapi/runtime/middleware.NewRouter.func1({0x55c9700, 0xc005ca1d70}, 0xc002bed400)
	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/router.go:80 +0x257
net/http.HandlerFunc.ServeHTTP(0xc0011a16e7?, {0x55c9700?, 0xc005ca1d70?}, 0x2?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
github.com/go-openapi/runtime/middleware.Redoc.serveUI.func1({0x55c9700, 0xc005ca1d70}, 0xc002bed400)
	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/ui_options.go:164 +0xda
net/http.HandlerFunc.ServeHTTP(0xc0011a16e7?, {0x55c9700?, 0xc005ca1d70?}, 0x0?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
github.com/go-openapi/runtime/middleware.Spec.func1({0x55c9700, 0xc005ca1d70}, 0xc002bed400)
	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/spec.go:72 +0x1a8
net/http.HandlerFunc.ServeHTTP(0xc0010afb80?, {0x55c9700?, 0xc005ca1d70?}, 0x3?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
github.com/cilium/cilium/pkg/metrics.(*APIEventTSHelper).ServeHTTP(0xc000e0dd10, {0x55c95e0, 0xc0021eca80}, 0xc002bed400)
	/go/src/github.com/cilium/cilium/pkg/metrics/middleware.go:63 +0x1d0
github.com/cilium/cilium/pkg/api.(*APIPanicHandler).ServeHTTP(0xc000fd2000?, {0x55c95e0?, 0xc0021eca80?}, 0x3?)
	/go/src/github.com/cilium/cilium/pkg/api/apipanic.go:49 +0x5b
net/http.(*ServeMux).ServeHTTP(0x410ca5?, {0x55c95e0, 0xc0021eca80}, 0xc002bed400)
	/usr/local/go/src/net/http/server.go:2747 +0x1ca
net/http.serverHandler.ServeHTTP({0x55b2d38?}, {0x55c95e0?, 0xc0021eca80?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc000fa0f30, {0x55e7e98, 0xc0011061e0})
	/usr/local/go/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 1234
	/usr/local/go/src/net/http/server.go:3360 +0x485

goroutine 2091 [sync.Mutex.Lock, 11 minutes]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0xc000ad7640?)
	/usr/local/go/src/runtime/sema.go:95 +0x25
sync.(*Mutex).lockSlow(0xc000cd1460)
	/usr/local/go/src/sync/mutex.go:173 +0x15d
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:92
sync.(*RWMutex).Lock(0x0?)
	/usr/local/go/src/sync/rwmutex.go:148 +0x31
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).unconditionalLock(...)
	/go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:51
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).SetCiliumEndpointUID(0xc000cd1408, {0xc0020b0510, 0x24})
	/go/src/github.com/cilium/cilium/pkg/endpoint/identifiers.go:160 +0x31
github.com/cilium/cilium/pkg/endpointmanager.(*EndpointSynchronizer).RunK8sCiliumEndpointSync.func1({0x55e7ed0, 0xc0035c50e0})
	/go/src/github.com/cilium/cilium/pkg/endpointmanager/endpointsynchronizer.go:204 +0xe18
github.com/cilium/cilium/pkg/controller.(*controller).runController(0xc0035c77c0, {{{0x4ee74c2, 0x1a}}, {0x55f1d20, 0xc0035c8ba0}, 0xc003948a80, 0x0, 0xc000e5a8a0, 0x2540be400, 0x0, ...})
	/go/src/github.com/cilium/cilium/pkg/controller/controller.go:251 +0x8a
created by github.com/cilium/cilium/pkg/controller.(*Manager).createControllerLocked in goroutine 2086
	/go/src/github.com/cilium/cilium/pkg/controller/manager.go:115 +0x43d

goroutine 1234 [IO wait]:
internal/poll.runtime_pollWait(0x7fc27c0cc698, 0x72)
	/usr/local/go/src/runtime/netpoll.go:351 +0x85
internal/poll.(*pollDesc).wait(0xc002306a80?, 0x7fc2c35e35b8?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc002306a80)
	/usr/local/go/src/internal/poll/fd_unix.go:620 +0x295
net.(*netFD).accept(0xc002306a80)
	/usr/local/go/src/net/fd_unix.go:172 +0x29
net.(*UnixListener).accept(0xc002a25e00?)
	/usr/local/go/src/net/unixsock_posix.go:172 +0x16
net.(*UnixListener).Accept(0xc0011334a0)
	/usr/local/go/src/net/unixsock.go:260 +0x30
net/http.(*Server).Serve(0xc00327e870, {0x55c9400, 0xc0011334a0})
	/usr/local/go/src/net/http/server.go:3330 +0x30c
github.com/cilium/cilium/api/v1/server.(*Server).Start.func1({0x55c9400?, 0xc0011334a0?})
	/go/src/github.com/cilium/cilium/api/v1/server/server.go:460 +0x72
created by github.com/cilium/cilium/api/v1/server.(*Server).Start in goroutine 1
	/go/src/github.com/cilium/cilium/api/v1/server/server.go:458 +0x4a8
```
  
</details>

[gops_stack_whole.txt](https://github.com/user-attachments/files/20614451/gops_stack_whole.txt)

```
Goroutine 560 (7min) - AUTH GC
├── auth.cleanupEndpoints()
├── endpoint.GetSecurityIdentity()
└── endpoint.rlockAlive() ◄─── BLOCKED on RLock
    └── sync.RWMutex.RLock ◄───── WAITING

Goroutine 2101 (11min) - IDENTITY RESOLVER  
├── endpoint.identityLabelsChanged()
├── endpoint.lockAlive() ◄──────── BLOCKED on Lock
└── sync.RWMutex.Lock ◄─────────── WAITING

Goroutine 2770 (9min) - REGENERATION
├── endpointmanager.RegenerateAllEndpoints()
├── endpoint.RegenerateIfAlive()
├── endpoint.SetRegenerateStateIfAlive()
├── endpoint.lockAlive() ◄──────── BLOCKED on Lock  
└── sync.RWMutex.Lock ◄─────────── WAITING

Goroutine 3343 (7min) - DELETE ENDPOINT (HTTP)
├── daemon.deleteEndpointByContainerID()
├── daemon.deleteEndpointRelease() 
├── endpointCreationManager.CancelCreateRequest()
├── endpoint.K8sNamespaceAndPodNameIsSet()
├── endpoint.unconditionalLock() ◄─── BLOCKED on Lock
└── sync.RWMutex.Lock ◄──────────── WAITING

Goroutine 2091 (11min) - CEP SYNC
├── EndpointSynchronizer.RunK8sCiliumEndpointSync()
├── endpoint.SetCiliumEndpointUID()
├── endpoint.unconditionalLock() ◄─── BLOCKED on Lock
└── sync.RWMutex.Lock ◄──────────── WAITING
```

### How can we reproduce the issue?

1. Create ipv6-only kind cluster:
`kind create cluster --config kind-config.yaml --name cilium-ipv6`
  
    <details>
      <summary>kind-config.yaml</summary>
    
      ```
      kind: Cluster
      apiVersion: kind.x-k8s.io/v1alpha4
      networking:
        ipFamily: ipv6
        apiServerAddress: "::1"
        apiServerPort: 6443
        podSubnet: "fd00:10:244::/56"
        serviceSubnet: "fd00:10:96::/112"
        disableDefaultCNI: true
        kubeProxyMode: "none"
      nodes:
      - role: control-plane
      - role: worker
      - role: worker
      ```
    
    </details>

2. Add kvstore pod
`kubectl apply -f kvstore.yaml`

    <details>
      <summary>kvstore.yaml</summary>

      ```
      apiVersion: v1
      kind: Pod
      metadata:
        name: kvstore
        namespace: kube-system
        labels:
          app: kvstore
      spec:
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
        tolerations:
        - operator: Exists
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node.cilium.io/agent-not-ready
          operator: Exists
          effect: NoSchedule
        containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.6.0
          command:
          - etcd
          args:
          - --listen-client-urls=http://[::]:2378
          - --advertise-client-urls=http://[::]:2378
          - --data-dir=/tmp/etcd
          - --log-level=info
          - --logger=zap
          - --log-outputs=stderr
          ports:
          - containerPort: 2378
            hostPort: 2378
            protocol: TCP
          env:
          - name: ETCDCTL_API
            value: "3"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            exec:
              command:
              - etcdctl
              - --endpoints=http://[::1]:2378
              - endpoint
              - health
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
              - etcdctl
              - --endpoints=http://[::1]:2378
              - endpoint
              - health
            initialDelaySeconds: 5
            periodSeconds: 10
      ```

    </details>

3. Deploy cilium with such helm values:
`cilium install -f cilium-values.yaml --version 1.17.4 --set 'etcd.endpoints[0]="http://[<ADDRESS_OF_KVSTORE_POD>]:2378"'`

    <details>
      <summary>cilium-values.yaml</summary>
      
      ```yaml
      ipv6:
        enabled: true
      ipv4:
        enabled: false
      envoy:
        enabled: false
      kvstore: etcd
      etcd:
        enabled: true
        ssl: false
      routingMode: native
      ipv6NativeRoutingCIDR: "fd00:10:244::/56"
      identityAllocationMode: crd  # default
      ```
      
    </details>

4. Observe endpoint regeneration working correctly by rolouting DaemonSet

> 0s                       Warning   FailedCreatePodSandBox   Pod/coredns-674b8bbfcf-f7pgb                            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "4cdaa9a76db35f663ce834fd7621dc5cc855e715aa7f5cfaf8fb5285373d890a": plugin type="cilium-cni" failed (add): unable to create endpoint: Cilium API client timeout exceeded

5. Add these options to helm values:
  ```yaml
  etcd:
    enabled: true
    ssl: false
  ```
Agent and operator would restart due to changes to Deployment. 
Endpoint regeneration is stuck.

6. Rollback to restore

### Cilium Version

v1.17.3

### Kernel Version

6.6.37

### Kubernetes Version

v1.30.11

### Relevant log output

```shell

```

### Anything else?

Also noticed multiple process looked stuck in controller status section of `cilium status --verbose` output (as well on another cluster, where identity allocation never changed):
```
Name                                               Last success   Last error   Count   Message
endpoint-1164-regeneration-recovery                never          never        0       no error
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
