### ISSUE TITLE
[EKS1.33/bottlerocket] Cilium 1.17.2 netkit + tproxy dropping traffic with SOCKET_LOOKUP_FAILED

### ISSUE THREAD

**Issue by mhulscher** [cilium/cilium#39892]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.4 and lower than v1.18.0

### What happened?

Unfortunately I can't yet test the following scenario with 1.17.4 because the fix for [this issue](https://github.com/cilium/cilium/issues/39106) has not yet landed in a stable release, apologies.

[Bottlerocket 1.39.1](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.39.1) on EKS 1.33 uses kernel 6.12.23.

When installing cilium (helm) with `bpf.datapathMode=netkit`, `bpf.tproxy=true` and with L7 policies present, traffic is dropped.

```json
# Snippet from `hubble observe`
{
    "event_type": { "type": 1, "sub_type": 178 },
    "traffic_direction": "EGRESS",
    "file": { "name": "bpf_lxc.c", "line": 1360 },
    "drop_reason_desc": "SOCKET_LOOKUP_FAILED",
    "Summary": "UDP"
}
```

When setting `bpf.tproxy=false` (and recreating the node), the issue does not occur and networking behaves as expected. I am not sure whether this is a bug, or whether tproxy is simply incompatible with netkit devices.

### How can we reproduce the issue?

Install cilium with the following helm values:

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: eks.amazonaws.com/compute-type
          operator: NotIn
          values:
          - fargate
agentNotReadyTaintKey: startup-taint.cluster-autoscaler.kubernetes.io/cilium-not-ready
bandwidthManager:
  bbr: true
  enabled: true
bpf:
  datapathMode: netkit
  masquerade: false
  tproxy: true
bpfClockProbe: true
certgen:
  image:
    repository: 123456789123.dkr.ecr.eu-west-1.amazonaws.com/aio-g3og/quay.io/cilium/certgen
cluster:
  name: aio-g3og-one
clustermesh:
  apiserver:
    image:
      repository: 123456789123.dkr.ecr.eu-west-1.amazonaws.com/aio-g3og/quay.io/cilium/clustermesh-apiserver
cni:
  chainingMode: none
dnsProxy:
  endpointMaxIpPerHostname: 4000
  minTtl: 0
enableIPv4BIGTCP: true
enableIPv4Masquerade: false
enableIPv6BIGTCP: true
enableIPv6Masquerade: false
encryption:
  enabled: false
  nodeEncryption: true
  type: wireguard
endpointHealthChecking:
  enabled: false
eni:
  awsEnablePrefixDelegation: true
  ec2APIEndpoint: ec2.eu-west-1.amazonaws.com
  enabled: true
  eniTags: {}
  iamRole: arn:aws:iam::123456789123:role/aio-g3og-one-cilium-operator
  instanceTagsFilter:
  - aws:eks:cluster-name=aio-g3og-one
  updateEC2AdapterLimitViaAPI: true
envoy:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: eks.amazonaws.com/compute-type
            operator: NotIn
            values:
            - fargate
  enabled: true
  image:
    repository: 123456789123.dkr.ecr.eu-west-1.amazonaws.com/aio-g3og/quay.io/cilium/cilium-envoy
  nodeSelector:
    kubernetes.io/os: linux
  priorityClassName: system-node-critical
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: false
      labels:
        system: "true"
  resources:
    limits: null
    requests:
      cpu: 50m
      memory: 100Mi
  rollOutPods: true
  tolerations:
  - operator: Exists
  updateStrategy:
    type: OnDelete
extraConfig:
  api-rate-limit: |
    {"endpoint-create":"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true","endpoint-delete":"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true","endpoint-get":"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true","endpoint-list":"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true","endpoint-patch":"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true"}
healthChecking: false
hubble:
  enabled: true
  eventBufferCapacity: "8191"
  metrics:
    enableOpenMetrics: true
    enabled:
    - dns:query;labelsContext=source_namespace,source_workload
    - httpV2:exemplars=true;labelsContext=source_namespace,source_workload,source_app,destination_namespace,destination_workload,destination_app,traffic_direction
    serviceMonitor:
      enabled: false
      labels:
        system: "true"
  relay:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: k8s-app
              operator: In
              values:
              - hubble-relay
          topologyKey: kubernetes.io/hostname
    enabled: true
    image:
      repository: 123456789123.dkr.ecr.eu-west-1.amazonaws.com/aio-g3og/quay.io/cilium/hubble-relay
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
    replicas: 3
    resources:
      requests:
        cpu: 25m
    rollOutPods: true
    updateStrategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
  ui:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: k8s-app
              operator: In
              values:
              - hubble-ui
          topologyKey: topology.kubernetes.io/zone
    backend:
      image:
        repository: 123456789123.dkr.ecr.eu-west-1.amazonaws.com/aio-g3og/quay.io/cilium/hubble-ui-backend
    enabled: true
    frontend:
      image:
        repository: 123456789123.dkr.ecr.eu-west-1.amazonaws.com/aio-g3og/quay.io/cilium/hubble-ui
    ingress:
      className: ingress-nginx
      enabled: true
      hosts:
      - hubble.example.com
    podDisruptionBudget:
      enabled: false
    replicas: 1
    resources:
      requests:
        cpu: 25m
    rollOutPods: true
    updateStrategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
image:
  repository: 123456789123.dkr.ecr.eu-west-1.amazonaws.com/aio-g3og/quay.io/cilium/cilium
ipam:
  mode: eni
k8sServiceHost: DF70D124F21DA0DD112D0F9CA1D95DE0.yl4.eu-west-1.eks.amazonaws.com
k8sServicePort: 443
kubeProxyReplacement: true
l7Proxy: true
labels: k8s:!job-name k8s:!controller-uid
loadBalancer:
  l7:
    backend: envoy
  serviceTopology: true
localRedirectPolicy: true
nodeinit:
  image:
    repository: 123456789123.dkr.ecr.eu-west-1.amazonaws.com/aio-g3og/quay.io/cilium/startup-script
operator:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - cilium-operator
        topologyKey: topology.kubernetes.io/zone
  extraArgs:
  - --unmanaged-pod-watcher-interval=0
  image:
    repository: 123456789123.dkr.ecr.eu-west-1.amazonaws.com/aio-g3og/quay.io/cilium/operator
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
  priorityClassName: system-cluster-critical
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: false
      labels:
        system: "true"
  replicas: 2
  resources:
    requests:
      cpu: 25m
  rollOutPods: true
  tolerations:
  - key: node.kubernetes.io/not-ready
    operator: Exists
  - key: startup-taint.cluster-autoscaler.kubernetes.io/cilium-not-ready
    operator: Exists
  - key: startup-taint.cluster-autoscaler.kubernetes.io/dns-not-ready
    operator: Exists
  - key: efs.csi.aws.com/agent-not-ready
    operator: Exists
pmtuDiscovery:
  enabled: true
policyEnforcementMode: default
preflight:
  image:
    repository: 123456789123.dkr.ecr.eu-west-1.amazonaws.com/aio-g3og/quay.io/cilium/cilium
priorityClassName: system-node-critical
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      system: "true"
    metricRelabelings:
    - action: keep
      regex: cilium_operator_ces_sync_errors_total|cilium_controllers_failing|cilium_errors_warnings_total|cilium_ipcache_errors_total|cilium_policy_import_errors_total|cilium_policy_l7_parse_errors_total|cilium_bpf_map_pressure
      sourceLabels:
      - __name__
resources:
  limits: null
  requests:
    cpu: 50m
    memory: 300Mi
routingMode: native
socketLB:
  enabled: true
  terminatePodConnections: true
svcSourceRangeCheck: false
updateStrategy:
  type: OnDelete

```

### Cilium Version

`1.17.2`

### Kernel Version

`6.12.23`

### Kubernetes Version

`EKS 1.33`

### Regression

N/A

### Sysdump

N/A

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by borkmann** [comment]
> When installing cilium (helm) with bpf.datapathMode=netkit, bpf.tproxy=true and with L7 policies present, traffic is dropped.

Hey :wave: Did you manage to debug this further? Does it work with `bpf.tproxy=false`, and does it work with `bpf.datapathMode=veth, bpf.tproxy=true`?

I just briefly looked into the bpf_skc_lookup() helper in the kernel, and it does derive `caller_net = dev_net(skb->dev)` so netkit behavior here should not be different from veth.

**Comment by borkmann** [comment]
(Cc also @joestringer wrt bpf tproxy.)

**Comment by mhulscher** [comment]
@borkmann 

> Does it work with bpf.tproxy=false

This config works (traffic is not dropped, there are no errors produced):

```yaml
bpf:
  tproxy: false
  datapathMode: netkit
```

Enabling tproxy but omitting the datapathMode, which I assume defaults to veth, also works:

```yaml
bpf:
  tproxy: true
```
