### ISSUE TITLE
Gateway not working from inside kubernetes cluster

### ISSUE THREAD

**Issue by tahvane1** [cilium/cilium#39959]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.4 and lower than v1.18.0

### What happened?

I'm running netkit and native routing. BPF masguerading but no nat for these IPs. I get this drop where I think source labels are messed up as I cant' figure out network policy to allow it.
![Image](https://github.com/user-attachments/assets/d44bb4b1-4d06-4764-9fde-edb1ef3df254)

### How can we reproduce the issue?

create gateway http route and try to connect from inside cluster

### Cilium Version

1.17.4

### Kernel Version

6.13.12

### Kubernetes Version

v1.32.4+rke2r1

### Relevant log output

```shell

```

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Hi @tahvane1, I'd recommend reviewing https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/#cilium-s-ingress-config-and-ciliumnetworkpolicy and the example at https://docs.cilium.io/en/stable/network/servicemesh/ingress-and-network-policy/#gs-ingress-and-network-policy to learn more about targeting Network Policy at the `reserved:ingress` identity.

In particular, the example of allowing Ingress traffic when using a default deny seems like it might be the most useful. https://docs.cilium.io/en/stable/network/servicemesh/ingress-and-network-policy/#default-deny-ingress-policy

**Comment by tahvane1** [comment]
ExternalTrafficPolicy is cluster for gateway. I have tried all kinds of policies for ingress. For example:

```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-ingress-egress
  annotations:
    argocd.argoproj.io/hook: PreSync
specs:
- endpointSelector:
    matchExpressions:
    - key: reserved:ingress
      operator: Exists
  egress:
  - toEntities:
    - cluster
  - toCIDR:
    - 172.16.1.4/32
  ingress:
  - fromEntities:
    - world
    - cluster
```

And I have spend quite many hours to trying to solve this (as it is really pain in the ass trying to support services with internal/external names at the same time.
