### ISSUE TITLE
cilium 1.17.4 netkit  feature failed to install on almalinux10 KVM guest

### ISSUE THREAD

**Issue by erictarrence** [cilium/cilium#39972]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.4 and lower than v1.18.0

### What happened?

I had already set routesMode=native ,but cilium cannot start ,it show "Packets must be routed through the tunnel device"

the error logs display below:
```
time="2025-06-10T03:37:13.952366201Z" level=info msg="  --routing-mode='tunnel'" subsys=daemon
....
time="2025-06-10T03:37:13.952450728Z" level=info msg="  --tunnel-port='0'" subsys=daemon
time="2025-06-10T03:37:13.952454396Z" level=info msg="  --tunnel-protocol='vxlan'" subsys=daemon
time="2025-06-10T03:37:13.952458423Z" level=info msg="  --tunnel-source-port-range='0-0'" subsys=daemon
....
time="2025-06-10T03:21:09.071960885Z" level=info msg="Final node label prefixes to be used for identity evaluation:" subsys=labels-filter
time="2025-06-10T03:21:09.072552232Z" level=fatal msg="auto-direct-node-routes cannot be used with tunneling. Packets must be routed through the tunnel device." subsys=daemon
```

### How can we reproduce the issue?

1.My node  network CIDR is  192.168.0.0/23
  My k8s  podSubnet is 10.110.32.0/19

2.My kubeadm configuration file is as follows:

```
apiVersion: kubeadm.k8s.io/v1beta4
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.0.152
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  imagePullSerial: true
  name: master1
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
timeouts:
  controlPlaneComponentHealthCheck: 4m0s
  discovery: 5m0s
  etcdAPICall: 2m0s
  kubeletHealthCheck: 4m0s
  kubernetesAPICall: 1m0s
  tlsBootstrap: 5m0s
  upgradeManifests: 5m0s
---
apiServer:
  extraArgs:
  - name: enable-aggregator-routing
    value: "true"
  - name: max-mutating-requests-inflight
    value: "500"
  - name: max-requests-inflight
    value: "1500"
apiVersion: kubeadm.k8s.io/v1beta4
caCertificateValidityPeriod: 87600h0m0s
certificateValidityPeriod: 8760h0m0s
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes-2
controlPlaneEndpoint: "192.168.0.101:6444" #keepalived vip
controllerManager:
  extraArgs:
  - name: terminated-pod-gc-threshold
    value: "1024"
  - name: allocate-node-cidrs
    value: "true"
  - name: cluster-cidr
    value: 10.110.32.0/19
dns:
  imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
  imageTag: 1.12.1
encryptionAlgorithm: RSA-2048
etcd:
  local:
    dataDir: /data/etcd
    imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
    imageTag: 3.5.21-0
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
kind: ClusterConfiguration
kubernetesVersion: v1.33.1
networking:
  dnsDomain: cluster.local
  podSubnet: 10.110.32.0/19
  serviceSubnet: 172.23.4.0/22
proxy: {}
scheduler: {}
```

3.My cilium Helm install command is as follow:

```
helm repo add cilium https://helm.cilium.io
helm  search repo  cilium 
helm upgrade --install cilium cilium/cilium --version 1.17.4 \
  --namespace kube-system \
  --set routesMode=native \
  --set bpf.datapathMode=netkit \
  --set bpf.masquerade=true \
  --set bpf.distributedLRU.enabled=true \
  --set ipv4.enabled=true \
  --set enableIPv4BIGTCP=true \
  --set kubeProxyReplacement=true \
  --set bpfClockProbe=true \
  --set bandwidthManager.enabled=true \
  --set bandwidthManager.bbr=true \
  --set kubeProxyReplacement=true \
  --set loadBalancer.acceleration=native \
  --set loadBalancer.mode=dsr \
  --set loadBalancer.dsrDispatch=opt \
  --set k8sServiceHost=192.168.0.101 \
  --set k8sServicePort=6444 \
  --set ipam.mode=kubernetes \
  --set ipv4NativeRoutingCIDR="10.110.32.0/19" \
  --set installNoConntrackIptablesRules=true \
  --set autoDirectNodeRoutes=true \
  --set direct-routing-skip-unreachable=true
```

### Cilium Version

 1.17.4 

### Kernel Version

6.12.0-55.9.1.el10_0.x86_64

### Kubernetes Version

Client Version: v1.33.1
Kustomize Version: v5.6.0
Server Version: v1.33.1

### Relevant log output

```shell

```

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
