### ISSUE TITLE
Intermittent EGRESS DENIED Possibly Leading to Connection Resets

### ISSUE THREAD

**Issue by devasmith** [cilium/cilium#40003]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.4 and lower than v1.18.0

### What happened?

Hi guys.

Our haproxy pods deployed in an "LB Cluster" running Cilium, act as proxies. They receive incoming client requests and then initiate outbound connections to a backend service.

The traffic flow for these connections is:
CLIENT -> haproxy-0 svc (LB Cluster) -> haproxy pod (LB Cluster) -> NodePort (PROD Cluster) -> Traefik (PROD Cluster) -> Application (PROD Cluster). See picture further down for a better overview.

**Specifically**, the issue occurs during the connection from the haproxy pod (in the Cilium cluster) to the NodePort in the separate PROD Cluster (which runs Flannel). We are intermittently observing EGRESS DENIED verdicts for TCP ACK and FIN packets for this specific outbound traffic (haproxy pod -> NodePort). This possibly leads to connection resets (observed as Connection reset by peer by clients) after approximately 540 seconds (possibly based on what the client have configured in their end). This problem did not occur when our LB Cluster was running Flannel/Canal as its CNI.

(Note: We have also observed occasional INGRESS DENIED logs to ephemeral ports on haproxy pods, but the primary issue and the one matching this flow diagram is the EGRESS DENIED from haproxy to the PROD cluster's NodePort.)

### How can we reproduce the issue?

Not sure how to reproduce as it is intermittent and setup is quite complex, see traffic flow further down.

### Cilium Version

v1.17.4

### Kernel Version

5.14.0-570.18.1.el9_6.x86_64 running Rocky Linux 9 (RHEL 9)

### Kubernetes Version

RKE2 v1.31.8+rke2r1

### Sysdump

Noticed some sensitive data (for us) in here, let me know how to anonymize if you need this information.

### Relevant log output

```shell
Output from `hubble observe -P --verdict DROPPED -f`


Jun 9 13:22:00.135: prod/haproxy-app-6f5559855-mhh8t:8443 (ID:5938) <> x.y.z.x:61565 (world) policy-verdict:none EGRESS DENIED (TCP Flags: ACK, FIN)
Jun 9 13:22:00.135: prod/haproxy-app-6f5559855-mhh8t:8443 (ID:5938) <> x.y.z.x:61565 (world) Policy denied DROPPED (TCP Flags: ACK, FIN)
Jun 12 06:02:29.145: 10.83.11.123:30080 (ID:16777241) <> dev/haproxy-7c669577c6-cbrcw:50814 (ID:37801) policy-verdict:none INGRESS DENIED (TCP Flags: SYN, ACK)
Jun 12 06:02:29.145: 10.83.11.123:30080 (ID:16777241) <> dev/haproxy-7c669577c6-cbrcw:50814 (ID:37801) Policy denied DROPPED (TCP Flags: SYN, ACK)

Our logs

We see a HTTP 200 in our logs, but the client never get the response.

event.original
10.42.23.27 - XYZ [10/Jun/2025:04:05:51 +0000] "POST /oauth-v1/token HTTP/1.1" 200 2780 "-" "python-requests/2.31.0" "x.y.z.p (Client IP), 10.83.15.112 (Prod worker)"

Client observation

We had a latency of "539.961626246s" for this request and we received ERROR: refresh_application_token_client_api: Network error during token refresh: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

### Anything else?

**Traffic flow**

<img width="2976" alt="Image" src="https://github.com/user-attachments/assets/693a4bb1-ccee-490e-8c95-2d1884b379c3" />

**rke2-cilium HelmChartConfig**

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    routingMode: native
    installNoConntrackIptablesRules: true
    autoDirectNodeRoutes: true
    ipv4NativeRoutingCIDR: 10.42.0.0/16
    k8sServiceHost: localhost
    k8sServicePort: 6443
    rollOutCiliumPods: true
    bpf:
      masquerade: true # BPF-based masquerading is enabled
    cni:
      chainingMode: none
    conntrackGCInterval: "0s" # Note: "0s" for conntrackGCInterval in Cilium implies no periodic GC, relies on BPF map pressure
    hostFirewall:
      enabled: true
    hubble:
      enabled: true
      export:
        dynamic:
          enabled: true
          config:
            content:
              - name: ingress-egress-traffic-blocking
                filePath: /dev/stdout
                includeFilters:
                  - event_type:
                    - type: 1
                      sub_type: 181
                    traffic_direction:
                    - INGRESS
                    - EGRESS
      relay:
        enabled: true
      ui: 
        enabled: true
    prometheus:
      enabled: true
      port: 9962
      metrics: 
        - +cilium_bpf_map_pressure
```

**NetworkPolicy that is applied for a haproxy instance**

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: haproxy-app
  namespace: prod
spec:
  egress:
  - ports:
    - port: 8080
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          name: maintenance
      podSelector:
        matchLabels:
          app: maintenance
  - ports:
    - port: 30080
      protocol: TCP
    to:
    - ipBlock:
        cidr: 10.81.15.103/32
# ... List continues with more NodePort rules
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
      podSelector:
        matchLabels:
          app.kubernetes.io/component: prometheus
          app.kubernetes.io/instance: k8s
          app.kubernetes.io/name: prometheus
    ports:
    - port: 9101
      protocol: TCP
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - port: 8081
      protocol: TCP
    - port: 8443
      protocol: TCP
  podSelector:
    matchLabels:
      app: haproxy-app
  policyTypes:
  - Egress
  - Ingress
```

**CiliumClusterwideNetworkPolicy has Egress allowed**

**Slack thread reference**: https://cilium.slack.com/archives/C01JALNQAR1/p1749551365559999

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
