### ISSUE TITLE
Dropped traffic for some services after upgrade 1.16.x -> 1.17.3

### ISSUE THREAD

**Issue by riuvshyn** [cilium/cilium#40098]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.4 and lower than v1.18.0

### What happened?

Unexpected dropping traffic after upgrade from 1.16.x to 1.17.3
We have global default deny policies for both services and hosts (firewall) and every service is covered by relevant network policies, after upgrade to 1.17.3 we have noticed that return traffic for some services started being dropped potentially due to `unknown` identity for the k8s node.

hubble log:
```

message | {"flow":{"time":"2025-06-17T13:58:45.093991884Z","verdict":"DROPPED","IP":{"source":"172.23.106.158","destination":"172.23.106.70","ipVersion":"IPv4"},"l4":{"TCP":{"source_port":443,"destination_port":32934,"flags":{"SYN":true,"ACK":true}}},"source":{"identity":69550,"namespace":"vpn-ingress-controller","pod_name":"vpn-ingress-controller-controller-64c65fdbc-6pgc5"},"destination":{"identity":1},"Type":"L3_L4","node_name":"test/ip-172-21-237-87.eu-central-1.compute.internal","event_type":{"type":1,"sub_type":133},"traffic_direction":"INGRESS","drop_reason_desc":"POLICY_DENIED","Summary":"TCP Flags: SYN, ACK"},"node_name":"test/ip-172-21-237-87.eu-central-1.compute.internal","time":"2025-06-17T13:58:45.093991884Z"}
-- | --

```

```
xx drop (Policy denied) flow 0x337205d5 to endpoint 0, ifindex 20, file bpf_host.c:1845, , identity 69550->unknown: 172.23.106.158:443 -> 172.23.106.70:32934 tcp SYN, ACK
```

where: `172.23.106.158:443` is a service pod IP and `172.23.106.70:2261` is a k8s node IP

It looks like it happens somewhere [here](https://github.com/cilium/cilium/blob/v1.17.3/bpf/bpf_host.c#L1842)

After some debugging we have found that it was caused by host level global default deny policy:
```
specs:
  egress:
  - {}
  ingress:
  - {}
  nodeSelector:
    matchLabels: {}
```

to fix the issue we had to create following host policy:

```
spec:
  description: |
    This policy allows ingress traffic for workloads with a matching selector from the configured wise service, ports and protocols to the host.
    This is not to be confused with the technical terminology of a Kubernetes Service.
  enableDefaultDeny:
    egress: false
    ingress: false
  ingress:
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: vpn-ingress-controller
        io.kubernetes.pod.namespace: vpn-ingress-controller
    toPorts:
    - ports:
      - endPort: 65535
        port: "1025"
        protocol: TCP
      - endPort: 65535
        port: "1025"
        protocol: UDP
  nodeSelector:
    matchLabels: {}
```

### How can we reproduce the issue?

not really sure how to reproduce it, but something like:
1. With 1.16.6 Cilium Create global default deny host policy
2. Deploy service with CNPs to allow service expected egress/ingress (it happened for us with ingress controller)
3. Upgrade Cilium to 1.17.3

### Cilium Version

1.17.3

### Kernel Version

5.15.0-1084-aws

### Kubernetes Version

1.30.13

### Relevant log output

```shell
cilium monitor logs:

xx drop (Policy denied) flow 0x337205d5 to endpoint 0, ifindex 20, file bpf_host.c:1845, , identity 70338->unknown: 172.23.106.158:443 -> 172.23.106.70:2261 tcp SYN, ACK
xx drop (Policy denied) flow 0xd7b16a91 to endpoint 0, ifindex 20, file bpf_host.c:1845, , identity 70338->unknown: 172.23.106.158:443 -> 172.23.106.70:51846 tcp SYN, ACK
xx drop (Policy denied) flow 0x9b91c008 to endpoint 0, ifindex 20, file bpf_host.c:1845, , identity 70338->unknown: 172.23.106.158:443 -> 172.23.106.70:56303 tcp SYN, ACK
xx drop (Policy denied) flow 0xc1833bd4 to endpoint 0, ifindex 20, file bpf_host.c:1845, , identity 70338->unknown: 172.23.106.158:443 -> 172.23.106.70:56303 tcp SYN, ACK
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
