### ISSUE TITLE
“Add ‘reject’ option to return TCP RST/ICMP instead of silent DROP for policy-denied flows”

### ISSUE THREAD

**Issue by janavenkat** [cilium/cilium#40228]
### What happened?

When a pod’s egress traffic is denied by a `CiliumNetworkPolicy`, the packet is silently **dropped**.  
The client keeps retransmitting SYNs until the Linux `tcp_syn_retries` budget is exhausted, so the request appears to “hang” for 20-30 s before failing.  Is it the expected behaviour or there way to reject immediately? but it is painful for apps for being timedout.

Relevant background:

* Cilium enforces L3/L4 policy with eBPF and currently uses a **DROP** verdict with no active response.  [docs.cilium.io](https://docs.cilium.io/en/stable/operations/troubleshooting.html)

### Steps to reproduce

1. Deploy Cilium v1.17.5 using [Kind](https://docs.cilium.io/en/stable/installation/kind/#gs-kind).  
2. Apply this minimal CNP that only allows HTTPS to GitHub:

   ```yaml
   kind: CiliumNetworkPolicy
   metadata:
     name: fqdn-only-github-https
   spec:
     endpointSelector:
       matchLabels:
         app: test-box
     egress:
       - toFQDNs:
           - matchPattern: "*.github.com"
       - toEndpoints:   # allow DNS to kube-dns
           - matchLabels:
               k8s:io.kubernetes.pod.namespace: kube-system
               k8s:k8s-app: kube-dns
         toPorts:
           - ports:
               - port: "53"
                 protocol: ANY
             rules:
               dns:
                 - matchPattern: "*"  
 3. Exec into the pod and run
`wget -T 5 http://google.com   # or curl --connect-timeout 5 ...`
 4. Observe in Hubble UI. Traffic get's blocked
  ```
   cilium hubble port-forward
   cilium hubble ui
   ```
 
####  Another way to block in the DNS request but we're not seeing the block requests in Hubble UI

1. Deploy Cilium v1.17.5 using [Kind](https://docs.cilium.io/en/stable/installation/kind/#gs-kind).  
2. Apply this minimal CNP that only allows HTTPS to GitHub and DNS requests for GitHub:

   ```yaml
   kind: CiliumNetworkPolicy
   metadata:
     name: fqdn-only-github-https-dns
   spec:
     endpointSelector:
       matchLabels:
         app: test-box
     egress:
       - toFQDNs:
           - matchPattern: "github.com"
       - toEndpoints:   # allow DNS to kube-dns
           - matchLabels:
               k8s:io.kubernetes.pod.namespace: kube-system
               k8s:k8s-app: kube-dns
         toPorts:
           - ports:
               - port: "53"
                 protocol: ANY
             rules:
               dns:
                 - matchPattern: "github.com"  
   ```
  3. Exec into the pod and run
`wget -T 5 http://google.com`
  4. Now it's should be immediately failed because of DNS rejection
  5. But there is no way to monitor in Hubble as it's reject in DNS

I may be mistaken in my understanding. I appreciate the help.

### Why these points matter  

* **Silent DROP is the root cause** – documentation confirms that Cilium’s default action is to drop without feedback.  [docs.cilium.io](https://docs.cilium.io/en/stable/operations/troubleshooting.html?)  
* **Feature already discussed** – pointing to #17944 and #13451 shows you have searched existing issues first.  [github.com 17944](https://github.com/cilium/cilium/issues/17944) [github.com 13451](https://github.com/cilium/cilium/issues/13451)  
* **dnsRejectResponseCode only covers DNS** – citing the docs/PR explains why that knob can’t help with TCP.  [github.com 6571](https://github.com/cilium/cilium/pull/6571)
