### ISSUE TITLE
Cilium hostFirewall rules are ignored in tagged VLAN

### ISSUE THREAD

**Issue by abcdegorov** [cilium/cilium#40247]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.5 and lower than v1.18.0

### What happened?

Hi! I have recently encountered a problem where host firewall policies are ignored, making the cluster fully exposed to the outside world. We have Cilium deployed with host firewall enabled and audit mode turned off, but this doesn't seem to work – I'm able to access endpoints on various ports (e.g. API on 6443 and node-exporter on 9100) by directly querying `<node>:<port>`.
Here are our Cilium values:
```yaml
nameOverride: "cilium"
fullnameOverride: "cilium"

upgradeCompatibility: "1.32"
localRedirectPolicy: true
rollOutCiliumPods: true

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

nodePort:
  enabled: true

endpointRoutes:
  enabled: true

bpf:
  datapathMode: netkit
  masquerade: true
  hostLegacyRouting: false
  tproxy: true
  preallocateMaps: true
  mapDynamicSizeRatio: 0.08

  distributedLRU:
    enabled: false

kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256

k8sServiceHost: 127.0.0.1
k8sServicePort: 7445   # https://www.talos.dev/v1.9/kubernetes-guides/configuration/kubeprism/

hostFirewall:
  enabled: true
policyAuditMode: false

bandwidthManager:
  enabled: true
  bbr: true 

externalIPs:
  enabled: true
hostPort:
  enabled: false

loadBalancer:
  algorithm: maglev
  mode: snat

ipam:
  mode: "kubernetes"
k8s:
  requireIPv4PodCIDR: true

autoDirectNodeRoutes: true
ipv4NativeRoutingCIDR: 10.244.0.0/16
routingMode: native

egressGateway:
  enabled: false

hubble:
  enabled: true
  tls:
    enabled: true
    auto:
      enabled: true
      method: cronJob
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        k8s-app: prometheus
    enableOpenMetrics: true
    dashboards:
      enabled: true
      namespace: monitoring
    enabled:
    - dns:query;ignoreAAAA
    - drop
    - tcp
    - flow
    - icmp
    - http

  relay:
    enabled: true
    prometheus:
      enabled: true
    rollOutPods: true

  ui:
    enabled: true
    rollOutPods: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: example-clusterissuer
        # haproxy-ingress.github.io/config-backend: |
        #   haproxy-ingress config
      className: "haproxy"
      hosts:
        - hubble-ui.${cluster_name}.k8s.example.com
      tls:
        - secretName: hubble-ui-tls
          hosts:
            - hubble-ui.${cluster_name}.k8s.example.com
operator:
  replicas: 3
  nodeSelector:
    node-role.kubernetes.io/control-plane: ''
  rollOutPods: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        k8s-app: prometheus

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
    labels:
      k8s-app: prometheus
envoy:
  enabled: false

extraConfig:
  "api-rate-limit": "{\"endpoint-create\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,mean-over:15,auto-adjust:true\", \"endpoint-delete\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,mean-over:15,auto-adjust:true\", \"endpoint-get\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,mean-over:15,auto-adjust:true\", \"endpoint-list\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,mean-over:15,auto-adjust:true\", \"endpoint-patch\": \"rate-limit:10/s,rate-burst:10,parallel-requests:10,mean-over:15,auto-adjust:true\"}"

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
```
I have tried using both `native` and `tunnel` routing modes just in case there would be a difference, but there wasn't.

We also have a number of CCNPs deployed:
```yaml
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: common
spec:
  nodeSelector:
    matchLabels: {}
  ingress:
    - icmps:
        - fields:
            - type: 8
              family: IPv4
            - type: 128
              family: IPv6
    - fromEntities:
        - host
        - remote-node
        - health
    - toPorts:
        - ports:
            - port: "53"
              protocol: ANY
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
        - matchLabels:
            app.kubernetes.io/name: metrics-server
        - matchLabels:
            k8s-app: hubble-relay
    - fromEntities:
        - host
        - remote-node
        - health
      toPorts:
        - ports:
            - port: "4240"
              protocol: TCP
            - port: "4244"
              protocol: TCP
            - port: "4245"
              protocol: TCP
            - port: "8472"
              protocol: UDP
            - port: "10248"
              protocol: TCP
            - port: "10250"
              protocol: TCP
            - port: "10257"
              protocol: TCP
            - port: "10259"
              protocol: TCP
    - fromCIDR:
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "10.0.0.0/8"
      toPorts:
        - ports:
            - port: "4240"
              protocol: TCP
            - port: "4244"
              protocol: TCP
            - port: "4245"
              protocol: TCP
            - port: "8472"
              protocol: UDP
            - port: "10248"
              protocol: TCP
            - port: "10250"
              protocol: TCP
            - port: "10257"
              protocol: TCP
            - port: "10259"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: controlplane
spec:
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/control-plane: ""
  ingress:
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "2379"
              protocol: TCP
            - port: "2380"
              protocol: TCP
            - port: "6443"
              protocol: TCP
    - fromCIDR:
        # - VPN GWs and other hosts
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: haproxy-lb-local
spec:
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  ingress:
    - fromEntities:
      - host
    - fromEndpoints:
      - {}
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: ingress
spec:
  description: "Ingress policy for haproxy-ingress/haproxy-ingress-direct ports and LoadBalancer service port range."
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  ingress:
    - toPorts:
      - ports:
        - port: "160"
          protocol: TCP
        - port: "886"
          protocol: TCP
        - port: "161"
          protocol: TCP
        - port: "887"
          protocol: TCP
        - port: "30000"
          endPort: 32767
          protocol: TCP
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: prometheus
spec:
  description: "Allow prometheus to scrape metrics"
  nodeSelector:
    matchLabels:
      {}
  ingress:
    - fromCIDR:
        - # External Prometheus host
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: talos
spec:
  description: Allow access to Talos Linux apid and trustd
  nodeSelector:
    matchLabels: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: etcd-backup
      toPorts:
        - ports:
            - port: '50000'
              protocol: TCP
    - fromEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "50000"
              protocol: TCP
            - port: "50001"
              protocol: TCP
    - fromCIDR:
        # - VPN GWs and other hosts
      toPorts:
        - ports:
            - port: "50000"
              protocol: TCP
            - port: "50001"
              protocol: TCP
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: vlans
spec:
  nodeSelector:
    matchLabels:
      {}
  ingress:
    - fromCIDR:
        - 172.16.0.0/12
        - 192.168.0.0/16
        - 10.0.0.0/8

```
With this setup, I'm supposed to see at least something when accessing example aforementioned ports on cluster nodes, but there is absolutely nothing in `cilium monitor` regarding these ports.

### How can we reproduce the issue?

1. Install Cilium with Helm using provided values
2. Apply provided CCNPs (fill in your allowed host CIDRs)
3. Query various ports on nodes from a host not present in the allowed CIDRs list

### Cilium Version

`1.17.5`

### Kernel Version

`6.12.18-talos`

### Kubernetes Version

`v1.32.3`

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
