### ISSUE TITLE
mellanox ConnectX-4 Lx virtual function breaks with xdp acceleration "best-effort"

### ISSUE THREAD

**Issue by ashtonian** [cilium/cilium#40259]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.5 and lower than v1.18.0

### What happened?

Using Mellanox ConnectX-4 lx connector with ubuntu 24.04 w/ hwe 6.11 kernel, esxi 8u3 with sr-iov enabled using a virtual function seems to break xdp acceleration. The esxi driver is 4.23.6.2-7vmw.803.0.0.24022510. The nic firmware is 14.32.21.02. Recently switched from x710s to the mellanox and started getting dns failures. Tracked it down to xdp acceleration. With best-effort set I start to get io timeouts in the core-dns pod. 

```sh
     tx_tls_drop_no_sync_data: 0
     tx_tls_drop_bypass_req: 0
     rx_xdp_drop: 0
     tx_queue_dropped: 0
     rx_oversize_pkts_sw_drop: 0
     rx_xsk_xdp_drop: 0
     rx_xsk_oversize_pkts_sw_drop: 0
     rx0_xdp_drop: 0
     rx0_oversize_pkts_sw_drop: 0
     rx1_xdp_drop: 0
     rx1_oversize_pkts_sw_drop: 0
     rx2_xdp_drop: 0
     rx2_oversize_pkts_sw_drop: 0
     rx3_xdp_drop: 0
     rx3_oversize_pkts_sw_drop: 0
     tx0_tls_drop_no_sync_data: 0
     tx0_tls_drop_bypass_req: 0
     tx0_dropped: 0
     tx1_tls_drop_no_sync_data: 0
     tx1_tls_drop_bypass_req: 0
     tx1_dropped: 0
     tx2_tls_drop_no_sync_data: 0
     tx2_tls_drop_bypass_req: 0
     tx2_dropped: 0
     tx3_tls_drop_no_sync_data: 0
     tx3_tls_drop_bypass_req: 0
     tx3_dropped: 0
driver: mlx5_core
version: 6.11.0-28-generic
firmware-version: 14.32.2102 (DEL2810000034)
expansion-rom-version:
bus-info: 0000:03:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: yes
[    0.343904] NET: Registered PF_XDP protocol family
2: ens0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:50:56:00:00:02 brd ff:ff:ff:ff:ff:ff
    altname enp3s0
xdp_tx_mpwqe       : off
xdp:

tc:
ens0(2) tcx/ingress cil_from_netdev prog_id 1303 link_id 18
ens0(2) tcx/egress cil_to_netdev prog_id 1302 link_id 19
cilium_net(3) tcx/ingress cil_to_host prog_id 1285 link_id 17
cilium_host(4) tcx/ingress cil_to_host prog_id 1277 link_id 15
cilium_host(4) tcx/egress cil_from_host prog_id 1279 link_id 16
lxc_health(6) netkit/peer cil_from_container prog_id 1259 link_id 12
lxc5bb034d51b8f(8) netkit/peer cil_from_container prog_id 1235 link_id 14
lxc5be7083c66a4(10) netkit/peer cil_from_container prog_id 1237 link_id 13
lxcbcbbeb534a50(12) netkit/peer cil_from_container prog_id 1265 link_id 20
lxc76f02b6758f7(14) netkit/peer cil_from_container prog_id 1340 link_id 21

flow_dissector:

netfilter:

Features for ens0:
rx-checksumming: on
tx-checksumming: on
	tx-checksum-ipv4: off [fixed]
	tx-checksum-ip-generic: on
	tx-checksum-ipv6: off [fixed]
	tx-checksum-fcoe-crc: off [fixed]
	tx-checksum-sctp: off [fixed]
scatter-gather: on
	tx-scatter-gather: on
	tx-scatter-gather-fraglist: off [fixed]
tcp-segmentation-offload: on
	tx-tcp-segmentation: on
	tx-tcp-ecn-segmentation: off [fixed]
	tx-tcp-mangleid-segmentation: off
	tx-tcp6-segmentation: on
generic-segmentation-offload: on
generic-receive-offload: on
large-receive-offload: off
rx-vlan-offload: on
tx-vlan-offload: on
ntuple-filters: off
receive-hashing: on
highdma: on [fixed]
rx-vlan-filter: on
vlan-challenged: off [fixed]
tx-lockless: off [fixed]
netns-local: off [fixed]
tx-gso-robust: off [fixed]
tx-fcoe-segmentation: off [fixed]
tx-gre-segmentation: on
tx-gre-csum-segmentation: on
tx-ipxip4-segmentation: off [fixed]
tx-ipxip6-segmentation: off [fixed]
tx-udp_tnl-segmentation: off [fixed]
tx-udp_tnl-csum-segmentation: off [fixed]
tx-gso-partial: on
tx-tunnel-remcsum-segmentation: off [fixed]
tx-sctp-segmentation: off [fixed]
tx-esp-segmentation: off [fixed]
tx-udp-segmentation: on
tx-gso-list: off [fixed]
fcoe-mtu: off [fixed]
tx-nocache-copy: off
loopback: off [fixed]
rx-fcs: off
rx-all: off [fixed]
tx-vlan-stag-hw-insert: on
rx-vlan-stag-hw-parse: off [fixed]
rx-vlan-stag-filter: on [fixed]
l2-fwd-offload: off [fixed]
hw-tc-offload: off
esp-hw-offload: off [fixed]
esp-tx-csum-hw-offload: off [fixed]
rx-udp_tunnel-port-offload: off [fixed]
tls-hw-tx-offload: off [fixed]
tls-hw-rx-offload: off [fixed]
rx-gro-hw: off [fixed]
tls-hw-record: off [fixed]
rx-gro-list: off
macsec-hw-offload: on
rx-udp-gro-forwarding: off
hsr-tag-ins-offload: off [fixed]
hsr-tag-rm-offload: off [fixed]
hsr-fwd-offload: off [fixed]
hsr-dup-offload: off [fixed]
```

cilium chart config: 
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  failurePolicy: abort
  valuesContent: |-

    ipv4NativeRoutingCIDR: "10.42.0.48/28"
    ipMasqAgent:
      enabled: true
      config:
        nonMasqueradeCIDRs:
          # Node IP range
          - "10.42.0.48/28" # .48-.63
          # Pod range (redundant with nativeRoutingCIDR)
          - "10.44.0.0/16"
          # Service range
          - "10.45.0.0/16"
          # External load balancer service range
          # - "10.46.0.0/24"
    policyEnforcementMode: never
    dnsProxy:
      enableTransparentMode: false
    localRedirectPolicy: true
    apiRateLimit: "endpoint-create=rate-limit:40/s,rate-burst:500,min-parallel-requests:4,max-parallel-requests:40;endpoint-delete=rate-limit:40/s,rate-burst:500,min-parallel-requests:4,max-parallel-requests:40;endpoint-get=rate-limit:40/s,rate-burst:500,min-parallel-requests:4,max-parallel-requests:40;endpoint-patch=rate-limit:40/s,rate-burst:500,min-parallel-requests:4,max-parallel-requests:40;endpoint-list=rate-limit:40/s,rate-burst:500,min-parallel-requests:4,max-parallel-requests:40"
    cni:
      chainingMode: "none"
    ipam:
      mode: "kubernetes"
    k8sServiceHost: 10.42.0.60
    k8sServicePort: 6443
    gatewayAPI:
      enabled: false
    debug:
      enabled: true
      verbose: flow kvstore envoy datapath policy
    daemon:
      # TODO: not sure if this is needed with ngninx
      enableSourceIPVerification: false
    ## STD:
    annotateK8sNode: true
    routingMode: native
    enableCiliumEndpointSlice: true
    # Allows to explicitly specify the IPv4 CIDR for native routing.
    # When specified, Cilium assumes networking for this CIDR is preconfigured and
    # hands traffic destined for that range to the Linux network stack without
    # applying any SNAT.
    # Generally speaking, specifying a native routing CIDR implies that Cilium can
    # depend on the underlying networking stack to route packets to their
    # destination. To offer a concrete example, if Cilium is configured to use
    # direct routing and the Kubernetes CIDR is included in the native routing CIDR,
    # the user must configure the routes to reach pods, either manually or by
    # setting the auto-direct-node-routes flag.

    # replace kube-proxy with eBPF load-balancer
    kubeProxyReplacement: "true"
     # Enables masquerading of IPv4 traffic leaving the node from endpoints.
    enableIPv4Masquerade: true
    enableMasqueradeRouteSource: false # not supported (--enable-masquerade-to-route-source=\"true\") currently not supported with BPF-based masquerading

    # -- Install Iptables rules to skip netfilter connection tracking on all pod
    # traffic. This option is only effective when Cilium is running in direct
    # routing and full KPR mode. Moreover, this option cannot be enabled when Cilium
    # is running in a managed Kubernetes environment or in a chained CNI setup.
    installNoConntrackIptablesRules: true

    # -- Enable installation of PodCIDR routes between worker
    # nodes if worker nodes share a common L2 network segment.
    autoDirectNodeRoutes: true

    # -- Enable skipping of PodCIDR routes between worker
    # nodes if the worker nodes are in a different L2 network segment.
    directRoutingSkipUnreachable: true

    # Enable BPF clock source probing for more efficient tick retrieval.
    bpfClockProbe: true
    bpf:
      disableExternalIPMitigation: true
      ctTcpMax: 1048576   # 1M entries
      ctAnyMax: 524288    # 512k entries
      # Perform masquerading (SNAT) using eBPF instead of iptables for efficiency
      masquerade: true
      # (Optional) Use netkit pod devices instead of veth for lower latency & multi-queue support # ^ Requires kernel 6.7+ provides ~10% conntrack performance gain
      datapathMode: "netkit"
      # Enable eBPF host routing (bypass upper host stack); direct packets out of BPF instead of Linux
      hostLegacyRouting: false

      # Use per-CPU distributed LRU for core BPF maps to reduce contention (multi-core scalability) at cost of more mem
      distributedLRU:
        enabled: true

      #Enables pre-allocation of eBPF map values. This increases memory usage but can reduce latency.
      preallocateMaps: true

      # default 0.0025
      mapDynamicSizeRatio: 0.035
      # TODO: does not work
      events:
        # Increase aggregation interval, cpu optimization for hubble
        monitorInterval: "10s"
        # default:
        #   rateLimit: 10000
        #   burstLimit: 50000
      # Enable the option to define the load balancing mode (SNAT or DSR) on a per-service basis through service.cilium.io/forwarding-mode annotation.
      lbModeAnnotation: true

    ciliumEndpointSlice:
      enabled: true

    enableIPv6BIGTCP: false
    # Disable for now
    ipv6:
      enabled: false

     # TODO: verify network support
    enableIPv4BIGTCP: false
    ipv4:
      enabled: true

    # Enable Cilium's BGP control plane to advertise routes (for native routing across nodes)
    bgpControlPlane:
      enabled: true

    nodePort:
      enabled: true
    hostPort:
      enabled: true
    externalIPs:
      enabled: true
    socketLB:
      enabled: true

    loadBalancer:
      enabled: true
      algorithm: "maglev"
      # Use hybrid SNAT mode for services (SNAT only when needed for external traffic, preserving client IP when possible)
      mode: "snat"
      # (Optional) XDP acceleration for NodePort/LB services - attach XDP at NIC driver for fastest packet path # ^ Requires NIC driver support for XDP
      acceleration: "best-effort"
      dsrDispatch: ipip
    bandwidthManager:
      # Enable eBPF baandwidth manager (EDT scheduling) for pod egress traffic
      enabled: true
      # Use BBR congestion control for pods (improves throughput/latency to Internet) ^ BBR for pods requires Linux kernel >= 5.18 and eBPF host-routing to be effective
      bbr: true

    hubble:
      enabled: true
      eventQueueSize: 32768
      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - icmp
          - http
      relay:
        enabled: true
        prometheus:
          metricsService: false
          enabled: false
          serviceMonitor:
            enabled: false
      ui:
        enabled: true
        replicas: 1
        ingress:
          enabled: true
          hosts:
            - hubble.<::DOMAIN_INTERNAL::>
          annotations:
            external-dns.alpha.kubernetes.io/target: "internal-lb.<::DOMAIN_INTERNAL::>"
            cert-manager.io/cluster-issuer: acme-issuer
    operator:
      prometheus:
        metricsService: true
        enabled: true
        serviceMonitor:
          enabled: true
    prometheus:
      metricsService: true
      enabled: true
      serviceMonitor:
        enabled: true
    dashboards:
      enabled: true
    nodeinit:
      enabled: true
```

### How can we reproduce the issue?

use cilium wit mellanox 4 lx w/sriov with xdp enabled                                                                                                                                                                                                                                                         

### Cilium Version

Client: 1.17.3 3993bd06 2025-04-09T16:59:44+00:00 go version go1.23.8 linux/amd64
Daemon: 1.17.3 3993bd06 2025-04-09T16:59:44+00:00 go version go1.23.8 linux/amd64

### Kernel Version

Ubuntu 24.04.2 LTS (GNU/Linux 6.11.0-28-generic x86_64)

### Kubernetes Version

v1.33.1+rke2r1
containerd://2.0.5-k3s1

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
