### ISSUE TITLE
Cilium accepts namespaced CiliumNetworkPolicy with nodeSelector, but doesn't do anything

### ISSUE THREAD

**Issue by atykhyy** [cilium/cilium#40268]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.5 and lower than v1.18.0

### What happened?

I can create a namespaced `CiliumNetworkPolicy` object with an egress policy specifying a `nodeSelector` (e.g. `nodeSelector: {}`). Cilium sets the status of the policy object to Valid, but the egress policy specifying `nodeSelector` doesn't do anything. I believe Cilium is correct in not enforcing such an egress policy - it is illogical for a namespaced object to be applicable to nodes - but it might be more intuitive to flag the `CiliumNetworkPolicy` object as invalid rather than silently ignoring the policy.

### How can we reproduce the issue?

Apply
```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: test
  namespace: kube-system
specs:
- egress:
  - toCIDR:
    - 1.1.1.1/32
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
  nodeSelector: {}
```
to a Cilium cluster with host firewall and policy enforcement enabled. `kubectl get cnp -n kube-system test` will show it as valid. Then run 
```
kubectl exec -n kube-system -c cilium-agent cilium-12345 -- openssl s_client -connect 1.1.1.1:80
```
openssl will time out (assuming there is no other egress rule allowing the connection). For comparison,
```yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: test
specs:
- egress:
  - toCIDR:
    - 1.1.1.1/32
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
  nodeSelector: {}
```
allows the connection (openssl will show CONNECTED and complain about bad SSL exchange).

### Cilium Version

1.17.5

### Kernel Version

Linux aks-system-18391608-vmss000001 5.15.173.1-1.cm2 #1 SMP Sun Dec 8 02:17:37 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.31.3

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
