### ISSUE TITLE
Labels in network policy YAML are ignored

### ISSUE THREAD

**Issue by ashwinp** [cilium/cilium#4164]
### Title

Labels specified in the cilium network policy YAML are ignored.

### General Information

- Cilium version (run `cilium version`)
```
kubectl exec -it cilium-sq7xr -n kube-system -- cilium version
Client: 1.0.90 ac4b37c 2018-05-06T22:01:46+02:00 go version go1.9 linux/amd64
Daemon: 1.0.90 ac4b37c 2018-05-06T22:01:46+02:00 go version go1.9 linux/amd64
```
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
K8s

### How to reproduce the issue

1. Apply a cilium network policy with a label, say `testlabel` with value `abc`:
```
specs:
- endpointSelector:
    matchLabels:
      k8s:app: somecoolapp
      k8s:io.kubernetes.pod.namespace: someorganization
      k8s:version: "1"
  ingress:
  - fromEndpoints:
    - matchExpressions:
      - key: k8s:io.kubernetes.pod.namespace
        operator: Exists
    - matchLabels:
        reserved:host: ""
    toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
      rules:
        http:
        - {}
  - fromEndpoints:
    - matchExpressions:
      - key: k8s:io.kubernetes.pod.namespace
        operator: Exists
    - matchLabels:
        reserved:host: ""
    toPorts:
    - ports:
      - port: "7070"
        protocol: TCP
      rules:
        http:
        - {}
  labels:
  - key: testlabel
    value: abc
```
2. Check whether the label shows up in `cilium policy get`. It does not.
```
kubectl exec -it cilium-sq7xr -n kube-system -- cilium policy get -o json | grep abc
---empty---
```
