### ISSUE TITLE
Expose which policy is enforced on each node in k8s CNP status

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#4248]
hi,

right now the status field in cnp looks like this:
```
  status:
    nodes:
      minikube:
        enforcing: true
        lastUpdated: 2018-05-25T00:09:50.623919535Z
        localPolicyRevision: 408
        ok: true
```
this doesn't quite tell me which policies are in effect. it would be nice to have a field that can be used to identify which policies are being enforced on each node, maybe something like a map from namespace to cnp labels/annotations.
