### ISSUE TITLE
Document L7-aware egress to external host Example

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#4260]
Currently all L7-aware filtering examples show ingress rules, where the policy is applied on the HTTP/gRPC/Kafka service that is running inside the k8s cluster.  However, we should also have a document that shows an example were the service is running outside the cluster, but all clients are in the cluster and are locked down using egress policies. 

With Cilium 1.0 and earlier, that should be possible using a policy like: 

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "enable kafka-client1 to produce to topic empire-announce"
metadata:
  name: "rule1"
spec:
  endpointSelector:
    matchLabels:
      app: kafka-client1
 egress:
    - toPorts:
      - ports:
        - port: "9092"
           protocol: TCP
           rules:
           kafka:
           - role: "produce"
             topic: "empire-announce"
```

However, this policy is somewhat incomplete, as it technically would allow this client to talk to any external kafka broker and produce to empire-announce.   

With Cilium 1.1, I believe we should be able to include a CIDR in this rule, such that we limit this access specifically to the IP address(es) of the external Kafka brokers. 

For example: 

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "enable kafka-client1 to produce to topic empire-announce on external brokers that have IPs 1.1.1.10 and 1.1.1.20"
metadata:
  name: "rule1"
spec:
  endpointSelector:
    matchLabels:
      app: kafka-client1
 egress:
  - toCIDR:
    - 1.1.1.10/32
    - 1.1.1.20/32
    toPorts:
      - ports:
        - port: "9092"
          protocol: TCP
        rules:
          kafka:
          - role: "produce"
            topic: "empire-announce"
```
