### ISSUE TITLE
CI: runtime: install: cannot stat 'cilium-docker': No such file or directory

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4440]
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1009/

```
23:02:14     runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins'
23:02:14     runtime: for i in cilium-docker cilium-cni; do make -C $i install; done
23:02:14     runtime: make[2]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
23:02:14     runtime: install -m 0755 cilium-docker /usr/bin
23:02:14     runtime: install: cannot stat 'cilium-docker': No such file or directory
23:02:14     runtime: Makefile:22: recipe for target 'install' failed
23:02:14     runtime: make[2]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
23:02:14     runtime: make[2]: *** [install] Error 1
23:02:14     runtime: make[2]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
```

**Comment by tgraf** [comment]
It's not specific to `cilium-docker`:
```
    runtime: make[2]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
    runtime: make[2]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
    runtime: install -m 0755 -d /etc/cni/net.d
    runtime: install -m 0644 10-cilium-cni.conf /etc/cni/net.d
    runtime: install -m 0755 -d /opt/cni/bin
    runtime: install -m 0755 cilium-cni /opt/cni/bin
    runtime: install: 
    runtime: cannot stat 'cilium-cni'
    runtime: : No such file or directory
```

**Comment by tgraf** [comment]
This issue never reproduces using local ginkgo for me

**Comment by tgraf** [comment]
Confirmed that the files are not present before invoking make install:
```
    runtime: ./plugins:
    runtime: total 12
    runtime: drwxr-xr-x 1 vagrant vagrant 4096 Jun 10 04:18 cilium-cni
    runtime: drwxr-xr-x 1 vagrant vagrant 4096 Jun 10 04:18 cilium-docker
    runtime: -rw-r--r-- 1 vagrant vagrant  266 Jun 10 04:03 Makefile
    runtime:
    runtime: ./plugins/cilium-cni:
    runtime: total 28
    runtime: -rw-r--r-- 1 vagrant vagrant    68 Jun 10 04:03 10-cilium-cni.conf
    runtime: -rw-r--r-- 1 vagrant vagrant 12155 Jun 10 04:03 cilium-cni.go
    runtime: -rwxr-xr-x 1 vagrant vagrant  1156 Jun 10 04:03 cni-install.sh
    runtime: -rwxr-xr-x 1 vagrant vagrant   428 Jun 10 04:03 cni-uninstall.sh
    runtime: -rw-r--r-- 1 vagrant vagrant   573 Jun 10 04:03 Makefile
    runtime:
    runtime: ./plugins/cilium-docker:
    runtime: total 12
    runtime: drwxr-xr-x 1 vagrant vagrant 4096 Jun 10 04:03 driver
    runtime: -rw-r--r-- 1 vagrant vagrant 2951 Jun 10 04:03 main.go
    runtime: -rw-r--r-- 1 vagrant vagrant  425 Jun 10 04:03 Makefile
```

The compilation seems to succeed though:
```
    runtime: make[2]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
    runtime: go build -i -ldflags '-X "github.com/cilium/cilium/pkg/version.Version=1.0.90 02d0975b6 2018-06-10T04:03:11+00:00 go version go1.9.3 linux/amd64"' -tags lockdebug -o cilium-cni ./cilium-cni.go
    runtime: make[2]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
```
