### ISSUE TITLE
Label io.kubernetes.pod.namespace with source any does not overwrite default k8s:io.kubernetes.pod.namespace label

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4504]
The following policy does not work:
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "k8s-expose-across-namespace"
  namespace: ns1
spec:
  endpointSelector:
    matchLabels:
      name: leia
  ingress:
  - fromEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: ns2
        name: luke
```

We currently require the `k8s:` source to be specified explicitly:
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "k8s-expose-across-namespace"
  namespace: ns1
spec:
  endpointSelector:
    matchLabels:
      name: leia
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: ns2
        name: luke
```

Example yamls:
```
apiVersion: v1
kind: Namespace
metadata:
  name: ns1
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: leia-deployment
  namespace: ns1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: leia
      namespace: ns1
    spec:
      containers:
      - name: leia-container
        image: docker.io/cilium/json-mock
---
apiVersion: v1
kind: Service
metadata:
  name: leia
  namespace: ns1
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    name: leia
---
apiVersion: v1
kind: Pod
metadata:
  name: luke-pod
  namespace: ns2
  labels:
    name: luke
spec:
  containers:
  - name: luke-container
    image: docker.io/cilium/json-mock
---
apiVersion: v1
kind: Pod
metadata:
  name: vader-pod
  namespace: ns2
  labels:
    name: vader
spec:
  containers:
  - name: vader-container
    image: docker.io/cilium/json-mock
```
