### ISSUE TITLE
Unable to start Vagrant Developer VM in Kubernetes mode

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#5082]
I have a branch checked out with minimal changes from master (I can try reproducing this on master if needed)

At the root of the Cilium repository, run the following:
```
NFS=1 K8S=1 ./contrib/vagrant/start.sh
```

The provisioning step fails:
```
    k8s1: [Service]
    k8s1: ExecStart=/usr/bin/kube-proxy \
    k8s1:   --cluster-cidr=10.0.0.0/10 \
    k8s1:   --kubeconfig=/var/lib/kube-proxy/kube-proxy.kubeconfig \
    k8s1:   --proxy-mode=iptables \
    k8s1:   --v=2
    k8s1: 
    k8s1: Restart=on-failure
    k8s1: RestartSec=5
    k8s1: 
    k8s1: [Install]
    k8s1: WantedBy=multi-user.target
    k8s1: Created symlink /etc/systemd/system/multi-user.target.wants/kube-proxy.service -> /etc/systemd/system/kube-proxy.service.
    k8s1: Failed to restart kube-proxy.service: Unit containerd.service not found.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
