### ISSUE TITLE
[RFC] memcached L7 policy 

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#5333]
This is the issue to track discussion about L7 Memcached policy format and use cases. It focuses on binary memcache protocol, but use cases will be translated to text protocol

My proposal is: 

### API structure
Memcache rules should be included in `pkg.policy.api.L7Rules` as an additional L7 rule slice.

memcache rule should should have following fields:
`opCode`: string specifying memcached opcode OR opcodes group. 
`key`: string specifying regular expression that request key should match to in order for rule to be in effect for this request.

### opcode groups
opcode groups group opcode into logical sets which make sense to have from user perspective: instead of specifying several opcode rules for each `get` operation in this form:
```
[{ "opCode": "get"},{"opCode":"getq"},{"opCode":"getk"},{"opCode":"getkq"}]
```
user may specify one policy rule to cover all get variants:
```
[{"opCode":"readGroup"}]
```
Of course user still can define all opcodes separately if he needs finer-grained policies.

Proposed groups are:
```
readGroup: ["get", "getq", "getk", "getkq"]

writeGroup: ["set", "add", "replace", "delete", "increment",
                      "decrement", "append", "prepend", "setq", "addq",
                      "replaceq", "deleteq", "incrementq", "decrementq",
                      "appendq", "prependq", "touch", "gat", "gatq"]

flushGroup: ["flush", "flushq"]
```

Range opcodes (0x30 through 0x3c) are not supported by memcache server (per https://github.com/memcached/memcached/blob/master/protocol_binary.h#L118), so I excluded them from proposed grouping.

**Comment by aanm** [comment]
I think we should support both.

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l7-rule"
spec:
  endpointSelector:
    matchLabels:
      app: myService
  ingress:
  - toPorts:
    - ports:
      - port: '80'
        protocol: TCP
      rules:
        memcached:
        - opCode: "get"
          key: "bar"
        - opCode: "get"
          key: "foo"
        - opGroup: "read"
          key: "foo"
```

As `get` belongs to `opGroup: Read`, the `get: foo` won't matter and can be merged into the `opGroup: read` rule as they share the same key.

**Comment by tgraf** [comment]
> [{"opCode":"readGroup"}]

For Kafka we used the term role. This also avoids a potential conflict if we use a group name now that eventually becomes an op code in the official spec.

```
rules:
  memcached:
    -role: "read"
     key: "bar"
```

> key: string specifying regular expression that request key should match to in order for rule to be in effect for this request.

We should introduce a separate field for the key name variants so we can ensure efficient implementation later on:

`keyExact:`
`keyPrefix:`
`keyRegexp:`
