### ISSUE TITLE
Documentation: update HTTPRule examples to have correct capitalization in examples

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#5419]
Starting with K8s 1.11, whose client libraries Cilium uses,  variations of 'http' w.r.t. capitalization are not accepted:

https://kubernetes.io/docs/setup/release/notes/#urgent-upgrade-notes

I.e., the following policy should use `http` instead of `HTTP` for the http rules:

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l7-rule"
spec:
  endpointSelector:
    matchLabels:
      app: foobar
  ingress:
  - toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        HTTP:
        - method: GET
          path: "/$"
          headers:
          - "X-My-Header: true"
```

Update the examples here to reflect this requirement: https://github.com/cilium/cilium/tree/master/examples/policies/l7
