### ISSUE TITLE
Cilium service drop connection after 2minutes

### ISSUE THREAD

**Issue by eloycoto** [cilium/cilium#5825]
Hi, 

On Cilium master, when a long lived connection happens from a pod to a service IP connection drops after 2 min. 

Ways to reproduce: 

Apply the following manifest:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: netperf-client
  labels:
    id: netperf-client
    zgroup: testapp
spec:
  containers:
  - name: netperf
    image: tgraf/netperf
---
apiVersion: v1
kind: Service
metadata:
  name: netperf-service
spec:
  ports:
  - port: 12865
  selector:
    name: netperf-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: netperf-server
spec:
  replicas: 2
  template:
    metadata:
      name: netperf-server
      labels:
        id: app1
        name: netperf-server
        zgroup: testapp
    spec:
      containers:
      - name: netperf
        image: tgraf/netperf
```

Exec the following:
```
kubectl exec -ti netperf-client -- time netperf -l 30000 -t TCP_STREAM -H ${netperf-service-IP}
```

After two minutes and 11 seconds the connection is drop:

```
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ kubectl exec -ti netperf-client -- time netperf -l 30000 -t TCP_STREAM -H 172.20.0.167
MIGRATED TCP STREAM TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 172.20.0.167 (172.20.) port 0 AF_INET
netperf: send_omni: connect_data_socket failed: Operation timed out
Command exited with non-zero status 1
real    2m 9.40s
user    0m 0.00s
sys    0m 0.00s
```

Monitor log: 
```


<- endpoint 39609 flow 0x477ff0c7 identity 23855->0 state new ifindex 0: 10.10.1.182:33695 -> 10.98.225.106:34679 tcp SYN
-> stack flow 0x477ff0c7 identity 23855->2 state established ifindex 0: 10.10.1.182:33695 -> 10.98.225.106:34679 tcp SYN
-> 0: 10.10.1.182:33695 -> 10.98.225.106:34679 tcp SYN
<- endpoint 39609 flow 0xed671294 identity 23855->0 state new ifindex 0: f6:4f:a2:ed:88:50 -> da:d1:b4:75:8b:b0 ARP
-> lxc8d9fc8dae525: da:d1:b4:75:8b:b0 -> f6:4f:a2:ed:88:50 ARP
```

Pod to Pod works ok.
@tgraf is trying to reproduce in 1.2 

Actions: 

- [ ] Fix the issue
- [ ] Add a nightly test that test long lived connections using a service.  (Eloy)

Issue also found on PR https://github.com/cilium/cilium/pull/5765 where no persistent connection, but connection cannot be established correctly.
