### ISSUE TITLE
Cilium DaemonSet is not scheduled on all nodes

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#6263]
If you are experiencing issues with Cilium not being scheduled on all nodes, make sure if the Cilium DaemonSet contains the necessary tolerations for the taints in the nodes where Cilium is not being scheduled.

By default Cilium DaemonSet should have the following tolerations:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cilium
  namespace: kube-system
spec:
...
  template:
...
    spec:
...
      tolerations:
        - effect: NoSchedule
          key: node.kubernetes.io/not-ready
          operator: "Exists"
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: "Exists"
        - effect: NoSchedule
          key: node.cloudprovider.kubernetes.io/uninitialized
          operator: "Exists"
        # Mark cilium's pod as critical for rescheduling
        - key: CriticalAddonsOnly
          operator: "Exists"
```

If the node has a taint that is not tolerated by Cilium DaemonSet, in the following example `key=master, effect: NoSchedule`, Cilium won't be scheduled in that node.

```yaml
apiVersion: v1
kind: Node
spec:
...
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoSchedule
    key: dedicated
    value: master
```

To make Cilium schedulable in this node, we need to add the missing tolerations to the DaemonSet

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cilium
  namespace: kube-system
spec:
...
  template:
...
    spec:
...
      tolerations:
        - effect: NoSchedule
          key: node.kubernetes.io/not-ready
          operator: "Exists"
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: "Exists"
        - effect: NoSchedule
          key: node.cloudprovider.kubernetes.io/uninitialized
          operator: "Exists"
        # Mark cilium's pod as critical for rescheduling
        - key: CriticalAddonsOnly
          operator: "Exists"
        - key: dedicated
          operator: "Equals"
          value: "master"
          effect: NoSchedule
```
