### ISSUE TITLE
Deploy cilium policies with kubernetes without specifying pod namespace

### ISSUE THREAD

**Issue by warbaque** [cilium/cilium#6272]
## Proposal / RFE

I'd like to handle policies between mesos, kubernetes and docker, preferrably using kubernetes to apply cnp's. Currently whenever you apply policies, `k8s:io.kubernetes.pod.namespace` is added to matchLabels by default.

Option to deploy rules without pod namespace would be nice.

**policy.yaml**

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "example policy"
metadata:
  name: "example-policy"
spec:
  endpointSelector:
    matchLabels:
      'id': example-server
  ingress:
  - fromEndpoints:
    - matchLabels:
        'id': example-client
    toPorts:
    - ports:
      - port: "8181"
        protocol: TCP

```

**generated policy**

```
[
  {
    "endpointSelector": {
      "matchLabels": {
        "k8s:io.kubernetes.pod.namespace": "default",
        "any:id": "example-server"
      }
    },
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "any:id": "example-client",
              "k8s:io.kubernetes.pod.namespace": "default"
            }
          }
        ],
        "toPorts": [
          {
            "ports": [
              {
                "port": "8181",
                "protocol": "TCP"
              }
            ]
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "io.cilium.k8s.policy.name",
        "value": "example-policy",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.namespace",
        "value": "default",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.derived-from",
        "value": "CiliumNetworkPolicy",
        "source": "k8s"
      }
    ]
  }
]
```
