### ISSUE TITLE
toFQDNs with no IP data do not block traffic

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#6292]
When a toFQDN rule has L4/L7 sections, it will incorrectly interpret the L3 as a wildcard allow-all. This means it isn't really enforcing what one expects. When IPs are inserted into toCIDRSet the enforcement is correct.
This policy works incorrectly with our minikube GSG:
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: rebel-escape
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      any:org: alliance
  egress:
  - toEndpoints:
    - matchLabels:
       "k8s:io.kubernetes.pod.namespace": kube-system
       "k8s:k8s-app": kube-dns
  - toFQDNs:
      - matchName: "notasubdomain.cilium.io"
    toPorts:
      - ports:
        - port: "80"
```
Both of these work when they should not (the port is enforced, as would a L7 HTTP rules)
`kubectl exec xwing -- curl -s cilium.io`
`kubectl exec xwing -- curl -s google.com`
