### ISSUE TITLE
Endpoint build trigger for endpoint already waiting to be built triggers warning

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6793]
```
2019-01-21T10:47:27.592006537Z level=debug msg="Skipped invalid state transition to waiting-to-regenerate due to: Triggering synchronous endpoint regeneration while syncing state to host" code=Warning containerID=f5678a1465 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=83 endpointState=waiting-to-regenerate identity=34866 ipv4=10.10.1.155 ipv6="f00d::a0a:100:0:f26b" k8sPodName=monitoring/prometheus-core-5c9fbf5cc6-h874w policyRevision=0 subsys=endpoint type=0
2019-01-21T10:47:27.592075407Z level=warning msg="Endpoint in inconsistent state" endpointID=83 endpointState=waiting-to-regenerate subsys=daemon
```

**Comment by tgraf** [comment]
Possibly related:
```
    log:
    - code: Warning
      message: 'Skipped invalid state transition to ready due to: Completed endpoint
        regeneration with no pending regeneration requests'
      state: waiting-to-regenerate
      timestamp: "2019-01-26T21:12:23Z"
```
[cilium-sysdump-20190126-131816.zip](https://github.com/cilium/cilium/files/2799505/cilium-sysdump-20190126-131816.zip)
