### ISSUE TITLE
Test upgrade from 1.2.7 to 1.4.0

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6852]
- [x] Test the upgrade from 1.2.7 to 1.4.0
- [x] Validate FQDN upgrade
   - [x] Work with @raybejjani to have an FQDN policy loaded throughout the upgrade.
   - [x] Upgrade to 1.4.0 with the poller enabled and make sure that FQDN policy continues to work
- [x] Document release notes required for upgrade

**Comment by joestringer** [comment]
One particular task necessary for upgrade if we're going to support FQDN poller with v1.4: https://github.com/cilium/cilium/issues/6870

**Comment by joestringer** [comment]
In my local microk8s environment, I tested this v1.2 DS (docker path updated):

[cilium-1.2-with-k8s-1.11-ds.yaml.txt](https://github.com/cilium/cilium/files/2823864/cilium-1.2-with-k8s-1.11-ds.yaml.txt)

Against this v1.4 DS (docker path updated, added the `--tofqdns-enable-poller` option to the arguments):

[cilium-1.4-with-k8s-1.13-ds.yaml.txt](https://github.com/cilium/cilium/files/2823865/cilium-1.4-with-k8s-1.13-ds.yaml.txt)

With this monkey:

https://github.com/cilium/chaos-monkeys/tree/master/monkeys/et-call-home-fqdn-policy

This includes the DNS proxy policy:

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: chaos-test-et-call-fqdn-{{ .Values.basename }}
spec:
  endpointSelector:
    matchLabels:
      name: {{ .Values.name }}
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: '53'
        protocol: ANY
      rules:
        dns:
          - matchName: {{ .Values.fqdn }}
  - toFQDNs:
      - matchName: {{ .Values.fqdn }}
  - toCIDR:
    - "1.1.1.1/32"
```

The monkey was OK on v1.2.7.

Upgrade occurred at 01:09 UTC:

```
[Feb  1 17:09:54 PST] cilium $ kubectl apply -f cilium-1.4-with-k8s-1.13-ds.yaml 
```

Hit two failures during upgrade, most recent is roughly 4-5 minutes later:

[fqdn-failure-2019-02-02T01:14:18.0000000000Z.txt](https://github.com/cilium/cilium/files/2823878/fqdn-failure-2019-02-02T01.14.18.0000000000Z.txt)

Latest successful pod started around 2019-02-02T01:15:37.141119228Z. Pods were happy after that.
