### ISSUE TITLE
operator crash on invalid CNP

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6910]
The following malformed policy crashes the operator:

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-ingress-cluster
spec:
  egress:
  - toEndpoints:
    - matchLabels:
        'k8s:io.kubernetes.pod.namespace': {}
  endpointSelector:
    matchLabels: {}
  ingress:
  - fromEndpoints:
    - matchLabels:
        'k8s:io.kubernetes.pod.namespace': {}
```
