### ISSUE TITLE
Kubernetes nodes intermittently going into NotReady status on Cilium 1.3.2 when containerd v >= 1.2.0 is used as CRI

### ISSUE THREAD

**Issue by utkuozdemir** [cilium/cilium#6954]
## Bug report

**General Information**

- Cilium version `1.3.2`
- Kernel version `Linux loyal-foal 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use: `Kubernetes 1.12.2` with `Containerd 1.2.0`
- Sample artifact:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: simple-nginx
  template:
    metadata:
      labels:
        app: simple-nginx
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:stable-alpine
        name: simple-nginx
```
- System dump: 
[cilium-sysdump-20190206-152441.zip](https://github.com/cilium/cilium/files/2836696/cilium-sysdump-20190206-152441.zip)

**How to reproduce the issue**

Cilium version 1.3.2, when used on a cluster with Containerd >=1.2.0 causes nodes to intermittently go into `NotReady` status.

1. Set up a cluster with the following components: Kubernetes 1.12.2, Containerd 1.2.0 (also reproducible in 1.2.2) Cilium 1.3.2 configured to use Containerd socket as described [here](https://blog.scottlowe.org/2018/09/06/kubernetes-cilium-containerd-using-kubeadm/).
2. Apply the deployment above.
3. Scale the deployment to many instances, such as `kubectl scale deployment simple-nginx --replicas 50`
4. Watch nodes in the meantime via `kubectl get node -o wide --watch`. The workers that get the pods scheduled on them will go into `NotReady` status, with the description `container runtime is down`. They will go back to `Ready` state after some short time.
5. Downgrade the Cilium version to 1.3.0 (with cleaning Cilium state enabled in configmap), try again - issue is not reproducible anymore.
6. Upgrade back to Cilium 1.3.2, scale down the deployment to 1. Scale it back up to 50 - issue reappears.
7. Downgrade Containerd to version 1.1.4 - issue again is not reproducible anymore - Cilium 1.3.2 works fine with Containerd 1.1.4.
