### ISSUE TITLE
FQDN policy ineffective if there is no L7 DNS rule

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#7109]
With a policy like this, and the default YAMLs in Cilium v1.4, FQDN allow policy is ineffective:

```
apiVersion: "cilium.io/v2"                                                                                                                                                                                                                                     
kind: CiliumNetworkPolicy                                                       
metadata:                                                                       
  name: "to-fqdn"                                                               
spec:                                                                           
  endpointSelector:                                                             
    matchLabels:                                                                
      app: test-app                                                             
  egress:                                                                       
    - toEndpoints:                                                              
      - matchLabels:                                                            
          "k8s:io.kubernetes.pod.namespace": kube-system                        
          "k8s:k8s-app": kube-dns                                                                                           
    - toFQDNs:                                                                  
        - matchName: "my-remote-service.com" 
```

Currently this will show up as "Policy denied" in the `cilium monitor` output, with the destination identity as "2", when the destination should be governed by FQDN policy.

This is because it does not enable the proxy via L7 DNS rule, and the poller is disabled by default.

It would be good to have some way to detect this misconfiguration and signal it.

Potential guard-rails:
* Consider within a policy, if there is `toFQDNs`, poller is disabled, and there is no `toPorts.rules.dns` rule,  reject the policy at load time
* Alternatively add a controller that periodically scans through the policy repository and validates that either for every identity that is selected by a rule with `toFQDNs`, that there is:
  * Poller enabled, or
  * Also a rule that selects that identity with an L7 DNS rule
