### ISSUE TITLE
ICMP does not work for k8s service

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#739]
When installing a simple service like this:
```
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: demo
    role: backend
spec:
  ports:
  - port: 80
  selector:
    app: demo
    role: backend
```

This will result in a L4 loadbalancer to be installed which will only match packets on port 80. Any ICMP packets will not match the installed loadbalancer and are thus dropped. This is expected behaviour.
