### ISSUE TITLE
Use etcd proxy for clustermesh

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#7405]

**Comment by eloycoto** [comment]
Hi!

I was playing with etcd-proxy and here an small summary about the things that
can be done.

To install etcd-proxy we only need to apply the following deployment, that it's
easy part:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-proxy
  namespace: kube-system
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: etcd-proxy
        etcd_cluster: cilium-etcd
        io.cilium/app: etcd-proxy
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - /usr/local/bin/etcd
        - grpc-proxy
        - start
        - --advertise-client-url=https://cilium-etcd-proxy.kube-system.svc:2379
        - --listen-addr=0.0.0.0:2379
        - --resolver-prefix=https://cilium-etcd-proxy.kube-system.svc:2379
        - --resolver-ttl=60
        - --endpoints=https://cilium-etcd-client.kube-system.svc:2379
        - --data-dir=/var/etcd/data
        - --cacert=/etc/etcdtls/operator/etcd-tls/etcd-client-ca.crt
        - --cert=/etc/etcdtls/operator/etcd-tls/etcd-client.crt
        - --key=/etc/etcdtls/operator/etcd-tls/etcd-client.key
        - --trusted-ca-file=/etc/etcdtls/member/server-tls/server-ca.crt
        - --cert-file=/etc/etcdtls/member/server-tls/server.crt
        - --key-file=/etc/etcdtls/member/server-tls/server.key
        - --debug=true
        image: quay.io/coreos/etcd:v3.3.11
        imagePullPolicy: IfNotPresent
        name: etcd
        ports:
        - containerPort: 2380
          name: server
          protocol: TCP
        - containerPort: 2379
          name: client
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/etcdtls/member/peer-tls
          name: member-peer-tls
        - mountPath: /etc/etcdtls/member/server-tls
          name: member-server-tls
        - mountPath: /etc/etcdtls/operator/etcd-tls
          name: etcd-client-tls
      volumes:
      - name: member-peer-tls
        secret:
          defaultMode: 420
          secretName: cilium-etcd-peer-tls
      - name: member-server-tls
        secret:
          defaultMode: 420
          secretName: cilium-etcd-server-tls
      - name: etcd-client-tls
        secret:
          defaultMode: 420
          secretName: cilium-etcd-client-tls
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd-proxy
    etcd_cluster: cilium-etcd-proxy
  name: cilium-etcd-proxy
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd-proxy
    etcd_cluster: cilium-etcd
  sessionAffinity: None
  type: ClusterIP
```

This set-up has two things that need to be changed:

1) Well-know identities in Cilium.

The main reason is if we want to use the proxy from operator we need to change
the configmap, so Cilium DS will be affected. I think that can be ok to have
the etcd-proxy as well-know identity.

2) Secure connections between endpoints and certificates handling:

a) Use the same certicates as etcd-operator and add a new domain in
the following lines:
https://github.com/cilium/cilium-etcd-operator/blob/master/certs/certs.go#L131-L136

b) Install a new certificate for the proxy and use the new certificate from
cilium-config configMap, this is more trouble for users, but I think that is
the best way.

Around the issues that can happen:

- Lack of monitoring in the proxy. I didn't found a way (yet) to know:
	- cache usage and metrics.
	- The number of backends endpoints that the proxy has.

- Using the endpoints as the cilium-etcd-client service works for me, deleted
the endpoints and all works as I expected. Maybe there is any corner case that
I didn't catch yet.

- Delay on events. Issue https://github.com/etcd-io/etcd/issues/9988

**Deployment:**

For me there is two situations here:

1) Etcd-operator:

I think that this deployment should be part of etcd-operator, an env variable
that defines if etcd-proxy should be deployed. (Obviously the livenessProbe,
etc.. need to be adjust)

This way will help use to scale the proxy to the right numbers, 3 ETCD nodes-1
proxy.

2) Docs:

For some users this will be an addition for scale their ETCD databases and be
able to scale to more nodes, so a doc about how to install and how to monitor
will be helpful for them.


I'm not sure about next steps here, do we want to test this in a real-scale
cluster to see the benefits and make a decision about next steps?
