### ISSUE TITLE
CEP output has been changed

### ISSUE THREAD

**Issue by ruigulala** [cilium/cilium#7511]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.4.90  go version go1.12.1 linux/amd64
Daemon: 1.4.90  go version go1.12.1 linux/amd64
```
- Kernel version (run `uname -a`)
```
Darwin Ruis-MBP-2.lan 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
releases.cilium.io/tools/cluster-diagnosis.zip &&
python cluster-diagnosis.zip sysdump` and then attach the generated zip file)

**How to reproduce the issue**
```
1. kubectl create ns starwars

2. kubectl create -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/minikube/http-sw-app.yaml  -n starwars

3. Deploy the following policy to starwars namespace

4. kubectl get cep -oyaml -n starwars
```
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: to443
spec:
  egress:
  - toPorts:
    - ports:
      - port: "443"
        protocol: TCP
  endpointSelector:
    matchLabels: {}
```
Now, the cilium:latest has the following output.
```
   policy:
      egress:
        allowed:
        - dest-port: 443
          identity-labels:
            reserved:unknown: ""
          protocol: 6
        enforcing: true
      ingress:
        enforcing: false
```
Previously, we have the following output.
```
    policy:
      egress:
        allowed:
        - dest-port: 443
          identity: 1
          identity-labels:
            reserved:host: ""
          protocol: 6
        - dest-port: 443
          identity: 2
          identity-labels:
            reserved:world: ""
          protocol: 6
        - dest-port: 443
          identity: 3
          identity-labels:
            reserved:unmanaged: ""
          protocol: 6
        - dest-port: 443
          identity: 4
          identity-labels:
            reserved:health: ""
          protocol: 6
        - dest-port: 443
          identity: 5
          identity-labels:
            reserved:init: ""
          protocol: 6
...
```
