### ISSUE TITLE
mounting /lib/modules fails when deploying new Cilium DaemonSet in specific environments

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#7785]
In RC versions of Cilium v1.5, the mounting of `/lib/modules` may fail because the path contains a symlink. 

When deploying Cilium with the following `volume` and `volumeMount` configuration in the Cilium DaemonSet from https://raw.githubusercontent.com/cilium/cilium/v1.5.0-rc4/examples/kubernetes/1.10/cilium-ds.yaml

```
volumeMounts:
...
- mountPath: /lib/modules
          name: lib-modules
          readOnly: true
...
volumes:
      - hostPath:
          path: /lib/modules
          type: Directory
        name: lib-modules
...
```

And deploying the DaemonSet, the mounting of the volume fails:

```
  Warning  FailedMount            1m (x9 over 3m)  kubelet,<IP redacted>  MountVolume.SetUp failed for volume "lib-modules" : hostPath type check failed: /lib/modules is not a directory
```

`/lib/modules` actually symlinks to the following directory:

```
/usr/lib64/modules/4.11.9-coreos/
```

We need to notify users in the upgrade documentation that `/lib/modules` will not always be able to be mounted by Cilium, and recommend them to point to the path which `/lib/modules` resolves. This could be done via a `ConfigMap` parameter and then using that configuration value for the mount (possibly)?

I found the following link in the Kubernetes documentation, but we want to use the actual value from the ConfigMap to specify the volume.
