### ISSUE TITLE
AWS toGroups policy fails due to missing CA certs in cilium operator image

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#7833]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
1.4.4

- Kernel version (run `uname -a`)
4.15
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
EKS

**How to reproduce the issue**

Generally following this guide: https://docs.cilium.io/en/v1.4/gettingstarted/aws/  

Note, a restart of cilium-operator is required after creating the cilium-aws secret in the above guide. 

Example policy 

```
---
kind: CiliumNetworkPolicy
apiVersion: cilium.io/v2
metadata:
  name: xwing-access-hoth
spec:
  endpointSelector:
    matchLabels:
      class: xwing
  egress:
  - toPorts:
    - ports:
      - port: '80'
        protocol: TCP
    toGroups:
    - aws:
        securityGroupsIds:
        - 'sg-07d6483eed5d8a368'
```

Error in cilium operator log: 

```
level=error msg="Cannot create derivative rule. Installing deny-all rule." ciliumNetworkPolicyName=xwing-access-hoth error="Cannot retrieve data from AWS provider: Cannot retrieve aws information: RequestError: send request failed\ncaused by: Post https://ec2.us-west-2.amazonaws.com/: x509: certificate signed by unknown authority" k8sNamespace=aws-test subsys=Groups
```

Workaround:    Built an image using 1.4.4 branch, but with the following change to cilium operator Dockerfile (I'm sure a cleaner way would be to continue to use scratch image but copy files over to scratch image): 

```
diff --git a/cilium-operator.Dockerfile b/cilium-operator.Dockerfile
index f18a00f..9c8aa7b 100644
--- a/cilium-operator.Dockerfile
+++ b/cilium-operator.Dockerfile
@@ -7,8 +7,9 @@ ARG V
 RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o cilium-operator
 RUN strip cilium-operator
 
-FROM scratch
+FROM alpine:3.6
 LABEL maintainer="maintainer@cilium.io"
+RUN apk add -U --no-cache ca-certificates
 COPY --from=builder /go/src/github.com/cilium/cilium/operator/cilium-operator /usr/bin/cilium-operator
 WORKDIR /
 CMD ["/usr/bin/cilium-operator"]
```
