### ISSUE TITLE
Benchmark identity churn

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#8063]
Assess the impact of identity churn upon operation of Cilium.

* At least one local endpoint
* Apply policy that selects the endpoint, allowing traffic to/from identities with a given label
  * Initially inject 1 rule, can later attempt a higher baseline number
* Inject a baseline number of unique identities into the kvstore
* Vary the number of identities in the kvstore at a particular rate
  * Test 1: Set the baseline + varied identities to *not be* selected by the policy rule
  * Test 2: Set the baseline + varied identities to *be* selected by the policy rule
* Observe {CPU consumed, policy generation time}

**Comment by joestringer** [comment]
Target pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: pause
  labels:
    name: pause
spec:
  containers:
  - name: pause
    image: "gcr.io/google_containers/pause"
    ports:
    - containerPort: 80
```
