### ISSUE TITLE
policy: From clauses are not combined correctly

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#8231]
The following `NetworkPolicy` is not converted correctly:

* The list of from clauses are combined with an AND instead of an OR

```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: foo
spec:
  egress:
  - {}
  ingress:
  - from:
    - ipBlock:
        cidr: 1.0.0.0/26
    - ipBlock:
        cidr: 2.0.0.64/26
    - namespaceSelector:
        matchLabels:
          name: blah
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```
