### ISSUE TITLE
k8s CNP delete event metric doesn't work

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#8275]
When using prometheus integration and the standard Cilium grafana dashboard on master today (1.6 cycle), the event metric for CNP delete does not get incremented when a CNP is deleted.

**Comment by joestringer** [comment]
Documentation for setting up metrics:

http://docs.cilium.io/en/latest/configuration/metrics/#cilium-as-a-kubernetes-pod

I've been using these with microk8s (http://docs.cilium.io/en/latest/gettingstarted/microk8s/), but it should work equally well with minikube (http://docs.cilium.io/en/latest/gettingstarted/minikube/) or any real k8s cluster.

**Comment by neoakris** [comment]
Did you apply an optional configmap and bounce the pod to enable metrics?

enable-cilium-metric-export.cilium-metrics-config.cm.yaml
```
#This is an optional configmap listed in pods in the cilium-cni daemonset.
#If you apply this CM and then reboot all cilium-cni pods 'kubectl delete pods -l=k8s-app=cilium -n=kube-system'
#Then cilium pods will start exporting prometheus metrics
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-metrics-config
  namespace: kube-system
data:
  prometheus-serve-addr: ":9090"
```
You can exec into a cilium cni pod
run apt-get update
apt-get install curl
PodShell# curl localhost:9090/metrics

to verify
