### ISSUE TITLE
Add a  poddisruptionbudget manifest for the etcd-cluster

### ISSUE THREAD

**Issue by JrCs** [cilium/cilium#8336]
## Proposal

Can you create a poddisruptionbudget manifest like the one below for the etcd-cluster to avoid losing etcd quorum when draining nodes for example ?

```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: etcd
  name: cilium-etcd-cluster
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: etcd
```
