### ISSUE TITLE
Can I combine toPorts and fromCIDR to whitelist external IP addresses for specified ports?

### ISSUE THREAD

**Issue by moredure** [cilium/cilium#8426]
I am using DigitalOcean's CiliumNetworkPolicy, and trapped into not able to use cidr with both toPorts or ports (using default kubernetes network policy resource definition) 
```
---
kind: CiliumNetworkPolicy
apiVersion: "cilium.io/v2"
metadata:
  name: web-allow-external1
spec:
  endpointSelector:
    matchLabels:
      app: nginx
  ingress:
    - fromCIDR:
        - "85.238.106.86/32"
      fromPorts:
        - ports:
            - port: "6379"
              protocol: TCP
  egress:
    - {}
```

**Comment by mikefaraponov** [comment]
Also I expect that in such cases
```
kind: CiliumNetworkPolicy
apiVersion: "cilium.io/v2"
metadata:
  name: web-allow-external2
spec:
  endpointSelector:
    matchLabels:
      app: nginx
  ingress:
    - fromCIDR:
          - "85.238.106.89/32"
      fromPorts:
      - ports:
          - port: "6379"
            protocol: TCP
    - fromCIDR:
        - "62.16.0.182/32"
      fromPorts:
        - ports:
            - port: "80"
              protocol: TCP
  egress:
    - {}
```
I shouldn't be able to access 6379 from both specified ips
