### ISSUE TITLE
Ability to restrict listener addrs

### ISSUE THREAD

**Issue by trevex** [cilium/cilium#8473]
## Proposal / RFE

**Is your feature request related to a problem?**
Cilium uses the host network and therefore listens by default on all interfaces. This is even more troublesome if used in conjunction with MetalLB as those ports will be accessable on all announced public IPs.

The prometheus listener addr can be trimmed down with the environment variables as follows (instead of using the configmap):
```
        - name: CILIUM_PROMETHEUS_SERVE_PORT
          value: "9090"
        - name: CILIUM_PROMETHEUS_SERVE_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: CILIUM_PROMETHEUS_SERVE_ADDR
          value: $(CILIUM_PROMETHEUS_SERVE_HOST):$(CILIUM_PROMETHEUS_SERVE_PORT)
```

However the health listener can not be changed, e.g. cilium logs:
```
level=info msg="Serving cilium health at http://[::]:4240" subsys=health-server
```
On the host we can look at all listeners related to cilium:
```
sudo netstat -ltnp | grep cilium
tcp        0      0 127.0.0.1:39435         0.0.0.0:*               LISTEN      37403/cilium-health 
tcp        0      0 127.0.0.1:42971         0.0.0.0:*               LISTEN      35349/cilium-node-m 
tcp        0      0 127.0.0.1:39585         0.0.0.0:*               LISTEN      33053/cilium-agent  
tcp6       0      0 :::9090                 :::*                    LISTEN      33053/cilium-agent  
tcp6       0      0 :::4240                 :::*                    LISTEN      37403/cilium-health 
tcp6       0      0 :::42391                :::*                    LISTEN      33053/cilium-agent 
```
This shows that not only the health is listening on all IPs, but the `cilium-agent` has a second port it is listening on.

**Describe the solution you'd like**
I would expect cilium to not expose services other than on either localhost or the nodeIP/status.hostIP to reduce side effects on announced LoadBalancerIPs.
