### ISSUE TITLE
The ability to not deny DNS requests instead restrict it with empty response

### ISSUE THREAD

**Issue by fentas** [cilium/cilium#8697]
I have a namespace which should only be able to call everything within its namespace, be called from and into (sidecars) istio and has also `virtualservice` (api.project.in) defined enabling calling an API within another namespace. Resulting in the following `cnp`.

```
specs:
- endpointSelector: {}
  ingress:
  - fromEndpoints:
    - {}
- egress:
  - toEndpoints:
    - {}
  endpointSelector: {}
- endpointSelector: {}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: istio-system
- egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: istio-system
  endpointSelector: {}
- egress:
  - toEndpoints:
    - matchLabels:
        project.com/name: api
        k8s:io.kubernetes.pod.namespace: project
  endpointSelector: {}
- egress:
  - toCIDR:
    - 169.254.25.10/32
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchName: istio-pilot.istio-system.svc.cluster.local
        - matchName: zipkin.istio-system.svc.cluster.local
        - matchPattern: '*.35e787449149ac435252baa5a526aeb5.svc.cluster.local'
        - matchName: 'api.project.in'
  endpointSelector: {}
```

If the DNS config within the pod template spec left untouched the `following` will happen.
- (this is not consistent, not sure why) sidecar container can't talk to `istio-pilot.istio-system` because it will begin with `istio-pilot.istio-system.35e787449149ac435252baa5a526aeb5.svc.cluster.local`. This will be denied and the complete dns query will be dropped instead of going through all dns resolve.conf `search` domains. So after adding `matchPattern: '*.*.35e787449149ac435252baa5a526aeb5.svc.cluster.local'` rule this will work.
- If I now call `api.project.in` this will be also be dropped because dns will first try to go through all domains defined in the search option. `api.project.in.35e787449149ac435252baa5a526aeb5.svc.cluster.local`. This would now require to allow the complete chain until the full fqdn is resolved. If we now want to allow multiple endpoints `*.project.in` this will resolve into opening up all dns requests. This leaves (as far as I can see it) two options.
   - setting `ndots:2` because we have luckily two dots within our `vs` endpoints.
   - or write own dns resolver

---

_Ref. Slack thread_ https://cilium.slack.com/archives/C1MATJ5U5/p1564106142053800?thread_ts=1563184297.437800&cid=C1MATJ5U5
As mentioned by `Ray` in slack there is a `--tofqdns-dns-reject-response-code` option but this has no `succeed` respond code.
__edit__ have to try if maybe `nameError` will work.
