### ISSUE TITLE
Allow CiliumNetworkPolicy to specify a list of rules

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#900]
@tgraf It would be nice to be able to specify multiple rules as a single kubernetes CiliumNetworkPolicy. This would make it easier for an automated process/script to replace an existing policy without worrying about which rules already exist. It might look something like this:

```
- apiVersion: cilium.io/v1
  kind: CiliumNetworkPolicy
  description: Multiple rules
  metadata:
    name: my-policy
  spec:
    - endpointSelector:
        matchLabels:
          env: prod
          app: db
      ingress:
        - fromEndpoints:
            - matchLabels:
                env: prod
                app: web
          toPorts:
            - ports:
                - port: 80
                  protocol: TCP
              rules:
                http:
                  - method: GET
                    path: /private
    - endpointSelector:
        matchLabels:
          env: dev
          app: db
      ingress:
        - fromEndpoints:
            - matchLabels:
                env: dev
                app: web
          toPorts:
            - ports:
                - port: 80
                  protocol: TCP
              rules:
                http:
                  - method: GET
                    path: /private
```
