### ISSUE TITLE
Cilium Google GKE start up "Unable to delete Cilium iptables chain"

### ISSUE THREAD

**Issue by AlexsJones** [cilium/cilium#9071]
**what?** 

Cilium inoperable whilst following GKE guide.

```
level=warning msg="Unable to delete Cilium iptables chain" error="exit status 1" obj="[-w 5 -t filter -X CILIUM_TRANSIENT_FORWARD]" subsys=iptables
level=error msg="Command execution failed" cmd="[iptables -w 5 -t mangle -A CILIUM_PRE_mangle -m socket --transparent --nowildcard -m comment --comment cilium: mark transparent proxy traffic to be routed locally -j MARK --set-mark 0x00000200]" error="exit status 1" subsys=iptables
```

**How?**

`https://docs.cilium.io/en/stable/gettingstarted/k8s-install-gke/`

Following the above guide getting to this stage

```
➜  kubernetes kubectl -n kube-system get pods --watch                  
NAME                                                 READY   STATUS              RESTARTS   AGE
event-exporter-v0.2.4-5f7d5d7dd4-phm8h               2/2     Running             0          7m23s
fluentd-gcp-scaler-7b895cbc89-22p94                  1/1     Running             0          7m23s
fluentd-gcp-v3.2.0-8c6f6                             2/2     Running             0          7m48s
fluentd-gcp-v3.2.0-cgztp                             2/2     Running             0          7m29s
heapster-v1.6.1-7ff59bfd5d-jv29t                     3/3     Running             2          7m23s
kube-dns-autoscaler-76fcd5f658-tgc62                 1/1     Running             0          7m23s
kube-dns-b46cc9485-7n9sn                             0/4     ContainerCreating   0          7m22s
kube-dns-b46cc9485-m84s6                             0/4     ContainerCreating   0          6m37s
kube-proxy-gke-cluster1-default-pool-03c94062-tn6k   1/1     Running             0          8m29s
kube-proxy-gke-cluster1-default-pool-03c94062-w1xx   1/1     Running             0          8m28s
l7-default-backend-6f8697844f-hnsph                  0/1     CrashLoopBackOff    5          7m22s
metrics-server-v0.3.1-5b4d6d8d98-mqlsz               1/2     CrashLoopBackOff    5          7m22s
prometheus-to-sd-ss4wj                               1/1     Running             0          8m28s
prometheus-to-sd-v4hbp                               1/1     Running             0          8m29s
tiller-deploy-7f598f888c-q8q9z                       0/1     CrashLoopBackOff    6          7m22s
```

When we take a deeper look

```
  Warning  FailedCreatePodSandBox  4m14s                kubelet, gke-cluster1-default-pool-03c94062-w1xx  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "4d82aec7978d924e4ffebfdcab142919afba0f7a222fd132a1470d4f36f4d94a" network for pod "event-exporter-v0.2.4-5f7d5d7dd4-qpc8z": NetworkPlugin cni failed to set up pod "event-exporter-v0.2.4-5f7d5d7dd4-qpc8z_kube-system" network: unable to connect to Cilium daemon: failed to create cilium agent client after 30.000000 seconds timeout: Get http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)cilium%!F(MISSING)cilium.sock/v1/config: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
```

Looks like it's related back to our cilium pods not firing up.

Any suggestions welcome

---

Additional specific details here:

**Get all** 

```
➜  kubernetes kubectl get all -n cilium
NAME                                   READY   STATUS             RESTARTS   AGE
pod/cilium-node-init-pwvtw             1/1     Running            0          10h
pod/cilium-node-init-rwbrs             1/1     Running            0          10h
pod/cilium-operator-5c5fbb4f8f-hxpdw   1/1     Running            0          10h
pod/cilium-rkrh5                       0/1     CrashLoopBackOff   5          5m57s
pod/cilium-x626k                       0/1     CrashLoopBackOff   5          5m58s



NAME                              DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/cilium             2         2         0       2            0           <none>          10h
daemonset.apps/cilium-node-init   2         2         2       2            2           <none>          10h

NAME                              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cilium-operator   1         1         1            1           10h

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/cilium-operator-5c5fbb4f8f   1         1         1       10h


```

**Operator** 

```
Name:                   cilium-operator
Namespace:              cilium
CreationTimestamp:      Wed, 28 Aug 2019 22:04:21 +0100
Labels:                 io.cilium/app=operator
                        name=cilium-operator
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               io.cilium/app=operator,name=cilium-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:           io.cilium/app=operator
                    name=cilium-operator
  Service Account:  cilium-operator
  Containers:
   cilium-operator:
    Image:      docker.io/cilium/operator:v1.6.0
    Port:       <none>
    Host Port:  <none>
    Command:
      cilium-operator
    Args:
      --debug=$(CILIUM_DEBUG)
    Liveness:  http-get http://:9234/healthz delay=60s timeout=3s period=10s #success=1 #failure=3
    Environment:
      CILIUM_K8S_NAMESPACE:          (v1:metadata.namespace)
      K8S_NODE_NAME:                 (v1:spec.nodeName)
      CILIUM_DEBUG:                 <set to the key 'debug' of config map 'cilium-config'>                 Optional: true
      CILIUM_CLUSTER_NAME:          <set to the key 'cluster-name' of config map 'cilium-config'>          Optional: true
      CILIUM_CLUSTER_ID:            <set to the key 'cluster-id' of config map 'cilium-config'>            Optional: true
      CILIUM_IPAM:                  <set to the key 'ipam' of config map 'cilium-config'>                  Optional: true
      CILIUM_DISABLE_ENDPOINT_CRD:  <set to the key 'disable-endpoint-crd' of config map 'cilium-config'>  Optional: true
      CILIUM_KVSTORE:               <set to the key 'kvstore' of config map 'cilium-config'>               Optional: true
      CILIUM_KVSTORE_OPT:           <set to the key 'kvstore-opt' of config map 'cilium-config'>           Optional: true
      AWS_ACCESS_KEY_ID:            <set to the key 'AWS_ACCESS_KEY_ID' in secret 'cilium-aws'>            Optional: true
      AWS_SECRET_ACCESS_KEY:        <set to the key 'AWS_SECRET_ACCESS_KEY' in secret 'cilium-aws'>        Optional: true
      AWS_DEFAULT_REGION:           <set to the key 'AWS_DEFAULT_REGION' in secret 'cilium-aws'>           Optional: true
    Mounts:                         <none>
  Volumes:                          <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   cilium-operator-5c5fbb4f8f (1/1 replicas created)
Events:          <none>
```

**Daemonset**

```
kubectl describe ds/cilium -n cilium
Name:           cilium
Selector:       k8s-app=cilium,kubernetes.io/cluster-service=true
Node-Selector:  <none>
Labels:         k8s-app=cilium
                kubernetes.io/cluster-service=true
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 2
Current Number of Nodes Scheduled: 2
Number of Nodes Scheduled with Up-to-date Pods: 2
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  2 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           k8s-app=cilium
                    kubernetes.io/cluster-service=true
  Annotations:      scheduler.alpha.kubernetes.io/critical-pod: 
                    scheduler.alpha.kubernetes.io/tolerations: [{"key":"dedicated","operator":"Equal","value":"master","effect":"NoSchedule"}]
  Service Account:  cilium
  Init Containers:
   clean-cilium-state:
    Image:      docker.io/cilium/cilium:v1.6.0
    Port:       <none>
    Host Port:  <none>
    Command:
      /init-container.sh
    Environment:
      CILIUM_ALL_STATE:       <set to the key 'clean-cilium-state' of config map 'cilium-config'>      Optional: true
      CILIUM_BPF_STATE:       <set to the key 'clean-cilium-bpf-state' of config map 'cilium-config'>  Optional: true
      CILIUM_WAIT_BPF_MOUNT:  <set to the key 'wait-bpf-mount' of config map 'cilium-config'>          Optional: true
    Mounts:
      /sys/fs/bpf from bpf-maps (rw)
      /var/run/cilium from cilium-run (rw)
  Containers:
   cilium-agent:
    Image:      docker.io/cilium/cilium:v1.6.0
    Port:       <none>
    Host Port:  <none>
    Command:
      cilium-agent
    Args:
      --config-dir=/tmp/cilium/config-map
    Liveness:   exec [cilium status --brief] delay=120s timeout=5s period=30s #success=1 #failure=10
    Readiness:  exec [cilium status --brief] delay=5s timeout=5s period=30s #success=1 #failure=3
    Environment:
      K8S_NODE_NAME:                      (v1:spec.nodeName)
      CILIUM_K8S_NAMESPACE:               (v1:metadata.namespace)
      CILIUM_FLANNEL_MASTER_DEVICE:      <set to the key 'flannel-master-device' of config map 'cilium-config'>      Optional: true
      CILIUM_FLANNEL_UNINSTALL_ON_EXIT:  <set to the key 'flannel-uninstall-on-exit' of config map 'cilium-config'>  Optional: true
      CILIUM_CLUSTERMESH_CONFIG:         /var/lib/cilium/clustermesh/
      CILIUM_CNI_CHAINING_MODE:          <set to the key 'cni-chaining-mode' of config map 'cilium-config'>  Optional: true
      CILIUM_CUSTOM_CNI_CONF:            <set to the key 'custom-cni-conf' of config map 'cilium-config'>    Optional: true
    Mounts:
      /host/etc/cni/net.d from etc-cni-netd (rw)
      /host/opt/cni/bin from cni-path (rw)
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /sys/fs/bpf from bpf-maps (rw)
      /tmp/cilium/config-map from cilium-config-path (ro)
      /var/lib/cilium/clustermesh from clustermesh-secrets (ro)
      /var/run/cilium from cilium-run (rw)
  Volumes:
   cilium-run:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/cilium
    HostPathType:  DirectoryOrCreate
   bpf-maps:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/fs/bpf
    HostPathType:  DirectoryOrCreate
   cni-path:
    Type:          HostPath (bare host directory volume)
    Path:          /home/kubernetes/bin
    HostPathType:  DirectoryOrCreate
   etc-cni-netd:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:  DirectoryOrCreate
   lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
   xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
   clustermesh-secrets:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cilium-clustermesh
    Optional:    true
   cilium-config-path:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      cilium-config
    Optional:  false
Events:
  Type    Reason            Age    From                  Message
  ----    ------            ----   ----                  -------
  Normal  SuccessfulCreate  7m16s  daemonset-controller  Created pod: cilium-x626k
  Normal  SuccessfulCreate  7m15s  daemonset-controller  Created pod: cilium-rkrh5
```

**Cluster**
```
gcloud container clusters describe cluster1 --region=europe-west4-a
addonsConfig:
  kubernetesDashboard:
    disabled: true
  networkPolicyConfig:
    disabled: true
clusterIpv4Cidr: 10.56.0.0/14
createTime: '2019-08-28T20:58:27+00:00'
currentMasterVersion: 1.12.8-gke.10
currentNodeCount: 2
currentNodeVersion: 1.12.8-gke.10
defaultMaxPodsConstraint:
  maxPodsPerNode: '110'
endpoint: 34.90.124.98
initialClusterVersion: 1.12.8-gke.10
instanceGroupUrls:
- https://www.googleapis.com/compute/v1/projects/<REMOVED>/zones/europe-west4-a/instanceGroupManagers/gke-cluster1-default-pool-03c94062-grp
labelFingerprint: a9dc16a7
legacyAbac: {}
location: europe-west4-a
locations:
- europe-west4-a
loggingService: logging.googleapis.com
maintenancePolicy: {}
masterAuth:
  clusterCaCertificate: <REMOVED>
  password: <REMOVED>
  username: <REMOVED>
monitoringService: monitoring.googleapis.com
name: cluster1
network: default
networkConfig:
  network: projects/<REMOVED>/global/networks/default
  subnetwork: projects/<REMOVED>/regions/europe-west4/subnetworks/default
nodeConfig:
  diskSizeGb: 100
  diskType: pd-standard
  imageType: COS
  machineType: n1-standard-1
  metadata:
    disable-legacy-endpoints: 'true'
  oauthScopes:
  - https://www.googleapis.com/auth/devstorage.read_only
  - https://www.googleapis.com/auth/logging.write
  - https://www.googleapis.com/auth/monitoring
  - https://www.googleapis.com/auth/service.management.readonly
  - https://www.googleapis.com/auth/servicecontrol
  - https://www.googleapis.com/auth/trace.append
  serviceAccount: default
nodeIpv4CidrSize: 24
nodePools:
- config:
    diskSizeGb: 100
    diskType: pd-standard
    imageType: COS
    machineType: n1-standard-1
    metadata:
      disable-legacy-endpoints: 'true'
    oauthScopes:
    - https://www.googleapis.com/auth/devstorage.read_only
    - https://www.googleapis.com/auth/logging.write
    - https://www.googleapis.com/auth/monitoring
    - https://www.googleapis.com/auth/service.management.readonly
    - https://www.googleapis.com/auth/servicecontrol
    - https://www.googleapis.com/auth/trace.append
    serviceAccount: default
  initialNodeCount: 2
  instanceGroupUrls:
  - https://www.googleapis.com/compute/v1/projects/<REMOVED>/zones/europe-west4-a/instanceGroupManagers/gke-cluster1-default-pool-03c94062-grp
  management:
    autoRepair: true
  name: default-pool
  podIpv4CidrSize: 24
  selfLink: https://container.googleapis.com/v1/projects/<REMOVED>/zones/europe-west4-a/clusters/cluster1/nodePools/default-pool
  status: RUNNING
  version: 1.12.8-gke.10
selfLink: https://container.googleapis.com/v1/projects/<REMOVED>/zones/europe-west4-a/clusters/cluster1
servicesIpv4Cidr: 10.59.240.0/20
status: RUNNING
subnetwork: default
zone: europe-west4-a
```

_
