### ISSUE TITLE
L3 policy denied for a k8s network ipBlock where ipBlock belongs to podCIDR

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#9209]
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-client-a-via-cidr-egress-rule
  namespace: network-policy-176
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
  - to:
    - ipBlock:
        cidr: 10.17.56.149/32
  podSelector:
    matchLabels:
      pod-name: client-a
  policyTypes:
  - Egress

```
```json
[
  {
    "endpointSelector": {
      "matchLabels": {
        "k8s:io.kubernetes.pod.namespace": "network-policy-176",
        "k8s:pod-name": "client-a"
      }
    },
    "egress": [
      {
        "toEndpoints": [
          {}
        ],
        "toPorts": [
          {
            "ports": [
              {
                "port": "53",
                "protocol": "UDP"
              }
            ]
          }
        ]
      },
      {
        "toCIDRSet": [
          {
            "cidr": "10.17.56.149/32"
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "io.cilium.k8s.policy.derived-from",
        "value": "NetworkPolicy",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.name",
        "value": "allow-client-a-via-cidr-egress-rule",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.namespace",
        "value": "network-policy-176",
        "source": "k8s"
      }
    ]
  }
]
```
```bash
$ sudo cilium bpf policy get -n  4051 
DIRECTION   IDENTITY   PORT/PROTO   PROXY PORT   BYTES   PACKETS   
Ingress     0          ANY          NONE         3408    18        
Ingress     1          ANY          NONE         0       0         
Egress      0          53/UDP       NONE         1932    18        
Egress      16777220   ANY          NONE         0       0
```
```bash
$ sudo cilium identity get 16777220
ID         LABELS
16777220   cidr:10.17.56.149/32
           reserved:world
```
```
xx drop (Policy denied (L3)) flow 0x4fba8a0f to endpoint 0, identity 35312->54332: 10.16.153.25:45403 -> 10.17.56.149:80 tcp SYN
```

k8s policy spec does not say pod CIDR should not be set in this ipBlock

```golang
// IPBlock describes a particular CIDR (Ex. "192.168.1.1/24") that is allowed to the pods
// matched by a NetworkPolicySpec's podSelector. The except entry describes CIDRs that should
// not be included within this rule.
type IPBlock struct {
	// CIDR is a string representing the IP Block
	// Valid examples are "192.168.1.1/24"
	CIDR string `json:"cidr" protobuf:"bytes,1,name=cidr"`
	// Except is a slice of CIDRs that should not be included within an IP Block
	// Valid examples are "192.168.1.1/24"
	// Except values will be rejected if they are outside the CIDR range
	// +optional
	Except []string `json:"except,omitempty" protobuf:"bytes,2,rep,name=except"`
}
// NetworkPolicyPeer describes a peer to allow traffic from. Only certain combinations of
// fields are allowed
type NetworkPolicyPeer struct {
	// This is a label selector which selects Pods. This field follows standard label
	// selector semantics; if present but empty, it selects all pods.
	//
	// If NamespaceSelector is also set, then the NetworkPolicyPeer as a whole selects
	// the Pods matching PodSelector in the Namespaces selected by NamespaceSelector.
	// Otherwise it selects the Pods matching PodSelector in the policy's own Namespace.
	// +optional
	PodSelector *metav1.LabelSelector `json:"podSelector,omitempty" protobuf:"bytes,1,opt,name=podSelector"`

	// Selects Namespaces using cluster-scoped labels. This field follows standard label
	// selector semantics; if present but empty, it selects all namespaces.
	//
	// If PodSelector is also set, then the NetworkPolicyPeer as a whole selects
	// the Pods matching PodSelector in the Namespaces selected by NamespaceSelector.
	// Otherwise it selects all Pods in the Namespaces selected by NamespaceSelector.
	// +optional
	NamespaceSelector *metav1.LabelSelector `json:"namespaceSelector,omitempty" protobuf:"bytes,2,opt,name=namespaceSelector"`

	// IPBlock defines policy on a particular IPBlock. If this field is set then
	// neither of the other fields can be.
	// +optional
	IPBlock *IPBlock `json:"ipBlock,omitempty" protobuf:"bytes,3,rep,name=ipBlock"`
}
```

On a first glance, it looks easy to fix this bug, on policy import we check if the IP exists in the ipcache, if it does we allow based on ipcache's identity. If it does not we create a new CIDR identity. If a pod shows up with that IP, we add it to the list of allowed identities and remove the CIDR identity.

**Comment by ianvernon** [comment]
Nice find!

**Comment by manuelbuil** [comment]
I am seeing a problem which I think points to this issue. Just in case it provides more info:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: httpbin
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.244.1.0/24
  egress:
  - {}
```
```
$> cilium bpf policy get 01465
DIRECTION   LABELS (source:key[=value])   PORT/PROTO   PROXY PORT   BYTES   PACKETS   
Ingress     reserved:host                 ANY          NONE         0       0         
Ingress     cidr:10.244.1.0/24            ANY          NONE         0       0         
            reserved:world                                                                 
Egress      reserved:unknown              ANY          NONE         0       0    
```
```
xx drop (Policy denied) flow 0x0 to endpoint 1465, identity 10604->59535: 10.244.1.140 -> 10.244.1.139 EchoRequest
xx drop (Policy denied) flow 0x0 to endpoint 1465, identity 10604->59535: 10.244.1.140 -> 10.244.1.139 EchoRequest
xx drop (Policy denied) flow 0x0 to endpoint 1465, identity 10604->59535: 10.244.1.140 -> 10.244.1.139 EchoRequest
xx drop (Policy denied) flow 0x0 to endpoint 1465, identity 10604->59535: 10.244.1.140 -> 10.244.1.139 EchoRequest
```
If instead of `ipBlock` I use `namespaceSelector` or `podSelector`, ping works

**Comment by zbialik** [comment]
I'm not sure if this is related, but would this bug cause the below behavior? 

I have a `NetworkPolicy` defined with below spec:
```
spec:
  podSelector: {}  # Selects all pods in the namespace
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
```

When I execute a `Pod` in the same `Namespace`, I can't reach the k8s API (via `curl https://100.64.0.1`). The fact this policy would cause a denial of traffic for any egress at all is strange to me, but seems to be related to the fact I'm trying tor each the API over a podCIDR?
