### ISSUE TITLE
L4 policy with more than 40 ports doesn't work

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#922]
Cilium endpoints go into 'not-ready' state when I apply an L4 policy with more than 40 ports. It would be nice if Cilium can validate the policy before applying it so that endpoints don't go into not-ready state. Here is the policy I'm using:

```
kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: myapp
spec:
  podSelector:
    matchLabels:
      io.kubernetes.pod.namespace: mynamespace
  ingress:
  - from:
    - podSelector:
        matchLabels:
          io.kubernetes.pod.namespace: mynamespace
    ports:
    - protocol: TCP
      port: 1
    - protocol: TCP
      port: 2
    - protocol: TCP
      port: 3
    - protocol: TCP
      port: 4
    - protocol: TCP
      port: 5
    - protocol: TCP
      port: 6
    - protocol: TCP
      port: 7
    - protocol: TCP
      port: 8
    - protocol: TCP
      port: 9
    - protocol: TCP
      port: 10
    - protocol: TCP
      port: 11
    - protocol: TCP
      port: 12
    - protocol: TCP
      port: 13
    - protocol: TCP
      port: 14
    - protocol: TCP
      port: 15
    - protocol: TCP
      port: 16
    - protocol: TCP
      port: 17
    - protocol: TCP
      port: 18
    - protocol: TCP
      port: 19
    - protocol: TCP
      port: 20
    - protocol: TCP
      port: 21
    - protocol: TCP
      port: 22
    - protocol: TCP
      port: 23
    - protocol: TCP
      port: 24
    - protocol: TCP
      port: 25
    - protocol: TCP
      port: 26
    - protocol: TCP
      port: 27
    - protocol: TCP
      port: 28
    - protocol: TCP
      port: 29
    - protocol: TCP
      port: 30
    - protocol: TCP
      port: 31
    - protocol: TCP
      port: 32
    - protocol: TCP
      port: 33
    - protocol: TCP
      port: 34
    - protocol: TCP
      port: 35
    - protocol: TCP
      port: 36
    - protocol: TCP
      port: 37
    - protocol: TCP
      port: 38
    - protocol: TCP
      port: 39
    - protocol: TCP
      port: 40
    - protocol: TCP
      port: 41
```
