### ISSUE TITLE
CiliumNetworkPolicy using toServices->k8sService fails to rediscover new endpoints behind service

### ISSUE THREAD

**Issue by icantfindavaliduser** [cilium/cilium#9525]
## Bug report

We have CNPs that whitelist egress traffic via `toServices - k8sService`. We notice that after we perform a cluster upgrade which changes the endpoints IPs behind the service (pod runs with host network), the policy does not update with the new endpoints ip's behind the serevice and starts dropping traffic.

**General Information**

- Cilium version
```
Client: 1.6.3 e6233255f 2019-10-08T08:41:35-07:00 go version go1.12.10 linux/amd64
Daemon: 1.6.3 e6233255f 2019-10-08T08:41:35-07:00 go version go1.12.10 linux/amd64
```
- Kernel version
```
Linux vmss-agent-worker2-11prodva7-ieoin000001 4.19.68-coreos #1 SMP Wed Sep 4 02:59:18 -00 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use: Kubernetes upstream
```
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Link to relevant artifacts
rendered manifests of upstream helm, with minor customizations. i can provide more specifics if needed.

**Details**

Given the following CNP:

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  annotations: {}
  name: cnp-allow-kube-mgmt-to-apiserver
  namespace: opa
spec:
  egress:
  - toServices:
    - k8sService:
        namespace: default
        serviceName: kubernetes
  endpointSelector:
    matchLabels:
      app: opa
```

Service used by policy:
```
# kubectl get service kubernetes -n default
NAME         TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   192.168.0.1   <none>        443/TCP   175d

# kubectl get endpoints kubernetes -n default
NAME         ENDPOINTS                                                  AGE
kubernetes   10.18.112.140:6443,10.18.112.150:6443,10.18.112.151:6443   175d
```

Node of agent with outdated nodes in policy:

```
# kubectl get pod -n opa -o wide | grep opa-7db4d98f76-9nsz5
opa-7db4d98f76-9nsz5   3/3     Running   0          7d3h   172.16.4.77     vmss-agent-worker2-11prodva7-ieoin000001   <none>           <none>
```

On the node `vmss-agent-worker2-11prodva7-ieoin000001`, the policy has the old IPs behind the `kubernetes` service:

```
{
    "endpointSelector": {
      "matchLabels": {
        "any:app": "opa",
        "k8s:io.kubernetes.pod.namespace": "opa"
      }
    },
    "egress": [
      {
        "toCIDRSet": [
          {
            "cidr": "10.18.112.9/32"
          },
          {
            "cidr": "10.18.112.20/32"
          },
          {
            "cidr": "10.18.112.6/32"
          }
        ],
        "toServices": [
          {
            "k8sService": {
              "serviceName": "kubernetes",
              "namespace": "default"
            }
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "io.cilium.k8s.policy.derived-from",
        "value": "CiliumNetworkPolicy",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.name",
        "value": "cnp-allow-kube-mgmt-to-apiserver",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.namespace",
        "value": "opa",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.uid",
        "value": "a96f756d-6d55-404c-89fc-e92bd51ddb4f",
        "source": "k8s"
      }
    ]
  }
```

The CNP status also reflects this last change time:
```
      vmss-agent-worker2-11prodva7-ieoin000001:
      enforcing: true
      lastUpdated: "2019-10-23T11:27:31.377028179Z"
      localPolicyRevision: 304
      ok: true
```

I'm assuming because the cilium agent on the `vmss-agent-worker2-11prodva7-ieoin000001` has the policy outdated, it drops the traffic to the new IPs behind the service:

```
xx drop (Policy denied (L3)) flow 0x75ac92d9 to endpoint 0, identity 55538->16777371: 172.16.4.77:45836 -> 10.18.112.140:6443 tcp SYN
xx drop (Policy denied (L3)) flow 0xb5747d18 to endpoint 0, identity 55538->16777371: 172.16.4.77:45810 -> 10.18.112.140:6443 tcp SYN
xx drop (Policy denied (L3)) flow 0x21c30899 to endpoint 0, identity 55538->16777371: 172.16.4.77:45808 -> 10.18.112.140:6443 tcp SYN
xx drop (Policy denied (L3)) flow 0x2b116675 to endpoint 0, identity 55538->16777372: 172.16.4.77:45812 -> 10.18.112.150:6443 tcp SYN
xx drop (Policy denied (L3)) flow 0xa24cf734 to endpoint 0, identity 55538->16777373: 172.16.4.77:45814 -> 10.18.112.151:6443 tcp SYN
xx drop (Policy denied (L3)) flow 0x215abc6f to endpoint 0, identity 55538->16777371: 172.16.4.77:45836 -> 10.18.112.140:6443 tcp SYN
xx drop (Policy denied (L3)) flow 0x1b20e121 to endpoint 0, identity 55538->16777373: 172.16.4.77:45814 -> 10.18.112.151:6443 tcp SYN
```

The master nodes (that are behind the kubernetes service) have beeen properly updated, at least according to the status of the CNP's CRD:

```
    vmss-master-11prodva7-nkwuh000000:
      enforcing: true
      lastUpdated: "2019-10-30T11:10:23.202336209Z"
      localPolicyRevision: 399
      ok: true
    vmss-master-11prodva7-nkwuh000001:
      enforcing: true
      lastUpdated: "2019-10-30T11:11:51.441940978Z"
      localPolicyRevision: 298
      ok: true
    vmss-master-11prodva7-nkwuh000002:
      enforcing: true
      lastUpdated: "2019-10-30T11:10:05.863425392Z"
      localPolicyRevision: 510
      ok: true
```
