### ISSUE TITLE
Cilium keeps modified service ports in datapath

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#9576]
Deploy Deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  selector:
    matchLabels:
      id: app1
      zgroup: testapp
  replicas: 2
  template:
    metadata:
      labels:
        id: app1
        zgroup: testapp
    spec:
      containers:
      - name: web
        image: docker.io/cilium/demo-httpd:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: "port-80"
        - containerPort: 81
          name: "port-81"
        readinessProbe:
          httpGet:
            path: /
            port: 80
      nodeSelector:
        "cilium.io/ci-node": k8s1
```
Deploy service
```yaml
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  ports:
  - name: "port-80"
    port: 80
  - name: "port-81"
    port: 80
  selector:
    id: app1
```
Verify contents of service list, it should exist as expected:
```
$ cilium service list
ID   Frontend            Service Type   Backend
...
12   172.20.0.73:81      ClusterIP                                
13   172.20.0.73:80      ClusterIP 
```
Redeploy the same service without one of the ports
```yaml
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  ports:
  - name: "port-81"
    port: 81
  selector:
    id: app1
```
Verify the content of `cilium service list` is still the same. It shouldn't since port `80` is not mapping to anything anymore.
```
$ cilium service list
ID   Frontend            Service Type   Backend
...
12   172.20.0.73:81      ClusterIP                                
13   172.20.0.73:80      ClusterIP 
```

Affected versions: 
- master (def2c9e06e91d330c3dfdfc9384e65c2ad39fccf)
- v1.4.0-v1.4.9
- v1.5.0-v1.5.9
- v1.6.0-v1.6.3
