### ISSUE TITLE
Compatibility issues seen in the kafka-v1.yaml file while trying to test the Getting Started with Istio guide

### ISSUE THREAD

**Issue by soumynathan** [cilium/cilium#9603]
## Bug report

**Documentation Bug**
Compatibility issues seen in the kafka-v1.yaml file while trying to test the Getting Started with Istio guide 

**How to reproduce the issue**

1. Follow the instructions in the Getting Started using Istio guide. 
2. The issue is seen while running this command.
```
kubectl create -f https://raw.githubusercontent.com/cilium/cilium/1.6.3/examples/kubernetes-istio/kafka-v1.yaml
```

**Here is the error seen:**
```
unable to recognize "kafka-v1.yaml": no matches for kind "StatefulSet" in version "apps/v1beta1"

**Comment by swami-dvr** [comment]
This change worked for me
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-v1
spec:
  selector:
    matchLabels:
      app: kafka
```
