### ISSUE TITLE
Round-Robin DNS records

### ISSUE THREAD

**Issue by arnoldpistorius** [cilium/cilium#9631]
## Proposal / RFE

Round Robin DNS returns a list of ips instead of one. When using egress rule for a FQDN which has Round Robin DNS enabled it will not be able to reach the server (traffic is blocked).

Example response of DNS server for a record with Round Robin DNS:
```
Non-authoritative answer:
Name:    nu.nl
Addresses:  13.33.50.45
          13.33.50.15
          13.33.50.56
          13.33.50.24
```

Second time I execute the query there is a difference in order:
```
Non-authoritative answer:
Name:    nu.nl
Addresses:  13.33.50.56
          13.33.50.24
          13.33.50.15
          13.33.50.45

```
Solution would be that all resolved IPs are allowed by the egress rule.

**Comment by raybejjani** [comment]
@arnoldpistorius Could you include an example policy where this doesn't work? The current behaviour should accomplish what you suggest. Note that you do need to include L3 toFQDNs rules to allow the actual connection (https://cilium.readthedocs.io/en/latest/policy/language/#dns-based), and L7 DNS rules to allow the DNS lookups and provide the IPs used by the L3 rules (https://cilium.readthedocs.io/en/latest/policy/language/#obtaining-dns-data-for-use-by-tofqdns).

**Comment by arnoldpistorius** [comment]
@raybejjani 

Thanks for your reply. I had a couple of days off from work, so I was not able to respond faster.

It seems that the site nu.nl was redirecting to www.nu.nl and obviously that was blocked by the policy. I added a wildcard pattern to make it work.

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-nu-nl"
spec:
  endpointSelector:
    matchLabels:
      "app.kubernetes.io/instance": "app"
  egress:
    # Enable DNS lookups
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
          - port: "53"
            protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    - toFQDNs:
        - matchName: nu.nl
        - matchPattern: "*.nu.nl"
```
