### ISSUE TITLE
CiliumNetworkPolicy: Handle empty toPorts

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#965]
@aanm @tgraf I'm trying to create a catch-all policy so that all the requests within a namespace is rejected by default. I tried the policy below, but requests are still getting through.

```
kind: CiliumNetworkPolicy
apiVersion: cilium.io/v1
metadata:
  name: default-deny
  namespace: default
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
    - fromEndpoints:
        - matchLabels: {}
      toPorts: []
```

Additinally, I tried specifying an empty rule for port 0 as a workaround, but the spec below didn't produce any cilium policy:

```
kind: CiliumNetworkPolicy
apiVersion: cilium.io/v1
metadata:
  name: default-deny
  namespace: default
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
    - fromEndpoints:
        - matchLabels: {}
      toPorts:
        - ports:
            - port: '0'
              protocol: TCP
          rules: {}
```
It looks like there is something special about port 0 since the same spec worked when I changed the port to '80'.

**Comment by tgraf** [comment]
> @aanm @tgraf I'm trying to create a catch-all policy so that all the requests within a namespace is rejected by default. I tried the policy below, but requests are still getting through.

A policy to deny all traffic could be as simple as:
```
kind: CiliumNetworkPolicy
apiVersion: cilium.io/v1
metadata:
  name: default-deny
  namespace: default
spec:
  endpointSelector:
    matchLabels: {}
```

The selector will put all pods in the default namespace into default deny mode. This will block on L3 though. Do you absolutely need L4 blocking? i.e. do you need ICMP to pass while everything else is blocked or similar?
