### ISSUE TITLE
Cilium agent fails (timeout) to sync kubernetes cache after restart

### ISSUE THREAD

**Issue by cehoffman** [cilium/cilium#9697]
## Support

I have cilium agent deployed through the 1.7.0-rc1 helm chart, the config is at the end. The first time the agent started on each of the nodes (with workload already there because flannel was providing the vxlan fabric) everything was fine. I rebooted the nodes to switch to complete cilium management of the network. Again everything is fine. When cilium restarts though on a node, it never becomes ready. It stops at `level=info msg="Waiting until all pre-existing resources related to policy have been received" subsys=k8s-watcher`. It eventually times out waiting for this condition, exits and then is restarted.

I'm now trying this on the best of hardware, but the default 3 minutes should have been plenty of time to sync and it does work perfectly on a fresh reboot of the node. To explore the timeout more I pulled the code and extended the timeout to 10 minutes from the hardcoded 3 and made corresponding changes to the liveness probe in the daemonset to let it persist long enough for that timeout.

Again, the process never finished syncing. I then enabled debug to see if any of the individual resource type cache finished sync log lines occurred. None appears, it seems the first informer for network policies never completes which is should be taxing. There are only 2 networkpolicies in this cluster. The full logs from a container with debug on in this case is [here](https://gist.github.com/ed68eaa7146e79f317aaa7669ed72536).

Since the process connects to the apiserver earlier, I don't think it is a reachability issue although it definitely feels like it. I do have the non cluster network host and port of the apiserver set in the daemonset for the agent. It is not trying to use the internal cluster service address.

For a bit of context, this cluster is very small and has nearly no work occurring in it but it has the exact same configuration as our much larger cluster installs. I'm using it as a testing ground for new infrastructure services and components. Thus I know other informer based caches do work after restart, for example cert-manager and controller-manager itself.

```yaml
  auto-direct-node-routes: "false"
  bpf-ct-global-any-max: "262144"
  bpf-ct-global-tcp-max: "524288"
  cluster-name: home
  cni-chaining-mode: portmap
  container-runtime: none
  debug: "false"
  enable-host-reachable-services: "true"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-node-port: "true"
  host-reachable-services-protos: udp tcp
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  k8s-require-ipv4-pod-cidr: "true"
  masquerade: "true"
  monitor-aggregation: medium
  preallocate-bpf-maps: "false"
  sidecar-istio-proxy-image: cilium/istio_proxy
  sockops-enable: "false"
  tofqdns-enable-poller: "false"
  tunnel: vxlan
  wait-bpf-mount: "true"
```

Edit:

Updated gist to one with timestamps for each line
