### ISSUE TITLE
DNS proxy denies traffic with "L3 Denied" on AKS with CNI chaining

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9794]
Community report from Slack:

Environment: AKS with CNI chaining
Cilium: v1.6.5

### Summary

When applying an L4 policy, the traffic is allowed. However when adding an L7 allow-all policy, the traffic is then denied with `Policy denied (L3)`.

### More detail

Policy applied in default namespace:

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "enable-dns-egress"
spec:
  endpointSelector:
    matchLabels: {}
  egress:
  - toEndpoints:
    - matchLabels:
       "k8s:io.kubernetes.pod.namespace": kube-system
       "k8s:k8s-app": kube-dns
    toPorts:
      - ports:
         - port: '53'
           protocol: ANY
        rules:
          dns:
            - matchPattern: "*"
```

> After applying policy dns resolution doesn't work and with cilium monitor I can see dropped packages.

```
xx drop (Policy denied (L3)) flow 0x8e9cdc7a to endpoint 0, identity 63754->55258: 172.23.85.46 -> 172.23.85.24 DestinationUnreachable(Port)
xx drop (Policy denied (L3)) flow 0x8e9cdc7a to endpoint 0, identity 63754->55258: 172.23.85.46 -> 172.23.85.24 DestinationUnreachable(Port)
xx drop (Policy denied (L3)) flow 0x8e9cdc7a to endpoint 0, identity 63754->55258: 172.23.85.46 -> 172.23.85.24 DestinationUnreachable(Port)
```

Identity 63754 is my probe pod, 55258 is the core-dns pod.

If I remove L7 rule, then DNS resolution works, but L3 DNS based doesn't:

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "enable-dns-egress"
spec:
  endpointSelector:
    matchLabels: {}
  egress:
  - toEndpoints:
    - matchLabels:
       "k8s:io.kubernetes.pod.namespace": kube-system
       "k8s:k8s-app": kube-dns
    toPorts:
      - ports:
         - port: '53'
           protocol: ANY
```

**Comment by joestringer** [comment]
Sysdump from user: [cilium-sysdump-20191220-144343.zip](https://github.com/cilium/cilium/files/3989546/cilium-sysdump-20191220-144343.zip)

**Comment by ombre9** [comment]
I've tested with previous version of Cilium v.16.4 and this feature seems to be working.
Sysdump: [cilium-sysdump-20191230-111006.zip](https://github.com/cilium/cilium/files/4009637/cilium-sysdump-20191230-111006.zip)

**Comment by fabianallendorf** [comment]
I can confirm this issue. No problems with version 1.6.4 (although other problems #9429). Upgrading to 1.6.5 led to this unfortunately.

**Comment by raybejjani** [comment]
Hi folks, sorry for letting this sit for so long.
Unless there are other policies, you are missing a L3 toFQDN rule that wires up DNS lookups into the L3 datapath (the requests handled by the L7 DNS rule). More information at https://cilium.readthedocs.io/en/latest/policy/language/#example
Something like:
```
    - toFQDNs:
        - matchName: "my-remote-service.com"
```
needs to show up in a policy that applies to the endpoints you want to allow to connect to my-remote-service.com

I'm not sure why the upgrade caused this to change, though. This backport (https://cilium.readthedocs.io/en/latest/policy/language/#example) would have explained it but it was already in 1.6.4 looking at the commit history

**Comment by ombre9** [comment]
Unfortunately L3 toFQDN rule is missing from the bug descriptions and usually we put L3 toFQDN rules in other policies.
If you look at the sysdump you can see that the L3 toFQDN rule is there as well.
```
spec:
    egress:
    - toEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: kube-system
          k8s:k8s-app: kube-dns
      toPorts:
      - ports:
        - port: "53"
          protocol: UDP
        rules:
          dns:
          - matchPattern: '*'
    - toFQDNs:
      - matchName: www.google.com
    endpointSelector:
      matchLabels: {}
```

**Comment by tgraf** [comment]
I've tried to reproduce this by applying the following policy:
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "enable-dns-egress"
spec:
  endpointSelector:
    matchLabels: {}
  egress:
  - toEndpoints:
    - matchLabels:
       "k8s:io.kubernetes.pod.namespace": kube-system
       "k8s:k8s-app": kube-dns
    toPorts:
      - ports:
         - port: '53'
           protocol: ANY
        rules:
          dns:
            - matchPattern: "*"
```

It correctly allowed to perform the DNS lookup but denied the attempt to open a connection to the returned destination as expected.

After then extending the policy with:

```
    - toFQDNs:
      - matchName: www.google.com
```

It became possible to reach `www.google.com` but not `www.cilium.io`.
