### ISSUE TITLE
Enabling TLS-visibility for FQDN rule breaks other FQDN rules.

### ISSUE THREAD

**Issue by genbit** [cilium/cilium#9996]
**Summary:**

Specifying TLS-termination for one FQND rule breaks all other FQDN rules on the same Port.

**More detailes:**

Following @danwent 's getting started guide (https://github.com/cilium/cilium/pull/9808) to enable TLS visibility, I deployed and enabled TLS-visibility successfully for swap demo app:

1. Applied L7 policy with TLS termination:

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "L7 policy with TLS"
metadata:
  name: "l7-visibility-tls"
spec:
  endpointSelector:
    matchLabels:
      org: empire
      class: mediabot
  egress:
  - toFQDNs:
    - matchName: "swapi.co"
    toPorts:
    - ports:
      - port: "443"
        protocol: "TCP"
      terminatingTLS:
        secret:
          namespace: "kube-system"
          name: "swapi-tls-data"
      originatingTLS:
        trustedCA: "ca-certificates.crt"
        secret:
          namespace: "kube-system"
          name: "tls-orig-data"
      rules:
        http:
        - {}
  - toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
          - matchPattern: "*"
```

2. Make HTTPS request to swapi.co, as per getting started guide:
```
kubectl exec -it mediabot -- curl -sL https://swapi.co/api/planets/1/
```

3. Using hubble I was able to observe HTTPS request with L7 information:
```
Jan 30 06:14:41.673 [...]: default/mediabot:46760 -> 104.31.76.248:443(https) http-request FORWARDED (HTTP/1.1 GET https://swapi.co/api/planets/1/)
```
4. Make request to https://api.twitter.com

```
kubectl exec -it mediabot -- curl -v -sL https://api.twitter.com
```
Using hubble I observe Dropped flow as expected

```
Jan 30 06:16:10.477 [...]: default/mediabot:41318 -> 104.244.42.2:443(https) Policy denied (L3) DROPPED (TCP Flags: SYN)
```

5. Modify mentioned policy to add whitelist api.twitter.com:

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "L7 policy with TLS"
metadata:
  name: "l7-visibility-tls"
spec:
  endpointSelector:
    matchLabels:
      org: empire
      class: mediabot
  egress:
  - toFQDNs:
    - matchName: "api.twitter.com"
    toPorts:
    - ports:
      - port: "443"
        protocol: "TCP"
  - toFQDNs:
    - matchName: "swapi.co"
    toPorts:
    - ports:
      - port: "443"
        protocol: "TCP"
      terminatingTLS:
        secret:
          namespace: "kube-system"
          name: "swapi-tls-data"
      originatingTLS:
        trustedCA: "ca-certificates.crt"
        secret:
          namespace: "kube-system"
          name: "tls-orig-data"
      rules:
        http:
        - {}
  - toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
          - matchPattern: "*"
```

**6. Repeat step 4 and make https request to api.twitter.com**

```
➜  cilium git:(master) kubectl exec -it mediabot -- curl -v -sL https://api.twitter.com
* Rebuilt URL to: https://api.twitter.com/
*   Trying 104.244.42.2...
* TCP_NODELAY set
* Connected to api.twitter.com (104.244.42.2) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to api.twitter.com:443 
* Curl_http_done: called premature == 1
* Closing connection 0
command terminated with exit code 35

```

expected the request to be successful, instead TLS handshake fails.

7. Changing port from 443 to 8443 for swapi fqdn rule, allows api.twitter.com rule to work properly.
